### ISSUE TITLE
Copy Menu item appears disabled

### ISSUE THREAD

**Issue by srgloureiro** [Komodo/KomodoEdit#100]
I can't tell the exact context, it is a new file not yet saved. I do "Select All" and when I try to copy the "Copy" menu item appears disabled.

**Comment by Defman21** [comment]
Cannot reproduce to that. What's your OS and Komodo verison? (`Help - About Komodo`)

**Comment by srgloureiro** [comment]
Komodo Edit, version 9.0.0, build 15707, platform win32-x86.
Built on Thu Mar 19 07:01:30 2015.

**Comment by srgloureiro** [comment]
Komodo Edit, version 9.0.0, build 15707, platform win32-x86.
Built on Thu Mar 19 07:01:30 2015.

**Comment by Naatan** [comment]
I'm unable to reproduce this also. Can you reproduce the issue reliably?

**Comment by srgloureiro** [comment]
No. It must be an intermittent issue.

**Comment by Naatan** [comment]
Hmm ok, will keep an eye out - please let us know if you figure out steps to reproduce. Closing this until we have more info as I can't do anything with the current data.
