### ISSUE TITLE
Template Toolkit filetype assumes HTML

### ISSUE THREAD

**Issue by cavac** [Komodo/KomodoEdit#1002]
I'm using Template Toolkit a lot in my project. The filetype association "Template Toolkit" seems to assume that it is basically an HTML5 file. But in my case, i'm also generating XML-files with TT, as well as dynamic CSS and Javascript (like generating some unrolled functions dynamically based on certain workloads and browsers).

It would be very helpful if we had the ability to mix&match, so to speak, e.g. have the option to allow Template Toolkit tags in all kinds of files.

![komodo_template_toolkit_error](https://cloud.githubusercontent.com/assets/784308/12297393/3c543c70-ba0d-11e5-9189-106ae50afbf5.png)

**Comment by Naatan** [comment]
How would that work? HTML isnt CSS, nor is it JavaScript. If you were to associate it with all 3 then how would Komodo be able to show you the right syntax colors?

**Comment by cavac** [comment]
No, what i meant is that i have (for example) a binding for .ttxml (XML files with Template Toolkit), another like .tthtml (HTML with TT). Something like that.

**Comment by mitchell-as** [comment]
We'll have to look into the feasibility of this and get back to you. I have an idea in principle how this could work, but I'd have to explore it more in depth. Thanks for the suggestion!

**Comment by mitchell-as** [comment]
I've looked into this and our TemplateToolkit language support is written under the assumption that HTML is the markup language. There's no way of being able to "mix and match" short of creating new "sub-languages" where CSS, or Javascript, or whatever, is the "markup" language. You may be able to do this via Komodo's language extension tool, but we won't be working on this ourselves. I'm going to close the ticket, but thanks for your suggestion!
