### ISSUE TITLE
When open Find dialog set focus to Find what field

### ISSUE THREAD

**Issue by e-shulitsky** [Komodo/KomodoEdit#101]
It would be nice to bring these features back from komodo 8.5:
* When open Find dialog set focus to "Find what" field
* When hit Enter in "Find what" edit, start search immediately

**Comment by Naatan** [comment]
This should already work the way you described (it does for me).

What platform (OS) are you on and are you using Edit or IDE?

**Comment by e-shulitsky** [comment]
Hello Naatan,

I'm on Fedora 21 and I have latest Komodo edit

**Comment by Naatan** [comment]
Reproduced on Komodo Edit - linux.

Thanks @e-shulitsky.

**Comment by cgchoffman** [comment]
Fixed with 32ed693246ad

**Comment by cgchoffman** [comment]
@e-shulitsky this will be available in the nightly builds after lunchtime pacific time on April 7 2015 http://downloads.activestate.com/Komodo/nightly/komodoedit/

**Comment by e-shulitsky** [comment]
@cgchoffman thank you for fixing this issue! I have just updated and it works fine.
