### ISSUE TITLE
Komodo IDE ignores "Allow file contents to override Tab and Indentation settings"

### ISSUE THREAD

**Issue by vkost** [Komodo/KomodoEdit#1012]
Hi guys
I recently started using Komodo IDE, and noticed that it overrides my settings for tabs and indentation. Reading through the docs I found the option "Allow file contents to override Tab and Indentation settings", and I have turned it off both in global settings and in Project settings, and I'm sure there are no individual overrides on any files. Yet it still overrides my defaults (tab = 4 spaces) when it detects different indentation in the file. Also, it seems to me that if it detects ANY lines starting with a tab it will default to inserting tabs at the beginning of the lines I insert.

What I did to remedy this is to replace all tabs with 4 spaces using find/replace, and also I fixed several starting lines manually to make indentation as I want, and after that it started editing the file as expected. But I had to physically remove tabs from the file in order to avoid them being inserted.

I'd like to know is there any solution to this, since I work on a project developed by many before me and the files are pretty messed up :)

Thanks,
Vic

**Comment by vkost** [comment]
Just to note, this is not a copy of the issue #995, though it seems related.

**Comment by cgchoffman** [comment]
> Just to note, this is not a copy of the issue #995, though it seems related.

This sounds identical to #995.  Why do you think it's not?

**Comment by vkost** [comment]
I said it might be related, Carey. However, in issue #995 the user is
complaining about IDE inserting *double* tabs. My Komodo inserts tabs while
I expect it to insert SPACES, since that's how it's set up. Only after I
replace all tabs with spaces in the file and reload it, Komodo starts
behaving as I expect.

There's a chance I don't understand something in that other thread, so if
you think I'm wrong then keep this closed.

Cheers,
Vic

**Comment by cgchoffman** [comment]
In his use case, yes, it's inserting double tabs.  The issue though is that Komodo is picking up the file contents when it shouldn't.  So Komodo will do whatever it finds in the file, which is wrong and is what it sounds like you're reporting.

**Comment by vkost** [comment]
True
Thanks
