### ISSUE TITLE
html dual tag editing should disable after space

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1019]
- Highlight the text in a tag to edit
  eg. select div in the first tag below so the opening and closing tag text is selected for editing
```
<div></div> 
```
- change text to some other string then press space

Expect: Select to go away and return to single cursor

Actual: You still have two cursors.  Komodo will suggest tag attributes now and you'll get attributes in the opening and closing tags

**Comment by mitchell-as** [comment]
This ugly enhancement (code-wise!) is too risky for a bugfix release. Re-targetting for 10.0.
