### ISSUE TITLE
 Having to execute the Run command twice

### ISSUE THREAD

**Issue by Skyblues** [Komodo/KomodoEdit#102]
I am having an issue with the Komodo 9 Run command. I have to 'hit' the Run command twice every time I want to run a script.

I wrote this simple script to test this.
x = 10
y = 5
puts x + y

When I hit Run, I get the output in the Debug Output screen. The second time I hit Run, the black square in the Debug Output window becomes dark black but there in no output. When I hit Run the second time, I get the output again (and the black square in the Debug Output is greyed)

This happens whether I use the Start icon (>), F5 or Debug/Go -> Continue from the menu.

Is there a new setting I'm not seeing that I need to change?

Any suggestions on how I can fix this? I don't want to have to execute the Run command twice every time I want to run my scripts.

Thank you,
Jim

**Comment by Naatan** [comment]
Reassigning to Todd, been digging through this but it's never ending, problem seems to be that a "listener" doesn't end itself until another job is started.

Seems to be related to a bunch of fixes Todd did in 2014 (see https://github.com/Komodo/KomodoIDE/commits/master/src/chrome/komodo/content/debugger/debugger.js).

**Comment by Skyblues** [comment]
If you come up with a patch for this issue, let me know. I'd be happy to test it on my end.

Jim

**Comment by toddw-as** [comment]
Seems the debugger listener socket is shutting itself down (so the next time it tries to start debugging - there is no socket listening and it errors out).

**Comment by toddw-as** [comment]
Should be fixed with this change (private repo):
  https://github.com/Komodo/KomodoIDE/commit/775b938 (master)
  https://github.com/Komodo/KomodoIDE/commit/aef7228 (9.0.1 branch)

**Comment by Skyblues** [comment]
Is there a way we can get a build with the fix in it? I'd really like to start using my Komodo 9.

Jim

**Comment by Naatan** [comment]
@cgchoffman just pushed the latest nightly, you can grab it here - http://downloads.activestate.com/Komodo/nightly/komodoide/latest/

**Comment by Skyblues** [comment]
Awesome, it works great!

Thanks, Jim
