### ISSUE TITLE
Komodo wont load certain perl files

### ISSUE THREAD

**Issue by flytimothy** [Komodo/KomodoEdit#1021]
Ever since upgrading to 9.x.x Komodo wont open certain perl files at all.  I can create new perl scripts but it is hit or miss if Komodo will load an existing file.  This has me using notepad instead.  Is this due to the intellisense or ?

**Comment by cgchoffman** [comment]
Please use **Help > Troubleshooting > Reset file prefs**.  That should fix this issue.

**Comment by flytimothy** [comment]
Thank you this appears to have fixed it!
