### ISSUE TITLE
Formatters for indentation not working

### ISSUE THREAD

**Issue by tribis** [Komodo/KomodoEdit#1022]
Hi,
When I try to reindent a document or a selection with 
Format>Document>Using>Reindent or
Format>Selection>Using>Reindent
I get the following error, and no reindentation happens.

Exception... "Component returned failure code: 0x80004005
(NS_ERROR_FAILURE) [kolFormatter.format]" nsresult: "0x80004005
(NS_ERROR_FAILURE)" location: "JS frame :: chrome://komodo/content/formatters/formatting.js ::
_formatViewWithFormatterAndContext :: line 132"

in 
Komodo IDE, version 9.3.2, build 88191, platform win32-x86. Built on Thu Dec 10 11:38:17 2015.

**Comment by mitchell-as** [comment]
Would you please be more specific as to what text you're trying to format, what language it is, and which exact reindent menu option you selected? That will help us troubleshoot the issue. Thanks!

**Comment by tribis** [comment]
The language of the file is JavaScript however I just tested with a random PHP file and the result is the same.

I right-click on the open file's text and select from the context menu:

Format>Document using>Reindent or
Format>Selection using>Reindent

I see the hierarchy of the menu is a bit different than written previously.
Thank you

**Comment by mitchell-as** [comment]
I've tried a PHP file and this is the context menu I'm getting. It doesn't match the option you say you're trying. Perhaps you are running a version of Komodo different than 9.3?

![reindent](https://cloud.githubusercontent.com/assets/12902397/12515983/0efd2898-c0f9-11e5-92ff-d74052c7e9c6.png)

**Comment by tribis** [comment]
The only difference, apart from the colours (are you on Ubuntu maybe? I'm on Windows), is that your menu says "Python reindent" whilst mine says only "Reindent".
The version of Komodo I reported is copied and pasted from Help> About Komodo> copy build info



![komodo](https://cloud.githubusercontent.com/assets/54670/12516178/7310b56a-c12c-11e5-99de-b6d9d3594a93.png)

**Comment by mitchell-as** [comment]
Okay, thanks for the extra info. @cgchoffman can you reproduce this error on Windows? I cannot reproduce it on Linux.

**Comment by cgchoffman** [comment]
That should be **Python Reindent** which leads me to believe that you've modified the formatters in your preferences.  Edit > Preferences > Formatters.

**Comment by tribis** [comment]
No, I wouldn't know what to change. I have never used reindent before. I needed it because I had trouble with one file that suddenly changed from 4 spaces to 8 spaces tabs. I left a comment about it on another issue, same day.

Here are my settings for formatters. Maybe you can see if something is really changed.

![komodo formatter](https://cloud.githubusercontent.com/assets/54670/12567030/37d64756-c3bd-11e5-943e-c98e96266628.PNG)

**Comment by cgchoffman** [comment]
Looks to be the same as mine.  Thanks for checking. Could you try **Help > Troubleshooting > Restart in Safe-Mode** and see if you can reproduce?

**Comment by tribis** [comment]
Done that and there are 2 things I can tell:

The menu item is named "Python Reindent" as in your case
The failure happens the same way as in my ordinary version.

![komodo-failure-python reindent](https://cloud.githubusercontent.com/assets/54670/12577130/b9b9e15a-c418-11e5-88ac-b8c06f53b3ea.png)

**Comment by cgchoffman** [comment]
So far all I can find is perhaps the format service isn't being instantiated properly: https://github.com/Komodo/KomodoIDE/blob/master/src/chrome/komodo/content/formatters/formatters.js#L655

@tribis have you tried reinstalling 9.3.2?

**Comment by tribis** [comment]
The link leads to a "page not found". However I'll try and reinstall 9.3.2.

**Comment by tribis** [comment]
I've reinstalled 9.3.2 but unfortunately I get the exact same error message. Maybe it's useful to say that I'm on Windows 10. 
I'm still not able to view any page at the provided link reg. instantiation.

**Comment by Defman21** [comment]
https://github.com/Komodo/KomodoEdit/blob/master/src/chrome/komodo/content/formatters/formatters.js#L655

**Comment by Defman21** [comment]
Ahh wait Formatters are not available in Edit, my link won't work

**Comment by Naatan** [comment]
Seems to me you are running Python reindent on JavaScript. Have you tried running it on actual Python code?

**Comment by tribis** [comment]
Doh! This explains everything. As I mentioned I used that for the first time due to an immediate need to reindent a file that changed suddenly the indentation. My IDE shows:
Format>Document using>Reindent
so I thought that this is exactly what I need. I understand now that it is only for python code. 
Later in the thread, when you guys were speaking about Python reindent I came to think that it was written in python, not that it was only for python code. I don't code in python.
I guess this closes this issue. My apologies for the misunderstanding.
I will use JS beautify.

**Comment by cgchoffman** [comment]
> The link leads to a "page not found". However I'll try and reinstall 9.3.2.

That was a reference to the Komodo IDE source which is not public.  It wasn't an installer link.  I assumed you knew how to get those bits.  Sorry for the confusion.

> Seems to me you are running Python reindent on JavaScript. Have you tried running it on actual Python code?

It works for me on Javascript.  I don't think that's the issue but if @tribis is happy with JSbeautify then I think we're fine.

**Comment by Naatan** [comment]
Python Reindent will run on JS, it just wont run "well". As is evident by this thread :) Its intended for Python code.

**Comment by tribis** [comment]
funny how easy it is to misunderstand each other. I refer to the comment by @cgchoffman that is citing my: 
>The link leads to a "page not found". However I'll try and reinstall 9.3.2.
I never meant it was an installer.
I was answering to two separate sentences, with 2 separate sentences. 
You gave me a link to a resource, so I assumed there was something interesting for me there. I thought it was useful for you to know that I could not use it. However I intended to follow the advice contained in your second sentence.

**Comment by cgchoffman** [comment]
> I was answering to two separate sentences, with 2 separate sentences.

Understood.
