### ISSUE TITLE
Highlighting text, right clicking, and choose find or replace doesn't input highlighted words.

### ISSUE THREAD

**Issue by josephtheberge** [Komodo/KomodoEdit#1025]
As the title says, highlighting things and choosing to "Find..." or "Replace..." doesn't input highlighted words. This is also broken when going under the Edit tab and choosing the same options.

**Comment by Naatan** [comment]
What version of Komodo?

**Comment by josephtheberge** [comment]
Komodo Edit, version 9.3.2, build 16460, platform win32-x86. Built on Thu Dec 10 22:21:38 2015.

**Comment by mitchell-as** [comment]
That's odd. I am not able to reproduce this. Does it work when you restart in safe-mode? (Help > Troubleshooting > Restart in Safe-Mode).

**Comment by cgchoffman** [comment]
I can't repro on Windows.  9.3.2 build 88191
