### ISSUE TITLE
Can't exit, save failed

### ISSUE THREAD

**Issue by bs5975** [Komodo/KomodoEdit#1029]
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIDocument.isEncodable]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: vieweditor :: _validateEncoding :: line 1324"  data: no]

Exception: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIDocument.isEncodable]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: vieweditor :: _validateEncoding :: line 1324"  data: no]

Traceback:
_validateEncoding@vieweditor:1324:16
save@vieweditor:1421:21
viewManager.prototype.offerToSave@chrome://komodo/content/views.js:1622:16
viewManager.prototype.canClose@chrome://komodo/content/views.js:127:25
this.runCanCloseHandlers@chrome://komodo/content/komodo.js:229:22
this.observe@chrome://komodo/content/komodo.js:582:13
canQuitApplication@chrome://global/content/globalOverlay.js:45:4
goQuitApplication@chrome://global/content/globalOverlay.js:57:7
this.quitApplication@chrome://komodo/content/komodo.js:56:8
this._onClose@chrome://komodo/content/komodo.js:158:8

Komodo IDE, version 9.3.2, build 88191.
Built on Thu Dec 10 11:38:17 2015.

**Comment by mitchell-as** [comment]
Thanks for the report. From the traceback you posted I cannot determine exactly what went wrong, but my guess is that you inserted invalid characters into your buffer. What encoding was the document in? Something other than UTF-8? If so, it's likely there's an invalid character or byte sequence in there.

**Comment by bs5975** [comment]
No, it was UTF-8. I get this type of error relatively frequently and it’s my impression that it is much more common with a large file. But also sporadic. Is there a different encoding like UTF-16 that I should be considering?

Brian

Center for Computational and Integrative Biology
CPZN 7-7228 Simches Research Center
Massachusetts General Hospital
185 Cambridge Street
Boston MA 02114
617 726 5975

**Comment by cgchoffman** [comment]
@bs5975 Please open the ticket in your browser and reply.  You've included your phone number and work address in your response and (less importantly) Mitchell's previous response.

**Comment by bs5975** [comment]
I agree that this was undesirable. Why does the message footer say I should reply to the email directly?

**Comment by cgchoffman** [comment]
Because Github said so.  I'm just giving you a heads up.  If you reply to the email it injects your email into a comment, if you open the ticket in the browser then you reply there.  The footer gives you the option.

**Comment by mitchell-as** [comment]
No, UTF-8 is the encoding I'd recommend you use all the time. In your case, I would guess you are inserting non-UTF8 characters in your document. Do you cut and paste from websites, e-mail, other sources outside Komodo? That would definitely be a vector for inserting invalid characters by mistake.
