### ISSUE TITLE
What about using Pale Moon code instead Firefox?

### ISSUE THREAD

**Issue by timofonic** [Komodo/KomodoEdit#1031]
Hello.

What about Pale Moon code instead Firefox?

Pale Moon uses XUL Runner.

It's more optimized and lightweight, too.

Kind regards.

**Comment by Defman21** [comment]
Komodo uses Mozilla core, not a browser (like Firefox or Pale Moon)

**Comment by mitchell-as** [comment]
Right, Komodo is not a web application masquerading in a Firefox (or Pale Moon) web browser. It's a desktop application built on Firefox's core foundation, Mozilla.
