### ISSUE TITLE
Cannot bind macros to certain Ctrl+Shift shortcuts

### ISSUE THREAD

**Issue by tszynalski** [Komodo/KomodoEdit#1032]
Hi,

In Komodo Edit 9.3.2, you can no longer bind a macro to Ctrl+Shift+C, Ctrl+Shift+V and Ctrl+Shift+S. The New Key Sequence field doesn't register those combinations at all.
This worked a few releases back.

Best wishes and thanks for an awesome editor!

Tomasz

**Comment by Naatan** [comment]
I don't see any reason why those shortcuts should not work. 

 * What happens when you press them? 
 * What platform are you on?
 * What was the last release you used that didn't have this problem? And on what platform was it?

**Comment by tszynalski** [comment]
The platform in both cases was Windows. I don't remember when exactly it stopped working. As I wrote, nothing happens when you try to add the key in the New Key Sequence field in the Properties of a macro.

**Comment by Naatan** [comment]
Are you using any other software that interacts with your keyboard/input?

See if Help > Troubleshooting > Restart in Safe-Mode has any effect.

**Comment by tszynalski** [comment]
Well, guess what. It started working again. I didn't do anything, other than rebooting for Windows update. I'll let you know if it happens again.

**Comment by mitchell-as** [comment]
Okay, thanks for reporting back to us. I'm going to close this for now. Please re-open if it happens again and provide us with the necessary details. Cheers.
