### ISSUE TITLE
Improve Undo of Move Line by Alt+Arrows

### ISSUE THREAD

**Issue by srgloureiro** [Komodo/KomodoEdit#1033]
I think it makes sense the Undo/Redo of Move Line should be treated as a single-block each arrow keypress. ATTENTION: I said each arrow keypress, which does not necessarily mean an Alt Key Leave.

**Comment by mitchell-as** [comment]
Hi, I'm not sure I understand what you are saying. I've created a blank file with the following contents:

    1. foo
    2. bar
    3. baz

On the last line, I hit Alt+Up twice, moving "3. baz" to the top. When I Ctrl+Z (undo), the "3. baz" line is in the middle, and Ctrl+Z again puts it back at the end. This behavior makes sense to me. Are you suggesting something different? Thanks for any clarification.

**Comment by srgloureiro** [comment]
I suggest what what you've described, if I understood it correctly. It makes sense to do it as a unitary block for the whole time the Alt key is pressed, when user:
 - press and stay pressed Alt
 - press arrow
 - press arrow
 - releases Alt

But could also do a smart aggregate
 - press Alt
 - press arrow
 - press Alt
 - press arrow

**Comment by mitchell-as** [comment]
I see, thanks for the clarification and the suggestion. This seems like a lot work for little gain -- we will have to keep track of alt-key-down in addition to normal editing commands like move-line-up/down. I'm going to close this ticket.

**Comment by mitchell-as** [comment]
A different Undo behavior was requested.

**Comment by Naatan** [comment]
So if I pres alt+arrow,arrow,arrow then the undo action is from alt down to alt up rather than for each arrow keypress?

**Comment by srgloureiro** [comment]
I don't know why, but I am not seeing in the GitHub page all the issue's posts that came to my e-mail box!

**Comment by Naatan** [comment]
I removed the ones that we concluded on Slack. They don't add anything of value to this ticket.

**Comment by srgloureiro** [comment]
What is Slack?

**Comment by Naatan** [comment]
Oh sorry, Slack is what we used to chat internally. It's becoming a bit of an industry term.
