### ISSUE TITLE
git commit - Komodo IDE 9 crash

### ISSUE THREAD

**Issue by just-me-** [Komodo/KomodoEdit#1034]
**Do a git commit:**
If I say No or Yes to the question dialog - after selecting my files -  "Show SCC Output Messanges?", Komodo crashes / (endless loading - hangup).

But the commit is done well. I just need to shut down Komodo and restart it...
Then I can push it to the remote branch via Komodo without any problems. 

 The output of the error log:
[pystderr.log.zip](https://github.com/Komodo/KomodoEdit/files/110796/pystderr.log.zip)

**Comment by mitchell-as** [comment]
Thanks for the report!

Relevant snippet from the error:

[2016-01-30 13:54:28,600] [ERROR] CT::tracker.js: Scc error Error 128 running '[u'/usr/bin/git', 'show', u'HEAD:./cookieconsent.css']'
  in '/Applications/MAMP/htdocs/wuza/css':
fatal: Path 'css/cookieconsent.css' exists on disk, but not in 'HEAD'.
Traceback from ERROR in 'CT::tracker.js' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:337:27
    exports.ChangeTracker.prototype.onError@chrome://trackchanges/content/tracker.js:200:5

**Comment by just-me-** [comment]
Found it. 

Problems: 
For mac IDE: cant commit
For linux IDE: opening files takes ages 

Solution / source of bug:
Preferences => Editor - Indentation => deactivate the (in my opinion) cool feature "Enable elastic tabstops"

hope you get it down so I can use the elastic tabs again :-)


<img width="741" alt="pref" src="https://cloud.githubusercontent.com/assets/7271532/12857558/2bb0f976-cc4b-11e5-9925-8177357e5cb9.png">

**Comment by mitchell-as** [comment]
@just-me- So when you disable elastic tab stops, you do not get any crashes? The error message does not appear to involve elastic tab stops at all; that is why I'm asking.

**Comment by just-me-** [comment]
Yes - no crash and no long / endless loading. (Neither on OSX nor Linux.) 
At least not so far... I'll try again on the weekend to test more intensively,

I send you a log if I have activated the option on my Linux => long loadingtime for just opening files. 
[log.zip](https://github.com/Komodo/KomodoEdit/files/121961/log.zip)

**Comment by Naatan** [comment]
Is this consistently reproducible by enabling/disabling elastic tabstops?

**Comment by just-me-** [comment]
Absolutely.

On the Mac and the new log:
I activate the option - make a commit - et voilà; endless loading
[pystderr.log.zip](https://github.com/Komodo/KomodoEdit/files/122245/pystderr.log.zip)

I can create you tomorrow a new one via linux if you need it.

**Comment by mitchell-as** [comment]
Hi, sorry to bother but I'm having trouble reproducing this using a clean repository.

1. I've created a new project and initialize git.
2. I turned on tabs and elastic tabstops.
3. I then created a simple file test.py:

    foo<tab>=<tab>1
    bar<tab>=<tab>2
    foobarbaz<tab>=<tab>3

4. I get the nice alignment elastic tabstops is supposed to give me.
5. I use Komodo to add the test.py file to git and commit the changes.
6. I am prompted to show SCC messages and click "yes".
7. No hangup. I can close test.py and re-open it and it loads immediately.

Sadly the log files you attached do not shed any light on where the problem might be. (Not even elastic tabstops is implicated; I'm just going by your statement that it is to blame for the crashes.)

Do you have any tips or advice on how I can reproduce this?

**Comment by just-me-** [comment]
The commit problem is for me only on the Mac Komodo, not on the Komodo for Linux. On Linux i get the "opening-files-bug" by elastic tabstops. 

Open in a project ten files - all have loads of lines. (In my case ~3k-5k+ .pl/.pm files.) Then close Komodo and open it again. (Option "open last project and files" should be enabled. => more files, more loading time.) Your Komodo should now crash. 

Can I mail you my Komodo setting files?

**Comment by mitchell-as** [comment]
I understand what your settings are, so there's not need for you to send them to me right now. I'll try and find a few really large files, stuff them in a project, and try to reproduce the slowdown/crash. Thanks for the additional information.
