### ISSUE TITLE
Can't update prefs in the main prefs box: "ko.views is undefined"

### ISSUE THREAD

**Issue by ericpromislow** [Komodo/KomodoEdit#1035]
On trunk, commit cc738fac8a3158c90a3d4eb7ba649f49a5718f7e

When I try to update a pref I get this message:
*** Error in logger.error: TypeError: ko.views is undefined
[2016-01-30 14:09:18,550] [ERROR] prefs: Could not save prefs 'trackchanges_enabled' to values 'false': ReferenceError: k is not defined
Traceback from ERROR in 'prefs' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:417:27
    koPrefWindow.prototype._doSavePrefElements@chrome://komodo/content/pref/koPrefWindow.js:956:1
    koPrefWindow.prototype.savesinglepageprefs@chrome://komodo/content/pref/koPrefWindow.js:979:14
    koPrefWindow.prototype.savepageprefs@chrome://komodo/content/pref/koPrefWindow.js:969:18
    koPrefWindow.prototype._onOK@chrome://komodo/content/pref/koPrefWindow.js:293:14
    koPrefWindow.prototype.onApply@chrome://komodo/content/pref/koPrefWindow.js:338:16
    koPrefWindow.prototype.onOK@chrome://komodo/content/pref/koPrefWindow.js:329:16
    doOk@chrome://komodo/content/pref/pref.js:63:10
    oncommand@chrome://komodo/content/pref/pref.xul:1:1

Looks like two problems. First, I don't know where that 'k' is coming from. Second, the logger
does a 'require "ko/views"' and references ko.views, but in the preference box maybe ko.views
doesn't exist?  When I bring up the JS Shell and select the prefs window there's no ko.views.

**Comment by ericpromislow** [comment]
Seeing this in a fresh build of Edit, with another regression:

Pull up a .js.erb file (with my recent PR), bring up file properties/syntax checking.

At first I see these messages:

JavaScript strict warning: , line 0: TypeError: "XPCOMUtils" is read-only
JavaScript error: chrome://komodo/content/pref/koFilteredPrefTree.js, line 688: TypeError: docObject is null

Now click the "Check Code with JSHint" button, and press OK.  Dialog doesn't close,
no error messages in console. Click Apply. Nothing. Press cancel -- no error messages
appear in the launch window (running 'bk run -v'). Looks like prefs are completely broken.

**Comment by Naatan** [comment]
Opened a bug here: https://github.com/Komodo/KomodoEdit/issues/1053
