### ISSUE TITLE
cyrillic symbols disappeared on windows10

### ISSUE THREAD

**Issue by Amphyby** [Komodo/KomodoEdit#1036]
Just switched from Ubuntu 14.04 to Windows 10. 
After I've opened my python file with comments in Russian{cyrillic symbols}, all non-English symbols are shown as crossed rectangles. Changing encodings doesn't lead to anything - it seems to not work at all. From the other editors{tried SciTe and Sublime} all works well. Same pity on both Komodo Edit and IDE.

Can't write comments to my code in my native language:(
Futhermore can't read my own comments on my code, bcz it hides every Russian symbol by crossed rectangle.
Btw if I past Russian text to editor, it displayed wrong but i can copy it from there and past to any other program: browser, notepad etc and it appears as usual Russian text. 

Fix it asap Plz...

**Comment by mitchell-as** [comment]
Hi, does the font you are using (Edit > Preferences > Color Scheme) support Russian characters? Often times the crossed rectangles show when a character glyph cannot be displayed. If it was en encoding issue it's likely you'd get random characters in the extended ASCII set.

**Comment by Amphyby** [comment]
No, nothing changes. I was using Abyss theme on Linux, just now I've tried different themes/icon themes. 0 reaction from Russian input...
BTW it always ASCII. Even when I change encoding and save, it can appear that i have UTF8, but as I just reopen the file it shows ASCII again.

**Comment by mitchell-as** [comment]
Sorry, but your response is not clear. Have you confirmed that the font you are using supports Russian characters? (i.e. using that exact font in another program or editor shows Russian characters.)

**Comment by Amphyby** [comment]
I got ya finally! Ty. Yes, changing font to simple Calibri works!

p.s.:what a tard included this font instead of one was working fine in theme,always? o_O

**Comment by mitchell-as** [comment]
Thanks for your response and I'm glad it works for you.
