### ISSUE TITLE
PHP7: preg_replace_callback_array function not in auto-complete db?

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1049]
In 7.0, there's [a new function called `preg_replace_callback_array` function](https://secure.php.net/manual/ru/migration70.new-features.php#migration70.new-features.anonymous-classes)

I don't see a suggestion in auto-complete popup nor any help popups (which usually describes for what each argument is)

Btw Komodo works pretty damn good with PHP7! I really like it <3

**Comment by mitchell-as** [comment]
I think we need to update our PHP codeintel catalog. Thanks for catching this.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoEdit/commit/7f09f466fec4b6198e2b4699f08ecfa2525cddf3
