### ISSUE TITLE
PHP7: Komodo should show strict_types errors

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1051]
```
<?php

declare(strict_types=1);

function test(string ...$strings): string {
    $return = "";
    foreach ($strings as $string) {
        $return .= " {$string}";
    }
    return $return;
}

var_dump(test("hello", "world", 1));
```

There's an error on line 13, but Komodo don't show anything on that line.
```
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to test() must be of the type string, integer given, called in <File> on line 13 and defined in <File>:5
Stack trace:
#0 <File>(13): test('hello', 'world', 1)
#1 {main}
  thrown in <File> on line 5
```

There's an important thing - [if you don't have `declare(strict_types=1);`, then there are no errors in the example](https://secure.php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration.strict).

**Comment by mitchell-as** [comment]
It appears we'd have to parse the PHP code to determine whether or not `strict_types` is on. This doesn't look like a PHP linter or PHP compiler setting.

**Comment by Naatan** [comment]
@Defman21 does setting `strict_types=1` in the php.ini that Komodo uses resolve your issue?

**Comment by Defman21** [comment]
I'll try :)

**Comment by Defman21** [comment]
```
cat php.ini | grep strict
strict_types = 1
```

Still no errors. If I run it through CLI - it gives me the error:
```
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to test() must be of the type string, integer given, called in <File> on line 13 and defined in <File>:5
Stack trace:
#0 <File>(13): test('hello', 'world', 1)
#1 {main}
  thrown in <File> on line 5
```

Komodo uses the same ini as CLI does.

**Comment by Naatan** [comment]
Are you setting strict_types in your php code also? I'm not certain whether setting it in the ini works, that's what I'm trying to find out.

So try setting it in the ini and in the ini only, then see if running from the CLI works.

**Comment by Defman21** [comment]
>Are you setting strict_types in your php code also?

I was. I've removed it from the code and now I don't get any errors even If I have strict_types in php.ini

**Comment by Naatan** [comment]
Alright, so it appears you cannot set strict_types through the php.ini, that's odd.

**Comment by Defman21** [comment]
Well, can you do that? Seems like there's no way to use declare settings in php.ini.

**Comment by mitchell-as** [comment]
Our PHP linter relies on PHP's own `-l` flag, which does not appear to catch type errors:

    $ php7 -l strict.php
    No syntax errors detected in strict.php
    $ php7 strict.php
    Fatal error: Uncaught TypeError: Argument 3 passed to test() must be of the type string, integer given, called in strict.php on line 13 and defined in strict.php:5
    Stack trace:
    #0 strict.php(13): test('hello', 'world', 1)
    #1 {main}
      thrown in strict.php on line 5

Our linters should absolutely not be running code. PHP7's `-l` flag needs to start doing type checking if possible if we are to show such errors.
