### ISSUE TITLE
Folding code defined by regions

### ISSUE THREAD

**Issue by hirnwunde** [Komodo/KomodoEdit#1052]
Hi folks,

i had read the Issue #715 and want this for JS and/or PHP, too.

Is there a way to add those functionality to other "languages" then CSS?

Best regards

**Comment by mitchell-as** [comment]
No, you'd have to define custom folding for individual languages. We encourage PRs for enhancements like this.

**Comment by hirnwunde** [comment]
I had edited $INSTALLDIR/lib/sdk/udl/phplex.udl - but its looks like I have to recolpile the whole project to add changes like these.
After some investigation I can say that it is beyond my possibilities and knowledge.
Hopefully someone with deeper knowledge of building KomodoEdit will help.

**Comment by Defman21** [comment]
Can you share with me your edits? I'll try to compile Komodo with your changes.

**Comment by hirnwunde** [comment]
This is fully untested and would be my first try if it could work:

    --- C:/Program Files (x86)/ActiveState Komodo Edit 9/lib/sdk/udl/phplex.udl	Tue Oct 27 16:42:32 2015
    +++ C:/Program Files (x86)/ActiveState Komodo Edit 9/lib/sdk/udl/phplex_region.udl	Thu Feb 04 10:36:07 2016
    @@ -590,6 +590,9 @@
     fold "{" SSL_OPERATOR +
     fold "}" SSL_OPERATOR -
     
    +fold "// Region" SSL_OPERATOR +
    +fold "// RegionEnd" SSL_OPERATOR -
    +
    
     fold "{{{" SSL_COMMENT +
     fold "}}}" SSL_COMMENT -

Furthermore I do not even know if that would be the correct file.
I think the correct place is `KomodoEdit/sr/udl/udl/phplex.udl`

With these changes I want to fold this 
```php
<?

// Region

function Foo() {
	if ($a == $b){
		echo 'bar!';
	}
}

// EndRegion

?>
```
to this
```php
<?

[+] // Region [...]

?>
``

**Comment by Defman21** [comment]
Got it. I'll try to compile your changes today.
