### ISSUE TITLE
jshint dialog doesn't close

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1053]
Reference: https://github.com/Komodo/KomodoEdit/issues/1035

> Pull up a .js.erb file (with my recent PR), bring up file properties/syntax checking.
> 
> At first I see these messages:
> 
> JavaScript strict warning: , line 0: TypeError: "XPCOMUtils" is read-only
> JavaScript error: chrome://komodo/content/pref/koFilteredPrefTree.js, line 688: TypeError: docObject is null
> 
> Now click the "Check Code with JSHint" button, and press OK. Dialog doesn't close,
> no error messages in console. Click Apply. Nothing. Press cancel -- no error messages
> appear in the launch window (running 'bk run -v'). Looks like prefs are completely broken.

**Comment by mitchell-as** [comment]
I'm confused. Why am I being assigned this? when #1035 is fixed all of the pref problems should go away.

**Comment by Naatan** [comment]
My bad, had a wrong impression of the issue.
