### ISSUE TITLE
Cannot open some files in Komodo 9.3.2

### ISSUE THREAD

**Issue by cwlongshot** [Komodo/KomodoEdit#1055]
I've been using Komodo 5 and 6 for years. I just upgraded to 9.3.2 and now I can't open some files.  I double click on the left navigation project area - nothing. I used File->Open and selected the file. Won't open. Yet, a file in the same directory opens. All have the same permissions and are the same type of file (perl modules). I'm using Linux Red Hat 6u6 64-bit (2.6.32-504.el6.x86_64). I've tried Komodo 9 on Windows 7 (reading the exact same file from the network) and it doesn't have this issue, but I cannot debug my application on that platform.

This is a showstopper for me. I will have to go back to using Komodo 6 until this is fixed.

**Comment by cgchoffman** [comment]
try *help > Troubleshooting > Reset File Preferences*

**Comment by cwlongshot** [comment]
Yes, that fixed it. Thanks!

**Comment by cgchoffman** [comment]
You're welcome!
