### ISSUE TITLE
LESS syntax checking broken

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1061]
Install latest LESS: `npm install -g less` and point Komodo at it.

Write some obviously invalid CSS (don't even worry about LESS specifics), eg

```
foo { bar; 
```

The syntax check passes, no errors detected.

**Comment by mitchell-as** [comment]
I doubt this is a regression. It looks like LESS decided to change its output format again.

**Comment by Naatan** [comment]
Confirmed, if I downgrade all the way down to LESS 1.2 it works. Seems they changed the output shortly after that, and checking the output for different versions it doesn't seem to have changed much since.

**Comment by Naatan** [comment]
Old format (version 1.2):

```
(node) util.error is deprecated. Use console.error instead.
ParseError: Syntax Error on line 21 in /home/nathan/Projects/komodo-dev/src/chrome/komodo/skin/global/components/customize.less:21:20
20 
21     background-color: @contrast;
22     background-image: url("koicon://ko-svg/chrome/icomoon/skin/move.svg?color=@{escaped-special}");

FAIL: 1
```

New format (version 2.6):

```
ParseError: Unrecognised input in /home/nathan/Projects/komodo-dev/src/chrome/komodo/skin/global/components/customize.less on line 21, column 21:
20 
21     background-color: @contrast;
22     background-image: url("koicon://ko-svg/chrome/icomoon/skin/move.svg?color=@{escaped-special}");

FAIL: 1
```

**Comment by Defman21** [comment]
^ God of `git rebase`.
Anyway I fixed that, now I can see errors with your example Nathan :)

**Comment by babobski** [comment]
The "Use build-in Less Syntax Checker" is not working in komdo 10.
When I use this example, I get no linting errors
```less
foo { bar; 
```
![2016-05-25 08_48_18](https://cloud.githubusercontent.com/assets/3530262/15530556/7a46bde0-2255-11e6-8f51-78150e2bb060.jpg)

**Comment by babobski** [comment]
As work around, if you have node.js configured in komodo, you can point to the [lessc](https://github.com/less/less.js/tree/master/bin) file from the less repo as interpreter.
You will now get linting errors:
![2016-05-25 10_38_01](https://cloud.githubusercontent.com/assets/3530262/15533430/e803df20-2264-11e6-8d55-40ab54e79df0.jpg)

**Comment by mitchell-as** [comment]
There is no built-in Less syntax checker. That option should not exist. You must have lessc installed somewhere and configure Komodo to point to it.

**Comment by Naatan** [comment]
Huh, we do indeed show a "Use built-In Less Syntax Checker".  Bug logged here: https://github.com/Komodo/KomodoEdit/issues/1607
