### ISSUE TITLE
Add all "CSS Legal Color Values" to komodo

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#1062]
Currently komodo only supports rgb and hex, would be nice to have [all](http://www.w3schools.com/cssref/css_colors_legal.asp) color value's in the autocompletion.
```javascript
#
rgb(
rgba(
hsl(
hsla(
```

**Comment by Defman21** [comment]
Someone could even assign me for this issue. I'll do it in the same time with #1063.

**Comment by Naatan** [comment]
@Defman21 you're more than welcome to open a PR :)
