### ISSUE TITLE
Add support for the flexbox modal

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#1063]
Another enhancement request, currently i get no auto completion when working with the [flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)(the [future](http://www.sitepoint.com/responsive-fluid-width-variable-item-navigation-css/#the-future-flexbox) is almost [here](http://caniuse.com/#search=flexbox)) modal.

**Comment by Defman21** [comment]
Someone on the forums asked me to add those properties to the CSS CodeIntel. I'll do when I have a time. Can you give me the link to MDN documentation?

**Comment by babobski** [comment]
Of course no problem, the Mozilla documentation about using the [flexbox](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Using_CSS_flexible_boxes).
And the [mozilla](https://developer.mozilla.org/en-US/docs/Web/CSS/flex) documentation of the display flex. 
But this documentation will provide you with the most [information](https://css-tricks.com/snippets/css/a-guide-to-flexbox/).
It would be nice to support [all versions (old, tweener and new)](https://css-tricks.com/snippets/css/a-guide-to-flexbox/#browser-support).
And it would be great if you can add the [IE10 support(with all the -ms- prefixes)](https://msdn.microsoft.com/en-us/library/hh673531%28v=vs.85%29.aspx)

**Comment by Naatan** [comment]
Only assigning mitchell because he "owns" this part of Komodo, anyone is free to make a PR :)
