### ISSUE TITLE
Pressing ctrl + shift + s(save file as) on template file, want's to save wrong file 

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#1064]
Steps to reproduce
 * Have a modified file open (in my case a php file)
 * open a file from template (in my case html)
 * Hit ctrl + shift + s(save file as)

The expected result is saving the html file, the result is saving the php file.
Hitting ctrl + s is giving the correct results.

**Comment by mitchell-as** [comment]
This is not a bug. Ctrl+Shift+S is "Save All". There is no key binding associated with "Save File As...".

**Comment by babobski** [comment]
:disappointed:  You're right, didn't checked for the key binding.
