### ISSUE TITLE
In comodo edit 9 dont work collapse all folds 

### ISSUE THREAD

**Issue by fut149** [Komodo/KomodoEdit#107]
collapse all folds  dont work in komodo edit 9

**Comment by Naatan** [comment]
Do you have folds enabled in Prefs > Smart Editing > Folding?

**Comment by fut149** [comment]
I can not see this option. Thank your for your quick reply. I find Komodo to be really nice IDE and I hope you will soon fix all of it's bugs.







 -------- Оригинално писмо --------

От: Nathan Rijksen notifications@github.com

Относно: Re: [KomodoEdit] In comodo edit 9 dont work collapse all folds 
 (#107)

До: Komodo/KomodoEdit  

Изпратено на: 02.04.2015 18:14



 
 
  
Do you have folds enabled in Prefs > Smart Editing > Folding?

**Comment by Defman21** [comment]
Nathan gave you a bit wrong path to the pref. The right path is `Preferences - Edtior - Smart Editing - Folding`

**Comment by Naatan** [comment]
Closing this until further details are provided indicating this is a bug. Code folding will not work if code folding is not enabled.

**Comment by Defman21** [comment]
I've tested it and Collapse all folds works fine. (but I can't find an item for it, only through hotkeys)
