### ISSUE TITLE
I cannot get KomodoEdit to go back to how it used to be

### ISSUE THREAD

**Issue by Godzillathethird** [Komodo/KomodoEdit#1070]
I don't know what I did, but Komodo edit no longer displays any options for me. The three bars are gone and so are all the options from the top of the page. All that's displayed on my page are the new tab and display tabs buttons and the bottom window pane. I want to be able to use the options again. I hope I'm doing a good enough job of explaining my problem so that somebody may understand.

**Comment by mitchell-as** [comment]
Hi, in the "New Tab" view (Ctrl+T) go to "Troubleshooting > Reset UI". Does that help?

**Comment by Naatan** [comment]
It sounds like you simply disabled your toolbars. You should still have a menu button at the bottom left in your statusbar, or you can press ALT to make the menu appear. From there hit View > Toolbars > Show Toolbars.

**Comment by Godzillathethird** [comment]
Thank you Naathan it worked. Komodo Edit is now back to normal.
