### ISSUE TITLE
Places Pane misses a Refresh feature

### ISSUE THREAD

**Issue by srgloureiro** [Komodo/KomodoEdit#1072]
Example:
Open Places in "x:dir"
Now using Explorer, in that dir do "Crate New File"
Go Back to Places, and (AFAIK) there is no way to see the new file.

**Comment by mitchell-as** [comment]
I am not able to reproduce this. Every time I create a new file, the file is opened in Komodo's editor view and shows in the places pane. Are you working on a remote filesystem?

**Comment by srgloureiro** [comment]
No. I am working with a file on root of the d: unit

**Comment by Naatan** [comment]
Do you have `Prefs > Editor > Confirmation Dialogs > Detect when files are changed outside the environment` unchecked?

**Comment by srgloureiro** [comment]
I have 
Detect when **networked **files are changed outside the environment 
unchecked.

NB  the _networked _word, which I wrote in Bold

**Comment by Naatan** [comment]
What type of drive is x: ?

**Comment by srgloureiro** [comment]
A partition of the same physical HDD of c:

**Comment by Naatan** [comment]
Can you reproduce the issue with a folder using an very basic name on the c: drive? eg. `C:\foo`.

**Comment by cgchoffman** [comment]
Closing
