### ISSUE TITLE
Cannot delete 'Rails Tools' from toolbox

### ISSUE THREAD

**Issue by sgeard** [Komodo/KomodoEdit#1078]
Surely I should be able to do this. I don't use Ruby at all and can't imagine why I would. I'd like the toolbox to contain the tools I want to use and only them.
Komodo IDE 9.3.2, Linux/x64

**Comment by sgeard** [comment]
Should have saif this is for Komodo IDE 9.3.2, Linux/x64

**Comment by mitchell-as** [comment]
Thanks for the report. I thought it might be a permissions issue, but I cannot delete it either.

**Comment by sgeard** [comment]
So the Rails Tools are indelible by design which means this is a design bug - but still a bug.
What is the likelihood of this actually being fixed in 10.1?

**Comment by cgchoffman** [comment]
Are you negatively effect in someway that we are not aware of by this?  The toolbox item resides in the Komodo install directory so we cannot allow you to delete it.  We'll have to build in the ability to disable an item.

**Comment by cgchoffman** [comment]
Or we could move this tool into the "sample tools" content that is installed into your userdir. Then you have full power over removing it.

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/753c67c7bdc7139ff0fa2171221a38727fd9cb46
