### ISSUE TITLE
Fix border around notifications on Windows

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#108]

**Comment by Naatan** [comment]
@cgchoffman assigned you since its easier to test for you. I think all you need to do is add an `!important` to https://github.com/Komodo/KomodoEdit/blob/master//src/modules/notify/skin/notify.less#L3

**Comment by cgchoffman** [comment]
Tested the changed Windows:
With or without the ```!important```, Default Skin still has the border.  With Abyss enabled, the border is fine but the "x" to close the dialog is gone.
