### ISSUE TITLE
Customization request - code anaylzer/browser

### ISSUE THREAD

**Issue by sgeard** [Komodo/KomodoEdit#1080]
I'd like to be able to add my own analyzer for the 'Code (#)' tab for languages you don't provide analysis for (Fortran in my case). Version 10?

**Comment by mitchell-as** [comment]
This is actually already possible, but not documented. If you go to Komodo's `lib/mozilla/python/komodo/langinfo_prog.py` file and search for `section_regexes`, you'll see an example for C++. Those regexes populate the code browser for C++ source files (without the need for codeintel). If you search for `Fortran`, you'll see an absence of `section_regexes`. If you like, you can create and submit your own set of regexes to us for inclusion in future Komodo releases.

The other way to do this is to create a Komodo Language Extension (Project > New From Template > Create Komodo Language) and create codeintel for Fortran. This codeintel will identify functions, variables, etc. that the code browser will automagically pick up. However, this is probably more complicated than you'd like it to be, probably due again to lack of documentation. We will work on improving documentation after K10.
