### ISSUE TITLE
Disable multi caret with ctrl+click

### ISSUE THREAD

**Issue by kaniztra** [Komodo/KomodoEdit#1081]
Multi-Mode always set when i copy-paste my code with pressed ctrl.
Please, make possibility to disable this function

**Comment by mitchell-as** [comment]
Thanks for the suggestion. In the mean time you can create a userscript with the following:

    require('ko/editor').scimoz().multipleSelection = false;

Every time you run it on a document, multiple carets will be disabled, so Ctrl+Click will do nothing extra.
