### ISSUE TITLE
Code Outline doesn't properly support Perl private functions

### ISSUE THREAD

**Issue by oryandunn** [Komodo/KomodoEdit#1084]
In Perl, if you have a private function of the form:
`my $myPrivateFunc = sub { ... }`
the code outline window lists $myPrivateFunc as a variable (which it is), as well as any variable within that subroutine at the same level of $myPrivateFunc.  I've attached a screenshot with an example.  You can see $myPrivateFunc, $this, $param1, $param2, $c, and $d are all siblings.

Ideally, at the very least, internal variables would be shown in the code tree as children of $myPrivateFunc.  Also, I'm not sure how, but it'd be nice if the tree could somehow flag $myPrivateFunc as both a variable and a function.

As it stands, with large classes in perl with private functions, the code outline is very cluttered, and makes the outline very difficult to use.

![screenshot from 2016-02-11 17-14-14](https://cloud.githubusercontent.com/assets/10134311/12992531/07900b1c-d0e3-11e5-85a9-092b619c0827.png)

**Comment by mitchell-as** [comment]
Thanks for the report. It looks like we do not recognize private functions and their members.
