### ISSUE TITLE
Excluding a folder from project, does not exclude it from "go to" definitions

### ISSUE THREAD

**Issue by harpreetsb** [Komodo/KomodoEdit#1085]
so lets say I two folders `Lib` and `Libx`.
Now  folder `Lib` and `Libx` both same file 'a.php' each, with follwing code
```php
<?php
function hello(){
 // Code goes here
}
```
there is another file `b.php` with code
```php
<?php
include("Lib/a.php");
hello();
```
**Note that I have excluded  folder `Libx` from project preferences**
##Steps
- CTRL+click on the function in file `b.php` take to function definition of file `Libx/a.php`.

though similar steps work fine for javascript, I get a popup to chose one file, but not for PHP

**Comment by mitchell-as** [comment]
My guess is that codeintel already picked up that folder before you excluded it and that folder and its files are now in the codeintel database. Does the behavior go away when you open a new tab (Ctrl+T), click "Troubleshooting" in the overlay panel, and select "Reset Codeintel Database"?

**Comment by mitchell-as** [comment]
Closing since #195 will take care of this.
