### ISSUE TITLE
SSH key config for remote server doesn't remain.

### ISSUE THREAD

**Issue by landy2005** [Komodo/KomodoEdit#1089]
I'm try to specify OpenSSH server key for remote server connection (server type SFTP).
But it not stored in config for selected server.

After research, I found this key stored in first entry of servers list.
Remove key config from first server and try to add key in any other server (exept first) produces the same result.

**Comment by landy2005** [comment]
`Komodo IDE, version 9.3.2, build 88191, platform macosx.
Built on Thu Dec 10 13:22:09 2015.`

**Comment by cgchoffman** [comment]
Could you provide step by step instructions on how to produce this?  I can't reproduce an issue specifying SSH keys for a server configuration.

**Comment by landy2005** [comment]
I test this only on MacOS (not has any other OSes).

1. Open Preferences -> Servers (here I have list with 5 or more servers, all with type SFTP)
2. Select any not first server from list
3. Specify an OpenSSH key file -> Browse -> selected file (my private key filename is 'mike_rsa') -> Open
4. Press 'OK' or 'Apply'.
5. Switch to any other preference, than back to Servers
6. Now I see - key not stored in required server (and not used for connect to it), but stored in first server in list.

But update..
At work (10.10 Yosemite) - key stored in first server in list
At home (10.11 El Capitan) - key complete not exist on any server after saving.

**Comment by landy2005** [comment]
Maybe it is also important, most of the servers from the list has custom (non empty) 'Default path' and 'Password'.

Second update... on (10.11 El Capitan) I found how to store correct key - if I change both fields (key and password), than after press 'Apply' there is a popup window 'Do you wish to save changes to server?'.
When I try to change and save ssh key only, after "Apply' there is no popup window.

Later will try this at work (with 10.10).

**Comment by landy2005** [comment]
Yes, on (10.10 Yosemite) if I change both ssh key and password, than key is stored (has save popup). When change only ssh key, not stored (do not have popup).

**Comment by cgchoffman** [comment]
Hrm, sounds like somethings wrong in the Apply/Save state method for that preferences screen view.  This actually sounds familiar.  Thanks for digging @landy2005

**Comment by cgchoffman** [comment]
#923

**Comment by cgchoffman** [comment]
I knew it sounded familiar.
