### ISSUE TITLE
Add support for css pointer events

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#1090]
Currently there is no support for pointer events, would be nice if this can be included.

Specs:
[https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events)

**Comment by cgchoffman** [comment]
This should be easy to do as a PR.  I don't have a reference for where this stuff goes though.  Can someone add one to make it easier for anyone interested in helping?

**Comment by Naatan** [comment]
ping @Defman21 :p

**Comment by Defman21** [comment]
My PC is broken and I don't know when I'll fix it.  :(

**Comment by mitchell-as** [comment]
I hear your PC lives @Defman21. You can help me push this into Komodo 10 :)

**Comment by Defman21** [comment]
👍

**Comment by Defman21** [comment]
#1191 :smiley:
