### ISSUE TITLE
After restarting with multiple windows the Addon dialog fails

### ISSUE THREAD

**Issue by wedeluxe** [Komodo/KomodoEdit#1094]
I love using multiple windows. Sadly, restoring the workspace when restarting with multiple windows fails. But that's a different (maybe related) story, I commented on that bug #253.

**Problem**

After starting Komodo Edit with multiple windows, the Addon dialog works / shows up only in one of those windows. It fails without any sign of life in the others.

Doesn't make any difference wether I use
- Menu > Tools > Add-ons
- BurgerMenu > Add-ons
- a key binding connected to the command "Add-ons: Open the addon dialog (extension manager)"

Note: In any new window created during the current session, the Addon dialog shows up as expected. The bug occurs only in all (except one) restored windows after a restart.

**Settings and surroundings**

- Preferences > Workspace > 
    - When starting Komodo : "Restore last workspace"
    - When opening a project : "Open recent files"
    - When closing a project : "Close all open files in project"
- Preferences > Places > 
    - Allow Multiple Open Projects : DISABLED
- Running
    - GNOME 3.16.2 on Arch Linux 64-bit
    - Komodo Edit, version 9.3.2, build 16460, platform linux-x86_64

**Comment by Naatan** [comment]
@cgchoffman what was the other bug that you were looking at that was related to multi window restoring?

**Comment by cgchoffman** [comment]
I report this already and was trying to figure it out for a while but I think someone else if going to need to take a look: https://github.com/Komodo/KomodoEdit/issues/1006

Note:  I did NOT see this in ALL windows.  i only see if in one out of many windows and it's always the second window.  @wedeluxe can you please double check that you're seeing it in ALL restored windows?  If I have 3 windows restore, window 1 is NOT broken, window 2 IS broken, window 3 is NOT broken.

**Comment by wedeluxe** [comment]
I did a lot of testing.
Settings and surroundings are as mentioned in the initial posting above.

Here's a step by step guide of what I did:
(Steps 1 to 4 are to put Komodo Edit into a somewhat clean state.)

1. Close all windows except one
2. Menu > Project > Close All Projects
3. Menu > File > Close > All files
4. Menu > File > Quit
5. Start Komodo
6. Single Window comes up. Addon dialog works. As expected.
7. Open eight more windows (Menu > File > New > New Window)
8. Addon dialog works in 9/9 windows. As expected.
9. Menu > File > Quit
10. Start Komodo
11. Addon dialog works in 6/9 windows.

I repeated steps 5 to 11 with different counts of windows. I double or multiple checked.
Here are the results:

Addon dialog works in 6/9 windows.
Addon dialog works in 6/9 windows.
Addon dialog works in 6/9 windows.
Addon dialog works in 5/8 windows.
Addon dialog works in 5/8 windows.
Addon dialog works in 4/7 windows.
Addon dialog works in 4/7 windows.
Addon dialog works in 3/6 windows.
Addon dialog works in 3/6 windows.
Addon dialog works in 2/5 windows.
Addon dialog works in 2/5 windows.
Addon dialog works in 1/4 windows.
Addon dialog works in 1/4 windows.
Addon dialog works in 1/3 windows.
Addon dialog works in 1/3 windows.
Addon dialog works in 1/2 windows.
Addon dialog works in 1/2 windows.
Addon dialog works in 1/1 windows.
Addon dialog works in 1/1 windows.

There clearly is a pattern. Three windows fail in the higher counts.

During all these tests there were three entries in the recent projects list.
It smells like this is related to the error in one way ore another.

**Comment by cgchoffman** [comment]
> Please respond in linked ticket above.

Please respond in the linked ticket in my response above.  Please include your logs in that response: Help > troubleshooting > View Log File.
