### ISSUE TITLE
Crazy scrollbar

### ISSUE THREAD

**Issue by stramin** [Komodo/KomodoEdit#1095]
This error was reported for Komodo IDE 8, and I think was fixed in Komodo 9 beta (nightly).

https://www.youtube.com/watch?v=kAoNWDDG_rE

I just bought Komodo IDE 9 and this error is back.

How to reproduce it:

Open a long file
Turn minimap on
Click and drag the scrollbar (not the minimap)

OS: Windows 7/8/10
OS Language: Spanish

**Comment by mitchell-as** [comment]
Thanks for the report. Confirmed.

**Comment by mitchell-as** [comment]
This should be resolved when #1304 is resolved.

**Comment by mitchell-as** [comment]
Resolved in #1304. The scrollbar was actually the minimap's scrollbar, not the editor's scrollbar.
