### ISSUE TITLE
Shortcut for publishing synchronize

### ISSUE THREAD

**Issue by stramin** [Komodo/KomodoEdit#1096]
I do not know if this is a good place to post a request...

I need to synchronize my website all the time, so i have to:

- Press Alt key to show the toolbars
- Select "Tools"
- Then select "Publishing"
- Then select a server configuration
- Wait for the sync status
- Press Synchronize!
- If a file fails then the synchronization stops, i can not continue and i must start again

I think this is a too long way for synchronizing

What about a shortcut for the server configuration?

![](http://forum.komodoide.com/uploads/default/original/1X/6081904e5d5f94c74b28653db68e16da316ffa15.png)

**Comment by cgchoffman** [comment]
this should be grouped in with general publishing updates if possible.

**Comment by Naatan** [comment]
You mean the UX task we have on Trello?

**Comment by cgchoffman** [comment]
I guess?  I don't know what board it's on.

**Comment by cgchoffman** [comment]
This is done in the latest 10.1.  Though this requests a permanent button.  We've only provided a dynamic button.  Maybe we should add a Publishing button to the bottom of the sidetoolbar as well which would contain the Open, create options?

**Comment by Naatan** [comment]
@cgchoffman that would be covered by https://github.com/Komodo/KomodoEdit/issues/1953

**Comment by cgchoffman** [comment]
ahh right ok.  Gonna close this then.  @stramin.  Checkout the new Dymanic Button for publishing in 10.1 plus the added publishing commands.
