### ISSUE TITLE
Komodo Edit 

### ISSUE THREAD

**Issue by scholer** [Komodo/KomodoEdit#1098]
Under preferences -> syntax checking for language Python3.
Komodo fails to detect Pylint installation (checkmark is grayed out).
This used to work (as in: it worked the day before yesterday). Not sure what happened. Have tried restarting Komodo, etc.
Been trying a couple of different python versions, but nothing helps. 
How do I get debug information so I can debug this issue? 
It this a known issue? 
I can run pylint manually just fine, e.g. with `python -m pylint mymodule.py`.

Environment:
Komodo Edit 9.3.2 
OSX
Anaconda Python distribution
pylint installed using `conda install pylint`

**Comment by mitchell-as** [comment]
Perhaps your Python installation itself has changed recently. Does `python -V` output Python 3.x on your system?
