### ISSUE TITLE
Support ES6 Template Literals

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1105]
It seems we are already highlighting backticks as strings, but we are not highlighting variables inside those strings.

Reference:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

Sample code:

```
var foo = "World";
var bar = `Hello ${foo}!`;
```

In this example `${foo}` should be highlighted as a variable and should support auto completions.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoEdit/commit/0b4b05241dfdab4610bb93451de01213ec2b9944
