### ISSUE TITLE
Indenting: Initial indent setting not getting set when doc is opened

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1106]
### Short Summary

I can only reproduce this on Windows so far.  I open a file and run `require("ko/editor").scimoz().indent` and the result is `0`.  This results in `cmd_backSmart` failing as a division by zero error occurs.

@Naatan thinks that it's his refactoring of koDocument.py which removed cases where prefs were implicitly set.  

As soon as you use your Tab key to create an indent the setting is set and the issue goes away.

**Comment by cgchoffman** [comment]
Note: prefs.xml file to reproduce the issue was dropped into slack for @Naatan

**Comment by mitchell-as** [comment]
Just so you know, Scintilla has two indent-type options: `scimoz.tabWidth` and `scimoz.indent`. `tabWidth` is exactly what you think, the width of a tab in spaces. `indent` is a bit different (but I'm not exactly sure how), but it is allowed to be zero. When it it zero, Scintilla internally uses `tabWidth`. Therefore any time you are asking scimoz for tab width, you *must use `tabWidth`* and not `indent`, or else you'll get division by zero.

**Comment by Naatan** [comment]
Link to prefs.xml: https://activestate.slack.com/archives/komodo/p1456361573000495

**Comment by cgchoffman** [comment]
Thanks @mitchell-as,  useful info.

**Comment by mitchell-as** [comment]
Just FYI, as indicated in my comments above, `scimoz().indent == 0` is perfectly valid. We just need to handle it properly.
