### ISSUE TITLE
Adding "as <anything>" in Python Imports makes "Go to Definition" Fail

### ISSUE THREAD

**Issue by TangoOversway** [Komodo/KomodoEdit#1107]
### Short Summary

If I have an import of my own Python module written out with "as [anything]" appended, "Go to Definition" will fail.  (This was discovered while dealing with issue #1016 about loading imports.)

### Steps to Reproduce

1. Create your own Python module, say, "foo.py" and save it in an editing directory
2. Make sure the directory containing foo.py is in your additional import path.  (Add it to your import paths in Edit > Preferences > Languages > Python > Additional Python Import Directories.)
3. Create a new Python module, say, "bar.py"
4. In Bar.py, add "import foo as fu"
5. Right click on "foo" in the line just created and pick "Go to Definition" in the context menu.

### Expected results

This should open foo.py in the Komodo editor, or, if it is open, go to the file in the appropriate tab.

### Actual results

Nothing!

If you remove the "as fu" from the end of the line, then it works as expected, but as long as the "as fu" is appended to the import command, "Go to definition" will not work.

### Platform Information

Komodo IDE
Build info: Komodo IDE, version 9.3.2, build 88191, platform macosx. Built on Thu Dec 10 13:22:09 2015.
OS X El Capitan 10.11.3

**Comment by mitchell-as** [comment]
Thanks so much!

**Comment by TangoOversway** [comment]
So that fixes it?  When will I be able to get an update with this in it?


Thanks!


Hal

**Comment by mitchell-as** [comment]
Yes, this will be fixed in the next nightly build that we'll push out in the next few days. Keep your eyes peeled: http://downloads.activestate.com/Komodo/nightly/komodoide/latest-9.3.x/

**Comment by TangoOversway** [comment]
Thank you!

I thought this was a small enough issue that it’d be rather low priority.  (But also figured it’ be an easy fix, too.)


Hal
