### ISSUE TITLE
Quick Bookmark bad behavior

### ISSUE THREAD

**Issue by cdcmicro** [Komodo/KomodoEdit#1110]
### Short Summary

Commenting a block that contains bookmarked lines clears bookmarks and adds a bookmark on the last line of the block.  Commenting here refers to pressing `Ctrl-/` with a series of lines selected in the editor.  Possibly related to #754.

### Steps to Reproduce

Start with:

![screenshot_022516_014220_pm](https://cloud.githubusercontent.com/assets/13684992/13335361/993fcb78-dbc5-11e5-8e34-98bb134a120f.jpg)

Press `Ctrl-/` to comment-out the block

### Expected results

![screenshot_022516_020111_pm](https://cloud.githubusercontent.com/assets/13684992/13335909/3e95db4c-dbc8-11e5-8e8b-4fdeada9026b.jpg)

### Actual results

![screenshot_022516_014538_pm](https://cloud.githubusercontent.com/assets/13684992/13335457/12325bc2-dbc6-11e5-9f54-302c4bf03966.jpg)

The "new" bookmark on line 5 requires several `Ctrl-F2` presses to clear it.

If the comment/new bookmark is on a block-closing line, sometimes no number of `Ctrl-F2` presses will clear it until I `F2` to it from elsewhere and `Ctrl-F2` again.

The behavior is the same whether I create the bookmarks with `Ctrl-F2` or `Ctrl-Shift-digit` except the "new" bookmark shows the indicator for the highest-numbered bookmark in the commented selection.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 9.3.2, build 88191, platform win32-x86
*Operating System (and version)?* Win7 x64

**Comment by cdcmicro** [comment]
Doesn't seem to be language-sensitive.  Behaves the same in javascript.

**Comment by Naatan** [comment]
@mitchell-as I guess this is because the commenting code rewrites the lines entirely rather than modifies them?

**Comment by mitchell-as** [comment]
Yes, that would do it.
