### ISSUE TITLE
X86_64 xdebug extention causing apache 2.4 to segfault.

### ISSUE THREAD

**Issue by jellisii** [Komodo/KomodoEdit#1114]
--- Please replace the dots (...) with your answers and remove this line. ANY information is helpful, you are in no way obliged to fill out all the fields ---

### Short Summary

I'm trying to set up remote debugging for PHP and have hit a snag.  Whenever I enable the xdebug module in my setup and load a page, Apache segfaults 

### Steps to Reproduce

Using Ubuntu 14.04 with PHP5.5

eellis@e2:~$ php -v
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with the ionCube PHP Loader v4.7.5, Copyright (c) 2002-2014, by ionCube Ltd., and
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
    with Xdebug v2.2.5-komodo, Copyright (c) 2002-2014, by Derick Rethans
eellis@e2:~$ 

eellis@e2:~$ apache2 -v
Server version: Apache/2.4.7 (Ubuntu)
Server built:   Jan 14 2016 17:45:23
eellis@e2:~$ 

Loading xdebug with the following:
eellis@e2:~$ cat /etc/php5/mods-available/xdebug.ini 
; xdebug config for Linux and Mac OS X
; Extension from Komodo-PHPRemoteDebugging-9.3.2-88191-linux-x86_64.tar.gz
zend_extension=/usr/local/lib/php5/xdebug.so 
xdebug.remote_enable=1
xdebug.remote_handler=dbgp
xdebug.remote_mode=req
xdebug.remote_host=my.remote.address
xdebug.remote_port=9000
xdebug.remote_log=/tmp/xdebuglog
xdebug.idekey=my.ide.key

Enable the above and restart Apache.
Load a page.

### Expected results

A page.

### Actual results

A segfault

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 9.3
*Operating System (and version)?* Linux Mint 17.3

### Errors / Logs

```
[Mon Feb 29 11:23:04.396477 2016] [core:notice] [pid 27393] AH00052: child pid 27398 exit signal Segmentation fault (11)

```

--- 
Information on locating the Komodo error log:

N/A

### Screenshots / Screencasts

N/A

**Comment by Naatan** [comment]
Note neither xdebug nor apache are maintained by us. Please ask for general support on our forums or file a bug on the xdebug or apache bug trackers.

Our forums: http://forum.komodoide.com/

**Comment by jellisii** [comment]
According to http://docs.komodoide.com/Manual/debugphp#debugging-php-komodo-ide-only_remote-php-debugging_configuring-remote-php-debugging_step-1-copy-the-debugging-extension-to-the-web-server:

> **Note**: You must use ActiveStates distribution of Xdebug. It is built specifically for debugging in Komodo. 

Which is why I opened an issue here in the first place.  If this isn't the case, then the documentation should be updated to reflect reality.

**Comment by Naatan** [comment]
The ActiveState distribution only ensures compatibility, using one that came with your distro should in most cases work too and will in this case likely resolve your issue.

I'm not sure why the word "must" was used in the documentation, this just isn't true. I'll update the documentation accordingly.

**Comment by jellisii** [comment]
Thank you sir.
