### ISSUE TITLE
Auto multi caret when deleting delimiters

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1116]
This is a continuation of #1115 but would still be a different feature (ie. different pref, slightly different workflow).

Same as the referenced issue the idea is to facilitate editing delimiters, but in this case it should "just work". Ie. I don't need to adopt a workflow (selecting delimiters to replace them), instead Komodo just "gets it".

Essentially what I want it to do is whenever I delete a delimiter with backspace or delete Komodo puts me in multi-caret mode with a caret in both places that the delimiters used to be. If I continue deleting text then the multi-caret is removed and it continues as if it never happened. In other words if I delete a delimiter and the next keypress is not a delimiter then the multi-caret is cancelled.

Please target for 10 if you like the idea and it's implementable as a nice-to-have (ie. you think you'll have time and you think it won't be too time consuming).

**Comment by mitchell-as** [comment]
From my understanding, I see a problem with this idea. Consider this initial state:

    console.log("hello world"|

Now press backspace:

    console.log(|hello world|

Press backspace again:

    console.log(hello worl|

You've lost the first `"` character, so Komodo does not continue as if it never happened. If you intend to have an "anti soft character" where the first quote is put back, that ups the complexity big time.

While this would certainly be cool if it works, it has enough moving parts to make me wonder if it's worth the time and effort to do. I don't think Komodo gives me the tools I need to do this so I may have to patch the C++ event code to emit more events to handle (onBeforeInsert- and onBeforeDelete-type of events).

**Comment by Naatan** [comment]
Good point. I think we can close this in favour of the enhancement you addressed where selecting a delimiter also selects the other one.
