### ISSUE TITLE
show section list annoyance

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#1118]
### Short Summary

I know this is an old feature, but still. Leaking the leftover keypresses to the editor sux.
### Steps to Reproduce
1. Hit the hotkey to open up the popup of the items
2. Start typing
3. As soon as there's no match e.g. "get" "x" the popup closes
4. The next keypresses go to the editor changing the code
### Expected results

figure something for 4. whatever is easy
### Platform Information

Komodo IDE, version 9.3.2, build 88191, platform linux-x86_64.
Built on Thu Dec 10 13:00:48 2015.
### Screenshots / Screencasts

![screenshot_2016-03-01_17-26-16](https://cloud.githubusercontent.com/assets/350912/13433663/1f756552-dfd3-11e5-8e4a-101fc29bb152.png)

**Comment by Naatan** [comment]
I actually fought with this way back around 8.5 (it used to be much worse), I don't recall exactly what the reason was but the desired behaviour was more challenging than you'd expect. I'll try to tackle this again.

Note as a workaround you could use the Sections scope in Commando.

**Comment by agroszer** [comment]
yah I know the Sections scope, downside is it does not display the class names for methods (for python). If you have lots of same named methods in the same .py file... good luck figuring which is in which class.

**Comment by agroszer** [comment]
![screenshot_2016-03-01_17-57-03](https://cloud.githubusercontent.com/assets/350912/13434687/0e28094a-dfd7-11e5-92d5-2f00bff626c8.png)

**Comment by agroszer** [comment]
#1120

**Comment by lagbox** [comment]
This really needs to be fixed, this is way past due. Using the section list is not a good user experience.
Do anything you would normally expect to do and it closes. You backspace the input, it closes. You type something that doesn't match, it closes.  You end up typing into your editor.

**Comment by Naatan** [comment]
This is already fixed in 11, the section list has been completely redone and is now called a symbol list. Unfortunately it'll still be a while before the first beta - sorry :)
