### ISSUE TITLE
macro hotkey overrides UI basic hotkey

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#1119]
### Short Summary

Have a macro bound to alt+down arrow, that overrides the combo open alt+down arrow hotkey

### Steps to Reproduce

1. Have a macro bound to alt+down arrow (for me that goes to the next code section)
2. open up incremental search (ctrl+i)
3. hit alt+down arrow

### Expected results

4. The previous search items popup should show up

### Actual results

4. It goes to the next code section

### Platform Information

Komodo IDE, version 9.3.2, build 88191, platform linux-x86_64.
Built on Thu Dec 10 13:00:48 2015.

### Screenshots / Screencasts

![screenshot_2016-03-01_17-32-19](https://cloud.githubusercontent.com/assets/350912/13433805/c2fb7892-dfd3-11e5-9ce9-9ac513704a19.png)

**Comment by Naatan** [comment]
Was going to assign this when I figured; this is a macro. What the macro does is completely unknown to Komodo, so it would not make sense for Komodo to have a bias about when not to trigger a macro keybinding. If you don't want your macro to trigger in a certain context then your macro needs to be handling this logic itself.
