### ISSUE TITLE
Sections scope does not show class name

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#1120]
### Short Summary

(Python) When having lots of same named methods in the same .py file the list does not show the class name, which makes it hard to hit the method you want.

![screenshot_2016-03-01_17-57-03](https://cloud.githubusercontent.com/assets/350912/13436896/b932b204-dfe1-11e5-8ec5-c0aea11a49a9.png)

**Comment by mjainQA** [comment]
No test case needed.
