### ISSUE TITLE
Komodo freeze after some opened files are updated externally(git terminal)

### ISSUE THREAD

**Issue by satmovi** [Komodo/KomodoEdit#1123]
### Short Summary

I have some files opened in Komodo. Usually the app freezes when some of the files are updated in terminal, using git pull/
...
### Platform Information

_Komodo Edit or IDE?_ ... IDE
_Komodo Version?_ ... 9.3.2
_Operating System (and version)?_ ...
OSX El Capitan
### Errors / Logs

```
could not resolve 'if'
[2016-03-04 11:40:31,554] [ERROR] koCodeIntel:     INFO: eval '$self.model' at CustomDataTables.pm#54  <Trigger 'perl-defn-defn' at 1909 (explicit)>
    INFO: start scope is (<blob 'IMM::Controller::CustomDataTables'>, ['IMM::Controller::CustomDataTables', 'create_empty_table'])
    INFO: is '$self' accessible on (<blob 'IMM::Controller::CustomDataTables'>, ['IMM::Controller::CustomDataTables', 'create_empty_table'])? yes: <argument '$self'>
    INFO: lookup 'model' on <argument '$self'> in (<blob 'IMM::Controller::CustomDataTables'>, ['IMM::Controller::CustomDataTables', 'create_empty_table', '$self'])
    ERROR: evaluating '$self.model' at CustomDataTables.pm#54: no type-inference info for <argument '$self'>
[2016-03-04 11:40:34,673] [ERROR] hyperlinks::GotoDefinition: 
-- EXCEPTION START --
TypeError: s is undefined
+ stack
    _simpleEscapeHtml@chrome://komodo/content/hyperlinks/gotodefinition.js:215:9
    _setDefinitionsInfo@chrome://komodo/content/hyperlinks/gotodefinition.js:313:1
    GotoDefinitionUIHandler.prototype.setDefinitionsInfo@chrome://komodo/content/hyperlinks/gotodefinition.js:396:9
-- EXCEPTION END --
```

**Comment by Naatan** [comment]
1. Could you share your full error log?
2. Is the freeze temporary or does it require you to restart Komodo?
3. Are the files located on a mount or a local partition?
4. Does the issue occur when you don't have any of the files being updated open?

**Comment by satmovi** [comment]
Hello,
1. Attached the log for a freeze, I had to force quite the app.
2. I had temporarily freezes and also ones that required restart
3. Local disk, no mount.
4. I think it only occurs when some of the files opened in Komodo are updated externally(I’m usually doing git pull from osx terminal). Komodo freezes and I have to force quit, then when I open it again and asked to reopen the files… clicking Yes will freeze again, so I have to open Komodo without any files opened.

**Comment by Naatan** [comment]
Hey @satmovi, unfortunately email attachments don't show up here. Please attach it manually via github.com.

**Comment by tonyattwood** [comment]
Hi,

I've visited a very nice place some time ago and have very good  memories associated with it, here are some pics of that amazing  place <http://expert.braugi.com/e4qdo>

tony.attwood@ntlworld.com
