### ISSUE TITLE
JSHint Options don't apply

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1124]
### Short Summary

Passing in custom options to jshint does not seem to take effect.

### Steps to Reproduce

1. Set `moz=true` in JSHint options (see http://jshint.com/docs/options/#moz)
2. Create a new javascript doc
3. Paste in the following code

```
var x = function () true
```

### Expected results

No syntax errors

### Actual results

Syntax error and a recommendation to set moz=true 

### Screenshots / Screencasts

![jshint opts](https://cloud.githubusercontent.com/assets/278649/13533944/bac6fece-e200-11e5-9049-a95e5087d67d.png)

**Comment by mitchell-as** [comment]
Hehe, oops. If you have `moz=true` on its own, then syntax checking works. But with more than one option it chokes.

**Comment by mitchell-as** [comment]
It turned out to be a bug in JSHint that was fixed in a later release. We cannot use that release though since 2.6.3 is the latest that works for us.
