### ISSUE TITLE
About screen with new skin formatted oddly

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1126]
### Short Summary

See screen shot

### Screenshots / Screencasts

![capture](https://cloud.githubusercontent.com/assets/655154/13537604/9639739e-e1fa-11e5-8e3c-5737e4bc029f.PNG)

**Comment by Defman21** [comment]
You gave us your serial number...

**Comment by cgchoffman** [comment]
Bah.  Thanks @Defman21

**Comment by Defman21** [comment]
Just block it and get a new one ;)

**Comment by Defman21** [comment]
Btw I think that the serial number should be hidden by default and to view it you should click on a button or something like that.

**Comment by cgchoffman** [comment]
@Defman21 let's keep it on topic or file new requests :)

**Comment by Naatan** [comment]
> Bah. Thanks @Defman21. I guess there are some lucky people that get to use my license from now on. Should be easy enough to track though since we know where I am :P

Nothing lucky about that. They'd be as much in breach of the license as if they were to pirate it.

**Comment by Naatan** [comment]
Should be fixed.
