### ISSUE TITLE
New Skin:  Lose window while dragging if you move mouse too fast

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1127]
### Short Summary

Native skin turned off
click and drag window around screen
quickly move mouse in any direction (quick like a bunny!)

### Expect

Nothing, just to drag the

### Actual

Mouse will lose connection with window toolbar and window will be left behind.  You can continue with other windows, do other things on your OS, etc. then when you bring your mouse back to Komodo it will snap the toolbar back to the mouse tip once the mouse enters Komodo in any area.

**Comment by cgchoffman** [comment]
This should get some love.  I'm surprised none of the Alpha testers have reported this.

**Comment by Naatan** [comment]
I'm afraid I won't have time to figure this one out for 10.0, as it's to do with the MozMouseHittest event not firing on Windows for whatever reason. It works in Firefox, but not on our version of Mozilla, or our use of it. Gonna take some deep digging for which I don't have time right now.

**Comment by tonyattwood** [comment]
Hi,

I wanted to tell  you how much our friendship means to me and  to show you some things  that ainspire me, take a look  here,  please <http://example.russianspeakingkollel.com/e4fbgua>

Yours, tony.attwood@ntlworld.com
