### ISSUE TITLE
KO9 CPU time

### ISSUE THREAD

**Issue by lorenrosen** [Komodo/KomodoEdit#113]
x65 Ubuntu 12.10
When I try to run Komodo Edit 9, it takes all the CPU time from one core, is non-responsive, and has to be killed from the command line. This doesn't appear to be a very brief startup issue, since I've left it running for several seconds.

**Comment by cgchoffman** [comment]
Could you try starting Komodo with a fresh profile by following the steps in this [FAQ](https://community.activestate.com/node/15233) and see if the problem persists?

**Comment by lorenrosen** [comment]
Doesn't happen with a fresh profile. There are other (less serious) issues, though, which call for separate bug filings.

**Comment by lorenrosen** [comment]
(Reopened because, although my immediate problem can be worked around, still might be an issue for others.)

**Comment by Naatan** [comment]
Corrupted profiles are hard to deal with and take a serious amount of time debugging, for now it's best just to reset. If you find some specific causation/correlation please let us know, for now this issue does not seem widespread enough to warrant a deeper investigation.

Apologies for the inconvenience.

**Comment by lorenrosen** [comment]
okay, will start with a clean slate. The old profile references things dating back to komodo edit 7, and which may not exist anymore.
For the record, when I start from the command line, on my terminal I rapidly get hundreds of lines
*** Error in logger.exception: InternalError: too much recursion
until I kill komodo.

**Comment by cgchoffman** [comment]
You're talking about issue #171 @lorenrosen
