### ISSUE TITLE
Add pref to make multi-caret word insensitive

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1131]
Suggested pref:

 * [checkbox] Make multi-caret word-insensitive if selection is longer than [textbox] characters

**Comment by mitchell-as** [comment]
Under what context/circumstances would this apply? Ctrl+D?

**Comment by Naatan** [comment]
Exactly, CTRL+D

**Comment by mitchell-as** [comment]
Forgive my nitpickiness, but is this really useful? I cannot think of a case that would justify the work and pollution of the preferences page.

**Comment by Naatan** [comment]
I often find myself using Ctrl+D and it giving me mixed results. I don't have an explicit use-case right now that I can share, but it is something I find myself often running into.

How much work would be involved? I agree this likely does not merit a ton of time investment, but if it's only an hour or so I think it's worth it.

**Comment by cgchoffman** [comment]
I use Ctrl+D all the time but I don't understand what this is asking for otherwise I would weigh in.

**Comment by mitchell-as** [comment]
@cgchoffman it sounds like if you Ctrl+D on something long like "foobarbaz", then instead of restricting multiple subsequent selections to "foobarbaz", it will select "fooBarBaz", "FOOBARBAZ", etc. (ignoring case). That's assuming the number of characters in "foobarbaz" is more than the one in the preference.

@Naatan yes, this would not take too long, but I still don't see a valid use case for this.

**Comment by Naatan** [comment]
Sorry, as said I don't currently have an explicit use-case, other than the fact that I have ran into it various times. We can leave this open until I run into it again so I can give a use case. If this is really fast to turn into a pref I prefer we just go ahead and do that though.

**Comment by Naatan** [comment]
Here's a use case:

```
        var emptyDirty = list.find("#staged-empty");
        if (stagedItems)
            emptyDirty.hide();
        else
            emptyDirty.show();
```

I want to change instances of "staged" to "empty". Currently multi-caret cannot help me with this as it considers staged-empty different from stagedItems (just the word "staged").

**Comment by Defman21** [comment]
Good example! Sometimes I face with that as well.

**Comment by Naatan** [comment]
@mitchell-as perhaps rather than making this a pref we could simply add another command for it, which is word insensitive.

**Comment by mitchell-as** [comment]
I like that idea better with the separate command. The "longer than X characters" pref part is awkward.
