### ISSUE TITLE
New UI: No window buttons for main window when native deco's are on

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1132]
### Short Summary

When native decorations are on there is no window decorations at all so you're missing the  "-", expand, or  "x" buttons for the window

### Steps to Reproduce

Enable native decorations: right click toolbar > customize > Enable Native window decorations

### Expected results

To still have those buttons

### Actual results

I don't have them

**Comment by Naatan** [comment]
Is this still happening?

**Comment by cgchoffman** [comment]
> Is this still happening?

I'm not seeing it on OSX or Windows, so yes as those are the platforms I would have reported this from.
