### ISSUE TITLE
New UI: Non-main window windows have extra window buttons

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1133]
### Short Summary

When you enable native window decorations and open secondary windows, the second window will still have the custom window decorations ( see screenshot), as well as an additional close button.

### Steps to Reproduce

Enable native window decorations
open preferences

### Expected results

No additional buttons

### Actual results

there are additoinal buttons, see screenshot

**Comment by Naatan** [comment]
No screenshit? But fairly certain this is fixed. Reopen if not.

**Comment by Defman21** [comment]
Screenshit? Lol

**Comment by Naatan** [comment]
hush

**Comment by cgchoffman** [comment]
Ahh yesh, this should be fixed by https://github.com/Komodo/KomodoEdit/commit/d1093a629d6be6387fc7786794bb51f026c6ae17
