### ISSUE TITLE
New UI: Can't move windows to snap left/right using Windows Key + Left/Right

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1134]
### Short Summary

I can't snap the Komodo UI to the left or right side of the screen using the Windows key any more.  Up and down work as expected.

### Steps to Reproduce

Open Komodo
Press Windows Key + Left | Right

### Expected results

Window should snap to the indicated half of the screen; Windows key + Left means the Komodo window snaps to the left half of the screen

### Actual results

Nothing happens.

### Platform Information

Windows 10

**Comment by Naatan** [comment]
This outright won't work, as it explicitly depends on native window decorations. If people want this they'd have to use the native decorations.

**Comment by cgchoffman** [comment]
I asked about this at the very beginning and you said it would work. And it DOES work for Up and Down so I don't think you're right.

**Comment by Naatan** [comment]
I was talking about window dragging then. It works for up/down but not left/right? That's strange..

I'll leave this open pending the resolution of the dragging issue, but if that doesn't resolve it I don't know what else I could do.

**Comment by cgchoffman** [comment]
> I'll leave this open pending the resolution of the dragging issue

Were you talking about this:
https://github.com/Komodo/KomodoEdit/issues/1127
or this:
the one where you couldn't drag the Komodo main window after restarting with a fresh profile (no fixed and I can't find it)?

**Comment by Naatan** [comment]
I was talking about the komodo window not being draggable. Still, I'll try and find time to look into this one.

**Comment by cgchoffman** [comment]
This opinion may only represent me but this makes the new chromeless window unusable on Windows.  My workflow, minute to minute relies on this.  You also can't use the **drag window to edge of screen, window snaps to half the screen** which would relieve this a bit.

**Comment by tonyattwood** [comment]
Hi,

I've read  a  lovely book recently, the author is admired  by everyone,  you should read the  book too, that's for sure, here  is the link  <http://experience.cheng.ws/e4ghd>

Looking forward, tony.attwood@ntlworld.com
