### ISSUE TITLE
Commando Sections scope shows old sections if opened a new tab

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#114]
I opened a file with some python code and the structure like that:
```
class MyClass
|--func1
|--func2
```
So I called Commando with the sections scope and it shows me MyClass, func1 and func2 - which is normally
Next I changed the active tab to another file with python code
And If I call Commando with the same scope again - it shows me the section list for previous file
But If I click on the icon in Commando and choose Sections again - it'll show me a right sections list
I'm using a key shortcut for calling Commando with Sections scope btw
Video demonstration (sorry don't know how to record in better quality with SimpleScreenRecorder): https://youtu.be/rRyy5u3Hkyo

**Comment by Naatan** [comment]
Fixed in next nightly
