### ISSUE TITLE
Hide autocompletions when terminated by non-alphanumeric characters

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1141]
Take the following example:

```
var ob = { functionName: function() {} };
ob.functionName();
```

Delete the last line and write it out in full, you will get completions for `functionName` but when you type the brackets the completions will continue to show. It would make more sense that the completions would hide as soon as I type brackets or anything that cannot be part of a property name.

Careful not to break autocomplete fill-up characters when looking at this.

**Comment by mitchell-as** [comment]
This was actually done in #656 but overshadowed by the change specified in #871/#880. Since that change has been reverted in master now (it was previously only reverted in 9.3.x), this ticket is no longer applicable.
