### ISSUE TITLE
CodeIntel fails on sdk/logging.js

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1144]
Open https://github.com/Komodo/KomodoEdit/blob/master/src/chrome/komodo/content/sdk/logging.js in Komodo and check your section list.

Just adding this since you said you're improving codeintel by checking JS files that aren't interpreted properly and then take it from there, this seems like a good candidate.

**Comment by mitchell-as** [comment]
It looks like you're doing some fancy

    foo = exports.foo = function() { ... }

stuff that is throwing off codeintel. I think if you populate `exports` like most JS modules this will go away. Regardless, I'll get around to supporting these convoluted cases.

**Comment by Naatan** [comment]
That's not uncommon in JS so something we ought to be able to cover.

Not my code btw (mostly anyway).

**Comment by mitchell-as** [comment]
After more investigation this is actually a bug with the new anon function call codeintel support. Retagging as such.
