### ISSUE TITLE
New UI: No text in scintilla editor even with fresh profile

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1145]
### Short Summary

I've not had text in the editor since pulling in the new UI.  See screenshot.  I created the file in K9.2 then opened it in K10.  I did a browser preview to confirm that the file that is open has text in it.

### Steps to Reproduce

Just open a file in KOmodo 10 on Windows

### Expected results

See text in the editor

### Actual results

There is nothing in the editor or the minimap which is enabled in the screenshot below

### Platform Information

Komodo IDE and Edit, new UI
Windows 10

### Additional Information

![capture](https://cloud.githubusercontent.com/assets/655154/13658851/c0784412-e62f-11e5-8fe1-d99da25bdc7c.PNG)

**Comment by cgchoffman** [comment]
Interesting note for this.  If I go into Full screen mode (View > Full Screen) then back to normal, the scintilla will now show content BUT the IDE around the scintilla plugin is blank.  See screen shot: 
![capture](https://cloud.githubusercontent.com/assets/655154/13763547/269f263e-ea04-11e5-8086-c0e071d19f93.PNG)

**Comment by Naatan** [comment]
Does turning on window decorations fix this? Does the issue also occur in eg. the Rx editor?

**Comment by cgchoffman** [comment]
@Naatan Turning on window decorations has no effect.
Yes, it also occurs in the Rx editor, Log viewer, Userscript editor. 

@mitchell-as, I can't remember what other Scintilla views there are.  Is there an easy way I can cycle through and test each view to see if this issue occurs in all/only some of them?

**Comment by mitchell-as** [comment]
@cgchoffman `src/chrome/komodo/content/bindings/views-*` lists all views. Some that you missed are the diff views and terminal views (debugging and interactive shells use terminal views).

**Comment by cgchoffman** [comment]
Thanks @mitchell-as , All of those have the same issue.  
@Naatan Tried add `window{background: red;}` to normalize.less with no effect.
@mitchell-as Also tried `scimoz.colourise(0,-1)` on the open editor buffer but had no effect.

**Comment by Naatan** [comment]
I fixed the issue where swapping window decorations would outright not work on Windows. For now enabling native window decorations works around this issue, @mitchell-as will be looking into the issue of scintilla not drawing properly when the native window decorations are disabled.

**Comment by mitchell-as** [comment]
I cannot reproduce this in master with a clean profile and native decorations disabled (this is the default). I did notice that native window decorations are turned on as a side effect of exiting full screen mode though, and the preference remains unchecked in the 'Customize' dialog. I had to toggle that checkbox twice to turn native decorations back off.

**Comment by Naatan** [comment]
Thanks @mitchell-as!

Please open a new bug on the fullscreen issue if you can repro it.
