### ISSUE TITLE
Bug when "open remote directory"

### ISSUE THREAD

**Issue by drpark** [Komodo/KomodoEdit#1147]
### Short Summary

Often (not at every time, but too many often to be annoying), when doing "open remote directory" 
It seems to freeze and i need to force closing komodo and relaunch it...And this 2 or 3 times consecutively before getting the window allowing me to choose the remote directory.

This happens on my laptop, desktop and my colleagues too...
### Steps to Reproduce

Open remote directory, then it freeze
### Platform Information

_Komodo Edit or IDE?_ IDE
_Komodo Version?_ 9.3
_Operating System (and version)?_ WINDOWS 10
### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by Naatan** [comment]
Can you share some information about the remote directory that you are trying to open? Can you reproduce the issue with a completely different remote (different server, different protocol, you can easily test this with an ftp server that has anonymous access).

**Comment by cgchoffman** [comment]
Closing in favour of #1758
