### ISSUE TITLE
Tag matching highlight is not working for a single char variables.

### ISSUE THREAD

**Issue by farkass** [Komodo/KomodoEdit#1148]
### Short Summary
When clicking before or after a single letter variable, the references should be highlighted.

### Steps to Reproduce
Load any code - python, ruby, javascript -  with single letter variable defined and used.

### Expected results
Highlight all the instances.

### Actual results
HIghlight remains on previous variable longer then 1 char.

### Platform Information
Komodo Edit, version 9.3.2, build 16460, platform win32-x86.
Built on Thu Dec 10 22:21:38 2015.

### Additional Information

 -- eg. Error logs, screenshots, workarounds --
![selection_793](https://cloud.githubusercontent.com/assets/9973405/13697904/eb64689e-e770-11e5-9d0c-5f6fa3dab70a.jpg)
![selection_795](https://cloud.githubusercontent.com/assets/9973405/13698197/e55aa31c-e772-11e5-803f-e97384b6ea8e.jpg)

**Comment by Naatan** [comment]
I cannot refactor > variable rename single length vars either. Maybe there is a "by design" reason for this though, @mitchell-as can you find out?

**Comment by mitchell-as** [comment]
Pretty sure this is a bug.

**Comment by farkass** [comment]
Thanks!
It is the same in this version:
Komodo Edit, version 9.3.2, build 16460, platform linux-x86_64.
Built on Thu Dec 10 19:37:22 2015.

**Comment by mitchell-as** [comment]
I happened upon this preference: Edit > Preferences > Editor > Smart Editing > Variable Highlighting > Minimum length for automatic highlighting

By default it is 2. If I change it to 1 I can highlight `i`s.

**Comment by farkass** [comment]
Thank you, changed the preference value!
