### ISSUE TITLE
New UI: Color Scheme Editor "Save" Does Not Reflect Reality

### ISSUE THREAD

**Issue by mitchell-as** [Komodo/KomodoEdit#1151]
1. Start with a clean profile.
2. Open the color scheme editor.
3. Create a new scheme ("test").
4. Change the color of a style that shows up in the preview (e.g. Common - strings).
5. Immediately after picking the color, the preview shows up fine.
6. Press "Save" and the preview reverts to the original color, but the actual color remains correctly changed.

The preview should accurately reflect the updated color.

Note: this appears to only happen the first time. Subsequent edits appear to work okay. That's why step 1 is so important.

**Comment by Naatan** [comment]
This has been fixed in a recent commit
