### ISSUE TITLE
New UI: Color Scheme "Ok" and "Save" Buttons Act Counterintuitively

### ISSUE THREAD

**Issue by mitchell-as** [Komodo/KomodoEdit#1152]
1. Open the color scheme editor.
2. Create a new color scheme.
3. Change some colors.
4. Click "Ok".
5. Nothing actually changes and the default scheme is still used. The only way I can activate my new custom scheme is to click "Apply" and select stuff.
6. The same thing happens if I click "Save" in step 4.
7. The same thing happens if I want to switch between schemes. Selecting the scheme and clicking "Ok" or "Save" still uses my original scheme.

Either Ok should act like "Apply" or be removed completely. "Save" seems to only save the colors but not apply them either. At this point I don't really know which button does what anymore.

**Comment by Naatan** [comment]
I'll rename OK to Close. Because this is now a Color Scheme Editor (not a pref screen) having OK change the current color scheme doesn't make sense.
