### ISSUE TITLE
"HTML Tag Relocator" crashes Komodo when cursor at end of document.

### ISSUE THREAD

**Issue by brokencube** [Komodo/KomodoEdit#1153]
### Short Summary

Using "HTML Tag Relocator" (Ctrl+Shift+Z), when relocating a tag to the end of the document, a further press of Ctrl+Shift+Z crashes Komodo.
### Steps to Reproduce

Create a small document containing `<p></p>abcdefgh`.  With the cursor somewhere in the HTML tag, press (Ctrl+Shift+Z) 3 times.
### Expected results

The first press highlights the end tag, The second press should move the end tag to the end of the document. The third press should do nothing.
### Actual results

The first two presses work as expected. The third press crashes Komodo.
### Platform Information

Komodo IDE, version 9.3.2, build 88191, platform linux-x86_64. Built on Thu Dec 10 13:00:48 2015.
Ubuntu 15.04
### Additional Information

The trigger seems to be activating the Tag Relocator when the highlighted tag is already at the end of the  document.

**Comment by Naatan** [comment]
Could you provide a full example? Yours does not appear to include any HTML tags.

**Comment by Naatan** [comment]
Reproduced.

**Comment by cgchoffman** [comment]
@brokencube you're using "HTML Tag Relocator"!!??  Awesome! It's the first thing I ever wrote for Komodo and it's pretty hidden.  And here I thought it was perfect this whole time :(  Thanks for making/ruining my day @brokencube. Kidding.  We'll get this sorted.

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/6bd683dd50547da5b9224ec8e0edcecb839346dc
