### ISSUE TITLE
Find In Files Search History Tabs Don't Remember "Directory" Field

### ISSUE THREAD

**Issue by seattledeveloper** [Komodo/KomodoEdit#1154]
### Short Summary

Please refer to screenshot below.  Search again (Y) in the search results tabs (A, B, C), doesn't remember the original context (directories) used in first search (X).
### Steps to Reproduce

Search in files for a certain directory (Tab A).  Search a second time using a different search term and directory location (Tabs B or C).  Go back to A and click the search icon in Y.  It will search in the latest directories used, not the directory first associated with original search.
### Expected results

It seems the context should be remembered.
### Actual results

The context is not remembered.
### Platform Information

Komodo IDE, version 9.3.2, build 88191, platform win32-x86. Built on Thu Dec 10 11:38:17 2015.
### Additional Information

![find-in-files-context-error](https://cloud.githubusercontent.com/assets/9749337/13711712/e5605bfc-e774-11e5-8cc6-3a0330883ecc.png)

**Comment by Weyfarere1** [comment]
Same with:
Komodo Edit, version 10.2.3, build 17708, platform macosx. Built on Tue Jul 11 21:58:40 2017.

The revert of the context is especially troublesome when performing Replace All and Save All operations. 

With the toolbar located at the bottom of the window, and the the Where option at the very bottom it is  difficult to manage. Personal preference would be locate optional toolbars in one place at the top where it would be easier to monitor.

**Comment by seattledeveloper** [comment]
I would like to re-open this issue.  I just confirmed with Komodo IDE, version 11.0.2, build 90813, platform win32-x86. Built on Mon Dec 04 08:56:02 2017 that this behavior still exists.

**Comment by cgchoffman** [comment]
The behavior in the original ticket is not possible any more.  

> Go back to A and click the search icon in Y

That icon is no longer clickable.  Please elaborate on why you think it still occurs.

**Comment by seattledeveloper** [comment]
I Just did that -- several times -- all with the same results.  Here's the steps to reproduce:

1. Use keys CTL+SHIFT+F to bring up find in files
2. Add text, select "Files" for Where, and chose a Directory to search
3. Use keys CTL+SHIFT+F to bring up find in files again
4. Add text, select "Files" for Where, and chose a Directory to search, *choosing a different directory*
5. Go back to the first tab
6. Go to Y and hit enter

This first tab with search the directory specified in step 4 above, not 2 as expected.  In fact, both tabs will search on the second directory until another one is chosen at the CTL+SHIFT+F step.

Hope this is helpful.

**Comment by cgchoffman** [comment]
I didn't see this behavior but i'll look again.

**Comment by WilkeJoel** [comment]
My issue with the Find/Replace is different. 

Using the Next/Last & Replace actions with Current Directory the panel remains open and the actions are not changed. 
If you use Replace All, the panel closes when it is done.
Then when you open it again to perform a similar function, the Find & Replace text are the same but the Where has reverted back to Open Files.
Given that it closes automatically, user expectation is that either all three inputs should remain the same as the last use or all three should revert back to its clean state.
My personal preference would be to have the panel remain open until I close it overtly.

**Comment by cgchoffman** [comment]
@WilkeJoel, you seem to have reported two different issues, neither of which are what this report is about.  Could you file a separate for your Toolbar location comment and another for you "**Where** field changes" comment?

**Comment by cgchoffman** [comment]
@WilkeJoel, to clarify, I know the title says "Where" context but that is not what the bug report talks about.  @seattledeveloper, developer is talking about the **Directory** field.  Am I correct, @seattledeveloper?

**Comment by cgchoffman** [comment]
Yep, I don't want to diagnose two different issue in one ticket so I'm asking for a new ticket if there is an issue with the **Where** field.  @seattledeveloper, I'm going to update the title.

**Comment by cgchoffman** [comment]
Oh btw, great original report and follow up.  I've thought that a couple times looking at this ticket.  Thank you for that.

**Comment by seattledeveloper** [comment]
You're welcome Carey.  Thanks for the kudos.  I appreciate that a tool that I use every day is being actively maintained and updated, and issues are taken seriously.  Ed
