### ISSUE TITLE
Main menu freeze

### ISSUE THREAD

**Issue by thunderamur** [Komodo/KomodoEdit#1155]
Just see video of the issue in youtube
https://youtu.be/DcJkUysCGrM

To reproduce the issue must be opened at least one file with the code!

Komodo Edit, version 9.3.2, build 16460, platform linux-x86_64
Ubuntu 14.04.4

**Comment by mitchell-as** [comment]
Hi, you'll have to press the Escape key and then you'll be able to move around menus again. This has come up before and I think it's an Ubuntu-only thing.
