### ISSUE TITLE
Show trackchanges and syntax issues in Minimap

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1157]
### Short Summary

Show trackchanges and syntax errors in Minimap.  This would make minimap a lot more useful.

**Comment by Freakmeister** [comment]
You don't even need code preview there. Trackchanges would be enough. Visual Studio have minimap like this and it is pretty useful feature.

**Comment by cgchoffman** [comment]
> You don't even need code preview there.

@Freakmeister are you talking about the Code side pane (View > Tabs & Sidebars > Code)?  That's not related to this ticket.  If you don't want to see the Code pane you can close the side pane using `Ctrl + Shift + C` (This assumes Code pane is showing as apposed to your toolbox...then you would press `Ctrl +Shift+ L`).

**Comment by Freakmeister** [comment]
@cgchoffman No, I'm talking about miniature code preview on minimap itself. Font on minimap is too small to understand anything and it takes space from editor. It's just usless feature. It would be better to have just trackchanges on scrollbar without code miniature. You can download free version of Visual Studio to see how they did this.

**Comment by cgchoffman** [comment]
Understood @Freakmeister.  I was confused as you used "code preview" to mean Minimap.  That's a different feature request, though similar.  Some people want the minimap and this is to make minimap better.  I do recommend you file a new enhancement request to show trackchanges in the scrollbar.  I agree it's a common and useful tool.  You might include syntax errors as well which I should I should have done for this ticket in retrospect.

**Comment by Defman21** [comment]
#574 - syntax issues.

**Comment by mitchell-as** [comment]
Closing in favor of #1887.
