### ISSUE TITLE
New UI: Open Files SCC actions are not files specific

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1161]
### Short Summary

SCC commands run from the Open Files context menu are run on project level.  Should be file specific in this context.

### Steps to Reproduce

Open Open Files pane
Right click a file and perform an SCC task on that file (revert, commit, add)

### Expected results

Action is done on that file

### Actual results

Komodo tries to do the action on the entire project

**Comment by mitchell-as** [comment]
This appears to be fixed in master. Only the "revert" option remains from the commands in the original ticket. All of the other options are file-specific and not project-specific.
