### ISSUE TITLE
OSX: Keybinding fails to disable fullscreen mode

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1162]
### Short Summary

I've added a keybinding for fullscreen mode on OSX.  It works fine to enable full screen mode but when pressed again Komodo does NOT come out of full screen mode.

### Steps to Reproduce

assign keybinding to full screen mode 
press it to put Komodo in full screen mode
Press it again to disable 

### Expected results

Komodo to leave full screen mode (confirmed that Windows does this)

### Actual results

Nothing happens

NOTE: Other keybindings no longer work.  For example, `Meta + ,` won't open the preferences after the full screen mode keybinding has been pressed.  Using the work around below fixes that.

###Workaround

Shift focus to some other program then back to Komodo.  The keybinding will now work.  Also the menu View > Full Screen will work

**Comment by Naatan** [comment]
Do these steps give the expected result on 9.3?

**Comment by cgchoffman** [comment]
Yes.  I have to change the default (current default has been usurped by an OS level binding) but it toggles full screen properly on 9.3.

**Comment by Naatan** [comment]
Can you repro it when using native window decorations?

**Comment by cgchoffman** [comment]
...I can't reproduce this any more...You fixed it!  I'm going to close.  I'll reopen if it happens again.

**Comment by Naatan** [comment]
With the power of my MIND!
