### ISSUE TITLE
Commando ignores exclude filters

### ISSUE THREAD

**Issue by hobbsd** [Komodo/KomodoEdit#117]
This function wasn't working for me after an upgrade from KE8.5, so I uninstalled KE9, cleaned the registry (this is on Win7), renamed the profile folder, and then installed KE9. So it has the application default exclude filters (with `__pycache__`, `.hg`, etc.), and my freshly-created project file has the same filters, but Go To Files still searches those excluded locations.

**Comment by Naatan** [comment]
I'm not able to reproduce this. Are you using a Project? Can you ensure the Project is loaded?

**Comment by hobbsd** [comment]
I am using a Project, and it's loaded. I'm experiencing this issue on both of my Win7 machines. The exclude filters are working for the Places sidebar, just not Go To Files.

**Comment by Naatan** [comment]
@cgchoffman can you reproduce on Windows? It works fine for me on linux.

**Comment by cgchoffman** [comment]
Sorry for the delay.  Yes I can repro this on Windows.  Don't need a project open.

**Comment by Naatan** [comment]
Another one with the issue: http://forum.komodoide.com/t/commando-and-ignored-files/1488/4

Seems to be windows only.

**Comment by cyberbit** [comment]
:+1: Same issue here for me. Otherwise flawless functionality.

**Comment by cgchoffman** [comment]
This is likely issue #94.  No point in keeping this open.  It can be re-opened if fixing issue #94 doesn't resolve this.

**Comment by cgchoffman** [comment]
Oops sorry folks!  Wrong ticket.
