### ISSUE TITLE
Section list wrongfully thinks it's inside functions

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1171]
### Short Summary

Komodo is showing the wrong function name in the section list.

### Steps to Reproduce

Open the following file and put your caret on the linked line:

https://github.com/Komodo/KomodoIDE/blob/master//src/chrome/komodo/content/sleuth/sleuthResultsTab.js#L951

### Expected results

The section list shows the `updateTestPlanMenu` function

### Actual results

The section list shows the `getElementById` function

### Additional Information

The code browser pane highlights the right function

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoIDE/commit/7ef8a4d6c2c42a48079bf9dbcdd20fb8b8db56c2
