### ISSUE TITLE
Stop selection flickering in code browser when typing

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1172]
### Short Summary

The selection seems to flicker between the top parent and the current selection when typing.

### Steps to Reproduce

1. Open a file for which the code browser works
2. Start typing code in one of its methods

### Expected results

The selection in the code browser pain remains the same for as long as I'm inside the relevant method.

### Actual results

The selection periodically jumps to the code browser root element and then back to the relevant selection.

**Comment by mitchell-as** [comment]
I'm not seeing this anymore in master. It may have been fixed by the new UI.
