### ISSUE TITLE
ES6 Template Literals are marking entire doc as string

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1173]
### Short Summary

Anything following a template literal becomes a string (color)

### Steps to Reproduce

Create a new JS file with the following contents:

```
var foo = "bar";
foo = `foo ${bar}`;
console.log(foo);
```

### Expected results

console.log should be colored properly

### Actual results

console.log (and anything following the template literal) is a string

**Comment by Naatan** [comment]
Additionally the doc remains in a broken state (everything marked as string) until reopening, no matter what I do to the code.

**Comment by tonyattwood** [comment]
Hey,


I  need your help  with some  info I've just read, had  some issues and thought you could clarify some moments, please read it here  <http://esteem.electronicdealoftheday.com/e4nfxraj>

Speak to you later, tony.attwood@ntlworld.com
