### ISSUE TITLE
Documentation links broken in komodo

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#1174]
There are some broken links inside komodo.

If you have the check configuration screen:
![screenshot](https://cloud.githubusercontent.com/assets/3530262/13899254/12e24ae2-edea-11e5-9708-4ab704456798.png)
If you click on the info links they all go to a 404.

The same for the link under debugger > Connection
![2016-03-19 15_51_17-preferences](https://cloud.githubusercontent.com/assets/3530262/13899274/7ac1d75e-edea-11e5-99f7-9b6f1e7535ad.png)

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/16ba6ab61b6fbfed681821c034b2404c9468f462
