### ISSUE TITLE
relative imports/includes fail when linting

### ISSUE THREAD

**Issue by belonesox** [Komodo/KomodoEdit#1175]
### Short Summary
Let is consider sample FooBar module in Python
https://github.com/belonesox/foobarpy/blob/master/mods/foom/foom.py

with some relative imports.
If we call 
pylint foom.py
— no problem with relative imports.
If we use Komodo IDE/Komodo Edit 
we have Pylint errors like 
Ln: 7, pylint: E0401 Unable to import '#iw6prl.foo2' (ERROR)

### Steps to Reproduce
* Clone https://github.com/belonesox/foobarpy
* Open mods/foom/foom.py in Komodo IDE/Komodo Edit
* Enable Pylint syntax checking in Preferences

### Expected results
No errors in import, 
try just run 
pylint foom.py
 — should be no import errors.

### Actual results
![d](https://cloud.githubusercontent.com/assets/1609739/13907028/f01bb7de-eef5-11e5-9320-6ebd3f444091.png)

Ln: 7, pylint: E0401 Unable to import '#iw6prl.foo2' (ERROR)

### Platform Information

*Komodo Edit or IDE?* 
Komodo IDE 9.3.2
Komodo Edit 9.3.2
*Komodo Version?* 9.3.2
*Operating System (and version)?* 
Linux, Windows 7

### Additional Information
Looks like the problem Komodo run pylint on some temporary file somewhere,
and that this problem is rather old (https://community.activestate.com/node/9417 + bugs in closed bugzilla products).

I hope the problem should be finally fixed (I am tired to set "pylint: disable" for every relative import).

 -- eg. Error logs, screenshots, workarounds --

### Dev Edit

This will affect any linter that supports relative imports.

**Comment by belonesox** [comment]
Tracing pylint calls I see, that Komodo use temporary filename in some temp dir for saving unsaved text and pylint checking. 
Of course, this is wrong way, any relative imports will be "false negative".

**Comment by Naatan** [comment]
Seems we may finally have a test case for https://github.com/Komodo/KomodoEdit/pull/14

@belonesox could you comment on Todd's statement?

> As far as I understand, in Python it is illegal to use a relative import to refer to modules located in a different directory on the filesystem. (Moreover, import .some is also an illegal statement.) Therefore, your attempt to import modules.first.some via from .some import ... in a file not located in modules/first is invalid Python.

**Comment by belonesox** [comment]
>@belonesox could you comment on Todd's statement?

It is not true.
https://www.python.org/dev/peps/pep-0328/

«from ...xxx import yyy» syntax works for Python 2 (since 2.5) and Python 3, and even supported by pylint checker.

**Comment by Naatan** [comment]
@mitchell-as can you look into integrating https://github.com/Komodo/KomodoEdit/pull/14 ?

**Comment by mitchell-as** [comment]
@Naatan yes I can, but that will not fix this ticket, which has nothing to do with #14. (Linting vs. codeintel).

**Comment by Naatan** [comment]
oh sorry, you're right. 

@belonesox have you tried running pylint manually on the file in question?

**Comment by mitchell-as** [comment]
@belonesox I'm having trouble reproducing this on an Ubuntu 14.04 Linux machine.

0. I've installed pylint (v1.1.0) for Python 2.7.6.
1. I've enabled Pylint checking for Python files without specifying a pylintrc file.
2. I git cloned the project you suggested and opened the file in question (but not as a project).
3. Pylint shows warnings for "Unused import VERSION" and "Unused import "CONSTA".

**Comment by mitchell-as** [comment]
Reproduced in Python3 with pylint 1.5.4.

**Comment by belonesox** [comment]
Thank you, but I should not that this is only workaround, such way can not handle relative wildcard imports, and "Komodo pylint" will raise errors like that:

![d](https://cloud.githubusercontent.com/assets/1609739/13946595/a0b0f90c-f026-11e5-856e-5574fe5f7d65.png)

( https://github.com/belonesox/foobarpy/blob/master/mods/foom/foom2.py, syntaxically correct, OK for pylint running on same directory )

**Comment by mitchell-as** [comment]
Thanks for the additional case. It looks like we'll have to come up with something more robust.

**Comment by Naatan** [comment]
This could be useful:

```
    --init-hook=<code>  Python code to execute, usually for sys.path
                        manipulation such as pygtk.require().
```

To alter the cwd.

**Comment by mitchell-as** [comment]
Nope, using `--init-hook` to set the cwd is no good. I'm pretty sure that in this case (with relative imports) the linter needs to be run on the file directly as opposed to on a temporary file. I think Pylint is getting confused with module names:

```
[2016-06-20 12:58:32,027] [DEBUG] koPythonLinter: stdout: '************* Module #O2PYXI\nC0103: 1,0: Invalid module name "#O2PYXI"\n [...]
```

(That weird module name is the name of the temporary file.)

If I run Pylint directly on the file in its directory, I get the expected results. However, none of our linters run directly on files -- they always create temporary files and lint those. I'm not sure of the ramifications if we linted files (or at least Python files) directly. @Naatan what do you think?

**Comment by tonyattwood** [comment]
Hi,


Have you already  read my  new article? I  think  that's what you need at the moment, please, read it  here  <http://favor.amcatinternational.com/e4voad>

tony.attwood@ntlworld.com

**Comment by mitchell-as** [comment]
@Naatan  ping. I see you upped the severity, but didn't respond to my question.

**Comment by Defman21** [comment]
I think that `require_relative` in Ruby also is being covered by this issue.

**Comment by Naatan** [comment]
Ramifications I can think of:

 - linters could write temp files relative to the file they are linting, this would be bad
 - dirty files should not be saved to perform linting (at least not in the same file path)

I would suggest adding a pref that lets people say "save temp linting files in the same directory", but given the miniscule amount of people that actually customize these prefs I'm not convinced this is worth the effort.

I'd imagine we could address this more intelligently if and when we write our own linters?

**Comment by mitchell-as** [comment]
While we'd have more control over this if we wrote our own linters, it would likely be a big undertaking.

I think at this point we can conclude there is no way of catching every case of relative imports. So far it looks like we only cannot handle wildcard relative imports. I'd recommend just putting `# pylint: disable=WXXXX` at the top of the source, where `XXXX` is the number of the specific warning from pylint.
