### ISSUE TITLE
Allow blow selection when folding is off

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1176]
### Short Summary

I would like to use block selection, but I never ever used the fold margin so I have it turned off. Unfortunately this means I can't use block selection, because.. well I'm not sure why the two should be connected? I'm sure there is a reason, which is not to say it can't be done.

### Steps to Reproduce

1. Turn off the fold margin
2. Make a block selection

### Expected results

Block selection is made

### Actual results

Komodo shows an alert "Block-selection doesn't work when folding is off."

**Comment by mitchell-as** [comment]
As we discussed internally, block selection is intimately tied with fold points determined by the lexer. We can't have the "block select" as a we know it function without those fold points.
