### ISSUE TITLE
Cannot disable syntax checking for individual file.

### ISSUE THREAD

**Issue by belonesox** [Komodo/KomodoEdit#1177]
### Short Summary
Komodo has individual file preferences overrides global preferences.

I use backgroud syntax checking for my projects (trying that there will be no annoing underline marks),
but sometimes I have to open files from another projects (there contributors dot not care about pylint at all).

I expected that possible to disable syntax checking for such individual files, but it does not work.

![d](https://cloud.githubusercontent.com/assets/1609739/13946976/fe6b924e-f028-11e5-8e13-bccd348fc9f5.png)

### Steps to Reproduce
* Grab project https://github.com/belonesox/foobarpy/
* open mods/foom/foom2.py
* disable syntax checking in The File Preferences

### Expected results
* No syntax marks, clear, syntaxically colored code.

### Actual results
![d](https://cloud.githubusercontent.com/assets/1609739/13946851/2923f6c6-f028-11e5-919d-b0f2fdf39b67.png)

### Platform Information

*Komodo Edit or IDE?* 
Komodo Edit and Komodo IDE

*Komodo Version?* 
9.3.2

*Operating System (and version)?* 
Linux and Windows

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by mitchell-as** [comment]
This appears to have been fixed in master. I am able to turn on editor-wide syntax checking for Python, but turn it off for specific files, particularly the `foom.py` file mentioned in the steps.
