### ISSUE TITLE
Remote Files Dialog: Missing icons for goback, up-one-folder, create folder, reload

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1178]
### Short Summary

I see then in the DOM inspector but the icons don't appear and nothing appears in it's place

**Comment by Naatan** [comment]
Can you describe how I get to the dialog in question?

**Comment by cgchoffman** [comment]
Places Gear > Open remote directory.  That will get you the dialog.

**Comment by mitchell-as** [comment]
This has been fixed. I see the 4 icons now.

**Comment by cgchoffman** [comment]
Ahh thanks @mitchell-as: forgot to reference this ticket https://github.com/Komodo/KomodoIDE/commit/b093bf42801d645626483fd3ed84accd3a11984c
