### ISSUE TITLE
Replace window closed when changing file in "replace in open files"

### ISSUE THREAD

**Issue by oehhar** [Komodo/KomodoEdit#1179]
### Short Summary

In "replace in open files", the replace window is incorrectly closed when a match is found in another file.

### Steps to Reproduce

   *   Open two panes with the contents "A". (Ctrl-T - new file A)
   *   Press CTRL-Shift-H to open the replace dialog
   *   Find: "A", Replace: "B", Where: Open files
   *   Press the down arrow icon in the search dialog. The "A" in the current tab is selected
   *   Press "Replace". The "A" in the current pane is replaced. The second pane is shown. The "A" is selected. The replace dialog is closed

### Expected results

Do not close the replace dialog

### Actual results

The replace dialog is closed incorrectly

### Platform Information

   *   Komodo IDE
   *   9.3.2
   *   Windows 10 64 BIT GER

### Additional Information

![komodo_replace](https://cloud.githubusercontent.com/assets/12413997/13986239/a5136576-f101-11e5-8f1e-40d3c11ea143.png)

**Comment by mitchell-as** [comment]
This has been fixed in master.
