### ISSUE TITLE
KO9 shared library init errors

### ISSUE THREAD

**Issue by lorenrosen** [Komodo/KomodoEdit#118]
Ubuntu12.10
When I start Komodo Edit (via the command line) I get the errors
LoadPlugin: failed to initialize shared library /home/loren/.mozilla/plugins/nppdf.so [/home/loren/.mozilla/plugins/nppdf.so: wrong ELF class: ELFCLASS32]
LoadPlugin: failed to initialize shared library /usr/lib/mozilla/plugins/nppdf.so [/usr/lib/mozilla/plugins/nppdf.so: wrong ELF class: ELFCLASS32]

It does start after that, though it sounds like some plugins might not work. FWIW the shared libraries referred to do exist.

**Comment by Naatan** [comment]
It seems you downloaded the 32bit version of Komodo but are using a 64bit OS. Please download the 64bit verison.

**Comment by lorenrosen** [comment]
Pretty sure I downloaded the right one. But after deleting and reinstalling komodo several times, I stopped getting the error messages.

**Comment by lorenrosen** [comment]
Also, note this is a plugin, so perhaps the plugin install downloaded 32 bit libraries?

**Comment by Mook-as** [comment]
Yeah, the messages look like they're trying to (and failing) to load 32 bit plugins in a 64 bit process.  For example, see [first result](http://askubuntu.com/questions/332526/) on a random search for `ELFCLASS32`.

You can probably ignore the warning unless you actually want to load those plugins in Komodo for some reason; in that case, you'll need to locate the 64 bit equivalents.  `nppdf.so` is (probably) the Adobe Acrobat Reader browser plugin; you _probably_ don't need it inside Komodo (and, outside Komodo, Firefox is more likely to be using their JS-based PDF reader instead).
