### ISSUE TITLE
Project list reset at every startup

### ISSUE THREAD

**Issue by cbertozzi** [Komodo/KomodoEdit#1180]
### Short Summary

The entire project list reset every time system reboots

### Steps to Reproduce

- open one or more projects;
- close komodo Edit and reboot system;
- reopen Komodo Edit;

### Expected results

Project list are popolated with projects; 

### Actual results

No project listed;

### Platform Information

Komodo Edit, version 9.3.2, build 16460
OS X Yosemite (version 10.10.5)

**Comment by Naatan** [comment]
Can you try disabling Prefs > Places > Allow multiple open projects.

**Comment by cgchoffman** [comment]
I think this is actually Prefs > Appearance > Most Recently Used: Number of Projects

**Comment by Naatan** [comment]
Ahh right, I knew it was somewhere in there :)

**Comment by cbertozzi** [comment]
Thanks for the answers, but I think that the ploblem is elsewhere, that's my settings:

![screen shot 2016-03-24 at 09 46 09](https://cloud.githubusercontent.com/assets/492083/14012331/6c5985c2-f1a5-11e5-8d12-11bf3da6c21a.png)

![screen shot 2016-03-24 at 09 45 53](https://cloud.githubusercontent.com/assets/492083/14012336/713492d0-f1a5-11e5-8fa4-e84f19c601f9.png)
