### ISSUE TITLE
Sections scope does not see nested rules (SCSS)

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1184]
### Short Summary

Sections scope does not see nested rules in SCSS.

### Steps to Reproduce

```scss
.root {
  .nested { color: red; }
}
```

Open Sections scope and try to find `.nested` in it.

### Expected results

I can see something like `.root > .nested`

### Actual results

Only `.root` is visible

### Platform Information

*Komodo Edit or IDE?* : IDE
*Komodo Version?* : version 9.3.2, build 88191
*Operating System (and version)?* Ubuntu 15.10

**Comment by Naatan** [comment]
Already handled in #1093 :)

**Comment by Defman21** [comment]
Ahh, I thought that this fix only fixes Code pane, but if it fixes Commando Section Scope as well, then cool! :)
