### ISSUE TITLE
unable to open the file: 'quickstart.xml#view-quickstart'

### ISSUE THREAD

**Issue by ahmadaidin** [Komodo/KomodoEdit#1185]
### Short Summary

unable to open the file: 'quickstart.xml#view-quickstart'
### Platform Information

Kodomo Edit - 9.3.2 - 16460

windows 10 pro
### Additional Information

 -- eg. Error logs, screenshots, workarounds --
![screenshot_15](https://cloud.githubusercontent.com/assets/9548073/14061720/cf8aabb0-f3b9-11e5-8c76-984e71037d0a.png)

**Comment by Naatan** [comment]
You seem to have a corrupted profile, please try resetting it:

http://docs.komodoide.com/Troubleshooting/How-do-I-Start-Komodo-with-Default-Settings
