### ISSUE TITLE
Correlative replacement

### ISSUE THREAD

**Issue by stramin** [Komodo/KomodoEdit#1188]
This is a request (Enhancement)

We all made a code like this:

```
file1 = field.txt
file2 = config.ini
file3 = opt1.bat
file4 = opt2.bat
file5 = opt3.bat
...
file56 = errors.log
file57 = debug.log
```

I think should be useful to have a tool to make correlative codes like this, like a "for", something like the current replace tool, with inputs like these:

From: 1 (initial number, start)
Step: 1 (incremental step)
To: 57 (last number, end)
Text: file# = (texto to write, the # symbol will be replaced by number)

![image](https://cloud.githubusercontent.com/assets/17409281/14111542/83a61196-f5a1-11e5-9e7f-35674f989a9e.png)

this could be useful for many tasks, like ini files, SQL queries, arrays, etc.

```
DELETE FROM table WHERE id=45642
DELETE FROM table WHERE id=45643
DELETE FROM table WHERE id=45644
DELETE FROM table WHERE id=45645
```

```
$array[23]=banana;
$array[24]=apple;
$array[25]=carrot;
$array[26]=coffee;
$array[27]=non-foo-non-bar-variable-here;
```

regards!

**Comment by mitchell-as** [comment]
Hi, I think a macro coupled with a userscript would be more appropriate for you. In envision something like:

1. Create a userscript that increments the number at the current position.
2. Record a macro that runs that userscript and goes down to the next line.
3. Move to the first number to change and execute the macro.
4. Repeat until you reach the last number to change.
