### ISSUE TITLE
Create iterative "block selection" mechanic

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1189]
Take the following bit of code:

```
<foo>
  <bar>Foobar!</bar>
</bar>
```

If I have my cursor in foobar I'd like to be able to execute a command which would select the text inside the node (ie. `Foobar!`), then when I execute the same command again it would select the next block, ie. `<bar>Foobar!</bar>`, then when executing it again the next block up from that (now we're up to `<foo>`), etc.

XML is just an example, but this should work for any language. This could work simply by selecting the current "colored" block.

When we implement this we'll also have to come up with a better name than "block selection", or perhaps we need to rename the current "block selection" command to something else as it never does what I expect it to do.

Edit: JS sample:

```
if (true)
{
    for (let x=0;x<10;x++)
    {
        console.log("Hello there!");
    }
}
```

Starting my caret at "Hello there!" each iteration should select code as follows:

```
Hello there!
```

```
"Hello there!"
```

```
("Hello there!");
```

```
log("Hello there!");
```

```
.log("Hello there!");
```

```
console.log("Hello there!");
```

```
    {
        console.log("Hello there!");
    }
```

etc.

Writing this down made me realize one thing: it should not just trigger on colored code but also on delimiters, otherwise it would select too much in some cases. Perhaps it should simply work JUST on delimiters?

The idea is that you can use this pretty much anywhere though, this should not rely on codeintel as it would make the feature too limited.

**Comment by mitchell-as** [comment]
I'm not even sure where to begin with this one. Yeah it would be cool if my IDE could read my mind what blocks I want to select, but this feature is incredibly language-specific and doing it right without any sort of codeintel is borderline impossible. Perhaps I'm basing this assessment too much on my knowledge of language syntaxes. If you have a simple set of rules that a language-agnostic algorithm can follow, then please share. (Do keep in mind keyword languages like Ruby (do/end) and Python's indentation rules considering that comments and strings do not necessarily have to adhere to indentation rules.)

**Comment by Naatan** [comment]
I think you are over-thinking this one again. This should not be super intelligent, it should just be a command that extends the selection based on certain delimiters, the end. No language specific features, no codeintel awareness. 

The problem with something super intelligent isnt just that it is error prone, but it tends to also work in ways that aren't very obvious to the end-user. Making a feature like this "dumb" helps both in terms of maintenance as well as making it a simple and easy to use feature for users.

It's the same thing as with multi-caret, most users just want to select multiple instances of a word, that's it. Nothing else. Same goes here, I just want to extend the selection to the next set of delimiters, that's it.

**Comment by mitchell-as** [comment]
Okay, well your samples seemed to indicate you wanted more than just the delimiters you were musing about towards the end of the ticket. I'll work on block-selecting between delimiters.

**Comment by cgchoffman** [comment]
Most editors I tested during the keybinding saga had this command and it was pretty awesome.

**Comment by Naatan** [comment]
Sorry, what I meant towards the end is that I had realized that simply using scintilla colors as the delimiters would not suffice. So we should just define our own delimiters and disregard how scintilla is coloring things.
