### ISSUE TITLE
KO9 top of screen

### ISSUE THREAD

**Issue by lorenrosen** [Komodo/KomodoEdit#119]
Ubuntu 12.10
This may be an artifact of having both 8 and 9 installed (and invoking the latter via the command line) but when I run 9 at the top of the screen it says "Komodo Edit 8".
(Actually the older install is 8.5, and says "Komodo 8.5" at the top.)

**Comment by Naatan** [comment]
I cannot reproduce this. Did you install using the version available from our website?

**Comment by lorenrosen** [comment]
Figured out what was happening.
The install left a vestigial launcher for supposedly komodo 8. But what the window manager thought was 8 (and gave the appropriate window wrapping) was actually 9.
Fixed this by moving the komodo 8 folder from ~/Desktop, logging out and then in again, starting 9 from the command line, and locking that icon to the launcher. Also had to delete the reference to 9 from my desktop (so it was just in the launcher).

**Comment by Naatan** [comment]
Good to hear you figured it out :) Thanks for letting us know what the solution was.

**Comment by lorenrosen** [comment]
Should add that the old komodo install wasn't vestigial. (As is reasonable, it still remained.) But I don't know why a launch icon didn't appear for the new install (although it's possible it did but I overlooked it), nor why the supposed launch icon for komodo 8 launched komodo 9. This was before I changed my PATH environment variable.

**Comment by lorenrosen** [comment]
Another thing to add -- for other reasons I started Komodo 8.5 via the command line. Nevertleless the Ubuntu launcher (which has an icon for komodo 9) shows komodo 9 as running, though the window title bar says 'Komodo Edit 8.5'.
