### ISSUE TITLE
New UI: OSX: Native decorations don't transition properly when enabled/disabled

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1192]
### Short Summary

If you start komodo with with native decorations enabled and you disable them, the OS Close, Maximize and Minimize buttons will remain.  They do NOT appear if you enable them when you've started KOmodo with them disabled.

### Steps to Reproduce

Enable native window decorations
Disable native window decorations

### Expected results

OS buttons in top left corner of window to go away

### Actual results

They do not go away

**Comment by Naatan** [comment]
Are you up to date? I recently pushed a commit that should fix this.

**Comment by cgchoffman** [comment]
I can't tell.  When I enable native window decorations now the OS buttons don't appear at all and you can't click/drag the window.  Doing a pull and build to retest.

**Comment by cgchoffman** [comment]
I think the actual issue here is that the transition doesn't happen.  Or it partly happens.  I"m up to date on Master.  I"m updating the ticket to be more clear.

**Comment by mitchell-as** [comment]
I cannot reproduce this on Linux at least.

**Comment by Naatan** [comment]
OSX doesn't support changing this on the fly, you have to restart the app. I had a warning that showed this but it appears I accidentally deleted it. Will have to add it again.
