### ISSUE TITLE
Can't see scroll bars in main window on OSX 10.5.5

### ISSUE THREAD

**Issue by dyguk** [Komodo/KomodoEdit#1197]
### Short Summary
Using Komodo Edit, version 9.3.2, build 16460, on OSX 10.5.5 I am not seeing vertical or horizontal scroll bars in the main window. I don't know if this is a bug or a setting I'm missing, so apologies if I've put this in the wrong place. I do see the scroll bars in the various Preferences windows. I am using the normal Mac default settings that only show scroll bars when you start scrolling.

All other programmes and windows are functioning normally.

### Steps to Reproduce
Every time on my Mac...

### Expected results
Should see scroll bars

### Actual results
Don't see scroll bars

### Platform Information

Komodo Edit, version 9.3.2, build 16460, 
on OSX 10.5.5

### Additional Information

 -- eg. Error logs, screenshots, workarounds --
![image](https://cloud.githubusercontent.com/assets/8697558/14139177/3812e156-f6bd-11e5-8041-08a8aab4427b.png)

**Comment by mitchell-as** [comment]
I'm a bit confused. You say you have the OSX setting to show scrollbars only when scrolling, yet you expect to see scrollbars in Komodo's editor view all the time (i.e. without scrolling)? Let's ignore the fact that you see scrollbars in other places in Komodo.

There should be some scrolling options in Edit > Preferences > Appearance, particularly an option to always show scroll bars. Does that give the desired result?

**Comment by dyguk** [comment]
Thanks mitchell-as. Problem solved. In Preferences > appearance there is an option for 'Skin Editor Scrollbars'. I had that turned on... it never occured to me to turn it off... but when I did turn uncheck it the scroll bars have appeared in exactly the way you would expect on OSX.

Sorry for the confusion - I was only wanting to see scroll bars when scrolling. All is good now.

Maybe it's worth rephrasing that option in future builds?

**Comment by mitchell-as** [comment]
Awesome, thanks for letting me know. I think we will address the phrasing you mentioned in Komodo 10.
