### ISSUE TITLE
Publishing: Allow to overwrite remote file on Publishing tool

### ISSUE THREAD

**Issue by rimvydasr** [Komodo/KomodoEdit#1198]
### Short Summary

Feature Request: allow to overwrite remote file on Publishing tool when remote file was changed.

### Steps to Reproduce
edit remote file on ftp server.

### Expected results

chose to overwrite local file or reupload local file and lose changes

### Actual results
 allows only to download remote file.

### Platform Information

KomodoIDE
9.3

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by cgchoffman** [comment]
Open Tools > Publishing > yourConfig, select the conflicting file > right click > upload

Unless you mean #548

**Comment by rimvydasr** [comment]
it is similar to #548.

in my case local file is not changed, thus there is no "confilict" and "resolve confilict" menu is disabled.

i need to force overwrite remote file when local file is not changed.

**Comment by cgchoffman** [comment]
ahh you didn't say that in the original post.  Could you elaborate on this please?  Is this for only one file?  Are you asking for a button for "push all (no matter what...even if there are no changes)"?  Please provide a full use case so we know exactly what you're asking for.  This is a feature request after all.

**Comment by rimvydasr** [comment]
two use cases:
1. some file editors changes file timestamp when you open it for view only and there is no real changes on file, tool still considers remote file as modified.
2. when someone modifies file on server and i need to reject his changes by overriding file.
yes, this is for single files.

i think the best way for implementation would be to simply enable "resolve conflict" menu on right click for selected files.

"push all" button would be useful for initial synchronizations or as workaround for #782

**Comment by cgchoffman** [comment]
> "push all" button would be useful for initial synchronizations or as workaround for #782

That's covered #148

**Comment by cgchoffman** [comment]
Usecase 2 is done: https://github.com/Komodo/KomodoIDE/commit/0b0097f5c5ec69138f559e1a877ac7724b00254c
*Right click file > Publishing > Force Push*

Case 1 is covered by #148
