### ISSUE TITLE
PHPUnit doesn't work in Komodo IDE 9

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#120]
http://forum.komodoide.com/t/how-to-use-phpunit-with-komodo/1420

**Comment by cgchoffman** [comment]
As we discussed in the forum post, I'm unable to repro on Windows. It's working fine for me.

**Comment by Defman21** [comment]
The problem solved by installing PHPUnit via apt-get and adding `/usr/bin/php` to the `include_path` in file `/etc/php5/cli/php.ini` (`include_path=".:${USER}/pear/share/pear:/usr/share/php"`)
