### ISSUE TITLE
Remote Debugger Enhancement

### ISSUE THREAD

**Issue by tprocter** [Komodo/KomodoEdit#1200]
### Short Summary
Include some branding or distinctive output when starting the perl debugger using the komodo perllib to make it more obvious when the komodo libraries are not active.

Having spent some time troublshooting the komodo debugger only to realize it wasn't komodo at all (http://forum.komodoide.com/t/perl-remote-debug-hangs-on-connecting/2599/3), this suggestion might help to short-circuit that.

### Platform Information

*Komodo Edit or IDE?*   IDE
*Komodo Version?*  currently using: 9.3.2
*Operating System (and version)?*  Any (found on linux to Windows 7 remote debugging session)

**Comment by Naatan** [comment]
Could you provide the steps you are taking and clarify at which point you want to have visual feedback?

**Comment by tprocter** [comment]
For example:

after setting up PERL5LIB=/path/to/perllib and PERLDB_OPTS="RemotePort=<my_ip>:port"

running> perl -d test.pl
could open with:
Komodo Perl Debugger 9.99

before any program output.

--> this is just an idea.  I'm not sure if there would be unwanted consequences.

**Comment by mitchell-as** [comment]
Thanks. We'll have to look into this and see if there will be adverse effects.

**Comment by mitchell-as** [comment]
I've looked into this and I'd prefer not to add a banner to the debug stdout for Perl. We don't do this for any other language either. Instead if you'd like to verify Komodo's Perl debugger is functioning properly, you can go to Edit > Preferences > Languages > Perl > Debugger Logging > Enable Debugger Log. Then start debugging and take a look at the `perl5db.log` that is written. If it is populated without error, that means Komodo's Perl debugger is functioning properly.

Our other languages also have debugger logs that can be enabled and disabled.
