### ISSUE TITLE
key shortcuts in split view mode don't work across panes

### ISSUE THREAD

**Issue by dch** [Komodo/KomodoEdit#1202]
### Short Summary

![splits](https://i.imgur.com/684DU8N.png)

In normal mode, cmd-1...8 switch between the different panes as expected.
When switching to split view mode, the keyboard shortcut assigned to the tab changes to being split specific instead of the previous keystroke.

### Steps to Reproduce

- start in normal (non-split) view
- open 8 tabs (8 isn't necessary but it matches the screenshot)
- use cmd-1..8 to switch between them seamlessly
- enable split view on a few tabs
- try cmd-1..8 again to switch between them

### Expected results

starting in the left split pane:

- cmd-1 takes me to first tab in left split pane
- cmd-8 takes me to last tab in right split pane

starting in the right split pane:

- cmd-1 takes me to first tab in left split pane
- cmd-8 takes me to last tab in right split pane

### Actual results

starting in the left split pane:

-  cmd-1 takes me to first tab in left split pane - OK
- cmd-8 takes me to last tab in right split pane - FAIL

starting in the right split pane:

- cmd-1 takes me to first tab in left split pane - FAIL
- cmd-8 takes me to last tab in right split pane - FAIL

cmd-1 takes me to the *first* tab in the *right* split pane. This doesn't match the intuitive flow of switching to the other pane automatically.

### Platform Information

```
Komodo IDE, version 9.3.2, build 88216, platform macosx.
Built on Wed Mar 2 01:36:40 2016. 
El Capitan
```

### Additional Information

![splits](https://i.imgur.com/684DU8N.png)

From an editor workflow perspective, it makes most sense to allow cmd-1..8 to function as in non-split tab mode, i.e. it would seamlessly cross the split view barrier. It's very jarring to jump to split view, and need to remember a different set of tab numbers.

**Comment by Naatan** [comment]
What do you have CMD-1 through CMD-8 bound to? 

Also, it appears you're using a userscript or addon for the tab numbers?

**Comment by dch** [comment]
I repeated this with a blank profile (i.e. no extensions or custom bindings) and it still happens the same way:

cmd-1 takes you to the first pane in the active split view etc. The bindings are native.

I also checked this with rotated & unrotated splits, I'd not realised that horizontal splits are not the default.

The actual bound keys displayed above each tab are presumably part of a plugin so I'll need to track that down separately.

**Comment by Naatan** [comment]
> 
cmd-1 takes you to the first pane in the active split view etc. The bindings are native.

I'd still like to know the exact commands you have them bound to, please let me know what they are set to under Prefs > Keybindings.

**Comment by dch** [comment]
sorry for the delay @nataan. I am using a custom binding that would originally have been based off the first or 2nd generation of vi key bindings. The "General: Switch to Tab 1" is bound to Meta+1, and the sequence continues logically. This is the same as in defaults for 9.3.

**Comment by Naatan** [comment]
Hmm I think this is working by design. If I execute "Focus on Other split view" I can properly cycle through the tabs in that split. It makes sense to me that the tabs between the splits are not continuous especially considering that in some point in the future we'd like to let you have any number of splits (in any sort of configuration).

I'd suggest you set a binding to "Focus on Other split view" and get used to using that. I'm not convinced that this is something that needs to be changed. Let me know if you disagree, I will leave this open till then.

**Comment by dch** [comment]
I agree, considering if the splits can be arranged vertically or horizontally, a contiguous numbering sequence wouldn't make sense in both arrangements. Also yay for more splits in the future!

**Comment by tonyattwood** [comment]
Hello,

I just wanted to say how much I miss  you and share with you some important information, just read  it, you  won't  regret <http://favourite.practicaldefenseconcepts.com/e4bkw>


Speak to you later, tony.attwood@ntlworld.com
