### ISSUE TITLE
Some dialogs are opening with no backgroun

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1204]
### Short Summary

Effected dialogs I've found:
* Prefs
* Color Schemes
* DOM Inspector

This appears to be Windows only.  not seeing it on OSX.

**Comment by mitchell-as** [comment]
I'm pretty sure this has been fixed with the lack of alpha transparency of windows now. @cgchoffman do you still see this on master?

**Comment by Naatan** [comment]
Yep this is fixed.
