### ISSUE TITLE
new UI: Dialogs are not seperate windows in the Windows Taskbar

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1205]
### Short Summary

When you have K10 open on Windows now and you open additional dialogs they all overlap in the hoverover popup that the Windows taskbar provides. 

**EDIT:  Changed reproduction steps below**

Contrast against K9:
Open Komodo 9
Open prefs dialog
Open Color Schemes dialog
Hover over the K9 icon in the Windows Taskbar at the bottom of your screen
You should see 2 windows popup to select

K10:
Open K10
Open prefs
Open Color Schemes dialog
Hover over the K10 icon in the Windows Taskbar
You will only see one window pop and if you look close you can see that they are overlapping.

This could get painful for Windows users if dialogs lose focus and fall behind the main window.  There will be no way to bring them back other than to MOVE the window that is blocking

**Comment by Naatan** [comment]
That's because it's not using native windows decorations, short of updating Mozilla we cannot fix this. :\

I fear on WIndows the "no platform decorations" option should default to "No".

**Comment by cgchoffman** [comment]
I have native decorations on.

**Comment by cgchoffman** [comment]
This is bad if we're not going to fix this.  The broken use case is real and not useable in certain cases.

**Comment by Naatan** [comment]
Can you share a screenshot of the issue?

**Comment by cgchoffman** [comment]
Oh I think I see what's going on.  I might need to change the summary.  Native decorations aren't working on the dialogs but I have native decorations on.  So THAT is the issue.

**Comment by Naatan** [comment]
Is this still reproducible ?

**Comment by cgchoffman** [comment]
> Is this still reproducible ?

Nope.  Doesn't look like it.

**Comment by tonyattwood** [comment]
Hello,

I found a cool  site  with  some  great stuff for summer, I  thought  it may be  helpful to you too, here is the link  <http://follow.goutama.org/e4szf>

All the best, tony.attwood@ntlworld.com
