### ISSUE TITLE
New UI: Can't see bottom of Komodo window when full screen

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1206]
### Short Summary

If I go full screen on Windows I can't see the bottom of the Komodo window.  See screenshots below.
**Native Window Decorations are on.**

#### hidden icons and incremental find

![capture](https://cloud.githubusercontent.com/assets/655154/14188151/7be179be-f73b-11e5-8d90-df41a8028feb.PNG)

#### What I expect to see

![capture](https://cloud.githubusercontent.com/assets/655154/14188169/9d1cf8e2-f73b-11e5-875b-371bda64d938.PNG)

**Comment by cgchoffman** [comment]
I was just seeing this in my current editing sessions but re-sizing the window fixed it and the overflow out of view is gone and I can't reproduce it.

**Comment by Naatan** [comment]
This sounds really familiar ...

**Comment by cgchoffman** [comment]
This appears to be fixed due to the issue reported in #1329 so i'll just go ahead and close this.
