### ISSUE TITLE
Commando fails to find files using relative paths

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1208]
### Short Summary

yep, this one again.  I can't open files using relative paths in Commando
### Steps to Reproduce
1. I have my project file in `src` in the Komodo repo
2. I wanted to open the README.md in the repo root
3. I open COmmando and typed `..\` and I see the contents of the repo root, including **READEME.md**
4. I type `..\r` and everything disapears and I can't open the file

See screenshot/gif
### Expected results

Results to filter to **readme.md**
### Actual results

All results are gone
### Platform Information

Version: Master
Platform: Windows 10
### Additional Information

![commando-filepaths](https://cloud.githubusercontent.com/assets/655154/14216445/a654b518-f7fd-11e5-890b-f2092454d7b3.gif)

**Comment by Naatan** [comment]
Does a forward slash work? (Damn windows hippies!)

**Comment by cgchoffman** [comment]
No, but it's actually functioning slightly differently now. The list doesn't change when i type characters after the `\` or the `/`.
![commando-filepaths](https://cloud.githubusercontent.com/assets/655154/14221729/f6ad5a40-f81d-11e5-85af-23385ccf1938.gif)

**Comment by cgchoffman** [comment]
I hate this ticket.  It pops up periodically then just seems to solve itself.  I can't reproduce this anymore and it's been working for a while now.  Just gonna close.
