### ISSUE TITLE
Windows cursor bug

### ISSUE THREAD

**Issue by tcdaly** [Komodo/KomodoEdit#121]
I'm experiencing an intermittent bug in version 8.5.4 in Windows 7.

The pointer will turn into a rotating circle (hourglass) when the cursor is over any area of the screen apart from the projects/toolbox pane.  The mouse/pointer otherwise continues to operate the program normally.  It is not clear what triggers the bug.  Restarting the application cures it.

Build info: version 8.5.4, build 14424, platform win32-x86. Built on Thu Aug 14 00:30:5

**Comment by Naatan** [comment]
Can you reproduce this issue on Komodo 9?

**Comment by tcdaly** [comment]
I've now upgraded to version 9.  I have not experienced the bug yet, but will let you know if I do.

**Comment by tcdaly** [comment]
This has now occurred in v9.  It happens when opening a specific project in my project list (but not the others).

Komodo Edit, version 9.1.0, build 15798, platform win32-x86.
Built on Sat May 30 06:10:24 2015.

**Comment by Naatan** [comment]
Interesting, could you share the .komodoproject file? Feel free to censor out project name, path.

**Comment by tcdaly** [comment]
<?xml version="1.0" encoding="UTF-8"?>

<project id="8c195b93-e986-4ff8-9b39-1e07afef6747" kpf_version="5" name="redbox.komodoproject">
<preference-set idref="8c195b93-e986-4ff8-9b39-1e07afef6747" id="project" preftype="project">
  <long id="prefs_version">1</long>
</preference-set>
</project>

**Comment by tcdaly** [comment]
It's an intermittent problem - sometimes it happens when the project is opened, sometimes it doesn't.  The project does contain a few large files of a few MB each.  That's the only thing I can think of that makes the project different from any other.

**Comment by Naatan** [comment]
Carey can you try to reproduce this when you have time (Mondays?). It seems fairly edge case so unless we can easily repro this without spending a ton of time we may just have to close this issue until clear steps to reproduce can be found.

**Comment by cgchoffman** [comment]
I've not been able to reproduce this and I don't think I've ever seen it either.  @tcdaly,  did you try deleting and recreating the project file from scratch?

**Comment by tcdaly** [comment]
No, but I will try doing that.   In your code, is there an event that switches the cursor from a pointer to a spinning circle, and likewise a circle back to a pointer?  Can you think of any circumstances in which the 2nd event would fail to trigger?

**Comment by Naatan** [comment]
Not to my knowledge, I think this is handled at a lower (OS) level.
