### ISSUE TITLE
Exiting Full Screen Mode on Windows Turns on Native Window Decorations

### ISSUE THREAD

**Issue by mitchell-as** [Komodo/KomodoEdit#1212]
### Steps to Reproduce

Start with no Native Window Decorations on Windows. Go into Full Screen Mode (F11) and then leave it. Now you have Native Window Decorations turned on. When right-clicking the titlebar and going to 'Customize' (toolbars), the Native Window Decorations is unchecked. I have to check and then uncheck in order to turn Native Window Decorations back off.

### Platform Information

*Komodo Edit or IDE?*  IDE
*Komodo Version?*  Master
*Operating System (and version)?*  Windows 7

**Comment by Naatan** [comment]
We likely need to repeat this logic when fullscreen is toggled:

https://github.com/Komodo/KomodoIDE/blob/master/src/chrome/komodo/content/library/uilayout.p.js#L1777
