### ISSUE TITLE
Cannot Start Komodo 10 With a Clean Profile

### ISSUE THREAD

**Issue by mitchell-as** [Komodo/KomodoEdit#1213]
### Short Summary

Try to start Komodo 10 with a clean profile and you cannot. You just get the "Welcome to Komodo" startup wizard with no content and no ability to go through it. Closing the dialog kills Komodo.

Log:

    [2016-04-04 11:32:10,427] [ERROR] console-logger: TypeError: require is not a function (2) in chrome://komodo/content/startupWizard/startupWizard.js:4
    Traceback (most recent call last):
      File "chrome://komodo/content/startupWizard/startupWizard.js", line 4, in

### Platform Information

*Komodo Edit or IDE?*  IDE
*Komodo Version?*  Master
*Operating System (and version)?*  Windows, probably others too.

### Additional Information

Reverting https://github.com/Komodo/KomodoIDE/commit/a349ac6a7aab13dcf4216b382197c73c12f6b6f2 fixes the problem.

**Comment by mitchell-as** [comment]
I'm not seeing this anymore in master, at least on Linux.

**Comment by tonyattwood** [comment]
Hello,

During my  last journey I've  visited a wonderful place, you'd love  it!  Please take a look here <http://fair.seocostaricaexperts.com/e4brbdpz>

Best wishes, tony.attwood@ntlworld.com
