### ISSUE TITLE
SCC Revert doesn't reload file

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1214]
### Short Summary

I just ran git > Revert from OpenFiles.  When I tried to close the reverted file i was alerted that the file had changed on disk and asked if I wanted to reload the file.  Before clicking `yes` I checked the file and it had not in fact changed to it's reverted state in Komodo.

### Steps to Reproduce

- Open a file under SCC control in Komodo
- Make changes and save
- In Open Files right click > SCC > Revert

### Expected results

File to reflect the new reverted state

### Actual results

File in buffer in Komodo has not changed.

**Comment by mitchell-as** [comment]
This appears to be fixed in master.
