### ISSUE TITLE
Extra Empty Directory Created in Userspace

### ISSUE THREAD

**Issue by mitchell-as** [Komodo/KomodoEdit#1215]
### Short Summary

On Windows, Komodo creates two directories in C:\Users\<username>\AppData\Local\ActiveState\: "KomodoIDE" (which is the user data directory) and "Komodo IDE" (note the space). The latter directory contains a single, empty "komodo" directory.

### Steps to Reproduce

Start with a completely clean C:\Users\<username>\AppData\Local\ActiveState\ folder.

### Expected results

Just the "KomodoIDE" user data directory should be created.

### Actual results

"KomodoIDE" along with "Komodo IDE" that appears to be unused.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10
*Operating System (and version)?* Windows

**Comment by cgchoffman** [comment]
This is used by Mozilla.  If you use komodo on Windows for long enough there will be content in it.  Can't hurt to look into removing it I suppose.  It was introduced around when we moved to Mozilla 35

**Comment by mitchell-as** [comment]
Okay, if content eventually goes in it, then we shouldn't touch it. I thought it was something completely superfluous.
