### ISSUE TITLE
CSS completions given on new line

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1216]
### Short Summary

When starting a new line after a textual property CodeIntel gives autocompletions in CSS/LESS/SCSS

### Steps to Reproduce

Create a new file and enter `menulist`, then press enter.

### Expected results

Create a new line, nothing else

### Actual results

Autocompletions show.

**Comment by mitchell-as** [comment]
I disagree on this being a bug. You haven't completed your selector.

    div
    code
    {
        /* ... */
    }

is a perfectly valid selector. I'm guessing you intend to put a '{' on your next line after pressing enter and don't need the autocompletion.

**Comment by Naatan** [comment]
I don't think you follow my meaning, this is definitely a bug.

This is where my caret is at:

```
menulist
|
```

It's giving me completions starting with "a", indicating it is not basing the completions on anything.

Regardless, completions should only show for words that are in the same line, we don't do cross line completions.

**Comment by Naatan** [comment]
After speaking with Mitchell this appears to not be a bug since CSS properties can be multi-line. I'll close this and open a new ticket for an enhancement.
