### ISSUE TITLE
Make CSS/HTML code completions configurable

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1217]
Depends on Komodo/KomodoEdit#880

In HTML and CSS (and potentially some other languages) codeintel triggers completions on empty selectors, eg. typing `<div` would show you all possible attributes. While this is a nice feature that I'm sure many people appreciate and use I've always found it annoying myself as it is inconsistent with how completions usually work, ie. completions normally only trigger on actual words.

It would be good if this behaviour could be disabled and completions only be triggered on partial words.

**Comment by mitchell-as** [comment]
I don't see how this is much different than dot method completion (e.g. `foo.|`): after the dot, you get completions. If you halt typing in the middle of a completion, dismiss the completion box, and continue typing, no completions come up until you press `Ctrl+J`. In the case of HTML and CSS, the spacebar functions as the dot. Everything else still applies and is consistent.

**Comment by Naatan** [comment]
The problem is that space is far too arbitrary. When I type a dot in eg. JS that quite clearly means I'll be writing a property. When I type a space in CSS it could intend to do any number of things.

**Comment by mitchell-as** [comment]
Okay, I'll see if I can work something in that allows a few letters to be typed in before an auto-trigger. This may not happen until after Komodo 11 though.

**Comment by mitchell-as** [comment]
With the new codeintel architecture, we are no longer constrained to the space key triggering completions in HTML and CSS.
