### ISSUE TITLE
Can't edit files on Komodo startup

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1218]
### Short Summary

I've been losing the ability to edit files in Komodo. It appears all you need to do is make a clean profile then start Komodo and open a file.

### Steps to Reproduce

Pull the latest on master, build && run, open a new file, try to backspace/activate incremental find/Ctrl+w the file closed

### Expected results

Those things above to work

### Actual results

They don't

**Comment by mitchell-as** [comment]
I confirm this bug. Additionally my terminal windows contains a bunch of repetitions of this:

    JavaScript error: chrome://komodo/content/editor.js, line 164: TypeError: docState.hasPref is not a function

The two may be related.

**Comment by mitchell-as** [comment]
For me, this only happens on the FIRST file (via Ctrl+N). I can edit just fine in subsequent files, but anytime I got back to the first I cannot.

**Comment by cgchoffman** [comment]
> For me, this only happens on the FIRST file (via Ctrl+N). I can edit just fine in subsequent files, but anytime I got back to the first I cannot.

confirmed this for me as well.
