### ISSUE TITLE
Select Previous (part of) Word skips linebreak

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1219]
### Short Summary

When selecting the whitespace at the start of a line using the mentioned command it include the line break

### Steps to Reproduce

Use the following snippet:

```
foo
    |foo
```

Invoke the "Select Previous Part of Word" command.

### Expected results

It selects the whitespace between foo and the start of the line

### Actual results

It selects the whitespace between foo and the end of the previous line

### Additional Information

"Move back part of word" behaves correctly.

**Comment by mitchell-as** [comment]
"Move back part of word" also moves past the line ending to the previous line. "Select previous part of word" selects to the position "move back part of word" moves to. There is nothing wrong with the given behavior -- in fact this is default Scintilla behavior. It counts any consecutive string of whitespace as a "word".

**Comment by Naatan** [comment]
I disagree, it is not the behavior that you expect as an end user. At the end of the day we are targeting users and not Scintilla's technical specifications.  

If I have this binding set to quickly make selections without iterating over every character (which is what the common use case would be) then for it to skip across linebreaks is an annoyance with no real purpose.

**Comment by mitchell-as** [comment]
As far as I know, we'd be the only editor that had that feature. Vim, Emacs, gEdit, heck probably even notepad all have "select previous (part of) word" selecting past a newline and onto the previous line (think Ctrl+Shift+Left Arrow). I as a user would not expect something different, but that's just me. Enhancement is a better label. I'll implement it as a new command altogether.

**Comment by Naatan** [comment]
That's a good compromise. I have not tested many different editors, but I know Sublime for one uses the behavior I'm advocating, and it is also an editor that seems to be well liked for it's editing UX.

**Comment by mitchell-as** [comment]
https://github.com/Komodo/KomodoEdit/commit/4c436a38eb2958276c884850d54761f5e89bd8ab
