### ISSUE TITLE
Komodo crashes on launch (OS 10.6.8)

### ISSUE THREAD

**Issue by Buzut** [Komodo/KomodoEdit#122]
Komodo just crashes when I try to launch it.  Error message:

Process:         launchd [14475]
Path:            /Users/Buzut/Desktop/Komodo Edit 9.app/Contents/MacOS/komodo
Identifier:      com.activestate.KomodoEdit
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  launchd [105]

Date/Time:       2015-04-05 16:36:13.839 +0200
OS Version:      Mac OS X 10.6.8 (10K549)
Report Version:  6

Interval Since Last Report:          54692323 sec
Crashes Since Last Report:           15
Per-App Crashes Since Last Report:   6
Anonymous UUID:                      2029D18D-B374-438C-A1CB-1916A8D92672

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0xfffffffffffffff8
Crashed Thread:  Unknown

Backtrace not available

Unknown thread crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000055  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x0000000000000000
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00007fff5fc01028  rfl: 0x0000000000010203  cr2: 0xfffffffffffffff8

Binary images description not available

Model: MacBookPro5,5, BootROM MBP55.00AC.B03, 2 processors, Intel Core 2 Duo, 2.53 GHz, 8 GB, SMC 1.47f2
Graphics: NVIDIA GeForce 9400M, NVIDIA GeForce 9400M, PCI, 256 MB
Memory Module: global_name
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x8D), Broadcom BCM43xx 1.0 (5.10.131.42.4)
Bluetooth: Version 2.4.5f3, 2 service, 19 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Serial ATA Device: M4-CT128M4SSD2, 119,24 GB
Serial ATA Device: TOSHIBA MK3255GSXF, 232,89 GB
USB Device: Internal Memory Card Reader, 0x05ac  (Apple Inc.), 0x8403, 0x26500000 / 2
USB Device: BRCM2046 Hub, 0x0a5c  (Broadcom Corp.), 0x4500, 0x06100000 / 2
USB Device: Bluetooth USB Host Controller, 0x05ac  (Apple Inc.), 0x8213, 0x06110000 / 4
USB Device: iPhone, 0x05ac  (Apple Inc.), 0x12a8, 0x24100000 / 3
USB Device: Built-in iSight, 0x05ac  (Apple Inc.), 0x8507, 0x24400000 / 2
USB Device: Apple Internal Keyboard / Trackpad, 0x05ac  (Apple Inc.), 0x0237, 0x04600000 / 3
USB Device: IR Receiver, 0x05ac  (Apple Inc.), 0x8242, 0x04500000 / 2

**Comment by Defman21** [comment]
https://github.com/Komodo/KomodoEdit/issues/105#issuecomment-88376641

**Comment by Naatan** [comment]
Komodo 9 only supports OSX 10.9 and up.

**Comment by Buzut** [comment]
Yep, realized it. Thx for your answer. I'm so sad I can't use the latest Komodo any more.

**Comment by Naatan** [comment]
Sorry, supporting older versions comes with a lot of maintenance and compromise, plus it doesn't really make sense when the OS itself isn't even supported any more by its vendor. Might be time to upgrade ;)
