### ISSUE TITLE
There is no menu when in focus mode

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1221]
### Short Summary

Enabling focus mode doesn't have a menu anywhere.  You need to use Commando to disable focus mode.

### Steps to Reproduce

Enable Focus Mode under the View menu.

### Expected results

There be a menu option somewhere, a hamburger menu, or still be able to pop up the menu using Alt.  Likely the former is the better, cross platform option.

### Actual results

No menu any where in the UI

**Comment by Naatan** [comment]
Fwiw this is only an issue when using native decorations. When using non-native decorations the menu will appear in the titlebar.
