### ISSUE TITLE
Interactive Debugger UI Needs Improvement

### ISSUE THREAD

**Issue by mitchell-as** [Komodo/KomodoEdit#1223]
### Short Summary

In the previous Komodo, when you open an interactive debug prompt while at a breakpoint when debugging, the button you clicked acted like a toggle button (it was shown as being pushed down). This is due to the fact that while an interactive debugger is running, you cannot step into, over, or other perform any other "go" actions. The pushed down toggle button was a good visual indication of why those options were disabled. The new Komodo 10 UI does not have this and it can be very unintuitive why you cannot perform "go" actions if you've forgotten the debug prompt is open. (It looks very similar to the output window.)

### Steps to Reproduce

1. Create a simple file to debug and place a breakpoint on the first line.
2. Debug.
3. At the breakpoint, open an interactive debug prompt (via the toolbar in the bottom pane).
4. The "go" actions are disabled, but there's no real indication why.

### Expected results

The button to start/stop the interactive debug prompt should indicate whether or not a session is active, just like in Komodo 9.

### Actual results

No indication why the "go" actions are disabled.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10
*Operating System (and version)?* Any

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by Naatan** [comment]
Fixed in https://github.com/Komodo/KomodoIDE/commit/f97b837fa8d92b2adcabf7443baa2addf0060197
