### ISSUE TITLE
chrome remote debugger opens wrong pref window

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1224]
### Short Summary

When trying to debug without having configured chrome the prompt that shows has a "Preferences" button, when clicked it opens the Languages > HTML pref screen. It should open the "Browsers" pref screen.

**Comment by mitchell-as** [comment]
Whenever a debugger invocation is invalid (e.g. executable does not exist), the error dialog you described is shown along with a "Preferences" button. When that button is clicked, Komodo tries to open the preferences dialog to a "section" (for lack of a better word) named `invocation.name.toLowerCase() + "Item"`. For example, "html5Item" or "javascriptItem". This happens in `src/chrome/komodo/content/debugger/debugger.js:2247`. In that `if` block we'll have to check if the language name is in a list of Chrome-debuggable languages ("html", "html5", "javascript", plus a few more perhaps), and if so, redirect to "WebItem" or whatever the equivalent preference "section" for setting the web browser is. I don't know how to do this though. Assigning to @Naatan.

**Comment by Naatan** [comment]
Fixed in https://github.com/Komodo/KomodoIDE/commit/01b4f9dd630e8b7832b9bca89c37efabddabc1fe
