### ISSUE TITLE
Chrome debugging: Allow debugging from html-like languages

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1225]
### Short Summary

I cannot invoke the debugger when editing .erb files. Similarly it won't work for other languages that are HTML-based. It would be good if this worked for any language that is HTML-based and does not have another debugger explicitly defined for it.

PHP files would be a good example of this being able to go both ways, in this case PHP would win the toss. We should have a way of letting the user pick which language he wants to debug at that point but for now let's focus on the basics.

**Comment by Naatan** [comment]
HTML5 also doesn't seem to work, but that would be solved by this ticket.

**Comment by mitchell-as** [comment]
Closed via https://github.com/Komodo/KomodoIDE/commit/7d21f0c737995ddf50dcc7717d0d6b8817cefd53
