### ISSUE TITLE
Can't enable native windows borders on Windows

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1228]
### Short Summary

I can't turn on native windows borders on Windows.

### Steps to Reproduce

Right click the toolbar  > Customize > enable native windows borders

### Expected results

Native window borders to be enabled

### Actual results

No dice

Note: restart doesn't fix this and starting from a clean profile doesn't work either.

**Comment by Naatan** [comment]
"Enable native window borders" does not exist in the place that you described (anymore), are you up to date?

**Comment by cgchoffman** [comment]
> are you up to date?

My brain isn't.
