### ISSUE TITLE
Node modules make Komodo hang

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1229]
### Short Summary

I don't know the exact issue, but my project with relatively few node modules is making Komodo hang. I've narrowed it down to the node_modules folder, if I move that folder outside my project Komodo does not hang. If I move it back inside my project Komodo will hang after a short period. Presumably when it scans it.

### Steps to Reproduce

 1. Create a new project, add some bogus files
 2. Add the packages.json below to the root (under additional information)
 3. Install the referenced modules by running `npm install` from the directory that holds the package.json
 3. Wait a few seconds (generally happens within a minute)

### Expected results

 1. Nothing

### Actual results

 1. Komodo hangs

### Platform Information

*Komodo Edit or IDE?* IDE
*Operating System (and version)?* Linux

```
$ npm --version
3.3.6
$ node --version
v5.0.0
```

#### package.json 

```
{
  "name": "Electron Quick Start",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "scripts": {
    "start": "electron --js-flags=\"--harmony\" --enable-transparent-visuals --disable-gpu main.js"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/atom/electron-quick-start.git"
  },
  "keywords": [
    "Electron",
    "quick",
    "start",
    "tutorial"
  ],
  "author": "GitHub",
  "license": "CC0-1.0",
  "bugs": {
    "url": "https://github.com/atom/electron-quick-start/issues"
  },
  "homepage": "https://github.com/atom/electron-quick-start#readme",
  "devDependencies": {
    "babel-preset-react": "^6.5.0",
    "electron-prebuilt": "^0.37.5",
    "gulp": "^3.9.1",
    "gulp-babel": "^6.1.2",
    "gulp-concat": "^2.6.0",
    "gulp-debug": "^2.1.2",
    "gulp-sass": "^2.1.0",
    "gulp-sourcemaps": "^1.6.0",
    "store": "^1.3.17"
  },
  "dependencies": {}
}
```

#### note 1

my komodoproject file has this pref in it:

```
  <string relative="path" id="nodejsExtraPaths">node_modules</string>
```

This is not something I defined myself (so it really shouldnt be in there, but thats besides the point for this bug).

#### note 2

It seems to be an infinite loop of some sort. Komodo starts consuming increasing amounts of memory as soon as I open a project with that node_modules folder (doesnt happen on all projects with a node_modules folder). Moving the folder out of the project solves this also.

Is our new node module codeintel logic aware that modules can depend on each other (NPM has a bad reputation for having a lot of recursion).

**Comment by mitchell-as** [comment]
As we discovered, the SCC is to blame. Turning off git prevents the blocking.
