### ISSUE TITLE
PHP Remote debugging:  many reports of Komodo crashing while debugging

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1233]
### Short Summary

There have been multiple reports over the passed few months of PHP remote debugging crashing Komodo.  The reports are relatively consistent and warrant further investigation. I personally have not been able to reproduce the issue though.

OTRS: http://otrs3.activestate.com/otrs/index.pl?Action=AgentTicketZoom;TicketID=48510

**Comment by mitchell-as** [comment]
Possible a duplicate of https://github.com/Komodo/KomodoEdit/issues/1007

**Comment by tonyattwood** [comment]
Hello,

I've came across that  information  yesterday and  thought it would  help you, read more here please <http://excellent.baseil.com/e4stwe>

Hope this helps, tony.attwood@ntlworld.com

**Comment by Naatan** [comment]
Closing this as it is old and not actionable. Not to mention #1007 might have resolved this?
