### ISSUE TITLE
SCC: Handle large number of dirty files properly

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1234]
Komodo does not handle a large amount of dirty files well when committing files or pretty much performing any SCC action that employs the 'status' method. This needs to be handled more gracefully, both in backend and frontend.

Frontend currently only sorting the commit file selection is a bottlebeck. Backend pyxpcom seems to absolutely freak out on large data sets.

An easy test for this is to npm install some large packages (with tons of dependencies) and then checking out the commit UX.

**Comment by agroszer** [comment]
The pain is that it's NOT just dirty files. But lotsa files under SCC. That makes KO X unusable for me.

**Comment by Naatan** [comment]
Have you tried the final release? Although this hasn't been completely solved yet I have made significant optimizations such that it's a far smaller problem.

**Comment by agroszer** [comment]
Yah I'm trying the final, weird is that the very first places open took ages, now it's better.

**Comment by Naatan** [comment]
It might have still been running startup procedures. Especially after a major upgrade this could take a little while longer.

**Comment by Naatan** [comment]
This is fixed in 10.1, the commit dialog no longer groups (sorts) files by modification type and only by filename.
