### ISSUE TITLE
Custom Decorations: not able to move window without using window moving modifier (Alt)

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1239]
### Short Summary

I'm not able to move the window without pressing Alt. With native decorations I can.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10 alpha
*Operating System (and version)?* Ubuntu 16.04

**Comment by Naatan** [comment]
This usually happens after a while on linux, I'm not sure what the trigger is. Please let me know if you can figure out reproduction steps.

**Comment by Defman21** [comment]
*Saying "yes of course" there as well*

**Comment by Defman21** [comment]
Changing color scheme produces this issue for me and lagbox from IRC chat.

**Comment by Naatan** [comment]
Does changing the color scheme for just the editor reproduce it?

**Comment by Defman21** [comment]
Yes.

**Comment by lagbox** [comment]
For me just opening the color scheme editor causes this, whether applying anything or not.
I am also received this issue after changing projects and if any error dialogue pops up.
In safemode the changing projects is not effecting it though.

**Comment by lagbox** [comment]
:+1:
