### ISSUE TITLE
CodeIntel incomplete, inability to use section scope

### ISSUE THREAD

**Issue by lagbox** [Komodo/KomodoEdit#1241]
### Short Summary
After codeintel has run, it seems incomplete and there is no `symbols.db` created for the sections scope to use.
Also get locked into that scope and can't back out of it.

### Steps to Reproduce
For me, loading a simple Laravel project and let codeintel run.

### Expected results
Expecting the codeintel to be complete and the ability to search symbols.

### Platform Information
Komodo IDE 10 Alpha

Ubuntu 15.10

### Additional Information

[pystderr.txt](https://github.com/Komodo/KomodoEdit/files/216260/pystderr.txt)

```php

<?php

namespace App\Http\Controllers;

use App\Data;
use App\Http\Requests;
use Illuminate\Http\Request;

class DataController extends Controller
{
    public function tt()
    {
        $this->authorize()     /* <--- I have left the cursor between those () */
    }
...
```

**Comment by Naatan** [comment]
His codeintel scan appears to never really complete, it's sending a start and complete notification continuously.

**Comment by lagbox** [comment]
By the way, great job on Komodo IDE 10 so far guys. Looks absolutely amazing and is much faster :-)

**Comment by mitchell-as** [comment]
If it's possible, would you please share the entire content of your DataController.php file? I need some more context to be able to pinpoint the error. Thanks!

**Comment by mitchell-as** [comment]
Actually, never mind. I think I identified the problem. Sorry for the noise.
