### ISSUE TITLE
KO not responding after a while

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#1242]
### Short Summary
(after installing my favourite qwin addon)
KO goes not responding after while (seems like while building code intelligence)

### Platform Information

Komodo IDE, version 10.0.0-alpha1, build 88789, platform linux-x86_64. Built on Fri Apr 8 10:30:36 2016.
Linux ebi 4.2.0-34-generic #39-Ubuntu SMP Thu Mar 10 22:13:01 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mitchell-as** [comment]
Hi, could you provide some more information on how to reproduce this? I installed qwin, restarted Komodo, opened a project along with a Python file, triggered autocomplete, and code intelligence took a bit of time, but ultimately gave me completions.

**Comment by Naatan** [comment]
Few questions:

1. Are you using a project with SCC? 
2. Do you have a lot of uncommitted changes?
3. What is happening to the CPU and memory when Komodo hangs?
4, Have you tried "waiting it out" (if after 5 minutes it still hangs I'd say its a full on hang)

**Comment by agroszer** [comment]
I installed qwin, restarted Komodo, opened 2 standalone .py files, no project, editor was sitting around it was building the code intelligence DB

1. yes, pretty big one
2. no, more like close to nothing, a few lines
3. CPU is at 100%, mem grows very slowly (ca 2 megs/sec)
4. Jim it's dead (after 15mins)

pystderr.log does not seem to have corresponding stuff

looks like this happens when the SCC sidebar icon gets the "..."
![screenshot_2016-04-13_19-48-01](https://cloud.githubusercontent.com/assets/350912/14503513/b257643e-01b0-11e6-8483-ae45c5159858.png)

**Comment by Naatan** [comment]
Thanks @agroszer, that is a known issue with SCC. I've made improvements for this on the master branch (should be released in a day or two) but the longer standing issue for this is https://github.com/Komodo/KomodoEdit/issues/1234

Closing this in favour of that bug.

**Comment by Naatan** [comment]
fyi committing those files (or adding them to gitignore) will resolve the hang.
