### ISSUE TITLE
multiscreen + goto anything popup

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#1243]
The goto anything popup seems to show up at random places on my multi screen setup (XFCE, xubuntu 15.10)

### Platform Information

Komodo IDE, version 10.0.0-alpha1, build 88789, platform linux-x86_64. Built on Fri Apr 8 10:30:36 2016.
Linux ebi 4.2.0-34-generic #39-Ubuntu SMP Thu Mar 10 22:13:01 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Naatan** [comment]
This is a known bug, but it should be better the second time you open it, is this not the case?

**Comment by agroszer** [comment]
yah, after a few opens it knows the right place

**Comment by Naatan** [comment]
Alright, thanks for verifying :) I'll get on this.
