### ISSUE TITLE
Troubleshooting Button on New Tab page doesn't work anymore

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1245]
### Short Summary

If I'm clicking on it there's no popup with items.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10 alpha
*Operating System (and version)?* Ubuntu 16.04

**Comment by Naatan** [comment]
@cgchoffman wanna take this?

90% sure it's a matter of moving the icon to a lower level nodes (menu buttons dont like icons on the top level element).

**Comment by cgchoffman** [comment]
YupYup!  Thanks.
