### ISSUE TITLE
Need to re-open the file to apply new Indentation settings

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1246]
### Short Summary

I've changed Indentation settings from 4-width of a tab to 2-width but none of my opened files applied it to themselves. Auto-indent still uses the old setting and only if I re-open the file - everything will work.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10 alpha
*Operating System (and version)?* Ubuntu 16.04

**Comment by Naatan** [comment]
Where did you change the indentation setting?

**Comment by Defman21** [comment]
Prefs - Indentation

**Comment by mitchell-as** [comment]
Global indentation settings changes take effect immediately in all documents, but per-language ones do not. I've updated the UI with a notice that a file reload is needed for per-language indentation settings changes.

**Comment by tonyattwood** [comment]
Hi,


I've tried some  new  experimental methods of  treatment, it  really  helped me. Read more abot that here <http://favourite.metrowesthomesteam.com/e4wzirdn>

Kind regards, tony.attwood@ntlworld.com
