### ISSUE TITLE
Window positions inconsistent

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1247]
### Short Summary

It just moves. See the video, I don't know how to describe it properly.
https://youtu.be/vDwQaXGvxGU

### Steps to Reproduce

Make file dirty and try to close it.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10 alpha
*Operating System (and version)?* Ubuntu 16.04

### Additional Information

Workaround: don't close files and don't make them dirty and always save them and love them <3

**Comment by cgchoffman** [comment]
Do you notice this happening with other dialogs?  and is it always the exact same spot that the dialog will move to?

**Comment by Naatan** [comment]
It happens with all windows, it's a known bug I've been aware of and have on my personal shortlist.

**Comment by Defman21** [comment]
The spot changes depends on window's position I guess.

**Comment by cgchoffman** [comment]
For me it's the exact same location, every dialog, every time.  Bottom left corner of my left monitor.

**Comment by Naatan** [comment]
It's probably dependant on your window manager, Windows seems to handle it better than Gnome.
