### ISSUE TITLE
No auto-completion for PHPUnit

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1249]
### Short Summary

There's no auto-completion for PHPUnit. Maybe Komodo should have some sort of an API catalog for it?

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10 alpha
*Operating System (and version)?* Ubuntu 16.04

**Comment by Naatan** [comment]
If you add PHPUnit to your path you would get autocompletion for it.

It does make sense to have a catalog for this though, thanks for the suggestion!

**Comment by Defman21** [comment]
I have phpunit.phar on my $PATH and in my include_path ini setting but I don't see any auto-completions for it.

**Comment by Naatan** [comment]
I think .phar is compressed somehow? It should be in a flat file format.

**Comment by mitchell-as** [comment]
I had to use the actual PHPUnit source in standard format.

**Comment by Defman21** [comment]
phar is an executable php archive (whatever it means), I can see its contents (valid PHP contains a lot of requirements and classes)

**Comment by mitchell-as** [comment]
Well at >2MB codeintel certainly wouldn't scan it. I cannot see us supporting scanning of phar archives anyway due to their size.

**Comment by Defman21** [comment]
So I need to download PHPUnit source and add it as an external directory for scanning for auto-completions?

**Comment by Naatan** [comment]
Yes, if you want them before completion of this ticket that is what you would have to do.

**Comment by Defman21** [comment]
Well I can't add any Import Directories because of #1251 :(

**Comment by Naatan** [comment]
Ok well that bug is being tracked so ..

**Comment by mitchell-as** [comment]
Note to self: running `ci2 scan -fpnr /path/to/phpunit/src > /tmp/foo.cix`, and then importing the `/tmp/foo.cix` catalog does not work when trying the PHPUnit sample

```
<?php
use PHPUnit\Framework\TestCase;

class MoneyTest extends TestCase {
    public function testFoo() {
        // Assert
        $this->assertEquals
```

The `use PHPUnit\` declaration does not work.

**Comment by mitchell-as** [comment]
Note: I was using it wrong in my above comment. It's supposed to be `class MoneyTest extends PHPUnit_Framework_TestCase {`. Then the assert completions started showing.

**Comment by Defman21** [comment]
Thanks for that, Mitchell!
