### ISSUE TITLE
Showing go-to-anything under kwin when maximized changes window width

### ISSUE THREAD

**Issue by Mook-as** [Komodo/KomodoEdit#1250]
### Short Summary

When using kwin as the window manager, and the Komodo window is maximized, showing the go to anything dropdown makes the window move.

### Steps to Reproduce

0. Be using kwin as the window manager. (The easiest way to do this is to start a KDE/Plasma desktop session.)
1. Make sure Komodo is not maximized, and the window width does not span the width of the screen.
2. Make sure Komodo is not using native window borders.
3. Maximize the Komodo window with the (+) button
4. Trigger the go-to-anything dropdown (`Ctrl+Shift+K`, I think?)

### Expected results

* The go-to-anything dropdown appears.
* The main window remains where it is.

### Actual results

* The go-to-anything dropdown appears.
* The main window's right edge moves towards the left.

### Platform Information

Komodo IDE, version 10.0.0-alpha1, build 88789, platform linux-x86_64.
Built on Fri Apr 8 10:30:36 2016.

Ubuntu 14.04 / KDE 4.13.3

### Additional Information

* Repeatedly triggering the bug will move the right edge leftwards until the window width matches the size of the window before maximizing

**Comment by Naatan** [comment]
Given step 3 I assume this means that using native window borders "resolves" the issue?

**Comment by Mook-as** [comment]
Correct, using native window borders does not exhibit this behaviour.

**Comment by Mook-as** [comment]
As a note: This still happens on:
Komodo IDE, version 10.0.0-alpha1, build 88973, platform linux-x86_64.
Built on Tue Apr 26 10:17:54 2016.

Also, it does _not_ happen when the toolbar buttons are hidden. Yay?
