### ISSUE TITLE
Editing lists (Import Directories, Mapping URI, etc...) is not possible: lack of icons

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1251]
### Short Summary

Under Prefs - Languages - PHP I don't see any way to add a new directory into PHP Directories setting.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10 alpha
*Operating System (and version)?* Ubuntu 16.04

**Comment by cgchoffman** [comment]
Icons need updating.  Old screenshot to show whats needed:  
![capture](https://cloud.githubusercontent.com/assets/655154/14503271/37ac493a-0164-11e6-9f64-d9eee6ce27be.PNG)

**Comment by Defman21** [comment]
They are missing in any of Languages.

**Comment by Defman21** [comment]
They are missing everywhere in Prefs. Any of this type of setting is not editable for now.

**Comment by Naatan** [comment]
Add/delete is already fixed on master, but we need to add the up/down icons.
