### ISSUE TITLE
Enabled API catalogs are not indicated in any form 

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1252]
### Short Summary

Prefs - Code Intelligence - API Catalogs: enabled API catalogs are not indicated so it's hard to see what's enabled. (I'm using Monokai scheme)

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10
*Operating System (and version)?* Ubuntu 16.04

**Comment by Defman21** [comment]
For example jQuery is enabled there (Taken from the log: `ie: lookup ('PHPUnit_Framework_TestCase',) in <PHP cataloglib: HTML5, Komodo, **jQuery**>`)
![Imgur](http://i.imgur.com/bTHZk5Q.png)

**Comment by Naatan** [comment]
Fixed in https://github.com/Komodo/KomodoIDE/commit/f3d9a8874596a89f29823bddde7c7f3cf21bf220
