### ISSUE TITLE
OSX: Editor goes blank after being restored from being minimized

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1254]
### Short Summary

I lose my code content from a file when I bring Komodo back from being minimized

### Steps to Reproduce

Open Komodo
Open a file
Minimize the screen
Bring back the screen

### Expected results

There to be text in the editor

### Actual results

The code flashes on the screen then disappears.

**Comment by mitchell-as** [comment]
Duplicate of #564
