### ISSUE TITLE
New: OSX: can't drag window when windows decorations enabled

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1255]
### Short Summary

When I enable Window decorations on OSX, i can't drag the main window any more

### Additional Information

OSX
Latest master as of April 13th at 14:26 #8dc99c8

**Comment by Naatan** [comment]
Are you dragging it by the native titlebar?

**Comment by cgchoffman** [comment]
That might be the issue, there is no native titlebar:
![screenshot at 14-44-05](https://cloud.githubusercontent.com/assets/655154/14510423/38150a20-0186-11e6-85a5-fbc230dd67a7.png)

**Comment by Naatan** [comment]
Ah right, that's it. I'll close this in favour of https://github.com/Komodo/KomodoEdit/issues/1192
