### ISSUE TITLE
JS console: Input field doesn't grow with input that is higher than it's container

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1258]
### Short Summary

The input area of the JS console doesn't grow as you add lines.  See screenshot.

![capture](https://cloud.githubusercontent.com/assets/655154/14542489/fea2875e-0243-11e6-8f7e-c1cf1b8e5b4a.PNG)

**Comment by Naatan** [comment]
This has since been fixed.
