### ISSUE TITLE
Code intelligence too fond of "input"

### ISSUE THREAD

**Issue by DaveAndersonQA** [Komodo/KomodoEdit#1259]
### Short Summary
Something that I do very frequently in Python is iterate. For example:

```
for var in iterable:
    Do something...
```

The problem is, every time I attempt to type something like the above, Komodo IDE inserts the word "input" where I simply want "in".  Code intelligence only suggests "input" or "int" in such cases.

### Steps to Reproduce
Try to type the code example above

### Expected results
If I am typing rapidly and hit a space after "in", then I probably only want to type "in ". The only way I can get close to this behavior is to type: 

`"in<Esc> "`

In my searches I have found mention of a delay that can be set, where I would need to pause for a configurable delay before code intel fills in for me. I cannot find anything in the prefs to control this, though I did find the unrelated delay setting under "Smart Editing". Possibly it was removed prior to 9.3.

I would like to see one or both of the following solutions:

1) Set a configurable delay, so if I know what I want I can just type it without interference
2) For common misses like in my example, allow me to configure what is intended for the character combination "in ".

I use "in " about 100x more often that I want "input", though some people may use "input" 100x more than "in ". Option 2 above should be configurable for different needs. I realize #2 would be a long shot anyway, due to the effort required... but it never hurts to ask. :)

### Actual results
See above... "input" is placed in the editor when I type "in "

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 9.3
*Operating System (and version)?* Win7-64 Pro

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by cgchoffman** [comment]
I 100% disagree with a delay.  If I"m using code intel then i want suggestions NOW.  I don't want a delay.

I think suggestion 2 is overly complicated and far to narrow a use case as well.

I'd suggest that there be an option to only select code intel suggestions when `tab` is pressed or some other explicit, but simple, key or combo.  It makes more sense to me that `space` means you don't want the code suggestions and you want to keep typing.

**Comment by DaveAndersonQA** [comment]
The delay that was mentioned in the references I found defaulted to 250ms. The idea being, the code intel never pops up until you pause. You could set it for 100ms, 50ms, or turn it off and get the current behavior.

I would be perfectly content with the mapping you suggest:

`tab` Use the currently highlighted code intel item
`space` Don't interpret, try to be intelligent or guess, just enter what I typed.

**Comment by cgchoffman** [comment]
Ugh, sorry @DaveAndersonQA.  It's something else.  You have *Prefs > Code Intelligence > Enable Autocomplete Fill-up Characters*.  You'll need to disable that.  Does that solve the issue for you?

**Comment by DaveAndersonQA** [comment]
That fixed it, yes... Thanks. However, this is non-intuitive(since `space` is not mentioned in the pref panel) and breaks the fill-up functionality that I have become accustomed to. The prefs panel mentions that this pref applies to "certain characters" and mentions '(' and '.', and I do find this useful. For now it is easier for me to disable the pref as you suggested, but perhaps you would consider removing `space` from the list of "certain characters" that trigger this functionality? Alternatively make this list of "certain characters" editable?

Perhaps making the list of applicable characters known would help. Maybe they are in the docs but I can't get there from here: http://docs.komodoide.com/Manual/prefs gives me "Sorry there was a nasty error - incompatible character encodings: UTF-8 and ASCII-8BIT "

**Comment by Naatan** [comment]
This pref has been disabled by default in new installations due to it's confusing nature. 

I think beyond that it doesn't really warrant being fleshed out (allowing you to specify custom fill-up characters). The use-case you ran into has been addressed by not making it a preference that is enabled by default.

**Comment by DaveAndersonQA** [comment]
Is there actually a use case for `space` as a fill-up character? I can't think of one. Why not just remove it from the list?

**Comment by cgchoffman** [comment]
> Is there actually a use case for space as a fill-up character?

Every time you want to use a variable without calling a function or getting a property from the types class.  Or key/reserved words, ie. `pr` > `print`.  If I used this pref (i do not), I would want it to trigger on spaces.
