### ISSUE TITLE
Add a way of resetting file level prefs (globally)

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#126]

**Comment by Naatan** [comment]
Also - prefs that are saved on the file should be doing so more explicitly.

**Comment by AtmanActive** [comment]
I just got bitten by this.
Auto-updated Komodo IDE from 9.2 to 9.2.1 and suddenly my indentation prefs are completely ignored by Komodo, and when I go to file level prefs for the same thing, then something changes indeed but still not behaving correctly.

Deleted 'doc-state.xmlc' manually and everything started working normally again.

**Comment by cgchoffman** [comment]
Thanks for the heads up.  Sorry for the pain but is it possible that you could detail exact steps taken?  It'll help us trace the code a little more.

**Comment by AtmanActive** [comment]
- Komodo offers to auto-upgrade from 9.2 to 9.2.1 - I say yes
- Went to prefs to see if some other font would suit me better
- Upon exiting prefs got error about prefs getting corrupted or something - my Komodo suddenly turns white (it was always black before and after that)
- I restarted Komodo to try to make it come back to it's senses
- Everything looks like it is working normally, except my indentation settings are not being followed at all
- Tried changing indentation settings - still nothing happens - read somewhere that Komodo remembers setting for each file and that it has a priority over main prefs (BTW, my prefs option 'Allow file contents to override Tab and Indentation settings' is OFF at all times)
- Tried changing indentation settings in the file I'm working on, and I see that indeed something changes there, like, these settings are used, but in some completely wrong way I couldn't understand or make work as desired
- Finally read somewhere to delete the file 'doc-state.xmlc' while Komodo is off and did just that
- Everything back to normal and works as expected from that moment on

**Comment by AtmanActive** [comment]
Continued here:

https://github.com/Komodo/KomodoEdit/issues/719

**Comment by Naatan** [comment]
This has been added in 9.3 (nightly) under the troubleshooting button.
