### ISSUE TITLE
CodeIntel scanning and go to definition issue

### ISSUE THREAD

**Issue by lagbox** [Komodo/KomodoEdit#1260]
### Short Summary
The initial codeintel scan (pre filling) goes very smoothly, status gets updated in a progression.

Once engaging in a autocomplete activity that causes codeintel to scan, I start getting the 100% scanning project folder flashing in the status. This happens in a loop between 100% and 0% for several minutes. During that time that bar will go back to the text Go To Anything, then it will flash back to scanning in that loop.

When it finishes, I have some autocomplete and codeintel popover with information about the method. I can not 'Go To Definition' of anything, as that option is disabled in the context menu when right clicking.

### Steps to Reproduce
For me, open up lets say the `DataController` in `app/Http/Controllers` and add a method and inside it do a `$this->` and expect some auto complete.

### Expected results
Expecting the codeintel status to be a smooth progression and not be flickering the way it is.
I expect the 'Go to Definition' option to be available.

### Actual results
Inability to 'Go to Definition' on anything.

### Platform Information
Komodo IDE, version 10.0.0-alpha1, build 88840, platform linux-x86_64. Built on Thu Apr 14 02:28:19 2016.

Ubuntu 15.10
PHP 7.0.5-2+deb.sury.org~wily+1

### Additional Information
Repo with example project used. This is only a few changes from a fresh Laravel 5.2 install. You can clone the repo and run `composer install` to get all the dependencies, including the framework.

[Test Laravel install repository](https://github.com/lagbox/komodotest)

[pystderr.txt](https://github.com/Komodo/KomodoEdit/files/220089/pystderr.txt)

The previous fixes applied, have added the symbols.db as expected and now have site-wide symbol searching available.
Thanks again guys, 10 is going to be a game changer :).

**Comment by lagbox** [comment]
I came back to the editor after about 45 minutes to an hour and I have the 'Go to Definition' active in the context menu. Using it causes the rescan, which causes the flickering, with no way to know when it is done. After about 10-15 minutes it gets to an actual percentage as it is scanning through some shared php libs and PEAR directories outside of the project. After waiting another 5 minutes or so, the 'Go to Definition' will start working.
Sorry if this is getting verbose.

**Comment by Naatan** [comment]
Reproduced on a clean profile (I could not reproduce it on my existing profile).

**Comment by Naatan** [comment]
Fixed this by configuring the php interpreter, php.ini and composer all explicitly (not find on path). 

@mitchell-as seems odd that the codeintel scanner would depend on this if all the project files are local?

**Comment by mitchell-as** [comment]
First, thanks @lagbox for the awesome report. It is a model of excellence. I know nothing about PHP, yet with your detailed steps I was able to set everything up easily and trigger a real-world use case of autocompletion for PHP (instead of a superficial one). Not only that, but you've set up a repository for us. You're awesome!

Okay, I am getting the "flickering" scan notification, but that is because there are a number of small directories that need to be scanned individually (you can see this by going to Komodo's notification pane and you'll see numerous "Scanning one directory" notifications. If one were to ignore that notification, you won't get the "flickering".

As for the lack of goto-definition, I am not able to reproduce it. I can jump to the "Data" class and "Controller" class for example.

Note: I did not have to set any PHP exe, php.ini, composer location, etc. I did not use composer to install any dependencies either. This was all done from a clean profile.

**Comment by lagbox** [comment]
First, you are very welcome. Anything I can do to make things easier, let me know :-).

The flickering makes perfect sense how you have described it. Without this knowledge it just 'looks' like something funky is going on as I can't see the full path its scanning so I only see a partial path (which is the same every time as its the root of the project, until it gets to the outside of project scanning). Seeing it that way kinda makes it look like its going from 0-100 over and over again, as opposed to walking through directories.
Now, knowing how this works and knowing to look at the notifications I can get a better idea of its progress.

After this scanning has finished, I do not have the 'Go to Definition' available immediately (I am going to work this out today with some tests). 
Also with restarts it isn't available right away, but after a short duration it becomes active. So I would suppose for starting the application, there is a subsystem that just isn't quite ready yet at the time.

I am going to do some more testing today and will let you know if anything changes.

And again, thank you guys very much :-)

**Comment by Naatan** [comment]
> Okay, I am getting the "flickering" scan notification, but that is because there are a number of small directories that need to be scanned individually (you can see this by going to Komodo's notification pane and you'll see numerous "Scanning one directory" notifications). If one were to ignore that notification, you won't get the "flickering".

Hmm so this isn't really a percentage indicator, it's a "I'm scanning this dir" notification. I'll see if I can infer as much from the notification codeintel scans, if not that code may need some updating.

**Comment by lagbox** [comment]
Yea, I kinda think a user would expect that percentage to be a complete percentage of the scanning as a whole, as to know the actual progress, not a per directory percentage.

I moved my `~/.komodoide/10.0` folder and started it up again, went through the initial config, opened this project and let it scan.
The 'Go to Definition' option is available from the start. I use it, to cause a code scan and after it completes it seems everything is as expected.

The main issue I am seeing is that status bar will go back to 'Go to Anything' for a bit, then start scanning again, so its very difficult to know that it actually is finished. So a user might think the codeintel and Go to Definition are not working, when in fact the scan process hasn't fully completed yet.

I hope this information helps.

**Comment by cgchoffman** [comment]
> Hmm so this isn't really a percentage indicator, it's a "I'm scanning this dir" notification. I'll see if I can infer as much from the notification codeintel scans, if not that code may need some updating.

Isn't this what code intel has always done?  It's just more apparent because the notifications are right in your face now.  if you watch the notification tab in 9.x and repro this you'll see 100s of scanning messages flying by (i assumed they were popping up per folder or cix file).


> The main issue I am seeing is that status bar will go back to 'Go to Anything' for a bit

I agree, this would be the main issue.  It's weird that it tells you it's done but isn't. It caught me already where I thought I should have code intel suggestions but couldn't get any, then suddenly the notification popped up saying "hey i'm scanning again!"

**Comment by mitchell-as** [comment]
@cgchoffman is right @Naatan, the percentage indicator is always how it's been. The percentage works for the directory codeintel is scanning. If it's a small directory with only one file, you'll get 0 to 100% in a hurry. If it's a larger directory like the PEAR directory mentioned earlier, then you'll see a gradual increase to 100% (again, noted earlier).

**Comment by Naatan** [comment]
What it's always been like is irrelevant if it doesn't work well. In this case it affects 10.0 because the notification is far more apparent than it has been in the past.

**Comment by lagbox** [comment]
That seems like a user experience issue that should be adjusted, no? Otherwise as users we are in the dark at what is going on as a whole process and not knowing the actual progress or when it will be finished. 

I would worry a new user would not know what is going on, be trying to use features that are dependent upon this scanning and assume something isn't working properly, get frustrated and stop using it, when in reality they just need to wait for this process (as a whole) to finish.

Just trying to point out something I see as a user that is an issue, not from a developers stand point; I can't imagine how complex this stuff is actually internally to do, or if it is possible to make such an adjustment.

**Comment by tonyattwood** [comment]
Hello,

It's never too late  to read some  interesting info here  <http://explore.rosenbergtxflowers.com/e4vfgpr>

Regards, tony.attwood@ntlworld.com
