### ISSUE TITLE
Search input box has strikethrough if not found

### ISSUE THREAD

**Issue by clokep** [Komodo/KomodoEdit#1261]
### Short Summary
The search input box turns red and has a weird strikethrough if the string is not found.

### Steps to Reproduce
Type in a string that doesn't exist.

### Expected results
The search input box turns red.

### Actual results
The search input box turns red and has a strikethrough.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* Komodo IDE, version 10.0.0-alpha1, build 88840, platform macosx. Built on Thu Apr 14 01:40:38 2016.
*Operating System (and version)?* OS X El Capitan

### Additional Information

![screen shot 2016-04-15 at 9 29 34 am](https://cloud.githubusercontent.com/assets/517124/14562813/e6c0f338-02ec-11e6-85ce-515ee8631393.png)

**Comment by Naatan** [comment]
I cannot reproduce this. Could you see if it still happens on the latest build?

http://downloads.activestate.com/Komodo/nightly/komodoide/latest-10.0.0_alpha1/

You need to manually upgrade due to an issue in the first release.

**Comment by clokep** [comment]
@Naatan I still see it with a build that has this version: `Komodo IDE, version 10.0.0-alpha1, build 88789, platform macosx. Built on Fri Apr 8 14:49:07 2016.` (that was from downloading from the above link you gave me). Although this build seems older so that confuses me...

**Comment by cgchoffman** [comment]
@clokep nathan passed over the wrong link.  I gotta clean up the nightly folders: http://downloads.activestate.com/Komodo/nightly/komodoide/latest-master/

**Comment by clokep** [comment]
@cgchoffman we had a conversation on IRC about it and @Naatan thinks he knows what's happening.

**Comment by cgchoffman** [comment]
Sounds good @clokep.  Just wanted to clarify why the build numbers looked wrong (i was confused at first too).
