### ISSUE TITLE
ES6 Backticks leaking

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1266]
### Short Summary

Everything after the backtick is still marked as a string.

### Steps to Reproduce

1. Create a new javascript file
2. Paste in the following:

```
var foo = 'bar';
console.log(`${foo}`);
// I'm a string
```

### Expected results

Comment on the last line be highlighted as a comment

### Actual results

Comment is highlighted as string

### Additional Information

I rebuilt CodeIntel just to be sure. Still happening.

Didn't we already fix this?

**Comment by mitchell-as** [comment]
Please rebuild Scintilla. Anything syntax-highlighting related is Scintilla/UDL and not codeintel.

**Comment by Naatan** [comment]
Man my brain was washed. Of course I meant Scintilla, somehow my brain was turning that into CodeIntel though ..
