### ISSUE TITLE
Auto-suggest,  method definitions, goto method definition: fail if multiple types if file are opened. 

### ISSUE THREAD

**Issue by harpreetsb** [Komodo/KomodoEdit#1268]
### Short Summary

lets say you have file like `tpl`, `php`, `js`
like 3 of each type.
after working for a while the auto-suggest or method completion does not popup.
Neither the "goto definition" works for `php` or `js`;
`CTRL+CLICK` initially works as `goto definition` but then starts creating multiple cursors.
`HOVER + CTRL` initially gives an underline, referring that clicking it will take you to the definition.
Underline is shown but does not take you to definition.

This whole situation repeats after restarting Komodo.
### Steps to Reproduce

open multiple files like `tpl`, `php`, `js`
like 3 of each type.
after working for a while the auto-suggest or method completion does not popup.
Neither the "goto definition" works for `php` or `js`;
### Expected results

Auto suggest, method definitions popups should be shown.
Goto to definition must work
### Actual results

None of it works
### Platform Information

_Komodo Edit, version 9.3.2, build 16460, platform linux-x86_64. Built on Thu Dec_ 
_9.3.2_ 
_Ubuntu 15.10?_ 
### Additional Information

 -- eg. Error logs, screenshots, workarounds --
![selection_008](https://cloud.githubusercontent.com/assets/6584304/14599419/d3ca7efe-0574-11e6-82cb-e61d409d6c01.jpg)

**Comment by mitchell-as** [comment]
Would you please submit your error log when you experience these problems? (Help > Troubleshooting > View Log File).

When you say auto suggest does not work, do you mean it does not work at all? Or just for your functions?

When you Ctrl+Hover over a definition (but do not click it yet), does it resolve? As in, does it show the supposed location of that function in a popup? (If not, then codeintel does not know where the function is defined and you'll get the multiple carets when you attempt to Ctrl+Click). Does codeintel know where any of your functions are defined for that matter? Or just specific ones?

**Comment by Naatan** [comment]
In additional to what @mitchell-as asked for, could you post the output of `ps aux | grep komodo` next time this happens?

**Comment by harpreetsb** [comment]
LOG
http://paste.ubuntu.com/15914351/

**Comment by harpreetsb** [comment]
@mitchell-as no auto suggest does not work at all.

**Comment by mitchell-as** [comment]
Hmm, it appears codeintel shut down for an unknown reason. Can you also send your ~/.komodoedit/9.3/codeintel.log?

I also noticed from your logs that codeintel is skipping a "jqx-all.js" file, which is over 1MB. You will not get any autocompletions based on that file.

**Comment by harpreetsb** [comment]
That file is not important.
the codeintel.log
```
WARNING:codeintel.manager:File u'/var/www/html/lyfboat/mails/assets/elements/jqwidgets/jqwidgets/jqx-all.js' has size greater than 1MB (2513103)
WARNING:codeintel.manager:File u'/var/www/html/lyfboat/app/assets/elements/jqwidgets/jqwidgets/jqx-all.js' has size greater than 1MB (2513103)
Traceback (most recent call last):
  File "/usr/lib/komodo-edit/python/lib/python2.7/logging/__init__.py", line 859, in emit
Traceback (most recent call last):
  File "/usr/lib/komodo-edit/support/codeintel/oop-driver.py", line 185, in <module>
    except Exception as ex:
MemoryError
````

**Comment by mitchell-as** [comment]
Okay, so codeintel ran out of memory. It's use is capped at 1GB. Does this problem happen shortly after you start Komodo Edit? Or have you left it open for a while and after a while things stop working? If it happens right away, try resetting your codeintel database: Help > Troubleshooting > Reset Codeintel Database.

**Comment by harpreetsb** [comment]
well its happens like after 15 minutes after i start working. when things stop working i still keep working. unless I really need codeintel of files other then currently opened files.
I tried resetting codeintel like 3 days ago, but this keeps happening.

**Comment by harpreetsb** [comment]
should i exclude this 1mb file from code intell? if that helps?

**Comment by mitchell-as** [comment]
No, codeintel skips those large files automatically. What I think is happening is that your project is really large and codeintel just runs out of memory scanning it. You can try tweaking the Edit > Preferences > Code Intelligence > Code Scanning options (try scanning fewer directories and/or do not include all files from the project base directory). After tweaking those settings you should reset your codeintel db again.

Other than that, I'm not sure what we can do to work around this -- I haven't seen this happen before.

**Comment by mitchell-as** [comment]
(Sorry, what I mean by "large" is there are a LOT of files, files smaller than 1MB in size that codeintel will scan without issue.)

**Comment by harpreetsb** [comment]
Got it. Will try this tomorrow.

**Comment by harpreetsb** [comment]
And yes project is really large.

**Comment by Naatan** [comment]
@mitchell-as isn't codeintel supposed to restart itself?

**Comment by mitchell-as** [comment]
@Naatan Yes, but it runs out of memory every time.

**Comment by Naatan** [comment]
@harpreetsb could you tell us a little bit about the project? eg.

 1. What language is mainly used?
 2. Do you use a package manager? (which?)
 3. Where are the bulk of the files located?
 4. Are there large sets of files that you would no want codeintel to scan? (share a little bit about them if you can, structurally)

I'm not looking for anything overly specific. We don't care about file or path names, but a general idea of the structure of your project would be very helpful.

**Comment by harpreetsb** [comment]
1. It's a PHP project, Wordpress, Slim framework, some python code, various php libraries.
2. Composer is used but not frequently, its has not been used since 4 months.
3. screenshots

4 we have lots of custom classes, that use wordpress functions, these are not plugins.

![selection_009](https://cloud.githubusercontent.com/assets/6584304/14628702/e8f355ae-061d-11e6-8b54-abbdd353d89f.jpg)
![selection_010](https://cloud.githubusercontent.com/assets/6584304/14628703/e8fe540e-061d-11e6-9af4-30740d4cf425.jpg)
![selection_011](https://cloud.githubusercontent.com/assets/6584304/14628704/e9044dc8-061d-11e6-9007-2b2fc3a5e61b.jpg)
![selection_012](https://cloud.githubusercontent.com/assets/6584304/14628705/e909fcfa-061d-11e6-99d1-7f6fcdf789ad.jpg)
![selection_013](https://cloud.githubusercontent.com/assets/6584304/14628706/e914a75e-061d-11e6-83cf-a2d48b19e8d6.jpg)

**Comment by Naatan** [comment]
> 4 we have lots of custom classes, that use wordpress functions, these are not plugins.

Which codeintel should not scan correct? Can you see any way Komodo could automatically identify these files?

**Comment by Defman21** [comment]
>It's use is capped at 1GB

Why I can't configure this? If I would have a 32GB RAM, I think I would give CodeIntel 3-4GB from it.
