### ISSUE TITLE
Won't indent past 1 indentation

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1269]
### Short Summary

I've seen this a few times but was never able to figure out how to reproduce it.

Komodo will at times outright refuse to indent. Nothing is in the error log not do I see any reason why it would not work.

### Steps to Reproduce

1. Open windows.xml in the komodo project (use commando, should only have 1 match (in content/bindings).

2. Paste the following contents after line 14:

```
    <binding id="root-element"
             extends="chrome://global/content/bindings/general.xml#root-element">
    <implementation>
      <constructor>
        <![CDATA[
          var w = require("ko/windows").getMain();
  var evt = new CustomEvent("myevent",
                            {
                              bubbles: true,
                              cancelable: true,
                              detail: { 'foo', 'somevalue' }
                            });
  window.dispatchEvent(evt);
        ]]>
      </constructor>
    </implementation>
    </binding>
```

3. Make a selection starting at the line with `var evt` and ending at the line with `window.dispatch..`

4. Attempt to indent

### Expected results

Indentation is made

### Actual results

Nothing happens

### Additional Information

I can unindent and indent again, but never past the first indent.

Unindenting something that is indented by more than 4 indentation blocks seems to unindent it by 4 entire blocks. It seems to be confusing indentation width by indentation blocks?

Indentation works fine on single line selections.

**Comment by mitchell-as** [comment]
I'm not seeing this in a clean profile with 4 space indent, 4 tab width, and no tab indentation. I can my global indent settings to 2/2 and I can still indent/dedent multiple times. What are your indentation settings?

**Comment by cgchoffman** [comment]
@Naatan, This is exactly what I was getting last week.  Me and @mitchell-as  spent a while digging into it and it turned out to be that my preferences were set to 4x8 which apparently breaks indenting.  Can you confirm indentation prefs?  make sure you check all the levels.  I ended up finding it in ONE project that happened to have that setting.  It was cascading down to certain files, but only when they were opened automatically with the project.

**Comment by Naatan** [comment]
My prefs are set to 4x4. This issue does not happen on 4x4 files though.

It seems the problem may stem from the file I'm editing having 2 width spaces.

**Comment by mitchell-as** [comment]
Right, which is why I also tested 2/2. Maybe Komodo "detects" 2 width spaces and sets it while keeping 4 width tabs. If so, we've identified the big bug I was alluding to on slack.

**Comment by Naatan** [comment]
Here are my prefs btw:

https://db.tt/Lm0lXexo

**Comment by mitchell-as** [comment]
That doesn't look bad. What about your file preferences and project preferences? Does a 2/4 setting exist anywhere? For the record I can set indentation to 2/4 manually and reproduce your problem of only being able to indent/dedent once, so we're onto something.

**Comment by Naatan** [comment]
File prefs are not set. I went through my global and project prefs manually and could not find any instance where indentWidth or tabWidth was not set to 4.

**Comment by mitchell-as** [comment]
Okay, in your Edit > Prefs > Editor > Indentation, what happens if you uncheck "Allow file contents to override tab and indentation prefs"?

**Comment by Naatan** [comment]
It does not resolve the issue.
