### ISSUE TITLE
JSON validator doesn't work properly

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#127]
```json
[
  [1]
  [1, 2],
]
```
Komodo says that there are no errors in the JSON but they are:
![errors](http://i.imgur.com/UbcVBYp.png)

**Comment by ervumlens** [comment]
There are practical problems with the JSON validation as well.

**Single quotes**
Only double quotes are valid JSON, but Komodo's validator accepts singles.
* Code
```json
['a']
```
* JSONLint
```
Parse error on line 1:
[    'a']
-----^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', ']'
```
* Komodo

![image](https://cloud.githubusercontent.com/assets/13005338/8707974/b3a7aa94-2afe-11e5-93e5-7808ff2bb6ef.png)


**Trailing commas**
Forbidden in the JSON spec, allowed in Komodo.
* Code
```json
["trailing", "comma->",]
```
* JSONLint
```
Parse error on line 3:
...    "comma->",    ]
---------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['
```
* Komodo

![image](https://cloud.githubusercontent.com/assets/13005338/8708016/108ff2fc-2aff-11e5-809a-7a5bc863e2d8.png)


**Comments**
Forbidden in the JSON spec.
* Code
```json
//Howdy, folks
["a"]
```
* JSONLint
```
Parse error on line 1:
//Howdy,folks[    
^
Expecting '{', '['
```

* Komodo

![image](https://cloud.githubusercontent.com/assets/13005338/8708044/46d2aabc-2aff-11e5-885c-3dcf1dae8a9d.png)


Other JS-y things are allowed in the editor that aren't JSON.

**Comment by Naatan** [comment]
Ideally we should support an external linter like we do for jslint/jshint.
