### ISSUE TITLE
Goto Definition failing in some JS files

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1270]
### Short Summary

See title

### Steps to Reproduce

Open up https://github.com/Komodo/KomodoIDE/blob/master/src/chrome/komodo/content/dialogs/colorscheme.js#L530

Right click `selectDefaultLanguage` and hit "Go to definition"

### Expected results

It brings me to https://github.com/Komodo/KomodoIDE/blob/master/src/chrome/komodo/content/dialogs/colorscheme.js#L349

### Actual results

It throws an error:

```
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by mitchell-as** [comment]
I'm not able to reproduce this. Then again, I started with a clean codeintel db. What happens when you ctrl+hover over `selectDefaultLanguage`? Do you get the popup below?

![codeintel](https://cloud.githubusercontent.com/assets/12902397/14753254/207cf1f2-08a2-11e6-98cb-8698165dda5f.png)

**Comment by mitchell-as** [comment]
ping @Naatan

**Comment by Naatan** [comment]
No longer able to reproduce this either. I'm guessing this was fixed by another bug.
