### ISSUE TITLE
CodeIntel: Pre-scan project structure and exclude problematic directories

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1272]
Some people use CodeIntel with huge projects. Projects that would take codeintel forever to scan and would eat up far more memory than warranted. We need a way to automatically identify project structures that cause this and exclude them from codeintel.

The idea is that when someone uses Komodo with a project like this we'll give them some sort of heads up warning saying "Your project is too large for Komodo to manage effectively, we've excluded the following directories from being codeintel enabled: ..."

**Comment by mitchell-as** [comment]
This has been added in Komodo 11.
