### ISSUE TITLE
Debugging Perl code using the threads module

### ISSUE THREAD

**Issue by jrheisey** [Komodo/KomodoEdit#1274]
### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by cgchoffman** [comment]
Please file a proper enhancement request with the appropriate fields in the first comment filled out.

**Comment by jrheisey** [comment]
The Komodo IDE  debugger seems to hang after the threads->create() function is called.
Using version 9.3.2, build 88191 on Windows 7 64 bit.
Reference this unresolved forum posting.
http://forum.komodoide.com/t/debugging-perl-script-using-threads-fails/2060

Is this a known limitation?

**Comment by cgchoffman** [comment]
Please file a new bug report with the appropriate fields filled out.
Make sure to include the minimum viable code that will produce the issue for you so we can test here.  Please don't comment on this ticket any more and file a new one.  Sorry for the inconvenience.
