### ISSUE TITLE
Notification pop up with dual icons

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1275]
### Short Summary

I triggered a snippet to auto-abbrev and the notification appears with 1.5 icons for each icon
See screenshot
![capture](https://cloud.githubusercontent.com/assets/655154/14649746/499ff642-061d-11e6-90ef-752682a584e5.PNG)

**Comment by Naatan** [comment]
Fixed in https://github.com/Komodo/KomodoEdit/commit/6e872084665e3fbfc60e6222b2784aa71973a2e1
