### ISSUE TITLE
Some file names are unreadable in Places

### ISSUE THREAD

**Issue by clokep** [Komodo/KomodoEdit#1278]
### Short Summary
Some filenames are not readable in the "Places" list

### Steps to Reproduce

1. Browse to a directory (the ones I've used were all under version control)
2. Some files have a black filename, others have a light blue
3. Click on a file with the black filename, everything is readable (the filename itself goes white, the selection background is blue)! :white_check_mark: 
4. Click on a file with the light blue background, the filename does NOT change color, so you have a blue background and a blue filename. :cry: 

### Expected results

The filename would go white so it's readable.

### Actual results

The filename stays lightblue.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* Komodo IDE, version 10.0.0-alpha1, build 88858, platform macosx. Built on Fri Apr 15 01:43:18 2016.
*Operating System (and version)?* OS X El Capitan :ship:

### Additional Information

![screen shot 2016-04-20 at 11 36 17 am](https://cloud.githubusercontent.com/assets/517124/14680843/b54b5f74-06ec-11e6-987b-cf5dd94a13cf.png)

The selected JavaScript file is normally the same color as "moz.build" right under it. When selected it becomes unreadable.

**Comment by Naatan** [comment]
Thanks @clokep! Luckily I already fixed this one on master :) Should be on the nightly branch soon.
