### ISSUE TITLE
ES6 backticks break on multi-line strings

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1280]
### Short Summary

When using multi-line strings the ES6 backticks do not parse properly (leak until EOF)

### Steps to Reproduce

Open a new JS file with the following content:

```
var world = 'Earth';
console.log(`Hello ${world}\
            !`);
// I should be a comment
```

### Expected results

Last line highlighted as a comment

### Actual results

Last line is highlighted as a string

**Comment by mitchell-as** [comment]
I cannot reproduce this. I tried typing your text and I also saved that text to a file and opened it manually. Both times I get this:

**Comment by mitchell-as** [comment]
I'm not able to reproduce this. I tried typing your text as well as saving it to a file and opening it. Both times I get this:

![jstemplates](https://cloud.githubusercontent.com/assets/12902397/14714137/d0d5c98a-07b1-11e6-85e5-56df3e2e8c71.png)

**Comment by Naatan** [comment]
Seems it doesn't reproduce when you paste the code.

Try selecting the last line and pressing backspace.

**Comment by mitchell-as** [comment]
Yup, that did it. Thanks!

**Comment by mitchell-as** [comment]
You found a bug in Scintilla. I submitted a patch upstream.
