### ISSUE TITLE
PHP phpdoc array type

### ISSUE THREAD

**Issue by garak** [Komodo/KomodoEdit#1282]
### Short Summary

The array annotation with types is not honored.
See https://phpdoc.org/docs/latest/references/phpdoc/types.html#arrays

### Steps to Reproduce

Example script:
```php
<?php

class Foo
{
    public function dummy()
    {
        return;
    }
}

class Bar
{
    /**
     * @return Foo[]
     */
    public function getFoos()
    {
        return $foos;
    }
    
    public function baz()
    {
        $foos = $this->getFoos();
        foreach ($foos as $foo) {
            $foo->dummy();  // this should be auto-completed
        }
    }
}
```

### Expected results

Since `getFoos` method is declaring to return an array of `Foo` objects, I should see an auto-completion for `$foo` variabile inside the foreach loop.

### Actual results

No auto-completion.

### Platform Information

*Komodo Edit or IDE?*  IDE
*Komodo Version?* 9.3
*Operating System (and version)?* Ubuntu 16.04

### Additional Information

None

**Comment by mitchell-as** [comment]
I get the correct autocompletion of "dummy" from `$foo` in the `foreach` loop. It appears this functionality already exists.

**Comment by mitchell-as** [comment]
To be fair I tested this in Komodo X. It's possible support for this was added in another ticket.

**Comment by garak** [comment]
Meanwhile I upgraded to Komodo 10 and I can confirm that it's working. Thanks.

**Comment by mitchell-as** [comment]
Thank you very much for confirming the fix! :)
