### ISSUE TITLE
RxToolkit: Cannot use JavaScript

### ISSUE THREAD

**Issue by mitchell-as** [Komodo/KomodoEdit#1283]
### Short Summary

Open RxToolkit and try to select JavaScript as the language, but Komodo reports that there is no support for it.

### Steps to Reproduce

Open RxToolkit and try to select JavaScript. Komodo reports back that there is no support for it.

### Expected results

I can use RxToolkit with JavaScript. I could do so in 9.x.

### Actual results

Komodo say I cannot.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10
*Operating System (and version)?* Linux

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by Naatan** [comment]
Fixed in https://github.com/Komodo/KomodoIDE/commit/edc7c3dd538901d34ab091d7ca9b21f7d4d2574f
