### ISSUE TITLE
RxToolkit: Selecting Ruby Causes Mayhem

### ISSUE THREAD

**Issue by mitchell-as** [Komodo/KomodoEdit#1284]
### Short Summary

Opening RxToolkit and selecting Ruby causes mayhem. I don't know how to describe it. I get a "phantom" window the size of my screen that appears transparent (no decorations, nothing). I can move this phantom window around, and use Alt+F4 to close it, but I have to reset my profile in order to use RxToolkit again.

### Steps to Reproduce

Open RxToolkit and select Ruby.

### Expected results

I can use Ruby with RxToolkit.

### Actual results

I get the phantom window that I described with no way to use RxToolkit until I reset my profile.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10
*Operating System (and version)?* Linux

### Additional Information

In Komodo 9.x when I select Ruby I get the "Match All Results" bar colored red along with the following error displayed in the RxToolkit results textbox:

```
There is an error in your regular expression: /home/mitchell/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- iconv (LoadError)
	from /home/mitchell/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/mitchell/Komodo-IDE-9/lib/support/rxx/ruby/lib/json/common.rb:2:in `<top (required)>'
	from /home/mitchell/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/mitchell/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/mitchell/Komodo-IDE-9/lib/support/rxx/ruby/lib/json.rb:1:in `<top (required)>'
	from /home/mitchell/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/mitchell/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/mitchell/Komodo-IDE-9/lib/support/rxx/rxx_ruby.rb:13:in `rescue in <main>'
	from /home/mitchell/Komodo-IDE-9/lib/support/rxx/rxx_ruby.rb:9:in `<main>'
```

I think that perhaps the new UI cannot display such error messages and that is causing this phantom window problem.

**Comment by Naatan** [comment]
Fixed in https://github.com/Komodo/KomodoIDE/commit/b77c5ae0d88b8359644be22bf0744255b34d4668
