### ISSUE TITLE
Perl Debugger: Locals view jumps around with a couple dozen variables

### ISSUE THREAD

**Issue by jrheisey** [Komodo/KomodoEdit#1286]
### Short Summary
I have a Perl program with several dozen of constant integer variables initialized in module scope.
The module allocates a couple of complex data types during execution.

Due to the variable names the constants are at the top of the Local view.
However my interest is in the complex data.
While single stepping in the code the Local view update but it also scrolls to the top requiring me to manually scroll and find the specific variable which interests me.

### Steps to Reproduce
Sorry I cannot justify the time it would take to contrive a sample.

I just realized that it may have something to do with having clicked one of the column headers to sort the variables.

### Expected results
I would expect the view to take in consideration of the view's position within the variable list and scroll back to that position after each view update.
This is a real time waster having to find the specific variable each time I single step.

### Actual results
While single stepping in the code the Local view update but it also scrolls to the top requiring me to manually scroll and find the specific variable which interests me.

If I reverse the variable order the view jumps to the bottom of the list.

### Platform Information
Perl 5.8.8
*Komodo Edit or IDE?*  IDE 
*Komodo Version?* Komodo IDE, version 9.3.2, build 88191, platform win32-x86.
Built on Thu Dec 10 11:38:17 2015.
*Operating System (and version)?* Windows 7 64 bit

### Additional Information
* Of course a workaround is to use the Watch view.

 -- eg. Error logs, screenshots, workarounds --

**Comment by mitchell-as** [comment]
Hi, if you click on the variable you are interested in, does that keep the scroll position?

**Comment by jrheisey** [comment]
no

**Comment by mitchell-as** [comment]
Forgive me if you've already contemplated this, but I just realized that the Watch view (in the tab to the left of "Locals") is probably what you want. You aren't dynamically generating variable names right? Add the name of the complex variables you are interested in to the Watch view and they'll update as you step through your program.

**Comment by tonyattwood** [comment]
Hi,

I  just  wanted to  show you my new web page  layout, take a look  here  <http://explore.geneticjunk.com/e4ykzkt>

Faithfully, tony.attwood@ntlworld.com
