### ISSUE TITLE
Places doesnt update on saving project exclude filters

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#129]

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoEdit/issues/93#issuecomment-95297110

The filter was "*.txt" and it worked fine in commando.  Wouldn't that apply to this issue and indicate it's not fixed?

**Comment by Naatan** [comment]
The issue was that Places literally didnt update when you changed the project preferences. That has for sure been fixed, but it sounds like we may be running into an issue which gives a similar broken UX.

**Comment by cgchoffman** [comment]
Ahh ok, the Places does reload.  I'll open a new issue.
