### ISSUE TITLE
View > Line Numbers is inverted

### ISSUE THREAD

**Issue by mitchell-as** [Komodo/KomodoEdit#1290]
### Short Summary

View > Line Numbers is inverted. When I start with a clean profile, View > Line Numbers is checked, but I don't see line numbers. When I uncheck it, I get line numbers.=

### Platform Information

*Komodo Edit or IDE?*  IDE
*Komodo Version?* 10
*Operating System (and version)?* Linux

**Comment by Naatan** [comment]
Did you have line numbers unchecked in the wizard per chance?

**Comment by mitchell-as** [comment]
Yes, that appears to be the default setting.

**Comment by Naatan** [comment]
@cgchoffman can you check that? It should be checked by default.

**Comment by cgchoffman** [comment]
I'm not seeing this with line numbers.  When I accept the defaults from the Startup Wizard (line numbers checked) I have line numbers in my files and it's checked in `view > View Line Numbers`.

BUT, If I do the same with Mini-map (unchecked in wizard), the mini-map is disabled in the editor but it's checked in `view > View minimap`.

@mitchell-as and @Naatan are you guys able to repro this on master?

**Comment by mitchell-as** [comment]
The line numbers appears checked by default now (that changed since this ticket was filed). BUT when you disable line numbers from the wizard, it's still checked in the View menu even though I don't see any line numbers in the editor view.

**Comment by cgchoffman** [comment]
Ahh right.  Ok thanks for clarifying @mitchell-as

**Comment by Naatan** [comment]
I fixed the line numbers in the wizard while I was in there yesterday. The issue there was unrelated to this one.

**Comment by cgchoffman** [comment]
Yep I realize that.  I thought the issue was that it's inverted no matter what.
