### ISSUE TITLE
Need multiple instances of Komodo running on one machine

### ISSUE THREAD

**Issue by jrheisey** [Komodo/KomodoEdit#1291]
### Steps to Reproduce
Have one instance of Komodo running.
Start another from the Windows task bar.

### Expected results
I can think of two scenarios where this is needed.

1. Debugging two paired client and server applications.
2. Comparing the behavior of two versions of the same application.
    - This is what I would like to do at the moment. 
    - I am making significant changes to a complex parsing module.
    - I would like to single step in each version at the same time to determine where my changes are going wrong.

### Actual results
When I try to run a second instance of Komodo no GUI pops up.
I can see it start up and shutdown in task manager.

### Platform Information
*Komodo Edit or IDE?* IDE
*Komodo Version?* Komodo IDE, version 9.3.2, build 88191, platform win32-x86.
Built on Thu Dec 10 11:38:17 2015.
*Operating System (and version)?* Windows 7 64 bit

**Comment by Naatan** [comment]
This already exists. File > New > New Window.

It's not possible to start it by clicking the taskbar icon again, because the window manager will just select the existing window instead.
