### ISSUE TITLE
Mac OSX - Window doesn't expand to fullscreen on green window control button

### ISSUE THREAD

**Issue by zoofood** [Komodo/KomodoEdit#1293]
### Short Summary
If you select the green window button to make the window go full screen, nothing happens.

### Steps to Reproduce
Open Komodo, hit the green X button on the top right hand corner of the window.

### Expected results
Expand to full screen like other apps.

### Actual results
Button highlights (expands slightly) on mouseover, but pressing on it does nothing.

### Platform Information

Komodo IDE, version 10.0.0-alpha1, build 88858, platform macosx. Built on Fri Apr 15 01:43:18 2016
El Capitan 10.11.4

**Comment by Naatan** [comment]
Reproduced. Probably has something to do with OSX maximize technically not being a maximize.

**Comment by Naatan** [comment]
Should be resolved now.
