### ISSUE TITLE
Mac OSX - Crash if close window w/ red X, click on Komodo in the dock and click menu item

### ISSUE THREAD

**Issue by zoofood** [Komodo/KomodoEdit#1295]
### Short Summary
Komodo crashes as the red X button is not quitting the application, just closing the window. 

### Steps to Reproduce
http://screencast.com/t/vyWwYiHmEUds

Close window w/ red X, click on Komodo in the dock and click about menu item, if it doesn't crash right then, it will on some other window open or application menu action.

### Expected results
Quit application completely. No crash.

### Actual results
Crash.

### Platform Information
Komodo IDE, version 10.0.0-alpha1, build 88858, platform macosx. Built on Fri Apr 15 01:43:18 2016
El Capitan 10.11.4

**Comment by Naatan** [comment]
Aaand we got our first blocker! Too bad @zoofood is an activator and thus does not qualify for the reward :p I'll buy you a beer next time I'm in Vancouver though!

**Comment by zoofood** [comment]
First!

**Comment by tonyattwood** [comment]
Hello,

I  have  recently  read  an interesting article  that you may like, please read it,  you  won't regret! Here is the link <http://fair.sbcengr.com/e4kejyop>


Be well, tony.attwood@ntlworld.com
