### ISSUE TITLE
Support for codeigniter codeintel and autosuggest

### ISSUE THREAD

**Issue by harpreetsb** [Komodo/KomodoEdit#1296]
### Short Summary
I have been using codeigniter again and Komodo edit does not seem to gain it codeintell. There are no auto suggestion of its code files or even classes i create.
Previously i found  this solution http://jimdoescode.blogspot.in/2010/10/hooray-for-codeigniter-code-completion.html
But it does not seem to work on komodo 9.

can someone help?

### Platform Information

Komodo Edit, version 9.3.2, build 16460, platform linux-x86_64. Built on Thu Dec
Ubuntu 15.10 

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by Naatan** [comment]
Try using something like:

https://github.com/speilberg0/ci-codeintel-helper

Note that Sublime CodeIntel IS our CodeIntel, someone ported it to Sublime and people are improperly referring to it as Sublime CodeIntel now.

It's unlikely that we will be supporting individual framework autoloading mechanisms. The PHP community itself has realized that each having their own magic is a problem too and are largely moving towards using PSR-4 in their frameworks, which is supported in Komodo 10. CodeIgniter seems to also be going in this direction: http://forum.codeigniter.com/thread-298.html
