### ISSUE TITLE
Minimap highlight split when scrolling

### ISSUE THREAD

**Issue by clokep** [Komodo/KomodoEdit#1298]
### Short Summary
Sometimes I see the highlight of the minimap split into two separate rectangles.

### Steps to Reproduce

1. Open a new file that doesn't have a saved scroll location and has enough lines to scroll (open a file you've never opened in Komodo before)
2. Scroll using the mouse wheel (slowly?)

### Expected results

The minimap highlight scrolls with the document.

### Actual results

The minimap highlight splits in half.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10a
*Operating System (and version)?* Komodo IDE, version 10.0.0-alpha1, build 88858, platform macosx. Built on Fri Apr 15 01:43:18 2016.

### Additional Information

![screen shot 2016-04-25 at 11 59 40 am](https://cloud.githubusercontent.com/assets/517124/14790105/cb011f58-0add-11e6-997e-dd9c8b8896c4.png)

Pressing "Page down" seems to exhibit the same behavior, but it immediately refreshes and fixes itself.

I can't ALWAYS reproduce this, but once I can it happens every time.

I think I've only seen this with Python files, but I'm not 100% on that.

Nothing in the log file looks related.

**Comment by mitchell-as** [comment]
This looks like a drawing artefact. I'm not sure what to make of it. Any ideas @Naatan?

**Comment by clokep** [comment]
Not sure if it's related...but I've also known the minimap is sometimes different widths?

**Comment by Naatan** [comment]
@mitchell-as the minimap preview is done entirely in scintilla iirc. Even the highlight is basically just a scintilla text selection. So I'm afraid you'd be the one to know this one.

I'm not able to reproduce the issue though. @clokep can you reproduce it with a clean profile? Help > Troubleshooting > Restart in safe-mode.

**Comment by clokep** [comment]
@Naatan Yes, I can reproduce on a clean profile.

**Comment by Naatan** [comment]
Could you share a file on which you can reproduce?

**Comment by clokep** [comment]
I was able to reproduce with https://github.com/django/django/blob/4d1c229ee5cb210e8b592a8d9c87d4a66864328e/tests/auth_tests/test_validators.py

Other things I noticed, I was able to reproduce by double clicking on the file in "Places". I'm unsure if you have to open it this way or not to reproduce.

**Comment by mitchell-as** [comment]
I cannot reproduce, but I will look into the minimap code and see if there's something going wrong with selections. That makes a lot of sense @Naatan .

**Comment by Naatan** [comment]
Yeah I can't repro either using a clean profile and the file provided.

**Comment by mitchell-as** [comment]
After looking into this and studying the screenshot in the original post, I conclude this is a drawing artefact. It's true that we use a big block selection in the minimap in order to indicate where you are in the current document, but there is no way Scintilla can make an irregular block selection like the one shown. Also, OSX has been notorious for having graphical glitches now and then.
