### ISSUE TITLE
Searching in current document by enter key doesn't find words in right order

### ISSUE THREAD

**Issue by jamadam** [Komodo/KomodoEdit#130]
Following is the reproducing procedure.

* Hit command-F, 
* Type keyword, 
* Hit enter
* Hit enter
* Hit enter

The application find the keywords in random order. I expect down direction.
"find the next occurance" button and "find the previous occurance" button works as expected.

![2015-04-07 17 22 24](https://cloud.githubusercontent.com/assets/442658/7019419/b1b7493a-dd4a-11e4-8e4a-e81f3339edf9.png)

UPDATE

Forgot to write essential infomation.

MacOSX Yosemite(10.10.2)
Komodo Edit, version 9.0.0, build 15707, platform macosx.
Built on Thu Mar 19 06:08:01 2015.

**Comment by Naatan** [comment]
Could you please provide a test case on which to reproduce this issue? So a sample snippet, cursor starting position and the text to search for.

**Comment by cgchoffman** [comment]
I'm not able to reproduce this, Edit or IDE.

**Comment by jamadam** [comment]
Thanks for looking to this. Here is the detailed procedure.

* Open new file by command+n, paste following snippet

    aaaaaaaa

* move cursor to position[0,0]
* command+F
* type "a" (automatically selects 1st a)
* enter (unexpectedly selects 3rd a)

**Comment by jamadam** [comment]
Additional information here.

The single enter works as if I hit enter twice. And I happen to notice that shift+enter works as opposite direction without the issue.

I'm using macbook pro (early 2015) with US keyboard. The OS is Japanese version with IME but tested with the IME off.

**Comment by Naatan** [comment]
I cannot reproduce this either. Anything else out of the ordinary about your install?

**Comment by cgchoffman** [comment]
Hey Jamadam, kind of a reach but what character encoding is set for the file?

**Comment by jamadam** [comment]
I've tried UTF-8 and ASCII.

**Comment by Naatan** [comment]
Does this happen on all files or just certain ones?

**Comment by jamadam** [comment]
All files.

**Comment by jamadam** [comment]
It also occurs with external keyboards.
With this bug, you possibly overlook half amount of search results and It's critical for me.
I would appreciate it if you could have further investigation.

**Comment by Naatan** [comment]
Are you able to reproduce the problem with a clean profile? https://community.activestate.com/node/15233

**Comment by jamadam** [comment]
Thanks. I just tried the clean profile and could reproduce the bug.

**Comment by Naatan** [comment]
I'm not sure what could be happening. @mitchell-as wanna weigh in?

**Comment by ervumlens** [comment]
@jamadam, could you try these steps to see what happens?

1. Create a new Komodo Javascript macro. Copy in the code from the bottom of this comment.
2. Create a new, empty file.
3. With the new file open, run the macro.

The file should be filled in like this:
```
aaaaaaaaabbbbbaaababa   
^^^^^^^^^     ^^^ ^ ^   
0,1,2,3,4,5,6,7,8,14,15,16,18,20
```

Here's the macro. 

```javascript
//This is a javascript macro to test searches. Run it when an empty file is open.

const body = "aaaaaaaaabbbbbaaababa   ";
let   hits = "                        ";
const token = "a";
const results = [];
const editor = require("ko/editor");
editor.focus();
const scimoz = editor.scimoz();
scimoz.text = body;
scimoz.currentPos = 0;

let oldPos = -1;

function search() {
	scimoz.searchAnchor();
	let newPos = scimoz.searchNext(0, token);
	if (newPos == -1 || oldPos == newPos) {
		return false;
	} else {
		results.push(newPos);
		scimoz.currentPos = newPos + 1;
		oldPos = newPos;
		return true;
	}
}

let i = 0;
while (search() && i++ < body.length){}

for (k in results) {
	let pos = results[k];
	hits = hits.substr(0, pos) + "^" + hits.substr(pos + 1)
}

scimoz.text += `\n${hits}\n${results}`
```

**Comment by Naatan** [comment]
Damn @ervumlens, you beast. I hope you'll consider sending in your resume the next time we're hiring.

**Comment by ervumlens** [comment]
@naatan :blush:

**Comment by Defman21** [comment]
Yeah I want to see @ervumlens in Komodo developers team :stuck_out_tongue:

**Comment by ervumlens** [comment]
@Defman21 Aw, you guys. :smile_cat:

**Comment by jamadam** [comment]
@ervumlens

Thanks. I tried your macro and resulted as you expected.

**Comment by ervumlens** [comment]
Thanks for doing that. 

Could you try running the macro again (same steps), and then afterwards try searching for "a" like you normally would in that file? I.e., search in the new file in the way that causes problems.

**Comment by jamadam** [comment]
@ervumlens  I tried what you said and problem occured.

I also tried MacOSX safe mode with clean Komodo profile and problem is reproduced.
Just to make sure, I also tried newly downloaded Komodo Edit 8(old version) and problem is not reproduced.

**Comment by ervumlens** [comment]
> I also tried newly downloaded Komodo Edit 8(old version) and problem is not reproduced.

@jamadam That's good to know, thanks for taking the time to try it.

@Naatan Random thought: flashback to #403 and the phantom character from the search results, as described in [this comment](https://github.com/Komodo/KomodoEdit/issues/403#issuecomment-119170238):

> It has something to do with the search results.
If a found umlaut in the "Find Results 1" window is pressed, the cursor is positionned between the characters 

In other words, in #403 the search positions the cursor incorrectly based on some mystery criteria. And here we have another search/cursor/criteria thing happening. The problems have their differences, but still :fish:y...

IMO KE 8 is in the clear, and so is scimoz at this point. I don't know a good way to search through just KE 9 changes. The best I can find so far relates to [UTF8 changes in search code](https://github.com/Komodo/KomodoEdit/commit/ee0ce33e441f900ca0270ebf88677aace446cd09#diff-a965a6bff552fe1a604dc50fae90f8bf).

**Comment by mitchell-as** [comment]
Komodo doesn't use Scintilla's built-in search facilities, but slaps on its own interface. Therefore ervumlens' macro will not shed any light on this issue.

I can reproduce this, but only on Mac OSX. I haven't determined the cause yet.
