### ISSUE TITLE
Some scintilla elements use the wrong height

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1303]
### Short Summary

They seem to only have a height of a few px

### Steps to Reproduce

Open snippet properties

### Expected results

Scintilla be a decent height

### Actual results

Scintilla is tiny

**Comment by mitchell-as** [comment]
Userscript settings show the correct Scintilla height. This is probably snippet-specific.

**Comment by Naatan** [comment]
I've seen it in a few other places too. I suspect we just need to be explicit about editor height.
