### ISSUE TITLE
OSX: First Start Wizard Shows Close/Minimize/Maximize Window Buttons on Both Sides

### ISSUE THREAD

**Issue by mitchell-as** [Komodo/KomodoEdit#1307]
### Short Summary

The first start wizard on OSX shows the window buttons on both left and right sides.

### Steps to Reproduce

Clean profile on OSX and start Komodo.

### Expected results

The wizard has the window buttons on the left, as with traditional OSX windows.

### Actual results

There are window buttons on both sides.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10
*Operating System (and version)?* OSX

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by Naatan** [comment]
It does appear to load, but takes a LONG time to do so.
