### ISSUE TITLE
Uninstalling add-on dialog has wm decorations even if it's disabled

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1314]
### Short Summary

the title

### Steps to Reproduce

Open Commando and try to uninstall any add-on. You'll get a prompt that has both wm and Komodo's decorations.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10
*Operating System (and version)?* Ubuntu 16.04

**Comment by Naatan** [comment]
This should be fixed.
