### ISSUE TITLE
js console: code hints are lost under the toolbar and scintilla

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1315]
### Short Summary

I can't see some of the code suggestions as I'm writing in the js console as they are hidden by everything above the js console
### Steps to Reproduce

open the js console pane
type some code that will give you code hints long enough to exceed the height of the js console pane
### Expected results

hints to be over top of all ui
### Actual results

The list that is outside the jsconsole cannot be seen as it's blocked by the tool bar and editor above
### Additional Information

![capture](https://cloud.githubusercontent.com/assets/655154/14868293/bc44f480-0c81-11e6-85ef-fffafe15aad9.PNG)

**Comment by Naatan** [comment]
This is because your bottom pane is too small for it to fit. I'll see if I can easily fix it but it's not worth a lot of effort if not imo.

**Comment by Naatan** [comment]
Not a new bug btw, this should happen in 9 as well.

**Comment by tonyattwood** [comment]
Hi,

I'd like to invite you to  my party, it's gonna be  a surprise  for my family, here is  the invitation <http://expert.pinardelsol.info/e4tjq>


See you around, tony.attwood@ntlworld.com
