### ISSUE TITLE
Some dialogs have a drop shadow when opened without OS decorations

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1318]
### Short Summary

SOme dialogs, I believe the ones that originate from `ko.dialog.alert` or maybe a higher level are drawn with a large drop shadow when OS decorations are not turned on.

### Steps to Reproduce

Turn off OS decorations
Open a file and edit it but don't save
Close the file to trigger the "do you want to save?" dialog.

### Expected results

Not an ugly window

### Actual results

An ugly window

### Platform Information

I'm seeing this on Windows but I note that on OSX there is a shadow around the dialog but it's nice.  It's shaded properly.  The issue on windows is that it's just a large black area under and to the side of the window.

### Additional Information

![capture](https://cloud.githubusercontent.com/assets/655154/14871082/e2b88156-0c93-11e6-9918-c96deaeba553.PNG)

**Comment by cgchoffman** [comment]
![screenshot at 16-21-45](https://cloud.githubusercontent.com/assets/655154/14871161/bb9c75ea-0c94-11e6-859c-0ac7d75f3fb7.png)
Pretty borders in OSX.

**Comment by Naatan** [comment]
Yep. I have not seen this on Linux.

Odd that it only does it for some windows on Windows. Maybe modal dialogs only?

**Comment by cgchoffman** [comment]
I think it's interesting that the area that the black area covers on Windows is almost identical in area to the OSX shadow but as I said earlier today, I couldn't find anything related to shadows in the DOMi CSS rules of Computed Styles.

**Comment by tonyattwood** [comment]
Hi,

I know  you're gonna  be surprised by that news, just take  a look <http://explore.outten.com/e4pramgu>

Very truly yours, tony.attwood@ntlworld.com
