### ISSUE TITLE
Startup Wizard pushes close button partially off screen

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1319]
### Short Summary

Windows only I believe but haven't tested on Linux.  The Close button is pushed off the screen.  See screenshot

### Steps to Reproduce

Start Komodo with clean profile

### Expected results

Start up wizard have full close button

### Actual results

only half the close button is showing.

### Additional Information

![capture](https://cloud.githubusercontent.com/assets/655154/14871638/ff1280cc-0c98-11e6-82c4-b3d776a7f489.PNG)

**Comment by Naatan** [comment]
Should be fixed.
