### ISSUE TITLE
Prefs dialog disappears when opened

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1320]
### Short Summary

I've managed to make the prefs dialog disappear and never want to reappear.

### Steps to Reproduce

Turn off window decorations
open the prefs dialog
minimize the prefs dialog
close it (in the task bar or something)
try to open the prefs dialog again

### Expected results

The prefs dialog to open

### Actual results

The dialog briefly appears in the top right corner of the screen then disappears.  If you hover over KOmodo in the Taskbar you'll see if as a short dialog (not the proper height of the prefs dialog) and when it's clicked nothing happens.

### Platform Information

I think this is Windows only.  I can't get my self into this scenario on OSX.

**Comment by Naatan** [comment]
I need to make sure the window restoration code checks if the window is on-screen.

**Comment by cgchoffman** [comment]
Isn't this handled by and existing service?  Or are you gradually wanting to redo this stuff as we move forward?

**Comment by Naatan** [comment]
It is, but because I am disabling the window decorations this service does not run, so I have to re-implement it.. sort of.

**Comment by cgchoffman** [comment]
Confirmed @Naatan, looks good on Windows.
