### ISSUE TITLE
Updates dialog is just...wrong

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1321]
### Short Summary

I think the Komodo updates dialog is gone.  I can't be sure because I can't actually see the entire dialog that is shown now but what I do see isn't our dialog.  See screenshot.

### Steps to Reproduce

Install one of the nightlies that is not the latest one: http://downloads.activestate.com/Komodo/nightly/komodoide/2016/04/
Check for updates

### Expected results

Just the classic updates dialog

### Actual results

I don't think this is an issue on OSX since I tested that this morning for another bug report.

This is what it looks like on Windows:
![capture](https://cloud.githubusercontent.com/assets/655154/14872097/c4006ada-0c9d-11e6-94e6-db3b1267c4a6.PNG)

**Comment by lagbox** [comment]
I have the same issue, updated to 88986 and it is still there.

**Comment by Naatan** [comment]
This was fixed in https://github.com/Komodo/KomodoEdit/commit/b70c7beba8d99db8b4f6e49682db4064f089d7ab and should be in the next nightly.

**Comment by lagbox** [comment]
You guys rock :)
