### ISSUE TITLE
"Go back" button reopens closed tabs

### ISSUE THREAD

**Issue by h2ad2** [Komodo/KomodoEdit#1322]
### Short Summary
See title

### Steps to Reproduce
1. open a few tabs (2 or 3)
2. close the tabs by pressing the x-marker
3. press the menu button "Go back one location" (icon: left arrow)

### Expected results
1. tabs NOT reappearing 
2. menu button dimmed

### Actual results
1. menu buttun should be dimmed, indicating there is nothing to go back to
2. tabs reappear

### Platform Information
Komodo Edit, version 9.3.2, build 16460, platform win32-x86.
Built on Thu Dec 10 22:21:38 2015.

### Additional Information
(none)

**Comment by mitchell-as** [comment]
To me this feels like "by design", but @Naatan or @cgchoffman would be the authority on this one.

**Comment by Naatan** [comment]
Indeed, this is by design. I don't see how not allowing you to press back would be an improvement.
