### ISSUE TITLE
Indent entire line with an indent command

### ISSUE THREAD

**Issue by lagbox** [Komodo/KomodoEdit#1323]
### Short Summary
(Ctrl + ]) currently will indent from the position of the cursor. Would be nice to have an option to have it indent the entire line regardless of the position of the cursor.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10 Alpha
*Operating System (and version)?* Ubuntu 15.10

### Additional Information
I added a macro to do this that gets the position of the cursor and line length, calls a home + indent, then moves the cursor to the position it was plus the difference in line length. For indent and unindent respectively.

**Comment by Naatan** [comment]
Thanks @lagbox, great idea :)

To be clear this would be a new command, we're not changing the way the current command works.

**Comment by cgchoffman** [comment]
+1.  nice suggestion.  I actually run up against this often.

**Comment by lagbox** [comment]
@cgchoffman I can put the 2 macros into a gist if you want, may not be pretty but they work

**Comment by cgchoffman** [comment]
> I can put the 2 macros into a gist if you want

You'd be doing me a double solid if you add it here: https://github.com/Komodo/macros

**Comment by Naatan** [comment]
Don't add it there, that repo is deprecated. If you want to submit userscripts use the instructions here:

http://komodoide.com/packages/submit-instructions/#pane-packages

**Comment by lagbox** [comment]
This is what I put together [Gist - indent/unindent entire line(s), respecting position change](https://gist.github.com/lagbox/ceb20645980eed9dc16c63789546e9af)

Ill add a repository when I get a chance and submit it.
