### ISSUE TITLE
ssh connect error

### ISSUE THREAD

**Issue by i-code59** [Komodo/KomodoEdit#1324]
### Short Summary
failed to load files after successful login.  successful login on multiple servers except just this one.  Komodo 8 is successful on this one server.
reported exception is :
File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\paramiko\transport.py", line 731, in open_channel
    raise e
 OverflowError: Python int too large to convert to C long

### Steps to Reproduce
connect to server

### Expected results
file list

### Actual results
failed connection

### Platform Information
KomodoIDE 9.3

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoEdit/issues/252#issuecomment-187463877
Dup
