### ISSUE TITLE
no window decor: Full screen on Windows covers task bar

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1329]
### Short Summary

Making Komodo full screen on Windows with no OS decorations will cover the task bar

### Steps to Reproduce

Turn off window decorations
maximize the window

### Expected results

Taskbar accessible

### Actual results

Is not accessbile

### Platform Information

*Operating System: Windows*

**Comment by Naatan** [comment]
Dupe of #1206?

**Comment by cgchoffman** [comment]
Nope, they seem to be the opposite. #1206 is that you can't see the bottom of Komodo.  This is that you can't see Windows Taskbar....oh wait...That means that #1206 is fixed.

**Comment by tonyattwood** [comment]
Hello,
I thought you might like the stuff I  found by chance, it seems  so exciting and unusual, please take  a look  here  <http://example.skylineworldtravel.com/e4wbfq>
Rushing, tony.attwood@ntlworld.com
