### ISSUE TITLE
Debug output is showing a breakput margin

### ISSUE THREAD

**Issue by dallmon** [Komodo/KomodoEdit#133]
1. Clicking on the resize area between the locals and the error pane when the cursor is a resize cursor raises a growl that says "Breakpoint margin click ignored - Errors is not a debuggable language."

2. Merely moving the cursor over the breakpoint margin then resizes the errors pane, even if Komodo does not have focus.

Komodo IDE, version 9.0.0, build 87165, platform macosx.
Built on Tue Mar 24 18:39:57 2015.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoIDE/commit/109668cc565cd80352c2dc1897631ed82d68c917
