### ISSUE TITLE
Komodo restores old workspace windows when it shouldn't

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1330]
### Short Summary

Not sure how i got into this state but every time I start Komodo now it restarts two windows, neither of which reflect my workspace when I shutdown Komodo
### Steps to Reproduce
- Ask me for my 10.10.10.zip profile folder
- Start Komodo with that profile

Prefs > Workspace > When starting Komodo: Restore last workspace.  With the legacy workspace code this should only restore one window.  Should start looking there.
### Expected results

Komodo to start with my last working project and files open.
### Actual results

Komodo opens two windows:
- one with just the new tab
- one with a random log file i saved while testing bugs.  Files is called `broken-prefs-window.txt`
### Additional Information

Here is the relevant info from the prefs file: [workspace-prefs.txt](https://github.com/Komodo/KomodoEdit/files/241621/workspace-prefs.txt)
Note the first two Preference-sets.  One has no files (newtab window) and the other has the file mentioned above.
Also note that I can't reproduce the issue with the prefs.xml file alone (I'm not talking about the file above).  You have to use the entire profile i mentioned in the repro steps.

**Comment by Naatan** [comment]
I fixed this earlier today, are you up to date?

**Comment by cgchoffman** [comment]
Should be, yes.  I confirmed with my local bukd before filing.  I originally found it in the nightly from yesterday.

**Comment by cgchoffman** [comment]
Confirmed this morning, i'm up to date and can repro with a specific profile.

**Comment by Naatan** [comment]
And this isn't a new bug?

**Comment by cgchoffman** [comment]
I have no idea if this is related to changes in Komodo 10 so I don't know if it's "new".

**Comment by Naatan** [comment]
Can you reproduce it on 9?

**Comment by cgchoffman** [comment]
Oh...yes. So not new.

**Comment by cgchoffman** [comment]
This should be resolved with the updates made to the restore system.
