### ISSUE TITLE
Can't copy/cut lines with no select

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1333]
### Short Summary

You should be able to hit cut/copy with no selection and have the entire line (including EOL char at the end of current line) added to the clipboard

### Steps to Reproduce

Put your cursor on a line with no selection
copy or cut

### Expected results

entire line added to clipboard

### Actual results

nothing happens

**Comment by Defman21** [comment]
I'm not able to reproduce it on Linux, build 88986.

**Comment by cgchoffman** [comment]
Not able to repro with a fresh profile with local build either.  Tried changing key binding settings in broken instance just to see but had no effect.

**Comment by Naatan** [comment]
So is this still an issue?

**Comment by mitchell-as** [comment]
No, I cannot reproduce this.

**Comment by cgchoffman** [comment]
My local build is not doing this.  Can someone else try this on Windows?

**Comment by Naatan** [comment]
Tested on windows. Seems to work fine for me.
