### ISSUE TITLE
Filemerge Still Pops Up Every Time a VCCS function is called

### ISSUE THREAD

**Issue by andresrs** [Komodo/KomodoEdit#1334]
Following on the #1332 issue: I think that's I was doing. I set up the ~/.subversion/config file to use Filemerge. It seems that Komodo is calling `svn diff` internally either on the trunk, or on the opened files, when there's no need for a diff. For example, the new *Check for status changes from outside of Komodo* functionality could be using `svn status` instead of the `svn diff`. All this happens regardless of the status of the *Uses an external diff tool* option.

Interestingly, I don't have this problem with Komodo IDE 9.

**Comment by Naatan** [comment]
Please don't open new bug reports. You can still comment on closed bugs.

Komodo performs a diff via the new Version Control widget in your bottom panel. `svn status` would not be an alternative solution for this.

If you have further concerns about the imlpementation please add them to ticket #1332.

**Comment by tonyattwood** [comment]
Hey,

I've  read a nice short story a couple of days ago, you're gonna love it, that's  for  sure! Here it is <http://example.kargobiz.com/e4vttwad>

Pardon my monkey thumbs, tony.attwood@ntlworld.com
