### ISSUE TITLE
Unindent deletes selection

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1336]
### Short Summary

Unindent can delete the selection if you do not select to the start of the line.

### Steps to Reproduce

Create a new file, paste in the following contents:
```
        test
```

Select the line from end to 4 spaces before the start, then perss the unindent shortcut.

### Expected results

Line is unindented.

### Actual results

Selection is deleted.

**Comment by mitchell-as** [comment]
This is not new. It happened in Komodo 9 and is default Scintilla behavior. A new command like the one in #1323 should be created for the behavior you are describing.
