### ISSUE TITLE
Feedback on 3rd "Let's Get Started" window

### ISSUE THREAD

**Issue by we3geeks** [Komodo/KomodoEdit#1340]
![ki10-20160430d](https://cloud.githubusercontent.com/assets/2390335/14938457/57eda790-0ee1-11e6-9fa4-6111a1d421c1.png)

Wording on the third "Let's Get Started" window feels awkward. It seems like it should be either "... to access all of Komodo's preferences." or "... to access Komodo Preferences." It feels like were stuck somewhere between referring to preferences in general and referring to Komodo's "Preferences" UI.

**Comment by mitchell-as** [comment]
I agree the wording could be better. For what it's worth, the grammarian in me wants "in order to access" instead of "to access".

**Comment by Naatan** [comment]
I'll change it to what @mitchell-as suggested. It doesn't feel awkward to me either way but then English isn't my first language, so thanks for noticing! :)
