### ISSUE TITLE
Komodo IDE 10 does not retain "tab" ordering in the right pane

### ISSUE THREAD

**Issue by we3geeks** [Komodo/KomodoEdit#1341]
Note sequence of "tabs" in right pane, in particular the positioning of the "Open Files" tab:
![ki10-20160430e](https://cloud.githubusercontent.com/assets/2390335/14938525/72105652-0ee3-11e6-9590-e1baf85c01e2.png)

After exiting and restarting, sequence of right pane tabs is different ("Open FIles" is at the extreme right, instead of the extreme left, within the right pane:
![ki10-20160430f](https://cloud.githubusercontent.com/assets/2390335/14938537/b24bf3fc-0ee3-11e6-9eea-4adf689039a5.png)

**Comment by mitchell-as** [comment]
Might this be a workspace restore issue @cgchoffman? I'm not sure if this was bugged in previous versions of Komodo, so I didn't label as "new". Feel free to re-tag as necessary.

**Comment by Naatan** [comment]
This definitely isnt a new bug. Something to consider when we consolidate workspace.js into workspace2.js

**Comment by cgchoffman** [comment]
This is likely fixed by this fixed: https://github.com/Komodo/KomodoEdit/commit/ee2f184d2650037f12c7841727f9b88506e96c9d
There is a build ready for testing here:
 http://downloads.activestate.com/Komodo/nightly/

**Comment by we3geeks** [comment]
Appears to still be an issue in Komodo IDE. Please consider re-opening.

I can drag the tabs into a different order (e.g., Open Files as the left-most tab) in the right pane but that order does not stick after quitting and restarting.

Build Info: Komodo IDE, version 10.1.0, build 89382, platform macosx. Built on Wed Aug 3 01:53:04 2016.

**Comment by mitchell-as** [comment]
I confirm that tab order is still resetting upon restart. It doesn't matter which pane I try and re-order tabs in -- they still return to their stock positions when I restart Komodo.

**Comment by cgchoffman** [comment]
Well that's frustrating.  The ui saves the fact that tabs are stacked (ie. adding open files to the Places widget) but it doesn't save the order that tabs appear :S

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoEdit/commit/e6d04b8020ddf07e49bdf1a0529184b44edbddce
