### ISSUE TITLE
Komodo IDE 10 does not honor or retain "View > Toolbars > Show Editor Tabs" setting

### ISSUE THREAD

**Issue by we3geeks** [Komodo/KomodoEdit#1342]
Toggling "View > Toolbars > Show Editor Tabs" does nothing (editor tabs are still shown), and after exiting with that setting NOT checked and then restarting, Komodo restarts with it again checked.

**Comment by we3geeks** [comment]
Likely a partial duplicate of #1231, although that one does not touch on whether the setting is appropriately retained after stopping and restarting Komodo.

**Comment by mitchell-as** [comment]
This seems to have been fixed by #1231 as I'm not able to reproduce in master.
