### ISSUE TITLE
Komodo IDE v10 not installed with v10 samples in Toolbox

### ISSUE THREAD

**Issue by we3geeks** [Komodo/KomodoEdit#1343]
![ki10-20160430g](https://cloud.githubusercontent.com/assets/2390335/14938611/45c87590-0ee6-11e6-9619-3d73c2a47d12.png)

Previous versions of Komodo have always installed an updated set of sample macros/snippets/userscripts in the Toolbox, and moved the previous version's to the "Obsolete..." section. Installing v10 left v9.1's as the current set?

**Comment by Naatan** [comment]
This is by design. As of version 9.3 (IIRC) we do not import samples anymore if you are not doing a fresh install of Komodo. The samples are only to help you get started, they're not something that needs to persists with every single update.
