### ISSUE TITLE
Komodo IDE v10 UI inconsistent use of radio buttons vs. checkboxes

### ISSUE THREAD

**Issue by we3geeks** [Komodo/KomodoEdit#1344]
The UI used to specify the file type uses checkboxes:
![k10-20160420a](https://cloud.githubusercontent.com/assets/2390335/14939578/daa6ec1e-0f09-11e6-8725-2b3a97bec534.png)

... whereas the UI for specifying the match-type in the UI for "find" capability uses the more appropriate radio-button:
![k10-20160420b](https://cloud.githubusercontent.com/assets/2390335/14939589/0cc523c8-0f0a-11e6-9171-d6dcd181870b.png)

Of these two, the use of checkboxes for specifying the file type feels wrong, since by definition a file can be of only one type.

**Comment by Naatan** [comment]
Actually they have always been checkboxes. It appears the styling used in previous versions made it irrelevant though.
