### ISSUE TITLE
Selection+foreground color in Komodo v10 default color scheme leaves selected text invisible

### ISSUE THREAD

**Issue by we3geeks** [Komodo/KomodoEdit#1345]
The "find" text, using the default color scheme leaves selected text in certain contexts basically invisible against the selection-background color:
![k10-20160420c](https://cloud.githubusercontent.com/assets/2390335/14939604/b6e63086-0f0a-11e6-88e3-6589633d6bdf.png)

(Same issue noted in a different context in #1339)

**Comment by we3geeks** [comment]
Another example:
![k10-20160502b](https://cloud.githubusercontent.com/assets/2390335/14953727/8f06fb66-1029-11e6-8a6d-c9f834257b58.png)

**Comment by cgchoffman** [comment]
I'm not seeing this.  The background text is blue and highlighting is white.  I can see the text fine. Build 89034 and my local build. 
![capture](https://cloud.githubusercontent.com/assets/655154/14969329/a4e5b2cc-1076-11e6-8aa1-621437050acd.PNG)

**Comment by cgchoffman** [comment]
@Naatan @mitchell-as are either of you getting this?

**Comment by Naatan** [comment]
@cgchoffman your OS colors don't create the same issue as @we3geeks is getting. The issue here is that the OS is setting the selection colors, we want to be setting these ourselves instead. See https://developer.mozilla.org/en-US/docs/Web/CSS/::selection

**Comment by tonyattwood** [comment]
Hello,

I've been looking for some  stuff when by chance I found  that! It's so sad, please read ant tell me what  you  think  <http://favor.pregnancyjuice.com/e4zzrro>


Best Wishes, tony.attwood@ntlworld.com
