### ISSUE TITLE
Button with no label in Add Command window

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1349]
### Short Summary
Right to "Help" button
![pic](http://i.imgur.com/e8e7Pwj.png)

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10
*Operating System (and version)?* Ubuntu 16.04 with Openbox

**Comment by mitchell-as** [comment]
I'm not seeing this in master, so it was probably fixed.

**Comment by Naatan** [comment]
@Defman21 if you still see this can you run DOM Inspector on the element?

**Comment by Defman21** [comment]
Yep.

**Comment by Defman21** [comment]
I don't see this anymore :|

**Comment by Defman21** [comment]
Well If I detect it again I'll run DOM Inspector.

**Comment by Defman21** [comment]
Ahh it's just invisible. What info do you need from DOM Inspector?

**Comment by Defman21** [comment]
The tree: 
```
<xul:button xmlns:xul="http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul" dlgtype="extra2" class="dialog-button" hidden="true"/>
|- <xul:hbox xmlns:xul="http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul" class="box-inherit button-box" xbl:inherits="align,dir,pack,orient" xmlns:xbl="http://www.mozilla.org/xbl" align="center" pack="center" flex="1" anonid="button-box"><xbl:children><xul:image class="button-icon" xbl:inherits="src=image"/><xul:label class="button-text" xbl:inherits="value=label,accesskey,crop"/></xbl:children></xul:hbox>
|-- <xul:image xmlns:xul="http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul" class="button-icon" xbl:inherits="src=image" xmlns:xbl="http://www.mozilla.org/xbl"/>
|-- <xul:label xmlns:xul="http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul" class="button-text" xbl:inherits="value=label,accesskey,crop" xmlns:xbl="http://www.mozilla.org/xbl"/>
```

**Comment by Naatan** [comment]
Are you sure you're selecting the element in your screenshot? Like you said it's invisible, that should mean you cannot see or select it in the UI (I cannot).

**Comment by Defman21** [comment]
I sure. I remember some of the properties of the button in screenshot and
they are the same as the one I posted

**Comment by Defman21** [comment]
It was visible for some reason but now it's not

**Comment by Naatan** [comment]
So you're no longer able to reproduce the issue?

**Comment by Defman21** [comment]
Yes, but what is this button?

**Comment by Naatan** [comment]
It's a placeholder button that dialogs can use.

**Comment by tonyattwood** [comment]
Hi,


I've  watched a really great movie a couple  of days ago, it  inspired mea lot, you may watch  the trailer here <http://esteem.treataf.org/e4trxue>

tony.attwood@ntlworld.com
