### ISSUE TITLE
Duplicate line up/down duplicates to right with partial selections

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1353]
### Short Summary

See title

### Steps to Reproduce

Select part of a line (not the entire line) and invoke the command to duplicate the selection up or down.

### Expected results

Selection is duplicated above or below the current line.

### Actual results

Selection is duplicated to the right of the current selection.

**Comment by mitchell-as** [comment]
I cannot reproduce this. I have the following buffer contents:

```
1
2 foobarbaz
3 
```

I highlighted `bar` and used commando to invoke the "duplicateUp/Down" commands. Both times I get the duplication happening on the current line.

**Comment by mitchell-as** [comment]
This is by design. Partial selections should be duplicated to the left and right.

**Comment by mitchell-as** [comment]
Note to self: only the selection should be duplicated to the line above/below.

**Comment by Naatan** [comment]
Note that this command duplicates the current line if no selection was made. This should not change.

**Comment by tonyattwood** [comment]
Hi,

I've  read a lovely book recently, the author is admired by  everyone, you should read the  book  too, that's for sure,  here is the  link  <http://effort.shawnforry.com/e4ekr>

Regards, tony.attwood@ntlworld.com
