### ISSUE TITLE
Places > Projects > coloring of project names isn't clear.

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1354]
### Short Summary

I've meant to file this for a while but forgot :(  I don't understand the styling of project names in Places any more.  See the screenshot below.

Things to note about the screenshot:
1. There is NO OPEN project.
2. No project has been opened since starting that session of Komodo

![capture](https://cloud.githubusercontent.com/assets/655154/14965361/f145ef34-1061-11e6-8122-632f3d461a24.PNG)

So given that image and the notes above, I don't understand what the styling is trying to tell me.  This might just be a bug in the styling too and no messaging is intended at all.

**Comment by Naatan** [comment]
They're styled according to their SCC status. But this status isn't appropriate for projects atm, we should just remove it (for Projects that is).

**Comment by Naatan** [comment]
Fixed with https://github.com/Komodo/KomodoIDE/commit/e4f7c8be11bb88a7e7fff455b8bafd57a61f268a

**Comment by tonyattwood** [comment]
Hello,

I've met  a friend of  mine  yeasterday  and he  told something really important, you'll be surprised!  Read more about  it here <http://esteem.treataf.org/e4vjsygp>


tony.attwood@ntlworld.com
