### ISSUE TITLE
scc History dialog too small for content

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1358]
### Short Summary

The Window is OK at first but then the content is loaded into the dialog and you lose the close buttong and the commit content is cut off.  See screen shot.

### Steps to Reproduce

Open a file under SCC 
right click file tab and select Source Code Control > History of file

### Additional Information

 
![capture](https://cloud.githubusercontent.com/assets/655154/14968600/6f891582-1072-11e6-9f80-b2c86cbc4737.PNG)

**Comment by Naatan** [comment]
Fixed with ea142efc9a9defc36828a60d889ca8d3699cc54c
