### ISSUE TITLE
cannot close panels

### ISSUE THREAD

**Issue by neurobashing** [Komodo/KomodoEdit#1359]
### Short Summary
Panels (places, etc) cannot be closed once opened

### Steps to Reproduce
Open any pane (left, right, or bottom) via keystroke or toolbar button

### Expected results
The panel closes.

### Actual results
Nothing happens.

### Platform Information

Komodo IDE, version 10.0.0-alpha1, build 89034, platform macosx.
Built on Mon May 2 01:56:48 2016.

### Additional Information

-- EXCEPTION START --
TypeError: xtk.domutils is undefined
+ stack
    uilayout_togglePane@chrome://komodo/content/library/uilayout.js:539:1
    handlers.cmd_viewLeftPane@chrome://komodo/content/library/controller.js:13:36
    broadcasterController.prototype.doCommand@chrome://komodo/content/library/controller.js:113:20
    command_doCommand@chrome://komodo/content/library/commands.js:239:1
    command_doCommandAsync/<@chrome://komodo/content/library/commands.js:196:13
-- EXCEPTION END --
[2016-05-03 10:35:26,552] [ERROR] uilayout: 
-- EXCEPTION START --
TypeError: xtk.domutils is undefined
+ stack
    uilayout_togglePane@chrome://komodo/content/library/uilayout.js:539:1
    handlers.cmd_viewLeftPane@chrome://komodo/content/library/controller.js:13:36
    broadcasterController.prototype.doCommand@chrome://komodo/content/library/controller.js:113:20
    command_doCommand@chrome://komodo/content/library/commands.js:239:1
    command_doCommandAsync/<@chrome://komodo/content/library/commands.js:196:13
-- EXCEPTION END --

**Comment by Naatan** [comment]
xtk.domutils should never be undefined. Can you share your full error log?

**Comment by neurobashing** [comment]
safe mode does indeed solve the problem. When in safe-mode anyway. Rogue extension? 

Full log at https://gist.github.com/neurobashing/b88e0a2b5f9ff164960106422b17f1ad

**Comment by Naatan** [comment]
Could be. Do you have addons installed? Could you try Help > Troubleshooting > Restart Without Addons.

Also - does this issue happen when starting with only a single Komodo window?

**Comment by neurobashing** [comment]
restarting without add-ons fixes it, too. yes, it happens with a single komodo window.

**Comment by neurobashing** [comment]
hmm also fwiw Commando doesn't work. is there a flag to open it w/o doing a migration, and installing a totally fresh profile?

**Comment by neurobashing** [comment]
Ok removed HTML Tools and Git Branch (argh!) and that seems to have fixed it. Guess I need to update it to 10 anyway ... marking fixed and closed I guess.

**Comment by Naatan** [comment]
Did you manually install those after updating? The new update process should not have included addons that were not compatible.

**Comment by Naatan** [comment]
> hmm also fwiw Commando doesn't work. 

Can you report a bug on this?

**Comment by neurobashing** [comment]
nope, those were not installed, they were included. I'll report an issue. (Commando fixed itself when I removed them as well)
