### ISSUE TITLE
find all again seems to ignore regex

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#1362]
### Steps to Reproduce
1. find some text with regex with Find All in files
2. wait for the results to appear, make sure you get some
3. click the find again button in the find results tab (magnifier icon)
4. no results

### Expected results
the very same results as at 2)

### Platform Information
Komodo IDE, version 9.3.2, build 88191, platform linux-x86_64. Built on Thu Dec 10 13:00:48 2015.

**Comment by mitchell-as** [comment]
You need to put the focus in the textbox and press "Enter" again. Clicking the find icon is not sufficient.
