### ISSUE TITLE
new find / replace pane clipboard woes

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#1363]
### Short Summary
In short you can't really copy paste text to the new *replace* pane because as soon as it looses focus it goes away and does not remember values.

### Steps to Reproduce
1. shift+ctrl+h (replace in files)
2. enter some text to find
3. click in the editor, select some text (trying to grab the replacement)
4. find/replace pane closes, same happens if KO looses focus
5. shift+ctrl+h (replace in files) again, text entered at 2) is gone

### Platform Information

Komodo IDE, version 9.3.2, build 88191, platform linux-x86_64. Built on Thu Dec 10 13:00:48 2015.

**Comment by mitchell-as** [comment]
Hi, you can use Preferences > Find > Pin the Find Frame to prevent the pane from disappearing on focus lost.

**Comment by Naatan** [comment]
Note this issue has been entirely resolved in Komodo 10.
