### ISSUE TITLE
Komodo v10 UI polish: Inconsistent alignment of controls on Preferences panels

### ISSUE THREAD

**Issue by we3geeks** [Komodo/KomodoEdit#1365]
### Short Summary
Labels and their corresponding controls on the Appearance panel within Preferences window are inconsistently vertically aligned. Look, for example, at the alignment of the controls and their labels in the upper "Interface" panel vs the controls and their labels in the "Side Panes Layout" panel in the attached screenie.

### Expected results
Consistent alignment 

### Actual results
Inconsistent alignment...

### Platform Information
Komodo IDE, version 10.0.0-alpha1, build 88986, platform macosx.
Built on Wed Apr 27 01:55:56 2016.
### Additional Information

 -- eg. Error logs, screenshots, workarounds --
![k10-20160503b](https://cloud.githubusercontent.com/assets/2390335/15013019/24d5e6ac-11ba-11e6-867c-83a2ba433f8c.png)

**Comment by Naatan** [comment]
@cgchoffman the labels parent boxes need an align="center" attribute.

Don't try to fix this with normalize.less, the effects would be too far reaching.

**Comment by cgchoffman** [comment]
@we3geeks do you mind if we change this bug from "fix Appearance prefs" to "Fix all prefs panes in this fashion"?

**Comment by Naatan** [comment]
@cgchoffman go for it.

**Comment by tonyattwood** [comment]
Hey,

I think I've got a  really pleasant surprise for you, you'll like it  I swear <http://enjoy.recentlysoldhomes.info/e4dun>

Sincerely, tony.attwood@ntlworld.com
