### ISSUE TITLE
Slash vs Question mark on Code -> Un-comment region

### ISSUE THREAD

**Issue by kostadinnm** [Komodo/KomodoEdit#1369]
Code -> Un-comment region help text shows Ctrl + Shift + ?, which seems ambiguous to me. All the shortcuts(keybindings) on programs I used show the base key, which is slash('/').

The helptext is within the 'Code'-menu and on Edit->Preferences->Keybindings->Un-comment region command as well.

Maybe the slash('/') will be easier for the users.

It shown as if the user pressed the Shift-key twice, because the question mark('?') is a result of Shift + slash('/')

### Platform Information

*Komodo Edit
*Version 9.3
*Operating System - Windows 10

### Additional Information

![2016-05-04 18_01_26-komodo_preferences](https://cloud.githubusercontent.com/assets/18436405/15018879/3ebb905c-1224-11e6-94d1-de33efb62f12.png)

**Comment by Naatan** [comment]
I'm afraid this is simply a limitation of our keybinding system. Can it be fixed? Yes, but the implications of fixing it (both in terms of time spend and fallout from the change) would far outweigh the severity of the issue itself. As such I'm going to close this, I'm sorry.

**Comment by kostadinnm** [comment]
Too bad. Just one more question - is it present on Komodo IDE as well?!

**Comment by Naatan** [comment]
Yes, this would be a bug in both edit and IDE.
