### ISSUE TITLE
Per-file indentation is always 4

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1372]
### Short Summary

With the latest nightly, my Per-file indentation is always 4/4 even if in my preferences it set to 2/2 and Allow File Content to override Indentation settings is disabled. I'm using Ruby.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10
*Operating System (and version)?* Ubuntu 16.04 with Openbox

**Comment by Naatan** [comment]
Can you make a screenshot of your global and file level indentation prefs?

**Comment by Defman21** [comment]
I've created a new Ruby file (the second screen) if it matters. But this still happening with any Ruby files for me.
![screen01](https://cloud.githubusercontent.com/assets/7100645/15026219/6b5f978c-124e-11e6-975e-1a4a88d880b0.png)
![screen02](https://cloud.githubusercontent.com/assets/7100645/15026220/6b60bc8e-124e-11e6-9d81-5bb99ae8b7d9.png)

**Comment by Defman21** [comment]
If you want I can send you my prefs.xml

**Comment by Naatan** [comment]
Ah, the issue is that the default Ruby setting is also 2, if you set the pref to 1 and then to 2 it should properly take.

I'll update the default so this doesn't happen again.

**Comment by Defman21** [comment]
>Ah, the issue is that the default Ruby setting is also 2, if you set the pref to 1 and then to 2 it should properly take.

In global prefs?

**Comment by Naatan** [comment]
Global, per-language.

**Comment by Defman21** [comment]
https://youtu.be/izO_YYtcrWg

**Comment by Naatan** [comment]
@mitchell-as  ^ can you investigate?

**Comment by Defman21** [comment]
Some additional data:

`prefs.xml | grep indent`

```
  <long id="indentWidth">4</long>
  <long id="languages/Ruby/indentWidth">2</long>
```

Console pane: (created a new ruby file before executing these commands)
```
> require('ko/editor').scimoz().indent
< Number 0
> require('ko/editor').scimoz().tabWidth
< Number 4
```

**Comment by Defman21** [comment]
:+1:
