### ISSUE TITLE
Ruby file randomly stops responding to different keyboard keys

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1374]
### Short Summary

It happens absolutely randomly and I don't know what the reproduction steps. Sometimes Komodo just don't save a file with Ctrl+S, don't move the cursor with keys and don't delete text with Backspace. But if I switch to another tab, it works in it. Next if I switch to the broken tab after the working one Komodo starts doing the stuff normally.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10 beta
*Operating System (and version)?* Ubuntu 16.04 with Openbox

**Comment by Defman21** [comment]
Could this cause the problem?
```
[2016-05-04 20:51:52,923] [ERROR] console-logger: TypeError: popup.hidePopup is not a function (2) in chrome://breadcrumbs/content/sdk/breadcrumbs.js:861
Traceback (most recent call last):
  File "chrome://breadcrumbs/content/sdk/breadcrumbs.js", line 861, in 
```

**Comment by mitchell-as** [comment]
No, codeintel would not cause a problem with this, especially if you can go back to the original file that wasn't working.

Please let us know if you manage to find concrete steps that reproduce the problem.

**Comment by Defman21** [comment]
Will do!

**Comment by Naatan** [comment]
@Defman21 are you sure it only happens with Ruby?

**Comment by Defman21** [comment]
I don't. I didn't test other languages. I think it happens when CodeIntel starts lagging for me (pop-up shows with a big delay and hangs Komodo for 200-500ms, navigation in the popup lags a bit).

**Comment by Defman21** [comment]
And no, my project isn't THAT big. About 300 lines of code split into 5-7 files.

**Comment by Naatan** [comment]
Can you share a full error log when it happens again?

**Comment by Defman21** [comment]
Ok!

**Comment by Defman21** [comment]
Not able to reproduce anymore :)
