### ISSUE TITLE
Ruby bug with numbers

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1375]
### Short Summary

See screenshot: (instance_exec should be white, as for `"".b`)
![rubybug](https://cloud.githubusercontent.com/assets/7100645/15026778/2677565c-1251-11e6-9aa8-80be588f2100.png)

### Steps to Reproduce

Copy or write this code urself:

```ruby
213.instance_exec 123 do
    puts self
end

"".b
```

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10 beta
*Operating System (and version)?* Ubuntu 16.04 with Openbox

**Comment by mitchell-as** [comment]
Good catch! Thanks.
