### ISSUE TITLE
Filter field in the Breadcrumbs does not work

### ISSUE THREAD

**Issue by jsnjack** [Komodo/KomodoEdit#1379]
### Short Summary
Filter field in the Breadcrumbs does not work

### Steps to Reproduce
Open file, go to the breadcrumbs, type something in the filter input

### Expected results
the list of files should change

### Actual results
nothing happenes

### Platform Information
Komodo Edit, version 10.0.0-beta1, build 17142, platform linux-x86_64

**Comment by tonyattwood** [comment]
Hello,

I've got a question regarding that stuff we  discussed recently, please read  it  here <http://enjoy.ultimatefoodusa.com/e4aloki>


All the best, tony.attwood@ntlworld.com
