### ISSUE TITLE
komodo edit 9 colour schems

### ISSUE THREAD

**Issue by melli5** [Komodo/KomodoEdit#138]
what is with the colour schemes in komodo edit 9, disgusting, do you really expect developers to stare at a screen like that all day, ended up just downgrading back to 8, can't be bothered spending the time changing it all back.

**Comment by Naatan** [comment]
If you don't like it, don't use it. They're just defaults and everyone has their own opinions.

**Comment by Defman21** [comment]
@melli5 you able to download schemes from Komodo 8: https://github.com/Komodo/KomodoEdit/tree/8.5.4/src/schemes/color_schemes
