### ISSUE TITLE
Some of the toolbar icons misaligned

### ISSUE THREAD

**Issue by jsnjack** [Komodo/KomodoEdit#1380]
### Short Summary
Some of the toolbar icons (syntax check result and open in the browser icons) misaligned

### Steps to Reproduce
Open komodo with a new toolbar

### Expected results
I think every button should have icon in the middle and also has equal dimensions

### Actual results
Some of the icons have different size

### Platform Information
Komodo Edit, version 10.0.0-beta1, build 17142, platform linux-x86_64

### Additional Information
![screenshot from 2016-05-04 23-35-49](https://cloud.githubusercontent.com/assets/5493713/15028427/99081ad0-1251-11e6-8e61-b11ffc2f9baa.png)

**Comment by Defman21** [comment]
Btw the indicator with red thing should be on the left of Komodo window.

**Comment by Naatan** [comment]
@Defman21 not on Komodo Edit

**Comment by Defman21** [comment]
Ahh ok.
