### ISSUE TITLE
Buttons on the left + Classic toolbar layout looks broken

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1381]
### Short Summary
![odd](https://cloud.githubusercontent.com/assets/7100645/15028705/26c26322-125b-11e6-92be-2389e87b1103.png)

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10 beta
*Operating System (and version)?* Ubuntu 16.04 with Openbox

**Comment by Naatan** [comment]
Nice find! THanks @Defman21
