### ISSUE TITLE
Window resizing does not work properly

### ISSUE THREAD

**Issue by jsnjack** [Komodo/KomodoEdit#1382]
### Short Summary
Window resizing does not work properly

### Steps to Reproduce
Open komodo, press Win + right arrow

### Expected results
the window should occupy exactly 50% of the screen width and 100% of the screen height and should be aligned to the right

### Actual results
Nothing happens

### Platform Information
Komodo Edit, version 10.0.0-beta1, build 17142, platform linux-x86_64

**Comment by Naatan** [comment]
This has been fixed and should be in the nightly either today or tomorrow.
