### ISSUE TITLE
Add a way to reset two and more things at once

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1383]
### Short Summary

For example I want to reset Per-File preferences and CodeIntel cache, I need to do it one by one and wait Komodo for re-starting. It would be better if there will be a button like "Add this to queue" and when you press "OK" in the latest dialog of the pref you want to reset, Komodo will do all of the things I queued.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10 beta
*Operating System (and version)?* Ubuntu 16.04 w/ Openbox

**Comment by Naatan** [comment]
Sorry but those options are last resorts. I don't think there is much value in fleshing them out for ease of access.

**Comment by tonyattwood** [comment]
Hey,

I'm planning some house renovation in the near future, so I wanted to show  you some  pictures of walls  I really  like, what do you  think?  Here  is the  link <http://explore.outten.com/e4haege>

Regards, tony.attwood@ntlworld.com
