### ISSUE TITLE
Projects widget ends up empty

### ISSUE THREAD

**Issue by lagbox** [Komodo/KomodoEdit#1384]
### Short Summary

Sometimes the projects widget will end up empty after certain actions.

### Steps to Reproduce

Change the appearance of Komodo. (Interface Colors)
After it finishes reloading, wait a little bit and the projects widget will end up empty.

### Expected results

Projects widget to have the same contents as before.

### Actual results

Projects widget will end up becoming empty.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?*  10.0.0-beta1, build 89080    and previous build(s)
*Operating System (and version)?*  Ubuntu 15.10

**Comment by Naatan** [comment]
Specifically what appearance prefs did you change? I'm not seeing this.

**Comment by lagbox** [comment]
Sorry, I changed the appearance ("Use the same color scheme for everything" - checked) and changed "Interface Colors" to something else and hit OK.

**Comment by Naatan** [comment]
Thanks, reproduced.
