### ISSUE TITLE
Languages section is broken

### ISSUE THREAD

**Issue by jsnjack** [Komodo/KomodoEdit#1386]
### Short Summary
Languages section in the file preferences is broken

### Steps to Reproduce
Open any file, right click on the correspondent tab and select File Preferences. Go to Languages section

### Expected results
Nice looking page

### Actual results
Some of the language options are out of placeholders

### Platform Information
Komodo Edit, version 10.0.0-beta1, build 17142, platform linux-x86_64

### Additional Information
![screenshot from 2016-05-05 00-15-00](https://cloud.githubusercontent.com/assets/5493713/15029629/151cfbea-1257-11e6-9e45-b2c1ff2eff9a.png)

**Comment by Naatan** [comment]
That certainly is strange. Thanks for reporting!
