### ISSUE TITLE
IDE 10 migrates incompatible extensions

### ISSUE THREAD

**Issue by neurobashing** [Komodo/KomodoEdit#1387]
### Short Summary
First-run experience of IDE 10 migrates extensions which are incompatible.

### Steps to Reproduce
HTML-Tools extension was installed, and is incompatible w/ IDE 10. Remove (platform specific) local data (eg on MacOS, ~/Application Support/KomodoIDE/10.0) and run IDE 10

### Expected results
Normal operation w/ incompatible extensions not installed

### Actual results
Incompatible extensions are installed, IDE breaks badly

### Platform Information

Komodo IDE, version 10.0.0-alpha1, build 89034, platform macosx. Built on Mon May 2 01:56:48 2016.
### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by Naatan** [comment]
Thanks @neurobashing, I noticed this too. I did implement code that should prevent this but apparently it is not working.

**Comment by Naatan** [comment]
Damnit, I was able to reproduce it at first and now can't :(

**Comment by Naatan** [comment]
There we go.

So @neurobashing - you won a $50 gift card as per the contest here: http://komodoide.com/blog/help-us-test-komodo-ide-10-and-well-give-you-usd50/

Mail me what you would like your gift card to be for :) nathanr at activestate.com
