### ISSUE TITLE
Ruby catalog needs updating (2.3.0)

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1389]
### Short Summary

For example, there's no method `include?` for `[]` type in auto-complete. But in 2.3.0 this method exists. 
Or, there's no `instance_exec` or `instance_eval` methods for any Ruby object available (for `self` as well, so if there's no object before `instance_exec` (like `"hi".instance_exec`) it still should be visible in auto-complete popup, like `puts` or similar)

**Comment by mitchell-as** [comment]
I did update the Ruby catalog to 2.3, but either the rdoc doesn't exist for the methods you described (totally possible), or our rdoc/ri crawler is missing something (less likely, but still possible).

**Comment by Defman21** [comment]
http://ruby-doc.org/core-2.2.2/BasicObject.html#method-i-instance_exec

**Comment by Defman21** [comment]
http://ruby-doc.org/core-2.2.0/Array.html#class-Array-label-Obtaining+Information+about+an+Array

**Comment by mitchell-as** [comment]
Note to self: line 344 (`methods = (liveObject.instance_methods + liveObject.methods - Module.methods).sort`) is incorrectly assuming `liveObject.method(:include?) == Module.method(:include?)` for the Enumerable module (this is false). Need to rewrite this expression to accurately "diff" the Enumerable module.
