### ISSUE TITLE
Project - New from template - Komodo extension/language wizard appears under main Komodo window

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1391]
### Short Summary

Those just creates project files, but in previous version (Komodo 9) there was a wizard to create basic project files. (`manifest.rdf`, etc.)

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10 beta
*Operating System (and version)?* Ubuntu 16.04 /w Openbox

**Comment by Defman21** [comment]
Ahh, sorry. There *is* a wizard, but it's hidden by main Komodo window (so it appears under Komodo).

**Comment by Naatan** [comment]
Are you able to consistently reproduce this? I'm not able to reproduce it at all.

Might be a bug with "Openbox" (never heard of that). If you're going to use a third party window manager like that I'd recommend you use the native window decorations.

**Comment by Defman21** [comment]
Openbox is used in XFCE/LXDE and other light DE's.

**Comment by Defman21** [comment]
Anyway Preferences window doesn't have this bug - it appears over Komodo.

**Comment by Naatan** [comment]
I don't see how that makes any difference to what I said.

**Comment by Defman21** [comment]
Even with native decorations the wizard appears under Komodo window.

**Comment by Naatan** [comment]
Do you have Gnome or Unity installed? Could you try reproducing it there?

**Comment by Defman21** [comment]
I have Unity. Will try.

**Comment by Defman21** [comment]
Reproduced on Unity.

**Comment by Naatan** [comment]
Can you provide more accurate steps? I still cannot reproduce it on my end.

@mitchell-as could you try also?

**Comment by cgchoffman** [comment]
I can't reproduce on Windows.  In fact I could have sworn I filed this bug already.
@Naatan steps are:
1. Projects menu > New From Template > Create Komodo Language
2. save project file anywhere
3. When the save project file dialog disapears the Komodo Language Wizard appears for a for a brief flash then dissapears behind Komodo main window.

**Comment by Defman21** [comment]
>3. When the save project file dialog disapears the Komodo Language Wizard appears for a for a brief flash then dissapears behind Komodo main window.

That's the issue.

**Comment by mitchell-as** [comment]
Following @cgchoffman's instructions I reproduced this on Ubuntu (with Unity) 14.04.

**Comment by Naatan** [comment]
Ok, I was able to reproduce it on my Xubuntu VM.

**Comment by tonyattwood** [comment]
Hello,

I wanted to  share with you my experience in visiting a lovely place,  just take a look <http://follow.mikevergato.com/e4wzk>

Thx, tony.attwood@ntlworld.com
