### ISSUE TITLE
Laravel Blade directives support

### ISSUE THREAD

**Issue by lagbox** [Komodo/KomodoEdit#1395]
### Short Summary

There have been some new Blade directives added that aren't in the current syntax highlighting for Blade in Komodo.

```php
@extends(...)

@push(...)
@endpush

@stack(...)

@inject(...)

@each(...)

@continue / @continue(...)
@break / @break(...)

@hasSection(...)

@can(...)
@endcan

{!! ... !!}
@{{ ... }}
```

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.0.0-beta1, build 89080
*Operating System (and version)?* Ubuntu 15.10

### Additional Information

Reference:
[Laravel 5.2 - Blade Templates](https://laravel.com/docs/5.2/blade)
[Laravel 5.2 - Authorization - Within Blade Templates](https://laravel.com/docs/5.2/authorization#within-blade-templates)

**Comment by lagbox** [comment]
@mitchell-as Is this something that I can PR? I wouldn't know where to look if so.

**Comment by mitchell-as** [comment]
Hi @lagbox yes you might be able to PR this one! Thanks for the suggestion. Our laravel syntax highlighting is here: https://github.com/Komodo/KomodoEdit/tree/master/src/udl/udl (search for laravel in your browser and you'll find the folder and files).

**Comment by mitchell-as** [comment]
Closing this because the PR was merged. Thanks @lagbox !

**Comment by lagbox** [comment]
No problem, thanks again for the hard work guys :)
