### ISSUE TITLE
Preferences window prevents Komodo from Closing

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1397]
### Short Summary

If I have the preference window open and I close the main Komodo window, the main window closes but the pref window stays open
OS Decorations are OFF.

### Steps to Reproduce

Be on Windows(? doesn't happen on OSX for me)
Open Komodo
open Preferences
Close Komodo main window

### Expected results

ERr'thang to close

### Actual results

Main window closes but the preference window stays open and keeps the Komodo process alive.

### Platform Information

Komodo build 89080
Windows 10

**Comment by Naatan** [comment]
Does this happen on 9?

**Comment by cgchoffman** [comment]
Nope, confirmed this does not occur in Komodo 9.

**Comment by cgchoffman** [comment]
So i can't reproduce this in my local build.  My nightly profile is almost completely brand new though.  I JUST reset it yesterday morning, a whole new preference file, imported tools and schemes and extensions.  The local build profile has been lingering for a little while now.

**Comment by tonyattwood** [comment]
Hey,
Have you seen this  before? That's something really nice, more  info  here <http://follow.rickpalen.com/e4hrruza>

Wishes, tony.attwood@ntlworld.com
