### ISSUE TITLE
No output with this Ruby code

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1398]
### Short Summary

```
done = [(p "Is it good? [Y/n]"), gets.rstrip][1]

case done.downcase!
  when "y", ""
    p "Ok"
  when "n"
    p "Aborting..."
    exit
end
```

When I'm running this from the terminal, I get:

```
"Is it good? [Y/n]"

```

When I'm running this with Komodo debugger, I get:

![imgur](http://i.imgur.com/dN1ztB3.png)

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10 beta
*Operating System (and version)?* Ubuntu 16.04 /w Openbox
Ruby version: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
IRb version: irb 0.9.6(09/06/30)

### Additional Information

Maybe related to #1396

**Comment by Naatan** [comment]
I think this is because you're prompting for input, which we simply do not support. @mitchell-as can confirm.

**Comment by Defman21** [comment]
So it's not a bug? It works great with Python's input.

**Comment by Naatan** [comment]
@mitchell-as will have to confirm.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoIDE/commit/2967cbf511b656283ea917753e7cf9db53e21c1c
