### ISSUE TITLE
Ruby debugger does not respect the order of puts and gets

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1399]
### Short Summary

With this code:
```
p "hello world"
input = gets.chomp
p "hi"
```

In terminal I get:

```
"hello world"
123 <- that's my input
"hi"
```

In Komodo I get:
```
sdasd <- that's my input
"hello world"
"hi"
```

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10 beta
*Operating System (and version)?* Ubuntu 16.04 /w Openbox
Ruby version: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
IRb version: irb 0.9.6(09/06/30)

### Additional Information

Maybe related to #1398

**Comment by Defman21** [comment]
3 Priorities in the row!

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoIDE/commit/2967cbf511b656283ea917753e7cf9db53e21c1c
