### ISSUE TITLE
Cordova: Run Android actually Runs ios

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1402]
### Short Summary

I opened a cordova project from class in Komodo.  Cordova detection was great.  I tried to `Run Android` but it ended up starting the IOS emulator.  Looking at the command output, it does indeed start the IOS build process.  I double checked that I had both platforms installed as well.

### Steps to Reproduce

Open a Komodo project inside your Cordova project
Click the Cordova icon to run the `run android` command

### Expected results

My Android platform to be built and emulator to start up

### Actual results

IOS command runs and IOS emulator starts

**Comment by cgchoffman** [comment]
it seems all Android commands just run the equivalent IOS comment.  Maybe Komodo is recovering due to #1405 ?

**Comment by Naatan** [comment]
Nah it was way sillier than that.

**Comment by Naatan** [comment]
Fixed with https://github.com/Komodo/KomodoIDE/commit/3b96a9192151dd2a3a65d2cfd163b21a4195af65
