### ISSUE TITLE
Windows: k9 nightly prevents you from installing k10 nightly

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1403]
### Short Summary

Windows detects K9 nightly as the same thing as k10 nightly.  It will obviously have something to do with the Windows Registry though I've never looked at the installer bits that touch that.  Not a blocker but annoying.  SHould be fixed at somepoint

### Steps to Reproduce

Install Komodo 9 nightly on Windows
Try to install Komodo 10 nightly on Windows (on the same computer dummy)

### Expected results

Can do it

### Actual results

Can't do it

![pasted image at 2016_05_04 05_18 pm](https://cloud.githubusercontent.com/assets/655154/15058659/57750b60-12d2-11e6-831f-dbae84faa579.png)

**Comment by Defman21** [comment]
Rofl'd about Excepted and Actual results.

**Comment by cgchoffman** [comment]
Fixed https://github.com/Komodo/KomodoEdit/commit/bd44b5a1efc9b1be00900e29cd0582869ac0377c
