### ISSUE TITLE
Icons on OSX are still very large in 89095 build

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1404]
### Short Summary

<img width="350" alt="screenshot 2016-05-05 15 04 04" src="https://cloud.githubusercontent.com/assets/655154/15058730/cac340fa-12d2-11e6-9108-ebc5a7cdc168.png">

**Comment by Naatan** [comment]
Seems fine on build 89113

**Comment by cgchoffman** [comment]
You tested on OSX?I'm using the same build, even started in safe mode and I still have those large icons.

**Comment by Naatan** [comment]
You sure it's the same build? I tried both the build bot and local version. Both are fine.

**Comment by we3geeks** [comment]
I'm seeing this on Komodo IDE, version 10.0.1, build 89160, platform macosx.
Built on Thu May 12 01:55:19 2016.

<img width="351" alt="k10-20160515a" src="https://cloud.githubusercontent.com/assets/2390335/15276665/ef78ee46-1aab-11e6-86e5-4d63be94e2f4.png">

**Comment by Naatan** [comment]
I'll follow up on this once 10.0 is out the door, unfortunately it;s too late to do anything about this for 10.0.0.

**Comment by Naatan** [comment]
I'll fix this for the Places widget. Let me know if you still see this happening anywhere else in the UI. We'll have to fix this case by case.

**Comment by we3geeks** [comment]
Thanks; will watch for this in the nightly builds.
