### ISSUE TITLE
Cordova: Run Command: Seems to run in stripped down environment

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1405]
### Short Summary

i ran a command in the Cordova Scope (`cordova build`) and it failed with:
```
Running command: /Users/Yerac/Projects/Cordova/accelerometer-app/platforms/android/cordova/build 
[Error: ANDROID_HOME is not set and "android" command not in your PATH. You must fulfill at least one of these conditions.]
ERROR building one of the platforms: Error: /Users/Yerac/Projects/Cordova/accelerometer-app/platforms/android/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project

```
I just tried it from the commandline and it runs fine.  

### Steps to Reproduce

Open cordova project in Komodo
Click Cordova dynamic toolbar item and select run command
In Commando interface that appears just run `cordova build`

### Expected results

A whole lot of output that finishes with
```
    /usr/bin/touch -c /Users/Yerac/Projects/Cordova/accelerometer-app/platforms/ios/build/emulator/accelerometerApp.app

** BUILD SUCCEEDED **

** BUILD SUCCEEDED **
komac13:accelerometer-app Yerac$
```

### Actual results

I get an error that my environment isn't properly configured

**Comment by cgchoffman** [comment]
NOTE: `Cordova toolbar > Build Android` works

**Comment by Naatan** [comment]
It uses your Komodo environment. Have you tried setting the relevant variables under Prefs > Environment?

We definitely need to do a better job of detecting your environment, but that's another issue.

**Comment by cgchoffman** [comment]
hmm, those might be set in .profile and not seen by Komodo.  I'll look.

**Comment by cgchoffman** [comment]
```
# Android dev tools
export ANDROID_HOME=$CGC_DEV_TOOLS/Android/sdk
PATH=$PATH:$ANDROID_HOME
PATH=$PATH:$ANDROID_HOME/platform-tools
PATH=$PATH:$ANDROID_HOME/tools

# Apache Ant
export ANT_HOME=$CGC_DEV_TOOLS/apache-ant-1.9.6
PATH=$PATH:$ANT_HOME/bin
```

WEll i'll be...

**Comment by Naatan** [comment]
So I take it we can close this then? :)

**Comment by cgchoffman** [comment]
I don't think so.  I've configured those vars and now my cordova is completely broken.
`/bin/sh: cordova: command not found` but that's not even a part of my PATH.
I just deleted the variables to see if it works without them so i'll have to add them again to show you what I have... PS. UX upgrade needed in this dialog.

**Comment by Naatan** [comment]
The environments dialog?

See if you can figure it out, but I think the issue here is with your environment config and not with Komodo.

**Comment by cgchoffman** [comment]
But why would the toolbar buttons work and not Commando?  They're running basically the same commands.

**Comment by cgchoffman** [comment]
> The environments dialog?

yes, exactly.  

On the ticket thought, I added only the ANDROID_HOME var and that completely breaks cordova integration giving the same error that i posted 2 comments ago.

<img width="788" alt="screenshot 2016-05-05 16 24 00" src="https://cloud.githubusercontent.com/assets/655154/15060272/de241c5e-12dd-11e6-8f1f-4f239ae8df9e.png">
<img width="867" alt="screenshot 2016-05-05 16 25 16" src="https://cloud.githubusercontent.com/assets/655154/15060290/020367ce-12de-11e6-8c2b-42dec48e7f23.png">

**Comment by cgchoffman** [comment]
I think this is related:
```
2016-05-05 16:36:47,310] [ERROR] ko-shell: child process ended with code -1, stdout: , stderr: 
Traceback from ERROR in 'ko-shell' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:379:27
    this.run/<@chrome://komodo/content/sdk/shell.js:151:17
    emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:96:9
    handleError@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/system/child_process.js:108:7
    initialize/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/system/child_process.js:92:19
    delay/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/lang/functional/concurrent.js:38:20
    notify@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/timers.js:40:9

[2016-05-05 16:36:53,858] [ERROR] console-logger: TypeError: view.scintilla is undefined (2) in chrome://komodo/content/sdk/shell.js:344
Traceback (most recent call last):
  File "chrome://komodo/content/sdk/shell.js", line 344, in 
```

**Comment by cgchoffman** [comment]
I get the above error when interact with the Cordova Toolbar button.

**Comment by cgchoffman** [comment]
I removed the envvar in Komodo again and it works fine.  I added an arbitrary env var called "something" with a value of "somethin something" and it breaks Cordova integration.  I guess this might be a seperate bug as the original one I filed would most  likely be resolved if I could configure prefs > Environment without breaking Cordova  integration.

**Comment by Naatan** [comment]
Fixed by recent commits
