### ISSUE TITLE
Gulp Toolbar item has no content

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1408]
### Short Summary

This MIGHT be related to #1405 as i get the same error i mention in one of my comments: https://github.com/Komodo/KomodoEdit/issues/1405#issuecomment-217310336

but it has nothing to do with an environmental variable being set in Komodo.

### Steps to Reproduce

`npm intall gulp` into a folder
create a `gulpfile.js` in that folder
Create  a Komodo project in that folder and open it in Komodo
Click on the resulting Gulp Toolbar button

### Additional Information

```
[2016-05-05 16:48:12,023] [DEBUG] console: error: Error {}
[2016-05-05 16:48:12,026] [ERROR] ko-shell: child process ended with code -1, stdout: , stderr: 
Traceback from ERROR in 'ko-shell' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:379:27
    this.run/<@chrome://komodo/content/sdk/shell.js:151:17
    emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:96:9
    handleError@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/system/child_process.js:108:7
    initialize/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/system/child_process.js:92:19
    delay/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/lang/functional/concurrent.js:38:20
    notify@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/timers.js:40:9
```

**Comment by Naatan** [comment]
When you say "create a gulpfile" do you mean just an empty gulpfile?

**Comment by cgchoffman** [comment]
A `gulpfile.js` file, yes.

**Comment by Naatan** [comment]
Empty?

**Comment by cgchoffman** [comment]
Yes.

**Comment by Naatan** [comment]
Fixed with https://github.com/Komodo/KomodoIDE/commit/c9a021bab9bc72af17dd4b4e1794d672ff0318b3
