### ISSUE TITLE
Gulp project not detected on Windows

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1409]
### Short Summary

I've setup a basic Gulp project on windows and I don't get the toolbar button

### Steps to Reproduce

npm intall gulp into a folder
create a gulpfile.js in that folder
Create a Komodo project in that folder and open it in Komodo

### Expected results

Gulp cup toolbar button

### Actual results

Nothing

### Platform Information

89095 Komodo build
Windows 10 

### Additional Information

unfortunately there are no relevant errors.

**Comment by Naatan** [comment]
Fixed with https://github.com/Komodo/KomodoIDE/commit/0848c31c6e0b51f3cf4c0d94417f50ca2be555de
