### ISSUE TITLE
Ruby syntax coloring: dots in numeric range miscolored

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1410]
### Short Summary

```
two = 2
x = 1           #correct
x = 0x1         #correct
x = 1.2         #correct
x = (1..2)      #incorrect
x = (1...2)     #incorrect
x = (1 ..2)     #correct
x = (1 ...2)    #correct
x = (1 .. 2)    #correct
x = (1 ... 2)   #correct
x = (1.. 2)     #incorrect
x = (1... 2)    #incorrect
x = (1..two)    #incorrect
x = (1.. two)   #incorrect
x = (1 .. two)  #correct
x = (1 ..two)   #correct
x = (1...-2)    #incorrect
x = (1..0x2)    #incorrect
x = (1...0x2)   #incorrect

```

![Imgur](http://i.imgur.com/kS3To7z.png)

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10 beta
*Operating System (and version)?*

**Comment by Defman21** [comment]
Forgot to mention: `x = (1..0.2)` looks like `x = (1..2)`, but `0.2` colored properly, only `1.` looks bad.

**Comment by mitchell-as** [comment]
Thanks for the report!

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoEdit/commit/69884a5526315db3f3e532d4ad95eb962c37457e
