### ISSUE TITLE
Transparent komodo application

### ISSUE THREAD

**Issue by jsnjack** [Komodo/KomodoEdit#1411]
### Short Summary
I have just updated to the latest komodo 10 nightly build via komodo updater. When I open komodo the main window is transparent

### Steps to Reproduce
Update komodo to the latest build via komodo updater

### Expected results
Komodo updates

### Actual results
Komodo updated, but the main window became transparent

### Platform Information
Komodo Edit 10.0.0 Beta 1 nightly (Build 17156) linux-x86_64

### Additional Information
![screenshot from 2016-05-06 18-19-47](https://cloud.githubusercontent.com/assets/5493713/15077581/d4cacfb0-13b7-11e6-8bdf-339974b5111b.png)

[komodo_logs.txt](https://github.com/Komodo/KomodoEdit/files/252560/komodo_logs.txt)

**Comment by Naatan** [comment]
This is a bug in the latest Komodo Edit nightly. We'll push a new one today that should fix this.

The IDE nightly should work fine if you want to test that.

**Comment by cgchoffman** [comment]
New nightly will be available at ~12:15 PST.  You can either download it from the website or do `Help > Check for Update`
