### ISSUE TITLE
Menu Button position

### ISSUE THREAD

**Issue by lagbox** [Komodo/KomodoEdit#1412]
### Short Summary

Menu button is appearing on the left now.
### Steps to Reproduce

Set the [close, max, min] buttons to the left side.
### Expected results

Menu button to be in the right corner where it has been.
### Actual results

Menu button is now on the left side to the right of the [close, max, min] buttons.
### Platform Information

_Komodo Edit or IDE?_ IDE
_Komodo Version?_ 10.0.0-beta1, build 89095
_Operating System (and version)?_ Ubuntu 15.10

**Comment by Naatan** [comment]
This is by design, I thought it made more sense. No?

**Comment by lagbox** [comment]
I would assume something like that shouldn't move, but I can see how that could be an issue, as it would be to the left of the buttons when they are on the right.
I liked it in the right corner as it mimics how Firefox does it and I am used to it now ;-)

**Comment by Naatan** [comment]
What do others think?

@Defman21 @cgchoffman @mitchell-as @we3geeks [..]

**Comment by cgchoffman** [comment]
I wouldn't have a preference on Linux but on Windows I would definitely want them on the right.  But we're not talking about Windows, correct?

**Comment by lagbox** [comment]
@cgchoffman For me, I just want the menu to not be tied to the [close, max, min] buttons. As I moved those buttons to the left to match how my window manager/theme has them, but didn't expect the menu button to move with them.

**Comment by Naatan** [comment]
@cgchoffman the default will be on the right. The question is if you move the window buttons to the left should it also move the menu button.

**Comment by cgchoffman** [comment]
Oh again i have no opinion...I use *Alt*.  I can count on 2 hands how many times i've used the menu button.  I think it makes sense to group the menu button with the window buttons.  It doesn't makes sense to me to group the menu button as a Toolbar button.

**Comment by Defman21** [comment]
I like the new positioning of this button.

**Comment by lagbox** [comment]
Firefox, Midori and Chrome all have their menu on the right.

**Comment by Defman21** [comment]
Komodo is not a browser, it has its own UI. If you enable native decorations, it will automatically disable the re-order of Komodo's window buttons, so the menu will be on the right.

**Comment by Defman21** [comment]
Well no. I thought so. Looks like a bug for me :)

**Comment by Defman21** [comment]
Nvm, just needed to restart Komodo to apply the change properly.

**Comment by lagbox** [comment]
Yes I know Komodo isn't a browser, but it does control that bar itself and every application I use that has an independent menu button has it on the right side.
I would just use Alt to show the full menu bar if I was going to use something in the upper left side.

**Comment by Defman21** [comment]
As I said, you can use Native Decorations if you want to see it on right of titlebar or disable a setting so the Komodo's window buttons will be on right of titlbar with menu button as well.

**Comment by Defman21** [comment]
But also I think there should be a radio box with 2 options:

 * Stay close to the window controls
 * Be on the opposite side to window controls

By default it should be as now - stay close to the window controls.

**Comment by we3geeks** [comment]
I am pretty much exclusively a Komodo user on OS X, so I'm not sure my opinion really matters all that much but if forced to offer an opinion I would lean toward keeping the menu button on the right.

**Comment by Naatan** [comment]
I'll put it on the right. If anyone wants it on the left they can write a custom css rule for it in their color scheme config. Adding more prefs for this seems way overkill to me, and would create more maintenance for us and thus add more things that can break.
