### ISSUE TITLE
Changing to Komodo's native decorations doesn't move the menu button on left

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1415]
### Short Summary

title

### Steps to Reproduce

1. Use Komodo's decorations on left of titlebar.
2. Change to native decorations.

### Expected results

Button on right of titlebar.

### Actual results

Button on left of titlebar.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10
*Operating System (and version)?* Ubuntu 16.04 /w Openbox

### Additional Information

Restarting Komodo fixes it.

**Comment by Naatan** [comment]
THis doesn't make any sense to do unlses we add a pref to control the position of this button independently (which we may do).

**Comment by tonyattwood** [comment]
Hey,


I've just seen something really weird  and I decided to ask  you whether that is real or not. Just take a look <http://esteem.condosoftulsa.info/e4afa>

See you around, tony.attwood@ntlworld.com
