### ISSUE TITLE
When closing Komodo, it does not close it's children

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1417]
### Short Summary

title

### Steps to Reproduce

1. Open View Log File window (Help - Troubleshooting - View log file).
2. Close Komodo window

### Expected results

Any Komodo's child windows closed.

### Actual results

View Log File stays opened.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10
*Operating System (and version)?* Ubuntu 16.04 /w Openbox

**Comment by cgchoffman** [comment]
Build number? This was fixed yesterday I believe.

**Comment by Defman21** [comment]
89095

**Comment by Defman21** [comment]
Just saying, it does not happen with Preferences window. It closes properly.

**Comment by cgchoffman** [comment]
Check for updates and test again please.  Latest is 89113.

**Comment by Defman21** [comment]
Works good.
