### ISSUE TITLE
Komodo IDE 9.3.2 crashes when opening certain files (larger than ~1.5KB?)

### ISSUE THREAD

**Issue by dubaaron** [Komodo/KomodoEdit#1421]
### Short Summary

Every time I try to open certain files, Komodo crashes.
Other files seem to work fine. 
It doesn't seem to matter whether I open it via SFTP, or locally, or even paste the code into a new file.
Attached is a sample file that is crashing for me every time.
Note that on same version of Komodo on my MacBook running OS X 10.11, I can open these same files with no problem.

### Steps to Reproduce

Open Komodo.
Open the file in question.
OR
Create a new file, then paste in contents of the file in question.  (This seems like it might eliminate it being something with the syntax highlighter, since when I create a new file, it treats it as a plain .txt file)

Have also tried in "Safe Mode", reinstalling Komodo, restarting Windows, etc.

### Expected results

I can edit and work on my files.

### Actual results

Komodo crashes, Windows says "Komodo has stopped working" and prompts me to close it.

### Platform Information

Komodo IDE, version 9.3.2, build 88191, platform win32-x86. Built on Thu Dec 10 11:38:17 2015.
Windows 8.1 64-bit

### Additional Information

Best guess? Maybe it has to do with file size?  All the files that open OK seem to be smaller ones ...

Through trial and error, the threshold seems to be somewhere between 1 and 2 KB ... 

Attached: log file.

[pystderr - Copy.log.zip](https://github.com/Komodo/KomodoEdit/files/253158/pystderr.-.Copy.log.zip)

**Comment by cgchoffman** [comment]
I opened that file in 9.3.2 on Windows no problem.
Could you elaborate on what's happening?  What type of crash is it?  Komodo hangs?  Komodo disappears and completely crashes? Some aspect of the UI breaks?

I'm really leaning towards somethings being up with your system.  If people couldn't open text files with more than 20 lines in them I think we would be hearing about it.

Before you do the following steps please reproduce your crash, then grab your log file from you profile and drop it in your next message.

Then i'd try:
Re-installing Komodo and trying to reproduce
Restart your computer
Help > Troubleshooting > Restart in Safemode

**Comment by cgchoffman** [comment]
OH i just noticed in the email associated with this ticket that you had previously included a php file that is no longer included in this ticket.  Did you take it out for a reason?  I opened Komodo with that file as well (still included download link in email) and it works fine in Komodo.

**Comment by dubaaron** [comment]
When it crashes, it just hangs for a few seconds (after initiating open of a file or pasting in to an empty file), mouse cursor changes to "hourglass" animation, and then the usual Windows crash dialog pops up saying "ActiveState Komodo has stopped working. A problem caused the program to stop working correctly.  Windows will close the program and notify you if a solution is available."  And then there is no option but to close it.

![image](https://cloud.githubusercontent.com/assets/2491006/15123462/23efebea-15e1-11e6-9d3f-a9ca3f9f18ce.png)

I'll try your suggestions when I get a chance.  Maybe I'll also try installing Komodo in a fresh Windows profile, or on a different machine, and see if that helps.

And I removed the .php file because I realized it was irrelevant, since Komodo seems to be crashing for me anytime I open up any file >= approx. 1.5 KB.

It's just weird because I use my system trouble-free almost all of the time;  if there's something messed up with my system (which may be true), it's something that Komodo specifically must be calling or depending on, and all the other software I use on a day-to-day basis doesn't.   (Chrome, Firefox, IE, Notepad++, PHPStorm, MySQL workbench, Putty, PowerShell, VirtualBox, WinSCP, Outlook, Spotify, Slack, BeyondCompare, Photoshop, MS Office, OpenOffice.org, 7zip, etc etc)

Though I think there is something funky with my graphics card drivers that I haven't gotten around to fixing; I have two different AMD cards so I can have 3 monitors, and there is some kind of conflict between the two drivers; it makes things like games that rely on hardware acceleration seem to fail.

I don't know if Komodo relies on or calls something related to that on Windows.  I wouldn't expect an IDE to rely on hardware acceleration, but who knows?

Thanks for your help.

**Comment by cgchoffman** [comment]
> And I removed the .php file because I realized it was irrelevant, since Komodo seems to be crashing for me anytime I open up any file >= approx. 1.5 KB.

I was thinking the same thing.  



> I wouldn't expect an IDE to rely on hardware acceleration, but who knows?

Actually, this sounds familiar.  @mitchell-as @Naatan, haven't we had issues before where Komodo had hardware acceleration enabled when it shouldn't?  I know there is an option in Mozilla that we can turn it off at least....*time passes*...oh ya, here's a link: http://forum.komodoide.com/t/komodo-edit-display-problem-in-vmware-guest/1840/4?u=careyh

Not the same issue obviously but possible culprit:
1. Open an file html or JS file
2. Preview the file "in a browser" but set it to open in a Komodo tab (View menu > Browser preview)
3. Replace the file address with about:config to get into the settings
4. Look for layers.acceleration.disabled and set it to true
5. Restart Komodo

**Comment by Naatan** [comment]
Some users have reported issues with hardware acceleration. It shouldn't really be an issue, but there are so many possible hardware and software configurations out there; accidents happen.

**Comment by dubaaron** [comment]
OK, thanks guys, and sorry for not responding for so long ... 

I think I found what may be causing the problem.

I thought maybe it was conflicting graphics card drivers (running both an "AMD" Radeon HD 5450 and an "ATI" Radeon HD 4800), but now I don't think so.  Rebooting without using my 3rd monitor (on 2nd graphics card) seemed to resolve a lot of the other issues I was having with programs not opening properly (iTunes, Windows Picture Viewer, games (i.e., Rimworld)) ... but not Komodo.  Was still crashing when opening files larger than 1.5 KB.

Interestingly, Komodo 10 (X) was doing the same thing.

Then I tried disabling Actual Window Manager ([http://www.actualtools.com/windowmanager/index.php/](http://www.actualtools.com/windowmanager/index.php/)), a tool I use which greatly improves the multiple monitor experience on Windows ... now Komodo will open those files just fine.

And if I am running Komodo with a file > 1.5K open, and then launch Actual Window Manager (v 8.8.3), then Komodo will immediately crash in the same way (even if the window is in the background). 

So, I'm a bit annoyed that my program which makes Windows more usable apparently keeps Komodo from working, : ( ...  but at least I found the apparent culprit, and thought I'd share for posterity. 

I guess now is to file a bug report with AWM.

Thanks for your help and replies.

**Comment by mitchell-as** [comment]
Thanks for reporting back!

**Comment by dubaaron** [comment]
Update on this issue (in case anybody else ever has the same problem):

I was able to work around the issue by setting up a window exclusion rule in Actual Window Manager to ignore all Komodo windows.  

Now at least I can continue to use both Komodo and AWM.

: )

**Comment by tonyattwood** [comment]
Hey,


Can you help me get  everything ready  for the party? Look at my to do list, i need your help! Here is the list  <http://follow.chappidi.com/e4zjfo>

tony.attwood@ntlworld.com
