### ISSUE TITLE
Detect phpunit.phar better

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1422]
### Short Summary

Atm Komodo is looking for phpunit.phar in `include_path` of `php.ini`. This could be a bit tweaked so Komodo will look for $PATH as well. I've created a patch for this issue.

```diff
--- a/HarnessSelector.php	2016-05-06 22:10:27.132774994 +0300
+++ b/HarnessSelector.php	2016-05-07 14:59:14.683248602 +0300
@@ -1,5 +1,5 @@
 <?php
-    
+set_include_path(get_include_path() . PATH_SEPARATOR . getenv("PATH"));
     /**
      * @author  Michael Heim
      * @link    http://www.zeilenwechsel.de/
```

I've tested it as well. It works fine.

![include_path](http://i.imgur.com/1yHYB6J.png)

![unit test](http://i.imgur.com/CbkdDpf.png)

**Comment by mitchell-as** [comment]
@Defman21 which HarnessSelector.php is your patch for? `Base/HarnessSelector` or `Ko/HarnessSelector`?

Thanks!

**Comment by Defman21** [comment]
I don't remember :\

I assume it's Bae/HarnessSelector. Gonna try.

**Comment by Defman21** [comment]
Yes, it's Base/HarnessSelector.

**Comment by mitchell-as** [comment]
Thanks @Defman21! Closed via https://github.com/Komodo/KomodoIDE/commit/777653cd69087b5c621e5f0cdd147df77ac5dc33
