### ISSUE TITLE
Restore workspace does not respect Window controls on left of titlebar setting

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1423]
### Short Summary

While main Komodo window displays it on the left, Restore Workspace displays it on the right. 

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10 89113
*Operating System (and version)?* Ubuntu 16.04 /w Openbox

**Comment by Naatan** [comment]
@cgchoffman this just uses an onload event in uilayout, perhaps secondary windows are not firing events properly?

**Comment by cgchoffman** [comment]
I don't know what this is.  How do I reproduce this?

**Comment by Naatan** [comment]
I'll check it out with you when we start work on 10.1

**Comment by cgchoffman** [comment]
I'm pretty sure this will be resolved by this  fix: https://github.com/Komodo/KomodoEdit/commit/ee2f184d2650037f12c7841727f9b88506e96c9d

**Comment by cgchoffman** [comment]
Nightly available here for testing: http://downloads.activestate.com/Komodo/nightly/
