### ISSUE TITLE
Odd indentation in PHP upon hitting Enter at certain times

### ISSUE THREAD

**Issue by lagbox** [Komodo/KomodoEdit#1427]
### Short Summary

Sometimes upon hitting enter inside a function call you end up in the same column on the next line.

### Steps to Reproduce

Paste what is in the example below, place cursor between the brackets, hit enter.

```php
return view('blah', []);
```

You will end up with the actual result listed below.

### Expected results

```php
return view('blah', [
    ^
])
```
### Actual results

```php
return view('blah', [
                    ^])
```
### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.0.0-beta1, build 89113
*Operating System (and version)?* Ubuntu 15.10

### Additional Information

I can see that in normal flow, the characters to the right, brackets or parentheses, are underlined. When they aren't underlined this issue will happen.

![screenshot from 2016-05-08 02-06-07](https://cloud.githubusercontent.com/assets/3752215/15096330/79923060-14c1-11e6-9103-10b2c4b1f572.png)

These examples are specific to using brackets. If there are no brackets open hitting enter will align the closing parenthesis with the opening one.

**Comment by Naatan** [comment]
This is by design, some people (the person that implemented this) like this coding style, personally it annoys me endlessly as well.

So lets add a pref that controls this.

**Comment by lagbox** [comment]
Yea its kinda odd that it has the expected result, unless you follow one of those methods, then you get a different result.

**Comment by cgchoffman** [comment]
I didn't write it but I prefer it.  Isn't this already a pref?

**Comment by cgchoffman** [comment]
> Isn't this already a pref?

I guess not.  Never mind.

**Comment by lagbox** [comment]
I still get this from time to time. Sometimes it doesn't provide the other bracket.

It feels like some race condition because its not constant.

```php
return view('blah', [
                    ^)
```

Komodo IDE, version 10.1.1, build 89474, platform linux-x86_64.
Built on Thu Sep 1 14:52:01 2016.

**Comment by Naatan** [comment]
@mitchell-as could this be related to onUIupdate?

**Comment by mitchell-as** [comment]
Yes, if you type faster than 50ms, then you might not have the closing soft brace inserted. Recent changes to remove the timeout would prevent this from happening at all.
