### ISSUE TITLE
Komodo IDE v10 startup

### ISSUE THREAD

**Issue by sgeard** [Komodo/KomodoEdit#1428]
### Short Summary
When I startup KIDE10 I get many warnings/errors in the console and although it does start the result is a mess. Is this because of the startup error or is it just that KIDE10 is work in progress and it will be sorted out before the final release?

### Steps to Reproduce
Start komodo ide 10

### Expected results
No errors in the console (just warnings) and a much cleaner appearance.

### Actual results

[simon@localhost Komodo-IDE-10.0.0-beta1-89113-linux-x86_64]$ /opt/Komodo-IDE-10/bin/komodo 

(process:10774): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
Gtk-Message: Failed to load module "canberra-gtk-module"

(komodo ide:10774): GLib-GObject-WARNING **: Attempt to add property GnomeProgram::sm-connect after class was initialised

(komodo ide:10774): GLib-GObject-WARNING **: Attempt to add property GnomeProgram::show-crash-dialog after class was initialised

(komodo ide:10774): GLib-GObject-WARNING **: Attempt to add property GnomeProgram::display after class was initialised

(komodo ide:10774): GLib-GObject-WARNING **: Attempt to add property GnomeProgram::default-icon after class was initialised
1462702478859   addons.xpi      WARN    Unable to activate the default theme
1462702478891   addons.xpi      WARN    Unable to activate the default theme
[PIPELIGHT:LIN:unknown] attached to process.
[PIPELIGHT:LIN:unknown] checking environment variable PIPELIGHT_SILVERLIGHT5_1_CONFIG.
[PIPELIGHT:LIN:unknown] searching for config file pipelight-silverlight5.1.
[PIPELIGHT:LIN:unknown] trying to load config file from '/home/simon/.config/pipelight-silverlight5.1'.
[PIPELIGHT:LIN:unknown] trying to load config file from '/etc/pipelight-silverlight5.1'.
[PIPELIGHT:LIN:unknown] trying to load config file from '/usr/share/pipelight/configs/pipelight-silverlight5.1'.
[PIPELIGHT:LIN:unknown] sandbox not found or not installed!
[PIPELIGHT:LIN:silverlight5.1] using wine prefix directory /home/simon/.wine-pipelight.
[PIPELIGHT:LIN:silverlight5.1] checking plugin installation - this might take some time.
[install-dependency] wine-silverlight5.1-installer is already installed in '/home/simon/.wine-pipelight'.
[install-dependency] wine-mpg2splt-installer is already installed in '/home/simon/.wine-pipelight'.
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
err:wineboot:ProcessRunKeys Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2)
[PIPELIGHT:WIN:silverlight5.1] embedded mode         is on.
[PIPELIGHT:WIN:silverlight5.1] windowless mode       is off.
[PIPELIGHT:WIN:silverlight5.1] linux windowless mode is off.
[PIPELIGHT:WIN:silverlight5.1] force SetWindow       is off.
[PIPELIGHT:WIN:silverlight5.1] window class hook     is on.
[PIPELIGHT:WIN:silverlight5.1] strict draw ordering  is off.
[PIPELIGHT:WIN:silverlight5.1] replaced API function CreateWindowExA.
[PIPELIGHT:WIN:silverlight5.1] replaced API function CreateWindowExW.
[PIPELIGHT:WIN:silverlight5.1] replaced API function TrackPopupMenuEx.
[PIPELIGHT:WIN:silverlight5.1] replaced API function TrackPopupMenu.
fixme:advapi:RegisterTraceGuidsW (0x8a22a7, 0x940120, {aa087e0e-0b35-4e28-8f3a-440c3f51eef1}, 1, 0x82f6c8, (null), (null), 0x940120): stub
[PIPELIGHT:WIN:silverlight5.1] init successful!
[PIPELIGHT:WIN:silverlight5.1] OpenGL Vendor: Intel Open Source Technology Center
[PIPELIGHT:WIN:silverlight5.1] OpenGL Renderer: Mesa DRI Intel(R) Ivybridge Mobile x86/MMX/SSE2
[PIPELIGHT:WIN:silverlight5.1] Your GPU is in the whitelist, hardware acceleration should work.
LoadPlugin: failed to initialize shared library libXt.so [libXt.so: cannot open shared object file: No such file or directory]
LoadPlugin: failed to initialize shared library /home/simon/.mozilla/plugins/nppdf.so [/home/simon/.mozilla/plugins/nppdf.so: wrong ELF class: ELFCLASS32]
1462702479962   addons.xpi-utils        WARN    Error: XPI database modified after shutdown began (resource://gre/modules/addons/XPIProvider.jsm -> resource://gre/modules/addons/XPIProviderUtils.js:426:16) JS Stack trace: this.XPIDatabase.saveChanges@XPIProviderUtils.js:426:17 < XPIDB_removeAddonMetadata@XPIProviderUtils.js:1276:5 < XPI_uninstallAddon@XPIProvider.jsm:4690:7 < AddonWrapper_uninstall@XPIProvider.jsm:6935:5 < komodoCmdLineHandler.prototype.handleUpgrades/<@asCommandLineHandler.js:462:13 < safeCall@AddonManager.jsm:173:5 < getAddonsByTypes_noMoreObjects@AddonManager.jsm:2139:9 < AOC_callNext@AddonManager.jsm:305:7 < getAddonsByTypes_concatAddons@AddonManager.jsm:2134:11 < PL_getAddonsByTypes@PluginProvider.jsm:150:5 < callProviderAsync@AddonManager.jsm:235:12 < getAddonsByTypes_nextObject@AddonManager.jsm:2129:1 < AOC_callNext@AddonManager.jsm:311:7 < getAddonsByTypes_concatAddons@AddonManager.jsm:2134:11 < OpenH264Provider.getAddonsByTypes@OpenH264Provider.jsm:362:7 < callProviderAsync@AddonManager.jsm:235:12 < getAddonsByTypes_nextObject@AddonManager.jsm:2129:1 < AOC_callNext@AddonManager.jsm:311:7 < getAddonsByTypes_concatAddons@AddonManager.jsm:2134:11 < LightweightThemeManager_getAddonsByTypes@LightweightThemeManager.jsm:389:5 < callProviderAsync@AddonManager.jsm:235:12 < getAddonsByTypes_nextObject@AddonManager.jsm:2129:1 < AOC_callNext@AddonManager.jsm:311:7 < getAddonsByTypes_concatAddons@AddonManager.jsm:2134:11 < getAddonsByTypes_getVisibleAddons@XPIProvider.jsm:3822:7 < makeSafe/<@XPIProviderUtils.js:146:17 < asyncMap_gotValue@XPIProviderUtils.js:181:7 < asyncMap_callback@XPIProviderUtils.js:188:9 < completeAddon@XPIProviderUtils.js:135:5 < this.AddonRepository.getCachedAddonByID<@AddonRepository.jsm:575:7 < TaskImpl_run@Task.jsm:314:40 < TaskImpl@Task.jsm:275:3 < createAsyncFunction/asyncFunction@Task.jsm:249:14 < getRepositoryAddon@XPIProviderUtils.js:137:3 < asyncMap_each@XPIProviderUtils.js:187:7 < asyncMap@XPIProviderUtils.js:185:3 < this.XPIDatabase.getAddonList/<@XPIProviderUtils.js:1051:9 < Handler.prototype.process@Promise-backend.js:865:23 < this.PromiseWalker.walkerLoop@Promise-backend.js:744:7
1462702480559   addons.xpi-utils        WARN    Error: XPI database modified after shutdown began (resource://gre/modules/addons/XPIProvider.jsm -> resource://gre/modules/addons/XPIProviderUtils.js:426:16) JS Stack trace: this.XPIDatabase.saveChanges@XPIProviderUtils.js:426:17 < XPIDB_updateActiveAddons@XPIProviderUtils.js:1366:9 < XPI_shutdown@XPIProvider.jsm:2231:7 < _startProvider/AMProviderShutdown/<@AddonManager.jsm:673:21 < Promise@Promise-backend.js:348:5 < _startProvider/AMProviderShutdown@AddonManager.jsm:671:16 < Barrier.prototype<._wait@AsyncShutdown.jsm:648:27 < Barrier.prototype<.wait@AsyncShutdown.jsm:614:28 < AddonManagerInternal.shutdownManager<@AddonManager.jsm:1010:15 < TaskImpl_run@Task.jsm:314:40 < TaskImpl@Task.jsm:275:3 < createAsyncFunction/asyncFunction@Task.jsm:249:14 < Barrier.prototype<._wait@AsyncShutdown.jsm:648:27 < Barrier.prototype<.wait@AsyncShutdown.jsm:614:28 < Spinner.prototype.observe@AsyncShutdown.jsm:356:19

(process:10774): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
Gtk-Message: Failed to load module "canberra-gtk-module"

(komodo ide:10774): GLib-GObject-WARNING **: Attempt to add property GnomeProgram::sm-connect after class was initialised

(komodo ide:10774): GLib-GObject-WARNING **: Attempt to add property GnomeProgram::show-crash-dialog after class was initialised

(komodo ide:10774): GLib-GObject-WARNING **: Attempt to add property GnomeProgram::display after class was initialised

(komodo ide:10774): GLib-GObject-WARNING **: Attempt to add property GnomeProgram::default-icon after class was initialised
SciMoz was not closed correctly before destructor called.
SciMoz was not closed correctly before destructor called.

(process:10774): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
Gtk-Message: Failed to load module "canberra-gtk-module"

(komodo ide:10774): GLib-GObject-WARNING **: Attempt to add property GnomeProgram::sm-connect after class was initialised

(komodo ide:10774): GLib-GObject-WARNING **: Attempt to add property GnomeProgram::show-crash-dialog after class was initialised

(komodo ide:10774): GLib-GObject-WARNING **: Attempt to add property GnomeProgram::display after class was initialised

(komodo ide:10774): GLib-GObject-WARNING **: Attempt to add property GnomeProgram::default-icon after class was initialised

(komodo:10774): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

### Platform Information

*Komodo IDE?* 
*Komodo 10.0.0-beta1, build 89113 * 
*Linux x64 (Mageia4)* 

### Additional Information
![kide10](https://cloud.githubusercontent.com/assets/13196616/15097358/9df02f1c-1510-11e6-8d66-17947ce14e32.png)

**Comment by Naatan** [comment]
The console is a developer tool, unless you experience issues in your use of Komodo you do not need to be referencing it.

But yes, pre-release versions do typically have more going on that log than final versions.

**Comment by cgchoffman** [comment]
> and a much cleaner appearance.

Please clarify this @sgeard.  I don't see anything wrong with your Komodo's look other than I prefer a darker theme.

**Comment by sgeard** [comment]
It's not quite so evident on the image, but the mixture of different shades of grey backgrounds looks very messy to me. Also this is the 'Classic' look so I was expecting colour icons not all those flat grey ones. I have attached another image which shows lots of different grey backgrounds together with an exception generated when you press the bottom left button. You'll also notice that the row of icons along the top present in the first image is no longer present in the second. I pressed something but I've no idea what and there is nothing to indicate how I get them back, how do I now start the debugger. Is the code browser still available? If so I've got no idea how I'm supposed to find it, is there some additional telepathic connection required to use this new version? I tried selecting a function call and 'Goto Definition' but just got an error saying that 'Goto Definition is not available for this file'.
Customize Panes: seems only to be available from an area in a new tab (yet more grey bars) and it isn't possible to cancel or reset.
![kide10_2](https://cloud.githubusercontent.com/assets/13196616/15129790/f0826796-163b-11e6-8d49-97b6ac89a203.png)

**Comment by cgchoffman** [comment]
To reiterate what @Naatan already said, this is a pre-release.  You should expect bugs.  The `telepathic connection` feature may need some patching.

Anyway, @Naatan can answer questions about the new skinning.

As for the missing toolbar, could you try to figure out what you clicked?  It's next to impossible for use to diagnose a bug if you can't provide reproduction steps.  The error in the screenshot doesn't tell me much regarding a missing toolbar.  

What platform are you on?  That looks CentOSy?  I'm not familiar with where the menu bar is in that version but if you can find it, look under View > Toolbars > Show Toolbars to try and get the toolbar (debugging buttons, etc.) back.

Also, go-to def has never been supported for Tcl files I don't believe.

**Comment by Naatan** [comment]
If you don't like the colors of the color scheme you chose I would suggest trying a different color scheme. Alternatively you could always roll your own colors if you so desire.

Classic mode only emulates certain behaviours from the previous UI, it is not a drop in UI replacement nor will it be.

Could you please open new bug reports for your other issues, each in their own bug report? This ticket is becoming very confusing and unwieldy. I'll close it as the main issue has been addressed (logging entries).
