### ISSUE TITLE
Rails tools are broken

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1429]
### Short Summary

When I try to run a tool in Rails Tools toolbox, I get this error:
```
[2016-05-08 19:00:30,779] [ERROR] run_functions: 
-- EXCEPTION START --
TypeError: editor.ko is undefined
+ stack
    Run_RunCommand@chrome://komodo/content/run/run_functions.js:382:13
    Run_RunCommand@chrome://komodo/content/run/run_functions.js:317:12
    __rails_init/this.runCommand@chrome://railstools/content/rails_init.js:329:1
    generateRailsObject@chrome://railstools/content/rails_init.js:484:5
    anonymous@chrome://komodo/content/project/peMacro.js line 696 > Function:2:5
    macro_evalAsJavascript@chrome://komodo/content/project/peMacro.js:701:151
    _executeMacro@chrome://komodo/content/project/peMacro.js:106:30
    macro_executeMacro@chrome://komodo/content/project/peMacro.js:50:20
    this.invoke_executeMacro@chrome://komodo/content/toolbox/toolbox2_command.js:85:5
    this.invokeTool@chrome://komodo/content/toolbox/toolbox2_command.js:972:5
    this.onDblClick@chrome://komodo/content/toolbox/toolbox2_command.js:1018:5
    ondblclick@chrome://komodo/content/toolbox/toolboxPanel.xul:1:1
-- EXCEPTION END --
```

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10
*Operating System (and version)?* Ubuntu 16.04 /w Openbox

**Comment by cgchoffman** [comment]
I'm getting other errors.  Could you be more specific about what tool you're running @Defman21?

**Comment by Defman21** [comment]
I don't remember. Probably "create new migration" or something like that.

**Comment by Defman21** [comment]
Ahh no. It's Generators - Controller.

**Comment by cgchoffman** [comment]
OK thanks.  Please make sure you're provide clear, specific reproduction steps.  It makes our lives easier when we finally get to these issues.

**Comment by jwhulette** [comment]
I'm experiencing the same issue. Happens when trying to use any of the rails tools from the toolbox

[Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [koIPreferenceRoot.getStringPref]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: chrome://railstools/content/rails_init.js :: __rails_init/this.getRailsVersionInRange :: line 263"  data: no]

Komodo Edit, version 10.0.0, build 17209, platform macosx.
Built on Wed May 11 22:00:40 2016.

**Comment by Naatan** [comment]
That is not the same issue, it is a different error.  Please open a new bug and provide details on how to reproduce it.

**Comment by jwhulette** [comment]
I updated to 10.0.1, no more js error but now getting same error in log files:
[2016-06-20 08:41:17,401] [ERROR] run_functions: 
-- EXCEPTION START --
TypeError: editor.ko is undefined
+ stack
    Run_RunCommand@chrome://komodo/content/run/run_functions.js:415:13
    Run_RunCommand@chrome://komodo/content/run/run_functions.js:350:12
    __rails_init/this.runCommand@chrome://railstools/content/rails_init.js:329:1
    generateRailsObject@chrome://railstools/content/rails_init.js:484:5
    anonymous@chrome://komodo/content/project/peMacro.js line 729 > Function:2:5
    macro_evalAsJavascript@chrome://komodo/content/project/peMacro.js:734:151
    _executeMacro@chrome://komodo/content/project/peMacro.js:139:30
    macro_executeMacro@chrome://komodo/content/project/peMacro.js:83:20
    this.invoke_executeMacro@chrome://komodo/content/toolbox/toolbox2_command.js:118:5
    this.invokeTool@chrome://komodo/content/toolbox/toolbox2_command.js:971:5
    this.onDblClick@chrome://komodo/content/toolbox/toolbox2_command.js:1017:5
    ondblclick@chrome://komodo/content/toolbox/toolboxPanel.xul:1:1
-- EXCEPTION END --

When trying to use any userscript in the Rails Toolbox
Komodo Edit or IDE? IDE
Komodo Version? version 10.0.1, build 17276
Operating System (and version)? Mac OS X 10.10.5

**Comment by mitchell-as** [comment]
It looks more or less like the same error mentioned in the original post for this ticket. Thanks for the extra data point.

**Comment by mitchell-as** [comment]
FYI the 

```
[Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [koIPreferenceRoot.getStringPref]" nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)" location: "JS frame :: chrome://railstools/content/rails_init.js :: __rails_init/this.getRailsVersionInRange :: line 263" data: no]
```

error comes from not having Rails configured properly. (I had to point Komodo to my local rails installation.)
