### ISSUE TITLE
Komodo v10 UI: Light color schemes need dark icons in preferences window

### ISSUE THREAD

**Issue by we3geeks** [Komodo/KomodoEdit#1436]
### Short Summary
With a light color scheme selected, the light icons in the preference window's left pane become basically invisible. The icons are there but very difficult to see.

### Steps to Reproduce
Switch to "Classic" interface and widget colors

### Expected results
The icons should remain visible.

### Actual results
They don't?

### Platform Information

Komodo IDE, version 10.0.0-beta1, build 89113, platform macosx.
Built on Fri May 6 01:55:28 2016.

### Additional Information
![k10-20160510a](https://cloud.githubusercontent.com/assets/2390335/15145252/c0acb004-1671-11e6-9e74-36dcae6c1cdc.png)

**Comment by mitchell-as** [comment]
@Naatan I'm not sure what milestone this should be.

**Comment by Naatan** [comment]
I'll sneak it into 10 if we get another RC build.
