### ISSUE TITLE
Whitespace and keywords2 not visible when using "Cupertino"

### ISSUE THREAD

**Issue by clokep** [Komodo/KomodoEdit#1438]
### Short Summary
The "whitespace" and "keywords2" categories are not visible when using Cupertino.

### Steps to Reproduce
1. Using the "Cupertino" color scheme
2. Open a Python document that has a keywords2 item (and make whitespace visible), example below:

```python
class Foo(object):
    def __init__(self, x):
        self.x = x
```

As you can see, `self` is not easily visible.

### Expected results

`self` is easily visible

### Platform Information

*Komodo Edit or IDE?*  IDE
*Komodo Version?* Komodo IDE, version 10.0.0-beta1, build 89113, platform macosx. Built on Fri May 6 01:55:28 2016.
*Operating System (and version)?* OS X El Capitan

### Additional Information

![screen shot 2016-05-10 at 1 52 26 pm](https://cloud.githubusercontent.com/assets/517124/15156765/93bc35ca-16b6-11e6-947c-b7010b5cc513.png)

![screen shot 2016-05-10 at 1 53 16 pm](https://cloud.githubusercontent.com/assets/517124/15156770/96ced3ee-16b6-11e6-9c88-adc6bc8f8ed7.png)

**Comment by clokep** [comment]
Thanks @Naatan!

**Comment by Naatan** [comment]
You can download / try it out already via 

https://github.com/Komodo/komodo-color-schemes/blob/master/Cupertino.ksf

Note I made some additional tweaks to the Cupertino theme to make it more consistent with the OSX styling.
