### ISSUE TITLE
Komodo 10 beta: Missing Minimize/Maximize/Close Button

### ISSUE THREAD

**Issue by hoppfrosch** [Komodo/KomodoEdit#1443]
### Short Summary
As a followup of #1434:
I have certain Interface settings (see #1434 for screenshot of preferences)

Pressing ALT the menubar shows up, but the "usual" window control elements (Minimize/Maximize/Close-Buttons in the right upper corner of the window) are missing. Also the window icon in the upper left window corner  is missing (which is available  on a standard window when clicking in the icon in the upper left corner of a standard window)

### Expected results
Buttons/icon should be available to be able to do common window operations like closing or minimizing/maximizing a window via single mouseclick

### Actual results
Buttons are missing

### Platform Information

KomodoIDE 10 nightly 89113
Win7 Ultimate 64bit SP1

**Comment by mitchell-as** [comment]
@Naatan I think you fixed this in #1434 right? If so this ticket can be closed, as a new build should be coming out shortly.

**Comment by Naatan** [comment]
Yes, this is #1434
