### ISSUE TITLE
Commando wont load after an early cancel

### ISSUE THREAD

**Issue by lagbox** [Komodo/KomodoEdit#1444]
### Short Summary

If you can cancel the opening of Commando after you trigger it, before it actually visually starts to open, it will not open again until a restart.

### Steps to Reproduce

This may be difficult to reproduce.

Use key bindings to open Commando (for me I am having it open to file scope).
Before it can load (visually load), do anything to cancel the load. (which for most will mean immediately)

To cancel it could be clicking in the interface anywhere else, ctrl+p again, escape, etc ...

### Expected results

Commando to be able to open after this.

### Actual results

Commando will not load at all.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.0.0-beta1, build 89113
*Operating System (and version)?* Ubuntu 15.10

### Additional Information

There is a timing issue here. If you catch it too early, this issue will happen. If you catch it slightly later you may run into #1445 - Commando in white.

**Comment by mitchell-as** [comment]
Thanks, I was able to reproduce by rapidly pressing Ctrl+Shift+O (default bindings) until commando wouldn't open anymore.

**Comment by Naatan** [comment]
Thanks @mitchell-as, those steps allowed me to reproduce the issue.
