### ISSUE TITLE
Commando in white

### ISSUE THREAD

**Issue by lagbox** [Komodo/KomodoEdit#1445]
### Short Summary

Commando will become all white if its cancelled while loading some times.

I ran into this while trying to figure out what was causing #1444 

### Steps to Reproduce

Ctrl+p (Commando File Scope - Sublime bindings), then Ctrl+p while commando is loading.   (This is how I first noticed this)

If that doesn't reproduce then continue to try until it does something differently.

You will eventually get the white commando or commando will no longer open ( #1444  ).

### Expected results

Normal Commando

### Actual results

Will end up with Commando in white.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.0.0-beta1, build 89113
*Operating System (and version)?* Ubuntu 15.10

### Additional Information

![screenshot from 2016-05-11 02-46-17](https://cloud.githubusercontent.com/assets/3752215/15172576/cec91f66-1724-11e6-9e90-d204184ff924.png)

In doing this you may run into #1444 instead.

**Comment by mitchell-as** [comment]
Thanks, I was able to reproduce by rapidly pressing Ctrl+Shift+O (default bindings) until commando wouldn't open anymore.

**Comment by Naatan** [comment]
I cannot reproduce this. I'll focus on fixing #1444, if this bug still happens after that is fixed let me know and I'll reopen this.

**Comment by lagbox** [comment]
Yea this issue and reproduction steps is contrived. I never ran into this in normal operation, only when purposefully trying to break commando to figure out #1444.

**Comment by lagbox** [comment]
Just had this happen again. I had loaded commando filescope via bindings and had escaped out of it immediately after changing my mind and now it comes up as a white box.
