### ISSUE TITLE
Unsaved changes problematic with UTF-8

### ISSUE THREAD

**Issue by goozak** [Komodo/KomodoEdit#1446]
### Short Summary
Displaying "Unsaved changes" for a file encoded with UTF-8 that contains accented characters, the 'saved' version of the file treat UTF-8 characters (such as é) as ASCII (é becomes Ã©), but the (unsaved) version is properly encoded.  This results in every lines containing accented characters being flagged as changed.

### Steps to Reproduce
Save a file encoded in UTF-8 that contains accented characters
Add a line of text
"Show Unsaved Changes"

### Expected results
Only the new, unsaved text should be highlighted.

### Actual results
All lines containing accented characters are highlighted.

### Platform Information
Komodo IDE, version 9.3.2, build 88191, platform win32-x86.
Built on Thu Dec 10 11:38:17 2015.
Windows 7 Ultimate Service Pack 1
 

### Additional Information
![screenshot - 11-05-16 11_01_23](https://cloud.githubusercontent.com/assets/454810/15185553/bf2a9d76-1767-11e6-9d81-fb2cb337b311.png)

**Comment by Naatan** [comment]
Could you provide some sample text for us to test with?

**Comment by goozak** [comment]
Make sure the file is saved as UTF-8

Ceci est un document avec des accents...
Noël
Glaçage
Gaëtan
Hiver
Automne
Été
Printemps

**Comment by mitchell-as** [comment]
![utf8](https://cloud.githubusercontent.com/assets/12902397/15677650/2d1a13d2-2719-11e6-97f7-2d8e310328f9.png)

This looks to be a Windows only issue. @cgchoffman can you reproduce this one?

**Comment by cgchoffman** [comment]
Yep, i can reproduce this on Windows.  I get the exact same output as @goozak.

**Comment by mitchell-as** [comment]
Thanks @cgchoffman I'll mark this as a bug.
