### ISSUE TITLE
Windows Installer: Komodo isn't added to the System Path

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1451]
### Short Summary

It doesn't look like Komodo is added to the system path any more.  It appears this has been broken since Komodo 9.

### Steps to Reproduce

Run Windows installer for 9 or 10
On the Custom Setup page make sure Register as Default is enabled
Continue with installation
Open Terminal and enter `ko -v`

### Expected results

Komodo 9 or 10 to start

### Actual results

Depending on your system either nothing will happen or Komodo 7 or 8 will start(assuming you had one of those installed).

Secondary objective: Clean the path of old installs if they exist.

**Comment by Naatan** [comment]
You're confident it used to do this?

**Comment by cgchoffman** [comment]
Ya it definitely did and it's in the Description area of the Desktop Integration item on the Custom Setup page of the installer.  So a user will expect this to happen if they select that item to be configured during install.

**Comment by cgchoffman** [comment]
This must have been because I was testing a nightly build.  Just found that those builds aren't added to the system path.
