### ISSUE TITLE
Debugger Dialog: Javascript vs. Node: JS chrome options saved for NodeJS session

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1456]
### Short Summary

Javascript chrome options are being saved for NodeJS debugging sessions if the Javascript debugging happened first.

### Steps to Reproduce

Open a JS file and make sure it's type is set to JS, not Node.
Attempt a debug session.  Doesn't matter if it's successful as long as you click through the Debug Dialog
Switch file type to Node
Start debugger
Click on Environment tab in the Debug Dialog

### Expected results

Nothing in the `Interpreter Arguments` field

### Actual results

`--host=localhost --port=9222` are in the `Interpreter Arguments` field.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoIDE/commit/24ad045c6a85d8e3663d01b771f5afb384709599
