### ISSUE TITLE
Last Position

### ISSUE THREAD

**Issue by pipiscrew** [Komodo/KomodoEdit#146]
hi, 

I found the same request at http://community.activestate.com/node/7273 made on 2011
is very useful to go back or forward where were you...

example the flow on a index.html, 
-edit the html code
-edit the JS code (here sometimes need to go to HTML then from HTML then come back here)

the ALT+L/R Arrow is to jump between tabs 
![snap429](https://cloud.githubusercontent.com/assets/3852762/7067525/8b15827a-ded4-11e4-9f99-fc699770ef1b.png)

**Comment by cgchoffman** [comment]
This is a great idea.  It's a shame that person didn't file an enhancement request like you are now.  For now, have you tried using bookmarks?  Ctrl+F2 to add/remove a book.  F2 to cycle through your book marks in a file.

**Comment by pipiscrew** [comment]
^should have feature

nah, no time for bookmarking when developing, remember me VB6 times!!

**Comment by cgchoffman** [comment]
It's an enhancement of the existing forward/backward mechanism.  I would say it's an Enhancement.  And I don't follow how Bookmarks take time.  I use them all the time when I am interested in particular sections.

**Comment by Naatan** [comment]
I'm confused, isn't this already what back/forward does?

Back/forward is not to jump between files, not explicitly anyway. If the previous change was in another file then it will jump to that file.

**Comment by cgchoffman** [comment]
No I don't think that behavior was implemented or wasn't implemented in the desired way.  We'll another look at the backward/forward code to see if we can extend it a bit.

**Comment by pipiscrew** [comment]
@cgchoffman 
the point is that is serious moments, you didnt set the bookmark!! and you are 311lines up or down, and you wondering **where the hell was that?** ctrl+back or alt+back, you are there!!

@Naatan 
dont know, but as I tested no working properly (for me doesnt return back where was it)

@cgchoffman
I wonder like : I open a file with 1000lines, CTRL + F > search for test > landed to 405 > move ny cursor to 410 and edit @ column 10.

when I press ALT+BACK = I should go to 405 then ALT+BACK = line 1 (where I started)
in reverse should be the ALT+FORWARD... 

conclusion = where editor got L/R mouse click store the line number to an array
if user press ALT+BACK array.len -1 
if user press ALT+BACK array.len -2
if user press ALT+FORWARD array.len +1 

!!

thanks!

**Comment by cgchoffman** [comment]
The only problem i see with above is distinguishing between line 405 and the 5 lines you moved across to get to line 410 (Which i wouldn't want in my history).  We're thinking when  the new line is < 5 lines away (or some configurable number, perhaps only edited lines) no new entry is added.

**Comment by pipiscrew** [comment]
yes, plus when user #click a function name# should add to queue this line...

thanks for qsupport.

**Comment by cgchoffman** [comment]
fixed 2fa19a6d4096c4b6e3e2
