### ISSUE TITLE
Menu Bar Cut Off

### ISSUE THREAD

**Issue by rleap** [Komodo/KomodoEdit#1461]
### Short Summary
On windows 7, in max view, when you open menu bar (press alt key), the menu bar is half cut off at the top of the screen.

### Steps to Reproduce
Press alt key

### Expected results
The menu bar should be fully visible.

### Actual results
The menu bar is only half visible.

### Platform Information

*Komodo Edit or IDE?* 
IDE
*Komodo Version?* 
IDE 10 alpha version
*Operating System (and version)?* 
Windows 7

### Additional Information
![menubar](https://cloud.githubusercontent.com/assets/1198565/15218880/9d50f95c-1816-11e6-90ff-d1368ed1a90e.png)

 -- eg. Error logs, screenshots, workarounds --

**Comment by Naatan** [comment]
Reproduced. Note this only happens when the window is maximized.

**Comment by cyberbit** [comment]
I can confirm this issue on Windows 7, as well as similar one. When in Focus Mode and maximised, the title bar is cut off.

![image](https://cloud.githubusercontent.com/assets/7350183/15327330/bb80befe-1c16-11e6-8567-8a1650da7952.png)

I would have made a new issue, but I saw this one and considered that it is probably the same root problem.
