### ISSUE TITLE
XML parsing error on places settings page

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#1463]
### Short Summary
Just went trought my preferences but noticed i have a xml parsing error on the places page:
![2016-05-12 18_16_01](https://cloud.githubusercontent.com/assets/3530262/15222008/1cb845a4-186e-11e6-8426-e75a447fd9bd.png)

### Platform Information
[2016-05-12 18:07:37,882] [INFO] Startup: Welcome to Komodo Edit 10.0.0-beta1 build 17173 (platform win32-x86, running on Windows post2012Server version 6.3.9600)

**Comment by cgchoffman** [comment]
Not present in IDE.  Checking Edit.

**Comment by cgchoffman** [comment]
Confirmed.

**Comment by Naatan** [comment]
@cgchoffman it has the file twice, you should just remove it (the last entry).

**Comment by cgchoffman** [comment]
Why is one `Less://` and the other `chrome://`?

**Comment by Naatan** [comment]
Huh, good eye. The .css one shouldnt exist. This is probably fallout from that huuuuge commit that updates all these entries.
