### ISSUE TITLE
Window cannot be dragged around desktop in Use Native Window Borders mode

### ISSUE THREAD

**Issue by danielryoung** [Komodo/KomodoEdit#1465]
### Short Summary
Can't move window around desktop when not maximized when 'Use Native Window Borders' option is checked in preferences.  Komodo IDE, version 10.0.0-beta1, build 89113, platform win32-x86. Built on Fri May 06 01:02:38 2016.

### Steps to Reproduce

In Preferences, click 'Use native window borders' option in windowed, non-maximized, non Full Screen mode. Apply.   

### Expected results

window should be moveable around desktop between monitors or to change positions.  resizing works properly but repositioning on screen does not work. 

### Actual results

Clicking the menu bar, below the menu bar, the lighter shaded area with file tabs does not work to move the window around the desktop.  

### Platform Information

* Komodo IDE, version 10.0.0-beta1, build 89113, platform win32-x86. Built on Fri May 06 01:02:38 2016.

OS: Windows 7 x64 Enterprise

### Additional Information

![2016-05-12 10_32_51-text-1 txt project myproject - activestate komodo ide 10 0 nightly](https://cloud.githubusercontent.com/assets/2465585/15224205/ec899a40-182c-11e6-87ba-59d213260f28.png)

 work around is to disable classic mode.

**Comment by Naatan** [comment]
This is resolved on master, a nightly should be available soon.

**Comment by cgchoffman** [comment]
Nightly has been staged.  Will be available in approximately 2 hours.  They push live at 12 PST time and take a few minutes to move into place.
