### ISSUE TITLE
Remove Komodo-feedback email from Internal Error dialog

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1466]
### Short Summary

https://cloud.githubusercontent.com/assets/3530262/15215072/ce0d7a2c-1850-11e6-8066-1edab85196be.jpg

We just tell users to file bug reports now any way.  Link to git repo is included but it should point to `issues`: https://github.com/Komodo/KomodoEdit/issues
Note, I'd prefer top `issues` as apposed to `issues/new` so people think to check for the issue first before filing.

**Comment by Naatan** [comment]
We should add a link to our bug tracker instead.

**Comment by cgchoffman** [comment]
Agreed.  If you look at the linked image there is a link for that but I just noticed it doesn't actually point to issues.  That should be changed too.
