### ISSUE TITLE
Clone Dialog missing Git from options

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1468]
### Short Summary

You can't select Git as the SCC tool to clone a repo.

### Steps to Reproduce

`File > Source Code Control > Checkout`
Click the dropdown to select an SCC tool

### Expected results

To see Git

### Actual results

I don't see Git

**Comment by Naatan** [comment]
Fixed with https://github.com/Komodo/KomodoIDE/commit/1a2aac4819b4c58453aa41c3ec576c4de0e5a7bb
