### ISSUE TITLE
Checkout Dialog styling

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1469]
### Short Summary

With OS decorations off, the checkout dialog still has decorations
Can't read some of the text in the dialog.  See screenshot.
![capture](https://cloud.githubusercontent.com/assets/655154/15232569/183a3ed6-1857-11e6-8317-540ac07c632a.PNG)

**Comment by Naatan** [comment]
This is because it's a wizard, which we cannot override the decorations for currently. This'll be too much work for a 10.0.1 release.

**Comment by Naatan** [comment]
Seems to mostly look ok now.
