### ISSUE TITLE
docs: missing Userscript api

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1470]
### Short Summary

This section of the old docs doesn't exist in the new docs.
http://docs.activestate.com/komodo/9.2/macroapi.html#macroapi_top
http://docs.komodoide.com/Manual/macroapi#macroapi_top

**Comment by Naatan** [comment]
It has been moved here: http://docs.komodoide.com/sdk/macroapi

It seems the link for this (under SDK) is broken live atm, but the 10.0 branch should have already fixed this.

**Comment by cgchoffman** [comment]
OK is there a redirect for the old link?  It's referenced in quite a bit of external areas, eg. old and new forums.

**Comment by Naatan** [comment]
No there are no redirects from the old documentation to the new one. The old doc site is for older versions and the newer doc site is for newer versions of Komodo. I do still have to update the old docs to provide some sort of linkage to the new site though.

**Comment by cgchoffman** [comment]
A user said that they hit several links in public that pointed to that blank page.  I think a redirect is needed.

**Comment by Naatan** [comment]
That sounds like there are broken links. They need to be outright fixed, not redirected.

**Comment by cgchoffman** [comment]
I'll clarify with the user but i was under the impression that these were in forums and what not.  Fixing forums posts doesn't seem like the correct thing to do.

**Comment by Naatan** [comment]
It really depends on the link, can you link me to such a forum post?

**Comment by cgchoffman** [comment]
Don't know yet.  I've asked the user to specify where they were hitting the links from.
