### ISSUE TITLE
Sometimes opening parenthesis gets overwritten

### ISSUE THREAD

**Issue by lagbox** [Komodo/KomodoEdit#1476]
### Short Summary

Sometimes if you type out something with an opening parenthesis and it auto adds the following one, if you are too fast with the next character (single quote) it will overwrite the opening parenthesis. I run into this when I am typing out a call in normal work flow sometimes.

### Steps to Reproduce

This happens to me when in PHP documents where a suggested function name could exist and I want to quote the first argument. Seems to have to do with the auto suggest ability.

```php
['something' => config('
```

### Expected results

For it to not remove any characters.

```php
['something' => config('^')
```

### Actual results

Overwrites opening parenthesis.

```php
['something' => config'^')
```
### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.0.1, build 89160   and previous versions of 10
*Operating System (and version)?* Ubuntu 15.10

### Additional Information

![screenshot from 2016-05-14 02-48-00](https://cloud.githubusercontent.com/assets/3752215/15266807/50cad580-197e-11e6-8d67-ca9ff1c64e07.png)

Cursor is left between those quotes as the closing quote is added automatically.

Seems that if you can get `('` in as the suggest list starts to display, this will happen sometimes.

While trying to reproduce this I have ran into situations where it doesn't remove the parenthesis but also doesn't add the matching single quote.

**Comment by mitchell-as** [comment]
@lagbox Does this happen consistently for you? Or is it infrequent? I'm looking at our code that handles the auto-adding of matching brace characters and due to the fact that it runs in a separate thread on a 50ms timeout, there is a chance you are hitting your `'` key exactly when the timeout is fired. (Any other time "resets" the timeout to run 50ms later.)

**Comment by lagbox** [comment]
Sorry for the late reply, Ill play with it and see if this is still happening.

**Comment by mitchell-as** [comment]
Note: this should no longer happen due to this fix: https://github.com/Komodo/KomodoEdit/commit/d67cc172bf352719c36707007fe096d425742fa7

This issue may come back into play if we were to revert that fix, but I'm going to close it until then.

**Comment by lagbox** [comment]
So far so good. I will put it under some load and see if I can't reproduce.

**Comment by lagbox** [comment]
I have been able to reproduce this again.

```php
$table->morphs'|')
```
Also ended up with this result sometimes:
```php
$table->morphs('|'
```

**Comment by mitchell-as** [comment]
Okay, thanks for confirming. As I mentioned earlier in the ticket, I'm pretty sure this has been fixed and will be available in the next nightly build, whenever that might be.
