### ISSUE TITLE
javascript linting tooltip keeps blinking when 2 warnings on 1 line

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#1477]
### Short Summary
When you have two linting warnings, the linting popup doesn't popup, but keeps blinking while hovering.
![2016-05-15 11_32_56](https://cloud.githubusercontent.com/assets/3530262/15273169/fc2ab3ce-1a90-11e6-8830-7f46eae58167.png)
(i took the screenshot on the right moment, but in real life i can't read the popup because it's disappearing to fast)

### Steps to Reproduce
Have 2 linting errors on the same line
![2016-05-15 11_29_00](https://cloud.githubusercontent.com/assets/3530262/15273193/5b476104-1a91-11e6-83c6-4dbd7ebcaa12.png)

### Platform Information
Komodo edit 10 latest nightly

**Comment by fjossandon** [comment]
In case it helps to narrow it down, I have seen it happening on Windows but not on Ubuntu

**Comment by Naatan** [comment]
@mitchell-as curious, are these tooltips set through scintilla?

**Comment by mitchell-as** [comment]
@Naatan No, the tooltips would use a monospace font if so. (Scintilla uses shared styles for call tips.)

**Comment by babobski** [comment]
@mitchell-as at work I have 3 monitors, when I hover over a line with multiple warnings, it keeps blinking.

When I move the cursor more to the end of the file ( so the tooltip won't fit ) the tooltip is shown on the next monitor, but it doesn't blink.

![2016-06-09 15_08_51](https://cloud.githubusercontent.com/assets/3530262/15930761/e6b544dc-2e54-11e6-9013-870d5806bd99.jpg)

What made me think about the bug with the css color preview.
Looks like the same thing is happening here, when you hover the hyperlink the popup is shown, but the tooltip is shown behind the cursor ( as seen in my first message ), stealing the focus of the hyperlink causing the tooltip to blink.

**Comment by Naatan** [comment]
Interesting! Thanks for the additional info @babobski.

**Comment by cyberbit** [comment]
Works on 10.0.1 now!
