### ISSUE TITLE
No skin has default menu(selected item) highlights

### ISSUE THREAD

**Issue by harpreetsb** [Komodo/KomodoEdit#1479]
### Short Summary
Use any skin, the problem is you will not get default system menu or button highlights

### Steps to Reproduce
Open any existing project with previously opened files it would ask you 
`would you like to open files...`
with `YES` as default selected on system's default theme.
But with any skin you would not see it.
Same goes with any context menu.
right click any where and try navigating with arrow keys, you will not see any highlight at all.

### Expected results

The default highlighted buttons and context menu items must be highlighted with arrows keys

### Actual results
Expected results are not found

### Platform Information
Komodo Edit, version 9.3.2, build 16460, platform linux-x86_64. Built on Thu Dec 10 19:37:22 2015.
Ubuntu 16.04
## Additional Information

![selection_016](https://cloud.githubusercontent.com/assets/6584304/15282373/826ae6b4-1b60-11e6-956b-49797382a7e7.png)
![selection_013](https://cloud.githubusercontent.com/assets/6584304/15282372/8269d6fc-1b60-11e6-9e6a-412ad27e55df.png)

**Comment by harpreetsb** [comment]
in context menus only mouseover works

**Comment by Naatan** [comment]
Cannot reproduce, I get this:

![image](https://cloud.githubusercontent.com/assets/278649/15291818/d8c13dd2-1b4d-11e6-936b-d5082df24201.png)

Can you reproduce the issue using the default skin?

**Comment by harpreetsb** [comment]
Default theme works fine, but all other skins don't behave as expected.
how far is 10.0?

**Comment by Naatan** [comment]
Too close to fix this before launch, if it is indeed a bug.

I've tried some other skins and they all work fine though. Can you please share your exact build number for Komodo 10?

**Comment by harpreetsb** [comment]
i am not on komodo 10
`Komodo Edit, version 9.3.2, build 16460, platform linux-x86_64.
Built on Thu Dec 10 19:37:22 2015.`
build info copied from `about komodo`

**Comment by Defman21** [comment]
What is the skin btw?

**Comment by Naatan** [comment]
Ok, I thought you said you tested it on 10.

In this case my original response stands: This will be fixed in 10, which is due very soon.

Additionally it sounds like your issue is not with Komodo but with a third party skin, something we would not be able to resolve ourselves. You would need to contact the skin author.

If the skin is Spacemodo then I am the author, and unfortunately I have no intend in further developing that skin as the Komodo 10 skin succeeds it.

**Comment by harpreetsb** [comment]
@Defman21 
Tabula Rasa
Oceanmodo
Spacemodo

**Comment by harpreetsb** [comment]
@Naatan ok, waiting eagerly.

**Comment by Defman21** [comment]
If the skin is oceanmodo then I'm also gave no intend in further developing that skin. It has been created as a fork of spacemodo but komodo provides cool customization in 10 so it wouldn't be hard to have something similar to it

**Comment by harpreetsb** [comment]
can i have  fuzzy date for komodo 10 release?

**Comment by Defman21** [comment]
s/gave/have

**Comment by Naatan** [comment]
This week.
