### ISSUE TITLE
Publishing: Enable one-way synchronization

### ISSUE THREAD

**Issue by kamil7x** [Komodo/KomodoEdit#148]
Sometimes, there are situations, when I need to upload all my files to a server, e.g. when switching git branch. But when I try to synchronize, I have notices "remote file was deleted, so delete it locally", but that is not expected action in this case.

I think that possibility of choosing expected behavior could make Publishing better.
For example:
- force push only (overwriting and deleting remote files, that are not present locally, even if remote files are newer)
- push only (as above but with possibility to resolve conflicts)
- standard (as for now, look for newer files and then push/pull them)
- pull only (same as push only, but in opposite direction)
- force pull only (same as force pull only, but in opposite direction)

I think this would help not only me, but also other users.

NOTE FROM CAREY: When performing a forced push (all or single file) skip sync analysis

**Comment by Naatan** [comment]
Let's start with force push and take it from there.

**Comment by mjbrancato** [comment]
I agree with this! Force push will make it much more convenient for us! Thanks!

**Comment by cgchoffman** [comment]
#548 should be noted when this bug is being completed.  If the user is going to do a force push and they know they want to then we should not force them to wait for Komodo to do a Sync Analysis of the remote and local directories.

**Comment by cgchoffman** [comment]
Force push: https://github.com/Komodo/KomodoIDE/commit/0b0097f5c5ec69138f559e1a877ac7724b00254c

**Comment by cgchoffman** [comment]
Pull and force pull from Places: https://github.com/Komodo/KomodoIDE/commit/1e3cf2c028245c5c0c633bec256cede476774d96

**Comment by cgchoffman** [comment]
Allow Override of Sync Action in Publishing Dialog: https://github.com/Komodo/KomodoIDE/commit/35b601939ec02af4700aa41bb8600e63d4253424

**Comment by cgchoffman** [comment]
One last thing is to allow "Push/Pull" of a folder from Places.  Hitting a nasty bug in the Python code for that.  Callback and threading soup.  I just found a new clue today though.  Multiple `Threading.start()` calls might be happening on one Threading object, OR two threads are working from the same callback and at somepoint that callback gets invalidated/removed/somethinged.

**Comment by cgchoffman** [comment]
I'm going to close this.  Any further work we do will be a revamp of the entire tool and not be tracked here, but in a design doc in for a future release.
