### ISSUE TITLE
Can't *add* files to a SCC repo

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1481]
### Short Summary

I can't find a way to add new files to a repo in the Komodo UI anymore.  I assumed that this meant if I double click a "untracked" file in the commit dialog to add it tothe list of files to be committed then it would be "added" for me when I clicked commit.  If that is the case then it's broken.

### Steps to Reproduce

Create a new file in your SCC repo
Right click file tab or places item to try to SCC > Add it
Can't find
OR
Open commit dialog
Double click file to add it to the list of files to commit
Write commit message
click "commit"
Dialog flashes then resets to it's original state of no files selected to be commit but no commit took place.  Note that the Notifications tab will tell you that a commit took place.

**Comment by Naatan** [comment]
Fixed in https://github.com/Komodo/KomodoIDE/commit/312d1cc99d360a31d1669b14d50f9e67a3e5fde7

Should be in the next nightly.
