### ISSUE TITLE
Side Toolbar doesn't stay hidden after restart

### ISSUE THREAD

**Issue by cavac** [Komodo/KomodoEdit#1482]
### Short Summary

Side Toolbar does not stay hidden afteer a restart.

### Steps to Reproduce

Right click on toolbar -> Customize... -> Disable "Show Side Toolbar" -> Click "Done".

Restart Komodo.

### Expected results

Side toolbar does not show up.

### Actual results

Side toolbar is visible again.

### Platform Information

Komodo IDE 10.0.0 build 89159, Ubuntu 14.04 x64

**Comment by lagbox** [comment]
Reproduced on 10.0.1 build 89160
