### ISSUE TITLE
"Project" Sidebar nearly impossible to resize

### ISSUE THREAD

**Issue by cavac** [Komodo/KomodoEdit#1483]
### Short Summary

The Projects sidebar starts out "minimized" to the bottom after starting Komodo. When trying to resize it, i get the "resize" mouse pointer but the pane doesn't actually move when i try to drag it.

I sometime, seemingly randomly got it to work.

Also, when i restart Komodo, it's back in its default "minimized" state again, when in reality it should remember its position.

### Platform Information

Komodo IDE 10.0.0 build 89159 Ubuntu 14.04 x64

**Comment by cavac** [comment]
Update: Double-clicking the "Projects" sidebar header pops it up. But this is inconsistent with the "dragable" mouse cursor.

**Comment by lagbox** [comment]
Does double-clicking on the bar for the widget help?

**Comment by cavac** [comment]
Yes, double-clicking helps to open it. After that, it can be resized normally, although it still opens minimized after a restart.
