### ISSUE TITLE
Remove source code pro from default color schemes

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1484]
It doesn't support Cyrillic characters.

**Comment by Defman21** [comment]
It does not support **italic** style (and bold probably) for Cyrillic.

**Comment by Naatan** [comment]
Tomato tomato .. uhh .. that doesn't work in writing.

**Comment by Defman21** [comment]
Tomato?

**Comment by cyberbit** [comment]
Tomato.

**Comment by Defman21** [comment]
That's out of my understanding, tomatoes :tomato:

**Comment by cyberbit** [comment]
Tomatoes, potatoes.
