### ISSUE TITLE
Show Editor tabs is always "checked"

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1485]
### Short Summary

Even if it's disabled, it shows as checked.
### Platform Information

_Komodo Edit or IDE?_ IDE
_Komodo Version?_ 10.0.1-beta 88160
_Operating System (and version)?_ elementary OS 0.4

**Comment by cgchoffman** [comment]
I'm not seeing this on Windows or OSX.  Are you able to repro with a clean profile?

**Comment by Defman21** [comment]
Able to reproduce in Safe-mode, I'm on Linux though.

**Comment by cgchoffman** [comment]
Ok, thanks for confirming.

**Comment by mitchell-as** [comment]
I'm not seeing this on Linux in master. @Defman21 are you still seeing this with the latest nightly build?

**Comment by Defman21** [comment]
Yes. Gonna try safe mode though.

**Comment by Defman21** [comment]
I'm able to reproduce.
Komodo IDE, version 10.0.1, build 89206, platform linux-x86_64.
Built on Tue Jun 7 01:34:39 2016.

**Comment by mitchell-as** [comment]
@Naatan can you reproduce this on Linux? I cannot.

**Comment by Naatan** [comment]
I am not able to reproduce this either.

@Defman21 exactly what steps are you taking?

**Comment by Defman21** [comment]
Open Hamburger Menu - View - Toolbars - Show Editor Tabs.

**Comment by Defman21** [comment]
Note I'm not able to reproduce it when using Alt menu.

**Comment by Naatan** [comment]
Reproduced using the unified menu.

**Comment by Naatan** [comment]
So the issue here is that the Open Files module does not use a controller for its commands, which makes it so that the commands do not update properly. Re-targeting this for 10.1 as I'll need to implement a controller, which is too much for a patch release.

**Comment by cgchoffman** [comment]
Taking this.  A silly aesthetic that should be fixed.
