### ISSUE TITLE
Preferences window category list icon padding too small

### ISSUE THREAD

**Issue by cyberbit** [Komodo/KomodoEdit#1486]
### Short Summary
The icons in the list of categories in the Preferences dialog are scrunched closer together than in previous versions. 

### Steps to Reproduce
Open preferences window.

### Expected results
A space between the icon and text in the category list.

### Actual results
Icons are very close to item text in the category list.

### Platform Information
*Komodo Edit or IDE?* Edit
*Komodo Version?* 10
*Operating System (and version)?* Windows 7

### Additional Information
![image](https://cloud.githubusercontent.com/assets/7350183/15327992/05277014-1c19-11e6-8a7c-0114d320251f.png)

**Comment by Defman21** [comment]
Depends on the font.
![qwdqwdqwd](https://cloud.githubusercontent.com/assets/7100645/15328728/e8d00dce-1c66-11e6-8dbf-99ba6d8fc2f6.png)

**Comment by Naatan** [comment]
Yay custom fonts.

**Comment by Defman21** [comment]
Yay it's configurable :P

**Comment by tonyattwood** [comment]
Hi,

I've recently  met my old friend, he turned  out  to be  a  very creative  person, you may read more about  him here  <http://example.kargobiz.com/e4ghwwo>

Warmest, tony.attwood@ntlworld.com
