### ISSUE TITLE
Context menus very small

### ISSUE THREAD

**Issue by cyberbit** [Komodo/KomodoEdit#1487]
### Short Summary
The context and tools menus are very dense and small.
![image](https://cloud.githubusercontent.com/assets/7350183/15328552/e0a12eb8-1c1a-11e6-9daf-fce993623906.png) ![image](https://cloud.githubusercontent.com/assets/7350183/15328539/d6dc1794-1c1a-11e6-8850-5cc5073c49d4.png)

### Steps to Reproduce
Right-click in a file, or click anything on the menu bar.

### Expected results
Appropriately spaced and padded menus.

### Actual results
A menu that resembles a Whopper Jr.

### Platform Information

*Komodo Edit or IDE?* Edit
*Komodo Version?* 10.0.0
*Operating System (and version)?* Windows 7

### Additional Information
If this is a Color Scheme setting, I'd love to hear about it.

**Comment by Naatan** [comment]
> If this is a Color Scheme setting, I'd love to hear about it. 

It is! Check out Tools > Color Scheme Editor, and then check "Interface" from the drop down at the top left.

**Comment by cyberbit** [comment]
@Naatan I found the Interface settings, but I can't find anything that's menu-specific. Could you point me in the right direction? Thanks!

**Comment by Defman21** [comment]
Yeah, it's not that obviously so there's a suggestion for it #1490

**Comment by Naatan** [comment]
@cyberbit there is no menu specific setting, only a general interface setting. You could use this custom css (which you can enter in the color scheme editor when the Interface dropdown is selected):

```
menupopup label
{
  font-size: 1rem !important;
}
```
