### ISSUE TITLE
Pressing ESC in Color Scheme Editor LESS textbox moves cursor back one character

### ISSUE THREAD

**Issue by cyberbit** [Komodo/KomodoEdit#1489]
### Short Summary
Pressing <kbd>Esc</kbd> in the Color Scheme Editor LESS textbox moves cursor back one character. This continues until it can't anymore.

### Steps to Reproduce
Open Color Scheme Editor. Click into LESS editor. Press <kbd>Esc</kbd>.

### Expected results
Nothing happens.

### Actual results
Cursor moves back one character.

### Platform Information

*Komodo Edit or IDE?* Edit
*Komodo Version?* 10.0.0
*Operating System (and version)?* Windows 7

**Comment by Naatan** [comment]
I cannot reproduce this. @cgchoffman you?

**Comment by cgchoffman** [comment]
Not seeing this on Windows or OSX, Edit or IDE.

@cyberbit, Anything in your logs(*Help > Troubleshooting > View Log File*)? What key binding set are you using(*Edit > Prefs > Keybindings*)?

**Comment by cyberbit** [comment]
Closing, as I haven't been able to reproduce this whatsoever. It may have even been external to Komodo. I'll reopen if I happen upon it again, but it's so minor and obnoxiously specific, that probably won't happen.

**Comment by tonyattwood** [comment]
Hey,

I'm so  happy  to  tell you  about a  cool  place I've  been recently,you're gonna enjoy it,   just take a look  <http://favor.aldermanfamily.net/e4cbpgwk>


Good wishes, tony.attwood@ntlworld.com
