### ISSUE TITLE
Foreground for state ok, state info, etc. not configurable

### ISSUE THREAD

**Issue by cyberbit** [Komodo/KomodoEdit#1494]
### Short Summary
In some themes, the text on notifications is hard to read. The state foreground is configurable, but this doesn't appear to affect the special states.

### Steps to Reproduce
Open Color Scheme Editor. Select **Interface**.

### Expected results
All color combinations for elements should be easy to read.

### Actual results
`state ok`, `state info`, etc. are not easy to read, with `state ok` being next to impossible to understand. Again, if this can be CSSd, I would love to know.

### Platform Information

*Komodo Edit or IDE?* Edit
*Komodo Version?* 10.0.0
*Operating System (and version)?* Windows 7

### Additional Information
![image](https://cloud.githubusercontent.com/assets/7350183/15332770/8ea5bec8-1c2c-11e6-90a4-2662b2eb01aa.png)
![image](https://cloud.githubusercontent.com/assets/7350183/15332786/a2748a06-1c2c-11e6-8c0a-8db783460ddf.png)

**Comment by Defman21** [comment]
For now you can use custom CSS in your scheme:

```
tooltip.notify-panel > *, tooltip.notify-panel description {
	color: #ffffff !important;
	opacity: 1 !important;
}
```

Replace `#ffffff` with the color you want.

**Comment by cyberbit** [comment]
Nice, thanks!

**Comment by tonyattwood** [comment]
Hey,
I've been looking for some interesting info  when I found this stuff, please tell me what  you think <http://fair.hpcentralcoolingandheating.com/e4vllv>
Sincerely, tony.attwood@ntlworld.com
