### ISSUE TITLE
Open Files: No 'x' to close file if file name is too long.

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1497]
### Short Summary

The closing icon doesn't show up if one of the files names is longer than the width of the Sidebar.
I opened `Docker-and-Vagrant-Integration.markdown` from the docs and the issue was very apparent but you can get it by simply scaling the sidepane down so that it's too narrow for one of your files names.

My thoughts are two points:
- make a min width for the sidepane that seems reasonable
- Allow the icons to sit on top of the filenames somehow

**Comment by we3geeks** [comment]
Same as #168?

**Comment by Naatan** [comment]
Yup, thanks @we3geeks. I've targeted that one for 10.1.

**Comment by cgchoffman** [comment]
Thanks @we3geeks.  I knew I had seen that ticket but couldn't find it.

**Comment by tonyattwood** [comment]
Hi,


I just wanted to share with  you some pics of  my  favourite place, it;s so awesome! Here is  the link for the pics <http://follow.onefirstdate.net/e4jewn>

Warmest, tony.attwood@ntlworld.com
