### ISSUE TITLE
restoreOnRestart not working in Komodo 10.0.0, nor working properly in 9.3

### ISSUE THREAD

**Issue by jimmeek** [Komodo/KomodoEdit#1498]
### Short Summary
Just installed Komodo IDE 10.  Windows 7 professional, 64-bit.
The numerous files/windows I had open in 9.3 do not open in 10.0.
I examined the prefs.xml file and found  <boolean id="restoreOnRestart">1</boolean>.
I copied the history.sqlite database to the C:\Users\<myname>\AppData\Local\ActiveState\KomodoIDE\10.0 directory.

No joy.

Also, on upgrade to 9.3 from 8.5, I find that although restoreOnRestart works, the Komodo window titles are not set to the file names, as they were in 8.5.  The window title will update only if you select the window, either select a different tab in the window, or, if there is only one tab, do a "Split View" and select the split-view tab.

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by Naatan** [comment]
Komodo 10 would not restore files that you had open in a previous major version.

Are you able to reproduce this issue with a single Komodo version? If so, please provide exact reproduction steps.

**Comment by jimmeek** [comment]
I expected that Komodo 10 would restore files I had open in a previous version.
As I am working on multiple projects and have a number of active windows with multiple files open in each, I had hoped that Komodo 10 would would pick up that info from the earlier version.

**Comment by Naatan** [comment]
This is not the case. Komodo 10 is a major upgrade, it does not import everything from previous versions so as to ensure stability of your work environment. Your workspace will operate normally post upgrade, but it will not import the Komodo 9 auto-saved workspace.

**Comment by cgchoffman** [comment]
@jimmeek if you open your project does it not open all your previously open files from the last time you had that project open?  Projects should maintain it's own list of open files.  Workspace restore simply restores the Project, the project then restores the previously open files.

**Comment by cgchoffman** [comment]
Sorry, I was incorrect.  Projects do not import these prefs between major versions.

**Comment by tonyattwood** [comment]
Hello,


I've  recently found that article  on the web and  the facts I had found in  it were  just  shocking! Pleaseread  it here <http://favor.solisflos.com/e4afixjl>


tony.attwood@ntlworld.com
