### ISSUE TITLE
Commit Dialog not picking up my SVN project

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1499]
### Short Summary

The Version Control tab isn't picking up that I have an SVN project open in Places.

### Steps to Reproduce

Open an SVN project in places
Open  Version Control tab *View > Tabs & Sidebars > Version Control

### Expected results

The pane to be doing it's thang

### Actual results

Just gives me the "retry" interface.

**Comment by Naatan** [comment]
Is the .svn folder in the root directory that your Places panel is directed at?

**Comment by davestlyon** [comment]
Same here. The commit button just tells me no files have been checked. But that dialog/panel doesn't display any files. This is even though the version control icon in the left toolbar did let me add the file to the repo, just no committing. Version control history does work in the panel.

In my case, the .svn folder is NOT in the root directory- I have one root folder with vanilla web framework code and then in three separate folders are working copies of our custom code from various spots in the svn repository.

**Comment by Naatan** [comment]
@cgchoffman bump. I cannot reproduce this. Is Places pointed at an SVN folder?

@davestlyon That is how the feature works - you need to point Places at a directory that holds a SVN repository. You can still call the commit dialog for sub folders by right clicking a folder/file and using the source code control menu there.

**Comment by cgchoffman** [comment]
Sorry, I must have dreamed that I replied!  I really thought I had.  Yes there is a `.svn` folder in the Places root.  I checked out the update server code and opened the `aus.komodoproject` file therein. Version Control pane is empty.

**Comment by Naatan** [comment]
And this is still reproducible?

**Comment by cgchoffman** [comment]
Hrmm, it's not reproducible any more.  I think I must have missed something along the way.  it's working now.
