### ISSUE TITLE
New find window resizes smaller but not larger; no way to resize.

### ISSUE THREAD

**Issue by okinasevych** [Komodo/KomodoEdit#150]
Komodo Edit, version 9.0.0, build 15707, platform macosx. Built on Thu Mar 19 06:08:01 2015.

![screen shot 2015-04-09 at 2 49 03 pm](https://cloud.githubusercontent.com/assets/467636/7075656/4d9a19a2-dec9-11e4-8f5d-bc1bb0878ef7.png)

Selected a folder in Places, from context menu select Find. Change "Search in" to Current Document, then change it back to Files. Window does not resize, therefore buttons become inaccessible. 

One of several errors experienced with the new Find window.

**Comment by xdestiny** [comment]
This happens on Windows 7 as well.

If you open a Find/Replace dialog on the current document, for example Ctrl+H, and change the "Search in" control to "Files" the content of the dialog will change but not resize it to fit in the new elements. 

![komod_find](https://cloud.githubusercontent.com/assets/1251646/7088775/cbacea2c-df96-11e4-93dc-31e9ae0110c6.png)

**Comment by cgchoffman** [comment]
This has been reported and fix: issue #79.  Please use the latest nightly for the fix: http://downloads.activestate.com/Komodo/nightly/komodoedit/latest/
