### ISSUE TITLE
Separate some of the colour options

### ISSUE THREAD

**Issue by jsnjack** [Komodo/KomodoEdit#1504]
### Short Summary
Komodo is very flexible in adjusting user interface. However, I think it would be nice to have it even more flexible. Consider example on the screenshot.

There is one color option that is responsible for the elements pointed by red arrows. However, when it is an element of the interface (like in the top part of the image) it would be nice to have them dark (dark blue for example). If I make them dark blue, then the selected text in the Find dialog at the bottom of the image is hard to read.

For my personal taste, I would love to match background of the toolbar buttons with the background of the toolbar itself. However, if I do that I can't distinguish selected option in the Commando.

Also for me, naming in the scheme editor is not obvious at all. I have to check every element to find out for what it is responsible for.  

### Platform Information
Komodo Edit, version 10.0.0, build 17209, platform linux-x86_64

### Additional Information
![img](https://cloud.githubusercontent.com/assets/5493713/15339726/1277c2b0-1c86-11e6-82ea-c8f50d583e2f.png)

**Comment by Naatan** [comment]
The color options have purposefully been biased a little because otherwise you end up with sooo many options it defeats the purpose (I learned from my mistakes with Komodo 8 and 9).

Instead what you can do is put your own custom CSS rules in the color scheme editor:

![image](https://cloud.githubusercontent.com/assets/278649/15340580/19b0d7fc-1c58-11e6-9d97-447d5bb594f3.png)

I will soon be updating the docs site with more information on how to do this.

**Comment by jsnjack** [comment]
What is the easiest way to find out id or class of the element?

**Comment by Naatan** [comment]
Using DOM Inspector: http://komodoide.com/packages/addons/dom-inspector/
Combined with Element Inspector: http://komodoide.com/packages/addons/element-inspector/

**Comment by jsnjack** [comment]
Thanks!

**Comment by jsnjack** [comment]
![img2](https://cloud.githubusercontent.com/assets/5493713/15371555/547731d0-1d3c-11e6-8d20-9def5a2a9437.png)
@Naatan I played with these 2 plugins a bit. But, I think, what I am trying to say is that color constraint of the some elements is not logical. 

For example, compare elements 2, 3, 4 on the image. I would expect these all elements to have the same color. And element 5 - how is it related to the button's color? And more important why does it affect text selection color? I also think, that elements 1 should have a separate color setting. 

I hear you that having dozens of color settings is not the solution and I completely agree with you. I also think that even now there are too many color options. For example, why `secondary special` is responsible for the color of the some(!) buttons (green on the picture) when there is a special `button` setting!

I was thinking, that maybe the following color settings will be easier to understand:
 - main interface color (main panel color) - it's gray on the screenshot. To help user to distinguish different panels, like headerbar and filebar, you can set different transparency.
 - button color - reaponsible for ALL buttons (text color/ background color)
 - input field color - text, background, selection color and etc.
 - icon color (?) - I would set it to be the same as button text color
 - scrollbar color
 - selection color - I would also tie it to the color of the elements 1 on the screenshot. In a sense, it is selection too
 - widget color (Places, Syntax Check and etc) - background, font color

In that way It will be easy to understand what is responsible for what.

Sorry for being so persistent.

**Comment by Naatan** [comment]
I think those concerns fall mostly under this ticket:

https://github.com/Komodo/KomodoEdit/issues/1490

There is definitely a logic to it, but the current naming doesn't really convey it well.
