### ISSUE TITLE
Environment Prefs... button does nothing

### ISSUE THREAD

**Issue by wttw** [Komodo/KomodoEdit#1511]
### Short Summary

In "Preferences -> Languages -> Go" the "Environment Prefs..." button does nothing.

### Steps to Reproduce

Open the preferences dialog, click the button.

(It's possible that the GOPATH environment variable needs to be unset for the button to be displayed - that's normal on OS X, possibly rarer for Go devs on other platforms)

### Expected results

Something.

### Actual results

Nothing.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.0.0 build 89159
*Operating System (and version)?* OS X 10.11.4

### Additional Information

 -- eg. Error logs, screenshots, workarounds --
<img width="616" alt="preferences" src="https://cloud.githubusercontent.com/assets/389596/15343262/2560432e-1c50-11e6-88c2-340d4eda345e.png">

**Comment by Naatan** [comment]
Note this button is just a link to the Environment prefs, while obviously it needs to be fixed you can just manually navigate there for now.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/komodo-go/commit/49261cd09ba3793ae0258e14aa091b0bbbd1fbec
