### ISSUE TITLE
Feature Showcase unexpected behaviour

### ISSUE THREAD

**Issue by wttw** [Komodo/KomodoEdit#1512]
### Short Summary

"Help -> Tutorials -> Feature Showcase" fails with an error:

<img width="640" alt="komodo" src="https://cloud.githubusercontent.com/assets/389596/15343436/95f7dfe2-1c51-11e6-9c99-166be0012448.png">

(The directory .../samples exists but has no showcase_tutorials subdirectory).

Closing the error dialog (with the window close button or Cancel) opens the default brower to http://docs.komodoide.com/Manual/tutorial/showcasetut - which has no content other than navigation.

Hitting "OK" gives this error:

<img width="640" alt="komodo_alert" src="https://cloud.githubusercontent.com/assets/389596/15343481/fdc4501a-1c51-11e6-9542-a1e5c3e1f58f.png">

Closing this dialog or hitting "OK" opens the default browser to the same empty URL.

### Steps to Reproduce

Help -> Tutorials -> Feature Showcase

### Expected results

I'm not sure. Opening a project, I expect.

### Actual results

Error dialogs.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.0.0 build 89159
*Operating System (and version)?* OS X 10.11.4

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by Naatan** [comment]
Thanks for reporting!

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/0c4a355792d430ffc9c3035cc8b80700d007575f
