### ISSUE TITLE
Go to Definition does not work with double-sigil deref in Perl

### ISSUE THREAD

**Issue by shawnlaffan** [Komodo/KomodoEdit#1514]
### Short Summary

Go to Definition does not move the cursor when a perl reference is used in a double sigil deref.  

Reproduced in both 9.3 and 10.0

### Steps to Reproduce

Load the code below into Komodo.  

```perl
my $hashref = {};
my %y = %$hashref;
my %z = %{$hashref};
```

1.  Locate the cursor on the second line (%z assignment) and then run Go to Definition on $hashref in that line.  The cursor moves to the first line.
2.  Locate the cursor on the second line (%y assignment) and then run Go to Definition on $hashref in that line.  The cursor does not move.

The same occurs for array and scalar refs.  e.g.

```perl
my $arrayref = [];
my @a2 = @$arrayref;
my @a1 = @{$arrayref};

my $scalar = '';
my $s1 = $$scalar;
my $s2 = ${$scalar};
```

### Expected results

Cursor should move to the variable definition in all cases.

### Actual results

See above.

### Platform Information

*Komodo Edit or IDE?*   IDE
*Komodo Version?*    9.3.2 and 10.0
*Operating System (and version)?*   Windows 10

**Comment by mitchell-as** [comment]
Thanks for the report!

**Comment by shawnlaffan** [comment]
No worries.  

Ref generation is also affected:

```perl
my @array;
my $aref1 = \ @array;  #  works
my $aref2 = \@array;   #  does not work
my $aref3 = [@array];  #  works

my %hash;
my $href1 = \ %hash;   # works
my $href2 = \%hash;    # does not work
my %href3 = {%hash};   # works

my $sc = '';
my $sref1 = \ $sc;  #  works
my $sref2 = \$sc;   #  does not work
```
