### ISSUE TITLE
Enabling focus mode throws errors

### ISSUE THREAD

**Issue by wttw** [Komodo/KomodoEdit#1515]
### Short Summary
Focus mode pops up a big, red warning box:

[Exception... "[JavaScript Error: "elems.menuBc is null" {file: "chrome://focusmode/content/focusmode.js" line: 86}]'[JavaScript Error: "elems.menuBc is null" {file: "chrome://focusmode/content/focusmode.js" line: 86}]' when calling method: [nsIController::doCommand]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 239"  data: yes]
                                         Tue May 17 2016 22:32:31 GMT-0700 (PDT)

### Steps to Reproduce

View -> Toggle Focus Mode

### Expected results

Focus mode

### Actual results

Focus mode + giant red error box

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.0.0 build 89159
*Operating System (and version)?* OS X 10.11.4

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by mitchell-as** [comment]
Can you reproduce this in safe mode? (Help > Troubleshooting > Restart in Safe mode) I cannot reproduce this.

**Comment by wttw** [comment]
Yes, exactly the same error in safe mode.

**Comment by mitchell-as** [comment]
@Naatan or @cgchoffman can either of you reproduce this or know what might be the cause?

**Comment by Naatan** [comment]
I see the issue, it's OSX specific. Will fix asap.

**Comment by Naatan** [comment]
Fixed in nightly: http://downloads.activestate.com/Komodo/nightly/komodoide/latest/
