### ISSUE TITLE
Duplicate entries in Tools menu

### ISSUE THREAD

**Issue by wttw** [Komodo/KomodoEdit#1516]
### Short Summary

Trivial. There are two identical "Compare Files ..." entries on the Tools menu.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.0.0 build 89159
*Operating System (and version)?* OS X 10.11.4

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by mitchell-as** [comment]
Thanks for catching this!

**Comment by Defman21** [comment]
Fixed! https://github.com/Komodo/KomodoEdit/pull/1587

**Comment by Defman21** [comment]
@cgchoffman don't forget to close this one :stuck_out_tongue:

**Comment by cgchoffman** [comment]
...Let me get through the 100 emails in my inbox...

**Comment by Defman21** [comment]
Why not GitHub notifications?

**Comment by Naatan** [comment]
This wasn't integrated to IDE it seems.

**Comment by cgchoffman** [comment]
it has.  It's on my computer. Easy on me folks.  I'm 3 hours behind the closest person here :P

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/05aef3363a3915e7e411f40a66b8d2e3499e935f
