### ISSUE TITLE
Loaded file has indention: "space,8" while edit->file prefs show "tab,4"

### ISSUE THREAD

**Issue by oehhar** [Komodo/KomodoEdit#1518]
Thank you for Komodo 10. I see that lot of work was done, unfortunately nothing to fix "anoying bugs" which were introduced in Komodo 9 and are stil present. Here is an example:

Set your indention settings to "tab,4,4"
Load a file you have never used in tcl.
The used indention is "space,8,8"
The edit->file prefs shows "tab,4,4"

This was reported in many tickets. The workaround is to:
- set manually the settings to "space,8,8" and then to "tab,4,4"
- this must be done for each file

- This is present in Komodo 9 and 10

**Comment by mitchell-as** [comment]
Hi, do you happen to have "Allow file contents to override Tab and Indentation settings" checked in Edit > Preferences > Editor > Indentation?

**Comment by oehhar** [comment]
> Hi, do you happen to have "Allow file contents to override Tab and Indentation settings" checked in Edit > Preferences > Editor > Indentation?

No. The point is, that the preference shows something else than what is active. It is a very well known bug since 9.2...

**Comment by mitchell-as** [comment]
When you say "the used indentation is 'space,8,8'", do you mean that Komodo inserts 8 spaces when you press the Tab key? Or that the file uses 8 spaces per tab/indent and that Komodo still uses 4 spaces per tab?

**Comment by oehhar** [comment]
> When you say "the used indentation is 'space,8,8'", do you mean that Komodo inserts 8 spaces when you press the Tab key? Or that the file uses 8 spaces per tab/indent and that Komodo still uses 4 spaces per tab?

Komodo uses "space,8,8". What the file uses is not important.

**Comment by mitchell-as** [comment]
Okay, thanks.

**Comment by Naatan** [comment]
@oehhar I understand your frustration, but for what it's worth @mitchell-as has put a ton of effort into indentation bugs for Komodo X. Unfortunately the underlying mechanic was so broken (as was evident) that not everything got flushed out. This is a big priority for us though, so thanks for reporting!

**Comment by oehhar** [comment]
Thank you for fixing this. Komodo 10 will get a new try when this is released.

I personally don't close any bug which is not verified by the reporter for effectiveness. This was also the style at ActiveState before Andreas Cupries and collegues left.
I invite ActiveState to return to the old bug style and let the reporters verify the effectiveness of a patch and only then close them.
This would avoid to loose bug tickets as happened here.

**Comment by Naatan** [comment]
Unfortunately that would lead to the old style of having 10.000 bugs open and create a huge backlog of bugs that need to be verified. We're not averse to reopening bugs, so instead you can just post here if the bug is still present once we release an update and we can reopen it at that point.

**Comment by ereich1217** [comment]
I'm still seeing indentation issues in build 10.1.4.

I have 3 C++ files open and 2 of them have the correct indentation behavior and the third does not.  The third is using 2-spaces per indent whereas the others are using 4-spaces, which is what I want.

**Comment by cgchoffman** [comment]
@ereich1217, please file a new report.  This bug has been closed.  We can't make any assumptions about your issue based on this ticket so we need a full report from you.  Sorry for the inconvenience.

**Comment by oehhar** [comment]
For my experience, the issue is the option "Let file contents to overrride Tan and Indention settings".
If you open a file you have edited with a pre 10 Kommodo, do the following:
   -   uncheck the upper setting
   -   change all indention settings to another value
   -   press apply
   -   change the idention settings back (but do not check "Let file contents..."
   -   press Ok

**Comment by Naatan** [comment]
Please file a new bug.
