### ISSUE TITLE
Persistent storage of widget layout

### ISSUE THREAD

**Issue by hoppfrosch** [Komodo/KomodoEdit#1519]
### Short Summary

_Added by CareyH_

---

Komodo should persist all widget layout information through a restart:
- Order
- Placement (eg. two widget embedded beside eachother)
- detached state

---

As a followup of #1433:
Reordering tabs from bottom pane ("Version Control", Breakpoints" ...) is not stored persistently. 
### Steps to Reproduce

Having bottom tab visible: reorder the tabs on bottom pane, reorder the tabs, restart Komodo: 
### Expected results

Ordering of pane tabs should be persistent
### Actual Result

The new ordering of the tabs is lost and the original order is active again
### Platform Information

_Komodo IDE, version 10.0.1, build 89160, platform win32-x86._
_Win7 SP1 Ultimate 64-bit_

**Comment by cgchoffman** [comment]
It looks like if `ko.uilayout` started using `ko.widget` properly then.  It doesn't seem like these two things should be mutually exclusive.  If `ko.uilayout` wrapped `ko.widget.unload` and `ko.widget.restoreLayout` then we would get more logical UI restoration.

**Comment by cgchoffman** [comment]
Closing note: We will actually prefer to move away from `ko.uilayout` in general.  We'd like to focus the various tasks that that code handles into more specific tools.  Basically, we will eventually deprecate `ko.uilayout` and move it's functions into more logic modules.

**Comment by hoppfrosch** [comment]
Does not work yet - running Komodo IDE, version 10.2.0-alpha1, build 89795, platform win32-x86. Built on Fri Jan 27 01:00:30 2017.

Steps to reproduce:
* Within bottom panel drag-and-drop Tab "Version Control" from first to the last position 
* Restart Komodo

-> "Version Control"  is in the first position again

**Comment by cgchoffman** [comment]
This unfortunately won't get priority for a little while.  Is this a big issue for you @hoppfrosch, it seems like a minor annoyance.

**Comment by hoppfrosch** [comment]
Is this a big thing for me? yesno - but as long as issue #1433 is not fixed, I've got no chance to use my prefered difftool. Having the issue above not fixed, I cannot move the "version control" tab persistently from the first position to avoid komodoide permanently opening my preferred difftool on start (as "version control" tab is the default tab on komodo-start).

So I would rather see one of the two issues fixed (#1519 or preferred #1433)  in order to be able to use my external difftool

**Comment by cgchoffman** [comment]
I didn't say it shouldn't be fixed. I just asked how big of an issue it is for you :) Sounds like it's not a big issue and @Naatan has labelled it accordingly.

**Comment by hoppfrosch** [comment]
I didn't say its not a big issue for me. I said as long it is a big thing, as long as one of both is issues #1519 or  #1433 is not fixed, ;-)

**Comment by cgchoffman** [comment]
This should be resolved bye #1975.
