### ISSUE TITLE
Undo working as all or nothing

### ISSUE THREAD

**Issue by jkchant** [Komodo/KomodoEdit#1522]
When I make a big change to a file - select a large section and comment or uncomment, or copy/paste a large section of code, if I then make a series of smaller changes then hit undo - it undoes to before the big change, not to the last change I made. So if I copy and paste a large section of code into my file, make other changes then hit undo (CTRL-Z or on the toolbar) it reverts back to before the paste. 

If I click save after the paste (or comment/uncomment) then make more changes, it still reverts back to before the paste when I hit undo.  Hitting redo redoes everything including the last change made.

### Platform Information

*Komodo IDE* 
*Komodo Version?* 10
*Operating System (and version)?* Windows 7 64-bit

**Comment by jkchant** [comment]
May be related to  #1509 as I am experiencing that as well, and seems to occur after the commenting bug.

**Comment by mitchell-as** [comment]
Thanks for reporting. I believe that you are correct in that it is likely the error from #1509 has de-synchronized the editor's undo state.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoEdit/commit/55967bc4880ee5470780028411bf4fe9a4404047
