### ISSUE TITLE
Preserve servers when upgrading across major versions

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1524]
See http://forum.komodoide.com/t/komodo-edit-10-doesnt-migrate-remote-servers-from-ke-9/2715/4

**Comment by cgchoffman** [comment]
It looks like people upgrading to 10.1 will hit this issue as well.  I'm going to put priority on this.  Feel free to pull it off but it seems like a major UX issue.

**Comment by Naatan** [comment]
Only if they are upgrading from 9. People upgrading from 10.0 to 10.1 should not have this issue.

**Comment by cgchoffman** [comment]
That does not appear to be the case but I'll double check.

**Comment by Naatan** [comment]
If my above statement is false then this would be a bug.

**Comment by cgchoffman** [comment]
NVM, the user reporting the issue hadn't used 10 on that computer.  It was importing K9 settings so it's covered by this bug.  I tested upgrading from 10 to 10.1 and it works fine.

**Comment by Naatan** [comment]
Punting to 11 since this only affects major upgrades.

**Comment by Naatan** [comment]
Actually it could still affect stragglers, nvm.
