### ISSUE TITLE
Unable to compile outline.go

### ISSUE THREAD

**Issue by wttw** [Komodo/KomodoEdit#1528]
### Short Summary

This looks like #587 or #952.

Opening something.go gives "Error compiling outline: Unable to compile 'outline.go'[Errno 2] No such file or directory: 'go'" twice in the notifications tab, tagged as status-message and codeintel-message-event.

### Steps to Reproduce

Open a go source file.

### Expected results

Go codeintel functionality.

### Actual results

Errors as given above.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.0.0 build 89159
*Operating System (and version)?* OS X 10.11.4

### Additional Information

go is 1.6.2, installed as /usr/local/bin/go

PATH is set in Komodo preferences as /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

PATH in the environment Komodo is launched in is /usr/bin:/bin:/usr/sbin:/sbin. This is not configurable to be anything else for GUI applications launched in a normal way on OS X. But launching komodo with an explicit PATH set in the environment that includes /usr/local/bin leads to the same errors, so it's not an environment PATH issue.

 -- eg. Error logs, screenshots, workarounds --

**Comment by wttw** [comment]
Explicitly setting the path to go in Preferences->Languages->Go doesn't change anything.

**Comment by Naatan** [comment]
Could you see if setting your GOPATH env variable in `Prefs > Environment` resolves this issue?

To be certain that it takes I would recommend a restart. It should not be necessary, but better to be sure.

**Comment by wttw** [comment]
GOPATH is set both in the real environment, and in Preferences->Environment.

**Comment by Naatan** [comment]
Thanks @wttw, I've targeted #952 for 10.1 and will close this one as a duplicate.
