### ISSUE TITLE
Minimap gets squashed on OSX

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1529]
See OTRS #50375

Clicking the minimap splitter seems to "un-squash" it.

**Comment by Naatan** [comment]
@cgchoffman sadly my OSX build appears to be completely hosed :( Can you look into this one?

**Comment by cgchoffman** [comment]
@Naatan I can't find a ticket in OTRS relating to this.  That number pulls up some sales ticket.  I can't seem to reproduce the issue either.  Can you have a look for the OTRS ticket and link it?

**Comment by cgchoffman** [comment]
Switching ownership to you for now @Naatan.
