### ISSUE TITLE
Unable to go to definition of sys module

### ISSUE THREAD

**Issue by justquick** [Komodo/KomodoEdit#153]
When executing cmd_goToDefinition for the sys module in the stdlib i get the following error message

"Cannot show definition: symbol is defined in the stdlib or in an API catalog. Would you like to open the online language help for this symbol?"

![screenshot 2015-04-10 16 22 52](https://cloud.githubusercontent.com/assets/35289/7096806/8cc3b694-df9e-11e4-97fc-7864582ab8de.png)

Clicking yes takes me to a google search of "site:docs.activestate.com/activepython sys"

Other stdlib modules (eg os) do not have this issue and it seems to be pretty random.

OSX 10.10.3
Python 2.7.9 (pyenv)
Komodo Edit, version 9.0.0, build 15707, platform macosx.
Built on Thu Mar 19 06:08:01 2015.

Full logfile: https://gist.github.com/justquick/815db5ab9004b90bffe2

**Comment by Naatan** [comment]
I think this is because there is no sys.py in the python library directory, while there is an os.py. I'm not familiar with the low level intricacies of Python, so not sure if this ought to be something we should be able to resolve or not.

@toddw-as comment?

**Comment by justquick** [comment]
my bad, this is the expected behavior. thanks

**Comment by cgchoffman** [comment]
Hey you can't take all the blame.  I recommended you file this bug ;)
