### ISSUE TITLE
missing left angle character for viewing tabs to the left

### ISSUE THREAD

**Issue by hobbsd** [Komodo/KomodoEdit#1535]
### Short Summary
The character for the left scroll on the tabs bar, which appears when there are too many tabs open for them all to show at once, is missing. It looks like this:
![missing-character](https://cloud.githubusercontent.com/assets/1676348/15372830/69e84d96-1d10-11e6-9415-f5577ebc3cb9.png)

### Platform Information
Komodo Edit, version 10.0.0, build 17209, platform win32-x86.
Built on Thu May 12 00:43:26 2016.

**Comment by Naatan** [comment]
Not seeing this on Linux. I can't test windows right now since I am testing a licensing issue, @cgchoffman can you try?

**Comment by cgchoffman** [comment]
Looks to be Edit only.  Did you test Edit or IDE @Naatan ?

**Comment by Naatan** [comment]
Ah I didnt test edit. Looks like the edit icon definitions are out of date.

**Comment by cgchoffman** [comment]
Possible Cause is the existence of: https://github.com/Komodo/KomodoEdit/tree/master/src/chrome/komodo/skin/plat/shared

Getting confirmation from @Naatan in slack.

I'd like to point out that I would have NOT been able to figure this one out when we started development on KomodoX  #progression BOOM.

**Comment by Naatan** [comment]
I don't see why the existence of that folder should matter, none of its files are being included. It's more likely that we didn't integrate an icon change. Did you verify Komodo Edit's icon definitions (global/icons) are the same as IDE's? (they should be).

**Comment by cgchoffman** [comment]
That's the only explanation for the icon not rendering.  icon.less has the right class. One of the files in shared is overriding it as far as I can tell.

**Comment by Naatan** [comment]
If that's the case it would mean it;s still being included somewhere. Of course the directory should be deleted, but more importantly it should not be referenced anywhere.

**Comment by cgchoffman** [comment]
I think you were right in this comment: https://github.com/Komodo/KomodoEdit/issues/1535#issuecomment-224620488

*global/icons* might be out of sync.  I'll checkout it's history to see if something if missing.
