### ISSUE TITLE
Change in File Position status indicator resizes file edit pane

### ISSUE THREAD

**Issue by hobbsd** [Komodo/KomodoEdit#1536]
### Short Summary
Changing location in an open file makes the `File Position` status change, and when it changes to a wider size (e.g., when going from line 1 col 1 to line 100 col 66) it makes the corresponding editor pane wider.

### Steps to Reproduce
Open Komodo with a bunch of files open and vertically split view, change the cursor position from line 1 col 1 to somewhere else with higher numbers.

### Expected results
Edit pane should stay the same width.

### Actual results
It widens a bit.

### Platform Information
Komodo Edit, version 10.0.0, build 17209, platform win32-x86.
Built on Thu May 12 00:43:26 2016.

### Additional Information
Resize the split view using the middle bar by any amount, and the problem goes away.

**Comment by Naatan** [comment]
Fixed in nightly: http://downloads.activestate.com/Komodo/nightly/komodoide/latest/

**Comment by th3coop** [comment]
^^ Deleted spam.
