### ISSUE TITLE
Interactive Shell: OSX: Input appears below window edge under output

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1537]
### Short Summary

I keep having the interactive shell input field sitting below the window edge so you can see it.  It won't come into full view until you hit `up` twice to get the last command or you start typing.

### Steps to Reproduce

I can only reproduce this on OSX ... so get a mac first
Tools > Interactive Shell > Python
paste the following into the shell.  Make sure that you add additional `x`s if needed to make the input take up multiple lines
```
print('pizza is good. xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')
```
Press enter

### Expected results

Input field to be in full view

### Actual results

See this screenshot:
<img width="796" alt="screen shot 2016-05-18 at 3 08 21 pm" src="https://cloud.githubusercontent.com/assets/655154/15376611/ec01ce5c-1d0a-11e6-91b1-2ac0f3ac5279.png">

### Platform Information

*Operating System (and version)?* **OSX**

**Comment by mitchell-as** [comment]
@cgchoffman can you still reproduce this? For some reason I cannot on my OSX box. I get the following:
