### ISSUE TITLE
breakpoint pane in 10.0 does not show the breakpoint controls

### ISSUE THREAD

**Issue by shawnlaffan** [Komodo/KomodoEdit#1540]
### Short Summary

The breakpoint pane in 10.0 does not show the breakpoint controls until the pane is detached and expanded.  

### Steps to Reproduce

Set a breakpoint in a file and open the breakpoints pane.  

### Expected results

The controls at the bottom of the pane should be visible, as per 9.3 (see screenshot below).

### Actual results

They are not visible.  They can be shown if the pane is detached and then the bottom of the window is dragged downwards.  See screenshots below.  

### Platform Information

*Komodo Edit or IDE?*   IDE
*Komodo Version?*     10.0
*Operating System (and version)?*   Win 10.  

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

Version 9.  Controls are at the bottom of the window.  
![breakpoints_9](https://cloud.githubusercontent.com/assets/1332405/15378187/a1839ec4-1da4-11e6-945e-44a17f67dcb9.png)

Version 10.  No controls visible.
![breakpoints_10](https://cloud.githubusercontent.com/assets/1332405/15378315/c6134644-1da5-11e6-8edb-b656892b073f.png)

Version 10, pane detached.  Controls not visible. 
![breakpoints_10_on_detach](https://cloud.githubusercontent.com/assets/1332405/15378313/bec46d28-1da5-11e6-8a3b-6db7ad1c7a7f.png)

Version 10, pane detached.  Controls visible after dragging the bottom of the window to increase its size.
![breakpoints_10_detach_expanded](https://cloud.githubusercontent.com/assets/1332405/15378314/c2daacec-1da5-11e6-80b3-c58dae25dac0.png)

**Comment by shawnlaffan** [comment]
After more poking around, it seems to be a function of the bottom pane size.  It's also not just the Breakpoints tab.  

Any tools at the bottom of the tabs in the bottom pane are not shown when the pane height is small for the Syntax Checking and Run Output tabs.  Raising the height makes them visible (they rise up from the bottom of the window).  

The Notifications and Console tabs are unaffected.

**Comment by mitchell-as** [comment]
You're right. The bottom pane size needs to be a bit larger by default in order to show some of the tab contents. Thanks for noticing this!

**Comment by shawnlaffan** [comment]
Thanks.  Increasing the default pane size won't stop them from disappearing when the pane is reduced in size, so there is still scope for user confusion.

**Comment by tonyattwood** [comment]
Hello,

There is  a  letter that came to me as a complete surprise, you may find it interesting,  please read it  here <http://favor.greaterdfw.com/e4zos>

Good wishes, tony.attwood@ntlworld.com

**Comment by tonyattwood** [comment]
Hi,

I'd like to invite  you to my party, it's gonna be a surprise  for my family, here is the invitation <http://enjoy.robdavisphoto.com/e4kmlek>

tony.attwood@ntlworld.com
