### ISSUE TITLE
Python console can't seem to handle ascii chars

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1541]
### Short Summary
```
path = u'/Users/careyh/Projects/TEMP/testing-1510/TEST_ Month End Madness – what will you get for just $1, $2 or $3?.eml'`
```
The above line of code dropped into the Python interactive shell (*Tools > Interactive Shell > Python*) will fail but it shouldn't.

It will execute in a system terminal running the Python interpreter.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoIDE/commit/baad8492dd1ffa8c9ecad99b180fe992953231dd
