### ISSUE TITLE
keybinding for cmd_newlineExtra should be Shift+Return

### ISSUE THREAD

**Issue by shawnlaffan** [Komodo/KomodoEdit#1542]
The keybinding for cmd_newlineExtra in Default.kkf has spaces and thus does not work.  The keybindings editor lists it as  `Shift, +, Return`.

Line 17 is:
`binding cmd_newlineExtra Shift + Return`

but should be:
`binding cmd_newlineExtra Shift+Return`

**Comment by cgchoffman** [comment]
This is fixed and will be in 10.0.1

**Comment by shawnlaffan** [comment]
Thanks for that.

Shawn.

**Comment by cgchoffman** [comment]
No worries.  I had to make sure I wasn't lying to you so I double checked https://github.com/Komodo/KomodoEdit/blob/master/src/schemes/Default.p.kkf#L17

Thank you for the report.
