### ISSUE TITLE
IDE X: Vertical splits on OS X change width based on "Ln: x Col: y" changes

### ISSUE THREAD

**Issue by girvo** [Komodo/KomodoEdit#1547]
### Short Summary
I use vertical splits a lot. With the "Default" color scheme and theme, moving my editor cursor in a way that changes the "width" of the "Col" or "Ln" number in the status bar changes the width of the split, and can cause the split to flicker.

### Steps to Reproduce
1. Open a vertical split with files of a decent length (with variable column widths)
1. Move your editor cursor between lines such that your line number goes from a single digit to two digits

### Expected results
For the width of my vertical split to not change

### Actual results
The width does change

### Platform Information

*Komodo Edit or IDE?* 
IDE

*Komodo Version?* 
X

*Operating System (and version)?* 
OS X El Capitan

### Additional Information

 -- eg. Error logs, screenshots, workarounds --
![Line 1](https://i.imgur.com/siIKt9c.png)

![Line 17](https://i.imgur.com/PW4N0oV.png)

The status bar was moved to the bottom in an attempt to fix this issue, with no change. It also occurs with the status bar in its default position.

**Comment by mitchell-as** [comment]
Thanks, I can reproduce this.

**Comment by Naatan** [comment]
Thanks @girvo, this is being tracked here: #1536
