### ISSUE TITLE
CSS padding on combined menu bar causes cutoff when recent list is full

### ISSUE THREAD

**Issue by cyberbit** [Komodo/KomodoEdit#1548]
### Short Summary
Customizing the menus to have more padding results in some item cutoff on the recent options list, which can be moved around by scrolling. See image below; the "About Komodo" item is cut off.

### Steps to Reproduce
1. Go to Tools > Color Scheme Editor.
2. Click New... and save the scheme as Default 2.
3. Select Interface.
4. Add the following CSS to the Color Scheme Editor:
 
 ```css
 menupopup label {
     padding: .4 rem !important;
 }
 ```
 
5. Click on a bunch of menu options to fill up the recent options list (8 items) in the combined menu bar (triple bar icon).
6. Open the combined menu.

### Expected results
Custom styles work well in the expected places.

### Actual results
Padding creates a scroll area on the combined menu.

### Platform Information

*Komodo Edit or IDE?* Edit
*Komodo Version?* 10.0.0
*Operating System (and version)?* Windows 7

### Additional Information
Perhaps this can be styled away as well?
![image](https://cloud.githubusercontent.com/assets/7350183/15395668/4993972e-1d9e-11e6-80ae-0004b94082ae.png)

**Comment by Naatan** [comment]
This is not a bug in Komodo, when you start to write custom CSS it's your own responsibility to make it work. In this case you probably have to increase the menupopup min-width or something along those lines.

**Comment by cyberbit** [comment]
That's fair. But how would I know the selectors to which I would apply the styles? Is there interface documentation anywhere? I've been looking and am struggling to find anything useful.

**Comment by Naatan** [comment]
See http://forum.komodoide.com/t/how-to-write-custom-css-for-elements-im-not-familiar-with/2719/2

I intend to write more thorough documentation on this subject, but have not yet gotten around to it.
