### ISSUE TITLE
Projects not showing up

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#1550]
### Short Summary
Made 2 new projects yesterday, but today I'm not seeing them.

### Platform Information
Windows 10 Komodo 10 Ide

### Additional Information
```java
[2016-05-19 19:29:25,963] [ERROR] project-xul: 
-- EXCEPTION START --
TypeError: project is null
+ stack
    ManagerClass.prototype.moveToProjectDir@chrome://komodo-places/content/places.js:3209:13
    onApplied/<@chrome://komodo/content/pref/project.xul:219:17
    openDialogWrap@chrome://komodo/content/komodo.js:616:19
    peFile_Properties@chrome://komodo/content/project/peFile.js:328:13
    viewManager.prototype.do_cmd_editPrefsCurrent@chrome://komodo/content/views.js:2344:5
    xtk.Controller.prototype.doCommand@chrome://xtk/content/controller.js:61:9
    command_doCommand@chrome://komodo/content/library/commands.js:239:1
    command_doCommandAsync/<@chrome://komodo/content/library/commands.js:196:13
-- EXCEPTION END --
```

**Comment by cgchoffman** [comment]
Are there other projects visible?  I assume you're talking about the projects widget in Places.  Could you give more context to that error?  What were you doing?

**Comment by Naatan** [comment]
Before trying anything else - could you reproduce the issue with addons/toolbox disabled? Help > Troubleshooting > Restart without Addons.

**Comment by babobski** [comment]
Projects are back again, opend a project. Restarted and the projects are back again
