### ISSUE TITLE
currentLine color does not work

### ISSUE THREAD

**Issue by vZ2JEZsZW** [Komodo/KomodoEdit#1551]
Setting and  applying currentLine color in scheme editor have no effect.
![screenshot - 05192016 - 10 36 33 pm](https://cloud.githubusercontent.com/assets/7002789/15407358/727fba78-1e1b-11e6-81fd-a0fe8c27db4e.png)

Komodo Edit, version 10.0.0, build 17209, platform linux-x86_64

**Comment by Naatan** [comment]
You're looking for the color above that one: "caretLineBack".

We have a bug open to make this easier to interpret.

**Comment by Defman21** [comment]
FYI @vZ2JEZsZW #1490
