### ISSUE TITLE
Debugger issue

### ISSUE THREAD

**Issue by oleksiybondar** [Komodo/KomodoEdit#1553]
### Short Summary

Python debugger stops in a places without break points when exception happened, if this is a feature than it should have some switch in preferences

### Steps to Reproduce

1.  create python script with some code which cause an exception
2.  ensure that there is no breakpoints
3.  run script

### Expected results

script execution should be completed without any breaks

### Actual results

script stops on a line where exception happened

### Platform Information

Komodo IDE 10
Mac OS X Yosemite
Python 2.7.10

### Additional Information

http://prntscr.com/b63vrm
http://prntscr.com/b63z5b

**Comment by mitchell-as** [comment]
This is by design. You should run without debugging if you have no breakpoints and do not want to break on exception.

**Comment by Naatan** [comment]
Or use the "Run code in-line" feature. 

http://docs.komodoide.com/Manual/Run-Code-In-line
