### ISSUE TITLE
upgrade window is scaled weirdly

### ISSUE THREAD

**Issue by dch** [Komodo/KomodoEdit#1554]
### Short Summary

The check for updates window occupies 1/3 of the screen. There is no draggable handle to resize or move it out of the way, but it can be closed.

### Steps to Reproduce

Check for updates

### Expected results

Anything but that.

### Actual results

See ![update window](https://i.imgur.com/OhII4Ac.png)

### Platform Information

Komodo IDE, version 10.0.0-alpha1, build 88973, platform macosx.
Built on Tue Apr 26 10:36:47 2016

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

close the window.

**Comment by Defman21** [comment]
Upgrade to the latest version, it's fixed.
