### ISSUE TITLE
word wrap in vertical split mode causes split to jitter

### ISSUE THREAD

**Issue by dch** [Komodo/KomodoEdit#1555]
### Short Summary

Using word wrap in vertical split mode causes extreme jitter of entire pane during normal working (editing or selecting text, moving lines, scrolling pane etc).

### Steps to Reproduce

- use default theme / profile
- open 2 files that have a few consecutive long lines ( > 80 characters) somewhere in the text that are long enough to "spill over" onto the side of the split view area if word wrap is not enabled
- use split mode to achieve 2 vertical columns like a newspaper
- ensure file 1 is open in left split and file 2 in right split
- enable word wrap in both
- scroll to middle of page where long line is
- click repeatedly in lines on either side

### Expected results

boring screen doesn't change sizes or flicker while editing

### Actual results

https://wintermute.skunkwerks.at/~dch/tmp/wtf.mov

- flicker appears showing the contents of the window *behind* komodo very briefly (this is weird but not serious)
- the long lines unwrap & re-wrap briefly in the left hand pane (bad)
- this causes the entire right hand pane to change dimensions (double-plus-bad)
- the dimensions change continually throughout the file

### Platform Information

Komodo IDE, version 10.0.0-alpha1, build 88973, platform macosx.
Built on Tue Apr 26 10:36:47 2016.

### interface settings

- issue still occurs when using Default Theme
- l33tgram interface color scheme with 15 point size fira code font https://github.com/tonsky/FiraCode
- native window borders
- disabled options for Enable Classic Mode & Use Classic Toolbar Layout

### Additional Information

This occured in the 10.x alphas too but I was too busy to track down what was actually happening.  It's so annoying I switched to vim for a few days!

This seems to occur when any event that requires redrawing the right pane happens - e.g. scrolling from bottom to top of a file, editing text "near" the wrapped area, or selecting/dragging a block of text, for example.  See video at https://wintermute.skunkwerks.at/~dch/tmp/wtf.mov let me know when I can delete this.

**Comment by Defman21** [comment]
>l33tgram interface color scheme

It only has the editor colors for now, I'll update my stuff for Komodo X soon! :)

**Comment by mitchell-as** [comment]
I'm pretty sure this is a duplicate of #1547, which was fixed yesterday. Do you agree @Naatan?

**Comment by Naatan** [comment]
@mitchell-as that's what I was thinking too.

@dch can you check if the ticket @mitchell-as linked to overlaps with your issue? The word wrap could just be correlation.

**Comment by dch** [comment]
A.W.E.S.O.M.E. this looks like it's fixed in the nightly build I just grabbed.

```
Komodo IDE, version 10.0.1, build 89178, platform macosx.
Built on Fri May 20 01:57:51 2016.
```
