### ISSUE TITLE
Project does not open when restoring workspace

### ISSUE THREAD

**Issue by cyberbit** [Komodo/KomodoEdit#1560]
### Short Summary
If a project was open when Komodo is closed with "Restore workspace" enabled, the files are restored, but the project is not. I just checked 9.3 and it reopens the files and the project.

### Steps to Reproduce
1. Ensure that **Restore last workspace** is selected (**Preferences > Workspace > Workspace > When starting Komodo**).
1. Open a project.
2. Open some files in that project.
3. Restart Komodo.

### Expected results
The project should load with the workspace.

### Actual results
The project does not load with the workspace. This causes some problems when a developer thinks he/she is in a project (Find in Files does not have an option for searching the project, project-specific tools are hidden, Code Intel gets confused, etc.).

### Platform Information

*Komodo Edit or IDE?* Edit
*Komodo Version?* 10.0.0
*Operating System (and version)?* Windows 7

### Additional Information
This is the best way I could find to determine if the project is open or not. If Close Project is an available option, then the project is open. Otherwise it is closed.
![image](https://cloud.githubusercontent.com/assets/7350183/15433636/c3a3dec2-1e78-11e6-86c8-cd834239d7b6.png)

**Comment by cyberbit** [comment]
Interestingly, this is happening for me on Windows 7, but not Windows 10.

**Comment by cgchoffman** [comment]
Are you seeing the same issue if you use the Workspace Save/Open feature?  Menu *File > Save Workspace* and *File > Open > Workspace*.

**Comment by hobbsd** [comment]
This happens for me on Windows 10, at least when I have multiple projects open. For example, just now I had 3 projects open in separate windows; closed them all via `Alt-f4`; open Komodo, and it opens 3 windows, two of which have no project open (although Places is rooted at them) and one with project open.

**Comment by hobbsd** [comment]
I don't have a menu item _File > Save Workspace_.

**Comment by Defman21** [comment]
Seems like it's an IDE only feature.

**Comment by cgchoffman** [comment]
> Seems like it's an IDE only feature.

Confirmed, IDE only.  Sorry for the teaser.

**Comment by hobbsd** [comment]
I just noticed that if I close KE with the window's `x` button the open project is not restored on restarting, but if I close it with `Alt-f4` the project is restored. This is on Windows 10 with just one project window open.

**Comment by cyberbit** [comment]
Just tested @hobbsd's workaround on Windows 7, and it worked for me.

**Comment by cgchoffman** [comment]
I"m fairly certain that this will be resolved with this fix: https://github.com/Komodo/KomodoEdit/commit/0dc17085835b67a0273660a05fbffdd088513062

Previously the step that saves window state was skipped.  That's all wrapped up now.  If you care to try it will be available in a [nightly](http://downloads.activestate.com/Komodo/nightly/) soon.  I just pushed the fix today so the nightly from August 11 will NOT have the fix.  Any nightly after that will have the fix.

I'm going to close this as it seems to work for me.  If you test and find it's not working for you make sure you post the build number your using with your reply.
