### ISSUE TITLE
Code tooltips sometimes disappear quickly

### ISSUE THREAD

**Issue by cyberbit** [Komodo/KomodoEdit#1561]
### Short Summary
Tooltips that alert the user of code problems, such as those created by syntax checking, sometimes disappear very quickly when hovering a line of code.

### Steps to Reproduce
1. Open Komodo in Safe Mode.
2. Load the sample project (Project > Sample Project).
3. Open `javascript_sample.js`. Wait for the syntax checker to highlight some lines.
4. Hover over each line of code.

### Expected results
For each item, an appropriate tooltip should appear for `x` seconds.

### Actual results
A tooltip only appears for line 19. Lines 5 and 12 just blink the tooltip once every ~500ms on hover.

### Platform Information

*Komodo Edit or IDE?* Edit
*Komodo Version?* 10.0.0
*Operating System (and version)?* Windows 7

**Comment by Naatan** [comment]
Not seeing this on Linux. @cgchoffman you seeing this?

**Comment by babobski** [comment]
I think it's the same as the [issue](https://github.com/Komodo/KomodoEdit/issues/1477) I'm having with the double warnings on one line.

**Comment by Naatan** [comment]
@cyberbit does the issue happen on linting tooltips where there is only on warning/error on the line?

**Comment by cyberbit** [comment]
@Naatan Never noticed it before, but no!

![image](https://cloud.githubusercontent.com/assets/7350183/15438284/1177b700-1e91-11e6-8447-ca15db7705e8.png)

Line 1 has six linting tooltips, line 8 has two, and both blink. Line 6 has one and works. @babobski is right, this is basically a duplicate of #1477.

**Comment by Naatan** [comment]
Alright perfect, thanks for helping us narrow it down! :)
