### ISSUE TITLE
Calling "view log file" while having error log open removes title bar of window

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#1562]
### Short Summary

Just clicked on "view log file" while the log file was hidden behind the editor.
When i switched back the title bar has disappeared form the window.
Tried it again and got the same result.
### Steps to Reproduce

Click on **Help > troubleshooting > view log file** while you have the log file open.
### Expected results

Would be nice, if when the window is open, the window gets focus so it will appear in front of the editor.
### Actual results

![2016-05-20 18_06_35](https://cloud.githubusercontent.com/assets/3530262/15434455/36481ac2-1eb7-11e6-88cd-199a7d5749bb.png)
### Additional Information

As work around you can close the window trough the task-bar

**Comment by Naatan** [comment]
And the reward for weirdest bug goes to ..

**Comment by babobski** [comment]
Ah thanks :wink:

**Comment by Defman21** [comment]
I'm not able to reproduce it anymore on Ubuntu 16.04 with Unity, Komodo IDE 10.1 beta.
