### ISSUE TITLE
Empty code browser after upgrade to 10.0

### ISSUE THREAD

**Issue by cdcmicro** [Komodo/KomodoEdit#1565]
### Short Summary

After upgrading from IDE 9.3 to 10.0, the files that were open in my 9.3 workspace are open in the new 10.0 workspace, but the code browser for those files is empty.

### Steps to Reproduce

1. Close IDE 9.3 with some files open in the workspace
2. Install IDE 10.0
3. Open IDE 10.0, follow the initial config wizard (defaults)
4. IDE 10.0 opens with the files from my previous workspace

### Expected results

I expect to see the code browser populated for the open files (JS, Perl, SCSS)

### Actual results

Code browser is empty.

Close/restart IDE 10.0 doesn't help.

I had to close and reopen the  files in the workspace before the code browser populates

### Platform Information

Komodo IDE, version 10.0.0, build 89159, platform win32-x86.
Built on Wed May 11 15:04:59 2016.

*Operating System (and version)?* Win7 Pro x64

### Additional Information

With a workaround, it's hardly a showstopper.  But awkward anyway

**Comment by mitchell-as** [comment]
The code intelligence database is reset during a major upgrade, so it takes some time to re-scan files. This is normal. The fact that the browser eventually populates indicates everything is in working order.

**Comment by cdcmicro** [comment]
OK, well, I'm not seeing it "eventually" populate.  I remembered about the CI re-scan, so I left IDE 10 open over night and restarted it.  The code browser didn't populate until after I explicitly closed and re-opened each of the files in the workspace.

**Comment by mitchell-as** [comment]
I see, sorry for the misunderstanding then.
