### ISSUE TITLE
Formatters are all missing; cannot create new ones

### ISSUE THREAD

**Issue by djacopille** [Komodo/KomodoEdit#1566]
### Short Summary
Formatters are missing in new 10.0 version.  New ones cannot be added.  
Many preferences did copy in 9.x when installing 10.0.  Not formatters.

### Steps to Reproduce
OS X 10.11.5, Komodo IDE 10.0, click + to add formatter in prefs.
Fill out panel exactly like Komodo IDE 9.x (which works great on same machine).  Don't think different settings would work any better.  See screenshot below for actual settings.
Click OK.

### Expected results
New formatter shows up in the list of formatters once form is filled out and 'ok' is clicked.

### Actual results
Your new formatter...is not in the list.  No messages.

### Platform Information
*Komodo Edit or IDE?*  IDE
*Komodo Version?* 10.0
*Operating System (and version)?* OS X 10.11.5

### Additional Information
Screenshot shows 10.0 on left, and 9.x on right.  Once you click OK the list of formatters above the 10.0 formatter dialog remains equally as empty as it is in this screen shot.

 -- eg. Error logs, screenshots, workarounds --
![screen shot 2016-05-20 at 2 29 15 pm](https://cloud.githubusercontent.com/assets/13801692/15438449/370be708-1e9a-11e6-8264-e827a00d39a4.png)

Tried restarting and entering everything a dozen times - no success.

**Comment by Naatan** [comment]
Do the instructions here resolve your issue? http://forum.komodoide.com/t/how-to-add-a-formatter-in-komodo-10/2724/4?u=nathanr

**Comment by djacopille** [comment]
Yes, that works.

Since it’s happening to multiple people, and the formatters do not behave as if corrupt in 9.x, there may still be a bug in how 10.0 is importing this data.

Thank you,
Dave

**Comment by Naatan** [comment]
Indeed. This has already been fixed on our master branch, so Komodo 10.0.1 should fully address this issue.
