### ISSUE TITLE
Split view window resizes during selections

### ISSUE THREAD

**Issue by djacopille** [Komodo/KomodoEdit#1567]
### Short Summary
During left-right split views selecting text causes the left window to widen, right window to narrow.  Dragging to select multiple lines causes window to resize rapidly in a jittery way.
Issue is new to 10.0 - did not occur in 9.x.

### Steps to Reproduce
Open any document with text that can be selected.
Split view and rotate to a left-right view.
Select any text in left panel, or drag and select text.

### Expected results
Split view panes would remain same size.

### Actual results
When text is selected information about selected added at top of code pane, e.g.:
sel: 54 ch, 1 ln

Fitting this text seems to cause the left pane to enlarge, even though there's about 10 centimeters of empty space to the left of the Ln: xxx Sel: xxx text.

### Platform Information
*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.0
*Operating System (and version)?*  OS X 10.11.5

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by Naatan** [comment]
Fairly certain this is https://github.com/Komodo/KomodoEdit/issues/1536

The nightly should have this fixed: 

http://downloads.activestate.com/Komodo/nightly/komodoide/latest/

**Comment by djacopille** [comment]
Thanks – obviously not a critical issue.  I’ll wait for the public release of 10.0.1 and try again.
