### ISSUE TITLE
It takes longer than usual to apply color schemes

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#157]
It feels like it takes about 15 seconds for a color scheme to apply, whereas it used to take about 5 seconds.

Assigning to Todd in the hopes he has some clue about this. 

@toddw-as if you have no clue and this is a potential timesink please reassign to me.

**Comment by toddw-as** [comment]
Do you have a lot of files opened? If so, then the color-scheme apply time will be magnified at startup (as it gets called once per view).

**Comment by cgchoffman** [comment]
I notice this on Windows when I have started Komodo with -v.  Not sure what platform you were on @Naatan.  I don't have an issue when I don't start Komodo with -v

**Comment by Naatan** [comment]
That was it, seems its updating every buffer when the color scheme is changed. Not a regression, just me finding an edge case.

@toddw-as does it make sense to leave this open and aim to have scintilla updated for non-active buffers when they become active?

**Comment by toddw-as** [comment]
@Naatan The optimization of lazily loading buffers (or at least lazily styling them) was something I was interested in (to speed up Komodo startup), but I never got around to doing it - it's also a invasive change.

I don't think it's worthwhile keeping a bug open for it - if it becomes important enough then someone will do it :P

**Comment by Defman21** [comment]
This one has been fixed. Komodo X got a lot of optimization commits :P

**Comment by cgchoffman** [comment]
Looks like @toddw-as  had a good point.
