### ISSUE TITLE
Tcl code analyzer fails

### ISSUE THREAD

**Issue by sgeard** [Komodo/KomodoEdit#1570]
### Short Summary
Outlining and code analysis are incorrect for some procedures

### Steps to Reproduce
Open the attached file, you'll see that moveToPosition has collapsed the remainder of the file and the code analyzer has the second procedure 'f' in the wrong place.

![bug](https://cloud.githubusercontent.com/assets/13196616/15444006/7f8fdac6-1ee4-11e6-8cb8-69ca56eba89c.png)

[bug.tcl.gz](https://github.com/Komodo/KomodoEdit/files/275541/bug.tcl.gz)

### Expected results
moveToPosition should only collapse to its end and 'f' should be at an equal level within the namespace.

### Actual results
see attached png

### Platform Information

*Komodo IDE
*Komodo Version 10.0.0
Linux-x64

**Comment by mitchell-as** [comment]
Thanks for the report. It looks like you found an edge case in our Tcl lexer.

**Comment by sgeard** [comment]
If you unfold the proc moveToPosition you'll see that the # characters in the regexps cause the highlighting to go wrong. Is that part of the same problem?

**Comment by mitchell-as** [comment]
Yes, the two are likely linked.

**Comment by mitchell-as** [comment]
Note to self: the '#' is also responsible for putting `f` within the current function. Removing `#` puts `f` on its own.

**Comment by mitchell-as** [comment]
By not treating the `#` characters in the regexps as comment delimiters, both the folding issue and the incorrectly nested `f` have been fixed.
