### ISSUE TITLE
IDE X, Manage Packages has empty list

### ISSUE THREAD

**Issue by landy2005** [Komodo/KomodoEdit#1572]
### Short Summary

In toolbox "Anything" not displayed any installed addon/sheme/package

### Steps to Reproduce

Click on box "Go to Anything" > "Manage Packages" > 
And in this list any item empty (List Installed, List Outdated, Uninstall Packages)

But in "Legacy Addons" list I see many custom installed addons/packages.

### Platform Information

OS X El Capitan 10.11.5
Komodo IDE, version 10.0.0, build 89159, platform macosx.
Built on Wed May 11 15:42:24 2016.

**Comment by Naatan** [comment]
The legacy addons dialog shows system addons (ie. addons that Komodo comes packaged with and explicitly depends on). The new packages interface does not show these.
