### ISSUE TITLE
Go to Definition ignores block scope

### ISSUE THREAD

**Issue by shawnlaffan** [Komodo/KomodoEdit#1575]
### Short Summary

The Go to definition can jump to definitions in different block scopes.  

### Steps to Reproduce

Given the code below, right click on any of the $listref , $x or $y variables and choose Go to definition.

```perl
use strict;
use warnings;

{
    my $listref = [1..5];
    my $y;
    foreach my $x (@{$listref}) {
        $y++;
    }
}
{
    my $listref = [1..5];
    my $y;
    foreach my $x (@{$listref}) {
        $y++;
    }
}
```

### Expected results

The cursor should go to the definition within the block.

### Actual results

Regardless of which scope the selected variable is in, the cursor is moved to the definition in the first block.

### Platform Information

*Komodo Edit or IDE?*   IDE
*Komodo Version?*    10.0 and 9.3.2
*Operating System (and version)?*   Windows 10

**Comment by shawnlaffan** [comment]
Same applies for python.

```python
if (1):
    x = range(1, 5)
    y = 4
    for i in x:
        y = y+1
    print y
if (2):
    x = range (1, 5)
    y = 4
    for i in x:
        y = y+1
    print y
```

**Comment by mitchell-as** [comment]
Well, to be fair in Python your variables are scoped to the current function (or main). They are not lexically scoped as you might expect.

I'll need to look into your Perl example because I don't know much Perl.

**Comment by mitchell-as** [comment]
Our code intelligence system does not appear to handle anonymous (unnamed) scopes like you described. I cannot think of any case where this would be useful. I've slotted this ticket for a future release, but it's possible I'll choose to not support it unless there's a useful use case.

**Comment by shawnlaffan** [comment]
Thanks for that, and the tip about python.  

The useful use case is the principle of least surprise.  In my case I was refactoring a long sub, and started changing the wrong section after using go to definition.  These were within distinct (not nested) if-blocks, not anonymous blocks (modified example below).

It's also an issue that using go to definition on a variable declaration (e.g. `my $x`) goes to the first definition.

Rename variable is also affected, but renaming all cases of a variable will have less of an effect on code function.

```perl
my $flag = 1;

if ($flag) {
    my $listref = [1..5];
    my $y;
    foreach my $x (@{$listref}) {
        $y++;
    }
}
else {
    my $listref = [1..5];
    my $y;
    foreach my $x (@{$listref}) {
        $y++;
    }
}
```

**Comment by Naatan** [comment]
@mitchell-as are there any other advantages to implementing this? And how time consuming would this be?

I'm tempted to mark this as a limitation if it's such a limited use case and costs a lot of effort to implement

**Comment by mitchell-as** [comment]
I cannot think of any advantages other than what was already mentioned. I don't know how time consuming this would be, but I suspect it would not be trivial, as our "scopes" are categorized (by class name, function name, namespace name, etc.). Creating anonymous scopes is another level of abstraction I think. I would guess that it's also regression-prone, but that's just off the top of my head.

**Comment by Naatan** [comment]
I tested it on JS, which to my knowledge is the only language where anonymous functions are heavily relied upon. Luckily for JS we seem to properly be handling these.

As such I'm going to just mark this as a limitation, the limited use case does not justify the substantial work it would take to implement this.

Not to say we will never support this, but for us to support this it would take a larger codeintel rewrite that includes multiple facets of codeintel.

Please respond if you disagree with this decision.

**Comment by shawnlaffan** [comment]
I'm OK with it being marked as a limitation in the docs (maybe also in a menu tooltip).  Emulating perl's block scopes in a different language would have a high degree of difficulty.
