### ISSUE TITLE
New Komodo notifications are buggy

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#1577]
### Short Summary
The notifications using the the notify sdk, are not working very well.
The notifications are first showing blank and when the almost go away you have about half a second to read the message.

### Platform Information
Komodo 10 IDE

### Additional Information
This is how the notifications looks like most of the time, just before this is disappearing, text is blinking in.
![2016-05-22 09_39_22](https://cloud.githubusercontent.com/assets/3530262/15452964/89685c6c-2001-11e6-9c90-10536cd41eb1.png)

**Comment by Naatan** [comment]
Can you reproduce this in safe-mode?

**Comment by babobski** [comment]
Just tested it in safe mode, without importing any settings.
The database preloading is showing because it takes a while:
![2016-05-26 18_31_28](https://cloud.githubusercontent.com/assets/3530262/15582322/aa800be4-2370-11e6-97c5-d23b529d6ceb.png)
Only with normal notifications, it first get's blank for a while:
![2016-05-26 18_33_28](https://cloud.githubusercontent.com/assets/3530262/15583341/a6ef00fc-2375-11e6-853a-d38c00188bde.png)


Made a [screen capture](http://youtu.be/bysbTckbHUs?hd=1) so you can see what's going on.

**Comment by babobski** [comment]
@Naatan found out what is causing this.
At the notification settings I have those two options.
![2016-05-27 07_50_07](https://cloud.githubusercontent.com/assets/3530262/15598962/b8df5626-23df-11e6-8cf1-81366af47402.png)
If both are enabled, this effect occurs on windows ( at home and at work ).
If I check none, or one of them the behavior is normal, just can't use them both.

**Comment by Naatan** [comment]
Very odd, I have not seen this on Windows. @cgchoffman are you getting this?

**Comment by cgchoffman** [comment]
Yep, reproduced on Windows.  Confirmed that disabling one of the options mentioned by @babobski fixes the issue.

**Comment by cgchoffman** [comment]
I put it on 10.0.1 but that's based on zero knowledge of what will be involved in fixing this.  @Naatan you'll be the better judge to milestone this.
