### ISSUE TITLE
Find dialog should focus "Find what" textbox

### ISSUE THREAD

**Issue by srgloureiro** [Komodo/KomodoEdit#158]
Minor annoyance.
If the Find Dialog is closed and the user explicitly opens it, focus should go immediately to the "Find What" textbox. 
Sometimes I do Ctrl+Shift+F and begin to type immediately after. The text I typed is lost due to the "Find what" lack of focus.

**Comment by Naatan** [comment]
Thanks for reporting! This has been fixed in the nightly, see #79.
