### ISSUE TITLE
programm shows not all content in xml-files

### ISSUE THREAD

**Issue by debe0813** [Komodo/KomodoEdit#1581]
### Short Summary
If I scroll to the right, until scrolling stops, programm shows me not the whole line. It just fades out. But I can not scroll anymore further. However, I can go with the right-arrow, and reveal the rest. 
   
![bildschirmfoto 2016-05-22 um 11 01 03](https://cloud.githubusercontent.com/assets/19514133/15453195/b70c58c0-200c-11e6-8204-261bbdffbf37.png)

### Steps to Reproduce
1.Open File item.xml (unfortunatly, I can not upload it here.
2.Scrolling to the right

### Expected results
To see the whole content of the xml-file.

### Actual results
Content is after some time of scrolling hidden. You can not scroll anymore further, to reveal the rest.

### Platform Information

*Komodo Edit: v.9.3.3 
*Operating System (and version)?* Mac OSX 10.11.4. 

### Additional Information

 -- eg. Error logs, screenshots, workarounds --
I copied the file, into a new file. but problem continues.
//**Here the whole xml-File:**//

```
<?xml` version="1.0" encoding="utf-8"?>
<form>
    <config>
        <fields name="params">
            <fieldset name="splitmenu" label="Splitmenu Menu Options" addfieldpath="/templates/gantry/fields">
                <field name="splitmenu_item_subtext" type="text" size="30" default="" label="Subtext Line" description="You can put a second line here"/>
                <field name="splitmenu_customimage" type="imagelist" default="" label="Menu Image" description="The default location for images listed here is the template/images/icons/ folder.  Modify and update them as needed" directory="/templates/gantry/images/icons" exclude="" stripext=""/>
                <field name="splitmenu_customicon" type="iconlist" default="" label="Menu Icon" description="Choose an icon available via Font Awesome - http://fortawesome.github.com/Font-Awesome/" />
                <field name="splitmenu_customclass" type="text" size="30" label="Custom CSS Class" description="A Custom CSS class that can be assigned to this item"/>
            </fieldset>
        </fields>
    </config>
</form>
```

**Comment by babobski** [comment]
@debe0813 I tried to reproduce but I'm unable to. Also I'm only seeing you're xml tag.
Maybe you can try and put you're code inside a [code block](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting) (then the tags will be automatically escaped)

As work around you can enable word wrap trough the menu **View > Word Wrap**

**Comment by debe0813** [comment]
@babobski Thanks for your query and support. I got it (the code problem fixed)!

**Comment by babobski** [comment]
@debe0813 got it reproduced, when i paste you're code in new xml file i can't scroll further than this:

![2016-05-22 14_30_18](https://cloud.githubusercontent.com/assets/3530262/15453947/dbd23694-2029-11e6-8f1a-d4f35476bccd.png)

I know there are some setting for scrolling, under **preferences > editor**
![2016-05-22 14_32_10](https://cloud.githubusercontent.com/assets/3530262/15453954/1f962458-202a-11e6-89aa-47072d1afc4f.png)

If you check the setting **Automatically adjust the horizontal scrollbar width** and reboot komodo you can now scroll to the end of the line without using word wrap :)

![2016-05-22 14_35_52](https://cloud.githubusercontent.com/assets/3530262/15453966/930704a2-202a-11e6-83a2-a5792ebf9ba6.png)

**Comment by debe0813** [comment]
Thanks for fast reply! I did your advice. But its not working on my Mac. You can see below my configuration. Of course, I rebooted Komodo. But as you can see on the right, text was cut off. 
![bildschirmfoto 2016-05-22 um 14 54 47](https://cloud.githubusercontent.com/assets/19514133/15454051/2fcff134-202d-11e6-9fbe-ea97dbafa01d.png)

**Comment by babobski** [comment]
@debe0813 this option only allows you to scroll right to the end of you're code.
If you want word wrap enabled by default you should be going to the **preferences > editor > smart editing**.
Here you got the option **wrap long lines by**, if you select here word or character you're long lines will be wrapped automatically.
![2016-05-22 15_26_57](https://cloud.githubusercontent.com/assets/3530262/15454199/ad39c1a0-2031-11e6-93d1-a87f0512e104.png)

**Comment by debe0813** [comment]
I tried your, as you have shown, but its not working. Used Word, used Charakter, but it is not changing anything. 
![bildschirmfoto 2016-05-22 um 17 08 07](https://cloud.githubusercontent.com/assets/19514133/15454674/f619a698-203f-11e6-922f-055b2ef80060.png)

**Comment by Defman21** [comment]
Does it work for new files?

**Comment by debe0813** [comment]
yeah! on new files, it works. Than, I have only my screen. After that, the program breaks the line, and shows the rest in a new line. But in existing files, it just disappears.

**Comment by Defman21** [comment]
You could try to re-check View - Word Wrap for existing files or re-open them.

**Comment by debe0813** [comment]
jap, it works! However, is it demanding, to say, its only half solution? I mean, it seems tob be a buck or? Hope this problem will be fixed, so you can work as it is used to be.

**Comment by Defman21** [comment]
This was a workaround, not a solution or half of solution. I don't know is it a bug or not, devs would say more, but it's Sunday and they are on their weekend :)

**Comment by debe0813** [comment]
but this community is exaggerating. Great, that there are people, who are eager to help! Thanks to @babobski & @Defman21

**Comment by mitchell-as** [comment]
Hi, word wrap is a per-file preference, not a "global" one. You'll have to enable word wrap for individual files.

**Comment by mitchell-as** [comment]
Oops, sorry I missp

**Comment by mitchell-as** [comment]
So it sounds like this is no longer an issue of showing the content of a long XML line (word wrap has "fixed" that), but rather that checking "word wrap" only applies to the current and new files, not previously opened ones. Is that right?

**Comment by debe0813** [comment]
somethins went wrong on github today. I received your post via email, but here on the site, your post was not visible for approximately. 2 hours. So, i answered via mail. but now, it appeared, so for all visitors my answer again: 

Yeah, on the one side. „word wrap“ fixed it as a workaround. But if I am honest, its not a quite satisfying solution.It has to be checked every time on the files, which have this problem. Hope, it is possible,in the future, to address this issue. So, you can work as usual one codeline - one line in editor.

**Comment by Defman21** [comment]
>somethins went wrong on github today.

They were experiencing some issues with their databases.

**Comment by debe0813** [comment]
@Defman21 Thank you for your notification. Thought, My Computer was crazy.^^

**Comment by mitchell-as** [comment]
For performance reasons, the editor does not calculate the exact width of the horizontal scrollbar needed to show the entire line. When you reach the "non-real end of line", you can press the `End` key (or Cmd+Right on OSX?) to jump to the end of the line. At that point the editor will recalculate the length and the horizontal scrollbar will work on that line again.

**Comment by tonyattwood** [comment]
Hi,

Have  you heard the latest news? Not yet? You have to read it then, because it's  just  woooow!  Here is the info <http://expert.markpalk.com/e4zniibl>


Best regards, tony.attwood@ntlworld.com
