### ISSUE TITLE
Per-file indentation is broken again?

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1582]
### Short Summary

`require('ko/editor').scimoz().indent` gives me 4 and my indent is always 4 even if my per-language Ruby indent is 2.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.0.1 build 89178
*Operating System (and version)?* eOS 0.4

**Comment by Defman21** [comment]
```
  <long id="indentWidth">4</long>
  <long id="languages/Ruby/tabWidth">2</long>
  <long id="tabWidth">4</long>
```

This is what I have in my prefs.xml.

**Comment by Defman21** [comment]
Okay I've fixed it by re-setting Per-language setting for Ruby, so now my prefs looks like this:
```
  <long id="indentWidth">4</long>
  <long id="languages/Ruby/indentWidth">2</long>
  <long id="languages/Ruby/tabWidth">2</long>
  <long id="tabWidth">4</long>
```

**Comment by Naatan** [comment]
Fixing the issue yourself doesn't make it "not an issue". Can you reproduce the issue?

**Comment by mitchell-as** [comment]
As far as I could tell the issue was the lack of a Ruby-specific "indentWidth" setting of 2. "tabWidth" for Ruby was 2, but "indentWidth" for Ruby was not set. I assume this configuration is possible to obtain manually.

**Comment by Defman21** [comment]
Mitchell is right. If I'll reproduce it again I notice you
