### ISSUE TITLE
Width of tab characters not respected

### ISSUE THREAD

**Issue by efrecon** [Komodo/KomodoEdit#1584]
### Short Summary

Specifying 4 as the width of indentation and 8 as the width for tab characters, does not show tabs that are 8 chars wide.

### Steps to Reproduce

Open any file that has this type of indentation. Take this one as an example:

https://bitbucket.org/enbygg3/biot/raw/62a884dc7d917e77a4bd20cb6d6c2adb63a5c4d0/lib/biot/dst/tcp.tcl

### Expected results

Tabs characters should be shown 8 chars wide on screen

### Actual results

They are 4 chars wide

### Platform Information

Komodo Edit, version 10.0.0, build 17209, platform win32-x86

### Additional Information

![2016-05-23 10_28_55-](https://cloud.githubusercontent.com/assets/9443924/15464729/3c24dd42-20d1-11e6-970a-bb86820e5373.png)

I moved from emacs a while ago. Most of my files include tabs characters for representing 8 chars and have an indentation of 4 chars. This was working smoothly in the previous version of Komodo Edit, but the new version seems to have something broken. Reopening the file after changing the preferences doesn't change anything either.

**Comment by mitchell-as** [comment]
This should have been fixed in the latest 10.0.1 nightly build. Please give it a try. http://downloads.activestate.com/Komodo/nightly/komodoide/latest-master/
