### ISSUE TITLE
IDE X Debugger tooltip of Perl variable flickers very fast

### ISSUE THREAD

**Issue by GwenDragon** [Komodo/KomodoEdit#1585]
### Short Summary
With debugging of Perl in code window the Tooltip of a array or hash variable flickers very fast and does not show content.

### Steps to Reproduce

1. Create Perl code
```
my $inc = @INC;
my $t = { 99 => 'A' };
print $inc;
```    
2. Set a breakpoint a last line
3. Run program in debugger
4. Program stops at breakpoint of line 3
5. Hover mouse at variable $inc in code window
6. Tooltip of $inc shows the integer number of elements in @INC 
7. Hover mouse at variable @INC in code window
8. Tooltip flickers very fast (not visible to see!) and does not show content

### Expected results
Tooltip shows content of @INC array

### Actual results
Tooltip flickers very fast and does not show content of @INC 

### Platform Information

*Komodo Edit or IDE?* Komodo IDE 
*Komodo Version?* Komodo IDE, version 10.0.0, build 89159, platform win32-x86.
Built on Wed May 11 15:04:59 2016.
*Operating System (and version)?* Windows 10x64 Pro Version 1511 Build 10586.318

### Additional Information
In old Komodo 9 the tooltips showed the content of the used variables

**Comment by mitchell-as** [comment]
@cgchoffman Can you reproduce this? I cannot reproduce on Linux, but I noticed the popup style is different in Komodo X vs. Komodo 9. Maybe @Naatan has an idea why there might be popup flickering in X.

**Comment by cdcmicro** [comment]
I noticed this issue on my 10.0 installation (Win7) with javascript code.  Hover over a line with a warning, and the tooltip flashes and disappears very quickly.

**Comment by Defman21** [comment]
I've seen this somewhere in issues, gonna find it.

**Comment by Defman21** [comment]
https://github.com/Komodo/KomodoEdit/issues/1477 this?

**Comment by Naatan** [comment]
Yeah this is the issue @Defman21 referred to. Thank you for reporting!

**Comment by GwenDragon** [comment]
Fixed in Komodo IDE 10.0.1  :)
