### ISSUE TITLE
Missing icon in comand output tab

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#1586]
Komodo 9:
![2016-05-23 11_47_02-](https://cloud.githubusercontent.com/assets/3530262/15466928/30e6b486-20dc-11e6-8154-1dd1ed57da7c.jpg)

and in komodo 10 the icon is missing:
![2016-05-23 11_48_30-](https://cloud.githubusercontent.com/assets/3530262/15466960/4df4bda2-20dc-11e6-92ce-9c4eb1d9a9d8.jpg)

The icon opens the same pop-up as you whould use the menu **Tools > Run command**

**Comment by mitchell-as** [comment]
@Naatan we should probably add that bottom button again in case pressing 'Enter' isn't so intuitive for running a command.

**Comment by Naatan** [comment]
The button is still there, but it seems we did not assign it an icon.
