### ISSUE TITLE
rx toolkit: Can't locate JSON.pm

### ISSUE THREAD

**Issue by neurobashing** [Komodo/KomodoEdit#1588]
### Short Summary
'There is an error in your regular expression: Can't locate JSON.pm in @INC (you may need to install the JSON module) when attempting to create a Perl regex.

### Steps to Reproduce
1. Open regex toolkit
2. switch regex type to Perl
3. Enter regex

### Expected results
A match (or a failed match)

### Actual results
The package warning, above.

### Platform Information

Komodo IDE, version 10.0.1, build 89178, platform macosx.
Built on Fri May 20 01:57:51 2016.

### Additional Information

![screen shot 2016-05-23 at 9 40 36 am](https://cloud.githubusercontent.com/assets/59380/15472683/6de97678-20ca-11e6-9b27-88a50a046441.png)
Log:

[2016-05-23 09:40:33,256] [ERROR] koRxx: Can't locate JSON.pm in @INC (you may need to install the JSON module) (@INC contains: /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /Applications/Komodo IDE 10.app/Contents/SharedSupport/rxx/rxx_perl.pl line 10.
BEGIN failed--compilation aborted at /Applications/Komodo IDE 10.app/Contents/SharedSupport/rxx/rxx_perl.pl line 10.

[2016-05-23 09:40:33,559] [ERROR] koRxx: Can't locate JSON.pm in @INC (you may need to install the JSON module) (@INC contains: /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /Applications/Komodo IDE 10.app/Contents/SharedSupport/rxx/rxx_perl.pl line 10.
BEGIN failed--compilation aborted at /Applications/Komodo IDE 10.app/Contents/SharedSupport/rxx/rxx_perl.pl line 10.

[2016-05-23 09:40:51,026] [ERROR] koCodeIntel:     INFO: eval 'count' at get_epic_issues.pl#51  <Trigger 'perl-defn-defn' at 979 (explicit)>
    INFO: start scope is (<blob 'get_epic_issues'>, [])
    DEBUG: is 'count' from <from Env import JIRA_USER>? no
    DEBUG: is 'count' from <from Env import JIRA_PASS>? no
    DEBUG: is 'count' from <from JIRA::REST import *>? no
    DEBUG: is 'count' from <from Getopt::Long import *>? no
    DEBUG: is 'count' from <from Data::Dumper import *>? no
    INFO: is 'count' accessible on (<blob 'get_epic_issues'>, [])? no
    INFO: is 'count' accessible on (<blob '*'>, [])? no
    ERROR: evaluating 'count' at get_epic_issues.pl#51: could not resolve 'count'

**Comment by Defman21** [comment]
You should install JSON module for Perl.

**Comment by neurobashing** [comment]
As it is apparently a dependency for the rx toolkit, should it not be bundled?

**Comment by Defman21** [comment]
notice me github

**Comment by Defman21** [comment]
Well, I dunno. I don't use Perl so I don't see any reasons to bundle it with default installation imo. But that's my opinion :)

**Comment by mitchell-as** [comment]
I would think that it should be bundled, but not even Komodo 7 bundles it. I'm thinking this is by design. Is it not trivial to follow the prompt and install JSON?

**Comment by neurobashing** [comment]
At least in my current testing, it doesn't recognize the "lib::local" method of using CPAN. Note that from the shell my @INC is:
```
 λ ~ : perl
print @INC;
/Users/greggthomason/perl5/lib/perl5/5.18.2/darwin-thread-multi-2level
/Users/greggthomason/perl5/lib/perl5/5.18.2
/Users/greggthomason/perl5/lib/perl5/darwin-thread-multi-2level
/Users/greggthomason/perl5/lib/perl5
/Library/Perl/5.18/darwin-thread-multi-2level
/Library/Perl/5.18
/Network/Library/Perl/5.18/darwin-thread-multi-2level
/Network/Library/Perl/5.18
/Library/Perl/Updates/5.18.2
/System/Library/Perl/5.18/darwin-thread-multi-2level
/System/Library/Perl/5.18
/System/Library/Perl/Extras/5.18/darwin-thread-multi-2level
/System/Library/Perl/Extras/5.18.
```
*and* I have my local::lib config in Preferences->Languages->Perl->Additional Import Directories
![screen shot 2016-05-23 at 12 47 47 pm](https://cloud.githubusercontent.com/assets/59380/15477779/974487e6-20e4-11e6-9c54-c323aef68576.png)
My shell thinks JSON.pm is good to go:
```
   λ ~ : cpan JSON
Loading internal null logger. Install Log::Log4perl for logging messages
CPAN: Storable loaded ok (v2.41)
[LOTS OF CRAP ELIDED HERE]
CPAN: Module::CoreList loaded ok (v3.03)
JSON is up to date (2.90).
```
it's in my @INC:
```
   λ ~ : find . -name "JSON.pm"
./perl5/lib/perl5/JSON.pm
```

So any machine w/ a reasonably up-to-date CPAN install *should* have the right module, and it's easy to install, but I guess Komodo doesn't know how to find it.

**Comment by mitchell-as** [comment]
Hmm, it appears Komodo is looking for JSON in your /Library and /System paths without checking the directory you specified in your screenshot. Is there a Perl environment variable that you can use to modify `@INC`? If so, try setting it from Komodo (Edit > Preferences > Environment).

**Comment by neurobashing** [comment]
Already set, `PERL5LIB=/Users/greggthomason/perl5/lib/perl5`

**Comment by neurobashing** [comment]
ok setting PERL5LIB and PERL_LOCAL_LIB_ROOT fix it. Can Komodo look for those @ startup to see if a user has a local lib set up?

**Comment by mitchell-as** [comment]
I'm not sure how or why, but I have those exact env variables set up by default, and my Komodo uses them without issue. (I know next to nothing about perl and certainly did not set those variables!) I'm not exactly sure what you mean by "can Komodo look for those @ startup".

**Comment by neurobashing** [comment]
to be clear, setting them fixes it. (I would assume you set them up some time in the past as debugging or something; I didn't have them until I configured CPAN)

by "@ startup" I mean, is it acceptable to add them to the system @INC it reads, so users won't have their regex toolkit break. that way it'll "just work", in theory.

**Comment by mitchell-as** [comment]
Sorry for missing something so basic, but I'm still not following. (I probably have a really bad case of the Mondays.) If the environment variables are not set in Komodo, how can it know if/where a local Perl lib is in order to add it to `@INC`?

**Comment by Naatan** [comment]
Unfortunately this is just the way Komodo operates: We do not come shipped with any language distributions, but we hook into the ones you use. If your language is not properly configured from your global system shell (which Komodo launches from, unless you're using a custom start script) then Komodo will exhibit the symptoms of this issue.
