### ISSUE TITLE
Colorpicker swatch popup is flickering

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1590]
### Short Summary

Hover on a color and start moving your mouse (but keep it over the color). The popup is randomly flickering.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10 nightly
*Operating System (and version)?* eOS 0.4

**Comment by mitchell-as** [comment]
This was also present in Komodo 9 and is a minor drawing artefact. I don't think it's worth spending time on, but @Naatan can disagree. I'm going to close this ticket though.
