### ISSUE TITLE
Spellcheck somtimes inserting at wrong place instead of replacing it

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#1593]
### Short Summary
My english writing is not that strong but luckily komodo has spell-check.
Only in Komodo 10 it sometimes places the result at the end of a line below.

### Steps to Reproduce
I have the sample text:

`
The shortcut behaves the same in each program, if I put it the cursor in komodo in the editor or in firefox or in thunbird in a textfield. It inserting the same special charachter in each program, with the <kbd>ctrl + alt + w</kbd> shortcut. If i use it outside a textfield nothing happens.
`

It will ask you to replace firefox => Firefox, thunderbird => Thunderbird, textfield => text field.
If i replace all of them my code looks now like this:

`
The shortcut behaves the same in each program, if I put it the cursor in komodo in the editor or in Firefox or in thunbird in a text field. It inserting the same special charachter in each program, with the <kbd>ctrl + alt + w</kbd> shortcut. If i use it outside a textfield nothing happensThunderbird
`

The word Thunderbird is not replaced but, placed at the end of the buffer.
With larger text, its sometimes places it a few lines down, at the end of a line.

### Platform Information
Windows 10 Komodo Ide 10

**Comment by mitchell-as** [comment]
Thanks for the report.

**Comment by mitchell-as** [comment]
@babobski I thought I'd be able to reproduce this, but I cannot. Can you reliably reproduce it in some way? Looking at the code, it seems to me the only way this could happen is if you manage to perform some editing action after right-clicking the word but before clicking on a menu item to insert the suggestion. I haven't managed to do that myself.

**Comment by Defman21** [comment]
I was able to reproduce it, gonna try now.

**Comment by Defman21** [comment]
```
kurwa helveta javla fitta
hello |
```
| is your cursor. Try to fix first line of words.

**Comment by Defman21** [comment]
Okay seems like I found the reproduction steps.

`wrang wragg wrong`. First - fix "wrang" word using spell checker. Then don't move your cursor and fix "wragg"

**Comment by mitchell-as** [comment]
That's the problem. I don't know how to fix a word without moving my cursor -- right click always places my cursor on the word to change.

**Comment by Defman21** [comment]
It does for me but it still inserts it in a wrong place.

**Comment by Defman21** [comment]
https://youtu.be/f_SQGp7KYNI

**Comment by mitchell-as** [comment]
Thanks for the video @Defman21. You rock.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoIDE/commit/b652b8e086ce1e59dbb876e7492a2574da8630a8

**Comment by Defman21** [comment]
You are fast!

**Comment by tonyattwood** [comment]
Hi,

Just  wanted  to say hi and tell you how much  I  miss you, here  are some interesting  things  for  you <http://follow.mikevergato.com/e4brrrmx>

My best to you, tony.attwood@ntlworld.com
