### ISSUE TITLE
Can't use Find dialog after some time

### ISSUE THREAD

**Issue by jsnjack** [Komodo/KomodoEdit#1597]
### Short Summary

After I use komodo for some time, find dialog stops working
### Steps to Reproduce

Open komodo, open project, work with it. After some time komodo find dialog is broken
### Expected results

Komodo find dialog always works
### Actual results

Stops working after some time
### Platform Information

Komodo Edit, version 10.0.0, build 17209, platform linux-x86_64
### Additional Information

[komodo_log.txt](https://github.com/Komodo/KomodoEdit/files/279683/komodo_log.txt)

**Comment by Naatan** [comment]
Could you share the full error log the next time this happens?

**Comment by jsnjack** [comment]
It keeps happening 2-3 times per day. Still can't find reliable way to reproduce it. 

Full log from komodo session is attached
[komodo_full.txt](https://github.com/Komodo/KomodoEdit/files/302546/komodo_full.txt)

**Comment by Naatan** [comment]
Too much going on in that log to tell unfortunately. Please let us know if you find out what triggers the issue.
