### ISSUE TITLE
Markdown preview not working in nightly

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#16]
i have a markdown file open but the markdown preview toolbar button remains grey/disabled.

**Comment by Naatan** [comment]
I cannot reproduce this. Is the markdown file you're viewing actually interpreted as Markdown? (Language menu).

**Comment by Defman21** [comment]
Yes. It's doesn't work for me too.
06.03.2015 2:52 пользователь "Nathan Rijksen" <notifications@github.com>
написал:

**Comment by Naatan** [comment]
@Defman21 Wait are you saying you cant reproduce it or you cant press the markdown preview button?

**Comment by Defman21** [comment]
I don't see this button even If I choose "Markdown" as language.

**Comment by Naatan** [comment]
Ahh I think I know what's going on here. Please go into addons and uninstall the "Markdown Preview" addon. You probably had the old addon version installed rather than the native one that comes with Komodo. Uninstalling it should force the Komodo one.

Let me know (both of you) if this fixes your issues.

**Comment by Defman21** [comment]
Oh.. it is available under `View`...
And I can't uninstall it. Only disable.

**Comment by Defman21** [comment]
Also the version of the add-on is 0.3, last updated: 03/06/2015

**Comment by Naatan** [comment]
Is the button under `View > Toolbars > Customize`?

**Comment by Defman21** [comment]
`Tools Toolbar - Preview Markdown`

**Comment by Naatan** [comment]
??

**Comment by Defman21** [comment]
Yes it is under the path you wrote.

**Comment by Naatan** [comment]
Try toggling it there? Also make sure it's not being overflowed (your window is large enough to show it).

**Comment by Defman21** [comment]
Pressed it. Works fine. But in previous versions I could see "Preview" button just in the editor window...

**Comment by Naatan** [comment]
Eh? please read my instructions again, you are accessing a different option than the one I'm describing. I'm describing the toggle that enables the button on your toolbar, not a menu entry to open the markdown viewer.

**Comment by Defman21** [comment]
I hate myself. Yes - it's visible in Toolbar.

**Comment by Naatan** [comment]
lol. Deleting noisy comments.
