### ISSUE TITLE
HiDPI is messed up on Linux/Gnome

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#160]
Someone at pycon showed me HiDPI on Komodo Edit using Gnome Shell Classic, lots of things are messed up about it.

**Comment by toddw-as** [comment]
Could be same problem as #161

**Comment by Naatan** [comment]
Possibly, the scaling seemed to be all over the place. But it even affected Scintilla (doubling the font size). Autocompletions were miss-aligned, icons were tiny.. 

I'll have to install Linux on my macbook to dig in.

**Comment by Jiehong** [comment]
From #922, here is a screen of the issues:

![](https://cloud.githubusercontent.com/assets/1061229/11513217/3c2bf09c-9872-11e5-8619-ca298040b4ad.png)

This is with version 9.3.1, Gnome font scale set to 1.0, on a macbook pro (2880×1800, so dpi of about 192).

While trying to fix it, I came up with this moderate improvement:

- set layout.css.devPixelsPerPx to 2.0;
- set font size to 6;

And I ended up with the following capture:

![](https://cloud.githubusercontent.com/assets/1061229/11513432/686726da-9873-11e5-83e9-90097490bea4.png)

But, still:

- Icons are larger but blurred;
- Lines numbers and lines heights are still huge;
- Completion pop-up still tiny (not on the capture).

**Comment by Naatan** [comment]
This should be fixed in Komodo 10

**Comment by mithat** [comment]
Requesting this be reopened. It doesn't appear to be fixed here. Attached is an image of the Default theme in Komodo 10. I've got DPI set both in .Xresources and Xfce Appearances.
``` shell
$ uname -a
Linux xxxxxx 4.6.0-1-amd64 #1 SMP Debian 4.6.1-1 (2016-06-06) x86_64 GNU/Linux
```

![screenshot_2016-07-05_19-39-20](https://cloud.githubusercontent.com/assets/2021060/16592273/972d5ba4-42e8-11e6-806a-a6a4b12d8e0b.png)

**Comment by mitchell-as** [comment]
Hi, are you on a HiDPI screen?

**Comment by mithat** [comment]
This is on a Dell laptop's built-in 15"-ish 1600x900 screen. I don't know if that formally qualifies as HiDPI. I'm using 120 dpi because it produces the correct font geometry everyplace else -- save one or two Java Swing apps.

**Comment by cgchoffman** [comment]
@mithat, that screenshot looks like you've zoomed in the text, ie. Ctrl + Scroll wheel up.
Try hitting `Ctrl + 0` to reset zoom in the editor.

**Comment by Defman21** [comment]
@mithat 1600x900@15 DPI is 122.38 and no, it's not HiDPI. It should be about 220-400 DPI to be HiDPI (according to Retina sizes)

**Comment by mithat** [comment]
@cgchoffman  `Ctrl + 0` was the first thing I tried. :-)

**Comment by mitchell-as** [comment]
Tracking this now in #1531
