### ISSUE TITLE
CSS3 - column-count

### ISSUE THREAD

**Issue by Artekis** [Komodo/KomodoEdit#1600]
### Short Summary
I'm a bit new to this, but the CSS3 propery called "column-count" doesn't seem to be working, and is displayed as incorrect according to KomodoEdit.

### Steps to Reproduce
Try to use the column-count property in a CSS file.

### Expected results
Shouldn't have a incorrect underline symbol under it. When you preview it in the tab browser of Komodo, it should work fine, but it doesn't.

### Actual results
The chrome browser is able to understand it just fine and the column-count property works, but if you try to preview it in KomodoEdit, column-count does not work.

### Platform Information
Komodo Edit
Latest version as of today. Not sure where to get the definite number for it.
Windows 10

**Comment by Defman21** [comment]
>Latest version as of today. Not sure where to get the definite number for it.

Help - About Komodo. I'm gonna to fix this though.

**Comment by Defman21** [comment]
It presents in the codeintel: https://github.com/Komodo/KomodoEdit/blob/854dccaf47522990a4eda28a220da1ba39e66fe1/src/codeintel/lib/codeintel2/constants_css3.py#L325

What are you talking about? Komodo shows that column-count is an invalid property?

**Comment by Defman21** [comment]
Btw reproduced using 10 nightly. It's something related to Mozilla checker though.

**Comment by babobski** [comment]
For the displaying issue, css3 is still experimental, the most know features like border-radius can be used without prefix.
But a lot features still need prefixing if you want to support the major browsers.
The column-count still needs most of it's prefixes as you can see on [caniuse.com](http://caniuse.com/#search=column-count)

**Comment by Defman21** [comment]
I'd not call CSS3 experimental, it's likely beta. Major browsers are supporting most of the properties without prefixes and they are trying to drop any prefixes. (AFAIK Firefox and Chrome are trying to drop any prefixed properties). But for older compatibility - yes, you have to prefix your properties. However, there are different tools to make this process easier or even make it automatically.

**Comment by Naatan** [comment]
This is a limitation of the Mozilla CSS checker. You could work around this by using SASS for CSS checking, under Preferences > Syntax & Spell Checking > Language-specific syntax checking properties.

**Comment by Defman21** [comment]
Note: SASS linter does not warn about invalid properties. It would be helpful in case you know you don't make typos at all (well, Komodo has codeintel so you'd probably won't make a typo :smiley:).

**Comment by babobski** [comment]
@Defman21 What I meant with experimental, is that most parts of css3 are still working drafts at w3c ( like the [animations](https://www.w3.org/TR/css3-animations/) and [transistions](https://www.w3.org/TR/css3-transitions/) ), thats why will still need to check witch [prefixes](https://developer.mozilla.org/en-US/docs/Glossary/Vendor_Prefix) we should use.


> there are different tools to make this process easier or even make it automatically

You got one, with [emmet](https://github.com/Defman21/komodo-emmet) the prefixes are automatically added. It's currently adding to much prefxes, I'm running a adapted version, where I edited these [lines](https://github.com/Defman21/komodo-emmet/blob/master/content/js/emmet-app.js#L10141) so not everything is being prefixed.

I've got a fork of you're repo and I'm currently working on a preference page so you can adjust the prefixes It's using. Currently the emmet addon is not included in the packages, I know you had contact with the original developer and he will be working on a new version( read it somewhere on a post a time ago ).
But can you in the mean time add the emmet addon to packages so it's more accessible for the community?

Some other options for prefixing:
[prefix free](https://leaverou.github.io/prefixfree/)
[less autoprefix plugin](https://github.com/less/less-plugin-autoprefix)

**Comment by Defman21** [comment]
It should be available in the packages section. Not sure he'll work on a
new version, I'm gonna fork his emmet core and just build an add-on with it
so it will expand abbreviations only, without any other emmet features. I
don't need anything from it. I'll add this add-on to the packages though.

**Comment by babobski** [comment]
Emmet is available in the packages only the old one, but if I understand you right, you gonna add the K10 version to?

> I'm gonna fork his emmet core and just build an add-on with it

Ah good plan :+1: 
> without any other emmet features

Could I already make a enhancement request? I also use the wrap with abbreviation shortcut a lot.
When I need an extra wrapper around a code-block I find this an ideal function.

**Comment by Defman21** [comment]
>Emmet is available in the packages only the old one, but if I understand you right, you gonna add the K10 version to?

There's no difference between my fork and the version available in the Packages. I've just tweaked install.rdf so it wouldn't drop any incompatibility errors.

>Could I already make a enhancement request? I also use the wrap with abbreviation shortcut a lot.
When I need an extra wrapper around a code-block I find this an ideal function.

I don't even start working on this, so no. I'll notice you once I create a workable instance of it so you could create a request for this feature.

**Comment by cgchoffman** [comment]
This seems to have gone pretty far from the topic of this issue.  Can you please continue this discussion in the forums? :)
