### ISSUE TITLE
Left tab bar scroll icon broken

### ISSUE THREAD

**Issue by cyberbit** [Komodo/KomodoEdit#1601]
### Short Summary
The left scrolling arrow icon that appears on the tab bar when I'm working too hard (lots of tabs) is broken. See attached image.

### Steps to Reproduce
Open many tabs, or less than many and resize window to force tab bar scrolling.

### Expected results
The icons work as expected.

### Actual results
The left icon shows a little box with hex in.

### Platform Information

*Komodo Edit or IDE?* Edit
*Komodo Version?* 10.0.0
*Operating System (and version)?* Windows 7

### Additional Information
![image](https://cloud.githubusercontent.com/assets/7350183/15519561/b29ec414-21c7-11e6-856f-2e5b4da55af5.png)

**Comment by cgchoffman** [comment]
Dupe #1535

**Comment by cgchoffman** [comment]
Thanks though!

**Comment by cyberbit** [comment]
Ah, another miss! I'll keep trying. :P
