### ISSUE TITLE
In browser preview screen the refresh icon is not visible

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#1603]
### Short Summary
![2016-05-25 09_49_49](https://cloud.githubusercontent.com/assets/3530262/15532075/273ce134-225e-11e6-8918-06cad98002b1.jpg)
The refresh icon is not visible, but I can click on it and is still working

**Comment by mitchell-as** [comment]
Thanks for catching this!

**Comment by cgchoffman** [comment]
Edit or ide?

**Comment by babobski** [comment]
Just tested, 
but ide only

**Comment by cgchoffman** [comment]
Ok, thank you.  I wasn't at my desk and was certain this was done on IDE.  Evidently not though.
