### ISSUE TITLE
Remove "Use Built-In Less Syntax Checker" option

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1607]
Did we ever even have this?

**Comment by mitchell-as** [comment]
No, I think it was just a bad copy-paste job.

**Comment by babobski** [comment]
@Naatan on the komodo ide website it says you're supporting syntax checking for LESS
![2016-06-16 08_11_09](https://cloud.githubusercontent.com/assets/3530262/16107072/1bd3cad6-339a-11e6-93ca-b46dfd6c7a05.png)

**Comment by Naatan** [comment]
@babobski we do, we just don't ship a less executable, so the pref screen should not be showing that option.

**Comment by babobski** [comment]
ah ok, it's supported, but not default configured

**Comment by Naatan** [comment]
By default it will detect it on your PATH.
