### ISSUE TITLE
in_array caltips not working

### ISSUE THREAD

**Issue by camilner** [Komodo/KomodoEdit#1608]
### Short Summary
When editing a PHP document, the in_array function brings up the caltip for implode

### Steps to Reproduce
Create a new php file from template. type the following if(in_array(), wait for the yellow caltip box to appear,

### Expected results
I am expecting the caltip for in_array

### Actual results
I actually get the caltip for implode

### Platform Information
Komodo Edit. 
Version: 10.0.0. 
Build 17209. 
Operating System: OSX Yosemite
OS Version: 10.10.5

### Additional Information
See attached image:
<img width="453" alt="screen shot 2016-05-25 at 17 29 23" src="https://cloud.githubusercontent.com/assets/12657076/15548121/cbfd57ae-229e-11e6-8779-4a539cb6d66c.png">

 -- eg. Error logs, screenshots, workarounds --

**Comment by camilner** [comment]
If there is more information I can give please let me know. This is the first bug I've reported via GitHub

**Comment by Naatan** [comment]
I cannot reproduce this. Can you share a code snippet?

**Comment by camilner** [comment]
Hi Naatan. I am able to replicate this by just typing if(in_array()) as in the image attached on the issue

**Comment by cgchoffman** [comment]
@naatan I'm pretty sure this is a dupe if the linter tooltip flashing bug.  It's the same as the perl debugging issue closed yesterday where hovering on @INC caused the info tooltip to flicker too fast to see.   I'll see if I find it.

**Comment by mitchell-as** [comment]
@camilner I'm not able to reproduce this either, in IDE or Edit. Please try Help > Troubleshooting > Reset Codeintel Database.

**Comment by cgchoffman** [comment]
I think it's #1585.

**Comment by Naatan** [comment]
@cgchoffman the only similarity is that they're both tooltips. #1585 talks about linter tooltips flickering, this one talks about codeintel tooltips giving the wrong function. Based on that I would not think there is a relation.

**Comment by Naatan** [comment]
@camilner this is what I'm getting:

![image](https://cloud.githubusercontent.com/assets/278649/15550278/aff393cc-227e-11e6-9fb1-23fb2a111882.png)

Can you create a blank PHP file and reproduce the issue?

**Comment by camilner** [comment]
@Naatan & @mitchell-as, resetting the Codeintel Database has fixed this issue completely, the helper tooltip that is displayed is correct and the same as @Naatan's example. Thank you both very much for your help, I really appreciate it

**Comment by Naatan** [comment]
Thanks for letting us know :)
