### ISSUE TITLE
Prefer Tabs ignored

### ISSUE THREAD

**Issue by xcash** [Komodo/KomodoEdit#1609]
### Short Summary
I've a Python project made with Komodo -9 using tabs as indentation.
In Komodo X we're unable to force Tabs. At each Enter the editor inserts a run of spaces.
The flags `Prefer spaces...` are selected and `Allow files to override...` is unchecked globally and by project preferences.
This rends Komodo X unusable.

### Steps to Reproduce
We just open a .py file with tabs and just do an Enter on a row. 

### Expected results
Next row with tabs

### Actual results
Row with run of spaces

### Platform Information
Komodo Edit, version 10.0.0, build 17209, platform linux-x86_64. Built on Wed May 11 22:00:36 2016.

**Comment by mitchell-as** [comment]
Hi, this has been fixed in our nightly releases: http://downloads.activestate.com/Komodo/nightly/komodoide/latest/

**Comment by xcash** [comment]
@mitchell-as yeah it works like a charm now, thanks! :)
