### ISSUE TITLE
Scale pixels based on platform settings

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#161]
Reference: http://forum.komodoide.com/t/pixels-on-the-retina-display/1457

> As a work around I've manually edited lib/mozilla/greprefs.js and changed "layout.css.devPixelsPerPx" to better value. e.g 2.0.

**Comment by palmerj** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=975919 for more information

**Comment by toddw-as** [comment]
Need to update to Mozilla 38 to get this fix (we are currently using Mozilla 35).

**Comment by LukeCarrier** [comment]
This is still a major problem for Linux users.

**Comment by Jiehong** [comment]
Any news on this issue? How one can determine which Mozilla version is Komodo currently using?

**Comment by cgchoffman** [comment]
@Jiehong, we have Mozilla 35 under the hood.

**Comment by LukeCarrier** [comment]
FYI the lack of progress on this ticket is the reason I terminated my subscription and switched to a competing product. Your Linux customers pay the same licensing fee as all of your other users and don't all have time to keep waiting for you to prioritise a completely breaking deficiency in your product.

I think it's high time ActiveState started taking itself and its developer-focused products seriously and stopped pretending that this isn't a high priority problem. Either that, or ActiveState should issue a very clear message informing users that their custom isn't appreciated.

**Comment by Naatan** [comment]
Unfortunately I should have marked this as a duplicate, the issue is actually tracked here: #160.

It is slated for Komodo 10. Unfortunately given the underlying changes required this needs to go to a major release as it is likely to need significant testing.
