### ISSUE TITLE
commando sorting wrong

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#1610]
The sorting of commando got weird. 1, 2 at the bottom...
The previous string I searched for was prolly "copy"

can't repro for a second time

### Platform Information

Komodo IDE, version 10.0.0, build 89159, platform linux-x86_64.
Built on Wed May 11 15:27:38 2016.

### Additional Information

![screenshot_2016-05-26_14-40-48](https://cloud.githubusercontent.com/assets/350912/15574859/01c117b6-2350-11e6-897b-159619dd294f.png)

**Comment by Naatan** [comment]
I'll keep my eye out for this as well, but without reproduction steps this will be very hard to resolve. Closing until someone finds steps.
