### ISSUE TITLE
Command+shift+up text highlighting doesn't work in Komodo Edit 10.0.0 on OSX

### ISSUE THREAD

**Issue by elo2112** [Komodo/KomodoEdit#1611]
This issue affects Komodo Edit 10.0.0 and also appeared in Komodo Edit 9.3:
https://github.com/Komodo/KomodoEdit/issues/885
---

In Mac OSX applications, command+shift+down highlights text from the text cursor position to the bottom of a document, and command+shift+up highlights text from the text cursor position to the top of a document.

The command+shift+down shortcut in Komodo Edit 10.0.0 works normally, but command+shift+up does not highlight any text. This used to work in Komodo 8 and earlier versions, and was fixed in this commit for the 9.x release: https://github.com/Komodo/KomodoEdit/commit/4f37df520dd2471f1d3550c8a52ca0ed2b800abf

Tested most recently with Komodo 10.0.0 on Mac OS 10.11.5.

**Comment by cgchoffman** [comment]
Can you confirm the build number of the Komodo you're using: Komodo Menu > About Komodo
Also confirm you're using the default keybindings in your preferences.

I'm not able to reproduce this and the default OSX keybinding set has the correct keybinding: https://github.com/Komodo/KomodoEdit/blob/master/src/schemes/Mac.p.kkf#L59

**Comment by elo2112** [comment]
You're right, I didn't have the default key binding.  Sorry for the false alarm.

Komodo Edit, version 10.0.0, build 17209, platform macosx. Built on Wed May 11 22:00:40 2016.

After resetting the keys to defaults, though, I did discover a new key binding conflict.  The Default key bindings have meta+H bound to "Replace...", which conflicts with the standard OSX meta+H shortcut for hiding an application.  Should I create a new ticket?

**Comment by cgchoffman** [comment]
> Should I create a new ticket?

To keep things clear, yes please.  Thanks for confirming the other issue is ok.

**Comment by elo2112** [comment]
Will do.  Thanks for all of your very quick replies!
