### ISSUE TITLE
Komodo Edit 10.0.0 meta+H default binding conflicts with OSX system-wide "Hide Application" binding

### ISSUE THREAD

**Issue by elo2112** [Komodo/KomodoEdit#1614]
### Short Summary

The default key bindings have meta+H bound to "Replace...", which conflicts with the standard OSX meta+H shortcut for hiding an application.

### Steps to Reproduce

In OSX, use "Default" key bindings and press meta+H while using the application.  Instead of hiding the application (like in other apps, and in earlier versions of Komodo), the "Replace..." action is triggered.

### Platform Information

Komodo Edit, version 10.0.0, build 17209, platform macosx.
Built on Wed May 11 22:00:40 2016.

**Comment by mitchell-as** [comment]
Thanks for the report.

**Comment by hayne** [comment]
This is part of what was fixed for issue #1665 (now closed)

**Comment by elo2112** [comment]
Thanks!
