### ISSUE TITLE
Path breadcrumbs missing when file opened from remote server over SFTP

### ISSUE THREAD

**Issue by uFire** [Komodo/KomodoEdit#1617]
### Short Summary
When file opened from remote server over SFTP, there is no path "breadcrumbs" above the editor window. 

### Steps to Reproduce
Open a Perl file from remote server using SFTP

### Expected results
Path to the file expected to be shown above the editor window

### Actual results
Blank line where path expected

### Platform Information
Komodo IDE, version 10.0.0, build 89159
Windows 10 x64 

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by mitchell-as** [comment]
@cgchoffman or @Naatan I don't have access to an SFTP server to test this, but can either of you reproduce this?

**Comment by Naatan** [comment]
I don't have an SFTP server handy either, you @cgchoffman ?

@uFire  Please share your error log after reproducing the issue.

You can find your error log at Help > Troubleshooting > View Log File.

**Comment by uFire** [comment]
Played around connecting to my remote dev server using FTP and SFTP - results the same. Breadcrumbs filled ok for local files but always blank for remote ones. Log file attached.
[pystderr.zip](https://github.com/Komodo/KomodoEdit/files/287372/pystderr.zip)
