### ISSUE TITLE
run without debugging key binding skips settings dialog

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1624]
### Short Summary

`ctrl + R` skipps the debugger dialog :(  Hopefully there is another `F#` key left over for this.  I don't want to use F7 as when compared to most other debuggers, F7 was a debugging action, eg. step-in/over/out which makes more sense to me as well.

**Comment by mitchell-as** [comment]
Isn't this by design though? I thought run without debugging should not show the debug options dialog..

**Comment by Naatan** [comment]
I'm not certain what the ideal UX would be, but I do seem to remember that this wasn't a thing before.. so at the least this should probably be relabeled and retargeted.

**Comment by cgchoffman** [comment]
> I thought run without debugging should not show the debug options dialog..

@mitchell-as If we're going by previous functionality then it should show the debugging dialog.  I just tried it in 9 to confirm and the dialog appears.



> but I do seem to remember that this wasn't a thing before..

@Naatan I'm not sure what you mean here.  What part wasn't a thing?

**Comment by Naatan** [comment]
Nevermind, I just tested it on Komodo 9 and it does appear to be launching the debug dialog.

**Comment by cgchoffman** [comment]
I've reverted to the legacy key binding for `run without debugger`.  To accomplish this I've merged bindings ideas from JB and VS.
https://github.com/Komodo/KomodoIDE/commit/dc5b5658e593e9ba9967c8699ead71b843784a41
```
-binding cmd_dbgRun Ctrl+R
  binding cmd_dbgStepCursor F6
 -binding cmd_dbgStepIn F7
 -binding cmd_dbgStepOut F9
 -binding cmd_dbgStepOver F8
 +binding cmd_dbgRun F7
 +binding cmd_dbgStepIn F8
 +binding cmd_dbgStepOut Shift+F8
 +binding cmd_dbgStepOver F9
  binding cmd_dbgBreakpointToggle F4
```

**Comment by cgchoffman** [comment]
They are all under the right hand, from F5-F9, with a spread for the pinky to reach the "step over" (`F9`) binding which is intuitive in itself (reach over to step over).
