### ISSUE TITLE
Windows jumps when selecting in the split-mode

### ISSUE THREAD

**Issue by jsnjack** [Komodo/KomodoEdit#1627]
### Short Summary
Windows jumps in the split-mode

### Steps to Reproduce
Open project. Open 2 files in the vertical split mode. Start to selecting text in one of them

### Expected results
Opened window stay static

### Actual results
In the status bar "Sel: <some number>" is added and windows start to change their size, which looks very annoying

### Platform Information
Komodo Edit, version 10.0.0, build 17209, platform linux-x86_64

**Comment by Naatan** [comment]
Fairly certain this is #1536

The nightly should have this fixed:

http://downloads.activestate.com/Komodo/nightly/komodoide/latest/
