### ISSUE TITLE
Can't open new file or template

### ISSUE THREAD

**Issue by TheHunterZ** [Komodo/KomodoEdit#1628]
### Short Summary

If I go to New Tab>>New File , there is only the white 'X' and nothing else in the tab.
### Platform Information

_Komodo Edit or IDE?_ IDE
_Komodo Version?_ 10

_Operating System (and version)?_  Windows 7 Home Premium
### Additional Information

 -- eg. Error logs, screenshots, workarounds --
![bug kom 1](https://cloud.githubusercontent.com/assets/19651867/15652996/6131660a-268a-11e6-84d7-8e5086351f3e.PNG)

**Comment by Naatan** [comment]
Please share your error log after reproducing the issue.

You can find your error log at Help > Troubleshooting > View Log File.

**Comment by cgchoffman** [comment]
I can't reproduce this on my Windows 10 in my local build or the latest nightly, IDE and Edit.  Just an FYI, likely some clues in your logs @TheHunterZ
