### ISSUE TITLE
CommonJS ko/prefs: get/setPref is broken

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1631]
### Short Summary

While developing an add-on I found that `require('ko/prefs').getPref("whatever")` or `require('ko/prefs').setPref("whatever", true)` return exceptions:

getPref:

```
Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [koIPreferenceRoot.getPref]
Stack Trace:

    @chrome://console/content/js/console.js line 149 > eval:1:0
    this.execute@chrome://console/content/js/console.js:149:25
    this.onKeyNav/<@chrome://console/content/js/console.js:113:24
```

setPref:

```
Could not convert JavaScript argument arg 1 [koIPreferenceRoot.setPref]
Stack Trace:

    @chrome://console/content/js/console.js line 149 > eval:1:0
    this.execute@chrome://console/content/js/console.js:149:25
    this.onKeyNav/<@chrome://console/content/js/console.js:113:24
```

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10 nightly
*Operating System (and version)?* elementary OS

**Comment by cgchoffman** [comment]
I believe this is expected though it could be better documented.  `require('ko/prefs').getPref()` attempts to retrieve a preferences-set and if the returned value doesn't match then it throws an exception.  That's not very fun.

You need to use `require('ko/prefs').getString/Boolean/Long()` or the equivalent for `set` commands.

I think this would be a great task for the new SDK to take on: `require('ko/prefs').getPref()` should just work for any preference.  NOT `setPref()` though.  `set` should fail gracefully with a nice error if the user tries to set an incorrect type.

**Comment by Defman21** [comment]
>You need to use require('ko/prefs').getString/Boolean/Long() or the equivalent for set commands.

Yeah I wrote my own wrapper for it.

**Comment by Defman21** [comment]
Nathan says that getPref cannot be smarter, it will cause too much issues in other parts of Komodo, because they are relying on this pref very strictly. I agree with that, closing this as invalid.

**Comment by Naatan** [comment]
fwiw getPref is for getting a prefset, which holds string, long, bool, .. prefs. It's intended purpose has never been to get eg. string, long, etc prefs.

We could add something that is less explicit about the pref types, but I fear it would just open the door to buggy code. Something like this has to be done from the start or not at all.
