### ISSUE TITLE
About Komodo dialog is hiding version information with contributor list

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1632]
### Short Summary

See the screenshot.

![Uploading Capture.PNG…]()

**Comment by Defman21** [comment]
Nice screenshot.

**Comment by cgchoffman** [comment]
haha indeed. 
![capture](https://cloud.githubusercontent.com/assets/655154/15656613/15ef0764-265e-11e6-8a66-95aa11a5c193.PNG)

**Comment by Naatan** [comment]
I blame @jeff-hobbs :p

**Comment by cgchoffman** [comment]
If I add `window.sizeToContent()` on line *200* in *windows.p.xml* this resolves the issue.
https://github.com/Komodo/KomodoIDE/blob/master/src/chrome/komodo/content/bindings/windows.p.xml#L199

We could add it to `window.resize` instead but i'm unclear what the repercussions of that would be.

@Naatan can you weigh in on either of those options?

**Comment by Naatan** [comment]
Yes, that sounds like a good solution.

**Comment by Naatan** [comment]
Bah sorry, I thought you were saying to add sizeToContent() to the about dialog xul, not the window binding.

I'm hesitant about putting it on the window binding as it might have side effects, eg. on windows that have content too large to fit on screen. Also it likely affects the window restore (doesn't restore the size it was closed at anymore).

I'm not against this change but it needs further investigation, likely better to put it in 10.1 than 10.0.1. @cgchoffman up to you, either we revert this and add it only to the about dialog xul, or we leave it in but you'll need to do some exhaustive testing on Windows to ensure it doesn't have any side effects.

Sorry, my bad for not reading your comment properly.

**Comment by cgchoffman** [comment]
I suspected the same thing which is why I asked.  I'm fine with reverting it.  I can add it to the `onload` on the *about.xul* and see if that fixes it.  I can't find any of the dialogs that had the same issue any more :(

**Comment by cgchoffman** [comment]
I don't see a `dialog.xml` binding.  Even adding it there could be too broad though,if it existed.  Maybe this is just a "case by case" scenario?

**Comment by Naatan** [comment]
I meant `chrome://komodo/content/about/about.xul`. 

I think this is likely indeed a case by case type of thing.

**Comment by cgchoffman** [comment]
Thanks for the help @Naatan

**Comment by tonyattwood** [comment]
Hi,


I wanted to thank you  a lot for  all  you've done,  it was a real help. Please read my whole message here <http://esteem.trinityngo.com/e4shh>

My Best, tony.attwood@ntlworld.com
