### ISSUE TITLE
Don't work php variables and constants, color picker not appear for css

### ISSUE THREAD

**Issue by Andronachi-Marian** [Komodo/KomodoEdit#1633]
### Short Summary
I install both versions of komodo and in php constants, variabes don't work.
Exemple:  __ LINE __ ,__ FILE __, ..., $_COOKIE, $_SERVER (Content of the server: HTTP_HOST, etc).

### Steps to Reproduce
I delete the old ActiveState for version 9 and i install fresh version 10.
I create a file a.php on desktop and i type a variables and constants, autocomplete don't work.
In Komodo ide and edit 9 its wok fine. No problems.

### Expected results
My expected is to appear autocomplete for $_SERVER, $_POST, ... , etc
In css to work CTRL+LEFT CLICK on #COLOR to appear color picker like in version 9

### Actual results
Autocomplete in php, constants and variables don't work.
Color picker don't appear.

### Platform Information

*Komodo Edit or IDE?*  Both
*Komodo Version?* Komodo IDE, version 10.0.0, build 89159, platform win32-x86.
Built on Wed May 11 15:04:59 2016.
*Operating System (and version)?* Windows 7 Ultimate, Other: Not tested

### Additional Information

PHP ->
If remove the file 'php-7.0.cix' from 'ActiveState Komodo IDE 10\lib\mozilla\python\komodo\codeintel2\stdlibs' the variables and constants is work fine.
![php](https://cloud.githubusercontent.com/assets/19652512/15656326/906eb3f4-26ae-11e6-817d-ee6a5ac4d6b3.png)

> [2016-05-30 21:31:46,694] [INFO] Startup: Welcome to Komodo IDE 10.0.0 build 89159 (platform win32-x86, running on Windows 7 version 6.1.7601)
> [2016-05-30 21:31:46,694] [INFO] Startup: C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\komodo.exe built on Wed May 11 15:04:59 2016
> [2016-05-30 21:31:47,286] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
> [2016-05-30 21:31:47,344] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
>     @chrome://komodo/content/komodo.js:15:1
> 
> [2016-05-30 21:31:47,598] [ERROR] console-logger: TypeError: redeclaration of variable val (2) in chrome://analytics/content/analytics.js:204
> Traceback (most recent call last):
>   File "chrome://analytics/content/analytics.js", line 204, in 
> 
> [2016-05-30 21:31:47,832] [ERROR] console-logger: bad script XDR magic number (0) in :0
> Traceback (most recent call last):
>   File "", line 0, in 
> 
> [2016-05-30 21:31:48,056] [WARNING] keybindings: [Ctrl+0] was used for 'cmd_goToQuickBookmark_0', overriding to use 'cmd_fontZoomReset'
> [2016-05-30 21:31:48,615] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
> [2016-05-30 21:31:48,838] [INFO] elastic_tabstops: Elastic tabstops loaded.
> [2016-05-30 21:31:48,878] [INFO] komodospellchecker: Spell checker loaded.
> [2016-05-30 21:31:48,878] [INFO] komodospellchecker: Using dictionary en-US
> [2016-05-30 21:31:52,293] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
> [2016-05-30 21:31:52,296] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
> [2016-05-30 21:31:52,305] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
> [2016-05-30 21:31:54,756] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
> [2016-05-30 21:31:54,757] [WARNING] console-logger: Key event not available on some keyboard layouts: key="w" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
> [2016-05-30 21:31:54,759] [WARNING] console-logger: Key event not available on some keyboard layouts: key="n" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
> [2016-05-30 21:31:54,760] [WARNING] console-logger: Key event not available on some keyboard layouts: key="s" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
> [2016-05-30 21:31:54,762] [WARNING] console-logger: Key event not available on some keyboard layouts: key="d" modifiers="control,alt,shift" (1) in chrome://komodo/content/komodo.xul:0
> [2016-05-30 21:31:54,993] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010/lib/mozilla/components/koamAddonManager.js:138
> [2016-05-30 21:32:09,424] [ERROR] koScopeDocs-Py: Could not find cix for ext
> [2016-05-30 21:32:09,497] [ERROR] koScopeDocs-Py: Could not find cix for html5
> [2016-05-30 21:32:32,186] [WARNING] views: Inconsistent view count in view_closed event
> [2016-05-30 21:32:32,417] [WARNING] views: Inconsistent view count in view_opened event
> [2016-05-30 21:34:24,220] [WARNING] views: Inconsistent view count in view_closed event
> [2016-05-30 21:34:24,272] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of 0 (min 1)
> [2016-05-30 21:34:24,328] [WARNING] views: Inconsistent view count in view_opened event
> [2016-05-30 21:34:26,529] [ERROR] koPHPLinter: Error getting phpInfoEx.version.  Is a PHP interpreter defined?
> [2016-05-30 21:34:32,065] [WARNING] codeintel.php: no PHP was found from which to determine the import path
> [2016-05-30 21:34:41,786] [ERROR] koCodeIntel:     INFO: eval '_SERVER' at a.php#3  <Trigger 'php-defn-defn' at 13 (explicit)>
>     INFO: start scope is (<blob 'a.php'>, [])
>     INFO: _hit_from_citdl:: expr: '_SERVER', scoperef: (<blob 'a.php'>, [])
>     INFO: _hit_from_citdl:: expr tokens: ['_SERVER']
>     INFO: _hits_from_first_part:: find '_SERVER ...' starting at (<blob 'a.php'>, []):
>     INFO: _hits_from_first_part:: scoperef now (<blob 'a.php'>, []):
>     INFO: _hits_from_first_part:: checking namespace aliases
>     INFO: _hits_from_first_part:: pt3: is '_SERVER' accessible on (<blob 'a.php'>, [])? no
>     DEBUG: _hit_from_elem_imports:: Checking imports, tokens[0]: '_SERVER' ... imp_elem: <blob 'a.php'>
>     INFO: _hit_from_elem_imports:: trying import everything: tokens: ['_SERVER']
>     INFO: _hit_from_elem_imports:: trying with lpath: ('_SERVER',)
>     INFO: _hit_from_elem_imports:: ie: lookup ('_SERVER',) in <PHP curdirlib> => []
>     INFO: _hit_from_elem_imports:: ie: lookup ('_SERVER',) in <PHP cataloglib: pywin32, pywin32 (Python3)> => []
>     INFO: _hit_from_elem_imports:: ie: lookup ('_SERVER',) in <php-7.0 stdlib> => []
>     INFO: _hit_from_elem_imports:: ie: no matches found
>     ERROR: evaluating '_SERVER' at a.php#3: could not resolve first part of '_SERVER'
> [2016-05-30 21:35:02,701] [ERROR] koCodeIntel:     INFO: eval '_SERVER' at a.php#3  <Trigger 'php-complete-array-members' at 19>
>     INFO: _hit_from_citdl:: expr: '_SERVER', scoperef: (<blob 'a.php'>, [])
>     INFO: _hit_from_citdl:: expr tokens: ['_SERVER']
>     INFO: _hits_from_first_part:: find '_SERVER ...' starting at (<blob 'a.php'>, []):
>     INFO: _hits_from_first_part:: scoperef now (<blob 'a.php'>, []):
>     INFO: _hits_from_first_part:: checking namespace aliases
>     INFO: _hits_from_first_part:: pt3: is '_SERVER' accessible on (<blob 'a.php'>, [])? no
>     DEBUG: _hit_from_elem_imports:: Checking imports, tokens[0]: '_SERVER' ... imp_elem: <blob 'a.php'>
>     INFO: _hit_from_elem_imports:: trying import everything: tokens: ['_SERVER']
>     INFO: _hit_from_elem_imports:: trying with lpath: ('_SERVER',)
>     INFO: _hit_from_elem_imports:: ie: lookup ('_SERVER',) in <PHP curdirlib> => []
>     INFO: _hit_from_elem_imports:: ie: lookup ('_SERVER',) in <PHP cataloglib: pywin32, pywin32 (Python3)> => []
>     INFO: _hit_from_elem_imports:: ie: lookup ('_SERVER',) in <php-7.0 stdlib> => []
>     INFO: _hit_from_elem_imports:: ie: no matches found
>     ERROR: evaluating '_SERVER' at a.php#3: could not resolve first part of '_SERVER'
> [2016-05-30 21:36:46,661] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
> [2016-05-30 21:36:46,664] [WARNING] console-logger: Key event not available on some keyboard layouts: key="w" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
> [2016-05-30 21:36:46,664] [WARNING] console-logger: Key event not available on some keyboard layouts: key="n" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
> [2016-05-30 21:36:46,667] [WARNING] console-logger: Key event not available on some keyboard layouts: key="s" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
> [2016-05-30 21:36:46,667] [WARNING] console-logger: Key event not available on some keyboard layouts: key="d" modifiers="control,alt,shift" (1) in chrome://komodo/content/tail/tail.xul:0

CSS ->
![css](https://cloud.githubusercontent.com/assets/19652512/15656317/8476ab9c-26ae-11e6-9738-bec1eaa581c9.png)

**Comment by Naatan** [comment]
Please enter the requested fields (summary, steps to reproduce, expected result, .. ).

I am not sure what this bug is about and don't want to make assumptions.

**Comment by mitchell-as** [comment]
I'm not able to reproduce this. Which PHP interpreter version are you using?
![php](https://cloud.githubusercontent.com/assets/12902397/15678470/7712b374-271c-11e6-91b6-085408c62f0c.png)

**Comment by Andronachi-Marian** [comment]
I don't have interpreter. Is the default settings (Clean Install).
I install windows 8.1 Enterprine in VirtualBox and Windows 7 SP1 Ultimate, all clean, and is don't work for my.
Same errors in windows 8.1 [pystderr.txt](https://github.com/Komodo/KomodoEdit/files/293430/pystderr.txt)

Works fine if remove the file 'ActiveState Komodo IDE 10\lib\mozilla\python\komodo\codeintel2\stdlibs\php-7.0.cix'.

**Comment by mitchell-as** [comment]
Thanks, I've managed to reproduce this.

**Comment by mitchell-as** [comment]
@Andronachi-Marian as a workaround, if you have a PHP < 7 installed, point Komodo to it and it will not use the php-7.0.cix catalog.

**Comment by Naatan** [comment]
@mitchell-as is this a complicated fix? If not I think this is 10.0.1 worthy.

**Comment by mitchell-as** [comment]
I don't think so. I'll move to 10.0.1.
