### ISSUE TITLE
Menu's options grayed out,  unable to save , Komodo Edit 10

### ISSUE THREAD

**Issue by Agwright** [Komodo/KomodoEdit#1634]
### Short Summary

installed Komodo Edit on Dell latitude E5450 64 bits
no error's 
when to use it - pasted Text in all appearing on the same line using view menu when to put on word wrap but all options are greyed out,  clicked in the middle of the text , 1 I could add new text but hitting enter isn't put it on new lines
also the save options are greyed out

Komodo Edit, version 10.0.0, build 17209, platform win32-x86.
Built on Thu May 12 00:43:26 2016.

_**Komodo Edit_\* or IDE?\* 
_Komodo Version?_ 
_Operating System (and version)?_ 
![komodo](https://cloud.githubusercontent.com/assets/8565971/15665980/1c358d66-2706-11e6-9322-b76574209968.png)
 Window 7 
### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by mitchell-as** [comment]
Please share the contents of your error log (Help > Troubleshooting > View Log File).

**Comment by cgchoffman** [comment]
This sounds very familiar. Can you try switching from one file then back to this problem file?  Just click on another files tab then back to this problem file.  If it's the issue I think it is then that should get the menus back.  Please also provide your logs as @mitchell-as  requested.

**Comment by Agwright** [comment]
[pystderr.txt](https://github.com/Komodo/KomodoEdit/files/292773/pystderr.txt)

**Comment by Agwright** [comment]
Log file attached yep tried a few different files of various types - I can edit them but no new  lines when hitting enter or even a new file unable to enter to create new lines 
Thanks for looking at this

**Comment by cgchoffman** [comment]
I'm guessing it's these `TypeError: xtk.domutils is undefined`
Try to reproduce the issue in *Help > Troubleshooting > Safemode*
If that works try opening *Commando (Ctrl + Shift + O) > Packages > Manage Packages > List Outdated* and uninstall any packages there.

**Comment by Agwright** [comment]
perfect Thank you now working as normal

**Comment by cgchoffman** [comment]
Did you happen to notice which AddOn was causing the issue @Agwright ?

**Comment by Agwright** [comment]
will try and find out

**Comment by Agwright** [comment]
maybe "Track changes" :( thats a very useful add on :(

**Comment by cgchoffman** [comment]
I meant by doing the steps in this comment: https://github.com/Komodo/KomodoEdit/issues/1634#issuecomment-223021788

I want to determine if it was a third party addon that broke your install.  It can't be Trackchanges if the above comment resolved your issue.  Trackchanges is builtin, not third party so perform the safemode step does not remove it.

**Comment by Agwright** [comment]
Hi Sorry - I will add them on and see which one breaks it
