### ISSUE TITLE
Variable and expression values not displayed in hover tooltips in debug mode

### ISSUE THREAD

**Issue by jimmeek** [Komodo/KomodoEdit#1637]
### Short Summary

Despite having selected under Preferences->Debugger->Debugger/Editor Integration
"Show expression values in hover tooltips" by checking the check box, 
neither variable nor expression values are displayed when I hover the mouse over one, 
even if I have "selected" the variable or expression.  (Occasionally the expected "tooltip" 
will appear for a fraction of a second, much too short a time to read.)
### Steps to Reproduce

Run Perl program in debug mode.  Stop at breakpoint.  Hover cursor over any variable.   Select any expression and hover over it.  
### Expected results

Should see values in tooltips.  
### Actual results

Very occasionally one will appear for a fraction of a second. Otherwise nothing displayed.
### Platform Information

_Komodo Edit or IDE?_      IDE
_Komodo Version?_           10.0
Komodo IDE, version 10.0.0, build 89159, platform win32-x86. Built on Wed May 11 15:04:59 2016.
_Operating System (and version)?_ Windows 7 Professional
### Additional Information

prefs.xml content:

```
<boolean id="debuggerHoverValue">1</boolean>

<boolean id="perlDebugger.RecommendPadWalker">0</boolean>
```

**Comment by Naatan** [comment]
I'm unable to reproduce this, could you share a code sample?

**Comment by jimmeek** [comment]
Code sample attached.But this happens with all Perl code (haven't tried other languages yet).

**Comment by mitchell-as** [comment]
Please use the github interface to attach files. Using e-mail discards the attachments.
