### ISSUE TITLE
Method description dialog does not appear when instantiate class from another class

### ISSUE THREAD

**Issue by kevinlieser** [Komodo/KomodoEdit#1638]
When a class gets instantiated from another class via namespaces the auto-completion works, but the method description dialog not.

## To reproduce:

**Include this as file within a folder in "Preferences -> Languages -> PHP -> PHP Direcotries"**

```
<?php

namespace Test\Core\Controller;

class CoreController  {
	
	/**
	 * @var \Test\Core\Controller\CoreApi
	 * @inject
	 */
	public $api;

}

class CoreApi {

    /**
     * Method Description...
     * 
     * @param integer $param1
     * @return Array
     */
    public function myMethod($param1) {

    }
	
}
```

**Then create a new document with this content and try to auto-complete (let the method description dialog pop up) the `myMethod()` method.**

```
<?php

$test1 = \Test\Core\Controller\CoreApi();
$test1->myMethod();			// auto-completion and method description works

$test2 = \Test\Core\Controller\CoreController();
$test2->api->myMethod();	// auto-completion works, method description dialog not
```

### Expected results

Method description dialog should appear.

### Actual results

Method description dialog don't appear.

### Platform Information

*Komodo Edit or IDE?* 
IDE

*Komodo Version?* 
9.3.2

*Operating System (and version)?* 
Mac OS X 10.11.5

### Additional Information

**Error message:** TypeError: can only concatenate tuple (not list ) to tuple

**Screenshot example:** http://i.imgur.com/LKVMPgJ.jpg

**Comment by Naatan** [comment]
Great writeup! Thanks @kevinlieser!

**Comment by kevinlieser** [comment]
@Naatan you're welcome! Hope that Bug get also fixed in Komodo 9.3. Or hopefully i'll get a diff file to patch my Komodo 9.

**Comment by Naatan** [comment]
It's unlikely that this will make it into a 9.x release, as we do not intend to release any new 9.x versions unless we find something seriously breaking in 9.3. However we will be linking to the commit that fixes this issue here on github so you could use the diff from that to patch your 9.3 install if you so desire. Depending on the severity we could also add it to the 9.3.4 nightly release (which is unlikely to ever be anything but a nightly).

**Comment by kevinlieser** [comment]
Thanks, it works!
