### ISSUE TITLE
Go to Definition is failing with error

### ISSUE THREAD

**Issue by jpshdev** [Komodo/KomodoEdit#164]
When I press CTRL + k on Windows, I get a message in the notifications tab saying, "Ctrl+k was pressed. Awaiting further keys." When I press G it does nothing. Ctrl + left click also does not navigate to the definition, even when it is within the same file. There is nothing in the log file nor in the notifications tab.

**Comment by Naatan** [comment]
The keybinding is `Ctrl+K` then `Ctrl+G`, not `Ctrl+K` then `G`.

Note that go to definition of course will not work when Komodo cannot find the definition
