### ISSUE TITLE
Commando: Ability to go to file at specific line

### ISSUE THREAD

**Issue by Mook-as** [Komodo/KomodoEdit#1641]
### Short Summary
It would be nice if I could get Commando to go to a particular file in a line.  Something like `foo.js:42` should open `foo.js` and jump to line 42.

### Steps to Reproduce
1. Open Commando.
2. Type a file name followed by a colon, then a line number.

### Expected results
Commando finds result, and lets you go to that line.

### Actual results
Commando does not find the file.

### Platform Information
Komodo IDE, version 10.0.0, build 89159, platform linux-x86_64.
Built on Wed May 11 15:27:38 2016.

### Additional Information
I mostly use this with the output of `git grep -n`; so it would be extra nice if it would ignore any trailing colons too (since the output is actually `foo.js:42: <contents of the line>`, and normal selection here copies `foo.js:42:`).

**Comment by Naatan** [comment]
We have an existing enhancement request for this one:

https://github.com/Komodo/KomodoEdit/issues/1059
