### ISSUE TITLE
OSX- Editor blanks out when minimized

### ISSUE THREAD

**Issue by jdforce** [Komodo/KomodoEdit#1643]
### Short Summary
Even though am working on a php script, the editor tab seem to be empty after minimizing it for a while. If it is a single tab, it is very hard to show it again, usually have to close it and reopen the script.
If I have more than one tab open, just by clicking in other tab and clicking on the "disappeared text" tab, the missing text reappears.

This happened in the previous version too. Today installed Komodo edit 10, and it happens again.
Working with PHP scripts. Modified 

### Steps to Reproduce
Open a script. Do some edits. Minimize Komodo edit. After a while, click on the dock to view komodo edit again on maximized or normal view. The text will seem to disappear.

### Expected results
It should be minimized and back without any problem. 

### Actual results
Text is not visible, but the file is open, and vulnerable!

### Platform Information

*Komodo Edit or IDE?*  EDIT
*Komodo Version?*  10.0
*Operating System (and version)?* OSX el capitan 10.11.5  Imac 2013, 8GB Ram

### Additional Information
In the attached screen capture, I was working on a file but it does not appear after minimizing the window and opening it back.
![screen shot 2016-05-31 at 2 06 54 pm](https://cloud.githubusercontent.com/assets/19674384/15690633/4b4e5172-2739-11e6-8865-60fed5e39277.jpg)

 -- eg. Error logs, screenshots, workarounds --
On the new version (10.0), resizing the komodo window makes the text reappear.

**Comment by mitchell-as** [comment]
Duplicate of #564.
