### ISSUE TITLE
php class doesn't get updated while editing

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#1644]
### Short Summary
Open a project with a existing class, and extend the class with a new function. The autocompletion will only show the functions existed when komodo scanned the project on start

### Steps to Reproduce
@mitchell-as created a small [testcase](https://github.com/babobski/testCase01) with 2 commits.
In the first commit I have a class with a single function.
When i now extend the class with a second function, in the other file I get auto completion for only the first created function:
![2016-05-31 23_47_35](https://cloud.githubusercontent.com/assets/3530262/15691896/a4714154-278b-11e6-88d6-1fc8a4a1255b.png)
If i now reboot I get both functions under auto completion:
![2016-05-31 23_50_54](https://cloud.githubusercontent.com/assets/3530262/15691922/ca2ef922-278b-11e6-9366-c80721c30583.png) 
:hash: typo

**Comment by mitchell-as** [comment]
Thanks for going through the trouble of creating a test case, I was able to reproduce the problem.
