### ISSUE TITLE
Install: "please install into an empty directory"

### ISSUE THREAD

**Issue by tekhedd** [Komodo/KomodoEdit#1645]
### Short Summary

Installer won't go past the Custom Setup page, with the error "Please install into an empty directory." It does not matter what directory is chosen.

### Steps to Reproduce

- get a windows 8.1 64 bit system
- run Komodo-IDE-10.0.0-89159.msi
- accept the license agreement

It's probably an interaction with... something? 

Disk Usage correctly reports 256G available on the C drive.

**Comment by tekhedd** [comment]
Having the same problem with the KomodoIDE 9.x installer, so maybe it's something in my environment? I've been installing and uninstalling other dev tools all day without issues though.

**Comment by tekhedd** [comment]
Argh, my bad, system install service seems to be seriously broken. Anything using MSI is failing at this time. Well, I guess that's good news.

**Comment by cgchoffman** [comment]
As a workaround you can force the install using the following in CMD:
`> msiexec /qb /a Komodo-IDE-10.0.0-89159.msi`
Assuming you're in the same directory as the installer.

**Comment by tekhedd** [comment]
Thanks much, workaround didn't work though. Ultimately had to do a system restore. Well, I guess it's time for my annual reinstall of Windows again. *sigh* Wish I didn't have to support Windows at all. Someday.

**Comment by cgchoffman** [comment]
Ahh that's a shame, well have fun re-installing!
