### ISSUE TITLE
Django syntax checking doesn't work

### ISSUE THREAD

**Issue by hobbsd** [Komodo/KomodoEdit#1646]
Django template syntax checking causes a traceback in the syntax panel.

The linting system files, djangoLinter.py and koDjango_UDL_Language.py, appear to be the main culprits.

The djangoLinter.py module expects to be passed (via koDjango_UDL_Language.py) a tempfile of the template and the base directory of the Django project. It then sets `DJANGO_SETTINGS_MODULE` to the basename of that directory path with '.settings' appended. But it doesn't work to assume that the right settings file will be named 'projectdir.settings' (or whatever) -- e.g., mine are often named 'project.settings.dev'.

If `DJANGO_SETTINGS_MODULE` is set in the Komodo project environment, then koDjango_UDL_Language.py passes that value to djangoLinter.py, which is expecting a path, so that won't work (e.g., it ends up using 'project.settings.dev.settings').

If `DJANGO_SETTINGS_MODULE` is **not** set in the project, then koDjango_UDL_Language.py tries to find a nearby directory containing a settings.py file, and it consistently found the wrong directory in my case, which meant that, although djangoLinter.py used an actual settings file, it was one for a different project.

koDjango_UDL_Language.py also has to try to figure out which python interpreter to use by opening subprocesses and trying to import django, which seems error prone and slow. For an error example: the project is Python3; first it will try Python2 falling back to the system installation, because the project's Python2 interpreter is not set; if django is installed in the system Python2, it will go with the wrong interpreter.

If a definitive python interpreter could be set, along with requiring that `DJANGO_SETTINGS_MODULE` be set in the Komodo project env, then these problems go away.

### Platform Information

Komodo Edit, version 10.0.0, build 17209, platform win32-x86.
Built on Thu May 12 00:43:26 2016.

**Comment by mitchell-as** [comment]
Thanks for your detailed ticket and all of the sleuthing you did!

**Comment by mitchell-as** [comment]
With the fix I just committed, as long as your PYTHONPATH (either the environment variable or your Project Preferences > Languages > Python 3 > Additional Python 3 Import Directories) contains the parent directory of your Django app, setting `DJANGO_SETTINGS_MODULE` as you would a normal Django app will work just fine.

For example: if your app is in `/tmp/blog` and `DJANGO_SETTINGS_MODULE=blog.settings.dev`, then PYTHONPATH needs to include `/tmp`.
