### ISSUE TITLE
Less Linter fails on certain files

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1647]
### Short Summary

I just noticed that I don't get linting for *skin/global/icons.less* in the Edit repo.  The IDE repo is fine.  This error has the string "lint" in it so I'm including it but it doesn't seem like it would be the issue though I've never looked at the analytics stuff.
```
[2016-05-31 16:42:45,987] [ERROR] analytics: 
-- EXCEPTION START --
TypeError: proxy is undefined
+ stack
    ko.analytics</this._proxyGa@chrome://analytics/content/analytics.js:418:9
    ko.analytics</this._proxySend@chrome://analytics/content/analytics.js:399:9
    ko.analytics</this.trackPageView@chrome://analytics/content/analytics.js:345:9
    ko.analytics</this.onWindowFocus@chrome://analytics/content/analytics.js:319:9
    ko.analytics</this._eventProxy@chrome://analytics/content/analytics.js:442:13
    openDialogWrap@chrome://komodo/content/komodo.js:616:19
    dialog_alert@chrome://komodo/content/library/dialogs.js:379:1
    lint_jumpToNextLintResult@chrome://komodo/content/lint/lint.js:626:13
    @chrome://komodo/content/library/controller.js line 115 > eval:1:1
    broadcasterController.prototype.doCommand@chrome://komodo/content/library/controller.js:115:1
    command_doCommand@chrome://komodo/content/library/commands.js:239:1
    command_doCommandAsync/<@chrome://komodo/content/library/commands.js:196:13
-- EXCEPTION END --
```

**Comment by Naatan** [comment]
That error seems unrelated. Do you have a LESS linter configured?

**Comment by cgchoffman** [comment]
Not explicitly but Less linting is working fine for the IDE version of the file but it's not working for the Edit version.  The pref for Lang Specific Syntax Checking is set to `Find on Path`.  I forgot to mention that where the number appears on the Syntax Checking dynamic button there is a `?` instead of a number.  Also an alert dialog appears with "Unexpected Internal error checking `icons.less` using Less linter".  I'll try turning on debugging for linting.

**Comment by Naatan** [comment]
First try configuring the less syntax checker explicitly. If that fixes it we know what the problem relates to.

**Comment by cgchoffman** [comment]
Looks like I was confused by differences between Edit and IDE.  I need to refile this with appropriate information.
