### ISSUE TITLE
Don't ask to recover workspace when first starting KX

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1651]
### Short Summary

I just installed Komodo 10 on an old machine that I haven't used in a while.  The computer had been restarted at some point which had killed my Komodo instance.  I hadn't used the computer since.  I immediately installed Komodo 10 and started it.  It then told me that Komodo hadn't shutdown cleanly previously and asked if I wanted recover my last workspace.  This isn't possible so it shouldn't ask.

This is due to a pref that is set at start up that is cleared/changed when Komodo shutsdown so we know we had a clean shutdown.  I can't remember where this is done but workspace.js is what checks for it I believe. 
### Steps to Reproduce

Delete/move your komodo 10 profile
start komodo 9 then kill/crash it
Start Komodo 10
click through first start wizard
### Expected results

Komodo 10 to start without asking to recover
### Actual results

Komodo 10 asks to recover the workspace from komodo 9

**Comment by Naatan** [comment]
Do you know what the name of this pref is? You could simply add it to prefs.xml with the attribute ` nonvital="true"`.

**Comment by cgchoffman** [comment]
It's `komodo_normal_shutdown`.  Looks like this pref must be present in the default prefs so we can't remove it outright though.  eg. [this workspace code will fail if it's not present](https://github.com/Komodo/KomodoIDE/blob/master/src/chrome/komodo/content/workspace.p.js#L165).

We could simply search for where it's accessed and make it safer code by checking>creating it if it's not there.

**Comment by Naatan** [comment]
I didn't say to remove it, you just need to add that attribute I mentioned. That will keep it from being copied when you do a major upgrade.

**Comment by cgchoffman** [comment]
I don't know what `nonvital="true"` does.  I imagine it removes it no?  Or as you said, doesn't copy it.  So it will be missing from the copied over prefs no?

**Comment by Naatan** [comment]
It will be missing from the user prefs.xml, the global prefs.xml would still include it (with the default value).

**Comment by cgchoffman** [comment]
Ahh ok, so globals are merged in if missing?  That totally works then.

**Comment by Naatan** [comment]
Yep, our whole pref system trickles down. If something is defined in the global prefs.xml then it will never be undefined in any of the higher level pref contexts (user, project, file, ..)

**Comment by cgchoffman** [comment]
This isn't happening. Closing.
