### ISSUE TITLE
Word Wrap will not stay activated

### ISSUE THREAD

**Issue by jshrek** [Komodo/KomodoEdit#1656]
### Short Summary
When you turn on Word Wrap from the VIEW menu, and then exit and restart Komodo Edit, Word Wrap is turned off again.

### Steps to Reproduce
Start Komodo Edit, choose VIEW then WORD WRAP and verify it is activated. Shut down Komodo Edit and restart Komodo Edit and notice that WORD WRAP has been deactivated.

### Expected results
Word Wrap should stay in whatever state you set it too, even after shut down and restart of app.

### Actual results
Word Wrap always turns itself off after shut down and restart of app.

### Platform Information
Komodo Edit, version 10.0.0, build 17209
On Mac OSX v10.11.4

**Comment by mitchell-as** [comment]
Hi, the View > Word Wrap option is a file-level option. If you want to enable word wrap globally and have it persist for all files, you'll need to go to Edit > Preferences > Editing > Smart Editing > Wrap Longs Lines By.

**Comment by JabyPearl** [comment]
I don't see Smart Editing under Editor in Komodo Edit v10.2.1

Any one know where I can find it now?

**Comment by Defman21** [comment]
There's an arrow before the editor label in the preferences window. Click on it.

**Comment by JabyPearl** [comment]
Welp. That was easy. Thanks for pointing out the obvious to the oblivious :)

**Comment by alexweissman** [comment]
Why is this option nested under "Use Tab character to complete words"?

![screen shot 2017-09-24 at 6 15 47 pm](https://user-images.githubusercontent.com/5004534/30787363-97945752-a154-11e7-8eda-c61f19580bb3.png)

**Comment by Naatan** [comment]
It's not. It's underneath that sure, but not nested.

**Comment by alexweissman** [comment]
Hmm.  Are the font sizes supposed to be different, though?  That's what gives the impression of nesting.

**Comment by Naatan** [comment]
No, and they aren't for me:

![image](https://user-images.githubusercontent.com/278649/30825738-083db874-a202-11e7-8523-573ac76fba90.png)

I think this might be the color scheme you're using. Is it custom?

Anyway, getting a bit off-topic here. Please open a thread on the forum if you still have issues with this.
