### ISSUE TITLE
Commando file scope fails when project has "added" remote folders

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1657]
### Steps to Reproduce

Create a project
Right click > Add > Existing remote folder
Open Commando > File scope (must go directly to file scope, ie. press 4 in the first scope)
Search for a file in that folder (or any file in your project even if it's not in the "added" folder)

### Expected results

To Find it.

### Actual results

No files are shown at all.

**Comment by cgchoffman** [comment]
Reference: http://forum.komodoide.com/t/how-to-find-file/2809

**Comment by Naatan** [comment]
This is not a bug, it has never worked as it was beyond the scope of the Commando. As were remote files. Maybe we can flesh this out for Komodo 11.

**Comment by cgchoffman** [comment]
But it fails completely.  It doesn't find ANY files if there is an added file, even files in the project root.  That is a bug.

**Comment by Naatan** [comment]
No a bug is something that doesn't work even though it should. This outright shouldnt work because it was not implemented.

**Comment by Naatan** [comment]
-- Figuring this out with Carey in chat, seems I may have missunderstood some parts of the bug --

**Comment by cgchoffman** [comment]
The only thing i missed is that it was a remote folder that broke commando.  This is a bug as commando file scope no longer works at all for any files or folders whether they are remote or local.

**Comment by Naatan** [comment]
Ok, so it seems I was wrong on two counts here:

 - one, this bug is about commando not working at all when existing folders are used (I'm unable to reproduce this so far)
 - two, I in fact DID implement support for existing folders, but downright forgot about it .. -.-

My apologies. Moving on to reproducing this bug. I'm unable to reproduce this on Linux, Carey is trying if it's OS specific.

**Comment by Naatan** [comment]
Issue reproduced, it stems from "Existing Remote Folders". Relevant error:

```
[2016-06-03 12:42:20,352] [ERROR] console-logger: Error: 'scp://Test/home/nathan/Downloads' does not have a local path (2) in chrome://komodo/content/library/uriparse.js:168
Traceback (most recent call last):
  File "chrome://komodo/content/library/uriparse.js", line 168, in 
```

This breaks the files scope completely.

**Comment by stramin** [comment]
Thank you so much for all your work guys!

You are the best!
