### ISSUE TITLE
Unsaved changes not working properly on network drive

### ISSUE THREAD

**Issue by cyberbit** [Komodo/KomodoEdit#1658]
### Short Summary
When a file opened from a network drive has changes performed on it outside of Komodo, Komodo does not update or alert the user of changes. It works fine on a local drive.

### Steps to Reproduce
1. Save a text file with some contents on a network drive.
2. Draft changes to the file inside Komodo and outside Komodo, but only save the changes made outside Komodo.
3. Focus again on the file in Komodo.

### Expected results
Notification is displayed indicating conflicting changes (see attached image).

### Actual results
Nothing happens. This could lead to overwriting the changes made outside of Komodo, as there is no warning that changes were made.

### Platform Information
*Komodo Edit or IDE?* Edit
*Komodo Version?* 10.0.0
*Operating System (and version)?* Windows 7

### Additional Information
Notification working properly on local drive:

![image](https://cloud.githubusercontent.com/assets/7350183/15788284/6151523a-298c-11e6-8d82-df5552bb63b3.png)

Note that it's not an issue of Komodo being unable to access the file. Here's another test I did using the **Show Unsaved Changes** tool on the network drive file:

![image](https://cloud.githubusercontent.com/assets/7350183/15788291/68d93a7c-298c-11e6-87d0-69ec563c7cf9.png)

**Comment by cgchoffman** [comment]
Sounds like you want Preferences > Editor: Confirmation Dialogs: Detect when networked files...

Does that fix the issue?

**Comment by cyberbit** [comment]
Yup. Closing. :P

In Komodo 9, checking files regardless of type of folder was default behavior. I wonder if checking network drives should be on by default to avoid confusion?

**Comment by cgchoffman** [comment]
This is disabled due to an exisiting issue/enhancement request: https://github.com/Komodo/KomodoEdit/issues/70
Komodo core needs to be updated to do the file checking asynchronously otherwise I would agree.
