### ISSUE TITLE
KE9 icon has wrong dimensions (Windows and Linux)

### ISSUE THREAD

**Issue by acidicX** [Komodo/KomodoEdit#166]
The icon (KE9) looks clinched on both Windows (7/8.1 task bar icon) and Linux (cinnamon DE). The icon of 8.5.4 had the right dimensions. See attached screenshot.
![ke-icon](https://cloud.githubusercontent.com/assets/1297454/7120964/68525728-e211-11e4-8627-7fdf95c11988.jpg)

**Comment by Naatan** [comment]
This is by design. The old icon was too drawn out and looked very small compared to other OS icons. The new icon properly uses the icon dimensions.

It only looks clinched to you because you knew what the old icon looked like. I promise it will grow on you within a day :)

**Comment by acidicX** [comment]
Hasn't grown on me since several days but OK... :-)
Don't you think it is irritating when you look at the KE logo on the website? Are you going to change that too?

**Comment by Naatan** [comment]
No, the site logo will stay the same. However we will likely iterate on the application logo.

We don't intend to change the Komodo logo, just make the app logo more in-line with other OS icons.
