### ISSUE TITLE
Arabic Letters In PHP variable

### ISSUE THREAD

**Issue by amohsen1001** [Komodo/KomodoEdit#1660]
### Short Summary

[Image 1](http://backendadmin.com/arabic_komodo.png)
[Image 2](http://backendadmin.com/arabic_komodo_2.png)
[Image 3](http://backendadmin.com/arabic_komodo_3.png)

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by Defman21** [comment]
A reproducible code would be helpful there.

**Comment by mitchell-as** [comment]
There was another ticket with something similar; I cannot find it. Regardless, our text editing component Scintilla does not support right-to-left languages like Arabic very well. There's not much we can do here, sadly.
