### ISSUE TITLE
Chrome debugging not working

### ISSUE THREAD

**Issue by robclancy** [Komodo/KomodoEdit#1664]
### Short Summary
When following the chrome debugging video from the blog post I don't get it working with chrome beta working with embers serve command.

### Steps to Reproduce
- eh... setup like in the video
- have `ember serve` running, which will be on localhost:4200 by default
- have the app go to that url from one of its main files, I have tried on `app.js`

### Expected results
Debugging awesomeness.

### Actual results
INFO:chrome.dbgp.main:Debugging 'http://localhost:4200' over localhost:39096 on Chrome 127.0.0.1:9222
INFO:chrome.dbgp.DBGPClient:Connection to IDE established.
ERROR:chrome.dbgp.DBGPClient:File URI or URL 'http://localhost:4200' unavailable for debugging.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10
*Operating System (and version)?* Arch Linux

### Additional Information

ember-cli 2.5.1
chrome 51.0.2704.63 beta (64-bit)

**Comment by mitchell-as** [comment]
Hi, did you have Komodo start Chrome? Or did you start it yourself? If the latter, you need to start it with the `--remote-debugging-port=9222` switch.

**Comment by robclancy** [comment]
I had fully closed everything when trying before. But will try again to make sure.

**Comment by robclancy** [comment]
So last times I have tried I guess chrome never shut down properly so I got past this issue, had others but investigating more.

**Comment by gareththomasnz** [comment]
they do recommend a separate chrome or chromium just for komodo

**Comment by robclancy** [comment]
I tried multiple different chromes, not sure why you are commenting on a closed issue.

**Comment by cgchoffman** [comment]
Likely for people like himself who came across this issue, perhaps looking for answers (looks like Garth has them though!).  It's a good note to make as we do highly recommend that.  It's all good.
