### ISSUE TITLE
SCSS auto-completions make Komodo lagging

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1666]
### Short Summary

I don't know what causes that, but when I'm working in a SCSS file with a lot of nesting for 30-50 minutes, Komodo starts lagging. Auto-completions appears with delay and inserts with delay. I have to restart Komodo to get my best experience back.

[An example file](https://github.com/melharucos/melharucos.github.io/blob/source/source/stylesheets/site.css.scss)
### Platform Information

_Komodo Edit or IDE?_ IDE
_Komodo Version?_ 10.0.1 nightly
_Operating System (and version)?_ eOS (Linux)
### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by Naatan** [comment]
What makes you think this is due to SCSS and not something else?

**Comment by Defman21** [comment]
Dunno, huh. I just think Komodo is making a very nested tree of selectors. I'll try to reproduce that and open other files to see how it works.

**Comment by Defman21** [comment]
Totally forgot about this one. I reproduced this when I worked on a SCSS file with 30-50 classes/ids/etc. I tried a new file and it worked fine. (without lags)

**Comment by mitchell-as** [comment]
So:

1. When you are in your SCSS file with 30-50 classes/ids/etc., you get the lag.
2. When you create a new SCSS file, you don't get any lag.
3. When you switch back to your original SCSS file with 30-50 classes/ids/etc., you get the lag again.

Is that correct?

**Comment by Naatan** [comment]
@mitchell-as he said 30-50 "minutes".

**Comment by Defman21** [comment]
I said about 30-50 classes as well. I'm not sure it depends on the time I'm working on a file, but on its content. 
@mitchell-as yes.
