### ISSUE TITLE
Find dialog in IDE 9 not auto-filled

### ISSUE THREAD

**Issue by wdbaker54** [Komodo/KomodoEdit#167]
Placing the cursor on a word in the editor formerly auto-filled the find dialog with that word (at least on IDE version 8.5.4) when bringing up the dialog. It no longer does this in Komodo IDE, version 9.0.0, build 87165, platform linux-x86_64. It now requires a manual highlight of the word to auto-fill the find term in the dialog.

**Comment by paulsommer** [comment]
Are you sure this isn't configurable.
I also use Komodo IDE version 8.5.4 on 64 bit Linux, and the behavior is exactly as in your Version 9.
I have to say that I prefer an empty search field as it allows me to insert the clipboard content easily (either with middle click or with Ctrl-v). If I want to search the current word a double click for highlighting is not too much of a hassle (except off cause when you don't want to change between keyboard and mouse).
Maybe a configurable behavior would be the best (as requested in ticket #187 - search&replace dialog)

**Comment by wdbaker54** [comment]
It would be nice if the configuration is there for both types of behaviors but I don't recall where it might have been for 8.5.4 since I don't remember setting it. I can see your desire to have a clean find box but my habits are actually not to move from the keyboard to the mouse if I don't have to and having the word under the cursor be the default search term is nice since it is also highlighted in the find dialog to allow changing without any special effort (ctrl-v or middle click does over-write what is there).

**Comment by wdbaker54** [comment]
I think I can close this because I rolled-my-own find word under cursor macro (this is my first macro although I got a start from an old macro I saw written by Todd Whiteman). Here is the code that I eventually attached to my ctrl-f key:

// Highlight the word under the cursor.
var scimoz = ko.views.manager.currentView.scimoz;
var start = scimoz.wordStartPosition(scimoz.currentPos, true);
var end = scimoz.wordEndPosition(scimoz.currentPos, true);
scimoz.anchor = start;
scimoz.currentPos = end;
selection = scimoz.selText;
if (selection && selection.length > 0) {
    ko.launch.find(selection);
}
else {
    ko.launch.find();
}`

I guess you can teach an old dog new tricks - this shows how flexible Komodo is and I can't wait to try doing more macros now that I have started.
