### ISSUE TITLE
Can't change SCC keybindings

### ISSUE THREAD

**Issue by aaroncampbell** [Komodo/KomodoEdit#1670]
### Short Summary
In Komodo X the `CTRL+K,D` keyboard binding is set to something different. It used diff the current file. Now it diffs for the whole repo, which is far less useful and also broke for nested repos (see #1669). Unfortunately I can't restore the old behavior. When I check to see what the key binding is set to, it says `cmd_SCCdiff` but there doesn't seem to be the option to change any SCC bindings.

### Platform Information
Komodo IDE, version 10.0.0, build 89159, platform linux-x86_64
Specifically running Ubuntu 16.04

**Comment by cgchoffman** [comment]
You can change specific bindings under in Preferences > Keybindings.  Or you can choose the Legacy binding scheme.

**Comment by aaroncampbell** [comment]
Did you check to make sure you can change THIS keybinding? Because I can't. It's simply not listed there.

**Comment by cgchoffman** [comment]
Search `Source code control: compare`.   I see the issue though.  The "Key Sequence Currently Used By" field is telling you the "under the hood" command name, not the user friendly name and description.

**Comment by cgchoffman** [comment]
Sorry, too much needs to be change in this report to use it for THAT issue.  I'm closing this and filing a new one to reflect the issue I mentioned.

**Comment by aaroncampbell** [comment]
Yep, that was my bad. I tried to add the binding to find what it was bound to. When I saw `cmd_SCCdiff` I tried searching for `cmd`, `SCC`, and `diff` in the list of commands...none of which showed what I needed. Seems to work as expected now. Thanks.

**Comment by cgchoffman** [comment]
No problem.  New ticket here: https://github.com/Komodo/KomodoEdit/issues/1671
