### ISSUE TITLE
Code Intelligence Fails with Multiple Definitions of Same Function

### ISSUE THREAD

**Issue by aaroncampbell** [Komodo/KomodoEdit#1672]
### Short Summary
I work on a lot of WordPress projects. There are certain functions that exist in multiple places, usually where one instance is a stub. For example, `add_filter` exists as a stub with no parameters in [wp-admin/includes/noop.php](https://core.trac.wordpress.org/browser/tags/4.5.2/src/wp-admin/includes/noop.php#L16) (each function here has an `@ignore` comment) and the actual (oft used) function is in [wp-includes/plugin.php](https://core.trac.wordpress.org/browser/tags/4.5.2/src/wp-includes/plugin.php#L103). When you type `add_filter(` you get no parameters offered.

There are quite a few more functions that suffer from this. Including many that are in [wp-includes/pluggable.php](https://core.trac.wordpress.org/browser/tags/4.5.2/src/wp-includes/pluggable.php) which aren't overridden in core but are often overridden in a given project (these are each wrapped in a `function_exists` check and loaded later than other files. 

### Steps to Reproduce
- Start a WordPress project
- Open a file and type `add_filter(`

### Expected results
![code-intelligence-correct-add_filter](https://cloud.githubusercontent.com/assets/802412/15835800/44929524-2bf7-11e6-801d-08ac4d70915a.png)

### Actual results
![code-intelligence-incorrect-add_filter](https://cloud.githubusercontent.com/assets/802412/15835799/44928a2a-2bf7-11e6-9e03-1cb3c73fb51e.png)

### Platform Information
Komodo IDE, version 10.0.0, build 89159, platform linux-x86_64
Specifically running Ubuntu 16.04

**Comment by aaroncampbell** [comment]
I'm sure there are other projects that suffer from the same kind of issues, but WordPress is what I work in every day (and is wildly popular) so it's what I used as an example.

**Comment by mitchell-as** [comment]
Thanks for the report. I'm going to have to investigate whether or not this is feasible in a reasonable amount of time. The milestone is for planning purposes.

**Comment by seattledeveloper** [comment]
I have another use case that might be helpful to add.

I have a project that has customized session management.  There are several login locations for different classes of users, each with different PHP files with slightly different versions of functions with the same name, each file located relative to it's own login area.

It would be nice if code intelligence could work based on the files actually included within the file being edited, but this might be way too big an undertaking.  I'm not saying or implying that I need this feature for myself, just wanted to add another example.

Cheers!

**Comment by mitchell-as** [comment]
I believe the proper course of action here is to ignore storing functions with the "@ignore" tag.

**Comment by Naatan** [comment]
@mitchell-as would Wordpress' functions fall under that new logic?

**Comment by mitchell-as** [comment]
Yeah, my conclusion comes from analyzing a wordpress project.

**Comment by Naatan** [comment]
Perfect :)
