### ISSUE TITLE
Unclear keyboard shortcut for "Insert Newline (continue comments)"

### ISSUE THREAD

**Issue by cyberbit** [Komodo/KomodoEdit#1673]
### Short Summary
Komodo preferences (Key Bindings) indicate that the shortcut for this command is `Shift, +, Return`. This is the only command in the Default scheme that is structured in this way. Plus, I'm pretty sure it's impossible to trigger legitimately, as the <kbd>+</kbd> keystroke is absorbed by the editor.

Shouldn't the command be `Shift+Return`? No other command is bound to this.

### Platform Information

*Komodo Edit or IDE?* Edit
*Komodo Version?* 10.0.0
*Operating System (and version)?* Windows 7

### Additional Information
![image](https://cloud.githubusercontent.com/assets/7350183/15835819/65777e76-2bf7-11e6-9c33-93f6e6f274c4.png)

**Comment by cgchoffman** [comment]
I could have sworn you already filed this bug.  This is fixed in the latest nightly and will be included in 10.0.1 when it is released.  You are correct on your guess as to what the binding is.

**Comment by cyberbit** [comment]
Sweet! I guess I'll just manually change it for now. :D

**Comment by cgchoffman** [comment]
Ok, you can use the nightly too if you're interested: http://downloads.activestate.com/Komodo/nightly/komodoedit/

**Comment by cyberbit** [comment]
I'll probably do that for my home machine. Found this on my work machine, I think I'll stick to stable there, haha!

**Comment by cgchoffman** [comment]
#bettersafethansorry
