### ISSUE TITLE
Can't copy from colour picker

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1674]
### Short Summary

I just tried to copy a hex colour from the colour picker and neither `Ctrl + C` worked nor does it work with right clicking for the context menu.

**Comment by Naatan** [comment]
Works fine for me. Are you sure you didnt install the RGBA color picker?

**Comment by cgchoffman** [comment]
I am 100% sure that I installed RGBA and forgot...

**Comment by Defman21** [comment]
@cgchoffman fyi babobski wants to fix that https://github.com/babobski/RGBA-Colorpicker/issues/3
