### ISSUE TITLE
KomodoEdit 10 maximizes when switching computers with synergy

### ISSUE THREAD

**Issue by VeNoMouS** [Komodo/KomodoEdit#1675]
### Short Summary

On linux (debian), If i have another program on screen and change computers via synergy , KomodoEdit 10 maximizes to the foreground. 

Versions 8 and 9 do not do this, this was introduced in 10.

### Steps to Reproduce

Move from one pc to another pc via synergy.

### Expected results

It should stay in the state that it is.

### Actual results

Komodo because program on foreground.

### Platform Information

*Komodo Edit or IDE?*  Edit
*Komodo Version?* 10 and 10.0.1-17238
*Operating System (and version)?* Linux - Debian 8.4 64bit

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by VeNoMouS** [comment]
Also does it , if im in chrome on one screen, and ctrl+shift+i in for develoepr tools, chrome gets chucked to the background and komodoedit becomes the foreground..

**Comment by Naatan** [comment]
Try Preferences > Appearance > Use native window borders.

Let us know if you can reproduce this issue without the use of Synergy.

**Comment by VeNoMouS** [comment]
Confirmed that did indeed fix it, 2 things how ever, when switching to native borders, the bar at the top turns from blue to white.... how ever, turning off native borders again back to how it was before, then switching computers with synergy the issue no longer occurs....

**Comment by Naatan** [comment]
Try restarting Komodo after switching the pref, it might not fully switch all parts of the UI.
