### ISSUE TITLE
Run selected single line or multiple lines (block)?

### ISSUE THREAD

**Issue by quxiaojian** [Komodo/KomodoEdit#1676]
### Short Summary
I want to know if Komodo Edit could execute selected single line or multiple lines (block).

### Platform Information

*Komodo Edit or IDE?* 
Komodo Edit
*Komodo Version?* 
9.3
*Operating System (and version)?* 
Windows
### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by mitchell-as** [comment]
No, that is an IDE-only feature. http://komodoide.com/komodo-edit/. Please use the forums for other general questions instead of our bug tracker. http://forum.komodoide.com
