### ISSUE TITLE
CoffeeScript does not recognize #{}

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1678]
### Short Summary

```coffee
variable = 1
console.log "test #{variable}"
```

Komodo does not highlight `variable` inside a string as identifier, so `#{}` does nothing there.

```coffee
console.log "hello #{["test", ["123"]}"
```

Komodo highlights `["test", ["123"]` not properly:

![Imgur](http://i.imgur.com/szrd89D.png)

**Comment by mitchell-as** [comment]
Thanks. Scintilla's CoffeeScript lexer doesn't support string interpolation yet.

**Comment by Naatan** [comment]
Note this works for Ruby, which has veeery similar syntax.

**Comment by Defman21** [comment]
I sure CoffeeScript supports multi-line strings, so #1677 :)

**Comment by Defman21** [comment]
Thank you Mitchell!

**Comment by mitchell-as** [comment]
Note: Scintilla patch submitted upstream.
