### ISSUE TITLE
Komodo IDE Exception

### ISSUE THREAD

**Issue by vdsass** [Komodo/KomodoEdit#1679]
### Short Summary
Attempted to 'save' file.
File is 'large' .xml.  See issues discussed regarding file size: http://forum.komodoide.com/t/xml-file-opens-as-txt-file/2813

### Expected results
Saved file.

### Actual results
Exception

### Platform Information
*Komodo IDE?* 
*Komodo Version?* See below
*Operating System (and version)?*  Windows 7 Enterprise N Service Pack 1

### Additional Information
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIDocument.isEncodable]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: vieweditor :: _validateEncoding :: line 1405"  data: no]

Exception: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIDocument.isEncodable]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: vieweditor :: _validateEncoding :: line 1405"  data: no]

Traceback:
_validateEncoding@vieweditor:1405:16
save@vieweditor:1502:21
viewManager.prototype.do_cmd_save@chrome://komodo/content/views.js:1907:4
xtk.Controller.prototype.doCommand@chrome://xtk/content/controller.js:61:8
command_doCommand@chrome://komodo/content/library/commands.js:239:0
command_doCommandAsync@chrome://komodo/content/library/commands.js:191:0
@chrome://komodo/content/keybindings/keybindings.js line 2562 > eval:1:0
this.Manager.prototype.evalCommand@chrome://komodo/content/keybindings/keybindings.js:2562:22
this.Manager.prototype.keypressHandler@chrome://komodo/content/keybindings/keybindings.js:2733:16
gKeyHandler@chrome://komodo/content/keybindings/keybindings.js:2617:4

Komodo IDE, version 10.0.0, build 89159.
Built on Wed May 11 15:04:59 2016.

 -- eg. Error logs, screenshots, workarounds --

**Comment by Naatan** [comment]
Can you reproduce the issue after restarting Komodo?

**Comment by vdsass** [comment]
I re-started, but haven't seen the same behavior so far today. I had a bunch of find windows open and find started to act weird. That's when I tried to save. I'll keep track of my actions and get back to you if/when it happens. The large xml file will be a problem for me using Komodo on that file. The owner will not change the way the file is used; it will only get larger.

**Comment by Naatan** [comment]
Let me know if you can reproduce the issue. Unfortunately there isn't anything we can do here unless there is a clear trail.
