### ISSUE TITLE
svn commit doesn't work when a password is required

### ISSUE THREAD

**Issue by sgeard** [Komodo/KomodoEdit#1680]
### Short Summary
I tried to commit a file I'd changed but just got an error message because it doesn't seem able to request a password.

### Steps to Reproduce
Change a file and try to commit the change to svn

### Expected results
Password prompt followed by a successful commit

### Actual results
Failure:
/usr/bin/svn commit
    file:///home/simon/projects/chess/chess.tcl
SVNLibError(u"Error running '/usr/bin/svn --encoding utf-8 --file /tmp/tmpeeCqIW.svn commit chess.tcl', it did not exit properly: rv=1, cwd=u'/home/simon/projects/chess'\n\nStderr:\nsvn: E170001: Commit failed (details follow):\nsvn: E170001: Can't get password\n",)

### Platform Information
Komodo IDE, version 10.0.0, build 89159, platform linux-x86_64

### Additional Information
If I run it from the command line there is no problem:

[simon@localhost chess]$ svn commit -m 'Fix for king moves' chess.tcl
Authentication realm: <svn://persephone:3690> home
Password for 'simon': *******

Sending        chess.tcl
Transmitting file data .
Committed revision 590.

**Comment by Naatan** [comment]
Komodo does not support password prompts for VCS, you have to set up your SVN client with a saved password.

See for example: http://stackoverflow.com/questions/2899209/how-to-save-password-when-using-subversion-from-the-console
