### ISSUE TITLE
PHP CodeIntel: Variable Assignment in Control Structure "Header" Not Supported

### ISSUE THREAD

**Issue by mitchell-as** [Komodo/KomodoEdit#1682]
### Short Summary

```
if ($var = something) {
  $|
}
```
does not show `$var` in the autocompletion list.

### Steps to Reproduce

See above.

### Expected results

`$var` in the autocompletion list.

### Actual results

It's not there.

### Platform Information

*Komodo Edit or IDE?*  Both
*Komodo Version?* 10
*Operating System (and version)?* Any.

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by Naatan** [comment]
Would this also be an issue for:

```
if (true) {
  $var = 'foo';
  $|
}
```

?

**Comment by mitchell-as** [comment]
What you did is fine. I've updated the title to be more explicit.
