### ISSUE TITLE
Version Control:  Commit Changes dialog populates with other windows contents

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1686]
### Short Summary

I have two Komodo Windows open
I have the *Commit Changes* tab in the *Version Control* widget open in both
While I'm working eventually the OTHER window (ie. not the one I'm working in) will populate *Commit Changes* with my working windows file state information.

In my case I was working on Edit in one window and IDE in the other.  I ended up making a commit on IDE from the Edit project and didn't notice because i was editing the same file in each project.  I don't know how to reproduce this EXACTLY but if you work with the setup described above you should eventually hit the issue.

I've attached a screenshot to try and show what this looks like.  Yes the root directories in Places for each window were in the correct repo:
![capture](https://cloud.githubusercontent.com/assets/655154/15914949/18ddadb6-2d9a-11e6-88ab-14d419503567.PNG)

**Comment by Naatan** [comment]
Can you consistently reproduce this? The context of this screenshot could easily just be correlation, not causation.

**Comment by cgchoffman** [comment]
> The context of this screenshot could easily just be correlation, not causation.

The screenshot is just pointing out the resulting bug and what it looks like.  I don't know what is causing it.

Yes this is consistently reproducible following the steps I outlined above.  I'll try to clarify:
1. Start Komodo and open a Project that has git, wait until it shows it's status in the Commit Changes
2. open another Komodo window that has a git repo.  Wait until it updates it's own status in the Commit Changes tab.
3. Watch the first windows Commit Changes tab.  It should eventually update with the second windows state.

**Comment by Naatan** [comment]
Alright, thanks @cgchoffman.
