### ISSUE TITLE
Git changes are not updated in komodo

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#1687]
### Short Summary
When I do a git pull (commandline) to get the changed files, Komodo is coloring these files blue(changed). This is incorrect the should not be colored as the file is up to date with repo

### Steps to Reproduce
Open a project with remote changes.

> git fetch
> git pull

These files are now colored blue while there up to date with the remote.

### Expected results
That the files keep scc-ok color as the file now is up to date with the remote

### Actual results
Te changed files( but up to date with remote ) are colored blue (changed)

### Platform Information
Komodo X

### Additional Information
When I now open a file all the colors are restored to the actual state the have (scc-ok)

**Comment by Naatan** [comment]
I am not seeing this. Does opening one and right clicking the tab, then hitting "Refresh Status" make a difference?

**Comment by babobski** [comment]
In komodo 9, if there are changes in the directory the directory is updated.
In komodo 10 it just doesn't.

Just created a readme on git and pulled it to my local branch. But it is not showing up in komodo:
![2016-06-17 10_38_10](https://cloud.githubusercontent.com/assets/3530262/16145181/b6b44138-3477-11e6-808c-3f999f7106f1.jpg)
If I look in my file system the readme is there:
![2016-06-17 10_38_34](https://cloud.githubusercontent.com/assets/3530262/16145234/e13446ba-3477-11e6-9ff8-dd862aa1389e.jpg)
Only when I use the **refresh view**, the changes are shown

note: I'm using commandline for git, Komodo 9 updated these changes are updated simultaneously, in 10 not

**Comment by Naatan** [comment]
Do you have `Prefs > Editor > Confirmation Dialogs > Detect when files are changed .. ` checked?

**Comment by babobski** [comment]
@Naatan  ah that's it, disabled it a while ago at work, was having issues that komodo freezes, because we had ftp problems. Will test it tomorrow, we have found out what was causing it, so the option can be enabled again.

**Comment by tonyattwood** [comment]
Hi,

I've  visited an techno exhibition lately, that was so  awesome! Just take a look at those things  <http://expert.toneychoi.com/e4ysym>

tony.attwood@ntlworld.com
