### ISSUE TITLE
Add tooltip to spelling errors

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1688]
The fact that it doesnt have tooltips conflicts with the UX for linting errors/warnings, which are very similar. We should at least show something like: "Invalid spelling, right click to resolve".

**Comment by mitchell-as** [comment]
Note to self: Ideally I'd be able to listen for the 'editor_get_tooltiptext' event (emitted by `views-editor.p.xml`) from the spellcheck module. Figure out how to do this.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoIDE/commit/b5db6c701688edb06ce15041116ff1a76b592aaf
