### ISSUE TITLE
"Find in Files" target directories seem to change without user requesting it

### ISSUE THREAD

**Issue by hayne** [Komodo/KomodoEdit#1689]
### Short Summary
The "Find in Files" feature searches in the target directories specified in the bottom panel (the Find panel) in the field labelled "Directories".
I have this field set to the root of my code folders (the top-level folder) so that the search is applied to all of my code.
However sometimes the directory specified in this field gets changed (to some sub-folder) without any explicit request on my part. I don't know what triggers this change - I only notice it when the search fails to find things (because it is searching the wrong folder).

### Steps to Reproduce
Do lots of edits on lots of files in various folders, occasionally doing a Find in Files via the keyboard shortcut. Usually the FindAll works, but sometimes it doesn't and then I see that the target directory has been changed (I didn't ask for it to be changed).

### Expected results
The target directories field for Find in Files should never change unless I explicitly change it.

### Actual results
Sometimes the target directories field for Find in Files seems to change on its own.

### Platform Information
Komodo Edit 10.0.0
OS X 10.9.5

**Comment by Naatan** [comment]
What is it changing to?

**Comment by hayne** [comment]
The directories field is getting changed to some sub-folder.
E.g. my folder hierarchy is like this:
folderA
    folderB
    folderC
    folderD

I have the directories set to folderA,
but sometimes I notice it has changed on its own to folderB or some other sub-folder.

**Comment by Naatan** [comment]
It wouldn't just change by itself, more likely you are triggering a find in a specific context which you don't realize yourself.

How are you triggering the find frame?

**Comment by hayne** [comment]
I almost always use the keyboard shortcut:
Command-Shift-F

Let me put a question to you:
What user-interface mechanisms might change this "directories" field (in the Find in Files panel) aside from directly interacting with that field?

**Comment by Naatan** [comment]
There are several mechanisms that could change it, to name a few:

 * Ctrl+clicking on a breadcrumb folder (opens search in this folder)
 * Right clicking on a folder > Find..
 * Opening the find frame for a different context (eg. Project)
 * Running replace on a different context

Any of these seem familiar to you?

**Comment by hayne** [comment]
None of those are things that I have done - at least not on purpose.
The Ctrl-clicking on a breadcrumb folder is something that I might conceivable do accidentally
- especially since Ctrl-click on OS X is (supposed to be) equivalent to a right-click (to bring up the contextual menu). But it seems unlikely that I've done this accidentally as often as I've seen this problem.

**Comment by hayne** [comment]
I think I've found the cause of the problem.
It isn't Ctrl-click, it's Command-click. 
(Meta-click in Komodo parlance)

If I Command-click on a breadcrumb folder, the search target folder changes to that folder.
This is not a desirable effect as far as I'm concerned, especially since there is no (apparent) feedback that I have specified that folder as a target, and the Find in Files panel is far away from the breadcrumbs.

So I guess I shall look to find out how to disable this keyboard shortcut (Command-click on breadcrumb) so it doesn't do anything.

**Comment by hayne** [comment]
I don't see anything in the Preferences that will allow me to disable the effect of Command-click on a breadcrumb folder.

By the way, in the Places section of Preferences, it shows the following error message:

XML Parsing Error: XML or text declaration not at start of entity
Location: chrome://komodo-places/content/pref_places.xul
Line Number 2, Column 1:<?xml version="1.0"?>
^

**Comment by Naatan** [comment]
> If I Command-click on a breadcrumb folder, the search target folder changes to that folder.
> This is not a desirable effect as far as I'm concerned, especially since there is no (apparent) feedback that I have specified that folder as a target, and the Find in Files panel is far away from the breadcrumbs.

> So I guess I shall look to find out how to disable this keyboard shortcut (Command-click on breadcrumb) so it doesn't do anything.

This is correct, ctrl+click would become command+click on OSX.

Why are you Command clicking on a breadcrumb if you do not want to start a search on it? Simply do not command click then?

**Comment by Naatan** [comment]
> By the way, in the Places section of Preferences, it shows the following error message:

> XML Parsing Error: XML or text declaration not at start of entity
> Location: chrome://komodo-places/content/pref_places.xul
> Line Number 2, Column 1:<?xml version="1.0"?>

This is fixed in the latest nightly and will soon be available in a stable update. There is no option to disable command click on breadcrumbs, as the fix is to simply not command click (there is no other reason why you would do this).

**Comment by hayne** [comment]
I'll try not to do inadvertent Command-clicks.

Probably the reason why I sometimes Command-click on these is that I am switching between Windows in VirtualPC where Command-click does a right-click and OS X. 

But my feedback above about there being no feedback for the effect of a Command-click still stands.
It would be nice to have a preference to avoid this effect.

I suspect that the basis of my problem is that the Find in Files feature is too flexible for my needs.
I would much prefer that the current functionality be moved to an "Advanced Find ..." and have the Find in Files always search the same folder (unless I change it explicitly). 
I'm always doing one of 2 things:
- search in current file
- search across all files
Of course part of my problem is perhaps also that I have not defined a project. When I say "all files", I mean all files in my "project" - where I have used scare quotes to indicate that a project for me is just a folder hierarchy.

**Comment by Naatan** [comment]
The popup menu when you click a breadcrumb explicitly states the shortcut. Additionally the fact that command clicking on a breadcrumb brings up the find frame is in and of itself feedback. I don't believe this merits any further feedback. 

Appreciate your bringing this to us. I'll keep it in mind should we come across it again, but for now I don't believe there is anything actionable here.

**Comment by hayne** [comment]
> The popup menu when you click a breadcrumb explicitly states the shortcut. Additionally the fact that command clicking on a breadcrumb brings up the find frame is in and of itself feedback. I don't believe this merits any further feedback.

Ah - there's the *real* problem:
I hadn't noticed that when I Command-click on a breadcrumb folder, it opens the Find in Files panel.
Again, the fact that the panel is at the bottom, far away from the breadcrumbs is part of the problem.

And I had never looked all the way to the end of the popup menu that you get when clicking on a breadcrumb - for many of my folders, this menu is as high as the screen. So I never saw the shortcuts that are listed there.

**Comment by Naatan** [comment]
That's fair. I think most people would notice a new part of the UI appearing though. Is your resolution that high that you simply don't see it?

**Comment by hayne** [comment]
I do see it, but the whole window flashes (the part where my source code is) when I Command-click so other changes are less evident.

**Comment by cgchoffman** [comment]
Note: If it's already open it doesn't reopen, it just changes the *Directories* field.

I'm still confused why you would be clicking around holding Cmd though.  Is this a normal thing on OSX?  Or is there an expected OSX-style result?

**Comment by Naatan** [comment]
> Probably the reason why I sometimes Command-click on these is that I am switching between Windows in VirtualPC where Command-click does a right-click and OS X.

It's a fair point but also one that won't apply to the average user.

**Comment by hayne** [comment]
Command-clicking is not something I'm doing intentionally.
I mentioned above that one hypothesis is that since I am switching back and forth between Windows on VirtualBox and OS X, I might be doing inadvertent Command-clicks since Command-click is what VirtualBox is configured to use to get a right-click in Windows.

**Comment by hayne** [comment]
I agree it's not a concern for the average user
and now that I know what is doing this, I am much less likely to trigger it.
Perhaps breadcrumbs should be "off" by default so that when the user turns them on (in Preferences), you can explain all the capabilities they provide. For the first many days of use of version 10, I thought they were merely a visual indication of the path.

**Comment by Naatan** [comment]
Well they are that, plus more. Turning them off just would make them less discoverable to the majority of users.
