### ISSUE TITLE
KomodoEdit hangs during a restart

### ISSUE THREAD

**Issue by laurentj** [Komodo/KomodoEdit#169]
Komodo Edit, version 9.0.0, build 15707, platform linux-x86_64.

When Komodo is killed unexpectedely (for example, because a crash of Komodo, or because a crash of the OS, or because the laptop has been shuting down because low battery etc...), when we restart it, Komodo asks if  we want it reopen all windows and projects.

If I choose "yes", Komodo opens the first window successfully, but for the second window (when I opened several windows), it fails : the window is opened, but files are not opened, places is not drawn, the window is not really drawn, and Komodo hangs here : 100% cpu usage etc..

It worked in Komodo 8 : all windows were opened as before the crash.

**Comment by Naatan** [comment]
@cgchoffman I think this may be the codeintel issue you were working on, is there already a bug on this?

**Comment by cgchoffman** [comment]
Yep, this is issue #171.  Closing this one as I included my investigation notes in the other ticket.
