### ISSUE TITLE
Breadcrumb folder contents empty for remote files

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1690]
### Short Summary

Breadcrumb listings are empty for remote folders.

### Steps to Reproduce

 * Open remote file
 * Click on breadcrumb folder

### Expected results

 * File listing

### Actual results

 * No file listing

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by tonyattwood** [comment]
Hi,

Surprise! I've got a new hairstyle! It's so cool! Just take a look <http://excellent.lilbobby.com/e4rxhuam>

Best regards, tony.attwood@ntlworld.com
