### ISSUE TITLE
preference to make current file more evident

### ISSUE THREAD

**Issue by hayne** [Komodo/KomodoEdit#1691]
### Short Summary
The currently displayed file (in the editor) is indicated by a grey line below the file name at the top of the window. See attached screenshot.
This grey line is not sufficiently visually emphatic to make it easy to see at a glance what the name of the current file is. I.e. to see at a glance which file is displayed.

As you will see in the screenshot, the screen is very visually busy (lots of stuff) so the grey underline is not the most prominent thing.

### Expected results
Would like a preference to configure the indicator for current file so that it is more visually evident.

### Platform Information
Komodo Edit 10.0.0
OS X 10.9.5

# ScreenShot
<img width="812" alt="screen shot 2016-06-09 at 6 05 26 pm" src="https://cloud.githubusercontent.com/assets/712769/15948370/6f321d62-2e6e-11e6-8516-604c90fd32fe.png">

**Comment by cgchoffman** [comment]
I think you're looking for Prefs > Color Schemes.  In the Color Scheme Editor select the "Interface" field in the dropdown on the left.  There you can change `secondary special`.  We're working on making those fields more clear.

**Comment by hayne** [comment]
Hmm - I used the Color Scheme Editor and changed the 'secondary special' to pure blue (0, 0, 255) and pressed Apply and Apply to All, and then Closed the Color Scheme Editor.
Now while I do have the desired bright blue line under the current filename,
the whole of Komodo Edit's interface has changed back to the default black (or very dark) colour scheme.
Not what I wanted and it is unclear how to undo this change.
I note that the Color Scheme Editor was correctly showing the name of my (modified a few weeks ago) custom colour scheme. It seems like maybe the Color Scheme Editor did not correctly import the values of my current colour scheme.

**Comment by hayne** [comment]
BTW, my modified colour scheme was based on AtelierForestLight

**Comment by Defman21** [comment]
@hayne if you lost your scheme completely - you can use my own and tweak it. It's based on base16 colors of atelier forest.
http://defman.me/schemes/forest/
