### ISSUE TITLE
Python is running 95% CPU while Komodo X is open

### ISSUE THREAD

**Issue by st-bobb** [Komodo/KomodoEdit#1692]
### Short Summary
Looks like the scanning of files is taking too much CPU.
I have a MAgento PHP project. There are a lot of files but this should not hog my CPU

### Steps to Reproduce
Open Komodo X on an Mac running Yosemite
open a terminal and type top :)

### Expected results
CPU used when needed

### Actual results

CPU at 95% all the time

### Platform Information

*Komodo Edit or IDE?*  IDE 
*Komodo Version?* X
*Operating System (and version)?* 
Mac 10.10.5

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by mitchell-as** [comment]
The OSX kernel is responsible for scheduling CPU tasks and load. We don't have any control over that. Does your CPU usage go down after the code scan completes?

**Comment by st-bobb** [comment]
It doesn't seem to end the scan of files. Magento does have about 15,000 files.
I believe it eventually crashes Komodo. If it does next time I will attach the crash report.

**Comment by Naatan** [comment]
The fact that Komodo uses so much CPU during a scan is an issue though, @mitchell-as could we use something like [this](https://docs.python.org/2/library/resource.html)?

**Comment by st-bobb** [comment]
During the scan komodo is using about 15-45% CPU but Python remains at 95% even after the scan finishes. Komodo drops right down. So it looks like a Python process gets triggered but cannot complete itself.

**Comment by mitchell-as** [comment]
The python process is our code intelligence. The fact that it is still at high CPU means it's still scanning your code.

@Naatan No we will not be able to use that easily because it's a CPU time limit -- after using X seconds of CPU time a kill signal will be sent and our codeintel process would have to handle said signal and figure out how to start up again.

@st-bobb You can limit the depth of our code intelligence by changing Edit > Preferences > Code Intelligence > Code Scanning > Maximum Directory Depth

**Comment by st-bobb** [comment]
And here is the crash report. I was not monitoring CPU at the time. I xxx'd out a couple of things in case they were specific to this machine. office security :)

AdapterDeviceID: 0x d26
AdapterDriverVersion: 
AdapterVendorID: 0x8086
Add-ons: analytics%40activestate.com:1.0.0,breadcrumbs%40activestate.com:1.0,commando%40activestate.com:1.0,console%40activestate.com:1.0,domviewer%40ActiveState.com:1.0.0,fontawesome%40activestate.com:1.0,httpinspector%40activestate.com:1.0.0,icomoon%40activestate.com:1.0,industrial%40openoffice.org:1.0.0,koextgen%40activestate.com:0.2,komob%40activestate.com:0.4.3,markdown-viewer%40activestate.com:0.3,openfiles%40activestate.com:1.0,perldevkit%40ActiveState.com:8.0,profiler%40ActiveState.com:0.1,railstools%40activestate.com:0.3.1,tcldevkit%40ActiveState.com:5.0,bazaar%40ActiveState.com:1.0,editorconfig%40activestate.com:1.0.1,git%40ActiveState.com:1.0,golang%40activestate.com:1.3.3,mercurial%40ActiveState.com:1.0,publishing%40ActiveState.com:1.0,refactoring%40activestate.com:0.1,trackchanges%40activestate.com:1.0,zendframework%40ActiveState.com:0.8,dbexplorer%40ActiveState.com:1.0,klint%40dafizilla.sourceforge.net:1.4.0,check-compatibility%40dactyl.googlecode.com:1.3.1,elastic-tabstops%40activestate.com:0.1,focusmode%40activestate.com:1.0.2,komodospellchecker%40ActiveState.com:1.0,kopy%40activestate.com:1.0,runinline%40activestate.com:1.0,scope-bookmarks%40activestate.com:1.0,scope-combined%40activestate.com:1.0,scope-commands%40activestate.com:1.0,scope-openfiles%40activestate.com:1.0,scope-packages%40activestate.com:1.0,scope-sections%40activestate.com:1.0,scope-shell-bower%40activestate.com:1.0,scope-shell-composer%40activestate.com:1.0,scope-shell-cpanm%40activestate.com:1.0,scope-shell-docker%40activestate.com:1.0,scope-shell-gem%40activestate.com:1.0,scope-shell-npm%40activestate.com:1.0,scope-shell-pip%40activestate.com:1.0,scope-shell-ppm%40activestate.com:1.0,scope-shell-pypm%40activestate.com:1.0,scope-shell-vagrant%40activestate.com:1.0,scope-shell%40activestate.com:1.0,scope-tools%40activestate.com:1.0,scope-docs%40activestate.com:1.0,scope-files%40activestate.com:1.0,lintresults%40activestate.com:1.0,scope-shell-cordova%40activestate.com:1.0,scope-shell-grunt%40activestate.com:1.0,scope-shell-gulp%40activestate.com:1.0,scope-shell-phonegap%40activestate.com:1.0
BuildID: 89159
CrashTime: 1465835468
EMCheckCompatibility: false
EventLoopNestingLevel: 1
FramePoisonBase: 7ffffffff0dea000
FramePoisonSize: 4096
InstallTime: 1465426905
Notes: AdapterVendorID: 0x8086, AdapterDeviceID: 0x d26GL Layers? GL Context? GL Context+ GL Layers+ 
ProductID: {xxxx}
ProductName: Komodo IDE
PyxpcomMethod: {xxxxx}::removeObserver
ReleaseChannel: release
SecondsSinceLastCrash: 333452
StartupTime: 1465571328
Theme: classic/1.0
Throttleable: 1
Vendor: ActiveState
Version: 10.0.0
useragent_locale: en-US

This report also contains technical information about the state of the application when it crashed.

**Comment by mitchell-as** [comment]
If this happens again, will you please send the contents of your log file before restarting Komodo (the log is cleared on each restart). More often than not, log files are more helpful to us than crash reports.

**Comment by st-bobb** [comment]
sure

**Comment by mitchell-as** [comment]
@Naatan just thinking out loud, but this reminds me of the crashes we were investigating recently: `PyxpcomMethod: {xxxxx}::removeObserver` (garbage collection and memory reclamation errors).

**Comment by Naatan** [comment]
Anything in particular that makes you think it's related to this crash?

**Comment by mitchell-as** [comment]
The fact that `PyxpcomMethod: {xxxxx}::removeObserver` is in the crash report makes me think that's related.

**Comment by Naatan** [comment]
Mm, may be something to look into for Komodo 10.1. We'll know more once we have our new crash report server up and running.

I'm closing this bug report as the topic has been addressed, and the crash has nothing to do with the bug (well it could, but currently there is only some correlation).
