### ISSUE TITLE
Komodo IDE converts all environment variables to ALLCAPS ones.

### ISSUE THREAD

**Issue by yzazik** [Komodo/KomodoEdit#1698]
### Short Summary
Komodo IDE reports Environment variables converted to uppercase letters.

### Steps to Reproduce
Open cmd.exe shell.
Set an environment variable 'set TestVar=TestValue'.
Run 'set' and check that variable name preserved as 'TestVar'.
Open IDE using the same shell.
Go to Edit->Preferences...->Environment, variable is shown as 'TESTVAR'.
Also, in Perl it as populated through %ENV hash with ALLCAPS name.

### Expected results
Variable name is expected to be the same as given by 'set' command, i.e. 'TestVar'.

### Actual results
TestVar variable is replaced with TESTVAR.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 8.5
*Operating System (and version)?* Windows 7 x64 Ent SP1

### Additional Information
Elaboration: although its a common practice to use ALLCAPS names stating that names are case-insensitive, the last statement is wrong: the SEARCH is case insensitive, but the keys (variables names) should be preserved.

 -- eg. Error logs, screenshots, workarounds --

**Comment by mitchell-as** [comment]
The fact that you are seeing this in Perl as well indicates Komodo is not to blame. A quick search yielded this: http://stackoverflow.com/questions/28041494/set-case-sensitive-windows-environment-variables-in-perl. In Windows, environment variables are case insensitive.
