### ISSUE TITLE
KomodoEdit 10 doesn't recognize spaceship operator in php7

### ISSUE THREAD

**Issue by VeNoMouS** [Komodo/KomodoEdit#1699]
### Short Summary

When using spaceship operator <=> from php7 , KomodoEdit gives a ```syntax error,unexpected '>'```

### Steps to Reproduce
```
<?php
$blah_arr = usort($blah_arr, function($a, $b) {
    return $a['blah'] <=> $b['blah'];
});
```

### Expected results

Not to syntax error

### Actual results

```syntax error,unexpected '>'```

### Platform Information

*Komodo Edit or IDE?* Edit
*Komodo Version?* 10.0.1, build 17263
*Operating System (and version)?* Linux 64bit, Debian 8.4

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by Defman21** [comment]
Have you configured your php interpreter? I tried to reproduce it but don't see any errors.

**Comment by VeNoMouS** [comment]
Ah, i thought komodo used its own internal syntax checking my local client only has 5.6 where as remote serer had 7...

if that is the case, ignore and close this ticket :P
