### ISSUE TITLE
K09 CPU time with new profile

### ISSUE THREAD

**Issue by lorenrosen** [Komodo/KomodoEdit#170]
This is distinct from the earlier issue (113) because in the intervening time I started with a new profile, and re-opened a couple of old projects. It worked for a bit, but this time the same thing happened as with the earlier bug-- komomdo hung, had to killed from outside, and if started from the command line gives the 'infinite recursion' message

**Comment by Naatan** [comment]
What OS? Any more info? "the infinite recursion message" does not sound familiar to me.

Could you post your pystderr.log from your profile folder when Komodo has crashed, before restarting it?

**Comment by cgchoffman** [comment]
The infinite recursion issue is issue #171.  It's just the result of @lorenrosen having to Kill Komodo with two windows open.  This does sound like a new issue.

Could you also describe more details about what you were doing when Komodo hung?

**Comment by lorenrosen** [comment]
Ubuntu 14.04
Hangs on startup. Could be the same as #171, since as I recall I had, after starting afresh, opened two old projects, in separate windows, and worked on various files in those projects (in various tabs). But I don't recall the precise order of events relative to when komodo was quit and restarted. I'm pretty sure that I had stopped and restarted komodo several times (over the course of several days) before the restart upon which it hung.
Would be willing to try out a patch or 9.0.1 to see if it address the problem.

**Comment by Naatan** [comment]
The fix will be in a nightly later today, @cgchoffman can you ping here when it's up?

**Comment by cgchoffman** [comment]
Will be in the latest nighty http://downloads.activestate.com/Komodo/nightly/. This will push at lunch time Pacific time.

**Comment by lorenrosen** [comment]
Looks like 9.0.1 build from April 15 fixed the problem.
