### ISSUE TITLE
Javascript Linting still enabled regardless of setting KE10

### ISSUE THREAD

**Issue by 133794m3r** [Komodo/KomodoEdit#1701]
When writing javascript the linter is still enabled even when you uncheck "use jslint" whereas in 9 it says "use jshint/jslint".

The following code which is perfectly fine in javascript but linters don't like has the warning line under it.

var arr=new Arrray();

In version 9 it says it's valid and nothing is shown if jslint/jshint aren't checked in version 10 it still says "[] is preferred" which tells me the linter is still running for some reason.

This is a new thing with version 10 and version 9 doesn't show it, I tried redownloading version 9 again(new install deleted old folder to be sure no lingering files remained) and it's only in version 10.

**Comment by mitchell-as** [comment]
You are correct. Thanks for the report.
