### ISSUE TITLE
Find in Files results: double-clicking on result doesn't always scroll to the line in the file

### ISSUE THREAD

**Issue by hayne** [Komodo/KomodoEdit#1703]
### Short Summary

After doing a Find in Files, I double-click on one of the results (in the bottom panel), and it displays the file with that result, but doesn't always scroll to the correct line.
### Steps to Reproduce

I'm not sure if this reproduces it all the time - I only notice this problem sometimes (but quite frequently).
Do a "Find in Files" for a function name (for example).
Double-click on one of the results in the bottom panel.
It sometimes fails to scroll to the line of the result.
I think the problem might occur after doing something like the following:
- double-click on a result that is in fileA
- double-click on a result that is in fileB
- click in fileB (to set the cursor position) but don't modify it
- double-click on a different result in fileA
  It shows fileA, but the line with the result is not visible (not in the current view due to scrolling). Obviously this problem only occurs with files that are larger (usually much larger) than the display area.
### Expected results

Double-clicking on a result should scroll to that result.
### Platform Information

Komodo Edit, version 10.0.1, build 17263
OS X 10.9.5

I note that I have experienced this problem for quite a long time, across several versions of Komodo Edit (i.e. it is not just a version 10 problem)

Note also that double-clicking a second time on the same result (after the first double-click fails to scroll to the line) does work (does scroll to the line of the result).

I think the problem is something related to having the file already displayed and maybe related to having previously (quite recently) double-clicked on some other result that is in the same file.

**Comment by mitchell-as** [comment]
I am not able to reproduce this with the steps given (and I used some pretty large files to ensure that scrolling would have to be done). You said this occurs randomly, but do you have a set of steps that reproduces the problem every time? That would help us pin down the problem. Thanks!

**Comment by hayne** [comment]
I don't yet have a set of repro steps.
But I can repro it reliably (again and again) with the current set of files that I am using.
Note that I am on OS X - are you trying to repro this on OS X?

**Comment by mitchell-as** [comment]
That's fair. I'm on Linux. @cgchoffman can you reproduce this on OSX?

**Comment by hayne** [comment]
I'm wondering if perhaps this is a timing issue (race condition).
It does correctly switch to (display) the file of the result that is double-clicked.
But that file seems to come up at the same scrolling position that it was last at - i.e. it doesn't scroll.
Perhaps the command to scroll to the result line is being issued too early - before the file is displayed. Or while the file is in the course of being displayed and so the command to scroll is being ignored.

**Comment by cgchoffman** [comment]
@mitchell-as i am unable to reproduce on OSX following @hayne steps.

**Comment by mitchell-as** [comment]
@hayne I'm grasping at straws here, but can you reproduce this in Safe Mode? (Help > Troubleshooting > Restart in Safe-Mode.

**Comment by Naatan** [comment]
Could you also clarify what you mean by

> It sometimes fails to scroll to the line of the result.

Does it not scroll to a line at all, or is it scrolling to the wrong line?

Additionally, are you using word wrap?

**Comment by hayne** [comment]
I'm not sure, but I think it doesn't change the scroll position that it had the last time that file was displayed.
E.g. top line of file is line 395
Result is on line 317
I double-click on that result and it changes the file that is displayed to be the file of that result, but it still shows line 395 at the top.
When I manually scroll up to line 317, I see that the search term is highlighted (as it should be) - it wasn't highlighted before I did the double-click.

I'm not using word wrap.

**Comment by hayne** [comment]
As suggested, I restarted in Safe Mode (via the Help/Troubleshooting menu). 
It restarted and seemed to have the default colour scheme etc.
I did a Find in Files for the name of a function and it didn't find anything. (not surprising since no target directory was specified)
I then clicked on the "..." button to specify the root directory (folder) of my source code.
and then clicked the Find All button.
The results came up as usual.
I double-clicked on a result that was on line 317 in fileA. It showed that line correctly.
Then I double-clicked on a result in fileB. It showed that correctly.
Then I went back to fileA and manually scrolled down so that line 395 was at the top and clicked near the bottom of the visible lines (to set the cursor position).
Then I double-clicked on the result in fileB. I showed that correctly.
Then I double-clicked on the result that was on line 317 in fileA. It changed to show fileA but the top line was still line 395 (and hence the line with the result was not visible).

**Comment by hayne** [comment]
Further to my surmise about the problem being possibly related to timing / race condition,
I note that the files are Python .py files and that Komodo Edit is configured to do PyLint checking as well as syntax checking. I wonder if there is some delay caused by the syntax checking or the Pylint-ing.

In the Safe Mode case, I see that PyLint is NOT enabled, however Python Interpreter checking is enabled.

**Comment by hayne** [comment]
To check if the syntax checking is causing the problem (see previous note), I disabled it in Preferences in my usual config (not the Safe Mode version) and was still able to reproduce the problem.
