### ISSUE TITLE
Ruby: highlight `%<modifier>{}` properly

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1704]
### Short Summary

Komodo highlights `%r(reg ex)` as a string, but it's a regex actually. I think Komodo should use the regex color for `%r(whatever)`.

**Comment by mitchell-as** [comment]
The Scintilla lexer would need upgrading.

**Comment by Defman21** [comment]
@mitchell-as note:
```ruby
%r{regex}
%r'regex'
%r!regex!
``` 
are also valid. I can use almost any character as delimiter.

**Comment by Defman21** [comment]
* `%q[ ]` - Non-interpolated String (except for \\ \[ and \])
 * `%Q[ ]` - Interpolated String (default)
 * `%r[ ]` - Interpolated Regexp (flags can appear after the closing delimiter)
 * `%i[ ]` - Non-interpolated Array of symbols, separated by whitespace (after Ruby 2.0)
 * `%I[ ]` - Interpolated Array of symbols, separated by whitespace (after Ruby 2.0)
 * `%w[ ]` - Non-interpolated Array of words, separated by whitespace
 * `%W[ ]` - Interpolated Array of words, separated by whitespace
 * `%x[ ]` - Interpolated shell command
 * `%s[ ]` - Non-interpolated symbol

Any single non-alpha-numeric character can be used as the delimiter (aka `[]` in examples)

**Comment by Defman21** [comment]
Thanks Mitchell! :+1:

**Comment by Defman21** [comment]
@mitchell-as there are some modifiers missing: (`%i, %I, %s`). Should I open a new issue for that?

![image](https://cloud.githubusercontent.com/assets/7100645/19092129/6a32c6fc-8a96-11e6-8c9b-d019c2313971.png)

**Comment by mitchell-as** [comment]
No, I went ahead and committed '%s' support: https://github.com/Komodo/KomodoEdit/commit/437bf65173b07388ffde9c1540897834ea7f2942

%i and %I work for me. You might have to make sure you're rebuilding everything.

**Comment by Defman21** [comment]
I did bk build. Looks like it's not enough.

**Comment by mitchell-as** [comment]
You have to clean `src/scintilla`. Either `bk distclean; bk build` or `rm -r src/scintilla; bk build`.

**Comment by Defman21** [comment]
Thanks.

**Comment by Defman21** [comment]
![image](https://cloud.githubusercontent.com/assets/7100645/19124180/2ee261cc-8b43-11e6-9a11-f958e3a078a2.png)

Works now, thanks! :)
