### ISSUE TITLE
Find in Files (remote) - "No files were found to search in"

### ISSUE THREAD

**Issue by adzchappers** [Komodo/KomodoEdit#1705]
Right clicking on a folder, and choosing "Find" then typing in my search term, when I hit search I get a response of: "No files were found to search in."

First off - yes there are files in the selected folder. 

This is highly frustrating when you have thousands of files to search through on a project level instead! :-/

### Platform Information
Komodo Edit, version 9.3.2, build 16460, platform macosx.
Built on Thu Dec 10 19:37:46 2015.

OS:
OS X Yosemite, Version 10.10.4

**Comment by Naatan** [comment]
I'm unable to reproduce this. Are you using multiple Komodo windows by chance?

**Comment by limegreentangerine** [comment]
Sometimes happens when only one window is open, or multiple.

Files are stored on a server.

**Comment by limegreentangerine** [comment]
It's only just started happening in the last couple of weeks too. Which is what is stranger!

**Comment by Naatan** [comment]
There's the issue; Komodo does not support searching in files on remote servers. I'll make this issue about showing the proper feedback when you attempt this.

**Comment by adzchappers** [comment]
How strange, it's been working for a LONG time, and by a long time, I'm talking years, and suddenly stopped in the last few weeks or so.

**Comment by Naatan** [comment]
I may have assumed wrong, but I have no memory of that being a feature. Let me verify and get back to you.

**Comment by Naatan** [comment]
Verified, this is not a feature in Komodo.

Perhaps I missunderstood you though, because when I open a remote server in Komodo the "Find" menu is greyed out, I cannot even bring up the find panel.

What do you mean by "files are stored on a server"? How are you using them exactly?

**Comment by adzchappers** [comment]
I am doing a find, with Where being "Files", and Directories being the path to a file on our networked development web server.
![screen shot 2016-06-15 at 09 18 33](https://cloud.githubusercontent.com/assets/611127/16072803/9c56f90a-32da-11e6-87e5-270f8ca58c17.png)

**Comment by Naatan** [comment]
Gotcha, so the remote connection is not handled by Komodo.

Does it consistently fail? And does running a similar search on a local folder work?

**Comment by cgchoffman** [comment]
You're only searching a folder called "cy", see includes.  Is that and expect include?

**Comment by adzchappers** [comment]
FML. It's been a long few days :-/

**Comment by thatguypark** [comment]
I have this same issue.  If I do a RegEx search in the file, it finds it, if I do files search with the same search params and options, search results are either empty or inconsistent.   If I do a `grep` with the regex, I get ALL the files.

Even have this with a non-regex basic text search.  Returns only a few items, but again, a basic `grep` will return a full stack of results.   Any yes, I have spent about 10-20mins checking the directories it's search, and all my search options.   I think the search option is just flakey.   

I've been trialling Komodo 11 Edit on a MacOSX to see about switching over from my current IDE, but this is kinda going to be the deal breaker...

**Comment by cgchoffman** [comment]
@thatguypark,  please share a screenshot of the find dialog/tab.  This ticket is closed as invalid though I forgot to set that new label.  There was no bug.
