### ISSUE TITLE
When connected to a remote directory, cannot create new file.  Permissions are correct.  Also - when I create a new file from server - there is no easy  way to refresh file list.

### ISSUE THREAD

**Issue by tunedin76** [Komodo/KomodoEdit#1713]
### Summary:

When connected to a remote directory, cannot create new file.  Permissions are correct.  Also - when I create a new file from server
### Reproduce:

Connect to FTP rremote, hold ctrl down and drag - Copy with new name - This remote directory is in a project.
### Expected

  to create a new file
### Actual results

Error -  looks like file permissions but I have all permissions
### Platform Information

Komodo IDE 10 on Win 10
### Additional Information

 -- eg. Error logs, screenshots, workarounds --

After I create a new file on the server - there is no way to easily refresh the FTP list for that remote directory.

**Comment by Naatan** [comment]
Please share your error log after reproducing the issue.

You can find your error log at Help > Troubleshooting > View Log File.

Additionally, please file a new bug for your refresh issue.

**Comment by tunedin76** [comment]
[error.zip](https://github.com/Komodo/KomodoEdit/files/318766/error.zip)

**Comment by Naatan** [comment]
```
[2016-06-16 11:11:24,150] [ERROR] koPlaceTreeView: doTreeCopyWithDestNameAndURI_WorkerThread: can't copy file /sos/Members/functions/reset_login.php to /sos/Members/functions/pass_vou_gen.php: uncopied_symlinks
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\distribution\bundles\places@activestate.com\components\koPlaceTreeView.py", line 2797, in doTreeCopyWithDestNameAndURI_WorkerThread
    self._copyRemoteItem(conn, src_rfi, newPath, requester_data)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\distribution\bundles\places@activestate.com\components\koPlaceTreeView.py", line 2739, in _copyRemoteItem
    requester_data['uncopied_symlinks'].append(rfi.getFilepath())
KeyError: 'uncopied_symlinks'
```

Komodo seems to think there are symlinks in your source/target, is that true?

**Comment by tunedin76** [comment]
I haven't purposely added one, there shouldn't be.

**Comment by Naatan** [comment]
Komodo seems to think the source is a symlink, can you verify whether that's the case? If not the direct source then maybe one of its parents.

**Comment by Naatan** [comment]
Hi @tunedin76, please respond using the github web interface. Email responses are not parsed properly and github really ought to fix them or disable them altogether.

**Comment by tunedin76** [comment]
So there is no symlink. any ideas?

**Comment by Naatan** [comment]
Could you post the output of `ls -ahl` on the source directory? We'll have to find out what about this directory is giving Komodo the impression that it is a symlink.

**Comment by tunedin76** [comment]
An addition comment - I think all the FTP remote file errors stem from the same issue.  ANY time I open Komodo after closing it with a remote directory project open I get the error.  From that point I have difficulties.   If I remember to close remote project (AND open a local project with local folder) I can then switch to the remote project and I get no   errors..

**Comment by tunedin76** [comment]
To answer your prev question it is a Windows server directory - no hidden files or directories

**Comment by Naatan** [comment]
So steps to reproduce are:

 * Open a remote directory
 * Restart Komodo
 * Attempt to create a new file in the remote directory

Correct?

**Comment by tunedin76** [comment]
Yes. or attempt to rename a existing file or delete one.  It seems to be the exact way to reproduce.  I also  get the error upon opening Komodo
[pysterr.log.zip](https://github.com/Komodo/KomodoEdit/files/390908/pysterr.log.zip)

**Comment by Naatan** [comment]
Not able to reproduce with SCP. @cgchoffman do you have an FTP connection you can test the repro steps with?

**Comment by cgchoffman** [comment]
I've tested this a few times and never been able to reproduce it.   I'll check again though.

**Comment by tunedin76** [comment]
I don't know - I'm just reporting I'm in the middle of a huge project myself All I know is that it happens everytime.  I have re-installed, deleted projects, and etc.. Thanks for your time.

**Comment by cgchoffman** [comment]
I'm not able to reproduce this either and I don't see the error nathanr mention in the logs you've provided most recently @tunedin76 : 
https://github.com/Komodo/KomodoEdit/issues/1713#issuecomment-226525313

**Comment by tunedin76** [comment]
Ok.. I guess I am not getting the error.  My fault… I’ll stop wasting my time with reporting bugs.

**Comment by cgchoffman** [comment]
Oops, sorry i didn't mean to close that!

**Comment by Naatan** [comment]
@tunedin76 do you have access to any other FTP servers? Can you see if you can repro the issue on them?

It's starting to sound like there is something specific to the (type of) ftp server you are using.

**Comment by cgchoffman** [comment]
Had you reproduced the original issue when you submitted those logs?  Do you still get the permissions error?  Can you get a screenshot of that error?  If you're getting a permissions error there should also be a log entry for it as well but I don't see anything like that.

Is it the same error for every action? eg. delete, create, copy all result in permissions issues?

Building on @Naatan's response, is it possible for us to use the account as well to see if we can reproduce the issue?

**Comment by tunedin76** [comment]
It is IIS FTP on Windows Server 2012  Same thing happens on my local windows 10 home "development server" running filezilla server

**Comment by Naatan** [comment]
@tunedin76 in that case it might be something to do with your komodo settings. Could you try reproducing the issue with clean settings?

http://docs.komodoide.com/Troubleshooting/How-do-I-Start-Komodo-with-Default-Settings

You would have to configure one of your ftp servers again under the clean profile to test it.

Apologies for the inconvenience. It's unfortunate that you are thus far the only one able to reproduce this.
