### ISSUE TITLE
prefs: remove "Track Changes" color scheme preferences from Edit 

### ISSUE THREAD

**Issue by twhiteman** [Komodo/KomodoEdit#1715]
**Dev note**: https://github.com/Komodo/KomodoEdit/issues/1715#issuecomment-226800918

Maybe I'm blind, but I cannot find the color scheme preferences for the 'Track Changes' margin colors. My track changes margin colors all appear black (I'm using a variant of Base16_Light color scheme). Here's the colors and the prefs as shown in Komodo 9:
http://komodoide.com/blog/2014-12/tracking-editor-changes-in-komodo/
### Platform Information

Komodo IDE, version 10.0.1, build 89237, platform macosx.
Built on Wed Jun 15 10:57:18 2016.

**Comment by Defman21** [comment]
Hey Todd, it's in Color Scheme Editor - Editor. `changeMargin*` items.

**Comment by mitchell-as** [comment]
I must be blind too because I don't see it. You could configure it in Komodo 9.

**Comment by Defman21** [comment]
![wha](https://cloud.githubusercontent.com/assets/7100645/16153570/8c7e6b9a-34af-11e6-9be3-0694a5dc3108.PNG)

**Comment by mitchell-as** [comment]
Like Todd, I'm running 10.0.1 build 89237. I don't see that.

**Comment by Defman21** [comment]
Mine is Komodo Edit, version 10.0.1, build 17276, platform win32-x86.
Built on Wed Jun 15 08:36:15 2016. I assume it's IDE only?

**Comment by Defman21** [comment]
Yeah, don't see them in IDE as well.

**Comment by Naatan** [comment]
@Defman21 why are you running edit?

These colors are now controlled by the "State" colors under Interface. The fact that they still show under Komodo Edit is a bug.

**Comment by Defman21** [comment]
I'm on Windows, installed it just for testing purposes.

**Comment by mitchell-as** [comment]
This is no longer present in Komodo Edit 11.0.2.
