### ISSUE TITLE
New color swatch blinking and preventing click for colorpicker

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#1716]
### Short Summary
The new colorswatch function has problems with the focus, it keeps blinking.
Removed the fix for K 10.
This also prevents the click for opening the colorpicker, you will have too click many times for opening the colorpicker.

### Platform Information
Komodo 10.0.1 windows 10

### Additional Information
Made a [screencast](http://youtu.be/xqh4DITQn0w?hd=1)
and [one](http://youtu.be/Pg0QtLcowKM?hd=1) for opening the color picker

### Work arround
Bring back the [old color swatch](https://github.com/babobski/Old-Color-Swatch)

**Comment by Naatan** [comment]
Windows must be feeling special again.

Does this fix it?

```
#colorpicker_swatch
{
  padding: 5px;
}
```

**Comment by babobski** [comment]
Tested it, but it's not working.
Also while the flickering present, I get a lot of these logs:
`[2016-06-17 17:54:12,569] [WARNING] console-logger: XUL box for div element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://global/content/bindings/popup.xml:50`

**Comment by Naatan** [comment]
I don't think the warning is related, but thank you. I'll see if I can repro this on windows.

**Comment by tonyattwood** [comment]
Hi,

We've met a little group of tourists yesterday, they have shown us something  really cool, just take a  look <http://explore.jettoursandtravel.com/e4dopa>

Best Wishes, tony.attwood@ntlworld.com

**Comment by Naatan** [comment]
I cannot reproduce this on Windows :\ Are you using a custom DPI or something?
