### ISSUE TITLE
"Please Select the Files You Wish to Save" dialog pops up twice on quit

### ISSUE THREAD

**Issue by mitchell-as** [Komodo/KomodoEdit#1718]
### Short Summary

When I want to quit, Komodo twice asks me to select files to save if I have unsaved files (even if there's only one unsaved file).

### Steps to Reproduce

1. Open Komodo.
2. Create a new blank file.
3. Type something to make the file dirty.
4. Quit Komodo (e.g. Alt+F4)
5. I get the "Please select the files you wish to save" dialog with my dirty file.
6. Click "Don't save".
7. That same dialog pops up again.
8. Extra credit: While this second dialog is open, I can click "Cancel" and Komodo will still quit. In the first dialog, clicking "Cancel" prevents the quit.

### Expected results

I should only have to decline a save once.

### Actual results

It prompts me twice.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* X
*Operating System (and version)?* Linux

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by cgchoffman** [comment]
Making priority.  This has been around for a while and is very annoying.
