### ISSUE TITLE
TypeError: this._hookedMacrosByTrigger is undefined  Exception: TypeError: this._hookedMacrosByTrigger is undefined

### ISSUE THREAD

**Issue by wil831** [Komodo/KomodoEdit#1719]
### Short Summary

TypeError: this._hookedMacrosByTrigger is undefined

Exception: TypeError: this._hookedMacrosByTrigger is undefined

Traceback:
MacroEventHandler.prototype.callHookedMacros@chrome://komodo/content/project/peMacro.js:317:9
MacroEventHandler.prototype.hookPreFileSave@chrome://komodo/content/project/peMacro.js:543:12
save@vieweditor:1277:21
viewManager.prototype.do_cmd_save@chrome://komodo/content/views.js:1836:5
xtk.Controller.prototype.doCommand@chrome://xtk/content/controller.js:91:9
command_doCommand@chrome://komodo/content/library/commands.js:263:1
command_doCommandAsync@chrome://komodo/content/library/commands.js:215:1
@chrome://komodo/content/keybindings/keybindings.js line 2488 > eval:1:1
this.Manager.prototype.evalCommand@chrome://komodo/content/keybindings/keybindings.js:2488:23
this.Manager.prototype.keypressHandler@chrome://komodo/content/keybindings/keybindings.js:2657:17
gKeyHandler@chrome://komodo/content/keybindings/keybindings.js:2543:5

Komodo Edit, version 9.3.2, build 16460.
Built on Thu Dec 10 22:21:38 2015.
### Steps to Reproduce

Start Komodo Edit -> Save
### Expected results

Save
### Actual results

Error
### Platform Information

_Komodo Edit or IDE?_ Komodo Edit, version 9.3.2, build 16460, platform win32-x86. Built on Thu Dec 10 22:21:38 2015.
_Komodo Version?_ 
_Operating System (and version)?_ Windows 10
### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by mitchell-as** [comment]
Does this happen when you restart in safe mode? (Help > Troubleshooting > Restart in Safe Mode). At first glance I'm guessing you might have a bad macro that is configured to run on save.
