### ISSUE TITLE
I want know as close find replace

### ISSUE THREAD

**Issue by lucas1** [Komodo/KomodoEdit#1720]
Komodo IDE, 10.0.1

I want know as close find replace (CTRL + H) ?

Thanks.

**Comment by Defman21** [comment]
Click Esc.

**Comment by lucas1** [comment]
In version 9, I clicked in code and close. In new version if click in code not close, after click in code Esc not work.

**Comment by mitchell-as** [comment]
General questions should be posted on our forums (http://forum.komodoide.com). Our bug tracker is for issues only, not support.

Pressing Esc while in the find/replace dialog will close it.
