### ISSUE TITLE
Shift+Backspace does not do backspace

### ISSUE THREAD

**Issue by mortoray** [Komodo/KomodoEdit#1723]
### Short Summary

Shift+Backspace does not appear to do anything. In most other programs, editors, tools, command-lines, Textinput, etc. it is implemented as a standard backspace. 

### Steps to Reproduce

Shift+Backspace

### Expected results

Deletes previous character

### Actual results

Nothing

### Platform Information

Komodo Edit, version 10.0.1, build 17276, platform linux-x86_64. Built on Wed Jun 15 08:25:28 2016.

### Workaround

Add keybinding for Shift+Backspace to Editor:Backspace

**Comment by mitchell-as** [comment]
@cgchoffman is it worth mapping Shift+Backspace to Editor: Backspace by default? Or should we leave it up to the user? I'm inclined to have the user configure this.

**Comment by Naatan** [comment]
It makes sense to map it by default. If it is a logical action we should map it, in this case I think this is a logical action. Not to mention all other editors seem to do this.

**Comment by Defman21** [comment]
Didn't you have that in previous versions? IIRC I've lost the ability to remove chars while holding shift in Komodo X.

**Comment by Naatan** [comment]
The keybindings have been completely changed in Komodo 10. So what we had in previous versions is irrelevant as we explicitly meant to dump most of that.

**Comment by cgchoffman** [comment]
I seem to remember removing this explicitly as it made no sense.  I can add it back if it's commonly used in other editors, but why?  Does Shift+Backspace perform some action that Backspace alone doesn't?

**Comment by Naatan** [comment]
I think it's more that people might not let go of their shift key during selections. Given that other editors support it I'd say we should too.

**Comment by mortoray** [comment]
When typing and you press Shift+"WrongLetter", it's a natural reaction to just press "Backspace" then "RightLetter" to correct. That is, you'll just naturally be holding down Shift when pressing the Backspace.

**Comment by cgchoffman** [comment]
OK, it's not a problem to add this back for the default keybinding.  Thanks for clarifying.

**Comment by cyberbit** [comment]
Have you never heard of a capital backspace? Use it all the time.

**Comment by Naatan** [comment]
I have not. And apparently neither has Google. :p

**Comment by cyberbit** [comment]
Well now I'm Internet-offended. XD
