### ISSUE TITLE
Toolbar icons disappear when using classic layout

### ISSUE THREAD

**Issue by aschlei** [Komodo/KomodoEdit#1724]
### Short Summary

Icons on the "toolbar left" section disappear a few moments after starting Komodo Edit when using classic layout
### Steps to Reproduce
1. Right-click the toolbar and select Customize
2. Select the option "use classic layout"
3. Restart Komodo Edit
4. The "toolbar left" icons initially appear (here I have only a subset selected)
   ![komodo_initial](https://cloud.githubusercontent.com/assets/14320686/16199771/75b5f7fc-36d0-11e6-997b-8386ff479d20.png)
5. But after a second or so, they disappear
   ![komodo_second](https://cloud.githubusercontent.com/assets/14320686/16199784/82fa5994-36d0-11e6-96f8-fca33bb43fd5.png)
### Expected results

Icons selected should always be shown on the toolbar
### Actual results

Some selected icons disappear
### Platform Information

*Komodo Edit, version 10.0.1, build 17276, platform win32-x86.
Built on Wed Jun 15 08:36:15 2016.
*Windows 8.1 Pro
### Additional Information
- Also had this problem in 10.0.0, but it was sporadic (the icons would disappear randomly, but I could get them back).  With 10.0.1, they disappear every time at start.
- Workaround is to not use the classic layout option, however this only works well if you only have around 5-7 icons selected; more than that and they end up in another drop-down menu, which is not ideal for quick access.

**Comment by Naatan** [comment]
Can you reproduce this using `Help > Troubleshooting > Restart in Safe-mode` ?

Please verify that when restarting in safe-mode Komodo should be using the default UI (all your settings would be temporarily reset).

**Comment by aschlei** [comment]
Yeah, in safe mode, as soon as I check "use classic layout" the "toolbar-left" icons disappear.  After unchecking the box, they don't reappear either (but if I try to add additional icons they will show up again).

**Comment by cgchoffman** [comment]
I'm not sure this is reproducible anymore.  I tried enabling classic tool bar and enabling classic mode and neither triggered this issue. Closing for now. Comment if you can still repro and include the steps please.
