### ISSUE TITLE
Differently worded duplicate messages in Syntax Checking

### ISSUE THREAD

**Issue by CJDennis** [Komodo/KomodoEdit#1725]
### Short Summary
In a JavaScript file, unused variables and functions appear twice in the Syntax Checking list.

### Steps to Reproduce
1: Create a JavaScript file with the following code:
```
function dummy() {
  var value;
}
```
2: Look at Syntax Checking pane

### Expected results
Line Number - Type - Description
1 - Warning - function 'dummy' is defined but never used
2 - Warning - variable 'value' is defined but never used

### Actual results
Line Number - Type - Description
1 - Warning - 'dummy' is defined but never used
1 - Warning - unused var: dummy
2 - Warning - 'value' is defined but never used
2 - Warning - unused var: value

### Platform Information

Komodo IDE, version 10.0.0, build 89159, platform win32-x86.
Built on Wed May 11 15:04:59 2016.

Windows 7 Enterprise

### Additional Information

 -- none --

**Comment by mitchell-as** [comment]
Thanks for the report!
