### ISSUE TITLE
Error when closing tab

### ISSUE THREAD

**Issue by oehhar** [Komodo/KomodoEdit#1728]
Thank you for Komodo 10.0.1

When pressing the "x" of an editor tab or selecting "Close" or typing Ctrl+W, a red box opens below but tab does not close.
The logfile contains probably the contents of the red (totally unreadable) box:
```
[2016-06-21 17:51:37,473] [ERROR] commands: An error occurred executing the cmd_bufferClose command
-- EXCEPTION START --
[Exception... "[JavaScript Error: "this.log is undefined" {file: "vieweditor" line: 1254}]'[JavaScript Error: "this.log is undefined" {file: "vieweditor" line: 1254}]' when calling method: [nsIController::doCommand]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 239"  data: yes]
+ QueryInterface (function) 3 lines
+ message (string) '[JavaScript Error: "this.log is undefined" {file: "vieweditor" line: 1254}]'[JavaScript Error: "this.log is undefined" {file: "vieweditor" line: 1254}]' when calling method: [nsIController::doCommand]'
+ result (number) 2153185313
+ name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
+ filename (string) 'chrome://komodo/content/library/commands.js'
+ lineNumber (number) 239
+ columnNumber (number) 0
+ location (object) JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 239
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/library/commands.js'
| + name (string) 'command_doCommand'
| + lineNumber (number) 239
| + columnNumber (number) 0
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/library/commands.js :: command_doCommandAsync :: line 191
| + formattedStack (string) 'command_doCommand@chrome://komodo/content/library/commands.js:239:0
command_doCommandAsync@chrome://'...476 chars
| + inner (object) null
| + data (object) [xpconnect wrapped nsISupports]
| + QueryInterface (function) 3 lines
| + initialize (function) 3 lines
-- EXCEPTION END --
[2016-06-21 17:51:37,505] [ERROR] keybindings: 
-- EXCEPTION START --
2147500037
+ 0 (number) 2147500037
-- EXCEPTION END --
```

**Comment by Naatan** [comment]
Can you reproduce this using `Help > Troubleshooting > Restart in Safe-mode` ?

Please verify that when restarting in safe-mode Komodo should be using the default UI (all your settings would be temporarily reset).

**Comment by cgchoffman** [comment]
Platform and Version information too please: *Help > About Komodo*

**Comment by oehhar** [comment]
When starting in safe mode, the bug may not be reproduced.
The version is 10.0.1
Platform is Win10 64bit GER

**Comment by Naatan** [comment]
What addons do you have installed?

**Comment by oehhar** [comment]
When I choose in the menu: "Tools->Addons" it shows:

- 1 Classic Skin
- 2 Klint

Then, there is Tools->Addons (Legacy).
Then, the addons of my firefox installation and some others appear which are:

Always Active:

- ActiveState SciMoz7 1.0.0

Ask to Activate:

- ActiveTouch General Plugin Container29.13.2015.428
- Adobe Acrobat15.16.20034.57024
- Citrix Online Web Deployment Plugin 1.0.0.1041.0.0.104
- Intel Identity Protection Technology4.0.68.0
- Intel Identity Protection Technology4.0.68.0
- Java Deployment Toolkit 8.0.910.1411.91.2.14
- Java(TM) Platform SE 8 U9111.91.2.14
- Microsoft Office 201315.0.4514.1000

**Comment by cgchoffman** [comment]
Safe mode only removes 3rd party addons, so the ones under `Tools > addons`.  Did you try removing either Classic Skin and Klint and retesting?

**Comment by oehhar** [comment]
After the test using safe mode, the issue dissappeared also in unsafe mode.

**Comment by Naatan** [comment]
That would be correlation, not causation.

Please post your full error log if this happens again.
