### ISSUE TITLE
CSS box in Color Scheme Editor sticks when viewing Interface settings

### ISSUE THREAD

**Issue by cyberbit** [Komodo/KomodoEdit#1730]
### Short Summary

When toggling between viewing Editor and Interface settings, the custom CSS box on the right sticks to the panel and doesn't switch with the syntax preview.
### Steps to Reproduce

Open Color Scheme Editor. Select Interface on the left, then select Editor.
### Expected results

CSS box appears for Interface, syntax preview for Editor.
### Actual results

CSS box appears for both Interface and Editor.
### Platform Information

_Komodo Edit or IDE?_ Edit
_Komodo Version?_ 10.0.1
_Operating System (and version)?_ Windows 7

**Comment by cgchoffman** [comment]
This appears to be fixed
