### ISSUE TITLE
Intermittent error: Error opening template

### ISSUE THREAD

**Issue by CJDennis** [Komodo/KomodoEdit#1732]
### Short Summary

When creating a new JavaScript file I got the following:
Error opening template

After I dismissed the error message a new blank file opened up. Creating another file immediately worked as expected.
### Steps to Reproduce

Create a new JavaScript file
### Expected results

A new file created from the JavaScript template
### Actual results

Internal Komodo Error

Error opening template

```
Error loading template 'file:///C:/Program%20Files%20%28x86%29/ActiveState%20Komodo%20IDE%2010/lib/support/default-templates/Common/JavaScript.js'

Exception: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIDocumentService.createFileFromTemplateURI]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://komodo/content/views.js :: viewManager.prototype._doFileNewFromTemplate :: line 325"  data: no]

Traceback:
viewManager.prototype._doFileNewFromTemplate@chrome://komodo/content/views.js:325:18
viewManager.prototype._newTemplate@chrome://komodo/content/views.js:240:15
viewManager.prototype.newTemplateAsync/<@chrome://komodo/content/views.js:278:19


Komodo IDE, version 10.0.0, build 89159.
Built on Wed May 11 15:04:59 2016.
```
### Platform Information

Komodo IDE, version 10.0.0, build 89159.
Built on Wed May 11 15:04:59 2016.

Windows 7 Enterprise
### Additional Information

The computer was under heavy load at the time.

**Comment by cgchoffman** [comment]
Is this reproducible/repeatable?
If yes, is it  reproducible/repeatable in Help > Troubleshooting > Safemode?

**Comment by cgchoffman** [comment]
Closing in favor of #2165
