### ISSUE TITLE
Untabify doesn't work on selected text after changing indentation settings

### ISSUE THREAD

**Issue by CJDennis** [Komodo/KomodoEdit#1733]
### Short Summary

Untabify doesn't work on selected text after changing the indentation settings, requiring the selection to be cleared and reselected before it will work.
### Steps to Reproduce
1. Open or create a file that contains space indentation (not tabs)
2. Make sure View Whitespace is selected
3. Select all or part of the file that includes indentation
4. From the menu select Code -> Tabify Region
5. Go to the File Preferences and change:
   - Number of spaces per indent
   - Width of each Tab character
6. Click OK
7. From the menu select Code -> Untabify Region
### Expected results

The indentation should be reformatted in spaces at the new size.
### Actual results

The tabs are the right size but the last step fails to replace the tabs with spaces
### Platform Information

Komodo IDE, version 10.0.0, build 89159, platform win32-x86.
Built on Wed May 11 15:04:59 2016.
Windows 7 Enterprise
### Additional Information

 -- none --

**Comment by mitchell-as** [comment]
I don't think I can reproduce this in 10.0.1. Would you please upgrade to 10.0.1 and try this again?
