### ISSUE TITLE
List of open files is outdated

### ISSUE THREAD

**Issue by mortoray** [Komodo/KomodoEdit#1736]
### Short Summary

Using a keyboard shortcut for "Commando with the open files scope" results in a list that is temporarily out-of-date and sometimes out of place (the two seem connected somehow)
### Steps to Reproduce
- I assigned Alt+Q to "Comamnd with the open files scope"
- Press Alt+Q to open
- Close it
- Open several new files (or close files)
- Press Alt+Q to open
- the list of files is the previous list (and the window is the in wrong place),
- using the arrow keys to select does _not_ update the list
- typing in the search field causes the list to update (and the window to move to the right place)
### Expected results
- an updated list of files
- popup in the correct location
### Actual results
- the previous list of files
- popup in wrong location
### Platform Information

Komodo Edit, version 10.0.1, build 17276, platform linux-x86_64. Built on Wed 

Kubuntu 16.04, KDE Frameworks 5.18.0
### Additional Information

In the wrong location (older shot showing with Goto Anything shortcut, same happens with the Open Files one though):
![de7287eaf03f079bbc8a14a44496110c3221c54c](https://cloud.githubusercontent.com/assets/1308999/16255667/1fa554fc-384c-11e6-8ea2-61cf4534cb69.png)

**Comment by mitchell-as** [comment]
Thanks, I confirm that after opening five files and closing one, the "Open Files" scope still shows five files. I haven't managed to make Commando pop up in a different place though. Still, thanks for the report.
