### ISSUE TITLE
auto abbreviations not working

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#1737]
### Short Summary

From the forum ["(Auto-)Abbreviation for RHTML not Working"](http://forum.komodoide.com/t/auto-abbreviation-for-rhtml-not-working/2910), the auto abbreviation are not working for this language.
I also noticed that the auto abbreviations are not working in most languages.
In most languages the auto abbreviations are only working at the beginning of a document.

If I have for example php and I make here an auto abbreviation "php" to insert a php tag ( "<? | ?>" ).
The auto abbreviation is only working on the first line of the file, every where else I have to insert it manually.

In less the auto abbreviation are not working any where, I have to trigger it always manually.

In html and javascript the  auto abbreviation are working correct.

**Comment by mitchell-as** [comment]
I'm seeing some hit and miss behavior too. I cannot get them to work at all in RHTML, but they work for me in Less. If I make "php" an auto abbreviation in HTML (the language a PHP file starts in), I can indeed only trigger it on the first line.
