### ISSUE TITLE
"Show parsed output as list" failure

### ISSUE THREAD

**Issue by bmcgin** [Komodo/KomodoEdit#174]
In version 9.0.0, in the command properties, the "Show parsed output as list" checkbox is no longer working.  

In v.8 when this was checked, the Command Output window would open the list view.  In v9.0.0 the Command Output window is showing the raw output.

**Comment by Naatan** [comment]
It works fine for me, what are you using to parse your output?

I tested using the example given here: http://docs.activestate.com/komodo/9.0/tutorial/runcmdtut.html#parse

**Comment by bmcgin** [comment]
I just updated to 900 build 15707, still is not working. 

Here is the regEx:   "(.*)", line (?P<line>\d+), pos (?P<column>\d+):(?P<code>.*)

Here is sample output:
ORA-20006: "tax_rpt.psp": compilation failed with the following errors.
"tax_rpt.psp", line 60, pos 9: PLS-00113: END identifier 'LOOP' must match 'TAX_RPT' at line 1, column 11
"tax_rpt.psp", line 60, pos 16: PLS-00103: Encountered the symbol "HTP" 
"tax_rpt.psp", line 71, pos 43: PLS-00103: Encountered the symbol ";" when expecting one of the following:

   . ( , * % & - + / at mod remainder rem <an identifier>
   <a double-quoted delimited-identifier> <an exponent (**)> as
   from into || multiset bulk

"Show parsed output as list" is checked.  The raw output is what appears in the command window, then when I click on the list icon in the bottom right, it switches to the list view.

**Comment by Naatan** [comment]
I tried it on both Komodo 8 and Komodo 9, the output is identical for me. What is different for you on Komodo 8?

**Comment by bmcgin** [comment]
In K8, when "Show parsed output as list" is checked, the command window would show the list view without needing to click on list icon.

When "Show parsed output as list" was unchecked, the command window would show the raw text and then when the list icon is clicked, it would switch to the list view.

**Comment by bmcgin** [comment]
I just installed:  Komodo Edit, version 9.0.1, build 15738, platform win32-x86.

Still the same problem.

**Comment by Naatan** [comment]
I cannot reproduce this issue on either IDE or Edit (latest versions).

Try using a clean profile: https://community.activestate.com/node/15233

**Comment by vokiput** [comment]
I used  KOMODO_USERDATADIR variable to run in 'clean' environment. It didn't help.

![expected](https://cloud.githubusercontent.com/assets/5433342/9098911/98631b04-3b81-11e5-8cf6-114d9b6f7b5f.png)
Expected behavior.

![actual](https://cloud.githubusercontent.com/assets/5433342/9098910/986241ac-3b81-11e5-9786-48f3929270a0.png)
Actual behavior.

**Comment by Naatan** [comment]
Did you check the "Show parsed output as list" checkbox though?

**Comment by vokiput** [comment]
Yes, I checked this option.
I've got the same "unexpected' result when I run 'Find in Files' from Examples.

**Comment by Naatan** [comment]
Sorry, the same unexpected result? Find in Files is a completely different tool..

Will see if I can repro this again, tomorrow.

**Comment by vokiput** [comment]
I was able to reproduce it on a fresh machine. I mean this machine never used Komodo IDE or Edit.

I installed Komodo 8.5 and run Find In Files example command
![findinfiles](https://cloud.githubusercontent.com/assets/5433342/9117112/01263360-3c1d-11e5-819f-8cf7215e435a.png)
It showed expected list as
![expected](https://cloud.githubusercontent.com/assets/5433342/9117157/534852cc-3c1d-11e5-98e5-dbfb3fef7663.png)
After that I uninstalled 8.5 and installed 9.1 and it showed results as the plain text 
![actual](https://cloud.githubusercontent.com/assets/5433342/9117179/73561f22-3c1d-11e5-9e24-e76bd0ab154f.png)

Could you try to reproduce it on fresh Windows. My work machine is a Win 7 x64. At home I tested it on Win 7 x86.
