### ISSUE TITLE
Color of current line inverted in split view

### ISSUE THREAD

**Issue by djacopille** [Komodo/KomodoEdit#1745]
### Short Summary
When stepping through code in split view the current-line-background color in left pane is a dark color (as called for) but the right pane shows the same line with a white background.

### Steps to Reproduce
Stepping through Perl code where the same file is open in both split views, color of current-line-background seems to invert.  Only occurs to files in secondary split view pane during debugging.  Does not occur when not debugging.  While stepping through a file with this issue other code in other tabs in the secondary pane (code not part of the debug process) have the correct current-line-background color.

### Expected results
Colors should be consistently applied to both views, and are, except for the current line background.  If it was slightly off it wouldn't matter, but the inverse color applied makes some text unreadable.

### Actual results
![screen shot 2016-06-23 at 1 11 17 pm](https://cloud.githubusercontent.com/assets/13801692/16312979/139a68b0-3945-11e6-8b82-4c11675d2850.png)

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.0.1
*Operating System (and version)?* os x 10.11.5

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by Naatan** [comment]
You're confusing the current line with the "calling" line. The reason this line is highlighted in your other view is because it has a breakpoint on it which is currently active.

In other words, your color in the left view is determined by "caretLineBack", the color in the right view is determined by "callingLineColor".

**Comment by djacopille** [comment]
Nathan,

Still not clear.

It’s the same line of code in the same file – just two different views.  How can one be calling the other?

How does the same line in the same file have a breakpoint in one split-view but not the other?  My understanding is that breakpoints are file specific, not view specific.

Thanks,
Dave

**Comment by Naatan** [comment]
One isn't calling the other. It looks from your screenshot as if you're debugging, notice the yellow arrow? That means that is the current "calling line". The color scheme you use (which isn't one that is supplied by us) appears to color these white. Your color scheme seems to use a dark color for the current line color, which happens to be the calling line also in the left view. If you were to change your current line then you would likely have 2 white calling lines and a black one wherever your caret is.

The issue you are seeing is with your color scheme having badly defined calling/current line colors.

**Comment by djacopille** [comment]
That only affects the right pane. As I step through the code on the left the current line I’m debugging is the dark color.  No light color line ever shows up in the left pane.  I also didn’t see this phenomenon in 10.0.0, which I used nearly since release.  Only in 10.0.1 does the same line have different colorings in the left and right pane.

**Comment by tonyattwood** [comment]
Hey,

What a wonderfull news from  our best friend I've just read,  you may read it yourself  here  <http://follow.kargobiz.com/e4wcuim>


Sincerely, tony.attwood@ntlworld.com
