### ISSUE TITLE
Toolbox empty, fails to add new tools.

### ISSUE THREAD

**Issue by jvincentXES** [Komodo/KomodoEdit#1746]
### Short Summary

I have been experiencing issues with the Toolbox.  The sample tools do not appear, nor can I add new tools or snippets.  I completely reinstalled Komodo, but the problem persists.

### Steps to Reproduce

I have attempted to view the toolbox folder in Explorer, I have tried to add a new tool through the right-click menu in the Toolbox, and I have tried to add a new snippet from a selection in the editor.  None of these actions worked.
When I right-click on the Toolbox and select "Show in Explorer", I get the following error popup:
![image](https://cloud.githubusercontent.com/assets/20116025/16317989/a1f004d2-3952-11e6-900a-df922369ceb2.png)

When I right-click on the Toolbox and select "Add -> New Snippet...", nothing happens.

When I select some text in the editor, right click on it, and select "Add as Snippet into Toolbox", I get an error message in the Commando and an error entry in the notifications panel, both of which are documented below.

### Platform Information

*Komodo Edit or IDE?*  IDE
*Komodo Version?*  X
Prior to installing version X, I used Komodo IDE 9.3.
After I moved to X, I have uninstalled 9.3, as well as reinstalled X.
*Operating System (and version)?*  Windows 7 Professional SP1

### Additional Information

Toolbox remains empty, even after fresh install:
![emptytoolbox](https://cloud.githubusercontent.com/assets/20116025/16317567/5d02f772-3951-11e6-8f72-6e9a1d165979.PNG)

Selecting text to add to the Toolbox as a snippet:
![image](https://cloud.githubusercontent.com/assets/20116025/16317534/31f1c46e-3951-11e6-98b1-529ebf80498f.png)

Error notification in Commando
![image](https://cloud.githubusercontent.com/assets/20116025/16317521/24cef9c8-3951-11e6-8a7e-56b907043db0.png)

Error log entry:
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIToolbox2Service.getStandardToolbox]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://komodo/content/toolbox/toolbox2.js :: this.getStandardToolbox :: line 458"  data: no]
                       Thu Jun 23 2016 14:43:14 GMT-0500 (Central Standard Time)

Log file:
[pystderr.log.txt](https://github.com/Komodo/KomodoEdit/files/330708/pystderr.log.txt)

**Comment by cgchoffman** [comment]
Can you try shutting down Komodo and renaming 
`C:\Users\yourname\AppData\Local\ActiveState\KomodoIDE\10.0\toolbox.sqlite`.  Restart Komodo after that and see if that helps.

**Comment by jvincentXES** [comment]
I renamed the file and restarted Komodo.  The sample tools were present, and I was able to add new items.  It appears that everything is working correctly now.
Thank you so much tor your quick support!

**Comment by cgchoffman** [comment]
Could you elaborate on the steps leading up to this?  Have you ever had Komodo installed on this computer before?
Are there other versioned folders located in this folder `C:\Users\yourname\AppData\Local\ActiveState\KomodoIDE`?
Had you been using Komodo X for a while then this suddenly occurred? 
If Yes,
Was there any odd incidents that you noticed before this issue appeared?
If NO,
Was this very first start after install?

Glad we were able to sort the initial issue out so quickly.  You didn't lose any custom tools did you?

**Comment by jvincentXES** [comment]
Prior to installing Komodo X, I used Komodo 9.3, so there is a 9.3 folder within the KomodoIDE appdata folder.
I do not recall precisely when this error began, but I believe that it may have been present since I installed Komodo X the first time.  I have been using Komodo X for about a month, but didn't realize that the empty Toolbox might be an issue until I attempted to add a snippet and was confronted with an error.
The only odd symptom other than the empty Toolbox was that my cursor would rapidly flicker between a normal pointer and the busy icon the entire time I used Komodo.  I thought little of this oddity, because it was also present in 9.3.

None of my preferences or custom settings were lost.

**Comment by cgchoffman** [comment]
Ok, not too many definitive points to investigate there.  If you don't mind doing one more thing, could you start Komodo 9.3 and see if your toolbox was broken in 9.3 as well that would help...not much but would help to eliminate changes made to Komodo X as the culprit.  Thanks for the follow up!

**Comment by jvincentXES** [comment]
During my investigation into this issue, I uninstalled 9.3 to see if it might be the cause.  Should I reinstall and try it?

**Comment by cgchoffman** [comment]
yep, reinstalling won't effect this test.  If the profile folder file is corrupted, it will still be corrupted after a reinstall.  That folder isn't touched in the install/uninstall process.

**Comment by jvincentXES** [comment]
It appears that the issue is present in Komodo 9.3 as well.  The Toolbox is empty, and I got this error when adding a snippet:
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIToolbox2Service.getStandardToolbox]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://komodo/content/toolbox/toolbox2.js :: this.getStandardToolbox :: line 458"  data: no]
                       Thu Jun 23 2016 15:46:50 GMT-0500 (Central Standard Time)

**Comment by cgchoffman** [comment]
Ok, thank you for checking.  i'll leave you alone now.

**Comment by jvincentXES** [comment]
Thank you for your help!

**Comment by Naatan** [comment]
@cgchoffman can you target or close this? :)
