### ISSUE TITLE
Can't change file encoding using the file status bar

### ISSUE THREAD

**Issue by blfgomes** [Komodo/KomodoEdit#1747]
### Short Summary

Sometimes clicking on the file encoding (see image below) does not show the pop-up menu where you can change the encoding.

![encoding](https://cloud.githubusercontent.com/assets/7770451/16319942/b2e1fb1a-396b-11e6-90a0-6ba716ddb374.png)
### Steps to Reproduce

Open or create 2 files and click on the current file encoding (see image)
### Expected results

Pop-up menu with encoding options should appear.
### Actual results

Nothing happens.
### Platform Information

Reproduced on _Komodo IDE 10.0/Windows 7 Enterprise SP 1_ and _Komodo IDE 10.0.1/Windows 10 Pro_
### Additional Information

Sometimes it works, sometimes it doesn't. Changing the encoding by going to File Preferences works, though.

**Comment by cgchoffman** [comment]
Anything in the logs?  Help > Troubleshooting > View Log File.

There isn't much to go on here and i'm not seeing it on my windows install.

**Comment by blfgomes** [comment]
Nothing in the logs when I click it. Is there a verbose mode?

**Comment by cgchoffman** [comment]
You can start Komodo using `-v` in the commandline but on Windows that just redirects stdout and stderr to a terminal window rather than the log file.  We would need to locate relevant in Komodo and enable debug logging.  Before we do that though, is this reproducible in Safemode?

**Comment by blfgomes** [comment]
It is reproducible in Safe mode on both machines (default settings in the wizard). 
When I click on New File once, Text-1.txt works fine. When I create a second file, Text-2.txt, clicking on "UTF-8" does nothing.

**Comment by cgchoffman** [comment]
Ahhh weird.  I'm able to reproduce this 100% now.  Just open two files.  The Encoding dropdown is broken when the second file is opened.  Doesn't have to be a new file.

**Comment by cgchoffman** [comment]
Thanks for reporting and thanks for your patients.
