### ISSUE TITLE
Feature Request: add copy-to-clipboard item name in Code Inspector on right click

### ISSUE THREAD

**Issue by AtmanActive** [Komodo/KomodoEdit#1751]
Hi,

Right now, as of "Komodo IDE, version 10.0.1, build 89237, platform win32-x86. Built on Wed Jun 15 10:57:56 2016.", clicking on an item in Code Inspector with left mouse button (LMB) or right mouse button (RMB) does nothing. Double-clicking with either LMB or RMB jumps the main view to that line.

However, it would be super-handy if right-clicking on an item (variable or function or whatever) would just put that item name into the clipboard. That way I wouldn't have to double-click to jump there, then double-click in the editor to select the variable name, then CTRL+C to copy that name, then hit BACK to go back to the line where I was when I needed that name.
See? Simple RMB click could save 6 clicks and visual/mental distraction of jumping to other part of code and then jumping back.

I mean, Code Inspector already serves as a table of contents of all of my variables and functions in that particular file. Then, why not have the ability to quickly copy the variable or function name without leaving the current view?

Thanks.

Keep up the good work!

**Comment by AtmanActive** [comment]
Huh, it does work with CTRL+C. My bad, I didn't even try it.

So, you guys are one step ahead of me. Great! I love it.

Now, would there be any benefit of having RMB click do CTRL+C by default? I don't know. I'm not sure.

Thanks.

Cheers!

**Comment by mitchell-as** [comment]
I don't think Right+Click = Copy is very intuitive, especially if there is no feedback. Anyway, as you mentioned, Ctrl+C works and does what the user would expect. I think this is enough.

**Comment by Defman21** [comment]
Middle mouse button may be used to copy something.
