### ISSUE TITLE
Drag and drop kpf files on Komodo should import toolbox items

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1755]
### Short Summary

http://forum.komodoide.com/t/omg-what-did-you-guys-do-to-the-linux-updates/2922 - this user faced with a problem that he lost his templates during the upgrade process (which wasn't the right way to do that though), regardless of it, he definitely tried to open these kpf files but Komodo just opened them as plain text instead of importing them in the toolbox. This behavior is confusing, the user thought that that's how his template now looks like. Importing this instead of opening would be much better (just like for ksf files).

**Comment by cgchoffman** [comment]
Please attach the KPF file used.

**Comment by Defman21** [comment]
I don't have any 😛 
You should ask the author, not sure he'll give me anything since I'm not a developer.

**Comment by Defman21** [comment]
Hmm, there's a very "small" KPF the author posted in his first post.
```
{
"keyboard_shortcut": "",
"name": "VERKAUF - 03 Fotos",
"value": [

followed by more at the very bottom, consisting of:

],
"set_selection": "true",
"version": "1.0.12",
"indent_relative": "false",
"type": "snippet",
"treat_as_ejs": "false",
"auto_abbreviation": "false"
}
```

But he omitted the content of the template.

**Comment by cgchoffman** [comment]
> I don't have any  
> You should ask the author, not sure he'll give me anything since I'm not a developer.

Please don't make me have to dig for the resources I need to work on a ticket.  I'm trying to help resolve the issue.  Note that it's milestoned for Komodo 11.  If the resources aren't here for me when I finally work on it (months out) then it's a HUGE waste of time.

The content you're showing me is not a KPF (komodo project file).  It's a `*.komodotool`.  I need Freejack to participate in this ticket if he's the one having the issue.

**Comment by Defman21** [comment]
Sorry Carey. I  remember that and next time I'll try to find everything related to an issue to help you guys :)

**Comment by cgchoffman** [comment]
@freejack, when you see this, what I need from you is the original `*.kpf` file that was working as you expected before things blew up on you.

**Comment by cgchoffman** [comment]
Sounds like there is nothing to deal with here. http://forum.komodoide.com/t/what-broke-my-update/2922/30?u=careyh

**Comment by Defman21** [comment]
@cgchoffman:

```
18:48:21 - Defman: nathanr_: https://github.com/Komodo/KomodoEdit/issues/1755 this one
18:48:35 - Defman: I've reported it because I thought Komodo handles kpf files incorrectly
18:49:26 - Defman: but I'm completely lost in freejack's report so I don't even know what kind of file he were trying to open to import a template
18:49:52 - nathanr_: no that's fine
18:49:54 - Defman: I assume it's komodotoolbox file but I sure it's already just imports it instead of opening it
18:50:04 - nathanr_: that wasnt the issue he was reporting, just one you found in the process
```

**Comment by cgchoffman** [comment]
I'm not sure what you're trying to say.  I've already explained what  KPF file is and Komodo handles them properly.  I'm certain from the forum post that there is no bug, there was just confusion on Freejack's part about what he was seeing.  Unless you can reproduce this yourself there is nothing to do here.

I just renamed a `*.komodoproject` file to `*.kpf` and dropped it on Komodo.  Komodo opens the project without issue.  There is no bug here as far as I can tell.

**Comment by Defman21** [comment]
Well, if it works then good to know it! :)

**Comment by cgchoffman** [comment]
> Well, if it works then good to know it! :)

K cool!  Thanks for filing this anyway and your help in that forum post @Defman21!
