### ISSUE TITLE
Problem changing file encoding to utf-8

### ISSUE THREAD

**Issue by paulongithub** [Komodo/KomodoEdit#1762]
### Short Summary
Problem changing file encoding to utf-8 of json copied from uk govt. website

### Steps to Reproduce
Change file to utf-8 encoding

### Expected results
File changes to utf-8 encoding

### Actual results
Internal error setting the encoding for 'C:\web\testing\data\petition.json' to 'utf-8'.

Exception: TypeError: parent.view.lintBuffer is null

Traceback:
applyEncodingAndBOM@chrome://komodo/content/pref/file-properties.js:635
OnPreferencePageOK@chrome://komodo/content/pref/file-properties.js:227
@chrome://komodo/content/pref/koPrefWindow.js:244
@chrome://komodo/content/pref/koPrefWindow.js:299
@chrome://komodo/content/pref/koPrefWindow.js:330
doOk@chrome://komodo/content/pref/project.xul:201
oncommand@chrome://komodo/content/pref/project.xul:1

Komodo Edit, version 8.5.4, build 14424.
Built on Thu Aug 14 00:30:57 2014.

### Platform Information

*Komodo Edit or IDE?*
    Edit
*Komodo Version?* 
    Komodo Edit, version 8.5.4, build 14424.
*Operating System (and version)?* 
    Windows 10

### Additional Information
The JSON was copied from https://petition.parliament.uk/petitions/131215.json

**Comment by cgchoffman** [comment]
Dupe #1747

**Comment by cgchoffman** [comment]
Thank you for reporting.  See #1747 for more information.
