### ISSUE TITLE
file list dropdown in tabbox is missing scc status - misaligned icons (Mac, K10)

### ISSUE THREAD

**Issue by twhiteman** [Komodo/KomodoEdit#1763]
With some git files opened/modified, click on the tabbox file dropdown (right side of the main editor tabbox), the images are not aligned, and there is no scc status shown.

Screenshot:
https://www.dropbox.com/s/d9vwl3yttqth79s/Screenshot%202016-06-29%2010.56.58.png?dl=0

Komodo IDE, version 10.0.1, build 89237, platform macosx.
Built on Wed Jun 15 10:57:18 2016.

**Comment by Naatan** [comment]
Thanks Todd! My guess is these are remnants of the SCC icons.
