### ISSUE TITLE
scc menus and commands never get enabled (Mac, K10)

### ISSUE THREAD

**Issue by twhiteman** [Komodo/KomodoEdit#1764]
I can no longer use the scc menus (or keybindings) as the scc commands never get enabled. Even if I switch tabs, or restart Komodo the menus never get enabled, even though the file tab does show the correct scc status (i.e. Komodo knows that the file is under scc control).
https://www.dropbox.com/s/73sa7vubgzzcabx/Screenshot%202016-06-29%2011.08.21.png?dl=0
https://www.dropbox.com/s/c4x8m4vblrxh93l/Screenshot%202016-06-29%2011.08.51.png?dl=0

**Comment by Naatan** [comment]
This is likely due to version control being a bit TOO context sensitive in Komodo 10 - it cares deeply about your project/places context (too much so at the moment).

As a workaround you could point your Places widget at your repository root and then just close (hide) the widget again.

**Comment by twhiteman** [comment]
Ah, that did the trick. As you'd probably guess - I'd prefer to not have it tied to places :)

**Comment by Naatan** [comment]
Yep I know :) That wasn't an intentional restriction. Fwiw the VCS in Komodo 10 is more project focussed and less file focussed. But that should not mean that the file approach should outright not work.

**Comment by cgchoffman** [comment]
This shouldn't be reproducible anymore, should it?  Getting SCC context from the open file works fine.

**Comment by cgchoffman** [comment]
My macbook won't turn on or i'd test this...I will test this in a minute.

**Comment by cgchoffman** [comment]
Yep, appears to be working.

**Comment by cgchoffman** [comment]
Turns out I'm a liar.  BUT we have another ticket open for this exact same thing so i'll leave this closed.
https://github.com/Komodo/KomodoEdit/issues/2164
