### ISSUE TITLE
Make ctrl+D word insensitive

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1766]
Set up the ctrl+D (and equivalent) keybinds to use the new command created here:

https://github.com/Komodo/KomodoEdit/commit/48607b022945b18b6c981111b11a58f4b61ced3e

It is possible that people will prefer the old behavior, but I prefer to have a consistent and understandable UX that can then be further configured (eg. use the behavior that we currently have) than have a confusing UX that can then be configured to be not confusing but less specific.

So - in short - change keybinds that are set to `cmd_addNextSubstringToCaretSet` to `cmd_addNextSubstringToCaretSet`.

This is open for discussion if anyone disagrees.

**Comment by cgchoffman** [comment]
> So - in short - change keybinds that are set to cmd_addNextSubstringToCaretSet to cmd_addNextSubstringToCaretSet.

I assume you mean move keybindings from `cmd_addNextWordToCaretSet` to `cmd_addNextSubstringToCaretSet` correct?

**Comment by Naatan** [comment]
err yes, I'm not sure what happened there.
