### ISSUE TITLE
On version 10 opened projects are cleared on exit.

### ISSUE THREAD

**Issue by cmfrolick** [Komodo/KomodoEdit#1767]
### Short Summary
With version 9, when I exit the app, then open it again, all fo the projects that were open before are still opened. I have set to save the workspace on exit, it should save the project list since they are in the workspace.

### Steps to Reproduce
Open project(s)
Exit Komodo
Reopen Komodo
No projects will be open, they have to be re-opened.

### Expected results
Projects will be re-opened.

### Actual results
No projects are open.

### Platform Information

*Komodo Edit or IDE?*  Komodo Edit
*Komodo Version?*  10
*Operating System (and version)?*  Windows 7

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by Naatan** [comment]
@cgchoffman I think your recent commit related to workspaces probably fixed this issue, right?

**Comment by cgchoffman** [comment]
Nope, that was only for properly recovering the UI layout.  This sounds like the preferences to recover your workspace on startup hasn't been enabled.  *Prefs > Worspace > When Starting Komodo:*

**Comment by chalda-pnuzig** [comment]
I have this issue too and I have "Restore last workspace" enabled.
When I restart Komodo  all the files are restored but not the last open project.

**Comment by cgchoffman** [comment]
> I have this issue too and I have "Restore last workspace" enabled in preferences.
> When I restart Komodo all the files are restored but not the last open project.

@chalda-pnuzig though it sounds the same I don't think it is.  @cmfrolick is reporting that their MRU Projects list in the Project pane (usually bottom left of the Komodo UI) loses the list of recently open projects.  I assume you still have that list but Komodo just doesn't open your project that you last had open.   I need @cmfrolick to respond and answer out question though otherwise we will have to close this bug.

@cmfrolick please also confirm if this is reproducible in Help > troubleshooting > Restart in Safe Mode

**Comment by cmfrolick** [comment]
I have the same issue. The last open files reopen, but the projects do not.
On version 9 they did. I keep 5 projects open at all times, and it is a
nuisance to have to use the recent projects to reopen them.  I have the
setting to save the workspace on, it should save the workspace.

Thank you,
Charles Frolick

**Comment by cgchoffman** [comment]
@cmfrolick thanks for getting back to us.  Please see my request in my last comment.


> @cmfrolick please also confirm if this is reproducible in Help > troubleshooting > Restart in Safe Mode

**Comment by cmfrolick** [comment]
I will have to try safe mode as soon as I get a chance.

Thank you,
Charles Frolick

**Comment by cmfrolick** [comment]
Restarting in safe mode comes up with all preferences completely reset
every time, how could it reproduce anything but a fresh install?

My workspace preferences are:
Restore last workspace
Restore tab history
Open nofiles when opening a project
Close no files when closing a project
All others are default.

Thank you,
Charles Frolick

**Comment by cgchoffman** [comment]
> Restarting in safe mode comes up with all preferences completely reset
> every time, how could it reproduce anything but a fresh install?

Ahh yes, you'll have to do it manually.  Stop Komodo, move *C:\Users\yourname\AppData\Local\ActiveState\KomodoIDE\* aside, start Komodo then proceed to try to reproduce the issue.

**Comment by cmfrolick** [comment]
I did as you instructed, went with all of the defaults in the wizard.
Opened an existing project.
Exited Komodo. 
Started Komodo, and no projects in the project list.
I checked Preferences, and "Restore last workspace" is the default option.
I even tried opening a file from the project and then exiting Komodo. The file reopens, but not the project.

Thank you,
Charles Frolick

**Comment by cgchoffman** [comment]
Gah, after all that maybe @Naatan was right.  @cmfrolick are you using 10.0 or 10.0.1? *Help > About Komodo*.

**Comment by cmfrolick** [comment]
Komodo Edit, version 10.0.1, build 17276, platform win32-x86.

**Comment by Naatan** [comment]
@cgchoffman wasn't your fix committed after 10.0.1?

**Comment by cgchoffman** [comment]
oh that's right.  I'm confusing my local build with my release install.  10.0.1 does not have that fix.  We could do a nightly for this.  We don't have any ready at the moment though.  We need to branch master and cherry-pick fixes if we want to do that, then point the nightly build slaves at that branch.
