### ISSUE TITLE
Associate *.erb to RHTML

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1768]
### Short Summary

Since they looks the same as `.html.erb`, I think it would be better to associate them with RHTML. Plain text is not that good :)

**Comment by cgchoffman** [comment]
Isn't the naming convention the first example you provided?  I can't find any examples where only `*.erb* is used by it's self without a file style extension as well (eg. `html`, `xml`).  I'd say if it's not a standard then it should be left up to the developer to configure in their preferences.

**Comment by Naatan** [comment]
So the association should be something like `*.html.erb` ?

**Comment by Defman21** [comment]
This is how most partials works (RoR/Middleman/etc.). They don't need to be rendered as html pages but included in html pages and THEN rendered.

**Comment by cgchoffman** [comment]
> So the association should be something like *.html.erb ?

That's what I was thinking and it's already in the default file associating prefs.  But if there IS a case for `*.erb` then I'm on board, I just want to confirm it's a Ruby standard or at least very common.  From @Defman21's last comment it sounds like it might be the latter.  @Naatan you're more qualified to confirm that since you actually use Ruby.  i'm just playing devils advocate.

**Comment by Naatan** [comment]
Yeah I think there are cases where people just use `*.erb`, and then the most likely solution is *.rhtml, though if we set that and people use eg. `.yaml.erb` which we do not have an association for then this file would become html.

I don't think this could be handled reliably with a default file association, and devs should simply be more explicit with their file naming, especially for a file extension that was not intended to be used on its own (yes - I am aware I am guilty of this .. ;)).

**Comment by Defman21** [comment]
Is there no way to set "strict" extension? Like `me.erb` => RHTML, `me.yml.erb` => Text (or Yaml if there is no `yml.erb` association). Actually, this logic would be very interesting:

file.yml.html.erb
1. Try to find an association for `.yml.html.erb` => if fails, => step 2
2. Try to find an association for `.yml.html` => if fails => step 3
3. Try to find an association for `.yml` => if fails => set as Text

**Comment by Naatan** [comment]
I don't believe there is, but it's an interesting concept. Can you think of any other languages that would benefit from this though? I think it's overkill to implement it just for erb.

**Comment by Defman21** [comment]
`.css.less`, `.css.scss`, `.js.coffee`, `.django.html`, `.html.md`, `.hmtl.md.erb`, etc.

**Comment by Naatan** [comment]
None of those apply because in each of them (aside from the last one) the actual file extension describes the language used.

**Comment by Defman21** [comment]
Then I don't know any others.

**Comment by Naatan** [comment]
Then I'm going to close this as won't fix for now, at least until we find a larger use case.
