### ISSUE TITLE
Workspace error when shutting down Komodo (master branch version)

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1769]
nathanr careyh: seeing this when I shut down Komodo:

```
[2016-06-29 14:58:02,339] [ERROR] workspace: Error saving workspace: 
-- EXCEPTION START --
TypeError: prefpath.join is not a function
+ stack
    koWidgetManager_onunload@chrome://komodo/content/library/widgets.js:948:43
    view_saveWorkspace@chrome://komodo/content/workspace.js:661:1
    saveWorkspaceIfNeeded@chrome://komodo/content/komodo.js:27:9
    this.quitApplication@chrome://komodo/content/komodo.js:52:9
    this._onClose@chrome://komodo/content/komodo.js:159:9
-- EXCEPTION END —
```

[3:32 PM]  
careyh hmm looks like the widgets function doesn't like `require("ko/prefs")`

[3:32 PM]  
https://github.com/Komodo/KomodoIDE/blob/master/src/chrome/komodo/content/workspace.p.js#L661

[3:32 PM]  
oh...unless it's the empty list.

[3:33 PM]  
I bet that's being translated into a string or something

[3:33 PM]  
I can take a look

**Comment by tonyattwood** [comment]
Hey,

I  found some old  photos of us, these  are really precious memories for me, just  take  a look <http://fact.ryansrally.org/e4phqas>

Looking forward, tony.attwood@ntlworld.com
