### ISSUE TITLE
Syntax highlighting for PHP in HTML strings sometimes breaks

### ISSUE THREAD

**Issue by cyberbit** [Komodo/KomodoEdit#1773]
### Short Summary
One specific case of valid PHP inside of a quoted HTML string is not recognized by Komodo as PHP, but is instead assumed to be part of the HTML. See attached image.

### Platform Information

*Komodo Edit or IDE?* Edit
*Komodo Version?* 10.0.1
*Operating System (and version)?* Windows 7

### Additional Information
![image](https://cloud.githubusercontent.com/assets/7350183/16500850/11f39e50-3ecc-11e6-8ce2-3baf3a35b705.png)

**Comment by Defman21** [comment]
```
<? echo "hello" ?>
<?echo "hello"?>
<?= "hello" ?>
<?="hello"?>
<label href="<? echo "$server/$link" ?>"></label>
<label href="<? echo "$server/$link"?>"></label>
```

Not able to reproduce with this code. You forgot to close first `<label` tag.

**Comment by mitchell-as** [comment]
Thanks, I was able to reproduce the problem with that last line.

**Comment by Defman21** [comment]
Ahh yeah, `<?echo` seems to break something.

**Comment by cyberbit** [comment]
@Defman21 You're right! Updated the image.
