### ISSUE TITLE
Dedent causes some sort of completion

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1774]
### Short Summary

When dedenting certain code Komodo seems to perform some sort of auto completion.

### Steps to Reproduce

Create a LESS file with the following content:

```
@media (min-width: 800px)
{
        .inner-wrapper
        {
            
        }
}
```

Select lines 3 through 6 and press shift+tab

### Expected results

Selection is dedented.

### Actual results

Code is changed to:

```
@media (min-wi<div class="inner-wrapper"></div>        .inner-wrapper
        {
            
        }
}
```

### Additional Information

Likely this won't work unless you have my codebase, but hopefully it gives enough to go on?

**Comment by Naatan** [comment]
Nevermind, this is caused by Xemmet.

**Comment by Defman21** [comment]
Report to upstream please.

**Comment by Naatan** [comment]
Sorry Defman21 but it absolutely does. Uninstalling xemmet fixed the issue entirely.

**Comment by Defman21** [comment]
I'll look forward to try to find what's causing that, but for now I'll apply a very simple patch that won't trigger anything in Xemmet logic if Shift is hold.
