### ISSUE TITLE
hasTabstopInsertionTable is not false when a character has been typed at tabstop

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1777]
### Short Summary

Create this snippet:

```
{
    [[%tabstop:]]
}
```

Insert it, type some text (will appear at tabstop position). Then call `require('ko/views').current().get('koDoc').hasTabstopInsertionTable`. It **should** be false, but it still keeps saying it's true. Esc makes this false. Xemmet is rely on this and I'm pretty sure it's a bug in Komodo.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.0.1 latest
*Operating System (and version)?* elementary OS 0.4

**Comment by Defman21** [comment]
It keeps saying it's true even if the tabstop was replaced. (`%[[tabstop:replaceme]]`)

**Comment by Naatan** [comment]
@mitchell-as please investigate. Might be there is a reason for this.

**Comment by Defman21** [comment]
If there's such a reason, I want to know how to detect how much tabstops are there.

**Comment by mitchell-as** [comment]
It's not a bug. There is a tab stop table, but it happens to be empty in your particular case. You need to request the tab stop table and check its length to be non-zero. You can take a look here: https://github.com/Komodo/KomodoEdit/blob/83dae67f6ba49f0b861610337d46cb8a7a10f810/src/chrome/komodo/content/library/tabstops.js#L79

Line 91 is the length check. Empty tab stop tables are allowed and handled properly by us, so you can do the same :)

**Comment by Defman21** [comment]
Thanks Mitchell! :)
