### ISSUE TITLE
Jinja2 template support

### ISSUE THREAD

**Issue by hongquan** [Komodo/KomodoEdit#1778]
Please support Jinja2 template. It is a long standing request: https://bugs.activestate.com/show_bug.cgi?id=102989

Jinja2 is much-loved and is used in Flask, Bottle, Pyramid and even Django (Django 1.8 has built-in support for Jinja2, though it is not default engine).

**Comment by hongquan** [comment]
Cannot wait longer, I made an add-on for Jinja2 support here: https://bitbucket.org/hongquan/komodo-jinja

**Comment by Defman21** [comment]
That's cool!

**Comment by Naatan** [comment]
I'll leave this open for a potential native implementation. Thanks for the great work @hongquan !

**Comment by mitchell-as** [comment]
@hongquan Unfortunately your code has no license, so we're not able to incorporate it in the final product. Do you mind adding a permissive license to your code so that we can use it? Thanks for your consideration.

**Comment by hongquan** [comment]
Sure. I will do.

**Comment by hongquan** [comment]
Hi. I added the license (MIT).

**Comment by mitchell-as** [comment]
Thank you very much!

**Comment by Defman21** [comment]
You could add him to [Contributors](https://github.com/Komodo/KomodoEdit/blob/master/CONTRIBUTORS.txt) as well! :)
