### ISSUE TITLE
Environment prefs dont initialize when accessing them after searching in pref window

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#178]

**Comment by cgchoffman** [comment]
open your prefs window

and search for "env"

then press the Environment entry

it's tree elements will be empty and there will be not buttons

**Comment by mitchell-as** [comment]
I'm not able to reproduce this. (See attached screenshot.)

![env_prefs](https://cloud.githubusercontent.com/assets/12902397/10587662/1d62c006-7670-11e5-830c-959ff30aa64e.png)

@Naatan can you still reproduce?

**Comment by Naatan** [comment]
Nope, cannot reproduce anymore either.
