### ISSUE TITLE
RX Toolkit choosing language PHP shows Python Icon

### ISSUE THREAD

**Issue by mstra001** [Komodo/KomodoEdit#1783]
### Short Summary

In the RX Toolkit is a little icon for changing the language. It was initially set to Python, I changed it to PHP. Nothing happened. Then I switched to Perl, it showed a perl icon. Then I switched to PHP, it showed the python icon.
### Steps to Reproduce

Opening the Tools > RX Toolkit, changing the language to PHP
### Expected results

The icon shows PHP when changing the language of RX Toolkit to PHP
### Actual results

The icon shows python when changing the language of RX Toolkit to PHP
### Platform Information

Windows 10
Komodo IDE, version 10.0.1, build 89237, platform win32-x86 Trial

**Comment by Naatan** [comment]
Do you have PHP configured in Komodo? Prefs > Languages > PHP.
