### ISSUE TITLE
Userscripts don't respect global indentation pref

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1786]
### Short Summary

Title

### Steps to Reproduce

Create a new userscript, press TAB to add an indent

### Expected results

Indent uses spaces (if that is your global pref)

### Actual results

Indent uses tabs.

**Comment by mitchell-as** [comment]
Perhaps you meant to switch them around. I always get 4-space indentation in the userscripts editor, but if I try to change to tabs, or change tab width, I still get 4 spaces of indentation.
