### ISSUE TITLE
Blue circle on mouse pointer

### ISSUE THREAD

**Issue by PeterFullbrook** [Komodo/KomodoEdit#1789]
### Short Summary

Running Komodo Edit 10 on iMac - mouse pointer in editor window permanently displayed with blue circle as pointer tail and keeps bouncing and blinking randomly when not doing anything. Ok elsewhere within Komodo Edit and on other applications.
### Steps to Reproduce

Mouse pointer anywhere in Edit window
### Expected results

Steady standard mouse pointer changing to text pointer when over text.
### Platform Information

_Komodo Edit or IDE?_ Edit
_Komodo Version?_ 10
_Operating System (and version)?_ Mac OS X Version10.11
### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by mitchell-as** [comment]
Hi, what are the circumstances surrounding this issue? Does it happen at startup? Or is there a sequence of steps to trigger it? A screenshot may also be helpful. Does it persist between restarts of Komodo Edit? Can you reproduce it in Safe Mode? (Help > Troubleshooting > Restart in Safe Mode)
