### ISSUE TITLE
No window controls for Sync Settings window and the same type of windows

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#179]
http://forum.komodoide.com/t/no-way-to-close-dialog-for-sync-settings-excelt-alt-f4-komodo-ide/1204

**Comment by Naatan** [comment]
Sync has been removed, I dont see this as being a big enough issue such that we should release an update for 8.5.

**Comment by Defman21** [comment]
But the same problem with other windows such like Sync Settings.

**Comment by Naatan** [comment]
That's still Sync. Can you give an example of a window that is still present in Komodo 9?

**Comment by Defman21** [comment]
I'll try to find an example and let you know about it as far as I can.

**Comment by Naatan** [comment]
If you do find one please open a new bug and provide a short description of the problem. Thanks! :)

**Comment by Defman21** [comment]
Okay :+1:
