### ISSUE TITLE
Continue multiline comment (SQL, SCSS)

### ISSUE THREAD

**Issue by cdcmicro** [Komodo/KomodoEdit#1790]
### Short Summary

In SCSS and SQL multiline comments , Shift-Return doesn't continue.

### Steps to Reproduce

Create a mutltiline comment, perhaps...

```
/**
* comment|
**/
```
Pipe represents the cursor.

Press Shift-Enter

### Expected results

```
/**
* comment
* |
**/
```

### Actual results

```
/**
* comment
|
**/
```

### Platform Information

Komodo IDE, version 10.0.1, build 89237, platform win32-x86.
Built on Wed Jun 15 10:57:56 2016.IDE

### Additional Information

In Javascript, I get the expected results just by pressing Enter (or Shift-Enter).

It was the same in IDE9, so I'm calling it an enhancement request.

**Comment by mitchell-as** [comment]
Thanks for the suggestion!

**Comment by mitchell-as** [comment]
Note: SCSS already has comment continuation support. It was just SQL that needed it in this ticket.

**Comment by cdcmicro** [comment]
Thank you for the enhancement. Looking forward to the next release.
