### ISSUE TITLE
Error in Komodo 10

### ISSUE THREAD

**Issue by truetothemark** [Komodo/KomodoEdit#1793]
TypeError: can't access dead object

Exception: TypeError: can't access dead object

Traceback:
_doSave@vieweditor:1288:1
save@vieweditor:1408:28
viewManager.prototype.do_cmd_save@chrome://komodo/content/views.js:1843:5
xtk.Controller.prototype.doCommand@chrome://xtk/content/controller.js:91:9
command_doCommand@chrome://komodo/content/library/commands.js:272:1
command_doCommandAsync/<@chrome://komodo/content/library/commands.js:229:13

Komodo Edit, version 10.0.1, build 17276.
Built on Wed Jun 15 08:36:15 2016.
### Platform Information

_Komodo Edit
*Komodo Version - 10 
*Operating System (and version)?_ - Windows 7 sp1 
### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by mitchell-as** [comment]
Hi, thanks for the report. Unfortunately a traceback is not terribly helpful in this case. Can you consistently reproduce this problem? What are the steps? We need to know this in order to diagnose (and fix) the problem. Thanks.

**Comment by truetothemark** [comment]
Hi again. The error occures when I start a browser preview, then close it and try to save the file. Can I just download the previous version of Komodo? It was just perfect )

**Comment by cgchoffman** [comment]
I can't reproduce this on Windows.  Does the file not save?  

You can download any version of Komodo you like by clicking the *Full Archive* link on the download page: http://komodoide.com/download/

- Carey

**Comment by truetothemark** [comment]
It works every time for me ))
Windows 7, sp1.

TypeError: can't access dead object

Exception: TypeError: can't access dead object

Traceback:
_doSave@vieweditor:1288:1
save@vieweditor:1408:28
viewManager.prototype.do_cmd_save@chrome://komodo/content/views.js:1843:5
xtk.Controller.prototype.doCommand@chrome://xtk/content/controller.js:91:9
command_doCommand@chrome://komodo/content/library/commands.js:272:1
command_doCommandAsync/<@chrome://komodo/content/library/commands.js:229:13


Komodo Edit, version 10.0.1, build 17276.
Built on Wed Jun 15 08:36:15 2016.

**Comment by cgchoffman** [comment]
Does it happen when running in Help > Trouble Shooting > Restart in Sade mode?

**Comment by truetothemark** [comment]
After restarting in safe mode it worked just fine. But when I restarted again it just crashed.

**Comment by cgchoffman** [comment]
Sounds like either a broken addon or toolbox item.  You can check Commando Package scope (Ctrl + P)  > List Outdated and either try to update or un-install any listed addons.  Or have a look through your toolbox Userscripts for Userscripts that run on file save.

**Comment by truetothemark** [comment]
I've installed Komodo Edit 9 and it crashes as I load the file:

**Comment by cgchoffman** [comment]
They don't sound like the same problem.  Did you try any of the steps i suggested in my last comment while still running 10?
