### ISSUE TITLE
Global variables (and closures) are being reported as "unknown property" with Chrome remote debugging

### ISSUE THREAD

**Issue by matt42s** [Komodo/KomodoEdit#1796]
### Short Summary
Global variables (and closures) are being reported as "unknown property" with Chrome remote debugging in KomodoIDE 10.0.1 build 89237

### Steps to Reproduce

```
<html>
    <head>
        <script type="text/javascript">
			var global = "It is ridiculous that globals are not supported";
            function foo() {
				console.log( global );
				console.log("no-op");
            }
        </script>
    </head>
    <body>
        <h1 onclick="foo();">HELLO!!!</h1>
    </body>
</html>
```

Add a watch on "global"
Set a breakpoint at the no-op line

### Expected results
global should be reported in the Watch tab as "It is ridiculous that globals are not supported"
Additionally, it should be available in the Globals tab

### Actual results
global is shown with value "Unknown property 'global'"

### Platform Information

*Komodo Edit or IDE?*  IDE
*Komodo Version?* 10.0.1
*Operating System (and version)?* Win 10

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by cgchoffman** [comment]
That example code looks really familiar...#1785

**Comment by matt42s** [comment]
Of course it looks familiar, I used the code that mitchell provided as a template - when he asked me to give an example (in the support forums) 
If you looked past the similarities to the actual detail, you might see that it's a separate issue - unless you want to bunch it all into the one problem, might I suggest the subject is changed to "The chrome debugger is horribly broken"

**Comment by mitchell-as** [comment]
Thanks for taking the initiative to file this @matt42s . I'll work on this one too.

**Comment by mitchell-as** [comment]
To be clear @cgchoffman the global should show up in the watch window, per the fix in #1785, but it not showing up in the globals pane is another issue.

**Comment by cgchoffman** [comment]
Ok thanks for confirming @mitchell-as.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoIDE/commit/604fda3914d8654110388f10466d6fc31f0c4fd4
