### ISSUE TITLE
Refresh view not working on FTP remote folder

### ISSUE THREAD

**Issue by tunedin76** [Komodo/KomodoEdit#1798]
### Short Summary

Made changes on the server the remote folder is located, copying files into the directory pointed to through the project remote folder. "Refresh View" does not update the list. 

### Steps to Reproduce

Add a file to the remote folder through direct connection or another FTP program, then "Refresh View" on Komodo 10

### Expected results

Files to Show

### Actual results

No updates

### Platform Information

*Komodo IDE 10
*Komodo Version?* 
*Operating System (and version)?* Win 10

### Additional Information

 -- eg. Error logs, screenshots, workarounds --
Work  - around is to shutdown Komodo IDE and restart.

**Comment by cgchoffman** [comment]
You already filed this @tunedin76 #1714
