### ISSUE TITLE
Ctrl+> impossible keybinding

### ISSUE THREAD

**Issue by cdcmicro** [Komodo/KomodoEdit#1800]
### Short Summary

From the forums, [What&#x27;s the big deal with Commando](http://forum.komodoide.com/t/whats-the-big-deal-with-commando/2955/6)...

Commando: ToggleCommando with the Files scope is bound to Ctrl+>, which appears to be an impossible key combination (on Windows, anyway)

### Steps to Reproduce

Press Ctrl+>

### Expected results

Commando opens in Files scope

### Actual results

Nothing happens.

### Platform Information

Komodo IDE, version 10.0.1, build 89237, platform win32-x86.
Built on Wed Jun 15 10:57:56 2016.

### Additional Information

On my keyboard, pressing Ctrl + the (. >) key is either Ctrl+. or Ctrl+Shift+>

**Comment by cgchoffman** [comment]
My response:
http://forum.komodoide.com/t/whats-the-big-deal-with-commando/2955/7

Open to input.

**Comment by cgchoffman** [comment]
Note File scope key binding has been set since at least 9.3.2 (likely since Commando was added) and no one noticed that that binding doesn't work so I'm pretty sure we can remove these.

**Comment by cdcmicro** [comment]
Only @mitchell-as will miss them :-))

**Comment by mitchell-as** [comment]
It works on Linux, haha :)

**Comment by cgchoffman** [comment]
*head to desk* The perils of maintaining consistent key bindings across 3 platforms haha.
