### ISSUE TITLE
Scrollbars are too dark

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1802]
### Short Summary

Just had 3 people ask about changing the scroll bar to a lighter colour in the last 5 days, two of them were today.  I put my bean in that hat too, i've just been too lazy to change the colour.

This shouldn't take custom css.  It makes sense to me to have an option in the Interface section of the Color Schemes editor.

**Comment by cgchoffman** [comment]
Workaround: http://forum.komodoide.com/t/komodo-color-scheme-ui-sheet-color-reference/2865/5

**Comment by bradws** [comment]
Can you please provide step-by step process on how to change the color of the scrollbars in Komodo Edit 10.1.1 (Windows 7) as I have tried the above work-around, but it did not work. The scrollbars are too dark to see.

Thanks.

**Comment by Defman21** [comment]
Open Tools - Color Scheme Editor - Interface. Add this code to custom CSS:

```
scrollbar thumb
{
	background: #ff0000 !important;
}
```

**Comment by jolyonralph** [comment]
The above fix doesn't work for me on Komodo IDE 10.1.4 MacOS Sierra.

In fact, when I add this to the Custom CSS area for the Interface section, and apply, and close, then go back into the Color Scheme Editor the lines added have disappeared.

**Comment by Naatan** [comment]
Hit "New" to copy the current color scheme, then make the modifications.

**Comment by bradws** [comment]
Thank-you! I can confirm Defman21's fix as per above commented made on Nov 13, 2016 worked for me on Windows 7 Komodo edit v10.4.4
