### ISSUE TITLE
Shft+Del does not Cut

### ISSUE THREAD

**Issue by srgloureiro** [Komodo/KomodoEdit#1803]
Komodo Edit, version 10.0.1, build 17276, platform win32-x86.
Built on Wed Jun 15 08:36:15 2016.

Note: My windows and processor are both 64 bit.

**Comment by Defman21** [comment]
FYI it works fine on Linux for me.

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoEdit/commit/03fbd6be0aba332e3354c0ad23e27673f73fb597
