### ISSUE TITLE
Syntax Checking hiccup

### ISSUE THREAD

**Issue by tunedin76** [Komodo/KomodoEdit#1806]
### Short Summary

Javascript syntax hiccup 
### Steps to Reproduce

File is in PHP mode and syntax checking shows JS error on this line see images... When I remove the semi-colon I get another error - missing semi-colon

Note that file in JS mode correctly analyzes script
### Platform Information

Komodo IDE, version 10.0.1, build 89237, platform win32-x86.
Built on Wed Jun 15 10:57:56 2016. - on  Windows 10Pro
### Additional Information

![img2](https://cloud.githubusercontent.com/assets/16789318/16843980/616aba6e-49b1-11e6-9825-5679f246c14b.png)
![img1](https://cloud.githubusercontent.com/assets/16789318/16843981/616d175a-49b1-11e6-9f07-c42b2f718d5c.png)

**Comment by cgchoffman** [comment]
hi @tunedin76, please provide a sample of code that reproduces this.  There isn't a lot we can do with a screenshot.

And to clarify, you're reporting that the "Unnecessary semicolon" error shouldn't not show up, correct?       The "missing semicolon" error is correct.

**Comment by mitchell-as** [comment]
Note: I could not reproduce the "Unnecessary semicolon" warning by typing the text in the original screenshot. I agree that the "Missing semicolon" warning is correct.
