### ISSUE TITLE
Code completion CSS

### ISSUE THREAD

**Issue by tunedin76** [Komodo/KomodoEdit#1807]
### Short Summary

As I am typing CSS - anything with a dash autocompletes at the dash. Very annoying. For instance:

overflow-y as typed produces

overflow: -

the dash inserts a colon, a space and a dash

Maybe there is a setting I need to change - but as far as I know all key bindings are default.

Komodo IDE, version 10.0.1, build 89237, platform win32-x86.
Built on Wed Jun 15 10:57:56 2016. on Win10Pro

**Comment by Defman21** [comment]
Are you able to reproduce it in Safe Mode? (Help - Troubleshooting - Restart in Safe-Mode)

**Comment by cgchoffman** [comment]
Turn off Prefs > Code Intelligence: Enable autocomplete fill-up characters.  That will likely resolve the issue.
