### ISSUE TITLE
Autocomplete fill-up characters inserts an unwanted space

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1808]
### Short Summary

With this setting enabled, type something like:

```css
.test {
  col|
}
```

Then press space. There will be an additional space:

```css
.test {
  color:  |
}
```

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.0.1
*Operating System (and version)?* Windows 7 x64

**Comment by cgchoffman** [comment]
Are you using `spacebar` as the fillup character?

**Comment by Defman21** [comment]
Yes. Not sure there's a setting where I can set what characters should be used for fillup action.

**Comment by cgchoffman** [comment]
It doesn't consume the character.  It's assumed that you want the character inserted as the next char after your completion.  It says this in the preferences window.

**Comment by Defman21** [comment]
Hmm, ok. I should be more attentive next time. Thanks :)

**Comment by cgchoffman** [comment]
> Yes. Not sure there's a setting where I can set what characters should be used for fillup action.

Yes, that's kind of annoying.  I think it changes per language.  It must be given what it does.  


> Hmm, ok. I should be more attentive next time. Thanks :)

Don't worry about it. Thanks for keeping me on my toes.
