### ISSUE TITLE
JavaScript Template Literals: remaning code loses highlighting

### ISSUE THREAD

**Issue by manngo** [Komodo/KomodoEdit#1809]
### Short Summary
If I add a JavaScript template literal, the code after the current function loses its highlighting.
This seems to be limited to literals with embedded variables.

### Steps to Reproduce

- Create two functions.
- In the first function add the following code: `var a=3; alert('value is ${a}');`

__Sorry, but I can’t get the backtick to appear in the code above. Please replace the single quote (`'`) with a backtick!__

### Expected results

The rest of the code should be highlighted.

### Actual results

Code _after_ the first function is not highlighted.

### Platform Information

*Komodo Edit or IDE?* Edit
*Komodo Version?* 10.0.1
*Operating System (and version)?* OS X 10.11.5

### Additional Information

I can get it to work again by changing the syntax highlighter to another language and then back to JavaScript.

**Comment by Defman21** [comment]
I have the same problem.

```
(function() {
    var variable = 1;
    this.test = () =>
    {
        console.log(`test ${variable}`);
    };
    
    this.test2 = () =>
    {
        console.log("I'm green");
    };
}).apply(module.exports);
```

![screen](http://i.imgur.com/MYfVzO1.png)

**Comment by mitchell-as** [comment]
Thanks for the report. I can reproduce this.
