### ISSUE TITLE
Track Changes window should use settings from color scheme

### ISSUE THREAD

**Issue by we3geeks** [Komodo/KomodoEdit#181]
Enhancement request: For color consistency, the "track changes" window should use color settings from the color scheme (either the colors specified for the track changes-related settings margin or those used to color Diff files).

**Comment by Defman21** [comment]
It looks fine in Komodo 10.

**Comment by we3geeks** [comment]
@cgchoffman Was this closed because it has been fixed or for some other reason?

**Comment by Defman21** [comment]
It has been implemented :)

**Comment by cgchoffman** [comment]
To be honest, I have no idea what this ticket is asking.  There is no "track changes" window.  There is only a Track Changes margin.  Those colors are based on your color scheme so I would say this can be closed but by all means, if it's not done then please say so.

**Comment by mitchell-as** [comment]
I think this is the file diff viewer (visualize what has changed in a diff format) and has nothing to do with the track changes margin.

**Comment by we3geeks** [comment]
It is related to the track changes margin, at least from the standpoint that it opens when you click on the track changes margin. I made the enhancement request because the colors used in the track changes window did not seem to be based on either the color scheme settings for the corresponding colors used for the track changes margin (e.g., the color for the margin from the color scheme to denote additions was not the color used to denote additions in the track changes "diff" window), nor did they match the colors from the color scheme for diff files. It would be much more consistent if the colors for that diff window you get when you click on something from the track changes were based on /something/ from the color scheme...

If that has been implemented, great... I'll go do some testing with a couple of my color schemes to see if it works. What version would I expect to see this in?

But if it is being closed for some other reason, I guess I'm less OK with it just being closed without an explanation as to why.

**Comment by Naatan** [comment]
It has indeed been implemented.

**Comment by Defman21** [comment]
I'm using Komodo IDE 10.0.1.

This is how the window you're referring to looks like:

![test](https://i.imgur.com/qFJXR4d.png)

I'm using Oceanicnext color scheme.

**Comment by cgchoffman** [comment]
> at least from the standpoint that it opens when you click on the track changes margin

I guess I'm slow as DEfman and Naatan both got it but this would have been really helpful information in the first message :)

**Comment by we3geeks** [comment]
@cgchoffman I will take the blame for that; I will try to be more explicit in the future. It seems like some indication of why the issue was closed would have helped, too. I will do a bit more testing with a couple of my color schemes in both IDE and Edit. 

Are the colors for the diff viewer (is that what I should call it?) tied to the colors of the track changes margin or something else? (Just so I know what to look for.)

**Comment by Naatan** [comment]
@we3geeks It currently uses the SCC colors, because this frame is not a scintilla element. That's likely something that will change in the future.

**Comment by we3geeks** [comment]
@Naatan Thanks; that helps. As long as I have a way of coloring them to be consistent across all three areas (margin, editor, and this diff viewer frame), I'm happy. 

Are you referring to the 'scc *' entries within the 'InterfaceStyles' section, as opposed to the 'changeMargin*' entries in the 'Colors' section?

My intent would be to color the diff viewer frame content to match the colors I'm using for Diff files (which use 'additionline', 'chunkheader', 'deletionline', 'diffline', 'fileline' in the 'Diff' portion of the 'LanguageStyles' section.

**Comment by Naatan** [comment]
> Are you referring to the 'scc *' entries within the 'InterfaceStyles' section, as opposed to the 'changeMargin*' entries in the 'Colors' section?

Correct.

**Comment by Naatan** [comment]
> Are you referring to the 'scc *' entries within the 'InterfaceStyles' section, as opposed to the 'changeMargin*' entries in the 'Colors' section?

Correct.
