### ISSUE TITLE
Syntax Tooltip too persistent

### ISSUE THREAD

**Issue by manngo** [Komodo/KomodoEdit#1810]
### Short Summary

If I write some code which the syntax checker disapproves of, a tooltip naturally appears. However:
- the tooltip does not disappear if I continue typing underneath it
- if I switch to another window (cmd-tab) the tool tip appears on all other windows
### Steps to Reproduce
- in JavaScript, type int `alert(0)` and wait; you may have to move the mouse over the code
- when the tooltip appears, either continue typing, or switch to another window.
### Expected results

The tooltip should get out of the way.
### Actual results

Well, it doesn’t
### Platform Information

_Komodo Edit or IDE?_ Edit
_Komodo Version?_ 10.0.1
_Operating System (and version)?_ OS X 10.11.5

**Comment by mitchell-as** [comment]
I've noticed this too, but I think it's a problem related to Mozilla (Komodo is built on the Mozilla framework). This may be simply a nuisance to ignore from time to time.

@Naatan when you get back can you comment on this?

**Comment by manngo** [comment]
I have some more information on this bug.

Sometimes, the tooltip will pop up even if another application is in front. If it does, I need to switch back to Komodo Edit just to move the focus away from the offending line and then switch back to what I’m doing.

Is there any way of switching off the tooltip altogether for now?

**Comment by mitchell-as** [comment]
Short of turning off syntax checking, there is no way to disable the tooltip.

**Comment by Naatan** [comment]
I've noticed this too, I'm not sure what causes it but I'll for sure have a look at it.

**Comment by cgchoffman** [comment]
FYI, Firefox does this occasionally too.  I've noticed it anyway.  Maybe there is an upstream patch.

**Comment by manngo** [comment]
I have an interim solution. I edited `userChrome.css` and brute-forced the tooltip into the status bar.

I display my status bar at the bottom — if you display it up the top then one of the values will need to change.

	popupset>tooltip {
		/*	display: none; */ /* this would be a desperation measure */
		position: fixed;
		bottom: 26px !important;	/*	this moves down after the first display */
		right: 440px;
		background-color: transparent !important;
	}
	popupset>tooltip>description {	/* somehow, this is always visible */
		border: thin solid #ccc !important;
		background-color: #f8f8f8 !important;
	}

I don’t understand why the tooltip is always visible when I do this, but it’s only small and unobtrusive in its new location.

This always-visible tooltip looks remarkably similar to a small rectangle which has often haunted the screen in previous incarnations of Komodo Edit, so I wonder whether this is a long-standing bug.

BTW I’m not too sure about the Enhancement label. I see this more of a usability bug.

**Comment by manngo** [comment]
More information. I think it’s the same bug.

When, in another application (not Firefox), I move my mouse over the position where the document tabs in Komodo Edit are in the background, the tab tooltip pops up anyway.

Here is an example in  program called SvgLab:

![tooltip](https://cloud.githubusercontent.com/assets/3796633/17399820/bfa3fc30-5a87-11e6-9003-9245c600091f.png)


The tooltop shows a README.md file.

**Comment by Naatan** [comment]
huh. That's very odd. Starting to sound more like a Mozilla bug :\
