### ISSUE TITLE
Unreliable Python syntax checking tooltips

### ISSUE THREAD

**Issue by mithat** [Komodo/KomodoEdit#1811]
### Short Summary
Pylint and Python interpreter syntax checking seem to be detecting errors and warnings just fine, producing the expected squiggly underline on statements with errors and warnings. However, when hovering over the error or warning, a tooltip appear indicating what the problem is almost never appears.

### Steps to Reproduce
1. Configure Komodo Edit to use pylint or Python interpreter syntax checking for Python3. (I haven't tried Python2 or other languages' syntax checking.)
2. Create a Python project and introduce an error.

### Expected results
A tooltip appears when hovering over underlined statements.

### Actual results
A tooltip only very occasionally and inconsistently appears when hovering over underlined statements.

### Platform Information

*Komodo Edit or IDE?*  Edit
*Komodo Version?* Komodo Edit, version 10.0.1, build 17276, platform linux-x86_64.
Built on Wed Jun 15 08:25:28 2016.
*Operating System (and version)?* Debian sid and Xfce

### Additional Information
I tried this on a fresh Komodo profile.
Current least bad workaround: Open the bottom pane and show the Syntax Checking Status tab.

**Comment by Defman21** [comment]
This is how my config for Python 3 looks like

![Imgur](http://i.imgur.com/TRWhSm3.png)

and with this code:
```
def wefwefwef
end
```

I'm not able to reproduce the issue. The underline appears on the first line and when I hover over it, I see the description of the error.

Are you using non-standard DPI? (not 96) Or non-standard text scaling factor? (not 1.0)

**Comment by Defman21** [comment]
Ok I've tried both pylint and pep8 and even if there are two errors/warnings on the same line, everything works fine. A sample code would be much appreciated.

**Comment by mithat** [comment]
@Defman21, I am using 120 dpi. When I disable the custom DPI or set it to 96 dpi, the tooltips appear as expected.

**Comment by mitchell-as** [comment]
Thanks for the report. @Naatan this is not a Scintilla problem because Scintilla is not displaying the tooltips -- we are.

**Comment by Defman21** [comment]
@mitchell-as https://github.com/Komodo/KomodoEdit/issues/1681
