### ISSUE TITLE
Can't debug on local perl script

### ISSUE THREAD

**Issue by nsnake** [Komodo/KomodoEdit#1812]
### Short Summary

I use IDE 10.0.1 to debug perl 5.22 and 5.24 script, bug when i debug, nothing had show in 'Debug Output'
I had set  "debugger logging" and see:

I make sure below：

```
Configuring the Perl Debugger
To specify which Perl interpreter Komodo uses to debug and run Perl programs:

On the Edit menu, click Preferences.
In the Preferences dialog box under Languages, click Perl. Komodo searches for Perl interpreters on your system and displays them in the drop-down list.
If the preferred interpreter is in this list, click to select it. If not, click Browse to locate it.
Click OK.
To start a local Perl debugging session:

On the Debug menu or Debug Toolbar, click Go/Continue or Step In to invoke the debugging session. See Komodo Debugger Functions for full instructions on using Komodo's debugging functionality.
```

```
Logging enabled at Tue Jul 19 12:16:56 2016
**** $hostname=_
In main, E:\dev_app\perl\0.pl, 2
file:E:\dev_app\perl\0.pl, line:2, package:main
Skipping package [DB::DbgrCommon]
Skipping package [DB::DbgrCommon]
Skipping package [DB::DbgrCommon]
Skipping package [DB::DbgrCommon]
Skipping package [DB::DbgrCommon]
Skipping package [DB::DbgrCommon]
Skipping package [DB::DbgrCommon]
In bytes, D:/usr/lib/bytes_heavy.pl, 5
file:D:/usr/lib/bytes_heavy.pl, line:5, package:bytes
```
### Platform Information

_Komodo Edit or IDE?_  IDE
_Komodo Version?_      version 10.0.1, build 89237, platform win32-x86. Built on Wed Jun 15 10:57:56 2016
_Operating System (and version)?_  Windows10
### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by mitchell-as** [comment]
Would you please re-phrase the ticket? I really do not understand what the problem is. It sounds like debugging works, but you are not getting any output text in the "Debug Output" pane?

**Comment by cgchoffman** [comment]
Please provide sample code as well.

**Comment by nsnake** [comment]
@mitchell-as  
You are right, there is not getting any output text in the "Debug Output" pane.

**Comment by nsnake** [comment]
@cgchoffman 
There is code：
`print '1';`

**Comment by mitchell-as** [comment]
So you have configured Komodo's Perl interpreter to point to your Perl 5.22 or 5.24, you've opened a Perl script that simply says `print '1'`, clicked the "Play" button (or Debug > Go/Continue), and you get nothing in the output window?

Your "debug log" looks weird. Is Perl installed correctly? Can you go to your folder in a Windows command prompt and run `perl your_file.pl` and get the output `1`?

**Comment by nsnake** [comment]
@mitchell-as  yes, I have write a perl script  with oneline '**print 1**;'  and named _1.pl_  with komodo,  had save and click 'Start or continue debugging'  button,  but nothing in the output.
Other, i open cmd and input perl _1.p_l , i had seen output **1**

**Comment by Naatan** [comment]
Please share your error log after reproducing the issue.

You can find your error log at Help > Troubleshooting > View Log File.

**Comment by mitchell-as** [comment]
@nsnake there must be something wrong with your Perl configuration. I am getting the expected result with your parameters.

In addition to what Naatan requested, does Komodo list Perl debugging as "Ready" in Help > Check Configuration?

**Comment by nsnake** [comment]
@Naatan 
`[2016-07-28 17:01:18,987] [ERROR] dbgp.server: session cmdloop exception - sending session stop command
Traceback (most recent call last):
  File "D:\Komodo\lib\mozilla\python\komodo\dbgp\serverBase.py", line 66, in _cmdloop
    self._handleIncoming()
  File "D:\Komodo\lib\mozilla\python\komodo\dbgp\serverBase.py", line 167, in _handleIncoming
    self._dispatch(size,response)
  File "D:\Komodo\lib\mozilla\python\komodo\dbgp\server.py", line 791, in _dispatch
    dom = minidom.parseString(response)
  File "D:\Komodo\lib\python\lib\xml\dom\minidom.py", line 1931, in parseString
    return expatbuilder.parseString(string)
  File "D:\Komodo\lib\python\lib\xml\dom\expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "D:\Komodo\lib\python\lib\xml\dom\expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
ExpatError: not well-formed (invalid token): line 8, column 82
Exception in thread dbgp server cmdloop:
Traceback (most recent call last):
  File "D:\Komodo\lib\python\lib\threading.py", line 808, in __bootstrap_inner
    self.run()
  File "D:\Komodo\lib\python\lib\threading.py", line 761, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\Komodo\lib\mozilla\python\komodo\dbgp\serverBase.py", line 77, in _cmdloop
    self._dispatch(len(msg), msg)
  File "D:\Komodo\lib\mozilla\python\komodo\dbgp\server.py", line 808, in _dispatch
    self._responseHandler(root)
  File "D:\Komodo\lib\mozilla\python\komodo\dbgp\server.py", line 1094, in _responseHandler
    raise DBGPError('response without a transaction id')
koDBGPError: -1 (response without a transaction id)`

**Comment by Naatan** [comment]
Please share your full error log, not just a portion of it. That definitely looks relevant, but we'd need to see the full log to determine exactly how relevant.
