### ISSUE TITLE
Create project in current path (based on opened path in Places)

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1813]
### Short Summary

Usually I create a structure of my project in terminal, and in Komodo I actually work on it. However, creating a komodo project file for my project requires too much actions: find the menu item to start creating a project, then navigating to the folder where you want to create a project and then creating a project file.

A new item in the context menu of Places widget would be much appreciated or at least automatic navigation to current places directory in the path chooser dialog.

**Comment by mitchell-as** [comment]
Thanks for the suggestion.

Either a new menu item would work, or Project > New Project should open the file browser in places' root directory.
