### ISSUE TITLE
SASS Linter does not check syntax on Ruby 2.3

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1814]
### Short Summary

Not sure what's going on there, but Sass is always using buitlin scssLinterType for me (`lib/mozilla/components/koCSSExLinter.py:KoSCSSCommonLinter`)

But if I pick SCSS, it works fine for SASS file and it's invalid behavior because SCSS requires `--scss` to be passed to `sass` executable.

In my `prefs.xml`, I have these settings:
```
<string id="sassDefaultInterpreter">/home/defman/.rbenv/shims/sass</string>
<string id="sassLinterType">path</string>
```

Executing `require('ko/prefs').getString("sassLinterType")` in the console outputs `path`.

**Comment by Defman21** [comment]
Also you should avoid using sass/scss cache (`-C` option).

**Comment by Defman21** [comment]
Also cmd should not use `rubyPath` at all, this causes the `ruby: no Ruby script found in input  (LoadError)` error in `p.communicate()[1]`

**Comment by Defman21** [comment]
The regex objects for errors are outdated as well.

SCSS Error:

```
Error: Invalid CSS after "...t-align: center": expected "{", was ""\n        on line 8 of /tmp/tmpXD3qoJ.scss\n  Use --trace for backtrace.\n
```

SASS error:
the same

SASS warning:

```
WARNING on line 2 of /tmp/tmpDpTHws.sass:\nThis selector doesn't have any properties and will not be rendered.\n
```

**Comment by Defman21** [comment]
I've fixed it, but it would require a review.

**Comment by Defman21** [comment]
Well, Komodo still should recognize which type of scssLinterType is good for sass, I made this change just to make it work.

**Comment by mitchell-as** [comment]
What version of SASS are you using @Defman21?

**Comment by Defman21** [comment]
@mitchell-as the latest one: Sass 3.4.22 (Selective Steve)

**Comment by Defman21** [comment]
Also, is there a reason to pass SASS code to CSS linter? This would bring a lot of syntax errors. SCSS is very similar to CSS except for the variables stuff and mixins, but SASS does not even have `{}` in the code.

**Comment by mitchell-as** [comment]
I just had a go at this and I'm not seeing any issues with a default Komodo install (clean profile) with SASS (not SCSS). I have the following:

```
h1
    color: red;
```

and I get the proper warning on line 2 about ';' not expected. (Thus it appears the regexes are working.)

If you could provide some more specific information on what you're getting vs. what you're expecting, that would help me identify whether or not there is a problem here. The original ticket text is not very clear to me.

**Comment by Defman21** [comment]
I'm going to try it with a clean profile. I have both `sass` and `scss` installed though in my home directory via `gem install sass` (no sudo there). Is it the same for you?

**Comment by Defman21** [comment]
Ahh yeah, I've modified the code so a clean profile won't help. However, I'll try with an older nightly.

**Comment by Defman21** [comment]
Also my ruby version is:
```
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
```

I've tried with an older version of Komodo (Komodo IDE, version 10.0.0, build 89159, platform linux-x86_64. Built on Wed May 11 15:27:38 2016.). My SASS interpreter is `/home/defman/.rbenv/shims/sass` and with your sample I don't see any errors.

**Comment by Defman21** [comment]
Okay, I found what's the problem in detecting sass executable:
When I run it from the terminal, PATH contains sass executable.
When I run it from an icon, PATH does not contain sass executable. However, this still does not solve the problem.

**Comment by mitchell-as** [comment]
```
$ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
$ sass -v
Sass 3.4.22 (Selective Steve)
```

Sass checking is working as expected (same as my previous post). This sounds like a configuration issue on your part. (Perhaps your Komodo sass path is pointing to an older version of sass than your `$ which sass` points to.)

I'm going to close this issue. Please open a new ticket if you do find a reproducible bug. This ticket is too confusing as it is :)

**Comment by Defman21** [comment]
It points to the same path.

**Comment by Defman21** [comment]
I've tried to see what's in `stderr` variable and this is what I have:
```
koCSSLinter: ruby: no Ruby script found in input (LoadError)
```
