### ISSUE TITLE
Color picker does not work in SASS

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1815]
### Short Summary

title. It does not recognize any sort of color (hex, rgb, color name, etc.)

**Comment by mitchell-as** [comment]
Thanks for the report.

**Comment by Naatan** [comment]
Works in SCSS, not in SASS.

@mitchell-as I suspect this is some sort of language toggle?

**Comment by Naatan** [comment]
I almost feel we should just enable this by default for all languages. If it annoys people they can just disable the color picker hyperlinking but I can't think of many cases where a color value could be missinterpreted. Thoughts?

**Comment by cgchoffman** [comment]
I have no issue with that @Naatan.

**Comment by Naatan** [comment]
Mitchell agreed too (long as we exclude color constants).

Committed here - https://github.com/Komodo/KomodoEdit/commit/0c15f43bbd3eea2bb430d9459c23105db2146d7e

**Comment by Naatan** [comment]
Anyone reading this that doesn't like the change, you can revert the behavior with:

```
require("ko/prefs").setBoolean('hyperlinksColorpickerAlwaysEnable', false)
```
