### ISSUE TITLE
Refresh view still not working on FTP remote folder

### ISSUE THREAD

**Issue by tunedin76** [Komodo/KomodoEdit#1816]
### Short Summary

Added file to server, and refresh does not update projectr

### Steps to Reproduce
Add file to server, have a project that points to server remote folder, try to refresh

### Expected results
File to show

### Actual results

New File does not show up

### Platform Information

Komodo IDE 10.0.1 on Win 10 Pro

### Additional Information

 -- eg. Error logs, screenshots, workarounds --
Have to still shutdown IDE

**Comment by cgchoffman** [comment]
@tunedin76 what are you doing?  This is the third time you've filed the same bug.  If you have additional information please report in the original: https://github.com/Komodo/KomodoEdit/issues/1714

**Comment by Defman21** [comment]
@tunedin76 I'll notice you once the issue will be fixed. No need to remind the devs.

**Comment by cgchoffman** [comment]
@Defman21 , @tunedin76 filed the original bug.  They will get a notice when it's fixed.

**Comment by Defman21** [comment]
Maybe he's not familiar with GitHub :P

**Comment by tunedin76** [comment]
Maybe better communication with bug reports.


Get Outlook for Android






On Tue, Jul 19, 2016 at 12:30 PM -0400, "Sergey Kislyakov" <notifications@github.com> wrote:





Maybe he's not familiar with GitHub :P

---

**Comment by cgchoffman** [comment]
> Maybe better communication with bug reports.
> 
> 
> Get Outlook for Android

I'm not sure what you mean here. If you have a suggestions for a better work flow here in our issue handling then please state them in the http://forum.komodoide.com/ where we invite our users to discuss exactly this type of topic.

If you are missing information about your issue that you filed already then the appropriate place to respond is in your original ticket: https://github.com/Komodo/KomodoEdit/issues/1714

If you log into Github you will have a better experience.  Please don't file additional tickets for the exact same issue. It waists your time and ours as the ticket will just be closed and results in no trail of history.  Ping the original ticket for follow up.
