### ISSUE TITLE
Auto-indentation for SASS is missing

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1818]
### Short Summary

title

### Steps to Reproduce

```sass
body |
```

Press Enter

### Expected results

```sass
body
    |
```

### Actual results

```sass
body
|
```

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.0.1
*Operating System (and version)?* elementary OS 0.4

| is referring to the caret position.

**Comment by cgchoffman** [comment]
Was this working in previous version @Defman21 ?

**Comment by Defman21** [comment]
Gonna try!

**Comment by Defman21** [comment]
Tested on Komodo Edit, version 9.3.2, build 16460, platform linux-x86_64.
Built on Thu Dec 10 19:37:22 2015.

It's not working there.

**Comment by cgchoffman** [comment]
It may have never been implemented I guess.  Thanks for reporting @Defman21

**Comment by Defman21** [comment]
I think so.

**Comment by mitchell-as** [comment]
Moved back in priority. SASS syntax is a second-class citizen to SCSS and is less-widely used from what I gather.

**Comment by mitchell-as** [comment]
After spending some more time on this, I discovered we'd have to define a `_shouldIndent()` override function in `koSassLanguage` class that determines whether or not an indent should be done. This function needs to be able to recognize all the subtle details of when the next line should be indented. For example, `h1` should indent the next line, but not `h1,` (the in the case of a list of selectors). `h1[attr="value"]` should indent, as should `=border-radius($radius)`, but not `+border-radius(10px)`.

This will require a non-trivial amount of time to get right -- it's not as simple as checking if there's a selector immediately preceding the newline. Given SASS's stature against SCSS, I really don't see it worth investing any time into. It's also not clear to me SASS's future in version 4 (the indentation-based syntax that is).

All that said, I'm going to close this issue.

**Comment by Defman21** [comment]
I agree with that. I'm not sure what's the future of SASS, more over it's very complicated to provide something like that.
