### ISSUE TITLE
Cursor doesn't change to arrow when hovering over gutter 

### ISSUE THREAD

**Issue by rodsimpson** [Komodo/KomodoEdit#182]
If you go to set a break point, the cursor doesn't change to a pointer - it stays as the text edit icon.

**Comment by Naatan** [comment]
Probably a windows only bug. Does this happen for you @cgchoffman ?

**Comment by rodsimpson** [comment]
i am running on mac

**Comment by cgchoffman** [comment]
Not seeing this on Windows.
