### ISSUE TITLE
SASS Linter does not recognize WARNING messages

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1820]
### Short Summary

With this code:
```sass
body
    
```

There will be a warning:

```
WARNING on line 1 of /home/defman/sample.sass:
This selector doesn't have any properties and will not be rendered.
```

Komodo does not recognize it in any form.

**Comment by Defman21** [comment]
@mitchell-as would you mind accept a PR for this one? :)

**Comment by mitchell-as** [comment]
Thanks for the report. The linter will need to add a warning pattern matcher, but since Sass is second-class to SCSS, it's not high on the priority list.

**Comment by mitchell-as** [comment]
@Defman21 go for it!
