### ISSUE TITLE
Edit window jumps around when using the up/down keys if the "Find in Files" window is open 

### ISSUE THREAD

**Issue by i-shenl** [Komodo/KomodoEdit#1828]
### Short Summary

The edit window (coding area) jumps around when using the up/down keys while the "Find in Files" window is open. It jumps back and forth between the the beginning of the file and where the cursor currently is. 

Reproduced on Linux but unsure if reproducible on other platforms. 
### Steps to Reproduce

1) Open the attached perl file
2) locate the subroutine in this file and put the cursor inside the body of it
3) open the "Find in Files.." window
4) press the up and down keys. 
### Expected results

Should not jump around.
### Actual results

Note that while in the subroutine, the scrolling works ok. When the cursor leaves the subroutine, the editor window jumps back and forth as in the description.
### Platform Information

_Komodo Edit or IDE?_  Komodo IDE 
_Komodo Version?_ X
_Operating System (and version)?_ Linux
### Additional Information

 -- eg. Error logs, screenshots, workarounds --
[CustomerBuilds.txt](https://github.com/Komodo/KomodoEdit/files/372270/CustomerBuilds.txt)

**Comment by Defman21** [comment]
There's no Find in Files window anymore, instead of it there's a pane. I'm not able to reproduce the issue either.

**Comment by cgchoffman** [comment]
He's referring to the pane @Defman21.

**Comment by Defman21** [comment]
So in your file I put my cursor on line 121 (I assume it's the body of a subroutine, not familiar with Perl). I opened the pane, it automatically focused on the find input, I pressed the up key about 20 times, then I clicked on the editor area. My cursor is still on line 121. Am I doing something wrong?

**Comment by cgchoffman** [comment]
@i-shenl i'm not actually able to reproduce this even though you showed me that it happens, in person.  As @Defman21 alludes to, it's not clear how you get your cursor back into the editor once you've opened the Find in files pane.

Could you reproduce the issues and post your *Help > Troubleshooting > View Log File* to see if there is anything in there?
