### ISSUE TITLE
Can't change color of php variables

### ISSUE THREAD

**Issue by rodsimpson** [Komodo/KomodoEdit#183]
Trying to change the color of php variables, like $my_var. I am pretty sure I went through all settings, but there doesn't seem to be a setting to do this.

**Comment by Naatan** [comment]
Make sure you enable "Show Advanced" at the bottom left of the preferences dialog, then go to "Language Specific" and select "PHP".

Granted we definitely need to add "Variables" to the Common Syntax pane.

**Comment by rodsimpson** [comment]
Thanks!  FWIW, the IDE crashed when I did this.  But relaunching and trying again worked.
