### ISSUE TITLE
Error when saving xhtml file

### ISSUE THREAD

**Issue by gabittma** [Komodo/KomodoEdit#1830]
### Short Summary
Error showed up when trying to save the file. A dialog box requested I post the error here.

### Steps to Reproduce
In consistently happened while trying to save the file. The IDE did also seem to be sluggish with short hangs around the same time.

### Expected results
File saves

### Actual results
Error message

### Platform Information

*Komodo Edit or IDE?*  IDE
*Komodo Version?* 10.0.1
*Operating System (and version)?*  Windows 10

### Additional Information

[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIDocument.isEncodable]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: vieweditor :: _validateEncoding :: line 1407"  data: no]

Exception: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIDocument.isEncodable]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: vieweditor :: _validateEncoding :: line 1407"  data: no]

Traceback:
_validateEncoding@vieweditor:1407:16
save@vieweditor:1504:21
viewManager.prototype.do_cmd_save@chrome://komodo/content/views.js:1907:4
xtk.Controller.prototype.doCommand@chrome://xtk/content/controller.js:61:8
command_doCommand@chrome://komodo/content/library/commands.js:239:0
command_doCommandAsync@chrome://komodo/content/library/commands.js:191:0
@chrome://komodo/content/keybindings/keybindings.js line 2562 > eval:1:0
this.Manager.prototype.evalCommand@chrome://komodo/content/keybindings/keybindings.js:2562:22
this.Manager.prototype.keypressHandler@chrome://komodo/content/keybindings/keybindings.js:2733:16
gKeyHandler@chrome://komodo/content/keybindings/keybindings.js:2617:4

Komodo IDE, version 10.0.1, build 89237.
Built on Wed Jun 15 10:57:56 2016.

**Comment by mitchell-as** [comment]
Hi, your file probably has an invalid character in it. Did you copy-paste text in from another file or program (e.g. web browser)? What encoding are you using? Komodo will not save files in a particular encoding when there is an invalid character in that file.

**Comment by gabittma** [comment]
The encoding was UTF-8. There was no content copied and pasted it was just opened with Komodo then all edits were typed in directly. The hangs didn't seem to be predictable in any noticeable way other than being paired with the problem saving.

After closing and reopening Komodo then coming back to the file I was greeted with the not saved properly message. I'm not sure how many changes were lost in the restore, but after that it worked as expected again.

**Comment by mitchell-as** [comment]
That is quite odd. Are you typing on an international keyboard? If you find a way to consistently reproduce this problem, that would be very helpful.

**Comment by gabittma** [comment]
It's a US keyboard. If the problem duplicates I'll let you know. It's not a critical issue for me since restarting to fix it seemed to work.

**Comment by mitchell-as** [comment]
Okay, thanks for the response. I'll close this ticket in the meantime.
