### ISSUE TITLE
Tcl Highlight - no highlight on substitute variable in curly braces

### ISSUE THREAD

**Issue by mickey263** [Komodo/KomodoEdit#1831]
### Short Summary

TCL variable substitution in curly braces isn't highlighted

### Steps to Reproduce

```
set foo 1
puts $foo
puts ${foo}
```

### Expected results

${foo} is highlighted

### Actual results

${foo} isn't highlighted

### Platform Information

Komodo IDE 10.0.1 build 89237
win32-x86

### Additional Information

 -- eg. Error logs, screenshots, workarounds --
![capture](https://cloud.githubusercontent.com/assets/14289352/16985233/71b4e3ea-4e7f-11e6-976a-4752535f4b66.JPG)

**Comment by mickey263** [comment]
For my own information, why highlight the $ ?

**Comment by mitchell-as** [comment]
Hi, I'm not able to reproduce this. See image below.

**Comment by mickey263** [comment]
In your example, foo is not highlighted.

Here with default color scheme : 

![capture1](https://cloud.githubusercontent.com/assets/14289352/16990460/5fa98890-4e98-11e6-899a-ce209fdba711.JPG)

**Comment by Defman21** [comment]
Mitchell, he means variable highlighting

**Comment by mitchell-as** [comment]
Okay, then there is no bug here with unhighlighted variables in braces (`${foo}`). As for highlighting the `foo` in `set foo 1`, this is not trivial to do from Komodo's perspective and is another issue anyway.

**Comment by Defman21** [comment]
@mitchell-as you still don't get me. When you press a variable, Komodo underlines references to this variable in the code. $ErrorIndex is underlined, but ${ErrorIndex} is not.

**Comment by mitchell-as** [comment]
Mind your tone @Defman21. I'm not addressing you. I'm addressing the original ticket.

**Comment by mickey263** [comment]
Sorry i have a begginer level in English, so i have difficulties to explain my issue.

@Defman21 understood my problem. It's well in the case when i click on a variable, komodo don't highlight all corresponding variable "tag" in my code

**Comment by mickey263** [comment]
I understand what you talk about @mitchell-as.
Syntax color is ok, but not the komodo function : 
```
Variable Highlighting
Click on a variable to see all occurrences.
```

**Comment by Defman21** [comment]
@mitchell-as sorry for that. I didn't want to sound in bad tone at all :)

**Comment by mitchell-as** [comment]
Thank you both for your clarification. I understand the problem now. With my previous experience, the word "highlight" to me always means "syntax highlight" :) I have trouble realizing it can also mean "variable highlight". This is a bug that I will look into fixing.

**Comment by mickey263** [comment]
Thanks ! For me too, highlight mean syntax color ^^
Komodo introduces a double mean...
