### ISSUE TITLE
Komodo crash

### ISSUE THREAD

**Issue by mkimberling** [Komodo/KomodoEdit#1835]
### Short Summary
Komodo just crashed while I was editing Python code.

### Steps to Reproduce
I don't think I could reproduce the crash.  The program had been running all day.  I wasn't typing anything when it crashed.

[pystderr.txt](https://github.com/Komodo/KomodoEdit/files/374979/pystderr.txt)

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by cgchoffman** [comment]
I'm sorry but there isn't anything we can do with this.  We need reproduction steps at least.
