### ISSUE TITLE
Help button in File Preferences window prompts for access to github account

### ISSUE THREAD

**Issue by damienprystay** [Komodo/KomodoEdit#1838]
### Short Summary
The Help button in the File Preferences window links to docs.komodoide.com in such a way that github requires me to first grant the site limited access to my github account.

### Steps to Reproduce
1. Open a file in Komodo
2. Edit -> Current File Preferences...
3. Editor -> Indentation -> Click the 'Help' button

### Expected results
The relevant documentation is opened in a browser window (as it does when selecting Help from the global Preferences window).

### Actual results
The browser opens to a github.com page requiring that I grant the documentation site access to my public data (https://github.com/login/oauth/authorize?...):
![screenshot](https://cloud.githubusercontent.com/assets/3590102/17040670/fb83f1ac-4f55-11e6-976f-a52f433af85f.png)

### Platform Information
Komodo IDE 10.0.1, Mac OS 10.11.5

**Comment by cgchoffman** [comment]
HA, looks like those docs don't exist.  It's asking you to sign in so you can create the page you're trying to access I believe.

**Comment by Defman21** [comment]
I'll try that since I can edit the wiki.

**Comment by Defman21** [comment]
Yep @cgchoffman you're right. There's no http://docs.komodoide.com/Manual/indentation page.

**Comment by cgchoffman** [comment]
They are all broken in the File Level Prefs :(  New docs -1.  This might have to wait a bit.
