### ISSUE TITLE
Commando Sections does not work if no files are opened

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1843]
### Short Summary

Open a file with some sections in it (a css file for example). Then close it, open Sections and try to open a section from it. Nothing will happen. There are no errors in the log, I'm able to reproduce it in Safe Mode.

**Comment by Naatan** [comment]
If the file is not indexed the sections scope will not show it unless it is open. To index it you have to start editing it. There is a bug open to move this indexing process to somewhere more automated.
