### ISSUE TITLE
Unexpected Undo Of More Than One Previous Operation

### ISSUE THREAD

**Issue by bfailing** [Komodo/KomodoEdit#1846]
### Short Summary
Pressing Ctrl+Z (or clicking the Undo icon) causes undo of more than previous operation where multiple characters are entered without a carriage return and where multiple carriage returns are removed.  

### Steps to Reproduce
Add multiple characters to a single line.  Press Ctrl+Z (or click the Undo icon) and watch the entire string of characters disappear.

Alternatively, add multiple carriage returns to a document.  Remove the carriage returns (and/or spaces if spaces added because of the auto-indent feature) by pressing the delete key.  Press Ctrl+Z (or click the Undo icon) and watch all of the carriage returns (and spaces if removed) re-appear.

### Expected results
If adding multiple characters or carriage returns, undo should remove a single character or carriage return.  If removing multiple characters or carriage returns, undo should add a single character or carriage return. 

### Platform Information
Komodo Edit 10
Windows 10 

### Additional Information
This seems to have been brought up before (e.g., https://community.activestate.com/node/9184 and https://community.activestate.com/forum/undoredo-acting-weird-more-single-operations-are-undone) with previous versions.

**Comment by mitchell-as** [comment]
This is by design. Our editing component, Scintilla, appears to group undo-able actions by strings of insert/delete operations. From my experience, many modern applications do this too -- they do not have single character undo/redo.
