### ISSUE TITLE
Publishing Dialog seems to hang when pushing large projects

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1848]
### Short Summary

It seems that Komodo's publishing dialog isn't usable for large project if you want to do an initial push.  It's much easier to use an external tool.
### Steps to Reproduce
- Create a publishing config with a drupal install or something with 1000s of files
- configure an empty remote so everything has to be pushed
- Start the process, Komodo checks file state then you can click _synchronize_
### Expected results

I would expect it to take a while but give me immediate feedback that it's at least doing something
### Actual results

Nothing seems to happen.  It looks like the dialog simply hangs.  I didn't wait long enough to see what eventually happens because regardless this is bad.  It could be broken or it's just taking a long time to give feedback but either way this needs a better workflow.

**Comment by Naatan** [comment]
Too big for 10.1 to handle, lets do this for 11.

**Comment by cgchoffman** [comment]
I'm going to keep this on 11.1 because I know exactly where to look for this code and I just need to confirm what I think is happening is actually happening and see what I think i can do about it.
Note to self, this is where it's happening for file transfer: mhttps://github.com/Komodo/KomodoIDE/blob/master//src/modules/publishing/components/koRemoteTransfer.py#L385

Just need to find what hooks into the progress bar from the koPubSettings classes.

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/77127b22daeab5d25fb24a88a25d37421d463f39

**Comment by cgchoffman** [comment]
Komodo will now give helpful feed back as it checks file state so you know it's actually doing something.
Notes:
- I had no FAST way to determine how many files I was going to be checking remotely so remote state check just shows which files are being checked so you know it's still working.

Now that I think about it, the issue was that if it's a first sync scenario you had no prior knowledge of the remote directory so you didn't know what you were looking at.  If I just checked for existing info I could have used that for a *count* of remote files and if it didn't exist, fall back to just listing the file names.  Oh well, too late.  Future reference.
