### ISSUE TITLE
JavaScript Syntax Checking: jshint giving conflicting message

### ISSUE THREAD

**Issue by manngo** [Komodo/KomodoEdit#1850]
### Short Summary

With `jshint` checking turned on, a number of warnings appear. If I try to turn them off using `jshint` comments, another warning appears saying that ES5 option is now set per default. The other warnings remain.
### Steps to Reproduce

Example 1

Enter a non-ascii character (eg … ellipsis) anywhere, such as in a comment.
The unsafe character warning (may get silently deleted) appears.

Add /\* jshint -W100 */ which is supposed to suppress the above warning.

This seems to be an old story for this feature.

Example 2

To suppress warnings about unused parameters, add /\* jshint unused:var */.

Same results.
### Expected results

Everything is OK and no warnings
### Actual results

(a) it doesn’t work; (b) I get a new warning: ES5 Option is now set per default.
### Platform Information

_Komodo Edit or IDE?_ Edit
_Komodo Version?_ 10.0.1
_Operating System (and version)?_ OSX 10.11.6
### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by mitchell-as** [comment]
Hi, will you please give a code example for (b)? I don't know enough about JavaScript or jshint to trigger that. Thanks!

**Comment by Defman21** [comment]
@manngo the proper way to not report about unused vars is:
```
/* jshint unused: true */
```

**Comment by Defman21** [comment]
```
/* jshint -W100 */
console.log("•");
```

Also works fine for me using the built-in jshint.

**Comment by manngo** [comment]
OK, some corrections.

- The `jshint -W100` characters seem to be working, as long as I put it at the beginning (naturally!)
- I did not mention that I included `'use strict';` at the beggining
- The correct syntax for my example above is: `/* jshint unused: vars */` (not `var`).

According to the documentation [unused](http://jshint.com/docs/options/#unused), `unused: vars` is correct if you want to check for unused variables but not function parameters (for example, I routinely include an `event` parameter for event handlers, even if I don’t end up using it).

I have attached a screen shot of the result. I have added comments mentioning the jshint error.

![jshint-warnings](https://cloud.githubusercontent.com/assets/3796633/17160976/ba820e5a-53ec-11e6-8945-c5ccf7e0a295.png)

Rather distracting.

Thanks

**Comment by Naatan** [comment]
@manngo please see @mitchell-as's post, he is requesting sample code.

**Comment by mitchell-as** [comment]
@manngo FYI `/* jshint unused: true */` is telling jshint to flag unused variables, so that is why you're getting those warnings. However, I've fixed an earlier bug that would still flag unused variables (#1725).

Are you using your own version of jshint? I'm using Komodo's and am not seeing the ES5 option you mention. What are your JSHint Options in Edit > Preferences > Syntax & Spell Checking > JavaScript > JSHint? Mine are `moz=true unused=true esnext=true`.
