### ISSUE TITLE
Komodo 10 SVN Integration is not working

### ISSUE THREAD

**Issue by daniel-hughes** [Komodo/KomodoEdit#1853]
### Short Summary
When I try to commit a dialog is popped with a list of files in scope to be committed. System reports that "no files checked" even when I select files to commit in the dialog.

### Steps to Reproduce
1. Modify a file checked out from Subversion
2. Right click and select commit
3. Click the file in the list in the dialog to select it
4. Click "Commit"
5. See error message!

### Expected results
File should commit to Subversion repository

### Actual results
Error message

### Platform Information

*Komodo Edit or IDE?*  IDE
*Komodo Version?*  version 10.0.1, build 89237, platform macosx. Built on Wed Jun 15
*Operating System (and version)?* OS X 10.11.5

### Additional Information

![errormessage](https://cloud.githubusercontent.com/assets/4395843/17162591/56a16460-5385-11e6-9768-6ae889b58e9b.png)
 -- eg. Error logs, screenshots, workarounds --

**Comment by Naatan** [comment]
Please double click the files that you wish to commit.

**Comment by daniel-hughes** [comment]
Thank you.

Sincerely,
A Moron

**Comment by cgchoffman** [comment]
We still like you.  BTW the UI will be changed slightly in the next release to make that action more obvious.
