### ISSUE TITLE
console.js fails to handle exceptions

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1856]
### Short Summary

A command was failing in the js console for me and I didn't understand why until I noticed the error I've copied below, in my error logs.  

The command I was running was as follows:

```
var commands  = require("ko/commands");
commands.register("alertCarey", function(){alert("carey")},{label:"Carey Alerts!"})
```

When you press enter the error below should appear in your logs and the input never leaves the input field in the console though it is appended to the output area.
### Additional Information

```
[2016-07-27 13:43:07,293] [ERROR] console-logger: TypeError: ex.stack is undefined (2) in chrome://console/content/js/console.js:207
Traceback (most recent call last):
  File "chrome://console/content/js/console.js", line 207, in 
```

**Comment by Defman21** [comment]
https://github.com/Komodo/KomodoEdit/commit/2fe624de80a76e0965055eaff54f6847af4d7225

**Comment by Defman21** [comment]
@cgchoffman @Naatan could you close this issue? :)
