### ISSUE TITLE
Tutorial sizing pushes right side of Komodo out of the screen when Komodo is too narrow

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1857]
### Short Summary

When you start a tutorial while Komodo is below a certain width, the far right contents will get pushed way out (off the screen if the right side is against the edge of the screen).  I've attached a gif that shows what happens.  Note that If you grab one of the edges of the Komodo window and resize horizontally the window will POP to a width that works (DOMi tells me this width is 1170).  Something not shown by the gif is that making the tutorial bigger causes the Left pane to shrink which doesn't seem like it should happen.
![capture](https://cloud.githubusercontent.com/assets/655154/17223494/a7525f90-54b1-11e6-82f4-5f21e93ca3fb.PNG)

This seems like the scaling issue where Komodo would vertically get stuck and when you resized it up it would snap to a better size.

### Steps to Reproduce

- Size Komodo window to less than 1170.  1000 should do it
- Open the Get Started tutorial, Toolbox > Tutorials > Getting Started

### Expected results

Nothing special

### Actual results

![tutorial-sizing](https://cloud.githubusercontent.com/assets/655154/17223546/e09d1272-54b1-11e6-8047-cc98c1d0338c.gif)

### Platform Information

*Komodo  IDE* 
*Komodo Version 10.1 internal nightly* 
*Operating System (and version)* Win 10

**Comment by Naatan** [comment]
I'm unable to reproduce this. Can you try it in safe-mode?

**Comment by cgchoffman** [comment]
Yes, I am able to hit this in safe-mode.

**Comment by Naatan** [comment]
Ok, I'll have a look at this next week. Feel free to have a dig yourself if you feel like it ..

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/55c7478f0b73860cdbb1cf3296aa208781a48658
