### ISSUE TITLE
Tutorial isn't dragable and has moz border when popped

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1858]
### Short Summary

Native window borders turned off.  You can't move the tutorial window when it's popped out of the Komodo UI.  It also has a border. You also can't resize them.
![capture](https://cloud.githubusercontent.com/assets/655154/17224679/c828d820-54b6-11e6-8472-5fc706817457.PNG)

**Comment by Naatan** [comment]
Is this with or without native borders?

**Comment by cgchoffman** [comment]
Sorry, that's an important detail.  This is without native borders.  Adding that to the description.

**Comment by Naatan** [comment]
Does using native borders make a difference?

**Comment by cgchoffman** [comment]
It does not.

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/f25150ce502787ad06ecae28dbeb6607f28c2ae6
