### ISSUE TITLE
Komodo hangs up on any sequence like this #something=>[enter]

### ISSUE THREAD

**Issue by bilikaz** [Komodo/KomodoEdit#186]
when you type in editor anything like this:
#something=>
and when you press enter it hangs...
you can type anything between # and => and it will stop responding after pressing enter, if you leave spaces and hit enter it crashes too, but if you leave some chars on end like
#something=> sdsdf
it doesn't crash

**Comment by bilikaz** [comment]
This but is on komodoIde, didn't tested on edit.

**Comment by bilikaz** [comment]
After some more experiments i found out that it hangs on any text or sequence ending > and then pressing [enter], but this sequence must be first line

**Comment by Naatan** [comment]
Thanks for reporting @bilikaz, getting right on this.

**Comment by Naatan** [comment]
Gonna leave this open for a better (more intelligent) fix, this fix may have side effects.

@toddw-as could you review and let me know if this is safe to push into 9.0.1?

Thanks
