### ISSUE TITLE
SASS check for CSS: invalid errors

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1861]
### Short Summary

Go to Prefs - Syntax & Spell Checking. Enable SASS checking for CSS language.

Write this code:

```
@keyframes test {
    from {
        color: red;
    }
    
    to {
        color: blue;
    }
}

.div {
    animation-name: test;
}
```

You'll see some errors.
Save this code to a file.

Now run `sass -c --trace file.css`. You'd get an empty output which means that there are no errors.

Sass 3.4.22 (Selective Steve)
rbenv 1.0.0-21-g9fdce5d

**Comment by mitchell-as** [comment]
What is the error that you get? I'm not getting one. I removed the last `}` to ensure my syntax checking is working and it does.

**Comment by Defman21** [comment]
![errs](https://i.imgur.com/uyJ3Hhz.png)

**Comment by mitchell-as** [comment]
That doesn't look like the sass syntax checker, but a CSS syntax checker, and one that doesn't understand CSS3. Are you sure you're using the right syntax checker?

**Comment by Defman21** [comment]
![yes](https://i.imgur.com/Kih35ZU.png)

I'd test if it's on my PATH though, I think that there's a fallback on Komodo's old CSS checker.

**Comment by Defman21** [comment]
It's on my path I'm sure, I've run Komodo from the terminal so it will get the environment from `~/.zshrc`. Still the same errors. I think it's related to https://github.com/Komodo/KomodoEdit/pull/1827

**Comment by Defman21** [comment]
Okay it's not. I'm going to try safe mode.

**Comment by Defman21** [comment]
I'm able to reproduce it in safe mode as well.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoEdit/commit/d605b6f7cb54d7b68cc9ee2064d7c0b8cbbe7b2b. It's not SASS at all, but based on Komodo's codeintel. Change your language to Sass or SCSS if you want to use a dedicated parser.

**Comment by Defman21** [comment]
Thanks for the clarification! :)

**Comment by Defman21** [comment]
Hmm, IIRC someone from the devs asked to remove that option at all. It's legacy and CSS2 only, don't see any reasons to keep it. @Naatan I think you were the one who wanted to do that.
