### ISSUE TITLE
Tutorial: auto-moving window behaves oddly.

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1862]
### Short Summary

When I get to step 4 of the tutorial, suddenly the tutorial pops out of the Komodo window and sits beside the Prefs Window.    A couple oddities comeup from this:
1. if the prefs window is too far to the right then the tutorial pushes itself off screen.
2. when you move the prefs window it's unclear when the tutorial will move to match it.

It's a handy feature but it's behaving oddly and makes it frustrating to use.  Doesn't help that the tutorial can't be moved right now #1858.

**Comment by Naatan** [comment]
2. is not really fixable, it already moves as fast as it can.

As for 1, I think for the purpose of this tutorial we should just ensure that the window is centered on screen, that'll be easier than handling all the potential edge cases with it being on the edge of the screen.

**Comment by cgchoffman** [comment]
2. Another option, it could not move at all and just stay pinned.  It's definitely nice that it sticks to the prefs window but the fact that it can lag up to almost 10 seconds before snapping to the prefs dialog is very very jarring and confusing.

**Comment by Naatan** [comment]
It shouldn't lag 10 seconds, at most like a second. I'll have a closer look.

**Comment by cgchoffman** [comment]
Sorry I don't HAVE a repro.  It's very random.  I just start moving the dialog around and eventually the tutorial will stop following it.  If it just popped around within a second that would be fine with me.

**Comment by Naatan** [comment]
Fixed with https://github.com/Komodo/KomodoIDE/commit/36cdf40c194a968b53810dace7039bfb9aead785

Note the window still won't move until you finish moving the other window. There doesn't appear to be a way for us to get events while the window is being moved, only after it has finished moving.
