### ISSUE TITLE
Tutorial Getting started: Step 6 "Places Widget" link doesn't do anything.

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1863]
### Short Summary

Title.  It either doesn't do anything or I don't notice it doing anything.  i assumed it would flash the project cog but it doesn't.  I'm not sure what it's supposed to do (UX comment, I know I can look at the code)

**Comment by Naatan** [comment]
It shows the Places widget (if it's not already shown). I suppose it should also do a callout of sorts.

**Comment by cgchoffman** [comment]
That's what I was expecting (because I knew at somepoint the tutorial does that) but nothing happened.

**Comment by Naatan** [comment]
Fixed with https://github.com/Komodo/KomodoIDE/commit/765f579b57a4beaa1bdd485dd69ca6804906b252
