### ISSUE TITLE
Tutorial highlighting button looks odd

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1865]
### Short Summary

On slide 2  when you click the "eye icon" link or any other link on that step, the highlighting of the button looks really odd.  It leaves the toolbox unshaded but shades a portion of the screen far to the right of the Komodo window.  See attached gif.

![show-button](https://cloud.githubusercontent.com/assets/655154/17226144/c8193fcc-54bc-11e6-909a-b0b830a29bc7.gif)

**Comment by cgchoffman** [comment]
I think this might actually be related to #1857 somehow.  I'm not sure what size of window I had but at some point it highlighted the eye toolbar button perfectly...I can't get that size back anymore though.  Def doesn't work full screen.

**Comment by Naatan** [comment]
Can you reproduce this in safe mode without first reproducing #1857?

**Comment by cgchoffman** [comment]
Yes:
- Safe mode
- Full screen Komodo so I don't hit #1857 
- start tutorial and repro bug

**Comment by cgchoffman** [comment]
Oh sorry it does look like #1857 does seem to cause this issue.  I can't lockdown clear anti-reproduction steps though.  I'm not sure how to get it into a state where it DOESN'T happen.

**Comment by Naatan** [comment]
Fixed with https://github.com/Komodo/KomodoIDE/commit/a619f42c2176353886d154ea2e54469bf9cafe35
