### ISSUE TITLE
hyperlink triggered inside strings

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1869]
### Short Summary

I was trying to do multi cursor editing in JS file but Komodo kept trying to give me information about the word I was currently hovering on. See the *RIGHT HERE* in the example below.  I was pressing *Ctrl + Click* at the end of  the `toolbar` string and Komodo would popup an "Online Definition" dialog stating that it can't find the definition of the selected symbol.  That's not right, right?

```
 this.enableToolbars = function()
    {
        if ($("#main-toolboxrow-wrapper").visible() &&
            $("#toolbox_side").visible() &&
            $("#middle-toolboxrow").visible())
        {
            tutorials.logicCallout({element:'#main-toolboxrow-wrapper', message: "This is the Komodo side toolbar"}); // ****RIGHT HERE ****
        }
        else
        {
            ko.uilayout.setToolbarsVisibility(true, 'main-toolboxrow-wrapper');
            ko.uilayout.setToolbarsVisibility(true, 'toolbox_side');
            $("#middle-toolboxrow", w).attr("kohidden", "false");
            tutorials.logicCallout({element:'#main-toolboxrow-wrapper', message: 'This is the Komodo main toolbar'});
        }
        
    };
```

**Comment by mitchell-as** [comment]
You need to disable "Enable hyperlinking to definition" in Edit > Preferences > Smart Editing. The problem you are experiencing is just a limitation since hyperlinks also use Ctrl+Click.

**Comment by cgchoffman** [comment]
I was not aware that strings were included in hyperlinking.  Why would that ever be needed?  Also, if this is supposed to happen then when can I ever user ctrl+click to do multi cursor editing?

**Comment by cgchoffman** [comment]
I re-opened this because this is a bug in my mind btw.  If this is the way it's supposed to work then something seems wrong.

**Comment by Defman21** [comment]
I, personally, don't see any reasons to have hyperlinking enabled in strings. It could be useful in comments, but strings are strings. I'd want to have multi-cursor works in strings rather than hyperlinking.

**Comment by mitchell-as** [comment]
Python docstrings would use Ctrl+Click hyperlinking.

Ctrl+Click multi-caret was introduced relatively recently against the already existing Ctrl+Click hyperlinking. By trying to make both of them work together, some odd edge cases are popping up.

**Comment by Defman21** [comment]
Python docstrings and strings are equal for Komodo? I don't mean the color, it seems to be identical.

**Comment by cgchoffman** [comment]
> Ctrl+Click multi-caret was introduced relatively recently

I remember it being added and I remember it was a pain for you.  Unfortunately, I've never been able to get it to work when I actually want it. I thought for SURE a string would be a safe location to use it.  

> Python docstrings would use Ctrl+Click hyperlinking.

I would think that most times a person using ctrl+click in a string does not want go-to-definition.
