### ISSUE TITLE
Regression in Replace

### ISSUE THREAD

**Issue by garak** [Komodo/KomodoEdit#187]
In IDE 8 the Replace dialog was opening with empty "Replace with" text box.
Now, in IDE 9, the same text box contains the text of previous "Find & Replace" dialog.
This is really annoying, since you're forced to select the text box and remove the old content, before being able to write a new content.
It would be nice to get, at least, an option to restore old behavior.

**Comment by Naatan** [comment]
Closing this as the find dialog has been completely overhauled in 9.3.
