### ISSUE TITLE
Update Perl Remote Debugging Docs

### ISSUE THREAD

**Issue by mitchell-as** [Komodo/KomodoEdit#1870]
### Short Summary

Komodo's remote Perl debugging documentation needs to be updated to reflect the fact that the dbgp library needs to be installed to a path that contains "dbgp/perllib" in order to skip over debugger internals. (See #309)

**Comment by Naatan** [comment]
It'd make sense if we packaged the bits in such a way that it already has this structure.

**Comment by mitchell-as** [comment]
Documentation updated.
