### ISSUE TITLE
Tutorial callout is offset by native window border when they are enabled

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1872]
### Short Summary

![capture](https://cloud.githubusercontent.com/assets/655154/17262778/599a99fc-5592-11e6-860d-e546da84fa02.PNG)

**Comment by Naatan** [comment]
!&#*@^#*

**Comment by Defman21** [comment]
![c00l memes](https://cloud.githubusercontent.com/assets/7100645/17264719/f219df50-55f9-11e6-95af-6e6515febf06.png)

**Comment by Defman21** [comment]
![memed](https://cloud.githubusercontent.com/assets/7100645/17264774/5ccd0214-55fa-11e6-9202-a5fdb0d0205e.png)

**Comment by Naatan** [comment]
Fixed with https://github.com/Komodo/KomodoIDE/commit/a822d4de7395b4c5be6be1bf84bcea545ecfad13
