### ISSUE TITLE
Code on page seems to disappear when you minimize the app

### ISSUE THREAD

**Issue by ginko** [Komodo/KomodoEdit#1873]
### Short Summary
code on page seems to disappear when you minimize the application window and then maximize it.

### Steps to Reproduce
Open any file with code and minimize the application window then maximize it again.

### Expected results
code should stay visible on the page.

### Actual results
page is blank

### Platform Information

Komodo IDE
Komodo Version 10.0.1
Mac OS X (10.11.6)?

### Additional Information

  the work around is to bring the window app and then open another file and then toggle back to the original file. I've attached a screenshot to show the blank page
<img width="1430" alt="screen shot 2016-07-29 at 4 15 13 pm" src="https://cloud.githubusercontent.com/assets/183611/17262128/b0205702-55a7-11e6-889b-06ad786fddc7.png">

**Comment by cgchoffman** [comment]
This will be fixed in an upcoming release: https://github.com/Komodo/KomodoEdit/issues/564
