### ISSUE TITLE
Komodo 10.0.1 macosx Editor window does not refresh after hiding and revealing Komodo

### ISSUE THREAD

**Issue by davefultz** [Komodo/KomodoEdit#1875]
### Short Summary
With source code on view in the central pane, if you hide Komodo then reveal it again the pane is blank. Switching to another tab and back or closing and reopening the file restores the display. This also occurs with the output pane.

### Platform Information

*Komodo Edit or IDE?* 
IDE
*Komodo Version?* 
Komodo IDE, version 10.0.1, build 89237, platform macosx
*Operating System (and version)?* 
Mac OS X 10.11.6
### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by Defman21** [comment]
https://github.com/Komodo/KomodoEdit/issues/564
