### ISSUE TITLE
Hyperlink works once again after closing the color picker

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1876]
### Short Summary

I'm able to reproduce it 100%. 

### Steps to Reproduce

Hold Ctrl and click on a color. Press Esc. Hover on another color.

### Expected results

I won't highlight in any form.

### Actual results

It highlights like with Ctrl being pressed.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.0.1
*Operating System (and version)?* elementary OS 0.4

### Additional Information
It does work not only for colors. Everything that Komodo could recognize as a hyperlink will be highlighted with the corresponding indicator.

Pressing Esc workarounds the problem.

**Comment by mitchell-as** [comment]
Thanks for the report. It sounds like the color picker panel is not forwarding the 'escape' keypress on to Scintilla to cancel the "control mode" or whatever was enabled at the time of Ctrl+Clicking.

**Comment by Defman21** [comment]
Actually, I'm able to reproduce it by just closing the color picker with Ok or Cancel button. Not every time, but very often.

**Comment by Naatan** [comment]
I'm unable to reproduce this, nor is there any logic that I can see which tracks whether a link is currently active.

@Defman21 can you try safe-mode?

**Comment by Defman21** [comment]
Yes, I can.

**Comment by Defman21** [comment]
Wait.. I'm using a Komodo Edit build so it's kinda clear. I've made no changes to it except for adding alpha control in color picker, which is not related to hyperlinking. I'm able to reproduce the issue. I'm using Gala WM.

**Comment by Naatan** [comment]
Can you reproduce it on IDE?

**Comment by mitchell-as** [comment]
I can. Otherwise I would not have accepted the ticket. I should have explicitly stated that I reproduced the issue in my original response though.

**Comment by Defman21** [comment]
@Naatan yep, it's a bit random, but after 1-2 opens of colorpicker I'm able to reproduce it.

**Comment by Naatan** [comment]
Weird, I can trigger it as many times as I want without issues. Have you found any workarounds?

**Comment by Defman21** [comment]
Pressing Esc after closing the dialog.

**Comment by Naatan** [comment]
As in pressing it twice? Your reproduction steps specifically state pressing ESC as one of the steps to reproduce.

**Comment by Defman21** [comment]
* You open the color picker
* You close it somehow (Ok, Cancel of Esc)
* You press Esc <- workaround

**Comment by Naatan** [comment]
Ok. When it isnt working does the editor have focus? (ie. do you see the caret blinking).

**Comment by Defman21** [comment]
When I'm able to reproduce it, I can click on hyperlinks (after closing the picker it will run the related actions). When I'm not - then it does not have any focus.

**Comment by Naatan** [comment]
Ok so the links work but they won't highlight?

**Comment by Defman21** [comment]
I'll record a video.
