### ISSUE TITLE
Perl unit testing doesn't support TAP::Harness and Test::More and doesn't perform multiple tests.

### ISSUE THREAD

**Issue by dnadle** [Komodo/KomodoEdit#1878]
### Short Summary

Komodo perl unit testing unnecessarily requires a Makefile. Makefiles generated by Ext::MakeMaker only recognize tests in the t/ folder and not any subdirectories. The prove command provided by Test::Harness is superior to 'make test' because it recurses subdirectories of t/, and does not require a Makefile.

One can get 'make test' to run the prove command with the following:

```
#Makefile
test:
    perl "-MApp::Prove" "-e" "my $$app = App::Prove->new; $$app->process_args(('-r', 't')); $$app->run();"
```

It seems that whether the Makefile is produced by Ext:MakeMaker or is configured manually to use the prove command, _only a single .t file is executed_. Other .t files are not listed in the Unit Testing panel and their output is not shown.

**My strong preference for a fix to this bug is to support TAP::Harness with prove-like functionality and have 'make test' be an alternative test plan type.**
### Steps to Reproduce
1. Create a perl project with a t/ folder and write more than one test file ending in .t and using Test::More.
2. Generate a Makefile, either by writing a Makefile.PL, using the prove command above, or using an ExtUtils command like:

```
#Makefile
test:
    perl "-MExtUtils::Command::MM" "-e" "test_harness(0, ())" t/*.t
```
1. Create and execute a Perl - TAP test plan in Komodo IDE.
### Expected results

In the case of a generated Makefile or one using ExtUtils, all .t files in the t/ folder list in the Unit Tests panel, execute, and display output and pass/fail results.

In the case of a Makefile using App::Prove, all .t files in the t/folder _and subfolders_ list, execute, and display.
### Actual results

In all cases only a single .t file is listed. It's not clear how many execute. The summary of tests passed, failures, and errors on the IDE's bottom status pane are all zeros.

Unit Testing displays no output when tests pass but doesn't handle test failures correctly. The output panel shows '***\* Unrecongnized input'.
### Platform Information

_Komodo IDE_ 
_v 10.0.1_ 
_Windows 10 x64_

**Comment by mitchell-as** [comment]
@Naatan has been working on unittest improvements that among other things fix this issue.
