### ISSUE TITLE
Whitespace and parenthesis/braces misalignment in Vim mode

### ISSUE THREAD

**Issue by ANSI-C** [Komodo/KomodoEdit#1879]
### Short Summary
When in Vim mode with parentheses braces closed to each other, like   "){" the Vim shortcut does not land exactly on the related parentheses, but to the character next to it. Furthermore the editor displays whitespaces, especially at line ending that do not actually exist in the file.

### Steps to Reproduce

function example(){

}

paste in the editor and try to jump betwenn parentheses by % Vim shortcut

### Expected results

it should work exactly like Vim

### Actual results

it jumps to next character or to non existent whitespace

### Platform Information

*Komodo Edit or IDE?*
Both

*Komodo Version?* 8.5, 9.x, 10.x

*Operating System (and version)?* 
Windows 8.1, Linux (Cinnamon, Mate)

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by mitchell-as** [comment]
Thanks for the report. I can reproduce this when placing the caret on the `{` character. Instead of jumping to `}` it jumps to the last `e` in `example`.

**Comment by ANSI-C** [comment]
Hello Sir,

I would like to remark another bug in Komodo 8.5, tab settings are not 
honored, even after program restart, see below:

one tab key hit inserts 4 spaces (weird!) and a second tab key hit 
replaces the 4 spaces with one tab.

As you can see, indentation guides are completely wrong as well. Tried 
to fix this with no success.


Il 02/08/2016 16:31, mitchell ha scritto:

**Comment by mitchell-as** [comment]
Please upgrade to the latest Komodo 10, where indentation problems have been largely sorted out. If you still experience bugs, please file a new issue.

**Comment by ANSI-C** [comment]
Just bought it, thank you.


Il 12/08/2016 16:04, mitchell ha scritto:

**Comment by ANSI-C** [comment]
I can confirm this is fixed in 10.1.0, thanks. The phantom unexistent space at end of lines in Vim mode with block cursor style is still there.

**Comment by mitchell-as** [comment]
The "phantom space" is just how our editor is designed. There's no easy way around this minor imperfection.
