### ISSUE TITLE
Auto-detect indentation & tab settings does not work.

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1884]
### Short Summary

Create a file using nano with some tabs there:

```
	hello();
```
(don't copy this sample, GitHub converts tabs to 4 spaces).

Ensure you have the auto-detect tabs & indentation setting enabled.

Open this file and press Tab. Spaces will be inserted. To workaround the problem, I have to change per-file settings and make it use tabs.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.0.1
*Operating System (and version)?* elementary OS 0.4

**Comment by mitchell-as** [comment]
This was fixed in a previous issue.

**Comment by Defman21** [comment]
It will be in 10.1?

**Comment by mitchell-as** [comment]
Yes.

**Comment by Defman21** [comment]
Okay, thanks for the info :)
