### ISSUE TITLE
Editor content disappears when application is minimized and restored

### ISSUE THREAD

**Issue by edthorne** [Komodo/KomodoEdit#1888]
### Short Summary
The editor contents disappear when minimizing and restoring the application. The text is visible here:
<img width="901" alt="visible" src="https://cloud.githubusercontent.com/assets/1951518/17378288/ee965156-5982-11e6-9037-792469812a97.png">
After minimization and restoring it's no longer visible:
<img width="901" alt="hidden" src="https://cloud.githubusercontent.com/assets/1951518/17378287/ee954d92-5982-11e6-8da7-1d13830cc3e3.png">

### Steps to Reproduce
Open a file or use a new one.
Minimize the application.
Restore the application.
Observe the editor contents are not visible.

### Expected results
The editor contents are visible.

### Actual results
The editor contents are not visible.

### Platform Information
Komodo Edit, version 10.0.1, build 17276, platform macosx.
Built on Wed Jun 15 08:25:23 2016. 
OS X El Capitan 10.11.5

### Additional Information
Switching tabs or dragging the application to another window restores the editor contents.

**Comment by Defman21** [comment]
https://github.com/Komodo/KomodoEdit/issues/564

**Comment by edthorne** [comment]
Thanks.
