### ISSUE TITLE
Komodo IDE 9 high cpu-load on idle

### ISSUE THREAD

**Issue by andreas-bergstrom** [Komodo/KomodoEdit#189]
Running Komodo IDE 9 on OS X 10.10, Macbook Air mid-14. Komodo IDE with a small project opened idles at 20-30%. Even closing the workspace and just keeping Komodo IDE opened with a barebone window keeps load at the same.

However, Komodo Edit with opened project and files stays below 10% during active use. What is making Komodo IDE using that much CPU without doing anything?

Edit: I was using version 8 of Komodo Edit, gonna try 9 now.

**Comment by toddw-as** [comment]
Try the [nightly](http://downloads.activestate.com/Komodo/nightly/komodoide/latest/), as I suspect it might be this problem:
https://bugs.activestate.com/show_bug.cgi?id=106458

**Comment by cgchoffman** [comment]
Please re-open if the nightly doesn't resolve you issue @andreas-bergstrom
