### ISSUE TITLE
async/await throwing JSHint errors

### ISSUE THREAD

**Issue by shelby3** [Komodo/KomodoEdit#1890]
The JSHint included does not support async/await. This feature is incredibly important for modern asynchronous programming.

Please try to invest some resources to fix this.

**Comment by Naatan** [comment]
Could you provide some sample code that JSHint is failing on?

**Comment by damianb** [comment]
Totally valid.  Running KIDE 10.2.1.

```
const koa = require('koa')
const fs = require('fs-extra')
const app = new koa()
app.use(async function(ctx) {
	let to = './'
	let from = './there/'
	let someVar = await fs.copy(to, from)
	ctx.body = JSON.stringify(someVar)
})
```
Komodo barks with the following: 

* Line 4: "Expected ')' and instead saw 'function'.

Basically, it sees the async as being a var and not a keyword...and then sees the word "function" and flips its shit, thinking there's supposed to be a comma there, etc. etc.

* Line 9: "Expected an identifier and instead saw ')'.  Expected an assignment or function call and instead saw an expression.

This is all related to nodejs 7.something (I can't recall at the moment) adding async/await support natively.

**Comment by cgchoffman** [comment]
Reproduced.  Thanks for the repro code @damianb.

**Comment by damianb** [comment]
Looks mostly like it's JSHint's fault by the way, after doing a bit of reading; they've been caught unprepared for the merge and general availability of async/await.  

Related:
https://github.com/jshint/jshint/issues/2601
https://github.com/jshint/jshint/issues/2604
https://github.com/jshint/jshint/pull/2077

**Comment by Naatan** [comment]
jshint has been problematic for us for a variety of reasons, we may have to revisit our JS linting in the not so distant future.

**Comment by Naatan** [comment]
Fixed with https://github.com/Komodo/KomodoEdit/commit/acba82380f3b9031ef73339122d308fbb897ec17
