### ISSUE TITLE
Enhance support for C and C++

### ISSUE THREAD

**Issue by Graar** [Komodo/KomodoEdit#1893]
### Short Summary
This is an enhancement request for improved support for C and C++

I have many more enhancement requests, but I am not sure this is the correct place to do it.  Please append this issue with details of how to file enhancements.

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by Naatan** [comment]
We're not a C/C++ IDE. We have some limited support for those developers who have to use C/C++ as part of their toolchain on occasion, but beyond that we have no immediate plans to extend our support for these languages.

May I ask what functionality in particular you are interested in? And how do you see Komodo as being a more feasible solution than long standing C/C++ IDE's?

**Comment by Naatan** [comment]
I'm closing this for now, but please provide any feedback you have. If we end up doing something around this in the future it is unlikely that we would track it via our bugtracker as it would be a high level "feature".

**Comment by Graar** [comment]
Sorry, I thought the value proposition of Komodo was 'one editor for all your languages'.  

Which other IDE's would you recommend ?  Maybe I have been using the wrong IDE all along.  Which languages do you regard Komodo as being targetted at ?  Or maybe better which ones do you not regard it as being suitable for ?

The features I had in mind were things like support in the code browser for C++

Is this the correct forum to log enhancement requests, if not how do I do that ?

**Comment by Defman21** [comment]
Komodo is targeted for web development (HTML, CSS (including SASS, SCSS and Less), Javascript, Coffeescript), dynamic interpreted languages (such as Ruby, Python and PHP) and server-side languages (Ruby, Python, PHP, maybe Tcl and Perl, I don't use them personally).

I've used Code::Block on Linux when I was trying to learn C++.

**Comment by Naatan** [comment]
@Graar That's marketing for ya. The message there is we are "hopefully" one IDE for all your languages, we certainly have that potential as the languages we do support tend to be used together. Realistically though, we cannot support every single language.

The main languages Komodo is targeted at are on the splash page of komodoide.com, right above the fold.

This is indeed the correct forum to log enhancement requests, but at the end of the day we will decide whether or not an enhancement request is within the scope of our application. I'm not saying C/C++ isn't, it's just unlikely. And in the event that we do add more support for it it will be a major feature that would not be tracked via the bug tracker, it would be tracked internally.
