### ISSUE TITLE
Custom command on breakpoint hit

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1898]
### Short Summary

This is a very interesting feature in XCode. You can setup a custom command which will be called on breakpoint hit. I'd want to have access to Komodo SDK from that scope (so I can do alerts or whatever, even sending some info to my servers).

There should be some variables:

%B - Breakpoint name (`%FILE:%LINE`)
%H - Hit count
%S - scope (variable, return in function, etc.)
%V - scope value

**Comment by mitchell-as** [comment]
I think this is beyond the scope of Komodo. I don't see a very convincing use-case for this for the work involved. If you can think of something concrete, we can revisit this.

**Comment by Naatan** [comment]
I'm with @mitchell-as on this, any of the logic you are speaking of you could just run in your actual code itself. You basically want virtual code blocks that execute within your code?

A proper use-case would be good.

**Comment by Defman21** [comment]
I don't have an use-case right now but if I'll find it, I'll post it here.
