### ISSUE TITLE
Watch variables is broken

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1899]
### Short Summary

I'm trying to debug a Ruby script. I've tried to add a variable to the watching list. At first look, it didn't even appear. Then I tried to click somewhere in the watching list area and hit a treechildren which seems to be the "variable". I can't delete or edit that though.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.0.1
*Operating System (and version)?* elementary OS 0.4

**Comment by Defman21** [comment]
Ahh sorry. They will appear once I continue the debugging. But still, I'd rather to see variables I've added.

**Comment by Defman21** [comment]
They are appear once I've done with waiting for STDIN.

**Comment by mitchell-as** [comment]
It sounds like your Ruby script hasn't started executing then. Watch variables work in a simple Ruby script test for me. In order to reproduce your problem case, please provide a script and some steps.

**Comment by Defman21** [comment]
```
var1 = [(print "Hello: "), gets.rstrip][1]

colors = "red, green, blue"

colors << var1
```

Put your breakpoint at line 3 and add `colors` to the watching list. It won't appear until you'll enter something for the prompt.

**Comment by mitchell-as** [comment]
Okay, this is just how Ruby works. You've made it block waiting for stdin. No debugger commands from Komodo will run until stdin is read.

**Comment by Defman21** [comment]
Thanks for clarifying :)
