### ISSUE TITLE
non-alpha-numeric chars break callbacks and callouts

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1906]
### Short Summary

`[Komodo.com][callback:openPackageWebsite]` doesn't work
`[Komodo.com][callout:openPackageWebsite]` same.
Yes those are defined properly in their respective locations.  They just show up as the above when the tutorial runs.

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/b948c4e88afdc836332fcfd706db2d4fd6636ea5
