### ISSUE TITLE
publishing pull actions don't reload effected open files content

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1916]
### Short Summary

Pub.pull actions should reload any files that are open and effected

### Repro steps
- Configure/open a publishing folder
- open a file from that folder
- edit the remote version of that file
- right click the file in Places OR it's file tab > Publishing > Pull (you can use force as well)

The file gets pulled and saved to disk but it's not reloaded in the Komodo view.

**Comment by Naatan** [comment]
Fixed in https://github.com/Komodo/KomodoIDE/commit/f6b419cc56728dec0d7edd4d78d5ed4d6addfb34
