### ISSUE TITLE
Completion suggestions appear on top of selection

### ISSUE THREAD

**Issue by gushogg-blake** [Komodo/KomodoEdit#1919]
### Short Summary

The auto-complete box comes up on top of the text you're currently typing, so you can't see what you're typing.

### Steps to Reproduce

Start typing something to bring up auto-complete

### Expected results

Auto-complete appears *below* current line

### Actual results

Auto-complete appears *on* current line

### Platform Information

*Komodo Edit or IDE?* Edit
*Komodo Version?* 9
*Operating System (and version)?* Linux Mint 17 Mate edition

### Additional Information

Screen recording: https://youtu.be/ylQFaTnsSjs

**Comment by Defman21** [comment]
http://downloads.activestate.com/Komodo/nightly/komodoedit/latest/ please try a nightly build. This should be fixed.

**Comment by mitchell-as** [comment]
Hi, you can either reset your text/font scaling to 1.0 or upgrade to Komodo Edit 10. That will make the problem go away.
