### ISSUE TITLE
ColorPicker: $<color constant> is a hyperlink

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1920]
### Short Summary

I think it's related to https://github.com/Komodo/KomodoEdit/issues/1815

With this code:

```scss
.red {
    color: $red;
}
```

Press Ctrl and hover over `$red`. It will be recognized as a hyperlink. You can open color picker and change `red` part to something else, `$` will be there.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.1 beta
*Operating System (and version)?* Ubuntu 16.04

**Comment by Naatan** [comment]
Fixed thanks to @babobski - https://github.com/Komodo/KomodoEdit/pull/2066
