### ISSUE TITLE
Switcing from Interface to Editor in Color scheme editor does not change the preview

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1921]
### Short Summary

title.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.1 beta
*Operating System (and version)?* Ubuntu 16.04

### Additional Information

Switching from Interface/Editor to any language and then back to Editor brings the preview ability back.

**Comment by Naatan** [comment]
Works for me. Please try again with the new build.

**Comment by Defman21** [comment]
Confirmed. Switching to Interface opens my custom css. Switching to Editor does nothing - still displaying my custom css.
