### ISSUE TITLE
Color scheme editor: Editor/Whitespace background icon is incorrect.

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1924]
### Short Summary

I think it should use `Font/Background` color. I don't know what's using right now, but it's not `Font/Background` :)

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.1 beta
*Operating System (and version)?* Ubuntu 16.04

**Comment by Naatan** [comment]
Can you elaborate? The color scheme editor doesnt have icons ..

**Comment by Defman21** [comment]
It is. Those "A" things.

**Comment by Naatan** [comment]
Ahh, those aren't icons, but fair enough.

They are using the foreground and background color of the property that they are editing. If that's not the case for some of them please specify which ones.

**Comment by Defman21** [comment]
Editor/Whitespace. There's no "background" color for this one, and it's using something different. I think it should use the background color of Font item.

**Comment by Naatan** [comment]
The background color IS the color. The foreground is the default text color.

**Comment by Defman21** [comment]
It's not. As you can see, my background color is red, but the preview box (with A inside) for Whitespace using a different color, not background color. I've re-opened Color Scheme Editor so it did rebuild the preview boxes again.

![img](https://i.imgur.com/NN38gHn.png)

**Comment by Naatan** [comment]
What is that screenshot meant to prove? You're showing a red background for the default font but aren't showing it in the list on the left.

**Comment by Defman21** [comment]
![kill me](http://i.imgur.com/NN38gHn.png?1)

**Comment by Naatan** [comment]
Yes, but can you actually show that wwhitespace is red? Your color selection there is not for whitespace. Click on whitespace, then make a screenshot.

**Comment by Defman21** [comment]
Oops, sorry. I thought "A" shows the whitespace color but it seems like whitespace color is the background color of the preview box.
