### ISSUE TITLE
Context Menu opens on other monitor

### ISSUE THREAD

**Issue by MafooUK** [Komodo/KomodoEdit#193]
I have noticed that the context menu in the editor window has a habit of opening on my right monitor (multi monitor 2 screens) when I am over 50% across my left screen.
Example i have 2 Monitors set to 1600x1200 arranged left and right
With Komodo IDE open on the left monitor and I right click in the editor window the following seems to be true.
Right clicking on the left 50% of the editor will make the menu open where you would expect. However if you click anywhere on the right 50% of the left screen in the editor the context menu will appear on the right monitor on the left side of it but level hight where you would expect.
Hopefully teh screenshot below will highlight the issue
![2015-04-22_11-33-26](https://cloud.githubusercontent.com/assets/2932039/7272633/581a8630-e8e4-11e4-922b-7ff864f20ac4.jpg)

**Comment by cgchoffman** [comment]
Interesting.  Nice work finding the exact repro.  I believe someone reported this before but was never able to consistently reproduce it.  Confirmed repro steps.

**Comment by mafoo** [comment]
I have noticed something else I cannot remember if this happened before upgrading to 9.1 or not but it is also happening ...
When hovering over errors to get the pop up message about the error, it is also suffering this same rendering artefact
![2015-06-04_11-37-32](https://cloud.githubusercontent.com/assets/2932039/7982420/fcd1cd1e-0aae-11e5-8f88-b9af220aa4a9.jpg)

**Comment by mafoo** [comment]
I have noticed something else I cannot remember if this happened before upgrading to 9.1 or not but it is also happening ...
When hovering over errors to get the pop up message about the error, it is also suffering this same rendering artefact
![2015-06-04_11-37-32](https://cloud.githubusercontent.com/assets/2932039/7982467/361dc2da-0aaf-11e5-9526-c7a73326283d.jpg)

**Comment by mafoo** [comment]
Still a issue in 9.2.0

**Comment by Naatan** [comment]
@Mook-as any pointers? This seems like a mozilla issue, or at least an issue that exists in the way scintilla was implemented in mozilla (it only happens on right clicks on the editor).

Tagging @mitchell-as as well.

**Comment by jermainerf** [comment]
This is a very annoying issue. I teach a class where everyone uses Komodo Edit and everyone is in the class is complaining about this issue constantly because everyone has dual monitors.
Therefore, bump?

**Comment by Defman21** [comment]
Any dialogs also opens on the wrong screen from a [forum report](http://forum.komodoide.com/t/is-komodo-a-dead-end/2502?u=defman):
>Does not know that it is running in multi monitor setup e.g. I have Komodo on my 'Left' screen, but all dialog opens on the right screen, in other words they do not open relative to the IDE but relative to one screen

**Comment by Naatan** [comment]
I'll have a look at this soon. Worst case I'll just position the context menu manually.
