### ISSUE TITLE
New Tab Open Recent Files Hard to Read in Classic Mode

### ISSUE THREAD

**Issue by mitchell-as** [Komodo/KomodoEdit#1930]
### Short Summary

From http://forum.komodoide.com/t/recent-file-drop-down-list-uses-non-contrasting-colors-very-hard-to-read/3028:

The recent files menu on the new tab screen is hard to read in classic mode.

### Steps to Reproduce

1. Open two files.
2. Close them.
3. Ctrl+T for new tab.
4. Click on the arrow on the "Open File" button.

### Expected results

Easy to read menu options.

### Actual results

Hard to read menu options.

### Platform Information

*Komodo Edit or IDE?* Both
*Komodo Version?* 10.1 beta
*Operating System (and version)?* Any

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

![recent](https://cloud.githubusercontent.com/assets/12902397/17701911/b4f8cf0c-6399-11e6-90b5-6b06d212c6e9.png)

**Comment by jimtut** [comment]
This behavior appears in other drop-downs too.  It's probably all the same element/style, but I thought I'd add it here too.  When editing the properties of a custom toolbox item, the menu that lets you select from all the built-in "variables" behaves the same:

![image](https://cloud.githubusercontent.com/assets/5229799/17703816/092bd27a-63a1-11e6-969f-ca4cb7abfee0.png)

**Comment by jimtut** [comment]
There is a similar style problem, although this one MIGHT be different.  In the Debugging Options window, highlighting text in the input boxes uses a dark blue background and dark text:

![image](https://cloud.githubusercontent.com/assets/5229799/17703904/3de74b8e-63a1-11e6-9737-b51971a79347.png)

**Comment by jimtut** [comment]
That was fast, Naatan!  Is there any LESS/CSS file I can modify here now to get this change with the current version?

Also, what did you think about the 2nd pic I added, showing the color problem in the Debugging Options dialog?

**Comment by Naatan** [comment]
@jimtut you might be able to use this CSS:

```
:not(button) > button:not(.button-toolbar-a):not(.unstyled):not(.spinbuttons-button),
.button
{
	border: 1px solid @border !important;
	
	&:hover label.button-text
	{
		color: @selected-foreground !important;
	}
}
```

But I'm not certain it'll work with just that, as there is some cascading going on.

As for the debugging options issue you raised, please open a new bug for this. I had not seen that, but it illustrates perfectly why we cannot track multiple bugs in one bug report ;)

**Comment by jimtut** [comment]
I know, you're right about the multiple bugs in one ticket!  I was kind of hoping that it's related, but it's probably a different element/style  Bug #1932 created.

**Comment by rjasdf** [comment]
The FIND string field is just as bad as the image provided by jimtut.

Suggest you go through all color schemes and check for contrasting foreground/background.

**Comment by jimtut** [comment]
This is marked as Closed, and the Milestone is set to 10.1, but this bug is still present in 10.1.

**Comment by Naatan** [comment]
Make sure you're using the Classic scheme and not a copy of it.

**Comment by jimtut** [comment]
Sorry, you're right!  Thanks again.

**Comment by rjasdf** [comment]
With 10.1, the Find menu shows black text on dark blue. This is using "Classic" (not a copy of it.)
It is black on white until "pattern not found", then it becomes the unreadable combo.

**Comment by Naatan** [comment]
Please report a new bug.
