### ISSUE TITLE
I reset default as you told me about the error I had... now I can't get projects to work

### ISSUE THREAD

**Issue by tunedin76** [Komodo/KomodoEdit#1931]
### Short Summary
I did what you guys told me - now I am COMPLETLY down this is truly disturbing

I am including this errorlog as a nicety, but as of now I can't see how I am going to be able to use your IDE
[error.zip](https://github.com/Komodo/KomodoEdit/files/420464/error.zip)
.

Windows 10 pro Komodo 10 IDE

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by cgchoffman** [comment]
Did you mean to close this @tunedin76?  are you referencing another ticket?  We need more information to assist you at all.
- What do you mean "I can't get projects to work"?  Projects facilitate many different toolings
- When/why did we tell you to reset to default?
- "now I am COMPLETLY down this is truly disturbing" this is disturbing but I don't know what you mean by it.  I'll admit it's extremely ominous.

**Comment by tunedin76** [comment]
I just did as you told me on another ticket… referencing the FTP remote folder error, copying a file and the opening of KOMODO IDE 10 talking about symlinks. and got real frustrated  
I was told to reset KOMODO to factory and I had a HARD time getting everything to work.  I closed the ticket because it referenced my frustration and gave nothing helpful.

 

I still cannot create, rename, or delete any files in a remote folder.  Same error.  My FTP works 100% with notepad++, WINSCP, filezilla, etc. so.

**Comment by cgchoffman** [comment]
> I just did as you told me on another ticket

Please find that ticket and comment there.  This is not appropriate use of the ticket system.  We cannot track multiple tickets for a single issue.  Please, please stop filing multiple issue reports for  issues you have already reported.  This is not the first time you've done this @tunedin76 .

**Comment by tunedin76** [comment]
That’s why I closed the ticket.
