### ISSUE TITLE
Code disappears after hiding komodo

### ISSUE THREAD

**Issue by djacopille** [Komodo/KomodoEdit#1933]
### Short Summary
After hiding Komodo in split view (possibly other views) and unhiding the code under all active tabs is not displayed.  No amount of moving cursor restores code.  Only switching tabs restores view of code.  If there is only one tab opened in a view then you have to open another file so there is a tab to move to.

### Steps to Reproduce
Open code in split view.  Hide Komodo IDE.  Unhide Komodo IDE.

### Expected results
The IDE should look like it did right before hiding.

### Actual results
No code is shown anywhere under the tabs.

### Platform Information

*Komodo Edit or IDE?*  IDE
*Komodo Version?* 10.0.1
*Operating System (and version)?* 
OS X 10.11.5
### Additional Information

 -- eg. Error logs, screenshots, workarounds --
Screen shot shows two files full of code that you can't see.  Clicking on another tab and then back again shows that code.
![screen shot 2016-08-17 at 9 48 33 am]
(https://cloud.githubusercontent.com/assets/13801692/17738552/a9c65d0e-645f-11e6-9be2-b385606f3bf1.png)

**Comment by mitchell-as** [comment]
This has been reported and fixed.
