### ISSUE TITLE
Komodo IDE 10 Windows msi installer has no validated sigature

### ISSUE THREAD

**Issue by GwenDragon** [Komodo/KomodoEdit#1934]
### Short Summary
The signature of the MSI Installer cant be validated because it is not signed by a public signature

### Steps to Reproduce
Open property of msi package
Inspect tab Digital Signature
In signature list click on Active State
Hit button Details
Information shows that signature of ActiveState Software Inc. cant be validated
![msi-windows-ide-10-signature](https://cloud.githubusercontent.com/assets/501565/17740760/061cb942-649a-11e6-9936-33daa9642ee3.jpg)

### Expected results
Installer has a  signature which can be proofed and is signed by a wellknown third party signer.

### Actual results
Installer uses signature which can not be proofed

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.0.1
*Operating System (and version)?* Windows 10x64 Build 1607

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by Naatan** [comment]
Thanks for reporting, we're tracking this in #600
