### ISSUE TITLE
Big icons on OSX in Dialogs

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1937]
### Short Summary

The big icons are finally gone from places but they have found a new home in the New From Template dialog.

Also happens in the Userscript Properties dialog when choosing an icon, but only when you are looking at font icons, like FontAwesome or Icomoon.

<img width="609" alt="screen shot 2016-08-18 at 11 55 15 am" src="https://cloud.githubusercontent.com/assets/655154/17786716/fd3af112-653a-11e6-9cf9-b207f3ca180f.png">

**Comment by Naatan** [comment]
This dialog doesnt exist any longer in 11.

**Comment by Defman21** [comment]
But it exists in 10.2, isn't it?

**Comment by cgchoffman** [comment]
> But it exists in 10.2, isn't it?

Yes but a fix for this didn't make it into 10.2 and the next release that could include a fix for it would be Komodo 11 but the dialog won't exist at that point.
