### ISSUE TITLE
Unexpected crushes under Mac OS X Yosemite(10.10.5)

### ISSUE THREAD

**Issue by oleksiybondar** [Komodo/KomodoEdit#1940]
### Short Summary
Unexpected crushes under Mac OS X Yosemite(10.10.5 and previous versions builds of Yosemite), It crashes at least 3 times per day
As per debug I would understand if it crashed because of code which leads to 100% CPU load, but 
it's not like this... 
### Steps to Reproduce
I can't provide exact steps to reproduce, because it happens when performing various actions. Mostly I work with python code

, so probably steps to reproduce will be:

1. open some python project in Komodo IDE
2. update/debug some code for quite long time(aka longevity test)

### Expected results
Komodo IDE should not fail while editing/debugging code

### Actual results
unexpected crashes

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.0.1, build 89237
*Operating System (and version)?* Mac OS X Yosemite (10.10.5)

### Additional Information
[pystderr.log.zip](https://github.com/Komodo/KomodoEdit/files/426564/pystderr.log.zip)
 -- eg. Error logs, screenshots, workarounds --

**Comment by Defman21** [comment]
See #1007

**Comment by mitchell-as** [comment]
Hi, please follow the instruction here: https://github.com/Komodo/KomodoEdit/issues/1007#issuecomment-239868151 Your help is crucial to aid is in identifying the bug :)
