### ISSUE TITLE
tcloo breakpoint not respected

### ISSUE THREAD

**Issue by WheelDogs** [Komodo/KomodoEdit#1943]
Komodo IDE doesn't break anywhere with a class create.

o::class create ::dApp::pmgr {
    superclass ::twidget::treeview
    constructor {} {
        my variable Priv

```
    array set Priv [list \
        sn 0 \
        lastopen "" \
        history,max 10 \
        history,list [list] \
        cp,flag "" \
        cp,fpath "" \
        cp,item "" \
        view,flag "ALL" \
    ]
    next .pmgr
```

> ```
>   $::dApp::Obj(layout) pane add "L" [::msgcat::mc "Projects"] .pmgr
>     my configure -iboxobject $::dApp::Obj(ibox)
>     my Tree_Init
> }
> ```
> 
> is where breakpoint is set. Makes no diff where.
### Platform Information

Windows 7
*Komodo IDE 9.3.2

**Comment by WheelDogs** [comment]
Upgraded to 8.6 and Komodo 10; breakpoint effective some of the time.

**Comment by mitchell-as** [comment]
Hi, if you could please rework the code snippet in your original ticket, I'd be able to test it on my end and figure out what the problem is. As it is, I have no idea how to proceed. Thanks.
