### ISSUE TITLE
unable to 'step into code' 

### ISSUE THREAD

**Issue by WheelDogs** [Komodo/KomodoEdit#1945]
### Short Summary
Unable to step into 'sourced' script from within a tcloo method

### Steps to Reproduce

	method Plugin_Init {} {

		set appPath $::dApp::Env(appPath)
		set plugdir [file join $appPath plugins]
		source -encoding utf-8 [file join $plugdir plugin.tcl]

		set dlist [glob -nocomplain -directory $plugdir -types {d} -- *]
		set cut 0
		foreach {d} $dlist {
			set init [file join $d init.tcl]
			if {![file isfile $init]} {continue}
			#set PLUGIN [::dApp::plugin new $d]
			update
->>>>>		source -encoding utf-8 $init
			#if {[string first "_" [file tail $d]] == 0} {$PLUGIN toggle}

		}
	}

### Expected results
able to step into code

### Actual results
processes script and returns

### Platform Information

*KomodoIDE 10 
Win7
tcl/tl 8.6.4
*Operating System (and version)?* 

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by mitchell-as** [comment]
Please go to Edit > Preferences > Languages > Tcl > Debugging > Logging, check "Enable debugger log", set a path, try to reproduce your issue, and then send us the log. I cannot run your code snippet on my own to figure out what is wrong.

You may also include a code snippet that I can run stand-alone that exhibits the problem.

Thanks.

**Comment by WheelDogs** [comment]
Hi,

 

Thought that I updated the bug report. If not apologies.

 

After upgrading to 8.6 and Komodo 10, the problem went away.

 

However !!!

 

I did log another error –

 

Komodo identifies the statement “info class instances ::dApp::plugin” as an incorrect statement.

 

To wit: “invalid option “class” must be: args body ....

 

Clearly, this is contrary to the docs...

 

Please see attached.

 

It does execute properly

 

Rick

**Comment by Defman21** [comment]
Github does not support attachments from e-mail. You should visit https://github.com/Komodo/KomodoEdit/issues/1945 and attach your example.

**Comment by mitchell-as** [comment]
Okay @WheelDogs, you've reported the syntax problem already in #1944. I'll close this issue.

**Comment by WheelDogs** [comment]
Please check out #1960. I just posted.

 

Seems a global issue with ‘info’ and tclOO with regard to recognizing options.

 

It appears that the other, ‘info’ related issue, was closed.

 

Appreciate any help with this issue.
