### ISSUE TITLE
sass imports cause syntax errors

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1946]
### Short Summary

Our syntax checker seems to run scss in a way that relative paths do not get resolved properly.

### Steps to Reproduce

Ensure you have configured the scss syntax checker.

Create 2 files:

*base.scss*:

```
@import "include";
```

*_include.scss* (can be empty)

Now open base.scss

### Expected results

No syntax errors

### Actual results

it will say that the file to import was not found.

### Additional Information

Running `scss -c base.scss` succeeds (no errors).

**Comment by Defman21** [comment]
Because each time you're syntax checking something, Komodo copies the file somewhere in '/tmp/`. Of course there won't be any of your imports :)

**Comment by mitchell-as** [comment]
Related to #1175.
