### ISSUE TITLE
RPM packaging.

### ISSUE THREAD

**Issue by Luke-Nukem** [Komodo/KomodoEdit#1948]
### Short Summary

I've done an initial packaging [here](https://build.opensuse.org/package/show/home:luke_nukem/komodo-edit). It has multiple issues with the included Python libs and how they get compiled.

Instead of listing everything, it is easier to check the build logs in the link above. I am unsure of what direction to take from here, any advice would be appreciated.

### Platform Information

*Komodo Edit* 
*Komodo 10* 
*OpenSUSE Open Build Platform*

**Comment by mitchell-as** [comment]
Please use our forum (http://forum.komodoide.com) for questions like this, as we do not support any 3rd party packaging.

**Comment by Naatan** [comment]
Looks awesome :) If you wouldn't mind posting on the forums about what you did to package Komodo we'll be happy to advice from there.
