### ISSUE TITLE
Exlcude/include functionality for code intel

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#195]
https://bugs.activestate.com/show_bug.cgi?id=74765
Long standing request.

Allow users the ability to exclude folders or patterns from being scanned by code intel.

**Comment by bbak** [comment]
This is badly needed! I neither need all the `node_modules` used for Grunt, nor `bower_components` and similar in CodeIntel, when developing e.g. a (PHP-based) Website - which is just one use case. Please raise Priority on this request.

**Comment by Naatan** [comment]
Prioritized this, because node_module directory trees are a nightmare to scan (takes forever, bogs down codeintel).
