### ISSUE TITLE
Linting warnings don't show with Angular

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1952]
### Short Summary

Title

### Steps to Reproduce

Create a new angular file with contents:

```
<div>
```

### Expected results

Warning that the div doesn't close

### Actual results

No warning

### Additional Information

You have to manually change the syntax prefs for Angular to have error level "Errors and warnings". I suspect this pref is the problem though, as Angular does show errors.

**Comment by mitchell-as** [comment]
This needs to be cherry-picked into 10.1.x branch whenever it is created.
