### ISSUE TITLE
Sidetoolbar buttons are offset when they have a dropdown

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1956]
### Short Summary

Something is wrong with the alignment of sidebar buttons in Komodo IDE, version 10.1.0, build 89455, platform win32-x86.
Built on Mon Aug 22 08:23:01 2016.

This is a fresh profile.

See screenshot below

### Additional Information

![capture](https://cloud.githubusercontent.com/assets/655154/17874291/8a2a64e4-687f-11e6-8b0a-e5910e492adb.PNG)

**Comment by Naatan** [comment]
Does this persist after restart? I'm not seeing this.

**Comment by cgchoffman** [comment]
It appears to yes.

**Comment by Naatan** [comment]
Weird, not seeing this at all on either Windows or Linux. This happens when you first start with a clean profile? No additional steps?

**Comment by cgchoffman** [comment]
Just to double check i did another complete reset (i had been using Komodo for a bit since resetting a few hours ago).  Same thing :(

**Comment by Naatan** [comment]
Well then it looks like this bug is all yours :p Sorry, I can't repro :\

**Comment by cgchoffman** [comment]
Noooooooooooooooooooooooooooooooooo!  Ok.

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/e38f393ed1b4e24ed84e7eacd8a23a06a0308017
