### ISSUE TITLE
Code folding is broken for certain YAML files

### ISSUE THREAD

**Issue by rovf** [Komodo/KomodoEdit#1957]
When I edit YAML files, the folding of lines is broken, if the elements of a YAML list are aligned right below the parent element.

### Steps to Reproduce
Example demo.yaml:

```
---
key1:
    - element11
    - element12
    - element12
key2:
- element21
- element22
- element23
```

For this file, code folding is offered for key1, but not for key2. 

The difference is that within key1, there are spaces in front of the dash, while the dash for key2 is left-aligned in column 1, i.e. right below key2.

However, according to the YAML ANSI standard, both are fine. The standard says: *In YAML block styles, structure is determined by indentation. In general, indentation is defined as a __zero__ or more space characters at the start of a line.*

In fact, many Libraries (for example, the YAML libraries for Ruby or Java) generate YAML code with "zero spaces", to make the resulting string as short as possible. 

### Expected results

In the example, both lists (the one under key1 and the one under key2) should be treated equally.

### Platform Information

*Komodo Edit* 
*Version 9.3* 
*Operating System: Windows 7* 

### Additional Information

It is interesting to note, that the same bug appears in quite a few text editors (for instance, in Editra or Notepad++), while some do it right: NetBeans (provided the correct plugin is installed) folds correctly, as does SynWrite. Maybe many editors share the same parser? If you want to compare the current behaviour of Komodo Edit with the expected behaviour, I recommend to install SynWrite, because it comes configured correctly right out the box, while NetBeans is a bit tedious to set up.

**Comment by mitchell-as** [comment]
Thanks for the report.

**Comment by mitchell-as** [comment]
After looking into this further, I've determined that it's not really worth the level of effort to patch our editing component's lexer. The lexer folds primarily based on indentation changes, which is easy and works for user-written YAML (as opposed to machine-generated YAML). Changing the lexer to work for the case brought up in the ticket would require a much more detailed parser. Also, the fact that very few editors get it right means this is not a trivial task to solve. (Not all of them share the same editing engine.) I'm going to close this ticket.
