### ISSUE TITLE
PowerShell escape character not recognized

### ISSUE THREAD

**Issue by jasotastic** [Komodo/KomodoEdit#1958]
### Short Summary
PowerShell syntax highlighting is not recognizing the back-tick (grave-accent) escape character.

### Steps to Reproduce
Start a file.
Change the language to PowerShell.
Type "`"" and then anything else.

### Expected results
Since the " is escaped by the `, you would expect whatever follows to be highlighted as PowerShell script.

### Actual results
Instead, whatever follows is treated as a string inside quotes.

### Platform Information
*Komodo Edit or IDE?* Komodo Edit
*Komodo Version?* 10.0.1, build 17276, platform win32-x86.
Built on Wed Jun 15 08:36:15 2016.
*Operating System (and version)?* Windows 10

### Additional Information
![komodobug](https://cloud.githubusercontent.com/assets/6528275/17891269/4aa6041e-6900-11e6-86f9-26a4707753cc.png)

**Comment by mitchell-as** [comment]
Thanks for the report.
