### ISSUE TITLE
find tool not working - gives error

### ISSUE THREAD

**Issue by BernardA** [Komodo/KomodoEdit#1968]
### Short Summary
find tool does not work. gives error ( enclosed ).
This happen soon as I updated new version.
This is Edit 10.1.0 on Mac

### Steps to Reproduce
just try to find anything in a file

### Expected results
find occurrences of entered string

### Actual results
error message

### Platform Information
Mac latest 

*Komodo Edit or IDE?* Edit
*Komodo Version?* 10.1.0
*Operating System (and version)?* OS X 10.11.6
![screen shot 2016-08-26 at 15 52 01](https://cloud.githubusercontent.com/assets/9449665/18007806/d3f0e05c-6ba5-11e6-93b9-6a03f656d6b2.png)

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by mitchell-as** [comment]
Thanks for the report. We're tracking this in #1964 .
