### ISSUE TITLE
Tutorial causes window to resize

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#1971]
### Short Summary
When i open a tutorial, the window gets resized. 
Also when i go to the preferences, the behavior is a bit strange.

### Steps to Reproduce
Made a [screencast](https://www.youtube.com/watch?v=q_zOd9HFEFk&feature=youtu.be&hd=1) to show the issue.

### Platform Information
Komodo IDE X ( 10.1.0 ) - Windows  10

**Comment by cgchoffman** [comment]
Can you confirm your build number?  The tutorial popping out when you open the preferences was disabled for release as far as I know.  Build number should be 89455.

**Comment by babobski** [comment]
Confirmed, running build 89455
```
[2016-08-27 16:43:35,607] [INFO] Startup: Welcome to Komodo IDE 10.1.0 build 89455 
```

**Comment by cgchoffman** [comment]
Thank you.  Since a separate "feature" could you file a different issue for the odd behaviour when dialogs are opened.  You'll notice that the same thing happened no matter what dialog is opened, ie. The About Dialog.  We'll keep this ticket for the resize issue.

**Comment by Naatan** [comment]
Huh, your tutorial is showing both the new alert behavior as well as the old "auto undock" behavior. I have no idea how this can possibly be happening. There was never a version of the tutorial that did both.

I'll dig in.

**Comment by Naatan** [comment]
Fixed in https://github.com/Komodo/KomodoIDE/commit/5b72b57e2bf8890f8576055b99c46c406891b995
