### ISSUE TITLE
Odd behaviour when dialogs are opened

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#1972]
### Short Summary
The dialog behavior is a bit odd, as can be seen [here](https://www.youtube.com/watch?v=q_zOd9HFEFk&feature=youtu.be&hd=1)
### Platform Information
Komodo IDE X - Windows 10

**Comment by Naatan** [comment]
Huh, that's odd. Thanks for reporting!

**Comment by Defman21** [comment]
The behavior is:

If you're in maximized mode, a tutorial will change Komodo to window mode. The position after that will be the same as before going into maximized mode.

**Comment by Naatan** [comment]
Duplicate of #1971

**Comment by Defman21** [comment]
FYI Carey said that dialog behavior and tutorial behavior are two different things.

**Comment by cgchoffman** [comment]
@Naatan wrote the code.  It's his call.

**Comment by Defman21** [comment]
Hah okay! :)
