### ISSUE TITLE
Startup wizard after 10.0 -> 10.1 upgrade

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1973]
### Short Summary

For some reason, after I've upgraded from 10.0 to 10.1, Startup wizard opened for me.

### Steps to Reproduce

Upgrade from 10.0 to 10.1

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.0 -> 10.1
*Operating System (and version)?* Windows 7 x64

**Comment by mitchell-as** [comment]
Hmm, I'm not getting that. Did you clear or temporarily move your 10.0 profile beforehand?

**Comment by Defman21** [comment]
Nope.

**Comment by cgchoffman** [comment]
Can you reproduce this @Defman21?

**Comment by Defman21** [comment]
I'm going to try it again.

**Comment by cgchoffman** [comment]
Please do.  We can't repro.

**Comment by Defman21** [comment]
Hmm, not able to reproduce when upgrading from 10.0.0 to 10.1.0.

Gonna try 10.0.1 -> 10.1.0

**Comment by Defman21** [comment]
Not able to reproduce when 10.0,1 -> 10.1.0.
