### ISSUE TITLE
find does not work

### ISSUE THREAD

**Issue by HarryConings** [Komodo/KomodoEdit#1974]
find /find all does not work gives a error

### Steps to Reproduce
edit find 

### Expected results

find something

### Actual results
red error

### Platform Information

*Komodo Edit or IDE?* Komodo IDE 10.1.0 build 89455
*Komodo Version?* 
*Operating System (and version)?* win32 w7

### Additional Information
![error](https://cloud.githubusercontent.com/assets/19263856/18049787/b16a9400-6dea-11e6-90bd-976b6bbe5740.PNG)

[pystderr - kopie.txt](https://github.com/Komodo/KomodoEdit/files/442283/pystderr.-.kopie.txt)

 -- eg. Error logs, screenshots, workarounds --

**Comment by Defman21** [comment]
https://github.com/Komodo/KomodoEdit/issues/1964
