### ISSUE TITLE
Komodo spellchecker lints «»

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1976]
### Short Summary

For example, type `«Search for something»` in Komodo. `«Search` and `something»` will be highlighted as invalid words.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.1 nightly
*Operating System (and version)?* Ubuntu 16.04

**Comment by mitchell-as** [comment]
Hi, thanks for pointing this out. This is tough because the chevrons are unicode characters and we consider unicode characters as word characters. Without creating a giant table of unicode word separator characters, this is just a side effect we'll have to live with.

**Comment by Defman21** [comment]
Yeah, giant tables does not worth it :)
