### ISSUE TITLE
Feature Request: Close Tabs to the Right

### ISSUE THREAD

**Issue by brianV** [Komodo/KomodoEdit#1977]
### Short Summary

A very useful function in Firefox and Chrome is that ability to right-click on a tab and select 'Close Tabs to the Right'.

In an IDE, typically the tabs to the right are tabs opened in sequence for a specific purpose that can now be closed.

One example - during a debugging session, you may have 5-10 extra tabs open. If you are working based on a framework, these may even be code that belongs to you. Once the debugging session is over, those tabs often are not relevant anymore. It would be great if I could just use 'Close tabs to the Right' to close those tabs.

Another - sometimes while reading code, you may trace through several files to find the specific bit you are looking for. Simple to drag that tab over, right click, and 'Close tabs to the right'.

**Comment by babobski** [comment]
@brianV  I created a [addon](https://github.com/babobski/Close-tabs-to-the-right) that implements this feature, you can download the latest release from [here](https://github.com/babobski/Close-tabs-to-the-right/releases/latest).

**Comment by Naatan** [comment]
Thanks @babobski! This is exactly the type of thing we want addons to facilitate :)

**Comment by brianV** [comment]
@babobski The plugin does exactly what I was looking for! Thanks for the work on this.
