### ISSUE TITLE
Tutorials: moving window when something is highlighted does not move the highlight

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1979]
### Short Summary

Open Komodo in window mode, run Toolbox tutorial. Press on Toolbox link, then move Komodo. The black area won't move, more over you won't be able to close it anymore - the buttons will be under it.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.1 nightly
*Operating System (and version)?* Ubuntu 16.04

**Comment by Naatan** [comment]
Fixed in https://github.com/Komodo/KomodoIDE/commit/2417a0ac74939ef83cbd831aff46d428528d7259
