### ISSUE TITLE
Remove all uppercase characters from widget titles on OSX

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#198]
Reference: https://github.com/Komodo/KomodoEdit/issues/46

**Comment by we3geeks** [comment]
My opinion on this: If the widget title reflects a path from the underlying filesystem, the widget title should match the case used in the path (which may or may not be what you meant in logging this enhancement). If the underlying path is mixed case, I think the uppercase  letters in the path should be retained in the widget title.

**Comment by geary** [comment]
Right, I was just about to file a similar issue on the Places panel. It uppercases the file or directory name at the top of the list, which is silly and confusing. Filenames and pathnames should always be displayed in their original case.

The Open Files panel also has its title uppercased: OPEN FILES: 1. This looks silly too: the use of UPPERCASE like this is so 2013! I'm referring to VS2013 and Office 2013 which used BALLMER CASE for their menus. Fortunately, VS2015 is back to normal mixed case now that the DEVELOPERS DEVELOPERS DEVELOPERS guy is gone.

UPPERCASE was just a design fad that no developer or user ever appreciated. It has now run its course and Komodo should get rid of it everywhere.
