### ISSUE TITLE
Fonts are rendered poorly.

### ISSUE THREAD

**Issue by wolfhammer** [Komodo/KomodoEdit#1980]
### Short Summary

The interface font size is in rems only while the editor font is in pts.  The rem setting has too big a jump between sizes to dial in a good size for my monitor. The line height does not scale well with the font size.

### Steps to Reproduce

Komodo -> preferences -> appearance -> fonts

### Expected results

Larger font that renders well.

### Actual results

Too large a font that jumbles together.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10
*Operating System (and version)?* OSX

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by Defman21** [comment]
You can set any CSS valid font size, not only rem.

**Comment by Naatan** [comment]
If you scroll further there are pixel values too. Only the first couple of entries are rems.

@Defman21 that's the color scheme editor, he's talking about Prefs > Appearance.

**Comment by Defman21** [comment]
Ah. Forgot that there's such an option now :P
