### ISSUE TITLE
Odd fold markers in userscript window if they are disabled in Prefs - Editor

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1981]
### Short Summary

I've them disabled, but that's how it looks for me:

![img](https://i.imgur.com/dgEIOAy.png)

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.1 nightly
*Operating System (and version)?* Ubuntu 16.04

**Comment by Naatan** [comment]
Try moving aside your tools folder in your Komodo profile folder, then restart Komodo.

**Comment by Naatan** [comment]
Or Help > Troubleshooting > Restart Without Tools

**Comment by Defman21** [comment]
That didn't do the trick. Carey is able to reproduce it as well if he disable fold markers.

**Comment by cgchoffman** [comment]
Note that to reproduce you have to provide example code that wouldn't normally get a folding marker, ie. from the second `const` in @Defman21's example down to the closing bracket.  **Prefs > Editor > Smart Editing > Folding: don't show fold marks **
```
function blah() //none here
{ //they start here
    alert("pizza...seriously...the best");
} //stop here
```

**Comment by Naatan** [comment]
Reproduced, thanks :)
