### ISSUE TITLE
Userscripts Help on shortcuts not working

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#1987]
### Short Summary
The link Help on shortcuts is not working, when you click on it, nothing happens.
It's only producing a error in the error log:
```php
[2016-09-01 13:09:26,010] [ERROR] console-logger: TypeError: ko.prefs is undefined (2) in chrome://komodo/content/launch.js:24
Traceback (most recent call last):
  File "chrome://komodo/content/launch.js", line 24, in 
```

### Expected results
Some help function

### Actual results
Nothing happens

### Platform Information
Komodo Ide 10.1 - windows 10

**Comment by mitchell-as** [comment]
Thanks for the report.

**Comment by cgchoffman** [comment]
I find it funny that you keep finding these `Help` button bugs when you are one of the more knowledgeable Komodo community members @babobski.  Why are you always looking for help??  Just kidding ;)  Thanks for the report.

**Comment by Defman21** [comment]
lol
