### ISSUE TITLE
JSX support: doesn't highlight syntax errors AT ALL!

### ISSUE THREAD

**Issue by rulatir** [Komodo/KomodoEdit#1988]
### Short Summary

It seems that JSX support has brutally removed JavaScript syntax checking.
### Steps to Reproduce
1. Write a .js file with outrageous syntax errors.
2. Note that the errors are properly undersquiggled.
3. Switch the file's language to JSX
### Expected results

The outrageous syntax errors should still be undersquiggled.
### Actual results

No syntax errors are underdsquiggled at all. The realtime assistance that syntax error detection normally provides is completely sacrificed.
### Platform Information

_Komodo Edit or IDE?_ Edit
_Komodo Version?_ 10.1
_Operating System (and version)?_ Linux 64bit

**Comment by mitchell-as** [comment]
Would you please provide a concrete example? I used the string

`this is totally invalid syntax;`

In JS I get two syntax errors:
1. Expected an assignment or function call and instead saw an expression.
2. Missing semicolon.

In JSX I get one syntax error:
1. Unexpected identifier (on column 6).

While the errors are different (JSHint vs. JSXHint), it is not the case that syntax errors aren't highlighted at all.

**Comment by dorklord23** [comment]
@mitchell-as, I've done as you said and Komodo Edit 11 didn't detect anything wrong

**Comment by dorklord23** [comment]
![image](https://user-images.githubusercontent.com/17370471/31211505-c985e74a-a9c3-11e7-88f6-b01efacc1486.png)

**Comment by Naatan** [comment]
Make sure you have jsxhint installed and configured:

![image](https://user-images.githubusercontent.com/278649/31235708-2c776a6c-a9c0-11e7-8603-dee1e41f22fb.png)

**Comment by Naatan** [comment]
Also please file a new bug if you continue to see this issue. You are responding to a year old closed bug.
