### ISSUE TITLE
Freezing while previewing a Markdown code block

### ISSUE THREAD

**Issue by Heliozoa** [Komodo/KomodoEdit#1991]
### Short Summary
Komodo Edit freezes when trying to view a code block with "Markdown preview".

### Steps to Reproduce
Paste the following into a code block in a Markdown file and use Komodo Edit to attempt to preview it:
```
jono = uusi Tavujono
lue tavu jonoon //O(1)
while(tiedosto ei ole loppu)    //O(n) pakattavan tiedoston kokoon nähden.
    lue tavu //O(1)
    if(sanakirja sisältää jonon+tavun)  //O(n), sanakirjassa on tavuja enintään tiedoston koon verran.
                                        //Hajautuksen ansiosta käytännössä haku on paljon nopeampi.
        lisää tavu jonoon   //O(1)
    else
        koodi = hae sanakirjalta jonon koodi    //O(n) jonon pituuden suhteen. Jono on pisimmilläänkin pienempi kuin tiedosto itse, käytännössä aina huomattavasti pienempi.
                                                //Sanakirja käy läpi yhtäaikaisesti jonoa ja omaa hajautustauluaan ja palauttaa jonon viimeistä tavua vastaavan solmun koodin.
        lisää tavuihin koodi    //O(1)
        lisää sanakirjaan jono+tavu //O(n) jonon pituuden suhteen. Sanakirja hakee samoin kuin yllä jonon viimeistä tavua vastaavan solmun ja lisää sille uutta tavua vastaavan solmun.
        tyhjennä jono //O(1)
        lisää tavu jonoon //(O)1
```

### Expected results
The preview is displayed without issues.

### Actual results
Komodo Edit completely locks up and has to be forced to shut down.

### Platform Information

*Komodo Edit or IDE?* 
Edit
*Komodo Version?* 
version 10.1.0, build 17404
*Operating System (and version)?* 
Happened both on Windows 10 and the latest release of Manjaro

### Additional Information
I tried to replicate it with different text and for the most part I was unable to do so, hence the Finnish pseudocode. If you type the text out instead of copying it, it gradually slows down and eventually stops responding.

**Comment by Naatan** [comment]
I'm unable to reproduce this. What file encoding are you using?

**Comment by Heliozoa** [comment]
UTF-8. Here's a [screenshot](http://i.imgur.com/gTIGBuA.png) if it helps. It seemed like something that would happen just on my PC, but it happened both on my desktop (Manjaro and Win10) and laptop (Manjaro). Additionally on Windows it was on a fresh install of Komodo Edit.

**Comment by Naatan** [comment]
Can you reproduce it in safe-mode? Help > Troubleshooting > Restart in safe-mode.

**Comment by Heliozoa** [comment]
Markdown preview seems to be disabled in safe-mode, so I can't try it. I should be able to try it out on at least one other computer tomorrow.

**Comment by babobski** [comment]
Tested it on windows 10 and can reproduce the issue.
The problem is in the \`\`\` code block ( noticed it on the screenshot ).
When i create a markdown file with a code block.
\`\`\`
	-code-
\`\`\`

If i then copy the code from @Heliozoa, put it inside the code block, save the file.
If i then preview the file komodo crashes.

Tested in komodo edit and Ide, the both crash ( [screencast](https://www.youtube.com/watch?v=IEd8X_rBt4A) )

**Comment by Naatan** [comment]
Good catch @babobski ! reproduced :)
