### ISSUE TITLE
browsing source for finding/replacing words

### ISSUE THREAD

**Issue by dinasset** [Komodo/KomodoEdit#1994]
### Short Summary
I noticed that the search works fine ONLY if the open document (source program) is stored on a folder in the user's tree, otherwise it doesn't work

### Steps to Reproduce
 - being logged in as -let's say- User1, launch Komodo Edit and open a program which is stored on a folder related tostored in a different user's tree (let's say User2 or even Public)
- editing works properly, you can also modify and store the updated version
- but if you try to search a word in the "current document" you get an error

### Expected results
list of occurrences

### Actual results
error (cannot be attached because it's a red flash msg during only 3-5 seconds, then disappears) 

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by Naatan** [comment]
Please share your error log after reproducing the issue.

You can find your error log at Help > Troubleshooting > View Log File.

**Comment by cgchoffman** [comment]
If it's the issue I think it is there won't be anything in the logs but you can download the latest nightly and this issue will likely be resolved. Downloads.activestate.com/komodo

**Comment by cgchoffman** [comment]
Proper nightlies link: http://downloads.activestate.com/Komodo/nightly/

**Comment by cgchoffman** [comment]
To clarify (Sorry I was replying from the skytrain), I believe this is #1978.  Let us know if you find evidence to the contrary @dinasset

**Comment by dinasset** [comment]
Hi.
Thanks for your replies.
Downloaded version (nightly) 10.1.0 - 17406: problem fixed, thanks a lot.

**Comment by cgchoffman** [comment]
@dinasset thanks for confirming.
