### ISSUE TITLE
css transparent on click doesn't open color picker

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#1995]
### Short Summary
When you click on the color value transparent, you will get an not implemented error.

### Steps to Reproduce
Click on the color transparent value ;)

### Expected results
Color picker should open with full opacity 

### Actual results
Not implemented error is triggerd

### Platform Information
Ide X 10.1 - windows 10

**Comment by Defman21** [comment]
```
.color {
    color: transparent;
}
```

**Comment by mitchell-as** [comment]
Thanks for the report.
