### ISSUE TITLE
add all css display values to komodo

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#1996]
### Short Summary
Currently there are some css display options not showing, like the `display: inline-flex`.

### Additional Information
A full list of the display options can be found [here](https://developer.mozilla.org/en-US/docs/Web/CSS/display)

**Comment by Defman21** [comment]
https://github.com/Defman21/KomodoEdit/blob/e14fbf4434afc1ded802baccde6f9d2edbc5b8ad/src/codeintel/lib/codeintel2/constants_css1.py#L313

https://github.com/Defman21/KomodoEdit/blob/e14fbf4434afc1ded802baccde6f9d2edbc5b8ad/src/codeintel/lib/codeintel2/constants_css3.py#L707

https://github.com/Defman21/KomodoEdit/blob/e14fbf4434afc1ded802baccde6f9d2edbc5b8ad/src/codeintel/lib/codeintel2/constants_css_microsoft_extensions.py#L133

You can send a PR :)

**Comment by mitchell-as** [comment]
Indeed. PRs are certainly welcome :)
