### ISSUE TITLE
Browser preview button not showing up after creating file (xhtml)

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#1999]
### Short Summary
When you create a file from template, save the file.
The browser preview button is not showing up.

### Platform Information
Komodo Ide 10.1.1 Windows 10

**Comment by Naatan** [comment]
Working for me. Please provide steps to reproduce.

**Comment by cgchoffman** [comment]
#1595 dupe

**Comment by babobski** [comment]
or html5 file, the button doesn't show up after save, only when you switch from you're views.
If you where working with one file you will never get the browser preview button.

Made [screencast](http://youtu.be/5F0fjTLSHfI?hd=1) to show the issue.

**Comment by Naatan** [comment]
Thanks @babobski. We'll track it in #1595

**Comment by babobski** [comment]
:+1:
