### ISSUE TITLE
Global UI layout pref gets reset too easily

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2000]
### Short Summary

I haven't dug into this at all but, WAY too often the global UI preferences seems to revert to a default state some how.  It's extremely annoying.  I suspect this has to do with the piles of stale window states that get kept around by the Workspace legacy code.  So this would either be fixed by switching to Workspace 2 or making Workspace 1 more vigilant about culling stale prefs.

**Comment by Naatan** [comment]
Possibly related to the shutdown event that saves the current pref state. I think we should just save the pref state whenever it gets saved (it doesn't happen that often that it would affect performance).

**Comment by cdcmicro** [comment]
I've experienced this issue myself with IDE 10 on Windows.  And, as @cgchoffman notes, it's extremely annoying.

Most recently, it was after an unclean shutdown (Windows Update rebooted).  When I chose to restore the open files, my widgets (open files, DOM, database, places, etc) are all back in the default locations.

**Comment by cgchoffman** [comment]
I'm not pretty  sure this will be resolved by fixing #1975.

**Comment by cgchoffman** [comment]
Ok, this should be resolved by #1975.
Toolbar customization will be handled by #3287.
The Symbol Browser is an isolated issue as well which will be handled in #3179.
