### ISSUE TITLE
Toolbars Hide Unexpectedly On Closing All Files

### ISSUE THREAD

**Issue by bfailing** [Komodo/KomodoEdit#2003]
### Short Summary

I'm not sure what the intended behavior is with respect to toolbars hiding, but I find that all toolbars except for the one with "Toggle Focus Mode" and another with a custom script are hidden on closing all files.  When opening and beginning work on a new file, this requires re-displaying the hidden toolbars by navigating: Toolbars (either by right-clicking on the top pane or via the View > Toolbars menu) > Customize > clicking once on the open-eye icon (indicating that it is displayed when it is not) to show the closed-eye icon > clicking again to show the open-eye icon (which causes re-display of the toolbars) > Done.

Is there a way to set a default toolbar customization for all files and program states (e.g., with no files open, with one or more files open, etc.)?

It would be nice if the customized menu settings persisted between file openings/closings and restarting of the program.  It would also be nice if the eye icons for the toolbars accurately reflected the actual state (e.g., hidden or displayed) of the toolbars.

### Platform Information

Komodo Edit 10.1.1
Windows 10

**Comment by Naatan** [comment]
I think you're talking about the dynamic buttons, these show depending on whether they are relevant to what you are doing. For example browser preview does not show unless you have a file open that can be previewed.

Let me know if this doesn't cover your issue.

**Comment by bfailing** [comment]
Okay, you've confirmed that the issues I brought up are not in accordance with the intended functionality.  Why was this closed?

**Comment by Naatan** [comment]
> Okay, you've confirmed that the issues I brought up are not in accordance with the intended functionality. Why was this closed?

No I haven't. I explained how this is intended to work and how I believe that what you're seeing was what was intended. If my explanation does not cover your use-case please explain how your use-case differs.

**Comment by bfailing** [comment]
The attached screenshots illustrate the steps and corresponding issues I described.  

Screenshot 1 - Program started and no toolbars displayed.  

Screenshot 2 - New file opened but no toolbars displayed.  To display toolbars with common operations (e.g., save file, cut/paste, etc.), I have to go through the steps I described in my first post as discussed further below.

Screenshot 3 - Within the customize toolbars window, the open-eye icon on the "Toolbar-Left" category indicates that the toolbars are displayed when they are not.

Screenshot 4 - To get the hidden toolbars to display, I click on an eye icon.  In this case, I clicked the eye icon corresponding to the toolbar containing the new file icon (plus symbol) and the save file icon (3.5" floppy disk symbol).  This toolbar is properly hidden as indicated by the resulting closed-eye icon, but the others magically appear even though I have not interacted with their corresponding eye icons.

Screenshot 5 - After clicking the eye icon (corresponding to the toolbar containing the new file icon and the save file icon), the toolbar then appears.

Screenshot 6 - After clicking the "Done" button in the customize toolbars window, I then can begin work on the new file with all the toolbars displayed.

There are additional issues related to toolbar display.  For example, sometimes it remembers the toolbar states for a given file when opening/closing the file, and other times not (e.g., the toolbars revert to the state shown in Screenshots 1 and 2).  If your dynamic toolbar functionality is tied to a file type or even a specific file, then this should be consistent.

And as previously noted/asked, it would be nice if you could set the icons which are always displayed for all file types and for specific file types.

![1](https://cloud.githubusercontent.com/assets/17439289/18373801/2d566ac6-75fc-11e6-9b83-fb02d8174403.jpg)
![2](https://cloud.githubusercontent.com/assets/17439289/18373802/2d58d9b4-75fc-11e6-828c-55e00c8ac860.jpg)
![3](https://cloud.githubusercontent.com/assets/17439289/18373804/2d595d08-75fc-11e6-88af-26560a311483.jpg)
![4](https://cloud.githubusercontent.com/assets/17439289/18373803/2d590010-75fc-11e6-98c2-1660bb5020f9.jpg)
![5](https://cloud.githubusercontent.com/assets/17439289/18373805/2d5e90b6-75fc-11e6-91ff-e97ff669f528.jpg)
![6](https://cloud.githubusercontent.com/assets/17439289/18373806/2d604456-75fc-11e6-8613-c281ae86c2b5.jpg)

**Comment by Naatan** [comment]
Thanks for the screenshots, they're very helpful! Using your steps I was able to reproduce the issue. It appears to be happening only on Komodo Edit.

**Comment by Naatan** [comment]
Note it appears the issue only happens when the toolbar is in classic mode. So as a workaround simply don't use classic mode for now (least until we get a nightly out, or until I find a better workaround).

**Comment by Naatan** [comment]
Will try and get a nightly up by EOD. Ping @cgchoffman if you'd be so kind? :) Need one off the 10.1.2 branch. Thanks!

**Comment by cgchoffman** [comment]
Hi @bfailing, the edit nightly is staged and should be live around 12.  You might be able to open the JS Console and run the following command:
`require("sdk/preferences/service").set("app.update.channel", "nightly");`
then run` Help > Check for Updates...`.

If that doesn't work then the installer *will* be here: http://downloads.activestate.com/Komodo/nightly/komodoedit/
