### ISSUE TITLE
Unable to move the main window

### ISSUE THREAD

**Issue by WheelDogs** [Komodo/KomodoEdit#2009]
### Short Summary

Unable to use the mouse or keyboard to move the window. Only able to resize by selecting border. Mouse selection of any part of the bar that contains the min, max and close buttons does nothing.
### Expected results

Holding mouse button down and moving the mouse moves the window
### Actual results

nothing
### Platform Information

Komodo IDE 10.1.1 (just updated) 

_Operating System (and version)?_ 
win 7, sp1
### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by WheelDogs** [comment]
Went back to 10.1.0; same issue...

**Comment by Defman21** [comment]
Try to use native decorations (Prefs - Appearance)

**Comment by Naatan** [comment]
What Defman said - Prefs > Appearance > Platform Integration > Use native window borders.

Let us know if that works.

**Comment by WheelDogs** [comment]
Thanks for getting back to me...

Did you dirty...deleted all vestiges of earlier versions from the program and user folders. Kept only the .lic files.
Then reinstalled 10.1,0 and the issue went away...

If it is of any help, thought, the problem appeared after Komodo did the update and install...not I.

**Comment by WheelDogs** [comment]
Problem remains...unable to move the komodo application window...at all. Commonly used techniques fail to produce any repositioning.

**Comment by Naatan** [comment]
@WheelDogs you didn't respond to my last comment, please let me know if that worked.

**Comment by WheelDogs** [comment]
No, it made no difference.

When Komodo completes the instantiation of the UI, it is occupies the entire display. The only way to move it is to keep resizing...

**Comment by WheelDogs** [comment]
Hi,

 

Replied on github issue. Thanks.

 

Rick

**Comment by Naatan** [comment]
Can you reproduce this using `Help > Troubleshooting > Restart in Safe-mode` ?

Please verify that when restarting in safe-mode Komodo should be using the default UI (all your settings would be temporarily reset).

**Comment by WheelDogs** [comment]
Works after “Restart in Safe-mode”

**Comment by WheelDogs** [comment]
Yes. Worked after "Restart in Safe-mode". But, then, of course, next time loaded, the issue returns...

Hope this helps...

**Comment by cgchoffman** [comment]
@WheelDogs you're replying twice each time.  Just open the ticket in the browser.  When you reply to the email it dumps the entire contents of your email (even the previous emails) into the github post.

**Comment by Naatan** [comment]
Please share your error log after reproducing the issue.

You can find your error log at Help > Troubleshooting > View Log File.

**Comment by WheelDogs** [comment]
[pystderr.txt](https://github.com/Komodo/KomodoEdit/files/625947/pystderr.txt)

**Comment by Naatan** [comment]
Hmm, try Help > Troubleshooting > Restart without Addons. And if that does not work try "Restart without Tools".

**Comment by WheelDogs** [comment]
Neither worked...however, Restart in Safe Mode produces the expected result...i.e. mouse down, motion does move the UI.

**Comment by Naatan** [comment]
Very strange. Could you share a screenshot of your main komodo window and your prefs > appearance window? Perhaps there is some odd combo I haven't thought of.

**Comment by WheelDogs** [comment]
Please find requested screenshots attached.
![komodo_001](https://cloud.githubusercontent.com/assets/21134598/20898634/1b569f74-baf5-11e6-8c51-be566c0a863c.png)
![komodo_002](https://cloud.githubusercontent.com/assets/21134598/20898632/1b5295f0-baf5-11e6-83b0-bc142ed497da.png)
![komodo_003](https://cloud.githubusercontent.com/assets/21134598/20898633/1b53acce-baf5-11e6-9e41-05495e6f8e86.png)

**Comment by WheelDogs** [comment]
One is K loading with no script to edit; one is K loading the preceding script edit session, and one is the prefs\appearances.

Hope this helps.

BTW: when restarting in safe mode, only the first ui can be moved. Any subsequent UI invoked from that point are locked. i.e. restarted in safe mode, loaded a script, ui locked in place.

**Comment by WheelDogs** [comment]
...editor ui is not moveable...

**Comment by Naatan** [comment]
Ah, are you perhaps trying to drag on the dark blue menubar instead of the toolbar? The toolbar is draggable, the menubar (dark blue) I believe is not.

**Comment by WheelDogs** [comment]
I have tried dragging on everything that is in sight.

**Comment by WheelDogs** [comment]
Am able to resize, but not drag.

**Comment by Naatan** [comment]
Hmm ok, starting to think it might just be best if you reset your profile (reset all your settings), as I'm not sure what could be causing this and thus far you appear to be the only one affected.

Instructions on resetting Komodo: http://docs.komodoide.com/Troubleshooting/Reset-Komodo

**Comment by WheelDogs** [comment]
Will do, thanks.

**Comment by WheelDogs** [comment]
Well, scroll back up through this thread and you'll see that this was how I solved this problem previously.
The kicker is, I prefer K9 over K10 for it;s simplicity, etc. K10, though a lot slower, has some improved debugging capabilities. So at one point I must have deleted K10, reinstalled K9, then later reinstalled K10. In doing so, K10 inherited, or mismanaged what it inherited, to produce the subject problem.

**Comment by WheelDogs** [comment]
So, after following resetting process, all seems well.
1. deleted all libs.
2. restarted K10.
3. copied K9 libs from backup.

Now, both are executing as expected.

BTW: for what it is worth, I believe that the K is trying to serve to many masters...i.e. too many languages. I understand economies of scale, but in this instance K reflects a "fallacy of composition". To wit, it does not recognize as valid any of the object oriented commands that are now part of tcl 8.6. So given my experience that K10 is slower than K9 and I am using object commands, I have gone back to K9.

When K10 is capable of completely supporting tk 8.6 development then it would be reasonable to remove K9 from my system.

Too many languages, too many things to consider. I vote for language specific development that shares code.

Just say'n

**Comment by Naatan** [comment]
>  I prefer K9 over K10 for it;s simplicity, etc. K10, though a lot slower

This cannot be true. We made tons of performance improvement in K10 that simply are in no way present in K9. If K10 is truly slower than K9 for you either you are affected by some type of bug or it may be a perception problem.

> When K10 is capable of completely supporting tk 8.6 development then it would be reasonable to remove K9 from my system.

We do have some Tcl 8.6 support incoming for 10.2, but the object oriented change they introduced is significant and will take more work. It will likely land in 11 or soon after.

**Comment by nightmare-moon** [comment]
I found the same issue with komodo 11.. but what you have to do is click on the top of the UI 
and then uncheck Show Menu bar then you can move the UI around.
WTF...

**Comment by cgchoffman** [comment]
@nightmare-moon looks like that was the key.  That's disabled by default and I guess not a lot of people enable it so no one else noticed.  I'm just going to open a new ticket that's more focused: https://github.com/Komodo/KomodoEdit/issues/3622

**Comment by shinyion** [comment]
I am having this same issue in KE v 11.1.1
So he is not the only one and it is a year later. Running Win 10.

**Comment by th3coop** [comment]
@shinyion see my last comment.  New issue opened.  Comment there.

**Comment by Undefined-Variables** [comment]
I've got this same problem 

K11, 
Windows 10,
 64bit,
 16GB Ram,

Annoying as hell, its stuck on the wrong screen and will not budge no matter what I do! Don't really want to reinstall as would take a day to reinstall everything and set up servers again... Major headache!

**Comment by Undefined-Variables** [comment]
Sorry I found issue View -> Full Screen

**Comment by th3coop** [comment]
> as would take a day to reinstall

Take a day to reinstall Komodo?

**Comment by Undefined-Variables** [comment]
Not the install but adding the remote servers would take a long while... Maybe not a day but a good mornings work!

**Comment by TalleyMetal** [comment]
I had the same problem this morning. The solution ended up being View->Full Screen was checked... although the window was not full screen.  i unchecked it and now I can move the window.
