### ISSUE TITLE
"Document using GoFmt" deletes all code in text editor.

### ISSUE THREAD

**Issue by danny-su** [Komodo/KomodoEdit#2010]
### Short Summary

"Document using GoFmt" deletes all code in text editor.
### Steps to Reproduce

Open a .go file, Format->Document using GoFmt.
### Expected results

All code are formated.
### Actual results

All code are deleted.
### Platform Information

Komodo IDE v10.1.1, Windows 10 64-bit
### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by mitchell-as** [comment]
Thanks for the report!

**Comment by cgchoffman** [comment]
Note on this:  I remember this being reported before but I can't find the report.  The issues, if I recall correctly, is that the Go format tool takes a file name and formats it on the disk.  Other formatting tools provide a method where you pass in a string, the tool formats it, gives it back, then we dump it into the file.
I wonder if the GoFmt supports input yet?

**Comment by Naatan** [comment]
Interesting. If it doesn't support input we should still be able to use a temp file though.

**Comment by cgchoffman** [comment]
Sure, I'm not saying we can't do it.  Main concern is that it won't work with the current Komodo backend for formatting.

**Comment by mitchell-as** [comment]
https://github.com/Komodo/komodo-go/commit/14282c20d7b8c5e33c89d90c716665d15bcac346

**Comment by Naatan** [comment]
Need to add an upgrade step to koInitService, only fresh installs would get the fix otherwise.

**Comment by Naatan** [comment]
Fixed in https://github.com/Komodo/KomodoIDE/commit/03f3c3e00c0ca572a5c39d693638cddb75472f38
