### ISSUE TITLE
When creating a html5 file the wrong file type is selected

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#2014]
### Short Summary
As can be seen in the [screencast](https://www.youtube.com/watch?v=5F0fjTLSHfI) I create a html5 file, but the wrong file type get's selected.
It's selecting html and not html5

### Steps to Reproduce
Create a html5 file from template

### Platform Information
Komodo 10.1.1 windows 10

**Comment by mitchell-as** [comment]
That's very strange. When I follow the same steps, File > New from Template... > Web > HTML5, I get the same "HTML 5-1.html" filename and my language is "HTML5", not "HTML". @cgchoffman can you reproduce this one?

**Comment by Naatan** [comment]
Not able to reproduce either.

**Comment by cgchoffman** [comment]
Nope can't repro and I was doing this a lot on Thursday and Friday.  This sounds like Prefs > Lang > HTML > Default HTML DocType has been changed.

**Comment by babobski** [comment]
Tested it also in edit, but in edit I'm getting the correct result.
Only in Ide I get the wrong file type

**Comment by Naatan** [comment]
@babobski have you checked the pref @cgchoffman suggested?

**Comment by babobski** [comment]
@Naatan I've looked at the pref, but it has the same doctype configured as in edit:

![2016-09-14 06_47_47](https://cloud.githubusercontent.com/assets/3530262/18500386/4de6392a-7a47-11e6-8041-38e03cea950a.png)

If i select the normal html file from **new > file from template > html** the default file type is html5, only when I create a html5 **new > file from template > html5** the file type is html and not html5.

![2016-09-14 06_54_25](https://cloud.githubusercontent.com/assets/3530262/18500480/1af3a4b6-7a48-11e6-8baf-59c89e359ba8.png)

**Comment by cgchoffman** [comment]
Please share your logs and try with a fresh profile.  Did you auto-update to this version?  If yes, from which version?

**Comment by babobski** [comment]
Closing it for now, Tested it at work but here it's selecting the right html5 file type. The problem only affects my home computer.

**Comment by Naatan** [comment]
Let us know if you figure out what the issue is or if you need more help narrowing it down.

**Comment by babobski** [comment]
I found a workarround to "fix" it, by setting the file association for `.html` from html to html5. 
But will let you know when I find something else.
