### ISSUE TITLE
Unexpected internal error saving (Save As) 'en.po'

### ISSUE THREAD

**Issue by tribis** [Komodo/KomodoEdit#2016]
### Short Summary
Internal Komodo Error
Unexpected internal error saving (Save As) 'en.po'

### Steps to Reproduce
1. Open a new file
2. Save as <name>.po

### Expected results
The file is saved

### Actual results
An error message pops up with the internal error pasted below

### Platform Information
Komodo IDE, version 10.1.1, build 89474.
Built on Thu Sep 01 14:27:01 2016.
Windows 10

### Additional Information

The content of the error rmessage is:

[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIScintillaScheme.applyScheme]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://komodo/content/bindings/scintilla.xml :: applyColorScheme :: line 729"  data: no]

Exception: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIScintillaScheme.applyScheme]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://komodo/content/bindings/scintilla.xml :: applyColorScheme :: line 729"  data: no]

Traceback:
applyColorScheme@chrome://komodo/content/bindings/scintilla.xml:729:16
set_language@chrome://komodo/content/bindings/scintilla.xml:360:24
set_language@viewbufferbase:537:16
_setLanguage@vieweditor:758:12
set_koDoc@vieweditor:272:16
saveAsURI@vieweditor:1814:12
saveAs@vieweditor:1722:19
viewManager.prototype.do_cmd_saveAs@chrome://komodo/content/views.js:1974:4
xtk.Controller.prototype.doCommand@chrome://xtk/content/controller.js:61:8
command_doCommand@chrome://komodo/content/library/commands.js:239:0
command_doCommandAsync/<@chrome://komodo/content/library/commands.js:196:12

Komodo IDE, version 10.1.1, build 89474.
Built on Thu Sep 01 14:27:01 2016.

A similar error happens if I try to save a file as <name>.pop and edit subsequently the name into <name>.po
the error this time is:

morekomodo_command--null
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIScintillaScheme.applyScheme]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://komodo/content/bindings/scintilla.xml :: applyColorScheme :: line 729"  data: no]

**Comment by mitchell-as** [comment]
Thanks for the report.
