### ISSUE TITLE
What is wrong with JavaScript syntax highlighting in PHP files?

### ISSUE THREAD

**Issue by nmoschkin** [Komodo/KomodoEdit#2018]
This has been a constant issue for me, even when I had an active license for Komodo IDE.

In a PHP file, JavaScript will intermittently not parse correctly ... the code will sometimes go all white, without any syntax highlighting or references ... 

This issue has persisted since at least version 6.  Every time a new version comes out, I wait with baited breath that the issue will be resolved, but it never is.  

What gives?

**Comment by Defman21** [comment]
An example would be very appreciated.

**Comment by nmoschkin** [comment]
I can't really provide one.  It comes and goes....

**Comment by cgchoffman** [comment]
You said you've had this issue since Komodo 6.  Is there a bug report for that?  Is there some historical context to go on?

With out logs, sample code or any other context, there isn't anything we can do to help here.

**Comment by nmoschkin** [comment]
Um ... So, if I have lots of interwoven PHP and HTML/JavaScript code, it becomes an issue.  Sometimes, after an edit, the JS code will go white and the HTML code will go funky-colored.

Sometimes, I can press return on a line of JS code and it all just suddenly corrects itself.

Sorry, the code I'm working with is not exactly public, so I can't really "provide an example."  

I have never lodged a bug report, before, I just assumed everyone dealt with this and that you guys would get to it eventually ... but I'm perplexed why it happens.

At any rate, like I said, unless you're willing to sign an NDA and a BAA, I can't show you the code with which I am having an issue.

**Comment by mitchell-as** [comment]
Well if you ever manage to construct some sample code that causes the glitch, please let us know. We haven't seen it and without anyone having logged a bug for it, I'm not surprised we haven't fixed it :)

**Comment by Naatan** [comment]
@nmoschkin perhaps you could try reproducing the issue on a minimal code snippet?

Note we only need a single file, we don't need access to your entire project. If you prefer you could share it to us via email so it's not public.

**Comment by nmoschkin** [comment]
Okay ... I will see if there is a sample I can send you for which this is an issue.

Please give me an email address to send the snippet to.

**Comment by Naatan** [comment]
Send it to support@activestate.com and please add a reference to this ticket (the URL or ID).

**Comment by nmoschkin** [comment]
Okay.  I sent an email using the URL as a reference.

While we're on the subject ... why don't JavaScript function tips mostly not work in a PHP file?

**Comment by mitchell-as** [comment]
After a private e-mail exchange related to the above-mentioned source code, I've determined this is not a bug. As the user types, code may no longer be syntactically valid. One should not expect Komodo to highlight it accurately. In this case, an unclosed quote in `<div style="` was causing JS to be highlighted as HTML. This is expected.

**Comment by mitchell-as** [comment]
@nmoschkin Sorry I overlooked a question you had asked. JavaScript function tips may not work inside PHP files if there is embedded PHP in JavaScript blocks -- our JavaScript code intelligence cannot discern between PHP and JavaScript in these instances.

**Comment by babobski** [comment]
@mitchell-as I also have more frequent problems that on file open or while editing php the render gets broken:

![afbeelding](https://cloud.githubusercontent.com/assets/3530262/22326112/b8745c26-e3b1-11e6-9a8a-1a39b717b239.png)

In this example there is JavaScript only this is inside a php string.
When i add a space before the html tag and backspace it, the file is rendered correctly:

![afbeelding](https://cloud.githubusercontent.com/assets/3530262/22326601/ad9ba3a2-e3b3-11e6-8a77-4aee5b691c10.png)

**Comment by mitchell-as** [comment]
@babobski Will you please open a separate ticket with your issue? With code samples too please.

**Comment by babobski** [comment]
@mitchell-as will do, first I want to try to reproduce with some test code.
