### ISSUE TITLE
OSX Full Screen is SERIOUSLY broken

### ISSUE THREAD

**Issue by jhihn** [Komodo/KomodoEdit#2019]
### Short Summary
OSX Full Screen is SERIOUSLY broken

### Steps to Reproduce
Dual monitors - OSX El Cap
Use the green circle to maximize the window
The other display is blacked out.

### Expected results
It is maximized to the display, other display is still usable. 

### Actual results
One display is Komodo, other is black

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.1.1
*Operating System (and version)?* OSX 10.11.5

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by jhihn** [comment]
FWIW, it also happens on K-IDE9 as well.

**Comment by jhihn** [comment]
Mission Control: "Displays have separate Spaces" is off

**Comment by cgchoffman** [comment]
I can't reproduce this even with Mission Control: "Displays have separate Spaces" turned off.

Anything in the logs? I assume it doesn't happen with other applications?  Could you try it with Firefox specifically?

**Comment by jhihn** [comment]
I think I may have messed this up.

 I used to be able to use both displays as I thought it should work, but now even Chrome is "broken'. Originally, Displays have separate Spaces" was on. I think it got reverted when I upgraded to El Cap.

I'll change the setting and try again. (requires reboot).
