### ISSUE TITLE
Check for Updates

### ISSUE THREAD

**Issue by srgloureiro** [Komodo/KomodoEdit#202]
1. I do Help > Check for Updates. The "View more information about this update" is WRONGLY pointing to the 9.0 page.

2. After I receive the update, Komodo says "The integrity of the update could not be verified"

**Comment by Naatan** [comment]
It's pointing to http://docs.activestate.com/komodo/9.0/, nothing wrong about that?

What build number are you updating from?

**Comment by testworksau** [comment]
Same issue for me r.e. the integrity of the update issue.

**Comment by Naatan** [comment]
Duplidate of #196

**Comment by srgloureiro** [comment]
@Naatan : 
«
It's pointing to http://docs.activestate.com/komodo/9.0/, nothing wrong about that?
»

It does not go to 9.0.1 nor that page says anything about 9.0.1.

«
What build number are you updating from?
»

9.0 > 9.0.1
