### ISSUE TITLE
Komodo 10 no longer allowing debugger connections...

### ISSUE THREAD

**Issue by ESPlanner** [Komodo/KomodoEdit#2022]
While working on a PHP project, Komodo 10 crashed (10 is much less stable than 9).  Prior to that, I was able to debug my PHP code, set breakpoints, etc.  Now when I try to enable "Listen for debug connections" nothing happens.  The PHP preferences say that I am correctly enabled for php debugging.  PHP info reports that the debugger is installed:

Xdebug v2.2.5-komodo,

properly for the correct php version.

Xdebug configuration is as follows:
```
Version	2.2.5-komodo
IDE Key	XDEBUG_ECLIPSE

Supported protocols	Revision
DBGp - Common DeBuGger Protocol	$Revision: 1.145 $

Directive	Local Value	Master Value
xdebug.auto_trace	Off	Off
xdebug.cli_color	0	0
xdebug.collect_assignments	Off	Off
xdebug.collect_includes	On	On
xdebug.collect_params	0	0
xdebug.collect_return	Off	Off
xdebug.collect_vars	Off	Off
xdebug.coverage_enable	On	On
xdebug.default_enable	On	On
xdebug.dump.COOKIE	no value	no value
xdebug.dump.ENV	no value	no value
xdebug.dump.FILES	no value	no value
xdebug.dump.GET	no value	no value
xdebug.dump.POST	no value	no value
xdebug.dump.REQUEST	no value	no value
xdebug.dump.SERVER	no value	no value
xdebug.dump.SESSION	no value	no value
xdebug.dump_globals	On	On
xdebug.dump_once	On	On
xdebug.dump_undefined	Off	Off
xdebug.extended_info	On	On
xdebug.file_link_format	no value	no value
xdebug.idekey	no value	no value
xdebug.max_nesting_level	100	100
xdebug.overload_var_dump	On	On
xdebug.profiler_aggregate	Off	Off
xdebug.profiler_append	Off	Off
xdebug.profiler_enable	Off	Off
xdebug.profiler_enable_trigger	Off	Off
xdebug.profiler_output_dir	/var/tmp/	/var/tmp/
xdebug.profiler_output_name	cachegrind.out.%p	cachegrind.out.%p
xdebug.remote_autostart	Off	Off
xdebug.remote_connect_back	Off	Off
xdebug.remote_cookie_expire_time	3600	3600
xdebug.remote_enable	On	On
xdebug.remote_handler	dbgp	dbgp
xdebug.remote_host	127.0.0.1	127.0.0.1
xdebug.remote_log	no value	no value
xdebug.remote_mode	req	req
xdebug.remote_port	9000	9000
xdebug.scream	Off	Off
xdebug.show_exception_trace	Off	Off
xdebug.show_local_vars	Off	Off
xdebug.show_mem_delta	Off	Off
xdebug.trace_enable_trigger	Off	Off
xdebug.trace_format	0	0
xdebug.trace_options	0	0
xdebug.trace_output_dir	/var/tmp/	/var/tmp/
xdebug.trace_output_name	trace.%c	trace.%c
xdebug.var_display_max_children	128	128
xdebug.var_display_max_data	512	512
xdebug.var_display_max_depth	3	3

```
I've restarted my web server and Komodo 10 (I'm running 10.1, build 89474) with no joy.

I haven't tried rebooting my machine, but that's next.

Still, Komodo should allow me to debug things remotely and it's not.  Any help would be appreciated.

**Comment by mitchell-as** [comment]
Hi, we did not changed anything in remote debugging for PHP between versions 9 and 10. Therefore this is likely a configuration problem. If you haven't already done so, please follow the instructions here: http://docs.komodoide.com/Manual/debugphp#debugging-php-komodo-ide-only_remote-php-debugging.

Komodo telling you it can debug PHP means it can do local debugging. It does not report that remote debugging is working, since that depends on your application.

How are you invoking remote debugging by the way?

**Comment by Naatan** [comment]
In addition to what @mitchell-as is asking, please check the status of Debug > Listener Status.

**Comment by ESPlanner** [comment]
Turns out when I started to close windows in preparation for a reboot I discovered the Active State Komodo crash reporter was open.  For some reason, the crash reporter doesn't bring itself to the front of the desktop.  Once I closed the crash reporter everything started working again.  So apparently whatever the issue is, it's related to the crash reporter.
