### ISSUE TITLE
Socket Closed Error

### ISSUE THREAD

**Issue by pdubinsky** [Komodo/KomodoEdit#2024]
While coding a file that has been open as a remote server, Komodo Edit spontaneously announces that the file has changed on the server. The KE prompts to reload the file. When saving the new file back to the remote server, KE displays "There was an error attempting to save 'filename.php ': Socket closed. The only way to recover is to close KE and reopen. The remote server is set up as an SFTP connection.

Open a file on a remote server using Open -> Remote File... Continue working on the newly opened file. Soon the above error will happen.

### Platform Information
Komodo Edit
version 9.3.2
Win10
version: 10.0.10586 Build 10586

**Comment by Defman21** [comment]
I'd suggest to try to use Komodo Edit 10. There were some fixes for remote stuff.

**Comment by Naatan** [comment]
As @Defman21 said please try Komodo 10 and let us know if your issue persists.

**Comment by pdubinsky** [comment]
I loaded the following Komodo Edit 10.1.1 and the problem has not recurred since I started 10.1.1 approximately 8 hours ago. In the previous version, 9.3.1, the problem would occur within 60 seconds.

I try again tomorrow and notify you of my results.

Thx for the help.

P
Komodo Edit, version 10.1.1, build 17414, platform win32-x86.
Built on Thu Sep 01 23:54:28 2016.

**Comment by Naatan** [comment]
Thanks for the followup @pdubinsky, I'll close this issue then as it is resolved in 10 :)
