### ISSUE TITLE
Scrollbar does not follow Ctrl-End

### ISSUE THREAD

**Issue by oehhar** [Komodo/KomodoEdit#2025]
### Short Summary

The scrollbar of the edit window does not follow Ctrl-End

### Steps to Reproduce

   *   Take a multi-page file
   *   Scroll to the top
   *   Press Ctrl-End to scroll at the end

### Expected results

Scrollbar jumps to the end

### Actual results

Scrollbar does not move

### Platform Information

*Komodo Edit or IDE?* 
IDE
*Komodo Version?* 
10.1.0
*Operating System (and version)?* 
Win 10 64bit GER
### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by mitchell-as** [comment]
Hi, please go to Edit > Preferences > Key Bindings. Then enter "document end" in the "Commands:" filter. You'll get two results. Pick the first one ("Editor: Go to End of Document"). What is the Current Key Sequence? Ctrl+End? Or is it empty? If the latter, your key bindings have left out this binding.

For the record I cannot reproduce this on a stock install of Komodo IDE 10.1.

**Comment by oehhar** [comment]
Ctrl+End
