### ISSUE TITLE
Vim p (paste) command pastes line above current line instead of below when current line is word-wrapped

### ISSUE THREAD

**Issue by ANSI-C** [Komodo/KomodoEdit#2026]
### Short Summary

Vim p (paste) command pastes line above current line instead of below when current line is word-wrapped

### Steps to Reproduce

- double y to yank a line text
- move to a line sufficiently long to be word-wrapped
- paste with "p"

### Expected results

the previously copied line should be pasted below current line

### Actual results

it is being pasted above

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* Komodo IDE, version 10.1.1, build 89474, platform win32-x86. Built on Thu Sep 01 14:27:01 2016.
*Operating System (and version)?* Windows 8.1

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by Naatan** [comment]
Reproduced.
