### ISSUE TITLE
commit tab/dialog get's windows error when there are only deleted files

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2031]
### Short Summary

If you delete a directory in your repo the commit dialog will stop updating and only show the following error:
`WindowsError(267, 'The directory name is invalid')`

![capture](https://cloud.githubusercontent.com/assets/655154/18691988/eebf9e50-7f4b-11e6-8330-8361086afb30.PNG)

**Comment by cgchoffman** [comment]
I didn't set the label.  It seems important to fix though so I set the milestone to 11.

**Comment by Naatan** [comment]
Oh I see, some other jerk set that label. Tsk tsk.

**Comment by cgchoffman** [comment]
Hrm, i'm not seeing this specific error any more but i'm seeing a different one which i have fixed:
```
Error 128 running 'C:\Program Files\Git\cmd\git.exe diff views.p.js'
  in 'C:\Users\cgcho\Projects\komodo\KomodoIDE\src\chrome\komodo\content': 
fatal: ambiguous argument 'views.p.js': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/93269782d24c95b128f67719bfed986955bbb569
