### ISSUE TITLE
When working with multiple windows, widget state get lost

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#2034]
### Short Summary
When working with multiple windows, the widget state get lost.
![2016-09-22 07_56_38- htaccess](https://cloud.githubusercontent.com/assets/3530262/18738244/3296931e-809a-11e6-87b5-f271aa56189c.png)
I have the places, open files and the relative includes widget combined in to one.
Normally I only have to combine the widgets again is when Komodo crashes, but this behavior is showing up when I just start Komodo and worked in the previous session with multiple windows.

### Platform Information
Komodo Ide 10.1.1 windows 10

**Comment by Naatan** [comment]
@cgchoffman this would require moving to workspace2.js I think, no?

**Comment by cgchoffman** [comment]
I resolved an issue around this for 10.1 I think but this boils down to a bug I've already reported: https://github.com/Komodo/KomodoEdit/issues/2000

Widget layout recovering isn't very consistent.  I think switching to workspace2 might help as the original workspace code leaves stale windows state prefs behind which end up getting loaded later when multiple windows are opened.  I think we can close this for #2000.  Let us know if you disagree @babobski.
