### ISSUE TITLE
cant move default color picker

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#2036]
### Short Summary

If you have a color at the bottom of you're window, and you trigger the colorpicker.
You're unable to move the color picker, so you can't access the buttons.
### Platform Information

Komodo Ide 10.1.1 Windows 10

**Comment by Defman21** [comment]
ColorPicker is a `<window>` object so you should able to move it. It works on Linux.

**Comment by babobski** [comment]
![2016-09-22 14_31_08-](https://cloud.githubusercontent.com/assets/3530262/18748221/8a81841c-80d1-11e6-955a-ce85ff459f0e.png)
Had the same problem problem with the rgba colorpicker  with the implementation of the xul wrapper.
It uses a dialog, witch I cant move on windows, to fix it I had to change it into a window.

**Comment by Defman21** [comment]
Try to use native decorations?

**Comment by babobski** [comment]
When using native decorations I can move the color picker.
When I'm not using native decorations, there are windows I can move ( like the preferences window, project preferences ) and there are windows that cannot be moved like the properties of a toolbox-item.
And the run command window doesn't use a xul wrapper.

**Comment by Defman21** [comment]
None of these you named are using `<dialog>` except for properties of a toolbox item.

Also you're missing the meaning of xul wrapper - it's being used to wrap HTML so it could access XUL itself (`chrome://` urls, Less, etc.). You should be able to move `Run Command` window because it's a window, not a dialog.

**Comment by babobski** [comment]
>  You should be able to move Run Command window because it's a window, not a dialog.

Added the note for the run command, because it's missing the decorated border, it's already using native decoration.
![2016-09-22 15_06](https://cloud.githubusercontent.com/assets/3530262/18749272/62bf545e-80d6-11e6-87f4-4c58493787cc.png)

**Comment by Naatan** [comment]
There are definitely some dialogs that cannot be moved. These should pretty much exclusively be modal dialogs. I'm not having any issue moving the color picker one when native decorations are disabled. @cgchoffman could you test on Windows? I only have access to OSX today :\

**Comment by cgchoffman** [comment]
Confirmed @babobski bug:  I can't move color picker on Windows with native decorations disabled.

**Comment by Defman21** [comment]
This is Windows only. I can move dialogs without native decorations.

**Comment by Defman21** [comment]
#1621 could be related to this.

**Comment by babobski** [comment]
Looks like it's the default behavior for a dialog on windows.
If I look at the dialogs under [https://github.com/Komodo/KomodoEdit/tree/master/src/chrome/komodo/content/dialogs](https://github.com/Komodo/KomodoEdit/tree/master/src/chrome/komodo/content/dialogs) all the windows that are using "dialog" I can't move.
alert.xul, compare.xul, iconpicker.xul are all using the "dialog" type and I can't move any of them.

**Comment by Defman21** [comment]
It's a bug. It would be an excepted behavior if it would behave in the same way across all systems (OSX, Linux, Windows).
