### ISSUE TITLE
Re-work color picker

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#2038]
### Short Summary

Maintaining the code is VERY hard. (2007) It's old, there are some variables with no name meaning (hard to tell to what they are referring), jshint fails on each line, there are bugs with EOL's, there are tabs (:heart: spaces)
and it uses tables.

Not necessary to change the functionality, just make the code more modern.

**Comment by Defman21** [comment]
Probably, when we get rid from tables, it will become responsive. Which will fix resizing functionality.

**Comment by Naatan** [comment]
We won't ever rework this color picker, it wasn't written by us in the first place. If and when we dedicate time for this it will be to write our own.
