### ISSUE TITLE
erroneous linter warnings

### ISSUE THREAD

**Issue by brendonmartino** [Komodo/KomodoEdit#2041]
### Short Summary
Irrelevant Linter warnings constantly appear on every ruby coded page in random lines.
It is always the same warnings which are randomly (it would seem) placed and have absolutely no real merit in the context of the file:

"method redefined; discarding old user_dir"
"File.exists? is a deprecated name; use File.exist? instead"
"previous definition of user_dir was here"

### Steps to Reproduce
Create or open a ruby file with enough lines. I can reproduce it always with ruby files of a certain length or complexity.

### Expected results
Linter warning should be relevant, not random and irrelevant.

### Actual results
These three warnings exist randomly on new and old files, even after an upgrade to latest version: Komodo-Edit-10.1.1-17414

### Platform Information

Komodo-Edit-10.1.1-17414
Windows 10 (64-bit), latest patches applied

### Additional Information
-on request...

**Comment by Naatan** [comment]
Objectively those seem like totally relevant linter warnings to me, can you share a file on which they are triggered in a way that is unexpected?

**Comment by brendonmartino** [comment]
The whole file? Not really. The codebase is proprietary. I can share with you a snippet of code, though:

`  def self.log_step(logStr)
    @step_count = @step_count + 1

    puts "*** Step #{@step_count}: #{logStr}"
    @logger.info("*** Step #{@step_count}: #{logStr}")

    @step_start_time = Time.now
  end`

In this example, the linter tags the that starts with @logger.info with:
"previous definition of user_dir was here"

There is no correlation with any code, past or present...I don't think any example sI post here can help you at all. There is nothing to see, nor any clues to be gained from it. Like I said, it's totally irrelevant.

Can anyone else reproduce this on their own? Or does my machine just have a hex on it? ;-)

**Comment by brendonmartino** [comment]
Try this: get the code from this page:
http://sandbox.mc.edu/~bennet/ruby/code/class1_rb.html

Now save it as a ruby file and open it with Komodo.

In my machine, the linter highlights line 24:
```print "A: ", a.get, " ", b.get,"\n";```
with: "method redefined; discarding old user_dir"

**Comment by brendonmartino** [comment]
Can anyone replicate this? Or am I just special?

**Comment by Defman21** [comment]
I'm not able to reproduce it. I think you've added an additional Ruby Import directory (Prefs - Languages - Ruby).

**Comment by brendonmartino** [comment]
Don't think that's the problem...I uninstalled and installed this version of Komodo fresh -- no changes to stock install....I only see one Ruby listed there. I don't think that's the issue..

**Comment by Defman21** [comment]
Worth trying to reproduce it in Safe Mode. (Help - Troubleshooting - Restart in Safe Mode). Reseting CodeIntel cache could do the trick too.

**Comment by brendonmartino** [comment]
ok, I'll try those suggestions to see if they work...

**Comment by brendonmartino** [comment]
None of those suggestions worked. After fiddling with things for an hour, I'm about ready to give up and go back to Komodo Edit 9.3 (Komodo-Edit-9.3.2-16460).

It's not just that, either. The new version of Komodo 10 Edit is super buggy. Several times I tried to close a file and it didn't make the tab disappear. I also tried saving files and the save icon never turned grey (it did save the file, but it was not updating the icon). The last straw was, I was trying to open a file and it would not open it. 

I'm done with this IDE version. Wake me when it's been tested a little better...

**Comment by mitchell-as** [comment]
Sorry you've been having so much trouble. I was not able to reproduce the random linter warnings from the class1.rb file you linked to. We did not change any of our Ruby linter code from 9.3 to X. If you don't have such problems in 9.3 then I'd venture a guess it's either a configuration issue or bad profile. As a last resort you can backup your entire c:\users\username\appdata\local\activestate\komodo* folder, remove it, and launch Komodo again.

Our products get plenty of testing and you are the only person who has reported/experienced this issue. None of us in this ticket can reproduce it. I'm afraid it does not appear at first glance that Komodo is to blame here. You mentioned some other open/save/close/etc. issues too. As far as I'm aware, you are the only one experiencing those too. Our issue tracker usually fills up quickly if it's a problem that affects all of our users.

Please feel free to re-open this issue if you have more information to share.

**Comment by Naatan** [comment]
> It's not just that, either. The new version of Komodo 10 Edit is super buggy. Several times I tried to close a file and it didn't make the tab disappear. I also tried saving files and the save icon never turned grey (it did save the file, but it was not updating the icon). The last straw was, I was trying to open a file and it would not open it.

That really sounds like something about your install is corrupt. Did safe-mode give any results? Note when you restart in safe-mode your IDE should start with default settings. If it does not then you are not in safe-mode.
