### ISSUE TITLE
Replace `>/v` symbols with folder open/close icons in Trees

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2042]
### Short Summary

Had a discussion with a user in the forums and I actually agree with their rational that open/close icons are more desirable over the `>/v` symbols we currently use to indicate whether a folder is open or closed in a file tree.

I suspect that we might have done this because the symbols are something we can't remove from the xul that the tree is built out of under the hood but filing this to find out.

**Comment by Defman21** [comment]
Please give us a choice! I really like those >/v

**Comment by Naatan** [comment]
I'll leave this open to discuss but I don't agree that this should be an enhancement request. As I said on Slack I do not agree with the idea that this is a bug or undesirable. 

My stance is that the current visual indicators are sufficent and properly communicate that this is a folder (or a parent). In addition to the icon the folders are also colored differently. 

Adding folder icons adds a lot of clutter, and the open/closed state of folders are not good at communicating the state.

**Comment by cgchoffman** [comment]
> My stance is that the current visual indicators are sufficient

This is true but I personally think icons would be better and more appealing.  I'm not with @defman, I don't like the arrow symbols.  Seems like it would be more consistent in the Treeviews to have icons for folders like the other objects there.

> Adding folder icons adds a lot of clutter, and the open/closed state of folders are not good at communicating the state.

If we choose one or the other I don't see this as clutter. Having both is definitely clutter (as it was before).  And there is an open and a closed folder icon (was already implemented in 9) so it should show open/closed state just fine.

**Comment by Naatan** [comment]
The other issue this would create is if we created folder icons then they should only show in places where the parent structure is a folder structure, not in eg. Preferences where the parent structure are categories. Hence it wouldn't just be a case of replacing icons, it would need new logical structures to identify the parent structure and show the appropriate icon accordingly. 

Aside from my not seeing the merit and subjectively preferring the current implementation, it also just doesn't seem worth the effort it would take to implement this, given that only two users (Carey included) have expressed that they would prefer folder icons.

**Comment by babobski** [comment]
Personaly I liked the situation with the folder icons more. 
The biggest problem I have with removing the icons is when you pick a remote file. 
There is now no diffrence between a folder or a file.
Komodo 9.*:
![2016-09-23 06_51_57](https://cloud.githubusercontent.com/assets/3530262/18774516/40238e7c-815a-11e6-9948-7798af7410d8.png)

Komodo 10.*
![2016-09-23 06_53_15](https://cloud.githubusercontent.com/assets/3530262/18774531/6bfd77ba-815a-11e6-93bc-34912b416a19.png)

**Comment by tribis** [comment]
Can I ask, how many users complained about the icons in Komodo 9?

**Comment by Defman21** [comment]
@babobski the scope is Places, not the Remote File Picker. I assume this is a bug.

> like the other objects there.

This is configurable, I'm able to hide file icons at all. It was hard for me to see the difference between open/closed folder icon, but `>/v` looks much more different rather than a yellow folder with a little triangle in it.

**Comment by cgchoffman** [comment]
2 out of 4 users is almost a majority ;)

Seriously though, I agree that unless this gets more interest, it's not worth doing at all.

**Comment by cgchoffman** [comment]
@babobski I think @Defman21 is right.  That's extremely annoying.  Could you open a new bug please?  It's unforutnately not related to this bug at all.  The treeview implementations are very different between the two interfaces.

**Comment by tribis** [comment]
My thought was: how many complains it took Active State to remove the icons in the first place. I doubt that anybody had complained about the icons being in the way, nonetheless you removed them. Now someone has become affectionate to the new look, and three complains about the missing icons are no longer enough. So in my view the "vote" should have been: no complains to remove the icons, against complains to put the icons back. This is just for fun anyway.

If you succeed removing the folder icons in the project pane it will make the situation better for everybody (both icon lovers and haters) by reducing the obvious inconsistency.

Btw. I have added the bug report about the remote file dialoge (see the reference to it in this thread, above your second last comment)

**Comment by Naatan** [comment]
The new UI had a lot of reasoning behind it, if we held everything to a vote we'd never get anywhere, and you'd end up with a horrible frankenstein of a product. 

To learn more about the new UI check http://komodoide.com/blog/komodo-extreme-makeover/

As for the votes we have gotten. Three votes is nothing when you consider our userbase is in the thousands. I'd want to see significantly more people voice their distaste for the current implementation before considering changing it, unless a compelling argument could be made that made the folder approach objectively better.

**Comment by tribis** [comment]
I said it was just for fun.

**Comment by cdcmicro** [comment]
For my two cents, I'm OK with the >/v.  I think it's a design choice that falls into the category of "something new to get used to".

**Comment by babobski** [comment]
If you want to get the folder icons back in the places widget, this can easily be done with some custom less in your scheme.

If you add this:
```less
tree.twisty-only treechildren::-moz-tree-image
{
    margin-left: -10px !important;
}

#directoryTree treechildren treeitem[type="folder"] {
	background-image: url("koicon://ko-svg/chrome/icomoon/skin/folder2.svg?size=12") !important;
	background-size: 12px !important;
}

#placesViewbox_placesWrapper tree  treechildren::-moz-tree-twisty {
	background-image: url("koicon://ko-svg/chrome/icomoon/skin/folder2.svg?size=12") !important;
	background-size: 12px !important;
}
	
#placesViewbox_placesWrapper tree treechildren::-moz-tree-twisty(open) {
	background-image: url("koicon://ko-svg/chrome/icomoon/skin/folder-open.svg?size=12") !important;
}	
```

The places widget will kook like:

![afbeelding](https://cloud.githubusercontent.com/assets/3530262/23291933/281a3a30-fa5c-11e6-9c99-630214c13457.png)

**Comment by tribis** [comment]
Aha, neat, thank you!
/paolo
Den 24-02-2017 kl. 06:41 skrev Bob de Haas:
