### ISSUE TITLE
Multiple entries for Komodo Edit in AppData folder on Windows

### ISSUE THREAD

**Issue by testworksau** [Komodo/KomodoEdit#2046]
### Short Summary

I recently had a hard disk failure which required me to reinstall everything.

I installed Komodo Edit 10.0, and it has since upgraded to 10.1.

The AppData directory looks as follows.

![image](https://cloud.githubusercontent.com/assets/11973031/18770237/7221e8c0-8177-11e6-8b8e-089c2d4f1b17.png)

### Steps to Reproduce

1. Uninstall Komodo Edit
2. Wipe the AppData -> ActiveState directory
3. Install Komodo Edit 10
4. Upgrade to 10.1 via the auto upgrader

### Expected results

There should only be one folder containing the Komodo Edit application data

### Actual results

There are two folders containing the Komodo Edit application data

### Platform Information

*Komodo Edit or IDE?*  Edit
*Komodo Version?* 10.1
*Operating System (and version)?* Windows 10

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by cgchoffman** [comment]
> There should only be one folder containing the Komodo Edit application data

They are different folders and hold different information.  They are both meant to be there.
