### ISSUE TITLE
Context menus in Komodo 10, are cluttered and unclear

### ISSUE THREAD

**Issue by tribis** [Komodo/KomodoEdit#2048]
### Short Summary
I use Interface colors: standard, and preferably classic mode. 
The new context menus in Komodo 10 are a regression in readability, clearness, usability. To make this point it takes some writing:

In general, context menus in Komodo 10 try to be something different from what is the platform standard. 
Some considerations about this point:
1. Why should the Windows standard that suits millions of people suddenly be unfit for a single IDE?
2. Why should I, that obviously have chosen Windows as a platform, feel a need to have something different when I use my IDE (I could use McOS or Linux if I hated this standard) for something as basic as context menus (If I remember well MS Windows introduced those first)?

If you decide nonetheless that you want and can outsmart the platform standard, here are some 
specific considerations on the result:

Here are 2 screenshots to see what we are speaking about:
The standard context menu (from Komodo 9, but it could be taken from a context menu in Firefox or in Windows Explorer:
![komodo9-contextmenu](https://cloud.githubusercontent.com/assets/54670/18777719/fc7e4a9c-8170-11e6-9321-110984d176e9.PNG)

Here the same in Komodo 10:
![komodo10-contextmenu](https://cloud.githubusercontent.com/assets/54670/18777835/96521ba8-8171-11e6-92b2-4d506b84a706.PNG)

Differences from 9 to 10 are: 

- Reduced contrast between text and background
- Removed shadow that hovers menu away from background
- The outer border has become white, with the result that it is only visible on those edges that happen to be above some darker surfaces
- Removed the icons that served as an additional clue to what the menu item is about
- Reduced the space above and below each menu item (cannot say for sure but it looks so)

Now, unless the previous menus where a punch in the eye, everybody can say, even without looking at the result, that this list cannot be good. What you have done is effectively to remove/attenuate all those features that made the context menu, and its items inside it, stand out and be easily readable and readily perceivable.

Possibly I could understand an argument supporting this move if the menus where always in the way, but they only appear when we need them. And when we need them, we only need *them* and nothing else: why should it be an advantage that they be less conspicuous and more difficult to read, and their items more difficult to interpret just to save space, on something that is at the focus of all of your attention when we use it, and then disappears automatically ?

Furthermore the design choice breaks with how other similar elements are done in the same IDE:
Pls. see an inline menu in the preferences dialog:

![komodo-menu-consistency](https://cloud.githubusercontent.com/assets/54670/18777548/04b78936-8170-11e6-8653-df475112bea0.PNG)
Here the design is the same as those of the old context menu (and for goodness' sake don't change it!)

Finally, if for some reason I could not convince you, I would like to be able to choose the old menus when selecting "enable classic mode"

### Platform Information
Komodo IDE, version 10.1.1, build 89474, platform win32-x86. Built on Thu Sep 01 14:27:01 2016

**Comment by mitchell-as** [comment]
Hi, sorry you don't care for the changes. I'm pretty sure there's been a discussion like this before on our forums. The new menu look is part of Komodo X's UI refresh and will likely take a bit of time to get used to. We did incorporate a request to increase menu item padding, but other than that, I don't think we're planning to revert to the old style. @Naatan please correct me if I'm wrong.

Also, classic Mode is just an approximation to the old style and will not be a perfect replica.

**Comment by tribis** [comment]
I do care pretty much, but I don't find them well-thought out.
However, as you have accepted the point about more air around the text (item padding), please do notice that all the rest of your design is based on pretty large bands where the elements sit. For instance on the top bar  there is a wide space around and in between the buttons/icons. So please try to strike a similar proportion so that the look is consistent. If you do that I think the menu will look more "finished" than it looks now.

Finally it would be relieving if someone could explain me the (design) logic of having a border that is not (always) visible, no matter the specific design.
Don't bother to answer me, I will stop caring about this from now. I've used a couple of days to notify all the things that have hurt me the last few months, now I go back to work.

At least this will stand for the next debate that I seem to have missed this time. Maybe for Komodo 12 or 13. 'Cause I'll probably still be using it :)

**Comment by Naatan** [comment]
> Finally it would be relieving if someone could explain me
> ...
>Don't bother to answer me, I will stop caring about this from now.

With due respect, that seems a bit contradicting ;) I'll assume you still want this question answered. 

Originally the menu's did not have borders at all, unfortunately that created issues where the menu's did not contrast with whatever is behind them. So I added the border which was "meant" not to be visible unless necessary. The end result is a border which feels broken, which I've come to realize. 

This as well as many other small issues (eg. your concern about the padding being somewhat inconsistent) will be addressed. It's important to note that the new UI is just that - new. It will still evolve further over the coming releases, though future updates to the UI will be much smaller and more iterative.

**Comment by tribis** [comment]
I just didn't want you to use more time on an issue that I accept won't be (fundamentally) changed. So I just put my last comment to future memory, as I wrote. Your comment now seems also more conciliatory than the previous one. And thanks for the answer, that makes sense.
