### ISSUE TITLE
Ruby: `method %{}` does not highlight %{} as string

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#2051]
### Short Summary

```ruby
whatever.call %{
  Oh... 'cool!';
}
```

%{...} should be string. You can replace `whatever.call` with `puts` and it will work fine.

**Comment by mitchell-as** [comment]
Duplicate of #1704 in a way. Once #1704 is resolved, this will be too.

**Comment by Defman21** [comment]
Technically, `%<modifier>{}` should be highlighted differently depending on the modifier. If there's no modifier, then highlight it as string. I don't know any other modifiers that should be highlighted differently except for `%r{}`. I'll address this in #1704
