### ISSUE TITLE
Profile/optimize onUpdateUI

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#2055]
Since we removed the delay it's worth looking into what is happening under onUpdateUI and ensuring it's not running into redundancies now that we are no longer grouping calls.

Context: https://github.com/Komodo/KomodoEdit/commit/d67cc172bf352719c36707007fe096d425742fa7

**Comment by Defman21** [comment]
I think you could collect some profiling data from those who granted you a permission to collect anonymous data. As for me, I didn't notice any drops in performance.
