### ISSUE TITLE
Package installation times out

### ISSUE THREAD

**Issue by zack10** [Komodo/KomodoEdit#2059]
### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by mitchell-as** [comment]
Hi, does it work if you try again? I get that sometimes too and just have to try again and it works.

**Comment by zack10** [comment]
yes it worked with other packages but for color schemes it does not work i
tried it many times but it didn't work

**Comment by mitchell-as** [comment]
What color scheme? I just tried with "Blue Soda" and it worked without issue.

**Comment by zack10** [comment]
well then i'm probably the only one having this problem cause whenever i
try to install a color scheme it errors out

**Comment by mitchell-as** [comment]
If this happens again, please post the contents of your Help > Troubleshooting > View Log File.

**Comment by zack10** [comment]
OK, Thanks 👍
