### ISSUE TITLE
Shortcut for "Make Lowercase" does something else in Komodo 9.0.1

### ISSUE THREAD

**Issue by vitaly-krugl** [Komodo/KomodoEdit#206]
Komodo 9.0.1 
Mac OS X Yosemite on MacBookPro

Keying in Shift-Command-U brings up unexpected dialog: 
![screen shot 2015-04-23 at 4 36 43 pm](https://cloud.githubusercontent.com/assets/1441066/7309758/5559fad6-e9d7-11e4-8cb8-d11b2039452a.png)

This sub-menu documents the "Make Lowercase" shortcut as Shift-Command-U:
![screen shot 2015-04-23 at 4 38 05 pm](https://cloud.githubusercontent.com/assets/1441066/7309759/597e3ed8-e9d7-11e4-8b26-8629e1456d81.png)

**Comment by Naatan** [comment]
Fixed on IDE repo.
