### ISSUE TITLE
nodejs debugger crash on a variable assignation

### ISSUE THREAD

**Issue by eco747** [Komodo/KomodoEdit#2060]
### Short Summary

the Komodo debugger crash when executing this line of NodeJS code:
var L = "’";
### Steps to Reproduce

just create a .js with this line & start debugging
(copy it)
### Expected results

L should be assigned & not crash the debugger
### Actual results

read ECONNRESET
Error: read ECONNRESET
    at exports._errnoException (util.js:1036:11)
    at TCP.onread (net.js:564:26)
### Platform Information

Komodo IDE 10 
windows 10

**Comment by eco747** [comment]
in fact it's the same for all (french) special chars
var L = 'Précédent';

**Comment by mitchell-as** [comment]
Thanks for the report. At first glance it appears that something cannot handle UTF-8.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoIDE/commit/c3d5a2d62c2e44056c47c051b9a6b4cdcc710da5
