### ISSUE TITLE
Add Preference to "gofmt" Executable for Code Formatting

### ISSUE THREAD

**Issue by mitchell-as** [Komodo/KomodoEdit#2062]
### Short Summary

Komodo assumes the "gofmt" executable is in the same location as the "go" executable. A preference needs to be added in the Edit > Preferences > Languages > Go preference set to point to "gofmt".

See discussion here: https://github.com/Komodo/komodo-go/commit/14282c20d7b8c5e33c89d90c716665d15bcac346#commitcomment-19197863

**Comment by Naatan** [comment]
Marking as bug and prioritizing as this currently causes gofmt to break on Windows

**Comment by Naatan** [comment]
After further thought; the location can already be customized using Prefs > Formatters. Adding another pref would just make this mechanic convoluted and confusing.
