### ISSUE TITLE
Left Panel

### ISSUE THREAD

**Issue by uziel200** [Komodo/KomodoEdit#207]
In the new version: 9.0.1 with the Abyss skins over OS X, the left panel don't show the background color in darkness, so the text is not visible.

[Example](https://cloud.githubusercontent.com/assets/5307189/7322933/dfb2a464-ea70-11e4-9e96-b603fc54ca47.png)

**Comment by cgchoffman** [comment]
Looks like you still need to do a restart.  Does the issue persist after a restart?

**Comment by uziel200** [comment]
Yes, the issue continue after restart. Actually I've uninstall and install again and the issue persist.

**Comment by Naatan** [comment]
What OSX version is this?

**Comment by uziel200** [comment]
OS X Yosemite 10.10.3

**Comment by cgchoffman** [comment]
I've reproduced  Left pane remains bright and shiny.

**Comment by Naatan** [comment]
Will further track this in #213
