### ISSUE TITLE
Unhandled exceptions when starting debugging or interactive Python shell

### ISSUE THREAD

**Issue by anthonyho007** [Komodo/KomodoEdit#2079]
### Short Summary

My Komodo IDE won't compile in python nor interactive shell works. I have been using the python shell frequently in the past, but a few days ago,  the interactive shell crash and it won't  work again, even if i try uninstall and install it again
### Steps to Reproduce

Run/Go 
Tools > interactive shells > python shells
### Actual results

Unhandled exception in thread started by <bound method dbgpSocket._getIncomingDataPacket of <dbgp.client.dbgpSocket instance at 0x10c99c680>>
Traceback (most recent call last):
  File "/Applications/Komodo IDE 10.app/Contents/SharedSupport/dbgp/pythonlib/dbgp/client.py", line 2233, in _getIncomingDataPacket
    self.queue.put(argv)
AttributeError: Queue instance has no attribute 'put'
### Platform Information

OS X Build 13F1603
Komodo IDE 10 (newest version)
### Additional Information

 -- eg. Error logs, screenshots, workarounds --
Python 2.7.5 (default, Mar  9 2014, 22:15:05) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)] on darwin
Type "copyright", "credits" or "license" for more information.
Unhandled exception in thread started by <bound method dbgpSocket._getIncomingDataPacket of <dbgp.client.dbgpSocket instance at 0x1102d5680>>
Traceback (most recent call last):
  File "/Applications/Komodo IDE 10.app/Contents/SharedSupport/dbgp/pythonlib/dbgp/client.py", line 2233, in _getIncomingDataPacket
    self.queue.put(argv)
AttributeError: Queue instance has no attribute 'put'

**Comment by mitchell-as** [comment]
That's really odd. Does your PYTHONPATH have anything in it that includes a custom "Queue" module?

Or, does it work if you try running in safe mode? (Help > Troubleshooting > Restart in Safe mode)
