### ISSUE TITLE
Komodo 10 crashing on startup after working with SFTP

### ISSUE THREAD

**Issue by RogierVelde** [Komodo/KomodoEdit#2082]
### Short Summary

Komodo sometimes crashes on startup after working with remote folders. When this occurs it does this every subsequent try, can only be worked around by starting without an internet connection so that it catches the error.
### Steps to Reproduce

Not sure, but it happened on both my old personal laptop as well as a brand new work laptop with clean windows install. Seemingly at random.
### Expected results

The editor opens with previous open files restored
### Actual results

The program crashes without an error report/message and gets terminated by windows.
### Platform Information

Komodo Edit 10, Windows 10.0.14393
### Additional Information

I connect to external folders over SFTP, with a private key that has a passphrase. Maybe it could have something to do with that? As it crashes it doesn't ask me to enter the passphrase (which is what should happen directly on startup as it connects)
Where can I find a log to supply with the report?

**Comment by Naatan** [comment]
Can you reproduce this using `Help > Troubleshooting > Restart in Safe-mode` ?

Please verify that when restarting in safe-mode Komodo should be using the default UI (all your settings would be temporarily reset).

**Comment by Naatan** [comment]
Please share your error log after reproducing the issue and before restarting Komodo again.

http://docs.komodoide.com/Troubleshooting/Where-does-Komodo-keep-settings-data#where-does-komodo-log-errors

**Comment by RogierVelde** [comment]
It happened again, error log:
[pystderr.log.txt](https://github.com/Komodo/KomodoEdit/files/532663/pystderr.log.txt)

**Comment by Naatan** [comment]
Can you uninstall the gitbranch extension? It's no longer required as the functionality is built-in to Komodo 10.1

Other than that I don't see anything in your log that looks wrong. Does the crash happen consistently or is it random?

**Comment by RogierVelde** [comment]
Huh, I don't recall even installing such an extension as I work with Git CLI but I'll look into that.

It seems to happen at random, but as I said - once it happens it keeps happening until I start Komodo without an internet connection.

**Comment by Naatan** [comment]
When you have your next crash could you send your prefs.xml to support@activestate.com and reference this ticket? 

For finding your prefs.xml: http://docs.komodoide.com/Troubleshooting/Where-does-Komodo-keep-settings-data

**Comment by LionelLaffineur** [comment]
Dears,

I have the same problem every time I start Komodo Edit 10.1; I've attached my log file
[pystderr.log.txt](https://github.com/Komodo/KomodoEdit/files/560088/pystderr.log.txt).

It is easy to reproduce as it happens every time starting Komodo after a remote server has been connected.

Thanks in advance for your help,
Lionel

**Comment by Naatan** [comment]
@LionelLaffineur Please see my previous post, the same would apply to anyone having this issue. Thank you!

**Comment by Naatan** [comment]
OTRS #57884

Thanks @RogierVelde !

**Comment by koyae** [comment]
@Naatan I just upgraded from 8.5 to 10.2 and I am having this problem. For me, crashes are consistent on every startup with the Windows "KomodoEdit has stopped working" message, which appears 3 to 5 seconds after KomodoEdit opens. I also have an entry in the Servers list that uses a passworded SSH-key.

**Platform:** Windows 7 Enterprise

Footnote: the heading you linked to with http://docs.komodoide.com/Troubleshooting/Where-does-Komodo-keep-settings-data#where-does-komodo-log-errors does not exist, and I'm not seeing any `pystderr.log` anywhere on disk.

**Comment by cgchoffman** [comment]
> Footnote: the heading you linked to with [...] does not exist

Are you saying the link doesn't work or you can't find the path on your system? If it's the latter please share what path you're trying to use.

The link works fine for me and those paths are correct.

**Comment by koyae** [comment]
@cgchoffman
![screen](https://cloud.githubusercontent.com/assets/11679041/23324160/7c2218a8-faa9-11e6-8717-dfc8a876ba36.png)

**Comment by cgchoffman** [comment]
@koyae. K, the webpage works.  As I said, those paths are correct so please share the path your are trying to find.

**Comment by koyae** [comment]
@cgchoffman For comparison, here's **Version:9**'s page. I was saying the current version is missing the heading which @Naatan [was trying to link to](https://github.com/Komodo/KomodoEdit/issues/2082#issuecomment-251140488):
![screen2](https://cloud.githubusercontent.com/assets/11679041/23324234/d6cacde0-faa9-11e6-84a8-3e7a98a37e17.png)

With regards to the log-file itself in my case, I think Komodo just failed to create a dump the first time. After reopening it to let it crash again, the file's now appeared (find attached).
[pystderr.zip](https://github.com/Komodo/KomodoEdit/files/800652/pystderr.zip)

Sorry for any confusion.

**Comment by cgchoffman** [comment]
> For comparison, here's Version:9's page. I was saying the current version is missing the heading which

Thanks for clarifying, I had no idea what your were talking about.

> With regards to the log-file itself in my case, I think Komodo just failed to create a dump the first time. After reopening it to let it crash again, the file's now appeared (find attached).
> pystderr.zip

That log file should always exist regardless of a crash.  Komodo doesn't dump crash information to that file. It's just run time errors and information.  See nathanr's comment here: https://github.com/Komodo/KomodoEdit/issues/2082#issuecomment-257339057

We're looking for prefs.xml files now.

Thanks for helping.

**Comment by koyae** [comment]
@cgchoffman I've sent a zipped version of my `prefs.xml`-file to the support@activestate.com address. Thanks and cheers.

**Comment by cgchoffman** [comment]
> I've sent a zipped version of my prefs.xml-file to the support@activestate.com address. Thanks and cheers.

@koyae  awesome, thank you very much.  I'm just about to start testing.

**Comment by cgchoffman** [comment]
Thanks everyone. Reproduced this.  The key was indeed the keys.  Apologies that I didn't take a look at this sooner.  Having said that, you'll have better luck using PuTTY on Windows for SSH work.  If you're interested in switching to PuTTY we have docs for it and i'll be happy to assist you if you get stuck.

Digging in for a repliminary look.  I can't say at this point whether or not a fix would be released before 11.

**Comment by cgchoffman** [comment]
There will be a nightly available with this fixed tomorrow 12 pm (Feb 28): http://downloads.activestate.com/Komodo/nightly/
