### ISSUE TITLE
Unable to step into 'sourced' tcl code

### ISSUE THREAD

**Issue by WheelDogs** [Komodo/KomodoEdit#2086]
### Short Summary

Ordinarily, one is able to step into source tcl script.
Note: going to discuss another related issue - In general, Komodo is weak on debugging core ooTcl.
The sourced code executes 'my pwd', where pwd returns a different value when executed in debug mode or run from source. Interesting.

Stated differently, if the same tcl code is executed directly by wish no error results - pwd returns the correct directory value.
### Steps to Reproduce

see attached

set a breakpoint at the orange arrow in Plugin_Init
set a breakpoint in oo:objdefne $plugin

run debug mode
K breaks at first breakpoint.
First 'step into' results in error.

The error is produced because pwd returns a directory in which the calling script is located; not the directory of program containing the pwd command.

The 'puts' command doesn't even get executed (it doesn't appear in debug area_

All  that resul
### Expected results

step through source code
### Actual results

step to next line in calling code
### Platform Information

*Komodo IDE
*Komodo Version 10.1.1
WIn10, 64 bit. 
![komodo 10 1 1 001](https://cloud.githubusercontent.com/assets/21134598/19134492/522f2938-8b2c-11e6-8a68-7676234d2930.png)
![komodo 10 1 1 002](https://cloud.githubusercontent.com/assets/21134598/19134493/560f0492-8b2c-11e6-8b54-9f79f9eb4b0c.png)
![komodo 10 1 1 003](https://cloud.githubusercontent.com/assets/21134598/19134496/57898ac2-8b2c-11e6-8dcf-f74ffb7c9ba1.png)
![komodo 10 1 1 001](https://cloud.githubusercontent.com/assets/21134598/19134509/6587024e-8b2c-11e6-9f78-4784c31ec787.png)
### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by mitchell-as** [comment]
Hi, I'm sorry in that I really don't understand what this ticket is saying. You gave me some screenshots and a description of something wrong that seems to be happening, but that error dialog does not look like Komodo's. Is your script throwing that error?

Without some sample code and instructions that reproduce a problem, I likely will not be able to help, as there is nothing for me to test and analyze on my computer.

**Comment by WheelDogs** [comment]
Will clean it up somewhat.
There are really two issues here:
1. The error that results from K's inability to return the correct value from the pwd command. When the same code is executed directly from wish, there is no error.
2. the apparent inability to step through a 'sourced' script.

I will put in what should be unnecessary code to eliminate the error in pwd. Perhaps, should have reported it separately, anyway.

The screen shots are of the code that is producing the problem. I can provide it in text form as well.

**Comment by cgchoffman** [comment]
> I can provide it in text form as well.

Please always do this :)  Screenshots aren't helpful unless you're bug is about aesthetics.  If you need us to execute code then provide the minimal viable code needed to reproduce the issue then give us exact steps of how to proceed.  Thanks for reporting.

**Comment by WheelDogs** [comment]
'main.tcl' contains the method Plugin_Init.
The breakpoint within the 'foreach' is respected.
From that point, I am not able to step into the script that is being sourced. In this case, it is 'init.tcl'.
Notice, init.tcl has a breakpoint. It is ignored.

What happens:
The sourced script simply gets executed.

Notice the code after "set dir [my pwd]"
I had add additional folder names to the 'file join' command because K doesn't return the correct path.
The script in the 'else' clause is the original script. It works only when Komodo is not being used. i.e. when the script is executed directly from the shell.

Net: when using Komodo the execution of pwd returns a path that is different from that returned when executing the script otherwise.

Am using tcl/tk 8.6.4 with the core oo.

attached are images that show the breakpoints; and tcl scripts
![breakpoint001](https://cloud.githubusercontent.com/assets/21134598/19205504/e29f22c2-8cb0-11e6-8b68-933f362dfd70.png)
![breakpoint002](https://cloud.githubusercontent.com/assets/21134598/19205505/e2a6f056-8cb0-11e6-9518-e4b1591bc0ae.png)


[brreakpoints.txt](https://github.com/Komodo/KomodoEdit/files/517111/brreakpoints.txt)
The  script that contains the 'sourcing' command is huge and instantiates all sorts of objects.
It is a customized version of 'ezedit' which can be downloaded from github, i believe,


In addition, it would be super of Komodo included  a view listing the methods. It doesn't.

**Comment by WheelDogs** [comment]
Will do and just did...

 

Thanks...

**Comment by WheelDogs** [comment]
![breakpoint001](https://cloud.githubusercontent.com/assets/21134598/19215628/db203d9a-8d70-11e6-9016-cadb0cd94596.png)
![breakpoint002](https://cloud.githubusercontent.com/assets/21134598/19215627/db1ec62c-8d70-11e6-968b-f9abb2f04ffd.png)
[brreakpoints.txt](https://github.com/Komodo/KomodoEdit/files/517904/brreakpoints.txt)

**Comment by WheelDogs** [comment]
breakpoints.txt contains the script shown

**Comment by WheelDogs** [comment]
.txt file at end of images contains the two scripts.

**Comment by WheelDogs** [comment]
Hi,

 

The post has been updated with better images and actual .txt file containg scripts

**Comment by Naatan** [comment]
@mitchell-as is out this week as he's at a convention, he'll respond when he's back or has some time to spare.

**Comment by WheelDogs** [comment]
[brreakpoints.txt](https://github.com/Komodo/KomodoEdit/files/522396/brreakpoints.txt)
I will try to have two clean script for you tomorrow...

**Comment by mitchell-as** [comment]
@WheelDogs, I cannot run your scripts. It appears that "main.tcl" is missing a class declaration or something because I get this error:

```
Error in startup script: invalid command name "method"invalid command name "method"
    while executing
"method Plugin_Init {} {
```

I do not know much about Tcl. I need some code that will work on my computer. A simple source file(s) that reproduces the issue is sufficient -- it does not have to be your original code.

**Comment by WheelDogs** [comment]
Will do
