### ISSUE TITLE
lang_nodejs.py compares upper cased 'fileName' with lower cased name

### ISSUE THREAD

**Issue by lmk1988** [Komodo/KomodoEdit#2087]
### Short Summary
lang_nodejs.py compares upper cased 'fileName' with lower cased name

### Steps to Reproduce
1) Create Project
2) Use require('app-module-path').addPath(__dirname)
3) Specify Node.js directory in language/Node.js 
4) Directory added with upper cased naming (e.g D:\myCode\)
5) Code Intel does not work

## Why it does not work (in lang_nodejs.py)
1) Code Intel enters method load_as_file() with "D:\myCode\index.js"
2) Code Intel enters get_hits_from_lib()
3) From (os.path.normpath(blob.get("src")) != filename:) it compares failure with d:\mycode\index.js

## How to workaround/fix
1) Add filename = filename.lower(); at the start of method get_hits_from_lib();

### Platform Information

*Komodo Edit* 
*10.1* 
*Windows 10*

**Comment by mitchell-as** [comment]
Thank you very much for the detail of the ticket and suggested fix. It made my job easier :)
