### ISSUE TITLE
KomodoEdit Elastic Tabs don't work as expected

### ISSUE THREAD

**Issue by MaskedVII** [Komodo/KomodoEdit#2088]
Salve community!
I've start to update my templates so all of them have tabs and start to use elasticTB, 1char instead 4spaces and all the show. I've done my research, uninstall the upgraded KEdit 9 to 10 and minor updates to a fresh install of 10.1.1. ElasticTabs don't work as expected:

As example a perl file, 1 elasticTB per space and you can see the diff in the spaces
![kests01](https://cloud.githubusercontent.com/assets/10841884/19171164/04681a06-8be1-11e6-8a1f-93310c592961.png)

and the output in the shell elasticTB don't align
![kests02](https://cloud.githubusercontent.com/assets/10841884/19171235/561e2750-8be1-11e6-80fb-bdff2f76019d.png)

Also is in Python, Lua and Pascal, I've not tested other languages
Some questions:
Global Indentation settings and Per language are the same, so why the big difference between spaces in a short and uninportant table?
The draw edge line column don't restrict the max line lenght?... In others languages there is no problem but with Python the max length line must 79 chars, the elasticTB spread beyond that line.

Archlinux, KDE Plasma, nvidia K2200, i4790, 32GBRam
Komodo Edit 10.1.1

Thanks for your fast response to defman and nathanr!

**Comment by mitchell-as** [comment]
Hi, please turn on "View > Whitespace" and also describe where I can "see the diff in the spaces". I really don't know what I'm looking at.

The second screenshot does not look like Komodo, or is your window manager making Komodo transparent? At any rate, we do not support elastic tabstops in output windows like shells. It is only in the editor window.

The edge line gives you a visual reference of lines that might be too long. It does not restrict line length at all. That is your responsibility.

**Comment by Defman21** [comment]
>The second screenshot does not look like Komodo, or is your window manager making Komodo transparent?

I'm sure it's a terminal app.

**Comment by MaskedVII** [comment]
Salve community!
Updating ElasticTB:
![kests03](https://cloud.githubusercontent.com/assets/10841884/19205659/6bf44028-8ca9-11e6-92dc-e636b515740a.png)
And as I say in the output window of the shell (bash) the elasticTB don't match
![kests04](https://cloud.githubusercontent.com/assets/10841884/19205688/9f1eeaac-8ca9-11e6-9c8b-17b58e766553.png)

Even writing a output to a file.txt the tabs don't align
![garbage01](https://cloud.githubusercontent.com/assets/10841884/19205869/98ba71c6-8caa-11e6-8073-dd0fca2004af.png)

Thanks in advance

**Comment by Naatan** [comment]
Is your issue that the tabs are a different width in your terminal?

This is what tabs are, I suggest you use spaces if this is an issue for you. The tab width is determined by whatever is rendering them.

**Comment by MaskedVII** [comment]
I know the tab width is determinated by the render engine, one line in blank must reset the units for the elasitcTB (4/8 spaces, units, whatever) and this work well in KE, but as the example above they don't work as expected because in the same block of code they render in diff way!. So what's the point to use an editor with elasticTB that can't display the same indentation in single block of code?, I know that TB are for working and SP for presentation (portability), but the evidence is clear ... the elasticTB don't work as expected, if the single block of code has the same output ... fine, but diff lines has a different behavior in the same block code, I think that something is wrong... don't agree with me?
thanks naatan!

**Comment by Naatan** [comment]
Tab characters "indent" to the next column. That's why some blocks are different widths despite the number of tab characters being the same. This is how tab characters work, it's not something Komodo does differently.

**Comment by MaskedVII** [comment]
I have done my research, so the Head and Tail spaces rules the format, it's not I wan't to initiate a holywar or "trolling" in this case, searching for a procedure to fix my needs and maybe trow a improvement at respect, obvoiusly I don't know how KE manage the elasticTB but for me a line blank resets the elasticTB indentation but if you have a block of code I think they must indent in the same way, if you have a writing code for this I'll be grateful!, beleive me coding in KE for me is better than SText or At... so I put here my experience and thoughts... Thanks naatan! again!

**Comment by Naatan** [comment]
I hear you, but as it stands Elastic Tabstops uses tabs and so will never work in the way you want. There's been talk about implementing the same functionality with spaces for indentation, but unfortunately this poses a significant challenge. At the moment we have no plans on extending this functionality, though that may still change.

**Comment by mitchell-as** [comment]
@MaskedVII You said "So what's the point to use an editor with elasticTB that can't display the same indentation in single block of code?"

These drawing artefacts can happen with Unicode characters since they can have variable widths. Komodo is primarily a code editor, so you will often not run into an issue like this with coding characters.
