### ISSUE TITLE
Not opening file from top text entry

### ISSUE THREAD

**Issue by srgloureiro** [Komodo/KomodoEdit#2089]
I tried to open the afxmenubutton.cpp by typing (and auto suggestion) it on the top text entry. My current tab's file is on the same disk directory.

And I got the message
![image](https://cloud.githubusercontent.com/assets/6369967/19204899/2d6dce22-8cd7-11e6-9166-59591a8ab267.png)

I suspect it has to do with space on the file's path.

Komodo Edit, version 10.1.1, build 17414, platform win32-x86.
Built on Thu Sep 01 23:54:28 2016.

**Comment by cgchoffman** [comment]
Wow, not sure how I've never hit this.  Reproduced.
