### ISSUE TITLE
pwd returns an incorrect and incomplete directory path

### ISSUE THREAD

**Issue by WheelDogs** [Komodo/KomodoEdit#2090]
### Short Summary
Net: when using Komodo the execution of pwd returns a path that is different from that returned when executing the script otherwise

tcl script 'main' includes a method that sources tcl scripts.
the sources script invokes 'my pwd'.

When in komodo, it return the path of folder that contains the main.tcl script
When executed from wish, it returns the path of the sourced script.
### Expected results

Expect pwd to return the same value when using Komodo as it does when executed from wish

### Actual results
returns the directory of the tcl script 

### Platform Information

*Komodo IDE?* 
*Komodo Version 10.1.1
*WIn10 

### Additional Information

Notice the code after "set dir [my pwd]"
I had add additional folder names to the 'file join' command because K doesn't return the correct path.
The script in the 'else' clause is the original script. It works only when Komodo is not being used. i.e. when the script is executed directly from the shell.
![breakpoint001](https://cloud.githubusercontent.com/assets/21134598/19205954/788982a8-8cb3-11e6-8cb4-5141d7fbbf8d.png)
![breakpoint002](https://cloud.githubusercontent.com/assets/21134598/19205955/788a017e-8cb3-11e6-8bbe-10ddfd0f64bb.png)
[brreakpoints.txt](https://github.com/Komodo/KomodoEdit/files/517136/brreakpoints.txt)

Maybe helpful:: this version of Komodo interprets the core oo commands as invalid.

**Comment by Naatan** [comment]
Your steps to reproduce are missing, please elaborate.

**Comment by WheelDogs** [comment]
Will try to have complete set of code for your eval tomorrow...

**Comment by mitchell-as** [comment]
This is by design. When you run `tclsh foo.tcl` manually, you are running it within a particular filesystem directory. However, Komodo often uses the absolute path to the file, like `tclsh /tmp/foo.tcl`. Given those two cases, the `pwd` in the first is `/tmp/` and the `pwd` in the second is `/`. In the Debugging Options dialog, you can set the "Directory" path to be the pwd you want.

**Comment by WheelDogs** [comment]
have tried the recommended solution. It doesn't solve the problem. It is not possible to set the directory in the debugging options for all of the possible directories in the application hierarchy.
