### ISSUE TITLE
Can't add remote accounts with danish characters in name/hostname (æøå)

### ISSUE THREAD

**Issue by griebel** [Komodo/KomodoEdit#2091]
Can't add remote accounts with danish characters in name/hostname (like ÆØÅ æøå)
### Steps to Reproduce

Try to type pærer as Name or pærer.dk as hostname and then click Add. 
### Expected results

A new remote account entry
### Actual results

Nothing happens when i click Add.
If I click Apply, the dialog ask if I want to save, clicking yes, does nothing.
### Platform Information

Komodo Edit 
10.1.1 build 17414 macosx

**Comment by Naatan** [comment]
Please share your error log after reproducing the issue.

You can find your error log at Help > Troubleshooting > View Log File.
