### ISSUE TITLE
Pref window is transparent and scaled down on KDE

### ISSUE THREAD

**Issue by MaskedVII** [Komodo/KomodoEdit#2092]
Glitches in the GUI of Komodo
Salve community!
When work in vertical split (two files side by side) and open the preferences window the right half is nearly transparent and sometimes scaled down, I can't take a picture beacuse when switch or activate anything it restores.
Other is the minimap, two issues you can select the view of the minimap per file (very cool feature) but sometimes the GUI don't respond, I need to save work and quit KE, when back everything is working fine. The other, the minimap in the left side sometimes "flickers" in RGB color is too fast to take a picture and I can't figure out the steps to reproduce.
And finally a whim... the icons per language are cool, when the icons for haskell, lua, pascal, assembly will be available?

Archlinux, i4790, nVidia K2200, 32GBRam, monitor Benq 1ms of access

**Comment by Naatan** [comment]
Please report one issue at a time, we'll make this one about the right half being transparent. You'll need to open separate bug reports for the other issues, please.

Could you record a short video of the issue?  I use Arch linux too and I use SimpleScreenRecorder for recording videos.

Also, what desktop manager are you using?

**Comment by Defman21** [comment]
I remember their is using KDE.

**Comment by MaskedVII** [comment]
Sorry I think that all of them where an issue of the GUI... And yes... using SimpleSR, that's my bad I was trying to catch them with spectacle... Using Arch, Plasma and nVidia X server. Asking compositor>rendering backend (xrender or OpenGL x.x) has any impact in KE?
Thanks!

**Comment by Naatan** [comment]
Knowing the display manager helps us reproduce if necessary.

Please provide a screen recording of the problem.

**Comment by MaskedVII** [comment]
I'm embarrassing myself... SDDM, Plasma, and nvidia all from official repository, and updated I will try to catch all of them in a single video for upload and then report individually

**Comment by cgchoffman** [comment]
Might want to check to see if this is reproduced in safe mode before you go doing a whole bunch of screencaps. Help > Troubleshooting > Safe mode.

**Comment by MaskedVII** [comment]
That's a pro observation, thanks cgchoffman. Reporting, using SimpleSR and the glitches don't show up ... Testing in safe mode and I will report back

**Comment by MaskedVII** [comment]
Start komodo in safe mode and none of the above glitches come out (near 2 hrs), so I've done my part to give the community some glitches in my framework in response of using your free software, I hope the staff take note and review all this, but I'll not give more of time on this because the response of the staff was poor, I'm not asking for code or solutions I'm giving my time in good form for contribute a little to the KE, Thanks anyway!

output shell when run KE in safe mode was:
(process:26303): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
(komodo edit:26303): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
(komodo edit:26303): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

trying to check about:config but too many parameters for a quick search

Salve community!

**Comment by cgchoffman** [comment]
> but I'll not give more of time on this because the response of the staff was poor,

@Naatan and I are staff.  Were you expecting more from us?  Or did you not realize that we are on the dev team?  We've provided you with no less help then anyone else who reports an issue.
