### ISSUE TITLE
Komodo crashes on OS X when pasting Unicode string

### ISSUE THREAD

**Issue by clokep** [Komodo/KomodoEdit#2096]
### Steps to Reproduce
- Open a Python file
- Paste امارات
- Enclose the above string in single quotes
### Expected results
- Komodo pasts the text and lets you continue editing the document.
### Actual results
- Komodo crashes 😢 
### Platform Information

_Komodo Edit or IDE?_ Komodo IDE, version 10.1.1, build 89474, platform macosx. Built on Thu Sep 1 15:11:44 2016. 
_Operating System (and version)?_ 10.11.6 (15G1004)

**Comment by clokep** [comment]
My suspicion is that this is a RTL string, which breaks Komodo somehow.

**Comment by Naatan** [comment]
We definitely don't support RTL, but it also definitely shouldn't result in a crash when you paste in a string like that.

**Comment by Naatan** [comment]
Hmm, oddly I cannot reproduce this on Linux or OSX. Can you reproduce the issue in safe-mode?

**Comment by clokep** [comment]
I updated the instructions above. This does *NOT* crash in safe mode.

**Comment by Naatan** [comment]
What encoding are you using when the crash occurs?

**Comment by clokep** [comment]
FWIW I just checked with Komodo 10.1.4 and this doesn't seem to crash anymore.

**Comment by Naatan** [comment]
Perfect, thanks @clokep! :)
