### ISSUE TITLE
21-day free trial refuses to run without license after 2 days

### ISSUE THREAD

**Issue by vitaly-krugl** [Komodo/KomodoEdit#210]
I had a licensed version of Komodo 8.x on my MacBookPro and decided to try the 9.x version via the 21-day free trial. I moved the Komodo 8.x app out of the Applications folder and moved `~/Library/Application Support/ActiveState` to another location.

After this, I was able to run the 21-day free trial for one day. However, when I tried running it in the second day, it pops up the attached dialog and refuses to run without a license. This is a pretty frustrating free trial.

![screen shot 2015-04-24 at 3 32 18 pm](https://cloud.githubusercontent.com/assets/1441066/7329728/768d1fb0-ea97-11e4-8a36-7f930c0c6759.png)

**Comment by cgchoffman** [comment]
Hi @vitaly-krugl, Please try these workaround steps: https://community.activestate.com/node/15061
