### ISSUE TITLE
Tag matching doesn't allow selection highlighting

### ISSUE THREAD

**Issue by SleepyJay** [Komodo/KomodoEdit#2102]
### Short Summary
Tag-matching works fine, but if I select a tag that is matched, there is no change in the display. You should be able to change the style to a selected-tag-match. You CAN cut/copy the selection fine.

### Steps to Reproduce
Activate a tag-match. 
Select (like mouse-drag) a section of the matched tag. 
Notice that you cannot tell what you have selected. 

### Expected results
The part of the tag that is selected (some or all) should be a different color/style. 

### Actual results
No color/style change.

### Platform Information

*Komodo Edit* 
*Komodo Version 10.1.1* 
*Mac OS El Capitan* 

### Additional Information
This is cosmetic, only.

**Comment by Naatan** [comment]
I'm not sure I understand what you mean. When I select a tag I clearly see my selection. What color scheme are you using?

**Comment by cgchoffman** [comment]
I believe this is the same issue that a few people have reported (including myself).  Highlighted text doesn't have enough contrast so you can see what you've selected.

@SleepyJay you can adjust this in Tools > Color schemes editor: 
- On the left make sure "editor" is selected in the drop down.  
- Find Selection Background
- Change it

If that doesn't resolve the issue and I'm wrong in my assumption then please provide screenshots to show what you're talking about.

**Comment by SleepyJay** [comment]
Well... that was interesting. I did what you suggested and darkened the Selection Background. And now I see the selection *behind* the tag-highlight. You can just see like a pixel or two happen to stick out from the top of the tag-highlight. I guess that's better than nothing? But not quite right. 

In my screenshot, you can see I selected "foo" and there is a tiny line drawn above it. (My tag-highlight is orange and my selection-background is gray-ish.)

![Selected-foo-in-tag-highlight](https://cloud.githubusercontent.com/assets/4315430/19525711/e3fc2898-95ef-11e6-8b3b-bdbffd07d9f0.png)

**Comment by Naatan** [comment]
Huh ok, I see what you mean now - thanks for the screenshot!

How are you triggering this highlight exactly?

**Comment by SleepyJay** [comment]
I clicked on one of the $foobar 's to get the tag highlighted. 

Then I mouse drag from 'f' to  the second 'o' for selection. Same result with shift-arrow selection.

**Comment by mitchell-as** [comment]
Note: our indicators are being drawn over the selection. If we want to draw them under it, we need to set `scimoz.indicSetUnder(number, true)` where `number` is the variable highlight indicator. A potential side effect is that any other indicator or selection will hide the indicator completely.

**Comment by SleepyJay** [comment]
It doesn't sound like you have other control over the indicator or selection... like height of the indicator/selection or some other style characteristic.

**Comment by mitchell-as** [comment]
That is correct. We cannot control those things.

Now technically, there are a couple of pixels above and below the indicator. It may not be obvious, but it is there.

I'm in favor of closing this ticket. What do you think @Naatan ?

**Comment by Naatan** [comment]
Is there no proper solution possible?

**Comment by babobski** [comment]
Maybe trow in a little bit of opacity on the tag-highlight background, so the selection is shown trough the background.

**Comment by mitchell-as** [comment]
Yes, @babobski is exactly right. Change the opacity. That will help immensely. I was wrong about the indic under -- it won't affect the selection.

**Comment by Naatan** [comment]
So as it turns out this is not an issue on any of our color schemes. The only reason you are seeing this is cause you are using a custom color scheme that uses a different setting for "tag matches". Either change your "tag matches" to "underline" or try @babobski's solution.

**Comment by SleepyJay** [comment]
Yes. Less Alpha works. Thanks!
