### ISSUE TITLE
Pressing left/right with block selection does not move selection

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#2105]
### Short Summary

If you Ctrl + Click at several places (so you'll create multiple carets) or use Ctrl+D (find selected part in the buffer), you can use right/left arrow to move carets. I'd want to see similar feature for block selection (Alt + mouse selection).

**Comment by cgchoffman** [comment]
Hold `Alt + Shift + Left|Right`.  Works fine for me.  You can't just press `Left|Right`.  As with an selection, that takes you out of selection mode and moves the cursors by itself, as it hsould.

**Comment by Defman21** [comment]
You didn't get me. For example, I have this code:

```
d|e|f 
d|e|f 
d|e|f 
d|e|f 
d|e|f 
```

|...| - selection. I want to press Left so `d` will be selected.

```
|d|ef 
|d|ef 
|d|ef 
|d|ef 
|d|ef 
```

**Comment by cgchoffman** [comment]
Yes I did.  Press `Alt + Shift + Left` and it will select the column of `d`s.  It might be a different keybinding on Linux, I'm not sure.  You CAN extend block selection using the keyboard.
https://github.com/Komodo/KomodoIDE/blob/master//src/schemes/Default.p.kkf#L61

**Comment by mitchell-as** [comment]
@Defman21 sadly, that is not how block selection works. The only way to get this functionality is for us to patch the editing component, and that requires too much of a time investment :(

**Comment by cgchoffman** [comment]
> @Defman21 sadly, that is not how block selection works.

I don't understand @mitchell-as.  I'm doing it right now.  See gif below.

![block-select](https://cloud.githubusercontent.com/assets/655154/19570792/509400b4-96b0-11e6-9352-5b6720267802.gif)

**Comment by cgchoffman** [comment]
And using `alt + click`:
![block-select](https://cloud.githubusercontent.com/assets/655154/19570837/7df45130-96b0-11e6-8042-e58aed689e0a.gif)

**Comment by Defman21** [comment]
Do'h. 

```
def
def
def
def
```

Select `e` using block selection.

Now try to select `d` without re-creating the selection block. You **can't** do that, you're able to select `de` or `ef`. You can't move your selection block to select `f` or `d`.

**Comment by mitchell-as** [comment]
It's worth pointing out that if you make multiple selections (not carets, but selections) and press an arrow key, the selections do not move either. Block select should not do this. It is a single selection, not multiple ones.

**Comment by Defman21** [comment]
Is there a way to create multiple cursors in the same way as block selection? Like holding Ctrl and _selecting_ a vertical line, it would take a lot to manually clicking on each line.

**Comment by mitchell-as** [comment]
No, not without creating a userscript.

**Comment by Defman21** [comment]
Okay, thanks for the answer.
