### ISSUE TITLE
Incorrect License Dialog During Komodo Trial Period

### ISSUE THREAD

**Issue by bullsear** [Komodo/KomodoEdit#2106]
### Short Summary

This dialog showed up after rebooting my MacBook Pro.  The error is correct.  I'm still in the 21 day trial period, having just downloaded Komodo IDE yesterday.

"The licensing system showed this dialog but we are in a trial period.

Komodo IDE, version 10.1.1, build 89474.
Built on Thu Sep 1 15:11:44 2016."

I was able to relaunch Komodo after dismissing the dialog.
### Steps to Reproduce

Download Komodo IDE for a trial on a Mac Book Pro and reboot.
### Expected results

No dialog should appear.
### Actual results

Error dialog appeared.
### Platform Information

_Komodo Edit or IDE?_ IDE
_Komodo Version?_ Komodo IDE, version 10.1.1, build 89474, platform macosx.
Built on Thu Sep 1 15:11:44 2016.
_Operating System (and version)?_ OS X 10.11.5
### Additional Information

license info
Trial license, serial number _1690226255_. Expires on Wed Nov 09, 2016 (20 days left).
 -- eg. Error logs, screenshots, workarounds --

**Comment by cgchoffman** [comment]
I don't understand what the bug is here.  Are you saying it's the reminder to purchase a license? That is by design.
