### ISSUE TITLE
Not clear what tab is active in split view

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#211]
- Open two tabs
-move one to split view. 

Expected: one of the tabs is partially highlighted, telling that it is the foreground (active)
Actual: both tabs are highlighted, not being possible to tell which one is in foreground.

**Comment by mitchell-as** [comment]
The caret and line background are shown in the newly focused view while the unfocused view shows nothing to indicate that it has focus. In the new UI, obviously the tab bar needs to indicate which of the files is open in that view. I don't think this ticket is applicable any more. Please re-open if you disagree.

**Comment by Naatan** [comment]
> In the new UI, obviously the tab bar needs to indicate which of the files is open in that view

Are you saying it should but doesn't? It properly highlights the tab for me.

**Comment by mitchell-as** [comment]
It should show which file is open and it does.
