### ISSUE TITLE
Missing icon for browser preview and image

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#2111]
### Short Summary
Missing icons in the tabs for images and browser preview

### Platform Information
Komodo Ide 10.1.1

### Additional Information
![2016-10-26 10_15](https://cloud.githubusercontent.com/assets/3530262/19718698/b4773960-9b66-11e6-913f-7eb92f2662a2.png)

**Comment by mitchell-as** [comment]
Thanks for the report.

**Comment by Naatan** [comment]
Thanks @babobski, coincidentally I fixed this last week - https://github.com/Komodo/KomodoEdit/commit/4d263a30797211cd0afb1fdd46dd6edc42a940e0
