### ISSUE TITLE
Variables disappear when debugging Perl script

### ISSUE THREAD

**Issue by ebucking** [Komodo/KomodoEdit#2113]
### Short Summary
When debugging in IDE, some variables get lost as I move through the code. Variables declared as "our". Visible in some sections, not in others. Running the same script in console debugger, the variables are always present.

### Steps to Reproduce
Don't know a suitable reproduction.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.1.1
*Operating System (and version)?* Windows 7 64-bit

### Additional Information
Don't know what you can do about this. Thought you should be aware of it. Using the ratlperl.exe that comes with an older version of IBM Rational Clearcase. Based on Perl 5.8.6.
 -- eg. Error logs, screenshots, workarounds --

**Comment by Naatan** [comment]
Unfortunately we cannot take action on a bug that is not reproducible :\ Please let us know if you figure out how to reproduce the bug.
