### ISSUE TITLE
javascrip window.location dont show any auto completions

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#2116]
### Short Summary

If you have a javascript file and type `window.location.` you dont get any autocompletion.
### Steps to Reproduce

Create a javascript file and type `window.location.`
### Expected results

aoutocompletions is shown for:

```
href 
hostname 
pathname 
protocol 
assign 
```
### Actual results

Nothing is shown.
### Platform Information

Komodo Ide 10.1.1 windows 10
### Additional Information

[Reference](http://www.w3schools.com/js/js_window_location.asp)

**Comment by mitchell-as** [comment]
Thanks for the report.
