### ISSUE TITLE
javascript window.history. or history. dont show any autocompletion

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#2117]
### Short Summary

If you have a javascript file and type `window.history.` or `history.` you dont get any autocompletion.
### Steps to Reproduce

Create a javascript file and type `window.history.` or `history.` you dont get any autocompletion.
### Expected results

Autocmpletion is shown for:

```
back
forward
go
length
pushState
replaceState
onpopstate
state
```
### Actual results

Nothing is shown
### Additional Information

[Reference](https://developer.mozilla.org/en-US/docs/Web/API/History_API)

**Comment by mitchell-as** [comment]
Thanks for the report.
