### ISSUE TITLE
share: add "change team" buttonto slack share

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2119]
### Short Summary

This would be in the slack dialog.  Yes, another button.  May need to revisit the setup of the buttons since that would now be 4 buttons on that tiny dialog.
1. delete key
2. close dialog/reopen OR reload dialog OR just reload channel list

Reload channel list might be the smoothest option since that will automatically re-authenticate the user and allow them to sign into  a new team which will then populate a new list of channels from that team.  Most of this code already exists and may be a possible to use as is.

**Comment by Naatan** [comment]
I'd rather have a "Select Team" dropdown at the top of the dialog. Don't overload the dialog with buttons.

**Comment by cgchoffman** [comment]
That would be good but we're locked into the Slack API workflow which handles the team selection for you.  You can't hand it a url to you team ie. `blah.slack.com` otherwise you're just logging into the chat and not requesting a API key.  Will have to investigate this.  It can probably be done, i'm just not sure what the workflow would be.

I agree a dropdown would be slicker.

**Comment by Naatan** [comment]
Can't you just login multiple times and save multiple keys?

**Comment by cgchoffman** [comment]
Yep.  Could do that too.  You'll have to add a login button somewhere which I haven't considered but that's minor.

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/8ab2dc0328c818d0b108579a82254b8636819734
