### ISSUE TITLE
Abyss Skin: Can't read "found occurrences " in find diaglog

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#212]
https://bugs.activestate.com/show_bug.cgi?id=102154

I am using Interface Skin: Abyss, Icon Set: IcoMoon - Cupertino. So open a file, and search for some word in it: the Find window opens, and you go clicking Find Next until there are no more occurrences of that word in the file - generally speaking it works fine, after the the last occurrence, the window tells you "N occurrence(s) were found". 

Expect: to be able to read the message about occurrences found.

Actual:  Can't read it.

**Comment by cgchoffman** [comment]
Screenshot https://bugs.activestate.com/attachment.cgi?id=16958

**Comment by Naatan** [comment]
Closing as this is no longer part of core Komodo.
