### ISSUE TITLE
Type Error in console

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#2120]
### Short Summary
Noticed I'm getting a error in console log when pressing <kbd>Ctrl</kbd> + <kbd>k</kbd>:

![2016-10-31 18_54_18](https://cloud.githubusercontent.com/assets/3530262/19865173/734dbe4e-9f9b-11e6-97e9-b4a9678cea1d.png)

Looked at the [code](https://github.com/Komodo/KomodoEdit/blob/d0fe723a7d39d08a207b8d45a94bd12cb756b039/src/modules/notify/content/sdk/notify.js#L602), but this one should be rather easy to fix.

### Platform Information

Komodo Ide 10.1.1 - Windows 10

**Comment by Naatan** [comment]
Thanks @babobski :)
