### ISSUE TITLE
Component failure: koIPlaceTreeView does not work after reinstall of KO IDE 9.3

### ISSUE THREAD

**Issue by dreftymac** [Komodo/KomodoEdit#2121]
### Short Summary

KO 9.3 displays an error message when using the "Places" dialog pane:

![komodo-reinstall-required-001](https://cloud.githubusercontent.com/assets/4074354/19872552/9d019a9a-9f77-11e6-82c8-4510b9569d0d.png)

### Steps to Reproduce

* Open a text file that has a path to a local directory on Windows

* (eg) href="c:\mydocs\foodirectory\"

* Click on the filepath, komodo will attempt to open the directory in the "places" pane

### Expected results

* ko opens the directory in the "places" pane

### Actual results

* Error message (see attached image above).

### Platform Information

*Komodo IDE 
* 9.3 branch (latest) 
* Windows 7

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by Naatan** [comment]
I'm not able to reproduce this on Komodo 10 on Windows. Unfortunately we no longer support Komodo 9, I'm afraid you'd have to upgrade to get this fixed.
