### ISSUE TITLE
Show `Tabs/spaces` in the status bar

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#2125]
### Short Summary

title. The only way to find out what's being used is View - show whitespaces.

**Comment by Defman21** [comment]
Also a popup menu that allows to convert tabs to spaces and spaces to tabs would be appreciated.

**Comment by Naatan** [comment]
This falls into the "too much information" category for me, I don't think it's something most people need to see and it just fills the statusbar with information making the UI cluttered. If someone really wants this they'll have to make a userscript or addon for it.

**Comment by babobski** [comment]
Ok, I will create one. 
As this is almost the same approach as the EOL-widget and I think it would be a nice feature to have.
