### ISSUE TITLE
Create indent safe paste function

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#2127]
### Short Summary
Currently busy with some whitespace bugs ( or whats causing it ).
Noticed that if you paste code in komodo it will be inserted as is.
What I want is a "smart" paste function, so it will adjust the indenting to the current file settings.
So you will not end up with mixed whitespace in you're file.

In phpstorm this is default enabled, and you got the following options:
![2016-11-02 14_54_52-settings](https://cloud.githubusercontent.com/assets/3530262/19931338/759faf6e-a10c-11e6-91e9-27d1b5735982.png)

**Comment by Defman21** [comment]
Sublime have similar feature - Ctrl+Shift+V will do the same.

**Comment by mitchell-as** [comment]
Thanks for the suggestion!

**Comment by mitchell-as** [comment]
Upon revisiting this ticket, I remember this came up in Slack chat recently. It appears Komodo already has this feature. It's accessible from Commando's commands: Editor: Tab-Aware Paste.
