### ISSUE TITLE
Show branch picker before language picker

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#2129]
### Short Summary

![image](https://cloud.githubusercontent.com/assets/7100645/19936021/962af396-a135-11e6-85cd-c72e57e7c73d.png)

![image](https://cloud.githubusercontent.com/assets/7100645/19936073/c047f610-a135-11e6-96e1-de3f2d60ecc1.png)

I keep pressing the wrong button :P

**Comment by cgchoffman** [comment]
This sounds like a job for a Userscript.  I definitely wouldn't want this.  If you put it in the middle it makes it EASIER to hit the wrong button, not harder.

**Comment by Defman21** [comment]
the wrong button in this case is the branch switcher.

**Comment by cgchoffman** [comment]
Why are you switching the language of your file so much?  The most common button to use would be the branch selector.  This isn't a benefit to the majority of users, that is why it's a good candidate for a Userscript.

**Comment by Defman21** [comment]
Ok. I'll implement that with an userscript.
