### ISSUE TITLE
Moving the main windows around the screen not working

### ISSUE THREAD

**Issue by llimz** [Komodo/KomodoEdit#2132]
I don't know if the issue is linked or not but since I updated to Sierra, I'm not able to move the main window around the screen. I hold the left click button on the main window toolbar but nothing happens. Sometimes if works but it is not very often. It is hard to define how often maybe 1 out of 30 tries.

Resize and double click to maximize the main window is working correctly

*Komodo Edit 9.3.2
*Operating System macOS Sierra 10.12

**Comment by Defman21** [comment]
Upgrade to Komodo Edit 10.

**Comment by Naatan** [comment]
Komodo 9 is not moveable via the toolbar, you need to drag the titlebar.
