### ISSUE TITLE
main window blinking a lot when resizing panel

### ISSUE THREAD

**Issue by ecterrab** [Komodo/KomodoEdit#214]
When resizing the lower panel, that shows the Command Output and other stuff, the main window and the lower panel blink unexpectedly - they shouldn't. I tried to attach as small vide showing that but Github does not allow to attach a movie, only PNG, GIF or JPG. I am sending the video by email to Carey.

**Comment by Naatan** [comment]
Possibly same issue as #205

**Comment by Naatan** [comment]
I'm closing this in favour of #205, please track that bug and let us know if your issue still persists once that bug has been fixed.
