### ISSUE TITLE
Remote server connection (FTP) extremely slow

### ISSUE THREAD

**Issue by kevinlieser** [Komodo/KomodoEdit#2142]
I am using a remote server connection via FTP. I am browsing with the Places Panel (as i browse my local server) and the tree reacts very very slow. Much more slower than using an FTP client like Transmit (on Mac).

I there a way to speed this up?

*Komodo Edit or IDE?* 
Komodo IDE

*Komodo Version?* 
10.1.1

*Operating System (and version)?* 
Mac OS Sierra 10.12.1

**Comment by cgchoffman** [comment]
Please use the forums for questions: http://community.komodoide.com/
Try `Preferences > Editor: Disable "Detect when networked files are changed"
