### ISSUE TITLE
Komodo hangs while booting server that is used in Places panel

### ISSUE THREAD

**Issue by kevinlieser** [Komodo/KomodoEdit#2143]
I am using my local office server for development and have my file tree in the Places panel. My office server turns off after a few minutes and boot via Wake on LAN when i use my computer again.

While the server is starting, my network volumes (on Mac) are (for sure) not accessible so when I now start Komodo 10 it tries to read the places folder which is not accessible and i cannot use Komodo (only beach ball is rotating – nothing clickable) until my server is fully started up and the network volumes used in Places are available.

In Komodo 9 i could start Komodo and use it, the folder in Places panel gets refreshed when volumes are available but until then i could work.

*Komodo Edit or IDE?* 
Komodo IDE

*Komodo Version?* 
10.1.1

*Operating System (and version)?* 
Mac OS Sierra 10.12.1

**Comment by Naatan** [comment]
This is due to #1959, unfortunately there is no work around aside from disabling network file polling (Prefs > Editor > "Detect when networked files are changed outside the environment").
