### ISSUE TITLE
PHP autocomplete directory have to get scanned every time I launch Komodo

### ISSUE THREAD

**Issue by kevinlieser** [Komodo/KomodoEdit#2144]
I've set up an additional PHP directory in the settings to scan and use for autocompletion. FYI: It's a TYPO3 source folder. In Komodo IDE 9 it got scanned after I added it and I can use it directly every time I launch Komodo. In Komodo 10 it need to get scanned before i can use it – and that every time I start Komodo 10. Also Komodo do not start scanning after launch, it starts when I type a backslash and want wo write code. Then I have to wait a few minutes for the scan to complete (until then no autocompletion works). 

*Komodo Edit or IDE?* 
Komodo IDE

*Komodo Version?* 
10.1.1

*Operating System (and version)?* 
Mac OS Sierra 10.12.1

**Comment by cgchoffman** [comment]
If Komodo is scanning your directory it means either something has been added or it didn't finish scanning the directory before you closed Komodo.  Watch *View > Tabs & Sidebars > NOtifications* to see when scanning is done.  Or watch the commando/notifications field at the top of the window.

Please confirm that you have seen Komodo report that it is done scanning and you were able to use completions from your project.

> Also Komodo do not start scanning after launch

Komodo has never done this. 

Please use the forums to ask questions if you need clarification on why things are happening: http://community.komodoide.com/

**Comment by kevinlieser** [comment]
It's scanning and at the last folder it stops - so it seems that it did finish. When I now close Komodo and start Komodo again and type on the first PHP file a backslash it starts scanning again (visible in notification panel and in the notification field on top.

**Comment by cgchoffman** [comment]
Do you have a link for the TYPO3 code you're adding?  I'd like to test to see if I can reproduce.

**Comment by kevinlieser** [comment]
Sure, here it is: https://get.typo3.org/7.6.12
I am just scanning the whole folder and this worked fine with Komodo 9.

**Comment by cgchoffman** [comment]
> It's scanning and at the last folder it stops - so it seems that it did finish

Do you get completions though?  If you're not getting completions then scanning must not be finished.

**Comment by kevinlieser** [comment]
Yes, I get autocompletions (Namespace: \TYPO3\CMS\Core\...) after it stops / finished.

**Comment by cgchoffman** [comment]
Yikes, reproduced.  Thanks for reporting.

**Comment by cgchoffman** [comment]
Additional info:
- tried creating a project inside the Typo3 source to see if it's related to `Additional Folders` in the PHP prefs but it has no effect.  Komodo rescans the code again
- Full path to code is `C:\Users\blah\Downloads\TYPO3\typo3_src-7.6.12.tar\typo3_src-7.6.12\typo3_src-7.6.12`
- Doesn't appear to happen with any other language otherwise every time I start Komodo it would be scanning my Komodo source.  I would have noticed that by now.

**Comment by mitchell-as** [comment]
This bug will be addressed when we finish our codeintel architecture changes. Right now it looks like not all of the scan results are being written to the database. A workaround would be to ensure all writes happen as directories are scanned, but that may be too I/O heavy.

**Comment by mitchell-as** [comment]
Komodo 11's CodeIntel no longer scans "on demand", but scans on load. This issue should no longer occur.
