### ISSUE TITLE
Browser preview in Komodo tab wrong placement

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#2146]
### Short Summary
Noticed the browser preview is showing on the wrong place, if you close the previewed file before closing the browser preview.

### Steps to Reproduce
 * Open a html file
 * Open browser preview ( in komodo tab )
 * Close the html file
 * Close the browser preview
 * Open the html file
 * Open browser preview ( in komodo tab )

The previewed file is now shown at top, and not at the bottom.

### Expected results
The preview opens at the same position

### Actual results
The preview and code are switched places

### Platform Information
Komodo Ide 10.1.1 Windows 10

**Comment by Naatan** [comment]
Thanks @babobski We're working on a new UX for previewing that will likely land in Komodo 11. It's not tracked on github but we are tracking it internally. I'll close this ticket in favour of that task though. Thanks for reporting!
