### ISSUE TITLE
tool menus keep sliding off page to left where not seen on monitor. I uninstalled and reinstalled and still have the same issue.

### ISSUE THREAD

**Issue by sjjagers** [Komodo/KomodoEdit#2148]
### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by Naatan** [comment]
Please fill out the fields requested.

**Comment by cgchoffman** [comment]
Please refile this with a *brief* title, a screenshot, and the fields in the ticket properly filled in.
