### ISSUE TITLE
Skin is not applied after upgrade to 9.0.1

### ISSUE THREAD

**Issue by testworksau** [Komodo/KomodoEdit#215]
I upgraded Komodo Edit from 9.0.0 to 9.0.1 on my home PC and my work PC, both had the same issue.

I had the Abyss skin applied with the Monokai_Dark color scheme on both machines. The screenshot below is the resultant view.

Clicking Apply from the Preferences -> Appearance page or restarting Komodo Edit does not fix the issue. 

I had to change the skin to "Classic", click "Apply", then change back to "Abyss" and click "Apply" again to resolve the problem.

![image](https://cloud.githubusercontent.com/assets/11973031/7339598/f6b91f6e-ecb7-11e4-9acc-b123cf3ac723.png)

Komodo Edit, version 9.0.1, build 15745, platform win32-x86.
Built on Mon Apr 20 19:05:56 2015.

**Comment by Naatan** [comment]
Assume you meant skin, not color scheme, as your screenshot is of the appearance pane.

**Comment by testworksau** [comment]
Yes, that's correct - my apologies!
