### ISSUE TITLE
Color Scheme Editor crashes KO

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#2154]
Color Scheme Editor crashes KO after a few modify things, Apply cycles

### Steps to Reproduce
1. Modify some items colors
2. Click Apply
3. goto 1

KO submitted some crash reports just a few mins ago

### Platform Information

Komodo IDE, version 10.1.1, build 89474, platform linux-x86_64.
Built on Thu Sep 1 14:52:01 2016.

**Comment by Defman21** [comment]
Happened to me sometime. No logs though :(

**Comment by mitchell-as** [comment]
Sadly, I am not able to reproduce. We'll need more than crash reports to help pin this one down. Let us know if you manage to find some steps that reliably reproduce the problem.

**Comment by Naatan** [comment]
Particularly I'd be interested to know if it happens when applying schemes only to the editor or only to the interface.

**Comment by agroszer** [comment]
all 3 checkboxes were checked: editor+interface+widgets
