### ISSUE TITLE
Left click does not work

### ISSUE THREAD

**Issue by srgloureiro** [Komodo/KomodoEdit#216]
Left click on the editor does nothing. Double-click does not work also.

It works everywhere, except on the text editing widget.

Komodo 9.0, Windows 8, 64bit

**Comment by Naatan** [comment]
Could you post your error log after having attemtped to double click on the editor (pystderr.log - see: https://community.activestate.com/faq/komodo-profile-structure)

Also, see if using a clean profile works around the issue? https://community.activestate.com/node/15233

**Comment by srgloureiro** [comment]
I restarted Komodo and the bug is not occurring now.

**Comment by Naatan** [comment]
Ok, if it happens again please copy over your error log to this ticket, I'll reopen if/when that happens.
