### ISSUE TITLE
SCC: Open file context: Menu items are disabled

### ISSUE THREAD

**Issue by damienprystay** [Komodo/KomodoEdit#2164]
### Summary
With the Places working directory not under source control, but an open file that is in SCC, the File -> Source Code Control (and Right click on the file's tab -> Source Code Control) menu items are not available (e.g. Show Changes in File). The File History tab in the Version Control pane is populated correctly, so it is recognizing the file's SCC status there.

### Platform Information

Komodo IDE 10.1.2, build 89508, on OSX 10.11.6.

**Comment by Naatan** [comment]
I can't reproduce this. Is this consistently reproducible for you? (try some different files, please).

**Comment by damienprystay** [comment]
Yep, multiple files in multiple svn and git repos.

It seems to relate somehow to what directory is the Places root: when it's `/` or `/Users/` or `/Users/damien/`, the menus are disabled; when it's... apparently pretty much anywhere else, they work. (The files in question are all somewhere beneath `/Users/damien/`.) So that's... weird?

**Comment by Naatan** [comment]
I tried pointing Komodo at /home/nathan and opened a file in a SVN repo that lives somewhere underneath that directory, no issues.

@cgchoffman could you try the reproduction steps?

**Comment by cgchoffman** [comment]
Yep I can reproduce this.

- I opened a KomodoIDE repo file (ie. C:\Users\Carey\projects\KomodoIDE)
- enabled file tabs (i never have them showing)
- Checked that I have right click > SCC > Show changes
- Changed places so it was a few directories above my KomodoIDE dir (ie.  C:\Users\Carey)
- SCC context menu on the file tab is all disabled.

**Comment by cgchoffman** [comment]
Likely related issue:https://github.com/Komodo/KomodoEdit/issues/2532

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/0f1538902c3a865d2e68f96393c95fcb3235a66d
