### ISSUE TITLE
Komodo freezes on external change of files

### ISSUE THREAD

**Issue by ANSI-C** [Komodo/KomodoEdit#2167]
### Short Summary

If a file in a project is modified outside Komodo and the change detection option is enabled, Komodo freezes.
Note that networked file change is not enabled

### Steps to Reproduce

- enable file change detection
- change a file

### Expected results

- in this case file should be transparently reloaded or closed

### Actual results

- Komodo freezes

### Platform Information
Komodo IDE, version 10.1.1, build 89474, platform win32-x86.
Built on Thu Sep 01 14:27:01 2016.

### Additional Information

 -- eg. Error logs, screenshots, workarounds --
![sshot-2016-11-20- 17-49-37](https://cloud.githubusercontent.com/assets/7015883/20464581/012453d2-af4a-11e6-95af-2f28e5679c0c.png)

**Comment by mitchell-as** [comment]
For the record, I cannot reproduce on Linux and I cannot imagine why you'd experience a freeze. @cgchoffman can you reproduce this on Windows?

**Comment by Naatan** [comment]
Anything special about the file you are changing? Is it on a mount? Special type of filesystem?

As it stands we don't have enough information to reproduce your issue.

**Comment by ANSI-C** [comment]
Local NTFS on Windows 8.1 (SSD), the change is being done by git command 
included in MobaXTerm <http://mobaxterm.mobatek.net/>.

BTW, does Komodo have an embedded git client capable to keep Linux fs 
attributes? Also an embedded diff view like the one Meld 
<http://meldmerge.org/> has would be fantastic.


Il 21/11/2016 16:58, Nathan Rijksen ha scritto:

**Comment by Naatan** [comment]
Komodo uses the git executable you configure, it does not come embedded with one. It does have built-in diff but it's not as comprehensive as Meld. Let's keep this thread about the bug at hand though, you can post on our forums should you have any more general use questions.

Does Komodo only hang when the change is done by a git command or does it also happen if you modify a file externally in eg. Notepad?

**Comment by ANSI-C** [comment]
Tested a change with Notepad++, no issues.


Il 21/11/2016 17:07, Nathan Rijksen ha scritto:

**Comment by Naatan** [comment]
Could you try disabling git integration in Komodo? Prefs > Source code control > Git.

**Comment by ANSI-C** [comment]
Done, it freezes anyway.

I have a minidump of Komodo while in freezing state, if you would like 
it. Cannot attach it here.


Il 21/11/2016 17:30, Nathan Rijksen ha scritto:

**Comment by Naatan** [comment]
Could you send it to support@activestate.com and reference this bug?

**Comment by ANSI-C** [comment]
Sure, just done it.

Thanks!


Il 22/11/2016 17:15, Nathan Rijksen ha scritto:

**Comment by Naatan** [comment]
How did you produce the dump btw? Your bug says Komodo froze, not that it crashed. Those dumps are only generated when it crashes.

**Comment by ANSI-C** [comment]
Sysinternals process explorer.
-- 
Anselmo Canfora
+39 320 4657378

**Comment by Naatan** [comment]
No dice unfortunately.

 What exactly are you doing outside of Komodo that will cause Komodo to freeze? And am I right in assuming that it only happens when using git?

**Comment by ANSI-C** [comment]
External git command updates a file opened in Komodo while file change monitoring option is enabled. Same thing doesn't happen if I change same file with another external program like Notepad++.
-- 
Anselmo Canfora
+39 320 4657378

**Comment by Naatan** [comment]
What git command are you performing?

**Comment by ANSI-C** [comment]
/git pull <remote> master/


Il 22/11/2016 18:54, Nathan Rijksen ha scritto:

**Comment by Naatan** [comment]
Does it happen even if no files changed?

**Comment by ANSI-C** [comment]
No, only if an opened file is changed by git.
-- 
Anselmo Canfora
+39 320 4657378

**Comment by Naatan** [comment]
Does unchecking "Detect when files are changed .. " work around the issue?

**Comment by ANSI-C** [comment]
Of course yes, Komodo freezes after detecting a change by external git 
command.


Il 23/11/2016 18:14, Nathan Rijksen ha scritto:

**Comment by Naatan** [comment]
@cgchoffman have you ever noticed this on Windows?

ie. Komodo freezes when you git pull externally on a file that is currently open in Komodo.

@ANSI-C: btw is this 100% reproducible or is there an element of randomness? ie. does it sometimes work without issues?

**Comment by ANSI-C** [comment]
It happens every time.
-- 
Anselmo Canfora
+39 320 4657378

**Comment by cgchoffman** [comment]
> @cgchoffman have you ever noticed this on Windows?

Never.  I'm doing this several times a day too.  I have that pref set.  I tested it when it was first reported too by opening and editing about 30 files, commiting them, then switching to a new branch so all the files changes would be reverted.  Komodo didn't hesitate for a even a second.  It just did the file updating in the background.

**Comment by Naatan** [comment]
Very odd. @ANSI-C could you see if the issue is reproducible in safe-mode? `Help > Troubleshooting > Restart in Safe-mode` ?

Please verify that when restarting in safe-mode Komodo should be using the default UI (all your settings would be temporarily reset).

**Comment by ANSI-C** [comment]
Hello, in safe mode it does not freeze.


Il 24/11/2016 17:48, Nathan Rijksen ha scritto:

**Comment by Naatan** [comment]
Ok, could you share your prefs.xml with us? You can send it to support@activestate.com and reference this ticket to keep it from public eyes.

Info on locating your prefs.xml: http://docs.komodoide.com/Troubleshooting/Where-does-Komodo-keep-settings-data

**Comment by ANSI-C** [comment]
Hi, thanks for support, file sent.


Il 29/11/2016 18:18, Nathan Rijksen ha scritto:

**Comment by Naatan** [comment]
The prefs.xml you send has file monitoring disabled, which you said worked around the issue. Is the only difference between this prefs.xml and the one that reproduces the issue that you disabled file monitoring? If not please share a prefs.xml that reproduces the issue for you.

**Comment by ANSI-C** [comment]
Yes, It is the only one. I have been forced to keep it disabled to avoid this very issue.
-- 
Anselmo Canfora
+39 320 4657378

**Comment by Defman21** [comment]
@ANSI-C could you please reply using Github, not mail? You are providing your phone number in each reply and I doubt you want to do that.

**Comment by ANSI-C** [comment]
@Defman21 ouch! Many thanks! Lazy man overlooked his signature while replying from phone...

**Comment by Naatan** [comment]
Just had time to test this, and for me it does not freeze. I'm not sure what the issue could be, probably some type of corruption in your profile folder. I would recommend doing a profile reset, that should resolve your issue but you would have to redo your preferences. You could try backing up your prefs.xml and copying that over so most of your prefs are preserved, as it seems the issue does not originate from prefs.xml.

Instructions on resetting your profile folder: http://docs.komodoide.com/Troubleshooting/Reset-Komodo
