### ISSUE TITLE
Unable to select in Komodo alerts 

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#2173]
### Short Summary

Run this:

```
require("ko/dialogs").alert("Does Carey <3 pizza and beer? Yes - select it and paste somewhere, no - ignore")
```

### Expected results

Im able to select the text inside the alert

### Actual results

<s>Carey is sad</s> Im not able to select the text.

### Platform Information

*Komodo Edit or IDE?* Edit
*Komodo Version?* 10.10.0-devel, build 17446 (with native decorations)

**Comment by Naatan** [comment]
This is by design, you're not supposed to be able to select text in a regular UI dialog.

If you want to give selectable text use 

```
require("ko/dialogs").alert("Uh oh", { text: "Does Carey <3 pizza and beer? Yes - select it and paste somewhere, no - ignore" } )
```

**Comment by Defman21** [comment]
Huh okay. Thanks :)
