### ISSUE TITLE
Can't move userscript properties window

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2175]
### Short Summary

Open the properties of a userscript or create a new one.  You can't move the window that opens.  OS border decorations are off.  It's resolved if you turn on OS Window borders.

**Comment by Defman21** [comment]
https://github.com/Komodo/KomodoEdit/issues/2036

https://github.com/Komodo/KomodoEdit/issues/1621#issuecomment-251143476

**Comment by cgchoffman** [comment]
Are you saying this is a dupe or what @Defman21 ?  As far as I know we have to modify the window to be movable so each broken window needs to be fixes separately (ie, individual reports so they all get fixed).  I'd asked about this before internally and that's what i was told.

**Comment by Defman21** [comment]
Well I thought this is the problem with decorations, not dialogs and windows.

**Comment by cgchoffman** [comment]
Ok, it would be more helpful if you said that in your first message rather than making me read two different bug reports.  I'll leave it up to @Naatan to decide what to do with this ticket.

**Comment by Defman21** [comment]
>Ok, it would be more helpful if you said that in your first message rather than making me read two different bug reports.

Sorry :)

**Comment by cgchoffman** [comment]
No worries.  Thanks for chiming in with details.

**Comment by babobski** [comment]
@cgchoffman this is a well known issue for me, and already mentioned it in [#2036 (comment)](https://github.com/Komodo/KomodoEdit/issues/2036#issuecomment-248896388) .

For me on windows it's related to every window using a `<dialog>` tag.
I already compared the dialogs from this [location](https://github.com/Komodo/KomodoEdit/tree/master/src/chrome/komodo/content/dialogs) that use the dialog with there behavior in Komodo.
But every window that uses a dialog tag I cant move or resize when having custom decorations enabled.

- colorpicker
- properties userscript
- Compare files
- Icon picker
- alert

**Comment by Naatan** [comment]
What this really boils down to (for this issue and the ones like it) is we have to be more clear and more explicit about what is a dialog and what is a modal.

Cases where dialogs are not movable where you think they should be are cases where a dialog is being interpreted as a modal.

**Comment by cgchoffman** [comment]
This doesn't appear to be a happening anymore.  Closing.
