### ISSUE TITLE
Enhancement: Configure a local mapping for searching on remote projects

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#2179]
### Short Summary
Would be nice to have a feature to map you're remote project to a local location, for search functionality. (as mentioned in #2178)
So when you use the search function in a remote project, it will search in the mapped local location.
And that you got the option when presented with the the search result I can open the mapped remote location of the file.

Currently you are not able to use the find functionality with remotes, so I think this would be a nice addition.

**Comment by Naatan** [comment]
This is what publishing is for, to have local files that "map" to remote files. I don't think it's worth implementing another slightly different use-case considering the amount of work that would be involved. Sorry :(

**Comment by babobski** [comment]
Ah to bad 😢 .

For my work i have a lot remote projects and Komodo doesn't allow me to search in remotes.
I'm currently publishing from remote to remote using a local "sync" folder.

Komodo does allow me to set the directory's to scan for codeintel, so I have codeintel auto-completion in my remote projects. Only searching in you're remote files is quit a work around.

**Comment by Naatan** [comment]
You could always mount your remote using ftpfs, but I gotta be honest; your use-case sounds niche and if I'm being totally honest it sounds like a bad way of managing your project files. 

Of course an IDE exists specifically to support your workflow, whatever that may be, but even then it still comes down to demand, and I can't imagine your use case is one that is shared by many (editing files remotely, then syncing them between 2 remotes, all the while also having a local cache).

Not trying to be mean here, just being realistic. 

If you're set on your workflow I think something like ftpfs will be the best solution. Though performance will be better with sshfs if you can use ssh.

**Comment by babobski** [comment]
>Not trying to be mean here, just being realistic.

I know komdo is not designed for this kind of use, but for local to remote development.

Our current setup at work doesn't allow for remote development, but it is on our bucketlist.
For syncing remotes the ideal situation is not remote to remote using a local "sync" folder.
But this is somthing I came up with this week, as for my codeintel to work on a remote, I already have to point to a local version.
So I'm currently trying out if I can use the build in sync/publishing function to control the syncing.
Discoverd the syncing option a few weeks ago when publishing a own project from my local development to my remote, I never used it before because i need to sync remote to remote.

I progam with Komodo for years, but for about 3 years back for work I switched to phpstorm.
About a year back I gradually switched back to Komodo as me and phpstorm just doesn't mach.

phpstrom is great when syncing between remote projects, but that has to do with part I find less atractive.
When creating a "project from excisting files" in phpstorm it syncs the remote to you're local for aurocompletion and searching. If you have a typical framework site it still can take about 10+ minutes to sync and with even larger projects it is getting worse. 
While this is happening you can't edit anything before it has done loading, in the mean time everyone has a fresh cup of coffee and when you're back it still isn't finished.
Sometimes when I have to make a 5 min change and I don't have the both project loaded (development and live), it can take me up to an 30-60 min loading time to make a 5 min change.

But the main thing that was annoying me, is all the "smart" auto format functions it's packed with. You can disable the most, but a "smart" auto indent that is not working properly can be so anoying.
Also upgrading phpstorm from 8.* to 9.* broke a lot of stuff.

phpstorm is a nice editor but it is not my cup of thee.
I don't like waiting and I dont like a editor that thinks it's smarter than me (and fails).
Komodo just let me do the coding and assists with autocompletion and other stuff, but it does not try to be smarter than me, it does not interupt my coding with anoying loading screens.

Only Komodo doesn't give me the same syncing options for remotes, this has to be done with a third party tool like [winSCP](https://winscp.net/). And a big miss is that searching is not supported for remote projects.

I know that komodo direction is more pointed at local development, but it would be nice to have some more remote support.

I think mounting the remote is more a OS X based thing as it is for windows, found some solutions but the seem not that attractive.

**Comment by Naatan** [comment]
> I think mounting the remote is more a OS X based thing as it is for windows, found some solutions but the seem not that attractive.

Linux actually, sorry I'm spoiled and did not consider windows :\ It does seem Windows supports mounting FTP: http://www.thewindowsclub.com/map-an-ftp-drive-windows

Although I'm not sure how well that will work with Komodo, as I'm not familiar with windows mounts.

For what it's worth we are putting focus on remote files and publishing for Komodo 11. At the end of the day though remote editing will never be as strong and efficient as local editing. 

I'd like to think most developers these days work using version control and deployment systems, or at least aim to make that transition. I understand your workflow isn't your choice but rather one enforced by your company, I think this is a situation many developers find themselves in. At the end of the day us facilitating niche and "bad practice" use cases will only lead to technical debt and annoyed programmers, making situations like this only MORE likely.
