### ISSUE TITLE
Account Setup is absent

### ISSUE THREAD

**Issue by vladisslav** [Komodo/KomodoEdit#218]
Komodo IDE, version 9.0.1, build 87208, platform win32-x86. Built on Thu Apr 16 
From manual: "To set up the account, select Tools > Komodo Services > My Account from the menu"
But in the "Tools" menu, there is no item "Komodo Services". See screenshot:
![komodo](https://cloud.githubusercontent.com/assets/7721913/7347780/86f4655c-ecf4-11e4-9c66-a3850a5d1e41.png)

**Comment by Naatan** [comment]
Seems the docs may need some updating, please try using the "Gear" icon on the collab pane instead. Opened a bug for this on the docs repo.
