### ISSUE TITLE
Prompted to download font Osaka every time Komodo starts

### ISSUE THREAD

**Issue by we3geeks** [Komodo/KomodoEdit#2188]
Every time I start either Komodo IDE or Edit, I am prompted to download font "Osaka". Looks like this may be an upstream problem? (See https://bugzilla.mozilla.org/show_bug.cgi?id=1283573)

![komodo-osaka](https://cloud.githubusercontent.com/assets/2390335/20645249/375cc856-b415-11e6-876c-13a71c5d1a54.png)

Komodo IDE, version 10.1.2, build 89508, platform macosx.
Built on Thu Nov 17 15:14:16 2016.

**Comment by aatiffraz7** [comment]
This happens when we call CGFontCreateWithFontName in gfxMacPlatformFontList::LookupLocalFont for the font "Osaka-mono".
LookupLocalFont is called from gfxMacPlatformFontList::InitSingleFaceList which is called during gfxPlatform::Init().

**Comment by mitchell-as** [comment]
@Naatan Are you seeing this on your mac?

**Comment by cgchoffman** [comment]
I just installed 10.1.3 on OSX and I'm not seeing this.

**Comment by Naatan** [comment]
I have not seen this, very odd.

**Comment by we3geeks** [comment]
Per the linked Mozilla bug entry above and the comments showing there, this appears to be specific to macOS 10.12 (which at least explains why @cgchoffman isn't seeing it) and (if I'm reading the comments correctly) not everyone on 10.12 is seeing it Firefox, either, but some are. Appears to still be being actively worked on, as of a couple days ago based on the comment timestamps.

**Comment by mitchell-as** [comment]
Hmm, then perhaps we'll have to backport whatever patch they end up with. Thanks for the additional information.

**Comment by Naatan** [comment]
@mitchell-as they already fixed it:

https://bug1283573.bmoattachments.org/attachment.cgi?id=8766885

**Comment by mitchell-as** [comment]
Thanks @Naatan, I did not see that.

**Comment by we3geeks** [comment]
Thanks, guys. Any chance this might be coming to a nightly build near me any time soon?

**Comment by Naatan** [comment]
We'll see about doing a 10.2 nightly soon. Can't give an ETA yet.
