### ISSUE TITLE
On deindent or indent on selection, overflows to next lines

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#2191]
### Short Summary
Got a new bug in 10.1.2 when selecting a block and deindent it will expend to the next line, messing up my code.
Made [screencast](http://youtu.be/Kiuq3ZLMH98?hd=1) to show the issue.

### Steps to Reproduce
Select a block ( in my case in a php file ) en deindent or indent

### Expected results
The selected block get's deindented

### Actual results
On deindent the selection expands to the next lines, deindenting lines I did not select.

### Platform Information
Komodo Ide 10.1.2
Windows 10

**Comment by babobski** [comment]
Downgrading to 10.1.1 😢 can't work with this bug

**Comment by cgchoffman** [comment]
Thanks @babobski #2180

**Comment by Naatan** [comment]
fyi we are preparing a 10.1.3 release which fixes this, and @cgchoffman is also preparing a nightly for the meantime.

**Comment by babobski** [comment]
@Naatan thanks, good to know

**Comment by cgchoffman** [comment]
Nightly will be available around 12 PST, just after.

**Comment by babobski** [comment]
@cgchoffman 👍
