### ISSUE TITLE
Identation, some code selected

### ISSUE THREAD

**Issue by jonatan-castaneda** [Komodo/KomodoEdit#2194]
### Short Summary
I just select an specific number of rows of code so as to indent it, but each time I press Tab, the number of lines selected increase one more.

### Steps to Reproduce

-Select two rows of code and press Tab
-Then Komodo select the next row of code (now you got 3 rows selected)

Example code: I want to indent the two rows wich are inside of the foreach 

    foreach($persons as $person){
echo $person->name;
echo $person->age;
    }

### Expected results

    foreach($persons as $person){
      echo $person->name;//select this two rows to indent
      echo $person->age;//
    }
    $x = null;

### Actual results

    foreach($persons as $person){
      echo $person->name;//select this two rows to indent
      echo $person->age;//
          }--> This row is automatically selected when I press Tab once
        $x=null; --> This row is automatically selected when I press Tab twice
### Platform Information

*Komodo Edit 
*Komodo Version 10.1
*Operating System Windows 10

**Comment by cgchoffman** [comment]
#2180 Thanks for reporting.  Fix incoming
