### ISSUE TITLE
Pane customizations lost after dirty shutdown

### ISSUE THREAD

**Issue by cdcmicro** [Komodo/KomodoEdit#2195]
### Short Summary

Pane customizations lost after dirty shutdown

### Steps to Reproduce

1. Leave Komodo open with several open files
2. Windows Update or other unplanned reboot (dirty shutdown)
3. After reboot Komodo says it didn't shut-down correctly, do I want to restore files from my last session - Yes

### Expected results

Customized arrangement of items in the left/right/bottom panes is restored along with the previously open files.

### Actual results

Default arrangement (Places, Open Files, Collaboration, and Databases in the left pane; Toolbox, Code, DOM in the left pane; other stuff in the bottom pane).

### Platform Information

Komodo IDE, version 10.1.2, build 89508, platform win32-x86.
Built on Thu Nov 17 15:59:27 2016.

### Additional Information

Fortunately, it's not a frequent occurrence.  But it's happened twice or three times since July.   Takes time to manually restore when it does.  Had to write it up while it still hurts :-)

**Comment by cgchoffman** [comment]
Thanks for the report #2000

**Comment by cgchoffman** [comment]
It may not sound exactly the same but the root issue is those stale workspace that are kept in the prefs.

**Comment by cdcmicro** [comment]
Duh!  I even commented on #2000.  Thanks for reminding me.

**Comment by cgchoffman** [comment]
No problem @cdcmicro!
