### ISSUE TITLE
Cannot apply default file associations on Windows

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#220]
Gives error: `[WARNING] wininteg: could not find relevant current action to
remove: 'Edit with Komodo'`

**Comment by tcdaly** [comment]
In Windows 7, Komodo 9.1.0, I can't get Preferences -> Windows Integration to work.  'Re-apply settings' does nothing and text files still don't open in Komodo when double-clicked.  If I try the Windows method - right click file, 'Open with', 'Choose default program', Komodo doesn't appear in the list of default programs (either 'recommended' or 'other').

Is that what this bug issue is about?

**Comment by cgchoffman** [comment]
Looks like our Appkeypath might have changed at some point.  The "action" it's supposed to be changing is "Edit with Komodo IDE".  But I'm noticing that file associations get set regardless of this error occurring.  Still digging.  @tcdaly to answer you question, no I don't think so but I'm still digging.  Sorry for the inexcusably delayed response.  I"m not 100% that appkeypath is the issue but it's definitely something off here.

**Comment by cgchoffman** [comment]
Still waiting to hear back if file associations were set or not.  They worked fine for me despite that error.

**Comment by tcdaly** [comment]
Not sure if it's quite relevant to the specific problem, but I can test Komodo Edit 9.3.0 in Windows 7 for the problem I reported on 17 June if it's any help?

**Comment by cgchoffman** [comment]
Yes, please.  It's still relevant.  We haven't touched the code so it should be the same.

**Comment by tcdaly** [comment]
Tested a clean install of 9.3.0 in Windows 7.
Preferences -> Windows Integration -> Configure Common Associations, ticked everything.  Manually added .txt to both lists. Clicked 'reapply settings to system', 'Apply', then 'OK'.

Problem as described on 17 June still applies for double-clicked text files (which open in Notepad), XML files (which are opening in IE) and HTML files (which open in Firefox).  However, I have the 'Edit with Komodo Edit' context menu option which works OK.  PHP and Perl files are behaving differently - these open in Komodo when double-clicked.

It seems to be a mixed picture.

**Comment by cgchoffman** [comment]
Well, this error is unrelated to whats going on:
`Gives error: [WARNING] wininteg: could not find relevant current action to remove: 'Edit with Komodo'`
File association support a new and an old application name (i don't know when we changed it) so it throws a warning when it tries the old app name and doesn't find it.

Carrying on...

**Comment by cgchoffman** [comment]
Well after all that.  There is no bug here.  Or at least not any more.  
Komodo only sets "edit" and "edit with Komodo IDE" in the prefs dialog.  The "Open" and "Open with Komodo IDE" are set somewhere else, most likely in the installer I'm guessing but I haven't dug into that part yet.  That would be a new bug pr an enhancement request depending on what the code says.

**Comment by cgchoffman** [comment]
Having said that, there is no reason to be so vocal with that log message.  We expect it, we don't need to show it.
