### ISSUE TITLE
Top bar (with minimize button and whole screen button) is missing 

### ISSUE THREAD

**Issue by i-shenl** [Komodo/KomodoEdit#2200]
### Short Summary
The top bar is missing in Komodo. The minimize, maximize, and close buttons are missing and the ability to move Komodo around when clicking on the top bar and dragging is lost. I have the "Use native window borders" checked in "Preferences -> Appearance -> Platform Integration".

As a result, Komodo takes up the whole screen. I can only get the focus off Komodo if I click on another window or hit the "Windows" key".

### Steps to Reproduce

None that I am aware of. The only thing I can think of that might cause this is when I upgraded from 10 to 10.1.2. 

### Expected results

Should still have the ability to minimize and move the Komodo app window around.

### Platform Information

Komodo IDE 10.1.2 on Ubuntu Linux 15.04

### Additional Information

To get out of this mode, either click on another app's window or press the Windows key.

**Comment by Naatan** [comment]
Spoke to i-shen. Appears to be how Unity does fullscreen. Nothing we can do about this. Well we could but it's not our job to fix Unity. ;)
