### ISSUE TITLE
Can't close tabs

### ISSUE THREAD

**Issue by kevinlieser** [Komodo/KomodoEdit#2203]
Sometime it is not possible to close tabs / files.
The error occurs when trying to close with "CMD + W".
When i press the close button on the tab itself the error do not appear but the tab also do not close.

**Error:**
```
[Exception... "[JavaScript Error: "this.log is undefined" {file: "vieweditor" line: 1254}]'[JavaScript Error: "this.log is undefined" {file: "vieweditor" line: 1254}]' when calling method: [nsIController::doCommand]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 239"  data: yes]
Fri Dec 02 2016 13:24:13 GMT+0100 (CET)
```

*Komodo Edit or IDE?* 
IDE
*Komodo Version?* 
10.1.1
*Operating System (and version)?* 
macOS Sierra 10.12.1

**Comment by mitchell-as** [comment]
Hi, would you please post some steps for us to reproduce the problem? What are the circumstances of "sometimes"? Thanks.

**Comment by kevinlieser** [comment]
There are no more steps, sorry! It happend for the third time. I was just working in multiple files and when i want to close the files (was working on remote (local server) via places panel) it hung and don't let me close it.

The first time i wanted to work in split view (same file). The split view window had an issue (was white and the tabs just where blank without filename – but also here - couldn't close it). I could create "new tabs" with CMD + N but they were also empty (with empty split view window). This happend 4 days ago maybe. After restarting Komodo i was able to use split view as normal.

The two other occurences were just tabs (without split view) that i wanted to close.

The Exception looks like Komodo wasn't able to log something :-)? `...chrome://komodo/content/library/commands.js :: command_doCommand :: line 239...`

**Comment by Naatan** [comment]
When the problem occurred and you opened new files, did it just open empty tabs? Ie. you could see the close button but nothing else.

**Comment by kevinlieser** [comment]
Excatly, but i can't close it.

**Comment by Naatan** [comment]
Yeah I had that happen to me the other week. It was very random and I was not able to reproduce it again :( This seems to happen to you often though?

**Comment by kevinlieser** [comment]
Sometimes, yeah. It's annoying because i have to restart Komodo (and so have to close all files – even if i just want to close a single file).

**Comment by Naatan** [comment]
Yeah no doubt. I'd love to fix this bug as it's been covertly buggin people for a while now, but it's very hard to fix a bug that isnt reproducible. At this point the best thing I could ask you for is to try and remember exactly what you were doing leading up to when the bug happens, and then explain those steps to us as best you can. If we can figure out what triggers the bug we can figure out a fix.

I'm sorry for the inconvenience :(
