### ISSUE TITLE
Support keyword auto completions for Perl

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2204]
### Short Summary

Seems like it should be there.

**Comment by mitchell-as** [comment]
`sub` is a Perl keyword, and our codeintel for Perl does not autocomplete keywords, just built-in functions. (FYI many of our codeintel languages do not autocomplete keywords either.)

**Comment by cgchoffman** [comment]
> FYI many of our codeintel languages do not autocomplete keywords either.

I just tried Ruby, Python and Javascript and they all autocomplete keywords.  It's a UX bug in my eyes if half the languages do one thing and half do another.  Is there a reason we can't do autocompletions on keywords for Perl?  I thought it was just a matter of setting them in a koLang file.

**Comment by Naatan** [comment]
I can't think of any good reason why we shouldnt be auto completing keywords. How much work would this be @mitchell-as ?

**Comment by mitchell-as** [comment]
Half a week to a week I would say. I wish it was as simple as setting keywords in a koLang file...

Sorry for the false info @cgchoffman. I must have been mis-remembering about our other languages.

**Comment by Naatan** [comment]
That would be half a week per language or overall?

**Comment by mitchell-as** [comment]
Just for Perl, It appears our other languages already provide completions for keywords.

**Comment by mitchell-as** [comment]
This has been implemented for Komodo 11.
