### ISSUE TITLE
Python3 Debug Error when Chinese character in src file path

### ISSUE THREAD

**Issue by athing3777** [Komodo/KomodoEdit#2205]
### Short Summary
i'm debug a .py file in python3. Everything is ok when the file name contains only ASCII charaters, but when i rename the file or the directory with some Chinese charaters, the following exception occurs:

Unhandled exception in thread started by <bound method dbgpSocket._getIncomingDataPacket of <dbgp.client.dbgpSocket object at 0x0000000002AC6F28>>
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\support\dbgp\python3lib\dbgp\client.py", line 2200, in _getIncomingDataPacket
    newData = newData.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb8 in position 66: invalid start byte

What's more, if a breakpoint retains in one .py file with Chinese-character-path , all the other .py files will report the above exception while debugging. But "Run without Debugging" goes normally.

### Platform Information
Komodo IDE 10.1.1
window 7 zh-cn

**Comment by mitchell-as** [comment]
Thanks for the additional information, but let's keep this in #2202.
