### ISSUE TITLE
Komodo IDE tcl/Tk CodeInteligence special behaviour if ":" in proc names

### ISSUE THREAD

**Issue by konradlustig** [Komodo/KomodoEdit#2206]
### Short Summary
Komodo IDE can not treat a ":" in the procedure names in tcl/Tk. It is necessary to put the proc name into braces as a workaround. But the tcl/Tk interpreter can treat both formats.

### Steps to Reproduce
```
proc Blasim:ImportDrivers {} {
    set import_list [glob -nocomplain src/*.tcl]
    foreach import $import_list {
        uplevel #0 "source $import"   
    }
}
#MAIN
Blasim:ImportDrivers 
```
### Expected results
import_list variable is no global variable but located below the Blasim:ImportDrivers
![expected](https://cloud.githubusercontent.com/assets/24384723/20879684/3c85de78-bad5-11e6-8608-8907bfee52f4.png)
 

### Actual results
![actual](https://cloud.githubusercontent.com/assets/24384723/20879502/68f95648-bad4-11e6-9f7b-40b4f8468b1d.png)

### Platform Information

*Komodo  IDE* 
*Komodo Version 10.1* 
*Win 7 64 bit* 

### Additional Information
Workaround:
encapsulate  Blasim:ImportDrivers in braces {} works:
proc {Blasim:ImportDrivers} {} {
...
}
but the tcl interpreter can use both formats!

 
 -- eg. Error logs, screenshots, workarounds --

**Comment by mitchell-as** [comment]
Thanks for the report.

**Comment by mitchell-as** [comment]
Method names with ':' in them fixed via https://github.com/Komodo/codeintel/commit/4a5f7bfc9588deec37414dc9ebc745daaeace8d4

The symbol browser no longer shows variables within methods, so the second part of this issue is no longer relevant.
