### ISSUE TITLE
Prefs > Environmental: Enable copy/edit of System vars in all scopes

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2209]
### Short Summary

Right now there is a mechanic where you can do the following:
- You can only copy then modify existing system variables in the global prefs.
- IF a pref is copied then modified in the global then it is inherited to Project prefs.  When you open the project prefs, that variable will magically appear prepopulated and you can edit it furter for your project.
- IF it hasn't been copied globally then you have to manually enter variables in the Project prefs

This is a hidden mechanic that I really only found by accident and makes it a pain to maintain custom "System" vars for a project.

I had some ideas but @Naatan mentioned the idea of simply make all Environmental pref windows the same which would solve this issue.

**Comment by cgchoffman** [comment]
Another draw back of the existing mechanic is that you can never reset the variable that you modify.  If you delete it then reopen the Project prefs it thinks it already initialized and doesn't check the global for prefs to pull in :(.  To work around it you have to delete the project file and create a new one.

**Comment by Naatan** [comment]
I'm closing this in favour of #2210. This bug is more UX oriented, I'd prefer this to be addressed by having a single modular Environmental editing interface, as we talked about before.
