### ISSUE TITLE
Unexpected Color Scheme Change

### ISSUE THREAD

**Issue by mitchell-as** [Komodo/KomodoEdit#2212]
### Short Summary

After starting Komodo for the first time and modifying an unrelated preference, the color scheme unexpectedly changes from "Default" to something else.

### Steps to Reproduce

1. Start Komodo with a clean profile.
2. Accept all defaults in the first start wizard.
3. Leave the tutorial tool open, and go to Edit > Preferences.
4. Ignore the alert dialog stating that the tutorial tool is still open.
5. Note that the color scheme is no longer "Default", but the first item in the list ("3024" in my case.)
6. Unknowingly changing some prefs and clicking "Ok" or "Apply" will unexpectedly change the color scheme.

### Expected results

All of the above steps should maintain the "Default" color scheme from the first start wizard.

### Actual results

The color scheme is changed to something unexpected.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.1.3
*Operating System (and version)?* Linux

**Comment by Naatan** [comment]
Fixed in 10.2.
