### ISSUE TITLE
Perl Subs no longer FOLD properly

### ISSUE THREAD

**Issue by arnoldrb** [Komodo/KomodoEdit#2213]
### Short Summary
In Komodo IDE 8 (my previous version) I could fold a perl sub and thus put it conveniently out of the way. Now with Komodo IDE 10.1.2 I find that all of my subs no longer fold completely. They sort of partially fold leaving more folds and ultimately a visual mess in place of the neat single remaining sub line that I am familiar with from version 8. Some subs do fold properly. 

In trying to get together an example to attach to this ticket it seems that the problem occurs near multiline commented-out code within the subroutine. See attached example code.

### Steps to Reproduce
It looks like a subroutine with several code lines commented out will not fold properly (hypothesis).

### Expected results
Perl sub should fold leaving only the initial sub definition line visible

### Actual results
When folded from sub start line the Sub folds at unexpected place. Remainder of sub is unfolded

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.1.2
*Operating System (and version)?* Windows 10 Pro (1607)

### Additional Information
[PerlNotFoldingProperly.zip](https://github.com/Komodo/KomodoEdit/files/637389/PerlNotFoldingProperly.zip)

 -- eg. Error logs, screenshots, workarounds --

**Comment by mitchell-as** [comment]
Hi, thanks for the report. I can confirm the bug. We updated our Perl lexer recently and it appears a regression snuck in.

**Comment by mitchell-as** [comment]
Note to self: Scintilla 3.7.3 still exhibits this problem, so we'll have to produce and send an upstream patch that fixes this.
