### ISSUE TITLE
Rx Toolkit highlighting usability problem in Komodo 10

### ISSUE THREAD

**Issue by arnoldrb** [Komodo/KomodoEdit#2214]
### Short Summary

In the Komodo 10 Rx Toolkit there is no distinction between highlighting for **expression match** and user highlighting to **edit** in the Search Text window. 

Quite often I manually edit the Search Text field to ensure that the regular expression covers all of the possibilities - rather than finding all of the exact examples for all of the cases.

One key part of this is the ability to highlight portions of the Search Text to cut, copy or delete or whatever. However, since there is no difference in the highlighting for user text selection versus expression matching this is now quite difficult to do. 

In Komodo 8 Rx Toolkit there was a clear distinction between these different types of highlighting. It was much easier to do this sort of operation.

I have attached two screenshot examples with exactly the same parts highlighted in version 8 (grey and yellow) and version 10 (all grey). It is easy to see how much more difficult is in version 10 to actually do this sort of operation.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* version 10.1.3, build 89510, platform win32-x86.
*Operating System (and version)?* Windows 10 Pro (1607)

### Additional Information

 -- eg. Error logs, screenshots, workarounds --
![komodo 8 rx toolkit](https://cloud.githubusercontent.com/assets/24299124/20988266/0c5c176a-bc9e-11e6-8d95-3b3cf765403b.jpg)
![komodo 10 rx toolkit](https://cloud.githubusercontent.com/assets/24299124/20988267/10a057d2-bc9e-11e6-90fa-51957e41bdb0.jpg)

**Comment by cgchoffman** [comment]
What color scheme are you using @arnoldrb?  I'm not seeing this in the default color scheme.

**Comment by cgchoffman** [comment]
To work around this you can edit the Color Scheme yourself (if you haven't already).
- **Tools menu > Color Scheme Editor**
- In the left column make sure *Editor* is selected
- In the menu below the drop down select `Match`
- Edit to your desire
- Click **Apply**
- Should just need to apply to **Editor** but I just apply to all out of habit.

**Comment by arnoldrb** [comment]
Thank you cgchoffman.
Solved my problem - I just don't know my way around the tool well enough.
Really a 'read the manual' issue but somehow I just don't read the online documentation like I would have reviewed the paper manual years ago.

**Comment by cgchoffman** [comment]
No worries at all @arnoldrb.  For future reference, for questions like this you should use the forums: http://community.komodoide.com/
