### ISSUE TITLE
Color Scheme: Default: Editor > "Match" is really really hard to see

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2215]
### Short Summary

This is similar to the discussion I've seen out there that the "find highlight" is too hard too see as well.  The `match` style is too subtle to see if you have a large section of content and minimal results.

As a bonus, if it makes sense, can `match` be changed to `regex match`?  Unless i'm not aware of the fact that it's used elsewhere, it would make it much more clear that it's for the Regex tool.

**Comment by Naatan** [comment]
Fixed in 10.2
