### ISSUE TITLE
Single apostrophe will break debugger

### ISSUE THREAD

**Issue by fjossandon** [Komodo/KomodoEdit#2217]
### Short Summary
Today I used the debugger and it died showing an initialization error message:
`Unable to initialize debugging system because Debugging will be unavailable until you change the debugger port in your preferences.`
I had just updated to latest version, so my first instinct was that the update had broken the debugger. I have the "system-provided free port" selected and debugger connection status was "Listening", so the message confused me since it appeared that it had nothing to do with the port.

After testing more with other scripts I finally realized that the problem was that in the script arguments I had copied a path that contained an apostrophe (like `/path/fo'lder`) without surrounding quotation marks, so when I changed it to `"/path/fo'lder"` it worked again. Also found that the script content is irrelevant, and if the Script Arguments contains a single `'` or `"` it will die with the message stated above.

### Steps to Reproduce
Take any script, put a single `'` or `"` in the script arguments and click OK

### Expected results
That the debugger initialize and let my own script code to complain if the `'` causes a malformed value in the argument.

### Actual results
The debugger dies with a wrong error message (it was not a problem with free ports). Also the error message is unrelated and did not help me to found the real error because it was something unrelated with ports.

### Platform Information
Komodo IDE, version 10.1.3, build 89510, platform macosx.
Built on Wed Nov 30 16:51:48 2016.
Mac OSX 10.11.6

**Comment by mitchell-as** [comment]
Hi, thanks for the detailed report. I've reproduced this.

**Comment by mitchell-as** [comment]
Upon further investigation, this is not actually a bug. If you do not properly escape quotes in command line arguments, you'll get an error. This happens in any shell, not just Komodo. I admit the error message "an unexpected error occurred" could be better, but when I look at Help > Troubleshooting > View Log File, I see: `ValueError: command line is not terminated: unfinished single-quoted segment`.
