### ISSUE TITLE
toolbox: can't drag and drop tools on Komodo to import them

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2219]
### Short Summary

When I drag and drop toolbox tools (`*.komodotool`) on to Komodo it opens the file in the editor.  It should import the file to the toolbox.

Handle it like `*.ksf` files; ask to import or open the file.
https://github.com/Komodo/KomodoEdit/blob/master//src/chrome/komodo/content/library/open.p.js#L200

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/6c2fe63767a5b3ad9cdb04533215ab1b67b4aff9

**Comment by Defman21** [comment]
Why IDE only?

**Comment by cgchoffman** [comment]
Oh yes, this should get into Edit as well.

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoEdit/commit/a4a31a8e6dff16462d1997f6825e65c832b68d61
