### ISSUE TITLE
inconvenient choice of colours for highlighting word in "Find" window (imported from old database, #102155)

### ISSUE THREAD

**Issue by ecterrab** [Komodo/KomodoEdit#222]
I am using Interface Skin: Abyss, Icon Set: IcoMoon - Cupertino. Open a file, double-click a word, then Edit -> Find: the Find window opens with the word highlighted. Expected: this highlighted word is easy to read; my understanding is that the background color is wrong, should be "not-light blue", as you see in the image the checkmark in "Match Case" and "Word", or otherwise keep it light blue but then the color of the font should be black, not white. Received: the text is displayed in white and the background is light blue, making almost impossible to read what is highlighted. I believe I tried all the Preference options for colours to have this working properly but couldn't find any that helps (is there one?). If these colours are optional, what is the option to set? In any case the current choice is not a good default.

This problem subsists in Komodo 9.0.1, latest build from April/15. Would it be
possible to bump the priority? (I mean: taking into account that It was tracked
an year and a half ago). The Abyss skin is beautiful, but for these minor
things, perhaps easy to adjust? Thanks.

I am attaching an image showing the issue:
![screen shot 2015-04-27 at 3 37 00 pm](https://cloud.githubusercontent.com/assets/12106224/7359476/93fd0d5e-ecf3-11e4-9d3b-8450a70c9d49.png)

**Comment by Naatan** [comment]
Closing as Abyss is no longer part of core Komodo, please consider reporting this issue here: https://github.com/Komodo/Abyss-Skin
