### ISSUE TITLE
Implement dependency functionality for add-ons

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#2221]
### Short Summary

I'd very like to see that.

To add a dependency, you should add `<dependency>name@host</dependency>` in the manifest.

When installing an add-on, you should resolve deps recursively and install from the deepest:

```
- addon 1
-- addon 2
--- addon 2.1
--- addon 2.2
-- addon 3
--- addon 3.1
--- addon 3.2
```

First, install `addon 2.1, addon 2.2, addon 3.1, addon 3.2`, then `addon 2, addon 3`, then `addon 1`. Since some of them could have a bootstrap file, it's important to install them from the deepest addon. (so addon2.1 could initialize its require path and addon2 could use it).

The database could be fetched from the packages json file :)

**Comment by Naatan** [comment]
Sorry but this will never happen. It burdens users for the convenience of developers. Addons are for users, not for developers.

Additionally even taking my previous point aside there just aren't enough addons to justify the type of development this would require.

Sorry :\

**Comment by Defman21** [comment]
Hmm okay, I excepted such an answer. No worries though, I'm on the way to implement something like that myself in a form of single javascript file :)

**Comment by Naatan** [comment]
Please be mindful of the end-user. Is this helping you or is this helping the user? Of course it's fine to do something that helps you while not affecting the user, but I have my doubts about doing dependency management on the users machine in a way that wouldnt affect them.

**Comment by Defman21** [comment]
Everything is async so there shouldn't be any drops in the performance. It's not dependency management, it just allows developers to use github repos as `require`.

**Comment by Naatan** [comment]
With due respect, this seems like a solution looking for a problem.

Package management is meant to be the developers job, not something that happens in the application itself.

I really like your enthusiasm, but this honestly feels a little bit missguided to me. If you want to create tools for developers, why not focus your efforts on something like npm or bower and how they might integrate into Komodo?

**Comment by Defman21** [comment]
Because I don't like any of them (except for bower, never used it myself because I'm more of a Ruby guy) and there's nothing need to be done to use npm packages at the development stage of a Komodo package. For the release stage, there are a lot of tools allows you to bundle npm modules into files that you can `require`, so from my point of view it's all cool :)

What I'm trying to create is a single javascript file with no dependencies (except for Komodo's SDK, of course) that any developer could put somewhere in the `content/` folder and use it to download other community created bits (or SDK's, whatever) and use them :) If there is more than one developer using the file, he won't mind about sharing dependencies of its package with other packages, they live in their own variables after all, but we just don't want to download them over and over for each package :)

If it's not going to work as I except, there's nothing bad. After all, this is just another project where I improve my JS skills and get more knowledge of Mozilla's and Komodo's architecture and SDK,

**Comment by Naatan** [comment]
Ok, if it's an educational tool for you then of course by all means :) But just beware that there likely isnt much (if any) demand for something like this. And even if there were I'd quite honestly be hesitant about allowing it as it creates a whole slew of new issues that are frankly unnecessary.

**Comment by Defman21** [comment]
Screw that. Loading dependencies from github in realtime is a bad idea.
