### ISSUE TITLE
No variables while debugging perl scripts

### ISSUE THREAD

**Issue by Yogislav** [Komodo/KomodoEdit#2224]
### Short Summary
I'm currently debuggiem a project written in Perl and while debugging, I see no local variables. I'm not talking only values, but the list itself is empty, and it doesn't seem to be related to going through long call stack, it happens even in the very beginning. I can add them manually to watch list, but the "local" list is not filled.

### Steps to Reproduce
1. Launch a perl script with -d argument.
2. Go through several variable assignments.
3. Check the debuging panel if the variables are there.

### Platform Information

*Komodo Edit or IDE?* Komodo IDE
*Komodo Version?* 10.1.3 (build 89510)
*Operating System (and version)?* Windows 7 Pro, 6.1.7601 SP 1

**Comment by Yogislav** [comment]
I'm using version 5.12.3

Oddly enough, restarting computer and Komodo seems to have fixed it. (Why havent' I tried that?)

**Comment by Naatan** [comment]
Let us know if the problem pops up again.
