### ISSUE TITLE
UnicodeEncodeError with python3

### ISSUE THREAD

**Issue by athing3777** [Komodo/KomodoEdit#2229]
**Short Summary**
Only a single statement: print('\u2022')
raise the exception as follow:
UnicodeEncodeError: 'gbk' codec can't encode character '\u2022' in position 0: illegal multibyte sequence

**Platform Information:**
Komodo IDE 10.1.1
window 7 zh-cn
python3.4

**Comment by mitchell-as** [comment]
Hi, this looks like a Python programming error, and not a Komodo error. Does the error also show up in your Help > Troubleshooting > View Log File? If so, please provide the entire message. If not, then it is a Python programming error and you'll have to fix it on your own. Thanks.

**Comment by Defman21** [comment]
I were trying to reproduce it in the python 3.5 repl and by running the komodo debugger: I don't get this error on Linux. (elementary OS 0.4, based on ubuntu 16.04)

**Comment by athing3777** [comment]
Thanks!
Messages in log file:
[2016-12-20 09:20:10,785] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2016-12-20 09:20:10,786] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
seems not related.

I can run the same code in IDLE of the same python3.4 intepreter.




彭炜明
北京师范大学信息科学与技术学院
athing@tju.edu.cn

From: mitchell
Date: 2016-12-19 23:16
To: Komodo/KomodoEdit
CC: athing3777; Author
Subject: Re: [Komodo/KomodoEdit] UnicodeEncodeError with python3 (#2229)
Hi, this looks like a Python programming error, and not a Komodo error. Does the error also show up in your Help > Troubleshooting > View Log File? If so, please provide the entire message. If not, then it is a Python programming error and you'll have to fix it on your own. Thanks.

**Comment by athing3777** [comment]
I find a workaround as follow:
=====================================
import io
import sys
sys.stdout = io.TextIOWrapper(sys.stdout.buffer,encoding='utf-8')
print('\u2022');

**Comment by mitchell-as** [comment]
Okay, thanks for the update. I don't think this is a Komodo issue.
