### ISSUE TITLE
Komodo Edit 9.3.2 crashing on shutdown

### ISSUE THREAD

**Issue by Paul142857** [Komodo/KomodoEdit#2236]
### Short Summary
Since updating to 9.3.2 earlier this month the program frequently crashes when I use the "Quit Komodo Edit" option in the File menu.

### Steps to Reproduce
I don't know how to reproduce this.  It does not happen every time that I shut down.  Perhaps about 75%-80% of the time.  It can take place after simply looking at an html file or after doing a simple edit and save of a file.

### Actual results
A box pops up asking me to report the problem before completing the shutdown.  The next time that I open Komodo Edit I get a message about it not shutting down correctly and asking me if I want to reopen the files that it was working with.  Whether or not I say "yes" or "no" to the reopen option the program sometimes crashes again on the next shutdown.

### Platform Information
Komodo Edit, version 9.3.2, build 16460, platform macosx.
Built on Thu Dec 10 19:37:46 2015.

**Comment by mitchell-as** [comment]
Did you recently upgrade to Mac OSX Sierra? See http://community.komodoide.com/t/osx-sierra-10-12-2-breaks-komodo-nightly-available-with-fix/3276 for more information.

**Comment by cgchoffman** [comment]
You can get Komodo Edit 10.1.4 here to try: http://downloads.activestate.com/Komodo/releases/10.1.4/

**Comment by Naatan** [comment]
For more information see 

http://community.komodoide.com/t/osx-sierra-10-12-2-breaks-komodo-nightly-available-with-fix/3276

**Comment by Paul142857** [comment]
Thanks! Upgrading to 10.1.4 did the trick.

**Comment by cgchoffman** [comment]
Awesome @Paul142857!  Glad we could get you sorted so quickly!
