### ISSUE TITLE
minimum number of columns to keep to the right of the cursor (imported from old database #96310)

### ISSUE THREAD

**Issue by ecterrab** [Komodo/KomodoEdit#224]
In the Preferences, Editor, Scrolling, we have "Minimum number of lines to keep above and below cursor". That is a great option. Say we set it to 5. Then wherever we are in a code file, we always see at least 5 lines above and below, instead of seeing only the very last line and nothing else.

But then when there is a long line in the code and I move the cursor to the end of the line, I am never sure whether I am or not at the end because I do not see any column further to the right (I always suspect I may be somewhere within the line, so not at its end - there is no clue to know). 

What I am suggesting is to resolve this small however concrete inconvenience by having a preference option of the form "Minimum number of columns to keep right of the cursor (when moving the cursor to the end of a line)"; and I would also suggest to have it default to 5. Anyway, having the option (not its default value) is what I see as the core thing.

This problem is still there in Komodo 9 last build April/15. I note that although a solution just for me was provided by implementing macros, I think this is a sort of relevant issue: you move the cursor over long line to its end and the only way to be sure you are at the end is to see - say - 5 additional blank characters. The rationale here is exactly the same as the one behind "Minimum number of lines to keep above and below cursor" regarding the vertical direction. It is missing regarding the horizontal direction.

**Comment by Naatan** [comment]
Could you provide (or link to) the macros that you used?

**Comment by ecterrab** [comment]
Hi Nathan
I didn’t use the macros suggested. I tried the first time they were suggested but they didn’t work. A correction was made afterwards (regarding the suggestion made) but I am not familiar with this kind of macros so end up living with the issue, but honestly remembering about it and disliking each time I cross with this, almost every day. It attempts against the user-experience of the Editor.

Regarding the macros suggested themselves, they are there in the old report: https://bugs.activestate.com/show_bug.cgi?id=96310

Is this all the info you need?

**Comment by Naatan** [comment]
Thanks, fwiw the working macro is:

```
var view = ko.views.manager.currentView;
var scimoz = view.scimoz;
var slop = 100; // Experiment with this value
scimoz.setXCaretPolicy(scimoz.CARET_SLOP | scimoz.CARET_STRICT, slop);
```

Simply add this to your toolbox by clicking the gear icon, then "New Macro". Give it a name, paste in the code and go to the Triggers tab, then set it to trigger "After File Open". Then press OK to close and save the macro.

After that any file you open will have space preserved before and after the cursor (horizontally).

We'll definitely look into adding this as a native feature.

**Comment by ecterrab** [comment]
I did what you said, and it does work. I still feel that this is an issue for everybody - the user experience of the Editor is not as good when you go to the end of a line and remain in doubt whether you are not not at the end. I guess you added that option regarding the vertical direction for this same reason. Looking forward for the implementation of this also in the horizontal direction.

Independent of that, while following your instructions, I noticed two bugs in the copy and paste within a macro window: 1) you paste stuff but nothing is visible, as if it didn't paste ... but then you move the focus elsewhere by clicking elsewhere, for instance to another tab of the same macro window, and then return to the main macro window and voila! there it is what you pasted before but was invisible. 2) after the contents appear, everything blinks steadily, even when you are doing nothing. All this is only visible in a movie, but github does not allow to attach a small movie. I managed to workaround by artificially adding a termination "JPG" to the movie. So you need to download the file, then remove the JPG termination, and you can watch all this ( 1) and 2) ) happening.

![bug in copy and paste in macro window mov](https://cloud.githubusercontent.com/assets/12106224/7359251/2bb711d8-ecf1-11e4-8348-f3e4f0cbc342.JPG)

**Comment by cgchoffman** [comment]
@ecterrab please don't file additional bugs within the same report.  

And we agree with you that this should be added.  As Naatan said "We'll definitely look into adding this as a native feature"

**Comment by ecterrab** [comment]
Hi, yes. I mentioned it here because this is how I crossed with the issue, always relevant to know. But I actually tracked this as a separate bug - see #226,

**Comment by cgchoffman** [comment]
A link back to this issue from the new report would suffice.

**Comment by cgchoffman** [comment]
Hi @ecterrab, could you try enabling *Prefereces > Editor > Scrolling: "Enable scrolling past end of buffer"* and see if this allows you to scroll passed the end of line boundary?

**Comment by ecterrab** [comment]
Hi, yes I tried that when I noticed the problem, time ago, then more recently before tracking the issue - it does not help.
