### ISSUE TITLE
CSS show auto completion popup after autocomplete of CSS attribute

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#2240]
### Short Summary
When you autocomplete a css attribute like `color: ` you will have to type the first letter of the value or trigger the auto completion by hand.
Would be nice if this would work in 1 action.

### Expected results
![example-1](https://cloud.githubusercontent.com/assets/3530262/21416910/f662d4e2-c816-11e6-9b04-0c4652ecbf98.gif)

### Actual results
![example2](https://cloud.githubusercontent.com/assets/3530262/21416916/fe4095c8-c816-11e6-94db-fe46baf94f29.gif)

**Comment by mitchell-as** [comment]
Thanks for the suggestion.

Note to self: It is the responsibility of Komodo to request completions immediately after a previous completion.

**Comment by mitchell-as** [comment]
This is now in Komodo 11.
