### ISSUE TITLE
Chrome Debugging on Windows Fails With File "unavailable for debugging"

### ISSUE THREAD

**Issue by mitchell-as** [Komodo/KomodoEdit#2243]
### Short Summary

http://community.komodoide.com/t/javascript-debugging-locally/3305/3

Try to start JavaScript debugging with Chrome on Windows and you'll get an error that the file is unavailable for debugging.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10
*Operating System (and version)?* X

### Additional Information

The workaround is to prefix the file in the debug dialog with `\`, so the file to debug is `\C:\...` instead of `C:\...`

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoIDE/commit/f1f8f33fcb8319e5d2297c9537df5b6081f320db

**Comment by MrAnalogy** [comment]
Michell-as' s link is 404.

**Comment by th3coop** [comment]
@MrAnalogy the IDE repo is private.  That a dev note for ourselves.

**Comment by MrAnalogy** [comment]
How do I resolve the problem and do debugging within komodo?

**Comment by th3coop** [comment]
@MrAnalogy I don't know what problem you're hitting.  Seeing as this is presumably fixed, it's not likely the same issue so we'll have to diagnose from scratch https://community.komodoide.com/
