### ISSUE TITLE
Unable to toggle open remote directory after renaming sub directory

### ISSUE THREAD

**Issue by azzuwan** [Komodo/KomodoEdit#2244]
### Short Summary
After renaming the remote directory I'm working in I'm unable to expand the parent directory. The remote directory ABC is in the /home/me/Desktop. After changing ABC to XYZ while working on the files inside ABC, /home/me/Desktop cannot be toggle open or expanded again even after restarting.

### Steps to Reproduce
1) Connect to a remote directory
2) Access a directory and make changes to files
3) Rename the current directory
4) Now the parent directory will not toggle open and errors will be thrown

### Expected results
Remote directory should  toggle open and close as normal and not throw any errors if any child directories named are changed even if the files in the directory are currently being edited.

### Actual results

1. Parent directory cannot not be toggled open even after subsequent restarts.
2. Error notification => "Exception:request:toggleOpenState_Open" "Message:2147500037" "NS_ERROR_FAILURE" 

### Platform Information

*Komodo Edit 10.1* 
*LInux Deepin (Debian Jessie)* 

### Additional Information
![deepinscreenshot20161226112934](https://cloud.githubusercontent.com/assets/816052/21474789/8aed8114-cae9-11e6-894d-bb383a996dae.png)

I can confirm that the remote machine can be accessed via SSH.

**Comment by azzuwan** [comment]
After a couple of days not using it, I got prompted by a login screen and no more problems it seems.

**Comment by Naatan** [comment]
Meaning you can't reproduce the issue anymore or it's just fixed for that particular folder?
