### ISSUE TITLE
Multiple window issue: when komodo is not responding for a few seconds, text typed in de mean while will be placed in a random komodo window

### ISSUE THREAD

**Issue by gjvh** [Komodo/KomodoEdit#2248]
### Short Summary
When komodo is not responding due to a slow connection, a random komodo window is brought into focus and the text typed in the mean while will be placed in that window, editing your code invollintary.

### Steps to Reproduce
Open 2 op more komodo windows on a slow connection to the webserver

### Platform Information

*Komodo Edit or IDE?* Edit
*Komodo Version?* 10.1.4
*Operating System (and version)?* Win10

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by mitchell-as** [comment]
There's really not much we can do here. As with any desktop application, key presses are buffered by the windowing toolkit and processed by an event queue whether or not the application is "responsive". We cannot "pause" Komodo from receiving key presses (or any other OS-related event) while it waits for a response from a remote server.
