### ISSUE TITLE
Komodo crashes when closing Tab (macOS)

### ISSUE THREAD

**Issue by kevinlieser** [Komodo/KomodoEdit#2251]
Komodo crashes when closing neu opened Tabs.

- Open Komodo 10
- create new tab
- type some chars
- close that tab (don't save)

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.1.1
*Operating System (and version)?* macOS 10.12.2

### Additional Information

AdapterDeviceID: 0x119e
AdapterDriverVersion: 
AdapterVendorID: 0x10de
Add-ons: breadcrumbs%40activestate.com:1.0,commando%40activestate.com:1.0,editorconfig%40activestate.com:1.0.1,fontawesome%40activestate.com:1.0,icomoon%40activestate.com:1.0,klint%40dafizilla.sourceforge.net:1.4.0,koextgen%40activestate.com:0.2,openfiles%40activestate.com:1.0,trackchanges%40activestate.com:1.0,zendframework%40ActiveState.com:0.8,refactoring%40activestate.com:0.1,beautify-js%40babobski.com:3.1,inspector%40mozilla.org:2.0.15,lesscompiler%40komodoeditide.com:2.1.4,HTMLtoolbox%40babobski.com:1.7,rgba-colorpicker%40babobski.com:1.2.1,check-compatibility%40dactyl.googlecode.com:1.3.1,elastic-tabstops%40activestate.com:0.1,focusmode%40activestate.com:1.0.2,komodospellchecker%40ActiveState.com:1.0,lintresults%40activestate.com:1.0
BuildID: 89474
CrashTime: 1483358715
EMCheckCompatibility: false
EventLoopNestingLevel: 1
FramePoisonBase: 7ffffffff0dea000
FramePoisonSize: 4096
InstallTime: 1478692468
Notes: AdapterVendorID: 0x10de, AdapterDeviceID: 0x119eGL Layers? GL Context? GL Context+ GL Layers+ 
ProductID: {36E66FA0-F259-11D9-850E-000D935D3368}
ProductName: Komodo IDE
PyxpcomMethod: {e2e8c6ce-d0b9-49de-a39d-496e9e5f32c4}::isEnabledFor
ReleaseChannel: release
SecondsSinceLastCrash: 128
StartupTime: 1483358686
Theme: classic/1.0
Throttleable: 1
Vendor: ActiveState
Version: 10.1.1
useragent_locale: en-US

This report also contains technical information about the state of the application when it crashed.

**Comment by babobski** [comment]
@kevinlieser this is already fixed in the latest release, see this [topic](http://community.komodoide.com/t/komodo-10-1-4-released/3291). Just upgrade and everything should be working again.

**Comment by kevinlieser** [comment]
Thanks! That worked. I have checked the "Check for updates" button in Komodo multiple times. I didn't see that there is a new version out there.
