### ISSUE TITLE
Some functions in Komodo 10 do not work when used over MobaXterm

### ISSUE THREAD

**Issue by i-shenl** [Komodo/KomodoEdit#2252]
### Short Summary

Some functions in Komodo 10 do not work when using it via MobaXterm. The customer is running this program from Windows to connect to an Ubuntu system and they are using Komodo over it. They claim it works fine in V9

### Steps to Reproduce

This is the customer's own words:

"I am running komodo on MobaXterm,
I have been running this way since long time ago,
I want to correct you it is a FUNCTION issue, rather than a PERFORMANCE issue:
The menu items File, Edit, Navigation, View Debug Project Tools and Help are not responding to any mouse click at all,
I also not able to click the blank area and hold to drag the window, If I want to drag and move window, I have to click and drag bar beneath the menu bar.
It predecessor V9 works fine, and I have been using X-win service provided by MobaXterm for many other applications
Could you please address this defect? I can not use it AS is. I bet a lot of X-win gui programs over Xwindows server."

### Expected results

Should work. He says it ws working in V9. 

### Platform Information

*Komodo Edit or IDE?* 10
*Komodo Version?* 
*Operating System (and version)?* 

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by mitchell-as** [comment]
Note: this sounds like an issue with the new UI. @Naatan would likely have more insight.

**Comment by Naatan** [comment]
Note we do not support custom window managers like MobaXterm, that said you can probably work around this issue by toggling Preferences > Appearance > Use native window borders.

Please [contact support](http://www.activestate.com/company/developer-sales-support-contact) if you have any further questions and have a support contract, otherwise you can [use the forums](http://community.komodoide.com/).

**Comment by goodprogrammer** [comment]
@Naatan, 
Hi, the menu items are not working, there is no way for user to access the Preferences->Appearance...
Thanks

**Comment by mitchell-as** [comment]
Try Ctrl+, (comma). That should bring up the preferences dialog.

**Comment by Naatan** [comment]
You can also type "General: Preferences" into the "Go to Anything" field.

**Comment by goodprogrammer** [comment]
@Naatan @mitchell-as 
The Use native windows border setting works. That is good.
BTW, I am testing it on Native Xwindows, environment. The menu are not working, same way as in MobaXterm environment.
. So the issue is not MobaXterm specific,
Thanks

**Comment by Naatan** [comment]
Right, but like I said we do not support custom window environments. And even though native X is basically the mother of all Linux window environments we do not support it. Few people run native x as their actual window manager.

All that said - you should definitely be able to use it when you toggle "Use native window borders", it's just not something we explicitly support.
