### ISSUE TITLE
cutting variables slow

### ISSUE THREAD

**Issue by krizoek** [Komodo/KomodoEdit#2253]
### Short Summary
cutting $variable text using ctrl+x slow after version 10.1.2, but it works great with 10.1.1

### Steps to Reproduce
new file
include $var=
then mark it with a doubleclick and cut it with ctrl+x
### Expected results
slow delay before the text actually get cut

### Actual results
up to 1min delay before the text disappears

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo Edit, version 10.1.1, build 17414, platform linux-x86_64.
Built on Thu Sep 1 21:26:22 2016.

### Additional Information
im running on funtoo linux, debian kernel 4.8.15-1, xfce.

 -- eg. Error logs, screenshots, workarounds --

**Comment by cgchoffman** [comment]
Is this reproducible if you restart in `Help > Troubleshooting > Restart in Safe-Mode`

**Comment by krizoek** [comment]
Yes, it does the same in safe mode. slow delay during cuts of variables

**Comment by mitchell-as** [comment]
Does this happen for a particular language? Plain text? etc. There really should be no delay when Ctrl+X. I cannot imagine why you're seeing a slowdown here.

**Comment by krizoek** [comment]
i do program php mostly, but it happens the same when its plain text too

**Comment by krizoek** [comment]
(process:32179): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
Gtk-Message: (for origin information, set GTK_DEBUG): failed to retrieve property `gtk-primary-button-warps-slider' of type `gboolean' from rc file value "((GString*) 0x7f36851976c0)" of type `gboolean'
1483476687759	addons.xpi	WARN	Exception running bootstrap method install on check-compatibility@dactyl.googlecode.com: TypeError: Unknown preference type: undefined (resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/k/ke104/lib/mozilla/extensions/check-compatibility@dactyl.googlecode.com.xpi!/bootstrap.js:169:18) JS Stack trace: set@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/k/ke104/lib/mozilla/extensions/check-compatibility@bootstrap.js:169:19 < install@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/k/ke104/lib/mozilla/extensions/check-compatibility@bootstrap.js:56:9 < install@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/k/ke104/lib/mozilla/extensions/check-compatibility@bootstrap.js:212:9 < XPI_callBootstrapMethod@XPIProvider.jsm:4436:9 < addMetadata@XPIProvider.jsm:3332:1 < XPI_processFileChanges@XPIProvider.jsm:3441:23 < XPI_checkForChanges@XPIProvider.jsm:3602:34 < XPI_startup@XPIProvider.jsm:2090:25 < callProvider@AddonManager.jsm:208:12 < _startProvider@AddonManager.jsm:667:5 < AMI_startup@AddonManager.jsm:821:9 < AMP_startup@AddonManager.jsm:2399:5 < AMC_observe@addonManager.js:55:7
SciMoz was not closed correctly before destructor called.
SciMoz was not closed correctly before destructor called.

(process:32179): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
Gtk-Message: (for origin information, set GTK_DEBUG): failed to retrieve property `gtk-primary-button-warps-slider' of type `gboolean' from rc file value "((GString*) 0x7fb53f8974c0)" of type `gboolean'
^C


does this say anything?

**Comment by krizoek** [comment]
# equery which glibc
/usr/portage/sys-libs/glibc/glibc-2.22.ebuild
 # equery depgraph glibc
 * Searching for glibc ...

 * dependency graph for sys-libs/glibc-2.13-r6
 `--  sys-libs/glibc-2.13-r6  unknown 
   `--  sys-devel/gcc-5.3.0-r1  (>=sys-devel/gcc-3.4.4) unknown 
   `--  sys-devel/binutils-2.25-r2  (>=sys-devel/binutils-2.16.90) unknown 
   `--  sys-kernel/linux-headers-4.3  (>=sys-kernel/linux-headers-2.6.9) unknown 
   `--  sys-devel/gcc-config-1.8-r1  (>=sys-devel/gcc-config-1.3.12) ~amd64 
   `--  app-misc/pax-utils-1.1.7  (>=app-misc/pax-utils-0.1.10) ~amd64 
   `--  virtual/os-headers-0  (virtual/os-headers) amd64 
   `--  sys-devel/gettext-0.19.8.1  (sys-devel/gettext) ~amd64 
   `--  sys-apps/sandbox-2.10-r2  (>=sys-apps/sandbox-1.2.18.1-r2) ~amd64 
   `--  sys-libs/libselinux-2.6  (sys-libs/libselinux) amd64 
   `--  sys-devel/libtool-2.4.6-r2  (>=sys-devel/libtool-2.4-r4) ~amd64 
   `--  sys-libs/timezone-data-2016j  (>=sys-libs/timezone-data-2007c) ~amd64 
   `--  sys-devel/gnuconfig-20161104  (sys-devel/gnuconfig) ~amd64 
[ sys-libs/glibc-2.13-r6 stats: packages (13), max depth (1) ]

 * dependency graph for sys-libs/glibc-2.19
 `--  sys-libs/glibc-2.19  unknown 
   `--  app-misc/pax-utils-1.1.7  (>=app-misc/pax-utils-0.1.10) ~amd64 
   `--  sys-libs/libselinux-2.6  (sys-libs/libselinux) amd64 
   `--  sys-devel/binutils-2.25-r2  (>=sys-devel/binutils-2.20) unknown 
   `--  sys-devel/gcc-5.3.0-r1  (>=sys-devel/gcc-4.3) unknown 
   `--  virtual/os-headers-0  (virtual/os-headers) amd64 
   `--  sys-libs/timezone-data-2016j  (>=sys-libs/timezone-data-2012c) ~amd64 
   `--  sys-devel/gnuconfig-20161104  (sys-devel/gnuconfig) ~amd64 
   `--  virtual/pkgconfig-0-r1  (virtual/pkgconfig) unknown 
[ sys-libs/glibc-2.19 stats: packages (9), max depth (1) ]

 * dependency graph for sys-libs/glibc-2.20-r1
 `--  sys-libs/glibc-2.20-r1  unknown 
   `--  app-misc/pax-utils-1.1.7  (>=app-misc/pax-utils-0.1.10) ~amd64 
   `--  sys-libs/libselinux-2.6  (sys-libs/libselinux) amd64 
   `--  sys-devel/binutils-2.25-r2  (>=sys-devel/binutils-2.24) unknown 
   `--  sys-devel/gcc-5.3.0-r1  (>=sys-devel/gcc-4.4) unknown 
   `--  virtual/os-headers-0  (virtual/os-headers) amd64 
   `--  sys-devel/gnuconfig-20161104  (sys-devel/gnuconfig) ~amd64 
   `--  virtual/pkgconfig-0-r1  (virtual/pkgconfig) unknown 
   `--  sys-libs/timezone-data-2016j  (sys-libs/timezone-data) ~amd64 
[ sys-libs/glibc-2.20-r1 stats: packages (9), max depth (1) ]

 * dependency graph for sys-libs/glibc-2.20-r2
 `--  sys-libs/glibc-2.20-r2  unknown 
   `--  app-misc/pax-utils-1.1.7  (>=app-misc/pax-utils-0.1.10) ~amd64 
   `--  sys-libs/libselinux-2.6  (sys-libs/libselinux) amd64 
   `--  sys-devel/binutils-2.25-r2  (>=sys-devel/binutils-2.24) unknown 
   `--  sys-devel/gcc-5.3.0-r1  (>=sys-devel/gcc-4.4) unknown 
   `--  virtual/os-headers-0  (virtual/os-headers) amd64 
   `--  sys-devel/gnuconfig-20161104  (sys-devel/gnuconfig) ~amd64 
   `--  virtual/pkgconfig-0-r1  (virtual/pkgconfig) unknown 
   `--  sys-libs/timezone-data-2016j  (sys-libs/timezone-data) ~amd64 
   `--  sys-apps/gentoo-functions-0.11  (sys-apps/gentoo-functions) ~amd64 
[ sys-libs/glibc-2.20-r2 stats: packages (10), max depth (1) ]

 * dependency graph for sys-libs/glibc-2.21
 `--  sys-libs/glibc-2.21  unknown 
   `--  app-misc/pax-utils-1.1.7  (>=app-misc/pax-utils-0.1.10) ~amd64 
   `--  sys-libs/libselinux-2.6  (sys-libs/libselinux) amd64 
   `--  sys-devel/binutils-2.25-r2  (>=sys-devel/binutils-2.24) unknown 
   `--  sys-devel/gcc-5.3.0-r1  (>=sys-devel/gcc-4.4) unknown 
   `--  virtual/os-headers-0  (virtual/os-headers) amd64 
   `--  sys-devel/gnuconfig-20161104  (sys-devel/gnuconfig) ~amd64 
   `--  virtual/pkgconfig-0-r1  (virtual/pkgconfig) unknown 
   `--  sys-libs/timezone-data-2016j  (sys-libs/timezone-data) ~amd64 
   `--  sys-apps/gentoo-functions-0.11  (sys-apps/gentoo-functions) ~amd64 
[ sys-libs/glibc-2.21 stats: packages (10), max depth (1) ]

 * dependency graph for sys-libs/glibc-2.22
 `--  sys-libs/glibc-2.22  unknown 
   `--  app-misc/pax-utils-1.1.7  (>=app-misc/pax-utils-0.1.10) ~amd64 
   `--  sys-libs/libselinux-2.6  (sys-libs/libselinux) amd64 
   `--  sys-devel/binutils-2.25-r2  (>=sys-devel/binutils-2.24) unknown 
   `--  sys-devel/gcc-5.3.0-r1  (>=sys-devel/gcc-4.4) unknown 
   `--  virtual/os-headers-0  (virtual/os-headers) amd64 
   `--  sys-devel/gnuconfig-20161104  (sys-devel/gnuconfig) ~amd64 
   `--  virtual/pkgconfig-0-r1  (virtual/pkgconfig) unknown 
   `--  sys-libs/timezone-data-2016j  (sys-libs/timezone-data) ~amd64 
   `--  sys-apps/gentoo-functions-0.11  (sys-apps/gentoo-functions) ~amd64 
[ sys-libs/glibc-2.22 stats: packages (10), max depth (1) ]


could it be something with sys-libs/glibc-2.22  ?

**Comment by mitchell-as** [comment]
That sounds unlikely to me. You didn't upgrade glibc inbetween Komodo installs did you?

Please try upgrading to Komodo 10.1.3 first and see if there is still a problem.

If so, the only thing I can think is to backup your profile folder, delete it (or move it somewhere else), and then start Komodo with a perfectly clean profile. (Your profile folder is in `~/.komodoide/10.1`)

**Comment by Naatan** [comment]
He said a clean profile didn't help.

@krizoek you said in your first post that the problem happens on cutting variables, but later on you say it happens in plain text files as well. So the problem happens on ANY test you cut or just specific text?

**Comment by krizoek** [comment]
i ended up using one of my computers with ubuntu, and checking there. it seems the latest version works. and it sais ldd (Ubuntu GLIBC 2.23-0ubuntu5) 2.23

i think it was with all types of cutting, but i tried specifically with having $before the text, but the delay came even with new text file, being plain text
