### ISSUE TITLE
Two bugs in copy & paste within the macro window

### ISSUE THREAD

**Issue by ecterrab** [Komodo/KomodoEdit#226]
I use the Abyss skin in a macintosh (yosemite), set in the preferences as seen here:
![screen shot 2015-04-27 at 3 25 23 pm](https://cloud.githubusercontent.com/assets/12106224/7359305/b79b1686-ecf1-11e4-9b84-6a439ff6cb2b.png)

While following instructions by Nathan to make a macro work, I copy from his email and paste into the macro window, and noticed two bugs: 1) you paste stuff in the macro window but nothing is visible, as if it didn't paste ... but then you move the focus elsewhere by clicking elsewhere, for instance to another tab of the same macro window, and then return to the main macro window and voila! there it is what you pasted before but was invisible. 2) after the contents appear, everything blinks steadily, even when you are doing nothing. All this is only visible in a movie, but github does not allow to attach a small movie. I managed to workaround by artificially adding a termination "JPG" to the movie. So you need to download the file, you can do that by right-clicking the question mark (github cannot render this as an image, of course) then save it as whatever with termination ".mov", and then you can watch all this ( 1) and 2) ) happening.

![bug in copy and paste in macro window mov](https://cloud.githubusercontent.com/assets/12106224/7359331/f6fa2dc6-ecf1-11e4-92b6-99f5fe65de5c.JPG)

**Comment by Defman21** [comment]
The first issue is currently tracking in Issues (I remember this issue)

**Comment by cgchoffman** [comment]
I think this is related to issue #42.

**Comment by Naatan** [comment]
We have a potential fix which will come to a nightly soon. Relevant bug: https://github.com/Komodo/KomodoEdit/issues/71

@ecterrab I really (REALLY) appreciate your help in reporting bugs, believe me it is a huge help and you are awesome for doing it :) May I be as crude though as to ask you to be a bit shorter in your bug reports? Everything you type we have to read and takes away from time we spend fixing bugs/implementing features and also obfuscates the actual problem you're reporting. Simple steps of "this is what I expected" and "this is what actually happened" would be very much appreciated. Thanks! :)

By the way, are you on our forums where I can PM you? I'd like to send you a little something as a token of appreciation for your efforts :)
