### ISSUE TITLE
Komodo returns incorrect [file dirname] value - serious integrity issue

### ISSUE THREAD

**Issue by WheelDogs** [Komodo/KomodoEdit#2265]
### Short Summary
The execution of 'file dirname' returns the name of the Komodo directory instead of the directory in which the script is located.

### Steps to Reproduce
The plugins folder resides in the directory that contains the script being executed.
See attached dir.
The program being test is "main"
"set dir [file join [file dirname [info script]] plugins]"

### Expected results
c:/StarPerformer/Side/sp_editor/plugins

### Actual results
c:\Program Files(x86)/ActiveState Komodo IDE 10/lib/support/tcl/plugins.

### Platform Information

*Komodo IDE 10.1.4 build 89515
 Tcl\Tk 8.6
![komodo file dir issue](https://cloud.githubusercontent.com/assets/21134598/21957781/1eef5eae-da6d-11e6-9b95-918a069ab67c.png)
![komodo file dir issue2](https://cloud.githubusercontent.com/assets/21134598/21957782/24164d7a-da6d-11e6-8039-c15949dac468.png)

*Operating System (and version)? Win 10 

### Additional Information
This suggests a serious integrity issue. Still waiting for K to support the embedded OO in 8.6
 -- eg. Error logs, screenshots, workarounds --

**Comment by WheelDogs** [comment]
Additional screen shot: depicts use of pwd to validate location. It is clearly different than the results from 'file dir'.
![komodo file dir issue3](https://cloud.githubusercontent.com/assets/21134598/21958020/eb6a6510-da71-11e6-8b1b-152c11fe320b.png)

**Comment by mitchell-as** [comment]
Hi, I don't know much about Tcl, but I tried to reproduce this in a simple file and was not able to get Komodo's path to show up. Are you sure something in your script is not causing the problem? Sorry I cannot ask a better question.

![foo](https://cloud.githubusercontent.com/assets/12902397/21989970/0be3ddfc-dbdb-11e6-8204-7819bbad675d.png)

**Comment by Naatan** [comment]
@WheelDogs we now have 3 bug reports for the same issue from you. Please stop reporting new bugs. We'll use this one to track the issue.

**Comment by WheelDogs** [comment]
Hi,

Actually 2 issues: pwd and info script.

Regardless, thanks for taking the time to consider...

Looking at it from the 30,000ft level, guess is this might have something to do with the lack of Komodo support for (or recognition of) the OO commands integrated into tcl 8.6. (That was posted earlier, also. Hoped it would be resolved by now, cause every debug session begins with a warning...regardless if there is a real issue or just invalid (OO) commands)

It is unlikely that you will be able to reproduce using a "simple" script. I can't either.

However, the complete set of code that I am using is available from github - it is ezdit 0.9.3

The examples above are in those scripts. So, they should be easy to find; easy to replicate the issue.

BTW: me thinks exdit would be useful in validating Komodo.

As of this time and without a fix, I will need to implement some hacks...

**Comment by Naatan** [comment]
Unfortunately we will need some sort of test case to investigate this. A big project like the one you linked is not a valid test case as it is well possible that it has some magic going on that are itself the cause of the issue.

Let us know if you figure out steps to reproduce the issue on a smaller scale. Until then we'll continue to track this bug but I don't consider it actionable for the time being. My apologies.

**Comment by WheelDogs** [comment]
Got it! Any time frame on support for the embedded OO?

**Comment by Naatan** [comment]
Likely Komodo 11 or shortly after. We're working on a very large codeintel overhaul that needs to complete before we can implement something like embedded OO.

**Comment by WheelDogs** [comment]
Thanks
