### ISSUE TITLE
"info script" returns incorrect directory

### ISSUE THREAD

**Issue by WheelDogs** [Komodo/KomodoEdit#2267]
### re: #2090. Setting the directory in the application launch UI does not solve the problem and is not practical. If there is another way to bring about consistency between Komodo and the runtime, please advise.

The offered solution may work for a simple, single script; but it doesn't in this instance.

### Steps to Reproduce
Execute the script using Komodo; execute the script from the binary executable

### Expected results
pwd produces the same results.

### Actual results
see attached.

### Platform Information

*Komodo IDE 10.1.4    89515

*Operating System Win10
![kpwd001](https://cloud.githubusercontent.com/assets/21134598/21967608/74dc9908-db58-11e6-83a3-34d295807466.png)

### Additional Information
![kpwd002](https://cloud.githubusercontent.com/assets/21134598/21967609/7eb39e4a-db58-11e6-934c-4bd7b37bab1c.png)
![kpwd003](https://cloud.githubusercontent.com/assets/21134598/21967610/81dbc5ac-db58-11e6-8efb-5801dbd359b9.png)

 -- eg. Error logs, screenshots, workarounds --

**Comment by WheelDogs** [comment]
The first set is from the use of Komodo; the second, from the tcl executable

**Comment by Naatan** [comment]
What are you doing to "execute the script" ?

**Comment by Naatan** [comment]
Closing in favour of 2265
