### ISSUE TITLE
Pop-up panel with changes is not properly displayed

### ISSUE THREAD

**Issue by TorMec** [Komodo/KomodoEdit#2268]
### Short Summary
The pop-up panel opened from the change-bar is not properly displayed if it is higher than the komodo's window (see attachment).

### Steps to Reproduce
1.  Do a sufficiently number of changes
2.  Reduce the high of komodo's window
3.  Click on the change-bar to open the pop-up panel

### Platform Information

*Komodo Edit* 
*Komodo Version 10.1.4* 
*Operating System linux-x86_64* 

### Additional Information

![bug](https://cloud.githubusercontent.com/assets/10964663/21981034/e754a524-dbe5-11e6-8754-dab564675a3f.png)

**Comment by TorMec** [comment]
Maybe similar to #1740 ?

**Comment by Naatan** [comment]
#1740 is correct, thanks for reporting though!
