### ISSUE TITLE
Selected text on Dark theme

### ISSUE THREAD

**Issue by srgloureiro** [Komodo/KomodoEdit#2269]
On Dark theme it is very difficult to discern the selected text, because it is dark gray over dark grey,

**Comment by cgchoffman** [comment]
I always have to change this as well.  I can't see the selected text on any computer I've used.

**Comment by cgchoffman** [comment]
I guess it should be assigned to me since I'm the one who has the issue.

**Comment by Naatan** [comment]
Stealing as I prefer to maintain curation of the color schemes.

**Comment by Naatan** [comment]
This has been addressed in 10.2.
