### ISSUE TITLE
Missing "Preferences - Fast Open", and related functionality in Komodo 9

### ISSUE THREAD

**Issue by ecterrab** [Komodo/KomodoEdit#227]
In the preferences of Komodo 8, there is a page for "Fast Open" as shown in this image:
![screen shot 2015-04-27 at 4 36 48 pm](https://cloud.githubusercontent.com/assets/12106224/7360133/f7773abe-ecfb-11e4-830e-d2292a55e7b5.png)
This Fast open provides great functionality, because I can close Komodo 8, then reopen, then Fast open takes me directly to the last directory I used, it remembers files (history), etc., as shown in the image.

Neither this page nor the corresponding functionality exists in Komodo 9. To be more precise: the preferences page for "File opening" in Komodo 9
![screen shot 2015-04-27 at 4 44 55 pm](https://cloud.githubusercontent.com/assets/12106224/7360219/c7cfbcd6-ecfc-11e4-854d-b657dc1d2836.png)
is actually the page for New Files in Komodo 8:
![screen shot 2015-04-27 at 4 45 34 pm](https://cloud.githubusercontent.com/assets/12106224/7360220/db60b3fe-ecfc-11e4-8e84-773cec6ea7aa.png)
and the functionality itself of Fast open does not appear in the menu File-Open of Komodo 9 (it does in Komodo 8), although it seems to exist in Komodo 9 via shortcut (in Komodo 8 I have it with Command+Shift+O), but it doesn't work, not as in Komodo 8. For example, if you close Komodo 9, then reopen, then try Fast open (via that same shortcut Command+Shift+O), it does not remember the previous directory (it always starts at the root, which is of no use, you know, we do not save programs at the root), and it does not remember previous files. I can attach a movie of this if necessary.

**Comment by cgchoffman** [comment]
Hi @ecterrab, Fast Open is now called Commando and the functionality has only changed in that it was extended essentially Fast Open Anything.  See the release notes for komodo 9.0: http://docs.activestate.com/komodo/9.0/releases/ide.html#whatsnew-9.0

**Comment by ecterrab** [comment]
I suggest you to reopen the issue just rename it: the functionality you are mentioning -definitely- does not work as Fast Open in Komodo 8, regarding what is already explained in the report you are closing. 

Now, Fast open of files is one of the things I use the most. All the time. Fast Open in K8 not only remembers the last directory it opened (so that I close Komodo, then reopen next day and continue opening files in my working directory of the previous day) but also has a history of files opened even if they are not in that working directory. Nothing of this works in Commando in K9. 

The lack of previously existing functionality plus the fact that Commando in K9 opens at the root, so that you need to do many clicks and typing in order to arrive at the file you want to open renders the functionality close to useless: It is equivalent if not faster to open files directly using the OS file browser that launches via File Open.

All in all, this is relevant functionality. Could it please be restored? Thanks.

**Comment by cgchoffman** [comment]
@ecterrab from the original report it is unclear what you're reporting, other than "it doesn't work how it used to work".  You mention 3 preferences pages.  2 of them are not related.  New files(k8) and Opening Files(k9) are not related to Fast Open(k8), Commando(k9).  

If you look at the preferences for Commando you will see the options you want: Preserver Previous Search..., Relative Paths use the current file's dir...  Those should get you the functionality you need.  For example, if I have a file open and I open Commando, the context is the containing directory of the file that has focus.  If there is no file open, the context is the root dir of the project.  

Also note that if you simply start typing a filename, regardless of how deeply buried in your project it is, if it is unique, Commando will serve it up for you to select.  It's actually insanely convenient.

Please watch the screencast @Naatan made for commando.  If you still think there is a bug or an enhancement to be made please file a different bug that specifically says the issues.  
http://komodoide.com/blog/going-commando-with-komodo-yes-you-ll-be-back/

So far, there is no bug as far as I can tell as all the functionality you mention does exist in Commando.  If you have more question about commando please ask us in the forums and we'll help you get it sorted out: http://forum.komodoide.com/

**Comment by ecterrab** [comment]
@cgchoffman true: I didn't read the advertisement of commando before writing this report. The functionality I mentioned above is: 

1) Do a Fast open in a directory, Close Komodo, Open Komodo, do another Fast open. Expected: I'd say as in K8, so that the second Fast Open opens in the same directory where the first Fast Open got closed. Received: no it doesn't. The issue: we typically close the editor, then reopen and intend to work on the same working directory as the day before. NOTE: checking "Preserve Previous Search Query" does not help at all regarding this issue - the second Fast Open mentioned starts again at the root. 

2) Checking "Relative paths use the current file's directory" does not work as you are saying. You have some file in focus, you launch Fast Open in K9 and the search again starts at the root. It is true that I do not have a "Project" set, but how is that relevant in this issue?

3) in K8, you start typing a file, and if it is present *in the directory you are*, by pressing tab you complete the name, as in any UNIX shell. This doesn't work in commando in K9, where you get a ton of matches from subdirectories that are not my working directory, and pressing tab is of no help to produce autocomplete. Look, this functionality is not the useful one; at least provide an option to restrict the search not including any of the subdirectories.

4) in K8, when you launch Fast Open, you see a history of previously opened files separated (lower part of the window) even if they are not present in the current directory being listed. This is very useful. We typically come back to work on files we have worked previously. In K9, this 'history' is not present.

Whether all these things are just bugs, something to adjust in the implementation as opposed to a new design that removed some previously existing functionality, I cannot tell. In any case, Carey, I'm not looking for a debate here. I am only giving you my impression after working tons of hours with Komodo 8 and using Fast Open, and after trying to recover in Komodo 9 that useful functionality. I realize there are more features in Commando than those in Fast Open in K8, mainly that you generalized the concept to other things (not just files) but the features that are useful for files (itemized above), implemented in the go-tool in Komodo 8, seem to be missing in Commando in Komodo 9, this is a fact, or at least it is not obvious how to emulate them, and I think that for files these K8 Fast-Open features are more relevant than the new functionality that command provides: with Fast Open you want to access your working material as directly as possible. In K8 go-tool that works almost impeccable, but not as well in K9 commando (I mean the items above).

**Comment by cgchoffman** [comment]
@ecterrab If you have question about how to use Commando, the appropriate place for those question is in the forums.  If you search there you may even find answer to your question.  Also, go tool implementation is still there.  You can save favourites by pressing Right arrow on a folder then select "Favourite".

Please continue discussion in the forums.
