### ISSUE TITLE
Selecting Framework in Unittest wizard moves the window

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#2273]
### Short Summary

title.

### Steps to Reproduce

1. Open the "Create Unittest Config" window.
2. Move it somewhere.
3. Open the framework menu.

### Expected results

The window don't move.

### Actual results

The window moves.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.2
*Operating System (and version)?* elementary OS 0.4

**Comment by Naatan** [comment]
Thanks for reporting :)

**Comment by jack17529** [comment]
can someone explain in detail?

**Comment by Defman21** [comment]
There's nothing you can fix: it's an IDE only bug.

**Comment by cgchoffman** [comment]
> can someone explain in detail?

What do you need explained exactly?  The report is specific enough.  Are you indeed asking how to fix it as @Defman21 thinks?

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoEdit/commit/47a0f7d5ca83e5ee47427ccb5a4b2dce186dd7e8
