### ISSUE TITLE
Unexpected Error while saving a html file

### ISSUE THREAD

**Issue by akhilpuri24** [Komodo/KomodoEdit#2277]
### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?*

**Comment by mitchell-as** [comment]
It is impossible for us to figure out what is going wrong without any information. I'm going to guess it's a file encoding issue. If your file is UTF-8-encoded, please ensure you don't have any invalid UTF-8 characters in it (e.g. latin1, cyrillic, etc.)

**Comment by Defman21** [comment]
UTF8 allows cyrillic characters.

**Comment by mitchell-as** [comment]
Yes, you're right. I meant cyrillic code page (Windows). Sorry for any confusion.
