### ISSUE TITLE
Vertical scroll hard to see  (Enhancement)

### ISSUE THREAD

**Issue by jimzag** [Komodo/KomodoEdit#2278]
### Short Summary
Sometime I struggle to find the vertical cursor due to the color being so close to the color of the vertical slider background, and also close in color to the default black editor background.  This is particularly a problem when editing a file with 1000+ lines of code because the slider is rather small at that point.

The attached screenshot is really a 'best case'.  If I took a picture of the monitor with a camera, you could see that just a little reflected light from the screen obliterates the difference between the background and the slider.

I really like the editing environment, colors, etc.  Just a little more contrast for the slider will help.

### Steps to Reproduce
screenshot attached

### Platform Information
Komodo IDE 10.1.4
![vert-scroll-hard-to-see](https://cloud.githubusercontent.com/assets/5787294/22177654/1ca16b64-dff0-11e6-8f39-93d12b47fcf1.jpg)

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?*

**Comment by Naatan** [comment]
Thanks for reporting. This is being tracked here - https://github.com/Komodo/KomodoEdit/issues/1802
