### ISSUE TITLE
HTML auto-completion not working properly inside PHP

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#2281]
I'm currently working on a mail-view only my html auto completion is not working properly.
I want to insert a table, but the auto completion is not showing the the table as option.

![2017-01-25 15_04_15-brochuremail](https://cloud.githubusercontent.com/assets/3530262/22293368/96fe7f9c-e30f-11e6-9c63-9466d2602c06.png)

If I move to the end of the document it does give me auto completion for the table tag:

![2017-01-25 15_05_41-brochuremail](https://cloud.githubusercontent.com/assets/3530262/22293434/c8f6cda6-e30f-11e6-8424-a3bcc61e0f39.png)

It looks like it can't handle the mix of php and html.
If I type a closing tag on the position where i want the table tag, it is giving me a auto-completion for closing a span tag ( until infinity )

![2017-01-25 15_12_32-brochuremail](https://cloud.githubusercontent.com/assets/3530262/22293722/fb0ec63a-e310-11e6-9b94-9ebda933fc26.png)

![2017-01-25 15_14_52-brochuremail](https://cloud.githubusercontent.com/assets/3530262/22293746/0f20a65c-e311-11e6-9938-736c31e035bb.png)

### Expected results
Getting the correct auto completion options

### Platform Information

Windows 10 Komodo IDE, version 10.1.4

### Additional Information
The code:
```php
<? $company_colors = array(
	603	 	=> '#0074ce',
	609		=> '#16603D',
	610		=> '#13498C',
	611		=> '#397BAA',
	612		=> '#02526E',
	613		=> '#768243',
);
?>

<? if(!empty($company)): ?>
	<? $logo = EO::app()->getBaseUrl(true) . '/public/images/layout/logo-'. $company . '.jpg' ?>
	<? $color = $company_colors[$company]; ?>
	<span style="font-family: 'Helvetica', 'Arial', 'Verdana', sans-serif; font-size: 12px; color: #333; line-height: 22px;">
		<h2 style="color: <?= $color; ?>;">
			Bedankt voor het downloaden van onze brochure
		</h2>
		Bedankt voor het downloaden van onze brochure. Hierbij ontvang je de <a style="color: <?= $color; ?>;" href="<?= EO::app()->urlTypeAbsolute('site/website-page/view-brochure') ?>">link</a> zodat je de brochure vaker kunt bekijken.<br />
		<br />
		Heel veel leesplezier en hopelijk tot ziens bij <?= EO::app()->name; ?>!
		<br /><br />
		<img src="<?= $logo; ?>" alt="<?= EO::app()->name; ?>"/>
	</span>
<? endif; ?>

```

**Comment by mitchell-as** [comment]
How strange. Thanks for reporting.

**Comment by onnlinetool** [comment]
Downloaden Downloaden Downloaden Downloaden Downloaden Downloaden Downloaden 

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

**Comment by mitchell-as** [comment]
This has been fixed in Komodo 11.
