### ISSUE TITLE
Komodo Edit deletes text when saving a document

### ISSUE THREAD

**Issue by pturley0** [Komodo/KomodoEdit#2285]
### Short Summary

With a document of a specific form, and certain preference settings, Komodo Edit will delete text when saving the document.

### Steps to Reproduce

1. In Preferences -> File Saving, turn on "Clean trailing whitespace and EOL markers."
1. Create a new document.
1. Under Edit -> Current File Preferences..., make sure the encoding is UTF-8.
1. Create a document with the following contents (also see attached):
    ```
    •••␌A

    •••ABCD

    ```
1. In this document, the first and last lines are blank, as is the one in the middle. Each '•' is a space, and the 'FF' glyph is the form feed character (0x0c), which I originally encountered in a GPL license.
1. Put your cursor on the *last* line.
1. Save the document. It doesn't matter whether you put an extension on it.

### Expected results

Komodo Edit saves my document exactly as shown.

### Actual results

Komodo Edit chops the 'BCD' from the penultimate line before saving the file:

```
•••␌A

•••A

```

### Platform Information

*Komodo Edit*
*Komodo Edit, version 10.2.0-alpha1, build 17637, platform macosx. Built on Wed Jan 25 09:00:15 2017.*
*macOS Sierra Version 10.12.13*

**Comment by pturley0** [comment]
[test-file.txt](https://github.com/Komodo/KomodoEdit/files/733336/test-file.txt)

**Comment by pturley0** [comment]
I've attached the test file described by this issue.

**Comment by pturley0** [comment]
[movie.mov.zip](https://github.com/Komodo/KomodoEdit/files/733350/movie.mov.zip)

**Comment by pturley0** [comment]
I've attached a movie that demonstrates the problem.

**Comment by mitchell-as** [comment]
Thank you for the report and for the test file. Reproduced.

**Comment by mitchell-as** [comment]
Note to self: this only happens when there are form feed characters in the buffer. Python thinks they are line separators, but Scintilla does not. koDocument.py's `lines = text.splitlines(True)` (around line 1446) needs to be changed to split lines by `\r\n|\n`, capture the line end, and construct `lines` appropriately.
