### ISSUE TITLE
Python3 syntax error underline when using file kwarg in print function

### ISSUE THREAD

**Issue by mwaltec** [Komodo/KomodoEdit#2288]
### Short Summary
When using Python3, Komodo IDE erroneously red underlines (syntax error) the print function if the developer uses the function's "file" keyword argument.

### Steps to Reproduce
In the editor:

`import sys`
`print("Trouble happened.", file=sys.stderr)`

### Expected results
The syntax of the above statement is correct and should not result in Komodo IDE red underlining the line.

### Actual results
Komodo IDE red underlines the line.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.1.4 build 89515
*Operating System (and version)?* Windows 7 x64

**Comment by Defman21** [comment]
Python3 does not give me any warnings while Python does. Make sure you've picked the right language for your file.

**Comment by mwaltec** [comment]
That was it. I could have sworn I created that file from Python3 template. Regardless, that did solve the problem. Thank you very much.
