### ISSUE TITLE
GoTo Anything does not work anymore in KomodoIDE alpha1 10.2.0

### ISSUE THREAD

**Issue by hoppfrosch** [Komodo/KomodoEdit#2294]
### Short Summary
GoTo Anything does not work anymore in Komodo IDE, version 10.2.0-alpha1, build 89795, platform win32-x86.
Built on Fri Jan 27 01:00:30 2017.

### Steps to Reproduce

Pressing hotkey for GotoAnything  results in the following: [see Image](http://i.imgur.com/TmnPi4a.png) (this is also the result, when mpues-clicking into GoToAnything Box)
* The list with the scopes does not appear anymore
* entering anything - nothing happens

### Expected results
GoTo Anything shoul work

### Platform Information
Komodo IDE, version 10.2.0-alpha1, build 89795, platform win32-x86.  Built on Fri Jan 27 01:00:30 2017.
Win7 Ultimate 64bit

**Comment by Defman21** [comment]
#2292

**Comment by cgchoffman** [comment]
@hoppfrosch *Help > Check for Updates* or http://downloads.activestate.com/Komodo/nightly/komodoide/latest-10.2.0/.  Should be working in that build.  Thanks for using the alpha builds btw.
