### ISSUE TITLE
Shift + Del key combination does not cut selected text but delets it

### ISSUE THREAD

**Issue by jovo-** [Komodo/KomodoEdit#2297]
### Short Summary
Shift + Del key combination should cut selected text as Ctrl + X.

### Steps to Reproduce
Select string of text & press Shift + Del key combantion.

### Expected results
Komo editor should cut selected text & put it in buffer.

### Actual results
Selected text is deleted.

### Platform Information
Komodo Edit, version 10.1.4, build 17456, platform linux-x86_64. Built on Fri Dec 16 18:34:05 2016.
openSUSE Leap 42.2

**Comment by Defman21** [comment]
You can change this keybinding to Cut in Preferences - Key bindings.

**Comment by cgchoffman** [comment]
Works for me and it's in the [default bindings](https://github.com/Komodo/KomodoEdit/blob/master/src/schemes/Default.p.kkf#L75).  What keybinding scheme are you using? `Prefs > Keybindings`

**Comment by Naatan** [comment]
@cgchoffman he wants it to cut, not delete.

This is working as intended though, the proper solution is what @Defman21 said. Shift+delete is meant to delete the line.
