### ISSUE TITLE
Update "Komodo Bugzilla database" pharse

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#23]
This button refers to the Issues and not to the Bugzilla anymore but it's still have a bad description. (I think `alt` tag) (the button available under `View - Toolbars - Customize... - Komodo Resources Toolbar`)

**Comment by Naatan** [comment]
Fixed - in https://github.com/Komodo/KomodoEdit/commit/8e5f594a927185f3a284f5f07d425e2d469ca254

Thanks Defman

**Comment by Defman21** [comment]
It's not what I meant. I meant this: https://github.com/Komodo/KomodoEdit/blob/9.0.0c1/src/chrome/komodo/locale/en-US/komodo.dtd#L385

**Comment by Naatan** [comment]
Seems I integrated the commit wrongly, want to do a PR on that Defman?

**Comment by Defman21** [comment]
Okay!

**Comment by srgloureiro** [comment]
What will you do with your old Bugzilla issues database? I think there was valuable information inside. Any plans to import its tickets to here? It would be nice.

**Comment by Defman21** [comment]
I sure Komodo devs will remove ability to create new issues in Bugzilla.

**Comment by Naatan** [comment]
We made a conscious decision not to import those issues as they have become very unwieldy over time. We still reference bugzilla for our milestones and will continue to do so for a while, but the switch to github is meant to  be a clean slate. If you had issues on Bugzilla that you are concerned will fall off of the radar please feel free to open them again on github.

The ability to create new issues on bugzilla has already been removed.
