### ISSUE TITLE
Add files to project not working

### ISSUE THREAD

**Issue by vladisslav** [Komodo/KomodoEdit#230]
Komodo IDE, version 9.0.1, build 87208, platform win32-x86. Built on Thu Apr 16 
I have a project but can't add files. See screenshot:
![komodo2](https://cloud.githubusercontent.com/assets/7721913/7372970/85677e2a-edd2-11e4-80ba-fcb420c387de.png)

**Comment by cgchoffman** [comment]
You have to open the project @vladisslav.
