### ISSUE TITLE
Colors set in the Color scheme editor are not correctly applied to the editor

### ISSUE THREAD

**Issue by hoppfrosch** [Komodo/KomodoEdit#2300]
I modified my color scheme:
* "_Brace Highlight_" - _OLD:_ Yellow (FG) on Darkgreen (BG) ---> _NEW_: Darkgreen (FG) on LightGreen (BG)

**BUG**: Within the preview window of color scheme editor the colors are displayed correctly - but within the editor the color are not displayed correctly ----> [see image](http://i.imgur.com/AsmdBa7.png)

I even restarted KomodoIDE - the result was the same: the colors of Highlighted brace pairs are still displayed incorrectly.

The same issue is valid for the color setting "_Brace: No-Match_"

**Comment by Naatan** [comment]
Hi @hoppfrosch, I very much appreciate your taking the time to report these! But would you mind reporting each issue in a separate github issue? We cannot reliably track multiple issues in one report.

Thank you

**Comment by Naatan** [comment]
To the point of your first issue - can you explain your exact steps for modifying the brace colors? I'm primarily interested in how you applied the color scheme.

**Comment by hoppfrosch** [comment]
I put those three issues together, as they seem to be just three aspect of  one problem:  Color Scheme editor does not behave well 

But as requested, I splitted this issue into #2300, #2305 & #2306

**Comment by Naatan** [comment]
Thanks @hoppfrosch, please see https://github.com/Komodo/KomodoEdit/issues/2300#issuecomment-277004212

**Comment by hoppfrosch** [comment]
@Naatan : I did nothing special. I already had a customized color scheme which worked until now. I just opened the Color Scheme Editor, selected the corresponding entry ("_Brace Highlight_") and selected the foreground and background color. I had a look on preview and changed the values to my liking. The I pressed "_Apply_" button. 
As I saw no effect, I restarted Komodo to look whether the desired settings are applied - without success.

My modified color scheme is based on "Classic" and contains beneath some color settings some CSS-modifications (which I didn't change in the step above).

If you tell me the steps how to do - I can sent you my color scheme ...

**Comment by Naatan** [comment]
When you pressed Apply did you check the "Editor" checkbox?

**Comment by Naatan** [comment]
I believe you should be able to share your color scheme on here, just rename it to .txt and drag it on the comment area. It's located in the schemes folder inside your [profile folder](http://docs.komodoide.com/Troubleshooting/Where-does-Komodo-keep-settings-data).

**Comment by hoppfrosch** [comment]
> When you pressed Apply did you check the "Editor" checkbox?
Yes I did - but nothing happend. (As I already reported a bug about "Non working apply button when changing Tab settings" some time ago, I assumed this might be the same behaviour ...)

I'll share my color scheme tomorrow as my workday is already over and I'm relaxing at home  :-)

**Comment by Naatan** [comment]
Sounds good, enjoy your evening :)

**Comment by hoppfrosch** [comment]
Here's my scheme: [Classic_JOK.ksf.txt](https://github.com/Komodo/KomodoEdit/files/749652/Classic_JOK.ksf.txt)

**Comment by hoppfrosch** [comment]
Sorry - my failure ... I changed the colors only within the "General" Editor color settings - and not within the language specific color settings .... (as I saw looking into my color scheme ...)

Consider this issue as invalid. ;-)
