### ISSUE TITLE
KOMODO IDE 10.1 on Windows 10 crashing

### ISSUE THREAD

**Issue by sachsg** [Komodo/KomodoEdit#2302]
On occasion KOMODO crashes/stops working and have to close the session. It appears to happen when re-entering the KOMODO window after do other activities in other windows.

### Steps to Reproduce

It is erratic and thus cannot be reproduced at will.

### Expected results

![20170202-komodo-crash-1](https://cloud.githubusercontent.com/assets/25506098/22550791/0c4e2446-e90f-11e6-95a4-572f0031f6bc.png)
![20170202-komodo-crash-1](https://cloud.githubusercontent.com/assets/25506098/22550803/20f1b58e-e90f-11e6-8315-655bb3907a2c.png)

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?*Komodo IDE, version 10.1.4, build 89515, platform win32-x86.
Built on Fri Dec 16 10:34:21 2016.
*Operating System (and version)?*  WINDOWS 10 (1607.14393.693) x64

### Additional Information

 

[KOMODO-10.1-20170202-Crash-1.zip](https://github.com/Komodo/KomodoEdit/files/747778/KOMODO-10.1-20170202-Crash-1.zip)

**Comment by mitchell-as** [comment]
@Naatan I see a lot of bugsnag notifications in the pystdout.log file. Is it possible to figure out what those are? It seems that the last one got cut off during the crash. I wonder if they're relevant.

**Comment by Naatan** [comment]
Bugsnag is for aggregation, it will report the same errors you see in pystderr.log, so it could tell you things like how many people get a certain error, on what platform, what version, etc.

I don't think it could help you here.

@sachsg do you get a crash reporting dialog when the crash happens?

**Comment by sachsg** [comment]
@Naatan I just have received that "KOMODO has stopped working" pop-up...

**Comment by Naatan** [comment]
Does Komodo itself remain open?

**Comment by sachsg** [comment]
no, if I click the close program....

**Comment by Naatan** [comment]
ok, if you press the X to close the window (top right in the titlebar), does Komodo remain open/functional?

**Comment by sachsg** [comment]
sorry have not tried that yet... and thus far today, I have not had any issues...
Also, I did do a rebuild of my codeintel from the troubleshooting menu yesterday...

**Comment by Naatan** [comment]
Please try that next time that happens.

Any crashes since rebuilding codeintel?

**Comment by sachsg** [comment]
no crashes since the rebuild...
And will try clicking the "x"

Thanks and have a good weekend...

**Comment by sachsg** [comment]
So far no re-occurrences of the issue since rebuilding.

**Comment by Naatan** [comment]
Thanks for reporting back @sachsg :)
