### ISSUE TITLE
Symbol color does not match selected colors in Color Scheme Editor 

### ISSUE THREAD

**Issue by hoppfrosch** [Komodo/KomodoEdit#2305]
### Short Summary
Split from  #2300   - see also Komodo/KomodoEdit#2300 and Komodo/KomodoEdit#2306

Have a look here:
![komodo_2017-02-02_11-25-00](https://cloud.githubusercontent.com/assets/419075/22583191/5227b73e-e9eb-11e6-916c-6f118a9205e7.png)

As you see I've selected for "_Brace: No match_" Red (FG) on LightRed (BG) - this is displayed correctly in the preview window 

**BUG:** The symbol for "Brace: No match" does not show the same colors! (it uses my old setting).

### Platform Information
Komodo IDE, version 10.2.0-alpha1, build 89798, platform win32-x86. Built on Tue Jan 31 01:00:32 2017.
Win7 Ultimate 64bit
 
I cannot say, whether these issues are present in previous versions of Komodo - but likely they are ....

**Comment by Naatan** [comment]
Are they correct when you move the selection off of the item?

**Comment by hoppfrosch** [comment]
No - moving the selection results in the effect as posted in #2306

**Comment by Naatan** [comment]
Ok, I'll wait for you to share your color scheme on the other bug, as I cannot reproduce it.

**Comment by hoppfrosch** [comment]
[Uploaded color scheme](https://github.com/Komodo/KomodoEdit/issues/2300#issuecomment-277169463)

**Comment by hoppfrosch** [comment]
I found some system:
The issue above is only valid immediately after changing the FG/BG colours (changed FG to light blue and BG to blue)
![komodo_2017-02-03_08-24-37](https://cloud.githubusercontent.com/assets/419075/22582925/39b36fd2-e9ea-11e6-814e-bcedd6d726bf.png)

After closing and reopening the Color scheme editor it looks like this:
![komodo_2017-02-03_08-26-36](https://cloud.githubusercontent.com/assets/419075/22582999/81bfd888-e9ea-11e6-98aa-8f8aa0797888.png)

This seems to be related to #2306: I think after pressing the apply button, you do not apply the new color settings to the symbol but to the text beneath the symbol .... Opening the Color Scheme editor you correctly apply the color to the  selected colors to the corresponding symbols ...

**Comment by Naatan** [comment]
Awesome, thanks for doing some digging @hoppfrosch!

**Comment by Defman21** [comment]
#1925?

**Comment by cgchoffman** [comment]
Agreed with @Defman21.
