### ISSUE TITLE
Inconsistent display of selected colors in Color Scheme editor

### ISSUE THREAD

**Issue by hoppfrosch** [Komodo/KomodoEdit#2306]
### Short Summary

Split from #2300 - see also #2300 and #2305

Have a look here:
![komodo_2017-02-02_11-34-07](https://cloud.githubusercontent.com/assets/419075/22583368/5d882e32-e9ec-11e6-8d04-9a54513d4f4c.png)

**BUG:** Why is the text of "_Brace: No Match_" displayed with the selected colors (Red on LightRed) - whereas the text of "_Brace: Highlight_" is displayed with simple "Black on White" (but here the symbol colors are correct ....)?

------------

### Platform Information

Komodo IDE, version 10.2.0-alpha1, build 89798, platform win32-x86. Built on Tue Jan 31 01:00:32 2017.
Win7 Ultimate 64bit
 
I cannot say, whether these issues are present in previous versions of Komodo - but likely they are ....

**Comment by Naatan** [comment]
Can't quite tell from your color scheme - are you selecting the "Brace Highlight" entry in your screenshot? The color would be from the highlight.

**Comment by hoppfrosch** [comment]
No - nothing was selected (selecting results in a dark (blue or black backgriund)

**Comment by hoppfrosch** [comment]
[Uploaded color scheme](https://github.com/Komodo/KomodoEdit/issues/2300#issuecomment-277169463)

**Comment by hoppfrosch** [comment]
I think I found a reason for this behaviour: See https://github.com/Komodo/KomodoEdit/issues/2305#issuecomment-277182490

**Comment by Naatan** [comment]
Thanks @hoppfrosch, we'll track this in #2305 then :)
