### ISSUE TITLE
"Save as" in split view

### ISSUE THREAD

**Issue by jcloggins** [Komodo/KomodoEdit#231]
When creating a new file by using "Save as" while the original file is in "split view" does not result in editing two different files.

Example:

open file xyz.pl and then split view
on one of the views "Save as" zyx.pl
note that changes to the view showing zyx.pl are reflected in the view showing xyz.pl

So far, the only way I have found to totally separate the files is to close the view showing one file or the other and then reopen it in a new view

**Comment by jcloggins** [comment]
In the scenario for this issue - saving the xyz.pl view will save the changes made to zyx.pl to the xyz.pl file.

I'm personally inclined to call a situation in which changes to one file can result in unintended changes to a different file qualifies as a bug rather than an enhancement.

**Comment by Naatan** [comment]
Reverted these fixes as this is not a bug, it's a feature. Being able to edit the same file in a split is intentional. It's so you can edit two places in that same file at the same time.

**Comment by th3coop** [comment]
The wording in the PRs is a little confusing.  It had me second guessing what's going on.  The commit prevented a third instances of a file being opened in a splitview.  You can have side by side instances of the same file in splitview, but if you "Move to splitview" one of those instances, it will simply open the instance in the adjacent view.  Re-reverting.
