### ISSUE TITLE
Error reporting in testing using IDE is different from running in wish

### ISSUE THREAD

**Issue by WheelDogs** [Komodo/KomodoEdit#2311]
### Short Summary
Komodo consistently provides stack and error info that seems to have little to do with the actual error; whereas the error reported when not using Komodo is exact.

What Komodo reports below is typical. Most often, the only way I can determine the actual cause is to use Komodo to step through the scripts; or actually run it directly in wish.

In addition, stack trace often reports: "null, line 1, in "

What the heck does that mean...
### Expected results
can't read "scriptFile": no such variable
can't read "scriptFile": no such variable
    while executing
"runtimeError "Script executable $scriptFile not found!""
    (procedure "loadScript" line 56)
    invoked from within
"loadScript $next(ScriptFileName)"
    (procedure "::SIMX::doNextScript" line 29)
    invoked from within
"::SIMX::doNextScript"
    (command bound to event)

### Actual results
Tcl bug: unexpected stack trace in "unknown"
wrong # args: should be "info functions ?pattern?"
    while executing
"DbgNub_infoCmd function bgerror -type -name -args"
    ("uplevel" body line 1)
    invoked from within
"DbgNub_uplevelCmd DbgNub_infoCmd $args"
    invoked from within
"info function bgerror -type -name -args"
    ("uplevel" body line 1)
    invoked from within
"DbgNub_uplevelCmd \#$level [list info function $namex -type -name -args]"

### Platform Information

*Komodo IDE 
*Komodo Version 10.1.4 build 89515
*Operating System (and version)?* 

### Additional Information

[2017-02-02 16:36:18,848] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2017-02-02 16:36:21,394] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2017-02-02 16:36:21,394] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2017-02-02 16:36:21,410] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
[2017-02-02 16:36:23,003] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010/lib/mozilla/components/koamAddonManager.js:138
[2017-02-02 18:13:42,766] [WARNING] views: Inconsistent view count in view_closed event
[2017-02-02 18:13:42,953] [WARNING] views: Inconsistent view count in view_opened event
[2017-02-02 18:14:07,641] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in

**Comment by WheelDogs** [comment]
Win7 and Win10 is the OS

**Comment by cgchoffman** [comment]
Please provide a file of sample code as well for reproducing the issue.

**Comment by Naatan** [comment]
Seeing as we're replacing the unit testing implementation in its entirety for 10.2 we will not be "fixing" this one, as it won't concern 10.2 and beyond. I'd recommend you give the Komodo 10.2 pre-release a try > http://community.komodoide.com/t/komodo-10-2-pre-release-now-available/3329/1

**Comment by WheelDogs** [comment]
Super...will do...

 

My other ‘wish’ would be for Komodo to ignore OO commands and not report as invalid. I understand the mods for OO aren’t in the bag for 10 or 11. However, elimination of this “false” notification also eliminates the need to ‘ignore’ it. Not good cause I never code it correctly the first time .  At least, if this notification is not issued for OO, then I know there is a real error.

 

I hope that makes sense...??

 

Rick

**Comment by Naatan** [comment]
> I hope that makes sense...??

Not really. Could you open a new bug report and elaborate? Screenshot would be helpful.

**Comment by WheelDogs** [comment]
Have reported the issue.

 

Komodo regard any of the tk 8.6 OO commands\structures as invalid. 

 

i.e. Komodo informs then prompts for you to run or not run.

 

“The current buffer contains syntax errors. Are you sure you want to continue debugging.”

 

 

So, if my code actually has an error that would  invoke this type of a prompt, how would I know whether it is really my error or Komodo false reporting?

 

Ordinarily, if I saw that message, I wouldn’t execute the script – I would try to find the error. However, because I use OOtcl, I get the notification every time.

 

I was told that the fix might be awhile.

 

 

Thus, it would be great is the notification would be suppressed until the time Komodo supports the tk OO commands.

**Comment by Naatan** [comment]
Please respond to the ticket in question. This ticket is not about Tcl OO.

Also, please don't use email to respond to tickets, github is really bad at interpreting emails and tends to leak personal information that way.

**Comment by WheelDogs** [comment]
No it's not about tclOO. It's about Komodo not recognizing tclOO commands as valid commands.
So when one goes to test one gets the message:

“The current buffer contains syntax errors. Are you sure you want to continue debugging.”

So construct what ever script is easy, include tclOO commands and you will see the messages.

The point is: how would someone know that there really was an error when Komodo indicates an errant condition when, according to the docs, there isn't one.

So, this was confirmed and I was told the integration of OO is too substantial for it to happen in the near term. In that case, it would be good to get a release of K that ignored the OO commands.

**Comment by Naatan** [comment]
@WheelDogs I appreciate that you want to get this resolved but I've asked you multiple times now to open a new bug for this. I'm closing this one permanently, this is not the right bug report to discuss your issue.
