### ISSUE TITLE
"Change Team" reports "Failed Authentication" so you have to redo your share.

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2314]
I thought this was working correctly but it's not.  When you click `Change Team` in the Slack share dialog it will open the Slack login window and get you to re-authorize.  WHen that completes the same Share dialog should be open but a new channels list loaded.

Right now the dialog closes and an "Authentication Failed" notification appears at the bottom of the screen.

**Comment by Naatan** [comment]
Can no longer reproduce.

**Comment by mjainQA** [comment]
Verified on 10.2.2 RC 3 on macOS.

Added a test case - http://testrail.activestate.com/testrail/index.php?/cases/view/176
