### ISSUE TITLE
Inserts tab, allthough it should insert spaces.

### ISSUE THREAD

**Issue by rovf** [Komodo/KomodoEdit#2315]
### Short Summary

I have set the file preferences so that spaces should be inserted instead of tabs.

### Steps to Reproduce

Open a file, which already has hard tabs. Convert these tabs to spaces. Ensure that the file preferences for this file say that spaces should be inserted instead of tabs. Go to some existing line and hit the tab key.

### Expected results

Spaces being inserted.

### Actual results

A hard tab being inserted.

### Platform Information

*Komodo Edit* 
*Version 9.3* 
*Windows 7* 

### Additional Information
![capture_20170206_174417](https://cloud.githubusercontent.com/assets/6795665/22656853/e1c4863c-ec94-11e6-9f59-6134b719e5af.jpg)
![capture_20170206_174500](https://cloud.githubusercontent.com/assets/6795665/22656855/e4a24614-ec94-11e6-8761-6a3de36153b2.jpg)

See screenshots. First screenshot shows the settings for this file. Tab should insert 2 spaces. Second screenshot shows excerpt of the editing area after hitting the tab key. The grey arrow indicates that a real tab has been entered.

**Comment by Naatan** [comment]
This is fixed in Komodo 10.1.4, please consider upgrading.
