### ISSUE TITLE
OS X autosuggestion FullScreen error

### ISSUE THREAD

**Issue by uziel200** [Komodo/KomodoEdit#232]
When Komodo is open in Mac OS X in Full Screen and when is typing code, and the Autocomplete appears, the Screen go back to the Desktop.

This make very uncomfortable to write code en the new version.

 Komodo Edit, version 9.0.1, build 15745, platform macosx. Built on Mon Apr 20 17:19:25 2015.
OS X: Yosemite 10.10.3

**Comment by cgchoffman** [comment]
Hi @uziel200, was it working for you in Komodo 9.0.0?

**Comment by uziel200** [comment]
Hi @cgchoffman, yes it works well in Komodo 9.0.0

**Comment by cgchoffman** [comment]
Good news, Hopefully a quick fix then.  Thanks for updating @uziel200.  Aim for 9.1 pending review of issue.

**Comment by uziel200** [comment]
@cgchoffman thks a lot for your time!

**Comment by Naatan** [comment]
I cannot reproduce this. Please see if the 9.3 nightly fixes this issue for you:

http://komodoide.com/download/#preview
