### ISSUE TITLE
Komodo fails to respect breakpoints and reports erroneous error infomation when Iwidgets are used.

### ISSUE THREAD

**Issue by WheelDogs** [Komodo/KomodoEdit#2321]
### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?*

**Comment by mitchell-as** [comment]
Closing the incomplete ticket.

**Comment by WheelDogs** [comment]
Big mistake...The is symptomatic of a serious design problem.

 

Instead, it would probably serve the product and the community better if this was bumped up to a design engineer.

**Comment by Naatan** [comment]
@WheelDogs you provided no details. The ticket was closed because it's not actionable, not because we disagree with something. Please fill out the fields requested when reporting a bug.
