### ISSUE TITLE
Komodo Edit throws exception when closing a tab

### ISSUE THREAD

**Issue by rovf** [Komodo/KomodoEdit#2325]
### Short Summary

Closing tabs is not possible.

### Steps to Reproduce

Open some files.

Click on the X on a tab to close it.
Alternatively use File/Close/CurrentFile

### Expected results

The tab should disappear

### Actual results

If clicking the close button on the Tab, nothing happens.

If I use the menu File/Close/CurrentFile, an exception flashes for a short time (about 2-3 seconds). It is displayed near the top right corner, replacing the field "Go To Anything".  The exception says:

   [Exception ... "[Java Script E ... :: and line 272" data: yes]

### Platform Information

*Komodo Edit 10.1.4* 
*MacOS Sierra 10.12.2* 

### Additional Information

- No screenshot possible.
- "Close Other Files" shows the same error
- Shutting down KomodoEdit (File/Quit) does not show any error.
- When starting KomodoEdit again, I get a message that the application was not shut down properly the last time it was opened, and offered me to restore the session, which I accepted.
- After this, closing the tabs worked flawlessly!

**Comment by mitchell-as** [comment]
Hi @rovf, thanks for the report. Can you reliably reproduce this problem? If so, please send the contents of your Help > Troubleshooting > View Log File. That would be of great help. The exception you mentioned sadly is not indicative of the problem.

**Comment by babobski** [comment]
Just for the information, I had this bug a few times. I was unable to close any file but without an exception.
Rebooting Komodo fixed it for me. If it happens again I will see if I can get some more information.
This bug for me is new in 10.1.4 I think I hit this bug about 3-4 times now, but what causing it, I still don't have a clue.

**Comment by rovf** [comment]
For the time being, it is not reproducible.

@babobski : What do you mean by _rebooting_ Komodo?

**Comment by Defman21** [comment]
Restarting.

**Comment by rovf** [comment]
I see. Well, this explains, why the error did not occur anymore after I restarted the editor.

**Comment by Naatan** [comment]
Please let us know if you can reproduce the issue, or if you managed to capture an error log from when it happens. Until then I'll close this issue as it is unfortionately not actionable without repro steps or more information.
