### ISSUE TITLE
Code sidebar is not restored when opening after killing Komodo

### ISSUE THREAD

**Issue by ANSI-C** [Komodo/KomodoEdit#2328]
### Short Summary

Sometimes I am forced to kill Komodo when it freezes due changes to opened files from external git.
In that case the code sidebar is not restored, I have to set it to visible again.

### Steps to Reproduce

- show code sidebar
- kill Komodo from task manager
- restart Komodo

### Expected results

it should restore full former settings 

### Actual results

code sidebar is not shown

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.1.4
*Operating System (and version)?* Win 8.1

Komodo IDE, version 10.1.4, build 89515, platform win32-x86. Built on Fri Dec 16 10:34:21 2016.

**Comment by Naatan** [comment]
Hi there, could you please provide steps to reproduce the issue? It looks like the steps you gave are for the workaround.

**Comment by Naatan** [comment]
@mitchell-as just pointed out that those are in fact your reproduction steps, I thought you were giving me a workaround.

Unfortunately we cannot really do anything about the issue you reported as you force closed Komodo, which can cause issues no matter what software you're using.

**Comment by ANSI-C** [comment]
Hi, sorry for my late response here, a saved setting should be restored even upon a restart after a crash, this does not happen in this case:
![immagine](https://cloud.githubusercontent.com/assets/7015883/23344210/84f99eda-fc78-11e6-8212-cbfe2153c214.png)

**Comment by mitchell-as** [comment]
The thing is, that setting is not saved. It is saved upon correctly quitting Komodo, not force-killing or crashing it.

**Comment by ANSI-C** [comment]
Yep, the other are.


Il 27/02/2017 16:10, mitchell ha scritto:

**Comment by Naatan** [comment]
@ANSI-C for that we have the following bug report: https://github.com/Komodo/KomodoEdit/issues/2000
