### ISSUE TITLE
Unable to drag/move Komodo Edit window in OSX 10.11 or 10.12

### ISSUE THREAD

**Issue by FrancisJMR** [Komodo/KomodoEdit#2330]
### Short Summary

When I open Komodo Edit, I cannot move the window around after placing my pointer on the top window frame clicking and dragging. Resizing, minimizing, and closing windows work fine.

At times (~1/10 times) I can click on the desktop to unfocus, then click on the window again and I can move/drag the window again. Resizing the window doesn't typically solve the issue but has at times. 

I've been having this issue on OSX El Captain (10.11) and recently updated to Sierra (10.12) with the same problem persisting.

### Steps to Reproduce

Simply launch Komodo Edit and attempt to drag/move window with a "mouse down" on the top window frame.

### Expected results

Should move!

### Actual results

Doesn't move (or does after multiple attempts)... :(

### Platform Information

Komodo Edit, version 9.3.2, build 16460, platform macosx. Built on Thu Dec 10 19:37:46 2015

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?*

**Comment by cgchoffman** [comment]
Please try to reproduce the issue using Komodo 10.1.4: http://downloads.activestate.com/Komodo/releases/10.1.4/

**Comment by FrancisJMR** [comment]
Hi Carey,
Fantastic, dragging windows now works great - didn't realize there was an update version for OSX my bad!
I'm seeing just one little bug with this new version 10.1.4: When I hold down the mouse, it drags fine, but if I use shortcut keys to toggle 'Spaces' on OSX while I click down, the window doesn't follow into the new space, but stays put in the original space. Note: I use 'Apple'+Number Keys to switch spaces.
Cheers,
Francis

**Comment by cgchoffman** [comment]
Please open a new bug.  Also try to avoid reply to the Git notification email.  Use the web interface.  Git doesn't filter the email content and you could end up posting phone numbers or whatever else you might have in a email signature.
