### ISSUE TITLE
Feature Request: Open Files from Projects

### ISSUE THREAD

**Issue by hoppfrosch** [Komodo/KomodoEdit#2333]
This feature request is similar to #2282:

Within "GoTo Anything" you are able to open a tab from "Open Files" or you can open a file from your currently active project (GoTo Anything: "Files" - or Ctrl-Shift-O)

It would be nice to be able to open a file **from any of your projects** which is listed within "Projects" panel via a GoTo-Anything command

**Comment by Naatan** [comment]
You can already do this in a way, simply locate the folder in question via commando and hit the right arrow key on it, then hit "Add Shortcut". Give your shortcut a name and then to use it type `shortcutname/`. This will put you right inside the directory you made a shortcut for.

Another thing you can do is add "live folders" to your project by right clicking it in the side panel and choosing add > Existing Folder. Commando will then include this folder in your searches.

These options will have to suit your needs, as Komodo does not have an awareness of all your projects, just the ones you recently accessed. And letting it search all of those would affect performance as well as give a bad user experience for those who do not want/need this (most people).
