### ISSUE TITLE
Feature request: Show line ending style of the document

### ISSUE THREAD

**Issue by rovf** [Komodo/KomodoEdit#2337]
Kommodo Edit allows to view the line ending character for each line. This is usually too much information and distracts from work. It would be great if the editor could also show the line ending style for the whole document in the status line, for example as a string "LF", "CRLF", "CR" or "UNDEF".

### Platform Information

*Komodo Edit* 
*10.1.4* 
*Windows 7*

**Comment by rovf** [comment]
Issue can be closed. I just noticed that there is an addon which can be installed and provides this feature.

**Comment by Naatan** [comment]
Yeah, that addon was a result of an issue just like yours :) We encourage people to implement these types of features as addons, as they are sometimes too specific to be included by default.
