### ISSUE TITLE
Fails to save .txt files

### ISSUE THREAD

**Issue by davetlewis-van** [Komodo/KomodoEdit#2341]
### Short Summary
Unable to save .txt files in RC.

### Steps to Reproduce
Ctrl+N 
type some text 
Ctrl+S

### Expected results
Save the file with the default name.

### Actual results
Error message pops up.

### Platform Information

*Komodo Edit or IDE?*  IDE
*Komodo Version?* 10.2.0-89815
*Operating System (and version)?* Windows 10 Enterprise Versino 1607 OS Build 14393.693

### Additional Information

TypeError: this._hookedMacrosByTrigger is undefined

Exception: TypeError: this._hookedMacrosByTrigger is undefined

Traceback:
MacroEventHandler.prototype.callHookedMacros@chrome://komodo/content/project/peMacro.js:284:9
MacroEventHandler.prototype.hookPreFileSave@chrome://komodo/content/project/peMacro.js:510:12
save@vieweditor:1452:21
viewManager.prototype.do_cmd_save@chrome://komodo/content/views.js:1905:5
xtk.Controller.prototype.doCommand@chrome://xtk/content/controller.js:61:9
command_doCommand@chrome://komodo/content/library/commands.js:239:1
command_doCommandAsync@chrome://komodo/content/library/commands.js:191:1
@chrome://komodo/content/keybindings/keybindings.js line 2562 > eval:1:1
this.Manager.prototype.evalCommand@chrome://komodo/content/keybindings/keybindings.js:2562:23
this.Manager.prototype.keypressHandler@chrome://komodo/content/keybindings/keybindings.js:2733:17
gKeyHandler@chrome://komodo/content/keybindings/keybindings.js:2617:5

Komodo IDE, version 10.2.0, build 89815.
Built on Thu Feb 16 01:00:18 2017.

**Comment by Naatan** [comment]
Thanks, this is the same issue as #2343
