### ISSUE TITLE
Toolbox is missing tools and tutorials

### ISSUE THREAD

**Issue by davetlewis-van** [Komodo/KomodoEdit#2343]
### Short Summary
The toolbox is empty on startup. The sample commands, tutorials, etc. are not available. 

### Steps to Reproduce
Start the application and show the toolbox.

### Expected results
Display a tree with toolbox content.

### Actual results
Empty pane.

### Platform Information

Komodo IDE, version 10.2.0, build 89815.
Built on Thu Feb 16 01:00:18 2017.

Windows 10 Enterprise Version 1607 OS Build 14393.693

*Operating System (and version)?* 

### Additional Information

 
![empyt_toolbox](https://cloud.githubusercontent.com/assets/23486608/23042238/b54435de-f44c-11e6-9094-75e48605533d.png)

**Comment by Naatan** [comment]
Fixed in https://github.com/Komodo/KomodoIDE/commit/2a3f3dc96886b172c929322ab3230a161492207c
