### ISSUE TITLE
Remove PyPM Location from Python Language Preferences

### ISSUE THREAD

**Issue by zoofood** [Komodo/KomodoEdit#2345]
### Short Summary
We are phasing out PyPM so this item can be removed from both Python and Python3 menu items. Note we no longer ship PyPM executable in our most recent distros.

### Steps to Reproduce
The menu I'm talking about is located here: https://screencast.com/t/ElStJ2dZntag

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?*

**Comment by cgchoffman** [comment]
I think @Naatan already did this.  PYPM is gone from the Python[3] lang prefs.

**Comment by mjainQA** [comment]
Verified in Komodo IDE, version 11.0.0-alpha1, build 90297, platform macosx.
Built on Mon Jul 31 23:44:58 2017. No test case needed.
