### ISSUE TITLE
ko/editor.getLine does not work propely with tabs

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#2351]
### Short Summary

title.

### Steps to Reproduce

```
	<aside>
		div>ul>li |
```

Run `require("ko/editor").getLine()`.

### Expected results

```
	div>ul>li
```

### Actual results

```
	div
```

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.2
*Operating System (and version)?* elementary OS

**Comment by mitchell-as** [comment]
Thanks for the report!
