### ISSUE TITLE
Slack sharing dialog doesnt update after authenticating

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#2352]
### Short Summary

You have to reopen the sharing dialog to see the changes after authenticating with Slack

### Steps to Reproduce

 1. start slack sharing on a clean profie
 2. authenticate

### Expected results

Dialog updates with list of channels

### Actual results

Dialog doesn't update

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?*

**Comment by cgchoffman** [comment]
I can't reproduce this:
Komodo IDE, version 10.2.0, build 89824, platform win32-x86.
Built on Thu Feb 16 14:03:56 2017.

**Comment by cgchoffman** [comment]
The dialog gets a list of channels after I authenticate.

**Comment by Naatan** [comment]
Will dig on this myself then.

**Comment by Naatan** [comment]
Fixed with https://github.com/Komodo/KomodoIDE/commit/a803a8c8bec6f887bab76ff913f2254a2ea8d5ea

There was a race condition it seems.
