### ISSUE TITLE
Clear linter indicators when typing

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#2353]
At the moment linting indicators don't get removed until the timeout is triggered. It would make sense that indicators get removed as soon as you start typing on a line, as it is unlikely that the linting result for that line will remain the same.

To be clear: this should only go for the current line, the rest can get updated on the timeout still.

**Comment by Defman21** [comment]
I remember @cgchoffman were asking for that and probably filled an issue as well.

**Comment by cgchoffman** [comment]
Diffferent issue @Defman21.  Different event triggers though same komodo component: https://github.com/Komodo/KomodoEdit/issues/2030

**Comment by Defman21** [comment]
https://github.com/Komodo/KomodoEdit/issues/1902

**Comment by Naatan** [comment]
Your memory is far better than mine @Defman21 :)
