### ISSUE TITLE
VC Tab:  Commit dialog doesn't update properly when commiting using SVN

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2355]
### Short Summary

I performed a commit through the Version Control commit dialog and the committed file just stays in the **Committing** section even though the commit completed successfully. Selecting the file shows nothing in the Diff section

### Steps to Reproduce

Perform an SVN commit

### Expected results

UI to update and reflect that the committed file is no longer "different"

### Actual results

File stays in **Committing** field.

**Comment by Naatan** [comment]
Fixed with https://github.com/Komodo/KomodoIDE/commit/c532fff2c3c54659bd855ec37760e430a3938b09
