### ISSUE TITLE
slack channel cache never ages out

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2359]
### Short Summary

https://github.com/Komodo/KomodoIDE/blob/master//src/chrome/komodo/content/sdk/share/slack/api.js#L256

This cache needs to expire and reload or be removed.  Depending on the team channels could change often.  Even on our AS team channels are being added or removed quite often.

**Comment by cgchoffman** [comment]
Komodo will now reset the channel cache after 5 minutes when the user attempt to load the Slack share UI.
https://github.com/Komodo/KomodoIDE/commit/55bfd784647e05ada141a825c70d0d083c1b6871

**Comment by cgchoffman** [comment]
To test:
- setup slack (right click in a file > share > Slack)
- Add a slack channel in your slack application
- wait 5 minutes 
- try to share something to your new slack channel

If the channel isn't there then this would be a fail.

**Comment by mjainQA** [comment]
Verified on 10.2.2 RC3 macOS.

No test case needed as this is an enhancement.
