### ISSUE TITLE
Sharing via Slack renders no method to abort a share on Linux.

### ISSUE THREAD

**Issue by jellisii** [Komodo/KomodoEdit#2360]
### Short Summary

Sharing via Slack renders no method to abort a share on Linux, maybe others.

### Steps to Reproduce

Highlight some code. 

Right click -> Share -> Share code via Slack.  

### Expected results

Render a method to abort a share.  Either a "cancel" button or a close window button.  Both of these should fire appropriate cleanup code.  

### Actual results

See screenshot below.

### Platform Information

Komodo IDE, version 10.2.0, build 89833, platform linux-x86_64.
Built on Fri Feb 17 15:05:44 2017.
Ubuntu 16.04, using XFCE.  

### Additional Information

[http://www.zimagez.com/zimage/screenshot2017-02-2213-00-18.php](http://www.zimagez.com/zimage/screenshot2017-02-2213-00-18.php)

**Comment by cgchoffman** [comment]
Well that's frustrating for you, @jellisii and clearly my mistake.  I believe this is due to a slightly large Interface font that you might be using.  For a workaround you can try reducing your font size in Prefs > Appearance.

Fixed (private repo link, just meant for dev ref.): https://github.com/Komodo/KomodoIDE/commit/307e4a4661c757dc210f5fc23a6611095e8b6059

**Comment by jellisii** [comment]
The font size does appear to be the issue, but this leads to another potential problem: I'm using Sans Serif at 1 rem on the interface in my color scheme, and have the fonts for the interface "Let the color scheme decide".  I don't consider these unreasonable settings, and I think they are from the default color scheme.  

I'm not knowingly altering anything with fonts in the window manager.  

The primary reason I use a custom theme is because at one point the edge line color was unusable (#1596).  I haven't checked to see if the default theme has been fixed.

If you'd like any more information, please let me know.

**Comment by cgchoffman** [comment]
It's all good @jellisii, I closed the ticket because I've fixed it on master and our 10.2.1 branch to be released later :)  You reported a totally valid bug.  Sorry for not being more clear.

Keep your eyes open for 10.2.1 nightly pre-releases and later a 10.2.1 point release which.

**Comment by cgchoffman** [comment]
Patched nightly build available: http://downloads.activestate.com/Komodo/nightly/komodoide/
Also includes patch for #2368.
