### ISSUE TITLE
Missing log file

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#2361]
### Short Summary
Just updated to 10.2 but I'm missing my log file at home. At work I installed the update by hand, because the update wasn't available through Komodo. At work I have a log file, but here at home it does not exist.

### Platform Information
Komodo 10.2 Windows 10

### Additional Information

![afbeelding](https://cloud.githubusercontent.com/assets/3530262/23226548/3b23f2f0-f936-11e6-9b89-119f6dcc227c.png)

**Comment by cgchoffman** [comment]
#2357

**Comment by babobski** [comment]
@cgchoffman 👍, just restarted and the log file is created.
