### ISSUE TITLE
can't turn off block select

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#2366]
### Short Summary
Staring a selection on a delimiter starts another one on the opposite delimiter. Drives me nuts.

https://youtu.be/-8-b_H4fE0w

Setting preferences / Smart editing / Delimited block select delimiters to empty does not help

I think this was not so in 10.1

### Expected results

Just select what I want

### Platform Information

Komodo IDE, version 10.2.0, build 89833, platform linux-x86_64.
Built on Fri Feb 17 15:05:44 2017.

**Comment by mitchell-as** [comment]
Hi, unchecking Edit > Preferences > Editor > Smart Editing > Edit matching delimiter on select should achieve the desired behavior.
