### ISSUE TITLE
Select matching delimiter should be limited to just the delimiter

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#2367]
### Short Summary

When this feature triggers it basically starts a multi-cursor selection and then just lets multi-cursor handle everything. This makes for annoying use-cases where starting a regular selection turns into a multi-selection.

### Steps to Reproduce

Create a JS file with contents:

```
console.log("foo"|)
```

`|` represents your caret

Press shift+left twice

### Expected results

The first iteration should select the delimiters, the second should revert to single select because obviously you're no longer intending to select the delimiter if your selection expands beyond delimiters.

### Actual results

It selects the delimiters as well as the characters in front of them.

**Comment by sfsccn** [comment]
I'm probably experiencing the same thing. I just upgraded to 10.2 and if I shift-select quoted text using arrow keys to add to the selection I get two cursors (weird) that keep selecting more than I want. It seems to depend on the language I'm viewing as.

Reproduce:

* Edit new my-file.txt
* Insert "Here is some 'quoted text'"
* View as language text and shift select end of line: nothing
* View as MySQL: dual cursor thing
* View as JavaScript: dual cursor thing

**Comment by Naatan** [comment]
Fyi for now you can just turn this off via

Preferences > Editor > Smart Editing > Edit matching delimiter on select

**Comment by Naatan** [comment]
Prioritizing this as it can be quite annoying at the moment. If the fix for this is not feasible for 10.2.1 then we should default this pref to be turned off for 10.2.1.
