### ISSUE TITLE
Custom Formatters Fail

### ISSUE THREAD

**Issue by mitchell-as** [Komodo/KomodoEdit#2368]
Per http://community.komodoide.com/t/perltidy-formatter-doesnt-work-in-komod-ide-10-2/3392

### Short Summary

Running a custom formatter (e.g. Perltidy) results in a Komodo error.

### Steps to Reproduce

Create a custom formatter like

```
Name: perltidy
Language: Perl
Formatter: Generic command-line formatter
Executable: /home/me/perl5/perlbrew/perls/perl-5.20.1/bin/perltidy
Command-line arguments: -pro=~/.perltidyrc
```

Then try to format a Perl document.

### Expected results

Formatted Perl

### Actual results

```
ERROR:xpcom:Unhandled exception calling 'int8 * format(in nsISomething);'
Traceback (most recent call last):
File "/home/me/Komodo-IDE-10/lib/mozilla/python/xpcom/server/policy.py", line 303, in CallMethod
return 0, func(*params)
File "/home/me/Komodo-IDE-10/lib/mozilla/components/koGenericFormatter.py", line 85, in format
context.prefset)
TypeError: Interpolate1() takes exactly 10 arguments (9 given)
```

### Platform Information

*Komodo Edit or IDE?* Any
*Komodo Version?* 10.2
*Operating System (and version)?* Any

### Additional Information

This commit causes the issue:

https://github.com/Komodo/KomodoEdit/commit/88bff5171c1658e013f499c508b1b841d1606ab2

Specifically, the new argument:

https://github.com/Komodo/KomodoEdit/commit/88bff5171c1658e013f499c508b1b841d1606ab2#diff-6aa28facfff2c4ba613d0ce9c79a5df5R637

Any calls to `Interpolate1` with the old argument list will fail. Either make that argument optional (append `=None`), or update all `Interpolate1` calls.

**Comment by simbabque** [comment]
Built-in formatters like _XML Tidy_ also fail with the same exception.

**Comment by Naatan** [comment]
@cgchoffman please check for other uses of this method. More things could be broken due to this.

**Comment by cgchoffman** [comment]
Patched nightly build available: http://downloads.activestate.com/Komodo/nightly/komodoide/
Also includes patch for #2360.
