### ISSUE TITLE
Cannot publish after reverting changes

### ISSUE THREAD

**Issue by jellisii** [Komodo/KomodoEdit#2369]
### Short Summary

After reverting changes in a file via source code control, you cannot push the file to the publishing endpoint.

### Steps to Reproduce

Have a project that has Git as its source control.  

Set up a publishing endpoint for the folder that contains the project code.  Ensure that "When a file is saved locally, auto-push it to the remote-server" is checked.  

Open a file, alter, and save it.  

Right click the file name in the open file tab strip at the top, and navigate to "Publishing"

### Expected results

I expect "Push" to be enabled.

### Actual results

"Push" is not enabled.  

### Platform Information

Komodo IDE, version 10.2.0, build 89833, platform linux-x86_64.
Built on Fri Feb 17 15:05:44 2017.

### Additional Information

[http://en.zimagez.com/zimage/screenshot2017-02-2311-14-23.php](http://en.zimagez.com/zimage/screenshot2017-02-2311-14-23.php)

Please observe in the screenshot above the cloud icon indicating the publishing state is blue, indicating said file needs to be pushed, but the menu options for push and diff are both disabled inappropriately. 

This did work in 10.1.x

**Comment by jellisii** [comment]
Any word on this getting fixed, or will it be one of those things that will have to wait until the publishing refactor happens?

**Comment by Defman21** [comment]
It should be fixed in Komodo 11 according to the milestone of the issue.

**Comment by cgchoffman** [comment]
@jellisii, does the `Push` option ever enable for you?  I've either stumbled across a new bug while checking yours or this goes deep then we thought.  Could you confirm that you are able to "Push" outside of these repro steps?

**Comment by jellisii** [comment]
I believe you may be correct...  Push nor Diff light up when a file I change outside of Komodo goes out of sync with the remote.

**Comment by cgchoffman** [comment]
Well that's fun.  Thanks for confirming @jellisii.

**Comment by cgchoffman** [comment]
Going to see if we can fit this into 10.2.2 but I'm slammed so I can't promise anything.

**Comment by jellisii** [comment]
Fair enough.  I have a couple of inelegant workarounds for the time being:

- Edit the file, save, remove edit, save.  This presumes "push on save" is enabled, which is normal for me.
- Run the publishing process.  

I'm actively grinding to not needing the publishing process in my normal day-to-day work, I'm just not there yet.

**Comment by cgchoffman** [comment]
> I'm actively grinding to not needing the publishing process in my normal day-to-day work

This is a really good goal to have (version control FTW)....maybe we shouldn't fix this so you're more motivated?  heh kidding!  Sorry for the inconvenience @jellisii.

**Comment by jellisii** [comment]
No worries.  :D

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/134f53bc8ca416d43b19e44d4e3d487e930e7094

**Comment by cgchoffman** [comment]
@jellisii The fixed nightly will be here: http://downloads.activestate.com/Komodo/nightly/komodoide/latest-10.2.x/ around 12:30 pm PST.  Confirm the build number is 89870 before testing.

**Comment by jellisii** [comment]
It does appear to fix the problem at first blush.  Thank you @cgchoffman

**Comment by cgchoffman** [comment]
@jellisii, great, thanks for confirming.
