### ISSUE TITLE
PerlTidy not working as formatter

### ISSUE THREAD

**Issue by FreshGrill** [Komodo/KomodoEdit#2371]
### Steps to Reproduce
Perltidy not working

### Expected results
Perltidy to work

### Actual results
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE)
[koIFormatter.format]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location:
"JS frame :: chrome://komodo/content/formatters/formatters.js ::
_formatViewWithFormatterAndContext :: line 132"  data: no]
                         Wed Feb 22 2017 15:08:14 GMT-0800 (Pacific Standard

### Platform Information
This is perltidy, v20160302

Komodo IDE, version 10.2.0, build 89833, platform win32-x86.
Built on Fri Feb 17 15:10:04 2017.
Windows 7 SP1 64bit.

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 

### Additional Information
This is perl 5, version 22, subversion 3 (v5.22.3) built for
MSWin32-x64-multi-thread
(with 1 registered patch, see perl -V for more detail)

U:\>perltidy -version
This is perltidy, v20160302

Komodo IDE, version 10.2.0, build 89833, platform win32-x86.
Built on Fri Feb 17 15:10:04 2017.

Under preferences, formatter, name PerlTidy, Language Perl, Generic Command
line Formatter.
Tried: perltidy, C:\Perl64\site\bin\perltidy_ko, C:\Perl64\site\bin\perltidy

When right and format document with perltidy:
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE)
[koIFormatter.format]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location:
"JS frame :: chrome://komodo/content/formatters/formatters.js ::
_formatViewWithFormatterAndContext :: line 132"  data: no]
                         Wed Feb 22 2017 15:08:14 GMT-0800 (Pacific Standard
Time)

**Comment by Naatan** [comment]
Duplicated of #2368
