### ISSUE TITLE
ko.abbrev.findAbbrevSnippet broken in 10.2

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#2373]
### Short Summary
ko.abbrev.findAbbrevSnippet no longer working properly. I have a custom addon for my self that uses 
ko.abbrev.findAbbrevSnippet only it fails for all my custom abbreviations:

![afbeelding](https://cloud.githubusercontent.com/assets/3530262/23302578/8624c518-fa8f-11e6-8f1e-299589c70821.png)

![afbeelding](https://cloud.githubusercontent.com/assets/3530262/23302590/9243060c-fa8f-11e6-839a-51ba97a716a8.png)

![afbeelding](https://cloud.githubusercontent.com/assets/3530262/23302619/aa5eac14-fa8f-11e6-9723-3e20ee84b0ec.png)

![afbeelding](https://cloud.githubusercontent.com/assets/3530262/23302677/007e50ea-fa90-11e6-8d27-b8d9401003e1.png)

![afbeelding](https://cloud.githubusercontent.com/assets/3530262/23302690/155462a2-fa90-11e6-9bad-f794ff18dd0a.png)

For PHP it is only working for abbreviations that are in the default folder:

![afbeelding](https://cloud.githubusercontent.com/assets/3530262/23302909/4588da56-fa91-11e6-9b85-2060e6f4185a.png)

### Steps to Reproduce
The snippets I'm using can be found [here](https://github.com/babobski/Smart-Tags-Auto-completion).
@cgchoffman noticed that the 'import > import folder from file system' is working correct, it is setting the correct languages for the imports.

### Platform Information
Komodo Ide 10.2 Windows 10

**Comment by cgchoffman** [comment]
WHy are you setting the Sub language for the search?  You should only need `ko.abbrev.findAbbrevSnippet(snippetName, language)`.

**Comment by Naatan** [comment]
@cgchoffman the point is it should be backwards compatible, we'll need to ensure that if this worked before it still works now.

**Comment by babobski** [comment]
@cgchoffman If i use the ko.abbrev.findAbbrevSnippet(snippetName, language) command, It still doesn't work.

![afbeelding](https://cloud.githubusercontent.com/assets/3530262/23338676/803cd8ba-fc11-11e6-8b95-7ddcfdbf73cb.png)

And the structure:

![afbeelding](https://cloud.githubusercontent.com/assets/3530262/23338680/93b14070-fc11-11e6-86e2-a7bfdf94bb77.png)

The snippets:

![afbeelding](https://cloud.githubusercontent.com/assets/3530262/23338682/a20c2ec8-fc11-11e6-85d5-ff86f8a629f4.png)

![afbeelding](https://cloud.githubusercontent.com/assets/3530262/23338686/aef28e8e-fc11-11e6-97db-f71b2e1a8394.png)

![afbeelding](https://cloud.githubusercontent.com/assets/3530262/23338690/be2054d6-fc11-11e6-8795-de881e8058bd.png)

**Comment by cgchoffman** [comment]
> @cgchoffman If i use the ko.abbrev.findAbbrevSnippet(snippetName, language) command, It still doesn't work.

Yes I was wrong.  The issue is fixed now and will be in the next nightly.

> And the structure:

Toolbox folder structure has no effect on snippets any more.
