### ISSUE TITLE
Find and replace not working in *.komodotool

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#2374]
### Short Summary
Noticed that for the issue #2373 to get it to work, i have to enable the treat as auto abbreviation.
So I wanted to preform a search and replace in my folder so I can enable them all at once.
Only komodo doesn't recognize the *.komodotool as a language.

Find is working only find and replace isn't.

### Expected results
That find and replace should work for *.komodotool files

### Actual results
It doesn't.

### Platform Information
Komodo Ide 10.2 Windows 10
 
Workaround use the find function, and the find next result key-binding to loop over the search results and make the replacement manualy.

**Comment by Naatan** [comment]
Working fine for me. Are you using the "current document" as the scope? What are the exact steps?

**Comment by babobski** [comment]
I'm using the "files" scope (screenshot includes the find results):

![afbeelding](https://cloud.githubusercontent.com/assets/3530262/23370453/084bb5ec-fd15-11e6-9a58-24661c4de00d.png)

Only when I exacute the replace I get the following screen (confirm enabeld):

![afbeelding](https://cloud.githubusercontent.com/assets/3530262/23370507/2c266994-fd15-11e6-8a5f-c47a889627de.png)

I'm getting a (unknown language) error

**Comment by Naatan** [comment]
Ahh gotcha. Thanks :)

**Comment by cgchoffman** [comment]
I consider this the same as https://github.com/Komodo/KomodoEdit/issues/467

**Comment by Naatan** [comment]
That would definitely help, but I think any language we supply should be handled by Komodo automatically.

**Comment by cgchoffman** [comment]
*.komodotool isn't a language that we supply.   I really don't think we should be creating the code to make *.komodotool recognized as a "language".  I think we should axe that find/replace mechanic.

**Comment by Naatan** [comment]
Fair, let's make #467 about axing the mechanic then, instead of adding an override.

**Comment by cgchoffman** [comment]
Ya, I like that idea better.  I hit this exact issue when i was working on tutorials.  I'd really like to see that mechanic gone.
