### ISSUE TITLE
language undefined warning when saving snippets

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#2375]
Open a snippet and press OK, check log for following warning:

```
JavaScript strict warning: chrome://komodo/content/project/snippetProperties.js, line 270: ReferenceError: assignment to undeclared variable language
```

**Comment by cgchoffman** [comment]
@Naatan I'm pretty sure those warnings are on Master and are due to the changes you made for Komodo 11 nathanr.   Can you confirm what build you're using?

**Comment by cgchoffman** [comment]
Also the error you posted isn't a "language undefined error".  It's an "undeclared var" error.  I can't reproduce either error on 10.2.

**Comment by cgchoffman** [comment]
`undelcared variable` error is fixed but can you confirm my question in my first comment @Naatan ?

**Comment by Naatan** [comment]
@cgchoffman yeah I'm using master. So is the commit you did for something else?

**Comment by cgchoffman** [comment]
@Naatan, you referenced two different errors.  I fixed one of them.  The title error is a different errror that is only on Master.  The one i fixed I've noticed before but it doesn't effect snippet saving at all but you labelled this for 10.2.1 so I fixed it.

**Comment by cgchoffman** [comment]
I was reading too much into error messages and bug titles.  I thought @Naatan was talking about another error that I've seen on Master.
