### ISSUE TITLE
Editor History: Landing in a location in a new file via Go To Definition does not create a history item

### ISSUE THREAD

**Issue by damienprystay** [Komodo/KomodoEdit#2378]
### Short Summary
Proceeding through a chain of Go To Definition actions that spans multiple files (by way of Command-clicking) causes certain hops to be omitted from the editor history navigation.

### Steps to Reproduce
1) Open a file A that contains a call to a function defined in file B.
2) Command-click the function name in A to go to its definition. B opens in a new tab, with the cursor at the function's definition.
3) Without clicking anywhere else first, Command-click another function name in B that's defined elsewhere in B. The cursor is moved to that second function's definition in B.
4) Click the "Go back one location" button. Instead of returning to our location as of the end of 2) (the definition of the first function), we're returned to our location as of 1) (the call to the first function).

More tersely, given `a.py`:
```
import b
b.foo()
```
and `b.py`:
```
def foo():
    bar()
def bar():
    pass
```
Open `a.py`, Command-click on `foo` to bring up `b.py`; command-click on the first `bar` to go to its definition, then click the Back button: instead of returning to `def foo():` in `b.py`, you return to `b.foo()` in `a.py`.

Clicking around in file B before Command-clicking on something seems to (sometimes?) set that as a history location (as does, sometimes, using the right-click context menu's Go To Definition option), so I get the impression that Go To Definition opening a file does not establish a point in the history by itself.

### Platform Information

Komodo IDE 10.2.0
Mac OS 10.11.6

**Comment by mitchell-as** [comment]
Thank you for the model report @damienprystay. I confirm everything that you've said. It is possible that the history only saves jumps that meet a certain (line) threshold, but perhaps @cgchoffman would know more on this.

**Comment by Naatan** [comment]
I've wrestled with this code many times, and honestly; I'm just gonna dumb it. Well the part that tracks history locations that is. Historically this was a very specific thing, where it would only track certain actions as "history". I'm going to dumb this down to the point where it just tracks any movement within the editor that's greater than X lines.

Opened a ticket for this here - https://github.com/Komodo/KomodoEdit/issues/2381

**Comment by mitchell-as** [comment]
Okay, well keep in mind with the steps given, one of the "goto definition" jumps is down one line. So if the threshold is 1 line, any up/down arrow keys will register as history events. That would be very noisy.

**Comment by Naatan** [comment]
Yeah that's why I say "greater than X lines". I'll make X configurable but the default will likely be 5 or so.
