### ISSUE TITLE
Cannot parse Python 3 "raise ... from ..." syntax

### ISSUE THREAD

**Issue by hstock** [Komodo/KomodoEdit#238]
When opening a file that contains the Python 3 "raise ... from ..." syntax, the "Code View" (outline, right panel) does show an error for the file. (There is no code outline for the file and a red exclamation mark before it)

Upon double click the line shows: "error scanning ...py: cannot recover from syntax error in line [line where raise ... from ... is used]"

This is Komodo 9.0.1 on Linux (Ubuntu 12.04) x86_64

**Comment by hstock** [comment]
Update: This only happens when it is used twice in the file.

Here is a minimal example file:

```python
#!/usr/bin/env python3

class my_class(object):
    def my_fun(self):
        try:
            pass
        except Exception as e:
            raise Exception() from e
      
    def my_fun2(self):
        try:
            pass
        except Exception as e:
            raise Exception() from e
```

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoIDE/commit/bf83c92e00b8d826028e4a8cba78511dd2537865
