### ISSUE TITLE
Unable to add Remote Folders

### ISSUE THREAD

**Issue by jbrule** [Komodo/KomodoEdit#2382]
### Short Summary
The "OK" and "Apply" buttons do not respond when trying to add a remote folder. Only options that works is "Cancel" and upon press the remote folder is not added to list.

I tried resetting config via -> http://docs.komodoide.com/Troubleshooting/Reset-Komodo but the issue persists.

### Steps to Reproduce
Click gear icon in left pane -> Open Remote Directory -> Dropdown -> Add Server

Server type: SFTP
Name: "Server 1"
Hostname: <hostname>
Username: <username>
Password: <password>
Default Path: /

Click Add
--> Button changes to update

Click "OK".
--> None responsive

### Expected results

Expect to click "Add" and then "OK" or "Apply" and have remote folder available in list.

### Actual results

The "OK" and "Apply" buttons are non responsive. Unhandled exception is reported in the error log file. [pystderr.log.txt](https://github.com/Komodo/KomodoEdit/files/821517/pystderr.log.txt)

### Platform Information

*Komodo Edit or IDE?* Edit
*Komodo Version?*  10.2
*Operating System (and version)?* MacOS Sierra

**Comment by cgchoffman** [comment]
I thought this had been filed before but I can't find the ticket I'm thinking of.  @jbrule, are you certain the server is never saved?  Though it's annoying, you should still be able to open a remote folder once you've configured a server.

**Comment by cgchoffman** [comment]
If you are able to open a remote folder, please change the title of this ticket to reflect the actually issue, `Ok` don't close the prefs dialog.  Note, `Apply` never closes the dialog.

**Comment by jbrule** [comment]
Issue is no longer occurring in later versions. Closing.
