### ISSUE TITLE
Option to disable dangerous multi caret

### ISSUE THREAD

**Issue by randomsock** [Komodo/KomodoEdit#2390]
Windows 7
Komodo Edit 10.2

Multiple carets seem to appear automatically if you select, for example, a quote, in which case it also selects the matching quote.  The problem is I don't ask for or expect this feature and as you continue to type/delete it screws your code somewhere you're not looking.

For example, select the first quote in:

    "fruit flies like bananas"

selects both, so typing something results in:

    (only |fruit flies like bananas(only |

I can see some edge cases where this feature might save a key-stroke (or two), but on balance, it's extremely dangerous, especially if it's happening way on down the line where you don't notice.

I can't find any way to disable it.  I tried the suggested user script in #1081 but it doesn't have any effect.

**Comment by mitchell-as** [comment]
Hi, you can disable this feature in Edit > Preferences > Editor > Smart Editing > Edit matching delimiter on select.

**Comment by randomsock** [comment]
Ah! got it - totally didn't see the little chevron that shows Editor expands some more.  Thanks.

**Comment by cgchoffman** [comment]
> totally didn't see the little chevron that shows Editor expands some more. Thanks.

Good call.  I've filed an report about this.  I've noticed it before too but I know they are there so I never worried about it, #2391.
