### ISSUE TITLE
expand indicator in prefs is hard to see

### ISSUE THREAD

**Issue by th3coop** [Komodo/KomodoEdit#2391]
### Short Summary

I've seen this come up twice this week (#2390, and I think it contributed in the [forums](http://community.komodoide.com/t/tcl-syntax-check-on-close-command/3416/23?u=careyh) but that's just a guess) and I've noticed it personally as well.

I find it really hard to see the arrow indicating that the Language preference will expand to show me more things.  

![capture](https://cloud.githubusercontent.com/assets/655154/23763034/fbf694de-04ac-11e7-8b3c-60d42524d01c.PNG)

**Comment by Defman21** [comment]
I did some research on it and it's a quite complicated task. You can override the icon because koicon converts svg to png for some reason. I think it's possible to implement color overriding when generating icons, but I don't know how :/

**Comment by Naatan** [comment]
SVG's get converted to PNGs because it's cheaper on the resources.

**Comment by Defman21** [comment]
Didn't know that, okay.

**Comment by th3coop** [comment]
@Defman21 did you open a PR for that fix?

**Comment by Defman21** [comment]
Yeah, but it was closed.

https://github.com/Komodo/KomodoEdit/pull/2477

**Comment by th3coop** [comment]
@Defman21 thank you very much sir.

**Comment by th3coop** [comment]
@Defman21 can you submit it again?  I'm going to merge it.  Could you slap in an opacity `0.6` to the `-moz-tree-twisty` with it?

**Comment by Defman21** [comment]
Done.
