### ISSUE TITLE
When viewing the log file, an error is logged every second.

### ISSUE THREAD

**Issue by goozak** [Komodo/KomodoEdit#2394]
When viewing the log file (Help > Troubleshooting > View Log File), this error is logged every second, filling the log:

[2017-03-10 09:46:31,966] [ERROR] console-logger: TypeError: w.require(...).checkSpelling is not a function (2) in viewbufferbase:1138
Traceback (most recent call last):
  File "viewbufferbase", line 1138, in 

Komodo IDE, version 10.2.0, build 89833, platform win32-x86. Built on Fri Feb 17 15:10:04 2017.
Windows 10 Enterprise, version 1607, build 14393.693

[pystderr.txt](https://github.com/Komodo/KomodoEdit/files/834249/pystderr.txt)

**Comment by Naatan** [comment]
Is this reproducible after restarting Komodo? If so please share your full error log after restarting and reproducing the error.

**Comment by goozak** [comment]
That is the log included in the original comment (pystderr.txt — had to change the extension from .log to .txt for GitHub to accept it).

**Comment by Naatan** [comment]
Ah my bad. Nothing stands out in there. Do you have an editor open (and active) when that error occurs?

**Comment by goozak** [comment]
Yes.
Tried closing everything (Left/Right/Bottom panes, no files open — just 'New Tab') and the issue is still present, even if I restart Komodo in that configuration.

**Comment by Naatan** [comment]
Does spell checking work when you type code? Just try miss-spelling a word in a comment.

**Comment by goozak** [comment]
Spell checking does not work.  (I actually didn't know this feature existed, I don't remember ever seeing any notice about spelling — even though I routinely write comments in French and English...)

Turning off spellchecking does fix the issue.

**Comment by Naatan** [comment]
Can you reproduce this using `Help > Troubleshooting > Restart in Safe-mode` ?

Please verify that when restarting in safe-mode Komodo should be using the default UI (all your settings would be temporarily reset).

**Comment by goozak** [comment]
In Safe-mode, spell checking works and there are no extra logging when viewing the log.
So, my profile seems to be the problem (I keep forgetting Komodo is based on Mozilla).

**Comment by Naatan** [comment]
Are you using any addons? Might be worth trying to disable those. Currently you can only disable addons via `Tools > Addons (Legacy)`.

**Comment by goozak** [comment]
I may have installed a couple a while back.  Even if I disable a bunch of them (those I kept are from Komodo staffers) and restart, spell checking is still not working and "View Log File" still generate entries.

Anyway, I'm fine with simply turning spell checking off.  I don't want to bother you with a profile gunk up — I've been dragging this one for several versions, I think.  Might as well get a fresh start.

**Comment by Naatan** [comment]
Up to you. For what it's worth it's most likely an addon or userscript causing the issue.
