### ISSUE TITLE
Auto edit delimiters should cancel sooner

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2395]
### Short Summary

I know a fix just went in to resolve this but i personally think it could be cancelled sooner.  Right now the only time the double cursor is disabled is if I hold *Shift* and continue the selection in the original direction.  Any other key movement, with or without *shift* will keep the double cursor enabled.

I think the second cursor should be gone as soon as the cursor leaves the initial delimiter

### Steps to Reproduce

Sample text:
`aaaaaa|"bbbbbbb"cccccc`

1. Place cursor at `|`
Holding shift, press right twice.  The second cursor will appear then disapear on the second press

2. Place cursor at `|`
Holding shift ,press right once, then left.  The second cursor remains.  It should be gone.  The thing happens if you release Shift before you press left.  It should be gone in that case too.

3. Place cursor at `|`
Hold shift and press right once.  Release Shift and press right again.  The second cursor remains.  It should be gone.

Let me know if you want a gif for these.

**Comment by mitchell-as** [comment]
Hmm. This is a feature of Scintilla. When you have multiple carets (no matter how they were created), any arrow keys will move all cursors. While I agree in theory to what you expect to happen, programatically detecting this scenario may be tricky, or at least not very efficient (performing a check every single time the cursor is moved).

The workaround is to press Escape.

**Comment by Naatan** [comment]
I think we could simply monitor the next keypress, if it doesnt have a value (JS can tell you the "value" of a keypress) then we cancel the multi-caret. Stuff like left arrow, shift left arrow, etc. should not have a value.

I can look into this if you like @mitchell-as? Seems at this point it's mainly a matter of interpreting events. I think the scintilla specific stuff has been handled, unless you have another idea?

**Comment by mitchell-as** [comment]
@Naatan go for it. I wouldn't know where to begin.

**Comment by Naatan** [comment]
Can you link me to the logic for this? As well as the logic for HTML tag editing, since we'd want the behavior for that to be the same.

**Comment by mitchell-as** [comment]
Both bits of logic are in views-editor.p.xml's "onUpdateUI" method.
