### ISSUE TITLE
Can`t add custom Linter.

### ISSUE THREAD

**Issue by mathew85** [Komodo/KomodoEdit#24]
Custom Linter modules are not working with Komodo 9.
In log we get:

> [2015-03-09 08:17:36,684] [ERROR] lint: 
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [koILintService.addRequest]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: chrome://komodo/content/lint/lint.js :: this.lintBuffer.prototype._issueRequest :: line 477"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [koILintService.addRequest]'
+ result (number) 2147549183
+ name (string) 'NS_ERROR_UNEXPECTED'
+ filename (string) 'chrome://komodo/content/lint/lint.js'
+ lineNumber (number) 477
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'this.lintBuffer.prototype._issueRequest@chrome://komodo/content/lint/lint.js:477:12
this.lintBuffer.prototype._continueRequest@chrome://komodo/content/lint/lint.js:421:8
'
+ location (object) JS frame :: chrome://komodo/content/lint/lint.js :: this.lintBuffer.prototype._issueRequest :: line 477
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/lint/lint.js'
| + name (string) 'this.lintBuffer.prototype._issueRequest'
| + lineNumber (number) 477
| + columnNumber (number) 12
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/lint/lint.js :: this.lintBuffer.prototype._continueRequest :: line 421
| + formattedStack (string) 'this.lintBuffer.prototype._issueRequest@chrome://komodo/content/lint/lint.js:477:12
this.lintBuffer.prototype._continueRequest@chrome://komodo/content/lint/lint.js:421:8
'
| + stack
    this.lintBuffer.prototype._issueRequest@chrome://komodo/content/lint/lint.js:477:12
    this.lintBuffer.prototype._continueRequest@chrome://komodo/content/lint/lint.js:421:8
> -- EXCEPTION END --

Sample project can be found:
http://s000.tinyupload.com/?file_id=53559971691208244892

There`s also problem with importing Code Intel cile file:

> [2015-03-09 08:17:36,993] [ERROR] codeintel.citadel: unexpected error scanning `main.ts'
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo Edit 9 nightly\lib\mozilla\python\komodo\codeintel2\citadel.py", line 266, in scan
    scan_tree = cile_driver.scan_purelang(self)
  File "C:\Users\sssss\AppData\Local\ActiveState\KomodoEdit\9.0\XRE\extensions\testlang_language@yourdomain.org\pylib\codeintel_ts.py", line 258, in scan_purelang
    import cile_ts
> ImportError: No module named cile_ts 

but for that we can move content of file to the codeintel scan_purelang class

**Comment by Naatan** [comment]
Thanks for the report!

Before I look into this; what makes you generalize this to "custom linters dont work" - rather than just your particular linter having an issue in Komodo 9?

If there is indeed an inherent issue with third party linters in Komodo 9 we will make this a top priority, but so far this is the first issue I've seen of the kind.

**Comment by ericpromislow** [comment]
Looks like the error is on the python side.  I would wrap the call to
getLinterForLanguage in koLintService.addRequest with a

try:
   request.linter = self.getLinterForLanguage(request.linterType)
except:
   log.exception(can't get linter")
   raise

Restart komodo, attempt linting, and see if you get a better error message.

- Eric

**Comment by mathew85** [comment]
Hello,

after wraping around try block, there`s some more error message:

> [2015-03-10 09:18:24,535] [ERROR] koLintService: can't get linter
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo Edit 9 nightly\lib\mozilla\components\koLintService.py", line 422, in addRequest
    request.linter = self.getLinterForLanguage(request.linterType)
  File "C:\Program Files (x86)\ActiveState Komodo Edit 9 nightly\lib\mozilla\components\koLintService.py", line 388, in getLinterForLanguage
    return self._getLinterByCID(linterCID)
  File "C:\Program Files (x86)\ActiveState Komodo Edit 9 nightly\lib\mozilla\components\koLintService.py", line 404, in _getLinterByCID
    raise ServerException(nsError.NS_ERROR_UNEXPECTED, errmsg)
ServerException: 2147549183 (Internal Error creating a linter with CID '@activestate.com/koLinter? 
> language=Ts;1': 2147746132 (No such component '@activestate.com/koLinter?language=Ts;1'))

I moved koLinter class to the same file where is koTsLanguage and it looks like it`s working now.

**Comment by Naatan** [comment]
Good to hear, thanks for the update!

**Comment by acidicX** [comment]
I've got the same issue - different error message though. Should I open a new issue?

First, with "custom" (updated) jshint:

````[WARNING] koJavaScriptLinter: Error in jslint/jshint: stderr: /path/to/jshint.js:2194:8 TypeError: Array is undefined
, command was: [u'/opt/komodo-edit/lib/mozilla/js', u'/opt/komodo-edit/lib/support/lint/javascript/lintWrapper.js', u'--include=/path/to/', u'--jshint-basename=jshint.js', u'browser=true', u'devel=true', u'jquery=true', u'node=true', 'strict=false']````

and updated jslint:

````[WARNING] koJavaScriptLinter: Error in jslint/jshint: stderr: /opt/komodo-edit/lib/support/lint/javascript/lintWrapper.js:83:10 ReferenceError: JSLINT is not defined
, command was: [u'/opt/komodo-edit/lib/mozilla/js', u'/opt/komodo-edit/lib/support/lint/javascript/lintWrapper.js', u'--include=/path/to/', u'--jslint-basename=jslint.js']````

The included jslint is very, very old and could really use an update btw.

Komodo Edit, version 9.1.0, build 15798, platform linux-x86_64. Built on Sat May 30 05:22:08 2015

**Comment by girvo** [comment]
@mathew85 Hey, would you mind sharing that sample linter project? I'm attempting to get `eslint` working in Komodo, and would love to know what moving parts I'm missing!
