### ISSUE TITLE
Ugly LabelFrame in AByss theme in CGI Input section / Simulate CGI Environment

### ISSUE THREAD

**Issue by asb-capfan** [Komodo/KomodoEdit#240]
* Komodo IDE is set to Abyss theme
* run debugger with "Debugging Options" dialog
* check "Simulate CGI Environment" option at the bottom
* click "CGI Input" tab

The "Request Variable" text of the LabelFrame enclosing the fields for defining varaibles strikes through the text.
In the default theme, this is not the case.

**Comment by cgchoffman** [comment]
Any chance you could provide a screenshot?

**Comment by asb-capfan** [comment]
![Uploading ugly-labelframe.PNG…]()

**Comment by cgchoffman** [comment]
Awesome.  Thank you very much @asb-capfan

**Comment by Naatan** [comment]
Closing this as Abyss is no longer part of Komodo, please consider filing it on the Abyss repo. 

https://github.com/Komodo/Abyss-Skin
