### ISSUE TITLE
Can't change dialogs to `<window>` + `class='dialog'` with out breaking dialog

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2404]
The suggested fix for making a dialog draggable is to change it's base `<dialog>` element to `<window>` and add `class='dialog'` but this breaks some mechanics that come with the `dialog` binding I believe.  You lose basic buttons like `ok` and `cancel` and in some cases it just totally breaks the dialog.  Example of totally broken is making that change to *snippetProperties.xul*.

**Comment by Naatan** [comment]
That's not a bug, my suggestion to you was wrong.
