### ISSUE TITLE
komodo freezes several times

### ISSUE THREAD

**Issue by quintijn** [Komodo/KomodoEdit#2407]
After consulting the help desk I submit this bug report. Komodo freezes often at unexpected moments, even when I am working in another program. Here is the error log:
[pystderr.log.txt](https://github.com/Komodo/KomodoEdit/files/855780/pystderr.log.txt)

I trust most of the relevant info is in this logfile. Windows 7.

Greetings, Quintijn Hoogenboom
(The Netherlands)

**Comment by Naatan** [comment]
Can you please provide some more information? There's very little information for us to go on here.

 * Steps to Reproduce, when does it happen?
 * What version of Komodo?

**Comment by quintijn** [comment]
Hi Nathan,

 

Version, see attachment

Steps to repoduce: None, it happens intermittently I am afraid.

 

Greetings, Quintijn

 

Van: Nathan Rijksen [mailto:notifications@github.com] 
Verzonden: maandag 20 maart 2017 20:46
Aan: Komodo/KomodoEdit
CC: quintijn; Author
Onderwerp: Re: [Komodo/KomodoEdit] komodo freezes several times (#2407)

 

Can you please provide some more information? There's very little information for us to go on here.

*	Steps to Reproduce, when does it happen?
*	What version of Komodo?

**Comment by Naatan** [comment]
Note you aren't on the latest version, version 10.2.1 was released last week.

As for the freezes, how often do they happen? How long do they last? Is there any ryme or reason as to when they happen?

**Comment by quintijn** [comment]
OK, I will install this version tomorrow. I will write down when a freeze happens. If it happens, it remains so until I kill the process. I see no cause. I will keep you informed.

 

Greetings, Quintijn

 

Van: Nathan Rijksen [mailto:notifications@github.com] 
Verzonden: maandag 20 maart 2017 21:54
Aan: Komodo/KomodoEdit
CC: quintijn; Author
Onderwerp: Re: [Komodo/KomodoEdit] komodo freezes several times (#2407)

 

Note you aren't on the latest version, version 10.2.1 was released last week.

As for the freezes, how often do they happen? How long do they last? Is there any ryme or reason as to when they happen?

**Comment by Naatan** [comment]
Ok so effectively Komodo hangs until you force quit it?

How long does it generally take before this happens (from a fresh start)? And is there any consistency in what you are doing when Komodo hangs?

**Comment by quintijn** [comment]
Hi Nathan, this morning (it is 15 hrs here now), 3 crashes within a few minutes. But I got a clue maybe. See attached screenshots.

 

Maybe the fail to start listener on port 9073 is a clue?

 

Otherwise a de-install and install again?

 

Greetings,

 

Quintijn

 

Van: Nathan Rijksen [mailto:notifications@github.com] 
Verzonden: maandag 20 maart 2017 22:18
Aan: Komodo/KomodoEdit
CC: quintijn; Author
Onderwerp: Re: [Komodo/KomodoEdit] komodo freezes several times (#2407)

 

Ok so effectively Komodo hangs until you force quit it?

How long does it generally take before this happens (from a fresh start)? And is there any consistency in what you are doing when Komodo hangs?

**Comment by Naatan** [comment]
Hi @quintijn, could you please respond via github? Email responses get mangled and do not include attachments.

You could try turning off the remote debugging listener via Debug > Listen for Debugging connections.

In addition I would recommend you give safe mode a try to see if the crash still happens,  `Help > Troubleshooting > Restart in Safe-mode` ?

Please verify that when restarting in safe-mode Komodo should be using the default UI (all your settings would be temporarily reset).

And last but not least; I don't suppose you're given a crash report dialog?

**Comment by quintijn** [comment]
Hi Nathan, can I just disable the listening for debugging connections, or does the normal python debugging then not run anymore? Or can I choose a system provided free port (in the preferences)?

I will try the safe mode ASAP.

Greetings, Quintijn

**Comment by Naatan** [comment]
The listening is only required for remote debugging, so if you are not using remote debugging you can safely disable it.

**Comment by quintijn** [comment]
Hi, I set it to a system free port. I do not see where to disable it at all. The remote debugging.

**Comment by Naatan** [comment]
Hit Alt, then go to Debug and then hit "Listen for Debugging connections".

**Comment by quintijn** [comment]
Hi Naatan, the listener is off now. This morning another freeze. While another message, about an unrecognised utf-8 character was there. 

I now emptied the documents and have Komodo running for some time with 1 (latin-1) file opened, with no such error message. So, could this be the cause, and how can I tackle (retrieve) such an error?

![relevant messages possibly](https://cloud.githubusercontent.com/assets/21167695/24196879/af42d42e-0eff-11e7-81f7-e9020f39500a.png)

**Comment by Naatan** [comment]
That's very unlikely to be related, but if you notice any consistency around it let me know.

Please try safe-mode next. And I'd be surprised if Komodo freezes when you don't interact with it at all.

**Comment by quintijn** [comment]
In safe mode it works, but incredibly slow at times. So probably in normal mode the same: it recovers when you wait long enough. See a few screenshots
![in safe mode recovered but slow2017-03-24_11-57-06](https://cloud.githubusercontent.com/assets/21167695/24293357/aed1bcf6-1091-11e7-88d7-b94930cc3411.png)
![in safe mode 2017-03-24_12-52-45](https://cloud.githubusercontent.com/assets/21167695/24293358/aed2ab70-1091-11e7-92fa-6693ca47be29.png)
![very slow 2017-03-24_12-54-36](https://cloud.githubusercontent.com/assets/21167695/24293359/aedb5072-1091-11e7-831f-cf713e414f06.png)
![in safe mode recovers again 2017-03-24_11-21-29](https://cloud.githubusercontent.com/assets/21167695/24293360/aeddbcae-1091-11e7-95ba-5d3be295613b.png)

**Comment by quintijn** [comment]
Hi again, it seems the keyboard input reacts very slow. In safe mode it recovers after a while until now. In normal mode it sometimes does, but most of the time it keeps locked and I have to kill the process.

Can I try anything with cleaning up user config files, re-install or so? Or going back to a previous version and upgrade step-by-step to see when the problems arise? BTW on my laptop, also Windows 7, 64 bit machine, I have no problems.

**Comment by Naatan** [comment]
Could you try our latest nightly in safe-mode, it resolves an issue around input reacting slowly:

http://downloads.activestate.com/Komodo/nightly/komodoide/latest/

**Comment by quintijn** [comment]
OK, will see what happens!

**Comment by quintijn** [comment]
Probably solved! 

Hi Nathan, I saw Komodo and Git struggling for processor time for a while. But eventually this ended without a crash. Then I saw a process TGitCache. After killing this process I did not get a freeze up-to-now.

I also disabled The Git checking in the source code control part of the preferences. Still git checking seems to be done however.

See attachments. 

I use tortoisegit on windows7.

Hope this will remain so...

greetings, Quintijn

![git source code control checking](https://cloud.githubusercontent.com/assets/21167695/24661748/824a2e8c-1953-11e7-8f7b-eacac5d0bed0.jpg)

![source control preferences](https://cloud.githubusercontent.com/assets/21167695/24661577/0566446e-1953-11e7-86aa-949a4f316a4e.jpg)

![tgitcache](https://cloud.githubusercontent.com/assets/21167695/24661449/b230bfc2-1952-11e7-8a7a-025f8800efea.jpg)

**Comment by Naatan** [comment]
Thanks @quintijn, git does have a locking mechanic so if you have multiple tools trying to perform git commands you'll likely run into some conflicts. This is a limitation of git and not something we can do anything about. That said, while it may affect your git experience in Komodo, it should not cause crashes or freezes. The file update checks happen in the background.

**Comment by quintijn** [comment]
I will go on using Komodo on and off the coming days and I will report whether the problems return or not...

In the meantime it is not clear to me why komodo is checking git files while I thought I disabled the source code control althogether...

**Comment by Naatan** [comment]
In this case it might simply be looking at the files regardless of VCS. I'm not familiar enough with Windows to know why that might cause locks though, or why tgitcache would care.

**Comment by Defman21** [comment]
It doesn't look like you've disabled git cvs in Komodo: the checkbox is still enabled.

![image](https://cloud.githubusercontent.com/assets/7100645/24670155/b599066a-1975-11e7-836c-b42a83ee0769.png)

**Comment by quintijn** [comment]
Sorry, I disabled Git support by Komodo just now. I trust this problem is solved by now.
