### ISSUE TITLE
Popup Window Size

### ISSUE THREAD

**Issue by jaylitten** [Komodo/KomodoEdit#2408]
### Short Summary
A simple request. When previewing a webpage inside the Komodo browser in Edit 10 for Mac, the popup dialogue box needs to be longer. At this point, the OK button is only partially visible.

### Steps to Reproduce
run any alert command on a web page.

For instance, ...

<script>
		alert("Trump sucks!");
</script>

### Expected results

I expected the OK button to be fully visible in the popup window that appears.

### Actual results

The OK button is only partially visible.

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 

Komodo Edit, version 10.2.1, build 17670, platform macosx Sierra version 10.12.3. 

![komodo-popup](https://cloud.githubusercontent.com/assets/16841852/24120972/bd9d3358-0d73-11e7-8ec5-56d1bcac7d40.png)

Thank you!

**Comment by Defman21** [comment]
#2445
