### ISSUE TITLE
Support nested tabstops in snippets

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2410]
This is what it would look like:
`[[%tabstop:foo, [[%tabstop:bar]]]]`
Why it's useful:
Rather than tabbing through a list of optional tabstops, you can wrap all of them in one (like above) and either write/skip the first tabstop or tab into it and start filling in the options vars of your new function.

I'm sure there's more but I don't want to spend more time on figuring them out.

**Comment by Defman21** [comment]
Very useful for wrapping optional arguments!

**Comment by cgchoffman** [comment]
> Very useful for wrapping optional arguments!

Agreed.  That was the use case I came across as well.

**Comment by cgchoffman** [comment]
So I'm not sure what happened. I don't think I fixed this but this is already supported.  Even the snippet I provided works.
