### ISSUE TITLE
Komodo doesn't seem to understand GOPATH set by ActiveGo installer

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2413]
### Steps to Reproduce

- Install ActiveGo
- Open Komodo

### Expected results

There to be one path in the `GOPATH` variable

### Actual results

`GOPATH` is `C:\Users\cgcho\Projects\ActiveGo\;C:\ActiveGo\gopath`

which results in the following error in Komodos logs when you open the prefs
`pref.pref-golang: The GOPATH environment variable is set but C:\Users\cgcho\Projects\ActiveGo\;C:\ActiveGo\gopath doesn't name a directory`

**Comment by Naatan** [comment]
This is a warning, and it does not seem to prevent anything from working.
