### ISSUE TITLE
Gofmt isn't working

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2415]
### Short Summary

I tried this with a community Windows GO installer and ActiveGo

### Steps to Reproduce

Install Go
open a Go file
right click > Format > GOfmt

### Expected results

Go formatted

### Actual results

```
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIFormatter.format]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://komodo/content/formatters/formatters.js :: _formatViewWithFormatterAndContext :: line 132"  data: no]
                       Tue Mar 21 2017 15:01:28 GMT-0700 (Pacific Standard Time)
```

**Comment by Naatan** [comment]
Fixed with https://github.com/Komodo/KomodoIDE/commit/d09c29c853bff12041ab5b7e70be4e5b9b89a898
