### ISSUE TITLE
Refactoring: Rename Class Member: Replace With field is missing

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#242]
- open a refactoring support language file
- right click on a variable
- refactoring > Rename class member

Expect: A *Find What* and *Replace With* field

Actual:  There is only a *Find What* field.

**Comment by Naatan** [comment]
Fixed on IDE repo. (https://github.com/Komodo/KomodoIDE/commit/3b50f20ae4a2ff6e2ee2522dae4b25b4391ed284)

**Comment by tonyattwood** [comment]
Hi,

What do  you think  about  that ornaments? Please take a  look and tell me whether you like  them, here  is the link <http://favor.tiffanyvergato.com/e4fumq>


Yours sincerely, tony.attwood@ntlworld.com
