### ISSUE TITLE
lagging cursor move with XML files

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#2423]
### Short Summary
Lagging cursor move with XML files

Have a look at the video, notice how the holding down and up arrow keys make moving the current line up/down jump around with the XML file
OTOH the same with a python file is nice and smooth

### Steps to Reproduce
open https://github.com/zopefoundation/zope.formlib/blob/master/src/zope/formlib/configure.zcml
open a pyparsing.py (200K ish python code)
I recorded the video with a pristine
Komodo Edit, version 10.2.1, build 17670, platform linux-x86_64.
but experience the same with
Komodo IDE, version 10.2.1, build 89853, platform linux-x86_64.

### Expected results
smooth scrolling in all file types

### Platform Information

Komodo Edit, version 10.2.1, build 17670, platform linux-x86_64.

### Additional Information

https://www.youtube.com/watch?v=LBtsDild_Wk

**Comment by mitchell-as** [comment]
Thanks for the report. It looks like Komodo 10 introduced the slowdown. Moving around in K9 is as smooth as butter.

**Comment by mitchell-as** [comment]
Note to self: turning off 'edit matching tags' and 'edit matching delimiter' has no effect. Scrolling is still slow.

**Comment by Naatan** [comment]
Marking this as a priority as I think this might be where all our slowdown reports have been coming from. If the fix is simple enough we should try and include it for 10.2.2.

Thanks for the great report @agroszer !

**Comment by agroszer** [comment]
if that's the cause for most cursor move lags

ship it guys!

**Comment by Naatan** [comment]
That's definitely the plan, but we don't rush releases unless there is something preventing Komodo from running outright.

That said, nightly is up: http://downloads.activestate.com/Komodo/nightly/komodoide/latest/
