### ISSUE TITLE
error message produces irrelevant info regardless of actual error

### ISSUE THREAD

**Issue by WheelDogs** [Komodo/KomodoEdit#2425]
While debugging tcl script, the following text occurs regardless of what produced the error. With the exception of the first line of the text, the remaining text seem irrelevant. Standard tcl conveys stack info, the name of the script, etc.

### Steps to Reproduce

Try it with any tcl code

### Expected results
can't read "criteria(Group_Name)": no such element in array
can't read "criteria(Group_Name)": no such element in array
    while executing
"if {$criteria($column) != ""} {append $sqlcmd " AND $column='$criteria($column)'"}"
    (procedure "_btn_selectParticipants" line 12)
    invoked from within
"_btn_selectParticipants"
    (in namespace inscope "::sctn_rstr_edit" script line 1)
    invoked from within
"::namespace inscope ::sctn_rstr_edit _btn_selectParticipants"
    invoked from within
"._label_Participants invoke "
    invoked from within
"._label_Participants instate !disabled { ._label_Participants invoke } "
    invoked from within
"._label_Participants instate pressed { ._label_Participants state !pressed; ._label_Participants instate !disabled { ._label_Participants invoke } } "
    (command bound to event)

### Actual results

can't read "criteria(Group_Name)": no such element in array
wrong # args: should be "info functions ?pattern?"
    while executing
"DbgNub_infoCmd function bgerror -type -name -args"
    ("uplevel" body line 1)
    invoked from within
"DbgNub_uplevelCmd DbgNub_infoCmd $args"
    invoked from within
"info function bgerror -type -name -args"
    ("uplevel" body line 1)
    invoked from within
"DbgNub_uplevelCmd \#$level [list info function $namex -type -name -args]"

### Platform Information

*Komodo  IDE?* 
*Komodo Version 10.2.1
*MS Win10

**Comment by cgchoffman** [comment]
This report is too ambiguous. Please follow the report outline.

I've refiled so the devs who end up working on this don't have to do unnecessary legwork/research because the reporter didn't file a proper report.
#2426
