### ISSUE TITLE
IDE 10.2 Rx Toolkit not matching semicolon

### ISSUE THREAD

**Issue by cdcmicro** [Komodo/KomodoEdit#2429]
### Short Summary

In the Rx Toolkit, the Rx pattern includes a semicolon, but it is not highlighted in the Search Text.

### Steps to Reproduce

Rx string is `(&*#[\d]+;?\b)`

![screenshot_032917_041328_pm](https://cloud.githubusercontent.com/assets/13684992/24480713/a684de0e-149a-11e7-8c45-1c6b64a9aa00.jpg)

### Expected results

In the highlighted results, the trailing semis in `&#39;` and `#1010;` should be highlighted as part of the match.

### Actual results

Semicolons not highlighted.  In my perl code, the semis are matched as expected.

### Platform Information

Komodo IDE, version 10.2.1, build 89853, platform win32-x86.
Built on Wed Mar 08 12:38:48 2017.

### Additional Info

The goal is to be able to capture `#1010`, `#1010;`, and `&#39;`

**Comment by Naatan** [comment]
The problem is with your regex. `\b` won't work with `;` as ;` is not a "word" character, least that's my interpretation.

It works without the `\b`.

**Comment by cdcmicro** [comment]
Apologies for dumb user error.  Should have been a forum post.

**Comment by Naatan** [comment]
No worries :)
