### ISSUE TITLE
Show Editor Tabs menu option still selected after being deselected

### ISSUE THREAD

**Issue by mjross** [Komodo/KomodoEdit#2432]
### Short Summary
The main menu > View > Toolbars > Show Editor Tabs menu option is still selected after being deselected.

### Steps to Reproduce
When I go to main menu > View > Toolbars, the option "Show Editor Tabs" is selected (i.e., ticked), as I would expect, because I see under the blue toolbar, near the middle, three icons, for "New Tab", "List all tabs", and "New Tab" (but this one represented by a plus sign). When I deselect that option, those three icons disappear, as expected. But when I return to that Toolbars menu, the option is still shown as being selected. 

### Expected results
The option "Show Editor Tabs" menu option should be deselected.

### Actual results
The option "Show Editor Tabs" menu option is still selected.

### Platform Information
Komodo IDE 10.2.1 on Windows 10 Pro

### Attachments
"Show Editor Tabs menu option behavior.png":
![show editor tabs menu option behavior](https://cloud.githubusercontent.com/assets/829492/24534909/13d4c7e6-158e-11e7-8dd9-4828fa6f0937.png)

"C:\Users\Michael\AppData\Local\ActiveState\KomodoIDE\10.2\pystderr.log":
[pystderr.log.txt](https://github.com/Komodo/KomodoEdit/files/884412/pystderr.log.txt)

**Comment by mitchell-as** [comment]
How strange, I cannot reproduce this on Linux. It might be a Windows-only issue. @cgchoffman can you reproduce this?

**Comment by Naatan** [comment]
This is being handled in #94. Thanks for reporting, regardless!

**Comment by mjross** [comment]
Sorry for submitting a duplicate issue. Nothing promising came up when I did a search.

**Comment by Naatan** [comment]
No worries :)
