### ISSUE TITLE
Toolbox HTML anchor tags in wrong case and space missing in "w/Dialog"

### ISSUE THREAD

**Issue by mjross** [Komodo/KomodoEdit#2433]
### Short Summary
In the right pane, in the Toolbox section, in the HTML category, there are some errata:

1) All of the tag names are in lowercase, except the two anchor tags, which are `<A>`. They both should be `<a>`, to be consistent with the others.

2) For the seven instances of the string "w/Dialog", there should be a space between the "w/" and the "Dialog" since they are two words, namely, an abbreviation of "with Dialog". See examples at https://www.urbandictionary.com/define.php?term=w%2F.

### Platform Information
Komodo IDE 10.2.1 on Windows 10 Pro

### Attachments
![toolbox html tags errata](https://cloud.githubusercontent.com/assets/829492/24574576/46c18936-1652-11e7-83a0-97ee129f9fcd.png)

**Comment by Defman21** [comment]
@Naatan should I fix *.komodotool as well? I've fixed *.ktf

**Comment by Naatan** [comment]
What do you mean? Change ktf to komodotool? Sure if you like.

**Comment by Defman21** [comment]
There are komododool files left in https://github.com/Komodo/KomodoEdit/tree/master/src/samples/tools/HTML
Should I make changes to them as well? I don't think they are being used at all.

**Comment by Naatan** [comment]
Nah don't worry about it. And for the record - .komodotool is the new format, .ktf is the old.

**Comment by Defman21** [comment]
Aha, gotcha.
