### ISSUE TITLE
Fold Lines will not dissapear

### ISSUE THREAD

**Issue by Alcyros11** [Komodo/KomodoEdit#2434]
![Uploading error1.PNG…]()

### Short Summary
Fold Lines stay on even when checkbox is unchecked, This problem was the same with earlier versions of Komodo edit, I have wasted so much time trying to fix this, reinstalling etc and it is not changing it, it is not good on my eyes lol, screenshot attached
![system](https://cloud.githubusercontent.com/assets/26843243/24581735/abc23202-1753-11e7-851c-f19afe1c3279.PNG)

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* Latest
*Operating System (and version)?* see screenshot

**Comment by Alcyros11** [comment]
![error1](https://cloud.githubusercontent.com/assets/26843243/24581743/da349008-1753-11e7-9ca0-45633a651266.PNG)

**Comment by Alcyros11** [comment]
It is quite frustrating not being able to turn these lines off, I am on the trial version and will buy the full version if this issue can be resolved as I really like Komodo, however I will have to move on to another editor if I cannot sort this

**Comment by Naatan** [comment]
Hi, we have an issue open here which should effectively resolve yours -  https://github.com/Komodo/KomodoEdit/issues/2377

**Comment by Defman21** [comment]
But he can't even disable it.

**Comment by Naatan** [comment]
No you cannot disable it, that is by design. But the color contrast is terrible, once that is fixed disabling it should no longer be desirable.

**Comment by Defman21** [comment]
There's the "Use horizontal lines on folds" thing and I thought that this should hide folds when it's unchecked.

**Comment by Defman21** [comment]
And it's actually working for me, huh. I just had to re-open a file with some folds.

**Comment by Alcyros11** [comment]
The color contrast is fine for me, it suits me, i guess everyone is different, the problem is there is a checkbox saying to turn these lines on/off but it doesnt work :/

**Comment by mitchell-as** [comment]
Confirmed as a bug. Sorry for the confusion @Alcyros11 .

**Comment by mitchell-as** [comment]
This appears to have been fixed. I cannot reproduce it any more in 10.2.x or 11.

**Comment by Alcyros11** [comment]
Hi Mitchell, I just did a fresh install of 10.2.3 and it is still doing it :( it has been months since I reported this do you know of any solutions here? Here is a fresh screen shot from tonight
![bug-komodo](https://user-images.githubusercontent.com/26843243/29496577-de20c678-8607-11e7-8a60-cecff0854ef1.PNG)

**Comment by Alcyros11** [comment]
You can see the "use horizontal lines on folds" checkbox is not checked, yet those fold lines are still there in the new update :(
