### ISSUE TITLE
Support for 1 space instead of a tab to Global Indentation Settings

### ISSUE THREAD

**Issue by pm3d** [Komodo/KomodoEdit#244]
I'd like a feature in KomodoEdit under the Tabs view that says:
Actively replace Tabs with spaces (except in .py files)
or maybe something like
Actively replace Tabs with [      4 ] spaces for the following extensions
[multi-select list box of languages/extensions]

I have no idea how to go about implementing this.
![globalindent](https://cloud.githubusercontent.com/assets/8332828/7445313/6f78aace-f17b-11e4-8f5f-16b728a7c874.png):

This is related to: save with \n or save with \n\r

**Comment by Defman21** [comment]
Click "Show Advanced".

**Comment by pm3d** [comment]
Show advanced, where?

**Comment by pm3d** [comment]
I see where, but this doesn't fix the problem.  Though it shows tabs as a single space, it will not actively convert tabs to spaces

**Comment by Defman21** [comment]
It was my fault, sorry. I didn't read your message completely. I don't see this feature anywhere with "Show Advanced". This is kinda of enhancement :smiley:

**Comment by cgchoffman** [comment]
No, Defman21, you were correct.  Show Advanced will give you "per Language indentation settings" under Editor > Indentation.  See this FAQ for more information: https://community.activestate.com/taxonomy/term/559.  To then associate file extensions with a language, use the File Association Preferences.  

It's best if you ask for assistance in the [forums](http://forum.komodoide.com/) first.  If it is an enhancement or bug you'll be referred to the issue tracker to file a bug.

**Comment by pm3d** [comment]
No, Defman21, you were correct. Show Advanced will give you "per Language indentation settings" under Editor > Indentation.  <-- But the settings don't achieve what I'm asking about

**Comment by cgchoffman** [comment]
Ahh, you want to format your code.  Assuming you're using Komodo ide, Right click > Format > Python Reindent.  Also, Code menu > Format > Reindent.

Note:  To have the global prefs take efftect, you need to close and reopen the file.  Global pref changes only effect newly opened files, eg. files opened after the pref is set.

This feature is not in Komodo Edit.

**Comment by cgchoffman** [comment]
Note: Komodo has been around for a while and often Edit users have mocked up IDE functionality.  In the forums I've found a code formater that you can try: http://community.activestate.com/forum/format-document-script
