### ISSUE TITLE
Getting Started tutorial screen 9 Creating Files HTML not rendered

### ISSUE THREAD

**Issue by mjross** [Komodo/KomodoEdit#2442]
### Short Summary
In the "Getting Started" tutorial, on screen 9 ("Creating Files"), in the first task, part of the second bullet point appears as HTML that is, for some reason, not being rendered correctly. The second sentence begins "Select the" and continues with a block of HTML:
&lt;i class="icon icon-bars"&gt;&lt;/i&gt;&nbsp;&#042;&#042;&lt;a href="javascript:topWindow.require('tutorials').logicCallout('menuButton')"&gt;Menu button&lt;/a&gt;&#042;&#042;, then the &#042;&#042;File&#042;&#042; menu and then select &#042;&#042;New&#042;&#042; and then &#042;&#042;File from Template&#042;&#042;.

Also, the second task is numbered "1", just like the first task.

### Platform Information
Komodo IDE 10.2.1 on Windows 10 Pro

### Attachments
![getting started tutorial screen 9](https://cloud.githubusercontent.com/assets/829492/24627138/6185ff9e-1879-11e7-9208-5fdb497cf9b9.png)

**Comment by Naatan** [comment]
Huh, that's strange. Thanks for reporting!

**Comment by mjross** [comment]
Happy to help!

**Comment by Naatan** [comment]
Fixed with https://github.com/Komodo/KomodoIDE/commit/582a9f24c99df84eeb49f78cb09640856743fb49
