### ISSUE TITLE
Missing auto-completions for the cursor property

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#2444]
### Short Summary
Noticed I'm missing the 'not-allowed' value in the cursor auto-completion.
For the complete list of possible values
https://developer.mozilla.org/en-US/docs/Web/CSS/cursor

**Comment by acllenentine** [comment]
I'm having a very similar issue. At first I thought this had to do with the touchpad on my laptop being too sensistive. My gues is that You're correct, as the code tries to second guess my horrible spelling, for some reason it often gives up completely and ends up some where totally different in side that field. 

I have noticed that it also start cliking the the button the mouse sometimes in those moments.

**Comment by mitchell-as** [comment]
Thanks for the report. PRs welcome on this one :)

**Comment by Defman21** [comment]
Gonna fix it.
