### ISSUE TITLE
OK button in warning message (almost) not clickable

### ISSUE THREAD

**Issue by NinsgVeen** [Komodo/KomodoEdit#2445]
When opening a remote location that somehow isn't set right the error message that comes and has to be clicked away is very small, making it hard to click on the OK button.

#### Steps to Reproduce
I have a faulty set FTP connection in my FTP list(faulty password, or non existing domain). When connecting via 'Open remote directory' the connecting freezes, but after a while the error message appears.
When connecting through the sites plugin to the faulty FTP the error message comes fairly soon, but also is hard to click away.

#### Expected results
I expect the error message to come up, but easily clickable, so I can correct the FTP mistake.

#### Actual results
The OK button is hardly visible because the message window is too small, therefore takes a little searching if you're not used to it.

#### Platform Information
I use Komodo Edit 10.2.1 with the sites plugin on MacOS Sierra 10.12

#### Additional Information
sites message:
![screen shot 2017-04-04 at 14 14 06](https://cloud.githubusercontent.com/assets/2707235/24656150/8718d61e-1941-11e7-9f5e-7e8781183f6e.png)

through open remote directory
![screen shot 2017-04-04 at 14 17 07](https://cloud.githubusercontent.com/assets/2707235/24656149/87142b96-1941-11e7-906f-0a5a34c680a5.png)

**Comment by mitchell-as** [comment]
Thanks for the report.
