### ISSUE TITLE
Exception when moving file

### ISSUE THREAD

**Issue by jhihn** [Komodo/KomodoEdit#2448]
### Short Summary
I had a file in ~ that I wanted to move to ~/subdir/subdir
I right clicked on the file tab and selected move to...
I used finder to open the destination directory and clicked save.

[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIDocument.getUnsavedChanges]" nsresult: "0x80004005 (NS_ERROR_FAILURE)" location: "JS frame :: chrome://komodo/content/project/peFile.js :: peFile.prototype.doCommand :: line 178" data: no]
Tue Apr 04 2017 13:29:29 GMT-0400 (EDT)

### Steps to Reproduce
See above.
I repeated this action several times.
Each time I got an exception.
I've reproduced this 100% of the time

### Expected results
The file to be moved without error

### Actual results
It in fact was moved, apparently before the error occurred (as confirmed by `ls`) But it was scary because when you look for it, it's gone from the old location, as you don't expect an exception after the move.

### Platform Information
OSX 10.12.3 (16D32)
Komodo IDE, version 10.2.2, build 89871, platform macosx.
Built on Thu Mar 30 00:11:01 2017.

### Additional Information
It also is a bother that the exception dialog doesn't have any buttons. I had to figure out how to hit enter to close it.

**Comment by mitchell-as** [comment]
Thanks for the report.

**Comment by Naatan** [comment]
Possibly related to #1071

**Comment by cgchoffman** [comment]
I can't reproduce this.

**Comment by cgchoffman** [comment]
I tried this in Edit, IDE 11 on OSX and Windows
