### ISSUE TITLE
build.py: change bzip to gzip-v2

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#2449]
Mozilla changed that (bzip -> gzip) so should we.

**Comment by Defman21** [comment]
https://github.com/Komodo/KomodoEdit/blob/master/mozilla/build.py#L2087

**Comment by Naatan** [comment]
Could you provide some more context? The idea is that most of the info we need is in the bug report. Your report would cause us to start looking and inferring and that is both time consuming and error prone. Follow the guidelines for issue reports please.

**Comment by Defman21** [comment]
Mozilla changed their upstream archives and now they are using bzip-v2 format for mozilla-release hg archive. Currently it tries to fetch gzip, which no longer exists. It should only affect those who want to build Komodo themselves.

**Comment by Naatan** [comment]
We'll need to check where the archive is coming from, since the AS server still use gzip.

**Comment by Defman21** [comment]
There's a dedicated logic for AS server, so it won't affect your stuff.
