### ISSUE TITLE
Actively replace Tabs with spaces (except in .py files) or maybe something like Actively replace Tabs with [ 4 ] spaces for the following extensions

### ISSUE THREAD

**Issue by pm3d** [Komodo/KomodoEdit#245]
Actively replace Tabs with spaces (except in .py files)
or maybe something like
Actively replace Tabs with [ 4 ] spaces for the following extensions

There is no way to "Actively replace Tabs with spaces", despite the recent issue being closed

There is a setting that says "Prefer tabs over spaces" but there is no "Actively replace tabs with [ x ] spaces" .. meaning I want every indention Tab to be converted into a [# of, or 1] space character on load, and, optionally any time I hit tab

**Comment by pm3d** [comment]
Uploading a 720p screencast about this issue to http://youtu.be/D7faz1TI71s

**Comment by cgchoffman** [comment]
Hi @pm3d, this is another request for formatting.  See my comments in the other issue you filed: https://github.com/Komodo/KomodoEdit/issues/244#issuecomment-98791972

**Comment by pm3d** [comment]
This NOT a request for formatting, it's a request for sanity

**Comment by cgchoffman** [comment]
@pm3d the formatting tool in Komodo IDE does what you're requesting.  Give a try.
