### ISSUE TITLE
js console history lost when enter is press with no input

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2458]
### Short Summary

If you enter an empty command in the js console it deletes all command history

### Steps to Reproduce

- enter some commands in the js console
- make sure you can cycle through them by pressing up arrow
- enter a blank command (ie. press enter when there is no text in the input field)

### Expected results

Either nothing, don't register the key press or it takes the blank input but I still have history

### Actual results

Input is taken and processed which results in all command history gone.

**Comment by Defman21** [comment]
Sounds like a PR thing!
