### ISSUE TITLE
Komodo ide hangs on windows 8

### ISSUE THREAD

**Issue by bilikaz** [Komodo/KomodoEdit#246]
when i try to open all those files at once (8 php files) komodo stops responding, editor is still active, but rest part doesn't work

**Comment by bilikaz** [comment]
![hang](https://cloud.githubusercontent.com/assets/5980498/7454480/b1ddf2a0-f27c-11e4-965f-40527f196cf6.png)

![hang1](https://cloud.githubusercontent.com/assets/5980498/7454481/b2049ff4-f27c-11e4-890a-debe7ab7582f.png)
![hang2](https://cloud.githubusercontent.com/assets/5980498/7454482/b205517e-f27c-11e4-97b1-9300c28534ab.png)

**Comment by bilikaz** [comment]
link to zip http://vbtech.eu/hang.zip

**Comment by cgchoffman** [comment]
I cannot reproduce this.  Can you please try [resetting your user profile](https://community.activestate.com/faq/komodo-file-locations#pref_reset) then see if you can reproduce the issue?  If you are still able to reproduce the issue, I will need you to provide more details in the steps to reproducing the issue.

**Comment by bilikaz** [comment]
I found out that it's basically related somehow with graphics and each time komodo hangs up i get error in error log "Display driver igfx stopped responding and has successfully recovered."  going to look for driver updates maybe it will help

**Comment by bilikaz** [comment]
still no progress as i noticed there is some kind of code intelligence issue going to reinstall komodo and clear all profile data

**Comment by bilikaz** [comment]
didn't helped..
[2015-05-05 11:46:47,743] [WARNING] views: Inconsistent view count in view_closed event
[2015-05-05 11:46:47,868] [ERROR] codeintel.komodo.KoCodeIntelManager: Error reading data from codeintel
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\components\koCodeIntel.py", line 1161, in run
    ch = self.pipe.read(1)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\win32_named_pipe.py", line 212, in read
    raise ctypes.WinError(ctypes.get_last_error())
WindowsError: [Error 109] The pipe has been ended.

all time same issue, even when standing still any suggestions where to look else? i can just browse throw menu, or read log file and after some time it stops forking with same error...

**Comment by bilikaz** [comment]
hmm reinstal of windows helped.. i gues there was some problems with registry... of old edit versions i used before

**Comment by cgchoffman** [comment]
You resinstalled Windows?  Or resinstalled Komodo?  It sounds more like there was something wrong with your OS and would have run into issues with other software at some point as well.  I don't think a registry problem would have results like this.
