### ISSUE TITLE
editor highlights contents of tag in XML when selecting tag name

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2460]
### Short Summary

I've come across a very strange issue.  Disabling "Edit matching delimiter on select" has no effect.  10.2.2 for now as I'm not sure what this effects exactly.  Seems like it might be 10.2.2 worthy.

See gif:
![no-idea](https://cloud.githubusercontent.com/assets/655154/24775526/1dd62cc8-1ad2-11e7-9d65-6be966573437.GIF)

### Steps to Reproduce

See Gif.

**Comment by mitchell-as** [comment]
Would you please attach the file in question? I cannot reproduce this on a simple HTML file. Thanks.

And the preference is in Languages > HTML. Something about selecting matching tags.

**Comment by cgchoffman** [comment]
The file is https://github.com/Komodo/KomodoIDE/blob/master//src/prefs/prefs.p.xml

Disabling *Html > Edit matching tags on select* resolves the issue.  Note that if I use the keyboard (arrow + Shift) to highlight the tag I have no issue.

**Comment by Naatan** [comment]
I'm unable to reproduce this. Can you try on a clean profile?

**Comment by cgchoffman** [comment]
Still happens with a clean profile.  It happens in XML and HTML files if that matters.

**Comment by Naatan** [comment]
Is it as simple as opening an XML based file and doing what you did in the gif or is there more to it?

**Comment by cgchoffman** [comment]
Essentially ya.  I started Komodo with a fresh profile, open the Sample Project in the Project pane Gear menu, then opened the HTML file in that project.  Just have to select the name of the tag after that.
Note:
- don't select the preceding `<`
- don't select the space after the name if there is one
- only select the name, ie, `div` in `<div id="pizza">`

**Comment by Naatan** [comment]
Reproduced on Windows. Strangely only happens when manually drawing the selection with the mouse, not when double clicking or using the keyboard.
