### ISSUE TITLE
UI: Logs dialog loses title bar if dialog is opened while already open

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2464]
### Short Summary

If the dialog is already open and you do *Help > Troubleshooting > View Log File* the dialog will lose the title bar,  including the close, minimize and maximize buttons.

### Platform Information

This is on Windows.  Happens on Master or 10.2

**Comment by Defman21** [comment]
I remember it was already filed. Probably by @babobski

**Comment by Defman21** [comment]
https://github.com/Komodo/KomodoEdit/issues/1562

Yep. Even Windows only :)
