### ISSUE TITLE
Minimap doesn't move when scrolling via wheel in editor

### ISSUE THREAD

**Issue by lagbox** [Komodo/KomodoEdit#2467]
### Short Summary

The minimap doesn't move when the editor itself scrolls via mouse wheel.

### Steps to Reproduce

Show the minimap.
Use your mouse wheel in the editor (not the minimap).
The editor will move, but the minimap will not update.

### Expected results

The minimap to update its position relative to the editors new position.

### Actual results

Minimap doesn't move.

### Platform Information

*Komodo Edit or IDE?* Komodo IDE
*Komodo Version?* version 10.2.2, build 89878, platform linux-x86_64. Built on Tue Apr 4 23:34:04 2017
*Operating System (and version)?* Ubuntu 16.10

### Additional Information

Same behavior in safe-mode.

**Comment by Defman21** [comment]
It worked fine in Komodo 9: minimap were following your current viewport.

**Comment by mitchell-as** [comment]
This is the commit that breaks minimap mouse scrolling. I'm not sure why. https://github.com/Komodo/KomodoEdit/commit/dd6ceab77b4a1ba6cbd8327a5379c17ea35e7ca2

**Comment by mjainQA** [comment]
I am still able to reproduce this. Is it fixed?

**Comment by lagbox** [comment]
@mjainQA  I might be wrong, but I would assume it is fixed, but hasn't made it into a nightly yet.

**Comment by cgchoffman** [comment]
@lagbox, this should have been fixed in the nightly.  Apologies for not making that clear.  It looks like this never made it into branch `10.2.x` (which is the branch that nightlies build from...fun fact).  Nice catch @mjainQA.  Just going to confirm that it's not there then i'll integrate into 10.2.x.

**Comment by cgchoffman** [comment]
I cherry picked the commit into 10.2.x.  @lagbox we won't be making a new nightly before we release 10.2.2 but 10.2.2 is coming really soon.

This cherry-pick MIGHT get rejected, just a heads up.  It's cutting it a little close even for me.

**Comment by lagbox** [comment]
No worries here my friend :-)
