### ISSUE TITLE
Import Sublime Snippets Error - Komodo IDE

### ISSUE THREAD

**Issue by stikx2432** [Komodo/KomodoEdit#2471]
### Short Summary

Import Sublime Snippets Folder error.

### Steps to Reproduce

Import https://github.com/jprichardson/sublime-js-snippets 

### Expected results

Import folder of sublime snippets in to Komodo

### Actual results
I noticed that a new folder was created called 'sublime-converted-snippets ' in the folder of the snippets I try to import.
A popup with the error below shows

Something went wrong importing your snippets: [Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [koIToolbox2Service.importDirectory]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: chrome://komodo/content/toolbox/toolbox2_command.js :: this.importSublimeSnippetFolder :: line 433"  data: no]

### Platform Information

IDE 10.2.1 + 10.2.2

### Additional Information

I only copied what was relevant from the log. 
```
[2017-04-09 12:49:08,323] [ERROR] sublime-converter: Folder Conversion Failed: global name 'WindowsError' is not defined
[2017-04-09 12:49:08,327] [ERROR] ko.toolbox2: 
-- EXCEPTION START --
Something went wrong importing your snippets: [Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [koIToolbox2Service.importDirectory]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: chrome://komodo/content/toolbox/toolbox2_command.js :: this.importSublimeSnippetFolder :: line 433"  data: no]
+ 0 (string) Something went wrong importing your snippets: [Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [koIToolbox2Service.importDirectory]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: chrome://komodo/content/toolbox/toolbox2_command.js :: this.importSublimeSnippetFolder :: line 433"  data: no]
-- EXCEPTION END --
```

Also created a folder 'sublime-converted-snippets' in the folder of the snippets I was trying to import

Something went wrong importing your snippets: [Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [koIToolbox2Service.importDirectory]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: chrome://komodo/content/toolbox/toolbox2_command.js :: this.importSublimeSnippetFolder :: line 433"  data: no]

**Comment by Defman21** [comment]
Please attach your log file as well. (Help - Troubleshooting - View Log File).

**Comment by Naatan** [comment]
> Actual results
> Error

Please supply the actual error you received.

> Also created a folder 'sublime-converted-snippets' in the folder of the snippets I was trying to import

That is not a valid way of importing sublime snippets, it will certainly not work.

Have you tried importing the snippets one by one?

**Comment by Naatan** [comment]
Reproduced the issue. @cgchoffman I think there might be a problem with unix paths, as I can repro even with an empty directory.

**Comment by cgchoffman** [comment]
Thanks for the report @stikx2432: https://github.com/Komodo/KomodoIDE/commit/862f55db2947cf119e5e4177895fc99a1b513e41

**Comment by Defman21** [comment]
lol

**Comment by Naatan** [comment]
We're testing out a new tool. @cgchoffman had to tame it.

**Comment by Defman21** [comment]
gotcha

**Comment by cgchoffman** [comment]
@stikx2432, sorry for the noise.  Here's a helpful message though!  This fix will be in a nightly tomorrow that you can try out if you're interested. I'll set a reminder to my self to notify here when it's ready.

**Comment by stikx2432** [comment]
Sounds good to me.

**Comment by cgchoffman** [comment]
Bits has been staged,  They will be accessible here around 12pm (lunch) PST: http://downloads.activestate.com/Komodo/nightly/komodoide/latest-10.2.x/

Should be build number 89881.
