### ISSUE TITLE
Support newer version of JShint

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2479]
### Short Summary

This came up in Komodo/KomodoEdit#1851 but i don't think any one filed a bug about it.  When you download the latest jshint using NPM then point Komodo at `npm\node_modules\jshint\dist\jshint.js` or `jshint-rhino.js` no syntax checking occurs.

### Steps to Reproduce

1. npm install -g jshint
1. point *Prefs > Syntax & Spell Checking > Lang Specific > JSHint: custom linter* to `C:\Users\Usersname\AppData\Roaming\npm\node_modules\jshint\dist\jshint.js`.
1. CLick ok

### Expected results

To have syntax Checking

### Actual results

No syntax checking ever happens.

**Comment by Defman21** [comment]
```
[2016-07-26 18:29:46,886] [WARNING] koJavaScriptLinter: Error in jshint: stderr: /usr/local/lib/node_modules/jshint/dist/jshint.js:2198:8 TypeError: Array is undefined
, command was: [u'/home/defman/Apps/Komodo/latest/lib/mozilla/js', u'/home/defman/Apps/Komodo/latest/lib/support/lint/javascript/lintWrapper.js', u'--include=/usr/local/lib/node_modules/jshint/dist/', u'--jshint-basename=jshint.js', u'moz=true', u'unused=true', u'esnext=true', 'node=1', 'strict=false']
```

Mozilla's js engine does not support Array as of version 35 (there's a special version of jshint without Arrays, but it doesn't work either), may be if we could update the mozilla version this would be fixed.
