### ISSUE TITLE
Encoding error when debugging Python on Windows

### ISSUE THREAD

**Issue by born4web** [Komodo/KomodoEdit#2480]
### Short Summary
- Fresh install of KomodoIDE 9.3 then after support recommended tried 10.2
- Windows 10 with Czech language support
- every Python program I tried to run in IDE produced that error (picture of traceback included for both version of KomodoIDE

### Steps to Reproduce
Every Python program I try to run produce the same error

### Expected results
Run Python program

### Actual results
Traceback on screen shot

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 

### Additional Information

![importantinfofromide93](https://cloud.githubusercontent.com/assets/16520049/24974762/a2396dae-1fc3-11e7-834f-31a2328d955b.JPG)
![importantinfofromide102](https://cloud.githubusercontent.com/assets/16520049/24974767/a654cf3c-1fc3-11e7-9d17-5fd9a0e8cccd.JPG)
[pystderr_version103_log.txt](https://github.com/Komodo/KomodoEdit/files/917570/pystderr_version103_log.txt)
[pystderr_version93_log.txt](https://github.com/Komodo/KomodoEdit/files/917571/pystderr_version93_log.txt)
[pystderr_version93_log.txt](https://github.com/Komodo/KomodoEdit/files/917572/pystderr_version93_log.txt)

**Comment by Naatan** [comment]
Seems there is an error in czech, could you translate?

```
error: [Errno 10054] Stávající připojení bylo vynuceně ukončeno vzdáleným hostitelem
```

**Comment by born4web** [comment]
I hope to translate it OK...

Existing connection was forcely ended by remote host

**Comment by born4web** [comment]
Another one: 
WindowsError: [Error 109] PĹ™esmÄ›rovĂˇnĂ­ bylo ukonÄŤeno.

translation: Redirection was ended

I have no idea why those errors are thre

**Comment by Naatan** [comment]
Are you remote debugging or are you running the script locally (ie. just hitting the play button)?

**Comment by born4web** [comment]
Just hit the play button on local script, no remote debuging. Thats why I do not understand why they are those errors...

**Comment by Naatan** [comment]
@mitchell-as any ideas?

**Comment by mitchell-as** [comment]
Hi @born4web. Please do the following:

1. Go to Edit > Preferences > Languages > Python.
2. At the bottom there is a section called Debugger Logging.
3. Change the path to a path you can access.
4. Try pressing the play button on your script that is causing the error.
5. Check the path you set in the Debugger Logging preference. There should be a debug log there.
6. Attach that log in a reply to this ticket.

Thanks!

**Comment by born4web** [comment]
Log file is not created

This is error I receive on debug window in KomodoIDE

----------------------
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\support\dbgp\bin\pydbgp.py", line 307, in <module>
    sys.exit( main(sys.argv) )
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\support\dbgp\bin\pydbgp.py", line 293, in main
    client.connect(host, port, '__main__', args)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\support\dbgp\pythonlib\dbgp\client.py", line 2321, in connect
    self.sendInit(name, args[0])
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\support\dbgp\pythonlib\dbgp\client.py", line 2513, in sendInit
    self.socket.send_response('<init %s/>' % _getAttrStr(attrs))
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\support\dbgp\pythonlib\dbgp\client.py", line 2247, in send_response
    self._socket.send(_encode_response(response))
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\support\dbgp\pythonlib\dbgp\client.py", line 122, in _encode_response
    return packet.encode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 319: ordinal not in range(128)

**Comment by mitchell-as** [comment]
Okay, so that is the full error message. Thank you and sorry for the trouble. I will dig into this.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoIDE/commit/c9182d25791fb7892b7315c8ebb93d450ab9073f

**Comment by born4web** [comment]
Hello the link is broken.

**Comment by Defman21** [comment]
It's a private repo so you can't see it.

**Comment by cgchoffman** [comment]
@born4web, there will be a nightly build with this patch available just after 12 pm PST.
http://downloads.activestate.com/Komodo/nightly/komodoide/
Confirm the build number is `89888` before downloading.

**Comment by born4web** [comment]
I have tested that release and it works good job :)

Will you be patching version 9 also? I do not have paid version 10 only version 9 of Komodo IDE...

Thanks Petr

**Comment by Naatan** [comment]
Unfortunately not no, we do not maintain older releases except for extremely critical bugs.

**Comment by born4web** [comment]
This sounds like critical bug :) I can not use version 9 on my Windows 10 computer :)

**Comment by Naatan** [comment]
By critical bug I mean Komodo stops working outright. The fact of the manner is Komodo 9 is no longer supported. I would suggest you contact support@activestate.com, they might be able to facilitate an upgrade for you.
