### ISSUE TITLE
sdk element.js parseOptions breaks ui/span

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2482]
### Short Summary

Can't start the First start wizard after this change: https://github.com/Komodo/KomodoIDE/commit/710ffd81bdba0d37501d119e8cf68f1ab34658ad#diff-d73fb095ff6474d4e7062ebacabf94ddL199

I attempted this patch but it breaks `listbox.addListCols`:
```
Index: C:\Users\cgcho\Projects\komodo\KomodoIDE\src\chrome\komodo\content\sdk\ui\element.js
--- a\chrome\komodo\content\sdk\ui\element.js
+++ b\chrome\komodo\content\sdk\ui\element.js
@@ -36,1 +36,1 @@
         {
-            this.attributes = options.attributes || options;
+            this.attributes = Object.assign(options.attributes || options, this.attributes);
             this.options = options.options || {};
```

With the above patch the following code breaks:
```
var listbox = require("ko/ui/listbox").create({ attributes: { rows : 4 } });
listbox.addListHeaders(["Name", "Desc","Paths","Detected"]);
listbox.addListCols(["testing", "blah blah", "menu", checkbox]); // Breaks here
```

**Comment by Naatan** [comment]
The code that is breaking for you is unrelated to the patch. It breaks because listcols don't take a string value, you can only pass attributes/options to it. I think you're confusing listcols with listcells.

**Comment by Naatan** [comment]
I'll use this bug for fixing the issue with attribute inheritance though.
