### ISSUE TITLE
"Replace" button misleading; also does another find

### ISSUE THREAD

**Issue by mjross** [Komodo/KomodoEdit#2483]
### Short Summary
In the Edit > Find dialog, the "Replace" button not only replaces the currently found instance of the search string, but it then automatically jumps ahead to the next instance of the string, if any, even though the user did not request for Komodo IDE to perform another find operation. Thus the button's label is misleading and should be replaced with "Replace and Find". Often a user wants to find and replace only the first instance and then make additional desired edits near that first instance, or simply verify that the replacement was correct, especially when using a regex. But instead, if the next instance is many lines below the first, then the replacement is now off the screen, and the user is forced to backtrack to it -- perhaps by changing the search string (to match the replacement value) and then searching backwards, which adds an extraneous entry to the "Find" field. A new button, labeled "Replace", should be added which would perform a replace operation and then stay put, so the user can see the replacement before optionally searching for the next instance.

### Platform Information
Komodo IDE 10.2.1 on Windows 10 Pro

**Comment by Naatan** [comment]
This is by design. If all you want to do is replace one single instance then why use find/replace at all? Just find and make your change then and there. I'm fairly certain this is how it's done in most if not all editors.

**Comment by mjross** [comment]
Yes, in the scenario that you describe – namely, the user knows that there is only one instance of the search string – then it would not make sense to use the full find/replace dialog, but instead just do a quick find (the Fast Find feature in Komodo IDE) and then change it manually. But more often than not, there are multiple instances within a file or the user does not know how many there are. I assumed that was clear from my mentioning of "next instance", but in my description I could have been explicit that I'm not talking about the scenario of just a single known instance.

In my experience, I have seen editors that also do the automatic find operation again, and others that give the user the option of replacing and staying put (as well as replacing and finding again). An example of the latter is jEdit, which I've been using for years now. Screenshot attached. Being able to execute the replace operation and see the results, for each particular instance, is extremely useful – particularly when doing complex regex replacements.  Countless times I have made a mistake in a regex pattern, and was quite thankful that the editor didn't (unintentionally) hide the problem from me by automatically jumping forward to the next instance more than one screenful of text away.

Does that make sense?

Perhaps it would be more appropriate if I were to file this as a feature request.

![jedit find and replace](https://cloud.githubusercontent.com/assets/829492/25050141/5a55bf1c-210b-11e7-9d4d-ca1a9a5f7a43.png)

**Comment by Naatan** [comment]
I think a feature idea on the forum would be appropriate. I personally feel that this is something the user has perfect control over; you can hit find first and then hit replace if you want to review changes. Additionally you can hit Replace All to get a result window which shows you what was replaced. I feel adding a Replace & Find button just adds layers of complication that aren't required.

**Comment by mjross** [comment]
But in order for the user to perform the replacement and then review the change to make sure that, say, the regex worked as intended, he has to backtrack to the instance that was just changed, which quite possibly has moved off the screen. So he has to page up and hope that he sees the changed text, or he has to use the find capability and type in a new search string that, he hopes, will match the result of the change, and alter the search dialog to search backwards. That's not my idea of perfect control, as it requires extra steps – all because there is no way to make the Replace feature just do the replace operation and not do anything else.

I don't see how layers of complication are added by the proposal. Naturally, making a change such as this would involve adding another button and some additional code behind the scenes. But to me it seems that the user interface would be made more clear, since the "Replace" button would do exactly that and nothing more, and the "Replace and Find" button would also do exactly what it advertises. And it would give more power to the user, since he could use one button or the other depending upon whether he wants to see and immediately verify the change.

Regarding the option of using "Replace All", that would solve some of the problem, but only if the results panel at the bottom showed the results of the changes. Yet when I tested it earlier, instead of the "after" text being displayed, it always shows the "before" text – which of course does not help the user who wants to review the changes and see if anything went wrong. Screenshots attached. (Since I'm so new to Komodo IDE, it is possible that there is some setting somewhere that I don't know about which could change it so that the "Replace All" result panel would show the "after" text instead.)

![replace all before](https://cloud.githubusercontent.com/assets/829492/25056574/6c374bbe-212f-11e7-8618-af211ea34d44.png)

![replace all after see panel at bottom](https://cloud.githubusercontent.com/assets/829492/25056580/743821da-212f-11e7-98cd-44112df49bbe.png)
