### ISSUE TITLE
Any Tcl source file with non-ascii character will fail the syntax checker

### ISSUE THREAD

**Issue by zoofood** [Komodo/KomodoEdit#2487]
[Sorry for lack of info, no further info was provided, although I can reach out to the original source if needed. -JR]

### Short Summary

Any source file with a non-ASCII character will cause a failure of the
syntax checker.

### Steps to Reproduce

Attempt to edit a file with a non-ASCII character.

### Expected results

Should not produce an error.

### Actual results

error

### Platform Information

Komodo IDE

**Comment by mitchell-as** [comment]
Do you think this is related to #839 @zoofood ?

**Comment by zoofood** [comment]
Oh yes, that is exactly the one! This can be closed, sorry for the dupes.
