### ISSUE TITLE
Can't share any documents using kopy.io

### ISSUE THREAD

**Issue by zoofood** [Komodo/KomodoEdit#2488]
This came in via ActiveState/appdirs#94.

### Short Summary

After the transition of kopy.io to https I can't share any documents on Komodo IDE.

### Platform Information

Komodo IDE

**Comment by cgchoffman** [comment]
Looks like the requests are timing out.  It takes a while for these errors to appear in the logs
```
[2017-04-18 11:10:38,651] [WARNING] kopy: kopy.io: HTTP Request Failed: 0
[2017-04-18 11:11:56,875] [WARNING] kopy: kopy.io: HTTP Request Failed: 0
[2017-04-18 11:12:35,023] [WARNING] kopy: kopy.io: HTTP Request Failed: 0
[2017-04-18 11:12:48,697] [WARNING] kopy: kopy.io: HTTP Request Failed: 0
```

**Comment by Naatan** [comment]
This commit doesn't need to go into 10.2.2 as I also changed the kopy.io server to still accept new shares on http so that older integrations don't break.

**Comment by mikhalenia** [comment]
Yes it was the redirect from http to https. Now it works. Thanks!

**Comment by mjainQA** [comment]
Verified on 10.2.2 RC3 macOS.

Added a test case to verify sharing code via Kopy.io over Secure connection.

**Comment by zoofood** [comment]
OK great.
