### ISSUE TITLE
Dialogs not resizing (possibly Windows only)

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2493]
I'm getting dialogs that won't fit their content.

The following snippet dropped into the JS Console will produce the image below the snippet:
```
ko.dialogs.okCancel("sdfsdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd")
```
![image](https://cloud.githubusercontent.com/assets/655154/25194891/c5e3b69c-24f0-11e7-90fb-10cacb25b47c.png)

Notes:
- If you click `Ok` then run the code again it will fit the text, to reproduce the issue you have to change the text input then it will open not showing all the content.

**Comment by Defman21** [comment]
It fits on Linux for me (both with native/komodo's decorations), so looks like a windows only issue.

**Comment by mjainQA** [comment]
Verified on Windows and macOS with 10.2.2 RC3.

Added a test case - http://testrail.activestate.com/testrail/index.php?/cases/view/173
