### ISSUE TITLE
Duplicate entries for creating file from template

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2501]
### Short Summary
Duplicate entries for Python are available for creating a file from Template

### Steps to Reproduce

I don't know how to reproduce this but somehow it shows up.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.2.2
*Operating System (and version)?* macOS

### Additional Information
![image](https://cloud.githubusercontent.com/assets/26605593/25206891/ad679636-251f-11e7-8a78-b2df1716eb77.png)

**Comment by cgchoffman** [comment]
Is this reproducible with a clean profile?
Help > Troubleshooting > Restart in Safe-Mode

**Comment by mjainQA** [comment]
Yes it is reproducible when Komodo was started in safe-mode.

**Comment by cgchoffman** [comment]
Are you sure Komodo started in Safe-mode?  The First Start Wizard should have appeared when Komodo started.  Also, could you try Linux and Windows?  I'm not seeing this in Windows.

**Comment by Naatan** [comment]
This entire feature is replaced in Komodo 11, not worth fixing in the interim.
