### ISSUE TITLE
Right arrow key is not expanding selection in Commando

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2505]
### Short Summary
Using right arrow key is not expanding selection in Commando as per the tip at the bottom. Right arrow key works after the main option is selected.

### Steps to Reproduce

1. Click on Commando
2. Select any option by single-clicking on it
3. Use right arrow key - notice nothing happens

### Expected results

Right arrow key should expand options else NO TIP should be displayed 

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.2.2 RC2
*Operating System (and version)?* macOS

### Additional Information
![image](https://cloud.githubusercontent.com/assets/26605593/25246796/9bb0fb6e-25bd-11e7-9cb3-c6f4434f58ac.png)

**Comment by Defman21** [comment]
The tip should not be there if `allowExpand` of an item is `false`. Should be pretty easy to fix though.
