### ISSUE TITLE
No autocomplete for javascript function/method inside class

### ISSUE THREAD

**Issue by alienator** [Komodo/KomodoEdit#2517]
in the first file I have:
class A {
 doSomething() {
 }
}

and in a second one:
var a = new A();

while type 'a.'  or 'a.do' doesn't show any suggestion from autocomplete.
if the first file looks like:

a = {
 doSomething: function() {
 }
}

then it works.

using Komodo Edit, version 10.2.1, build 17670, platform linux-x86_64.  in OpenSuse 42.2leap x64, gnome desktop

**Comment by Naatan** [comment]
Thanks for the report. This comes down to Komodo currently not supporting ES6 classes for codeintel. I've reported a new issue for this here:

https://github.com/Komodo/KomodoEdit/issues/2518

**Comment by alienator** [comment]
thanks, great job
