### ISSUE TITLE
Options 'Copy' or 'Move' are not working in Commando

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2519]
### Short Summary

Options 'Copy' or 'Move' are not working in Commando. Even if it does something in the background there are no notifications.

### Steps to Reproduce

1. Search for files in Commando
2. Select any file
3. Use right arrow key to display file options
4. Select copy or move

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.2.2 RC2
*Operating System (and version)?* macOS

### Additional Information
![image](https://cloud.githubusercontent.com/assets/26605593/25290453/f5739d26-2682-11e7-899e-8f48e0dd7295.png)

**Comment by Naatan** [comment]
I think this is technically working but it's meant to give you a feedback on how to paste it somewhere, which is the part that isnt working. This has likely been broken for quite a while.

**Comment by Defman21** [comment]
I think that Copy should be renamed to Copy to and Commando should ask for a path (or leave everything as is and just add "Paste here" item when there's a file (or files) waiting for their new place)

**Comment by Naatan** [comment]
> or leave everything as is and just add "Paste here" item when there's a file (or files) waiting for their new place

That's what it does, or is supposed to do.

**Comment by Defman21** [comment]
I'll try to fix that if you don't mind :)

**Comment by Defman21** [comment]
Haha there's the logic for it and the Paste option appears when you Copy/Move a file, though no tip were given to me.
