### ISSUE TITLE
Navigation menu labels inconsistent

### ISSUE THREAD

**Issue by mjross** [Komodo/KomodoEdit#2528]
### Short Summary
On the Navigation menu, the terminology is not consistent – specifically, sometimes the verb is "Go" and other times "Jump". For two others, neither verb is present.

In particular:
- For the labels "Jump to Matching Brace", "Jump to Corresponding Line (for Diff mode)", "Jump to Next Section", and "Jump to Previous Section", each "Jump" should be replaced with "Go".
- "Next Bookmark" should be changed to "Go to Next Bookmark". "Previous Bookmark" should be changed to "Go to Previous Bookmark".

### Platform Information
Komodo IDE 10.2.1 on Windows 10 Pro

### Attachments
![navigation menu](https://cloud.githubusercontent.com/assets/829492/25294835/9e1c1912-26a6-11e7-8039-bdc2a2a37bab.png)

**Comment by Defman21** [comment]
I'd rather use "Jump to" instead of "Go to" 😃 (there are much more references to jump action rather than go action). @Naatan your thoughts?

**Comment by mjross** [comment]
But "Go to" is shorter and more straightforward than "Jump to". I have never seen the phrase "Jump to" on a menu in any software application, so when I first saw it on the Komodo IDE Navigation menu, I was wondering if it meant something special, something more than simply "go to".
