### ISSUE TITLE
Can't Add new files to SCC despite checking the project out and creating the project file

### ISSUE THREAD

**Issue by i-shenl** [Komodo/KomodoEdit#2532]
### Short Summary

The Add menu item is greyed out when trying to add a new file to an SCC project before checking it in.

### Steps to Reproduce

1) Checkout a git project using File -> Source Control ->  Clone / Checkout project
2) set SCC Handler to git
3) Checkout this url:  https://github.com/i-shenl/learn-chaincode
4) point it to a folder you want to check it out to
5) checkout the project
6) Right click on the "start" node and select "New File"
7) Add to this file, and save it to the "start" directory under "learn-chaincode"
8) Right click on the tab above that has the name of the file you just created
9) select "Source Control" and "Add File"

### Expected results

Should be able to add this file because it's new

### Actual results

The Add File option is greyed out.

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?*

**Comment by cgchoffman** [comment]
I'm proposing this instead: https://github.com/Komodo/KomodoEdit/issues/2531

**Comment by Naatan** [comment]
Closing in favour of #2531
