### ISSUE TITLE
SCC statusbar: does not show branches with / in them

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#2533]
### Short Summary

title.

### Steps to Reproduce

Create a git repository with 3 branches:

```
* master
* fix/test
* test
```

### Expected results

To see all of them in the SCC statusbar.

### Actual results

Only `master` and `test` are visible.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* latest nightly
*Operating System (and version)?* elementary os 0.4

**Comment by mitchell-as** [comment]
Thanks for the report. Confirmed.

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/7f3638fed9f84528b35f352eeb6ace90ec9ea597
