### ISSUE TITLE
'Go to Definition' is not working for 'Go' functions

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2535]
### Short Summary

When looking up the definition of the function/object, cursor does NOT Jump to the corresponding definition of the object for GO scripts.

### Steps to Reproduce
1. Open any Go file
2. Right-click on any function/object
3. Select 'Go to definition' 

### Expected results

Cursor should jump to the corresponding definition of the object

### Actual results

Cursor does not jump.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.2.2 RC2
*Operating System (and version)?* win 10 64-bit

### Additional Information
![image](https://cloud.githubusercontent.com/assets/26605593/25363970/d0b1684a-2913-11e7-85a6-d59091ca8162.png)

**Comment by mitchell-as** [comment]
Hi, do you happen to have Komodo pointing at the correct "godef" exe? Edit > Preferences > Languages > Go > Godef Location.

It wasn't found by default on my computer, so I had to manually set it up. When I did set it up, it seemed to work just fine, at least in the current source file.

**Comment by cgchoffman** [comment]
Mine wasn't working either but once I set godef.exe manually and `GOPATH` in *Prefs > Environment* (that's awkward) everything worked.

The fact that Komodo doesn't find `godef.exe` automatically is the bug here.

**Comment by mjainQA** [comment]
Even after manually setting path for godef on Windows and mac, Go to definition is not working.

**Comment by cgchoffman** [comment]
We had talked about you reinstalling Go and all your packages when lasts we spoke about this ticket.  Did you do that yet?

Are you getting the same error in your notifications?  Is anyone else able to reproduce this issue?  So far it's working fine for Mitchell and I.  If no one else can reproduce the breakage then I'm not sure there is much to be done here.

**Comment by mjainQA** [comment]
My installation is correct as I am able to compile and run Go code outside Komodo. Paths are also set up properly. It could be something to do with Godef and Godep installation or path settings. If its working for devs, I am not going to spend more time in investigating this. Please feel free to close this issue.

**Comment by cgchoffman** [comment]
Oh i had one more idea.  You could try godef in the commandline.  Make sure you adjust the paths to work for you system:
- cd learn-chaincode\start 
- run `godef -f chaincode_start.go fmt.Println`

You should get output like `C:\Go\src\fmt\print.go:256:6`.
