### ISSUE TITLE
Update check fails on Linux

### ISSUE THREAD

**Issue by GrahamStuart** [Komodo/KomodoEdit#2539]
### Short Summary
Check for Updates pops up an error screen

### Steps to Reproduce

On Linux 64. Help | Check for Updates

### Expected results

Should either report an update is available, or that no update is available.

### Actual results

"Update Failed
There were problems checking for, downloading, or installing this update. Komodo IDE could not be updated because:
Update XML file malformed (200)
You can update Komodo IDE manually by visiting this link and downloading the latest version:
http://www.komodoide.com/download

(OK)"

### Platform Information

Any Komodo 10. including 10.2.1.RC2 
Ubuntu 16
Linux

### Additional Information

The link to komodoide.com/downloads offered is also out of date, and does not redirect.

**Comment by cgchoffman** [comment]
I can't find any portion of message given in the Komodo src or the Update server code.  Given that it's not able to parse the response from the server it must be in the Komodo source but I can't find it.  Am I crazy?  I can't even find `http://www.komodoide.com/download`.

**Comment by cgchoffman** [comment]
I can't reproduce the XML error either but I'm using a Ubu 14 VM so  i'll update to 16 and try again.

**Comment by GrahamStuart** [comment]
I found out how to stop the message.

**Comment by GrahamStuart** [comment]
Tools | Add-On (Legacy) | Enable Compatibility Check
Not sure when the Compatibility Check got turned off

**Comment by cgchoffman** [comment]
We turned it off :)  We don't use that dialog anymore and it will be gone soon.  So if you turn compatibility off again does the bug return?  If you run the following in the JS Console in Komodo you can change the setting back to `false`: `ko.open.URI('about:config', 'browser');`

Search for `compat`

**Comment by GrahamStuart** [comment]
The XML error comes back any time compat check is off

**Comment by cgchoffman** [comment]
K thanks for checking.  One last thing, can you confirm what version of Firefox you have installed?

**Comment by GrahamStuart** [comment]
Firefox 53.0

**Comment by cgchoffman** [comment]
Thank you very much.

**Comment by cgchoffman** [comment]
I"m hoping that this bug being fixed also fixes this: https://github.com/Komodo/KomodoEdit/issues/2542

**Comment by GrahamStuart** [comment]
It's a partial fix.
I can now enable Console, FontAwesome Icons, and Search Scope - Packages and still have a working update check.
CheckCompatibility1.3.1 still has to be disabled. So does Tcl Dev Kit.
And.. there's another extension that is now triggering the issue which didn't before, but I'm not sure which one. My working set of extensions from the last RC now fails to update check with RC3. I'll repeat the process of elimination....

**Comment by GrahamStuart** [comment]
It's quite a bit better than it seemed. Looks like some of the secondary update failures were due to missing dependencies on other extensions that were disabled. I'm now down to just one extension that will always cause the update to fail.
checkCompatibility1.3.1

**Comment by cgchoffman** [comment]
Since updating links in [komodo.p.js](https://github.com/Komodo/KomodoEdit/commit/ecf2ceda499a7810cf7906a78a5a883d76de78a8#diff-cbe8ae20aed35ac345530f2a0821f895) seems to have helped, I wonder if  *checkCompatibility* addon has a stale link in it that's giving the update server garbage when it's pinged?

**Comment by mitchell-as** [comment]
I've seen this every now and then. It usually resolves itself on its own. I'm not experiencing this error right now when checking for updates.

**Comment by cgchoffman** [comment]
@i-shenl, are you seeing this on your Linux machine?  Or is anyone else running Linux seeing this?  @Defman21?

**Comment by cgchoffman** [comment]
Removing `priority` as there is an easy workaround when it occurs and it appears that it's sporadic though waiting on more comments to confirm the latter.

**Comment by Defman21** [comment]
@cgchoffman I've never seen this. I'm running nightlies though.

**Comment by cgchoffman** [comment]
As far as I can tell it should happen no matter what though if someone can prove otherwise it would help us resolve rather then defer this ticket.  As it stands I don't think this need to be in 10.2.2.

Thanks for confirming @defman21.

**Comment by Defman21** [comment]
np :)

**Comment by Naatan** [comment]
Could be related to the redirects we have set up? I've seen this once or twice, not a common problem in my experience.

**Comment by mitchell-as** [comment]
This doesn't appear to be an issue. I haven't seen it pop up for 10.2.2 or 10.2.3.
