### ISSUE TITLE
Stale hardcoded links in Komodo source

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2542]
### Short Summary

Since moving all the Komodo stuff back to activestate.com there were a lot of links in Komodo's source that weren't updated.  Those need to get updated.

Similar to https://github.com/komodo/komodoedit/issues/2541 but just do a search for `http://komodoide.com` in the source and you'll get more links.

**Comment by cgchoffman** [comment]
For QA, links to confirm:
- any links in the installer
- https://github.com/komodo/komodoedit/issues/2539 (for @graham)

That should be good.

**Comment by graham** [comment]
Pretty sure you've got the wrong graham, have a nice day!

**Comment by Defman21** [comment]
Yep, sorry. The graham we need is @GrahamStuart

**Comment by cgchoffman** [comment]
QA, just make sure you're clicking all the links in Komodo.
