### ISSUE TITLE
Can't use collaboration feature

### ISSUE THREAD

**Issue by mikhalenia** [Komodo/KomodoEdit#2544]
### Short Summary
I can't use collaboration feature. In the Collaboration tab I see the message "Collaboration encountered a communication error and will recover automatically"
When I try to reconnect - it doesn't work.

### Steps to Reproduce
1. Open Komodo IDE
2. Open collaboration tab
3. Click to "Force reconnect now"

### Expected results
Ability to create new session

### Actual results
501 error

### Platform Information
*Komodo IDE
*Version 10.2.1
*Ubuntu 15.10

### Additional Information
If I use HTTP Inspector I see 501 error:

Request:
URL: https://collaboration-push-v3.activestate.com:443
connection: keep-alive
host: collaboration-push-v3.activestate.com:443
proxy-connection: keep-alive
user-agent: Mozilla/5.0 (X11; Linux x86_64; rv:35.0) Gecko/20100101 KomodoIDE/

Response:
status: 501
content-length: 177
content-type: text/html

**Comment by cgchoffman** [comment]
Please try to reproduce the issue in safe mode, *Help > Troubleshooting > Restart in Safe-Mode*.  Make sure that Komodo reverts to all default settings so you know you're in Safe Mode.

Also please reproduce the issue and provide your logs after reproducing.  Neither I nor QA are able to reproduce an issue with Collab.

**Comment by mikhalenia** [comment]
In the safe-mode everything works fine. Maybe it depends on my custom configuration I will check it. Thank you.

**Comment by cgchoffman** [comment]
@mikhalenia please update us with what you find.  Does it work once you restart again and are back out of Safe Mode?
