### ISSUE TITLE
Collab: Force Reconnect button shows on each Komodo start

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#2547]
### Short Summary

It's being there for a while and then disappears (after connecting to AS servers). I think it's better to display some sort of a loading circle and if there's an error then show the button. (probably the error message too)

### Steps to Reproduce

1. Open the Collab pane.
2. Restart Komodo.

The button will be there for a while and no indication of the connection progress is present.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.2.2 nightly
*Operating System (and version)?* elementary OS 0.4

### Additional Information

I'm way to far from AS servers (~7000-8000km) the connection is not being initialized that fast (~2-3s). You may want to somehow limit your speed to these servers to see the button. There are some tools to do that in Linux and I'm sure there's something for Windows.

**Comment by mitchell-as** [comment]
Thanks for the suggestion, but I don't think it's worth spending resources on something this minor.

**Comment by Defman21** [comment]
Okay, I understand :)
