### ISSUE TITLE
VIM emu: Color schemes become unreadable

### ISSUE THREAD

**Issue by rawktron** [Komodo/KomodoEdit#2559]
Your color schemes sometimes result in unreadable code. Specifically, the 'Dark Chalkboard' scheme makes some things unreadable when it highlights matching braces/parens/brackets. When you click in another window (say, to add a watch) the current line in the editor becomes unreadable reddish on reddish. Other of the schemes have similar quirks.

Platform: Win/Linux.

**Comment by mitchell-as** [comment]
We do not curate the "Dark Chalkboard" theme. If there's another theme that we do curate (those that come by default in Komodo 10) that result in unreadable code, that would be a bug.

**Comment by Defman21** [comment]
Dark Chalkboard was in Komodo 8 IIRC. If you have migrated from Komodo 8 to 9 or 10, it were saved though it's not going to be working properly because of new colors.

**Comment by rawktron** [comment]
That's a great explanation. Worth noting that it may be worth documenting the fact that migrated color schemes may not be fully supported.

**Comment by Defman21** [comment]
I'll update the docs someday.
