### ISSUE TITLE
Removing breakpoint indicator

### ISSUE THREAD

**Issue by jcloggins** [Komodo/KomodoEdit#256]
When entering code that moves the location of a breakpoint, the breakpoint indicator cannot be removed from the view pane.

Example:

In file xyz.pl create a breakpoint at line n
Add a new line of code before line at which the breakpoint is located
Note that the breakpoint moves with the change in location of the line it references
Clear the breakpoint
Note that the editing pane still shows the breakpoint even though it no longer exists

**Comment by cgchoffman** [comment]
Please confirm what version of Komodo you're using: Help > About Komodo (Komodo > About Komodo on OSX)

**Comment by jcloggins** [comment]
Komodo IDE, version 9.0.1, build 87208, platform win32-x86.

Built on Thu Apr 16 11:54:31 2015.

 

Jesse C. Loggins

Embedded Software Engineer 

UQM Technologies

4120 Specialty Place

Longmont CO  80504

(303) 682-4908

Fax: (303) 682-4901

 

For more company information, please visit us at www.UQM.com.

 

This email is intended solely for the person or entity to which it is addressed.  Information contained and transmitted in this email may contain legally privileged, confidential and proprietary materials belonging to UQM Technologies, Inc. If you are not the intended recipient, you are notified that any review, dissemination, disclosure, printing, copying or other use of this email is strictly prohibited and you are requested to delete this email from any computer and notify the originator immediately.

**Comment by mitchell-as** [comment]
For performance considerations, we do not keep the breakpoint markers in the view in sync with our internal breakpoint list while there are unsaved changes. Once you save the document, resynchronization occurs and you will be able to remove the breakpoint that moved.

We will keep this ticket open in our backlog, as there may be some room for improvement.

**Comment by jcloggins** [comment]
Quote: “Once you save the document, resynchronization occurs and you will be able to remove the breakpoint that moved, the breakpoint list will update, etc.”

I have done a little more experimenting with this issue and found that your statement is only correct up to a certain point.

If the breakpoint is cleared from the breakpoint list _before_ the document is saved, the indicator does not resynk and cannot be cleared until the editor is closed and reopened. At which point the breakpoint reappears in the breakpoint list and can be completely cleared.

**Comment by cgchoffman** [comment]
This bad boy needs to get fixed.  It's been around for a very long time.

**Comment by Naatan** [comment]
Yeah no kidding. Btw I think part of this bug is also that the breakpoint itself doesn't move, right?

If moving the breakpoint according to edits is too difficult I think an acceptable compromise would be to delete the breakpoint if the code around it is altered. Not ideal but definitely better than the current "solution".

**Comment by cgchoffman** [comment]
No the breakpoint moves.  If you set a breakpoint and add a line above it all the lines below that point + the breakpoint will move but you can't click on the breakpoint any more.  Issue goes away if you save the buffer.  The breakpoint becomes clickable.

**Comment by Naatan** [comment]
I know the margin symbol moves, but does the actual breakpoint move? Does the debugger break on the line that the margin indicates?

**Comment by mitchell-as** [comment]
Yes, it functions as expected once the file is saved.

**Comment by cgchoffman** [comment]
> Does the debugger break on the line that the margin indicates?

I'm not sure @Naatan .

**Comment by jcloggins** [comment]
Note: The behavior is different between saving before starting a debug session and the save that occurs as the result of starting a debug session.

**Comment by cgchoffman** [comment]
> Note: The behavior is different between saving before starting a debug session and the save that occurs as the result of starting a debug session.

Noted.  In what way are they different?

**Comment by jcloggins** [comment]
If the save is before starting the session, everything behaves normally

If the save is the result of starting the debug session, the breakpoint occurs in the proper location - but the capability of deleting it is lost until Komodo is restarted.

Also note that I am using a Windows system.

**Comment by cgchoffman** [comment]
Thanks @jcloggins

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoIDE/commit/32b25c7b9153281dfbc3090fbd28375edff8c693
