### ISSUE TITLE
Externally launch a tool or macro

### ISSUE THREAD

**Issue by feamsr00** [Komodo/KomodoEdit#257]
Is there any way to launch a tool from an external application? It would be great if Komodo could register as a protocol, like komodo://, with the ability to specify a specific tool and supply it options. It would be great if we could setup some Project/Issue specific preconfigured tools to our Project Tracker. Even a way to call a CLI command (while Komodo is running) to instantiate a tool would be useful.

That would be a user executing a tool from within Komodo. I was hoping to have a tool execute from another application or web page. We setup a new branch in our repository for each feature, and I created a tool for our team that automatically switches the local working copy to a specific branch for a specified issue. I would like to setup some way for a dev to click a link in our Issue Tracker to execute that tool with the Issue being viewed as a parameter.

> posted from http://forum.komodoide.com/t/externally-launch-a-tool-or-macro/1539/4

**Comment by Naatan** [comment]
Closing this issue, the forum is the proper medium for this discussion.
