### ISSUE TITLE
First Start Wizard says Komodo IDE instead of Komodo Edit

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#2572]
### Short Summary

If you run Komodo Edit for first time (or run the wizard again), you'll see Komodo IDE in the title of the window.

### Platform Information

*Komodo Edit or IDE?* Edit
*Komodo Version?* master branch
*Operating System (and version)?* Arch Linux 

### Additional Information

![screenshot_20170503_135401](https://cloud.githubusercontent.com/assets/7100645/25657725/faa6e1b6-3007-11e7-97f6-75f0ea2c2b45.png)

**Comment by mitchell-as** [comment]
Thanks for the report.
