### ISSUE TITLE
11: can't type B, C, S, F, O, P or T in commando any more

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2576]
### Short Summary

Komodo 11

You can't open commando and start typing without entering a scope now.  Another issue arising from this is that when you've entered a scope you can't type the quick key for that scope any more.

### Steps to Reproduce

- open commando (Ctrl + Shift + O)
- try to type something that has one of the following letters: B, C, S, F, O, P or T
- as soon as you hit that letter you will jump into the scope associated with that letter.

**Comment by Defman21** [comment]
Hmm I'm on the master branch and I can't reproduce it. I wanted to fix that though.

**Comment by Naatan** [comment]
This should only happen when you have ALT pressed. Are you able to reproduce this?

**Comment by cgchoffman** [comment]
> Are you able to reproduce this?

who are you talking to?  I am not pressing Alt and this is happening.

**Comment by Naatan** [comment]
You :) And I guess that answers my question.

**Comment by Naatan** [comment]
I cannot reproduce this. Are you still getting this? Are you certain the steps to reproduce are accurate?

**Comment by cgchoffman** [comment]
Nope.  Can't repro!
