### ISSUE TITLE
11: Project Pane > Gear > New Project doesn't work

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2577]
### Short Summary

I originally thought that XUL wasn't handling our `ko/commands.register`  and not being able to support a UXL element using the `observes` attribute (`observes="cmd_mycommand"`) but focusmode works fine in this manner.

So I don't know why this isn't working.  The command `cmd_openProjectwizard` works if you call it from commando or you set `oncommand` attr of the elemen.

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/8029402eb9e690bed89195f1aafffc4c699eb422
