### ISSUE TITLE
"Edit matching delimiter on select" creates a persistent duplicate cursor

### ISSUE THREAD

**Issue by damienprystay** [Komodo/KomodoEdit#2578]
With the "Editor -> Smart Editing -> Edit matching delimiter on select" option enabled, highlighting a delimiter (specifically a quote or double-quote; this behaviour doesn't seem to apply to backticks or any kind of brackets) causes the matching delimiter to also be highlighted, as expected.

However, the second cursor (acting on the matching delimiter) continues to exist after the selection is dismissed, whether by typing to replace the selected delimiters, or pressing ESC to unselect them, or navigating with the arrow keys. Any typing or keyboard selection at this point is performed by both cursors at once, persisting until the cursor position is set absolutely with the mouse or a keyboard command like "Home".

Relatedly (perhaps a separate bug, but it's the context in which this behaviour becomes an impediment rather than just kind of funny): when using SHIFT+ALT+arrow to select whole words, if the first thing selected was a quote character, Komodo selects the matching delimiter as well, but does not then unselect it (and remove the second cursor) if the selection continues on to include more characters.

E.g. given `foo['someKey'] = bar`, if I've decided to replace `'somekey'` with a variable name, put the cursor before the first quote character, and press SHIFT+ALT+RIGHT-RIGHT-RIGHT, what winds up selected is `'somekey'] =` - and as there are two adjacent cursors, whatever I type is duplicated, resulting in something like `foo[varNamevarName bar`. (That the colour scheme I'm using does not make the highlight colour vastly different from the current line colour also makes it less immediately obvious that something is wrong before I start typing.)

### Platform Information

Komodo IDE 10.2.1
macOS 10.11.6

**Comment by Naatan** [comment]
This is resolved in 10.2.2.
