### ISSUE TITLE
Commando: multiple selection using shift + arrows is broken on master

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#2580]
### Short Summary

title. Commando does not add new items to the selection with shift + arrow down/up.

### Platform Information

*Komodo Edit or IDE?* Edit
*Komodo Version?* master branch

**Comment by Defman21** [comment]
Ahh I can't add folders to multiple selection. Didn't know that.

**Comment by Naatan** [comment]
This is by design, I don't see a better way of handling this that wouldn't be confusing or error-prone.

**Comment by Defman21** [comment]
What about giving the user a Commando tip that the current selection could not be multi selected with something else?

**Comment by Naatan** [comment]
That's not a bad idea. Would have to try it out but might work.

**Comment by Defman21** [comment]
I can send a PR for that :) (that was implemented in the commit above)
