### ISSUE TITLE
random crash

### ISSUE THREAD

**Issue by arthuro3591** [Komodo/KomodoEdit#2591]
### Short Summary

Random crash while editing--copy and paste

### Steps to Reproduce

random

### Actual results
crash
[komodo crash 1.pdf](https://github.com/Komodo/KomodoEdit/files/987174/komodo.crash.1.pdf)
[komodo crash 2.pdf](https://github.com/Komodo/KomodoEdit/files/987176/komodo.crash.2.pdf)

### Platform Information

*Komodo Edit
*Komodo Version 10.2.1
*Operating System (and version)?*  Mac OS 10.12.4

**Comment by Naatan** [comment]
Please use the crash reporter for this. If you can reliably reproduce the crash a bug is in order, but otherwise a random crash on its own is not actionable as a bug.
