### ISSUE TITLE
New Project Wizard: Run Command fails to find exe

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2594]
### Short Summary

What ever is running commands in the Project Wizard isn't using the system PATH is appears.  No matter what command I try to run it fails to find the needed binary or batch/bash file.

### Steps to Reproduce

These steps assume you have Python on your system path.
1. Start Project Wizard: *Project menu > New Project*.
1. Fill in the first as you like just make sure the *Location* field isn't an existing folder.
1. Click **Next**
1. Enter `python -V` in the *Run Command* field.
1. Click **Next**

### Expected results
This output, note like 3:
```
Creating directory C:\Users\cgcho\Workspace\poop .. Done
Running Command "python -V" ..
 .. Python 2.7.13,
 .. operable program or batch file.
 .. Done
Creating Project file .. Done

All Done!
```

### Actual results
Note line 3 again.  On Windows that message means it can't find the executable on your PATH.
```
Creating directory C:\Users\cgcho\Workspace\poop .. Done
Running Command "python -V" ..
 .. 'python' is not recognized as an internal or external command,
 .. operable program or batch file.
 .. Done
Creating Project file .. Done

All Done!
```

**Comment by Naatan** [comment]
Does it work if you use `python.exe` instead of just `python`?

**Comment by cgchoffman** [comment]
Yes it does.
