### ISSUE TITLE
Some Python keywords missing for autocomplete

### ISSUE THREAD

**Issue by cftarnas** [Komodo/KomodoEdit#2597]
### Short Summary

Some Python and Python3 keywords are missing from autocomplete, the ones I run into the most are _for_ and _in_. This does not affect all keywords - for example _if_, _else_,  and _def_ are not missing. This causes problems as incorrect suggestions are offered and defaulted to.

### Steps to Reproduce

Create a new python file and try to write the simple list comprehension:
`arr = [i for i in range(0, 10)]`

### Expected results

- When typing _for_, _for_ should be offered for autocomplete.
- When typing _in_, _in_ should be offered for autocomplete. 

### Actual results

- The only autocompelte suggestion for _for_ is _format_ and that is what is chosen unless you hit escape.
- The autocomplete suggestions for _in_ are _input_ and _int_. Unless you hit escape _input_ is chosen. 

If you were to actually go with the default suggestions when typing the comprehension, this would be the result:
`arr = [i format i input range(0, 10)]`

### Platform Information

*Komodo IDE, version 10.2.2, build 89895, platform macosx.
Built on Fri Apr 28 17:57:38 2017.* 
*OSX 10.12.4* 

### Additional Information

Currently the only workaround is to manually override the autocomplete for very common keywords.

**Comment by mitchell-as** [comment]
This has been fixed in the codeintel refactoring for Komodo 11.

**Comment by mitchell-as** [comment]
https://github.com/Komodo/KomodoIDE/commit/7b7a8443e958333edff53c0f5fd86994d6e6309b
