### ISSUE TITLE
Komodo IDE freezes randomly several times a day

### ISSUE THREAD

**Issue by vrurg** [Komodo/KomodoEdit#2598]
### Short Summary

The IDE freezes unpredictably. Good times is when it happens once a day. Bad times is like today – nearly 10th freeze in two hours and counting.

### Steps to Reproduce

None in particular. It could be saving attempt, starting a debug – any moment in time.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.2.2 but probably started in 10.2.1 or 10.2 even.
*Operating System (and version)?* macOS Sierra 10.12.4

### Additional Information

Unfortunately, the error log get overwritten  with every restart. Will try to get its content directly the next time it freezes.

**Comment by Naatan** [comment]
This issue is being tracked here: https://github.com/Komodo/KomodoEdit/issues/2424
