### ISSUE TITLE
Stuck notification pane

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2600]
### Short Summary

I can get a stuck notification panel pretty easily lately as I've been using Focus mode which appears to move notifications to popup panels.  The only way to remove the stuck panel is to delete it from the DOM using DOMi or restart Komodo.

### Steps to Reproduce

- Reset your code intel databases
- Turn on Focus mode
- Get Komodo to scan a project for code intel (the key here being the flurry of notifications thrown out by code intel that it's scanning all the things).

### Expected results

All notifications to disappear when they aren't relevant any more.

### Actual results

Eventually one will stick around.  If you look in the DOMi it actually looks like there is an entire stack of them.

**Comment by Defman21** [comment]
That pisses me off a lot. They are overlapping other windows and the only way to close them without DOM deletion is restarting Komodo. I guess I'll write an usersript that will force-remove them after 5 secs once they appeared.

**Comment by Defman21** [comment]
#2108 btw.
