### ISSUE TITLE
Komodo Ruby Syntax Error

### ISSUE THREAD

**Issue by dave-mac0** [Komodo/KomodoEdit#2601]
I'm using Komodo IDE (currently 10.2.2) on Windows 10 Pro to manage the development of an extension for SketchUp 2017.  Extensions are developed using Ruby.

I use the variable debug_check to manage Ruby console reporting during development. 

The following code snippet does not trigger a synatx error in Komodo but the SketchUp Ruby interpreter correctly throws an error when it checks for syntax on load:

puts ('some text') + if debug_check

Interestingly SketchUp does not actually identify the line number containing the incorrect syntax, it simply reports an enexpected end of input on the last line of the code file.

**Comment by Defman21** [comment]
Do you have a ruby interpreter installed? Komodo won't report anything without the `ruby` executable.

**Comment by dave-mac0** [comment]
I didn't as the Syntax & Spell Checking tab in Preferences doesn't state that you need a Ruby interpreter installed.  It allows you to set syntax checking preferences with the expectation that its just going to happen (the usual miracle cure approach).  Additionally SketchUp uses a number of Ruby libraries that are only available from within SketchUp so I was assuming that I would get errors about the SketchUp calls..

I've now installed the standard Ruby interpreter and now I get a lot of syntax warnings and errors.  

Thanks for the assistance.  I'll try to do a better job of reading the manual in future.

**Comment by cgchoffman** [comment]
> I didn't as the Syntax & Spell Checking tab in Preferences doesn't state that you need a Ruby interpreter installed.

This is a UX bug.  We should fix that.  Especially since other languages DO warn you that dependancies need to be installed before you can use syntax checking for that lang or tool. eg. ALL of the Python syntax checkers.

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoEdit/issues/2602
