### ISSUE TITLE
No docblock calltip if the docblock param count doesnt match the function param count

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#2603]
```
/**
 * Summary
 *
 * @param string $aaa one
 */
function foo($aaa, $bbb) {
    return 'foo';
}

foo(<|>
```

Above has no no docblock calltip unless I add another param to the docblock.

Obviously this is a bug on the users end, but no reason why we can't still facilitate them.

**Comment by mitchell-as** [comment]
I cannot reproduce this in latest master. I get the "Summary" docblock (after clicking the "i" button at the top-right of the completion list) with or without the correct parameter list in the documentation block.
