### ISSUE TITLE
Floating pane resetting it's size

### ISSUE THREAD

**Issue by AtmanActive** [Komodo/KomodoEdit#2604]
### Short Summary

Since latest update, (Komodo IDE, version 10.2.2, build 89895, platform win32-x86.
Built on Fri Apr 28 17:11:08 2017.), the floating pane does not want to save it's size and position anymore. This functionality was working properly since version 10.0.0 until now.

### Steps to Reproduce

Move any of the panes to a new floating pane.
Resize/adjust the pane's position.
Exit Komodo.
Start Komodo again.
Start pulling your hair out.

### Expected results

Floating pane opens with exact size/position/content as I left it when I quit Komodo working session.

### Actual results

Floating pane opens small (default size), looks like position is OK, content is OK.

### Platform Information

Komodo IDE, version 10.2.2, build 89895, platform win32-x86.
Built on Fri Apr 28 17:11:08 2017.

### Additional Information

I am running Komodo in portable mode, with a help of BAT startup file attached here.
I've been running it like that for last 4 years, never had any problems because of it.
Could be related, I'm hoping it's unrelated.
[Komodo_IDE_Portable.txt](https://github.com/Komodo/KomodoEdit/files/1002388/Komodo_IDE_Portable.txt)

Error log attached.
[Log.txt](https://github.com/Komodo/KomodoEdit/files/1002398/Log.txt)

**Comment by Naatan** [comment]
@mjainQA could you verify that this is a regression?

**Comment by f34rl3ss** [comment]
Same problem here with Komodo Edit 10.2.2 (no BAT startup, no portable mode)
Content of the floating pane is ok, but size/positon is not.

After closing/opening Komodo the pane is opening screen centered and the size is very small, equal to when the floating pane is initially created.

Using the editor on 3 different PCs and it happens on all of them.

**Comment by AtmanActive** [comment]
These regressions are particularly painful.
Please fix it guys.
Thanks.

**Comment by f34rl3ss** [comment]
A have an addition:
After restarting Komodo, the preferences menu (eg. directory-related funtions) in the floating pane is without function.
It can be opened and clicked, but nothing happens.

**Comment by Naatan** [comment]
Please create a new bug report for your issue @f34rl3ss. We only track one bug per report.

**Comment by mjainQA** [comment]
@Naatan Verified this issue - Its a regression in 10.2.2 on Windows. It works in 10.2.1.

Komodo has never been able to save floating pane size preferences On Mac. Tested on 10.2.0, 10.2.1 and 10.2.2.

**Comment by Naatan** [comment]
Thanks @mjainQA !
