### ISSUE TITLE
Windows: Have Komodo install associate *.ktf* file with Komdo

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2607]
### Short Summary

This will look bad if Komodo doesn't do this for it's own file types.

File types to include:
*.ktf, *.kkf, *.ksf

**Comment by Naatan** [comment]
I don't believe it does it for kkf and ksf either.

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/b7743def3338f77a941f58a89bf29c8a596020f3

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/64c8056f61209d4ef9992c06f551cb3672c4b146
