### ISSUE TITLE
Source debugging broken with node.js v0.12.2

### ISSUE THREAD

**Issue by rdominy** [Komodo/KomodoEdit#261]
With the latest Komodo IDE (9.0.1) and latest stable node.js (v0.12.2), source level debugging does not work.

Steps to reproduce:
1. Get latest node.js
2. Create a some simple node.js code in Komodo
3. Use the debugger to Step Into the code
The console displays "Debugger listening on port 5858", but never completes.

Downgrading to node.js 0.10.36 fixes the issue,  but many modules are beginning to require the later node.js.  Please support the latest stable release of node.js.

**Comment by cgchoffman** [comment]
Issue #177
