### ISSUE TITLE
Importing tools in toolbox can break Userscripts

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2610]
### Short Summary

It might not just be Userscripts but it's the only case I've found so far.

### Steps to Reproduce

- Build Komodo 11 
- Import the laravel tools:  Toolbox > Import > Laravel Tools
- Run *Laravel > Debugging > Generate Debug Config*
- You will get an error about a missing `)`

- Right click Userscript > Edit Userscript
- Note line 30 is missing a `{`

- Right click Userscript > Edit Tool (Advanced)
- Note line 30 is not missing the `{`

### Expected results

There to be no discrepancy.

### Actual results

There is a discrepancy between the two forms of editing.

**Comment by Naatan** [comment]
@cgchoffman I think we fixed this, right? (the file writing issue).

**Comment by cgchoffman** [comment]
Yep I'm pretty sure this got fixed: https://github.com/Komodo/KomodoIDE/commit/9473aa961b88f3e14e3d1170d3a863a43c8d8477#diff-82321d3785096eba461a6db7f9895e94
