### ISSUE TITLE
Create commands / keybinds for CodeIntel v3

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#2616]
These commands were removed and likely need equivalents:

 * cmd_jumpToNextSection
 * cmd_jumpToPreviousSection
 * cmd_triggerPrecedingCompletion
 * cmd_goToDefinition
~~ * cmd_viewCodeBrowser~~ Already define:https://github.com/Komodo/KomodoIDE/blob/master//src/chrome/komodo/content/library/controller.js#L16
 * cmd_codeBrowserLocate
 * ~~cmd_completeWord~~ **Not Code Intel**

**Comment by cgchoffman** [comment]
I assume the function that these commands would call already exist?  All I need to do is implement the command interface?

**Comment by Naatan** [comment]
No commands exist yet, that would be part of the task.

The SDK methods in most cases do exist, so creating the commands should be pretty straight forward.

**Comment by cgchoffman** [comment]
Started but not compmlete: https://github.com/Komodo/KomodoIDE/commit/0a25f386d53ded0e22f1cb6456b581b57fa10a18

**Comment by Defman21** [comment]
@Naatan why did you close this btw? 🤔

**Comment by cgchoffman** [comment]
We're tracking this somewhere else now :)  Thanks for checking though @defman21.

**Comment by Defman21** [comment]
Gotcha.
