### ISSUE TITLE
Create preference window for CodeIntel v3

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#2617]
Needs to cover:

 * Toggling of features
 * ...

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/159f7078aac20ae44a7b5da392a91cfde26e92d4

**Comment by cgchoffman** [comment]
### Feature overview

Two changes were made here:
1. Enable and disable code intel features
  1. Call tips
  1. completions
  1. Symbol Browser
  1. Symbol lists
1. Allow Pref SDK to register and display new prefs in the prefs window dymanically.

### Acceptance criteria

##### Code Intel
 Disabling the pref turns off the feature

##### Prefs
If the Code intel prefs are being displayed then this feature is working.


### Technical changes 
 
Ko/prefs sdk has a new function called `register` which takes a feature name and a path to a prefs.xul file which handles the prefs dialog interface functions to load and save a features prefs.


### Components to test
Prefs > Code Intel.  Ensure those features are turned off when disabled.

### Related commits
