### ISSUE TITLE
OSX crashes

### ISSUE THREAD

**Issue by hughdbrown** [Komodo/KomodoEdit#2618]
Komodo 10.2 is crashing regularly on OSX 10.12.4 on a machine with 16GB RAM. Happens a few times per day. Spinning beachball cursor comes up and that's all she wrote.

Truncated tech info looks like this: https://pastebin.com/QCDaSQ8b
(Apple creates a 512+ kb dump that I cannot paste here or in pastebin.)

**Comment by cgchoffman** [comment]
Tracking here: https://github.com/Komodo/KomodoEdit/issues/2424

Note the **Note from Developer** in the original report.  If you wish to help out please follow those instructions.
