### ISSUE TITLE
Arbitrary Komodo IDE crashes

### ISSUE THREAD

**Issue by dennisclima** [Komodo/KomodoEdit#2621]
### Short Summary

With no seeming consistency or pattern, Komodo dies. I spend most my time in TCL and Javascript modules.

### Steps to Reproduce

I cannot discern what causes the crashes.

### Expected results

No crashes.

### Actual results

Komodo arbitrarily crashes.

### Platform Information

Komodo IDE, version 10.2.2, build 89895, platform macosx.
Built on Fri Apr 28 17:57:38 2017.

MacOS v10.12.4 (Sierra)

### Additional Information

[pystderr.log.txt](https://github.com/Komodo/KomodoEdit/files/1019175/pystderr.log.txt)

**Comment by mitchell-as** [comment]
Hi, if you're experiencing a hang instead of a crash, #2424 is applicable. If it truly is a hard crash (you didn't force-kill Komodo), we'll need more information other than "arbitrarily crashes", as there's nothing we can do. Your log doesn't indicate any crashing issue.

**Comment by dennisclima** [comment]
I downloaded v9.2 upgraded to v9.3 as suggested in #2424. Things were ok for several days until the problem re-occurred today ...

**Comment by Naatan** [comment]
Please respond to #2424
