### ISSUE TITLE
Komodo 9.3 hangs just like 10.2

### ISSUE THREAD

**Issue by dennisclima** [Komodo/KomodoEdit#2623]
### Short Summary

I submitted a bug report for Komodo IDE 10.2 'hanging'. I was referred to a solution advising me to download v9.2. It hung. Upgraded to v9.3 - it hung.

### Steps to Reproduce

Hanging seems to be arbitrary.

### Expected results

No hanging..........

### Actual results

Hangs arbitrarily.

### Platform Information
Komodow IDE
Version 9.3
MacOS Sierra v10.12.4

### Additional Information

[pystderr.log.txt](https://github.com/Komodo/KomodoEdit/files/1025795/pystderr.log.txt)

**Comment by Naatan** [comment]
Please don't report a new bug, just respond to the existing one.
