### ISSUE TITLE
Fix Python interpreter validation to stop input of invalid file

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2625]
### Short Summary

Right now Komodo will warn a user that they chose a non Python 2 or non python 3 file for an interpreter but it will still set the file as the interpreter.  It even allows the person to save the preference.  This shouldn't be allowed to happen.  There should be a validation hook that all the preference pages use to validate themselves on save.

### Steps to Reproduce

- open prefs > Langauges > Python
- Select **Browse** to select a file.
- Select a file that is clealry not a Python executable.
- Komodo should warn that it's not a Python file and won't work

### Expected results

- Warning dialog should warn user then ask if they would like to continue with an **Ok** and **Cancel** button.  If they cancel nothing gets filled in.  If they click **OK** then the path is entered and they are allowed to save the possibly broken pref.
OR
- Drop down field does NOT get populated with selected path
- Komodo does NOT let you **Ok** out of the window or **Apply** changes  

### Actual results

Path gets set and You can save the pref by clicking **Ok** and/or **Apply**.

**Comment by Naatan** [comment]
I think we need some "continue anyway" mechanic to cover use-cases such as custom Python interpreters or new Python versions that break our detection mechanic.

**Comment by cgchoffman** [comment]
That's a good point.  Editing ticket.
