### ISSUE TITLE
ko/simple-storage.remove("blah") doesn't delete the storage

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2627]
### Short Summary

I honestly thought I had filed this before but I can't find the ticket now.

If you create a simple-storage instance, add something to it then delete the storage by calling `remove()` when you recreate the storage block using `get("blah")` you get the same storage object.

### Steps to Reproduce

In the JS Console( *View > Tabs & Sidebars > Console* )
- `require("ko/simple-storage").get("blah").storage.cheese = "pizza";`
- `require("ko/simple-storage").remove("blah");`
- `require("ko/simple-storage").get("blah").storage.cheese;`

### Expected Output

`undefined`

### Actual Output

`pizza`

**Comment by Naatan** [comment]
I can't reproduce this. Are you sure you weren't saving the storage object to a var and referencing that instead?

**Comment by cgchoffman** [comment]
*shakes head* i can't reproduce it any more either.  I JUST did the repro steps, restarted still had the storage.  Tried again, restarted, now it's working.  Closing.  I"ll reopen if I hit it again.
