### ISSUE TITLE
Replace deprecated gethostbyname

### ISSUE THREAD

**Issue by demanuel** [Komodo/KomodoEdit#2630]
While building the package in obs (opensuse build service), i got the following warning:

> [  172s] komodo-edit.x86_64: I: binary-or-shlib-calls-gethostbyname /usr/lib64/komodo-edit/lib/mozilla/libfreebl3.so
> [  172s] komodo-edit.x86_64: I: binary-or-shlib-calls-gethostbyname /usr/lib64/komodo-edit/lib/mozilla/libnssutil3.so
> [  172s] komodo-edit.x86_64: I: binary-or-shlib-calls-gethostbyname /usr/lib64/komodo-edit/lib/mozilla/libnssdbm3.so
> [  172s] komodo-edit.x86_64: I: binary-or-shlib-calls-gethostbyname /usr/lib64/komodo-edit/lib/mozilla/libnss3.so
> [  172s] komodo-edit.x86_64: I: binary-or-shlib-calls-gethostbyname /usr/lib64/komodo-edit/lib/mozilla/libsmime3.so
> [  172s] komodo-edit.x86_64: I: binary-or-shlib-calls-gethostbyname /usr/lib64/komodo-edit/lib/python/lib/python2.7/lib-dynload/_socket.so
> [  172s] komodo-edit.x86_64: I: binary-or-shlib-calls-gethostbyname /usr/lib64/komodo-edit/lib/mozilla/libxul.so
> [  172s] komodo-edit.x86_64: I: binary-or-shlib-calls-gethostbyname /usr/lib64/komodo-edit/lib/mozilla/libnssckbi.so
> [  172s] komodo-edit.x86_64: I: binary-or-shlib-calls-gethostbyname /usr/lib64/komodo-edit/lib/mozilla/libsoftokn3.so
> [  172s] komodo-edit.x86_64: I: binary-or-shlib-calls-gethostbyname /usr/lib64/komodo-edit/lib/mozilla/libssl3.so
> [  172s] komodo-edit.x86_64: I: binary-or-shlib-calls-gethostbyname /usr/lib64/komodo-edit/lib/mozilla/libnspr4.so
> [  172s] The binary calls gethostbyname(). Please port the code to use getaddrinfo().

The function gethostbyname is deprecated and komodo shouldn't use it.

In linux, according to man 3 gethostbyname:

> The gethostbyname*(), gethostbyaddr*(), herror(), and hstrerror() functions are obsolete. Applications should use getaddrinfo(3), getnameinfo(3), and gai_strerror(3) instead.

[In windows](https://msdn.microsoft.com/en-us/library/windows/desktop/ms738524(v=vs.85).aspx):

> Note  The gethostbyname function has been deprecated by the introduction of the getaddrinfo function. Developers creating Windows Sockets 2 applications are urged to use the getaddrinfo function instead of gethostbyname.

Thanks and best regards,
David Santiago

**Comment by cgchoffman** [comment]
> While building the package in obs (opensuse build service), i got the following warning:

This sounds like it's like old.  We don't support building Komodo Edit through OBS.  Please build Komodo from our git repo using the instructions found there.
https://github.com/Komodo/Komodoedit/

**Comment by demanuel** [comment]
Please re-open this. 

OBS is just a server that builds packages. It downloads the code code via git or from any other service.

Let me be clear:
[Your code is using a deprecated function.](https://github.com/Komodo/KomodoEdit/search?utf8=%E2%9C%93&q=gethostbyname&type=)

**Comment by cgchoffman** [comment]
If this gets fixed we will either be upgrading Mozilla to the latest or removing our dependency on Mozilla.  Don't get me wrong, we appreciate the report but we won't be fixing this. Is the build failing for you or are you just reporting the deprecation message?

**Comment by cgchoffman** [comment]
@Naatan, am I incorrect?

**Comment by demanuel** [comment]
It builds fine. I was just reporting the warning message.

**Comment by Defman21** [comment]
@cgchoffman I'm not Nathan but according to the warning above, you're correct, those warnings comes from the mozilla libs, Komodo does not implement the function itself. (though it's using the function there: https://github.com/Komodo/KomodoEdit/blob/e8d3366bfa1d16d27a28f58f4104fde212157011/mozilla/build.py#L2094 and you may want to change that at some time).

**Comment by Naatan** [comment]
Thanks guys :) This will be addressed when we update our Mozilla dependency. No point tracking this explcicitly.
