### ISSUE TITLE
Tooltip box for DOM has a huge box

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2631]
### Short Summary

Tooltip box for DOM looks odd. 

### Steps to Reproduce

1. Hover over DOM icon

### Expected results

The box size should be as per text in it

### Actual results

see screenshot

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.2.2
*Operating System (and version)?* mac OS

### Additional Information

![image](https://cloud.githubusercontent.com/assets/26605593/26695044/3e8b18c6-46be-11e7-9eab-8a51cdd44df8.png)

**Comment by cgchoffman** [comment]
I can't actually reproduce this on.  The tooltip text that appears when you hover over any of the side pane tabs icons, including the DOM widget icon, is only the size of the text it shows.

Check if the issue continues after a restart.  If not, also check if this goes away in Safe Mode.  If not share your logs and also check to see if you have custom CSS in the Interface section of the Tools > color scheme editor.

**Comment by mjainQA** [comment]
@cgchoffman Ha! Issue went away after a restart.

**Comment by cgchoffman** [comment]
hrm, well I'd close it for now unless you can figure out how to reproduce it.

**Comment by Naatan** [comment]
Thanks for the report! As it stands this widget will be removed in Komodo 11, the functionality has been merged into the symbol browser. As such there is no point in tracking this issue.
