### ISSUE TITLE
Indentation guides

### ISSUE THREAD

**Issue by PhilSDP** [Komodo/KomodoEdit#264]
I've noticed that the indentation guides in Komodo 9 (87208) are now static.  In previous versions when the cursor was at the start or end of an indentation block that guide would turn red, very useful for matching long XML elements.  I was hoping there was an option to enable this, but alas it does not appear so.

**Comment by cgchoffman** [comment]
Here's a work around using the following code as a macro in Komodo:
```javascript
 var pref_name = ko.interpolate.interpolateStrings(["showMatchingTags_clearInterval"]);
if (pref_name) {
    var pref_value = 5000;
    if (pref_value !== null) {
        var prefs = Components.classes['@activestate.com/koPrefService;1'].getService(Components.interfaces.koIPrefService).prefs;
        //dump("Setting pref '" + pref_name + "' to '" + pref_value + "'\n");
        prefs.setLongPref(pref_name, parseInt(pref_value));
    }
}
```
Alternatively you could use this macro to have Komodo ask you how long you want the timeout to be:
```javascript
var pref_name = ko.interpolate.interpolateStrings(["showMatchingTags_clearInterval"]);
var pref_value = ko.interpolate.interpolateStrings(["%(ask: Set timeout: -1 == no timeout)"]);
if (parseInt(pref_value)) {
    ko.prefs.setLong(pref_name, pref_value);
}
```

**Comment by PhilSDP** [comment]
Close, but no cigar.  This highlights the corresponding open/close tags, which I agree is nice.  But I was referring to the indentation guide itself (vertical line) is what used to change color.  The tag highlights can be useful if both tags are displayed, but that's not always the case with long elements.

**Comment by PhilSDP** [comment]
I see the difference, the guides do change color for matching braces {}, that is the behaviour that would be useful for XML tags too

**Comment by mitchell-as** [comment]
@PhilSDP Which version of Komodo had the indentation guide highlighting for HTML/XML tags? Neither Komodo 7.1.3 nor Komodo 8.5.4 had it. In fact, I'm not sure Komodo ever supported this feature.

It's worth pointing out that previous versions of Komodo did highlight indentation guides in red for brace characters. Either way, I'm going to mark this issue as an enhancement and add it to our backlog.

**Comment by PhilSDP** [comment]
That is correct, it should be an enhancement as (indirectly) mentioned in my previous post when I referred to the braces "that would be useful for XML tags too", actually for any language that has open/close tags.

**Comment by mitchell-as** [comment]
Note to self: `views-buffer.p.xml`'s `doUpdateUI` method calls `scimoz.doMatchBrace()`, which performs the usual brace matching. For XML/HTML, throw in a call to `getMatchingTagInfo()` (see an example later in that file) and if the tags have the same line indentation, brace match somewhere the start and end tags (`scimoz.braceMatch()`) and highlight the indent guide (`scimoz.highlightGuide = ...`).

**Comment by mitchell-as** [comment]
See also: https://github.com/Komodo/KomodoEdit/commit/e72d128296db4bd68cefb3ce487d4a13687b1868 and https://github.com/Komodo/KomodoEdit/commit/b38f06ec38e93ae982ebd98745e2480748af6131
