### ISSUE TITLE
Git integration stopped

### ISSUE THREAD

**Issue by NeilFraser** [Komodo/KomodoEdit#2644]
### Short Summary

Git integration stopped working about a month ago.

### Steps to Reproduce

System preferences:
![screen shot 2017-06-07 at 12 59 53](https://user-images.githubusercontent.com/250480/26877489-0631b020-4b82-11e7-9767-c917d80351a1.png)

Project preferences:
![screen shot 2017-06-07 at 13 00 50](https://user-images.githubusercontent.com/250480/26877495-09be86fa-4b82-11e7-8480-1b8520867cd6.png)

Komodo restarted.  Git verified on the command line.  GitHub client correctly reporting changes made by Komodo in project files.

### Expected results

Expect highlighting of changes in left margin, and available options in source control menu.

### Actual results

Highlighting of changes only reflects changes since last save.  Source control menu is disabled.
![screen shot 2017-06-07 at 13 03 58](https://user-images.githubusercontent.com/250480/26877646-75fbba18-4b82-11e7-9593-b2a03e44c9ed.png)

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?*  Version 10.2.2, build 89900
*Operating System (and version)?*  macOS 10.12.4

### Additional Information

git version 2.13.0.rc1.294.g07d810a77f-goog

I'm aware that Git integration currently causes Komodo to hang on macOS 10.12.4.  However it was mentioned in that issue that Git should be operating normally.

**Comment by Naatan** [comment]
I'm sorry but we cannot take bug reports for experimental builds. Let us know if you can reproduce this on a stable build.

Thay said, it may just require a restart after changing the pref in Komodo. Which would obviously be a bug but that might get you going right now.
