### ISSUE TITLE
KomodoIDE frequent crashes on OS X

### ISSUE THREAD

**Issue by cykonetic** [Komodo/KomodoEdit#2645]
### Short Summary
On a Mac OS X Sierra, Komodo randomly crashes

### Steps to Reproduce
I have been unable to determine the steps

### Expected results
A working IDE

### Actual results
An unresponsive IDE

### Platform Information
Komodo IDE, version 10.2.2, build 8989
macOS Sierra, 10.12.5 (16F73)

### Additional Information
Date/Time:       2017-06-07 09:22:29 -0400
OS Version:      Mac OS X 10.12.5 (Build 16F73)
Architecture:    x86_64h
Report Version:  25

Data Source:     Stackshots

Command:         komodo
Path:            /Applications/Komodo IDE 10.app/Contents/MacOS/komodo
Version:         10.2 (10.2.2)
Parent:          launchd [1]
PID:             8546

Event:           hang
Duration:        1.89s (process was unresponsive for 12 seconds before sampling)
Steps:           19 (100ms sampling interval)

Hardware model:  MacBookPro11,4
Active cpus:     8
[komodo_crash.txt](https://github.com/Komodo/KomodoEdit/files/1058121/komodo_crash.txt)

**Comment by Defman21** [comment]
https://github.com/Komodo/KomodoEdit/issues/2424#issuecomment-306282744
