### ISSUE TITLE
Enable/support *Convert to Uppercase/Lowercase* on strings containing numbers

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2646]
### Short Summary

Seems like it should work.

**Comment by Naatan** [comment]
Works for me

**Comment by cgchoffman** [comment]
Interesting.  It's because I used `cmd_delimitedBlockSelect`.  Apparently that doesn't enable the menu item under *Code> Convert selected Text*.

**Comment by cgchoffman** [comment]
Close for #2647
