### ISSUE TITLE
Unittest interpolation strings do not support Windows paths

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#2648]
### Short Summary

Carey found that bug here: https://github.com/Komodo/KomodoEdit/issues/2642#issuecomment-306896364

### Steps to Reproduce

1. Create an unittest that uses custom framework (so you can type your own command).
2. Use the `%F` placeholder in your command.

NOTE:  You can also paste a path in and it will fail so it's not related to `%F`.

### Expected results

Everything works fine.

### Actual results

Slashes were removed so the path is broken:

```
ERROR: file not found: C:UserscgchoProjectskomodocodeinteltestslanguage_testslegacyphptest_contexts.py
```

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* guess master branch? 😛 EDIT: This is in 10.2.2
*Operating System (and version)?* Windows

### Additional Information

Because @cgchoffman is busy and I'm not, I filed the bug myself :)

**Comment by Naatan** [comment]
Thanks @Defman21!

**Comment by cgchoffman** [comment]
Updated the ticket a bit.  It's 10.2.2.

**Comment by Naatan** [comment]
Can you still reproduce this on 11?

**Comment by cgchoffman** [comment]
Sorry for the delay, yes reproducible in 11.0.2
