### ISSUE TITLE
Set some default Mozilla prefs 

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2653]
### Short Summary

Make the following settings default in Komodo Mozilla:
```
gfx.direct2d.force-enabled -> True
gfx.font_rendering.cleartype.always_use_for_content -> True
gfx.font_rendering.directwrite.enabled -> True
```

NOTE to QA that this could effect Komodo performance.

**Comment by Naatan** [comment]
Note this should be windows only. Directwrite is apparently a windows only "feature".

**Comment by cgchoffman** [comment]
This doesn't need a QA note.  Just note if Komodo is excessively slow on windows and it MIGHT be this though there are many many other things it could be too.
