### ISSUE TITLE
Prefs window is broken on the master branch

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#2657]
### Short Summary

title. I can open it and see the categories, but clicking on them does nothing.

### Steps to Reproduce

1. Build Komodo Edit from the master branch.
2. Open prefs. (you'd have a profile already because the First Start Wizard window is broken too)

... or trust me that it's broken 😛 

### Expected results

Everything works and I'm able to change something without using `sdk:ko/prefs`.

### Actual results

I can't.

### Platform Information

*Komodo Edit or IDE?* Edit
*Komodo Version?* master branch
*Operating System (and version)?* Arch Linux

### Additional Information

```
JavaScript error: chrome://komodo/content/pref/pref.js, line 57: TypeError: modulePrefs is undefined
JavaScript error: chrome://komodo/content/pref/pref.js, line 123: TypeError: hPrefWindow is null
JavaScript error: chrome://komodo/content/pref/pref.js, line 123: TypeError: hPrefWindow is null
```

**Comment by Defman21** [comment]
![screenshot_20170617_111411](https://user-images.githubusercontent.com/7100645/27251361-182670bc-534e-11e7-9ab7-7bd1aa75d62a.png)

**Comment by cgchoffman** [comment]
This might be a missing commit from me.

**Comment by cgchoffman** [comment]
can't repro.  it's working fine now.
