### ISSUE TITLE
Version for version more make worse 

### ISSUE THREAD

**Issue by Fischmuetze** [Komodo/KomodoEdit#2661]
I'm using Komodo Edit since years. Unfortunately in the meanwhile this is the MOST BUGGY app on my Macs... It was a very, very beautiful program until version 8 but since this point the quality of the app decreased absolut dramatically for each update.
I have no other software on my Macs which is crashing so often. It crashed without any warning during the edit mode. The horizontal scroll behavior drives me nuts... it's so annoying very slow - no reinstallation nor clean the settings helps .. This app was make worse step by step ...

**Comment by mitchell-as** [comment]
Hi, sorry you've been experiencing so many problems with the random crashes :( You are likely experiencing #2424, which is being tracked. We hope to have a fix soon.
