### ISSUE TITLE
null chars added to end of file

### ISSUE THREAD

**Issue by gerrygrieve** [Komodo/KomodoEdit#2665]
### Short Summary
several null characters are added to bottom of files when  the file is Saved.
This has been happening with every save of php files; sometimes results in warnings
when running the file 
php x.php
Warning: Unexpected character in input: in /Volumes/homes/xtmp/x.php on line 15 ( last line)

i edit on   a iMac
System Version:	macOS 10.12.4 (16E195)
  Kernel Version:	Darwin 16.5.0

Komodo IDE, version 10.2.1, build 89853, platform macosx. Built on Wed Mar 8 

files are in a SMB mounted Volume from LInux server;

**Comment by cgchoffman** [comment]
It sounds like you're hitting an OSX SMB (evidently) long standing issue: https://community.activestate.com/node/10453

I would have thought OSX had solved this by now.  Are you using an old SMB protocol maybe?

**Comment by Defman21** [comment]
>https://community.activestate.com/node/10453

Access denied.

**Comment by Naatan** [comment]
I believe we have officially archived the older forums. Carey summarized it accurately though, this is and issue with samba (SMB), not with Komodo. The same issue is happening on other editors using the same mount. I'm not aware of there being a solution with Samba. I would suggest switching to cifs or sshfs.
