### ISSUE TITLE
TCL Syntax check: "zlib push compress chan": wrong # args

### ISSUE THREAD

**Issue by oehhar** [Komodo/KomodoEdit#267]
The following lines (from TCL http-2.8.8.tm) flag "wrong # of Arguments".
IMHO they are correct:
<attr>
zlib push compress chan
zlib stream compress
</attr>

Commodo 9.0.1

**Comment by Naatan** [comment]
Could you try setting Prefs > Tcl > Syntax Checking > "Force checking for specific Tcl/Tk Version" to "8.6" ?

**Comment by oehhar** [comment]
Naatan,
thank you for the message. This option is already set.
If you can not find it it is usual an old tclcollint.exe or however this is called on my side.

Thank you, please close the bug, not important,
Harald

**Comment by andreas-kupries** [comment]
Harald, given that you had the 8.6 option already set I have now tested the TDK checker with your example code.
I confirm that the current checker spits out these errors.
Reading the docs I believe you right that these are not errors and should not result in messages.
Will work on that ...
