### ISSUE TITLE
Implement better indent width detection

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#2673]
### Short Summary

From issue https://github.com/Komodo/KomodoEdit/issues/1756.

Komodo detects spaces vs tabs by scanning 300 lines of the code and making the decision based on the amount of spaces or tabs in these 300 lines. However, the width of an indent character is based on the first indentation. So, here's my comment:

>Why not checking which space width number is the most popular in the file rather than using the first indentation? So in case someone indents their 8-line config variable with 8 spaces and 280 lines of code with 4 spaces, their indent char will be 4 chars.

**Comment by Naatan** [comment]
In addition to this I think just checking the first ~30 lines should suffice (whilst saving on performance). If someone is doing considerably crazy stuff with indentation beyond there they're gonna need something other than indent detection to get them out of the woods (plus they clearly don't care about indentation anyway).

**Comment by Naatan** [comment]
Frankly I feel indentation detection is often missused. It's not something that should look at your file at a whole and detect the most commonly used indentation. If your files is using different types of indentation throughout then you evidently don't care about indentation.

Indentation detection is about automatically detecting the indentation of a file for those developers who care about indentation, but might simply have different files/projects that use different indentation levels for a variety of reasons.

I'd say there's a use case for detecting mixed indentation too, but that should be a different feature entirely. One that warns developers that their file is using mixed indentation and that they should probably fix that (using eg. a formatter).

**Comment by cgchoffman** [comment]
Re @mitchell-as's comment: Why don't we only check the first line after a function/class declaration?  Something that will/should always have a single indentation after it and is typically a very good indication of what the user is attempting to do in their file.  In @mitchell-as's example he points out that the majority of indentations are 8 space but relative to it's parent scope it's still only 4.

We could do this with the new code intel pretty easily.  Ask for the symbols in the file.  Get a couple functions and their scope line.  Check the indentation after that line.  

> I'd say there's a use case for detecting mixed indentation too,

@Naatan, we aren't talking about detecting mixed indentation are we?  Or are you factoring that in here?  Maybe the detection code could be a little less clever and just give up if it detects mixed results and says *Fix your code formatting*.

**Comment by mitchell-as** [comment]
@cgchoffman It's not quite that simple. I often break long function declarations into multiple lines like so:

```
function f(arg1,
           arg2,
           ...,
           argN) {
    // code
}
```

Properly detecting indentation would require syntactic parsing, which is expensive and can be error-prone.

**Comment by cgchoffman** [comment]
@mitchell-as, if you use the code intel suggestion the scope starts at line 4 and you would check line 5 so it should work fine.

**Comment by mitchell-as** [comment]
@cgchoffman Yes you are correct for the languages that support code intelligence, and for languages whose function definition lines are recognized to be on the last line of the definition. I wouldn't necessarily bank on the latter being the case in the future.

**Comment by cgchoffman** [comment]
> I wouldn't necessarily bank on the latter being the case in the future.

Fair enough, but I would say that that would be a reason to not support that feature in non-firstclass languages.

**Comment by Naatan** [comment]
# Feature overview

Indentation detection has been revised to be much simpler and straight forward. It will scan the first 250 lines of a file and use the shortest indentation found as the indentation used for that file. Lines that are comments or strings are not considered.

# Acceptance criteria

Open files using a variety of different indentation types/widths and ensure Komodo detects them properly. 

# Technical changes 

Only the underlying indentation detection mechanic changed, all the rest (API's and high level interactions) remain unchanged.

# Components to test

File opening, indentation preferences

**Comment by mjainQA** [comment]
Verified that indentation is detected properly.

**Comment by Defman21** [comment]
It doesn't for me. I have a simple Ruby file:

```
def test
  puts 123
end
```

If I open it, I have 4 spaces indent. I expect to see 2 spaces indent.

**Comment by Naatan** [comment]
Please report a new bug @Defman21

**Comment by Defman21** [comment]
Nevermind, forgot to enable the "Allow file contents to override Tab and Indentation settings" setting.
