### ISSUE TITLE
Find by filename in remote files?

### ISSUE THREAD

**Issue by PCGeekBrain** [Komodo/KomodoEdit#2678]
### Short Summary
Is it possible to search for files in a remote ftp server?

### Steps to Reproduce
open up a ftp server and look for files

### Expected results
the files that have that text in the filename on the server

### Actual results
nothing found unless currently open in the workbench

### Platform Information
Komodo Edit
10.2
Windows 10 15063.413

**Comment by cgchoffman** [comment]
This isn't currently a feature.  In the future, for questions please use the forums: https://community.komodoide.com/
And for feature ideas use: https://community.komodoide.com/c/feature-ideas

**Comment by PCGeekBrain** [comment]
Thanks 👍

**Comment by cgchoffman** [comment]
I had thought this might be possible using our remote commands ability but that would be only possible through SSH'd protocols.  I'll keep this open for now just incase we can think of something better later.

Forums ref:
https://community.komodoide.com/t/remote-file-search/3662/4?u=careyh

**Comment by Naatan** [comment]
There's nothing else to think of really. FTP has a limited set of commands you can run. Basically we'd have to manually run through directories to find files, which will be slow. Some FTP servers supply a find command of some sort but not all.

**Comment by PCGeekBrain** [comment]
What about for SCP and SFTP (SSH) connections?

**Comment by cgchoffman** [comment]
@PCGeekBrain, as i mentioned, it would ONLY be possible through SSH type protocols.  We typically would want the feature to be supported across all protocols we support.  I guess we'd have to weigh the benefits of implementing this feature for a subset of support protocols for an even smaller subset of our users.  This has been asked for but very rarely.

**Comment by Naatan** [comment]
Plus this is exactly why the Publishing feature exists. Frankly it is bad practice to be editing files directly via FTP, I don't feel inclined to spend resources on supporting a workflow that you ideally shouldn't adopt. 

You're running into limits with your current workflow, rather than try and force your needs into a workflow that evidently cannot support it why not try and adopt a new workflow more suited to your needs?

**Comment by PCGeekBrain** [comment]
:+1: Agreed. Sadly it is not my choice. oh, well. Thanks for the help. it is really appreciated :1st_place_medal:
