### ISSUE TITLE
FTP Remote files -> 200 TYPE is now 8-bit binary

### ISSUE THREAD

**Issue by PCGeekBrain** [Komodo/KomodoEdit#2680]
### Short Summary
I cannot find this anywhere else but this randomly starts happening when attempting to open remote files after some small amount of time

### Steps to Reproduce
open ftp files after some time

### Expected results
File opens in editor

### Actual results
Screen captured error opens

### Platform Information

Komodo Edit
10.2
Windows 10

#### Error log
```
[2017-07-11 14:55:10,394] [ERROR] koFTPConnection: FTP do_readFile ERROR: 200 TYPE is now 8-bit binary
ERROR:xpcom:Unhandled exception calling 'int8 * read(in int32, optional out uint32, out retval Array[]);'
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo Edit 10\lib\mozilla\python\xpcom\server\policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "C:\Program Files (x86)\ActiveState Komodo Edit 10\lib\mozilla\python\komodo\URIlib.py", line 942, in read
    return conn.readFile(self._uri.path)
  File "<XPCOMObject method 'readFile'>", line 3, in readFile
Exception: 2147500037 (NS_ERROR_FAILURE)
[2017-07-11 15:04:31,296] [ERROR] views: 
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIDocument.load]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://komodo/content/views.js :: viewManager.prototype._newViewFromURI :: line 602"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIDocument.load]'
+ result (number) 2147500037
+ name (string) 'NS_ERROR_FAILURE'
+ filename (string) 'chrome://komodo/content/views.js'
+ lineNumber (number) 602
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'viewManager.prototype._newViewFromURI@chrome://komodo/content/views.js:602:12
viewManager.prototype.'...232 chars
+ location (object) JS frame :: chrome://komodo/content/views.js :: viewManager.prototype._newViewFromURI :: line 602
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/views.js'
| + name (string) 'viewManager.prototype._newViewFromURI'
| + lineNumber (number) 602
| + columnNumber (number) 12
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/views.js :: viewManager.prototype._doFileOpen :: line 732
| + formattedStack (string) 'viewManager.prototype._newViewFromURI@chrome://komodo/content/views.js:602:12
viewManager.prototype.'...232 chars
| + stack
    viewManager.prototype._newViewFromURI@chrome://komodo/content/views.js:602:12
    viewManager.prototype._doFileOpen@chrome://komodo/content/views.js:732:11
    viewManager.prototype.doFileOpenAsync/<@chrome://komodo/content/views.js:757:19
-- EXCEPTION END --
```

#### screenshot
![capture](https://user-images.githubusercontent.com/12478828/28085503-ef94ad6c-6649-11e7-968d-a3ebdc833fc6.PNG)

**Comment by PCGeekBrain** [comment]
Refreshing the server from settings does not work either.

**Comment by cgchoffman** [comment]
I'm not following what's going on here.  Are you saying your firewall is blocking Komodo?  There isn't anything we can do about that.  How were you able to open a file if the firewall is blocking?  Does this work in a different FTP client?

**Comment by PCGeekBrain** [comment]
No, FileZilla works just fine with some occasional failed downloads when there are thousands of items in the queue. nothing out of the ordinary.

**Comment by cgchoffman** [comment]
That's a worrisome error.  What program do you have running that would be killing remote connections?

Are you able to reproduce this in *Help > Troubleshooting > Restart in Safe-mode*?

**Comment by PCGeekBrain** [comment]
I have a SSH background connection to a docker container. Maybe that is causing it? Let me take care of it and get back with more info in 10-20 min.

**Comment by PCGeekBrain** [comment]
Ok, I found out some interesting things.

1. This bug does not apply to SFTP (or at least does not appear to show itself as easily) so simply changing to SFTP and port 22

2. Safe-mode does not seem to change anything except actually _increase_ the frequency of the issue.

3. Constant background SSH connections to docker containers do not change anything related to this issue.

**Comment by Naatan** [comment]
This is really just your server providing an unstable connection. Filezilla is most likely just reconnecting you when a connection fails. Most komodo could do is be more permissive of failing connections (retries, timeouts).

**Comment by PCGeekBrain** [comment]
Makes sense. I guess I can contact them about it. Thanks Nattan 👍 . Sorry cgchoffman for wasting your time then.

**Comment by cgchoffman** [comment]
hey no worries @PCGeekBrain!  We're here to help.
