### ISSUE TITLE
An error is thrown while dragging and dropping a folder to a new location

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2682]
### Short Summary

An error is thrown when a folder is moved to a new location by dragging it.

### Steps to Reproduce

1. Move a folder to another location from places pane

### Expected results

1. No error should be thrown

### Actual results

1. An error message pops up. See the screenshot.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.2.3
*Operating System (and version)?* windows 10

### Additional Information
![image](https://user-images.githubusercontent.com/26605593/28090458-2dea548a-6641-11e7-8344-ce430e311bce.png)

**Comment by mjainQA** [comment]
Reproducible on MacOS.

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/b5eb3a7442e671532a78ccc2d294570bb951d904
