### ISSUE TITLE
uevent fails to load properly, causes Win10 task loop

### ISSUE THREAD

**Issue by WheelDogs** [Komodo/KomodoEdit#2685]
### Short Summary
package require uevent places system in loop

### Steps to Reproduce

"package require uevent

### Expected results

0.3.1  When using uevent installed from ActiveState

### Actual results
Debugging stops with this msg produced:
proc ::uevent::log::info args {uplevel 1 [linsert $args 0 ::logger::tree::uevent::info ]}

Output frame:
[Sat Jul 15 14:12:25 -0400 2017] [uevent] [info] 'function function -type -name -args'
[Sat Jul 15 14:12:25 -0400 2017] [uevent] [info] 'function function -type -name -args'
[Sat Jul 15 14:12:25 -0400 2017] [uevent] [info] 'function function -type -name -args'
[Sat Jul 15 14:12:25 -0400 2017] [uevent] [info] 'function function -type -name -args'
[Sat Jul 15 14:12:25 -0400 2017] [uevent] [info] 'function function -type -name -args'
[Sat Jul 15 14:12:25 -0400 2017] [uevent] [info] 'function function -type -name -args'
[Sat Jul 15 14:12:25 -0400 2017] [uevent] [info] 'function function -type -name -args'
[Sat Jul 15 14:12:25 -0400 2017] [uevent] [info] 'function function -type -name -args'
[Sat Jul 15 14:12:25 -0400 2017] [uevent] [info] 'function function -type -name -args'
[Sat Jul 15 14:12:25 -0400 2017] [uevent] [info] 'function function -type -name -args'
[Sat Jul 15 14:12:25 -0400 2017] [uevent] [info] 'function function -type -name -args'
[Sat Jul 15 14:12:25 -0400 2017] [uevent] [info] 'function function -type -name -args'
### Platform Information

Komodo Edit IDE 10.2.2

*Operating System (and version)?* 
Win 10 Pro Anniversary Update

App keeps running even when debugger stopped and Komodo exited.
There is no work-around.
Only way to terminate script is to use system task manager to end the task.

You can find your error log via Help > Troubleshooting > View Log File
-->

**Comment by mitchell-as** [comment]
Hi, thanks for the report. We'll look into this when we get the chance.

Note to self: figure out how to install uevent.

**Comment by WheelDogs** [comment]
teacup install uevent

**Comment by mitchell-as** [comment]
After internal discussion, this is not a Komodo issue, but a Tcl issue. ActiveState support will be handling with you @WheelDogs  via their support channel.

**Comment by WheelDogs** [comment]
If that is the case then why is there no issue with the script executing from directly from ActiveState TCL wish.
