### ISSUE TITLE
Overzealous quote matching.

### ISSUE THREAD

**Issue by NeilFraser** [Komodo/KomodoEdit#2688]
### Short Summary

When changing `===` to `!==` the quote matcher likes to be 'helpful' and give you `!=!`

### Steps to Reproduce

In a JavaScript file, add this line:
`a === b;`
Select the first `=` and replace with `!`

### Expected results

`!==`

### Actual results

`!=!`

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.2.2, build 89898
*Operating System (and version)?* macOS 10.12.5

### Additional Information

This is an example of quote matching being overzealous.  Maybe there's a general fix.  But this specific instance does keep popping up pretty regularly.

**Comment by cgchoffman** [comment]
It sounds like you've add `=` to your preferences.  I can't reproduce this.  Check *Edit > Prefs > Editor > Smart Editing: Wrap selection with typed...* and see if `=` is in the *Delimiter* list.

**Comment by NeilFraser** [comment]
Here's a video showing that turning on or off the "Wrap selection with typed..." option doesn't seem to do much:
  https://www.youtube.com/watch?v=Zp2jWDQe1Sg

Also visible in the video: when physically unchecked, the sub-options under this option become disabled, but when the dialog is loaded with the option unchecked, the sub-options are enabled.

**Comment by mitchell-as** [comment]
Thanks, reproduced.
