### ISSUE TITLE
Error message while trying to create a new file from Python3 template

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2689]
### Short Summary
An error is thrown while trying to create a new file from Template for Python3

### Steps to Reproduce

1. Right click on a folder
2. Select File from a template and select python3
3. Provide filename and save it without extension.

### Expected results

1. A file should be created

### Actual results

1. An error is thrown. See the screenshot.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.2.3
*Operating System (and version)?* macOS

### Additional Information

 
![pythontemplateerror](https://user-images.githubusercontent.com/26605593/28285910-44652e48-6aeb-11e7-9bf3-076b20b805c7.png)

**Comment by mjainQA** [comment]
Sporadic issue. I am unable to reproduce it again.

**Comment by cgchoffman** [comment]
Dupe: #2165
