### ISSUE TITLE
Tcl not in language list

### ISSUE THREAD

**Issue by btjanes** [Komodo/KomodoEdit#269]
This is with Komodo Edit 9, which I'm trying out before upgrading my Komodo IDE.

![screenshot from 2015-05-13 11 15 53](https://cloud.githubusercontent.com/assets/12431549/7614159/fd6398a0-f962-11e4-8ec6-ebdc695b4f1b.png)

**Comment by Defman21** [comment]
Try Komodo IDE 9 trial.
![scr](http://i.imgur.com/Hfp8SW5.png)

**Comment by btjanes** [comment]
OK, I can do that.  The problem is that I actively work on 2 machines.  Does the IDE license allow me to share machines or would I need a separate license for each installation?

**Comment by Defman21** [comment]
If both machines are yours - you can use your license on both of them. Am I right @Naatan?

**Comment by btjanes** [comment]
That would be wonderful.  Both machines are mine.  My Mac died over the
weekend (power button failure that apparently requires a full chassis
replacement???) and I'm working on my travel laptop.  If I can use the same
license between these machines, I'd be a happy camper.


*Brian Janes*
Lead Software Architect
Runtime Design Automation
Phone: (408) 320-RTDA (7832)
E-mail: brian.janes@rtda.com
Web: www.rtda.com

On Wed, May 13, 2015 at 12:25 PM, Sergey Kislyakov <notifications@github.com

**Comment by cgchoffman** [comment]
You do **not** need to own the computer you install Komodo on.  You **do** need to be the only one using Komodo under your license.

**Comment by Defman21** [comment]
Oh, excuse me for the wrong information I gave.

**Comment by cgchoffman** [comment]
That's ok @Defman21.  Probably better for you to leave licensing questions to us or point people to the website.

**Comment by Defman21** [comment]
Next time I leave it for you guys :smiley:

**Comment by btjanes** [comment]
Thanks for the clarification guys.  I'll download and install IDE here and
give it a go.


*Brian Janes*
Lead Software Architect
Runtime Design Automation
Phone: (408) 320-RTDA (7832)
E-mail: brian.janes@rtda.com
Web: www.rtda.com
