### ISSUE TITLE
Ruby (.rb) files unable to interpret the "gets" method

### ISSUE THREAD

**Issue by ShanWehttam** [Komodo/KomodoEdit#2692]
Product = Komodo edit version 10.2.0 build 17657 on windows 10

Please see below in italic text, a simple example file that fails to run correctly in Komodo edit

_#!/usr/bin/env ruby_

_puts "What is your name?"
name = gets
puts "What is your age?"
age = gets_

When this file is run, the "gets" messages are interpreted first.  The file cannot execute properly until the user has input his/her answer to both of the above questions.  This is incorrect.  The puts statement "What is your name?" should be executed first, before the user has a chance to enter their input.

How do i know this?
Running the same file in the command line yields the expected behaviour.  The issue must be specific to Komodo.

Its worth mentioning how easy its been to raise an issue with yourselves straight from the IDE.  Thumbs up.

**Comment by mitchell-as** [comment]
Thanks for the report.

Note: from Komodo IDE, F7 (run without debugging) reproduces the issue, while F5 (debug) does not exhibit the issue.

**Comment by cgchoffman** [comment]
@mitchell-as, @ShanWehttam is using Edit.  They aren't using the debugger.   

@ShanWehttam, how exactly are you running your script?

**Comment by mitchell-as** [comment]
@cgchoffman I know, and Edit has a "run without debugging" kind of feature, so the problem exists in IDE too. I added the extra information about IDE's "debug" working properly to pinpoint the problem is in "run without debugging" specifically.

**Comment by cgchoffman** [comment]
so are you talking about *Tools > Commands* then running `%ruby %F` or something?  That's the only "run without debugging" method I know in Edit.  Also, anything debugging would be more up your alley I think.   I don't think i'm the right person for this ticket.

**Comment by mitchell-as** [comment]
After some further investigation, I've concluded this is not a bug. When you execute your script in a terminal, the terminal keeps the stdout and stdin buffers in sync. When Komodo launches the external process, it communicates over pipes, which are buffered, and not kept in sync (due to the nature of pipes). You'll have to have Ruby sync at least `$stdout` in order to work. Adding

`$stdout.sync = true`

to the top of the file in Komodo caused Komodo to execute the file properly.

**Comment by ShanWehttam** [comment]
Thank you both for investigating this.
 @cgchoffman   You're right, I do use %(ruby) "%F" to run my scripts in the editor
@mitchell-as Thank you for your solution.  Placing '$stdout.sync = true' at the top of my file does the trick.
