### ISSUE TITLE
IDE Stops Responding, and has to be forced killed on Mac/OS

### ISSUE THREAD

**Issue by kalash-bepress** [Komodo/KomodoEdit#2695]
### Short Summary
Periodically, the IDE will stop responding (often when being switched to from a different app, but sometimes while using it). I get an infinite beach ball, and have to kill it from the Activity Monitor.

### Steps to Reproduce
It is random on  my side. It can happen about once every 2 days, up to twice a day.

### Platform Information

Komodo IDE
10.2.2 build 89895
MacOS Sierra 10.12.5

### Additional Information
I've twice remembered to "sample" the app before killing it. I'm including those (it freezes more often than these 2 dates would imply, I just normally kill and restart to get work done).

I'm also including the pystderr.log, even though it looks to only cover the time since restart, however maybe it says something useful.

NOTE: I have a commercial license and active serial number, should anyone need it.

[pystderr.log.zip](https://github.com/Komodo/KomodoEdit/files/1163284/pystderr.log.zip)

[Sample of Komodo July 13, 2017.txt](https://github.com/Komodo/KomodoEdit/files/1163265/Sample.of.Komodo.July.13.2017.txt)
[Sample of Komodo Jul 20 10-40.txt](https://github.com/Komodo/KomodoEdit/files/1163266/Sample.of.Komodo.Jul.20.10-40.txt)

**Comment by cgchoffman** [comment]
HI @kalash-bepress, you're liking hitting #2424.  Please try this build and see if it resolves your issue: http://downloads.activestate.com/Komodo/nightly/komodoide/latest-10.2.x/

**Comment by kalash-bepress** [comment]
Thanks! Running it now, I'll report back if it goes all funny :)
