### ISSUE TITLE
There was an error attempting to save 'FileName': 451 Failure writing to local file

### ISSUE THREAD

**Issue by Pyr0o** [Komodo/KomodoEdit#2697]
### Short Summary
When trying to remote edit a file, when I save I get the error "There was an error attempting to save 'FileName': 451 Failure writing to local file". I've tried deleting the file and creating it again but still get the same error when I try to save.
The remote file was empty when I tried to open it again. I lost a lot of work from this bug 

### Steps to Reproduce
I'm not sure what caused it but it occurred randomly when trying to save to a remote directory

### Expected results
Saves the remote directory file

### Actual results
An error

### Platform Information

Komodo Edit, version 10.2.2, build 17703, platform win32-x86. Built on Sat Apr 29 02:34:29 2017.

OS: Windows 10

**Comment by cgchoffman** [comment]
@Pyr0o, sorry you lost work.  Could you get your logs if you haven't restarted Komodo yet? *Help > troublelshooting > View Log file*

Could you provide any more details of the steps you took leading up to this?  Had you been editing the file for some time?  Had you open and closed it before?  Had you been able to save it before?  How are you connecting to this remote file?  Is it a mounted drive or are you using a remote connection in Komodo?

**Comment by Pyr0o** [comment]
I have restarted Komodo as administrator but here is the log anyway: https://pastebin.com/3DA8ECgq

I had been editing this file for about a week now and have closed and opened it several times before.
I am using the FTP service in komodo remote directory

**Comment by Pyr0o** [comment]
Ok, I figured it out. Its not a bug. My FTP server was full! my bad dude

**Comment by Pyr0o** [comment]
Sorry for wasting your time

**Comment by cgchoffman** [comment]
hey glad I could help! (i didn't help...)  Thanks for letting us know you resolved it.
