### ISSUE TITLE
SCC Show Changes in New Window Opens Minimized

### ISSUE THREAD

**Issue by wdbaker54** [Komodo/KomodoEdit#2698]
I am running Komodo IDE 10.2.2 on Ubuntu Linux 16.04 using the Unity graphical shell.

Any time I request a Source Code Control -> Show Changes in File with my preferences set to show changes in a new window, the new window opens with only a single line visible and I either have to grab the border and expand the window or click on the maximize button to see the changes.

I saved my .komodoide directory and re-opened Komodo with all default settings to see if some setting or other was causing it and the problem was still there. I wish I had a Mac or a PC to see if the OS was affecting it but I don't.

I don't recall this happening using Komodo 9 on the same platform.

**Comment by wdbaker54** [comment]
As much as I hate to admit it - I logged in using the Gnome shell instead of Unity and the problem went away - the window opened normally. I guess it is related to Unity and is not a problem with Komodo. I will close this ticket and start using Gnome as much as I hate to.

**Comment by Naatan** [comment]
fwiw http://www.omgubuntu.co.uk/2017/04/make-gnome-shell-look-feel-like-unity :)

**Comment by wdbaker54** [comment]
Thanks, Nathan. That helps.
