### ISSUE TITLE
Commando:  Doesn't work with relative paths.

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#27]
Entering ".." or "..\.." to ascend directories in commando results in "No Results".  This using the Files scope and the Everything scope, where I would expect them to work.

**Comment by Naatan** [comment]
Typing `../` works, but yeah it would make sense if just `..` works.

`....` isn't a thing, far as I'm aware.

**Comment by cgchoffman** [comment]
ya, "...." is not a thing. "..\\.." is though (hopefully two escape characters work this time?).  "../.." didn't work either.

**Comment by cgchoffman** [comment]
I think you mentioned that you wanted me to take this one Naatan.  Take it back if I'm wrong.

**Comment by Naatan** [comment]
I'm actually not able to reproduce this one on Windows. Is this still happening for you?

**Comment by cgchoffman** [comment]
Can't repro any more.

**Comment by cgchoffman** [comment]
Oh I finally got a repro.  This seems to only occur when there is no file open.  Should have a fall back to work relative paths from.

**Comment by Defman21** [comment]
You may want to update the milestone :)

**Comment by cgchoffman** [comment]
No need! Looks like it's working.  Thanks for pinging.

**Comment by Defman21** [comment]
`..` does not work for me.

**Comment by cgchoffman** [comment]
Are you running Windows?

**Comment by Defman21** [comment]
Linux. I think it would be better If I open a new issue.
