### ISSUE TITLE
Can't install packages on Windows

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2700]
### Short Summary

Trying to install a package through Commando on Windows results in a error when a portion of the code tries to `join` to strings together into a path.

I don't know how this broke but based on the fix I've found I don't know how this ever worked:

```
Index: C:\Users\cgcho\Projects\komodo\KomodoIDE-10.2.x\src\modules\scope_packages\content\packages.js
--- a\modules\scope_packages\content\packages.js
+++ b\modules\scope_packages\content\packages.js
@@ -1081,1 +1081,1 @@
     {
-        var filename = url.match(/[^\/\\]+$/);
+        var filename = url.match(/[^\/\\]+$/)[0];
         var target = OS.Path.join(dir || OS.Constants.Path.tmpDir, filename);
```
I've investigated the `typeof url` and it's just a *string*.  When i perform the actions manually in the JS console in Komodo I get the same error, eg.:
```
var s = "foobarbaz"
var ns = s.match(/foo/)
f.join(ns,"bar") // arg.split is not a function
Cu.import("resource://gre/modules/osfile.jsm");
OS.Path.join(ns,"bar") // path.startsWith is not a function
OS.Path.join(ns[0],"bar") // String "foo\bar"
```
 ` OS.Path.join` can't take an `match` object.  It doesn't seem to know what to do with it.  I've tried using `require("ko/file").join` and get a similar error which basically implies "this isn't a string so i can't do anything with it".

### Steps to Reproduce

- Open Commando > Packages > Color schemes (or any other package)
- select one to install

### Expected results

 Package to install

### Actual results

Commando UI hangs for about 10 seconds then shows a timeout notification

### Platform Information

10.0, 10.2.2 and 10.2.3 have been tested so far.
Windows

### Additional Information

*Error*
```
[2017-07-21 11:38:07,484] [ERROR] console-logger: TypeError: path.startsWith is not a function (2) in resource://gre/modules/osfile/ospath_win.jsm:195
Traceback (most recent call last):
  File "resource://gre/modules/osfile/ospath_win.jsm", line 195, i
```

**Comment by Naatan** [comment]
@cgchoffman didnt you fix this?

**Comment by cgchoffman** [comment]
:S I don't remember.  Someone must have.

**Comment by cgchoffman** [comment]
@mjainQA, this needs to be confirms on all platforms.  I checked Windows and OSX with this patch but a double check would be good.
