### ISSUE TITLE
Notification feature shows releasenotes for the current version rather than New release

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2701]
### Short Summary

I'll start by apologizing if i've tested this wrong but there isn't a zube card that I can find that has a feature outline.
Was testing the release notification screen.  After reading the code it looks like it looks for a versioned URL for releasenote:
```
ko.prefs.getString("versioncheck.url") // String "http://docs.komodoide.com/changelog/%s"
```
So if I'm running Komodo 10.2 it will look for  http://docs.komodoide.com/changelog/10 on it's first attempt (it then looks for a point release but that's not important here).

If it finds that then it will serve up that page in the notification window but if the point of the window is to alert users of a newer version of Komodo then it should load http://docs.komodoide.com/changelog which presumably would be the latest.

### Steps to Reproduce

- Create  http://docs.komodoide.com/changelog/10 with notable text like "THIS IS A TEST FOR KOMODO 10"
- Start Komodo 10.2.3
- wait for notification dialog to appear

### Expected results

Release notes from http://docs.komodoide.com/changelog/ which presumably would be Komodo currentVer +1.

### Actual results

`THIS IS A TEST FOR KOMODO 10` is in the notification window.

**Comment by Naatan** [comment]
This is exactly what it is meant to do :) The reason being we want to be able to target different older versions of Komodo to inform them about the latest version of Komodo available.

**Comment by Naatan** [comment]
https://activestate.slack.com/archives/C03NU4MN5/p1500679117192676

**Comment by cgchoffman** [comment]
This needs a zube card.  It's not clear what's supposed to happen or how it's supposed to be tested.

**Comment by Naatan** [comment]
I'll write it out when I'm back from vacation, but in essence it is meant to show the popup when the url configured returns a 200 or 301 http code, in any other event it should do nothing. It's a very "dumb" feature that I kept intentionally dumb due to the timing.

**Comment by Naatan** [comment]
Btw please don't create those doc pages unless we are releasing 11. For testing you can just change the pref value.

**Comment by cgchoffman** [comment]
> For testing you can just change the pref value.

Change the code to test the code?  That doesn't sound like a good test method.

**Comment by Naatan** [comment]
You're not changing the code, you're changing a pref. Being the author of this code I'm perfectly comfortable with that suggestion.
