### ISSUE TITLE
CodeIntel: Need to forward user-specified directories as "importPaths"

### ISSUE THREAD

**Issue by mitchell-as** [Komodo/KomodoEdit#2705]
Right now, Komodo forwards environment variables like `PYTHONPATH` and `RUBYLIB` to the new CodeIntel as additional directories to look for imports in.

`src/modules/codeintel/content/sdk/feature/completions.js:101`:
```
var key = languages[view.language].extrapaths;
importPaths = view.koDoc.getEnvVar(key);

service.getCompletions(..., importPaths, ...)
```

However, Komodo also needs to forward along any user-specified directories (e.g. via Edit > Preferences > Languages > Python > Additional Python Import Directories).

This probably would involve pre-pending a `:`-separated list of directories to the appropriate environment variable (if any). For example, given a `PYTHONPATH` of `/foo` and additional Python import directories of `/bar` and `/baz`, `importPaths` should be `/bar:/baz:/foo`. Note: *all* environment variables are `:`-separated -- there are no language-specific separators.

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/d96ede3f4e68da1b933774df422e6590dd3034f9
