### ISSUE TITLE
Windows: Can't install Komodo 11 side-by-side K 10

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2709]
### Short Summary

Should be able to have both installed

### Steps to Reproduce

- Have Komodo 10 installed
- Run Komodo 11 MSI installer

### Expected results

- Installer to run

### Actual results

![capture](https://user-images.githubusercontent.com/655154/28588247-d0c72d98-712e-11e7-910a-ab7e7e53466c.PNG)

**Comment by cgchoffman** [comment]
I don't know if this is a regression or not so not sure it requires the *Introduce in 11* label

**Comment by Naatan** [comment]
Probably some wix specific config file that needs updating?

**Comment by cgchoffman** [comment]
I can't remember.  But we've hit this before with nightlies so hopefully I can find that ticket and see how we fixed it rather than digging into how Windows identifies installers again.

**Comment by Defman21** [comment]
I installed K11 QAC (QA Community) build side-by-side K10.

**Comment by cgchoffman** [comment]
@Defman21 OS?  This should be labelled Windows Only.

**Comment by Defman21** [comment]
Windows 10.

**Comment by cgchoffman** [comment]
Oh you're using a "nightly".  That was fixed a while ago.  I had a "release" build when I tested this.  I'll have to check this again when we have an Release Candidate build.  Thanks for confirming @defman21

**Comment by Defman21** [comment]
The new QA build gives me this error :(

**Comment by cgchoffman** [comment]
> UPD: removing the previous QA build solves the problem.

yep.

**Comment by Naatan** [comment]
In that case the error was actually appropriate.

**Comment by Defman21** [comment]
I thought it would either override the installation or remove it and then install a new one.

**Comment by cgchoffman** [comment]
Only if it's an identical installer will it ask if you want to do something with the old install.   It would be an enhancement request if we were to change this behavior.

**Comment by cgchoffman** [comment]
Forgot about this.  This is indeed an issue still :(

**Comment by cgchoffman** [comment]
Looking into #1403.

**Comment by cgchoffman** [comment]
Thank goodness for issue trackers: https://github.com/Komodo/KomodoEdit/commit/b69305796a85f716e7a051474b84934fb3ebb4cd

**Comment by cgchoffman** [comment]
@mjainQA:
On Windows, install Komodo IDE/Edit 10 using the MSI.  Then do the same for Komodo 11 latest RC (RC3 or later).

You should have no issues installing both on your computer.
