### ISSUE TITLE
Integrate EditorConfig

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#271]
https://github.com/editorconfig/editorconfig-core-py#readme
http://editorconfig.org/

**Comment by cgchoffman** [comment]
contact point for EditorConfig if needed: OTRS#030034846

**Comment by we3geeks** [comment]
Previously logged as https://bugs.activestate.com/show_bug.cgi?id=94369 and https://bugs.activestate.com/show_bug.cgi?id=101281 in the old bug tracker, and touched on more recently in the forums at http://forum.komodoide.com/t/support-for-editorconfig/1234

Particularly as a member of a team using Komodo, I'd love to see this get some attention.
