### ISSUE TITLE
Tool detection:  Go gets grouped with Tools section

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2710]
### Short Summary

Go interpreter is showing up in the *Tools* section of the Component Detection screen.

### Steps to Reproduce

- Help > Run Startup Wizard again
- Proceed to Component detection screen
- Find Tools section

### Expected results

`Go` to be in the *Languages* section

### Actual results

`Go` is in the *Tools* section

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoIDE/commit/4b6e5927220262747cc6ce46b3682c09335f0cf4
