### ISSUE TITLE
CodeIntel: Typing after completions and then selecting inserts too much

### ISSUE THREAD

**Issue by mitchell-as** [Komodo/KomodoEdit#2711]
After triggering a code completion list, type part of a prefix and then press Enter. Instead of the trailing bit of the completion after the typed prefix, the entire completion is inserted. This is incorrect.

In a JavaScript file, start typing: `re`. You'll get some completion candidates including the "return" keyword. Type an additional `t`. Now press enter. I expect to see `return` inserted, but instead I get `retreturn`.

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/89c63385e9b131bb79101d1c54fa4242e11f4925
