### ISSUE TITLE
codeintel, rvm, ruby not finding libraries

### ISSUE THREAD

**Issue by jcobol** [Komodo/KomodoEdit#2715]
### Short Summary

Code intelligence fails to find libraries that I have installed into the 'rvm' Ruby environment.

### Steps to Reproduce

Install rvm, Chef, Komodo.
Configure Komodo to look for Ruby libraries in /usr/local/rvm/gems/ruby-2.4.1/gems/chef-13.1.31/lib
Allow code intelligence database to update.
Start typing require line:

  require '

Also tried adding /usr/local/rvm/gems/ruby-2.4.1/gems/chef-13.1.31/lib/chef/
and setting the Ruby interpreter to /usr/local/rvm/bin/rvm-auto-ruby but it didn't help.

### Expected results

Notice that expected libraries (eg. chef) don't show up in code intel.

### Actual results

Only core modules are listed as suggestions.

### Platform Information

*Komodo Edit or IDE?*
Komodo IDE
*Komodo Version?*
10.2.2
*Operating System (and version)?* 
CentOS 7

### Additional Information

Full background is discussed here:
 https://community.komodoide.com/t/rvm-ruby-chef-code-intelligence/3669/6

**Comment by mitchell-as** [comment]
This should be fixed in Komodo 11 with its CodeIntel improvements.
