### ISSUE TITLE
kopy.io doesn't work

### ISSUE THREAD

**Issue by mikhalenia** [Komodo/KomodoEdit#2716]
### Short Summary
https://kopy.io doesn't work now.

### Steps to Reproduce
1. Open site in any browser

### Expected results
Stable state of the site

### Actual results
502 Bad Gateway

### Platform Information
Ubuntu 15.10

**Comment by mitchell-as** [comment]
Thanks for the report.

**Comment by Naatan** [comment]
kopy.io is back up
