### ISSUE TITLE
CodeIntel: Completions often stop working

### ISSUE THREAD

**Issue by mitchell-as** [Komodo/KomodoEdit#2719]
CodeIntel simply stops working quite often due to the error:

    JavaScript error: chrome://codeintel/content/sdk/feature/symbollist.js, line 431: TypeError: view._symbollist.close is not a function

Simply create a new file, select a codeintel-supported language like Python, start typing and get some completions. Repeatedly hit backspace until the file is empty, start typing again. At some point completions stop coming and you get the error above.

In my case, in a Python file I repeatedly typed "im" in order to trigger completions for the keyword "import", pressed backspace twice, typed "im" again. After two or three cycles I eventually got the JS error above and codeintel stopped working until I restarted Komodo.

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/eb4e778d2fcdfc3b302fa3acf80a78a660767fe9
