### ISSUE TITLE
Color Picker Hangs/Crashes

### ISSUE THREAD

**Issue by webdevdonnie** [Komodo/KomodoEdit#272]
In full screen mode, KomodoEdit will attempt to launch mac_osx_color_picker on hover over any hex value.

Sometimes it hangs indefinitely without fully opening the picker, and sometimes will even crash editor. Other times, can just be cancelled etc. It's quite annoying that it even pops up at all, should only be activated on click.

Selecting john_dyer_color_picker seemed to stop the hang/crash issue.

When editing CSS, I usually have my hex color values commented out for easy copy/paste. Perhaps an option for no color picker would be super rad in future updates?

Thanks!

**Comment by Naatan** [comment]
What version of Komodo are you using?

**Comment by webdevdonnie** [comment]
Komodo Edit, version 8.5.4, build 14424, platform macosx.
Built on Wed Aug 13 23:56:46 2014.

**Comment by Naatan** [comment]
Please update to 9.0.1, this should be fixed in that version.
