### ISSUE TITLE
Symbol Browser warns "Buffer is not supported" when New Tab view is open

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2729]
### Short Summary

Might need a special case for New Tabs.  

### Steps to Reproduce

Close all files
open Symbol browser

### Expected results

"Open Supported File/Buffer"

### Actual results

![capture](https://user-images.githubusercontent.com/655154/28735991-9eb09216-739c-11e7-9449-9a7ee76fd1be.PNG)

**Comment by Naatan** [comment]
Basically the thing wrong here is that it refers to the "current buffer" when no buffer is currently open. The message needs to be more generic. "Nothing shown" is not a proper solution.

**Comment by cgchoffman** [comment]
makes sense.  Updating ticket.

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/c39997d3f56dc2bd42253ab42d33e64310cc3ba4
