### ISSUE TITLE
komodo start failure

### ISSUE THREAD

**Issue by lorenrosen** [Komodo/KomodoEdit#273]
latest 9.0.1 (from 15 April)
suddenly komodo wouldn't start. The error log has
-- EXCEPTION START --
Error: path does not exist: /home/loren/.komodoedit/9.0/XRE/icons/fileicons/PHPPHP16.png.forcedAttrs.svg
+ stack
    friendlyError@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:62:1
    ensureExists@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:54:11
    ensureFile@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:47:3
    remove@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:174:3
    _createPngFromSvg/img.onload/<@chrome://komodo/content/sdk/icons.js:586:25
    notify@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/timers.js:40:9
-- EXCEPTION END --

temporarily got komodo to start by copying a likely sounding file into the file it was looking for. But before that I hadn't modified the icons stuff, so I have no idea why it wouldn't start.

**Comment by Naatan** [comment]
The error you pasted in is a known bug but should not stop Komodo from starting. Could you post the rest of your error log when Komodo has failed to start?

**Comment by lorenrosen** [comment]
Wouldn't start again. May not be the same issue. There's no recent stack trace. End of the error log shows a truncated trace from day before yesterday.

[2015-05-16 17:13:05,010] [ERROR] console-logger: TypeError: topView.findViewsForURI is not a function (2) in chrome://breadcrumbs/content/breadcrumbs.js:430
Traceback (most recent call last):
  File "chrome://breadcrumbs/content/breadcrumbs.js", line 430, in 

[2015-05-16 17:16:39,502] [ERROR] ko.extensions.todo: 
-- EXCEPTION START --
[Exception... "Component not initialized"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: chrome://todo/content/todo-ko7.js :: this.TodoSearcher.prototype.observe :: line 223"  data: no]
+ toString (function) 3 lines
+ message (string) ''
+ result (number) 3253927937
+ name (string) 'NS_ERROR_NOT_INITIALIZED'
+ filename (string) 'chrome://todo/content/todo-ko7.js'
+ lineNumber (number) 223
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'this.TodoSearcher.prototype.observe@chrome://todo/content/todo-ko7.js:223:48
_doSave@vieweditor:1157'...421 chars
+ location (object) JS frame :: chrome://todo/content/todo-ko7.js :: this.TodoSearcher.prototype.observe :: line 223
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://todo/content/todo-ko7.js'
| + name (string) 'this.TodoSearcher.prototype.observe'
| + lineNumber (number) 223
| + columnNumber (number) 48
| + sourceLine (string) ''
| + caller (object) JS frame :: vieweditor :: _doSave :: line 1157
| + formattedStack (string) 'this.TodoSearcher.prototype.observe@chrome://todo/content/todo-ko7.js:223:48
_doSave@vieweditor:1157'...421 chars
| + stack
    this.TodoSearcher.prototype.observe@chrome://todo/content/todo-ko7.js:223:48
    _doSave@vieweditor:1157:16
    save@vieweditor:1294:27
    viewManager.prototype.do_cmd_save@chrome://komodo/content/views.js:1833:4
    xtk.Controller.prototype.doCommand@chrome://xtk/content/controller.js:91:8
    command_doCommand@chrome://komodo/content/library/commands.js:263:0
    command_doCommandAsync/<@chrome://komodo/content/library/commands.js:220:12
-- EXCEPTION END --
[2015-05-16 17:16:39,569] [ERROR] console-logger: TypeError: topView.findViewsForURI is not a function (2) in chrome://breadcrumbs/content/breadcrumbs.js:430
Traceback (most recent call last):
  File "chrome://breadcrumbs/content/breadcrumbs.js", line 430, in 

 The full error log, 1600+ lines long, shows a number of errors from that day, but I don't think it will attach. Can email it or whatever.
[Uploading pystderr.log …]()

**Comment by Naatan** [comment]
No reproducible bug here, closing. Thanks for taking the time to report, please let us know if the problem happens again and there is a clear causation.
