### ISSUE TITLE
Commando: Can't use right key to move cursor through text field

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2730]
### Short Summary

In Commando it looks like the "perform action on selected item" action is triggered too easily.  In Komodo 10 it didn't trigger unless your cursor was at the end of the word.  It now triggers no matter where in search query your cursor is.

### Steps to Reproduce

- open commando
- type a query
- move cursor left using left arrow key
- move cursor right using right arrow key

### Expected results

Cursor to move right

### Actual results

Opens the action menu for what ever item is selected

**Comment by Naatan** [comment]
It should only do this if the cursor is at the end of the text selection already. Are you saying it did this while the cursor was in the middle of the text?

**Comment by cgchoffman** [comment]
> Are you saying it did this while the cursor was in the middle of the text?

Yes, as soon as I hit the right arrow with the cursor anywhere in the string it will trigger the menu:

![commando](https://user-images.githubusercontent.com/655154/28835840-a3681836-769b-11e7-9779-543bcd08ebd8.GIF)

**Comment by Naatan** [comment]
Thanks! That's no good.
