### ISSUE TITLE
Selected file box is cut off by scroll bar

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2731]
### Short Summary

The selected file box is oddly cut off by scroll bar

### Steps to Reproduce

1. Select any file in places pane

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 11 - Build July 28th
*Operating System (and version)?* macOS

### Additional Information

 
![image](https://user-images.githubusercontent.com/26605593/28739027-262617ac-73ac-11e7-8893-bd6420a8cef5.png)

**Comment by Naatan** [comment]
This is by design, the scrollbar is floating on top. Nothing is being cut off, you'll note if there is text that spans that far it won't go underneath the scrollbar.
