### ISSUE TITLE
Warning: main(): Couldn't fetch mysqli_result in C:\wampserver\www\.......\.......php on line 151

### ISSUE THREAD

**Issue by mshrage-snt-net** [Komodo/KomodoEdit#2734]
### Short Summary
Debugger appears to crash with Warning: main(): Couldn't fetch mysqli_result in C:\wampserver\www\upload-rmc-content-files\upload2-rmc-content-files.php on line 151

### Steps to Reproduce
Step to line 151 - line is mysqli_free_result(sql1result);
long delay then the crash information in HTML output panel.

### Expected results
no delay and no crash.

### Actual results
long delay then the crash information in HTML output panel.

### Platform Information

*Komodo Edit or IDE?* 
Kormodo IDE 10
*Komodo Version?* 
10
*Operating System (and version)?* 
Windows 10

**Comment by Defman21** [comment]
That's a warning in your code, I doubt Komodo is related to it.

**Comment by Naatan** [comment]
As Defman said, this is your code throwing a warning. Since you run it through the debugger the debugger will simply log it for you.
