### ISSUE TITLE
Symbol Browser missing icons.

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2736]
### Short Summary

If you point me in the right direction I could probably take this.  Feel free to assign back to me with a note of where to look.
Many scopes are missing icons in the symbol browser.  They all seem to be the default object `STRU`.
![capture](https://user-images.githubusercontent.com/655154/28840099-bdb7ef40-76aa-11e7-8be9-97bc80f4e171.PNG)

### Steps to Reproduce

- open the symbol browser (*Ctrl+shift+c*)

### Expected results

All items should have icons

### Actual results

Many don't have icons

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/c5d64baef992b69fd7342821b1a9bec4fa295e81
