### ISSUE TITLE
"import .. as .." shows "as" value as completion

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#2737]
### Steps to Reproduce

Create python code:

```
import os as foobar<|>
```

### Expected results

no completions

### Actual results

foobar is shown as an autocompletion (and it says that the catalog is the source)

**Comment by mitchell-as** [comment]
I'm not seeing this in latest master. Can you still reproduce?

**Comment by Naatan** [comment]
Hmm nope.. strange, not like I've been fixing codeintel bugs :p Anyway tests are still running fine, so I guess.. magic?
