### ISSUE TITLE
HTML files always have javascript/css codeintel symbols

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#2738]
### Steps to Reproduce

Open a new file and set the language to HTML, open the symbol browser

### Expected results

Symbol browser is empty

### Actual results

Symbol browser shows javascript and css symbols

**Comment by mitchell-as** [comment]
I opened an HTML file, ensured HTML5 was the language, opened commando with the mouse, selected "symbols" (#7), but the result list is empty. Please advise how to reproduce.

**Comment by Naatan** [comment]
The "Symbol Browser" is the widget in the right pane. The thing in Commando is called the "Symbol Scope".

**Comment by mitchell-as** [comment]
https://github.com/Komodo/KomodoIDE/commit/bc64e3664c710b754ec42e35fe314ae15fa942a6

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoIDE/commit/123313f92a7a4f56fa74dd14045576fe0bd6adcd
