### ISSUE TITLE
No arguments sent to phpunit?

### ISSUE THREAD

**Issue by sfsccn** [Komodo/KomodoEdit#2740]
### Short Summary

When I create a phpunit test, the stdout contains only the phpunit "usage" information. That is, only what phpunit shows with no arguments:

PHPUnit 6.2.3 by Sebastian Bergmann and contributors.

Usage: phpunit [options] UnitTest [UnitTest.php]
       phpunit [options] <directory>
...

I'm wondering if the arguments are missing when Komodo runs phpunit.

### Steps to Reproduce

* Create MyClass.php and MyClassTest.php files in /my/path
* Create a PHPUnit test
* Set the "Path" to /my/path
* Set the "Framework" to phpunit
* Leave "Advanced" options as default (teamcity, project, etc)
* Run the test

### Expected results

phpunit test results

### Actual results

No test results. Only phpunit "usage" output under the stdout tab.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.2.3
*Operating System (and version)?* Linux 3.10.0-514.26.2.el7.x86_64

### Additional Information

If I enter the command "phpunit --teamcity /my/dir" in the "Command Output" tab I see the same phpunit output as I would see on the command line. That is, it works normally. Here is an example of output:

PHPUnit 6.2.3 by Sebastian Bergmann and contributors.

##teamcity[testCount count='1' flowId='17303']

##teamcity[testSuiteStarted name='/var/www/html/php/php-unit/hands-on-testing/example-0010-simple-card-test' flowId='17303']

##teamcity[testSuiteStarted name='CardTest' locationHint='php_qn:///var/www/html/php/php-unit/hands-on-testing/example-0010-simple-card-test/CardTest.php::\CardTest' flowId='17303']

##teamcity[testStarted name='testGetNumber' locationHint='php_qn:///var/www/html/php/php-unit/hands-on-testing/example-0010-simple-card-test/CardTest.php::\CardTest::testGetNumber' flowId='17303']

##teamcity[testFinished name='testGetNumber' duration='0' flowId='17303']

##teamcity[testSuiteFinished name='CardTest' flowId='17303']

##teamcity[testSuiteFinished name='/var/www/html/php/php-unit/hands-on-testing/example-0010-simple-card-test' flowId='17303']

Time: 48 ms, Memory: 8.00MB

OK (1 test, 1 assertion)

**Comment by Naatan** [comment]
This is by design, you need to have a phpunit.xml file in the directory that you run the tests in. If you want to pass arguments you can change the "Framework" to "Custom" and modify the command as needed.

**Comment by sfsccn** [comment]
Yay! Worked. phpunit.xml:

```
<phpunit>
  <testsuites>
    <testsuite name="mytest">
      <directory>tests</directory>
    </testsuite>
  </testsuites>
</phpunit>
```

Thanks!
