### ISSUE TITLE
SCC: cmd_SCC_openWebService_file isn't working

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2751]
### Short Summary

There's nothing in the logs unfortunately.

### Steps to Reproduce

- with a file under git control open
- ctrl+shift+g or `cmd_SCC_openWebService_file` in commando

### Expected results

THe file to open in it's repo in the browser

### Actual results

Nothing

**Comment by Naatan** [comment]
I get this on occasion but have not found a way to reproduce it consistently. It exists in 10 too.

**Comment by cgchoffman** [comment]
K, it's 100% broken for me though.  Is it working for you? @Naatan

**Comment by Naatan** [comment]
It's about 50/50 at the moment for me.

**Comment by Naatan** [comment]
Still reproducible in latest build?

**Comment by cgchoffman** [comment]
yes

**Comment by cgchoffman** [comment]
baaaaahahaha. I guess I'm too used to my own keybindings.  There is no key binding for this command.  The command is working fine.
