### ISSUE TITLE
UTF8 Tools break Toolbox

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#2754]
Create tool with following content (in Komodo 10):

```
{
  "keyboard_shortcut": "", 
  "name": "Test Replace UTF8", 
  "language": "JavaScript", 
  "trigger_enabled": false, 
  "value": [
    "var the_sel = komodo.editor.selText;", 
    "the_sel = the_sel.replace(/CAMI\u00d3N/mg, \"Vehicle\");", 
    "komodo.editor.replaceSel(the_sel);"
  ], 
  "version": "1.1.5", 
  "rank": 100, 
  "async": false, 
  "type": "macro", 
  "trigger": "trigger_postopen"
}
```

Import the tool into the Komodo 11 tools folder (via filesystem, while Komodo isnt running).

Then start komodo 11 and notice the toolbox doesnt load, errors in log.

**Comment by cgchoffman** [comment]
Ok so I was using my own example this whole time and just tried this example and nothing bad happens when I use it but my example still fails.  @naata, can you still reproduce this?  I think i have to open a new bug

**Comment by Defman21** [comment]
You've pinged the wrong user, fool! (that's a joke, you're not a fool!)
![img](https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fstatic.giantbomb.com%2Fuploads%2Fsquare_small%2F0%2F1927%2F201563-gtasa_bigsmoke.jpg&f=1)

**Comment by cgchoffman** [comment]
Apparently I'm lying about this not breaking too.  Nevermind.  The repro steps **are** valid.
