### ISSUE TITLE
Create Template Toolbox files for major languages.

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2759]
### Short Summary

Create templates to be used when when you do *File > New >File From Template*

Python2/3, ruby, Perl, Tcl, JS, Node, etc.

Should include shebang for file type detection.

Note there is already one for PHP.

**Comment by Naatan** [comment]
> Should include shebang for file type detection

Not necessary for Komodo, that's part of the template mechanic. I wouldn't add a shebang for languages that don't generally use those.

**Comment by cgchoffman** [comment]
> Not necessary for Komodo, that's part of the template mechanic.

I don't understand what you mean?  What is part of the template mechanic?

> I wouldn't add a shebang for languages that don't generally use those.

What language listed doesn't support shebangs?  All of them do as far as i know.  That's why they were in the original templates.

**Comment by Naatan** [comment]
> I don't understand what you mean? What is part of the template mechanic?

The language selection is part of the template tool, it doesnt need a shebang to identify the language.

> What language listed doesn't support shebangs?

I'm not talking about whether it supports it, I'm talking about whether it's conventional for a language to use shebangs in its files. For example someone who creates a JavaScript file will veeery rarely want to use shebangs as it's just not conventional for javascript files.

We want these templates to be of value for the majority of developers, not for a select minority.

**Comment by cgchoffman** [comment]
> The language selection is part of the template tool, it doesnt need a shebang to identify the language.

ok but it should still have a shebang if it makes sense.  I agree JS wouldn't need one but JS files aren't run from the commandline.  All the others, including NodeJS should have them.

**Comment by Defman21** [comment]
Well, shellbangs in Python and Ruby files are quite popular.

**Comment by Naatan** [comment]
NodeJS shouldn't have them. When you put a shebang in a file you are saying "this file is directly runnable from the client". Frankly i don't believe it belongs in a template unless that template is specifically a shebang template.

**Comment by cgchoffman** [comment]
Alright, if you want to get rid of them that's your call.

**Comment by Naatan** [comment]
I do. These templates are meant to be defaults, if people want more specific templates they have the ability to create them.

**Comment by Naatan** [comment]
PHP and Python (2) are missing.

**Comment by cgchoffman** [comment]
PHP is already there from before.  Good catch on Python.  I swear I made it.  Not sure where it went.

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/9b7c6ae1f7c697be6e94cc8d9b941f0d4407f354
