### ISSUE TITLE
Print Debugging tools aren't imported to upgraded profiles

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#2760]

**Comment by Naatan** [comment]
There is a folder called "Print Debugging" inside the samples/tools folder, it should be imported when you upgrade to Komodo 11.

**Comment by cgchoffman** [comment]
Cool, pretty sure this got fixed by the same thing that fixed the missing File Templates and Folder templates.   It's working for me now in the latest nightly.  Can't you check if it's working for you @Naatan ?

**Comment by Naatan** [comment]
This wasn't broken, it's just not implemented. So this isn't fixed by anything else.

**Comment by cgchoffman** [comment]
> it's just not implemented.

This would have been good information to include in the report.  I'll do this now then so QA isn't prevented from testing this.

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/df5ca43861776832e22a554b98856ed808d6afd5

**Comment by cgchoffman** [comment]
@Naatan is this needed for Edit?

**Comment by Naatan** [comment]
Nope, all good.

**Comment by mjainQA** [comment]
Verified in Komodo IDE, version 11.0.0-alpha1, build 90514, platform macosx.
Built on Sun Aug 20 23:39:49 2017
