### ISSUE TITLE
guessIndentation called when scintilla isnt ready

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#2763]
Certain getStyleAt calls in guessIndentation are returning 0 even when they are not 0 (eg. comments), my guess is Scintilla is still "rendering" at the time that guessIndentation is called.

I've created a workaround in https://github.com/Komodo/KomodoIDE/commit/b25ec2fd75fb9010e356ab85e7f092e263f69d6d, but workarounds suck. Please find a proper fix and revert above commit.

Commit for edit: https://github.com/Komodo/KomodoEdit/commit/9dfe99f01d3737bc58a923cc89610049236e5eac

**Comment by mitchell-as** [comment]
@Naatan I reverted that fix locally and opened peFolder.p.js and sdk/dialogs.js and I don't see any indentation detection problems. What am I doing wrong?

**Comment by Naatan** [comment]
It seems to mainly happen when Komodo restores files on startup. Try opening some big Python files, those seemed to be the main ones suffering from this issue.
