### ISSUE TITLE
Remove .cix files from build

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#2764]
They should not be in the build, only in the source.

**Comment by cgchoffman** [comment]
Make sure to update the *feature-core.ini* file.

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/d9ae4a747ed729defec5792b143ea840d5506732

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/05c91dc949626e6a60aa72685bf1b10e29b75d13
