### ISSUE TITLE
Code Intel fails to complete scan of Komodo project

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2766]
### Short Summary

I keep getting asked to scan my project.  Finally looking at the logs and notifications output it appears to stop at the same stop every time.  it seems to stop at 42% every time i perform the test.

![capture](https://user-images.githubusercontent.com/655154/28989969-d9629a12-792d-11e7-87ae-27b22ed4bdee.PNG)

codeintel logs (truncated so only output from the repro session):
[codeintel3.txt](https://github.com/Komodo/KomodoEdit/files/1201862/codeintel3.txt)

Komodo logs:
[pystderr.txt](https://github.com/Komodo/KomodoEdit/files/1201864/pystderr.txt)

### Steps to Reproduce
You can delete your code intel database in your profile folder to perform these repro steps
- Start Komodo
- Open the Komodoide project
- Komodo ask you to scan your project for codeintel
- let scan complete
- Close project 
- Reopen project

### Expected results

- Komodo not to ask you to scan project again

### Actual results

- Komodo asks you to scan again.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 11
*Operating System (and version)?*  Windows

**Comment by Naatan** [comment]
Share your Komodo project file please. I'm not seeing this on linux. Either you have different excludes, paths or it's a platform specific issue.

**Comment by cgchoffman** [comment]
[KomodoIDE.komodoproject.txt](https://github.com/Komodo/KomodoEdit/files/1201886/KomodoIDE.komodoproject.txt)

**Comment by Naatan** [comment]
Please try this again with build 90359. It will likely still stop at 42% but codeintel will recover and dump where the code was hanging to your codeintel3.log file, so check the log file and share the backtrace please.

**Comment by cgchoffman** [comment]
build 90377:
[codeintel3.txt](https://github.com/Komodo/KomodoEdit/files/1212350/codeintel3.txt)

**Comment by cgchoffman** [comment]
build 90377, codeintel `tail -f`:
[codeintel-tail.txt](https://github.com/Komodo/KomodoEdit/files/1212382/codeintel-tail.txt)
