### ISSUE TITLE
Appearance settings in Preferences not working properly

### ISSUE THREAD

**Issue by ffurger** [Komodo/KomodoEdit#2771]
### Short Summary

I am trying to configure Komodo 10 appearance by changing the font size in the Font section. However, Komodo 10 doesn't seem to recognise sizes in pixels. For example, it displays Avenir 1.1 rem, but it ignores Avenir 16px or any other px size for that matter. 

### Steps to Reproduce

Just try yourself. Select a font such as Avenir and try to set its size by selecting a px size. See my screenshot for an illustration.
<img width="1648" alt="screen shot 2017-08-04 at 16 03 08" src="https://user-images.githubusercontent.com/30805047/29063489-58b79de4-7c26-11e7-9397-5849f33001bb.png">

### Platform Information

*Komodo IDE
*Komodo Version 10
* MacOS 10.12.6

**Comment by Defman21** [comment]
https://github.com/Komodo/KomodoEdit/issues/2484 :)
