### ISSUE TITLE
Not always getting a primary completion in completions list

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2777]
### Short Summary

I was trying to get completions from `ko.logger` object in Python.  I typed `log.i` and Komodo will not show me `info` as the primary completions, it only shows "secondary completions"

Here's an image to explaining what I mean by primary and secondary completions:
![screenshot 2017-08-09 11 46 28](https://user-images.githubusercontent.com/655154/29138709-69044a98-7cf9-11e7-9b08-9e857d1eda3a.png)

And this is the issue I'm having (I don't initially get a primary completion for `info`:
![flicker](https://user-images.githubusercontent.com/655154/29138768-819cb78e-7cf9-11e7-8bb1-38ad92696494.GIF)

### Steps to Reproduce

- open a python file in the Komodo project
- enter the following code:
```
log = logging.getLogger("koToolbox2Components")
log| #cursor is at the end of `log`
```
 - type `.` to get completions for the `log` object
- Then type `i` so you get `info` in the list of suggestions

### Expected results

It should be a primary completion and selected

### Actual results

It is not and it is not select so when you hit enter you put in a new line rather than `info`.

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/26de935efbb7fa409ce021c90223412cab271948
