### ISSUE TITLE
Can't select secondary completions

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2778]
### Short Summary

I can't complete a secondary completion even if it's selected

### Steps to Reproduce

![secondary-completions](https://user-images.githubusercontent.com/655154/29139248-17682bf8-7cfb-11e7-88d6-75a2ef094529.GIF)

### Expected results

The selected completion to be entered into the code

### Actual results

It is not

**Comment by Naatan** [comment]
Can't reproduce. I assume you pressed enter to select the item?

Share your error log after reproducing please.

**Comment by cgchoffman** [comment]
Hmm, can't repro any more either. Closing.
