### ISSUE TITLE
Perl lvalue subs break in the Komodo IDE debugger

### ISSUE THREAD

**Issue by wchristian** [Komodo/KomodoEdit#2782]
The following Perl code:

    sub xar :lvalue { $moo }
    print( xar = 10 );

prints `10` when ran in the shell.

In the Komodo IDE debugger it dies with this error:

    Can't modify non-lvalue subroutine call at D:\cpan\Struct-Dumb-0.09\t\01point.t line 2.

This makes it impossible to debug code that uses @leonerd's IO::Async, as it uses Struct::Dumb, and plenty of other types of code that want to use l-value subs.

**Comment by Naatan** [comment]
@andygrundman @mitchell-as any insights?

**Comment by wchristian** [comment]
Anything?

**Comment by Naatan** [comment]
Opened a new ticket that covers this one - #2866
