### ISSUE TITLE
Syntax Checking messages are showing up in Notifications pane

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2783]
### Short Summary

I'm getting Syntax Checking updates in my Notifications pane

### Steps to Reproduce

- open a python file 
- type `import |`
- should cause a syntax error
- open notifications pane (*View menu > Tabs & Sidebars > Notifications*)

### Expected results

Nothing, or at least not a notificaitons about a syntax error

### Actual results

![capture](https://user-images.githubusercontent.com/655154/29184712-f5b89936-7dbb-11e7-9cb9-0ac7612b052d.PNG)

**Comment by Naatan** [comment]
Not new in 11 (haven't touched linting).

**Comment by cgchoffman** [comment]
But this wasn't in 10, so something changed in 11.  Shouldn't it be in 11?

**Comment by Naatan** [comment]
Are you sure it wasn't in 10? That's strange.

I'm not able to reproduce this myself. Can you repro on a clean profile?

**Comment by cgchoffman** [comment]
@Naatan it appears to be only Python files oddly enough.  I tried it in a JS file and it's not happening.  It does happen with a clean Profile.
