### ISSUE TITLE
code intel: can't get `import |` completions

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2784]
### Short Summary

I"m not getting completions after `import` in Python files.

### Steps to Reproduce

- open python file
- type `import |cursor stops here`

### Expected results

Should get completions for available modules

### Actual results

nothing happens

### Platform Information

*Komodo Edit or IDE?*  IDE 90396
*Operating System (and version)?* Windows

**Comment by Naatan** [comment]
This works for me, share your pystderr.log and codeintel3.log please.

**Comment by cgchoffman** [comment]
[codeintel3.txt](https://github.com/Komodo/KomodoEdit/files/1215982/codeintel3.txt)

**Comment by cgchoffman** [comment]
[pystderr.txt](https://github.com/Komodo/KomodoEdit/files/1215987/pystderr.txt)


There you go!

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/issues/121

**Comment by Naatan** [comment]
Don't see anything relevant. You don't even see `os` as a completion? Can you try to reproduce it on some different files?

**Comment by Naatan** [comment]
Also restart Komodo and try again, might be that your codeintel got corrupted, which is a bug I'm still trying to find repro steps for.

**Comment by cgchoffman** [comment]
#2951 is the actual issue.
