### ISSUE TITLE
Completions trigger twice

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#2788]
### Short Summary

title.

### Steps to Reproduce

1. Type `require 'json`
2. Type `'`

### Expected results

`require 'json'`

### Actual results

`require 'json'json`

![codeintel-bug](https://user-images.githubusercontent.com/7100645/29187147-64c01eca-7e17-11e7-9292-74f9e09343c9.gif)

**Comment by mitchell-as** [comment]
https://github.com/Komodo/codeintel/commit/e4f8857123c5db784a59581d2225a23949b0bb1e
