### ISSUE TITLE
Implement "highlight words"

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#2798]
CodeIntel v3 has lost the "highlight variables" feature, as an interim solution we will add a "highlight words" feature which only uses scintilla.

**Comment by mitchell-as** [comment]
https://github.com/Komodo/KomodoIDE/commit/4533cb2fb07da5a902ec2cf1163b968c9fd08210

**Comment by Defman21** [comment]
Is that in the QA build?

**Comment by Naatan** [comment]
Yes

**Comment by Defman21** [comment]
I guess it's enabled by default then?
