### ISSUE TITLE
Print statement toggle does not work

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#2801]
### Short Summary

I have a Python file with the following content:

```
print(123)
```

### Steps to Reproduce

1. Hold Ctrl and click on the margin.

### Expected results

The print statement switches to something else?

### Actual results

Nothing happens.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 11
*Operating System (and version)?* Windows 10

**Comment by Naatan** [comment]
This is due to Komodo/KomodoEdit#2760
