### ISSUE TITLE
Komodo does not detect print statements in the code

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#2802]
### Short Summary

I'm editing a ruby file with the following content:

```
print 123
```

### Expected results

See an icon of the print statement on the margin.

### Actual results

Nothing.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 11
*Operating System (and version)?* Windows 10

### Additional Information

The first print statement is written by me, the second one was added by ctrl+click on the margin.
 
![image](https://user-images.githubusercontent.com/7100645/29194521-a596e15c-7e32-11e7-9544-af9a10a61211.png)

**Comment by Naatan** [comment]
This is by design, the user can specify what his print statement should look like. I'm assuming you manually imported the print statement folder into your toolbox? Look at the tools it added, edit them as needed.

**Comment by Defman21** [comment]
Huh, I see how it works now. Anyway, I found a new bug.
