### ISSUE TITLE
Project wizard framework list has incorrect placeholder text

### ISSUE THREAD

**Issue by mook-as** [Komodo/KomodoEdit#2803]
### Short Summary
The project wizard's placeholder text is backwards.

### Steps to Reproduce
(From the menu:) Project → New Project…
Switch around the _Language_ dropdown (under the _Technology_ section), and observe the placeholder text in the _Framework_ listbox.

### Expected results
| Language Selected | Placeholder Text |
| --- | --- |
| None | Select a Language first |
| Bash | Selected Language has no known Frameworks |

### Actual results
| Language Selected | Placeholder Text |
| --- | --- |
| None | Selected Language has no known Frameworks |
| Bash | Select a Language first |

### Platform Information
Komodo IDE, version 11.0.0-alpha1, build 90396, platform linux-x86_64.
Built on Thu Aug 10 00:23:22 2017.

**Comment by Naatan** [comment]
Good eye!

**Comment by Naatan** [comment]
Fixed in latest build
