### ISSUE TITLE
Komodo uses the wrong Print Debugging snippet when switching a language for the buffer

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#2804]
### Short Summary

I have a clean profile, so the print debugging snippet for Ruby is:

```ruby
puts "[[%t]]"
```

### Steps to Reproduce

Create a Text file, change the language to Python, write this:

```
print("123")
```

This line gets recognized by Komodo as a print statement, which is true.

Then change the language to Ruby (I've miss-clicked the language first, so I changed it) and add this line:

```
puts "123"
```

### Expected results

```
print("123")
[x] puts "123"
```

`[x]` means the debugging statement icon on the margin.

### Actual results

```
[x] print("123")
puts "123"
```

I were confused by that until I re-opened the file.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 11
*Operating System (and version)?* Windows 10

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/614f3ef05b44a6b5c70a0a8bfbe46b075b4399d0
