### ISSUE TITLE
Can't get completions after `import` statement

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2806]
### Short Summary

I'm not able to get ANY completions on any line after an `import` statement in Python until

### Steps to Reproduce

tester note: `<|>` indicates the position of the cursor
- open a new Python file
- type enter an `import` statement, eg. `import sys`
- go to the next line
- try to get completions for `import`  by typing `i<|>`

### Expected results

completions that include `import`

### Actual results

nothing

### Additional information

You can declare more variables above the import statement and you will NOT get compleltions for them as well.

If you add a declaration statement below the `import` statement then move your cursor below it you **will**  get completions now.

eg.

```
import sys
blah = ""
i<|> # you will no get completions for `import`
```
A gif to show the issue 
![completions](https://user-images.githubusercontent.com/655154/29225745-54940710-7e84-11e7-8b7e-fc2ddd3dfcde.GIF)

**Comment by cgchoffman** [comment]
Code intel logs: 
[codeintel3.txt](https://github.com/Komodo/KomodoEdit/files/1218688/codeintel3.txt)
Pysterr.log: 
[pystderr.txt](https://github.com/Komodo/KomodoEdit/files/1218689/pystderr.txt)

**Comment by Naatan** [comment]
Fwiw I verified this isnt a client side issue.

**Comment by mitchell-as** [comment]
https://github.com/Komodo/codeintel/commit/77617512b2fc735f61cfa9aba26a29e97f587896
