### ISSUE TITLE
Current doc code intel scan offer screen is scanning recursively into child dirs, it shouldn't

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2808]
### Short Summary

When i open a random temp file in my *TEMP* dir Komodo will ask if I want to scan for code intel.  But it asks to scan every folder in my *TEMP* dir which currently is hundreds of thousands of files (should probably clean up in there).

Should it even be offering?  Maybe it wouldn't if it wasn't scanning recursively?

### Steps to Reproduce

- Open a file not associated with your project and start writing some code

### Expected results

- Nothing* unless there are thousands of files in my current folder that are relevant to the current file type.

### Actual results

- Komodo offers to scan every directory in that folder that holds my temp file.

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/3549582c2cf93e485d7ad48fa1dad82128104dcd
