### ISSUE TITLE
New Project opens a window at a different location first

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2809]
### Short Summary

While creating a new project, a window flashes on the top left corner of the screen before opening an actual window. See the screen capture

### Steps to Reproduce
1. Click on 'New Project'
2. Notice the above behavior

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* macOS
Komodo IDE, version 11.0.0-alpha1, build 90414, platform macosx.
Built on Thu Aug 10 23:39:13 2017.

**Comment by mjainQA** [comment]
![project_new](https://user-images.githubusercontent.com/26605593/29227355-648138a4-7e8a-11e7-8256-e5f2fb21b56f.gif)

![image](https://user-images.githubusercontent.com/26605593/29227359-68a7970c-7e8a-11e7-8f5a-d0785e405ae0.png)

**Comment by mjainQA** [comment]
Similar issue while opening preferences from the same start up screen.

**Comment by Naatan** [comment]
This is an unfortunate limitation due to our Mozilla dependency. Its borderless window mode is a bit janky and our implementation has a lot of workarounds. One is that we can't move the window to the intended position until it has loaded. Sadly nothing I can do about this.
