### ISSUE TITLE
No explanation message in StartWiz > Component scanner when scanning

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2812]
### Short Summary

The msg that explains what the component scanner is doing isn't there when a scan is happening.
The msg should be more straight forward.  I was trying to be playful when I wrote it but it just makes it long and I don't want to read it.  Should be very short, we're trying to get started, not read.

### Steps to Reproduce

- Help > RUn First start...
- Go to Component Scanning screen

### Expected results

 Scanning indicator to be present AND have message explaining what this screen is doing:
- Looking for installed languages and tools
- Setting default prefs 
- Allowing user to immediate configure tools/langs if default isn't sufficient

### Actual results

I only see the Scanning stuff.  No msg explaining screen.  It doesn't appear until the scan completes.

**Comment by cgchoffman** [comment]
Assigning to 11 but if need be this can slip if there are other things more important.

**Comment by Naatan** [comment]
Should probably be really short and concise. Something like "Detecting optional dependencies".

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/92bb102268886abe96aeb8ee817f9d22077f69cf
