### ISSUE TITLE
Notify on how to run component scanning again using 'Get Started' wizard

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2813]
### Short Summary

Currently there is no way for user to know how to run component scanning again using Get Started wizard. Once a user skips the scanning, the 'Get started' wizard gets closed. It would be nice to have such info displayed on the component scanning wizard. 

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 11
*Operating System (and version)?* macOS

### Additional Information
![image](https://user-images.githubusercontent.com/26605593/29229890-794e1cd8-7e95-11e7-834f-d6051cf9bbd3.png)

**Comment by Naatan** [comment]
Lets add this information to the last screen of the "Getting Started Wizard":

"You can run this Wizard again at any time via Help > Run First Start Wizard Again"

**Comment by cgchoffman** [comment]
This was done.
