### ISSUE TITLE
Display better descriptive information while scanning components in 'Get Started' wizard

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2814]
### Short Summary
While scanning components, a user might not know what is being scanned and why! A descriptive information such as setting Language and Tools preferences would be more helpful for the user.

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 11
*Operating System (and version)?* 

### Additional Information
![image](https://user-images.githubusercontent.com/26605593/29230782-4d17883a-7e99-11e7-8534-0c42596dbda6.png)

**Comment by Naatan** [comment]
How about "Detecting Optional Dependencies"?

**Comment by mitchell-as** [comment]
Duplicate of #2812
