### ISSUE TITLE
Unclear what happens if component scanning is skipped in 'Get Started' wizard

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2815]
### Short Summary

It is unclear for the users what will happen if component scanning is skipped. Would it break Komodo? For e.g. would certain functionality be not available in Komodo if scanning is skipped? It would be nice to display an informative message about why it is being scanned and what will happen if skipped?

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 

### Additional Information

 
![image](https://user-images.githubusercontent.com/26605593/29231419-f07df516-7e9b-11e7-949f-5c3b5ada900a.png)

**Comment by Defman21** [comment]
This button was disabled for me while scanning iirc.

**Comment by Naatan** [comment]
@cgchoffman lets disable the "Next" button until the scan is completed. Technically it won't make any difference of course, but this will avoid confusion.

**Comment by cgchoffman** [comment]
> This button was disabled for me while scanning iirc.

@Defman21 it is not.  I skip it all the time.

@Naatan ok.

**Comment by Defman21** [comment]
>@Defman21 it is not. I skip it all the time.

Yeah I see. Keeping a lot of Komodo issues in the head makes me doing mistakes sometimes you know ;)

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/bc7c9c6b138e250287dd119dd2acfa76af10895a
