### ISSUE TITLE
About Komodo does not display build and license info

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2818]
### Short Summary

Sometimes 'About Komodo' does not display build and license info

### Steps to Reproduce

1. Go to Komodo -> About Komodo
2. Once About Komodo window is open, Go to Komodo -> About Komodo

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 11
*Operating System (and version)?* macOS

### Additional Information

 Go to Komodo -> About Komodo
![image](https://user-images.githubusercontent.com/26605593/29231776-4b5e4246-7e9d-11e7-8232-d05539a3265c.png)

**Comment by cgchoffman** [comment]
Logs?  It's working fine for me.

**Comment by mjainQA** [comment]
[pystderr.txt](https://github.com/Komodo/KomodoEdit/files/1219179/pystderr.txt)

**Comment by Naatan** [comment]
```
[2017-08-11 14:51:33,210] [ERROR] console-logger: ReferenceError: ko is not defined (2) in chrome://komodo/content/about/about.js:6
Traceback (most recent call last):
  File "chrome://komodo/content/about/about.js", line 6, in 
```

**Comment by Defman21** [comment]
`var ko = require("ko/windows").getMain().ko` 😄

**Comment by Naatan** [comment]
Gee wiz thanks @Defman21, I was wrecking my brain.

**Comment by cgchoffman** [comment]
I can't reproduce this issue.  Please try to reproduce in safe-mode.

**Comment by mjainQA** [comment]
reproducible on Windows 10 and macOS RC1:

Komodo IDE, version 11.0.0, build 90651, platform macosx.
Built on Fri Sep 1 16:41:44 2017.

**Comment by mjainQA** [comment]
Reproducible in safe-mode.

**Comment by cgchoffman** [comment]
can you attached your logs again please

**Comment by cgchoffman** [comment]
I don't really know what to say.  I can't reproduce on either of those platforms.  Can anyone else reproduce this issue?  I'm reluctant to fix an issue that I can't see.

**Comment by Defman21** [comment]
I'll try.

**Comment by Naatan** [comment]
> I'm reluctant to fix an issue that I can't see.

I'd be impressed if you could fix an issue you can't see :p

**Comment by Defman21** [comment]
Can't reproduce on Windows 10, build 90651.

**Comment by mjainQA** [comment]
[pystderr_2017-09-05_15:45_Komodo IDE 11.0.0 (Build 90651).txt](https://github.com/Komodo/KomodoEdit/files/1279185/pystderr_2017-09-05_15.45_Komodo.IDE.11.0.0.Build.90651.txt)

**Comment by cgchoffman** [comment]
@mjainQA, can you restart in safe mode, repro then send your logs?  There is something very wrong with that install that you sent your logs from.

**Comment by mjainQA** [comment]
Logs from safe mode:
[pystderr.txt](https://github.com/Komodo/KomodoEdit/files/1279251/pystderr.txt)

**Comment by Naatan** [comment]
```
[2017-09-05 16:22:37,934] [ERROR] console-logger: ReferenceError: require is not defined (2) in chrome://komodo/content/about/about.js:6
Traceback (most recent call last):
  File "chrome://komodo/content/about/about.js", line 6, in 

[2017-09-05 16:22:38,015] [ERROR] console-logger: TypeError: infoSvc is undefined (2) in chrome://komodo/content/about/about.js:24
Traceback (most recent call last):
  File "chrome://komodo/content/about/about.js", line 24, in 
```

I guess require not being defined is causing the infoSvc to not get defined. Not sure why require isnt being defined though. @mjainQA is this consistently reproducible ?

**Comment by mjainQA** [comment]
Yes, it is 100% reproducible even with RC2.

**Comment by cgchoffman** [comment]
I guess the question is do we dig into why it's only broken for @mjainQA (on Windows and OSX) or do we punt and see if we can get more data (more people hitting it) as to why/how it's happening?

**Comment by cgchoffman** [comment]
I still can't reproduce this.  @mjainQA, are you able to?

**Comment by mjainQA** [comment]
Yes 100% reproducible with 11.0.1 nightly.

**Comment by mjainQA** [comment]
Unable to reproduce it in Komodo IDE, version 11.0.1, build 90775, platform macosx.
Built on Wed Oct 11 23:49:43 2017.

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/66a4442af277708a50ae305af8ade0da577a39ba
