### ISSUE TITLE
Python detected but still marked invalid

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#2820]
This is from @mjainQA's machine, so check with her for details. Note how Python 3 is detected (path in dropdown) but it is still marked invalid:

![image.png](https://zube.io/files/komodo/d471266be1410445137b3cca92ed41cf.png)

**Comment by cgchoffman** [comment]
@Naatan, i was working with @mjainQA the other day and she had Python 2 configured for Python 3.  I'm pretty sure that's why it's marked as invalid.  This is by design.

**Comment by cgchoffman** [comment]
That's why is has the "download" button showing.

**Comment by cgchoffman** [comment]
I was wrong.  This was a separate issue from detecting if it's a valid Python version.  My fix for #2862 will resolve this.
