### ISSUE TITLE
Live Preview: 'Web browser' option under Preview is misleading

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2822]
### Short Summary
'Web browser' should be called something else because
1) There is a browser preview option already under Top menu View which opens file in a browser
2) Web browser does not relate to opening/previewing a file in the editor. 

### Steps to Reproduce

1. Open any HTML file
2. Click on the dropdown arrow in the preview button

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 11
*Operating System (and version)?* macOs

### Additional Information
![image](https://user-images.githubusercontent.com/26605593/29233673-37b85088-7ea7-11e7-9dbe-6fc043a4ac39.png)

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/538b5eb8692f9fa7d2b3b4ca400bfaa8bf345756
