### ISSUE TITLE
Alert box has 'OK' option cut off

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2824]
### Short Summary

Komodo alert box has its 'Ok' text cut off. 

### Steps to Reproduce
1. Save the attached file exp.txt as .html
2. Click on Preview button
3. Click on hyperlink in the file

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 11
*Operating System (and version)?* macOS

### Additional Information
![image](https://user-images.githubusercontent.com/26605593/29234038-3f791602-7ea9-11e7-984f-5732d89eb198.png)
[exp.txt](https://github.com/Komodo/KomodoEdit/files/1219219/exp.txt)

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoEdit/commit/9211ed62bfea667f5773fdd9dfe9326cf37de2af
