### ISSUE TITLE
Automatically add gem's source code dir to CodeIntel include dirs

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#2827]
### Short Summary

Adding my gems dir is a bit too heavy for CodeIntel, it scans it forever. However, limiting the amount of CodeIntel additional include dirs to the gems I'm using in my current opened project could help a lot.
 I'll do a bit of a research myself and write the code that will print all the dirs needed to be included according to either Gemfile or gemspec of the opened project. I guess it won't be that hard to integrate this code into the codenitel code :)

**Comment by Naatan** [comment]
Please feel free to open a PR if you figure something out. I don't consider this actionable for us. Note that codeintel is pure Python, so anything you write would have to be Python.

**Comment by Defman21** [comment]
I'm not sure how could I open a PR for this task. I don't have access to the codeintel code, I can only create an abstraction code in Python that will return a list of gem's dirs for current project/folder.

**Comment by Naatan** [comment]
Sure, maybe instead share it on the forum then.

**Comment by Defman21** [comment]
Okay :)
