### ISSUE TITLE
Cannot go to definition on catalog symbols

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#2834]
```
import os
os.path.join()
```

Put caret on path and invoke goto definition.

Gives prompt: "The file '/:python:' does not exist"

**Comment by mitchell-as** [comment]
https://github.com/Komodo/codeintel/commit/005a7a88c2deb6a32d706b59fcf8f3156979b3a4

**Comment by mitchell-as** [comment]
Based on slack conversation, the correct thing to do is check of the file to go to is in ":xxx:" format, which indicates a stdlib symbol. If in that format, do not attempt to open that non-existent file, but perhaps perform a more appropriate action.

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/88215aff1bfd0b6b6984fbf3351e67e9435d2514

**Comment by Naatan** [comment]
@mjainQA please provide details as to why you are reopening.

**Comment by mjainQA** [comment]
By mistake.
