### ISSUE TITLE
Tab-aware past does not replace selection

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#2835]
### Short Summary

title.

### Steps to Reproduce

1. Copy something to your clipboard.
2. Select something.
3. Fire the tab-aware insert command

### Expected results

The selection is replaced with the content of the clipboard.

### Actual results

The content of the clipboard appended to the selection.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 11

**Comment by mitchell-as** [comment]
Duplicate of #2714

**Comment by mjainQA** [comment]
Verified in Komodo IDE, version 11.0.0-alpha1, build 90514, platform macosx.
Built on Sun Aug 20 23:39:49 2017

Test case steps: see 2714
