### ISSUE TITLE
Unable to right click on a filename

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2836]
### Short Summary

Unable to right-click on a filename.

### Steps to Reproduce
1. Open any file in the editor
2. Right-click on the filename

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 

Komodo IDE, version 11.0.0-alpha1, build 90438, platform macosx.
Built on Mon Aug 14 09:36:30 2017.

### Additional Information
![image](https://user-images.githubusercontent.com/26605593/29290300-6df5c50a-80f4-11e7-9254-d14544047343.png)

**Comment by cgchoffman** [comment]
@mjainQA, can you confirm this wasn't in Komodo 10?  It looks like this is OSX only so it may have existed in 10 and no one noticed.

**Comment by mjainQA** [comment]
This is a new issue introduced in K11. I am unable to reproduce in 10.

**Comment by cgchoffman** [comment]
Thanks @mjainQA,  I retested on my Windows machine with the lastest build and am experiencing the issue as well.
