### ISSUE TITLE
(Select Symbol) Text is cut off

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2839]
### Short Summary

(Select Symbol) text is cut off despite window has enough room. This issue is sporadic.

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 

### Additional Information
![image](https://user-images.githubusercontent.com/26605593/29294511-907b1c14-8104-11e7-9a11-b56e4fe5a18e.png)
Komodo IDE, version 11.0.0-alpha1, build 90438, platform macosx.
Built on Mon Aug 14 09:36:30 2017.

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/3984d605ea5276247571cee7bd8d163b352d1ab9
