### ISSUE TITLE
File size a real problem in Komodo 9

### ISSUE THREAD

**Issue by PhilSDP** [Komodo/KomodoEdit#284]
I am now at the point where Komodo 9 can no longer open text files that Komodo 8 could.  Over the last few weeks I have been working a project that generates text files in the 90MB+ range and then use Komodo to analyze.  Originally I created a benchmark that is about 150MB, now I try and open it as well as its replacement (92MB) and Komodo says they are both too large.
Because these text files are core to logging internal processes, it is looking like I will have to start (once again) searching for an IDE that provides similar functionality to Komodo along with responsiveness.

**Comment by Naatan** [comment]
Komodo is unfortunately just not focussed on supporting huuuuge files. It's an editor meant for coding.

I don't personally understand why people want to use one editor exclusively for ALL of their text editing needs. I generally use VIM, Gedit and Komodo in a days work. Each have their use.

Anyway we have an issue open to improve large file compatibility: #134, but fair warning - it is not a huge priority given that it is no the focus of Komodo.

**Comment by cgchoffman** [comment]
If you're using Komodo to process logs you may want to look into a tool like Splunk or Papertrail which are designed for massive log processing.

**Comment by PhilSDP** [comment]
Thanks all.  I'll check out the suggested tools, in the meantime I used TextPad and Visual Studio.  

In general I don't "edit" these files, only view them and occasionally empty them.  One of the main features I use Komodo for with these files is the "Find all" combined with the split view.  The same is not true though for XML files.  A large part of the files I work with are XML and/or javascript.  The latter has not been an issue so far but since I'm not always the creator of the former they can be an issue.  Over the last few years I've been slowly educating my co-workers to split XML files into their functional components, but some are still not yet "split down".  Smaller is better and they are seeing the benefits at run time too.
