### ISSUE TITLE
Folder template is opening file picker instead of folders

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2840]
### Short Summary

While trying to unpack folder template, user is getting option to pick files instead of folders.

### Steps to Reproduce

1. Go to toolbox
2. Select Folder templates -> Python -> Django
3. Click on ... and notice you are unable to select a folder.

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo IDE, version 11.0.0-alpha1, build 90438, platform macosx.
Built on Mon Aug 14 09:36:30 2017.
### Additional Information
![image](https://user-images.githubusercontent.com/26605593/29295713-b577070c-810a-11e7-8a05-26676313344b.png)

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/8efb712794124bfb1345020dcb36d4aeed854c69
