### ISSUE TITLE
Komodo IDE 11 imports from previous Komodo Edit before IDE

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2843]
### Short Summary

Title

### Steps to Reproduce

- move your profile folder aside for a fresh install for all installs
- Install and run Komodo Edit 10 and create something in the toolbox so you know it's the edit toolbox
- Do the same for IDE 10
- Install and run Komodo 11

### Expected results

Komodo to import from Komodo IDE 10

### Actual results

Komodo imports from Komodo EDIT 10

**Comment by Naatan** [comment]
As discussed lets remove the import from edit. They're 2 different products, importing is frankly not the expected behaviour and can cause all sorts of issues.

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/95738b1a3697d1434e7bc49acf0bbbb459b8556f
