### ISSUE TITLE
Pref "Enable soft Charachters" is disabled in 11

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#2849]
### Short Summary
In Komodo X I have the pref "Enable soft Charachters" enabled.
In Komodo 11 the pref is disabled.

### Platform Information
Komodo IDE, version 11.0.0-alpha1, build 90443, platform win32-x86

**Comment by Naatan** [comment]
Are you certain you have no Komodo IDE or Komodo Edit profile folders lower than 11.0 that had this pref also disabled?

Komodo inherits from the highest number profile folder it can find that is under the current version number.

**Comment by babobski** [comment]
I recently had to install a new hard drive, so I only have the previous Ide installed.

![afbeelding](https://user-images.githubusercontent.com/3530262/29333405-f492556e-8203-11e7-84f3-e9e64833298d.png)

**Comment by Naatan** [comment]
Could you try moving 11.0 aside and running 11 again to see if you can repro?

**Comment by babobski** [comment]
Just removed everything related to 11 and installed the latest nightly, but the pref is disabled again.

**Comment by cgchoffman** [comment]
You're not enabling it in the First Start Wizard, correct?
![capture](https://user-images.githubusercontent.com/655154/29377510-e33e318a-8270-11e7-80ac-2c314ee84d5d.PNG)

**Comment by cgchoffman** [comment]
HUh...it does disable that pref but it's not that pref in the code...Not sure what's going on here.
