### ISSUE TITLE
css autocompletion

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#2850]
### Short Summary
The current css autcompletion is changed a bit.
A have a few issues concerning the css autcompletion.

**CSS - Class and Id autocompetion**
If you enter a the trigger character(#,.), after autocompletion you will and up with double of them.

**After inserting attribute, auto insert :_(space)**
In komodo X after inserting the css attribute, the : and the space are auto-inserted.
In komodo 11 this is missing.

**Inserting the attribute value.**
If you type for example a color attribute, and type # you will get a autocompletion for #. 
If you insert this you end up with a double #.
The autocompletion for !important is not working, typing ! is canceling the autocompletion.

**The autocompletion for the attributes is coming to soon.**
I'm used that if I type out `#testDiv {` and press enter, I will get the following result:
```CSS
#testDiv {
	|
}
```
Now I'm getting the following result:
```CSS
#testDiv {-moz-appearance|}
```
The autocompletion for the attributes is coming to soon, preventing me to open the css block.

### Platform Information
Komodo IDE, version 11.0.0-alpha1, build 90443, platform win32-x86

### Additional Information
Workaround: use <kbd>Esc</kbd> to cancel the autocompletion.

**Comment by Defman21** [comment]
>If you enter a the trigger character(#,.), after autocompletion you will and up with double of them

Could you elaborate on that? I don't follow...

>After inserting attribute, auto insert :_(space)

Reproduced.

>If you type for example a color attribute, and type # you will get a autocompletion for #.
If you insert this you end up with a double #.

Reproduced.

>The autocompletion for !important is not working, typing ! is canceling the autocompletion.

Reproduced.

>The autocompletion for the attributes is coming to soon, preventing me to open the css block.

Reproduced. Workaround: be faster 😛

**Comment by babobski** [comment]
@Defman21  
If you type out `.class` or `#id`, you will end up with `..class` or `##id`.

**Comment by Defman21** [comment]
How I can trigger them?

**Comment by babobski** [comment]
You need to already have classes or ids in your css file.
You will get auto completion for the previous used, when you type `.` or `#`.

**Comment by Defman21** [comment]
Wow, I didn't know that. Thanks for the info.

**Comment by Naatan** [comment]
Fixed on IDE repo, will be in tomorrows build.
