### ISSUE TITLE
Strange black border/space arround some dialogs

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#2851]
### Short Summary
Some dialogs are showing a strange black border:
![afbeelding](https://user-images.githubusercontent.com/3530262/29331515-fb216138-81fc-11e7-85e0-eadf2d9ff1e9.png)
Probably a Windows thing ;)

### Platform Information
Komodo IDE, version 11.0.0-alpha1, build 90443, platform win32-x86

**Comment by Defman21** [comment]
Nathan fixed that a while ago.

https://github.com/Komodo/KomodoEdit/issues/2436

I guess some bugs want to stay in Komodo  😃

**Comment by Naatan** [comment]
Are you getting this on 10 also?

**Comment by babobski** [comment]
Not that I noticed.
In 10 I don't have the same border:
![afbeelding](https://user-images.githubusercontent.com/3530262/29332489-7c9ab0b8-8200-11e7-99e5-1712b114f522.png)

**Comment by Naatan** [comment]
Ok, thanks for checking!
