### ISSUE TITLE
Auto-dedent is not working when inserting via an abbreviation

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#2852]
### Short Summary

title.

### Steps to Reproduce

```
<html>
  <head>
    123
    </h|
```

| is your cursor. Wait for autocompletions, select `head>`.

### Expected results

```
<html>
  <head>
    123
  </head>
```

### Actual results

```
<html>
  <head>
    123
    </head>
```

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 90443
*Operating System (and version)?* Arch Linux

### Additional Information

I'm able to reproduce it in Ruby as well with the `end` keyword. I guess any language that has dedent words suffers from this issue. Typing these words manually triggers the dedent code.

**Comment by mitchell-as** [comment]
@Naatan koLanguageCommandHandler.py:773 (`_finish_autocomplete()`)

**Comment by Naatan** [comment]
Thanks!

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/5a7d83cbc566a8f60f4fede099cfd5e7904bce24
