### ISSUE TITLE
Unable to disable 'print statements' in the editor by renaming toolbox

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2859]
### Short Summary

Renaming the Print debugging toolbox or individual print files (such as Python3 Print Statement) does not disable 'print statements' in the editor.

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo IDE, version 11.0.0-alpha1, build 90447, platform macosx.
Built on Tue Aug 15 12:35:44 2017.
### Additional Information
![image](https://user-images.githubusercontent.com/26605593/29338388-d51744ea-81c9-11e7-94cb-1f0fbbbbd1b9.png)

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/507804aecd1c467aee58a98b49c2406ddf51f192

**Comment by mjainQA** [comment]
Able to reproduce in Komodo IDE, version 11.0.0-alpha1, build 90514, platform macosx.
Built on Sun Aug 20 23:39:49 2017.

![image](https://user-images.githubusercontent.com/26605593/29540889-a15aca6c-8685-11e7-8e99-70b51db6db5a.png)

**Comment by Naatan** [comment]
Cannot reproduce. Working fine on my end. So you have the buffer open, you rename the snippet and the print debugging icons stay?

**Comment by mjainQA** [comment]
Thats correct!

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/614f3ef05b44a6b5c70a0a8bfbe46b075b4399d0
