### ISSUE TITLE
Komodo 11 install Detecting Components displays all entries twice

### ISSUE THREAD

**Issue by mjross** [Komodo/KomodoEdit#2860]
### Summary
When installing Komodo 11 (but not 10, if I recall correctly), the Detecting Components window has many entries, organized into four sections: Languages, Package Managers, Tools, and Version Control. But those four sections appear twice in the window. Please see the screenshots below. 

### Platform Information
Komodo IDE 11 build 90396 on Windows 10 Pro

### Attachments
![detecting components 1](https://user-images.githubusercontent.com/829492/29342677-687bcc50-81e9-11e7-92b2-ec84ed2bd904.jpg)

![detecting components 2](https://user-images.githubusercontent.com/829492/29342681-6f119068-81e9-11e7-8844-9175e96d79e8.jpg)

![detecting components 3](https://user-images.githubusercontent.com/829492/29342686-7733d4b8-81e9-11e7-987c-1f6cf41264da.jpg)

![detecting components 4](https://user-images.githubusercontent.com/829492/29342692-7b89eea8-81e9-11e7-9f41-f1fa520961a5.jpg)

![detecting components 5](https://user-images.githubusercontent.com/829492/29342708-7f1fdfdc-81e9-11e7-86e1-01c48e135b16.jpg)

![detecting components 6](https://user-images.githubusercontent.com/829492/29342710-82f4efda-81e9-11e7-9f5d-a8d6c82bf0a1.jpg)

**Comment by cgchoffman** [comment]
I'm not able to reproduce this.  Can you reproduce this?  If yes, please grab your logs and share (please restart though).  Then try to reproduce in safemode.

**Comment by cgchoffman** [comment]
I'd also be interested in your prefs.xml.  Could you send it to support@activestate.com referencing this ticket and asking for moi (Carey)?

**Comment by mjross** [comment]
Hola! Brief reply as I'm preparing to board a plane soon. I will try to
reproduce the bug with another install, but may get the same result as it
would duplicate the first install. I'm not sure how I could get the logs
etc you mention since don't they presume a working install, i.e. the
installation has been completed, and this potential bug is during the
install? (I will try to get back online with my laptop by Thursday evening,
but no guarantees, since the WiFi in Antigua may be poor.)

**Comment by cgchoffman** [comment]
That is not install, it's Komodo starting.  You can get the logs from your profile folder.  Same with the prefs.xml.

**Comment by mjross** [comment]
That's what I get for trying to think in an airport. :)  Okay. I'll dive
into this when I get settled in. Perhaps I should clean off K 10 and 11,
and do a fresh install of 11? I'm now wondering if having the two might be
a source of issues.

**Comment by cgchoffman** [comment]
Here's what you can do:

### Test upgrade

- Stop Komodo
- Copy your current profile (*...\AppData\Local\ActiveState\KomodoIDE\*) and name it something else
- in the non copied (original) profile remove your 11 folder
- Start Komodo
- See if they are doubled

### Fresh 10 - upgrade

- Same as above but remove the 11.0 and 10.3 folders
- Start Komodo 10 (create a new clean 10 profile)
- Start Komodo 11 (the upgrade)
- See if they are doubled.

### Fresh

- Stop Komodo
- open a terminal window
- `set KOMODO_USERDATADIR=C:\some\path\you\use\for\temp\stuff\`
- Start Komodo from that terminal
- See if they are doubled

Just make sure you keep that original profile.  I'm interested in your *prefs.xml* file.

**Comment by mjross** [comment]
So avoiding the deleting and reinstalling of all those files, and instead
using the profiles to get the same effect? Sounds good.

And when you write "Stop Komodo", you mean simply closing the program(s),
i.e., there isn't some hidden background process I need to worry about?
(I've noticed a trend of software increasingly using background processes
in conjunction with the user-facing programs.)

**Comment by cgchoffman** [comment]
> there isn't some hidden background process I need to worry about?

Nope, no backround process to kill.  Just turn off komodo.

**Comment by Naatan** [comment]
Just to be clear, we want to find out what the repro steps are, we're not looking for a workaround.

**Comment by mjross** [comment]
Absolutely.

**Comment by mjross** [comment]
First I upgraded to Komodo IDE 11 build 90491 (related to the issue described at https://github.com/Komodo/KomodoEdit/issues/2898). Then I followed the steps outlined in that first section above, titled “Test upgrade”. Consequently, the Detecting Components entries are not displayed twice, but only once. In other words, I'm no longer able to reproduce the problem. Sorry for the false alarm. It looked so peculiar, I just had to report it. :)

Any need for me to try those other steps outlined above? I suspect my time would be better spent trying out new features in version 11.

**Comment by Naatan** [comment]
Actually @cgchoffman has reproduced it internally, though now cannot reproduce it anymore either. There's definitely some sort of race condition.

**Comment by mjross** [comment]
*Good to hear that I'm not the only one experiencing that odd behavior. :-)*

**Comment by cgchoffman** [comment]
I finally got this.  We clicked "back" or "next" then returned to the Components screen which appends a new lists of components.

**Comment by mjross** [comment]
Good detective work!

I don't recall clicking "Next" and "Back", but that's probably what
happened.

**Comment by cgchoffman** [comment]
> I don't recall clicking "Next" and "Back"
haha me neither!

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/03de60ea6f3fb33ca87812acebb2964813e90570

**Comment by cgchoffman** [comment]
Decided to just not let the components reload since reloading would overwrite any chances the user made:
https://github.com/Komodo/KomodoIDE/commit/92bb102268886abe96aeb8ee817f9d22077f69cf#diff-ec0d788af4ad9b41997a80c3a24dab68R87
