### ISSUE TITLE
Servers are missing in Komodo 11

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#2867]
After install of Komodo 11, I don't have any servers configured anymore.
They are not imported from Komodo X.

## Platform Information
Komodo IDE, version 11.0.0-alpha1, build 90456, platform win32-x86

**Comment by cgchoffman** [comment]
Relevant perhaps: https://github.com/Komodo/KomodoEdit/issues/1524

**Comment by cgchoffman** [comment]
@babobski, i'm hitting some Mozilla sized speedbumps here.  Follow the original workaround steps from #1524.
- Stop Komodo
- Copy *XRE\key3.db* and *XRE\logins.json* to your new 11.0 profile.
- Start Komodo

Something gets initialize before we can get the files in place.  This may or may not be doable from our end :(

**Comment by babobski** [comment]
oke, noticed that my publishing configurations does get imported into 11.
 Only they will not run (you will get prompted for ftp credentials) because the server configurations are missing.

**Comment by cgchoffman** [comment]
Did you follow the workaround steps yet?  Publishing not working would be expected giving this bug.

**Comment by babobski** [comment]
No, I did not yet. only noticed the publishing does get imported.
Just wanted to leave a note.

**Comment by cgchoffman** [comment]
Ok, that's good.  It's expect.

**Comment by cgchoffman** [comment]
Thanks for the report @babobski.
