### ISSUE TITLE
'Use these settings on all files' is not working for 'Format On Save' feature

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2868]
### Short Summary

Formatter options are not saved when clicked on 'Use these settings on all files'

### Steps to Reproduce

1. Open any python file
2. Select 'Python reindent'
3. Click on 'Use these options for all the python files'
4. Open another python file
5. Notice 'Python reindent' is not selected

### Expected results

Python reindent formatter should be selected for all the python 3 files by default

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo IDE, version 11.0.0-alpha1, build 90447, platform macosx.
Built on Tue Aug 15 12:35:44 2017.
### Additional Information
![image](https://user-images.githubusercontent.com/26605593/29379801-79710ed2-8278-11e7-90a1-322fa3d0487e.png)

**Comment by Naatan** [comment]
I cannot reproduce this, does the file that's not showing the global setting have a "Use global formatting preference" menu item?

**Comment by mjainQA** [comment]
@Naatan I am unable to reproduce it either. I might have reset the preferences using 'global settings' option.

**Comment by Naatan** [comment]
Ok, please reopen if you can reproduce. I suspect the file you were viewing had its own setting, which override the global setting.
