### ISSUE TITLE
'Format on Save' options are confusing

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2869]
### Short Summary

Currently 'Format On Save' feature has following two options:
1) Use these settings for all files
2) Use global formatting preference. 

Option # 2 is not worded correctly as it indicates that there are options set/available in Komodo preferences. 

Suggestions: 

1) Merge option # 2 with Option # 1 so that user can set/reset global options for the chosen formatter across all the files using a single setting.

2) Disable/Enable option # 1 based on formatter selection or have a check box available for the user.

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo IDE, version 11.0.0-alpha1, build 90456, platform macosx.
Built on Tue Aug 15 23:38:36 2017.
### Additional Information
![image](https://user-images.githubusercontent.com/26605593/29381114-0a985a1a-827d-11e7-99e1-28eae8cbfebb.png)

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/12ccbe979a3260e5f944a6789d4ae4963f062e8b
