### ISSUE TITLE
Fail to detect pyflakes for Python3

### ISSUE THREAD

**Issue by hongquan** [Komodo/KomodoEdit#287]
Even I installed pyflakes for python3, Komodo still cannot detect it.

![selection_022](https://cloud.githubusercontent.com/assets/314607/7782527/7c83c99a-014f-11e5-8e43-fc7a1fccd9d9.png)

**Comment by Naatan** [comment]
Could you try ensuring that HOME, PYTHONPATH and PYTHONHOME are (properly) configured in Prefs > Environment?

**Comment by hongquan** [comment]
I set nothing in the Environment. It should use default Python configuration, right?

**Comment by Naatan** [comment]
Correct. Could you please take this to the forums? This does not appear to be a bug, but rather an issue with your project setup.

**Comment by hongquan** [comment]
But my project is supposed to use the default Python 3. If the default Python 3 has Pyflakes installed, it should be used, right?

**Comment by hobbsd** [comment]
I have the same problem (see issue #303), but in my case the configured Python3 is in a virtualenv.

**Comment by hobbsd** [comment]
Although, I see that in the application prefs the error exists as well:

![screen-2015-07-01_13-18](https://cloud.githubusercontent.com/assets/1676348/8460610/f99625a0-1ff3-11e5-8c59-e7200364282e.png)

That Python34 installation does have pyflakes installed.

**Comment by rsyring** [comment]
This is also a problem for me.  I have a custom Python3 interpreter.  Under Languages -> python 3, my interpreter is set to `/opt/python34/bin/python3.4`.  And pyflakes is installed:
```
rsyring@loftex:~$ /opt/python34/bin/python3.4
Python 3.4.3 (default, Apr  2 2015, 17:47:59) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyflakes
>>>
```

But the syntax checking settings area insists that Python3 does not have pyflakes installed.

**Comment by rsyring** [comment]
I can also confirm that when installing pyflakes into the system's python3, the settings warning went away.  So the detection of pylint is not respecting the custom python3 bin setting.

**Comment by rsyring** [comment]
Well...it went away until I restarted Komodo.  Now it's back to not recognizing pep8 or pyflakes regardless of which python3 I set it to.

**Comment by Naatan** [comment]
Please set your environment variables as I described in my first comment. Setting a python executable alone does not tell Python where your libraries are located if it's in a non-default location.

**Comment by rsyring** [comment]
@Naatan how is that supposed to work when I want to support two python versions (2 & 3)?  If I set the environment variables editor wide for Python 3, then it's not going to work for Python 2.  Or am I missing something?

**Comment by Naatan** [comment]
You can set environment variables at the global, project and file level. So if one project uses a different version of Python than the other then just edit the environment preferences for one of the projects.

**Comment by hobbsd** [comment]
Just out of curiosity, why would the environment variables need to be set in this case? Normally, the python interpreter knows where its libraries are located.

**Comment by hongquan** [comment]
Yes, we are all using the standard python library path, not custom location. Python interpreter should know where to look for, without `PYTHONPATH` environment variable.

**Comment by hongquan** [comment]
I set `PYTHONPATH` for project, but Komodo still fails to detect PyFlakes

![Pythonpath](http://forum.komodoide.com/uploads/default/original/1X/faa1f2bd547738e97351a75432152ddbf9d0708c.png)

**Comment by ervumlens** [comment]
Komodo Edit is testing for pyflakes in Python3 by executing the equivalent of the following <sup>1, 2</sup> :

`/usr/bin/python3 -c "import pyflakes3.scripts.pyflakes;"`

This fails for me after pip3'ing `pyflakes`. Trying to pip3 `pyflakes3` produces an error.

In contrast, Python2 pyflakes is tested for by looking for `pyflakes` on the path and by executing the equivalent to this <sup>2, 3</sup> : 

`/usr/bin/python -c "import pyflakes;"`

This works fine for me after pip2'ing `pyflakes`.

I can't tell you if changing the preference code will actually enable Python3 pyflakes checking, but I think this at least explains why the preference acts the way it does. 

---
1: [pref-syntax-checking.js#L901](https://github.com/Komodo/KomodoEdit/blob/8865f7249de2715c648b6aebc37b0f00b6466214/src/chrome/komodo/content/pref/pref-syntax-checking.js#L901)
2:  [koAppInfo.py#L606](https://github.com/Komodo/KomodoEdit/blob/8865f7249de2715c648b6aebc37b0f00b6466214/src/components/koAppInfo.py#L606)
3: [pref-syntax-checking.js:L696](https://github.com/Komodo/KomodoEdit/blob/8865f7249de2715c648b6aebc37b0f00b6466214/src/chrome/komodo/content/pref/pref-syntax-checking.js#L696-L703)

**Comment by ervumlens** [comment]
The following Komodo macro illustrates the problem. Python3 `pyflakes` module is available, but not `pyflakes3.scripts.pyflakes`.

```javascript
//this is a javascript macro
var python3 = Components.classes["@activestate.com/koAppInfoEx?app=Python3;1"].
        getService(Components.interfaces.koIAppInfoEx);

//var python3Exe = python3.executablePath;
//alert(python3Exe);

var found = python3.haveModules(1, ['pyflakes3.scripts.pyflakes']);
alert("Python3 module 'pyflakes3.scripts.pyflakes' found? " + found);

found = python3.haveModules(1, ['pyflakes']);
alert("Python3 module 'pyflakes' found? " + found);
```

**Comment by Naatan** [comment]
Thanks for digging @ervumlens, that's a great help!

**Comment by rsyring** [comment]
@Naatan thanks for reopening!
