### ISSUE TITLE
Adding opening brace doesnt add closing brace anymore

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#2871]
```
if (true)<|>
  return false
```

Typing `{` at the caret should insert `}` after the return, it doesnt.

This is handled by `_insertCloseBraceAfterLine` (thanks @mitchell-as)

**Comment by cgchoffman** [comment]
Don't you have to enable Prefs > editor  > Smart editing > Enable Soft characters?  I have a ticket to fix this not being enabled by default.  I can't reproduce this issue as I have that pref enabled.

**Comment by Naatan** [comment]
Bah, you're right. Seems like I was affected by that bug also.
