### ISSUE TITLE
Enhancement: UI to edit exclusions/inclusions for publishing

### ISSUE THREAD

**Issue by neurobashing** [Komodo/KomodoEdit#2874]
### Short Summary
I'd like the ability to edit the includes/excludes in publishing via UI.

### Steps to Reproduce
1. Set up publishing
2. forget to exclude some file type
3. Curse appropriately

### Expected results
Something like Publishing->Edit Configs

### Actual results
close Komodo, edit prefs.xml in vim

### Platform Information

current incl 11 Alpha

**Comment by cgchoffman** [comment]
I'm grateful you would still use Komodo after an apparent grievous oversite like this!  Thankfully there is no oversite.
![capture](https://user-images.githubusercontent.com/655154/29426284-0048943a-833b-11e7-857c-225a093b0e98.PNG)
