### ISSUE TITLE
Project->New Project ... from menubar not working

### ISSUE THREAD

**Issue by neurobashing** [Komodo/KomodoEdit#2875]
### Short Summary
From the OSX menubar, Project->New Project does nothing

### Steps to Reproduce
Project->New Project.

### Expected results
New project wizard.

### Actual results
nothing happens.

### Platform Information
Komodo IDE, version 11.0.0-alpha1, build 90456, platform macosx.
Built on Tue Aug 15 23:38:36 2017.

**Comment by cgchoffman** [comment]
Confirmed on OSX.  No issue on Windows.

**Comment by mitchell-as** [comment]
No issue on Linux either. OSX only issue.

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/62f1f440bd320072d970486229810296a476cb1a

**Comment by cgchoffman** [comment]
@mjainQA, *Menu Project > New Project...* and *Places pane > Projects section > Gear menu > New Project...* need to be tested on all platforms.
