### ISSUE TITLE
Always update the file db entry when a file was processed in the queue

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#2879]
At the moment when the queue processes a file it does not update (delete and reinsert) a file entry unless the scan was successful. It should update the file entry regardless as it's not like scanning it again will fix the issue. Without this the scanner will repeatedly scan the file whenever it comes up as it is never marked as "already scanned".

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/codeintel/commit/d4b0ded4e69e33d4edf14dbaee1328c23f595901
