### ISSUE TITLE
Package Manager -> Initialize using a file picker

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2881]
### Short Summary
 
It is using a file picker instead of folders

### Steps to Reproduce
1. Click on + button on the top right side
2. Select any package manager
3. Click on Initialize

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo IDE, version 11.0.0-alpha1, build 90477, platform macosx.
Built on Thu Aug 17 09:32:28 2017.
### Additional Information
![image](https://user-images.githubusercontent.com/26605593/29430417-290bbcfe-8349-11e7-8c35-c2aaf07a2dbc.png)

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/4a8e382cabe45ae0a549e080b295adf991d8ec5e
