### ISSUE TITLE
System default colorpicker is shown

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#2882]
### Short Summary
When editing css files I'm getting the systems default colorpicker.

### Platform Information
Komodo IDE, version 11.0.0-alpha1, build 90456, platform win32-x86

### Additional Information
![afbeelding](https://user-images.githubusercontent.com/3530262/29432043-5556f2b4-839a-11e7-8b46-d43aa1fa0a42.png)

**Comment by babobski** [comment]
```
[2017-08-17 22:20:01,836] [ERROR] koSysUtils: Unable to load the colorpicker with CID: u'@babobski.com/rgbaColorPicker;1'
```

**Comment by Naatan** [comment]
That's not a feature we have :P Guessing this was your code?

Gadver, Windows in het Nederlands? ;)

**Comment by babobski** [comment]
@Naatan It is copying over my preferences for the colorpicker `@babobski.com/rgbaColorPicker;1`.
Only I did not installed the addon yet, so it fails loading the colorpicker.

Ja altijd naar dat Nederlands 😉
