### ISSUE TITLE
No buttons to close the error dialog

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2887]
### Short Summary

There are no buttons for closing the error dialog

### Steps to Reproduce

Open any file in a editor
Right click on the file name and select 'Move to'
Choose the destination path and click ok
Notice the error message

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo IDE, version 11.0.0-alpha1, build 90477, platform macosx.
Built on Thu Aug 17 09:32:28 2017.
### Additional Information

 
![image](https://user-images.githubusercontent.com/26605593/29437838-fdfbe1b4-8367-11e7-9b40-935d12cd406f.png)

**Comment by babobski** [comment]
@mjainQA as workaround, can you resize the dialog so the buttons does appear?
