### ISSUE TITLE
Not using the set default language for the new files created

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2889]
### Short Summary

Komodo is creating 'Text' files for New files by default despite it is set to other languages in Pref.

### Steps to Reproduce

1. Go to Pref -> File Opening
2. Set 'Ruby' as default language
3. Right click in Places pane and create a 'New' file
4. Notice the default language

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo IDE, version 11.0.0-alpha1, build 90477, platform macosx.
Built on Thu Aug 17 09:32:28 2017.

### Additional Information
![image](https://user-images.githubusercontent.com/26605593/29439032-aef6976e-836f-11e7-83b7-8358f07cd966.png)

**Comment by mitchell-as** [comment]
Technically this was not a bug, as the preference states the default language applies to files created using the "New" button, not the "New File..." menuitem. I've fixed this anyway and updated the preference label.
