### ISSUE TITLE
Theme won't stick after build 15786 update

### ISSUE THREAD

**Issue by randomsock** [Komodo/KomodoEdit#289]
I have my skin set to Abyss with IcoMoon Light (and corresponding dark editor colours) but after this update it reverts to the black on white default.  Well, it does visually, but the preferences are still set as I had them.  If I change and reset them again to Abyss and IcoMoon Light to force it to re-apply, it changes visually OK, but reverts to default again when Komodo restarts.

**Comment by Naatan** [comment]
This was fixed in https://github.com/Komodo/KomodoEdit/commit/622a10818c98a387a71011c0e01d0c99a6fb1833, this fix is not in the current nightly but will be available in the next one (later today).

**Comment by randomsock** [comment]
Awesome, thanks.
