### ISSUE TITLE
Unable to create a GEMFILE via package manager gem -> initialize

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2890]
### Short Summary
Getting an error while trying to initialize using gem package manager. 

### Steps to Reproduce
1. Click on + on top right in side bar
2. Click Gem -> initialize. Choose the location for GEMFILE
3. Notice the error

It works on command line outside Komodo
### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo IDE, version 11.0.0-alpha1, build 90491, platform macosx.
Built on Thu Aug 17 23:38:33 2017.
### Additional Information

 
![image](https://user-images.githubusercontent.com/26605593/29471942-d181ba38-8406-11e7-9b70-d1c0bc80b6ea.png)

**Comment by Naatan** [comment]
This is an issue with your configuration, you are using rvm but Komodo cannot auto detect your rvm paths. You need to configure Preferences > Environment appropriately.

There might be something we can do in the future to facilitate this, but at the moment this is not part of the spec.
