### ISSUE TITLE
Rendering issue in "Getting Started" tutorial

### ISSUE THREAD

**Issue by we3geeks** [Komodo/KomodoEdit#2892]
Several screens within the "Getting Started" tutorial appear to have embedded logic being rendered in Komodo v11 (verified in build 90491), and present on at least screens 5, 8, 9 and 10 of the tutorial. This does not appear to be an issue in v10.

Example (see the text within the "Task" section):
<img width="438" alt="2017-0818-k11-a" src="https://user-images.githubusercontent.com/2390335/29475340-877ea50c-841c-11e7-85b7-1d7a5e8aedcd.png">

Build Info:
Komodo IDE, version 11.0.0-alpha1, build 90491, platform macosx. Built on Thu Aug 17 23:38:33 2017

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/8fa87edc15ad3cd0a09c81c879fa88eb41d2e5e6
 Thanks @we3geeks.
