### ISSUE TITLE
Preferences window does not have an icon

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#2893]
### Short Summary

title.

![image](https://user-images.githubusercontent.com/7100645/29476843-80a3c31e-846e-11e7-81a2-ab36ef9cb528.png)

I guess it's platform-independent.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* latest QA build
*Operating System (and version)?* Windows 10

**Comment by Naatan** [comment]
It has never had one.
