### ISSUE TITLE
Quick bookmarks are removed on file save

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#2894]
Add a quick bookmark, save the file, quick bookmarks are removed.

**Comment by Naatan** [comment]
Seems the problem is formatters. The issue is actually that the quick bookmarks (and presumably any markers) get removed when you invoke a formatter. I was using Python reindent.

**Comment by mitchell-as** [comment]
When you replace the contents of the document, all markers are lost, including breakpoints. This is not new in Komodo 11.

**Comment by Naatan** [comment]
But with the format on save mechanic it becomes a bigger issue. I guess there isn't really a way this can be fixed though. We'd need to have full control of the formatters, which we don't.

**Comment by cgchoffman** [comment]
This will make "save on format" useless to me if we don't try to resolve it.  This doesn't seem like something we should just say "can't fix it".

**Comment by Naatan** [comment]
It's unfixable unless we write our own formatters. No way around it. The BEST we could possibly do is -guess- where the markers might end up, and that would be very rough and error prone guessing.

**Comment by cgchoffman** [comment]
Alright, well the fact still remains that this makes the formatting on save not very usable in quite a few cases.

**Comment by Naatan** [comment]
I agree it's very unfortunate, but I don't see a simple solution.

Keep in mind format on save was a 1 day hackathon product, not something we were explicitly targeting for 11.
