### ISSUE TITLE
No frameworks are listed for some languages

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2895]
### Short Summary

In project wizard, the frameworks are not populated for C++, Handlebars, . If the list is supposed to be empty, it should show the appropriate message.

### Steps to Reproduce

1. Click on 'New Project' from settings in Project Pane

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo IDE, version 11.0.0-alpha1, build 90491, platform macosx.
Built on Thu Aug 17 23:38:33 2017.
### Additional Information

 
![image](https://user-images.githubusercontent.com/26605593/29480812-02227e7e-8430-11e7-80a3-031af4934fab.png)

**Comment by Naatan** [comment]
We only facilitate certain frameworks. That said this could use some slight UX improvements, maybe just add a default entry "Other framework".

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/3a9b0084d69a8be26cd8cd8c912e7a81550b78cc
