### ISSUE TITLE
Komodo 11 upgrade has vague error message

### ISSUE THREAD

**Issue by mjross** [Komodo/KomodoEdit#2897]
### Summary
When installing Komodo 11 build 90491 on a Windows system that already has version 11 build 90396 as well as version 10 installed, I received the following error message: “Another version of this product is already installed. Installation of this version cannot continue. To configure or remove the existing version of this product, use Add / Remove Programs on the Control Panel.”

There seem to me to be at least problems with this error message and the requirement that the existing version be uninstalled, so I'll submit them as separate issues to allow separate discussion and possible change threads.

The error message should tell the user _which_ of the already installed versions needs to be removed. In my case, is it version 10 or is it version 11 build 90396 that is the source of the problem? I'm guessing the latter (and that's what I'll try next), but I could be wrong, and the user shouldn't have to try to guess at it and possibly end up removing the wrong version unnecessarily.

### Platform Information
Komodo IDE 10.2.2 and Komodo IDE 11 build 90396 on Windows 10 Pro

### Attachments
![windows installer dialog](https://user-images.githubusercontent.com/829492/29482558-31fd8f7e-8450-11e7-9eb4-281c8adfc137.jpg)

**Comment by Naatan** [comment]
As Defman said this is by design. I don't think we actually have much if any control of this as it's handled by MSI.

**Comment by mjross** [comment]
*Just to clarify, I'm not stating that the error message is invalid or
illegitimate, but rather that it unhelpfully does not specify which version
needs to be uninstalled.*

**Comment by Defman21** [comment]
I guess Komodo devs have no control over the message. It's up to Microsoft to specify the program you need to remove.

**Comment by mjross** [comment]
Thanks for letting me know that it is controlled by the Microsoft installation process. Yet I still find the error message to be unclear: From my perspective, Komodo 10 and 11 are not two different products, but rather two different versions of the same product, Komodo. After all, we refer to them as “version 10” and “version 11”. And when ActiveState releases the stable version 11, I doubt that they will announce it to be a new product offered by the company. Komodo 11 build 90491, relative to build 90396, for instance, would generally be referred to as a “point release”. Either way, we’re stuck with the MSI ambiguity.
