### ISSUE TITLE
Komodo 11 upgrade should not require uninstall of existing version

### ISSUE THREAD

**Issue by mjross** [Komodo/KomodoEdit#2898]
### Summary
When installing Komodo 11 build 90491 on a Windows system that already has version 11 build 90396 as well as version 10 installed, I received the following error message: “Another version of this product is already installed. Installation of this version cannot continue. To configure or remove the existing version of this product, use Add / Remove Programs on the Control Panel.”

There seem to me to be at least problems with this error message and the requirement that the existing version be uninstalled, so I'll submit them as separate issues to allow separate discussion and possible change threads.

Most software products allow the user to upgrade to a newer version -- especially a minor point release and not a major one -- without having to uninstall the existing version. In fact, some products, such as Google Chrome, can do all of that in the background. Why should the Komodo IDE user have to completely uninstall an existing version to upgrade it?

### Platform Information
Komodo IDE 10.2.2 and Komodo IDE 11 build 90396 on Windows 10 Pro

### Attachments
![windows installer dialog](https://user-images.githubusercontent.com/829492/29482600-8d99d968-8451-11e7-92b8-5de6ed5d1e9e.jpg)

**Comment by Naatan** [comment]
This is by design, you won't get this when you upgrade the stable release.

**Comment by mjross** [comment]
*Okay. I assume that the reasons for that outweigh the inconvenience to
testers in having to go through the uninstall process each time there is a
new-build release.*

**Comment by Naatan** [comment]
At least at this stage, yeah.

**Comment by cgchoffman** [comment]
I believe this is because we use the MSI tooling for install.  Other programs that don't hit this don't use MSI i'm fairly certain.  @mjross, once we get out of Alpha stage we will be able to publish the Nightlies and you will be able to use Komodo's built in *auto-update* tooling (which is what nathanr basically said above now that I read his comment again...).

**Comment by mjross** [comment]
Cool. Thanks.
