### ISSUE TITLE
Komodo asked to restart to complete changes after being started

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#29]
No changes were made.  Komodo asked to restart immediately.  
![image](https://cloud.githubusercontent.com/assets/655154/6603197/b6ef4a92-c7dd-11e4-886b-2948884c68dd.png)

Can't attach the logs.  I'll keep them in my dropbox for now, they will get purged at some point though.: https://www.dropbox.com/s/mloltijfleuysyg/namiklog.log?dl=0

**Comment by cgchoffman** [comment]
I've also asked namik to save the state of his profile before restarting so he still has that currently.  Unforutnately don't have the pre-start state which might have been interesting.

**Comment by Naatan** [comment]
Is this on first start? This is because on Linux Komodo auto-detects the skin, so it actually changes your skin at first start (if it detects one). Will see about moving that check to before the UI is initialized, but its not a huge issue.

**Comment by cgchoffman** [comment]
Yep first start.  I suspected the skin detection from reading the logs.  it's not a huge deal.  Certainly can wait.

**Comment by mitchell-as** [comment]
I'm not seeing this any more in master. It was probably fixed with the new UI changes.
