### ISSUE TITLE
KO11 cmd_jumpToNextSection cmd_jumpToPreviousSection missing?

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#2900]
Komodo IDE, version 11.0.0-alpha1, build 90491, platform linux-x86_64.
Built on Fri Aug 18 00:20:55 2017.

those worked with KO10, can't find them in 11.

**Comment by Defman21** [comment]
#2616

**Comment by agroszer** [comment]
dupe

**Comment by Naatan** [comment]
This particular one actually missed the boat, thanks for reminding us.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoIDE/commit/1638766230d9c82f4b2e3f822b855d838cee70d5

**Comment by agroszer** [comment]
sorta works, in some files... what are it's the dependencies? codeintel?

I have a python file what is supposed to be in codeintel, jump does nothing

I have an other python file what is not supposed to be in codeintel, there jump next is doing loops, like class1 > jump next > class2 > jump next > class3 > jump next > class1 > etc but there are lots of classes before 1 and after 3

**Comment by Naatan** [comment]
@agroszer if you have a reproducible use-case can you please report a new bug for it? Thanks!
