### ISSUE TITLE
KO11 high idle CPU usage

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#2901]
Komodo IDE, version 11.0.0-alpha1, build 90491, platform linux-x86_64.
Built on Fri Aug 18 00:20:55 2017.

Idle CPU usage is around 15-20%-ish without addons, whereas KO10 latest is under 5% with addons.

**Comment by Naatan** [comment]
I'm getting about 10%, but it does seem higher than KO10. I've not been able to find the cause of this yet. Let me know if you find anything that correlates.

**Comment by Naatan** [comment]
I'm actually not seeing this anymore after Fridays build. Can you update to the latest build posted on the forums and let me know what your idle cpu is?

**Comment by agroszer** [comment]
Komodo IDE, version 11.0.0-alpha1, build 90514, platform linux-x86_64.
Built on Mon Aug 21 00:23:15 2017.

still hovering around 20%

**Comment by Naatan** [comment]
Can you reproduce it in safe-mode?

**Comment by agroszer** [comment]
meeeh PITA, my home is git controlled, so I guess when KO safe mode starts up it starts SCC scanning which then sends CPU and RAM use through the roof... will try later

**Comment by agroszer** [comment]
is there any tool/addon which would show what's going on?

**Comment by Naatan** [comment]
Komodo 11 doesnt scan large folder structures unless you confirm the scanning prompt. If you start Komodo and wait for a few minutes to let it reach idle stage then you should be fine.

As for tools/addons, you could try profiling, I added documentation here:

http://docs.komodoide.com/SDK/How_to_profile_Komodo

**Comment by agroszer** [comment]
I think this is SCC scan, not codeintel, you know the issue when you got a git controlled folder with a gazillion files

**Comment by agroszer** [comment]
Got a cleo profile, looks like KO is repainting something? I could send you the file (160K), but how?

**Comment by Naatan** [comment]
Google drive or similar it? Paints happening is not abnormal and is unlikely to be causing 20% CPU.

**Comment by agroszer** [comment]
[unnamed-1503502313275.cleo.zip](https://github.com/Komodo/KomodoEdit/files/1246366/unnamed-1503502313275.cleo.zip)

**Comment by Naatan** [comment]
Nothing really stands out.

I noticed something strange in the Gnome System Monitor though, if that's what you're using. My Komodo CPU usage just gets stuck at a number when I alt tab out of Komodo and it only updates if I manually invoke refresh on the system monitor. Could this be affecting you also?

**Comment by agroszer** [comment]
Managed safe mode... It's a tad better. With safe mode CPU usage is hovering under 20 (15-20) without safe mode a bit over 20 (20-25). Without addons it's also a bit over 20 (20-25).

Here is a profile with safe mode: 
[unnamed-1503552739548.cleo.zip](https://github.com/Komodo/KomodoEdit/files/1247831/unnamed-1503552739548.cleo.zip)

I'm monitoring with htop in a terminal

**Comment by Naatan** [comment]
Could you try disabling any afdons you can under tools > addons (legacy). Komodo will be hella bugy but I'm only interested in if it fixed your idle cpu.

**Comment by Naatan** [comment]
Disabling codeintel seems to significantly reduce CPU usage for me.

**Comment by Naatan** [comment]
Narrowed down the issue to a CSS animation, sigh. Working on a fix now (SVG animations are apparently far more CPU friendly).

**Comment by Defman21** [comment]
I remember some hacks around CSS animations, one of them was calculating the animations with GPU by `transform: translateZ(0)` or something like that.

**Comment by Naatan** [comment]
I tried that, it had very little effect.

**Comment by agroszer** [comment]
actually LOL, looks like an OS reboot helps too, back to hovering around 15%-is, more like under 15

**Comment by Naatan** [comment]
15% is still wait too much though. If you open the symbol browser widget it should go down to near 0% while idle. 

I'll post a new build today.
