### ISSUE TITLE
Preferences > Languages > HTML > Default HTML Document Type list is empty

### ISSUE THREAD

**Issue by we3geeks** [Komodo/KomodoEdit#2902]
The dropdown list of HTML document types under "Preferences > Languages > HTML > Default HTML Document Type" appears to be completely empty. That's of interest, at least in part, as presumably the selected document type would be what drives tag/attribute completion in HTML documents (but also because I maintain a Komodo language extension for CFML that provides relevant tag/attribute completions via additional DTDs that can be selected through that preference).

<img width="869" alt="2017-0820-k11-a" src="https://user-images.githubusercontent.com/2390335/29495463-15b2e052-857d-11e7-9c6e-4c4ee9765833.png">

Build Info:
Komodo IDE, version 11.0.0-alpha1, build 90491, platform macosx.
Built on Thu Aug 17 23:38:33 2017.

**Comment by mitchell-as** [comment]
We have a ticket to figure out what to do about this: #2774

Right now, the HTML completions you get depends on the language: HTML5 gives you HTML5 completions, and HTML gives you HTML4 completions.
