### ISSUE TITLE
Tool tip is not displayed

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2907]
### Short Summary

Tool tip is not displayed. See screenshot.

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* win7 64
Komodo IDE, version 11.0.0-alpha1, build 90514, platform win32-x86.
Built on Sun Aug 20 23:00:13 2017.
### Additional Information

![image](https://user-images.githubusercontent.com/26605593/29529635-4d97cf4a-8655-11e7-8e30-f37492040c50.png)

**Comment by Naatan** [comment]
I cannot reproduce this. Can you reliably reproduce this? If so please give exact repro steps.

**Comment by mjainQA** [comment]
100% reproducible. Hover in the margin where once can set the breakpoint. 

![image](https://user-images.githubusercontent.com/26605593/29530110-2f6dd756-8657-11e7-9f78-2b76629b4bd1.png)

**Comment by Naatan** [comment]
Tried it on Windows with the classic color scheme, no dice. This may be another windows 7 specific issue.

**Comment by Naatan** [comment]
I'm gonna try a fix but I cannot verify it, so please make sure you verify it when this ticket is closed.
