### ISSUE TITLE
codeintel/completion error: tab trigger oddness

### ISSUE THREAD

**Issue by neurobashing** [Komodo/KomodoEdit#2909]
### Short Summary
In Python, I was writing an except block; I did `except Ex<tab>` and got

`except Ex   Exception:`

### Steps to Reproduce
As above.

### Expected results
`except Exception`

### Actual results
As above.

### Platform Information
Komodo IDE, version 11.0.0-alpha1, build 90514, platform macosx.
Built on Sun Aug 20 23:39:49 2017.

EDIT: Komodo background-crashed while I was entering this bug report.

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/5961d99562442ea7d70aabee32793f7c0ac41153
