### ISSUE TITLE
Extended Abbreviations gone after update to 9.0.1 => 9.1.0

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#291]
i dont know if this is a bug or a bad practice by me.
I extended the Abbreviations in 8.5 so i could use the "insert abbreviation snippet by name", i added some support for inline php in html files example: ? expanded to <?php ?> added if, ifelse, foreach.
extended the php for if ifelse and the javascript for console.
I've copied the Abbreviations to 9.0.1 but where lost on the update to 9.1.0, copied them to 9.1.0 and they are working again. do i have to copy them on every update, or is it a bug, or just a bad practice by me?

**Comment by Naatan** [comment]
Komodo automatically imports your old settings. The only exception is the "Samples" folder, this gets replaced each time you update Komodo as it is a "Samples" folder. You should not create tools under the samples folder. Note you can import your old samples from the "Obsolete Samples" folder in your toolbox.

Please do not use the samples folder for anything other than its intended use though.
