### ISSUE TITLE
blank UI fields in Sync/publish column selection

### ISSUE THREAD

**Issue by neurobashing** [Komodo/KomodoEdit#2910]
### Short Summary
The column selector is missing field labels.

### Steps to Reproduce
Tools->Publish-> and select a config to publish. In the Synchronization window, click the UI widget for selecting which fields to show.

### Expected results
Labels

### Actual results
![screen shot 2017-08-21 at 12 42 12 pm](https://user-images.githubusercontent.com/59380/29538975-90e5e860-86b7-11e7-9f98-4dc1f1cb325d.png)

(note that this occurs in light and dark themes)

### Platform Information
Komodo IDE, version 11.0.0-alpha1, build 90514, platform macosx.
Built on Sun Aug 20 23:39:49 2017.

### Additional Information
clicking the un-labeled fields does affect the UI.

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/19ae2e770055469cee713fe562e0bc66ad43ba81
