### ISSUE TITLE
Double clicking on File Template does not present the option for filename

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2911]
### Short Summary

1) When double-clicked on template from Commando, user is not given an option to choose filename. Instead a template opens in the editor.

2) Same when 'Use Template' option is used from Toolbox -> File Templates -> right click on any template 

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo IDE, version 11.0.0-alpha1, build 90514, platform macosx.
Built on Sun Aug 20 23:39:49 2017.
### Additional Information
![image](https://user-images.githubusercontent.com/26605593/29542189-3385ef54-868e-11e7-9de0-4dfe04ccc76a.png)

![image](https://user-images.githubusercontent.com/26605593/29542220-6559ed14-868e-11e7-9a30-87a064195baa.png)

**Comment by Naatan** [comment]
This is how the feature works. You can choose a filename when you save it.

**Comment by mjainQA** [comment]
Hey Nathan, Just trying to understand this feature better. So double clicking on File Template in Commando opens the template. What’s the intention here? Use Commando for editing file templates or create a new file using the template in Commando? 

Also, what's the difference in options between 'Use Template' and 'Edit Template' in the above screenshot? Both options simply open the template.

**Comment by cgchoffman** [comment]
> Also, what's the difference in options between 'Use Template' and 'Edit Template' in the above screenshot? Both options simply open the template.

I'm not sure about the Commando questions but for the Toolbox menus I know the answer:

Look at the names of the files that get opened.  They are not the same.  "Use Template" opens an HTML file.  "Edit Template" opens the template as a file to be edited, eg. *blah.template*.  They just look the same because you're not using EJS or anything that would dynamically change the contents of the file when you open it.

**Comment by Naatan** [comment]
Fwiw Madhu and I discussed this in a hangout call, so I consider these questions answered.

**Comment by cgchoffman** [comment]
K.  One comment. This doesn't seem like a good place for these types of questions.  They aren't related to the original ticket.  They should happen in Slack or in a chat like you guys did.
