### ISSUE TITLE
Dragging and dropping tools to a new folder creates a copy

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2912]
### Short Summary

Dragging and dropping the template to a new folder creates a copy of the file instead of moving it.

### Steps to Reproduce
1. Go to Toolbox as shown in screenshot
2. Drag and drop any template from one folder to another
3. Notice that it creates a copy and not move the file. Same file exists at both the locations
### Expected results

Expected that the template file should have been moved.

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo IDE, version 11.0.0-alpha1, build 90514, platform macosx.
Built on Sun Aug 20 23:39:49 2017.
### Additional Information
![image](https://user-images.githubusercontent.com/26605593/29542337-36fe522e-868f-11e7-81f9-4cdfd9c25705.png)

**Comment by cgchoffman** [comment]
Looks like it's all tools.

**Comment by Naatan** [comment]
Yeah, I renamed the title
