### ISSUE TITLE
Nothing is listed under Commando -> Packages

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2913]
### Short Summary

Nothing is listed under Commando -> Packages

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo IDE, version 11.0.0-alpha1, build 90514, platform macosx.
Built on Sun Aug 20 23:39:49 2017.
### Additional Information
![image](https://user-images.githubusercontent.com/26605593/29578551-7d258962-8724-11e7-8ebc-0e679f4b8c92.png)

**Comment by Naatan** [comment]
Error log please.

**Comment by mjainQA** [comment]
[pystderr_2017-08-22_Komodo IDE 11.0.0 Alpha 1 nightly (Build 90514).txt](https://github.com/Komodo/KomodoEdit/files/1242855/pystderr_2017-08-22_Komodo.IDE.11.0.0.Alpha.1.nightly.Build.90514.txt)

**Comment by mjainQA** [comment]
Resolved in the latest build.
