### ISSUE TITLE
Template is not created when trying to save using File -> Save As Other

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2916]
### Short Summary

A template is not created/saved when saved using File -> Save As Other

### Steps to Reproduce

1. Open any file
2. Click File -> Save As Other -> Template
3. Enter filename
4. Notice nothing happens

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo IDE, version 11.0.0-alpha1, build 90522, platform macosx.
Built on Mon Aug 21 23:38:43 2017.
### Additional Information
[pystderr_2017-08-22_Komodo IDE 11.0.0 Alpha 1 nightly (Build 90522).txt](https://github.com/Komodo/KomodoEdit/files/1243681/pystderr_2017-08-22_Komodo.IDE.11.0.0.Alpha.1.nightly.Build.90522.txt)

**Comment by Naatan** [comment]
What do you mean by "nothing happens"? Did you verify that a template was created in your toolbox?

It sounds like the issue here is likely UX - Komodo should better communicate what happened.

**Comment by mjainQA** [comment]
Yes, the newly created template is not available in the toolbox. 

Are you able to create a template using File -> Save As Other -> Template?

**Comment by Naatan** [comment]
I am. Unfortunately your logs are all but useless for macos as I can't see the forest through the trees. What's strange though is that if there is an error it should be near the bottom of the log. Are you sharing your log file immediately after reproducing the issue? It's important that you do otherwise it's increasingly hard to correlate log entries to your issue.

**Comment by mjainQA** [comment]
The attached error logs are right after the issue is reproduced (always)!

Is it just the logs on macOS are useless in general or you are referring to my install? 

Here is new error log:


[pystderr_2017-08-23_12:18_Komodo IDE 11.0.0 Alpha 1 nightly (Build 90532).txt](https://github.com/Komodo/KomodoEdit/files/1246725/pystderr_2017-08-23_12.18_Komodo.IDE.11.0.0.Alpha.1.nightly.Build.90532.txt)

**Comment by Naatan** [comment]
Very strange, there's nothing in the log indicating an issue. The template should be created.

Please try creating a template using the steps you gave but giving it a name that is entirely unique and easy to find. Then use the search box in the toolbox to see if it can find it. If it can't open your profile folder and navigate to the Tools folder and then search for the filename again. Do both of these tests come up empty?

**Comment by mjainQA** [comment]
Okay it created a template but NOT under File Templates. I was able to find it.

Sorry about that.
