### ISSUE TITLE
Template is created twice 

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2917]
### Short Summary
 Template is created twice when created using Template properties window.

### Steps to Reproduce
1. Go to Toolbox -> File Templates -> My Templates -> Add New Template
2. Specify name in the top box
3. Click Apply and then ok.
4. Notice there are two entries under My Templates.

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo IDE, version 11.0.0-alpha1, build 90522, platform macosx.
Built on Mon Aug 21 23:38:43 2017.
### Additional Information
****

 
![image](https://user-images.githubusercontent.com/26605593/29592055-e670d16a-8756-11e7-8998-53c1fc596e49.png)

**Comment by Naatan** [comment]
Looks like Apply and OK are both creating the template.
