### ISSUE TITLE
Confusing menu label for Folder Templates

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2926]
### Short Summary

'New template from folder...' is a confusing menu label for creating folder templates. In my opinion, it sounds like a user will be presented with templates in a particular folder to pick one for creating a new template.

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo IDE, version 11.0.0-alpha1, build 90532, platform macosx.
Built on Tue Aug 22 23:38:43 2017.
### Additional Information
![image](https://user-images.githubusercontent.com/26605593/29642445-caff5ef2-881d-11e7-9a81-c6fd74cd8df4.png)

**Comment by Naatan** [comment]
How does "Create a Template from this Folder" sound?

**Comment by mjainQA** [comment]
Here are my suggestions:
1) New Template from this folder
2) New Template (using this folder structure)
