### ISSUE TITLE
Go to Def not working

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2927]
### Short Summary

I'm getting this error:
```
[2017-08-23 16:12:44,881] [ERROR] codeintel/service/mediator: Request failed with message: Failed calling API method: getDefinition, message: global name 'PeeweeException' is not defined (-32603)
```

### Steps to Reproduce

Not sure how to reproduce, it just stopped working.

### Additional Information

Komodo Logs:
[pystderr - Copy.txt](https://github.com/Komodo/KomodoEdit/files/1247305/pystderr.-.Copy.txt)

Codeintel Logs:
[codeintel3 - Copy.txt](https://github.com/Komodo/KomodoEdit/files/1247306/codeintel3.-.Copy.txt)

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/codeintel/commit/5bb8298e06795485ab7baff7db5604e75243e799
