### ISSUE TITLE
Publishing Dialog has black border

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2929]
### Short Summary

The publshing dialog has that black border.  Just open it on Windows.

![capture](https://user-images.githubusercontent.com/655154/29644344-3030034c-882a-11e7-9b95-6ae0b150c6cf.PNG)

**Comment by Defman21** [comment]
#2851 is related to this issue.

**Comment by cgchoffman** [comment]
Same symptom, different cause.  That's why I filed a new bug @snek.  The fix for #2851 does that fix this issue. thanks

**Comment by Defman21** [comment]
My username is still Defman21, not snek 😃

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/ed9c8aa78f5d615e5294e302d6e71dd9ff8c98d3
