### ISSUE TITLE
Scroll bar sits on top of browse button in First Start Wizard - check configuration page

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2931]
### Short Summary
Scroll bar sits on top of browse button in First Start Wizard - check configuration page 

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo IDE, version 11.0.0-alpha1, build 90542, platform macosx.
Built on Wed Aug 23 23:38:52 2017.
### Additional Information
![image](https://user-images.githubusercontent.com/26605593/29680067-53eb3f2a-88b8-11e7-9200-baf5d4bcfa8c.png)

**Comment by Naatan** [comment]
@cgchoffman just add some padding-right to the scrolled area.

**Comment by cgchoffman** [comment]
Are you sure it's not a window sizing issue, ie. window.sizeToContent?  The title isn't centred.  If we add padding won't that mess up the window for other platforms?

**Comment by Naatan** [comment]
Nope, it's a scrollbar issue.

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/7e029b8b9abe8553a5486961d7c8ad4fc68458eb
