### ISSUE TITLE
Komodo 11 Drupal toolbox snippets CVS Id variable

### ISSUE THREAD

**Issue by mjross** [Komodo/KomodoEdit#2934]
In the Drupal toolbox snippets introduced with Komodo 11, drinfo contains `; \$Id\$` and drinstall and drmodule contain `// \$Id\$`. Those lines are incorrect and should be removed from the snippets, because the Id variable was used only for the CVS code revisioning system, which the Drupal community stopped using years ago.

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/0ee620ce7ea0b926fd3cb503cbfa7d4a6e8c86e3
