### ISSUE TITLE
CSS rules not saving in Color Scheme editor

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2935]
### Steps to Reproduce

This is using the default color scheme.

- Tools > Color scheme editor
- Select "interface" in the dropdown list on the left
- Add a new CSS rule (or any text) to the CSS field on the right
- CLick apply and apply
- CLose
- re open the color scheme editor

### Expected results

The text to still be there

### Actual results

It is not

**Comment by Naatan** [comment]
What color scheme did you have selected?

**Comment by cgchoffman** [comment]
Updated the report @Naatan.  I'm using *default*.

**Comment by Defman21** [comment]
I guess you have to create a new theme.

https://github.com/Komodo/KomodoEdit/issues/2478

**Comment by cgchoffman** [comment]
Oh yep, that's it's.  Dupe of #2478.
