### ISSUE TITLE
Help is not working for Folder template window

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2937]
### Short Summary

Help is not working for create folder template window via Toolbox

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo IDE, version 11.0.0-alpha1, build 90542, platform macosx.
Built on Wed Aug 23 23:38:52 2017.
### Additional Information
![image](https://user-images.githubusercontent.com/26605593/29692277-05fcfff2-88e4-11e7-9574-eb7f4f27c7f3.png)

**Comment by Naatan** [comment]
I need to remove this button (and other buttons like it). Keeping a mapping to the documentation site alive within Komodo is not feasible.
