### ISSUE TITLE
Unable to create a Folder Template using Toolbox

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2938]
### Short Summary

OK button is disabled while trying to create a Folder Template using Toolbox

### Steps to Reproduce

1. Go to Toolbox -> Folder Templates
2. Right click -> Add -> New Folder Template

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo IDE, version 11.0.0-alpha1, build 90542, platform macosx.
Built on Wed Aug 23 23:38:52 2017.
### Additional Information
![image](https://user-images.githubusercontent.com/26605593/29692493-36c453dc-88e5-11e7-978d-f9500e31d5a4.png)

**Comment by Naatan** [comment]
Seems the folder.. button is not firing an event, when I manually edit the folder URI (add a char and remove it) the button becomes enabled.
