### ISSUE TITLE
Places toolbar doesnt inhert theme background colour?

### ISSUE THREAD

**Issue by tomstorey** [Komodo/KomodoEdit#294]
Ive just installed Komodo Edit 9 and applied the latest update, and after selecting a theme (Abyss) with a dark background, the places toolbar doesnt seem to be applying this theme entirely. This results in a bright bar down the side of the screen which is against the nature of what Im trying to achieve (easy on the eye in dark environment.) The colour of the text is very light, however, which one might expect with a dark theme, and with the bright background this makes it very difficult to read the text.

Ive attached a screen shot showing what I am seeing (Ive purposely blocked out some of the text.)

Have tried a restart of Komodo, and also tried installing on a different machine and the issue persists.

Build info:
Komodo Edit, version 9.1.0, build 15786, platform macosx. Built on Thu May 21 04:13:48 2015.

![screen shot 2015-05-25 at 21 11 38](https://cloud.githubusercontent.com/assets/7754310/7801840/cee004f4-0322-11e5-83cd-0303669b0b53.png)

**Comment by Naatan** [comment]
I'm not seeing this, could you try unsetting and then setting the Abyss skin again?

**Comment by tomstorey** [comment]
Hi. Yep I have tried this and it doesnt resolve. Have also tried restarting my Mac.

Ive also noticed that when switching to another window, the background colour of the currently selected tab changes to something much brighter, although this is much less of an issue.. Probably best to see the attached image:

![screen shot 2015-05-28 at 11 37 38 pm](https://cloud.githubusercontent.com/assets/7754310/7872786/d743534a-0592-11e5-9e08-9fc269c55cbc.png)

**Comment by tomstorey** [comment]
As of build 15796 (which just came through as an update about 5 minutes ago) this now appears to be resolved.

Thanks!
