### ISSUE TITLE
Support history in commit messages

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2940]
### Short Summary

Komodo actually saves commit messages already.  I think they are saved to the prefs, `commit_message_history`.  Let's populate a popup history with that information.  

### Steps to Reproduce

In the commit pane of the Version Control tool do completions for previous commit messages.

**Comment by Naatan** [comment]
You can access the saved commit messages via the history button:

![image](https://user-images.githubusercontent.com/278649/29719012-9edf1752-8982-11e7-8c40-04b3f835775e.png)

I agree auto completions would be nice, but the investment it would take to implement that is more than the feature is worth.

I know we have completions elsewhere in Komodo, but those are a very different use case and their code would not be reusable here.

**Comment by cgchoffman** [comment]
Cool thanks!
