### ISSUE TITLE
Toolbox is not refreshed after importing Wordpress tools

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2941]
### Short Summary

WordPress tools are added to the selected folder in the toolbox. Tools only show after user switches focus in Komodo.

### Steps to Reproduce

1. Go to toolbox -> right click any folder -> import -> wordpress tools
2. Notice no tool is added
3. Click anywhere else and notice tools show up in the folder

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo IDE, version 11.0.0-alpha1, build 90542, platform macosx.
Built on Wed Aug 23 23:38:52 2017.
### Additional Information
![image](https://user-images.githubusercontent.com/26605593/29693078-71d44826-88e8-11e7-84b8-68c2474d291f.png)

**Comment by Naatan** [comment]
There's definitely a bug here in that the user should not have to shift focus, but I do not agree this needs a prompt. The user is giving Komodo contextual information when he right clicks the folder.

One design goal I have with Komodo is to not reduce it to annoying an unnecessary prompts anytime you do something. Of course prompts are still relevant, but only sometimes.

So we'll make this bug about fixing the refocus issue, not adding a prompt.

**Comment by Naatan** [comment]
@cgchoffman please be sure to read my comment above before working on this.

**Comment by cgchoffman** [comment]
The user is not supposed to be prompted when they use the context menu of a folder.  The only time they should be prompted for a location is when they use the *general* gear menu of the entire toolbox located in the top right of the toolbox pane.

I may not have made that clear in the feature spec.

**Comment by cgchoffman** [comment]
I can't reproduce this on Windows or OSX.  Wordpress tools are loaded  immediately.

**Comment by cgchoffman** [comment]
@mjainQA can you reproduce this still?

**Comment by cgchoffman** [comment]
I suspect what happened is that there is a delay while Komodo copies the files to your toolbox then the toolbox service loads them.  For @Naatan it took 2-3 secons.  For me it's immediate.  So @mjainQA, wait up to 5 seconds to see if they appear.

**Comment by mjainQA** [comment]
Unable to reproduce it anymore.
