### ISSUE TITLE
Spelling error in Laravel toolbox

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2949]
### Short Summary

See screenshot

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo IDE, version 11.0.0-alpha1, build 90546, platform macosx.
Built on Thu Aug 24 23:40:02 2017.
### Additional Information
![image](https://user-images.githubusercontent.com/26605593/29735778-6e6436ec-89b0-11e7-8a25-7256957fa933.png)

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/81e30a0efea4620be58c8f6875b123aed0ab4144
