### ISSUE TITLE
Code browser blank for projects opened in a new window

### ISSUE THREAD

**Issue by sfsccn** [Komodo/KomodoEdit#2952]
### Short Summary

The code browser is blank for all files in projects opened in a new window.

### Steps to Reproduce

* Open a project and view the code browser for a file in that project (php in my case)
* Open a different project in a new window and repeat. 

### Expected results

* Code browser should work normally in both cases

### Actual results

* Code browser only works for the first opened project. It's blank for the project opened in a new window (see screenshots).

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.2.3
*Operating System (and version)?* Linux RHEL/Fedora 3.10.0-693.1.1.el7.x86_64

### Additional Information

![normal](https://user-images.githubusercontent.com/7990148/29785243-796f01c8-8bec-11e7-802f-b8f766a2a10a.png)

![project in new window fails](https://user-images.githubusercontent.com/7990148/29785248-7d04624c-8bec-11e7-987a-faee6e0df94e.png)

This is very similar to the following issue. I wasn't sure if it was closed because it was planned to be fixed, so I thought I'd better submit my own issue.

https://github.com/Komodo/KomodoEdit/issues/2002

**Comment by Naatan** [comment]
This will be fixed in Komodo 11, which is due soon.

**Comment by sfsccn** [comment]
Sounds good, looking forward to v11!
