### ISSUE TITLE
Not uniform font size in Let's Get Started window

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2954]
### Short Summary

1. Check out the font size - not uniform appearance
2) OK and Cancel buttons are cut off - users needs to resize

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo IDE, version 11.0.0-alpha1, build 90564, platform macosx.
Built on Sun Aug 27 23:39:13 2017.
### Additional Information

 
![image](https://user-images.githubusercontent.com/26605593/29787795-131251b6-8be5-11e7-86ef-d3af976e3603.png)

**Comment by cgchoffman** [comment]
I think @Naatan, found this this morning and is fixing it so assigning to him.

**Comment by Naatan** [comment]
You're using a third party Color scheme. My money is on that being the issue here. Try changing back to Default.

**Comment by Naatan** [comment]
https://activestate.slack.com/archives/C03NU4MN5/p1503946625000145
