### ISSUE TITLE
KO11 codeintel prefs missing texts?

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#2958]
Komodo IDE, version 11.0.0-alpha1, build 90546, platform linux-x86_64.
Built on Fri Aug 25 00:23:09 2017.

![screenshot_2017-08-29_07-49-27](https://user-images.githubusercontent.com/350912/29806251-b2fbcbc2-8c8e-11e7-9233-399b373a7810.png)

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/0d9bbda5df1df0927636be72856a1fa33c57ce28
