### ISSUE TITLE
Can't read progress message in project wizard

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#2961]
This is reproduced by creating a new project with Angular as the language and framework.

![image](https://user-images.githubusercontent.com/278649/29837868-7284bc78-8cc7-11e7-8e01-3352d776c13e.png)

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/4152954cabd1fe2f7dd4ccd386809246857244d6
