### ISSUE TITLE
Print debugging needs its own tool

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#2966]
Using it as a snippet adds to much confusion and doesn't at all explain what is expected from the user.

**Comment by cgchoffman** [comment]
My use case doesn't fit the current implementation.  Hopefully it can be incorporated. https://github.com/Komodo/KomodoEdit/issues/3182#issuecomment-333172731

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/d529a10e2087106c7da2e2ed536099592c5d0820#diff-5d257edc11140fd74362dacc9ce4ba25
