### ISSUE TITLE
Symbol browser filter persists when you switch file

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#2970]
### Steps to Reproduce

 - open two python files
 - open the symbol browser widget
 - type some text into the filter field
 - change to the other file

### Expected results

 - filter text should only show for the file it was typed for

### Actual results

 - notice the filter text is still shown

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/f33a381cc3e7fca653549d9fb5ec7130c572515f
