### ISSUE TITLE
PHP Completions show CSS, JavaScript, HTML namespaces

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#2975]
![image](https://user-images.githubusercontent.com/278649/29840888-82c661b8-8cd1-11e7-81f3-63f5206855e6.png)

**Comment by Naatan** [comment]
Implemented a temporary workaround here - https://github.com/Komodo/KomodoIDE/commit/49dc29216c2100d5928ccafb64c75b763f3b7006

@mitchell-as please revert that above commit when you properly fix this.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/codeintel/commit/7954e42216bc11fc1f01eca247d7acd89dd3002e

**Comment by mjainQA** [comment]
Unable to reproduce in 11.0.1 nightly
