### ISSUE TITLE
White text on white background in Commando Shell

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#298]
The output text color is white and if your theme is with light background (e.g. `Chalk_Light`) - it's hard to see the output. Seems like CS just uses white color for the output instead of foreground color in the theme.

**Comment by Naatan** [comment]
Hmm I'm not seeing this. Can you try with a clean profile?

**Comment by Defman21** [comment]
Reproduced on a clean profile with `Tommorow_Light` scheme.
![bug](http://i.imgur.com/6aMszc3.png)

**Comment by Defman21** [comment]
Also I'm on Ubuntu 15.04 with Komodo IDE, version 9.1.0, build 87295, platform linux-x86_64.
Built on Wed May 20 21:59:57 2015.

**Comment by Naatan** [comment]
Ahh sorry, I thought you were talking about Commando itself.
