### ISSUE TITLE
Unable to insert variable/function by clicking on the suggestions

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2985]
### Short Summary

Unable to insert suggested variable/function 

### Steps to Reproduce

1. Create a perl file and start typing 

pr

2. Double click on the suggested function name as shown in the screenshot

### Expected results

I should be able to insert the suggested code

### Actual results

Nothing happens when you click on the function name

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo IDE, version 11.0.0-alpha1, build 90587, platform macosx.
Built on Tue Aug 29 09:32:53 2017.
### Additional Information
![image](https://user-images.githubusercontent.com/26605593/29844345-d29a0324-8cc3-11e7-93b6-0f26802be094.png)

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/cce321e8669e4e684093558401f4483792b25a26
