### ISSUE TITLE
No horizontal scroll bar appears in the editor window

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2986]
### Short Summary

When text is longer than the editor window, horizontal scroll bar is not appearing.

### Steps to Reproduce
1. Open any file in editor
2. Add a really long text as shown in the screenshot
3. Notice there is no horizontal scroll bar

### Expected results
Scroll bar should appear

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo IDE, version 11.0.0-alpha1, build 90587, platform macosx.
Built on Tue Aug 29 09:32:53 2017.
### Additional Information
![image](https://user-images.githubusercontent.com/26605593/29844884-a5155258-8cc5-11e7-98f4-b7ac43d27479.png)

**Comment by Naatan** [comment]
You're on MacOS. It only shows when you're scrolling.

**Comment by mjainQA** [comment]
![scrollbar_issue](https://user-images.githubusercontent.com/26605593/29888977-7ca17902-8d77-11e7-8e15-42d7897f7694.gif)
