### ISSUE TITLE
Code intel pref names are their pref.xml ids

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2989]
### Short Summary

*prefs > code intel*:

`prefs.enable_gotodef` & `prefs.enable_jumpsections` should be *Enable Go To Def* & *Enable Jump Sections* respectively.
![capture](https://user-images.githubusercontent.com/655154/29847665-c4377a9c-8cd1-11e7-867d-e2ac7a0137c5.PNG)

**Comment by Naatan** [comment]
Duplicate of #2958
