### ISSUE TITLE
can't close Commando with sections scope with ESC

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#299]
Komodo IDE, version 9.1.0, build 87333, platform linux-x86_64. Built on Tue May 26 01:40:23 2015.

opened a python file
<ctrl+space> (assigned to Open Commando with the Sections scope)
type something (seems not to matter whether it's found or not)
hit ESC
Commando does not close

**Comment by Naatan** [comment]
Unable to reproduce. Anything in your error log? (Help > Troubleshooting > View Log File).

**Comment by cgchoffman** [comment]
I'm seeing this too:
-Open commando
-select file scope
-type anything
-press escape

Expect: Commando to close immediately

Actual: It seems to just dismiss the found results but keeps the Commando dialog open

Note:  You have to delete all written text then hit escape twice.  Seems to have something to do with the new scope selector.
