### ISSUE TITLE
No completions in HTML after tag closing `>`

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2990]
### Short Summary

Can't get completions for next tag after closing char, `>`.

### Steps to Reproduce

- Open an HTML file
- trigger completion for a tag by typing `<`
- select any completion, `a` for `<a>` for example
- Close the tag, `<a>`
- Type another opening char of a tag, `<`, on the same line

### Expected results

Should get completions again 

### Actual results

There are no completions.

**Comment by Naatan** [comment]
I can't reproduce this (works for me).

**Comment by cgchoffman** [comment]
100% repro for me.  That's html 5 if it matters.

![codeintel](https://user-images.githubusercontent.com/655154/29881251-ed4b5b00-8d5e-11e7-9206-53478889024a.GIF)

**Comment by Naatan** [comment]
Oh I see, it does trigger when I type a letter, but it doesn't trigger just on the opening tag.
