### ISSUE TITLE
HTML5 template tabs stops aren't working

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2991]
### Steps to Reproduce

- Cltr + Shift +N
- select the HTML 5 template

### Expected results

`<|>` indicates where the cursor should be.
```
<!DOCTYPE html>

<html>
<head>
    <title><|>Page Title</title>
</head>

<body>

</body>
</html>
```

### Actual results

You should not see the two `[[%tabstop:...]]` strings.

```
<!DOCTYPE html>

<html>
<head>
    <title>[[%tabstop:Page Title]]</title>
</head>

<body>

[[%tabstop]]

</body>
</html>
```

**Comment by Naatan** [comment]
This is outright not supported at the moment. The bug here is that this template contains them.
