### ISSUE TITLE
Template Files properties dialog should provide dropdown of available Interpolations

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2992]
### Short Summary

See screenshot:
![capture](https://user-images.githubusercontent.com/655154/29848818-dd06fd8a-8cd7-11e7-832e-6c128e70316d.PNG)

### Steps to Reproduce

- Create a new File Template in your toolbox
- In the dialog that appears you should see  the button indicated in the screenshot.

**Comment by Naatan** [comment]
File templates do not support interpolations. In many cases it wouldn't have the context to perform them as the interpolations depend on a current file, and the template IS the current file and isn't necessarily saved to the filesystem at the time of creation.

**Comment by cgchoffman** [comment]
A forum post just reminded me that i never responded to this being closed.  I filed this because it's a regression.  Interpolation was supported in template files: http://docs.komodoide.com/Manual/templates#templates_creating-custom-templates_using-interpolation-shortcuts-in-custom-templates.
This will break users file templates: https://community.komodoide.com/t/file-templates-in-ide-11/3953

**Comment by Naatan** [comment]
Given the feedback received I'll reopen this, pending some research to determine how we can support interpolations for things that simply won't be available at the time of usage (file path and such). Maybe we'll just limit the interpolations to things such as date, username, etc.

**Comment by cdcmicro** [comment]
Arguably, shortcuts %f, %b, %F, %L, %d, and %D were unknowable, possibly incorrect, or just empty for file templates in previous versions.

**Comment by cgchoffman** [comment]
Interpolation dropdown lists in the applicable toolbox property windows are hardcoded so I can just not include interpolation that isn't applicable.  I'm guessing that's why this was never moved into  a XBL binding like so many other dropdown lists in Komodo.
