### ISSUE TITLE
Format on save using Tidy deletes content in HTML <body> tag

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2993]
### Short Summary

Formatter is deleting content from my file.

### Steps to Reproduce

- Use the default HTML file template (Ctrl + Shift + N)
- Add something between the `<body>` tags 
- Turn on "Format on Save" using the Tidy option
![capture](https://user-images.githubusercontent.com/655154/29848909-59eec576-8cd8-11e7-9e8c-cb2dcfacefa5.PNG)
- save file

### Expected results

A formatted file

### Actual results

The content added between the `body` tags is removed

![format](https://user-images.githubusercontent.com/655154/29848938-8f632f8a-8cd8-11e7-929f-5b12fcc82412.GIF)

**Comment by Naatan** [comment]
Huh, that's really strange. Not sure what we can do about this though given we are just handing this off to Tidy.

**Comment by cgchoffman** [comment]
If that's how Tidy works then it should be removed.   We can't tell someone that "that's how Tidy works" when it's deleted their code.

**Comment by Naatan** [comment]
This is a feature of Tidy:

http://api.html-tidy.org/tidy/quickref_5.4.0.html#drop-empty-elements

**Comment by cgchoffman** [comment]
ahhhh, nice find.  So if I had added text to it, it would have left it...confirmed
