### ISSUE TITLE
Project wizard provides poor feedback if SCC is missing

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2998]
### Short Summary

I just tried to clone a repo in the Project Wizard and got `Error occurred: Checkout Failed with code 2 null`.  This apparently means *git* isn't installed :D

### Steps to Reproduce

- Remove git from your path (rename it's install folder) or if it's not installed...just go ahead
- open project wizard, *Project menu > new project*
- doesn't matter what settings are on first page but DO fill them out
- select git as the version control
- Insert a valid git repo
- Click next

### Expected results

Be shown the error that my OS would return if I tried to use a command line tool that doesn't exist
OR
Say "The tool you're trying to use, *git*, isn't installed"

### Actual results

It actually looks like everything worked until i get the null error.  I check and the repo is never checked out.
![capture](https://user-images.githubusercontent.com/655154/29857549-121a3132-8d0e-11e7-9450-09b3c80509f0.PNG)

**Comment by Naatan** [comment]
Duplicate of #2963
