### ISSUE TITLE
codeintel asked to scan X files, then went away

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#2999]
- codeintel asked to scan 20000+ files
- I added one more exclude filter (bower_components)
- clicked rescan
- I expected the dialog to appear again, but it did not
- scan did not start either

Komodo IDE, version 11.0.0-alpha1, build 90546, platform linux-x86_64.
Built on Fri Aug 25 00:23:09 2017.

**Comment by Naatan** [comment]
Any chance all of those 20000+ files were in the bower_components folder?

The scanning prompt only shows again if you have more than 50 files that need to be scanned. If it finds less than 50 files it just goes ahead and scans them right away (you should see the notifications for this though).

**Comment by agroszer** [comment]
Nope, I have a gazillion other files, definitely more than 50.
See notifications? where?

**Comment by agroszer** [comment]
Ahh bottom pane notifications. Just slightly helpful. Don't blink ;-) The very last "Scan Finished" alone isn't very helpful. Like scan of **what** finished?

**Comment by agroszer** [comment]
https://github.com/Komodo/KomodoEdit/issues/3012

**Comment by Naatan** [comment]
Can you reproduce the issue?

**Comment by agroszer** [comment]
no failure since then

**Comment by mjainQA** [comment]
Add test case.
