### ISSUE TITLE
Support XUL CodeIntel

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#3001]
This worked in 10, it's basically html with a different doctype. I imagine there's more languages that work in a similar way. We should set up some basic routing to facilitate this without creating a whole new language each time.

**Comment by mitchell-as** [comment]
Related to #2774

**Comment by Naatan** [comment]
With the caveat that unlike those doctypes this would entail a different language.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/codeintel/commit/0c88b6b62b46f0864e038b158420aec2ffdc42ef
