### ISSUE TITLE
PHP CodeIntel - dollar signs aren't part of the variable name

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#3003]
This leads to issues with completions because searching for `$foo` returns no variables whereas searching for `foo` does but it also returns completions for things that aren't variables.

**Comment by mitchell-as** [comment]
Note: Komodo 10 stores PHP variables without the '$' prefix in its code/symbol browser too, so this is due to the legacy parser. We could manually add the prefix to symbols in the database, but then completions get complicated, as sometimes they'd have to eliminate the prefix and sometimes not (e.g. `$f<|>` -> `$foo` vs. `$foo-><|>` -> `$foo->bar`, not `$foo->$bar`).

**Comment by Naatan** [comment]
In your example the latter is a property, not a variable. Is our codeintel storing them as the same type?

**Comment by mitchell-as** [comment]
I think so. Consider the following test case:

```
            class MyClass {
                var $bar = 1;
                function foo() {
                    echo "this is the function foo";
                }
            }
            $a = new MyClass();
            $a-><|>
```

should give `foo` method and `bar` instance variable (not `$bar`).

**Comment by mitchell-as** [comment]
Also:

```
            class MyClass {
                private $x = 1;
                function foo() {
                    $this-><|>
```

should provide `x`, not `$x`.

**Comment by Naatan** [comment]
In that first one bar is not accessible as a property, it's just a variable. In the second one $x is a bit special I guess. Depending on how its accessed it will or will not have a dollar sign. I guess the differentiator is not the symbol type but rather the way it is accessed.

Seeing as the only bug we currently see from this is the one raised in the first post, maybe we should just figure that one out and leave it at that?

**Comment by tuckdesign** [comment]
In above cases $bar and $x are properties in php and it is correct to have $a->bar and $this->x. But problem is with simple variables. Take this test case:

$x = array();
foreach (<|> as $element) 
should be:
foreach ($x as $element)
but currently it gives:
foreach (x as $element) (https://www.screencast.com/t/j3ItIqbgfN3)

Interesting thing is that both properties (as in examples above, and simple variables) are marked as green 'v' letter.

PS. Using Komodo 11.0

**Comment by tuckdesign** [comment]
Interesting, vars like $GLOBALS, $_POST etc. don't have this problem, they show up correctly.

**Comment by mitchell-as** [comment]
Bumping up priority on this once since we're receiving lots of reports of completions being affected.

**Comment by Naatan** [comment]
Use case: https://community.komodoide.com/t/autocomplete-11-removing-the-on-variables/3931

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/codeintel/commit/a7ca05b3b3c5a28b7960ab27de9160152b64441c and https://github.com/Komodo/codeintel/commit/74912c518ddb1c310a02afd5c5b05fa51de8a915
