### ISSUE TITLE
Code completion suggestions disappear after second character is typed

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#3008]
### Short Summary

There are no code completion suggestions as soon as second character is typed in the script.

### Steps to Reproduce
1. Create a perl script with the following code:

`use strict;
use warnings;

my $activePerl_version = 'ActivePerl-5.26';

my $activePerl_version1 = 'ActivePerl-5.26';`

2. Type $ and notice the suggestions for  $activePerl_version and  $activePerl_version1
3. Type $a and notice there are no suggestions. 
### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo IDE, version 11.0.0-alpha1, build 90592, platform macosx.
Built on Tue Aug 29 23:38:56 2017.
### Additional Information

 
![code_completion](https://user-images.githubusercontent.com/26605593/29892015-e1932752-8d81-11e7-8859-a04d0070967e.gif)

**Comment by Naatan** [comment]
This is the same issue as #2984 (same cause).
