### ISSUE TITLE
Code intel is not picking up installed modules for Python

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3009]
### Short Summary

I installed ActivePython 3.5 with all the machine learning and data science modules.  I open a Python 3 file, confirm I have APy configured in python 3 prefs, type `import num<|>` and I don't get completions for `numpy`.  I didn't test the list exhaustively but at leaset *matplotlib* and *numpy* aren't suggested

**Comment by Naatan** [comment]
Is the folder that contains numpy configured under PYTHONPATH or the additional import pref?

**Comment by cgchoffman** [comment]
I would hope so.  It's part of the Python install.  I shouldn't need to configure that.

**Comment by Naatan** [comment]
I'll use this issue to address numpy not appearing in the list, the bug of Komodo not automatically scanning your default python module dir is logged here - #3017

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/b23f028989db90f554704ccdc36ce868645c3ef3
