### ISSUE TITLE
Facilitate adding/removing bookmarks

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#301]
Preferably one should be able to use something like ctrl+mouseclick on the margin.

**Comment by k-barton** [comment]
This is already in `<view>.onMarginClick`, but there is a bug that prevents it from working.
In `ko.views.manager.currentView.__proto__.__proto__.onMarginClick`, there should be `this.scimoz` rather than `this.scintilla.scimoz`: 
     
    function onMarginClick(modifiers, position, margin) {
        <...>
        else if (margin == s.MARGIN_SYMBOLS && this._mouseButton == 0) { // toggle bookmark
            var markerState = this.scimoz.markerGet(lineClicked); 
            if (markerState & (1 << ko.markers.MARKNUM_BOOKMARK)) {
                this.scimoz.markerDelete(lineClicked, ko.markers.MARKNUM_BOOKMARK);
            } else { 
                this.scimoz.markerAdd(lineClicked, ko.markers.MARKNUM_BOOKMARK);
            } 
        }
        <...>
    }

**Comment by mitchell-as** [comment]
This seems to work now via middle-click. Middle-clicking the bookmark margin toggles bookmarks.
