### ISSUE TITLE
Code Intel deletes my text in some case

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3011]
### Steps to Reproduce
- in a python file type out `len` and the following `(`
- This should give you completions for everything
- keep hitting `a` or whatever else until all suggestions are gone and only the tooltip for `len` is left
- hit tab

### Expected results

I expect my cursor to jump over the `)` soft char so it's at the end of the line
`len(aa)<|>`

### Actual results

`aa` gets deleted and cursor is moved to where I want it. Sometimes a tab is entered.

![completions](https://user-images.githubusercontent.com/655154/29906748-da96ce14-8dcb-11e7-9e05-16da89c0dd07.GIF)

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/7dd3959f42139ab90ed54f352232f043385cbbdc
