### ISSUE TITLE
koIFileEx.updateStatsAsync exception

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#3014]
Komodo IDE, version 11.0.0-alpha1, build 90546, platform linux-x86_64.
Built on Fri Aug 25 00:23:09 2017.

Don't know exactly what triggered this, was mucking with a repro of https://github.com/Komodo/KomodoEdit/issues/3013

-- EXCEPTION START --
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIFileEx.updateStatsAsync]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://komodo/content/views.js :: _view_checkDiskFiles :: line 2746"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIFileEx.updateStatsAsync]'
+ result (number) 2147500037
+ name (string) 'NS_ERROR_FAILURE'
+ filename (string) 'chrome://komodo/content/views.js'
+ lineNumber (number) 2746
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) '_view_checkDiskFiles@chrome://komodo/content/views.js:2746:16
'
+ location (object) JS frame :: chrome://komodo/content/views.js :: _view_checkDiskFiles :: line 2746
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/views.js'
| + name (string) '_view_checkDiskFiles'
| + lineNumber (number) 2746
| + columnNumber (number) 16
| + sourceLine (string) ''
| + caller (object) native frame :: <unknown filename> :: <TOP_LEVEL> :: line 0
| + formattedStack (string) '_view_checkDiskFiles@chrome://komodo/content/views.js:2746:16
'
| + stack
    _view_checkDiskFiles@chrome://komodo/content/views.js:2746:16
-- EXCEPTION END --

**Comment by cgchoffman** [comment]
Can you provide your entire log file please?

**Comment by cgchoffman** [comment]
@agroszer, i'm going to close this for now. If you have a repro and an issue that it's causing then please reopen.

**Comment by cgchoffman** [comment]
Oh and supply those two pieces of information :D

**Comment by agroszer** [comment]
log is gone... maybe next time
