### ISSUE TITLE
JavaScript/Node completions show Anonymous functions

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#3019]
```
require(<|>)

function()
{
    
};
```

Shows anonymous in the completions

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/codeintel/commit/ea4a6f6a7f3984ff2a98089f45b5846dd875852f

**Comment by mjainQA** [comment]
verified in Komodo IDE, version 11.0.1, build 90755, platform macosx.
Built on Tue Oct 10 09:26:02 2017.
