### ISSUE TITLE
Update PHPUnit Compatibility

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#302]
Komodo does not work properly with PHPUnit 4.x

**Comment by girvo** [comment]
:+1: really important feature I'd love to see. Is there any API documentation on the test harness stuff around?

**Comment by Naatan** [comment]
Relevant: https://github.com/darnellefunk/komodo-phpunit-harness 

Thanks for sharing @darnellefunk!

**Comment by Defman21** [comment]
Duplicate of #519, isn't it?

**Comment by Naatan** [comment]
Technically the other way around, since this one is older. Thanks @Defman21.

**Comment by Naatan** [comment]
Another one: https://github.com/mike-shmatov/KomodoPHPUnitDriver

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoIDE/commit/8e3f0321a1cf7925c742b3023332b41fc18a8e39

Note: Users need to ensure 'phpunit.phar' is in Komodo's PHP include path. (This may be obvious, but I know next to nothing about PHP.)

**Comment by Defman21** [comment]
@mitchell-as could you say where I can set the include path for Komodo's PHP language? I have phpunit.phar on my $PATH but seems like it doesn't work or I'm using too new version (5.3.2)

**Comment by mitchell-as** [comment]
PHPUnit 4+ requires PHP 5.6.0 or greater it looks like. So it seems you're using too "old" of a version :(

**Comment by Defman21** [comment]
Nah, I'm using PHP 7.0.4 and PHPUnit 5.3.2, everything is working! Thanks @mitchell-as :+1:
