### ISSUE TITLE
Unexpected error installing license key

### ISSUE THREAD

**Issue by dch** [Komodo/KomodoEdit#3025]
### Short Summary

Komodo IDE 11 dies on startup. `$HOME/.ActiveState` and `$HOME/.komodoide` are both created, and blank.

Tried it as root, same issue. I can't try this on a "normal linux" at present, maybe next week I will have a chance to confirm.

- Komodo-IDE-11.0.0-90546-linux-x86_64
- FreeBSD 12.0-CURRENT amd64

NB I've been using 10.2 and prior with FreeBSD's linux emulation. It's been super solid and very usable. I'm just back from holiday so this is the first 11.x release I'm trying. I immediately get this:

### Steps to Reproduce

Start komodo with an empty profile & home dir.

### Expected results

starts up, and maybe asks me for a licence.

### Actual results

```
Unexpected error installing license key.

cmd: "/usr/local/share/komodo-ide/lib/support/instlic"
stdout:
stderr:
/bin/sh: /usr/local/share/komodo-ide/lib/support/instlic: Permission denied
```

and then quits. no editor window ever turns up.

### Platform Information

- Komodo-IDE-11.0.0-alpha1-90546-linux-x86_64.tar.gz
- Komodo IDE, version 11.0.0-alpha1, build 90546. Built on Fri Aug 25 00:23:09 2017.
- FreeBSD !2.0-CURRENT amd64 using linux emulation

### Additional Information

startup debug info:

```
dch@wintermute /t/b> komodo -vvv
komodo: debug: Komodo information:
komodo: debug:   Version: Komodo IDE 11.0.0 Alpha 1 nightly (Build 90546) linux-x86_64
komodo: debug:   OS type: Linux release 2.6.32 on x86_64 (FreeBSD 12.0-CURRENT #5 r322803+f967822d99b6(drm-next): Thu Aug )
komodo: debug: Komodo startup options:
komodo: debug: 	nFiles: 0
komodo: debug: mutex name: '/home/dch/.komodoide/11.0/mutex.lock'
komodo: debug: acquired mutex: fd=4
komodo: debug: running lock name: '/home/dch/.komodoide/11.0/running.lock'
komodo: debug: No current running Komodo - Ok: fd=5
komodo: debug: commandments file name: '/home/dch/.komodoide/11.0/commandments.fifo'
komodo: debug: first commandments file name: '/home/dch/.komodoide/11.0/first-commandments.txt'
komodo: debug: saving startup environment...
komodo: debug: startup env name: '/home/dch/.komodoide/11.0/startup-env.tmp'
komodo: debug: writing out startup environment
komodo: debug: setting up environment for XRE launch...
komodo: debug: setting MOZ_NO_REMOTE=1
komodo: debug: setting PYTHONHOME=/usr/local/share/komodo-ide/lib/mozilla/../python
komodo: debug: setting _KOMODO_VERUSERDATADIR=/home/dch/.komodoide/11.0/
komodo: debug: setting KOMODO_VERBOSE=1
komodo: debug: setting XRE_PROFILE_PATH=/home/dch/.komodoide/11.0/XRE
komodo: debug: setting _XRE_USERAPPDATADIR=/home/dch/.komodoide/11.0/XRE
komodo: debug: startup argv for XRE:
komodo: debug: 	argv[0] = '/usr/local/share/komodo-ide/bin/../lib/mozilla/komodo'
sh: /dev/null: Permission denied
sh: /dev/null: Permission denied
sh: /dev/null: Permission denied
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
[2017-08-31 21:34:05,152] [INFO] Startup: Welcome to Komodo IDE 11.0.0-alpha1 build 90546 (platform linux-x86_64, running on Linux 2.6.32 version FreeBSD 12.0-CURRENT #5 r322803+f967822d99b6(drm-next): Thu Aug )
[2017-08-31 21:34:05,153] [INFO] Startup: /usr/local/bin/python built on Fri Aug 25 00:23:09 2017
[2017-08-31 21:34:05,213] [INFO] koInitService: Setting LC_CTYPE to utf-8
dch@wintermute /t/b> [2017-08-31 21:34:05,520] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
```

**Comment by Naatan** [comment]
We do not support BSD, as such I will have to close this issue. I suggest instead you post about this on the forums.

Note that despite is not supporting BSD this does not mean it won't work. It just means we do not provide support for it nor make any promises about whether or not Komodo will run (properly).

All that said - have you tried ensuring that Komodo is installed to a directory that your user has full access to?

**Comment by dch** [comment]
yep - I've been running 10.x happily on a couple of systems for several months, so this is only on the beta. I rolled back to 10.2 & no issues, and forward again -> problems. I'll re-try this on linux for comparison.

**Comment by Naatan** [comment]
10.3 has made no changes to the license or installer, so I'd be surprised if it's something we introduced there. Looking at the log it just looks like a permission issue of some sort, although I'm not sure why it's accessing /dev/null, possibly some Mozilla internal.
