### ISSUE TITLE
ko.utils.restart cause komodo to shutdown improperly

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3027]
### Short Summary

I've noticed with some of the trouble shooting options reset aspects of Komodo and now i'm getting it 100% of the time when restarting after enabling or disabling code intel prefs.

I THINK what is going on is that in the cases where Komodo retarts then tells you is shutdown improperly and asks you to "recover" the pref that gets removed on shutdown isn't being remove because the shutdown happens while the prefs are being modified...?  I'm not sure

In the case of the code intel change i added a setTimeout and it now works

```
    var msg = "Code Intel preferences changes require Komodo to restart.  Restart now?";
    var opts = {
        yes: "Yes",
        no: "No",
    };
    if(require("ko/dialogs").confirm(msg,opts))
    {
        require("ko/windows").getMain().setTimeout(()=>{legacy.utils.restart(true);},200);  //This timeout fixes it
    }
    return true;
```

@Naatan, assigning to you so we can discuss what this might be, tomorrow.

**Comment by cgchoffman** [comment]
Here is the commit for the code intel change with the timeout.

**Comment by Naatan** [comment]
This isn't the fault of ko.utils.restart, it's the place you're calling it in. You're calling it while prefs are still being written, which is what is causes the problem.

The proper solution would be an event or otherwise a timeout, which is what you used. So closing this :)

**Comment by cgchoffman** [comment]
I opened this to resolve other places this is called and it bungs up so I think we should keep it open.

**Comment by Naatan** [comment]
Where else have you reproduced this issue?

**Comment by cgchoffman** [comment]
> I've noticed with some of the trouble shooting options reset aspects of Komodo 

Specifically when I reset file preferences a couple of days ago, unfortunately i wasn't able to repro that 100%. 

I am ok with closing if there is nothing to be done but it sounded like you hadn't seen my other repro (reset file prefs) and wanted to make sure you had considered that before closing.

**Comment by Naatan** [comment]
Ultimately this is behaviour that should be controlled by the invoker. This code itself cannot do that job for you (or should not). If you can reproduce this elsewhere please log a bug for it.

**Comment by cgchoffman** [comment]
Ok sounds good.
