### ISSUE TITLE
weird button in Command Properties window

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#3028]
Komodo IDE, version 11.0.0-alpha1, build 90612, platform linux-x86_64.
Built on Thu Aug 31 09:16:06 2017.

right to Help

![screenshot_2017-09-01_10-24-22](https://user-images.githubusercontent.com/350912/29961408-dc69e4f8-8eff-11e7-9fbd-c0b298fef479.png)

**Comment by Naatan** [comment]
Again, same issue :)
