### ISSUE TITLE
Project Prefs > Syntax Checking has wrong current Python3 instance

### ISSUE THREAD

**Issue by hobbsd** [Komodo/KomodoEdit#303]
My project uses a virtualenv, and the default Python interpreter is set to use it, but under Syntax Checking (in the message that says it can't locate pylint/pyflakes/pep8) it says that Komodo thinks the current Python3 instance is the system installation.

Komodo Edit, version 9.0.1, build 15745, platform win32-x86.
Built on Mon Apr 20 19:05:56 2015.

**Comment by Naatan** [comment]
Is your file language set to Python or Python3?

**Comment by hobbsd** [comment]
It's set to Python3.

**Comment by Naatan** [comment]
Try setting it to Python.

**Comment by hobbsd** [comment]
I see that does make things *look* normal under Syntax Checking. But it's a Python3 project I'm working on, so that doesn't work.

**Comment by hobbsd** [comment]
Under Project Prefs > Syntax Checking, shouldn't the "current Python3 instance" be the default Python3 interpreter for the project?

**Comment by Naatan** [comment]
For me this appears to be properly using the interpreter that I defined. Where do you see that it is using the wrong interpreter?

re:
 > but under Syntax Checking (in the message that says it can't locate pylint/pyflakes/pep8) it says that Komodo thinks the current Python3 instance is the system installation.

**Comment by hobbsd** [comment]
I have a virtualenv Python3 configured, but in Project Prefs > Syntax Checking:

![screenshot from 2015-06-30 18 18 29](https://cloud.githubusercontent.com/assets/1676348/8443778/a041e3be-1f57-11e5-9c84-d7b4bd7b05ac.png)

**Comment by Naatan** [comment]
Another user with the issue: http://forum.komodoide.com/t/fail-to-detect-pyflakes-for-python3/1751/6

**Comment by Naatan** [comment]
We'll track the pyflakes issue in #287, thanks @hobbsd!
