### ISSUE TITLE
NodeJS should support import directories

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#3037]
NodeJS does not support import directories in 11.0.0, this should be addressed so that devs can configure their Node lib directory (the one that's shipped with node).

**Comment by Naatan** [comment]
@mitchell-as can you prioritise this? We may want to include it in 11.0 depending on the complexity of the fix.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/codeintel/commit/129a8df7f4470f3fa64557e43b10ba18b547afd5

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/codeintel/commit/faa41de52f07d881a2332db60a8e413b079c11e7

It turns out we have a NodeJS stdlib, so there's no need for NodeJS import directories.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/codeintel/commit/129a8df7f4470f3fa64557e43b10ba18b547afd5 and https://github.com/Komodo/codeintel/commit/ed77444ab44663ab1ee293cb2708657f6bc203c8

**Comment by mitchell-as** [comment]
Note: deleted all references to previous commits. Going to start over.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/codeintel/commit/129a8df7f4470f3fa64557e43b10ba18b547afd5, https://github.com/Komodo/codeintel/commit/ed77444ab44663ab1ee293cb2708657f6bc203c8, and https://github.com/Komodo/codeintel/commit/8e23088cee8751572e51ded511c88c9b67db4c0c
