### ISSUE TITLE
Getting code completion suggestions without typing anything

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#3040]
### Short Summary
Code completion suggestions are presented when entered 'space'.

### Steps to Reproduce
1. Use the following code and save as perl script.
```
my $activePerl_version = "ActivePerl-$version";
my $os = $^O;
my $activePerl_location = "/usr/local/$activePerl_version/bin";

switch ($os) {
	case "darwin" 
```
2. type case "darwin" and press 'space bar'
3. Notice the suggestions

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo IDE, version 11.0.0, build 90651, platform win32-x86.
Built on Fri Sep 01 21:08:06 2017.
### Additional Information
![image](https://user-images.githubusercontent.com/26605593/30077340-67242c06-9230-11e7-8777-7103f56f3796.png)

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/d2428cb0eadd0c21820dd5ca475850a68947453e
