### ISSUE TITLE
Remove *Projects > New From Temp > Create Komodo Ext*

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3043]
**Update**: *Remove the menu option to use this in favour of Toolbox > Folder Templates > Komodo Addon Boilerplate*

### Steps to Reproduce

- Project menu > New from template > Create Komodo Extension
- Setup the project in some temp folder
- Run the `Build` userscript in the toolbox under your project
![capture](https://user-images.githubusercontent.com/655154/30088539-e0968388-925b-11e7-847e-fb65d3b64caa.PNG)

### Expected results

The addon to build

### Actual results

Get the following output in the Command Output pane:
`The filename, directory name, or volume label syntax is incorrect.`

**Comment by cgchoffman** [comment]
We may want to fix this in the project of removing this workflow and adding it to the new New Project workflow.

**Comment by Naatan** [comment]
@cgchoffman can you dig in to this as a priority? This isn't part of Komodo itself, it's sourced from here: https://github.com/Komodo/Addon-Bootstrapper

**Comment by cgchoffman** [comment]
@Naatan the *Project menu > New from template > Create Komodo Extension* stuff is not from  https://github.com/Komodo/Addon-Bootstrapper.

It's https://github.com/Komodo/KomodoIDE/tree/master/src/modules/koextgen

**Comment by cgchoffman** [comment]
Oh you want this in the release?  This has likely been broken for a while.  I don't think this needs to be in 11.

**Comment by Naatan** [comment]
Oh sorry, I confused this with the folder template. Let's remove this menuitem in favour of the new folder template.

**Comment by cgchoffman** [comment]
@Naatan Ok, gotcha.
