### ISSUE TITLE
Node module completions have a trailing slash

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#3044]
When typing `require("moduleName")` and selecting a result the result is inserted as `require("moduleName/")`, I cannot think of many situations in which this would be desirable.

**Comment by mitchell-as** [comment]
This should only happen if the module is part of a directory. (e.g. a "node_modules/foo/bar.js" will give a "foo/" completion, followed by "bar".) What case are you running into?

**Comment by Naatan** [comment]
The test sample you shared yesterday. It might be in a directory but it still wouldn't require a slash at the end. I think the logic there ought to be "if the directory has sub-directories", but even then I'm not convinced on this being desirable. I'd favour devs manually inserting this character as it's not common in NodeJS (from my experience) to access modules in subdirectories.

**Comment by mitchell-as** [comment]
I don't understand. If you have the structure "node_modules/foo/bar.js", `require('foo')` would not return anything. It's not a valid module, right? The completion `foo/` gives a visual indication that `foo` alone is not a valid module, but there's more to it.

**Comment by Naatan** [comment]
In most cases the structure is `node_modules/foo/index.js` and the way you require it is with `require("foo")`, you don't type `require("foo/index")`.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/codeintel/commit/db0913f107d119aab14528f9ee41b36206af4632

**Comment by mjainQA** [comment]
Getting a trailing slash in Komodo IDE, version 11.0.1, build 90755, platform macosx.
Built on Tue Oct 10 09:26:02 2017.


![image.png](https://zube.io/files/komodo/9fd6426a8f4697e1dd7a8796389b3feb.png)

**Comment by mitchell-as** [comment]
As mentioned in slack, your test case producing a `/` was expected behavior. If you create a valid module, then the slash will go away.
