### ISSUE TITLE
CodeIntel prefs prompt for restart on all pref changes

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#3045]
It should only prompt for a restart when toggling features, not when changing other prefs.

**Comment by cgchoffman** [comment]
I'm not able to reproduce this.  Are you?  I suspect this is that issue where prefs will think you changed a pref you didn't change.  It's a long standing issue.  For example, I just opened prefs, did nothing, closed and the colour scheme reloaded for no reason.  I've also had it say "you can't set `blah` as a ruby interpreter" when I didn't even have that pref screen open.

**Comment by Naatan** [comment]
Hmm seems you're right. Just loading the codeintel screen seems to reproduce this. But it's consistent, any time I open the codeintel pref screen this happens. So at the very least we have a consistent repro for that bug, if that is what this is.

**Comment by cgchoffman** [comment]
Ahh gotcha, I can repro now.  Thanks.

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/cc17f5c45e78cac3266846de4bf82b32692d4018

**Comment by mjainQA** [comment]
Verified in 11.0.1

Test case: http://testrail.activestate.com/testrail/index.php?/cases/view/1412
