### ISSUE TITLE
Large clouds in Places

### ISSUE THREAD

**Issue by neurobashing** [Komodo/KomodoEdit#3046]
### Short Summary
Whoa, those cloud icons are large.

https://community.komodoide.com/t/feedback-on-v11-icons-in-places/3787/8?u=neurobashing

### Steps to Reproduce
Open 'places'

### Expected results
Icons that are not as large.

### Actual results
Extremely large icons

### Platform Information
Komodo IDE, version 11.0.0, build 90651, platform macosx.
Built on Mon Sep 4 23:37:49 2017.

### Additional Information
Orb is a good band https://en.wikipedia.org/wiki/Little_Fluffy_Clouds

**Comment by Naatan** [comment]
> Orb is a good band https://en.wikipedia.org/wiki/Little_Fluffy_Clouds

Marvellous.

**Comment by cgchoffman** [comment]
Looks like it's happening in the publisghin dialog as well.
<img width="519" alt="screen shot 2017-10-05 at 3 55 06 pm" src="https://user-images.githubusercontent.com/655154/31256179-bc122d7c-a9e5-11e7-94ca-f561997a5cd7.png">

**Comment by cgchoffman** [comment]
ref: https://github.com/Komodo/KomodoEdit/commit/7345614462f5e0fada86b58d5ab3a768c78b7c37

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/13e61f8c93a7945c3aa582c2d323155ea29d8be0
