### ISSUE TITLE
Alert dialog is gradually getting wider

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3049]
### Short Summary

I didn't notice for a while (obviously because i've been on this addon thing all day and JUST noticed that the restart dialog was getting wider) but the dialog is gradually getting wider and wider everytime it opens.

Previously (might even be bigger in this one but i didn't notice):
![capture](https://user-images.githubusercontent.com/655154/30135221-e3ed3f32-930e-11e7-909c-cf5f2be50cc0.PNG)

Now:
![capture](https://user-images.githubusercontent.com/655154/30135196-d18e8e36-930e-11e7-85e5-60863b80faf1.PNG)

### Steps to Reproduce

- install and remove an addon a bunch of time in a row to trigger the restart dialog

### Expected results

Dialog never to get bigger

### Actual results

Gradually gets wider.  You maye need to use DOM inspector and Element inspector then the BOX view or what ever it's called to watch the dialog width get wider.

**Comment by Naatan** [comment]
Can you still repro this on the latest nightly?

**Comment by cgchoffman** [comment]
My alert dialogs are still large.  I can't tell if they are growing.

**Comment by Naatan** [comment]
Please start in safe-mode and see if you can repro.

**Comment by shutack** [comment]
I am having this problem on Windows win32-x86 using Komodo Edit 11.0.2 build 18122

**Comment by Naatan** [comment]
Please open a new bug and include what dialog exactly is causing this.

**Comment by shutack** [comment]
I'll have to figure out where to enter the bug report. I've never done that.
The dialog message is: The file xxx is read-only. Would you like to save your changes under a different name or force the save?
The dialog box currently spans across 2 monitors. 
Thanks for your help.George

Sent from Yahoo Mail on Android 
 
  On Thu, Jan 18, 2018 at 10:55 AM, Nathan Rijksen<notifications@github.com> wrote:   
Please open a new bug and include what dialog exactly is causing this.

**Comment by Naatan** [comment]
Just hit "New Issue" at the top right of this page :) 

Also please avoid responding via email, github is really bad at parsing email replies.
