### ISSUE TITLE
No symbols are shown with legacy parser

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#3052]
### Short Summary

No symbols are shown when legacy parser is selected in code browser.

### Steps to Reproduce
1. Open any file with code methods and variables in it.
2. Click on cog button on under symbol browser
3. Select Use legacy parser
 

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
RC2:

Komodo IDE, version 11.0.0, build 90653, platform macosx.
Built on Tue Sep 5 16:05:14 2017.
### Additional Information
![image](https://user-images.githubusercontent.com/26605593/30137868-3fb9039a-931a-11e7-8ef1-d5c5638d3d51.png)

**Comment by Naatan** [comment]
To be clear, symbols show fine. The issue here is that they aren't showing on one particular syntax:

```
function hello(name) {

}
```

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoIDE/commit/6a52d295ac6fa65b3c10c803ffc4697d1e0152cd.

Note that not all languages have legacy symbol browsers. Only a select few. In this case, it needs to be JavaScript, not NodeJS.
