### ISSUE TITLE
Breadcrumb not updated after rename

### ISSUE THREAD

**Issue by rovf** [Komodo/KomodoEdit#3054]
### Short Summary

After renaming a file in Komodo Edit, the breadcrumb still shows the old file name.

### Steps to Reproduce

Open a file. Do a context click on the tab with the filename. Choose "Rename" and give the file a new name. 

### Expected results

The breadcrumb just below the tab, showing the path to the file, should also show the new name.

### Actual results

While the tab itself shows the new name, the breadcrumb still shows the old name.

### Platform Information

*Komodo Edit?* 
*10.2.3* 
*Windows 7 (64bit)* 

### Additional Information

(I can supply a screenshot by email, if needed. Attaching it using this web interface did not work).

**Comment by mitchell-as** [comment]
Hi, this should be fixed in Komodo Edit 11.

**Comment by rovf** [comment]
When will it be available?

**Comment by mitchell-as** [comment]
Soon. Thanks for your patience.

**Comment by mjainQA** [comment]
Verified in Komodo 11. No test case needed.
