### ISSUE TITLE
Debugging System Preferences

### ISSUE THREAD

**Issue by bellbrad13** [Komodo/KomodoEdit#3055]
### Short Summary
When I want to run a program with the debugger, in both the Windows and Mac version (10.2.3) when I click "Go" to start the debugger, it does not populate the "Script" with the program that currently has focus.

### Steps to Reproduce
- I run a program in the debugger called, "Zone_Add.py". The program completes successfully and the debugger has finished running.
- I switch to a different open tab in Komodo, "Zone_Delete.py" and click "Go" to run that script. The Debugger window fills in with "Zone_Add.py" (the last program run). If I fail to notice this or correct it, then it will re-run the previous script, not the one that currently has focus in the Komodo application.

### Expected results
Following the above example, it should run the program that currently has focus in the main window, so "Zone_Delete.py" in this example.

### Actual results
Following the above example, it runs "Zone_Add.py" which is the latest version shown.

### Platform Information
Komodo IDE, version 10.2.3, build 89902, platform macosx.
Built on Tue Jul 11 12:32:32 2017.

Screenshots are from MacOS Sierra 10.12.6 on an MacBookPro.  However, I have observed the same behavior in Windows 7.

### Additional Information
So the obvious workaround is just to remember to select the right file in the Debugger.  I suspect the issue may be more with my profile/preferences (which is the same between the systems) than any program issue, especially if this is not a common issue.

So screenshots are:
Zone_Add -> Initial state, Zone_Add.py has focus.
Zone_Add_Complete -> Debugger has run for Zone_Add
Zone_Delete_Has_Focus -> Switched to the Zone_Delete.py file
Zone_Delete_Start_Debug -> Clicked the "Go" button at the bottom of the screen, 'Zone_Add' is still shown as the selected file.
Zone_Delete_Run -> End state, Zone_Delete has run after manually selecting it from the dialog box.

<img width="1225" alt="zone_add_complete" src="https://user-images.githubusercontent.com/13790686/30170970-d2892914-93ad-11e7-810b-39bd710ecb40.png">
<img width="1158" alt="zone_add" src="https://user-images.githubusercontent.com/13790686/30170972-d29e52da-93ad-11e7-8eff-937cc8e63398.png">
<img width="1242" alt="zone_delete_has_focus" src="https://user-images.githubusercontent.com/13790686/30170973-d29f33f8-93ad-11e7-8873-3f8f16b2c3cd.png">
<img width="1211" alt="zone_delete_run" src="https://user-images.githubusercontent.com/13790686/30170971-d29dfc86-93ad-11e7-9e70-61bb7dd6b416.png">
<img width="1207" alt="zone_delete_start_debug" src="https://user-images.githubusercontent.com/13790686/30170974-d2c51aaa-93ad-11e7-9ea2-1cc9dfde6eda.png">

**Comment by Naatan** [comment]
When you say you click "Go" to run that script, can you specify exactly what method you use? A button, menu entry? Which one?

**Comment by bellbrad13** [comment]
The triangle in the bottom left corner underneath the word "Watch" on any of those screens is what I usually push.  The "Start or Continue Debugging" on the top of the screen exhibits the same behavior.  I have not tested this using either the menu or the keyboard shortcuts.

**Comment by Naatan** [comment]
Ok, there's your problem. That tab is dedicated to the debug session that started it. So it is by design that it shows the input you used for that session. To start a new session you use the debug button at the top of your screen or use the menu.

**Comment by bellbrad13** [comment]
Okay, I suspected it might have been an option I was using in preferences or something I was doing, since this would be a headache for a lot of people.  Thanks!
