### ISSUE TITLE
please put back the full file path to the app title

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#3064]
Komodo IDE, version 11.0.0, build 90651, platform linux-x86_64.
Built on Tue Sep 5 00:23:24 2017.

I know that this is just a feature of trials, but drives me NUTS

![screenshot_2017-09-08_11-37-05](https://user-images.githubusercontent.com/350912/30205760-1a038bfe-948a-11e7-9e65-b92aa0b816da.png)

**Comment by Naatan** [comment]
You can get back the old titlebar via Preferences > Appearance > Platform Integration > Use native window border.

The new titlebar will not be showing the path, this is by design and is unlikely to change.

**Comment by agroszer** [comment]
Use native window border: that's on... not having the full path somewhere is painful, our and other (zopeish) projects will have the very same named files in various folders. e.g. __init__.py, etc

**Comment by Naatan** [comment]
You should still be able to tell the path from the breadcrumbs. Any reason why you can't reference that?

**Comment by agroszer** [comment]
yuck... my eyes...

**Comment by Naatan** [comment]
Are you saying you didn't notice or are you saying the breadcrumbs are ugly?

**Comment by agroszer** [comment]
missed the breadcrumbs...
