### ISSUE TITLE
Package manager prefs are being loaded 4 times

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3065]
### Steps to Reproduce

-  prefs > Languages > NOdejs
- Look at the tools and package manager executable fields

### Expected results

There should be one entry for each, Yarn, NPM, Gulp, Grunt

### Actual results

There are 4 for each

### Platform Information

Windows

**Comment by Naatan** [comment]
Guessing this is a multi-window bug.

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/ecce074c042267c1764175ee0374bd0efb5bab32
