### ISSUE TITLE
PHP ... operator used in variadic function definitions is not recognized as valid syntax.

### ISSUE THREAD

**Issue by JBHUTT09** [Komodo/KomodoEdit#3067]
PHP 5.6 added the ['...' operator](http://php.net/manual/en/migration56.new-features.php#migration56.new-features.variadics) to be used when defining variadic functions. 

The code:
```php
<?php
    function myFunction(...$args) {
        print_r($args);
    }
    myFunction('one','two','three','and so on');
?>
```
Outputs:
```
Array(
    [0]=>one,
    [1]=>two,
    [2]=>three,
    [3]=>and so on
)
```
This works (and has worked) since PHP 5.6 was released in 2014. But Komodo Edit does not recognize the syntax as being valid.

![screen shot 2017-09-11 at 1 06 49 pm](https://user-images.githubusercontent.com/6395044/30287187-2c3962ac-96f2-11e7-8c9d-8db58b9e1c3f.png)

Komodo Edit ver 10.2.2
OS X El Capitan ver 10.11.2

**Comment by mitchell-as** [comment]
Hi, is the PHP interpreter Komodo is configured to use PHP >= 5.6? Edit > Preferences > Languages > PHP > Default PHP Interpreter.

Komodo uses PHP's built-in syntax checking.

**Comment by JBHUTT09** [comment]
I believe so. I've never touched any of these settings. Here's what I see:

![screen shot 2017-09-11 at 1 30 13 pm](https://user-images.githubusercontent.com/6395044/30288090-8780e1f0-96f5-11e7-8d44-6d68a91a441b.png)

"Find on Path" is what was selected.

**Comment by mitchell-as** [comment]
Okay, and what do you get when you run `/usr/bin/php -v` in the terminal?

**Comment by JBHUTT09** [comment]
`PHP 5.5.30 (cli) (built: Oct 23 2015 17:21:45) `
...
Damn, I feel so stupid. Thanks for the help. Sorry I wasted your time.

**Comment by mitchell-as** [comment]
It wasn't a waste. I'm glad you figured it out!
