### ISSUE TITLE
no JSDOC completions in javascript comments

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3069]
### Short Summary

There are no JSDoc completions in comments any more.  

### Steps to Reproduce

- open javascript file
- creatae comment block
```
/**
 *
 */
```
- in the middle line type a `@`

### Expected results

Completions for JSDoc, eg. `param`, `typedef`, `function`, etc.

### Actual results

Nothing

**Comment by Naatan** [comment]
There never were, this is a userscript (made by yours truly back when I was just a user ;)).

https://community.komodoide.com/packages/userscripts/phpdoc-and-jsdoc/

That said, we should probably support this.

**Comment by cgchoffman** [comment]
There were.  I just started Komodo 10 with a fresh profile and I get JSDoc completions.

**Comment by Naatan** [comment]
Oh sorry, I thought you were talking about the params being auto-filled. You're talking just about the param type completions.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoIDE/commit/cebfddc8e104fb15071345751960b70dd024cf93

**Comment by cgchoffman** [comment]
Awesome!
