### ISSUE TITLE
XPath predicate support

### ISSUE THREAD

**Issue by ssimo3lsuhsc** [Komodo/KomodoEdit#3070]
### Short Summary

According to your documentation, in the DOM Viewer, "The Filter box uses the XPath syntax supported in Python's ElementTree." However, that can be true ONLY if the Filter box supports XPath predicates.

### Steps to Reproduce

1. Launch Komodo IDE.
2. Select (three bars) >> File >> New >> File from Template (or press Ctrl + Shift + N).
3. Select HTML5 from the Common section.
4. Select the entire window contents.
5. Paste over them with this:
```
<!DOCTYPE html>

<html>
<head>
    <title>Page Title</title>
</head>

<body>
<p id="GoToHere">Go to here</p>


</body>
</html>
```
6. Select (three bars = "menu" symbol) > View > Toolbars and Sidebars > DOM.

7. In the Filter box that opens up, type ".//p". The number of elements shown in the DOM should decrease.

8. Now continue typing in the Filter box: "[@id='GoToHere']"

### Expected results
There would be elements in the DOM Tree. The expression ".//p[@id='GoToHere']" means as follows:

"." = Start from the root node of the document
"//" = Search among all the descendants of this node.
"p" = Return nodes with the tag name "p".
"[...]" = Predicate. The predicate makes an assertion that is used to filter the nodes further. Your statement above, "The Filter box uses the XPath syntax supported in Python's ElementTree" has a link under the text "ElementTree" that points to a document from TEN YEARS AGO. ElementTree supported predicates even then. But Komodo fails to parse the predicate. This predicate would be parsed by breaking it down as follows:
"@" = Tells the XPath parser that the following characters represent an attribute and not a descendant element node.
"id" = The name of the attribute we want to search for is "id".
"=" = Returns nodes where the "id" attribute is equal to some following string.
"'GoToHere'" = Should return nodes whose name is "p" and whose "id" attribute is the string "GoToHere."

### Actual results

There are no DOM elements shown.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.2.3
*Operating System (and version)?* Windows 7 Enterprise

### Additional Information

Screenshot of result:
![komodo window](https://user-images.githubusercontent.com/20207672/30441854-3b196b96-9940-11e7-9b60-b02d980de435.PNG) The DOM viewer is on the right, under the Filter search box.

I have been trying to change the documentation myself. However, that results in the following error when I try to log in via GitHub:
Authentication failed
Insufficient data from authentication provider, name not provided or empty

![Documentation Login Error Image Here](https://user-images.githubusercontent.com/20207672/30440433-20fb5ec6-993c-11e7-9995-52aeca843cc7.png)

**Comment by ssimo3lsuhsc** [comment]
I might add that my trial of Komodo IDE ends on October 5, 2017. If somebody cannot either fix this or else [fix the documentation](http://docs.komodoide.com/Manual/dom) by then, then Komodo IDE is not worth my wallet.

![dom viewer komodo ide edit documentation](https://user-images.githubusercontent.com/20207672/30442321-b53ef2dc-9941-11e7-9a17-8311d1e36cea.png)

**Comment by ssimo3lsuhsc** [comment]
The URL for the documentation is [here](http://docs.komodoide.com/Manual/dom).

**Comment by Naatan** [comment]
Thanks for the detailed report @ssimo3lsuhsc. We are getting close to releasing Komodo 11 which completely replaces the DOM Viewer with an all new symbol browser. This symbol browser currently does not support xpath, but I'll keep it in mind for the future. Regardless given the givens this bug report is not applicable as we won't be maintaining the old DOM viewer.

**Comment by Naatan** [comment]
Documentation updated, thanks for the tip!
