### ISSUE TITLE
no back/forward or reload buttons in new preview tool

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3076]
### Short Summary

New preview tool:
![capture](https://user-images.githubusercontent.com/655154/30446502-3a088374-993e-11e7-8cac-67965277893a.PNG)

Legacy browser preview:
![capture](https://user-images.githubusercontent.com/655154/30446611-81cfe184-993e-11e7-985c-79485a04137d.PNG)

**Comment by Naatan** [comment]
This is by design, the preview tool is for previewing one specific page. It is not to be used as the browser preview. If you use that use the Browser Preview feature.
