### ISSUE TITLE
Title bar still says "Komodo 10" on Linux 64-bit

### ISSUE THREAD

**Issue by i-shenl** [Komodo/KomodoEdit#3077]
### Short Summary

The title bar in the upper left of the screen still shows Komodo 10 when running Komodo 11 on Linux 64-bit

### Steps to Reproduce

Open Komodo 11 on a Linux 64-bit system - like Ubuntu

### Expected results
Should show Komodo 11

### Actual results
Shows Komodo 10. See screeen snap

### Platform Information

Komodo IDE 11 on Ubuntu 64 bit
/home/i-shenl/Pictures/Screenshot from 2017-09-14 11-26-08.png
![screenshot from 2017-09-14 11-26-08](https://user-images.githubusercontent.com/17010135/30447127-f2949530-993f-11e7-838f-07333e7ec3d7.png)

**Comment by Naatan** [comment]
https://activestate.slack.com/archives/C03NU4MN5/p1505415526000173
