### ISSUE TITLE
Completions color scheme not updating with rest of UI

### ISSUE THREAD

**Issue by damienprystay** [Komodo/KomodoEdit#3088]
Having applied the Default theme (for all of Editor, Interface, and Widgets), the options in the auto-suggestion/completion popup are unreadable, other than the currently highlighted one.

*EDIT*: See this comment for repro: https://github.com/Komodo/KomodoEdit/issues/3088#issuecomment-329622514

<img width="406" alt="screen shot 2017-09-14 at 14 51 18" src="https://user-images.githubusercontent.com/3590102/30457472-48e6782e-995c-11e7-9b6f-370aeb809fd0.png">

<img width="410" alt="screen shot 2017-09-14 at 14 51 31" src="https://user-images.githubusercontent.com/3590102/30457479-4b9db92e-995c-11e7-986b-a6e372a9f6ea.png">

Komodo IDE 11.0.0 build 90665
Mac OS X 10.11.6

**Comment by cgchoffman** [comment]
Hey @damienprystay, that doesn't look like the default theme.  Perhaps it applied incorrectly.

The default completions should look like this: 
![screenshot 2017-09-14 14 54 07](https://user-images.githubusercontent.com/655154/30457581-b4d0bd1a-995c-11e7-9e1c-e1e5b5c6ed66.png)

**Comment by cgchoffman** [comment]
@damienprystay could you attached your logs then try re-applying the color scheme?

**Comment by damienprystay** [comment]
I couldn't get the suggestion popup to occur anymore, so I restarted Komodo. After restart, the suggestion popup is the appropriate colour for the theme. However, then switching to another theme (Classic) leaves me with the previous theme's colours still in the suggestion popup. Restarting in Classic gives me Classic-themed popups, including after switching back to Default.

That might narrow it down a bit; I can attach the log if you still want it.

**Comment by cgchoffman** [comment]
Thanks @damienprystay, I can reproduce that now. Perfect.

**Comment by Naatan** [comment]
Yay XUL, just when I thought you couldn't surprise me anymore.

**Comment by Defman21** [comment]
You forgot to put any labels on this issue.

**Comment by Naatan** [comment]
You think you're so smart ...

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/76131f05b68e1c8e96482ec6840ec7a0b253984c
