### ISSUE TITLE
Code Browser doesn't load after first open

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3091]
### Short Summary

When a file is opened with the Code Browser closed, when I then open the code browser it will just load forever.  I have to switch buffers before it will actually load.

### Steps to Reproduce

- Make sure the code  browser is closed
- Open a file for code intel
- Open code browser

### Expected results

It to load content

### Actual results

The code browser just loads forever until you open another file.

**Comment by Naatan** [comment]
I cannot reproduce this. Can you still repro this on master?

**Comment by cgchoffman** [comment]
I cannot.  I'l reopen if I see it again.
