### ISSUE TITLE
Files created based on templates are detected as Text files

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#3092]
### Short Summary
Files created based on templates are detected as Text files. 

### Steps to Reproduce

1. Right click on the folder in places pane -> New File from Template
2. Select PHP template from Commando
3. Enter filename without extension for e.g. test
4. Click ok
5. Notice that file 'test' is detected as text file. See screenshot

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo IDE, version 11.0.0, build 90665, platform macosx.
Built on Wed Sep 13 19:50:11 2017.
### Additional Information
![image](https://user-images.githubusercontent.com/26605593/30460413-afb4e84c-996b-11e7-9f99-147b4c9fba9c.png)

**Comment by Naatan** [comment]
I can't help how it is detected in your side pane, as this is based on the file extension and reading the file to find out the real type would significantly slow down side pane loading. But the language ought to definitely be set properly.

**Comment by cgchoffman** [comment]
This has been buried in the views code for a while now.  It's amazing it never was hit before.  That code was a bit of a mess: https://github.com/Komodo/KomodoIDE/commit/7ab16f6171e3efdbd514c5a0b29d6f25b2ed649f
