### ISSUE TITLE
Less &: doesn't trigger pseudo autocompletion

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3094]
### Short Summary
When working with less files, you can extend almost everything with the & sign.
In Komodo X this is working.

### Steps to Reproduce
Create a less file and extend a selector by typing `&:`

### Expected results
pseudo autocompletion is triggerd

### Actual results
Nothing happends

### Platform Information
Komodo Ide 11.0.0 build 90651 windows 10

**Comment by mitchell-as** [comment]
Thanks for the report.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/codeintel/commit/93b39f76aee74f4853e60280d854437eb7554b42
