### ISSUE TITLE
HMTL autocompletion doesn't show autocompletion when matching whole tag

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3096]
### Short Summary
When using the html autocompletion, when you match a whole tag it does not show the tag in the autocompletion anymore

### Steps to Reproduce
```html
<table>
    <tr>
        
    </tr>
</table>
```
If you would like to insert a td and you would type `<td` the autocompletion is gone.

### Expected results
The tag will be shown in the autocompletion so you can select it

### Actual results
It's missing

### Platform Information
Komodo Ide 11.0.0 build 90651 windows 10

**Comment by Naatan** [comment]
This is a feature, you can toggle it via Preferences

![image](https://user-images.githubusercontent.com/278649/30488231-c172e032-9a03-11e7-935b-bc8166c12508.png)

**Comment by babobski** [comment]
oke, thanks good to know 👍
