### ISSUE TITLE
When using the "New file from template" function tab-stops and other snippet variables are inserted

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3097]
### Short Summary
When using the "New file from template" function tab-stops and other snippet variables are inserted.
Like when you select a HTML5 file the following snippet is inserted.

```html
<!DOCTYPE html>

<html>
<head>
    <title>[[%tabstop:Page Title]]</title>
</head>

<body>

[[%tabstop]]

</body>
</html>

```
But you can't use the tab-stops.

### Platform Information

Komodo Ide 11.0.0 build 90651 windows 10

**Comment by Naatan** [comment]
This is because you are using older templates, the latest RC has resolved this.
