### ISSUE TITLE
New file from template missing languages 

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3098]
### Short Summary
This might also be by design, but I'm missing a lot of languages when using new file from template.
I know these "Templates" would be blank, but I think it would be nice if you can still create these files trough "new file from template". 
As these are still the suported languages.

### Steps to Reproduce
Try to create a less or javascript file trough "new file from tamplate".

### Expected results
You would get a match for the correct language, so you can create a file with the correct language.

### Actual results
The files are missing.

### Platform Information

Komodo Ide 11.0.0 build 90651 windows 10

**Comment by Naatan** [comment]
This is addressed in our RC build, though since you are using a private beta you wouldn't see the updated templates unless you'd nuke your tools folder. You could manually copy over the sample files from the install directory once 11 is released.
