### ISSUE TITLE
HTML inline CSS autocompletion not working

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3099]
### Short Summary
The CSS autocompletion is missing for inline styles, while editing html/php files.

### Steps to Reproduce
```html
<!DOCTYPE html>

<html>
<head>
    <title>[[%tabstop:Page Title]]</title>
</head>

<body>
    <div style="">
        
    </div>
</body>
</html>

```
Type CSS in the style attribute.

### Expected results
CSS autocompletion should be shown.

### Actual results
The autocompletion is missing.

### Platform Information

Komodo Ide 11.0.0 build 90651 windows 10

**Comment by mitchell-as** [comment]
Thanks for the report.

**Comment by Naatan** [comment]
@mitchell-as too much for 11.0.1?

**Comment by Naatan** [comment]
Ok, please retarget if it's too much.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/codeintel/commit/3811ee6e26262b22716e2789c8d3eb632a9b0af2

**Comment by mjainQA** [comment]
Verified in 11.0.1 nightly


![image.png](https://zube.io/files/komodo/e6b0e4efc4fb8d9b42acc06cf971c42a.png)
