### ISSUE TITLE
floating panes: In customize mode, can't combine tabs by drag and drop

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#31]
- Right click pane tab icon, click customize
- try to drag and drop different tabs into other tabs.  

*Expect*: dragged tab to merge into  receiving tab in the indicated space (indicated by dotted line box)
*Actual*: Nothing happens

Functionality remains by using right click tab icon > Combine tab with

**Comment by Naatan** [comment]
I cannot reproduce this, are you sure you're dropping them right? You have to actually drop it at the place where you want it to be merged, you dont just drop it on the other tab.

Please post your pystderr when the bug occurs.

**Comment by cgchoffman** [comment]
Odd, You must have fixed it...:P kidding. I might have been misreading the visual indicators for where to drop.  It's working fine.
