### ISSUE TITLE
default Python interpreter suggestion

### ISSUE THREAD

**Issue by hobbsd** [Komodo/KomodoEdit#310]
It seems like it would be a good thing to be able to tell Komodo to *only* use a specifically designated Python interpreter and not ever fall back to looking for one on the path or standard system locations. That would make it easier to avoid some confusing issues, such as with syntax checking.

**Comment by Naatan** [comment]
Thanks for taking the time to report this.

A fall back is just that; something to fall back on if the default for whatever reason doesnt work. If there are use-cases where the default preference is not respected then those cases should individually be addressed. Removing the fall back would not really address your issue there.

As such I don't think there's anything to be done here, but please report the issue you've found where the default interpreter is not being respected.
