### ISSUE TITLE
In CSS block (inside HMTL file) autocompletion is preventing opening "block"

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3100]
### Short Summary
When using CSS blocks inside HTML files, the autocompletion is preventing me to open the css block.
I have to use <kbd>esc</kbd> to open the block.

### Steps to Reproduce
Create a HTML file:
```html
<!DOCTYPE html>

<html>
<head>
    <title>[[%tabstop:Page Title]]</title>
    <style type="text/css">
        .test 
    </style>
</head>

<body>

[[%tabstop]]

</body>
</html>
```
After .test ype `{` and press enter.

### Expected results
```html
<!DOCTYPE html>

<html>
<head>
    <title>[[%tabstop:Page Title]]</title>
    <style type="text/css">
        .test {
            
        }
    </style>
</head>

<body>

[[%tabstop]]

</body>
</html>

```

### Actual results
```html
<!DOCTYPE html>

<html>
<head>
    <title>[[%tabstop:Page Title]]</title>
    <style type="text/css">
        .test {-moz-appearance: }
    </style>
</head>

<body>

[[%tabstop]]

</body>
</html>
```

### Platform Information

Komodo Ide 11.0.0 build 90651 windows 10

**Comment by mitchell-as** [comment]
Related to #3089. This one's tricky.

**Comment by Naatan** [comment]
I think we should just not show completions on `{`. This is easily done through the config in router.py

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/38da19e9790e1e73567ef3ee914d68ac48d31ef2
