### ISSUE TITLE
PHP autocompletion

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3101]
### Short Summary
I struggle a bit with the autcompletion of php.
For example, when creating new files my settings are to create a new php file.
When I now try to create the opening of my file.
I will end up with:
```php
<?phpinfo
```
or with:
```php
<?php ABDAY_1
```

### Steps to Reproduce
Create a empty php file and type `<?php` and try to get to the next line without using <kbd>Esc</kbd>

### Platform Information

Komodo Ide 11.0.0 build 90651 windows 10

**Comment by mitchell-as** [comment]
Thanks for the report.

**Comment by mitchell-as** [comment]
Note to self: `<?php<|>` should not give a completion context.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/codeintel/commit/a6cd90da19217531f940ec47362440ebe0eecb79
