### ISSUE TITLE
Addon menu doesn't display (Mac)

### ISSUE THREAD

**Issue by jsooter** [Komodo/KomodoEdit#3105]
### Short Summary
Addons menu doesn't display and search box doesn't accept focus. Re-installling over Komodo doesn't fix the issue. Disabling extensions doesn't fix the issue. I don't have another Mac to test on so I don't know if it's limited to my system.

### Steps to Reproduce
Click Tools->Add-ons or click in search box.

### Expected results
Add-ons menu should appear

### Actual results
Nothing happens

### Platform Information

*Komodo Edit
*Komodo Version 10.2.3
*Operating System: macOS Sierra 10.12.6

### Additional Information
Log:
[2017-09-15 11:04:25,438] [ERROR] console-logger: TypeError: require(...).openCategory is not a function (2) in chrome://komodo/content/launch.js:458
Traceback (most recent call last):
  File "chrome://komodo/content/launch.js", line 458, in

### Work-around
Legacy Add-ons menu still functions

**Comment by Naatan** [comment]
Can you reproduce this using `Help > Troubleshooting > Restart in Safe-mode` ?

Please verify that when restarting in safe-mode Komodo should be using the default UI (all your settings would be temporarily reset).

**Comment by jsooter** [comment]
That fixed it.
