### ISSUE TITLE
Word Wrap doesn't work with New previewer

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3106]
### Short Summary

Word wrap isn't working when you use the new previewer tool.

### Steps to Reproduce

Open a markdown file
click the eye icon in the dynamic toolbar to open previewer
Turn on *View > Word Wrap* for that file
Type a long enough line that it pushes the scrollbar to the right.

### Expected results

Word wrap.

### Actual results

No word wrapping occurs.

**Comment by Naatan** [comment]
Are you talking about the preview itself not wrapping?

**Comment by cgchoffman** [comment]
This isn't happening.  It was just delayed due to the bug I filed regarding Komodo hanging.
