### ISSUE TITLE
Let's Get Started - "False positives" for languages, tools, vcs

### ISSUE THREAD

**Issue by davetlewis-van** [Komodo/KomodoEdit#3107]
### Short Summary

On a clean install on a new VM, Komodo reports "Located on PATH"  instead of "Not Detected" for a number of things that are not present on the system.

### Steps to Reproduce

Perform a clean Komodo install in a clean VM.

### Expected results

Only language, tools, and VCS that are installed should be "Located on Path"

### Actual results

Entries that (I believe) are not installed include:
Languages 
- Go
- Node.js
- PHP
- Ruby
- TCL

Tools
- gocode
- godef

Version control:
- CVS
- Perforce
- Subversion

### Platform Information

* Komodo IDE  
* 11.0.0 90665
* Ubuntu 16.04

**Comment by cgchoffman** [comment]
Main to things I'm interested in:
Can you reproduce this after a restart or does it only happen the once in the clean VM?
Can we run some commands in the machine to confirm those executable files don't exist?  Can I SSH to the machine and do that myself by any chance?

**Comment by davetlewis-van** [comment]
Yeah. I get the same result after restarting Komodo, and after rebooting
the vm.

I'm running the VM locally on Parallels, so I'm not sure there's an easy
way to ssh to it. You can get on my computer if that's easier.

**Comment by cgchoffman** [comment]
Can't find anything obvious on Dave's computer and I didn't add any log lines in executable finding code.  I'll have to try to reproduce this with a local build and add logging when i do.

**Comment by cgchoffman** [comment]
I was able to reproduce this on OSX though I have no additional insite

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/98c3c078b26853f9592e59d9e991dafb61efaaab
