### ISSUE TITLE
Typing too fast causes the completion suggestion popup to occur late

### ISSUE THREAD

**Issue by damienprystay** [Komodo/KomodoEdit#3110]
Forked from https://github.com/Komodo/KomodoEdit/issues/3089#issuecomment-329634263

Typing sufficiently quickly past a suggestion-prompting delimiter can cause the completion popup to occur (and remain) after the character that triggered it has been obsoleted.

E.g. (in PHP) typing `foo();` one character at a time shows the suggestion popup (other than for as many of the initial letters produced suggestions) occurs after `(`, and disappears after `)`; however, typing it at speed can result in the popup only occurring after the `;`, where it's no longer the same context, and attempting to type a newline will instead result in selecting the first suggestion.

Komodo IDE 11.0.0 build 90665
Mac OS X 10.11.6

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/76131f05b68e1c8e96482ec6840ec7a0b253984c

**Comment by damienprystay** [comment]
I'm still seeing this behaviour in 11.0.1 (build 90797), I'm afraid. It seems a little less consistent overall, but I've tripped over it a couple times today.

As a reasonably reproducible example: In a new file with the language set to Python, typing just `()` sufficiently quickly results in the completion popup created for the `(` still being present after the `)`.

(I would argue that it shouldn't be suggesting anything after `(` in the first place, since it has no context to work with and consequently suggests a list of every name it knows about. Though maybe that's a shorter and more useful list in languages other than those I use?)

**Comment by Naatan** [comment]
Related to #3341

**Comment by Naatan** [comment]
Closing this one to handle it in above mentioned ticket, this one was still handled under 11.0.1
