### ISSUE TITLE
Colour Picker is inoperably small and can't be resized

### ISSUE THREAD

**Issue by damienprystay** [Komodo/KomodoEdit#3111]
When I attempt to change a foreground or background colour in the colour scheme editor, the Colour Picker that spawns apparently doesn't have any controls, just the title "Color Picker" and a bar of the current colour (which doesn't respond to mouse clicks).

On playing with it a bit (clicking to focus the area with the coloured bar, and then using the arrow keys), it seems the controls are there, but they're all offscreen, and I can't resize the dialog to reveal them.

Komodo IDE 11.0.0 build 90665
Mac OS X 10.11.6

![screen shot 2017-09-15 at 16 28 00](https://user-images.githubusercontent.com/3590102/30506699-e576e13e-9a32-11e7-9382-3dee92ca7616.png)

![screen shot 2017-09-15 at 16 31 50](https://user-images.githubusercontent.com/3590102/30506755-6b52dc90-9a33-11e7-9429-dc1b0bb8b56d.png)

## Workaround

See https://github.com/Komodo/KomodoEdit/issues/3111#issuecomment-332617911

**Comment by babobski** [comment]
@damienprystay did you installed the RGBA colorpicker in Komodo X?
If so you might have the same issue as #2882

**Comment by Naatan** [comment]
@mjainQA can you repro this? Working fine for me on Linux.

**Comment by damienprystay** [comment]
@babobski Nope, no addons installed.

**Comment by Naatan** [comment]
@mjainQA ping

**Comment by Naatan** [comment]
More context: https://community.komodoide.com/t/issues-upgrading-to-11/3851/16?u=nathanr

**Comment by damienprystay** [comment]
Re. that community thread, I'll note that while the colour picker may be resizable as a workaround on Windows, it isn't resizable on Mac.

**Comment by Naatan** [comment]
@cgchoffman I think the .xul file this uses just needs a hard-coded width and height.

**Comment by babobski** [comment]
@damienprystay I added a workarround on the forrum:

**Comment by babobski** [comment]
@damienprystay update the above post to also add the css workaround here,

**Comment by damienprystay** [comment]
@babobski Aha! That works great, thank you.

**Comment by babobski** [comment]
No problem, glad to help 👍

**Comment by mjross** [comment]
In a fresh install of Komodo IDE 11 build 90668 on a Windows 10 Pro machine, I'm having the same problem (when trying to create a custom scheme), with the two fields side-by-side. Screenshot and log attached.

![color scheme editor color picker](https://user-images.githubusercontent.com/829492/30941305-ffc4e996-a3a1-11e7-8abf-7eef22e74692.jpg)

[pystderr.log.txt](https://github.com/Komodo/KomodoEdit/files/1338906/pystderr.log.txt)

**Comment by Naatan** [comment]
Thanks guys :) I think we have enough info to fix this one. Should be a simple fix, basically @babobski's workaround only applied directly to the xul file in question.

**Comment by Defman21** [comment]
Yeah... https://github.com/Komodo/KomodoEdit/pull/2039

**Comment by Naatan** [comment]
Very nice, thank you @Defman21

**Comment by babobski** [comment]
Thanks @Defman21 !
I noticed one thing more, the colorpicker window still has a resize button:

![afbeelding](https://user-images.githubusercontent.com/3530262/30980171-5497e700-a480-11e7-8652-8144bc924acc.png)

If I look at the code the openDialog function has the window feature `resizable=no`.
When I looked better, I noticed a [syntax error](https://github.com/Komodo/KomodoEdit/blob/d0fe723a7d39d08a207b8d45a94bd12cb756b039/src/chrome/komodo/content/colorpicker/xpcom_colorpicker.js#L76) has slipped in, in the pickColorWithPositioning function.

**Comment by Naatan** [comment]
Great digging @babobski ! @cgchoffman can you fix that while you're at it?

**Comment by Laniture** [comment]
I'm having the same issue on Linux.  https://github.com/Komodo/KomodoEdit/issues/3111#issuecomment-332617911 Fixed it.

I used.
```
window[title="Color Picker"] {
	min-height: 560px;
	min-width: 328px;
}
```
<br>

Probably unrelated warning.
```
JavaScript strict warning: chrome://komodo/content/colorpicker/colorpicker.js, line 166: ReferenceError: reference to undefined property navigator.appVersion.split(...)[1]
```
Dockerfile to replicate. https://ghostbin.tech/paste/dkrxv/raw
