### ISSUE TITLE
Tabbing to the replace-with box of the quick find-replace bar no longer works

### ISSUE THREAD

**Issue by koyae** [Komodo/KomodoEdit#3112]
### Short Summary

Open the quick replace dialog and hit **Tab**. The cursor does not jump to the next box.

### Steps to Reproduce

1. Press **ctrlH** or choose Edit->Replace on the toolbar. The cursor will jump to the "Find:" field as expected.
2. Press the **Tab** key on the keyboard.

### Expected results

Starting in the "Find:" box, the cursor fails to move to the next box "Replace:" when **Tab** is pressed, as was the behavior in e.g. v8.5.

### Actual results

Cursor remains in the current box.

### Platform Information

KomodoEdit v10.2.3
Occurs for me on the following platforms:
* 64-bit Windows 10 Home
* 32-bit Windows 10 Pro
* 64-bit Windows 7 Enterprise

Does not affect:
* Ubuntu 14.04 LTS

### Additional Information

This issue may be a more severe version of #2720.

I initially assumed something was just odd with my system since I didn't see anyone else reporting it, but this problem was occurring for me even on a fresh install of Windows 10 Home, and the **Tab** key appears to work normally in all other contexts. Since upgrading to 10.X from 8.5 maybe 4 to 6 months ago (to whatever the current version was at that time), this has remained an irritation.

At least with the **alt***Whatever* menu-bar hotkeys disabled (the ones for raising the top menu-bar's File menu, the Tools menu, etc.), **altL** allows jumping to the next box. as do **altI** and **altN** for hopping around. It's taken me until now to notice this, however.

**Comment by mitchell-as** [comment]
Would you please see if you can reproduce this in Safe Mode? (Help > Troubleshooting > Restart in Safe Mode) I am skeptical this would not work on Windows despite working on Linux.

**Comment by koyae** [comment]
Huh. This works fine from safe-mode.

What's the easiest way of determining what's maybe breaking this for me when running normally? Is there's a way of customizing-then-exporting settings from safe mode so I can replicate things back to a working state in normal mode?

**Comment by Naatan** [comment]
I would recommend you start by attempting the following options under Help > Troubleshooting:

Restart Without Addons
Restart Without Tools

**Comment by Defman21** [comment]
Are you using Xemmet by any chance?

**Comment by koyae** [comment]
I am.

**Comment by Defman21** [comment]
Hmm, I'll look into that issue.

**Comment by koyae** [comment]
@Defman21 I've done some digging and it looks like this was unrelated to Xemmet; I tried at my home computer and confirmed I hadn't installed Xemmet yet on that one, despite still seeing the exact same behavior.

@Naatan @mitchell-as This was a keybindings-issue which you may or may not wish to count as regression. I migrated to 10.x directly from KomodoEdit 8.5 and [binding **tab** and **shiftTab**](https://github.com/koyae/migration/blob/8ad2f8e03e68ce497ec4c7403ee09244333f4462/.komodoedit/8.5/schemes/kbindings.kkf#L157-L159) caused me no problems. I assume 8.5 ignored at least certain bindings when the find-replace box had focus. This may be because it was a separate dialog rather than a docked widget, though I don't remember precisely.

Thanks for helping me to track this down! Y'all are awesome.

**Comment by Defman21** [comment]
>I've done some digging and it looks like this was unrelated to Xemmet

Thanks for that.
