### ISSUE TITLE
"OK" button of macro-properties box does not close the window

### ISSUE THREAD

**Issue by koyae** [Komodo/KomodoEdit#3114]
### Short Summary

When viewing the "Properties" window of a given macro, pressing the "OK" option does not close the dialog.

### Steps to Reproduce

1. Context-click or hit use context-menu key on the name of a macro from the 'toolbox' pane (by default this lives on the right) to raise a context-menu (contains "Export as Zip file", "Execute userscript", "Edit userscript", etc.)
2. From the context-menu that appears, select "Properties".
3. In the window that appears, change zero or more settings, then choose the "OK" option from the bottom of the dialog.

### Expected results

Window closes and changes are saved.

### Actual results

Changes are saved but window remains open.

### Platform Information

KomodoEdit 10.2.3

Affected platforms:
* 64-bit Windows 7 Enterprise

Tested not-affected platforms:
* 64-bit Ubuntu 14.04 LTS
* 64-bit Windows 10 Home

**Comment by mitchell-as** [comment]
Would you please see if you can reproduce this in Safe Mode? (Help > Troubleshooting > Restart in Safe Mode) I am skeptical this would not work on a particular Windows OS despite working on other Windows OSs and Linux.

**Comment by koyae** [comment]
Your suspicions were correct; from safe mode, this seems to work as expected.

**Comment by mitchell-as** [comment]
Okay, thanks for the follow-up. Closing ticket.
