### ISSUE TITLE
HTML "Default template" not working

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#3118]
### Short Summary

I cannot get my HTML 5 file template to act as the default language template.

### Steps to Reproduce

* Open HTML 5 file template properties and mark it as  "Default template for selected language", use language "HTML 5"
* Create a new file and change the language to HTML 5

### Expected results

* The file template is inserted

### Actual results

* The file template isnt inserted

**Comment by cgchoffman** [comment]
I don't think this is how this work.  @naatan do templates inject content into an already open file?

**Comment by Naatan** [comment]
Can't reproduce anymore.
