### ISSUE TITLE
Calltip is not falling back to the bottom if there is not enough space

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#3122]
### Short Summary

Calltip is not falling back to the bottom if there is not enough space and displayed out of Komodo editor frame. See screenshot

### Steps to Reproduce
1. Create a ruby file
2. Type `require`

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo IDE, version 11.0.0, build 90667, platform macosx.
Built on Fri Sep 15 15:06:46 2017.
### Additional Information
![image](https://user-images.githubusercontent.com/26605593/30565134-0857e1ee-9c7c-11e7-9fb0-58aa835fc88e.png)

**Comment by Naatan** [comment]
This is not really solvable in the way suggested, since below the caret is where the completions show. All things considered this is doing the best it can do given the possibilities.
