### ISSUE TITLE
Code completion window not near the code to complete

### ISSUE THREAD

**Issue by neurobashing** [Komodo/KomodoEdit#3123]
### Short Summary
Window is WAY above the code, obscuring code I wanted to see

### Steps to Reproduce
Do something that triggers code completion.

### Expected results
Code completion/suggestions near the insertion point.

### Actual results
Code completion/suggestions WAY far away from insertion point.

### Platform Information
Komodo IDE, version 11.0.0, build 90667, platform macosx.
Built on Fri Sep 15 15:06:46 2017.
<img width="681" alt="screen shot 2017-09-18 at 5 25 36 pm" src="https://user-images.githubusercontent.com/59380/30565567-c9e501d8-9c96-11e7-936c-c71402c1bb78.png">

**Comment by Defman21** [comment]
I guess this one is related? https://github.com/Komodo/KomodoEdit/issues/3122

**Comment by neurobashing** [comment]
Ah, missed that one in my search.

it's probably related but I had a TON of screen space available, so if I had to guess it's miscalculating available space. (For some value of the above)

**Comment by Naatan** [comment]
I am not seeing this at all, are you able to reliably reproduce this?

**Comment by Naatan** [comment]
Hmm. Is this on retina? Also, how many monitors, and on which monitor is Komodo (xth from left)?

**Comment by neurobashing** [comment]
MacBook Pro (Retina, 15-inch, Mid 2015)
Just the main laptop monitor, no other graphics devices. I do have a t-bolt ethernet adapter but that's it.

**Comment by Naatan** [comment]
Does it do this with any and all code? 

Can you reproduce this using `Help > Troubleshooting > Restart in Safe-mode` ?

Please verify that when restarting in safe-mode Komodo should be using the default UI (all your settings would be temporarily reset).

@mjainQA tried this on her Retina macbook and was not able to reproduce.

**Comment by neurobashing** [comment]
<img width="646" alt="screen shot 2017-09-19 at 3 31 28 pm" src="https://user-images.githubusercontent.com/59380/30611656-f4f3f456-9d4f-11e7-9d71-a66e7c558252.png">
<img width="882" alt="screen shot 2017-09-19 at 3 32 02 pm" src="https://user-images.githubusercontent.com/59380/30611657-f4feb102-9d4f-11e7-88c1-3b45ca8eb21f.png">

it did not happen, in safe mode or otherwise, with ruby and bash. Only perl and python.

**Comment by Naatan** [comment]
Not sure I am interpreting your sentence properly. You're saying the issue only happened on Perl and Python files when in safe-mode?

**Comment by neurobashing** [comment]
It happens all the time (both safe and regular) with Perl and Python. 

It did not happen at all in Ruby and Bash, in either mode.

**Comment by Naatan** [comment]
Very strange. Can you even reproduce it with a simple "Hello World" Python file?

ie.

```
helloWorld = "Hello World!"
print hello<|>
```

**Comment by neurobashing** [comment]
in python, that works as expected: it cycles appropriately. It only seems to happen with callables (defs in python, subs in perl).

**Comment by neurobashing** [comment]
i should note that I don't get popups at all; i just cycle through w/ tab.

**Comment by Naatan** [comment]
What do you mean you don't get popups? Your screenshots clearly show popups.

Can you give some code samples that reproduce your issue?

**Comment by neurobashing** [comment]
sorry, in the 2-line hello world sample, I mean. 

here is my python sample:
```python
#!/usr/bin/env python3

import sys

def something():
    return "Hello"

def blah():
    return "blah"

something()
```

**Comment by Naatan** [comment]
Thanks so much for noticing and logging this @neurobashing, this would have been embarrassing to release with.
