### ISSUE TITLE
"Create Firefox Extension" project template uses deprecated code

### ISSUE THREAD

**Issue by mjross** [Komodo/KomodoEdit#3127]
The Project > New From Template > Create Firefox Extension functionality creates several files to use as a template for a new Firefox extension/add-on project, but instead of the code being based on the current WebExtensions API, it uses the now-deprecated legacy API. For instance:
- chrome.manifest and install.rdf are now unused filenames
- myprojectextension_overlay.xul contains deprecated XUL code
- Build.komodotool and Reconfigure.komodotool contain outdated manifest keys

A note from developer.mozilla.org: 

> Add-ons using the techniques described in this document are considered a legacy technology in Firefox. Don't use these techniques to develop new add-ons. Use WebExtensions instead. [...] Starting from Firefox 53, no new legacy add-ons will be accepted on addons.mozilla.org (AMO) for desktop Firefox and Firefox for Android. Starting from Firefox 57, only extensions developed using WebExtensions APIs will be supported on Desktop Firefox and Firefox for Android.

**Comment by Naatan** [comment]
@cgchoffman lets remove this.

**Comment by mjross** [comment]
I'd be happy to contribute my Firefox add-on boilerplate files, which even include GIMP files for the icon images. And if you would like to add another option, for Google Chrome add-ons, I have (very similar) starter files for those as well.

**Comment by Naatan** [comment]
I appreciate that @mjross, but I think this would be better contributed as a package. This is not something we as Komodo developers should be maintaining.

**Comment by mjross** [comment]
That makes sense.

**Comment by cgchoffman** [comment]
Yep, that was my first thought too @naatan. Thanks for filing this @mjross

**Comment by mjross** [comment]
No worries. Any chance I get to try to add to people's workloads...  ;+)
