### ISSUE TITLE
Reset All in Komodo 11 also reset settings in Komodo 10

### ISSUE THREAD

**Issue by damienprystay** [Komodo/KomodoEdit#3128]
Shortly after switching to Komodo 11, I used the `Troubleshooting -> Reset All` command to reset the UI. When I later quit K11 and launched K10, I found my UI had been reset there as well. (It did back up the K10 profile in the process, so nothing was irrevocably lost.)

Komodo IDE 11.0.0 build 90665
Mac OS X 10.11.6

**Comment by Naatan** [comment]
This is by design. You can access the old folder in the same location as the new, it has -backup-<date> appended to it.
