### ISSUE TITLE
sdk/shell platform conditional is inversed

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#3129]
https://github.com/Komodo/KomodoIDE/blob/master/src/chrome/komodo/content/sdk/shell.js#L309

This causes issues when running a command from commando with ":ot", and likely has implications elsewhere also.

**Comment by cgchoffman** [comment]
That doesn't look wrong to me.  Index of `0` means the start of the string.  It's definitely presumptuous but it's not wrong.  Better would be `platform.indexOf('win') >= 0`. 

because I don't trust my self at all I double checked:
```
require("sdk/system").platform // "winnt"
require("sdk/system").platform.indexOf('win') //  `0`
```

**Comment by Defman21** [comment]
>because I don't trust my self

![a meme](https://i.imgur.com/2inOdiQ.jpg)

**Comment by Naatan** [comment]
Do'h, you're right. It's looking at indexOf not a boolean.
