### ISSUE TITLE
Pull with Rebase doesnt work

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#3130]
### Steps to Reproduce

1) Click on File -> Source Control -> Pull with Rebase

### Expected results

Changes are pulled in and the code rebasing is done where it merges new changes on Komodo with the code pulled in.

### Actual results
An exception occurred during SCC operation: 'TypeError: ko.scc.PullRebase is not a function'

**Comment by Defman21** [comment]
I doubt you expect an exception ;)

**Comment by Naatan** [comment]
You and your logic.

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/455a2d71fcf71f5ba13071b758049df31289346e
