### ISSUE TITLE
Commando: implement pagination in commando

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3136]
### Short Summary

If there is a display limit set that cuts off results we should load more results if the user has reached the bottom of the displayed results

### Steps to Reproduce

-Open Commando
- Open commands scope
- scroll to the bottom

### Expected results

- more commands to load when i reach the bottom

### Actual results

Nothing.

**Comment by Naatan** [comment]
This would require significant refactoring of how Commando works. Commando was designed with this limitation in mind, if you want better results then make your query more specific.
