### ISSUE TITLE
Komodo is somehow setting "Located on PATH" for binaries in prefs

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3139]
### Short Summary

This somehow comes from the Dependencies interface in the start up wizard.  Not sure how. 

### Steps to Reproduce

Check the SVN binary preference.  That's been the one that is consistently set on all platforms, regardless of whether or not the binary is installed.

### Expected results

Pref should be set to `Find on PATH` if the binary isn't found or not explicitly set by the user.

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/8442dbe90fd7983769fe2233f1add5befe937c3d

**Comment by Naatan** [comment]
This really shouldn't be checking against a localized string. You should set a proper value.

**Comment by cgchoffman** [comment]
Eww, ya gross.  I'll set "found" boolean on the object.  Thanks.

**Comment by cgchoffman** [comment]
On second thought, I can't just check an "found" property.  `Located on Path` is an item in the menu and if the user doesn't change it to a specific path then Komodo will save `Located on Path` to the prefs.  Apparently you can't have placeholder text in a menulist?  I can't find a way to do that at the moment.

**Comment by cgchoffman** [comment]
Found a better way: https://github.com/Komodo/KomodoIDE/commit/60b46aea87a2aa440de63cb0989eba90c1c510ca

**Comment by mjainQA** [comment]
@cgchoffman This is not fixed in Komodo IDE, version 11.0.1, build 90755, platform macosx.
Built on Tue Oct 10 09:26:02 2017.


![image.png](https://zube.io/files/komodo/b4791cabfda37def0bc66b747e3895dd.png)

**Comment by mjainQA** [comment]
Verified in Komodo IDE, version 11.0.1, build 90755, platform macosx.
Built on Tue Oct 10 09:26:02 2017.

**Comment by Naatan** [comment]
@cgchoffman please write pref upgrade code so people who used 11.0.0 don't get stuck with a broken pref.

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/fd9114bfc4dff2d06eefd8654937282de7a17d8c
