### ISSUE TITLE
Can't open slack share in browser

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3144]
### Steps to Reproduce

Open any file in Komodo
Right-click on the file and select share -> share code via Slack
Enter credentials for slack
Select a channel from the drop-down (for e.g. slacktesting)
Click on Share & Open Browser

### Expected results

Browser to open to shared content

### Actual results

Nothing appears to happen.  Then message IS sent to slack but the browser doesn't open

### Additional Information

```
Open any file in Komodo
Right-click on the file and select share -> share code via Slack
Enter credentials for slack
Select a channel from the drop-down (for e.g. slacktesting)


Click Share on Slack.
Verify that contents are posted on the selected channel


Click on Share & Open Browser
Verify that slack opens in a browser window with the file contents.
```

**Comment by Naatan** [comment]
Reproduced on Linux

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/27a21c9d5667c6b6e0f88cbf3829e76c3eabd714
