### ISSUE TITLE
Track changes dialog won't close

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#3147]
### Steps to Reproduce

Open the track changes dialog by hitting a changeset in the margin
Click anywhere else in the editor

### Expected results

Track changes dialog closes

### Actual results

Track changes dialog repositions itself

### Additional Information

Right clicking in the editor dismisses the dialog

**Comment by cgchoffman** [comment]
I can't repro this on Windows.

**Comment by Naatan** [comment]
Must be a Linux only issue then

**Comment by cgchoffman** [comment]
Just noticed that on OSX a similar but slightly different thing happens.  If I click in the editor (or try to click revert) the dialog will move to have it's top left corner where my cursor is.  It will then close though.  It doesn't remain open.
