### ISSUE TITLE
Slack share should pop up notification allowing user to open shared item in browser

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3149]
### Short Summary

Apparently you're supposed to be able to do that ^^.  I just found the code that does this by accident fixing a different bug.  

### Steps to Reproduce

- OPen a file
- right click > share > Share code Via slack
- Select **Share on Slack**

### Expected results

If it's successfully shared you should see a notification bubble appear that you can click on to open the shared snippet in the browser.

### Actual results

No bubble appears.

**Comment by Naatan** [comment]
"Apparently".. didn't you implement this? :p

**Comment by cgchoffman** [comment]
> "Apparently".. didn't you implement this? :p

I did but "apparently" the notify api changed and `notify/notify.send` doesn't open an interactive bubble any more?  Or maybe it never did and I missed that while testing.  I'm commiting a fix but i'm not putting it in 11.0.1.

**Comment by cgchoffman** [comment]
Fixed here: https://github.com/Komodo/KomodoIDE/commit/f0d1697a14eeafff7581ce8f40abb16fa432613a

Cherry-pick when 11.1 is shipping.

**Comment by Naatan** [comment]
Looks fine for 11.0.1, feel free to push to master.

**Comment by cgchoffman** [comment]
Sounds good: https://github.com/Komodo/KomodoIDE/commit/cca5abb27f24ac94547259081d8447160d833a8f
