### ISSUE TITLE
Pasting into previewable file doesn't trigger preview update

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3150]
### Steps to Reproduce

- open markdown file
- open previewer
- type text and note that preview updates
- cope and paste text into file

### Expected results

preview update

### Actual results

It does not update

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoIDE/commit/801fe6b197bdbd696b8c189ccb743a71f551c8d5

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoIDE/commit/0f37b5a40021905c42069287b2f767df7c6a27e7 and https://github.com/Komodo/KomodoIDE/commit/86b58e4a5504ca7bd83566f7eb735309cc27a6c0,

Originally attempted to fix with https://github.com/Komodo/KomodoIDE/commit/801fe6b197bdbd696b8c189ccb743a71f551c8d5, but used the wrong event name.
