### ISSUE TITLE
Windows: Display file tabs in the titlebar

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#3152]
### Short Summary

title. Firefox does that in 57+ and I like it. Is it possible to move the tabs to the titlebar when e.g. I'm using native decorations?

**Comment by Naatan** [comment]
It's certainly possible, but it's not something we are looking to achieve with our UX. This would have to be implemented in the form of an addon.

**Comment by Defman21** [comment]
Understood. I'll try to implement that as an add-on.

**Comment by Naatan** [comment]
Fair warning, this won't be easy. Tabs are part of the view binding, not to mention you have the split and rotation views to deal with.

**Comment by Defman21** [comment]
Thanks for the tip 😃
