### ISSUE TITLE
Sign License executable for Windows

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#3157]
### Short Summary

On Windows 10, whenever you run the license executable, Microsoft Defender pops out telling you that this executable ain't good or something. I guess since it's not signed in any way (like the Komodo installer), MD assumes the exe may be a virus.

**Comment by Naatan** [comment]
@cgchoffman do you know if we did anything with this in the past?

**Comment by cgchoffman** [comment]
The license installers have never been signed, on any platform, and we don't maintain them.

**Comment by cdcmicro** [comment]
You guys are probably tired of me complaining about code signing, but I think it's a big deal.  The Komodo team seems to think it's optional and a nuisance (OK, it's a PITA to set-up in a cross-platform environment).  IMO, when you skip signing, it looks unprofessional and dings ActiveState's brand.

`<soapbox>`
A respected commercial entity like ActiveState should never deliver compiled executables without a digital signature (DS) for platforms where it's supported/recommended (Windows and Mac).  Especially for its premium paid products like Komodo IDE.  At the very least, the downloaded installer package and license installer exe should carry ActiveState's DS.

Even better is to sign the likes of komodo.exe, ko.exe, and anything else that was compiled at AS.
`</soapbox>`

**Comment by Naatan** [comment]
We are signing our executables, but license installers are a bit of a special use-case.

**Comment by Defman21** [comment]
No longer valid I guess?
