### ISSUE TITLE
Occasional crash on windows 7 while debugging Perl code 

### ISSUE THREAD

**Issue by Roeya** [Komodo/KomodoEdit#316]
Almost every hour I have a crash of Komodo while debugging Perl code

Using Komodo IDE, version 9.0.1, build 87208, platform win32-x86.

Windows 7 sp1

**Comment by Naatan** [comment]
Could you share your error log when the crash happens (before you restart Komodo)?

It's the pystderr.log file - https://community.activestate.com/faq/komodo-profile-structure

**Comment by Roeya** [comment]
I have upgraded to  9.1.0, build 87337 today - and I did not have a crash for several hours...
