### ISSUE TITLE
Code completion is not working for Javascript and node.js scripts

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#3160]
### Short Summary

Code completion is not triggered for function `console`

### Steps to Reproduce

1. Create a javascript file
2. Type `con` and notice there is no `console` option
3. Create a node.js file
4. Type `console.` and notice there is no `console.log` option

See screenshots

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 11.0
*Operating System (and version)?* macOS

### Additional Information

![image](https://user-images.githubusercontent.com/26605593/30877171-c21656f6-a2ad-11e7-997f-76410d224128.png)

![image](https://user-images.githubusercontent.com/26605593/30877196-d52bae08-a2ad-11e7-9d1d-c27dc951ebaf.png)

**Comment by babobski** [comment]
I think it's the same issue as #125 
For me also the console does not autocomplete in js files.

**Comment by Naatan** [comment]
Yep, same issue. Thanks @babobski
