### ISSUE TITLE
Komodo IDE 11 installer "Detecting components" misidentifies installed components

### ISSUE THREAD

**Issue by mjross** [Komodo/KomodoEdit#3162]
### Summary
During the installation of Komodo IDE 11.0.0, on the "Detecting Components" window, the installer claims that my system has many programs and other components installed and that they were detected on the PATH, but most of those identified are not installed at all. In particular, in the "Languages" section, it claims that I have installed Go, Node.js, Perl, and Ruby – even though I don't. It does correctly claim that I have PHP and Python (2 and 3) installed, but only that first one is in my PATH. In the "Tools" section, it claims I have Gocode and Godef installed, but I've never heard of those before. In the "Version Control" section, it claims I have CVS, Perforce, and Subversion installed – but I don't. However, I do have Git installed, but it apparently was not detected. I did not see this problem back when installing Komodo IDE 10.

Here are the directories that comprise my PATH, with each on a separate line for easier reading:
```
C:\Windows\System32
D:\_m\computer\Windows
C:\_a\PHP
C:\_a\MariaDB\bin
C:\_a\ImageMagick
C:\_a\Drush
C:\_a\Drush\tools\bin
C:\_a\Komodo IDE 11\
C:\ProgramData\Oracle\Java\javapath
C:\Program Files (x86)\Intel\iCLS Client\
C:\Program Files\Intel\iCLS Client\
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\Program Files (x86)\Common Files\lenovo\easyplussdk\bin
C:\ProgramData\Lenovo\ReadyApps
C:\Program Files\Intel\WiFi\bin\
C:\Program Files\Common Files\Intel\WirelessCommon\
C:\Program Files (x86)\OpenVPN\bin
C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
C:\Program Files\Intel\Intel(R) Management Engine Components\IPT
```

### Platform Information
Komodo IDE 11.0.0 on Windows 10 Pro

### Attachments
![detecting components 1](https://user-images.githubusercontent.com/829492/30886761-8ee05ffc-a2d5-11e7-8684-df0b449508e0.jpg)
![detecting components 2](https://user-images.githubusercontent.com/829492/30886766-931601ee-a2d5-11e7-8815-73792a07ef64.jpg)
![detecting components 3](https://user-images.githubusercontent.com/829492/30886770-96e3367a-a2d5-11e7-904f-0a3fe0ef3ec1.jpg)
![detecting components 4](https://user-images.githubusercontent.com/829492/30886775-9a5a246c-a2d5-11e7-80af-5815cf6a8d4e.jpg)

**Comment by Naatan** [comment]
Thanks for reporting, this has been addressed in #3107.

**Comment by mjross** [comment]
Sorry. When I did a search, the earlier post didn't appear. I should have tried some variations on the search terms.

**Comment by Naatan** [comment]
Note by default it doesnt show closed issues, you have to click "closed" at the top :)

**Comment by mjross** [comment]
I probably forgot to do that. Thanks. :)
