### ISSUE TITLE
Code completion is not giving all the options for Python script

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#3163]
### Short Summary

Incomplete code completion options for Python script

### Steps to Reproduce

1. Create a python file
2. Type 
```
import os
os.
```
3. See the screenshot for the options

### Expected results

It should give options like `abort, access...`

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 11
*Operating System (and version)?* any

### Additional Information
![image](https://user-images.githubusercontent.com/26605593/30887022-7aa49186-a2ce-11e7-8fa4-fef4c6b8d633.png)

![image](https://user-images.githubusercontent.com/26605593/30887029-7e3ce078-a2ce-11e7-9508-5ca9e7eddad4.png)

 
Customer is getting the following error in the log:

<1506458969> [2017-09-26 14:43:09,415] [WARNING]  codeintel.language.common: filename for import resolver 'PythonImportResolver' does not exist and was not specified by 'FILENAME' environment variable

**Comment by Naatan** [comment]
I think it is giving all completions (see show all at the bottom), it's just giving them in the wrong order.

**Comment by mitchell-as** [comment]
I think this is up your alley @Naatan. The completions are indeed there, it's just a side-effect of sorting. The following patch moves those completions higher up, but I suspect there are other effects in general I'm not accounting for:

```
diff --git a/src/service/__init__.py b/src/service/__init__.py
index f3f5cfa..0227cac 100644
--- a/src/service/__init__.py
+++ b/src/service/__init__.py
@@ -102,9 +102,9 @@ class Service:
         if completions.name_part:
             entries = self._weighed(entries, completions.name_part, path, languageName)
         else:
-            entries = sorted(entries, key=lambda k: k['name'])
+            entries = sorted(entries, key=lambda k: k['name'].lower())
 
-        entries = sorted(entries, key=lambda k: k['source'] == "cix") # Show cix entries last
+        #entries = sorted(entries, key=lambda k: k['source'] == "cix") # Show cix entries last
 
         result["entries"] = entries[:limit]
```

**Comment by mjainQA** [comment]
Even with show all, I don't see all the entries such as `abort`, `access`....

**Comment by mitchell-as** [comment]
Yes, there appears to be some sort of artificial limit of the number of completions shown. But type 'a' and you'll see "abort", "access", etc.

**Comment by Naatan** [comment]
There is a hard limit so as to not affect performance too much. After all it's very unlikely someone would be cycling through 50+ entries rather than just typing another letter.

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/5b5bdbe62c307581349548e154a3db83daffac25
