### ISSUE TITLE
Codeintel: invalid completions

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#3164]
### Short Summary

```python
class MyClass:
    def test():
        print("213")

klass = MyClass()

klass.|
```

### Expected results

`test` in the completions.

### Actual results

`klass` in the completions.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 11
*Operating System (and version)?* Windows 10

### Additional Information

Typing `te` manually gives me the `test` completion.

**Comment by mitchell-as** [comment]
It's possible you typed too fast and the original `klass` completion (from scope) was left over. Try typing a bit slower, and you'll see the proper `test` method completion come up.

**Comment by Defman21** [comment]
I typed `klass.`. Very slowly.

**Comment by Defman21** [comment]
ping @mitchell-as. I disagree that this ain't an issue. I'm able to reproduce in Safe Mode as well.

**Comment by mitchell-as** [comment]
I'm sorry, but this is not an issue. I get the expected behavior on Komodo 11.0.0 build 90668. Our static unit test cases cover code like yours quite well. Any dynamic cases like yours that involve typing are timing anomalies.

**Comment by Defman21** [comment]
Hmm, yeah. That was an anomaly. It's working for me now, but it does not when I press Enter to auto-complete `klass` and then `.` to trigger its auto-completions. Does that work for you, Mitchell?

**Comment by Naatan** [comment]
Note the timing issue is tracked here - https://github.com/Komodo/KomodoEdit/issues/3110
