### ISSUE TITLE
Js lint error in logs when opening JS files

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3173]
### Short Summary

Every time I load a JS file the following error is dumped in the logs:
```
[2017-09-27 16:07:39,040] [ERROR] koJavaScriptLinter: Problem deleting file des(c:\users\cgcho\appdata\local\temp\tmppndgy2.js)
```

There are A LOT of files in my temp dir now.

### Steps to Reproduce

Open a JS file

### Expected results

Nothing in the logs

### Actual results

There is a couple second delay then the above error is dumped to the logs

**Comment by Naatan** [comment]
I can't think of anything that would have introduced this in 11. Are you not seeing this on 10.2.3?

**Comment by cgchoffman** [comment]
No, i've never seen it before.

**Comment by Naatan** [comment]
@cgchoffman I pushed this so we can get more logging info:

https://github.com/Komodo/KomodoIDE/commit/baa31d0a11919250121ad315b1e772752bff4dcc

Please reproduce the issue with above commit included in your build and report back what's being logged.

**Comment by cgchoffman** [comment]
I can't reproduce this any more.  I'll have to keep my eyes open for that error.

**Comment by cgchoffman** [comment]
I hit this again in the latest build.  Here's the error:
```
[2017-10-20 12:57:32,130] [ERROR] koJavaScriptLinter: Problem deleting file des(c:\users\cgcho\appdata\local\temp\tmpwnosbg.js)
Traceback (most recent call last):
  File "C:\Users\cgcho\Komodo IDE 11.0\lib\mozilla\components\koJavaScriptLinter.py", line 363, in lint_with_text
    os.unlink(jsfilename)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\cgcho\\appdata\\local\\temp\\tmpwnosbg.js'
```

**Comment by cgchoffman** [comment]
[pystderr.txt](https://github.com/Komodo/KomodoEdit/files/1403137/pystderr.txt)
Full log here

**Comment by cgchoffman** [comment]
I cant' reproduce this anymore.
