### ISSUE TITLE
Code Intel for namespaced user functions not working in Windows - v11

### ISSUE THREAD

**Issue by orangeaid** [Komodo/KomodoEdit#3174]
### Short Summary
In Komodo IDE 10, typing a backslash would give access to all namespaces, and their functions, in a PHP project - via the code intelligence drop-down list.  However, in order to retain this functionality, I had to frequently re-build the code intel DB.  When I saw that v11 was being advertised as having more stable code intelligence, I went straight ahead and bought a licence upgrade.  However, two days in to working with v11, I have ZERO access to my namespaced functions, and rebuilding the code intel DB has not fixed this.  Therefore, I have no option other than to go back to using v10 - having wasted over $100 on the new licence

### Steps to Reproduce
Create a PHP project with several namespaced function library files.  Use a daisy-chain method of including/requiring all the different namespaced libraries in to a script.  For example, have three library files - liba.php, libb.php, libc.php.  At the top of liba.php have the following line:
namespace libs\liba;
add some functions to this file
at the top of libb.php have the following line:
namespace libs\libb; require_once('liba.php');
add some functions to this file
at the top of libc.php have the following line:
namespace libs\libc; require_once('libb.php');
add some functions to this file.
You will note that libc.php now includes libb.php, which in turn includes liba.php.
Now create a test script - test.php, and at the top of this file have:
require_once('libc.php');
Continue developing for a couple of days, then try typing "\libs\\" (a back-slash, followed by "libs", followed by another back-slash) on a new line. 

(At this point, you should be seeing a code intel list including the namespaces: liba, libb, libc.  However, you do NOT see these namespaces in the list.  In fact when you type the first back-slash you do NOT even see the "libs" top level namespace.  All you see are all the global constants, etc.  In v9, v10, this works as one would expect and want.)

### Expected results
You should see a list containing the three defined namespaces for your three function libraries

### Actual results
You will NOT see your defined namespaces in the code intel auto-complete list, and therefore not be able to drill down to get your library functions, with their associated documentation comments.  Also, if you try re-building your code intel from scratch (via the Help > Troubleshooting > Reset CodeIntel Database), this does NOT solve the issue.

[pystderr.log](https://github.com/Komodo/KomodoEdit/files/1341027/pystderr.log)

### Platform Information
*Komodo Edit or IDE?* 
Komodo IDE
*Komodo Version?* 
11.0.0
*Operating System (and version)?* 
Windows 10 Pro 64 bit

### Additional Information
I only bought the version upgrade licence a couple of days ago.  I cannot be sure whether or not this issue was there from the start, as I cannot be sure that I tried to access namespaced functions via the code intel, before today, or not.  The main reason I decided to buy the upgrade was because of the claims that the code intel was more stable.  However, it seems that it simply doesn't work at all.

**Comment by orangeaid** [comment]
This may be an associated issue, or possibly just another bug in v11: Code Intelligence preferences aren't sticking.  In Edit > Preferences > Code Intelligence > Scanning,  I tried changing two preferences:
 - Max files to scan without prompting
 - Show calltips when typing
After clicking on the "Apply" and then "OK" buttons, and then re-opening the preferences, my changes weren't there!  Therefore it appears that I have NO WAY OF ENABLING the "Show calltips when typing" option!!

**Comment by orangeaid** [comment]
More preferences which don't stick:
- Code Intelligence > Scanning > Max files to scan without prompting

**Comment by mitchell-as** [comment]
Hi, the codeintel issue should be fixed in a forthcoming nightly build. Sorry for the inconvenience.

Related to #3102 

For any preferences not being retained, please open separate issues.

**Comment by orangeaid** [comment]
OK, sorry - I searched for code intel, and could not find any matching existing issues already reported.

**Comment by orangeaid** [comment]
When will the fixed version be released?  Will I be able to get it via the Help > Check for updates... menu option, or do I have to go somewhere to download the latest build?

**Comment by mitchell-as** [comment]
Hi, it should arrive in the coming days. It will be a manual download available here: http://downloads.activestate.com/Komodo/nightly/komodoide/latest/
