### ISSUE TITLE
Komodo crashes when using custom color scheme in startup wizard

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#3176]
### Steps to Reproduce

 1. Install attached color scheme
 2. Run the startup wizard
 3. Select the color scheme
 4. Finish startup wizard

### Expected results

Nothing special

### Actual results

Komodo crashes

[new.ksf.txt](https://github.com/Komodo/KomodoEdit/files/1341452/new.ksf.txt)

**Comment by mitchell-as** [comment]
I am not able to reproduce on master.

1. Start with a clean profile (go through first start wizard once).
2. File > Open, select "new.ksf".
3. Komodo asks to install the scheme, pick "Ok", and then decline to apply it.
4. Help > Run First Start Wizard.
5. Select the "new.ksf" scheme and continue through the wizard.
6. No crash. Nice new scheme.

**Comment by Naatan** [comment]
I can no longer reproduce, think this was fixed in https://github.com/Komodo/KomodoIDE/commit/329fa23306e49560b894f90726e5f36817fa0738
