### ISSUE TITLE
Komodo 11 do not read my additional auto-completion catalog

### ISSUE THREAD

**Issue by kevinlieser** [Komodo/KomodoEdit#3178]
### Summary

I have an catalog.xml with the following content:

```
<?xml version='1.0'?>
<catalog xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog" prefer="public">

<public publicId="-//W3C//DTD HTML 5//EN" uri="html5-fluid-vhs.dtd"/>
<system systemId="http://www.w3.org/TR/html5" uri="html5-fluid-vhs.dtd"/>
<uri name="http://www.w3.org/TR/html5" uri="html5-fluid-vhs.dtd"/>

</catalog>
```

It "overrides" the original HTML5 catalog with the DTD file I have created including HTML5, TYPO3 Fluid and TYPO3 VHS Viewhelpers. That catalog works fine on Komodo 10 but do nothing on Komodo 11.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 11.0.0
*Operating System (and version)?* macOS Sierra, now High Sierra 10.13.

### Additional Information

Attached the both files to integrate in the Settings -> Languages -> XML Catalogs which works fine in Komodo 10, but not in Komodo 11.

[Archiv.zip](https://github.com/Komodo/KomodoEdit/files/1342389/Archiv.zip)

**Comment by Naatan** [comment]
Thanks for the report. We are tracking this issue here:

https://github.com/Komodo/KomodoEdit/issues/2774

It will be resolved in Komodo 11.1.
