### ISSUE TITLE
Code intel scan stuck at 99% after updating paths in pref -> languages -> python

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#3181]
### Short Summary

Customer reported that the code intel scan is stuck at 99% after updating paths in pref -> languages -> python

### Steps to Reproduce

1. Add custom path to pref -> languages -> python

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 11.0
*Operating System (and version)?*

**Comment by Naatan** [comment]
I'll need more exact reproduction steps. This is not as simple as just adding a custom path.

**Comment by cgchoffman** [comment]
I asked @mjainQA to file this and I believe there is more information coming from the customer including logs and files being scanned, correct @mjainQA?  I'm going to reopen for that reason but of course if we don't get that information we should close this.

**Comment by mjainQA** [comment]
Yes, the customer was informed about this ticket and asked to provide more info.

http://otrs.activestate.com/otrs/index.pl?Action=AgentTicketZoom;TicketID=68151

**Comment by Naatan** [comment]
@mjainQA still waiting for more info on this.

**Comment by GrahamStuart** [comment]
Is this similar to #3163 ?

Reply is in Support ticket. Error messages are similar to #3163 
--------------------------
... here’s my codeintel log
 
<1506737863> [2017-09-29 19:17:43,963] [INFO]  codeintel.db.database: Database initialized
<1506737863> [2017-09-29 19:17:43,963] [INFO]  codeintel.scanner: Starting threaded file scanner.
<1506737863> [2017-09-29 19:17:43,963] [DEBUG]  SocketServer: Initializing SocketServer
<1506737863> [2017-09-29 19:17:48,871] [INFO]  Server: Started CodeIntel server on port: 57438, pid: 28776
<1506737863> [2017-09-29 19:17:48,878] [DEBUG]  SocketServer: Starting handle loop
<1506737863> [2017-09-29 19:17:54,760] [DEBUG]  service: Summarizing C:\Users\xray\AppData\Local\ActiveState\KomodoIDE\10.1\samples\python_tutorials, X:\tech_art\houdini\houdini16.0\python2.7libs, C:\Program Files\Side Effects Software\Houdini 16.0.667\houdini\python2.7libs, depth: 10
<1506737863> [2017-09-29 19:17:58,137] [DEBUG]  service: Scanning C:\Users\xray\AppData\Local\ActiveState\KomodoIDE\10.1\samples\python_tutorials, X:\tech_art\houdini\houdini16.0\python2.7libs, C:\Program Files\Side Effects Software\Houdini 16.0.667\houdini\python2.7libs, depth: 10
<1506737863> [2017-09-29 19:18:04,638] [DEBUG]  service: Getting completions for False at pos 2
<1506737863> [2017-09-29 19:18:04,638] [WARNING]  codeintel.language.common: filename for import resolver 'PythonImportResolver' does not exist and was not specified by 'FILENAME' environment variable
<1506737863> [2017-09-29 19:18:06,035] [DEBUG]  service: Getting completions for False at pos 5
<1506737863> [2017-09-29 19:18:06,035] [WARNING]  codeintel.language.common: filename for import resolver 'PythonImportResolver' does not exist and was not specified by 'FILENAME' environment variable
<1506737863> [2017-09-29 19:18:07,015] [DEBUG]  service: Getting completions for False at pos 8
<1506737863> [2017-09-29 19:18:07,016] [WARNING]  codeintel.language.common: filename for import resolver 'PythonImportResolver' does not exist and was not specified by 'FILENAME' environment variable
<1506737863> [2017-09-29 19:18:09,759] [DEBUG]  service: Getting completions for False at pos 12
<1506737863> [2017-09-29 19:18:09,759] [WARNING]  codeintel.language.common: filename for import resolver 'PythonImportResolver' does not exist and was not specified by 'FILENAME' environment variable
<1506737863> [2017-09-29 19:18:09,961] [DEBUG]  service: Getting completions for False at pos 14
<1506737863> [2017-09-29 19:18:09,963] [WARNING]  codeintel.language.common: filename for import resolver 'PythonImportResolver' does not exist and was not specified by 'FILENAME' environment variable
---------------------------------------

**Comment by Naatan** [comment]
No, completely different. One is about auto completions, the other is about scanning.

**Comment by mjainQA** [comment]
Customer hasn't responded - please feel free to close the ticket.
