### ISSUE TITLE
Code Intelligence Scanning settings input not functioning properly

### ISSUE THREAD

**Issue by lagbox** [Komodo/KomodoEdit#3184]
### Short Summary

1) Changes to 'Maximum directory depth for scanning' or 'Max files to scan without prompting' in the Code Intelligence preferences do not persist. 

2) The ability to increase and decrease the value via the up and down buttons only allows 1 in either direction from the current value.

### Steps to Reproduce

1)
Open Preferences -> Code Intelligence -> Scanning (section)
Set scan 'Maximum directory depth' or 'Max files to scan without prompting' to anything other than what it currently is set as.
Click Okay.
Reopen the preferences.

2)
Use the arrows on the input to increase or decrease the value by more than 1. 

### Expected results

1) Settings to persist.

2) Input to be able to increase or decrease the value by more than 1.

### Actual results

Settings do not persist.
Inputs do not allow increasing or decreasing more than 1 from the current value.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 11.0.0, build 90668, platform linux-x86_64
*Operating System (and version)?* Ubuntu 17.04

### Additional Information

Have tried this after a complete reset (Help -> Troubleshooting -> Reset Everything) of Komodo and still have the same issue.

Also not sure what 'Rescan' does when the scanning dialogue comes up when a confirmation is needed due to the 'Max files to scan without prompting' limit is reached.

**Comment by cgchoffman** [comment]
Thanks for the report @lagbox, tracking this here #3175
