### ISSUE TITLE
Unable to Right click refresh status

### ISSUE THREAD

**Issue by codermjb** [Komodo/KomodoEdit#3186]
### Short Summary
Unable to Right click refresh status for a folder, you have do Ctrl + k, R, it is greyed out.

### Steps to Reproduce
Right Click on a folder and try to refresh status.

### Expected results
Option to not be greyed out, to be able to refresh folder

### Actual results
Option Greyed out

### Dev Note

Issue is that we folded refresh view into refresh status, but refresh status has a more restrictive "disabled" state. We should just always show "refresh state".

**Comment by Naatan** [comment]
What version control system are they under? Does this happen on all folders or just some?

**Comment by mjbrancato** [comment]
It's not under version control, it's on the Remote FTP paths. This feature worked in all previous Komodo's. I would send a screenshot, but Lightshot doesn't support context menus.

**Comment by Naatan** [comment]
I just launched Komodo 10 to check this and refresh status is greyed out there too. To my knowledge this is for local files, particularly files under version control. Are you certain you've had this work on remote files? Maybe you're thinking of published files?

**Comment by mjbrancato** [comment]
My apologies, it was Refresh View and it looks like that feature is removed. So if a server gets a file added, I can't right click and refresh the view. I have to change the folder, close the IDE, then reopen, then reopen the folder to refresh the view?

**Comment by Naatan** [comment]
Ahhh I see. We have folded this into the "Refresh Status" menuitem, but it seems we did not update the disabled state for that item. Thanks for clarifying!

**Comment by mjbrancato** [comment]
@Naatan I understand now. In Komodo 10 it was sometimes confusing on which to choose (When both options were available so I can see why it is better to merge), but yes, it would be nice to refresh. And thank you.

**Comment by codermjb** [comment]
I am still unable to Refresh Status on a remote folder with the latest 90775 build in Linux.

**Comment by codermjb** [comment]
Screenshot of Build info: http://prntscr.com/gwqg51
Screenshot with option disabled: http://prntscr.com/gwqgit

**Comment by Naatan** [comment]
That's strange, I didn't see any other code that would disable it. Will have another look.

**Comment by codermjb** [comment]
This looks like it will be it (your commit), I will let you know on next build. Thank you.

**Comment by codermjb** [comment]
Verified working on Komodo IDE, version 11.0.1, build 90784, platform linux-x86_64. Built on Fri Oct 13 09:20:33 2017.

Thank you!

**Comment by cgchoffman** [comment]
@Edward-Jong,  remote directory is not a network mounted folder in this context.  A remote folder is a folder you've opened through the Places pane > Gear menu > Open Remote Folder.

**Comment by cgchoffman** [comment]
Thanks for double checking Edward.

**Comment by maxgrenderjones** [comment]
Until 11.0.1 is released, is there a workaround other than restarting komodo?

**Comment by codermjb** [comment]
Komodo IDE nightly builds.

It is fixed there and I verified the fix by Komodo.

http://downloads.activestate.com/Komodo/nightly/komodoide/latest/

**Comment by Naatan** [comment]
11.0.1 IS released :)

https://www.activestate.com/blog/2017/10/komodo-ide-11-01-released

**Comment by codermjb** [comment]
Awesome! I recieved an OTA update yesterday too, but wasn't sure if that
was nightly build updating since I am on the nightly build releases!

Great job Komodo Team!

**Comment by maxgrenderjones** [comment]
Exciting - thanks! In my limp defence, I thought it wasn't released yet as milestone 11.0.1 is showing as 98% complete with no date (so close!)

**Comment by Naatan** [comment]
Thanks for reminding me, I will go ahead and close that milestone :)
