### ISSUE TITLE
Match variable does not work when variable selected

### ISSUE THREAD

**Issue by mjbrancato** [Komodo/KomodoEdit#3187]
### Short Summary
Single Click on Variable: http://prntscr.com/gr1ice
Double Click or variable selected: http://prntscr.com/gr1igy
Komodo 10 had this feature

### Steps to Reproduce
Select a variable that is the same as another variable

### Expected results
All variables highlight

### Actual results
No variables highlight

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 11
*Operating System (and version)?* Xubuntu 16.0.4.2 LTS

**Comment by mitchell-as** [comment]
Hi, thanks for the report.

Note to self: this is likely due to the new word highlighting in lieu of codeintel highlighting. (editor.js)

**Comment by Naatan** [comment]
The bug here is that the highlight word workaround we implemented isnt working.

https://github.com/Komodo/KomodoIDE/commit/4533cb2fb07da5a902ec2cf1163b968c9fd08210

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoIDE/commit/e40c845cdb4324905abdc22768bf246e5e17b76c
