### ISSUE TITLE
Komodo 11 loses individual file language specifications

### ISSUE THREAD

**Issue by DEklof** [Komodo/KomodoEdit#3197]
### Short Summary
Please fill out the requested fields to the best of your ability.

### Steps to Reproduce
Open file with extension that is not in the file associations preferences but is defined at the file level as PERL in Komodo 10.

### Expected results
Still PERL

### Actual results
Now Text.

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?*

**Comment by cgchoffman** [comment]
Hi @DEklof, we're tracking that here: https://github.com/Komodo/KomodoEdit/issues/3180
