### ISSUE TITLE
Komodo sets colour scheme to 3024 if no scheme chosen in wizard

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3198]
### Steps to Reproduce

- Start Komodo with fresh profile
- Run through wizard and do not change the colour scheme selection, it will be **Default** (should be if you're starting with a fresh profile)
- When done the wizard, open prefs
- It should be open to the Appearance prefs, notice that 3024 is set for the colour scheme
- Don't change anything in the prefs, just click ok

### Expected results

Nothing to happen

### Actual results

Colour scheme changes

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 

### Additional Information

```
Traceback from ERROR in 'prefs' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:411:27
    koPrefWindow.prototype._setElementFromPrefValue@chrome://komodo/content/pref/koPrefWindow.js:595:1
    koPrefWindow.prototype.onpageload@chrome://komodo/content/pref/koPrefWindow.js:1083:13
    PrefUi_OnLoad@chrome://komodo/content/pref/pref-ui.js:203:5
    onload@chrome://komodo/content/pref/pref-ui.xul:1:1

[2017-09-29 16:31:32,293] [ERROR] prefs: 
-- EXCEPTION START --
Error: Invalid preference
+ stack
    koPrefWindow.prototype._setElementFromPrefValue@chrome://komodo/content/pref/koPrefWindow.js:598:1
    koPrefWindow.prototype.onpageload@chrome://komodo/content/pref/koPrefWindow.js:1083:13
    PrefUi_OnLoad@chrome://komodo/content/pref/pref-ui.js:203:5
    onload@chrome://komodo/content/pref/pref-ui.xul:1:1
-- EXCEPTION END --
```

**Comment by cgchoffman** [comment]
Looks like the wizard is setting an empty string for the pref rather than `Default`

**Comment by cgchoffman** [comment]
i can't reproduce this on master or in a nightly any more.

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/377a3124b0a2e3a706b661a643e973cf02156a81
