### ISSUE TITLE
Komodo process not killed after exit when preferences window opened

### ISSUE THREAD

**Issue by mathew85** [Komodo/KomodoEdit#32]
Komodo Edit, version 9.0.0-rc1, build 15647, platform win32-x86.
Built on Fri Mar 06 11:31:40 2015.

1. Open Preferences window
2. Exit Komodo
3. Close Preferences window

Komodo process is not exited.

There was problem with my configuration. Issue closed.

**Comment by cgchoffman** [comment]
Hey matthew, any feedback on the immediate close?  This was an issue (though unrelated to prefs I believe) at one point so if it might be back we would like to know.
