### ISSUE TITLE
Project preferences screen aslo sized improperly

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3201]
![afbeelding](https://user-images.githubusercontent.com/3530262/31044202-1eb1067a-a5cb-11e7-9d54-e5f6f309c5a1.png)

### Short Summary
Also the Project preferences is sized improperly.
Made a [screen-recording](http://youtu.be/aV4SnH1QVZw?hd=1) to show the issue, the window is opened at it's min height.
Also #2864 is not fixed.
The resize button is a still not working and gives me the same error:

```
[2017-09-30 10:39:08,707] [ERROR] console-logger: TypeError: this._getRequireMethod is not a function (2) in chrome://komodo/content/bindings/windows.xml:358
Traceback (most recent call last):
  File "chrome://komodo/content/bindings/windows.xml", line 358, in 
```

### Platform Information
Komodo IDE, version 11.0.0, build 90668, platform win32-x86

**Comment by Naatan** [comment]
Thanks, this is already fixed in the same commit that fixed the regular pref screen and the color picker :) Nightly should be available today.
