### ISSUE TITLE
Symbol browser css media queries 

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3209]
![afbeelding](https://user-images.githubusercontent.com/3530262/31046497-ade577ee-a5f9-11e7-905c-4650c0701cee.png)

![afbeelding](https://user-images.githubusercontent.com/3530262/31046517-16915182-a5fa-11e7-9445-8d8515d5c846.png)

### Short Summary
css media queries are not working well in the symbol browser.
Also I think it should have it's own symbol, and the value defined for the media query should be shown.

### Platform Information
Komodo IDE, version 11.0.0, build 90668, platform win32-x86

### Additional Information

[Possible media queries](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries)

**Comment by Defman21** [comment]
I guess it's a codeintel problem, so #1900

**Comment by mitchell-as** [comment]
Indeed, thanks for the link @Defman21.
