### ISSUE TITLE
Track Changes popup chases/runs away from the mouse

### ISSUE THREAD

**Issue by damienprystay** [Komodo/KomodoEdit#3213]
After clicking on a highlighted section of the change tracking bar to get a popup with the diff of that change, the next time I click within the editor, the popup will relocate itself to the location of the new click.

This results in not being able to click on the `Revert Changes` or `Share` buttons initially, because the chosen button is no longer under the mouse by the time I've clicked. Once the popup has moved this way once, the buttons can then be reached. (However, sometimes the popup immediately disappears after moving, apparently dependent on whether the mouse cursor is inside or outside of it on mouseup.)

This also means that even if you're just looking at the diff without wanting to use one of the buttons on it, dismissing the popup requires clicking away from it twice instead of once.

Komodo IDE 11.0.0 build 90668
Mac OS X 10.11.6

**Comment by Naatan** [comment]
This was handled in #3147. Will be in tomorrows nightly.
