### ISSUE TITLE
File > New > PHP.php not working

### ISSUE THREAD

**Issue by orangeaid** [Komodo/KomodoEdit#3216]
### Short Summary
When attempting to create a new file via the menu selection:
File > New > PHP.php
Nothing happens

### Steps to Reproduce
Open Komodo IDE, slelect:
File > New > PHP.php
from the menu

### Expected results
A new file should be opened in the editor

### Actual results
Nothing happens.
( File > New > HTML 5.html doesn't work either )

### Platform Information

*Komodo Edit or IDE?* 
Komodo IDE
*Komodo Version?* 
11.0.1 nightly
*Operating System (and version)?* 
Windows 10 Pro 64bit

**Comment by mitchell-as** [comment]
Hi, those menu options do not exist. Did you mean File > New > File from Template..., and then select a PHP or HTML 5 template? If so, I cannot reproduce this. Does it work for you in Safe Mode? (Help > Troubleshooting > Restart in Safe Mode), also your Help > Troubleshooting > View Log File may be of help after triggering the issue.

**Comment by orangeaid** [comment]
I beg to differ - please see screen-shot clip:
![menu](https://user-images.githubusercontent.com/16290586/31140816-8ab374c6-a86d-11e7-9a91-cbe3fed4b75f.jpg)

**Comment by Naatan** [comment]
Ah, this appears to be leftover from Komodo 10, is imported an MRU that is no longer supported. The issue here is that it shows those at all.

**Comment by orangeaid** [comment]
Yes - I guess I should add that currently I have 3 different versions of Komodo IDE installed:
9.3
10.2
11.01 nightly
I am not sure if there is any possibility of any interaction between versions or not.  I am currently using v10.2, as the recent nightly vor v11 has not fully fixed the code intel problems I reported in a previous issue #3174  I will create a new ticket for this at the weekend, with a set of test scripts that I will upload - for clarity.

**Comment by orangeaid** [comment]
P.S. Let me know if you still want me to try Safe Mode, or send you my logs.  Thanks - Simon

**Comment by Naatan** [comment]
No worries, I know what the problem is :) Thank you.
