### ISSUE TITLE
Sample snippets don't have a language field set

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#3218]
None of the sample snippets we provide have a language field set.

Note fixing this will only fix it for people that install Komodo once the fix has landed. We should think about writing some upgrade code that retroactively applies the language field.

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/dfd46c22317bc3aa5c1571295521f8c321db55ed
  This will upgrade any existing installs to work and it will upgrade tools shipped with Komodo as well.
