### ISSUE TITLE
Language attribute for imported abbreviations is not set to the correct language

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3219]
![caf95ede3f5460ed0dd91de5e0cd4c78956c0586](https://user-images.githubusercontent.com/3530262/31134983-05bb03a0-a864-11e7-82d6-6650bd0eec62.png)

### Short Summary
The language attribute is not set correctly when old folders are imported from previous komodo installation. As mentioned on the [forum](https://community.komodoide.com/t/how-do-i-use-abbreviations/3890/15), this will cause the "Insert Abbreviation Snippet by name" to fail.

For Edit I only had Komodo 8.5 installed, after I installed Komodo 11 the samples 8.5 folder is copied over.

![740d277130c80de97e76f013c68e05485cddff03](https://user-images.githubusercontent.com/3530262/31134896-bb66085e-a863-11e7-8cd1-1e7cd142fd91.png)

only the language attribute is not set, causing the "Insert Abbreviation Snippet by name" to fail (and probability also the auto abbreviations). There is also no other abbreviations folder.

If I look at the abbreviation snippet, the language is not set:

![7debcb3ea00ce0c0abd2651c2df96c984ae416d3](https://user-images.githubusercontent.com/3530262/31135443-4adfc870-a865-11e7-9213-430c54f95c69.png)

### Steps to Reproduce
* Clean your profile folder
* Install Komodo 8.5 (edit)
* Install Komodo 11 (edit)

### Work around
Select the correct language for the abbreviations.

### Platform Information
Komodo Edit, version 11.0.0, build 18063, platform win32-x86.

### Additional Information
I was testing out the following work around I think should work, but it doesn't. 

Download the latest Komodo Edit Source from [here](https://github.com/Komodo/KomodoEdit)
Download the zip and unzip it:

![ddca7300eb3f43607213f435f7e63bd68df2aba8](https://user-images.githubusercontent.com/3530262/31135680-0fd2e090-a866-11e7-836a-2d04e35765d0.png)

Remove the old samples folder.
And use the import function to import the new Abbreviations folder from you're latest Komodo Edit download:

![683f21ea5ec6a9212b4bd6009b34d1ef2309b0bb](https://user-images.githubusercontent.com/3530262/31135690-197caf68-a866-11e7-8477-d5e55c4c41a8.png)

https://github.com/Komodo/KomodoEdit/tree/master/src/samples/tools/Abbreviations

After the import the the structure looks good:

![cc262239bd2675497317e293aa236335a2bd2688](https://user-images.githubusercontent.com/3530262/31135706-21a803c2-a866-11e7-84e0-b42a59d021fe.png)

Only it did not set the languages correctly, causing the "Insert Abbreviation Snippet by name" to still fail.

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/dfd46c22317bc3aa5c1571295521f8c321db55ed
This should be fixed in the latest nightly: http://downloads.activestate.com/Komodo/nightly/komodoide/latest-master/
Shouldn't require anything but starting up Komodo. I had to re-implement the upgrade code that adds the language field as it wasn't compatible with the new Toolbox tool format.
