### ISSUE TITLE
Komodo requires version 2.24 or greater (GTK Error)

### ISSUE THREAD

**Issue by codermjb** [Komodo/KomodoEdit#3227]
### Short Summary
Install script shows error. I honestly want to ensure my pre-reqs are fine. It did say ignore if you have it installed, but just wanted to make sure.

`2017-10-02 23:16:41,317: WARNING: install: It appears that either your system does not have gtk-2.0 installed, or your system's version of gtk-2.0 is not up to date.
Komodo requires version 2.24 or greater. Please update gtk-2.0. While Komodo will still install correctly, it may not run.
This diagnostic is not fool-proof. If you are sure the package is installed and up to date, you may safely ignore this warning.
2017-10-02 23:16:51,895: WARNING: install: It appears that either your system does not have gtk-2.0 installed, or your system's version of gtk-2.0 is not up to date.
Komodo requires version 2.24 or greater. Please update gtk-2.0. While Komodo will still install correctly, it may not run.
This diagnostic is not fool-proof. If you are sure the package is installed and up to date, you may safely ignore this warning.`

GTK 2.24 installed: http://prntscr.com/gt0qq4

### Steps to Reproduce
See above

### Expected results
Warning message doesn't show

### Actual results
Warning message shows

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 11.0.1 nightly
*Operating System (and version)?* Xubuntu 16.0.4.2 LTS

**Comment by mitchell-as** [comment]
Hi, the key here is "this diagnostic is not fool-proof". With Linux systems it's sometimes really hard to tell if something is installed or not.

**Comment by codermjb** [comment]
>Hi, the key here is "this diagnostic is not fool-proof". With Linux systems it's sometimes really hard to tell if something is installed or not.

I understand that :-) , I just wanted to make sure I have everything setup on the system right since I never had that message with 9 and 10. I can look at the install.sh script later to see if I can put any recommendations for the script for that check.

**Comment by codermjb** [comment]
This might work too: pkg-config --modversion gtk+-2.0
http://prntscr.com/gtavcz

And if it doesn't show 2.24 and above, then show message. Works in CentOS and Ubuntu.

**Comment by mitchell-as** [comment]
That is true, but assumes the machine has `pkg-config`, which is a separate program, installed.

**Comment by codermjb** [comment]
@mitchell-as I agree, I thought so. I just wish I could help with that, even though it's negligible. I know it's default install on CentOS and Ubuntu (pkg-config) unless if they modified it. What is the gdk_check from? I wonder if there are 3rd party apps that can be used.

**Comment by mitchell-as** [comment]
We wrote gdk_check in order to minimize dependence on 3rd party software during installation.

**Comment by codermjb** [comment]
@mitchell-as that is awesome, that explains why I couldn't find it. Do you have the raw code for it if you wanted to share it?

This is petty, I do know that. But, I want to contribute even if it's 10 hours to do the smallest thing, that is a good start for me.

**Comment by Naatan** [comment]
@codermjb the best way to contribute is to just create addons, userscripts, etc and share them with the community :) We can take care of Komodo, but we cannot build a community on our own.

https://community.komodoide.com/packages/submit-instructions/#pane-packages

**Comment by codermjb** [comment]
@Naatan thank you! I will do that. I actually created a repo last night, but I will update and abide by that link!

Here is what I have so far: https://github.com/MJBCode/Komodo-Mods
