### ISSUE TITLE
Go to definition doesn't work

### ISSUE THREAD

**Issue by mikhalenia** [Komodo/KomodoEdit#3228]
I've installed Komodo IDE 11 and found some bugs with definition links.

All tests I've done on the Safe-Mode.

1. Doesn't work Go to definition by Ctrl+Click.
**Steps to Reproduce**: Press Ctrl and Click to any variable/class/function
**Expected results**: Go to definition of variable/class/function
**Actual results**: Set many cursors

2. Doesn't work Go to definition by Ctrl+K, Ctrl+G (by default key settings) when it's a variable
**Steps to Reproduce**: Set cursor near the variable (no matter where in the end or in the start) and do Ctrl+K, Ctrl+D
**Expected results**: Go to definition of variable
**Actual results**: Could not find definition

3. Doesn't work DevDocs searcher by base functions in any language files
**Steps to Reproduce**: Download and enable a dictionary for PHP in DevDocs, write simple program on PHP using function microtime, set cursor near using this function and do Ctrl+K, Ctrl+G
**Expected results**: Opened DevDocs with suggested variant by microtime
**Actual results**: No results, but if you type yourself microtime in DevDocs - it works

4. Doesn't show a short information widget about any variable/class/function when I do Ctrl+mouseover
**Steps to Reproduce**: Do Ctrl+mouseover on some variable/class/function
**Expected results**: It shows a widget with short information about ariable/class/function
**Actual results**: Nothing shows

**Platform Information**:

It's Komodo IDE 11 on Ubuntu 15.10.

**Additional Information**
I've got two versions of Komodo on my computer at the same time: Komodo 10 and 11 but all this points works only on 10 Komodo.

Please check it. Thx.

**Comment by mitchell-as** [comment]
Please re-file individual tickets for each of your bugs. We cannot do more than one issue per ticket. Also, we need concrete code/steps to trigger the problem. "It doesn't work" is not good enough for us to determine exactly what is wrong.

**Comment by mikhalenia** [comment]
1. https://github.com/Komodo/KomodoEdit/issues/3240
2. https://github.com/Komodo/KomodoEdit/issues/3241
3. https://github.com/Komodo/KomodoEdit/issues/3243
4. https://github.com/Komodo/KomodoEdit/issues/3244
Done.
