### ISSUE TITLE
Use font stack for color schemes

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3229]
### Short Summary
This I had laying on the shelf for a while, but I noticed when you create you're custom colorschemes.
The font is not set as a font stack.

I discovered this a while ago when I was over by my sister.
I was installing Komodo X there but noticed the font was failing, because I used the "Consolas" font, but this is only limited to Windows.

It would be better to use a font stack, so color schemes don't get broken when they are shared over different platforms.

### Platform Information

Komodo IDE, version 10.2.3, build 89902, platform win32-x86

**Comment by Naatan** [comment]
You can use font stacks, but you have to manually edit the ksf file to add them. Our color scheme editor does not allow you to input multiple font names.

**Comment by babobski** [comment]
@Naatan I looked at the `koScintillaSchemeService` lately, but I noticed the [`getFont`](https://github.com/Komodo/KomodoEdit/blob/d0fe723a7d39d08a207b8d45a94bd12cb756b039/src/schemes/koScintillaSchemeService.p.py#L630) functions has a boolean for the use as font stack. If you look at the function it will generate a font stack if not supplied.

I don't want to manually add a font stack, I was hoping Komodo could use a font stack as default.

**Comment by Naatan** [comment]
That just determines whether it should preserve the font stack or whether it should extrapolate the effective font from the stack. It does not create a stack.

There is no automated way of generating a font stack, this is something that is determined by the developer.

**Comment by babobski** [comment]
ah you're correct, was misreading the code. Thought it was going in the [else](https://github.com/Komodo/KomodoEdit/blob/d0fe723a7d39d08a207b8d45a94bd12cb756b039/src/schemes/koScintillaSchemeService.p.py#L655) and generating a font stack.
