### ISSUE TITLE
ctl-delete does not delete one word forward in Komodo 9

### ISSUE THREAD

**Issue by shawnlaffan** [Komodo/KomodoEdit#323]
In Komodo 8 one can press control-delete to delete one whole word ahead of the cursor.  This seems to be missing from Komodo 9.  Control-backspace still works, though.  

I use this ctl-delete frequently, so it would be nice to have it back.

I am using Komodo IDE on Windows.

Shawn.

**Comment by Naatan** [comment]
Still works fine for me, try setting the keybinding set to "Default" under Prefs > Keybindings.

**Comment by shawnlaffan** [comment]
Thanks for the tip.  

I just checked and it was set to default already.  

Looking into the settings, "Delete word right" is set to None under the Default scheme.  I've added it to a new scheme so have it working now, but am curious why it was missing in the first place.  

I've had multiple versions of ko9 installed on this machine, including alpha versions.  Possibly its absence is a left-over from a previous install.  

Shawn.

**Comment by shawnlaffan** [comment]
After a bit of further poking, the default scheme file contains no entry for cmd_deleteWordRight.

File loc is C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\support\schemes\Default.kkf

**Comment by Naatan** [comment]
Bah you're right, it exists on Mac/Emacs but not on Windows/Linux default. I've added it so should be in the next release. Thanks for reporting!

**Comment by shawnlaffan** [comment]
Thanks for fixing it.

Shawn.
