### ISSUE TITLE
Codeintel: Some kinds of Python3 type hints result in "No symbols found"

### ISSUE THREAD

**Issue by mamrhein** [Komodo/KomodoEdit#3232]
### Short Summary
The following kinds of type hints result in a parsing error, which silently leads to a "No symbols found" message:

- Using parametrized generic types as return type hint

- Using a string as return type hint

 

### Steps to Reproduce
Example 1:
```
from typing import List
class IntList(List[int]):
    def __new__(cls) -> List[int]:
        return []
```
Example 2:
```
class MyClass:
    def __copy__(self) -> 'MyClass':
        return self
```

### Expected results
Symbols listed in code browser.

### Actual results
Message "No symbols found".

### Platform Information

*Komodo IDE* 
*Komodo Version 11.0* 
*Linux (Gentoo / KDE Plasma 5.10)*

**Comment by mitchell-as** [comment]
Unfortunately we do not support type hinting yet. Hopefully this will change in the future.

**Comment by mamrhein** [comment]
"Unfortunately we do not support type hinting yet."
Ok. But why do some type hints break the code browser while others do not?

**Comment by mitchell-as** [comment]
At this time we depend on Python 2's source code parser, which can sometimes look past Python 3's type hints, and sometimes not.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/codeintel/commit/1678c1d1e40e44ed339f2f6c6bbf5467cf14b9c9.

**Comment by mitchell-as** [comment]
I forgot that we have a workaround for this and other Python 3 syntax we do not support at the moment. Now instead of seeing "no symbols found", you will see your symbols.
