### ISSUE TITLE
Komodo 11.0.0 and 11.0.1 using up all CPU processes on Linux Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by edwardjong2** [Komodo/KomodoEdit#3233]
### Short Summary
Komodo 11.0.0 and 11.0.1 using up all CPU processes on Linux Ubuntu 16.04 LTS

### Steps to Reproduce

Start up Komodo 11.0.0 and 11.0.1 on Linux Ubuntu 16.04 LTS.  
Start the System Monitor 
Wait several minutes.
The Komodo screen will turn black.
On the System Monitor, with the Processes tab will show that the komodo is using up all the CPU processes.
I have to kill the Komodo process on the System Monitor, otherwise the Ubuntu will react slowly.

### Expected results
Komodo 11.x should work like Komodo 10.  It does not consume all the CPU processes.

### Actual results
The Komodo screen will turn black.
On the System Monitor, with the Processes tab will show that the komodo is using up all the CPU processes.

### Platform Information
*Komodo Edit or IDE?* 
Komodo IDE
*Komodo Version?* 
11.0.0  11.0.1
*Operating System (and version)?* 
Linux Ubuntu 16.04 LTS.
### Additional Information

 
![screenshot from 2017-10-04 08-59-00](https://user-images.githubusercontent.com/29902530/31186222-e7c8c88a-a8e2-11e7-9c56-a1d13498f9fc.png)

[unnamed-1507135112530.cleo.txt](https://github.com/Komodo/KomodoEdit/files/1356655/unnamed-1507135112530.cleo.txt)

[koprofile.txt](https://github.com/Komodo/KomodoEdit/files/1356676/koprofile.txt)

**Comment by Naatan** [comment]
Turns out this is not so much a crash as much as it is his system running out of memory. Relevant issues logged here:

https://github.com/Komodo/KomodoEdit/issues/3237
https://github.com/Komodo/KomodoEdit/issues/3238
