### ISSUE TITLE
Doesn't work Go to definition of PHP variable by Ctrl+K, Ctrl+G

### ISSUE THREAD

**Issue by mikhalenia** [Komodo/KomodoEdit#3241]
### Short Summary
When I focus on some PHP variable in Komodo IDE 10 and press Ctrl+K, Ctrl+G (by default key settings) it goes to definition of this variable but it doesn't work on Komodo IDE 11.

### Steps to Reproduce
1. Open Komodo IDE 11
2. Create simple PHP file which contents some variable
```
<?php

$a = 1;

var_dump($a);
```
3. Focus on $a on 5 line and press Ctrl+K, Ctrl+G

### Expected results
Maybe It has to go to definition of variable like in Komodo IDE 10.

### Actual results
I see a message "Could not find definition".

### Platform Information
Komodo IDE 11
It's reproduced on Ubuntu 15.10 and Mac OS Sierra 10.12.6

### Additional Information
I've got two versions of Komodo IDE on my computer at the same time: Komodo IDE 10 and Komodo IDE 11. It's reproduced on Safe-Mode of Komodo.

**Comment by cgchoffman** [comment]
I can't get it to work in this example either.

**Comment by Naatan** [comment]
You are invoking go to definition on the definition itself :) The message you are getting is appropriate I'd say, though I guess it could say "already at definition".

**Comment by Naatan** [comment]
Reproduced. Seems to work on Komodo 10.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/codeintel/commit/0520d13a11a6f1dd9bed406f363b24844d730e32
