### ISSUE TITLE
Go to Def not working in a Python class

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3245]
This works in K 10
### Steps to Reproduce

- open koWindowIntegration.p.py
- Go to line 284
- Right click > Go to Definition on `_appKeyPath` in `self._appKeyPath, "editAssociations")`.

### Expected results

Cursor to jump to line 123

### Actual results

`Could not find definition`

**Comment by mitchell-as** [comment]
This was actually a duplicate of #3241.

**Comment by cgchoffman** [comment]
Perfect.  Thanks Mitchell.
