### ISSUE TITLE
Change location of feedback block on Find dialog

### ISSUE THREAD

**Issue by we3geeks** [Komodo/KomodoEdit#325]
Suggestion: Move the feedback block on the find/replace dialog to below the set of action buttons. 

Rationale: If I am doing a selective find/replace as I walk through a file, clicking the "Replace" button, I am primarily watching the edit buffer for the context in which the string was found, and just click, click, clicking my way through the replacements... and as soon as that feedback block is added to the panel, the buttons I have been using get moved down... and I am no longer clicking on what I thought I was. Having the feedback panel below the buttons would keep those buttons in the same location, and eliminate one small papercut.

(And this sort of change might apply in other dialogs that get used on a repetitive basis once opened?)

![komodo-20150607a](https://cloud.githubusercontent.com/assets/2390335/8024295/eef00d2a-0ceb-11e5-9142-1b9a15a69afd.png)

**Comment by Naatan** [comment]
No longer an issue in 9.3 due to find dialog overhaul.
