### ISSUE TITLE
Internal Error Licensing

### ISSUE THREAD

**Issue by mfzarates** [Komodo/KomodoEdit#3253]
The licensing system showed this dialog but we have a perpetual license.

Komodo IDE, version 10.2.3, build 89902.
Built on Tue Jul 11 11:52:38 2017.

**Comment by mitchell-as** [comment]
Sorry, but I don't see a dialog. Did you try re-running your license installer?

**Comment by Naatan** [comment]
Please contact our support team directly for issues such as this, we cannot discuss licensing issues in a public forum. support@activestate.com.
