### ISSUE TITLE
Ever increasing Save changes dialog box width

### ISSUE THREAD

**Issue by minipc** [Komodo/KomodoEdit#3254]
### Short Summary
The Close>Current File - Save changes... dialog popup increases in width with every appearance. 

### Steps to Reproduce
1. Create a test file.
2. Close it.
3. Repeat steps 1 & 2, multiple times and watch as the "Save changes..." dialog gets wider and wider until its title and right hand edge disappear of the right of the screen.

### Expected results
To see a dialog of appropriate width for the message that does fall off the edge of the screen.

### Actual results
It gets wider and wider and wider...

### Platform Information

*Komodo Edit or IDE?* Komodo Edit
*Komodo Version?* 10.2
*Operating System (and version)?* Windows 8.1

### Additional Information
screenshot
![untitled](https://user-images.githubusercontent.com/10897250/31384111-6e6e40b4-adb5-11e7-8d6e-2b8032c1ed71.png)

**Comment by mitchell-as** [comment]
Hi, this appears related to #3049.
