### ISSUE TITLE
Javascript auto-completions dont show after typing .

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3259]
### Short Summary
Noticed with the javascript auto completions, that it does not show the auto completions after typing a `.`. It does auto complete but only after typing a letter.

Tested some more, but the behaviour is inconsistent.
It sometimes does auto complete after a `.` and sometimes it doesn't.
Made a [screen-cast](http://youtu.be/CIDqzeDtnR8?hd=1) to show the behaviour.

Looks like it is behaving differently, when I first use a auto-completion and then a dot.
Or if i type out `window.` it does auto complete. 

### Platform Information
[2017-10-11 03:51:49,578] [INFO] Startup: Welcome to Komodo IDE 11.0.0 build 90668 (platform win32-x86, running on Windows post2012Server version 6.3.9600)

**Comment by mitchell-as** [comment]
I am not seeing this in master. We've improved completion triggering since 11.0.0, so it's likely that this has been fixed in the meantime.
