### ISSUE TITLE
Find Next doesn't respect RegEx setting

### ISSUE THREAD

**Issue by hobbsd** [Komodo/KomodoEdit#326]
I do a Find using Ctrl+F (the simple find box at the bottom) with `RegEx` turned on and type `^class `, hit Enter, it finds the appropriate text; and I escape out of the Find box to make an edit. But if I then hit F3 to Find Next, it can't find the search string and shows a message, `find: the pattern "^class " was not found.` (even though there are more occurrences).
F3 works if the Find box is still open, but then I can't make my edit and quickly find the next occurrence.

**Comment by Naatan** [comment]
Duplicate of #219
