### ISSUE TITLE
First selected value in auto completion doesn't get highlighted

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3261]
### Short Summary
Noticed with css auto completions that the first selected match doesn't get highlighted ( except from the part that the text is more white ).

![afbeelding](https://user-images.githubusercontent.com/3530262/31429410-3c561e62-ae6e-11e7-995e-7f1d21c196d3.png)

Only when I would cancel the auto completion and trigger it again it is showing correct:

![afbeelding](https://user-images.githubusercontent.com/3530262/31429634-ddba6d08-ae6e-11e7-8b85-f21e43b11ef5.png)

### Steps to reproduce
 * Create a Less file
 * Paste the following example
 * Type `col`

```less
#header {
	// type here col
}
```

### Platform Information
Komodo IDE, version 11.0.0, build 90668, platform win32-x86.

**Comment by mitchell-as** [comment]
I am not seeing this in Linux. @cgchoffman do you see this on Windows? It's also possible this has been fixed since 11.0.0.

**Comment by Naatan** [comment]
This is fixed on master/nightly.

**Comment by babobski** [comment]
confirmed
