### ISSUE TITLE
CSS dont show auto completion inside color values

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3262]
### Short Summary
Noticed when typing color values like rgba or rgb the auto completion fires inside the color values.
This is incorrect, it should not show the auto completions here:

![afbeelding](https://user-images.githubusercontent.com/3530262/31429951-b99122c2-ae6f-11e7-822c-214e95c927f3.png)

### Platform Information

Komodo IDE, version 11.0.0, build 90668, platform win32-x86.

**Comment by mitchell-as** [comment]
Thanks for the report.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/codeintel/commit/988ce0c6202cf8d3f5be8a31f5daaf15927fa5d4

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/codeintel/commit/988ce0c6202cf8d3f5be8a31f5daaf15927fa5d4
