### ISSUE TITLE
Code intel died in the night

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3265]
### Short Summary

Arrived at work and Code intel isn't working at all.  Komodo was running all evening.  I don't have any other information other than a code intel log with little to no helpful information and a large pystderr file with lots of complaints from mediator.js:

Codeintel:
```
<1507675779> [2017-10-10 15:49:39,782] [INFO]  codeintel.db.database: Database initialized
<1507675779> [2017-10-10 15:49:39,782] [INFO]  codeintel.scanner: Starting threaded file scanner.
<1507675779> [2017-10-10 15:49:39,782] [DEBUG]  SocketServer: Initializing SocketServer
<1507675779> [2017-10-10 15:49:44,769] [INFO]  Server: Started CodeIntel server on port: 54464, pid: 1660
<1507675779> [2017-10-10 15:49:50,102] [DEBUG]  SocketServer: Starting handle loop
<1507675779> [2017-10-10 15:49:56,372] [DEBUG]  service: Summarizing C:\Users\cgcho\Projects\komodo\KomodoIDE\src, depth: 0
<1507675779> [2017-10-10 15:49:57,049] [DEBUG]  service: Scanning C:\Users\cgcho\Projects\komodo\KomodoIDE\src, depth: 0
```
[pystderr.txt](https://github.com/Komodo/KomodoEdit/files/1376321/pystderr.txt)

Sorry for the vague bug report.  I think codeintel logs are getting truncated too aggressively.

**Comment by cgchoffman** [comment]
This happens quite often btw.  This isn't the first time I've hit this.  Code intel dies like this quite often it's just the first time I remembered to check codeintel3.log.

**Comment by Naatan** [comment]
I'll make this bug about fixing the log truncating when codeintel restarts. Other than that there isn't anything actionable unfortunately.

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/8ff4cb55f3f4609e56ebcf7ec20bb0308a4fc0d5
