### ISSUE TITLE
Not updating Code Browser

### ISSUE THREAD

**Issue by bluszcz** [Komodo/KomodoEdit#327]
Hi, I am trying a Komodo 9.1 on Ubuntu Trusty 14.04 (64 bit platform). Build which I am using has been downloaded from: http://downloads.activestate.com/Komodo/releases/9.1.0/Komodo-IDE-9.1.0-87337-linux-x86_64.tar.gz

When I have started Code Browser view  - it was showing all classes and methods (as expected). However, during modifying my Python file - changes have not been reflected in the Code Browser view.

I decided to turn off the view, and turn it back. It was totally empty. I repeated process few times - but Code Browser never came back - just blank.

After restart the  application -  Code Browser was working back. 

It happened once  - but I launched Komode IDE only three times at all.

**Comment by cgchoffman** [comment]
hi @bluszcz, can you include your logs when you are able to reproduce this issue?  Help > Troubleshooting > View Log File.  Make sure you've reproduced the issue or else the logs won't be helpful.

**Comment by bluszcz** [comment]
Since then I haven't experienced issue (I have my session opened since then).

**Comment by cgchoffman** [comment]
I suspect Komodos code intel was scanning your code again then.  If this does happen again, look for the throbber in the bottom right hand corner.  That indicates code intel is scanning and won't give suggestions.  I'll close for now but If you can repro please do reopen and include your logs but also look for the indicators I mention above.
