### ISSUE TITLE
Breadcrumbs bar symbol browser behaves poorly with long paths/small editor widths

### ISSUE THREAD

**Issue by damienprystay** [Komodo/KomodoEdit#3272]
The symbol browser item at the end of the breadcrumbs bar (which defaults to "(Select Symbol)") ranges from partially cut off to completely hidden when the current file's path is sufficiently deep in the directory tree to cause it to run into the right side of the bar (where the line and column numbers, file encoding, and language are). Being partially cut off isn't a big deal, since there's still a visible target to click on to bring up the symbol browser, but when the path length and editor width happen to line up the wrong way, it disappears entirely.

I'd say at least some minimum width of the symbol browser "breadcrumb" should always be visible, if necessary at the expense of collapsing more parts of the left side of the path behind the ellipsis.

Komodo IDE 11.0.0 build 90668
Mac OS X 10.11.6

**Comment by Naatan** [comment]
This is fixed on 11.0.1 and the nightly for it.
