### ISSUE TITLE
"Starting Scan" dialog won't go away

### ISSUE THREAD

**Issue by mjross** [Komodo/KomodoEdit#3276]
### Summary
A small green dialog box, titled "Starting Scan", usually pops up and will not go away, even when I click on the white "X" in the upper right of the dialog.

The dialog of course is visible when Komodo IDE has focus, i.e., I'm currently editing a file in Komodo IDE (first screenshot). In those circumstances, if one clicks the gear icon (to the left of the "X"), then a tooltip appears that reads "Disable Notifications of This Type", but it does not open up any additional menu or even seem to disable the notifications.

Even worse, the dialog is still visible outside of Komodo IDE (second screenshot).

The dialog remains indefinitely. I would guess Komodo IDE is scanning the file for syntax errors. In this example, the file is less than 300 lines long, so it's not a matter of the process just taking a long time on a huge file. The only way I've found to make the dialog disappear is to close Komodo IDE, but it reappears when I open Komodo IDE and resume editing code files.

It would be great to hear how to disable this notification.

### Steps to Reproduce
I don't know how to reproduce this behavior other than what I mention above, but I'm not sure if it's consistent.

### Platform Information
Komodo IDE 11.0.0 build 90668 on Windows 10 Pro

### Attachments
![starting scan dialog inside komodo](https://user-images.githubusercontent.com/829492/31576289-d70d730e-b0b4-11e7-8b7f-9196e0584289.jpg)

![starting scan dialog outside komodo](https://user-images.githubusercontent.com/829492/31576290-dff33846-b0b4-11e7-8134-c1f0064fbe25.jpg)

**Comment by mitchell-as** [comment]
Hi, when you click on the gear and select the "disable" option, does your Help > Troubleshooting > View Log File show any sort of error?

**Comment by Naatan** [comment]
Please share your error log after reproducing the issue.

You can find your error log at Help > Troubleshooting > View Log File.

**Comment by mjross** [comment]
It's been almost a week, and during that time, the "Starting Scan" dialog box still pops up but then goes away in a second or two. If it persists again, I'll update this report with an error log.

**Comment by mjross** [comment]
I haven't seen this behavior since I posted this issue, so I'll close it for now.

**Comment by monkeyone76** [comment]
@mjross I am having this exact same issue, should this be reopened, or new issue?

![2021-04-19 22_29_02-Settings](https://user-images.githubusercontent.com/11825950/115328683-00a96a80-a15f-11eb-8477-8681b2cfb4b6.png)
[log.txt](https://github.com/Komodo/KomodoEdit/files/6340217/log.txt)

**Comment by mjross** [comment]
@monkeyone76: I haven't seen the issue in a while, but if you are able to reproduce it now, please reopen this ticket and send them your log file (please see Naatan's comment above).
