### ISSUE TITLE
ko/dialogs open() buttons and class properties documentation improvements

### ISSUE THREAD

**Issue by mjross** [Komodo/KomodoEdit#3279]
[The documentation](http://docs.activestate.com/komodo/11/sdk/api/module-ko_dialogs.html) for the require("ko/dialogs").open() `buttons` and `class` properties could be much improved, specifically:

In the description of the `buttons` property we read:
> Currently this is limited to three buttons, plus an optional "Cancel" button.

The documentation should be updated to explain that any "Cancel" button apparently must be last:
`require( "ko/dialogs" ).open( "testing multiple buttons", { buttons: ["Yes", "No", "Fourth", "Cancel"] } );`

Otherwise the output is identical to the default when the `buttons` property is not used:
`require( "ko/dialogs" ).open( "testing multiple buttons", { buttons: ["Yes", "No", "Cancel", "Fourth"] } );`

![open dialog](https://user-images.githubusercontent.com/829492/31587940-d819fe68-b1a7-11e7-8983-c7245d2e0fa1.jpg)

In the description of the `class` property we read:
> the class attribute to be applied to the dialog icon.

The documentation should be updated to more clearly explain what is meant by that. Is the property like a CSS class added to an HTML element? If not, what is meant by that description? In either case, how can our code utilize the class designated?

**Comment by Naatan** [comment]
Thanks @mjross. Note I found another bug when I went over this, the property is called `className`, not `class`.
