### ISSUE TITLE
Preferences search add highlight matching prefrences

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3282]
### Short Summary

In PHP Storm when you would search in you're preferences.
The matching preferences are highlighted.

![find_settings](https://user-images.githubusercontent.com/3530262/31604627-38c1b398-b264-11e7-9e9b-ff045980002e.png)

I think it would be nice to see some similar function to Komodo.

**Comment by mitchell-as** [comment]
Thanks for the suggestion.

**Comment by Naatan** [comment]
Thanks @babobski, we're tracking this one here: #842

**Comment by babobski** [comment]
Oke, good to know!
