### ISSUE TITLE
ko/dialogs prompt() problems

### ISSUE THREAD

**Issue by mjross** [Komodo/KomodoEdit#3284]
### Summary
In require("ko/dialogs").prompt(), there are several oddities:
- The prompt is not displayed.
- value1 is not a default value.
- The first label/value pair is not displayed.
- When the second label/value pair is displayed, an unlabeled field is displayed above it.

### Steps to Reproduce
Help > Troubleshooting > Restart in Safe-Mode.  The example code and attachments below illustrate the issues:
```
    var d = require( "ko/dialogs" );
    
    //  The prompt is not displayed.
    d.prompt( "message", { prompt: "prompt" } );

    return_value = d.prompt( "enter x" );
    assert( return_value == "x", "return value" );

    //  value1 is not a default value on its own.
    return_value = d.prompt( "press Enter", { value1: "value 1" } );
    assert( return_value == "", "default value 1" );

    //  The first label/value pair is not displayed. value1 is not a default value.
    return_value = d.prompt( "press Enter", { label1: "label 1", value1: "value 1" } );
    assert( return_value == "", "default value 1" );

    //  When the second label/value pair is displayed, an unlabeled field is displayed above it. value1 is not a default value.
    return_value = d.prompt( "press Enter", { label1: "label 1", value1: "value 1", label2: "label 2", value2: "value 2" } );
    assert( return_value[ 0 ] == "", "default value 1" );
    assert( return_value[ 1 ] == "value 2", "default value 2" );

function assert( assertion, label ) {
    if ( ! assertion ) {
        alert( "Assertion failed: " + label );
    }
}

```

### Platform Information
Komodo IDE 11.0.0 build 90668 on Windows 10 Pro

### Attachments
![clipboard01](https://user-images.githubusercontent.com/829492/31642522-ae121888-b2a8-11e7-9223-f9676b3c2ef8.jpg)
![clipboard02](https://user-images.githubusercontent.com/829492/31642525-b173a19a-b2a8-11e7-80b0-bddb0df27d3d.jpg)
![clipboard03](https://user-images.githubusercontent.com/829492/31642530-b619fdac-b2a8-11e7-9932-9844b19f843c.jpg)
![clipboard04](https://user-images.githubusercontent.com/829492/31642532-b9b2c9ee-b2a8-11e7-89b3-cce58eb1f3c6.jpg)
![clipboard05](https://user-images.githubusercontent.com/829492/31642535-bc770500-b2a8-11e7-9da0-48dba1eb0594.jpg)

**Comment by Naatan** [comment]
I am sorry but I'm going to have to ask you simply to use ko/modal for what you are trying to do. As I said this SDK depends mainly on legacy code and I do not see much merit in spending cycles trying to fix code we intend to dump. I'll see about fast lining the deprecation of this SDK. 

As such while these are valid bugs we won't be fixing them as the solution is simply to stop using this SDK.

Note this is one of the few SDK modules that actually has this heavy legacy code reliance. By which I mean I hope this doesn't discourage you from using the SDK, as the majority of it is quite solid (doesn't rely on tons of legacy code).

**Comment by mjross** [comment]
I understand. My primary concern is that I'm trying to figure out how to display a menu or list of a dozen or so choices, and the user clicks one or enters a number to indicate his choice. Is that doable with ko/modal? (I've encountered some odd behavior from it, but will post that separately.)

**Comment by Naatan** [comment]
```
require("ko/modal").open(
    "pick an item",
    {
        items: {
            type: "listbox",
            options: { listitems: [ "one", "two", "three" ] },
            attributes: { }
        }
    },
    console.log
)
```

The type correlates to ko/ui items.

**Comment by mjross** [comment]
Excellent. Thank you. When reading the documentation, I assumed that "textbox" was one of many options, but wasn't sure where to find the others. Adding that reference to the documentation could be helpful to people who read it in the future.

If I have any further questions about how to work with this module, I'll post over in the forums.
