### ISSUE TITLE
Crash Reporter spawned without Komodo having crashed

### ISSUE THREAD

**Issue by damienprystay** [Komodo/KomodoEdit#3291]
I've just noticed that at some point the ActiveState Crash Reporter spawned, apparently in the background, telling me that Komodo has crashed while Komodo is still running without apparent issue.

I saw this occasionally on Komodo 10, but this is the first time I've noticed it on K11.

Komodo IDE 11.0.0 build 90668
Mac OS X 10.11.6

**Comment by Naatan** [comment]
Please enter "bug #3291" in the comment section of the crash report and send it in next time it happens. Ping us on here so we know to check :) Thanks!

**Comment by damienprystay** [comment]
I hadn't dismissed the crash reporter yet, so, done!

**Comment by Naatan** [comment]
It would appear this was the license dialog, though I have no idea why this would pop up while you are already running Komodo. Did you invoke Komodo from the command line to open a file perhaps?

**Comment by damienprystay** [comment]
I have been known to do that, but my bash history denies that I did so yesterday.

**Comment by Naatan** [comment]
Strange. Anyway I can't find anything I can do about this with the current information. Please let me know if it happens again and be sure to note what you were doing at the time.
