### ISSUE TITLE
K11 Markdown don't show minimap for markdown files

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3292]
### Short Summary
I have got the option for the mini-map enabled, only for my markdown files I don't want the mini-map enabled. It not much of use here.

I think it would be nice if it's disabled by default for markdown files.

**Comment by Naatan** [comment]
I don't see why it wouldnt be useful on Markdown. I think this type of behaviour would be better suited to a  userscript, as it doesn't really make sense as a default.

**Comment by babobski** [comment]
Oke, made a small userscript as a work arround 👍

```javascript
var currentView = require("ko/views").current(),
	language = currentView.get('language');

if (language === 'Markdown' && ko.views.manager.currentView.showMinimap) {
	ko.views.manager.currentView.destroyMinimap();
}
```
