### ISSUE TITLE
CSS don't auto complete after ;

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3297]
### Short Summary
In the css auto completions I'm getting completions after `;`.
This is unwanted, I just closed my line and want to move to the next.
But the auto completion is preventing me to do so:

![afbeelding](https://user-images.githubusercontent.com/3530262/31764932-008e5ace-b4c3-11e7-9c70-dcc8dd8dee29.png)

### Expected results
I would be able to move to the next line using <kbd>Enter</kbd>

### Actual results
The auto completion is preventing me to move to next line.
I have to opt-out first using <kbd>Esc</kbd>, before I can i use <kbd>Enter</kbd> to move to the next line.

### Platform Information

Komodo IDE, version 11.0.1, build 90791, platform win32-x86

**Comment by mitchell-as** [comment]
Hi, thanks for the report. That's a bit obnoxious. Just like the newline issue previously.

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/bd64cf89ac0430f2976feae5ab590c2fb251b40a

**Comment by cgchoffman** [comment]
#3506

**Comment by th3coop** [comment]
This is not fixed:
https://github.com/Komodo/KomodoEdit/issues/3812

**Comment by th3coop** [comment]
That might explain why it's still triggering in SCSS and LESS files, https://github.com/Komodo/KomodoEdit/issues/3716

**Comment by th3coop** [comment]
Sorry for the noise.  This IS fixed.  Less and SCSS are not fixed.
