### ISSUE TITLE
Javascript auto completion failing when use of `$` in var name

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3298]
### Short Summary
Javascript auto completion is failing, if you would use a dollar sign in you're variable name.

### Steps to Reproduce
 * Create a javascript file
 * Create or paste the following code
```
var $test = 'test';

```
 * If you type `$` you will get the auto completion
 * type the second letter `t`

Now the auto completion fails.
 

### Platform Information

Komodo IDE, version 11.0.1, build 90791, platform win32-x86

**Comment by mitchell-as** [comment]
Thanks for the report.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/codeintel/commit/cc112c36281f85e688a8beb3c6004efc1d052c16
