### ISSUE TITLE
Build repeating Mozilla download

### ISSUE THREAD

**Issue by kaiof** [Komodo/KomodoEdit#33]
When attempting to build per the instructions on the main page https://github.com/Komodo/KomodoEdit I'm making it progressively further through, but have yet to get all the way through "python build.py distclean all".

I assume it's intended to be the safest way to try again, wiping all the build files. Admitting that "python build..." is the last in a long string of build syntaxes I've learned, does it have to wipe the Mozilla download? Could it ask to keep it (if it's valid) or even be resumable?

Though I did check for dependencies ahead of time ('hg' and 'python27 not in the path' were the last two fatal errors), and fixing the dependencies hasn't been that hard (only a few minutes each time) the biggest problem has been the formidable package size combined with network bumps.

Thanks for any ideas, even if it's correcting how I'm trying to do this.

**Comment by cgchoffman** [comment]
Hey kaiof,

Generally, unless the Mozilla bits were pulled down incorrectly/incompletely, you shouldn't need to do a ```distclean```.  ```python build.py all``` is perfectly fine in the majority of cases.  build.py will then do various checks through the build process to see what steps have been completed and will skips the ones it deems completed.  

Asking if you want to keep the Mozilla folder kinda defeats the purpose of running distclean.  If you don't want to start from scratch, you shouldn't be running distclean.  

Don't get me wrong!  I feel your pain!  It's a massive build process.  What platform are you on?  Is it an option to use our Mozilla Docker image?  That allows you to skip the Mozilla build step.

- Carey

Komodo Dev Team

**Comment by kaiof** [comment]
Thanks Carey. It seems like every day I'm discovering a build system I haven't needed yet (the most entertaining come from bright developers giving exactly what works for them but no context what the build system actually is). Your system is a little more approachable!

I'll review Docker, but I've also traced the problem, which may correlate to low-resource consumers trying to get your product: a new type of ICMP appeared on this network, possibly due to a mesh/peering upgrade. Though I've caught some things like bizarre routes and a TLS concern, relaxing a few (standard, I thought) security settings resolved my horrible performance.

Expecting to be fine now, I looked up python's 'distclean': http://bugs.python.org/issue18312 ("preparation for a source code distribution"). I still wish there was a way to resume even a partial of that download (about 1GB), but Mozilla doesn't provide hashes (to resume even without 'distclean' or even verify the package) and I realize you've got to ensure a successful build. Thanks for the Docker suggestion and feedback.

**Comment by Mook-as** [comment]
It might be useful to modify [`build.py`](https://github.com/Komodo/KomodoEdit/blob/ced48a5c1066bf6301e4c0ad1ad297a8718955b7/mozilla/build.py#L2084) to support resuming downloads (and in your case, download `mozilla-central.hg` once manually and put it in the expected place after each `distclean` to resume from a complete file).  However, that will need to deal with the bundle not being a stable file - I believe Mozilla has a cron job that generates new bundles every now and then.  And it's probably not a good idea to resume a bundle that isn't the same file.  (And I suspect Carey is too busy with other things to code this right now.)

**Comment by kaiof** [comment]
Thanks, I can certainly try that. It does seem like an edge case as well and I'm sure it will be okay once I get a chance to retry. Please note when I went to check again if Mozilla actually had checksums, I found:

https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Source_Code/Mercurial/Bundles   

It mentions poor network connections and suggests a technique to retrieve / keep up to date once the bundle is retrieved. This is a little out of my area and may not be news, so I'm just including it in case it's useful. This issue shouldn't be one for me any more, and thanks for commenting!

**Comment by Naatan** [comment]
Thanks kaiof. I'll close this issue since it's a nice to have but not one that I see us actually targeting any time soon (what with all our other priorities). This is the type of issue that organically gets fixed when a dev with some free time on his hands runs into it at some point.

**Comment by Mook-as** [comment]
> It mentions poor network connections and suggests a technique to retrieve / keep up to date once the bundle is retrieved.

Right; Mozilla expects you to `hg pull -u` to stay up to date, not re-download their bundles.  That doesn't work if you're trying to run `distclean` all the time and wiping out the source tree.  Unfortunately that won't be useful in your situation.
