### ISSUE TITLE
Javascript auto completions for functions that are not in this file.

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3301]
### Short Summary
Noticed this before, but the javascript auto completions is auto completion functions or variables that does not exist in the file.

![afbeelding](https://user-images.githubusercontent.com/3530262/31768435-b397b1ea-b4cf-11e7-91ab-3728c9cf59b2.png)

### Expected results
Only auto completions are shown that are in the scope or are default functions.

### Actual results
Auto completions shows functions or variables that don't exist.

### Platform Information

Komodo IDE, version 11.0.1, build 90791, platform win32-x86

**Comment by mitchell-as** [comment]
Hi, this is intentional behavior, as that's how JS works in the browser.

**Comment by Naatan** [comment]
@babobski that's Komodo 10 ... ;)

**Comment by mitchell-as** [comment]
I need to clarify my earlier comment. Since we cannot know what JS files are included by the parent HTML file including the current JS file, we just assume all JS files in the current directory are being included, and import all of their symbols automatically.

**Comment by babobski** [comment]
@Naatan you're totally right, it is Komodo 10. Sorry for that had both open.
