### ISSUE TITLE
Unable to normaly define a scss variable

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3302]
### Short Summary
Tried out the scss support, but it is failing on the variables.
If i type a variable, I get auto completion for pseudo elements:

![afbeelding](https://user-images.githubusercontent.com/3530262/31769197-e4abd592-b4d2-11e7-9b4b-0e24f1264d55.png)

After I defined a variable, I'm getting auto completions for css attributes.
This is wrong:

![afbeelding](https://user-images.githubusercontent.com/3530262/31769245-24f85f80-b4d3-11e7-9d2f-0cbafc2368da.png)

### Platform Information

Komodo IDE, version 11.0.1, build 90791, platform win32-x86

**Comment by mitchell-as** [comment]
Thanks for the report.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/codeintel/commit/9e178d30f93296544e7c8498f058be7609728d00
