### ISSUE TITLE
LESS/SCSS completions missing after @

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3303]
### Short Summary
In LESS/SCSS files I'm missing the following auto completions:

![afbeelding](https://user-images.githubusercontent.com/3530262/31769428-d3a69e5c-b4d3-11e7-8367-bab27f9479b3.png)

In K11 it looks like:

![afbeelding](https://user-images.githubusercontent.com/3530262/31769443-e837eb96-b4d3-11e7-94aa-cee07bb14e73.png)

And the auto completions are missing ( like `@import` or `@keyframes` ).

### Platform Information
Komodo IDE, version 11.0.1, build 90791, platform win32-x86

**Comment by mitchell-as** [comment]
Hi, those completions should be there. It appears they just aren't in the first set of results. I'm getting them on my computer.

**Comment by babobski** [comment]
@mitchell-as just tested it, but you're correct the autocompletions are shown in popup:

![afbeelding](https://user-images.githubusercontent.com/3530262/31787332-ae2c5d50-b50b-11e7-98d5-52455a851db9.png)

The only thing is they don't work.
If I type `@im` it is not showing any result for `@import`

**Comment by mitchell-as** [comment]
Okay, I see that there is an issue with typing. Thanks for your patience.

**Comment by mitchell-as** [comment]
Note to self: probably has to do with the "characters allowed in completions" setting in router.py.

**Comment by babobski** [comment]
of course, no problem 👍

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/codeintel/commit/cc112c36281f85e688a8beb3c6004efc1d052c16
