### ISSUE TITLE
Cancel "scan files" popup if other project is opened

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3304]
### Short Summary
I sometimes accidentally choose the wrong project in my places widget.
When I then select the correct project, I still getting the "scan files" popup from the other project.

### Expected results
The "Scan files" popup is corresponding with the current open project.

### Actual results
The "Scan Files" popup is shown for the closed project

### Platform Information
Komodo IDE, version 11.0.1, build 90791, platform win32-x86

**Comment by Naatan** [comment]
If you prompt 2 scans at once they will complete one after the other. Assuming the first scan is too big that you'd want to cancel it you can cancel it when it prompts you to do the scan. If the scan is under 100 files it will go ahead and run it anyway, and it shouldn't take long at all to complete.

Adding logic in between this to cancel out of a 100 file scan would be a lot of work for very little payoff, so I'll mark this as a limitation.
