### ISSUE TITLE
Move dynamic sidebar to edit

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3308]
### Short Summary
I implemented for beautify js a dynamic sidebar button.
The one thing that's bothering me about the dynamic sidebar, is that it's only available for Ide.

I wan't to implement this feature more ( for my less/sass compiler, side by side and the git addon ).
The only thing holding me back, is that I'm not that keen on maintaining 2 diffrent logics.
One for Ide and one for Edit.

Would you guys be open for it, to make it available for edit?

**Comment by Naatan** [comment]
It is available for Edit, except it's not in the sidebar, it's in the top toolbar. But the button appears all the same.

**Comment by babobski** [comment]
Oh wow, great to know 👍
