### ISSUE TITLE
Alerts and prompts are growing

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3309]
### Short Summary
Lately I have this bug again that my dialogs and alerts are growing.
I had this bug before #968 
But every time I open a dialog in Komdo the dialogs has grown a tiny bit.
After a few times you will notice that it has grown.

![afbeelding](https://user-images.githubusercontent.com/3530262/31815718-d5e683ac-b58d-11e7-8c95-e7d8976ced88.png)

I had them bigger then this, but the size of the screens where reset when I switched to the nightly builds.

Did some more testing but got the [behaviour on recording](http://youtu.be/cBQKpcYeofg?hd=1).

### Platform Information

Komodo IDE, version 11.0.0, build 90668, platform win32-x86

**Comment by babobski** [comment]
Note: I was not on the latest nightly ( don't now what went wrong, installed nightly but didn't run ).
Installed the latest nightly but I'm unable to reproduce.

**Comment by Naatan** [comment]
Yep, this was fixed in the nightly :) Strange XUL bug, not sure what caused it but found a workaround.
