### ISSUE TITLE
CSS on @ if I select one from the list I end up with @@

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3311]
### Short Summary
I just wanted to make some keyframes only when I selected the keyframes from the list I end up with `@@`.

### Steps to Reproduce
 * Create a CSS file
 * Type `@`
 * Select `@keyframes` from the list

### Expected results
`@keyframes`

### Actual results
`@@keyframes`

### Platform Information

Komodo IDE, version 11.0.1, build 90791, platform win32-x86

**Comment by mitchell-as** [comment]
Thanks for the report.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/codeintel/commit/cc112c36281f85e688a8beb3c6004efc1d052c16
