### ISSUE TITLE
Code browser need to leave keyboard to select result

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3312]
### Short Summary
If you use the search function in the new code browser, you can't go to the result, without leaving you're keyboard. I was hoping I could use tab to loop through the results ( and select so it would jump to the function ).

![afbeelding](https://user-images.githubusercontent.com/3530262/31854318-2733442a-b697-11e7-8072-23de28c60a52.png)

### Platform Information

Komodo IDE, version 11.0.1, build 90791, platform win32-x86

**Comment by mitchell-as** [comment]
We're tracking this in #3270.
