### ISSUE TITLE
Strange white lines in symbol browser

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#3318]
### Short Summary
Strange white lines in symbol browser

### Steps to Reproduce

1. Open the attached file and view symbols in symbol browser. See the screenshot for the selected color scheme.

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo IDE, version 11.0.1, build 90794, platform macosx.
Built on Wed Oct 18 14:45:42 2017.
### Additional Information
![image](https://user-images.githubusercontent.com/26605593/31967063-92aedd46-b8c1-11e7-9318-51b5ec167bb4.png)

[exp.txt](https://github.com/Komodo/KomodoEdit/files/1412455/exp.txt)
![image](https://user-images.githubusercontent.com/26605593/31967099-baaef790-b8c1-11e7-95b1-3d76ff5948e8.png)

**Comment by Naatan** [comment]
As discussed on Slack this appears to be something wrong with your install in particular. Does switching your skin back and forth fix this?

**Comment by mjainQA** [comment]
I am unable to reproduce this after switching back from safe mode. Also, switching between various skins does not surface this issue. I will keep an eye on it.
