### ISSUE TITLE
Code intel prefs are gone when you open second Window

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3319]
### Steps to Reproduce

Start Komodo
Open prefs
Code intel prefs will be there
Open another window
Open prefs

### Expected results

Code intel prefs to still be there

### Actual results

They are gone.

**Comment by Naatan** [comment]
This exists in 11.0.0 also, not new in 11.0.1.

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/868698d409c1d1c837ddb4eb445317abc644261f
