### ISSUE TITLE
 Auto spellcheck support for markdown files Support

### ISSUE THREAD

**Issue by harpreetsb** [Komodo/KomodoEdit#332]
I think markdown files must require auto spell check. Is this a priority?

**Comment by Naatan** [comment]
Priority - no, but definitely something we'd like to look into (not just for markdown).

**Comment by datamafia** [comment]
This should be a priority. Seemingly trivial but **no** this is very important. 

It is sad that in my 8th year of using Komodo, I still have to open another app to spell check my documentation. 

I use MD like many developers, and I was excited to see MD preview come to 9.x. This feature is low to zero value without spell check.

Spelling mistakes should be caught with the greatest ease possible and having MD rendering without spell check is a disservice to programmers and developers who actually document their work.

I urge you to reconsider your priority on this item.

I made 9 errors in spelling creating this comment.

**Comment by cgchoffman** [comment]
> It is sad that in my 8th year of using Komodo, I still have to open another app to spell check my documentation.

Do you consider right clicking > Check spelling to be a different app?  I'm confused.

**Comment by datamafia** [comment]
Sorry, let me focus the statement further. Right click works, but this dialog lacks the efficiency necessary for writing docs fast. I typically use MarkdownPro (OSX App) where the behavior is consistent with modern apps, such as a web-browser where "squiggle" lines appear for bad spelling that also yield to a  right-click dialog.

![screen shot 2015-06-17 at 11 23 40 am](https://cloud.githubusercontent.com/assets/170310/8211134/74a699ee-14e3-11e5-81fb-a5653741323f.png)

The legacy spellcheck is tolerable (at best) for code writing, but MD is document driven and underscores the need for modernity. 

The concept of modernity and the forward progression of technology is key to this discussion as my eyes, brain, and workflow are trained to operate in a particular manner. Such behavior is a product of the ecosystem (a technological equivalent of biological acclimatization see https://en.wikipedia.org/wiki/Acclimatization).

To deny such ideas is to bury one's head in the sand. Komodo maintainers must continuously reassess issues like "how do people work?", "what advancements are happening in other tools?", "how are patterns of use evolving?".

You certainly don't want to be the last to show up to the browser party supporting tabs where Mozilla was critical in cutting a new path for modern data discovery and consumption habits. Mozilla via the Gecko engine are part of the core and history of Komodo and I encourage the team to stay fresh and look forward.

Few users "speak up", we know the stats, so take my suggestion and consider what I represent on a user level and how support and rendering (preview) of MD files beckons certain expected features.

I enter this discussion not as a mad, unhappy, or combative user. Instead I contribute as a developer who has well over 10 MD apps installed interested to offer input regarding the advancement of a tool in Komodo that would allow me to run one less application everyday.

Thx.

**Comment by cgchoffman** [comment]
@datamafia your input is respect but this is not helpful in the bug report.  If you would like to discuss this please email us or post in the forums.  Please keep you message concise.

**Comment by Naatan** [comment]
Little birdy told me this may be coming to IDE soon .. sshhh.

**Comment by cgchoffman** [comment]
This is out the door in the pre-release nightlies: http://downloads.activestate.com/Komodo/nightly/komodoide/latest-9.2.0/

**Comment by tonyattwood** [comment]
Hello,

That  new book I've just read seems to be really  amazing, it's just  has to be on your  list! Please read it  here <http://experience.amountainclimber.net/e4tbtpvf>

Speak to you later, tony.attwood@ntlworld.com

**Comment by datamafia** [comment]
Haha, just got a ping on this thread. Wanted to deliver an update. I had to drop use of Komodo because the linter, code formatting, and other features were so bad that the team asked me to stop using Komodo. Good luck.
