### ISSUE TITLE
Update Navigation > Show Section List

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#3320]
Seems I missed this when I implemented the new CodeIntel.

This should instead be a "Show Symbol List" entry, not to be confused with the Symbol Browser. (Symbol List is in the status bar).

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/619e469ed2f6cef4849744b6131b13c2d8a5cc2a

**Comment by Naatan** [comment]
This should be handled from the codeintel module, otherwise it's not modular.

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/b9f050d81ac6fb052a349d60fba1b90e69ee4da7

**Comment by cgchoffman** [comment]
That took forever to test :(  `bk build` can be SO FLAKY.
