### ISSUE TITLE
Sporadic: Not getting a file save dialog while creating a new file from template. 

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#3324]
### Steps to Reproduce

1. right click any folder in places pane
2. select new file from a template
3. select any template for e.g. HTML
4. Repeat the above steps to see if you consistently get a dialog to give filename
### Expected results

![image](https://user-images.githubusercontent.com/26605593/32024155-69f3a13c-b990-11e7-94e8-6b5c5f5640a9.png)

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo IDE, version 11.0.1, build 90794, platform macosx.
Built on Wed Oct 18 14:45:42 2017.

**Comment by cgchoffman** [comment]
I don't think it's even possible to get this bug anymore.  The entire template system got gutted and re-written.

**Comment by cgchoffman** [comment]
Marking as invalid.  There is nothing to be done for this ticket for the QA team other than general smoke testing of Templates.
