### ISSUE TITLE
Remote debugger not working

### ISSUE THREAD

**Issue by yshtil** [Komodo/KomodoEdit#3327]
### Short Summary
Listening port not changing when apply pressed, listener status not shows

### Steps to Reproduce
Debug->listener status pressed
Preferences -> debugger connections ->specific port - entered 9000, pressed apply,ok

### Expected results
Listener status shoud show something
Specific port setting should persist

### Actual results
Listener status not shown
Setting of specific port ignored

### Platform Information
[pystderr.log](https://github.com/Komodo/KomodoEdit/files/1419536/pystderr.log)

*Komodo Edit or IDE?* Komodo IDE
*Komodo Version?* 11.0.0 build 90668 platform win32-x86
*Operating System (and version)?*

**Comment by Naatan** [comment]
This part looks suspicious:

```
[2017-10-26 10:51:09,371] [ERROR] pref-debugger-connection: 
-- EXCEPTION START --
TypeError: gDBGListener is null
+ stack
    UpdateSummaryUI@chrome://komodo/content/pref/pref-debugger-connection.xul:117:1
    onkeyup@chrome://komodo/content/pref/pref-debugger-connection.xul:1:1
-- EXCEPTION END --
```

Can you reproduce this using `Help > Troubleshooting > Restart in Safe-mode` ?

Please verify that when restarting in safe-mode Komodo should be using the default UI (all your settings would be temporarily reset).

**Comment by yshtil** [comment]
I have restarted Komodo and the problem went away. 

----- Original Message -----

**Comment by cgchoffman** [comment]
aged out
