### ISSUE TITLE
Komodo crashes upon installing a package

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#3328]
### Short Summary

Komodo crashes upon installing a package

### Steps to Reproduce

1. Create a PHP project
2. From universal package manager (PHP) icon, select install package
3. In commando type 'ighk'
4. Select the first entry, click run command
5. Click close and notice Komodo crashes

**Logs**

[pystderr_2017-10-26_11:29_Komodo IDE 11.0.1 (Build 90794).txt](https://github.com/Komodo/KomodoEdit/files/1419626/pystderr_2017-10-26_11.29_Komodo.IDE.11.0.1.Build.90794.txt)

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo.IDE.11.0.1.Build.90794 on mac
### Additional Information
![image](https://user-images.githubusercontent.com/26605593/32070367-f3695da2-ba40-11e7-9f58-03f0d834fa37.png)

**Comment by cgchoffman** [comment]
I can reproduce on Windows.

**Comment by Naatan** [comment]
Does this happen for all package managers or just the PHP one?

**Comment by mjainQA** [comment]
Reproducible in 11.0.0

NOT reproducible with other package managers.

**Comment by Naatan** [comment]
Thanks @mjainQA. I'm tempted to leave it for 11.1 to fix then, seeing as it'd otherwise require a new RC and no one other than QA has reported it.
