### ISSUE TITLE
Update doc links for tutorials

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#3329]
### Short Summary

getting 404

### Steps to Reproduce

1. click on help -> tutorials -> PHP

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo.IDE.11.0.1.Build.90794
### Additional Information
![image](https://user-images.githubusercontent.com/26605593/32071938-cafafdd0-ba45-11e7-9c48-5686d57e01a8.png)

**Comment by cgchoffman** [comment]
Apparently I fixed this 5 months ago, Score!: https://github.com/Komodo/KomodoIDE/commit/eba68ed437a33118c48e4d9afc814f4dc98e6206
