### ISSUE TITLE
profiler window is not being launched 

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#3330]
### Short Summary

profiler window is not being launched after code profiling is finished.

### Steps to Reproduce

1. load python tutorial
2. Open helloworld.py
3. click debug -> start code profiling
4. Enter `-D "SAY_BYE" helloworld.py` in script arguments
5. click ok.
6. Notice profiler window is not launched

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo IDE, version 11.0.1, build 90794, platform macosx.
Built on Wed Oct 18 14:45:42 2017.
[pystderr_2017-10-26_14:34_Komodo IDE 11.0.1 (Build 90794).txt](https://github.com/Komodo/KomodoEdit/files/1420138/pystderr_2017-10-26_14.34_Komodo.IDE.11.0.1.Build.90794.txt)

### Additional Information
![image](https://user-images.githubusercontent.com/26605593/32078132-a62f5d6a-ba5a-11e7-9d20-87aa8decaea5.png)

**Comment by mitchell-as** [comment]
This was working in 10.x.

**Comment by mjainQA** [comment]
works in 11.0.0 as well.
