### ISSUE TITLE
Code intel/autocomplete interfereing with multi-line formatted arrays in PHP.

### ISSUE THREAD

**Issue by jellisii** [Komodo/KomodoEdit#3332]
### Short Summary
Komodo code intelligence misbehaves when populating a multiline-style array in PHP

### Steps to Reproduce

* create a PHP file
* open array, delay for a half-second, code intel box pops up with current context selected.
* press enter to put an element on a new line

### Expected results

It is expected that I get a newline, properly indented, with no new element added.  

### Actual results

The first thing in the codeintel box gets placed on the line instead of a new line.  

### Platform Information

Komodo IDE, version 11.0.0, build 90668, platform linux-x86_64.
Built on Tue Sep 19 16:11:12 2017.

Xbuntu 17.10

### Additional Information

This probably stems from me being in the industry long enough to remember when anything more than 80 columns on a console was a luxury: I use the edge line column at 72 characters too. :D

This particular thing behaved as I expected it to on Komodo 10.  

This may be related to #3331.  

![arraymisbehavior](https://user-images.githubusercontent.com/3483096/32104157-56a030ac-baf1-11e7-977f-8a375fa919c3.png)

**Comment by mitchell-as** [comment]
This is expected. When you press 'Enter' with the autocompletions visible, the first selected completion is inserted. If you want to insert a newline proper, press 'Escape' to dismiss the autocompletion list.

**Comment by jellisii** [comment]
is there a way to adjust the delay time for Autocompletions?  The workflow of "press this key that's not on the main part of the keyboard" is terrible.

**Comment by jellisii** [comment]
Also, are autocompletions correct in that context?  That's an array that I'm populating, and all I've done is indicate that I'm adding an element, not anything about what I'm adding.
