### ISSUE TITLE
ESLint support.

### ISSUE THREAD

**Issue by NeilFraser** [Komodo/KomodoEdit#3336]
Feature request: Support for ESLint in Komodo IDE.

There has been a trickle of such requests over the years.  In my case our team has chosen to use ESLint (for better or worse), and as the only Komodo user on the team, I'm unable to use their linter in my IDE.

**Comment by Naatan** [comment]
Thanks, this is planned but currently blocked by https://github.com/Komodo/KomodoEdit/issues/2747

PR exists at https://github.com/Komodo/KomodoEdit/pull/2656 thanks to @Defman21

**Comment by Naatan** [comment]
Handled in #3421
