### ISSUE TITLE
Code intel: allow `shift+tab` to skip completions

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3338]
### Short Summary

I've been having an issue where I cant trigger a snippet I use a lot becuase code intel completions trigger rather than my snippet.  It would nice if there was an easy way to skip rather having to hit *esc* every time.

**Comment by Naatan** [comment]
What would the difference of behavior be compared to ESC?

**Comment by cgchoffman** [comment]
I wouldn't have to hit esc

**Comment by Naatan** [comment]
But you'd instead press shift+tab?

**Comment by cgchoffman** [comment]
ya, i believe this was supported in 10.

**Comment by Naatan** [comment]
This will be addressed through #3466
