### ISSUE TITLE
Komodo 11 IDE: Symbol Browser doesn't work with characters like ä,ü,ö

### ISSUE THREAD

**Issue by onefloid** [Komodo/KomodoEdit#3339]
### Short Summary
When your Perl Script includes characters like ä, ü or ö Symbol Browser
shows a error message. We are using these characters in our comments. 

### Steps to Reproduce
1. This snippet works:
use strict;
use utf8;

sub print_hello {
    print "hello"; #o
}

2. This snippet doesn't work:
use strict;
use utf8;

sub print_hello {
    print "hello"; #ö
}

### Expected results
Symbol Browser  shows:
class main
method print_hello

### Actual results
Error Message in Symbol Browser: Could not load due to an error, if the issue persists please file a bug

### Platform Information

Komodo IDE
Komodo Version 11
Windows 7 Enterprise SP 1

### Additional Information

[pystderr.log](https://github.com/Komodo/KomodoEdit/files/1436697/pystderr.log)
![image](https://user-images.githubusercontent.com/33193059/32313208-ff85d316-bfa1-11e7-8e9e-60c34ef3c80e.png)

**Comment by mitchell-as** [comment]
Hi, have you upgraded to 11.0.1 yet? (If not, you should get a notice sometime soon.) I'm pretty sure this issue has been fixed in the new release.

**Comment by onefloid** [comment]
Yeah, the update fixed the issue. Thanks
