### ISSUE TITLE
Getting incorrect code completion options

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#3341]
### Short Summary

Getting code completion options for the following cases:

1) When `#` is added in between the code to comment part of the line
2) When space is added between the words/variables
3) When space is added after a variable

### Steps to Reproduce

1. Use the attached python code (Not always reproducible)

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo 11.0.1 (shipped version)
### Additional Information

 
![image](https://user-images.githubusercontent.com/26605593/32397629-ebd335c8-c0a7-11e7-984e-b7ae2f59fb34.png)

![image](https://user-images.githubusercontent.com/26605593/32397637-f658623e-c0a7-11e7-8f91-dca2ffcbfda3.png)

![image](https://user-images.githubusercontent.com/26605593/32397647-fc5eb6ec-c0a7-11e7-87e7-6a0609c05b8f.png)
[test1.txt](https://github.com/Komodo/KomodoEdit/files/1442591/test1.txt)

![image](https://user-images.githubusercontent.com/26605593/32397675-2b6d55e2-c0a8-11e7-9eee-c0871d35ce1d.png)

**Comment by mitchell-as** [comment]
Sounds like some timing issues.

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/293a561b2b0c57d336f97cfab20507190dd5729d
