### ISSUE TITLE
Komodo IDE 11.0.1: Refactoring variablesname doesn't work -> Exception... "[JavaScript Error: "legacy is not defined

### ISSUE THREAD

**Issue by onefloid** [Komodo/KomodoEdit#3342]
### Short Summary
When I try to rename variables, there is an Exception that the legacy is not defined. The extension Refactoring0.1 is enabled. Whene I try to open the mentioned url http://komodo.activestate.com/addons/refactoring/ . I only see an 404 error (404, baby!). 

On the same computer runs Komodo IDE 10.2.3. Here it works. 

### Steps to Reproduce
Here is an example code in perl .

`use strict;

my $word = 'abc';
my $word2 = 'abc2';

print $word;
`
Right click on $word and choose "Rename Variable". Then comes an exception notification.

### Expected results
Renamed Variables

### Actual results
Exception notification:
[Exception... "[JavaScript Error: "legacy is not defined" {file: "chrome://refactoring/content/refactoring.js" line: 89}]'[JavaScript Error: "legacy is not defined" {file: "chrome://refactoring/content/refactoring.js" line: 89}]' when calling method: [nsIController::doCommand]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 239"  data: yes]

### Platform Information

Komodo IDE 11.0.1
Windows 10 Pro

### Additional Information

[pystderr.log](https://github.com/Komodo/KomodoEdit/files/1443379/pystderr.log)

**Comment by mitchell-as** [comment]
Thanks for the report.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoIDE/commit/8e7a3cb7531d03bb2ce940e9b4a2180619ef99e6
