### ISSUE TITLE
Update dialog restart button did not restart Komodo IDE

### ISSUE THREAD

**Issue by mjross** [Komodo/KomodoEdit#3343]
### Summary
While using Komodo IDE 11.0.0, it prompted me to update to 11.0.1, which I started. After it downloaded all the update components (I'm guessing) in the background, a dialog asked if I wanted to restart immediately or later (I don't recall the exact wording). I clicked the button to restart Komodo IDE immediately, but it didn't restart on its own, even after I waited a long while (doing nothing else on the computer). So I manually started Komodo IDE and it is now 11.0.1. Thus, the update worked, except for the restart button. 

### Steps to Reproduce
Of course, I'm not able to reproduce it, as I have only one computer. :) Sorry this is so little to go on.

### Platform Information
Komodo IDE 11.0.0-then-11.0.1 on Windows 10.0.16299.19 Pro

### Attachments
[pystderr.log.txt](https://github.com/Komodo/KomodoEdit/files/1443713/pystderr.log.txt)

**Comment by Naatan** [comment]
Thanks @mjross, unfortunately the error log truncates on restart, and the one you attached appears to be from after the restart.

@cgchoffman did you use the update prompt on windows?

**Comment by mjross** [comment]
I see. Perhaps a good enhancement, if possible, would be that error log
truncation is delayed if the restart is due to an update.

**Comment by cgchoffman** [comment]
@Naatan I have not.  I'll try it now though.

**Comment by cgchoffman** [comment]
It worked fine for me.

**Comment by mjross** [comment]
I swear my Win10 is haunted...  :)  Next update, I'll try to remember to
save the logs before and after.

**Comment by Naatan** [comment]
:)

**Comment by rholland** [comment]
I have seen the same behavior across a number of events that require restart e.g. loading add-ons. Ko 11 often does not restart

**Comment by Naatan** [comment]
You could put `ko.utils.restart()` in a userscript and invoke that.
