### ISSUE TITLE
Symbol browser shows "No Symbols found" for perl

### ISSUE THREAD

**Issue by pju55** [Komodo/KomodoEdit#3344]

**Comment by Naatan** [comment]
Please provide more details. A code sample would be useful.

**Comment by pju55** [comment]
I would be happy to provide more details. 
But, as I said in the initial issue - no matter what perl script I open - the symbol browser shows "No symbols found".
If I open for instance some c-code, the browser works fine.
So I don't know what to provide. If you can help me further down the road I would be happy to provide.

PS: I find it a little cheap to close it on invalid label when it refers to an old issue which hasn't been solved although closed.

**Comment by pju55** [comment]
Sorry, I can see above, that the text I wrote initially didn't make it into the issue!
So, it was fair to close it. Can see the old issue has been re-opened.

**Comment by Naatan** [comment]
We'll handle this in #3205
