### ISSUE TITLE
Unit-testing extension change request related to pytest parsing

### ISSUE THREAD

**Issue by devdave** [Komodo/KomodoEdit#3345]
### Short Summary
PyTest has parametrizing fixture thing documented here https://docs.pytest.org/en/latest/parametrize.html

Using it changes the test output slightly

### Steps to Reproduce

Example output is:
txweb/tests/test_smartcontroller.py::test_argshandlingLogic[ExampleController] PASSED
txweb/tests/test_smartcontroller.py::test_requestAttrHandlingLogic[ExampleController] PASSED
txweb/tests/test_smartcontroller.py::test_default_Arguments_Works_As_Expected[ExampleController] PASSED
txweb/tests/test_smartcontroller.py::test_everything_method PASSED

### Expected results

Using the Komodo IDE unit-testing extension, all of the above tests are run, BUT it only shows "test everything method" in the results while skipping the ones with brackets and the parameterized fixture (in this case ExampleController).

Komodo IDE
Version's 10 and 11 (likely all prior as well)

### Additional Information

Issue is found here (and pytest3 but was unable to find that parser)

unittest@activestate.com.xpi/unittest.jar/content/sdk/parsers/pytest.js#17

Currently the regex is var entryRx = /^(.*?)::(\w+?)\s([A-Z]+)$/;

a rough replacement (.*?)::([\w+\[\]]+)\s([A-Z]*) works in matching both the basic case and the parameterized output.

**Comment by Naatan** [comment]
Thank you for the detailed report!
