### ISSUE TITLE
Komodo edit 11.0 - Print preview is blank under windows 10

### ISSUE THREAD

**Issue by Zebrafish007** [Komodo/KomodoEdit#3346]
### Short Summary

Upgrade from 10.2.3 to 11.0 few days ago went generally smooth but now I hit a minor bump: print preview hits a blank page. Attached the error-log.

### Steps to Reproduce

Opened random py-file (using 2.7.14 or 3.6. engine) and went straight to print preview.

### Expected results

blank "grayish" page without radio-bottons, text panes, type-bars, etc.. Window-name is "print preview".

### Actual results

See error-log attachment.

### Platform Information

*Komodo Edit 
*Komodo Version 11.0  build 18119 
Operating System (and version): Windows 10 (10.0.15063)

### Additional Information

 
[pystderr.log](https://github.com/Komodo/KomodoEdit/files/1447681/pystderr.log)

**Comment by Naatan** [comment]
Thanks for the report!

**Comment by Zebrafish007** [comment]
No problems encountered with the py.file print preview in Komodo Edit 10.2.3 build 177708; platform win32-x86 under above stated OS and same py-engines. This edit 10.2.3 version is still installed in the nextdoor folder to edit 11.0. Not sure if that shows in the error-log thus therefore mentioned... just in case.
