### ISSUE TITLE
lag in python code completion 

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#3347]
### Short Summary
There is a lag in python code completion. This is sporadic for me and happens on any code. Also, I am NOT trying to type super fast. Please see attached gif.

### Steps to Reproduce
1. Use any python code
2. notice code completion is triggered after few seconds 

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo IDE, version 11.0.1, build 90797, platform win32-x86.
Built on Fri Oct 27 14:40:19 2017.
### Additional Information
![image](https://user-images.githubusercontent.com/26605593/32468797-9cc94e40-c304-11e7-8658-a9b18a89291a.png)
![code_completion_k11 0 1_python](https://user-images.githubusercontent.com/26605593/32468833-cd23388a-c304-11e7-8208-fd76af859fb8.gif)

**Comment by mjainQA** [comment]
Observation: Code completion is getting triggered after `)`, no matter how slow I type.

**Comment by Naatan** [comment]
Fairly certain this is the same issue as #3341
