### ISSUE TITLE
Codeintel often not finding definition

### ISSUE THREAD

**Issue by tuckdesign** [Komodo/KomodoEdit#3349]
### Short Summary
Codeintel in Komodo IDE 11.0.1 is not working at all between files. It works only in one file but doesn't find any definitions in another files.
Tried resetting codeintel database and as result Komodo did 'scan' files, but scanning took really too short (considering that I am working on big project with a lot of files).

### Steps to Reproduce
Open project with multiple php classes that include one class into another.
In one of files click on 'Go to Definition' on class method that is defined in another file. 

### Expected results
Method should be found and cursor placed on that method in another file.

### Actual results
Method is not found with message in notifications 'Could not find definition'.

### Platform Information
Komodo IDE 11.0.1
OSX Sierra 10.12.6

**Comment by Naatan** [comment]
Any chance you still have Komodo 10 installed? Could you see if the same symbol can be found in Komodo 10?

**Comment by tuckdesign** [comment]
Hm, no. Can't get any definition in 10.2.3 also. Here I see it is scanning files (in 11.01 it is not scenning files, or not reporting that), but I get 'error determining definition'

**Comment by Naatan** [comment]
Ok, in that case we cannot work on this unless we have code that reproduces the issue. Are you able to share a test case?

**Comment by tuckdesign** [comment]
Not this one but will make you one an put on github.

**Comment by tuckdesign** [comment]
Here is git repository with only 2 php classes: https://github.com/tuckdesign/test_project
Codeintel is not working even there:
Open project and within it file2.php, right click on staticMethod in line 14 and then 'Go to definition'. It doesn't work. Same happens with other methods.

**Comment by Naatan** [comment]
Reproduced, note though that on line 14 you wrote "TextClass1", this should be "TestClass1". However after fixing Go to Definition still does not work.

**Comment by Zebrafish007** [comment]
Got also CodeIntel not working properly on 10.2.3 while 11.0 is running next to it. Nothing changes if both are closed and one of them is reopened. I hope that helps to figure it out further.

**Comment by Naatan** [comment]
@Zebrafish007 to be clear, you're having this exact issue raised here? I don't want to lump all "codeintel doesnt work as expected" issues into this one ticket.

**Comment by Zebrafish007** [comment]
@Naatan I want to prevent "duplicate" bugreports on exact (imo) same topic therefor my added info above. For me its python files and not php... so I thought... adding this info here would maybe help you? Just to be sure.... from your response I should have made a new ticket anyway?

**Comment by Naatan** [comment]
@Zebrafish007 if your issue is around go to definition and matches the rest of the description given here then no, this is fine. I just want to make sure that's the case as it wasn't necessarily evident :) Thanks!

**Comment by Zebrafish007** [comment]
That was the case. What I saw from my side is that blobs that were created 6th of November were not updated yesterday (23rd). Whereas I use good old notepad I see the filename and therefor know it should be updated lets say 3 days earlier. I figured out a nasty workaround this updatingbug.... just delete condeintel database (blobls.. etc)... this way Komodo Edit is forced to reconstruct a new codeintel.db and symbol.db the hardway whe you start the program the next time (fresh). Doesn't happen during a boot from "sleep" modus. Cold and fresh... thats how this trocical predator "The Komodo" likes its fish ;-)

**Comment by Naatan** [comment]
@Zebrafish007 hold up, you're using Komodo Edit? This bug is for Komodo IDE. If you are using Edit then we should in fact have a new bug report.

**Comment by Zebrafish007** [comment]
... just checked once more to be sure but yes its Komodo Edit, version 11.0.1, build 18119, platform win32-x86. Built on Fri Oct 27 23:54:50 2017. As mentioned before I've got also running Komodo Edit, version 10.2.3, build 17708, platform win32-x86. Built on Tue Jul 11 21:59:10 2017. So..new bugtag I guess. I'll toss one on Monday. Got a multiprocessing thingy this weekend to fix.

**Comment by Zebrafish007** [comment]
someone beat me almost to it under #3384. I'll post it anyway becasue his is IDE and mine id EDIT.

**Comment by mitchell-as** [comment]
This appears to have been fixed in master. I suspect it was a side-effect of the new "fuzzy matching" introduced for 11.1.

**Comment by tuckdesign** [comment]
@mitchell-as Why did you close this when it is still not working? Using Komodo IDE 11.0.2, build 90813. Tried with that simple test project that I gave you for testing (https://github.com/tuckdesign/test_project). Behaves the same as before, nothing fixed.

**Comment by tuckdesign** [comment]
@mitchell-as Ah, sry, you say 11.1. When will it be released?

**Comment by mitchell-as** [comment]
I'm not sure @tuckdesign, sorry. I hope it will be in a nightly soon though.

**Comment by tuckdesign** [comment]
@mitchell-as any idea when this will finally go out (even as nightly)? codeintel is pretty much dead without this fix :(

**Comment by mitchell-as** [comment]
@tuckdesign No, I'm afraid I don't know the answer to that :( Sorry.

**Comment by Naatan** [comment]
@tuckdesign likely in Q2, this will be part of Komodo 11.1 which is a larger update and needs some more time to be put through its paces.

**Comment by tuckdesign** [comment]
@Naatan Is anyone working on Komodo any more? There was no update (not even nightly) for too long... Is Komodo dead?

**Comment by Naatan** [comment]
@tuckdesign we're actually working on getting an update out hopefully this week. Sorry it's been so long.

**Comment by the6thBook** [comment]
I'm having the same issue. Komodo IDE, version 11.1.0, build 91033, linux-x86_64

**Comment by tuckdesign** [comment]
Yes, still present in 11.1.1 (nightly)... sometimes it does find definition but it is TOO slow. I find definition faster by doing global search and looking for 'function <name>'... that's sad because codeintel was really one of most important advantages I saw in Komodo (when it was working properly)

**Comment by tuckdesign** [comment]
Don't want to open new thread for something that is still not working. Honestly, I switched back to Komodo IDE 9.3.2 and it is much faster and codeintel is working in 90% of cases. It looks like moving codeintel from main thread was mistake, it works worse from Komodo 10 then it worked in 9.x. Also, @Naatan updates and releases are coming out too slow. Are you dropping Komodo as a product?

**Comment by skralg** [comment]
I have this same problem, Komodo Edit, version 11.1.0, build 18196, platform linux-x86_64.
The only difference is that my project uses Perl, with several perl modules in use.
