### ISSUE TITLE
Komodo IDE 11.0.1: Unit Test Tab is troubling with dots...

### ISSUE THREAD

**Issue by onefloid** [Komodo/KomodoEdit#3355]
### Short Summary
When I'am using dots '.' in the comment of a testing function the view of the result tab is breaking. Furthermore all dots are replaced with whitespaces.

### Steps to Reproduce

Here is a code snippet in Perl:
use strict;
use warnings;
use Test::More;

is( '1', '1', 'Hello. 1' );
is( '1', '1', 'Comment: ....' );
is( '3', '3', 'Hello. 3' );

done_testing;

1. Create the Unittest Config
3. Run the Unittest

Now there are no dots in the comments in the result tab. And the second test line isn't checked as 'ok'. stdout is correct.  
 
### Expected results
1 (1) Hello. 1
2 (2) Comment: ....
3(3) Hello. 3

### Actual results
1 (1) Hello 1
'>'ok 2 - Comment: 1/0/0
3(3) Hello. 3

Also look at the picture at the end...

### Platform Information

*Komodo  IDE 11.0.1* 
*Windows 7 SP1* 

### Additional Information
![image](https://user-images.githubusercontent.com/33193059/32663872-c0b2edc4-c62f-11e7-9d6e-7f810cc6195d.png)

![image](https://user-images.githubusercontent.com/33193059/32664290-18c491a6-c631-11e7-9533-0f9db2bed22d.png)

[pystderr.log](https://github.com/Komodo/KomodoEdit/files/1461731/pystderr.log)

**Comment by Naatan** [comment]
Thanks for the detailed report!

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/f4f2db791893c077123038e402ad00039e71df5f
