### ISSUE TITLE
Problems with non-ascii characters

### ISSUE THREAD

**Issue by GrahamStuart** [Komodo/KomodoEdit#3356]
### Short Summary

Symbols browser breaks if even one multi-byte character, or character \x80 -> \xff, is in the file.

### Steps to Reproduce

Take any known good file eg: alembic-script.py, and add an illegal character in a comment line.

`
`#!C:\Python35\python
`# -*- coding: utf-8 -*-
`import re
`import sys
`
`# 特
`
`from alembic.config import main
`
`if __name__ == '__main__':
`    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
`    sys.exit(main())
`
`

### Expected results

Symbols browser works before the comment line is added, and should work after the comment line is added.

### Actual results

"No symbols found" after the comment line is added. Removing the comment lets the Symbols browser work again.

### Platform Information

Komodo IDE 11 on Windows

### Additional Information

This message seems to be related:
Error console-logger: TypeError: data is null (2) in chrome://codeintel/content/sdk/feature/completeions.js.129
Traceback : File "chrome://codeintel/content/sdk/feature/completions.js", line 129, in
-->

**Comment by mitchell-as** [comment]
Hi, have you updated to Komodo 11.0.1 yet? That should have fixed this issue.

**Comment by GrahamStuart** [comment]
Yeah. There was a report that 11.0.1 fixed this temporarily, but I'm not seeing that. I did a complete remove and re-install. 11.0.1 does what 11.0 did, at least for me.

**Comment by mitchell-as** [comment]
Okay, I'll investigate then. Thanks for your patience.

**Comment by mitchell-as** [comment]
Hi, I am not able to reproduce this issue with the following file contents:
```
#!C:\Python35\python
# -*- coding: utf-8 -*-import re
import sys
from alembic.config import main
 # 特
if __name__ == '__main__': sys.argv[0] = re.sub(r'(-script.pyw?|.exe)?$', '', sys.argv[0])
sys.exit(main())
def foo():
    pass
```

My symbol browser shows the "foo" function, regardless of whether or not the Asian character is present. Perhaps Komodo 11.0.2 ended up fixing this.
