### ISSUE TITLE
Multiple issues with CodeIntel on Komodo IDE 11.0.1

### ISSUE THREAD

**Issue by Torgha** [Komodo/KomodoEdit#3357]
### Short Summary

Hello, I installed the trial version of Komodo IDE 11.0.1 as I am looking for a new IDE for my developments. The first project I added in Komodo is a symfony 3 project for a REST API (so a PHP project with large amount of files). 
The problem is that I cannot get CodeIntel working. Firstly, in the settings, the codeintel scan depth is set to 20. The summarization is done with a depth of 20 but if I disable the prompt for large file scanning, codeintel will scan with a depth of 0, which is not useful. Once the scan is done correctly (so when I get the prompt for scan and I modify the depth defaulted to 0 in that window), the codeintel log contains errors and is not working. Resetting the codeintel database via Help menu or manually with deletion of codeintel3.db in profile does not resolve the problem.

### Steps to Reproduce

- Install a fresh Komodo IDE 11.0.1
- Add a symfony 3 project
- Make the first codeintel scan of the project 

### Expected results

CodeIntel shows completion options when typing in a php file

### Actual results

No completion appears.

### Platform Information

Komodo IDE 11.0.1
Mac OS High Sierra 10.13.1

### Additional Information

For further information, here are the logs and screenshots that could be useful:

- Screenshot of CodeIntel settings:
<img width="512" alt="capture d ecran 2017-11-12 a 15 50 44" src="https://user-images.githubusercontent.com/9369204/32700152-56435f30-c7c1-11e7-86b9-05108115694c.png">
- Screenshot of CodeIntel scan prompt (The 0 displayed in Max Depth field should be 20 for me what I modify manually for the scan):
<img width="606" alt="capture d ecran 2017-11-12 a 15 53 08" src="https://user-images.githubusercontent.com/9369204/32700226-2c192e46-c7c2-11e7-845c-e47a4f280b2c.png">
- Screenshot of scan in progress:
<img width="1082" alt="capture d ecran 2017-11-12 a 16 02 00" src="https://user-images.githubusercontent.com/9369204/32700282-009b24c6-c7c3-11e7-9c3b-63d6787c6ade.png">
- Content of "codeintel3.log" after end of scan and tried to get completion in php file:

[codeintel3.log](https://github.com/Komodo/KomodoEdit/files/1464796/codeintel3.log)

- Content of "pystderr.log":

[pystderr.log](https://github.com/Komodo/KomodoEdit/files/1464797/pystderr.log)

**Comment by mitchell-as** [comment]
Hi, thanks for the detailed report and your error logs.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/codeintel/commit/e851dbecfbe342778d2ab17a09653dd55f770dd1 and https://github.com/Komodo/codeintel/commit/99b2b63046f5e351ea029b0db870a902f2263902
