### ISSUE TITLE
Userscript runtime error

### ISSUE THREAD

**Issue by louyo** [Komodo/KomodoEdit#3358]
### Short Summary

Newfile creates runtime error. Opens OK though

### Steps to Reproduce
Start Komodo 11.0.1 and click on the New File button

### Expected results
Open new file in the editor, probably be nice if it asks for type. 

### Actual results
Opens new file but opens a dialog saying runtime error, names the new file with .txt extension

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 

Komodo IDE, 11.0.1.

**Comment by louyo** [comment]
Should have said:
1. I am running on Linux, Mint 17.1. 
2. Komodo IDE 10 does not do this.

**Comment by louyo** [comment]
(Louyo obviously has never done this)

**Comment by Naatan** [comment]
Can you reproduce this using `Help > Troubleshooting > Restart in Safe-mode` ?

Please verify that when restarting in safe-mode Komodo should be using the default UI (all your settings would be temporarily reset).

**Comment by louyo** [comment]
OK, safe mode works OK. So, I deleted the 11.0 directory and let it create a new one. That also "fixes" it. So, I copied all the files (not the directories) from the bad 11.0 to the new one. It failed. Alas, that doesn't always recreate the problem, I had tried to narrow it down to which file. Since a new 11.0 fixed it, I give up trying to recreate it. Now to recover the preferences I screwed up. :)

**Comment by Naatan** [comment]
Try copying everything except your Tools and Extensions folders, most likely the issue is in one of those.
