### ISSUE TITLE
Adding Additional Directories to CodeIntel Does Prompt a Scan

### ISSUE THREAD

**Issue by mitchell-as** [Komodo/KomodoEdit#3359]
### Short Summary

When adding an additional directory for CodeIntel via Edit > Preferences > Languages > X > Additional X Import Directories, CodeIntel will not initiate a scan of that directory, but just assume that it is already scanned. This is not a problem if the directory is a child of the current project, but it is a problem when the directory is outside the project (e.g. in a directory created by `pip install`, `cpan install`, `gem install`, etc.)

### Steps to Reproduce

Create a directory and module file such as `/tmp/foo/` and `/tmp/foo/bar.py` where `bar.py` contains:

```
class Bar:
    pass
```

Now add `/tmp/foo` to Edit > Preferences > Languages > Python > Additional Python Import Directories.

Create a simple Python file such as `/tmp/foo.py` (as long as no project with a root of '/tmp' is open) or with another name outside a project that contains `foo/bar.py`.

Type `from `.

### Expected results

A completion list that contains the `bar` module from `bar.py` in the Additional Python Import Directories.

### Actual results

No `bar` in the list.

### Platform Information

*Komodo Edit or IDE?*  IDE
*Komodo Version?* 11.0.1
*Operating System (and version)?* Any

### Additional Information

My full `/tmp/foo.py` file is

```
from bar import Bar
print Bar()
```

This runs properly in the Python interpreter, so the expected `bar` completion is valid.

**Comment by michael-weinstein** [comment]
Is there any word on a fix for this?

**Comment by mitchell-as** [comment]
No, not yet. It is scheduled for Komodo 11.1 though.

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/c96152de45863d9171f41b7252b7f7e138dfdf92
