### ISSUE TITLE
CSS don't auto complete after ,

### ISSUE THREAD

**Issue by nathanielb** [Komodo/KomodoEdit#3360]
### Short Summary
It would be nice if the CSS auto complete did not pop up after typing a comma <kbd>,</kbd>. When writing CSS for Drupal the coding standards state that each selector should be on a new line. If I type one selector then comma and press enter it selects whatever the first item is on the auto complete list that pops up. 

### Steps to Reproduce
Create a new CSS file test.css. Start typing a selector .test-one type a comma <kbd>,</kbd> and press <kbd>Enter</kbd> I end up with `.test-one,.test-one`.

### Expected results
I expect to have .test-one, and a new line to start typing my next selector.

`.test-one,
`

### Actual results
`.test-one,.test-one`

### Platform Information
Komodo IDE, version 11.0.1, build 90797, platform win32-x86

### Additional Information
Wordpress also has similar coding standards.

https://www.drupal.org/docs/develop/standards/css/css-formatting-guidelines#rule-sets
https://make.wordpress.org/core/handbook/best-practices/coding-standards/css/#structure

Workaround is to press <kbd>Esc</kbd> then <kbd>Enter</kbd>.

**Comment by mitchell-as** [comment]
Thanks for the report. This sounds reasonable.

**Comment by cgchoffman** [comment]
https://github.com/Komodo/codeintel/commit/7f8ea3fa539d3b6258c19bbf0
https://github.com/Komodo/KomodoIDE/commit/1d49f6cef5255e9635c4e38bc21e481ae4302eaaad6934c5c83804f
