### ISSUE TITLE
Code completion in Python3

### ISSUE THREAD

**Issue by michael-weinstein** [Komodo/KomodoEdit#3361]
### Short Summary
Code autocompletion appears not to be parsing anything but the built-in libraries from python.  Komodo 10 still working fine for this.

### Steps to Reproduce
Running Komodo IDE 11 on a windows machine (have not tested on other operating systems).

### Expected results
I was expecting autocompletion to show up for python packages like numpy and pandas that were installed after python.

### Actual results
I can see autocomplete for packages like TTY and math that came with the python installation, but get nothing from packages that were pip3 installed.  I already checked the __file__ value for packages that are loading properly and found that the libraries were being loaded from the expected location.

### Platform Information

*Komodo Edit or IDE?*   IDE
*Komodo Version?*   11.01
*Operating System (and version)?*  Windows 10 (latest)

**Comment by mitchell-as** [comment]
Hi, normally you would be able to add extra libraries for CodeIntel via Edit > Preferences > Languages > Python > Additional Python Import Directories. However, this feature is currently bugged and we're tracking it here: https://github.com/Komodo/KomodoEdit/issues/3359. Also, we are looking into a way to automatically scan installed packages here: https://github.com/Komodo/KomodoEdit/issues/3017.

Note that CodeIntel cannot scan and provide completions for C libraries like Numpy.
