### ISSUE TITLE
Code Completion especially in CSS/SCSS files

### ISSUE THREAD

**Issue by petewulf** [Komodo/KomodoEdit#3363]
### Short Summary

Code Completion suggests senseless attributes when entering ENTER:  

"-moz-appearence", 
"-moz-background-clip"
...

This is COMPLETELY SENSELESS as Code suggestions/completions only makes sense when entering a character...nobody, nearly nobody ever all over the world needs "moz-appearance" as a default action when hitting the ENTER key.

### Steps to Reproduce
Press Enter immediately after opening bracket "{

### Expected results

.test{

 }

### Actual results

After pressing 9 times ENTER:

.test{
		-moz-appearance: -moz-mac-unified-toolbar
		
		-moz-mac-unified-toolbar
		
		-moz-mac-unified-toolbar
	}

### Platform Information

Komodo v11.01

**Comment by Naatan** [comment]
https://github.com/Komodo/codeintel/commit/b626de943ac72c9f3ea209414f175f43d52d226a
