### ISSUE TITLE
Notifications are Persistent and won't go away.

### ISSUE THREAD

**Issue by codermjb** [Komodo/KomodoEdit#3365]
### Short Summary
Notifications show up and don't disappear. You can't close them or disable them. And they still show up even if you move Komodo to a different screen, or even mimimize it, it still shows up in the same spot. Screenshot: http://prntscr.com/hajq30

### Steps to Reproduce
Open Komodo or even a project, Komodo likes to do some sort of scanning.

### Expected results
Notification to show, but then disappear.

### Actual results
Notification stays open, wont close with the x, gear and clicking don't show notification doesn't do anything. You have to close down Komodo completely for the notifications to disappear.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 11.0.1 nightly
*Operating System (and version)?* Xubuntu 16.0.4.2 LTS

**Comment by Naatan** [comment]
Please share your error log after reproducing the issue.

You can find your error log at Help > Troubleshooting > View Log File.

**Comment by mitchell-as** [comment]
@Naatan I seem to recall this being a Mozilla issue? Or perhaps that was with tooltips?

**Comment by Naatan** [comment]
That was the tooltips, and even that could eventually be worked around.

**Comment by babobski** [comment]
I have a same kind of issue open for this #2108

**Comment by Naatan** [comment]
Closing this in favour of #2108
