### ISSUE TITLE
KEdit 11.0 - settings customized left/right bottom pane seem to disappear after windows 10 crash

### ISSUE THREAD

**Issue by Zebrafish007** [Komodo/KomodoEdit#3367]
### Short Summary

Every now and then after Win10 crash default settings seem to be used by Edit11 for setting  pane left/right/bottom back to its original default state away from customized state bu user. This error happens also if Edit 11 uses more than 700mb of RAM memory (solely a Edit 11 crash).

After moving "places" and "open files" for the 20th time to teh right pane and everything from bottom pane to the right pane... I finally gave up and surrendered on submitting this as a possible bug.

### Steps to Reproduce

I wish I knew how to recreate it except for running 10 py-files for about a week and hit wake-up or sleepmode on my machine (internal mem hits by then 700ish mb size in internal mem.

### Expected results

Steam out of the ears, more grey hear, numb arm and frustration spamming from eyes, lost time to adjust the panes again.

### Actual results

Where to get this type of error log..if its registered?

### Platform Information

*Komodo Edit or IDE? Edit.
*Komodo Version?*  10.2.3 and 11.0
*Operating System (and version)?* Windows 10, 64bit.

### Additional Information

. See my other bug submission for more OS details.

I've checked AppData\Local\ActiveState\KomodoEdit\11.0\pystderr.log
but it doesn't show the crash and pane reset. Another errorlog perhaps?

**Comment by cgchoffman** [comment]
> Expected results
> 
> Steam out of the ears, more grey hear, numb arm and frustration spamming from eyes, lost time to adjust the panes again.

You expect to have a heart attack using Komodo?  That's an interesting use case.

Quite a few restoration bugs have been fixed and will be in 11.1.  I think this one refers to yours most: https://github.com/Komodo/KomodoEdit/issues/2000#issuecomment-337732968

**Comment by Zebrafish007** [comment]
Ooh .. wow...  lots of peeps having those then I guess. I see.. Good luck fixing it. .. (swims back to his own fish pool). Cheers for the link... was gonne ask for it. (apparently not all searchkey words I used showed in the original post).

**Comment by cgchoffman** [comment]
> apparently not all searchkey words I used showed in the original post

It took me a good 10 minutes to find that ticket.
