### ISSUE TITLE
Minimize svg images

### ISSUE THREAD

**Issue by tormec** [Komodo/KomodoEdit#3374]
I've notice that Komodo uses several svg images. Not all but some of them (maybe 50??) are over 1 kB and they can be minimized.

I've tried with some files in `/lib/mozilla/chrome/icons/default/fileicons/` and, for example, an image of:
  * 1.3 kB can be compressed till 920 B
  * 2.4 kB can be compressed till 1.1 kB
  * 3.1 kB can be compressed till 1.3 kB

For this test I've used a free online tool (https://kraken.io/web-interface).

Perhaps you won't save much weight so .. do as you think best.

### Platform Information

*Komodo Edit 11.0.1*

**Comment by mitchell-as** [comment]
Hi, thanks for your suggestion. Unfortunately, this would just be another step in our build process, and the effort and time spent does not justify the size decrease.
