### ISSUE TITLE
Cant install latest version from website

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3379]
### Short Summary
Just wanted to install Komodo 11 from the [official website](https://www.activestate.com/komodo-ide/downloads/ide).
But I'm unable to run the installer:

![afbeelding](https://user-images.githubusercontent.com/3530262/33154805-6656e3ce-cfeb-11e7-82d3-37e28d62cb51.png)

**Comment by cgchoffman** [comment]
Works fine for me.  I don't know what that error message says though.  Can you please translate to English @babobski?  I'd just try downloading the installer again if that's the "this isn't an installer" error.

**Comment by babobski** [comment]
I first ran into a windows safety error, that the installer was unsigned.
I clicked the more info, so I the "proceed anyway" button appears.

But after proceeding I was getting the following error.

The translation:

```
Can not open this installation package.
Contact the application vendor to verify that the package is a valid Windows Installer package.
```

I just deleted the download and retried, but this time I'm not getting any error.

**Comment by Naatan** [comment]
> I just deleted the download and retried, but this time I'm not getting any error.

Sounds like your Download was corrupted, maybe a connectivity issue.
