### ISSUE TITLE
Ctrl

### ISSUE THREAD

**Issue by jcloggins** [Komodo/KomodoEdit#338]

**Comment by cgchoffman** [comment]
No Ctrl.

**Comment by Defman21** [comment]
Ctrl works fine in Komodo btw.

**Comment by cgchoffman** [comment]
I would hope so or your keyboard would be broken me thinks.  Ignore my comment.  The bug is closed by the person that opened it as well so no need to follow up.

**Comment by Naatan** [comment]
I've always preferred Alt.

**Comment by cgchoffman** [comment]
> I've always preferred Alt.

Oh man, me too!
