### ISSUE TITLE
Komodo 11: Code Intel very slow for PHP

### ISSUE THREAD

**Issue by mikethicke** [Komodo/KomodoEdit#3380]
### Short Summary

When using Komodo for Wordpress development, Code Intel is extremely slow and inconsistent for autocomplete, and fails on "Go To Definition".

### Steps to Reproduce

1. Create PHP project in top-level directory of stock Wordpress install.
2. Add one file to wp-content folder
3. In Preferences|Code Intelligence, check all options under "Features", "Scanning", "Editing". Set Max directory depth to 10, Max files to scan without prompting to 100.
4. Reset Code Intelligence database.
5. Create short local function - hello($name, $day) with phpdoc-style comment
6. Write call to that function
7. Write call to external Wordpress function
8. Right-click the external function, select "Go to Definition".

### Expected results

When I type "hell" the local hello function should be an autocomplete option. When I select that option or press TAB, it should complete "hello()" with my cursor in the parentheses and the calltip for the function showing the documented parameters. When I press CMD-J after entering a value for the first parameter, it should again show me the calltip.

When I type "register_p" it should suggest "register_post_type" as the suggested completion. When I press TAB or select that option, it should act as for a local function. When I start to write parameters, it should show me the calltip for that function based on its documentation (Wordpress functions use phpdoc). When I press CMD-J, it should bring the calltip back if it has gone away. When I right-click and select "Go to Definition", it should open the file containing that function (post.php) and bring me to its definition.

### Actual results

When I type "hell", after 5 seconds various completions appear, including the local function. If I press TAB, it autocompletes the top result (a non-local function, 'hello_dolly'). If I select 'hello' from the list, it autocompletes 'hello' but without the parentheses. If I type the left parenthesis, then after a few seconds, sometimes the calltip for the hello function appears; but sometimes instead suggested completions for 'hello' appear, so that if I select one I get "hello(hello)"; and sometimes the calltip will appear for a few seconds before it changes to suggested completions for 'hello'. Rarely, I can actually see the documentation for my parameters instead just the function definition ('hello($name, $day)'). Going to function definition goes to the local function definigion.

When I type 'register_p' after a few seconds the expected completion appears, and pressing TAB completes as before. A calltip for the function never appears, either by waiting or pressing CMD-J. When I try to go to the function definition, it fails with error "Could not find definition". If I search for the function in the "Go to Anything" bar, the function is found, and selecting it takes me right to the function definition in post.php as expected.

In general, Code Intelligence is so slow that it would be essentially useless even if it did act consistently.

### Platform Information

Komodo IDE, version 11.0.1, build 90797, platform macosx.
Built on Fri Oct 27 15:20:52 2017.

macOS High Sierra
Version 10.13.1
MacBook Pro (15-inch, 2016)
Processor 2.6 GHz Intel Core i7
Memory 16 GB

### Additional Information

![ko2](https://user-images.githubusercontent.com/26980498/33194465-2a725010-d09e-11e7-8fa0-2bb00a08c09a.jpeg)
![ko1](https://user-images.githubusercontent.com/26980498/33194471-304ad4b2-d09e-11e7-8d0a-4bdbef0ea81b.jpeg)
<img width="1362" alt="ko3" src="https://user-images.githubusercontent.com/26980498/33194518-6dbb5132-d09e-11e7-99ec-9d9e96af9ea2.png">

**Comment by Naatan** [comment]
Thanks for the detailed report!

**Comment by Naatan** [comment]
Revised this ticket to address the slowness. The other points are being addressed in 11.1.

**Comment by mikethicke** [comment]
Bumping this as CodeIntel has never worked for me for PHP on MacOS, as described above.

**Comment by cmilner-rescon** [comment]
I'm having the same problem however Codeintel doesn't work at all for me. Fresh install of Komodo IDE (version 11.1.1, build 91089), done a Help > Troubleshooting > Reset Everything, new blank project, with one PHP file, and 1 variable and nothing. Any help would be greatly appreciated.

**Comment by cgchoffman** [comment]
@cmilner-rescon, this ticket is about code intel being slow.  Please open a forum post to figure out why code intel isn't working for you: 
https://community.komodoide.com/

I was testing PHP just the other day and it was working fine so i'm sure we can get your issue resolved.

**Comment by cgchoffman** [comment]
@mikethicke, I'm going to close this in favour of #3649 as the fixes implemented from that ticket will hopefully resolve this ticket as well.
