### ISSUE TITLE
Slow response when clicking Komodo edit in taskbar (o switching apps in taskbar)

### ISSUE THREAD

**Issue by gusarg81** [Komodo/KomodoEdit#3381]
### Short Summary
When saving changes in a file, Komodo Edit taskbar freeze for seconds (and normalize after saving process finishes). So clicking between apps will have no effects during that process (works if I use Alt+Tab). This problems is happening since I use Komodo Edit from version 9 till now (version 11.x).

### Steps to Reproduce
Make changes in a file and try to click to another app in the taskbar and nothing happens after seconds (or after saving process finishes).

### Expected results
Should behave like any other app located/minimized/etc. in taskbar.

### Actual results
The slow response to switch between applications located in taskbar by clicking.

### Platform Information
*Komodo Edit* 
*Komodo 11.0.1* 
*KDE Neon (latest KDE 5.x), which is an oficial KDE distro based in Ubuntu 16.04 LTS (https://neon.kde.org/)* 

### Additional Information
This problem is only present in Komodo Edit.
 
Thanks.

**Comment by Naatan** [comment]
Are you using remote files?

**Comment by gusarg81** [comment]
Hi,

    Nope, always Local files. Also sometimes happens after writing some code. I don't have any kind of addons either.

**Comment by Naatan** [comment]
I assume it only happens when switching to/from Komodo, and not other apps?

**Comment by gusarg81** [comment]
Well, it freeze any apps located in taskbar for seconds (not just Komodo Edit). Meanwhile I can switch between apps with Alt+TAB, I can't by mouse click.

As in my report said, this only behavior happens when I use Komodo edit.

**Comment by Naatan** [comment]
> freeze any apps located in taskbar for seconds (not just Komodo Edit)

> this only behavior happens when I use Komodo edit

These two phrases seem to contradict each other, can you elaborate?

**Comment by gusarg81** [comment]
Does not contradict at all. What I mean that this behaviour does not happen when using any other app. The only app that freeze the taskbar is when using along Komodo Edit.

**Comment by Naatan** [comment]
Meaning when Komodo is open you get taskbar freezes amongst all apps?

**Comment by gusarg81** [comment]
It freezes all the taskbar.

**Comment by Naatan** [comment]
I'm on Plasma myself so I can't imagine it's something with that. Can you reproduce this with Help > Troubleshooting > Restart in Safe-mode?

**Comment by gusarg81** [comment]
As soon I can I will test that. Now not lets forget that this is Happening in my 2 computers, since First time using Komodo v9, tested in Kubuntu in th past and now in KDE Neon.

**Comment by gusarg81** [comment]
Ok, I've tested in Safe-mode and still the same problem.

**Comment by Naatan** [comment]
You know now that you've mentioned this I have started noticing occasionally that I can't click my task bar. I haven't seen any evidence of it being connected to Komodo though, as it is super sporadic and without any identifiable cause. Have you found some reliable steps to reproduce the issue? You said file saving, but so far that doesn't really seem to trigger it for me.

**Comment by gusarg81** [comment]
Yeah, but always happen when i save a file (at least I am 90% sure), now the other times I am not exactly sure how often. Maybe a syntax checking problem or anything else? I don't know.

**Comment by Naatan** [comment]
Could you see in with a process monitoring tool whether the taskbar freezes correlate to high cpu usage for a process?

**Comment by gusarg81** [comment]
Hi,

    I didn't saw high CPU usage in that moment.

**Comment by Naatan** [comment]
I've been tracking the issue on my end and frankly I think this is a bug in Plasma rather than Komodo. I've seen it happen numerous times now when Komodo wasn't actually doing anything. And even if Komodo were doing something: That's no reason for a taskbar to hang. The issue here is with Plasma, not Komodo.

**Comment by gusarg81** [comment]
And how you are so sure of that being the only app with this problem?

A shame then, have to star looking for another IDE.

**Comment by Naatan** [comment]
> And how you are so sure of that being the only app with this problem?

I'm not. Regardless, it doesn't change what I said. This isn't a bug in Komodo, it's a bug in Plasma.

**Comment by gusarg81** [comment]
Even if that true, your way to "decide" that is Plasma Bug has not evidence of it (Is just because you say so). What a shame that developers like you exist. A bad image to us, the good ones :).

**Comment by Naatan** [comment]
Completely uncalled for. If you are who you think yourself to be maybe don't escalate discussions to a toxic level.
