### ISSUE TITLE
Blinking scrollbars in snippet property editor

### ISSUE THREAD

**Issue by neurobashing** [Komodo/KomodoEdit#3382]
### Short Summary
The scrollbars in property editor windows blink. It's disconcerting.

### Steps to Reproduce
Edit the properties of a snippet.

### Expected results
No blinking scrollbars

### Actual results
Blinking scrollbars, a mild headache

### Platform Information

Komodo IDE, version 11.0.1, build 90791, platform macosx.
Built on Sun Oct 15 23:56:34 2017.

But I tried it on edit (also latest nightly) and it occurs everywhere there (even in editor windows).

### Additional Information
capture:
https://imgur.com/a/5tsuv

**Comment by Naatan** [comment]
Thanks for the report. We are tracking this here: https://github.com/Komodo/KomodoEdit/issues/925
