### ISSUE TITLE
Komodo 11: CodeIntel fails for Python

### ISSUE THREAD

**Issue by davefultz** [Komodo/KomodoEdit#3384]
### Short Summary
Multiple attempts to reset the CodeIntel database have no effect: No Symbols Found.

### Steps to Reproduce

Help / Troubleshooting / Reset CodeIntel Database

### Expected results

Symbols

### Actual results

No symbols found

### Platform Information

*Komodo Edit or IDE?* 
IDE
*Komodo Version?* 
11.0.1
*Operating System (and version)?* 
Mac OS 10.12.6
### Additional Information
Python 2.7.6

Seeing this worked with a similar issue reported on the forum, I tried it. It had no effect:
<string id="console_history">["require(\"ko/prefs\").deletePref(\"codeintel.symbolbrowser.use_legacy.Python\")"]</string>

CodeIntel in Komodo 10 works just fine with this project.

Komodo 11 Settings:
![screen shot 2017-11-24 at 1 39 11 pm](https://user-images.githubusercontent.com/20732438/33222699-9ae62648-d11e-11e7-82a6-e8210275dc18.png)
![screen shot 2017-11-24 at 1 40 03 pm](https://user-images.githubusercontent.com/20732438/33222700-9af8de32-d11e-11e7-8475-0e7e4df4ac82.png)

 [2017-11-24 13:47:09,994] [DEBUG] codeintel/process: PYTHONPATH: /Applications/Komodo IDE 11.app/Contents/MacOS/../lib/python2.7;/Applications/Komodo IDE 11.app/Contents/SharedSupport/dbgp/pythonlib;/Applications/Komodo IDE 11.app/Contents/Resources/extensions/codeintel@activestate.com/content/../pylib/codeintel/lib;/Applications/Komodo IDE 11.app/Contents/Resources/extensions/codeintel@activestate.com/content/../pylib/codeintel/env/Lib/site-packages

**Comment by cgchoffman** [comment]
Could you describe the actual symptoms?  Code intel encompasses multiple features.  It sounds like you're saying the Symbol Browser isn't working?  

`Help / Troubleshooting / Reset CodeIntel Database`, these are not repro steps.  These are work around steps.  Please tell us what you're doing in Komodo, what you expect to see and what you're actually seeing.  

Also, if the project available for us to test on?  Python code intel is working for us on the entire Komodo IDE project.

**Comment by davefultz** [comment]
Carey,
If I reset the database, I watch the status and it reports complete.

The actual symptoms are no tips, no suggestions, no variable-complete, no symbol list. The attached image shows all I get.

if I reset the Komodo root to a directory with a couple files, quit and restart, codeIntel sees them. If I then set it back to my main project and reset, it sees bloody nothing.

Dave
![screen shot 2017-11-24 at 2 58 40 pm](https://user-images.githubusercontent.com/20732438/33224181-4e2a6004-d12c-11e7-9699-3661028dafb5.png)

**Comment by cgchoffman** [comment]
Thanks for clarifying.  Can you share your entire pystderr.log when Komodo says it's scanned and you try to get completions.  Also attach codeintel3.log would be helpful.  You'll need to rename them to have a `*.txt` extension.  On OSX you can find them in *~/Library/Application Support/KomodoIDE/11.0*.

**Comment by davefultz** [comment]
Logs attached. I've also included the file it seemed to stall on.

Dave
[r_en_JM.txt](https://github.com/Komodo/KomodoEdit/files/1502571/r_en_JM.txt)
[codeintel3.txt](https://github.com/Komodo/KomodoEdit/files/1502572/codeintel3.txt)
[pystderr.txt](https://github.com/Komodo/KomodoEdit/files/1502573/pystderr.txt)

**Comment by mitchell-as** [comment]
Thanks for providing the actual file that causes the problem. Our Python parser was not able to handle one of your UTF-8 characters.

Fixed via https://github.com/Komodo/codeintel/commit/f705651be13bdc1cb254cf58b2252bfc4219d072
