### ISSUE TITLE
Komodo 11.0.1 EDIT: CodeIntel fails for Python 

### ISSUE THREAD

**Issue by Zebrafish007** [Komodo/KomodoEdit#3386]
### Short Summary
As discussed under #3349 I have the same problem but with python files. CodeIntel is not frequently updated and therefore go-to-definition is outdated.

### Steps to Reproduce
No clue how to do that reproduction because it happens with all files. Make any script is just fine.

### Expected results
when the scripts are evolved go-to-definitions goes to the wrong place obviously.

### Actual results

Files from 6th of November are still not updated on November 27th.

### Platform Information

*Komodo Edit or IDE? 
*Komodo Version?* 
*Operating System (and version)?* 

Komodo Edit, version 10.2.3, build 17708, platform win32-x86. Built on Tue Jul 11 21:59:10 2017.
Komodo Edit, version 11.0.1, build 18119, platform win32-x86. Built on Fri Oct 27 23:54:50 2017.

Python 2.7.13/14

### Additional Information
Removal of symbol.db and deletion of all folders that contain "blob", etc.. under:
C:\Users\.......\AppData\Local\ActiveState\KomodoEdit\11.0\codeintel\db\python
helps Edit to reexamin the python files and thus update codeintel by recreating the db.

**Comment by mitchell-as** [comment]
Hi, it would really help us if you could create a simple file that causes the issue along with some detailed steps. Something like "Make any script is just fine" is far too vague. Thanks.

**Comment by Zebrafish007** [comment]
Hi Michell... this reporting is merely due to the fact I've posted supporting feedback on the issue reported under #3349. Nathan suggested to add this here as new issue because codeintel issue hits apparently also the EDIT version. The issue at hand affects all my py-files suggesting codeintel doesn't update at start EDIT or prior closing EDIT or after editing x bytes in py-scripts after warm-boot from sleep-modus (I leave EDIT running for about 12 consecutive days... (yes I read Nathans attempt fixing memmory-leaks). After approx. 12 days EDIT starts suddenly to spit furballs and hits slomo (4fps; mem jumps from 200mb to 800mb in use; not gradually increase indicating there is a small line in the code that duplicates some parts of mem). Then... only then I close EDIT and restart. Last pc shut-down and cold-reboot was... I guess three or four weeks ago... so approximately I had four cold EDIT starts... two for hitting the snail-pace... and two for a hack on the blob files as described above. Does this help? and btw.. that issue is also seen in the EDIT 10.2.3 version. I see peeps talking about it wasn't in 10.x So.... that may help to figure out where to search for the issue at hand?

**Comment by mitchell-as** [comment]
Hi @Zebrafish007, no this does not help. You appear to be talking about Komodo Edit getting slower over time, when this ticket is about codeintel. I visited issue #3349 that you linked to, but I did not find any code samples.

**Comment by Zebrafish007** [comment]
In addition, codeintel screening 4.000+ files py-files takes about 4-10 secs max. on my pc. Having it checked after two to five minutes (idle) time won't affect my coding at all. Or somewhere at a beginning of the startup sequence of EDIT itself? I'll survive those 4-10 secs for sure.

**Comment by Zebrafish007** [comment]
Snail-pace is not an issue here. Just a remark.

**Comment by Zebrafish007** [comment]
Some modifications in version 11.1 appear to have solved the raised issues... for now. If and once this happens again I will create a new ticket, link to this issue as this ticket was originally about codeintel. Thanks for the help thus far. Very much appreciated!
