### ISSUE TITLE
Symbol Browser could not load.  Don?€™t trust your input ..

### ISSUE THREAD

**Issue by DamianDoyle** [Komodo/KomodoEdit#3388]
### Short Summary
The Symbol Browser in IDE 11.0 fails when special (utf-8?) characters are used.
The error message is "Could not load due to an error, if the issue persists please file a bug".

### Steps to Reproduce

The Symbol Browser in IDE 11.0 fails when this line is inside a Perl file for example:

`# don?€™t trust your input!`

### Expected results
A code overview

### Actual results
Error message "Could not load due to an error, if the issue persists please file a bug"

### Platform Information

Komodo IDE 11.0 
Windows 10

### Additional Information
This problem does not exist in IDE 9.3

**Comment by mitchell-as** [comment]
Hi, please upgrade to Komodo IDE 11.0.1, which should have fixed this issue.
