### ISSUE TITLE
Komodo hangs when setting multi cursor in JS files and you have a selection

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3394]
### Steps to Reproduce

Open `snippetProperties.js`
highlight `gApplyButton` on line 41
hold ctrl and click right before `dialog` on line 44

### Expected results

Multi cursor set infront of `dialog`.

### Actual results

Komodo hangs.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoIDE/commit/872c744984415771de26f9b4efdaa7ba32c4ecb1
