### ISSUE TITLE
Completion inserts very weird in awkward cursor position

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3395]
### Short Summary

Thank goodness for gif capture:
![weird-completion-insert](https://user-images.githubusercontent.com/655154/33454557-14a06a8a-d5ce-11e7-8491-4728f3450788.GIF)

### Steps to Reproduce

See gif ^^

### Expected results

Completion to be inserted after the `.` in `elems.`.

### Actual results

`elems.` is consumed by the completion insertion.

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/8a9d0d84f36865b116773bcfaeb9768472c046a9
