### ISSUE TITLE
Komodo Edit 11 Shows up as Komodo Edit 10 on macOS

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#3396]
### Steps to Reproduce

 * Install Komodo Edit on macOS
 * Launch it through its launcher app by typing the name

### Expected results

 * Shows up as Komodo Edit 11

### Actual results

 * Shows up as Komodo Edit 10

**Comment by cgchoffman** [comment]
I can't reproduce this.  Where exactly does it show up as *Komodo Edit 10*?  I'm guess in Launcher?  I'm not seeing that.

**Comment by cgchoffman** [comment]
Gonna close this one.
