### ISSUE TITLE
First start wizard says "IDE" instead of "Edit" when using Komodo Edit

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#3397]
The title of the dialog for the first start wizard says IDE instead of Edit.

**Comment by Defman21** [comment]
#2574

**Comment by cgchoffman** [comment]
I don't know what's going on but I already fixed this: https://github.com/Komodo/KomodoEdit/commit/34444f55e1ab4b56e6dc410e8011489dcfe2aedc
Sorry @Defman21 , I must not have seen your pull request as I didn't use it.
https://github.com/Komodo/KomodoEdit/blob/master/src/chrome/komodo/content/startupWizard/startupWizard.xul#L19

Looking into why that didn't fix it.

**Comment by cgchoffman** [comment]
Can't repro:
![capture](https://user-images.githubusercontent.com/655154/33568916-d05d1cb2-d8dc-11e7-847c-0aded2ecb3a3.PNG)

**Comment by Naatan** [comment]
@cgchoffman seems that commit did not land on master. Might've just been on the versioned branch?

**Comment by Naatan** [comment]
Huh, not sure what I just did that showed me IDE.

**Comment by cgchoffman** [comment]
OSX is working fine as well.  I see "Komodo Edit - Let's Get Started"

**Comment by Naatan** [comment]
Strange. I guess I'll close this, not sure what happened to the user. Will follow up with him.
