### ISSUE TITLE
Komodo unusable after requesting file dialog with SFTP

### ISSUE THREAD

**Issue by vanoden** [Komodo/KomodoEdit#3402]
### Short Summary

When attempting to open or save a remote file over SFTP, the File Dialog box never appears and the application becomes unusable.  It seems as if the File Dialog has failed to appear and since it is modal, the application just plays the error sound when trying to access.  Close Window in the taskbar or other places does nothing.  The process must be killed from the task manager.

### Steps to Reproduce

File->Open->Remote File... from the menu.  It is intermittent, but seems related to slow responses from remote servers.  This happens most often, but is not limited to, when I am accessing a server over a VPN connection.  Usually have a number of other open files when this occurs.

### Expected results

File Dialog appears, or some error explaining why it can or did not.

### Actual results

No File Dialog appears.  Application is unresponsive as if waiting for a response from another window.  Must kill process and restart.

### Platform Information

*Komodo Edit or IDE?* Komodo Edit and IDE 
*Komodo Version?* version 11.0.1, build 18119, platform win32-x86 as well as others going back for years
*Operating System (and version)?* Windows 10 Home, Windows 8, Windows 7 running on a variety of hardware.  I've used this in Linux quite a bit, but cannot recall if the same problem happened.

### Additional Information

I don't have a log file as the restart cleared the old one out.  This happens 2-3 times per week so it's hard to reproduce but common enough to be painful.  Originally posted a comment to #1955 but it was suggested I enter a new bug.

**Comment by vanoden** [comment]
Just happened again.  I do see the Komodo icon in the taskbar flash a few times and then stop.  Interestingly, I can still scroll up/down the content in the editor, and using Alt-F I can get to and move through the menu's, but selecting an item does nothing.  That is, until I click the icon in the task window and select 'Close Window'.  Then it becomes completely unresponsive.

Looking at the pystderr.log file, there are some errors regarding getInterfaceStyleRaw, but these are from earlier in the afternoon.  There are no new entries in the couple of hours before it 'hung'.

**Comment by cgchoffman** [comment]
@vanoden, could you try this nightly and see if it helps?
http://downloads.activestate.com/Komodo/nightly/komodoide/latest-11.0.2/

**Comment by vanoden** [comment]
I have installed and will try to reproduce the issue.

Thank You

**Comment by cgchoffman** [comment]
Thanks @vanoden, standing by.  FYI, could you try replying to the ticket through Github rather than email?  When you reply through email it appends the entire contents of your email.  Besides the clutter, some times people share personal information in a very public manner when they do that.

**Comment by vanoden** [comment]
So far I have not been able to recreate the problem.  It has been intermittent in the past, but I've tried to recreate the steps as best I can and the dialog does eventually appear each time.  I'll keep testing a bit longer.

**Comment by cgchoffman** [comment]
I'm fairly certain we'll find this resolved.  I fixed a bug a few weeks ago (a month ago?) that was hiding modal dialogs behind the main Komodo window.  Hopefully your not able to reproduce the issue @vanoden.
