### ISSUE TITLE
Notification panel spans across the entire screen

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#3405]
### Short Summary
Notification panel spans across the entire screen

### Steps to Reproduce

1. Save the attached file as 'config.pm'
2. Click on the notification as shown in screenshot

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo IDE, version 11.0.2, build 90813, platform macosx.
Built on Mon Dec 4 09:43:06 2017.
### Additional Information
![image](https://user-images.githubusercontent.com/26605593/33903243-a1749ff0-df2c-11e7-9987-45275a5407dc.png)

[config.txt](https://github.com/Komodo/KomodoEdit/files/1552931/config.txt)

**Comment by cgchoffman** [comment]
I can't tell what that dialog is from the screenshot and the reproduction steps don't produce a dialog.  @mjainQA can you recall anything about this?  What is the dialog that was triggered?

**Comment by Naatan** [comment]
It's the syntax checking popup on the side toolbar. The long message is a linter message, basically we'll want to limit the length, or force it to reflow.

**Comment by cgchoffman** [comment]
Ok thanks.
