### ISSUE TITLE
Unable to turn off 'minimap'

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#3406]
### Short Summary

Minimap is always displayed. Toggling it off from View menu doesn't turn it off.

### Steps to Reproduce

1. Create a folder
2. create new file from template
3. Name it as ‘config.pm’ and copy paste the following code. https://raw.githubusercontent.com/foswiki/distro/Item14237/core/lib/Foswiki/Config.pm
4. Save it. 
5. Try toggling minimap feature on/off from View menu

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo IDE, version 11.0.2, build 90813, platform macosx.
Built on Mon Dec 4 09:43:06 2017.
### Additional Information
![image](https://user-images.githubusercontent.com/26605593/33903339-f1868102-df2c-11e7-93a4-0439d879c5b6.png)

**Comment by ssigwart** [comment]
A simpler way to reproduce is to just create a new file, then save it.  I'm getting there on figuring out how solve this.
