### ISSUE TITLE
Symbol browser sidebar is not being restored if Komodo restarts after crash

### ISSUE THREAD

**Issue by ANSI-C** [Komodo/KomodoEdit#3407]
### Short Summary

Restarted computer with Komodo opened, afater restarting it it complains about not being shut down properly, I select the "restore" option, then Komodo opens with sidebar hidden when I had it shown as selected setting.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 11.0.1
*Operating System (and version)?*  Windows 8.1

**Comment by mitchell-as** [comment]
Hi, this one is tough, because Komodo cannot save its state upon crashing. The question is, did you have the sidebar open when you originally started Komodo? If not, and if you opened the sidebar after starting Komodo, and Komodo crashed, it cannot restore the sidebar since its state was never "saved".

**Comment by ANSI-C** [comment]
Hello, the sidebar was opened and I had time to close properly and reopen Komodo with that setting.
Then after a crash, the sidebar is not restored. To be noted that yesterday I restarted the system with some applications opened, that were properly closed gracefully by Windows. At restart, only Komodo claimed that wasn't closed properly (there was any pending change to be saved on opened files). When I confirmed to restore files this time sidebar was restored properly as well.

**Comment by Naatan** [comment]
Restoring after a crash is gonna be error-prone no matter what you do. Komodo shut down uncleanly, there is no saying what it managed to save and what it didn't. Unfortunately this is not actionable for us.

**Comment by ANSI-C** [comment]
Just a note: Komodo was able to restore **everything** (opened files, settings, etc etc) except this, even after a crash.

**Comment by Naatan** [comment]
Fwiw we do have improvements to workspace restoring coming up. But the fact remains that when Komodo crashes the recovery isn't guaranteed to work. We can't recover from a crash, we can only try to recover to a point prior to the crash.
