### ISSUE TITLE
Anoying "4 Tab width" bug instead "8 Tab width" settings

### ISSUE THREAD

**Issue by Perlover** [Komodo/KomodoEdit#3408]
### Short Summary
Even if i have Global Preference as "8" for "Width of each Tab character" option, same in Project preferences and same for Perl-language files (last current version) the Komodo Edit 11.0.1 opens Perl files from project as "4 - Width of each Tab character". If i click by properties of opened file - i see there the "8" setting but i real see in Komodo as "4" setting. Only if i change by mannually the settings for each opened file (8 -> 7 -> Apply > 8 -> Apply button again back) i see normal mode after this.

### Steps to Reproduce

1) For example we should have a created project. May be we should change from default "4" to "8" Tab settings before.
2)To open any Perl file of project
3) To check real size of Tab width. I have "4" after.
4) In file properties of opened file i change "Width of each Tab character" settings (from 8 -> 7 for example -> Apply button -> 8 -> Apply button again back). After i see normal 8-width Tab symbol. If i close now this file and will reopen by "Ctrl+Shift+T" i see normal size (8). But if i open any new Perl file from project (not opened before) - i see again "4" Tab width setting (but in the file preference for opened file i saa there again "8" setting. After i should 4 point again for this file)

### Expected results
"8 - Width of each Tab character"

### Actual results
As "4 - Width of each Tab character"

### Platform Information

Komodo Edit 11.0.1
Linux Mint 18.2

**Comment by Perlover** [comment]
I unchecked the following option in global preferences and problem has gone out,
"Allow file contents to override Tab and Indentation settings"
But i don't understand how plain Perl file content can override Tab settings...
So i think this issue may be closed
Thanks!

**Comment by Defman21** [comment]
I guess that's the setting that autodetects the indentation based on the amount of spaces used for indenting lines in your code.
