### ISSUE TITLE
Komodo Edit 11.0.2 does not do Python syntax error highlighting

### ISSUE THREAD

**Issue by Bbeacham** [Komodo/KomodoEdit#3413]
### Short Summary
Previous versions of Komodo will have a red underline to indicate a Python 2/3 syntax error.  Komodo Edit 11.0.2 build 18122 built 12/04/17 does not do that.

### Steps to Reproduce
Create a simple Python program with a syntax error, and it will not be flagged as an error

![image](https://user-images.githubusercontent.com/34782094/34315484-0443d780-e735-11e7-8ae2-622e7363dbc9.png)

Example, Edit 11.0.2, no red line under 'def Main' since colon missing at end.
![image](https://user-images.githubusercontent.com/34782094/34315508-73e5e718-e735-11e7-9bbb-9b815f7308c5.png)

Example, Edit 7, red line is under 'def Main' since colon missing at end.
![image](https://user-images.githubusercontent.com/34782094/34315530-c074e4f8-e735-11e7-85db-ecb9eb6e8089.png)

*Operating System (and version)?* 

win32-x86

**Comment by Defman21** [comment]
Do you have a Python interpreter configured? (Preferences - Languages - Python/Python 3)

**Comment by Bbeacham** [comment]
Yes.  I spent all Friday afternoon trying every combination of configurations and color schemes I could find and think of.  I really don't see any configuration difference between the two versions of Komodo.

![image](https://user-images.githubusercontent.com/34782094/34322326-fbe9c352-e7d8-11e7-9a27-d3b759cff94a.png)

**Comment by Defman21** [comment]
You can expand this item, though with your color scheme the arrow seems to be invisible. Just double-click on the "Languages" item.
![image](https://user-images.githubusercontent.com/7100645/34322901-145a66be-e845-11e7-81cd-f6930213840a.png)

**Comment by Bbeacham** [comment]
Okay.  That fixes it.  Thank you.  Since I am just using Komodo as an editor, it didn't occur to me that the interpreter was needed for syntax checking.  

I use Komodo on my work laptop, while Python and the associated files being developed are on a Linux machine in the lab.  I get to them via a Samba share on the Linux machine.
