### ISSUE TITLE
Can't open certain files

### ISSUE THREAD

**Issue by kidip** [Komodo/KomodoEdit#342]
Since upgrading to Komodo 9, I can't open certain python files.  These files are for Django, and they were written in a previous version of Komodo.  If I open as a text file and then copy/paste into Komodo and resave they open fine. Only when I try to open them as Python files does Komodo complain.

[Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [koIDocumentSettingsManager.applyViewSettingsToDocument]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: vieweditor :: saveAsURI :: line 1658"  data: no]

Exception: [Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [koIDocumentSettingsManager.applyViewSettingsToDocument]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: vieweditor :: saveAsURI :: line 1658"  data: no]

Traceback:
saveAsURI@vieweditor:1658:12
saveAs@vieweditor:1601:19
viewManager.prototype.do_cmd_saveAs@chrome://komodo/content/views.js:1971:4
xtk.Controller.prototype.doCommand@chrome://xtk/content/controller.js:61:8
command_doCommand@chrome://komodo/content/library/commands.js:230:0
command_doCommandAsync/<@chrome://komodo/content/library/commands.js:187:12

Komodo IDE, version 9.1.0, build 87337.
Built on Fri May 29 20:57:45 2015.

**Comment by cgchoffman** [comment]
How exactly are you trying to open them?  You also seem to have cut the platform portion out of the Komodo version you're running.  Please provide that info.

**Comment by kidip** [comment]
I try to open them by just double clicking them in the viewer on the side or selecting File->Open.  Didn't realize I missed something I'm on OS X Yosemite 10.10.3.  Ugh, sorry I really failed at writing this, but this copy/paste is from making it a .txt file and then trying to 'Save As' back into a python file.

**Comment by Naatan** [comment]
Try deleting your doc-state.xmlc file in your profile folder (while Komodo is not running).

https://community.activestate.com/faq/komodo-profile-structure

**Comment by kidip** [comment]
That worked, thanks!
