### ISSUE TITLE
Update JS Linting to use ESLint which includes linting for JSX

### ISSUE THREAD

**Issue by rm-bergmann** [Komodo/KomodoEdit#3421]
### Short Summary
Currently in Komodo IDE the default linting for JSX files does not work well for me, and KomodoIDE expects the user to install and include a path to JSXHint.

JSXHint have deprecated it and recommended to use ESLint instead. Below is the quote from their github page:

https://github.com/STRML/JSXHint

"JSXHint is, and always was, a bad hack to make JSX lintable in the early days of React. It will always be inferior to proper linters like ESLint because it is not able to lint JSX or ES6 syntax, it instead compiles to ES5 then lints. You may get weird linter errors, especially with more involved transforms.

Don't use JSXHint anymore if you can switch to ESLint."

### Platform Information

Komodo Edit or IDE

**Comment by mitchell-as** [comment]
Thanks for the report!

**Comment by Defman21** [comment]
That depends on #2656
