### ISSUE TITLE
Edit matching delimeter on select allow backspace to be used

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3424]
### Short Summary
When you have the "Edit matching delimeter on select" setting enabled and you're editing a tag.
You can't press the <kbd>Backspace</kbd> button while editing.
When I have a `a` tag and want to transform it to a `span` tag, I tend to first want to remove the `a` first. 
And sometimes I make a small spelling mistake, but I'm unable to use the  <kbd>Backspace</kbd> button.

### Expected results
That you can use the <kbd>Backspace</kbd> key to edit the selected tags.

### Actual results
Using the <kbd>Backspace</kbd> button, cancel's the second selection.

### Platform Information

Komodo IDE, version 11.0.1, build 90797, platform win32-x86

**Comment by mitchell-as** [comment]
Thanks for the report.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoEdit/commit/a7156e80b641bacdbf49be5103b9cff7351ba137. I accidentally put in the wrong ticket number.
