### ISSUE TITLE
Code Outline doesn't properly support Perl private functions

### ISSUE THREAD

**Issue by oryandunn** [Komodo/KomodoEdit#3425]
### Short Summary
This is a regression bug that has shown up in version 11 of Komodo IDE.  Version 10 fixed my original bug report, which was #1084.
 
In Perl, if you have a private function of the form:
my $myPrivateFunc = sub { ... }
the code outline window lists $myPrivateFunc as a variable (which it is), but it has reverted to only showing it as a variable instead of both a variable and a function with children objects. I've attached a screenshot with an example of the correct behavior from Komodo IDE 10, and one from Komodo IDE 11 with the regression behavior.

Komodo IDE 10 Proper Perl Private Function Parsing:
![komodo 10 perl parse](https://user-images.githubusercontent.com/10134311/35016283-dc204e54-fae5-11e7-9054-a951166f7b68.png)

Komodo IDE 11 Incorrect Perl Private Function Parsing:
![komodo 11 perl parse issues](https://user-images.githubusercontent.com/10134311/35016302-f0110cc8-fae5-11e7-9e53-3e69c22f7bc5.png)

### Steps to Reproduce
Open a Perl file that has a private perl function.

### Expected results
Proper code outline parsing of private function as was done in Komodo IDE 10.

### Actual results
Perl private functions are not properly parsed for the code outline.

### Platform Information
Komodo IDE 11.0.1 on Windows 7 x64

**Comment by mitchell-as** [comment]
Thanks for the report.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/codeintel/commit/cf0ebc2fd1241dad45292a9acbcda0bbbb4e7c3a
