### ISSUE TITLE
Code outline tree is missing expand/collapse buttons on functions.

### ISSUE THREAD

**Issue by oryandunn** [Komodo/KomodoEdit#3426]
### Short Summary
In Komodo 10, the code outline had the expand/collapse tree buttons to expand/collapse functions.  These are missing in Komodo 11. 

![komodo 11 code outline missing collapse expand button](https://user-images.githubusercontent.com/10134311/35016594-511295d6-fae7-11e7-9dbe-b3d1e331dca9.png)

### Steps to Reproduce
Open Perl file that has functions and enable the "Show All Symbols" option in the code outline view.  Functions are not able to be collapsed.

### Expected results
Functions in the code outline should have a toggle to be able to collapse them without disabling the "Show All Symbols" option.

### Actual results
No expand/collapse buttons present and code outline view becomes difficult to use on a large file (where it was previously useful to navigate large files).

### Platform Information
Komodo IDE 11.0.1 on Windows 7 x64

**Comment by mitchell-as** [comment]
Thanks for the report.

**Comment by Naatan** [comment]
This is by design. You can hide the sub-symbols via the cog menu. The new symbol list is not intended do have collapse/expand functionality.

**Comment by oryandunn** [comment]
It's unfortunate you're **removing** this functionality.  It was there in version 10.  I found it quite useful, especially with very large files.  Now I have to toggle the whole view on/off, which resets the selection and jumps back to the top of the outline.  It really does make the whole view useless.  

Why not give users the option if they'd like to expand or collapse?

**Comment by Naatan** [comment]
Note there's an enhancement going into 11.1 that will make the symbol browser jump to the symbol (not just highlight) that you're currently at. I think this should address your use case.

**Comment by oryandunn** [comment]
While that would help, it's still not as useful as being able to expand/collapse each function.  For very large files, I would start with all functions collapsed, and expand only the ones relevant to what I was working on at the moment.  The code outline is very useful that way.  Unfortunately, we have some very large files, 5k-10k lines, so the outline completely expanded is huge and almost useless.

**Comment by Naatan** [comment]
With that many lines codeintel would likely become a bit slow regardless. It's not the ideal that we are targeting. 

The biggest reason why I'm hesitant about supporting this again is we are moving away from XUL trees, which would facilitate that mechanic. Our new implementation is based on lists, which don't currently supported expanding/collapsing children. So it would be substantially more work for a payoff that is somewhat debatable in terms of its value.
