### ISSUE TITLE
CSS3 auto-complete and syntax support

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#343]
Just a feature request :smiley:

**Comment by Naatan** [comment]
Can you elaborate? What specifically are you missing in terms of auto-complete and syntax support for CSS3?

**Comment by Defman21** [comment]
For example: `@keyframe`, auto-complete for `filter` property (such as `blur` or something another)

**Comment by Defman21** [comment]
Fixed a8377f170cc1a3b85370c3bde721f01077387e06
