### ISSUE TITLE
Symbol browser Display Scope not working for Perl since version 11

### ISSUE THREAD

**Issue by c2-atmanactive** [Komodo/KomodoEdit#3433]
### Short Summary

Since KomodoIDE v11, the Symbol Browser does not work for me to show the scope where my cursor is.
In KomodoIDE v10, the Symbol Browser (CODE pane) works both ways: 1.) I can double-click to jump to a subroutine, 2.) When I move through my source file, the Symbol Browser (CODE pane) tracks in which subroutine my cursor is and highlights it.
The first part works properly in KomodoIDE v11: I can click on the subroutine name and my cursor jumps there. But, the second part, where the sub in context should be highlighted, does not work at all.

I am coding Perl.

### Steps to Reproduce

1.) Install KomodoIDE v11.0.2
2.) Open a Perl module file
3.) Click on a subroutine name in the Symbol Browser (works fine)
4.) Move your cursor to some other subroutine - Symbol Browser highlights nothing.

### Expected results

Symbol Browser highlights the subroutine in which my cursor currently is. Just like in Komodo v10.

### Actual results

Symbol Browser highlights nothing. Looks stuck.

### Platform Information

*Komodo Edit or IDE?* 
IDE
*Komodo Version?* 
Komodo IDE, version 11.0.2, build 90813, platform win32-x86.
Built on Mon Dec 04 08:56:02 2017.
*Operating System (and version)?* 
Windows 7 SP1 x64

### Additional Information

![komodo_bug](https://user-images.githubusercontent.com/30599590/35222922-f34f3f88-ff7f-11e7-89d1-de35ad8d6d8e.png)

**Comment by mitchell-as** [comment]
Hi, thanks for the screenshot, but do you have a minimal code example that you can attach that demonstrates the problem? That would greatly aid in debugging this issue. Thank you.

**Comment by c2-atmanactive** [comment]
I am attaching the file as requested.

It bears repeating: this works perfectly in KomodoIDE v10.

[HTMLTexts_DB.pm.txt](https://github.com/Komodo/KomodoEdit/files/1653360/HTMLTexts_DB.pm.txt)

**Comment by mitchell-as** [comment]
Okay, thanks. I've confirmed the bug.

**Comment by casimirloeber** [comment]
I have come across this myself and it seems to only come into effect when the package declaration at the top of the file is more than 2 "levels" deep. What I mean by this is if you change line 1 from:

package C2::DB::MySQL::HTMLTexts_DB;

to

package C2::DB;

It works as expected. Not sure why, but this might help narrow it down

**Comment by mitchell-as** [comment]
Thank you, that helps!

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoIDE/commit/5da19ea10825a3fd56aaa809a9f9a131fbb7259d
