### ISSUE TITLE
Selected text to be indented by Tab size to right not indent size (unindent same)

### ISSUE THREAD

**Issue by Perlover** [Komodo/KomodoEdit#3436]
### Short Summary
"Decrease Indent" & "Increase Indent" (and keyboard shortcuts from "Preferences" -> "Key bindings" -> "Editor: Decrease Line Indentation" / "Editor: Increase Line Indentation" ) functions indent selected text at one Tab symbol not spaces of indent size

### Steps to Reproduce
1)
To set up "Preferences" -> "Editor" -> "Indantation" -> "Number of spaces per indent" -> "4"
To set up "Preferences" -> "Editor" -> "Indantation" -> "Width of each Tab character" -> "8"

2) Enter in editor some texts in some lines

3) To select some lines

4) To make indentation: through Menu button -> "Code" -> "Indent"

### Expected results
The selected text should be indented to right by 4 spaces (indent size)

### Actual results
The selected text will be indented to right by 8 spaces (Tab size) not by 4 spaces (indent size)
Same results with unindent (through Menu button -> "Code" -> "Unindent")

### Platform Information

*Komodo Edit or IDE?* 
Komodo Edit
*Komodo Version?* 
v11.0.2
*Operating System (and version)?* 
Linux Mint 18.3

**Comment by mitchell-as** [comment]
Hi, do you have "Edit > Preferences > Editor > Indentation > Allow file contents to override Tab and Indentation settings" checked? If so, uncheck it and try to indent/dedent again.

**Comment by Perlover** [comment]
No, i have unchecked this. I manuaaly uncheck it long time ago because i have other trouble - Tab space size to be overrided by editor but i want to have fix size...
So i see this bug with unchecked "Allow file contents to override Tab and Indentation settings"!

**Comment by mitchell-as** [comment]
Thanks for your response. I am not able to reproduce this. I used the following steps:

1. Create and save a new file "test.txt" with the contents
```
foo
bar
baz
```
2. "Edit > Current File Preferences > Editor > Indentation > Spaces/Tabs" set to 4 and 8, respectively, as indicated in your original post.
3. Select All.
4. Code > Indent. The contents are indented by 4 spaces, as expected.
5. Code > Indent. The contents are indented by another 4 spaces, as expected.
6. Code > Unindent. The contents are unindented by 4 spaces, as expected.
7. If I undo everything and start over, then check "Edit > Current File Preferences > Prefer Tab Characters over spaces", and then repeat steps 4-6, I get indentation by tabs that cover 8 spaces, as expected.

Now that I think about it, you might want to try Help > Troubleshooting > Reset File Preferences. Note however that this will reset any file-specific preferences you have set and revert them to global preferences.

**Comment by Perlover** [comment]
I did it (Help > Troubleshooting > Reset File Preferences)
But indent shifts to right by 8 spaces
After reset in settings i see 4 spaces for indent & 8 spaces for Tab
And "Allow file contents to override Tab and Indentation settings" is unchecked (i didn't change to after reset)

**Comment by Perlover** [comment]
But! If i uncheck option "Prefer Tab characters over spaces" in File Preferences the indent of selected text works as i hope!

**Comment by mitchell-as** [comment]
Yay! I'm glad you got it sorted out.

**Comment by Perlover** [comment]
Is it bug? I think yes. You closed ticket...

**Comment by mitchell-as** [comment]
When you have "Prefer Tab characters over spaces" checked, Komodo will indent by the equivalent of 8 spaces, which is what your tab settings state, no? When you uncheck that setting, Komodo indents by 4 spaces, which I assume "works as [you] hope!".

**Comment by Perlover** [comment]
Old Komodo Edit (8.x) worked other way

I think it's bug. I have in settings: 4 spaces for indent and i expect it anyway (regardless of Tab settings)

For example: it's common settings: 4 spaces for indent and 8 spaces to replace to Tab
If i have "Prefer Tab characters over spaces" it doesn't mean that i expect indent of selected text by 8 spaces! If you think that it's right behaviour so Komodo Edit works buggy buggy: not selected indent now it shifts to right by indend settings (4 spaces) but should indent by 8 spaces (if you admit that you are right)

I think it's bug and i ask to open ticket again. I don't see logic here...

**Comment by mitchell-as** [comment]
Are you saying that when you check "Prefer Tab characters over spaces", and when you select Code > Indent, Komodo indents by 8 spaces? (Not 1 tab that spans the equivalent of 8 spaces?)

**Comment by Perlover** [comment]
> Komodo indents by 8 spaces?
No, 1 Tab. But i have 8 spaces for one Tab! But indent i have 4 spaces! I expect indent by 4 spaces not one Tab which is 8 spaces!

But i have settings: 4 spaces for indent. I hope when i do indent of selected text it will be indented to 4 spaces to right. But i get 1 Tab, which is 8 spaces (positions)
I do not understand why you argue. I am programmer, i use Perl. There is standard: 4 positions for indent. And yes, i prefer that Komodo to change 4 spaces to one Tab (because a common practice to use 8 positions for Tab). But i don't understand why do you think it's right to indent to right by 8 positions if i have settings 4 spaces for indent.

I expect a following behaviour: Komodo Edit should shift a selected text to right by 4 positions (spaces) for one indent regardless Tab settings and after to change 8 spaces to one Tab. What is problem?

**Comment by mitchell-as** [comment]
Okay, I think I understand the confusion.

Komodo indents differently depending on whether or not you have "Prefer tab characters over spaces". If tabs are preferred, then Komodo will indent using tabs (NOT spaces), and the width of a tab is the 8 spaces you have set in your preferences. If tabs are NOT preferred, then Komodo will indent using the 4 spaces you have set in your preferences. It is NOT the case that Komodo should indent 4 spaces regardless of the prefer tabs setting. I sympathize with the confusion caused by the preference name, but the behavior you are experiencing is expected.
