### ISSUE TITLE
Snippet indentation is incorrect

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3437]
### Short Summary
**EDIT** update repro steps with enabled in snippet.
**EDIT** selection must be a "forward" selection, eg. `scimoz.anchor < scimoz.currentPos`

For some reason everyline after the first line in a multiline selection is getting indented as `current indent + current indent` instead of just it's current indent plus whatever the snippet adds.

![snippet-indent](https://user-images.githubusercontent.com/655154/35407433-ca0b709a-01c0-11e8-98fa-c4e63787bf75.GIF)

I must have broken this with the latest toolbox changes as this worked fine in 11.0.2

### Steps to Reproduce

- Create a snippet that has the *selection* interpolation:
```
[[%s]]
```
- Enable **Maintain indentation context after insertion** in snippet
- create a file with two lines of text that have atleast 1 space indentation.  Add more to make bug more obvious.
```
    blah
    blah
```
- Select from first line to end of second line, eg. `b` in first line (or start of line) to `h` on the second line.

### Expected results

No change

### Actual results

```
    blah
        blah
```

### Platform Information

*Komodo Edit or IDE?* 11.1 (master)

**Comment by Naatan** [comment]
Is your snippet using the "Maintain indentation context after insertion" setting?

**Comment by cgchoffman** [comment]
@naatan, yup.  Forgot to include that.

**Comment by Naatan** [comment]
That diff is unfortunately useless. What was the problem?

**Comment by cgchoffman** [comment]
Stuff being processed in the wrong order.  I just moved the indent calculations ahead of any content processing.
