### ISSUE TITLE
Release size

### ISSUE THREAD

**Issue by svnpenn** [Komodo/KomodoEdit#3438]
The release size is too large. For example, latest Notepad2-mod release is less
than 1 MB:

http://github.com/XhmikosR/notepad2-mod/releases

while latest Komodo Edit release is 74 MB:

http://activestate.com/komodo-ide/downloads/edit

**Comment by svnpenn** [comment]
https://github.com/adobe/brackets/issues/14071

**Comment by svnpenn** [comment]
https://github.com/atom/atom/issues/5012

**Comment by svnpenn** [comment]
https://github.com/visualfc/liteide/issues/891

**Comment by Naatan** [comment]
That's apples and oranges. Notepad2 is not equivalent to Komodo Edit. We are a much larger product.
