### ISSUE TITLE
Clicking on unselectable menu item changes its position on menu

### ISSUE THREAD

**Issue by ACueva** [Komodo/KomodoEdit#344]
Komodo IDE 9.1.0 build 87337m win32-x86

Steps to reproduce:

1. Open Menu
2. Click on an item that is not a selectable option.
3. Item will move menu location.

**Comment by Naatan** [comment]
Cannot reproduce, could you tell us specifically what menu item you're clicking?

**Comment by ACueva** [comment]
Original Menu:
![image](https://cloud.githubusercontent.com/assets/3093940/8242869/59c595d2-15c7-11e5-80b9-6c0b93480dae.png)

After I click on anything that is shaded:

![image](https://cloud.githubusercontent.com/assets/3093940/8242882/71147c44-15c7-11e5-8618-5fed505cd3ae.png)

![image](https://cloud.githubusercontent.com/assets/3093940/8242912/af4abad2-15c7-11e5-9b96-44ebbf034641.png)

**Comment by Naatan** [comment]
Those are the most recently used menu actions, its sorted by, well, what you used most recently.

**Comment by tonyattwood** [comment]
Hey,

This stuff is really crazy, you've got to see that  for sure!  Just  take a look here <http://extra.ambergaineymeade.com/e4nbbl>

All the best, tony.attwood@ntlworld.com
