### ISSUE TITLE
HTML5 Tidy adding you're own config file is overwriting default settings

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3440]
### Short Summary
If you're adding you're custom config file, for html tidy.
The default settings are overwritten.

### Steps to Reproduce
 * Create you're own config file
 * Add the missing SVG tags from this [post](https://community.komodoide.com/t/komodo-x-svg-tag-highlted-as-wrong/4136/2?u=babobski)
 * Setup html tidy to use this config file

### Expected results
The new added tags, would extend tidy's configuration.

### Actual results
Adding the config file is overwriting the default settings.
It is now recognizing the svg tags, but it does not recognize html5 element's(section, nav, footer, etc.) anymore.

**Comment by mitchell-as** [comment]
I think if you choose to supply your own config file, it should override Komodo's. I believe this is the case for all linters.

**Comment by babobski** [comment]
The only thing I have a issue with, is that you don't know which default settings are used.
If I take a look at the JSHint settings you can see which settings are applied:

![afbeelding](https://user-images.githubusercontent.com/3530262/35522507-d4f4ed92-051c-11e8-8cd7-ebaf3ea61908.png)

With html tidy, as user you don't have a idea which default settings are supplied.

**Comment by mitchell-as** [comment]
I agree with you and I sympathize. It is worth noting that our HTML-Tidy tool is horrendously old and outdated. As a result, we've had to hack up our config in order to support HTML5. We have a ticket (#1749) for updating our version of Tidy to support HTML5 out of the box, so at that point, the concerns of this ticket will no longer be founded.

**Comment by babobski** [comment]
oke, good to know 👍
