### ISSUE TITLE
Code browser not loading

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3448]
### Short Summary
I think this is related to my codeintell problem, noticed olaso the codebrowser is not loading.
When I wanted to take a look, I noticed all my tabs are missing:

![afbeelding](https://user-images.githubusercontent.com/3530262/35561717-8247b4a4-05b1-11e8-8d2c-f81e24a1a43a.png)

When I move a widget to the right sidebar, only the toolbox is loaded:

![afbeelding](https://user-images.githubusercontent.com/3530262/35562317-43e0ead0-05b3-11e8-8ac0-572a7ce0fc44.png)

### Expected results
Scrrenshot form 10.0.2

![afbeelding](https://user-images.githubusercontent.com/3530262/35561762-9db8eed8-05b1-11e8-821d-9f8ab2d1e87f.png)

### Platform Information
Komodo IDE, version 11.0.1, build 90797, platform win32-x86

**Comment by mitchell-as** [comment]
If codeintel is not working, then the code browser will not load. This is expected behavior. Issue #3442 needs to be resolved before we can address any further codeintel issues from you.
