### ISSUE TITLE
New file from template html5 does not select html5 as language

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3456]
### Short Summary
When you create a new HTML5 template with the "new file from template" it is not setting the language correct:

![afbeelding](https://user-images.githubusercontent.com/3530262/35620959-16601894-0683-11e8-8e2e-2f7f108fc205.png)

Also the template is not really a template anymore as it is missing the HTML5 markup:
```html
<!DOCTYPE html>

<html>
<head>
    <title>Page Title</title>
</head>

<body>



</body>
</html>
```

I guess the language is determinant by the doctype in the file,because it is missing it falls back to html.

### Platform Information
Komodo IDE, version 11.0.2, build 90813, platform win32-x86

**Comment by mitchell-as** [comment]
Thanks for the report.

**Comment by cgchoffman** [comment]
> Also the template is not really a template anymore as it is missing the HTML5 markup:

The only required markup is the doctype tag at the top.  Everything else is up to the user.

**Comment by babobski** [comment]
But then it's not really a template any more, if I want to create a new html 5 template the least what I would need is:

```html
<!DOCTYPE html>

<html>
<head>
    <title>Page Title</title>
</head>

<body>



</body>
</html>

```
Also when I [check](https://validator.w3.org/nu/#textarea) the document with only a doctype I'm getting a error that the head and title are required:

![afbeelding](https://user-images.githubusercontent.com/3530262/35644295-d99a4bc8-06c8-11e8-9dd7-3680fc5e2466.png)

**Comment by cgchoffman** [comment]
haha is that for real?  huh, alright. I guess we have to add a `<title>` tag :S.

**Comment by babobski** [comment]
Note the wrong language can easily be fixed, the wrong language is selected in the template:

![afbeelding](https://user-images.githubusercontent.com/3530262/35849074-ad2ad45c-0b20-11e8-997b-2e78ad4016df.png)
