### ISSUE TITLE
Less variable auto completion broken in K11

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3458]
### Short Summary
The less variables auto completion is not working in K11.

![afbeelding](https://user-images.githubusercontent.com/3530262/35627778-41f1c554-069a-11e8-8a6b-dfca7adeb144.png)

### Platform Information
Komodo IDE, version 11.0.2, build 90813, platform win32-x86

**Comment by mitchell-as** [comment]
Thanks for the report.

Note to self: the unit tests for this pass, so CodeIntel's language router is probably not handling word characters properly.

**Comment by mitchell-as** [comment]
I have no idea why this is happening. I've turned on logging to the max and for the simple file:

```
@nice-blue: #5B83AD;
@light-blue: @<|>
```

the codeintel.log file tells me it is returning two variables as potential completions. I'm not seeing them in the popup though.

@Naatan any idea?

**Comment by Naatan** [comment]
@mitchell-as it's probably being filtered out by one of the conditionals in completions.js starting at line 188 (in renderEntries).

**Comment by mitchell-as** [comment]
Thanks. Now I feel dumb.

Fixed via https://github.com/Komodo/KomodoIDE/commit/cb56086e50d31783c53c09f709d93f5755ad4ed7
