### ISSUE TITLE
Closing a project removes it from the project list

### ISSUE THREAD

**Issue by concussiongfx** [Komodo/KomodoEdit#3462]
### Short Summary
After closing a project, it is no longer listed in the project window.

### Steps to Reproduce
- Import or create a new project.
- Close project

### Expected results
Project remains in the project window

### Actual results
Project no longer listed and need to be reopened via the file requester

### Platform Information

Komodo IDE
11.0.2
macOS 10.13.3

**Comment by mitchell-as** [comment]
Hmm, I am not able to reproduce this. Does the issue still occur for you in Safe Mode? (Help > Troubleshooting > Restart in Safe Mode)

**Comment by concussiongfx** [comment]
It does not occur in safe mode.

**Comment by mitchell-as** [comment]
Okay, then typically an add-on is to blame for problems that occur outside of Safe Mode. You can try Help > Troubleshooting > Restart Without Addons. If the problem does not occur after that, then you'll have to figure out which of your add-ons is to blame. One thing that may aid in your search is by investigating Help > Troubleshooting > View Log File. Feel free to post the contents of this file after triggering the issue outside of Safe Mode if you'd like assistance.

**Comment by concussiongfx** [comment]
After some debugging, it turns out that this is from the "Allow multiple open projects" option.. Turning this off fixes the issue :) Not sure if this is expected behavior or not.

**Comment by Naatan** [comment]
I thought we removed that option. Where did you toggle it?

**Comment by concussiongfx** [comment]
Under "Places"
<img width="431" alt="screen shot 2018-02-12 at 12 27 12 pm" src="https://user-images.githubusercontent.com/16595730/36110313-23fe436a-0ff0-11e8-8ac5-72d9f285c17b.png">

**Comment by Naatan** [comment]
Thanks @concussiongfx , I filed a bug for this here - https://github.com/Komodo/KomodoEdit/issues/3471
