### ISSUE TITLE
Folds on Komodo 11

### ISSUE THREAD

**Issue by tunedin76** [Komodo/KomodoEdit#3463]
Version is Komodo IDE 11 on Windows 10
Issue is the folds for the functions and loops have disappeared.
They were up about a week ago, so I lean toward user error on myt part, however the section in preferences  under editor->smart editing under folds, all are active.

Am I missing something?

**Comment by mitchell-as** [comment]
Hi, do you get your folds back when you restart in Safe Mode? (Help > Troubleshooting > Restart in Safe Mode)

**Comment by tunedin76** [comment]
No the do not

**Comment by mitchell-as** [comment]
Okay, some color schemes make it really hard to see the fold lines immediately to the left of code and to the right of the line number margin. Double-check that they're not actually there. You can also try clicking in the whitespace immediately to the right of the line number margin on a line you know should be a fold point.

**Comment by mitchell-as** [comment]
It may also help for you to post screenshots of your fold settings and the code whose fold points are not being identified properly.

**Comment by tunedin76** [comment]
I guess it was the color scheme, they are there. I changed the foreground of the fold icon in the scheme editor. Thank you for your help

**Comment by mitchell-as** [comment]
You're welcome. I'm glad you got it working!
