### ISSUE TITLE
Support for async/await syntax for JavaScript/ECMAScript/Node

### ISSUE THREAD

**Issue by bbusschots-mu** [Komodo/KomodoEdit#3468]
### Short Summary

When writing JavaScript with the language set to either Node or JavaScript, the async/await syntax is not understood by Komodo Edit, and marked as an un-recoverable syntax error. Neither the `async` nor `await` keywords are understood.

The current LTS version of Node supports both of these keywords, as do all mainstream browsers other than IE ([according to MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function)).

### Steps to Reproduce

The following simple code snippet with the language set to either JavaScript or Node shows that neither the `async` nor `await` keywords are understood:

```
async function async1(){ return true; }
async function async2(){ await async1(); }
```

### Expected results

Should show as valid syntax.

### Actual results

Shows as a syntax error.

### Platform Information

* Komodo Edit
* Version 11.0.2
* macOS High Sierra 10.13.3

### Additional Information

![screen shot 2018-02-09 at 13 03 09](https://user-images.githubusercontent.com/4949446/36029095-ab0fb6a8-0d99-11e8-9f94-409d1706c6d6.png)

**Comment by Naatan** [comment]
This will be addressed by the introduction of ESLint support, which is targeted for Komodo 11.1

**Comment by StefRe** [comment]
Version 11.1 still fails to support async/await syntax. 
(Komodo Edit, version 11.1.0, build 18196, platform linux-x86_64. Built on Wed May 23 00:03:30 2018.)
