### ISSUE TITLE
Komodo 9 scrollbars

### ISSUE THREAD

**Issue by PhilSDP** [Komodo/KomodoEdit#347]
Is there a way to get back both the visibility and functionality of the standard windows vertical scrollbar?  In Komodo 9 it is almost invisible even when the mouse is over it, and there is no top and bottom thumb to scroll a line at a time, very awkward when trying to compare code in tabs.

**Comment by cgchoffman** [comment]
This would have been better asked in the http://forum.komodoide.com/
Preferences > Appearance: Skin Editor Scrollbars

**Comment by PhilSDP** [comment]
Sorry to be such a bother :(

**Comment by cgchoffman** [comment]
heh, sorry to sound like a jerk.  We do prefer that people ask for assistance in the forums first though.

**Comment by PhilSDP** [comment]
This is one of the things I have long complained about with Komodo, new features get defaulted "ON" so existing users have to figure out where this new feature can be manipulated.

**Comment by cgchoffman** [comment]
I would discuss this with you in a forum post or email but we do have our reasons.
