### ISSUE TITLE
Packages section on the website does not get updated.

### ISSUE THREAD

**Issue by k-barton** [Komodo/KomodoEdit#3480]
Package infos in the Komodo IDE Community "Packages" section seems to have been frozen for a while.
(not sure where is the right place to report it)

**Comment by Naatan** [comment]
Thanks for noticing, I've restarted the service and it should be updated again soon.

**Comment by k-barton** [comment]
This seems to be a recurring problem. The package info and links have not been updated for three months or so. It affects the installation of packages from within Komodo as well.

**Comment by mitchell-as** [comment]
@Naatan is there an action item for this?
