### ISSUE TITLE
Publishing: Force Pull All does Force Push instead

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#3484]
### Short Summary

title

### Steps to Reproduce

1. Setup a publishing thing.
2. Do some local modifications.
3. Force Pull all.

### Expected results

Remote files being pulled.

### Actual results

Local files being pushed.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 11.0.2
*Operating System (and version)?* Windows 10

**Comment by cgchoffman** [comment]
Thanks @Defman21, this was resolve by fixing a different ticket.
https://github.com/Komodo/KomodoEdit/issues/3016
