### ISSUE TITLE
Toolbox opens twice

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#3487]
### Short Summary

Running Komodo from the master branch gives me two toolboxes in my right panel, one is populated, the other is empty.

### Steps to Reproduce

Open Komodo

### Expected results

One toolbox

### Actual results

Two toolboxes

### Additional Information

Restarting in safe-mode makes no difference.

**Comment by cgchoffman** [comment]
I could have sworn I already filed this but I can't find it.

**Comment by Naatan** [comment]
Yeah it did sound familiar to me.

**Comment by cgchoffman** [comment]
I'm fairly certain i fixed this with this patch: https://github.com/Komodo/KomodoIDE/commit/f4ffea62204d4ac973eae3ee10926e109a930ead#diff-2dc02d4c55de7ab37347893dced64acb

@Naatan and I can no longer reproduce this issue.
