### ISSUE TITLE
Closing "Floating" tutorial doesn't actually end the tutorial

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3495]
### Steps to Reproduce

Requires that you're using a build with the fix for #3494.

- Create a new tutorial
- set the `Placement` field to `floating`
- click **ok** to save and close
- double click the new tutorial to start it
- immediately click the `x` in the top right of the window to close it
- start the tutorial again

### Expected results

- The tutorial to start normally

### Actual results

- you get a warning that a tutorial is already running and are asked if you want to close that running tutorial.

No errors

**Comment by Naatan** [comment]
#3494 doesn't have a fix?

**Comment by cgchoffman** [comment]
It does.

**Comment by Naatan** [comment]
Sneaky

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/eb694dd2cfe7925565bb84d11e95e3963f1cd29d
