### ISSUE TITLE
install in custom directory failed

### ISSUE THREAD

**Issue by bealdav** [Komodo/KomodoEdit#35]
Komodo IDE, version 9.0.0-rc1, build 87122, platform linux-x86_64.
Built on Thu Mar 12 01:38:38 2015.

How to reproduce fail:
Install in a custom path.
Nothing happens et process end shortly 

As opposite default config install in ~/Komodo-IDE-9, works nicely
Really good job of the komodo team. Thanks a lot: really nice new feature and now autocompletion really works

**Comment by toddw-as** [comment]
What's your OS - as it works correctly for me?

Please run "./install.sh -v" to get more log output.

**Comment by bealdav** [comment]
my os is linux.
You're right it's works now, sorry for the false positive. Thanks
