### ISSUE TITLE
Some little issues in Publishing Synchronization

### ISSUE THREAD

**Issue by stramin** [Komodo/KomodoEdit#3503]
I notices some GUI details to fix in Komodo IDE v.11 while publishing

the "Refresh tooltip", it says "Delete this current synchronization configuration"
![image](https://user-images.githubusercontent.com/17409281/37292297-65ffe024-25ef-11e8-9086-5040c0a4c617.png)
It should say "Refresh synchronization" or something

Publishing tool works pretty well, but these details could confuse an user (like I was the first time).

Greetings.

**Comment by cgchoffman** [comment]
Hey @stramin, thanks a lot for reporting these but these need to be three different tickets, please.

**Comment by cgchoffman** [comment]
Having three reports in one ticket is the best way to have a bug get closed by accident when one of the other issues is closed.  I hope you understand the need.

**Comment by stramin** [comment]
ok, splitting them now

**Comment by cgchoffman** [comment]
Perfect, thanks a lot.

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/23f9931c7beefb1524d7b2e4b6def76b4f0ddbc7
