### ISSUE TITLE
Some little issues in Publishing Synchronization 2

### ISSUE THREAD

**Issue by stramin** [Komodo/KomodoEdit#3504]
on the "Force Push All" button, where the dialogue prompt window is clipped at the right side:
![image](https://user-images.githubusercontent.com/17409281/37308336-87165856-261c-11e8-883c-a305dc8e973b.png)
(Same for "Force Pull All")

**Comment by cgchoffman** [comment]
Thank you very much @stramin.

**Comment by cgchoffman** [comment]
Ahh looks like I've already fixed this in master.  It'll be in 11.1 and any pre-release nightlies/betas that come out.

**Comment by cgchoffman** [comment]
Huh, i just hit this...I don't know why I didn't see it before.

**Comment by cgchoffman** [comment]
Oh no, I had fixed THIS issue but I just found the same bug in the Places Force Action menu item.

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/ad1fd9c20f97eb98b3df03ae3d04a81b4fe3d4ab
