### ISSUE TITLE
CSS CodeIntel completions still triggering on semicolon

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#3506]
### Short Summary

CodeIntel completions trigger on semicolon

### Steps to Reproduce

Write some css ending with a semicolon

### Expected results

No completions

### Actual results

Completions

### Additional Information

https://community.komodoide.com/t/ide-11-0-1-how-can-i-deactivate-css-code-intelligence-on-semicolon/4070/7

I believe the semicolon was added to the trigger blacklist, be sure to verify that.

**Comment by cgchoffman** [comment]
https://github.com/Komodo/codeintel/commit/964cf4ac09faf6fb6130707a66ec68674367dd5e
