### ISSUE TITLE
CSS file template has no file extension

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3507]
### Short Summary

It just gets "NONE" appended to the filename

### Steps to Reproduce

Ctrl+shift+N > Select CSS

### Expected results

**CSS-1.css** file name

### Actual results

**CSS-1NONE**

**Comment by Naatan** [comment]
Guessing this isn't CSS specific. Please be sure to check where that NONE is coming from, that should just be empty (files without extensions are a thing after all).

**Comment by Naatan** [comment]
@cgchoffman did you see my comment above?

**Comment by cgchoffman** [comment]
I don't know what to do with that comment.  There was a bug in the code.  It doesn't support not having an extension as far as I can tell so I added it.

**Comment by Naatan** [comment]
What I meant was your fix only works around the issue. Far as I can tell languages could still be lacking an extension, and this would still cause problems. So the bug isnt fixed. I think you need a `defaultExtension || ""` somewhere.

**Comment by cgchoffman** [comment]
Ok sure.

**Comment by cgchoffman** [comment]
Confirmed
