### ISSUE TITLE
Dialogs are blank and take several seconds to load

### ISSUE THREAD

**Issue by jsooter** [Komodo/KomodoEdit#3508]
### Short Summary
DIalogs /Modals are blank and take several seconds to load. 

### Steps to Reproduce
Anything that creates a popup dialog. For example: opening a project triggers a dialog asking "Would you like to open files you last had open in this project?"

### Expected results
See the message

### Actual results
Blank dialog box

### Platform Information

Komodo Edit
Version 11.0.2
Mac OS High Sierra 10.13.3 

### Additional Information

<img width="790" alt="screen shot 2018-03-14 at 10 03 35 am" src="https://user-images.githubusercontent.com/17498322/37414846-b2fb7cae-276f-11e8-9894-1678cba6afc4.png">

**Comment by cgchoffman** [comment]
Also please share your logs when you reproduce the problem.

**Comment by jsooter** [comment]
It happened a few times in safe mode but after I restarted it didn't happen again until I started editing files.
[pystderr.log](https://github.com/Komodo/KomodoEdit/files/1812752/pystderr.log)

**Comment by Naatan** [comment]
Is this the same as https://github.com/Komodo/KomodoEdit/issues/3475 ? @jsooter does mousing over the window reveal its contents?

**Comment by jsooter** [comment]
Mousing over it does nothing but arrow keys if there is an input field and it has focus will reveal the contents.

**Comment by pemcg** [comment]
I'm seeing the same thing. I've tried several colour schemes both light and dark, but each time the popup is just empty white.

**Comment by cgchoffman** [comment]
I'm going to close this in favour of #3475.  I think they are sufficiently similar (if not the same) that whatever fix we come up with will resolve both.

**Comment by GrahamStuart** [comment]
@jsooter You're on High Sierra, so try deselecting your Preferences | Appearance | Use native window borders. That change makes a big difference to this issue on High Sierra.

**Comment by cgchoffman** [comment]
@GrahamStuart This tickets closed now so you might as well comment on #3475.  I copied your tip to the other ticket.
