### ISSUE TITLE
Komodo IDE 11.02, sluggish / freezing under (Ubuntu) Linux

### ISSUE THREAD

**Issue by joho1968** [Komodo/KomodoEdit#3512]
### Short Summary

Even with just a few files open, KIDE becomes sluggish, slow, and sometimes unresponsive. I'm not really doing anything in particular to cause this, so I can't give a way to reproduce it. I open a project, KIDE restores some tabs/buffers, I start editing away, and then all of a sudden it gets sluggish.

The machine is a Core i7 with 16GB of RAM. KIDE often sits at 6-10% CPU, even when idle. Sometimes it peaks at 20-25% CPU.

### Steps to Reproduce

See above. I don't know if "running time" is a factor, or if it's related to the number of files on the remote server. But it happens all the time. If I close the application and re-open it, it behaves, for a while, and then it's back to its sluggish self.

### Expected results

With this machine configuration, I would expect zero sluggishness.

### Actual results

Way too sluggish.

### Platform Information

Komodo IDE, version 11.0.2, build 90813, platform linux-x86_64.
Built on Mon Dec 4 10:20:45 2017.
(Ubuntu 16.04.4.LTS)

### Additional Information

Using glances, I see KIDE has a 1.9 GB VIRT footprint and 400M RES footprint. I've tried to reset the cache(s) to no avail. Doing manual "Free memory" operations, I get it down sometimes to a 1.4 GB VIRT footprint.

I edit files via SSH most of the time.
I have attached a memory-report.

[memory-report.json.gz](https://github.com/Komodo/KomodoEdit/files/1824246/memory-report.json.gz)

**Comment by Naatan** [comment]
Running time is definitely a factor, Komodo is known to become slower after a day or two of running. I tend to restart it once a day. This isn't a one silver bullet type of problem and we work on various solutions every release. With Komodo 11 it has gotten noticeably better, but given enough time it is still a problem.

I'm closing this as there is nothing to track, the solution for this is to continue doing what we're doing; add performance improvements each release.

**Comment by cgchoffman** [comment]
@joho1968, you could try turning off *Prefs > Editor: Detect when networked files are changed...*.

**Comment by joho1968** [comment]
@Naatan The problem is that KIDE becomes pretty much useless when this happens, and I can't keep on re-starting the application several times per day.

@cgchoffman I could do that, if that helps. It opens up (possibly) another can of worms, but if it saves the agony of slow typing and/or several re-starts per day, perhaps it's worth it.

I typically have less than 20 files open in KIDE ... but I'm guessing it does a lot of file scanning of the remote server. If it does, and I generally enter at /, perhaps this is an issue? Perhaps an option to only scan the directories of where the open files are may be an idea.

**Comment by cgchoffman** [comment]
> but I'm guessing it does a lot of file scanning of the remote server.

Komodo does not scan remote folders.

**Comment by joho1968** [comment]
@cgchoffman Well, in that case disabling that setting seems to be a moot point, but I'll give it a shot.

**Comment by cgchoffman** [comment]
@joho1968, why would it be moot?  Komodo doesn't need to scan every file in your directory to see if the currently open files have changed.

**Comment by joho1968** [comment]
@cgchoffman Sorry, I must have gotten it wrong. I use KIDE to edit files over SSH 99% of the time. So I interpreted your "Komodo does not scan remote folders" as if this setting would have no impact for me. Also, using the "Refresh status" manually won't even trigger a detection, so it seems like once you disable it, it's off - period :)
