### ISSUE TITLE
Auto-completions CSS

### ISSUE THREAD

**Issue by tunedin76** [Komodo/KomodoEdit#3516]
In CSS
anytime a semi-colon is entered, -moz- autocompletin is immediate.... so EVERY line of CSS I have to hit:
semi-colon, ESC, then enter - or else I have to delete the autocompletion.
![capture](https://user-images.githubusercontent.com/16789318/37714168-3e4d23e6-2cef-11e8-9f8b-4c2a2c89e91d.PNG)
![capture](https://user-images.githubusercontent.com/16789318/37714173-425dd0de-2cef-11e8-8946-ab0fc2f888f8.PNG)

**Comment by Naatan** [comment]
Thanks for the report, we are tracking this here - https://github.com/Komodo/KomodoEdit/issues/3506
