### ISSUE TITLE
Golang gives completions after `;`

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3517]
### Short Summary

 typing `foobar := 123;|` immediately triggers completions after `;`, preventing me from going to a new line.

**Comment by mitchell-as** [comment]
This issue was also mentioned in #3445 in addition to the main problem. If you plan on working this ticket, please look into prioritizing #3445.

**Comment by cgchoffman** [comment]
I forgot to link.  Thanks for the reminder @mitchell-as

**Comment by Naatan** [comment]
I think we can probably add `;` to the global completion blacklist. Can't think of a scenario where you'd want completions after that.
