### ISSUE TITLE
BUG - Editing window jumps to top of file when buffer pasted from (CTRL+V)

### ISSUE THREAD

**Issue by shinyion** [Komodo/KomodoEdit#3519]
### Short Summary
After a period of time pasting from the buffer (CTRL+C then CTRL+V) causes the window to jump upwards to the top of file. Also cannot hide minimap at this time.

### Platform Information
Komodo Edit

**Comment by cgchoffman** [comment]
> Also cannot hide minimap at this time.

Please file a separate ticket for this.

Please see the template information in the bug report template and provide the request information.  This ticket is not actionable.

**Comment by shinyion** [comment]
I cannot reproduce the bug as it just happens. I am going to close this ticket as it takes less time for me to restart the application than to do the work to help you solve the problem
