### ISSUE TITLE
white sections appear in minimap

### ISSUE THREAD

**Issue by juzzyo** [Komodo/KomodoEdit#352]
This appears to happen irrespective of color scheme. Also appears on light color schemes. Screenshots attached.

Dark color scheme
![image](https://cloud.githubusercontent.com/assets/4934601/8220816/9c5cd7ac-159a-11e5-8590-05b12893eb8f.png)

Light
![image](https://cloud.githubusercontent.com/assets/4934601/8220841/faf91f3c-159a-11e5-8a92-ca9d749616b8.png)

Komodo IDE, version 9.1.0, build 87337, platform macosx. Built on Fri May 29 20:57:45 2015

**Comment by juzzyo** [comment]
The lines with a white background change when scrolling up and down. i.e. lines that have white backgrounds are not always a consistent color.

**Comment by cgchoffman** [comment]
Can you try and provide more details that could help us reproduce this?
The following might help:
- file type
- sample file that produces the issue for you
- any workaround you've discovered?
- Does it always occur or just it appear after a certain time period of use?
  - if yes to the above, any steps that you follow to reproduce

**Comment by cyril2** [comment]
This is such an useful feature! I'm trying to bring that back after upgrading to 9.3.2.... Was this a bug??

**Comment by Naatan** [comment]
I'm not sure what you're asking. This feature is still present in Komodo 9.3.2.

**Comment by cyril2** [comment]
Thanks for your answer. Sorry I wasn't very clear, I updated to 9.3.2
recently but I lost the white sections on the minimap.

They are not showing anymore even though I have the track change setting
enabled.
I tried to change the color in the preference ( 'Collaboration - local
change highlight' ) but that didn't do it.

**Comment by Naatan** [comment]
Ahh, I'm still confused though, they were a bug not a feature. What use did they have for you?

**Comment by cyril2** [comment]
Haha that's funny. For example, in a big file, I could easily see what
changes I made and didn't commit without having to make bookmarks.
Something a bit more obvious than the little margin log near line numbers.
Like you could scroll like crazy and stop whenever you see white stuff on
the minimap.

**Comment by Naatan** [comment]
Ok so you were using graphical glitches as a point of reference :P I'd suggest you make an enhancement request to perhaps get bookmarks to show in the minimap.

**Comment by cgchoffman** [comment]
#1156 & #1157.  Done and doner.  I've been meaning to file those requests for a while.
