### ISSUE TITLE
Ruby interactive shell will not load

### ISSUE THREAD

**Issue by dannyc1943** [Komodo/KomodoEdit#3526]
### Short Summary
when ever I try to start ruby interactive shell it produces a loop in the debug output at line 554 of rdbgp2.rb.  I cannot figure out what is causing this problem

### Platform Information
Ruby 2.5.0.  ruby and Komodo both installed on my "D" drive

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10
*Operating System (and version)?* Windows 7 x64

### Additional Information
Ruby Gem Byebug 10.0.2 installed

**Comment by Defman21** [comment]
https://github.com/Komodo/KomodoEdit/issues/3474#issuecomment-365963742

**Comment by mitchell-as** [comment]
Thanks for linking @Defman21 . Sorry @dannyc1943.
