### ISSUE TITLE
not smooth with the scroll operation with MAC

### ISSUE THREAD

**Issue by luckyfish0826** [Komodo/KomodoEdit#3528]
### Short Summary
when scroll with mouse or touchpad, the main view is not responding smoothly in MAC. 

### Steps to Reproduce
open a plain text file, then just use mouse or touchpad to scroll main view

### Expected results
smoothly scroll as all the app in mac.

### Actual results
a little bit slow behind.

### Platform Information

*Komodo Edit* 
*Komodo Edit 11* 
MacOS HS 10.13.1
MacbookPro 2017

### Additional Information
N /A .

Thank you for your great effort !

**Comment by Naatan** [comment]
Thanks for the report! This sounds like https://github.com/Komodo/KomodoEdit/issues/2064
