### ISSUE TITLE
Code Intel Crashes repeatedly then finally dies permanently

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3529]
### Short Summary

I have no reproduction steps other than it was running over night and it started having issues when I was nowhere near my computer so it shouldn't have been doing anything.

I just have lots of logs.

[codeintel3.txt](https://github.com/Komodo/KomodoEdit/files/1881188/codeintel3.txt)
[pystderr.txt](https://github.com/Komodo/KomodoEdit/files/1881190/pystderr.txt)

**Comment by Naatan** [comment]
This definitely needs to be looked at for 11.1.

**Comment by Naatan** [comment]
Note this may not be related, but there's a bunch of these:

```service: Getting completions for C:```

It's getting completions for the C: drive? :s

**Comment by cgchoffman** [comment]
This happened again last night.  Should I include more logs here before I restart?
@Naatan @mitchell-as

**Comment by mitchell-as** [comment]
@cgchoffman More logs probably do not hurt.

**Comment by mitchell-as** [comment]
After spending some time on this issue, I found db queries were taking too long, causing codeintel to timeout, and forcing a kill and restart. Fortunately, Codeintel is not "crashing". As I was composing this message, https://github.com/Komodo/KomodoEdit/issues/3536 was created, so I'm going to close this ticket in favor of that one, as it will solve this issue.
