### ISSUE TITLE
Sinkronisasi berkas bermasalah

### ISSUE THREAD

**Issue by yosacyber** [Komodo/KomodoEdit#353]
![capture](https://cloud.githubusercontent.com/assets/3403508/8230472/c26e7ac2-15ea-11e5-8546-568687d82d6a.PNG)
![untitled](https://cloud.githubusercontent.com/assets/3403508/8230473/c2b2f620-15ea-11e5-9242-8c4dac8545a5.png)

Seharusnya untuk fasilitas sinkronisasi, mohon sediakan fasilitas untuk force upload atau force download dimana tidak semua berkas tersinkronisasi dengan baik dan benar. contoh nya ketika saya melakukan perubahan pada berkas yang ada pada local server tetapi sinkronisasi tetap menampilkan data yang ada pada server remote ke server local. hal ini dapat merusak kode program yang telah dibuat. mohon diperhatikan dengan seksama.

atas perhatian dan kerjasama di ucapkan terimakasih!

**Comment by Naatan** [comment]
Please file your bugs in English.

**Comment by yosacyber** [comment]
Apologize in advance, I am not fluent in English. so I use a tool translate.google.com as language translators.

Supposedly for synchronization facility, please provide the facility to force the upload or download force where not all files are synchronized properly. his example when I make changes to an existing file on the local server but still showing the synchronization of existing data on the local server to the remote server. this can be destructive program code that has been made. please note carefully.

for your attention and cooperation in say thank you!

**Comment by Defman21** [comment]
Also please rename the bug report.

**Comment by cgchoffman** [comment]
I'm sorry but I still don't quite understand and it sounds like a sensitive issue.  All I can say is that you can Force Sync a file by right clicking on it in Places > Publishing > Push.

Other than that, we do not facilitate force push All, or force pull all unless you explicitly set it for a file.

The images you attached don't seem to  match the issue you're reporting either.  I do apologize but this ticket isn't workable currently.
