### ISSUE TITLE
Simplify completions handling for all our CodeIntel languages

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#3536]
In short, we need the following logic applied to all our languages (not just PHP):

https://github.com/Komodo/codeintel/commit/9c5a63f8a18f2800cbb3a97f6524dec49541ced6#diff-41a345eee15e8387d9cec1fa075634cdL1056

Main things that code does:

- Remove the dirname loop and pass all dirnames into the same call
- Explicitly look for symbols with the name_part prefix
- Only call resolveMember once

**Comment by mitchell-as** [comment]
I'm pretty sure https://github.com/Komodo/codeintel/commit/424b1c08498dbb9d5a898962ad2c4526c3f31e97 and https://github.com/Komodo/codeintel/commit/2baadd3b11abf56a2bc8605065bc1dbdc8ae5a47 added all the code that needs to be changed.

**Comment by cgchoffman** [comment]
Thanks for the ref @mitchell-as

**Comment by cgchoffman** [comment]
Note to self: review parent class `getCompl` function to see if an opt is possible there as well.

**Comment by Naatan** [comment]
Note to Carey's self: Assuming you mean the one in completions.py, that one basically just invokes the language specific ones. Optimisations there would be negligible. Not sure what you mean by whether opt is possible though.

**Comment by cgchoffman** [comment]
@Naatan, it was your idea.  You said you wanted me to look at other languages and optimize their getCompletions functions.  From what I understand, anything that doesn't have special magic imports (eg. JS and PHP) then it uses a base classes general function.  You said you wanted me to look there as well.

**Comment by Naatan** [comment]
Ah, I think you're talking about a different getCompletions function than I am. Essentially there's 2 "parent" classes.

**Comment by cgchoffman** [comment]
@Naatan, I was planning on only looking at the class you had modified, eg. anything that extends `AbstractScopeCompletionContext`.  Did you also want me to look at classes that extend `AbstractMemberCompletionContext`?  There is a `getCompletions` in there as well.

**Comment by cgchoffman** [comment]
https://github.com/Komodo/codeintel/commit/758d34de7f1d54d33fefe79194ea1f22c6445279
