### ISSUE TITLE
emmet not working in JSX file, when after self-closed tag

### ISSUE THREAD

**Issue by trogne** [Komodo/KomodoEdit#3538]
### Short Summary
emmet expansion (tab) is not working in JSX file, when we are positioned after self-closed tag (like "<br/>", or "<input ... />").

### Steps to Reproduce
In a JSX file, go inside a "<div></div>".

Enter input, then press tag. It works.

Enter a self-closed tag of your choice, like "<br/>".

Below, type a tag, e.g. "input", and hit "tab" : the tag does not expand. It's because of the previous "<br/>".

### Expected results
Emmet should expand the tag not matter kinds of tag before, whether "<a>", "<a/>" or "<a></a>".

### Actual results
Emmet does not expand the tag if previous tag is self-closed ( "<a/>" or "<a ... />").

### Platform Information
Komodo IDE 11.0.2
Windows 10

**Comment by mitchell-as** [comment]
Hi, please post this on our forums, as emmet functionality is maintained by a community member, not us.

https://community.komodoide.com

**Comment by Naatan** [comment]
To be clear, emmet is not shipped by us at all. You probably installed the xemmet addon.

**Comment by trogne** [comment]
I understand. I'll post this on on the forum. Thanks
