### ISSUE TITLE
Rx toolkit doesn't highlight matching strings

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#354]
The Regex toolkit isn't highlighting anything in the **Search Text** field any more.  Issue occurs as of 9.0.1.  Didn't check 9.0.

**Comment by Defman21** [comment]
Yep, it's the problem in default color schemes

**Comment by Naatan** [comment]
Hmm, was there another bug on this @Defman21? It sounds familiar.

**Comment by cgchoffman** [comment]
Note: I'm not using the default Color  Scheme

**Comment by Defman21** [comment]
Yeah, someone created a post about it on the forum and I answered to the
author, but iirc he didn't file a bug here.

**Comment by Defman21** [comment]
Btw it works fine for me. Komodo IDE, version 9.1.0, build 87333, platform linux-x86_64.
Built on Tue May 26 01:40:23 2015.
![scr](http://i.imgur.com/F6ljurI.png)

**Comment by cgchoffman** [comment]
Could you try and provide more details @Defman21?  Your Color Scheme?  The forum post you mention?  Can you reproduce this if you switch to a different Color Scheme?

**Comment by Defman21** [comment]
My color scheme is Autumn taken from here: http://komodocolor.appspot.com/scheme/preview/78002/autumn
I already wrote a link to the post. I can reproduce it only on default schemes, custom themes which has the `match_highlight` setting for Regex language works fine. What is your color scheme, Carey?

**Comment by cgchoffman** [comment]
Ahh thanks for editing you previous comment to add the link to the forum post.  I'm using isotope dark.

**Comment by Defman21** [comment]
You said that you are not using default color scheme... For sure you thought that I was talking about Tomorrow_Dark, didn't you? :stuck_out_tongue: All built-in schemes has this bug.
