### ISSUE TITLE
Find References does not work on PHP variables

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#3543]
Possibly an issue with the dollar sign? I've tried different variations, it always comes up empty.

Sample Code:
```php
<?php
$foo = "bar"; // Find reference on $foo

echo $foo;
?>
```

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoIDE/commit/cfa5dfd431fd0f848b0f3d7d3f28e93528d744f0

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoIDE/commit/61a616a73b7c47fb368134b8706bad2785832738
