### ISSUE TITLE
Symbol Browser doesn't list bound methods (JS)

### ISSUE THREAD

**Issue by gpolakow** [Komodo/KomodoEdit#3544]
### Short Summary
When a JS source file contains object definition, functions which are properties of the corresponding prototype and are bound in the object's creator vanish from the Symbol Browser.

### Steps to Reproduce
Create new empty JS file. Fill it with:

    function myObj() {
    }
    myObj.prototype.func1 = function() {
    };
    myObj.prototype.func2 = function() {
    };

The Symbol Browser look as expected:
![image](https://user-images.githubusercontent.com/38488375/39625442-afe298bc-4f9d-11e8-9dce-4f8c678067d7.png)

Now bind the `func1` to `myObj.this` by adding one line:

    function myObj() {
      this.func1 = func1.bind(this);
    }
    
    myObj.prototype.func1 = function() {
    };
    
    myObj.prototype.func2 = function() {
    };

and poof... `func1` is gone from the Browser:

![image](https://user-images.githubusercontent.com/38488375/39625518-0ceb91e4-4f9e-11e8-9619-3c3298c71d01.png)

Using `bind()` in such a way was not uncommon in some design patterns, the bug makes Symbol Browser useless when dealing with such code.

### Platform Information

Komodo IDE, version 11.0.2, build 90813, platform win32-x86.
Built on Mon Dec 04 08:56:02 2017.

Windows 10 version 1709 (OS Build 16299.125)

**Comment by mitchell-as** [comment]
Hi, this will be fixed in 11.1.
