### ISSUE TITLE
method autocompletion doesn't work

### ISSUE THREAD

**Issue by ANSI-C** [Komodo/KomodoEdit#3546]
### Short Summary
With module import correctly done, and "Additional Perl Import Directories" populated with right dirs, the typing "Module->" doesn't trigger anything, apart sometimes things completely (apparently) unrelated, that appear at least half minute after typing the ">" char.

### Steps to Reproduce
just try to use an OO module present in known (to Komodo) library paths

### Expected results
I should see a list of available methods to pick among

### Actual results
nothing shows up

### Platform Information
Komodo IDE, version 11.0.2, build 90813, platform win32-x86. Built on Mon Dec 04 08:56:02 2017.

**Comment by Naatan** [comment]
Could you share a code sample that reproduces your problem?

**Comment by ANSI-C** [comment]
Hello:

![immagine](https://user-images.githubusercontent.com/7015883/40109326-6096de6c-58fd-11e8-968e-d895db9e2c0c.png)

[https://metacpan.org/pod/JSON#new](https://metacpan.org/pod/JSON#new)

**Comment by ANSI-C** [comment]
Also "code intel" dialog keeps popping up without reason.

**Comment by mitchell-as** [comment]
Thanks for the update. It looks like our Perl catalog does not include the "new" method for the JSON package.

**Comment by ANSI-C** [comment]
That is just an example, I have lot of other modules whose methods are not being recognised, shouldn't be modules method listing automatic?

**Comment by mitchell-as** [comment]
The answer is: it depends. For stdlib modules, if we do not method entries in our catalog, then they will not be automatically listed. For user-written modules, that's another matter and we'll need some sample code. All of our Perl unit tests that involve non-stdlib modules are functioning correctly.

**Comment by ANSI-C** [comment]
Hi, cannot get any completion even for core Perl modules:
![immagine](https://user-images.githubusercontent.com/7015883/41981022-414ee972-7a28-11e8-91b6-c3bff9881a68.png)

**Comment by mitchell-as** [comment]
Hi, make sure you're using your `use JSON;` and `use Digest;` statements. Core Perl module completion will not work without them. When I do

```
use JSON;
my $test = JSON->
```

gives me JSON completions. Same with Digest.

**Comment by ANSI-C** [comment]
Yep, I do _use_ them, of course.

**Comment by mitchell-as** [comment]
So the snippet I provided does not work for you?

**Comment by ANSI-C** [comment]
Nope.

**Comment by mitchell-as** [comment]
Is any CodeIntelligence working for you? What about restarting in Safe-Mode? Please post the contents of your Help > Troubleshooting > View Log File. Please also post the contents of your codeintel3.log file. You'll find it in c:\users\username\appdata\local\activestate\komodoide\11.0\

**Comment by ANSI-C** [comment]
Hello, was forced to switch to IDEA since Komodo was no longer working for me, furthermore my ActiveState account credentials don't work anymore since you migrated to platform.activestate.com. I could give Komodo another try but I don't even receive reset password email triggered from platform.activestate.com

**Comment by ANSI-C** [comment]
Hi, please close this one, have been forced to switch to IDEA cause Komodo basically isn't working anymore for me since 8.x versions. Perhaps will give it a try from time to time to check if/when major bugs will be fixed. BTW, at this time my Komodo 11.1 gives back an error when trying to upgrade to latest version, sent an email to customer service about it.
