### ISSUE TITLE
Refactoring is very unreliable

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3548]
### Short Summary

refactoring now runs but it's very poor at finding proper scope and finding instances of the variable to be renamed.  The code needs to be redone to work better with the new code intel.

### Steps to Reproduce

For example, below, try renaming `rootpath`.
```python
import subprocess

def Usage(app_name):
    print("Usage: %s [-v | --verbose] [-h | --help]  [-f | --inputFormat] [[-i | --inputFile] filename] [[-u | --username] | [-tOutputType | --outputType]] [-U] [-G] " % app_name)
    print("       -h == display program options")
    print("       -f == input Format (%s) default %s" % (INPUT_TYPES, EMAIL))
    print("       -i == input filename")
    print("       -u == output usernames (cannot be used with -e option)")
    print("       -t == outputType (%s) default %s" % (OUTPUT_TYPES, USERID))
    print("       -U == Userids in inputfile")
    print("       -G == use GUI")
    print("       -v == verbose messages")
    print(rootpath)
    sys.exit(2)

arrUser = "foo@nvidia.com' , 'bar@nvidia.com"
arrOwner = "schehab@nvidia.com"
mgr = 2155
rootpath = 'C:\\tmp\\encrypt\\'
fileExport = rootpath + 'ExcelFiles\\'
exportFile = fileExport + str(mgr) + '-Org.xlsx'
cmd = 'powershell -command ". \'' + rootpath + 'encryptFile.ps1\'; $arrUser = \'' + str(arrUser) + '\'; $arrOwner = \'' + arrOwner + '\'; $filePath = \'' + exportFile + '\'; EncryptFile $arrUser $arrOwner $filePath '

	
print(rootpath)
if __name__ == "__main__":
    # get application name
    Usage("AIP-Test")

subprocess.call(cmd)
```
- What ends up happenings is "getCurrentScope" returns "null" which I guess means "global", starting at line `0`. 
- When continuing from the global scope it looks for the next scope to use as the area to search for instances of the variable.
- It finds `def Usage` at line 3 so goes from there.  
- This breaks things pretty badly

Another example:
- in the sample below
- perform refactor on second `pizza` just doesn't work at all.
- perform refactor on first `pizza` only renames that instance.
```javascript
var pizza = ""

function blah ()
{
    console.log(pizza);
}
blah();
```

**Comment by Naatan** [comment]
Does this mean there is no single clear cause to this issue that you can identify?

**Comment by cgchoffman** [comment]
I did finally narrow it down to something after I was able to figure out the spaghetti chaos that is this code.  I'm trying a couple things.

**Comment by cgchoffman** [comment]
This commit significantly increases reliability of this function: https://github.com/Komodo/KomodoIDE/commit/e638639a3a3973fdcec713af6a9ff51f8c906f24
but https://github.com/Komodo/KomodoEdit/issues/3549 is still causing issues with refactoring in JS files and will like effect other code if it's using the `getNextScope` function.
