### ISSUE TITLE
Ctrl+Home & Ctrl+End on Find Results Window not selecting respective elements

### ISSUE THREAD

**Issue by srgloureiro** [Komodo/KomodoEdit#355]
Hello.

When user hits Ctrl+Home the Find Results Window does not select first element.
When user hits Ctrl+End the Find Results Window does not select last element.

**Comment by Naatan** [comment]
What commands do you have those shortcuts assigned to?

**Comment by srgloureiro** [comment]
I do not have any custom shortcuts.

Try without Ctrl to see the difference.

**Comment by Naatan** [comment]
I don't see any default binding assigned to those keys that would skip through a list in the way you described. Do you intend for this to be an enhancement request or was this something that you expected to work (based on earlier versions of Komodo)?
