### ISSUE TITLE
Cannot get jquery completions

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#3558]
Use master or RC3 (once it's available).

Enable jquery catalog and try the following snippet:

```
$(document).ready(() => {
    $("<div>").fin
});
```

This should give a "find" completion.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/codeintel/commit/d0cbc2b981aeaf5f50eb8e80ba763e4c7cbdccf1
