### ISSUE TITLE
Can not create a new file on an SFTP server :(

### ISSUE THREAD

**Issue by SeriogaNY** [Komodo/KomodoEdit#3565]
### Short Summary
No way to create a new file on an SFTP server :(

### Steps to Reproduce
1. RightClick on an SFTP folder in "PLACES" panel 
2. Select "New File..."
3. NOTHING HAPPENS 

### Expected results
New file "Dialog Popup" in step 3 above

### Actual results
Nothing f#*king happens....

### Platform Information
Komodo Edit, version 11.1.0, build 18196, platform linux-x86_64.
Built on Wed May 23 00:03:30 2018.

### Additional Information
Problem started after update to version 11.1.0 from 11.0.0
~~Nothing relevant in the logs.~~
EDIT - Relevant log lines:

[2018-06-22 15:41:55,674] [ERROR] console-logger: Error: 'sftp://TBL/var/www/html' does not have a local path (2) in chrome://komodo/content/library/uriparse.js:201
Traceback (most recent call last):
  File "chrome://komodo/content/library/uriparse.js", line 201, in 

[2018-06-22 15:42:01,864] [ERROR] console-logger: Error: 'sftp://TBL/var/www/html' does not have a local path (2) in chrome://komodo/content/library/uriparse.js:201
Traceback (most recent call last):
  File "chrome://komodo/content/library/uriparse.js", line 201, in 

Please fix soon.
Thnx

**Comment by cgchoffman** [comment]
Relevant log lines:
```

ERROR:xpcom:Unhandled exception calling 'int8 * newURI(in utf8string &, in string, in nsISomething, out retval nsISomething);'
Traceback (most recent call last):
  File "C:\Users\cgcho\Komodo IDE 11.1\lib\mozilla\python\xpcom\server\policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "C:\Users\cgcho\Komodo IDE 11.1\lib\mozilla\components\koSFTP.py", line 47, in newURI
    self.defaultPort, aSpec, aOriginCharset, aBaseURI)
  File "<XPCOMObject method 'init'>", line 3, in init
Exception: 2152398858 (NS_NET_STATUS_WAITING_FOR)
[2018-06-22 12:50:56,381] [ERROR] console-logger: Error: invalid URI: sftp://Stackato - 10.19.0.148/home/stackato/drupal (2) in resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/url.js:37
Traceback (most recent call last):
  File "resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/url.js", line 37, in 
```

**Comment by Naatan** [comment]
`Stackato - 10.19.0.148` is this a case of bad user input or is it passing in the wrong server address?

@SeriogaNY can you verify that your server address is correct?

**Comment by SeriogaNY** [comment]
RE: can you verify that your server address is correct?
Yes, the server address is correct. I can Edit and Save files, Rename files and folders, I can create new Folders. However, I **can not create new Files**.

**Comment by smehrbrodt** [comment]
Same problem here, happens only since the update to Komodo Edit 11.1.0.
I am able to create new folders, but unable to create new files.

**Comment by lukeCleavland** [comment]
Same

**Comment by csorbamedia** [comment]
Same here.

**Comment by mitchell-as** [comment]
Hi, we've confirmed the bug and prioritized it. There is no need  for +1's. Thanks :)

**Comment by csorbamedia** [comment]
Please hurry! We use your software on a daily basis, this quite a serious bug.

**Comment by badc0ded** [comment]
Same. It's very annoying to have to create files in a separate terminal and then refresh folder view.

**Comment by raddimm** [comment]
same problem :(

**Comment by csorbamedia** [comment]
Why is this closed? The problem is still there and there is no update!

**Comment by cgchoffman** [comment]
Because it's been patched and will be in the next nightly.  If you find it doesn't work in the nightly then you can report back and we'll reopen the ticket.

**Comment by Naatan** [comment]
Note that bugs reflect the development status, not the release status.

**Comment by LeamasRein** [comment]
+1. Iinstalled 11 version an hour ago

> [2018-08-07 21:53:27,174] [ERROR] console-logger: Error: 'sftp://URL/path' does not have a local path (2) in chrome://komodo/content/library/uriparse.js:201
Traceback (most recent call last):
  File "chrome://komodo/content/library/uriparse.js", line 201, in

**Comment by Naatan** [comment]
@cgchoffman is working on a nightly that should address this. Carey please update this post when you've got something :)

**Comment by ConcourseMedia** [comment]
A work-around is to copy / paste an existing file and rename it.  Not ideal but better than having to create it on the command line.

**Comment by LeamasRein** [comment]
@ConcourseMedia, I have another idea. Install 10 version from website or use local drive with Dokan sshfs

**Comment by Naatan** [comment]
Version 11.0.2 should work too if you want a less severe workaround - http://downloads.activestate.com/Komodo/releases/archive/11.x/11.0.2/

**Comment by badc0ded** [comment]
@ConcourseMedia I'm not sure about in Komodo Edit, but copying to create file doesn't work in Komodo IDE

**Comment by ConcourseMedia** [comment]
It worked for me in Komodo Edit only if they were in different directories.

**Comment by cgchoffman** [comment]
There will be a 11.1.1 nightly in the following link in about an hour (when servers sync up).  Note that the version number says 11.1.0.  It's supposed to be 11.1.1 but the build started with the updated version is failing and rather than make you all wait any longer, you can just use the nightly that is labelled wrong.  

http://downloads.activestate.com/Komodo/nightly/komodoide/latest/

I will be be pushing a different nightly that is properly labelled, hopepfully tomorrow, but you do not need to update to it.  When we push a new nightly that has additional changes Komodo will automatically ask you to update to the latest nightly.

**Comment by cgchoffman** [comment]
Nightly is up.

**Comment by LeamasRein** [comment]
@cgchoffman what about komodo edit? Build 18199?

**Comment by cgchoffman** [comment]
@LeamasRein It's there.  You should be able to figure it out from that URL, no?

**Comment by cgchoffman** [comment]
http://downloads.activestate.com/Komodo/nightly

**Comment by LeamasRein** [comment]
@cgchoffman, of course, I checked the edit-version by url (and wrote the build number).
But I can't find out about fixing this bug by url for edit-version. I didn't ask "where find the komodo edit", right?

**Comment by cgchoffman** [comment]
You're question was ambiguous.  Yes Edit is fixed.  Did you try it and it's not working?

**Comment by LeamasRein** [comment]
Just checked, it works. Creation of folders and files is available by SFTP.

**Comment by cgchoffman** [comment]
@LeamasRein, great.  Thanks for confirming.

**Comment by hungtnguyen** [comment]
Same :( copy/paste an existing file and rename it the way I'm doing.

**Comment by hungtnguyen** [comment]
> Because it's been patched and will be in the next nightly. If you find it doesn't work in the nightly then you can report back and we'll reopen the ticket.

I find it doesn't work in the nightly :(

**Comment by omers** [comment]
Still happens to me.
Komodo Edit, version 11.1.0, build 18196, platform win32-x86. Built on Wed May 23 00:44:25 2018.

**Comment by cgchoffman** [comment]
@omers I'd be really surprised if it wasn't ;)  You're using the version that the issue was reported in.  Use the nightly.

**Comment by Mandalasand** [comment]
I have this same issue with Komodo IDE, been waiting a long time for at least a maintenance release.  As I am using the paid product version in a production environment, I would really like to simply use the Update feature to fix this ongoing and annoying issue.  Any idea when there might be an official production release scheduled?

**Comment by cgchoffman** [comment]
@Mandalasand if you have a license you should have received an email letting you know that Komodo 11.1.1 was released and how to get it.  Auto-update will not work for this release unfortunately.

**Comment by Mandalasand** [comment]
@cgchoffman thank you!  I do have a license but my filtering must have caught the email.  I'll search for it.  I appreciate the response and assistance!

**Comment by cgchoffman** [comment]
@Mandalasand, happy to help.  Sorry to punt but there is important information in that email.
