### ISSUE TITLE
11.1 Symbol Browser/CodeIntel broken in new window

### ISSUE THREAD

**Issue by cdcmicro** [Komodo/KomodoEdit#3567]
### Short Summary

The Symbol Browser (SB) and CodeIntel are dead or blocked when I open a new IDE 11.1 (IDE) window.

### Steps to Reproduce

1. Open IDE.  Initial or "main" window has working SB/CodeIntel.
1. Right-click a project from the Projects widget, and choose "Open project in a new window"

### Expected results

Project opens in a new window with SB/CodeIntel fully functional

### Actual results

Project opens in a new window, but SB says to open a buffer in a supported language for all files, either pre-existing/open in the project, or newly-opened.  FWIW, I have Perl, JS, and HTML files open.  Screenshot and log file below.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 11.1.0
*Operating System (and version)?* Win7 x64

### Additional Information

![screenshot_062418_032119_pm](https://user-images.githubusercontent.com/13684992/41824258-3fce19dc-77c2-11e8-80da-3b7f8910df02.jpg)

[pystderr.log.txt](https://github.com/Komodo/KomodoEdit/files/2131265/pystderr.log.txt)

**Comment by cdcmicro** [comment]
My usual pattern is to open the second and beyond projects from the commandline using `ko -n MyProject.komodoproject`  Those windows are similarly broken.

In addition, there's an error in the console like:

    Typeerror
    fileName: chrome://codeintel/content/sdk/service/mediator/codeintel.js
    lineNumber: 49
    columnNumber: 12
    Stack: 
        "Mediator/this.request@chrome://codeintel/content/s .."
        Mediator/this.request@chrome://codeintel/content/sdk/service/mediator/codeintel.js:49:13
        this.onServiceCall@chrome://codeintel/content/sdk/service/mediator.js:441:23
        this.mediate/<@chrome://codeintel/content/sdk/service/mediator.js:328:20
        this.scanCurrentWorkingDirectory@chrome://codeintel/content/sdk/feature/scanner.js:379:9
        this.start/<@chrome://codeintel/content/sdk/feature/scanner.js:428:13
        notify@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/timers.js:40:9
        injectOpenHandler/tw.openDialog@chrome://komodo/content/global.js:120:22
        openDialogWrap@chrome://komodo/content/komodo.js:641:19
        dialog_yesNoCancel@chrome://komodo/content/library/dialogs.js:131:1
        project_openProjectFromURL@chrome://komodo/content/project/projectManager.js:1539:26
        open_openURIAtLine@chrome://komodo/content/library/open.js:159:13
        open_openURI@chrome://komodo/content/library/open.js:84:12
        ko_workspace_restore/<@chrome://komodo/content/workspace.js:132:25
        this.waitForProjectManager/</delayFunc@chrome://komodo/content/workspace.js:520:17

**Comment by cdcmicro** [comment]
Same behavior in Safe Mode.

**Comment by cgchoffman** [comment]
Thanks for digging @cdcmicro, sorry you hit yet another bug.  We'll get these resolved asap.

**Comment by cdcmicro** [comment]
Thanks @cgchoffman.  I like the direction you're taking with 11 and I really want to be able to use it.  Sadly, this one's a showstopper for me, so I'm back to 10.2 for now.

Any chance you'll get back to posting nightly builds?

**Comment by cgchoffman** [comment]
Thanks @cdcmicro, I like it too.  We'll let you know how/when fixes will be coming.

**Comment by Naatan** [comment]
It looks like the new mediator code does not properly inherit an already existing codeintel connection on the main window. @cgchoffman give me a ping if you need help with this, shouldn't be too difficult once you know where to look.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoIDE/commit/926bf3947def3bf763a5159419ec870de9d08120
