### ISSUE TITLE
node.js: passing of interpreter arguments is not working when debugging node.js

### ISSUE THREAD

**Issue by drmead** [Komodo/KomodoEdit#357]
Komodo IDE, version 9.1.0, build 87337, platform win32-x86. Built on Fri May 29 18:45:28 2015.

The node.js source is:

    let x = "Success";
    console.log(x);

When I run this program from the command line, with the `--harmony` and `--use-strict` flags, there are no errors and it runs as expected.

    Y:\Personal\svm_task>node --harmony --use-strict let_test2.js
    Success

When I use "Run Without Debugging" within Komodo IDE I also get "Success"

When I try to debug from within Komodo with "interpreter arguments" set to:

    --harmony --use-strict

I get this error:

    Y:\Personal\svm_task\let_test2.js:1
    (function (exports, require, module, __filename, __dirname) { let x = "Success
                                                                  ^
    SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain [as _onTimeout] (module.js:497:10)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

It is definitely getting the same version of node.js from inside and outside. From the command line:

    node --harmony --use-strict --version let_test2.js 
    v0.10.33

Debugging from within Komodo with "interpreter arguments" set to:

    --harmony --use-strict --version

produces:

    v0.10.33

The bug appears regardless of whether I use "Debug in separate console", but I have observed that sometimes the separate console message produces a different error message.

====================================================================
This appears to be identical to a bug reported in Komodo IDE 8.5 and reputedly fixed in Komodo IDE 9

ActiveState Bugs » Bug #105067  2014-09-03 16:24:48 PDT
Fixed already in Komodo IDE 9 (with node,js debugger refactorings), but not in Komodo 8.5.

**Comment by Naatan** [comment]
As far as I'm aware the 'let' keyword is an ECMAScript 6 feature which is not part of NodeJS 0.10. Seeing as your test is called `let_test` I'd assume you're aware of this and are using some type of workaround. Could you elaborate on that?

**Comment by drmead** [comment]
Hi Nathan,

NodeJS 0.10 does support several ES6 features, but not by default. To
enable them, you have to pass the --harmony and --use-strict arguments when
starting node.js - as illustrated by successfully running let_test.js from
the command line by means of:

node --harmony --use-strict let_test.js

That's why I'm passing --harmony and --use-strict as interpreter arguments
when I'm running it under KomodoIDE.

I have retitled the bug report "node.js: passing of interpreter arguments
is not working when debugging node.js" as the interpreter arguments are
handled correctly when using "Run without Debugging".

Regards,
Derek

**Comment by drmead** [comment]
NodeJS 0.10 does support several ES6 features, but not by default. To enable them, you have to pass the `--harmony` and `--use-strict` arguments when starting node.js - as illustrated by successfully running let_test.js from the command line by means of:

    node --harmony --use-strict let_test.js

That's why I'm passing `--harmony` and `--use-strict` as interpreter arguments when I'm running it under KomodoIDE.

I have retitled the bug report "node.js: passing of interpreter arguments is not working when debugging node.js" as the interpreter arguments are handled correctly when using "Run without Debugging".

**Comment by drmead** [comment]
Oops - didn't intend to close the issue.

**Comment by Naatan** [comment]
Interesting, did not know about the `--harmony` stuff.

Back to the issue, I tried running the following script with some argments:

```
process.argv.forEach(function (val, index, array) {
  console.log(index + ': ' + val);
});
```

All arguments are printed, can you reproduce my test-case?

**Comment by drmead** [comment]
When I run your test case with interpreter arguments:

    --harmony --use-strict --no_such_node_option

and script arguments:

    --script_arg1

the output is:
 
    0: c:\program files\node\node.exe
    1: Z:\Derek\Komodo_bugs\Node-1.js
    2: --script_arg1
    Error: unrecognized flag --no_such_node_option
    Try --help for options

It looks as though the interpreter arguments are being processed, so the issue is presumably in the interface to the debugger.

**Comment by Naatan** [comment]
My bad, it's process.execArgv that I wanted, ie.

```
process.execArgv.forEach(function (val, index, array) {
  console.log(index + ': ' + val);
});
```

Using this with the komodo debugger it outputs 

```
0: --debug-brk
```

And none of the interpreter arguments I passed it.. Using it from the CLI it outputs

```
0: --harmony
1: --use-strict
```

@mitchell-as will hand this over to you to look further into. Definitely a bug, I think the node debugger simply isnt hooked up to use interpreter arguments.

**Comment by mitchell-as** [comment]
This will be fixed in the next release. It will require at least NodeJS v0.10.34: https://github.com/joyent/node/issues/8685
