### ISSUE TITLE
Ctrl+Shift+V does not cycle the clipboard ring.

### ISSUE THREAD

**Issue by srgloureiro** [Komodo/KomodoEdit#3571]
### Short Summary

Ctrl+Shift+V does not cycle the clipboard ring.

### Actual results

 It simply pastes

### Platform Information

Komodo Edit, version 11.1.0, build 18196, platform win32-x86.
Built on Wed May 23 00:44:25 2018.

**Comment by mitchell-as** [comment]
Hi, when you go to Edit > Preferences > Key Bindings, search for "Paste", and then select "Paste from clipboard history", does `Ctrl+Shift+V` show up in the "Current Key Sequence" box? It does for me for the default options and Ctrl+Shift+V presents me with a list of previously copied text.

**Comment by srgloureiro** [comment]
It is as in the image:
![image](https://user-images.githubusercontent.com/6369967/42338550-15208e36-8082-11e8-8bcb-13f8efe4ff5c.png)

**Comment by srgloureiro** [comment]
I changed the Key scheme to Default
![image](https://user-images.githubusercontent.com/6369967/42338809-f29e0766-8082-11e8-944d-4a2c3964f413.png)

then restarted Komodo. Now Ctrl+Shift+V does nothing at all :( 👎

**Comment by mitchell-as** [comment]
Hi, I see you are running Komodo Edit. Paste from history is only available from Komodo IDE. Sorry I missed that earlier.

**Comment by srgloureiro** [comment]
OK, it was not obvious reading the Change log. Paste from History was the main reason why I updated :P
