### ISSUE TITLE
x close character too close to filename in OpenFiles 

### ISSUE THREAD

**Issue by fnico35** [Komodo/KomodoEdit#3573]
### Short Summary
in the 'Open Files' window, the x character which is used to close a file is now just appended after the last character of the filename. It has the consequence that wanting to switch to a new opened  file in the editor window, many times, the file is closed by clicking inopportunely on the x character. 
In previous versions, the x character was at the end of the line, which is much much better.

### Steps to Reproduce
easy to reproduce

### Platform Information

*Komodo Edit or IDE?* Edit
*Komodo Version?* 11.1.0
*Operating System (and version)?* Windows 10

**Comment by Naatan** [comment]
The proper solution to this is to resize your side pane. We can't move it to the right any further or it would conflict with your scrollbar. Just make sure your side pane is big enough to contain the file names you're using.

**Comment by fnico35** [comment]
I've already tried this, it does not work for filenames, only for folder names.
In previous versions I have on Linux (8.5), it is on the right and does not conflict with the scrollbar (the x is located just left of the scrollbar)

**Comment by Naatan** [comment]
Could you share a screenshot of what you're seeing?

**Comment by Naatan** [comment]
Hi, could you please respond using the github interface? Github does not handle email well at all, it did not include your screenshots.

**Comment by fnico35** [comment]
Sure, here are 2 screenshots, one with the x char for the folder, the other one with the x char for the files
I have just deliberately sized down the window to have the scrollbar appearing.
This pb just appeared recently with the very recent update of Komodo 11.1
Regards
![komodo_scrennshot1](https://user-images.githubusercontent.com/40851737/42364251-137fb3c8-80ea-11e8-9636-43091b110f1d.jpg)
![komodo_scrennshot2](https://user-images.githubusercontent.com/40851737/42364252-13b15b1c-80ea-11e8-9f8f-623eaf9b5b7a.jpg)

**Comment by Naatan** [comment]
Oh, huh that's strange. Definitely a bug. Not sure what could have affected that, but obviously something did.

Thanks for reporting!
