### ISSUE TITLE
CSS GRID not supported

### ISSUE THREAD

**Issue by Inu-desu** [Komodo/KomodoEdit#3575]
### Short Summary
When typing CSS Grid codes it returns an error parse value or unknown property value.

### Steps to Reproduce
Typing 
.wrap {
display:grid
 Grid-template-areas: 
"title title title"
"logo menu menu"
}
### Expected results

should not return either a parse error or a unknown property value

### Actual results

it returned a parse error value and an unknown property value

### Platform Information

Komodo Edit
Version 11.1.0
Windows 10

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?*

**Comment by mitchell-as** [comment]
Hi, please go to Edit > Preferences > Syntax and Spell Checking, select CSS from the "Language" drop down, uncheck "Mozilla CSS Checker", and check "Komodo CSS Checker".
