### ISSUE TITLE
Excluding Directory\* on Find Dialog does not exclude

### ISSUE THREAD

**Issue by srgloureiro** [Komodo/KomodoEdit#358]
If I have Directory\\* on the exclude field, it does not exclude the contents of directory. The Include subfolders checkbox was checked on and it found files inside descendant folders of specified Directory.

**Comment by Naatan** [comment]
Unfortunately the exclude filter in the find dialog only covers files, not folders. Searching within your Project would respect the folders excluded from the Project though.

**Comment by cgchoffman** [comment]
I believe you can use folder names, you just don't need the *.  Simply include the directory name and it is excluded.

**Comment by srgloureiro** [comment]
@cgchoffman The approach you purpodes works. Thanks. 

But it could be problematic. Imagine you have a file named with the same name than the directory you exclude and guess what happens... file will not be searched!

**Comment by cgchoffman** [comment]
Only if your file doesn't have a file extension will it match.  From my experience it would be non-standard to remove file extensions from files other than maybe binary files, which you don't care about searching in...usually....hopefully.
