### ISSUE TITLE
Snippet Indentation Context Not Working in Komodo 11.1.0, build 91033

### ISSUE THREAD

**Issue by chrisluka** [Komodo/KomodoEdit#3585]
### Short Summary
When 'maintain indentation context' is selected in the snipppet properties, snippets inserted when the editor cursor is indented should "pick up" that indentation.  Doesn't seem to be working.  

### Steps to Reproduce
1) Create a snippet.  Enable the checkbox for "maintaining indentation context."

test_snippet {
    alert('hello');
}

2) In an editor window, indent the cursor, then insert the snippet.
3) The first line will be indented, all others will not.

### Expected results

    test_snippet {
        alert('hello');
    }

### Actual results

    test_snippet {
    alert('hello');
}

### Platform Information

Komodo IDE
Version 11.10
Build 91033
Windows Server 2016 standard, also reproduced on Windows 10

**Comment by cgchoffman** [comment]
#3569
