### ISSUE TITLE
Commando - Projects

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#359]
Just an idea. I really like Commando but I don't see any way to navigate between projects, so I have to go to the menu - Projects - Recent Projects. Navigating between projects like between files would be a very great feature :)

**Comment by Naatan** [comment]
I intend to implement this as an addon so people can see how it works and then create their own Commando scopes :) Will close this issue since it will not be tracked as a Komodo enhancement (just a separate, unsupported addon).
