### ISSUE TITLE
impossible to create file on ftp

### ISSUE THREAD

**Issue by drpark** [Komodo/KomodoEdit#3590]
Hi,
since last update, it is impossible to create a new file on ftp directly with komodo...
Thanks...it's a really annoying issue...

Easy to reproducte...

**Comment by Naatan** [comment]
This issue is tracked here - https://github.com/Komodo/KomodoEdit/issues/3590

**Comment by Blur-Creative** [comment]
linked to the same issue and closed? ok...
the same issue here. any workaround or solution?

**Comment by Defman21** [comment]
https://github.com/Komodo/KomodoEdit/issues/3565
