### ISSUE TITLE
Python 3.7.0 breaks Komodo

### ISSUE THREAD

**Issue by fjossandon** [Komodo/KomodoEdit#3592]
### Short Summary
Komodo IDE is not working with Python 3.7.0, it gives an error instead. New reserved keywords create an invalid syntax on the current code.

### Steps to Reproduce
Using Python 3.7.0, open Komodo, try to run any python3 script or click in Tools->Start New Python3 Shell and it will give an error:
```
Traceback (most recent call last):
  File "/Applications/Komodo IDE 10.app/Contents/SharedSupport/dbgp/bin/py3_dbgp", line 105, in <module>
    import dbgp.client
  File "/Applications/Komodo IDE 10.app/Contents/SharedSupport/dbgp/python3lib/dbgp/client.py", line 1975
    def interaction(self, frame, tb = None, async = 0):
                                                ^
SyntaxError: invalid syntax
```
This example is from Komodo 10, but Komodo 11 gives the same error.

### Expected results
Debug/execute the script.

### Actual results
Debugging window crash.

### Platform Information
Komodo IDE
Versions 10.2.3 and 11.1.0
Mac OS X El Capitan

### Additional Information
After looking around I found that in Python 3.7 `async` and `await` are now reserved keywords (https://docs.python.org/3/whatsnew/3.7.html), so all variables named like that are now an invalid syntax and must be renamed.

**Comment by fjossandon** [comment]
Found 2 "async" uses in client.py:
* `def interaction(self, frame, tb = None, async = 0):`
* `def cmdloop(self, async=0):`

**Comment by cgchoffman** [comment]
@fjossandon try Komodo 11.

**Comment by fjossandon** [comment]
@cgchoffman please check the report, I tested with Komodo 11 and it breaks too.

**Comment by cgchoffman** [comment]
You're logs say Komodo 10.

**Comment by cgchoffman** [comment]
Thanks for the report.

**Comment by fjossandon** [comment]
I said `This example is from Komodo 10, but Komodo 11 gives the same error.`. I did not think it was necessary to add the same again for Komodo 11, but if you need it here it is:
```
Traceback (most recent call last):
  File "/Applications/Komodo IDE 11.app/Contents/SharedSupport/dbgp/bin/py3_dbgp", line 105, in <module>
    import dbgp.client
  File "/Applications/Komodo IDE 11.app/Contents/SharedSupport/dbgp/python3lib/dbgp/client.py", line 1975
    def interaction(self, frame, tb = None, async = 0):
                                                ^
SyntaxError: invalid syntax
```

**Comment by cgchoffman** [comment]
> I did not think it was necessary to add the same again for Komodo 11

It's not, i was just saying that your logs said 10.  I did not read the whole report, my apologies.

**Comment by fjossandon** [comment]
no problem 👍

**Comment by cgchoffman** [comment]
> After looking around I found that in Python 3.7 async and await are now reserved keywords 

Thanks for looking this up btw.  I can't help but think this was a very very VERY silly change.  This will break a ton of code I imagine.  Maybe I missed warnings of this change coming.

**Comment by fjossandon** [comment]
Yep, I'm now seeing similar breaks in other projects.

I went to the file and renamed all the `async` to `asynch` and it worked!
```
diff client_old.py client.py
1975c1975
<     def interaction(self, frame, tb = None, async = 0):
---
>     def interaction(self, frame, tb = None, asynch = 0):
1979c1979
<             return self.requester.cmdloop(async)
---
>             return self.requester.cmdloop(asynch)
2523c2523
<     def cmdloop(self, async=0):
---
>     def cmdloop(self, asynch=0):
2526,2527c2526,2527
<         #log.debug("cmdloop async=%d", async)
<         if async and not self.poll():
---
>         #log.debug("cmdloop asynch=%d", asynch)
>         if asynch and not self.poll():
2532c2532
<             if not async and self._continueTransactionId is not None:
---
>             if not asynch and self._continueTransactionId is not None:
2549c2549
<                 if async:
---
>                 if asynch:
2554c2554
<             if async:
---
>             if asynch:
```
After that it complained about something with locale instead:
```
Traceback (most recent call last):
  File "/Applications/Komodo IDE 11.app/Contents/SharedSupport/dbgp/bin/py3_dbgp", line 307, in <module>
    sys.exit( main(sys.argv) )
  File "/Applications/Komodo IDE 11.app/Contents/SharedSupport/dbgp/bin/py3_dbgp", line 166, in main
    _fixencoding()
  File "/Applications/Komodo IDE 11.app/Contents/SharedSupport/dbgp/bin/py3_dbgp", line 148, in _fixencoding
    codeset = locale.getdefaultlocale()[1]
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/locale.py", line 568, in getdefaultlocale
    return _parse_localename(localename)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/locale.py", line 495, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8
```
Not sure if is related to your implementation or Python 3.7 (it works fine with Python 2.7), but found how to fix that (https://stackoverflow.com/questions/38916461/valueerror-unknown-locale-utf-8-when-importing-pandas-in-python-2-7/38917471#38917471) by adding the `LC_ALL=en_US.UTF-8` and `LANG=en_US.UTF-8` to the User environment variables in Komodo settings, and now it finally works:
```
Python 3.7.0 (default, Jul 23 2018, 20:23:10) 
[Clang 8.0.0 (clang-800.0.42.1)] on darwin
Type "copyright", "credits" or "license" for more information.
```

**Comment by cgchoffman** [comment]
Nice digging @fjossandon.

**Comment by drh-git** [comment]
hi fjossandon,

thanks for your help -- i had exactly the same problem, was stuck until i saw your post.  the diff output was particularly helpful.  on windows 10 i didn't have the locale problem after fixing client.py.  i hope that there aren't other uses of async or await in the activestate library.

**Comment by cgchoffman** [comment]
> i hope that there aren't other uses of async or await in the activestate library.

Komodo runs on Python 2.7.  We only hit this because the Python 3 debugger is necessarily written in Py3 and is run by the Python 3 interpreter you provide.  Komodo itself runs off it's own Python 2 interpreter and is unaffected by this bug.

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/7ea0055faa8312063cf9e6483a48d093be0a4c6a
This fix will be in a nightly build tomorrow around 12 pm PST.

**Comment by cgchoffman** [comment]
Confirming I pushed the nightly to the server and it will be available at the time stated above.

**Comment by fjossandon** [comment]
Thanks @cgchoffman !!

**Comment by cgchoffman** [comment]
@fjossandon, thank ME?...Thank YOU.

**Comment by cgchoffman** [comment]
Nightly: http://downloads.activestate.com/Komodo/nightly/komodoide/latest/

**Comment by Feroxxor** [comment]
Hi, 
does this mean I have to switch to Komodo IDE 11? I'm using Komodo IDE 9 and get the same Error. But I don't have a Komodo IDE 11 licence. Is there a fix for Komodo IDE 9?

**Comment by Feroxxor** [comment]
Hmm I get the same Error in Komodo IDE 11

> Traceback (most recent call last):
>   File "C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\support\dbgp\bin\py3_dbgp.py", line 105, in <module>
>     import dbgp.client
>   File "C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\support\dbgp\python3lib\dbgp\client.py", line 1975
>     def interaction(self, frame, tb = None, async = 0):
>                                                 ^
> SyntaxError: invalid syntax

**Comment by cgchoffman** [comment]
@Feroxxor, did you download the nightly in my last comment?

**Comment by Feroxxor** [comment]
Yes, but this was komodo 11 and I have 9. Or is there a nightly of komodo 9?

**Comment by Naatan** [comment]
Komodo 9 is not maintained any longer, you need to update to 11 to get updates. We offer an upgrades & support subscription for those who want to stay current, otherwise your purchase only covers the lifespan of the major version you purchased.
