### ISSUE TITLE
Can't create a new file in file explorer via sftp remote komodo edit 11.1.0

### ISSUE THREAD

**Issue by zynth666** [Komodo/KomodoEdit#3593]
### Short Summary

When I'm trying to create a new file in my remote directory nothing happens.

### Steps to Reproduce

Right-click any folder in a sftp accessible remote directory and choose 'New File...'.

### Expected results

Popup opens to enter file name and file is created.

### Actual results

Popup doesn't show up at all and no file is created.

### Platform Information

Komodo Edit 11.1.0 
Windows 10 Enterprise

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoEdit/issues/3565
