### ISSUE TITLE
Search-and-replace "Replace" text does not default to a blank entry

### ISSUE THREAD

**Issue by mjross** [Komodo/KomodoEdit#3596]
### Summary
When performing a search-and-replace operation, the text in the "Replace" field should default to whatever was last used (assuming that at least one replacement operation has already been performed). However, if the most recent replacement text is a blank string (i.e., the searched-for text is simply deleted and not replaced with any nonblank text), then that (empty) value is not used as the default value in the "Replace" field. As a consequence, if the user does not notice that the "Replace" field contains an earlier (nonblank) value, then he can accidentally end up inserting a value into one or more files, thinking that the searched-for text is being removed and not replaced with something spurious.

### Steps to Reproduce
Help > Troubleshooting > Restart in Safe-Mode. 

The four attached screenshots illustrate this in a very simple example. First the user searches for all "1" and replaces them with "X". Then he decides to remove all "2". Next he decides to remove all "3", but the "Replace" field does not contain a blank but instead the "X". In the fourth and final screenshot, we see that among all of the replacement values, only the "X" is displayed and a blank string is not one of the values.

I noticed this problem a while back, but finally was prompted to submit an issue because recently I was performing dozens of search-and-replace operations on hundreds of files, trying to remove countless lines of code, and each time I would restart the operation for one reason or another, I would discover to my consternation that the text was being replaced with an incorrect string that I had used as replacement text a while ago and had nothing to do with the current operations.

### Expected Results
The "Replace" field should default to whatever was last used, including a blank string.

### Actual Results
The "Replace" field fails to default to the blank string that was last used.

### Platform Information
Komodo IDE 11.1.0 build 91033 (on Windows Pro 10.0.17134.228)

### Social Media Hashtag
#BlankLivesMatter  ;+)

### Attachments
![clipboard01](https://user-images.githubusercontent.com/829492/44310602-ec55b400-a39e-11e8-9110-092e10e4e064.png)
![clipboard02](https://user-images.githubusercontent.com/829492/44310603-efe93b00-a39e-11e8-8961-7755911ec229.png)
![clipboard03](https://user-images.githubusercontent.com/829492/44310604-f37cc200-a39e-11e8-8911-7ac9d9729499.png)
![clipboard04](https://user-images.githubusercontent.com/829492/44310608-f5df1c00-a39e-11e8-940f-a5d2ae8f2bd5.png)

**Comment by cgchoffman** [comment]
Closing in favour of #3596.

**Comment by mjross** [comment]
Hi, Carey! Closing in favour of itself? Shouldn't that be a second (but similar) issue? (I may be misinterpreting this comment.)

**Comment by cgchoffman** [comment]
Well ya!  They describe the same issue!  Kidding, thanks for pointing that out haha.  I meant #2437

**Comment by mjross** [comment]
;)  But... but... *my* version is more wordy! (As usual...)

**Comment by cgchoffman** [comment]
haha always appreciated @mjross
