### ISSUE TITLE
Code folding

### ISSUE THREAD

**Issue by sgeard** [Komodo/KomodoEdit#3597]
### Short Summary
Code folding is not very useful

### Steps to Reproduce
Open a Tcl or Fortran (or probably any other file type)
E.g.
proc get_nsteps {from to step} {
    return [expr {1+entier(0.5+($to-$from)/$step)}]
}

proc get_log_nsteps {from to step} {
    return [expr {1+entier(log10($to/$from)/log10($step))}]
}

set cj 3
...

Click on the '+' next to "proc get_nsteps"
### Expected results

proc get_nsteps {from to step} {

proc get_log_nsteps {from to step} {
    return [expr {1+entier(log10($to/$from)/log10($step))}]
}

### Actual results
proc get_nsteps {from to step} {
proc get_log_nsteps {from to step} {
    return [expr {1+entier(log10($to/$from)/log10($step))}]
}

i.e. the blank line after the proc has been folded as well.

### Platform Information

*Komodo IDE*
*11.1.0*
*Mageia6 Linux 64* 

### Additional Information
This is behaviour is not the same as Visual Studio and in my view VS is correct and Komodo is wrong. It means that any blank lines used to improve layout and readability are lost which in turn makes the code less readable - defeating its raison-d'etre. Any chance of changing this behaviour?

**Comment by Naatan** [comment]
Komodo's editor component uses Scintilla. The code folding is not actually handled on our side, it's on Scintilla's side. So this would be a bug/feature-request for Scintilla rather than for Komodo.

https://www.scintilla.org/ScintillaToDo.html
