### ISSUE TITLE
jQuery autocompletions not working in 11.1.1

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3599]
### Short Summary
In Komodo 10 I'm getting auto-completions for all of jQuery's functions.
In Komodo 11.1.1 I'm getting none.

Komodo 10:
![afbeelding](https://user-images.githubusercontent.com/3530262/44728738-760f2b00-aadd-11e8-8ecf-7f8b34c01135.png)

Komodo 11.1.0:
![afbeelding](https://user-images.githubusercontent.com/3530262/44728788-8c1ceb80-aadd-11e8-85cc-079b712f26f6.png)

### Steps to Reproduce
For both Komodo 10 and 11 I have set a default directory, with includes a jQuery file:

![afbeelding](https://user-images.githubusercontent.com/3530262/44728887-cedec380-aadd-11e8-8866-80a7ab845b0f.png)

### Expected results
Getting auto-completions.

### Platform Information
Komodo IDE, version 11.1.1, build 91041, platform win32-x86

**Comment by Naatan** [comment]
Did you enable jQuery under Prefs > Code Intelligence ?

**Comment by babobski** [comment]
Thanks, that did the trick!
