### ISSUE TITLE
Bug in synchronization KomodoIDE

### ISSUE THREAD

**Issue by yosacyber** [Komodo/KomodoEdit#360]
Apologize in advance, I am not fluent in the English language so I use google translator to translate Indonesian into English.

1. in the image below an error in sync files in localhost and the server. beg to be corrected ...
(pada gambar dibawah ini terjadi kesalahan dalam menyinkronkan berkas yang ada di localhost dan pada server. mohon untuk diperbaiki...)
![untitled](https://cloud.githubusercontent.com/assets/3403508/8268900/2ee8f4f6-17bd-11e5-87c0-28e010151421.png)

2. Why frequent error when doing file synchronization process localhost with the existing file on the server? (Kenapa sering terjadi error ketika sedang melakukan proses sinkronisasi berkas localhost dengan berkas yang ada pada server?)
![capture](https://cloud.githubusercontent.com/assets/3403508/8268923/deb695c8-17bd-11e5-80c9-666c291f8b54.PNG)

3. File Synchronization frequent errors, shown in the picture below. no data is deleted on the server or data deleted on localhost. (Sinkronisasi berkas sering terjadi kesalahan, terlihat pada gambar dibawah ini. tidak ada data yang di hapus pada server maupun data yang di hapus pada localhost.)
![capture](https://cloud.githubusercontent.com/assets/3403508/8268937/76e9e7f0-17be-11e5-8f3d-3ba79b9c1af6.PNG)

4. Should add a special menu so that the data can be uploaded or downloaded in accordance with the wishes of users of these applications. it is very ... very ... very important, if the same error occurs. (Sebaiknya tambahkan menu khusus agar data bisa di upload atau di download sesuai dengan keinginan pengguna aplikasi ini. hal ini sangat...sangat...sangat penting, jika terjadi kesalahan yang sama.)
![capture](https://cloud.githubusercontent.com/assets/3403508/8268966/53bc38e0-17bf-11e5-90f6-2c7fbfe9e039.PNG)

5. should the push button is replaced or supplemented by buttons that are more useful, such as FORCE UPLOAD or FORCE DOWNLOAD (sebaiknya pada tombol push digantikan atau ditambahkan dengan tombol yang lebih bermanfaat, seperti FORCE UPLOAD atau FORCE DOWNLOAD)
![capture](https://cloud.githubusercontent.com/assets/3403508/8268978/29a2476a-17c0-11e5-9b7a-2ac2761422b1.PNG)

so much and thank you for your cooperation (sekian dan terimakasih atas kerjasamanya)

**Comment by Naatan** [comment]
Hi there, thank you very much for taking the time to report this. I do apologize but unfortunately we cannot use bug reports that report several issues at once. Could I kindly ask that you report your issues/suggestions separately (one report per bug)? 

Apologies for the inconvenience, thank you for your time.
