### ISSUE TITLE
Segmentation Fault while running komodo-edit "11.1.0-18196'

### ISSUE THREAD

**Issue by npandey2385** [Komodo/KomodoEdit#3602]
Hi ,

I am getting the Segmentation fault (core dump) while running komodo edit. Could you please help me on this issue ?

I ran gdb on core dump. Here is the logs:

Reading symbols from /komodo-edit/latest/bin/komodo...(no debugging symbols found)...done.
[New LWP 14868]
Error while mapping shared library sections:
`/komodo-edit/latest/lib/mozilla/libpython2.7.so.1.0': not in executable format: File format not recognized
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/komodo-edit/latest/bin/komodo'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f4ef3e3a453 in _dl_relocate_object () from /lib64/ld-linux-x86-64.so.2

I am using version "11.1.0-18196" and installed it over the NFS.

Thanks
Niraj

**Comment by cgchoffman** [comment]
Please fill out all the requested fields in the ticket template.

**Comment by npandey2385** [comment]
Do not install Komodo in a path that contains spaces or non-alphanumeric characters. In my path I am using "-" that's the reason getting this issue.

**Comment by th3coop** [comment]
> Do not install Komodo in a path that contains spaces or non-alphanumeric characters

This is not true.  Spaces and non-alphanumeric chars don't effect Komodos run time.  There might be an edge case but `-` isn't it.  That install path is highly suspect.  How did you install Komodo?

**Comment by npandey2385** [comment]
I got this info from the below site under "Installing Komodo on Linux"

http://docs.activestate.com/komodo/11/get/linux/

I used the command ./install.sh to install the Komodo. During installation I didn't see any issue as well.

**Comment by th3coop** [comment]
Thanks for clarifying @npandey2385 .  Have you tried reproducing your claim that special characters broke it?   I'm leaning more towards something corrupting the installer during download or at some other step.  I'd say anti virus but you're not on Windows so that's not likely.  If you download the installer again and run it, installing in the same path, do you get the same error?
