### ISSUE TITLE
Symbol browser missing collapse expand functionality

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3605]
### Short Summary
In the new symbol browser I'm really missing the expand/collapse functionality.
When working on large js files I'm missing this functionality, I noticed I can use the show all symbols in the cog menu. but when using this function on large files it becomes a bit messy.

I would prefer the expand/collapse functionality or at least a option to show all symbols for a specific function ( maybe with a context menu option ). 

Use case:
When I have a large js file and I want to see witch variables are defined for a specific function, in 10 I can expand the function and see witch variables are used for the function. In 11 I have to use the show all symbols function to see witch functions or variables are defined in the function. Only when hitting this option the list grows so big that the function I want to inspect is not showing in the list any more, I first have to scroll down to my function.

![afbeelding](https://user-images.githubusercontent.com/3530262/45869383-9e124700-bd88-11e8-991c-d4a55b74ecda.png)

For example I want to inspect witch variables or functions are defined in "getAvailibleOptions", in 10 I can just expand the function and see instantly witch function and variables are used in the function.

When I want to do the same in Komodo 11.* I first have this list:

![afbeelding](https://user-images.githubusercontent.com/3530262/45869609-34466d00-bd89-11e8-8b51-256180d83093.png)

When I now the use the "show all symbols" function it becomes a realy long list:

![afbeelding](https://user-images.githubusercontent.com/3530262/45869748-88515180-bd89-11e8-846b-4d6ae4f5dea0.png)

I have to scroll pretty far down to see what is defined in this function.
I tried using the search function to maybe go there faster but then I don't see the variables and function.

**Comment by Naatan** [comment]
This is by design, you can use the filter mechanic to narrow it down, but expand/collapse is not expected to return at this stage. Note the menu does give you further options to narrow down your scope.
