### ISSUE TITLE
Mac OS Mojave: Scroolbars show all the time instead of "When scrolling"

### ISSUE THREAD

**Issue by ecterrab** [Komodo/KomodoEdit#3608]
<img width="715" alt="screen shot 2018-09-25 at 12 13 33 pm" src="https://user-images.githubusercontent.com/12106224/46037838-43e1f080-c0be-11e8-96d4-8204f18be0dd.png">

### Short Summary

I updated to Mac OS Mojave, from High Sierra and Komodo Edit 8.5.4, which happens to crash systematically in Mojave, so I upated to the latest Komodo, 11.1.0 build 18196 from Wed May 23.

In my mac preferences, under General, I have "Show scroll bars: "When scrolling". But, in the latest Komodo, they show all the time, and rather thick (the ones that appear only when scrolling are thin in comparison).

I tried all the configuration items I could imagine, going one by one all the preference settings, including the Scrolling options under Preferences -> Editor, but couldn't figure out how to have the scrollbars, both the vertical and the horizontal ones, display properly (that would be "only when scrolling, and with thin width, not thick)

I also tried Help -> Troubleshooting -> Restart in Safe-Mode, and yes, that worked, the scrollbars displayed properly, but when going back to normal mode the problem is there again.

Note: my Komodo Preferences -> Appearance, has Enable Classic mode and Use native window borders selected, but even if I don't select one or both this undesired continuous display of thick scroll bars is still there. I'm mostly sure this is a setting I need to adjust ... but really couldn't find it.

### Steps to Reproduce

See above and image attached

### Expected results

Scrollbars, vertical and horizontal, displaying only when scrolling, and with thin width, as they display when restarting in Safe Mode.

### Actual results

Scrollbars, vertical and horizontal, displaying all the time and with thick width

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?*

**Comment by ecterrab** [comment]
I updated to Mac OS Mojave, from High Sierra and Komodo Edit 8.5.4, which happens to crash systematically in Mojave, so I upated to the latest Komodo, 11.1.0 build 18196 from Wed May 23.

In my mac preferences, under General, I have "Show scroll bars: "When scrolling". But, in the latest Komodo, they show all the time, and rather thick (the ones that appear only when scrolling are thin in comparison).

I tried all the configuration items I could imagine, going one by one all the preference settings, including the Scrolling options under Preferences -> Editor, but couldn't figure out how to have the scrollbars, both the vertical and the horizontal ones, display properly (that would be "only when scrolling, and with thin width, not thick)

I also tried Help -> Troubleshooting -> Restart in Safe-Mode, and yes, that worked, the scrollbars displayed properly, but when going back to normal mode the problem is there again.

Note: my Komodo Preferences -> Appearance, has Enable Classic mode and Use native window borders selected, but even if I don't select one or both this undesired continuous display of thick scroll bars is still there. I'm mostly sure this is a setting I need to adjust ... but really couldn't find it.

**Comment by Naatan** [comment]
Are you certain this happened only after installing Mojave? I don't have a mac handy to test right this minute, but I seem to recall this is just how Komodo works on MacOS.

**Comment by ecterrab** [comment]
Do you use Macs? It only happens in Mojave. I have another mac, still running High-Sierra, with the latest Komodo and _**identical**_ configuration, and this problem with the scroll bares does not happen there. Besides, recall (see the post above) this does not happen in Komodo's Safe Mode.

**Comment by Naatan** [comment]
Interesting. Could you try running the following from your Console widget (bottom pane):

```
ko.prefs.deletePref('koSkin_use_custom_scrollbars'); 
```

**Comment by Naatan** [comment]
Cool. No idea how that got set, but glad it's solved!
