### ISSUE TITLE
Commando: Files keyboard shortcut fails (the second time) when "Preserve Previous Search Query" is checked.

### ISSUE THREAD

**Issue by ecterrab** [Komodo/KomodoEdit#3609]
### Short Summary

Commando: Files keyboard shortcut (I have Shift + Command + O) fails (the second time) when "Preserve Previous Search Query" is checked. So it works the first time, but if I now click "Escape" to close the window and try again, it doesn't work anymore.

Workaround: open Komodo's Preferences -> Commando -> uncheck "Preserve Previous Search Query" while keeping "RelativePaths use the current file's directory" and "Don't require Alt or select results by number" both checked.

### Expected results

The keyboard shortcut works also when "Preserve Previous Search Query" is checked.

### Actual results

It doesn't.

### Platform Information

*Komodo Edit or IDE?*  11.1.0, build 18196
*Komodo Version?* 
*Operating System (and version)?*  Mac OS Mojave

**Comment by ssigwart** [comment]
@cgchoffman, I think #3696 solved this.

**Comment by cgchoffman** [comment]
it's working for me!
