### ISSUE TITLE
Command output issue (wrong order)

### ISSUE THREAD

**Issue by Alkatrass** [Komodo/KomodoEdit#3615]
I use python3 here and I have a wrong order in command output after running the script
Here is my simple script for example:
`num = input("enter a number:")`
`if float(num) < 0:`
 `___raise ValueError("Negative!")`
`else:`
    ` ___print("Positive")`

And the output after running the script should look like this:
`enter a number:`

But that's not true. I enter a number and after that I get a string which should be in the start of the output 
`1`
`enter number:Positive`

**Comment by Naatan** [comment]
Hi, this doesn't look like a bug report. Please consider posting on the forums or something like Stackoverflow.
