### ISSUE TITLE
Can't open save dialog on OSX mojave

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3620]
### Short Summary

When you try to Save As... a file, the dialog will eventually hang and freeze rendering Komodo unusable.  See video in Repro section  link to see it in action.

There is a bug in Mozilla that is causing this: https://bugzilla.mozilla.org/show_bug.cgi?id=1489785

Ref: 
https://community.komodoide.com/t/crashes-on-all-save-as-attempts/4441/

### Steps to Reproduce

Repro: https://community.komodoide.com/t/crashes-on-all-save-as-attempts/4441/18

**Comment by cgchoffman** [comment]
Build failed :( Took a bit of doing to fix the build server but it's running a new build now.  If it finishes by end of day i'll try and push a nightly to the servers.  Earliest, it will be there this evening, latest, Monday at noon, middle ground, i might push it to the server tomorrow.

**Comment by cgchoffman** [comment]
I've pushed a nightly with this fix to the staging server.  It will be public at around 12 noon PST.  You can get it here when it's available:
http://downloads.activestate.com/Komodo/nightly/komodoide/latest-11.1.x/

**Comment by smkiewel** [comment]
So sorry I missed this. This appears to have fixed my issue. Thank you so much. And sorry again for missing this.

**Comment by ctkjose** [comment]
Had same problem, tested with builds KomodoIDE (91046) and KomodoEDIT (18203) and is working as expected.

thanks...
