### ISSUE TITLE
Use interpolation string instead of hardcoded binary names in default unit testing commands

### ISSUE THREAD

**Issue by devdave** [Komodo/KomodoEdit#3623]
### Update From Dev

Ref: https://github.com/Komodo/KomodoEdit/issues/3623#issuecomment-439081744

We should update all the applicable unit testing default commands to use an interpolation string for the binary instead of a hard coded binary name. That way it will look at the users prefs before looking at the system path.

### WORKAROUND

Make a custom Unit Testing entry using the same default command but change the hard coded binary to the interpolation version.

Ref: http://docs.komodoide.com/manual/shortcuts#interpolation-shortcuts_interpolation-code-list

### Short Summary
I don't have Pytest installed to the global/system install of Python so running the unit tests throws up the message in stderr `c:\python36\python.exe: No module named pytest`

### Steps to Reproduce

1. Create a fresh Python3 project
2. Assign project to use a specific virtualenv's copy of Python
3. Write some code, write a test
4. Click on the edit symbol in widget to create a new test
5. Leave all fields as default, 
6. click OK and then click run

### Expected results
It feels like it should just automatically use %(python) and not be hardcoded to use "python3" in the `Command` field.

### Platform Information

Komodo IDE, version 11.1.0, build 91033, platform win32-x86. Built on Wed May 30 10:04:55 2018.

### Additional Information

A super quick fix to this - 

In the "Edit Unittest config" pop up box, 
1. change Framework dropdown to custom
2. fill command input with `%(python3) -m pytest --tb short --color no -vr a`
3. ensure Parser is set to `pytest`
4. voila

I always have virtualenvs per project so I can't remember how Komodo handles magic command line vars like %(python) or %(python3) but if it just defaults to whatever is on $PATH (%PATH% for Windows) then why not just have the default command text box argument just use the magic inject vars by default?

**Comment by cgchoffman** [comment]
I'm a little confused by your report so i'm just going to explain what the interpolation strings do.
They first look for a configured interpreter in your prefs, File > Project > Global, then look at your path.
`%python` is python2
`%python3` is self explanatory
If you didn't start Komodo from the terminal that you activated your virtualenv in then Komodo has no idea about that env.  



> It feels like it should just automatically use %(python) and not be hardcoded to use "python3" in the `Command` field.

Why would you do this?  You're using Python 3 so the interpolation string should be `%(python3)`

**Comment by devdave** [comment]
>Why would you do this? You're using Python 3 so the interpolation string should be %(python3)

That was a typo, I meant %(python3).

1. My project has my virtualenv set as default under languages -> Python 3
4. If have have my project active, with Python 3 set to use my virtualenv as the default Python 3 interpreter, then shouldn't the system know which Python 3 binary to use?

I know that just using default, the unit-testing widget was using the system installed version of Python 3 over what my project settings because pytest with failing, saying it was missing an installed library and the path to the system Py3 install was in the error message.

![kide_pytest](https://user-images.githubusercontent.com/281946/48541081-0f4a1400-e879-11e8-9647-c5c63eab0124.PNG)

**Comment by cgchoffman** [comment]
> That was a typo, I meant %(python3).

Thanks for clarifying.

That screenshot is very helpful.   The grayed out string will be run as is, without any interpolation, in a background process.  That means that it will look for the first `python3` binary that it finds on your PATH, it will not look at your prefs (where you've set your virtualenv binary).

So you're saying that that grayed out command should have `%(python3)` interpolation string instead of `python3` binary name?  That's probably a good idea.

Thanks for clarifying.  Just gonna run this by my colleague.  For now, go with the workaround you came up with as I'm not going to be able to get a fix + nightly out all that quickly and we have some other things ahead in the queue of fixes.

**Comment by devdave** [comment]
>So you're saying that that grayed out command should have %(python3) interpolation string instead of python3 binary name? That's probably a good idea.

Exactly.   If I switch to a custom test after copy & pasting that string in with the minor change of wrapping it in %() so it is %(python3), it works without issue.

**Comment by cgchoffman** [comment]
@devdave, great.  Thanks for confirming.  I'm going to update the original ticket info.
