### ISSUE TITLE
Komodo IDE 11.1 - Modals do not have top most window flags

### ISSUE THREAD

**Issue by devdave** [Komodo/KomodoEdit#3626]
### Short Summary

On opening Komodo IDE, a text alert/modal pops up asking if the prior workspace should be restored.  I often don't see this popup as it doesn't have top window status.   This hangs the IDE until an OK or No option is selected and used to be quite confusing.

### Steps to Reproduce

Depends I believe on using in a M$ Windows environment.  "Restore workspace", "New project", "Unit test edit", and a few other modals are affected.   

### Expected results

It feels like all should be top most so they are not lost.

### Platform Information

Komodo 11.1 - Windows 10

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoEdit/issues/1694
