### ISSUE TITLE
Windows 10 - Always use Komodo for php and css

### ISSUE THREAD

**Issue by profesionalplus** [Komodo/KomodoEdit#3632]
Hello,

every time i try to open php or css file, Windows 10 asks me with which software i want to open the file with. I choose Komodo and select "Always use this app to open...", however, when i later try to open any php or css file, it asks me again with which app would i like to open it.

This happens only with Komodo. Associating files with other software works fine. Any ideas?

Best regards

**Comment by rm-bergmann** [comment]
The problem you are describing I have not experienced with Komodo but I have experienced it with other apps and file extensions. I don't think this is an issue with Komodo. 

Take a look at this link which will take you through the steps f managing default apps by file extensions. 
If Komodo is already selected for css & php files, try select it again and point to the komodo .exe file of the current version. (It's possible that windows is still pointing to the location of a previous Komodo version)

https://www.lifewire.com/how-to-change-file-associations-in-windows-2624477

**Comment by profesionalplus** [comment]
Thx for your reply. This didn't help. Komodo is not even recognized in the apps list, like it wasn't even installed.

**Comment by babobski** [comment]
You can configure this inside Komodo **Preferences > Windows intergration**:

![afbeelding](https://user-images.githubusercontent.com/3530262/49577150-14b1f000-f947-11e8-836a-cb7b5f764593.png)

You can configure the associations by hand, or apply the common associations.
Hope this helps you out.

**Comment by profesionalplus** [comment]
This did the trick. Thanks a lot. :)

**Comment by babobski** [comment]
Glad to help!
