### ISSUE TITLE
Hang during OSX file pickper

### ISSUE THREAD

**Issue by sam-aldis** [Komodo/KomodoEdit#3633]
### Short Summary

Freezing during the display of native file picker

### Steps to Reproduce

Open -> Folder -> Navigate up a folder

### Expected results

Folder change in view

### Actual results

View hangs

### Platform Information

OSX - Mojave - Komodo Edit.

**Comment by casimirloeber** [comment]
I am experiencing the exact same behavior in Komodo IDE. The frozen open file dialogue gets stuck in focus even if I change applications underneath it. 

I have to force quite Komodo to deal with it.

MacOS 10.14.1 (18B75)
Komodo IDE, version 11.1.0, build 91033, platform macosx. Built on Wed May 30 10:04:57 2018.

**Comment by ctkjose** [comment]
Check this bug:
https://github.com/Komodo/KomodoEdit/issues/3620

 This was fixed in the latest nightly releases.

**Comment by Naatan** [comment]
This will be fixed in the upcoming 11.1.1 release.
