### ISSUE TITLE
Komodo hangs up while editing a large file

### ISSUE THREAD

**Issue by steveheflin** [Komodo/KomodoEdit#3636]
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIDocument.isEncodable]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: vieweditor :: _validateEncoding :: line 1367"  data: no]

Exception: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIDocument.isEncodable]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: vieweditor :: _validateEncoding :: line 1367"  data: no]

Traceback:
_validateEncoding@vieweditor:1367:16
save@vieweditor:1464:21
viewManager.prototype.offerToSave@chrome://komodo/content/views.js:1408:16
viewManager.prototype.canClose@chrome://komodo/content/views.js:127:25
this.runCanCloseHandlers@chrome://komodo/content/komodo.js:255:22
this.observe@chrome://komodo/content/komodo.js:621:13
canQuitApplication@chrome://global/content/globalOverlay.js:45:4
goQuitApplication@chrome://global/content/globalOverlay.js:57:7
this.quitApplication@chrome://komodo/content/komodo.js:56:8
@chrome://komodo/content/library/controller.js line 111 > eval:1:0
broadcasterController.prototype.doCommand@chrome://komodo/content/library/controller.js:111:0
command_doCommand@chrome://komodo/content/library/commands.js:239:0
command_doCommandAsync/<@chrome://komodo/content/library/commands.js:196:12

Komodo IDE, version 11.1.0, build 91033.
Built on Wed May 30 10:04:55 2018.

**Comment by cgchoffman** [comment]
Please fill out the fields in the default ticket.
