### ISSUE TITLE
Maintain indentation context after insertion is broken

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3640]
### Short Summary
For snippets, the maintain indentation context after insertion is broken.
It is reported in this [post](https://community.komodoide.com/t/abbrevation-indentation-context-not-maintained/4478)
Tested it, but with the same results.

### Platform Information
Komodo IDE, version 11.1.0, build 91033, platform win32-x86

**Comment by Naatan** [comment]
@cgchoffman I believe this is fixed in the upcoming 11.1.1 release, no ?

**Comment by cgchoffman** [comment]
I thought it was fixed but I assumed @babobski was on the nightly.  If you're not, please try it: http://downloads.activestate.com/Komodo/nightly/komodoide/latest-11.1.x/

**Comment by Naatan** [comment]
If he was then we forgot to update version.txt again :p

**Comment by babobski** [comment]
Tested it in he latest nightly, but it is working here.

**Comment by cgchoffman** [comment]
https://community.komodoide.com/t/abbrevation-indentation-context-not-maintained/4478/4?u=careyh
