### ISSUE TITLE
trying to use python debugging

### ISSUE THREAD

**Issue by elliotperkins153** [Komodo/KomodoEdit#3645]
### Short Summary
Trying to debug python 3 code
keep getting error message below

### Actual results
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\support\dbgp\bin\py3_dbgp.py", line 105, in <module>
    import dbgp.client
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\support\dbgp\python3lib\dbgp\client.py", line 1975
    def interaction(self, frame, tb = None, async = 0):
                                                ^
SyntaxError: invalid syntax

### Platform Information
komodo ide 11

### Additional Information
![image](https://user-images.githubusercontent.com/22898027/50378558-f22c0200-05e9-11e9-9d5c-4ea946546cc6.png)

**Comment by Naatan** [comment]
The Komodo 11.1.1 update should address this, but it is a manual update due to it having moved to the ActiveState Platform.

Download: https://www.activestate.com/products/komodo-ide/download-ide/
