### ISSUE TITLE
Drop Down Options Not Working

### ISSUE THREAD

**Issue by nikitatelkar** [Komodo/KomodoEdit#3648]
**Short Summary**

Drop down option for any menu does not work after being selected once.

**Expected results**

Eg. Clicking on the settings icon in the left toolbar to select directory, and then wanting to change the directory again. Or wanting to visualise the different colour schemes.

**Actual results**

Can only select the directory once, and if trying to change to another one, the option does not work. Applicable to all menus having a drop down menu.

**Platform Information**

Komodo Edit, version 11.1.0, build 18196, platform macosx. Built on Wed May 23 00:03:29 2018. MacOS Mojave version 10.14.1

**Comment by Naatan** [comment]
Any chance you could provide a video of the problem?

**Comment by laufeyjarson** [comment]
I'm seeing the exact same problem on Komodo IDE, version 11.1.1, build 91089, platform macosx. Built on Wed Dec 12 12:52:03 2018.  I'm not sure what a video will help, but I'll try and get one.

**Comment by laufeyjarson** [comment]
I can't attach any video files, but see: http://www.rdwarf.com/users/wwonko/Komodo11DropdownIssue.mov

**Comment by nikitatelkar** [comment]
Yup, that's exactly what I'm experiencing too.

**Comment by Naatan** [comment]
Thanks for the video, very useful! Just reproduced it on macOS.

**Comment by Naatan** [comment]
Awesome, thanks fo sharing @ssigwart ! we should be able to backport that fix.

**Comment by alexandr-mironov** [comment]
I has same problem, got any solution for this? (sorry for my English, it's not native lang)

**Comment by HunterAhlquist** [comment]
I can still produce the bug on MacOS 10.14.5 on Edit 11.1.1

**Comment by ssigwart** [comment]
A lot of fixes are in the 11.1.2 nightly:
https://downloads.activestate.com/Komodo/nightly/komodoedit/latest/

**Comment by cmcramer** [comment]
Same problem here. Sometimes doesn't happen after first time opened, sometimes takes 2-3 times before functionality is disabled. Also, dropdowns frequently respond slowly even when they work. (macOS 10.14.5)

**Comment by th3coop** [comment]
@cmcramer  are you using the "nightly" linked by @ssigwart in the comment above yours?  If not, please try it, if yes, thanks for letting us know!
