### ISSUE TITLE
%(python) interpolation shortcut doesn't use the project setting

### ISSUE THREAD

**Issue by hobbsd** [Komodo/KomodoEdit#365]
For example:
![screen-2015-06-22_16-14](https://cloud.githubusercontent.com/assets/1676348/8291874/20fc6ce0-18fa-11e5-9eb0-e0690b89c340.png)
But the current project has a virtualenv python configured.

The same appears to go for pylint syntax checking. I have pylint installed in the virtualenv, but the option is grayed out.

**Comment by mitchell-as** [comment]
For the record, the latest nightly is honoring my project python executable. I don't know if that means this issue is resolved though.

**Comment by mitchell-as** [comment]
This does not appear to be an issue any longer. I created a new project, created a "fake" Python executable, and changed my project's Python preferences to point to that fake Python. This was the content of my fake Python exe:

    #!/bin/sh
    echo 'my python'

I ignored the fact the project preferences was telling me I had an invalid Python executable and ran the command "%(python)". The output pane showed "my python", which shows my project setting for the Python executable was honored.
