### ISSUE TITLE
Minimapcan not be disabled

### ISSUE THREAD

**Issue by rovf** [Komodo/KomodoEdit#3654]
### Short Summary

Even though I have NOT checked in my Preferences "Use Minimap Scrollbar", the minimap is shown with every file.  

This happens even after a fresh install of the editor.

### Platform Information

*Komodo Edit* 
*11.1.1, build 18206, platform win32-x86* 
*Windows 7* 

### Additional Information

![capture_20190114_144338](https://user-images.githubusercontent.com/6795665/51116312-0e971500-180b-11e9-8f36-8da5a0fb45d4.jpg)

![capture_20190114_144408](https://user-images.githubusercontent.com/6795665/51116323-1787e680-180b-11e9-9b1b-46e10505fcdf.jpg)

**Comment by rovf** [comment]
![capture_20190114_144735](https://user-images.githubusercontent.com/6795665/51116473-7cdbd780-180b-11e9-9c12-db0acf6a5a7e.jpg)

**Comment by Naatan** [comment]
The setting in your Preferences can be overwritten on a per-file basis, which might be what's happening here. Is the minimap still enabled if you open a file that you've never opened before?

**Comment by cgchoffman** [comment]
I'm not able to reproduce this.  If anyone else come across this bug feel free to provide the requested info and request that we reopen.
