### ISSUE TITLE
pystderr.log is very verbose

### ISSUE THREAD

**Issue by ssigwart** [Komodo/KomodoEdit#3658]
### Short Summary
PHP completion and hint failures put a lot of data into `pystderr.log`.

### Steps to Reproduce
1.  Open a PHP project and go to a class file.  Tail `pystderr.log`.
2.  Either:
a.  Start typing something like `$a->` in a function where `$a` is not defined or
b.  Cmd hover over a keyword like `if` or `function` to trigger a hint lookup.

### Expected results
I'm not sure if these lookup failures should be logged at all, but if they are, I think it should be a short message.

### Actual results
For each such lookup failure `pystderr.log`, grows by around 1.5MB depending on the project.  I'm not sure if this can bog down Komodo Edit after a while.

### Platform Information
Komodo Edit 11.1.1
MacOS Mojave 10.14.2

### Additional Information
This seems like it might need changes if the logs are to be shortened:
https://github.com/Komodo/KomodoEdit/blob/71694f78e2fe602d30a7ee6cd7e5a67d5ed159cb/src/codeintel/lib/codeintel2/oop/controller.py#L32-L44
This seems to cause all the info and debug messages to be output.

**Comment by cgchoffman** [comment]
I can't actually reproduce this one.  Are you sure you didn't get the logging level somehow while testing something else?

**Comment by cgchoffman** [comment]
Oh woh, nvm.  The lookups were taking a LONG time in this project I guess.

**Comment by cgchoffman** [comment]
It does seem like this could cause significant performance hits.
