### ISSUE TITLE
Komodo-IDE-11.1.1-91089-linux-x86 crashed after start !!!

### ISSUE THREAD

**Issue by VladimirLarionov** [Komodo/KomodoEdit#3666]
[pystderr.log](https://github.com/Komodo/KomodoEdit/files/2802827/pystderr.log)

### Short Summary
Komodo-IDE-11.1.1-91089-linux-x86 crashes after launch in application launcher Fedora   4.20.3-200.fc29.i686
    I am get message:
    Sorry - Plasma
    Could not find the program '/root/Komodo-IDE-11/lib/mozilla/komodo'
    If you run Komodo-IDE-11.1.1-91089-linux-x86 the command line, the program works but an error     appears. Given in actual results.

### Steps to Reproduce
Download and install latest Fedora 29 Spin KDE and install/run Komodo IDE.

### Expected results
I want the program to run without crashing.

### Actual results
(process:5232): GLib-CRITICAL **: 21:53:15.460: g_slice_set_config: assertion 'sys_page_size == 0' failed
console.error: 
  Message: [Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [koIPreferenceRoot.getPref]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: chrome://komodo/content/sdk/prefs.js :: PreferenceSet/this.getPref :: line 264"  data: no]
  Stack:
    PreferenceSet/this.getPref@chrome://komodo/content/sdk/prefs.js:264:23
loadCatalogs@chrome://codeintel/content/sdk/feature/scanner.js:235:21
this.start/<@chrome://codeintel/content/sdk/feature/scanner.js:429:12
notify@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/timers.js:40:8

### Platform Information

*Komodo Edit or IDE?*  IDE
*Komodo Version?*  Komodo-IDE-11.1.1-91089-linux-x86
*Operating System (and version)?*  Fedora   4.20.3-200.fc29.i686

**Comment by Naatan** [comment]
Nothing stands out in the log, does starting with default settings help?

https://docs.activestate.com/komodo/11/manual/trouble.html#ko_default

**Comment by VladimirLarionov** [comment]
No, it does not help. The error remained.

**Comment by cgchoffman** [comment]
@VladimirLarionov, how did you install Komodo?  What commands did you use?

**Comment by VladimirLarionov** [comment]
1. Download the Komodo installer (.tar.gz file) into a convenient directory.
2. Unpack /home/vladimir/Downloads/KomodoIDE
3. su -
    cd KomodoIDE
    ./install.sh
    press ‘Enter’ to accept the default location
    export PATH=<installdir>/bin:$PATH
   To start Komodo on Linux enter komodo.

**Comment by cgchoffman** [comment]
Ok, that could be causing issues.  You should install Komodo as you, no `su`.  It got installed in your *root* users home dir, ie. `/root/`.   You must have selected the default install location.  Try deleting that install then re-run the installer *without* `su`.  That might resolve your issue.

**Comment by VladimirLarionov** [comment]
Unfortunately did not decide:

[vladimir@localhost Komodo-IDE-11.1.1-91089-linux-x86]$ ./install.sh
Traceback (most recent call last):
  File "./support/_install.py", line 731, in <module>
    sys.exit( main(sys.argv) )
  File "./support/_install.py", line 670, in main
    hdlr = logging.FileHandler(gInstallLog, mode='w')
  File "/home/vladimir/Downloads/Komodo-IDE-11.1.1-91089-linux-x86/INSTALLDIR/lib/python/lib/python2.7/logging/__init__.py", line 911, in __init__
    StreamHandler.__init__(self, self._open())[vladimir@localhost Komodo-IDE-11.1.1-91089-linux-x86]$ ./install.sh
Traceback (most recent call last):
  File "./support/_install.py", line 731, in <module>
    sys.exit( main(sys.argv) )
  File "./support/_install.py", line 670, in main
    hdlr = logging.FileHandler(gInstallLog, mode='w')
  File "/home/vladimir/Downloads/Komodo-IDE-11.1.1-91089-linux-x86/INSTALLDIR/lib/python/lib/python2.7/logging/__init__.py", line 911, in __init__
    StreamHandler.__init__(self, self._open())
  File "/home/vladimir/Downloads/Komodo-IDE-11.1.1-91089-linux-x86/INSTALLDIR/lib/python/lib/python2.7/logging/__init__.py", line 936, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/home/vladimir/Downloads/Komodo-IDE-11.1.1-91089-linux-x86/koinstall.log
  File "/home/vladimir/Downloads/Komodo-IDE-11.1.1-91089-linux-x86/INSTALLDIR/lib/python/lib/python2.7/logging/__init__.py", line 936, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/home/vladimir/Downloads/Komodo-IDE-11.1.1-91089-linux-x86/koinstall.log

**Comment by VladimirLarionov** [comment]
Oh! I am sorry. Do not read the previous message. After removal koinstall.log program installed successfully. Thank you.

**Comment by cgchoffman** [comment]
@VladimirLarionov you'll probably need to `rm` your Komodo profile.  It might have been created as the super user and now Komodo can't access it as your regular user.  It's at `~/.komodoide`.  You can either 1. `chown` it back to your user or 2. delete it then start Komodo.  I'd do option 2.

**Comment by VladimirLarionov** [comment]
OK. Thank you. No more questions.
