### ISSUE TITLE
IDE bugs me every day to join the AS Platform

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#3668]
I joined, I downloaded and installed Komodo IDE, version 11.1.1, build 91089, platform linux-x86_64. Built on Wed Dec 12 13:20:27 2018.
Well it's easy to close it, but it's annoying.

![screenshot_2019-02-01_06-06-39](https://user-images.githubusercontent.com/350912/52120013-0c91cc00-25e9-11e9-8108-08849fc3efaa.png)

**Comment by Naatan** [comment]
Did you press "not interested" or are you just closing of with the X?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by agroszer** [comment]
AFAIR closed it, but will pay attention next time

**Comment by cgchoffman** [comment]
Someone in the forums is reporting that "Not Interested" does not stop the dialog from appearing.

**Comment by agroszer** [comment]
yeah looks like not interested makes it go away

**Comment by stramin** [comment]
It doesn't work for me, I still getting the invitation to join the platform after joining and pressing "Not Interested" button.

**Comment by stramin** [comment]
Oh, I just pressed the "Not Interested" button, closed and reopen Komodo twice and it stopped, it seems like making some attempts make it work.
