### ISSUE TITLE
Filenames with '?' character causes an exception

### ISSUE THREAD

**Issue by zinic** [Komodo/KomodoEdit#367]
### Overview
When reading a directory with a file containing the '?' character, Komodo fails with an alert box containing an exception. Komodo IDE appears to be removing certain special characters when attempting to resolve the file's path.

### Build Tested
Tested against build: **Komodo IDE, version 9.1.0, build 87333, platform linux-x86_64. Built on Tue May 26 01:40:23 2015.**

### Steps
* ```mkdir test_project```
* ```touch 'test_project/the_file?'```
* Using Komodo IDE Create new project within ```test_project```

Upon completion of these steps an exception alert box pops up:
![error_box](https://cloud.githubusercontent.com/assets/25071/8339391/ebac1216-1a6b-11e5-967c-ade7a435106c.png)

**Comment by cgchoffman** [comment]
Dupe #1510
