### ISSUE TITLE
Create project send pop up windows in the background

### ISSUE THREAD

**Issue by bedardpl** [Komodo/KomodoEdit#3683]
### Short Summary
upon selecting the directory in the create project dialog box, the focus is back on the main ui and the create project windows seems to "disappear". That's a misleading as it's just get hidden by the fact that the focus is lost on the "create project window"

### Steps to Reproduce
create a new project
select a directory

### Expected results
back in the create new project windows where i can complete filling up name of the project
and other information

### Actual results
the create project pop up windows seems to disappear, but it's just that focus is back on the main ui element.

### Platform Information

Komodo IDE, version 11.1.1, build 91089, platform win32-x86.
Built on Wed Dec 12 11:57:06 2018.

*Operating System
OS Name	Microsoft Windows 7 Enterprise
Version	6.1.7601 Service Pack 1 Build 7601

**Comment by cgchoffman** [comment]
Thanks @bedardpl

**Comment by babobski** [comment]
#3257

**Comment by cgchoffman** [comment]
@babobski well that explains why it was so familiar.

**Comment by babobski** [comment]
I  Know, same here ;)
