### ISSUE TITLE
Run COmmand MRU not saving

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#37]
It looks like this might just be on Windows.  Nathanr can't reproduce on his machine.
- Run a command in Run Command
- Open Run Command again

*Expect*: Previous command to be in Run field, when I type should offer suggestions of possible commands, clicking dropdown should show me all previous commands
*Actual*: All of the above is not happening.

Tried restarting with KOMODO_USERDATADIR set but made no difference.

**Comment by Naatan** [comment]
Just reproduced this on Linux, so not Windows only.
