### ISSUE TITLE
Annoying error when opening Komodo on Linux

### ISSUE THREAD

**Issue by mjbrancato** [Komodo/KomodoEdit#370]
Every time I open up Komodo on Linux I get this annoying error: http://dl.dropbox.com/u/23057021/Selection_022.png

I have no FTP connections/servers listed as that either. So not sure why it's throwing that error.

**Comment by Naatan** [comment]
Might be trying to access a recently used file, it shouldn't be actually connecting but could be some type of bug (eg. trying to get the file status for a remote file where it isnt really necessary).

Try using the following code in a macro and then restart Komodo:

```
require("ko/prefs").deletePref("mruFileList")
```

**Comment by Naatan** [comment]
Please take it to the forums to discuss this further, there is no bug here as of yet: http://forum.komodoide.com/
