### ISSUE TITLE
Drag and Drop Bug OSX

### ISSUE THREAD

**Issue by datamafia** [Komodo/KomodoEdit#371]
I searched for "drag and drop " before creating ticket with no avail.

Synopsis:

Komodo crashes when using combination of copy (clipboard) and select+crag and drop.

How to replicate:

* open new file
* make some text
* select some text
* drag selected text

Results:

* double "paste" (used incorrectly, I know)
* occasional full crash

Desired results:

Komodo still running.

Additional Info:

Can induce crash by opening left pane. (weird right?)

This issue has been in the system in ver 7 and 8 (I think) as well, I remember being on a thread confirming behavior.

1:30 video on the topic: https://www.youtube.com/watch?v=pC30BLxne7M

**Comment by Naatan** [comment]
Thanks datamafia. In additional info you said opening left pane can induce a crash, does that relate to the drag text crash or is that separate?

I've reproduced the double paste issue, I can so far not reproduce a crash. I've noticed that it also seems to loose the selection after dropping.

@mitchell-as this is right up your alley. I suspect this is related to the Scintilla upgrade we did a few months ago, OSX has not been playing well with it at all. Possibly because we also changed our OSX SDK from 10.6 to 10.9.

**Comment by datamafia** [comment]
#### re: "you said opening left pane can induce a crash"

For that demo the left pane toggle made the crash. Just weird...

When working on Py files I was getting crash on copy selection A and select+move selection B.

#### re: "seems to loose the selection after dropping" 

Did not notice.

### Additional:

My crashes are very much centered around the "copy selection A and select+move selection B" action. This was a problem in the past, but a crash was not the result.

I will try to narrow down the Python file crash using "copy selection A and select+move selection B". I work in Python mostly so when I get something solid I will pass it through.

**Comment by cgchoffman** [comment]
More details for the next person to work on this:  #463 is a more consistent crash use case.  Granted it may not be the same issue.  I've never been able to reproduce @datamafia's crash but I have another user in OTRS that has.

**Comment by mitchell-as** [comment]
I'm not certain this is a Scintilla issue right now. I can 100% reproduce a crash by:

1. Opening a new file.
2. Hide the left sidebar.
3. Enter "hello" on the first line and then pressing enter a half-dozen times.
4. Double-click "hello" to select it and then drag-drop somewhere on an empty line.
5. Show the left sidebar.
6. Hard crash. The error report contains this tidbit: `PyxpcomMethod: {091116f0-0bdc-4b32-b9c8-c8d5a37cb088}::getCellText`. Seems like the crash is originating from the side pane, not Scintilla itself.

Still need to investigate further...

**Comment by mitchell-as** [comment]
The double-paste of dragged text has been reported as a bug to upstream Scintilla. When a fix is issued we'll back-port it.

**Comment by Naatan** [comment]
@mitchell-as could you provide a link to the relevant scintilla bug?

**Comment by mitchell-as** [comment]
http://sourceforge.net/p/scintilla/bugs/1752/
