### ISSUE TITLE
Tabbing through Find "dialog" is broken on OSX

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3715]
### Steps to Reproduce

- Focus on find field and start tabbing through

### Expected results

- Should tab through all fields and buttons in order, Left-Top to Left-btm then Right-top to Right-btm.

### Actual results

Only jumps through text fields

### Platform Information

*Operating System (and version)?* OSX ONLY

**Comment by ssigwart** [comment]
See https://robertnyman.com/2007/01/18/551/.  I think this is the default setting in OSX for `Keyboard > Shortcuts`:
![image](https://user-images.githubusercontent.com/1426848/53995220-657de400-4102-11e9-9385-ad0e2a229b7b.png)

Changing it to "All controls" makes it work.

**Comment by ssigwart** [comment]
[This might be the mozilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=424482) that enabled this setting.  @cgchoffman, perhaps that patch could be removed so it ignores that setting.  I'm not sure if that would be appropriate though.  I don't see why someone wouldn't want to be able to tab to all inputs, but OSX has a setting, so there must be some reason.

**Comment by cgchoffman** [comment]
I believe we can change the default pref inside mozilla rather than reverting a patch.  I basically followed Kanashii's instructions and set `accessibility.tabfocus_applies_to_ul` to `false`.  That might just do it for our purposes.

**Comment by cgchoffman** [comment]
@ssigwart not sure if you noticed the nightly that went out last week if you want to benefit from all these fixes.  I'll be doing another one tomorrow I believe.  Working on a Ruby debugging issue.
http://downloads.activestate.com/Komodo/nightly/komodoide/latest-master/

**Comment by ssigwart** [comment]
I did see that, thanks.  It's been working well.  Since #3708 is approved, would you be able to merge that one into the next nightly?

**Comment by cgchoffman** [comment]
@ssigwart oops.  Approved.   I forgot to push a nightly this morning.  I'll stage stuff now so it'll be life by noon tomorrow.

**Comment by ssigwart** [comment]
Thanks.  Looking forward to it.
