### ISSUE TITLE
Completions triggering on `;` for SCSS, possibly others

### ISSUE THREAD

**Issue by th3coop** [Komodo/KomodoEdit#3716]
### Short Summary

We fixed this in CSS but the fix didn't bubble up to SCSS.  I thought this was a setting in a subclass that all the styling markup langs used.  

### Steps to Reproduce

Open a SCSS file and completions should not be triggered when a `;` is pressed.

**Comment by rm-bergmann** [comment]
I can confirm I get this in LESS files. I'm now in the habbit of pressing ';' then 'ESC'

**Comment by RemcoWessels** [comment]
I just started with IDE 12.0.1 and the bug is (still?) alive and kicking.

**Comment by th3coop** [comment]
Closing in favour of the original ticket, #3297.  Evidently this was never fixed.

**Comment by th3coop** [comment]
Sorry folks.  Miss-reading ticket descriptions.  I'm NOT closing this ticket.

**Comment by th3coop** [comment]
This is silly I missed this.  I've is easy (and done).  I will publish a nightly with the fix in it tomorrow, should be available after 12 PM PST.
If you don't hear back from me in this ticket look [here](http://downloads.activestate.com/Komodo/nightly/komodoide/) for a new nightly (current was release Feb 05, build #91854).  If you don't see a newer nightly after 12 PM (lunch) tomorrow, ping me here to publish.  

Fixed (private repo, dev ref only): 
 https://github.com/Komodo/codeintel/commit/318a83fb2572407652d7100bb828507d54d5e2b4

**Comment by th3coop** [comment]
Should be fixed in this build:
http://downloads.activestate.com/Komodo/nightly/komodoide/latest-12.0.x/

CC: @babobski

**Comment by babobski** [comment]
@th3coop this seems to be fixed in the latest.
