### ISSUE TITLE
Linux  error at startup

### ISSUE THREAD

**Issue by BigGreenFrog** [Komodo/KomodoEdit#372]
I trying to use Komodo-IDE-9.1.0-87337-linux-x86 w CentOS release 6.6 (Final).

install into /opt/Komodo-IDE-9
<pre>
[136]gamma{grieve} /opt/Komodo-IDE-9/bin/komodo
komodo: error: error creating '/home/grieve/.komodoide': File exists
komodo: error: could not determine the user data dir
[152]gamma{grieve} rm -Rf /home/grieve/.komodoide
[153]gamma{grieve} ls /home/grieve/.komodoide
ls: cannot access /home/grieve/.komodoide: No such file or directory
[154]gamma{grieve} /opt/Komodo-IDE-9/bin/komodo
komodo: error: error creating '/home/grieve/.komodoide': File exists
komodo: error: could not determine the user data dir

</pre>

I've not tried with a priviliged account ( root)

**Comment by cgchoffman** [comment]
This is likely config error.  Can you post this question in the forums first then if we determine there is bug you can reopen this report http://forum.komodoide.com/

Please include the steps you followed to install Komodo.

**Comment by BigGreenFrog** [comment]
I’m not sure what you mean “ post this question in the forums first”  — I thought 
i did.

NB in reference to below, I have selinux Disabled.

gamma-root-->tar -xvf Komodo-IDE-9.1.0-87337-linux-x86.tar
gamma-root-->cd Komodo-IDE-9.1.0-87337-linux-x86
gamma-root-->./install.sh 
Enter directory in which to install Komodo. Leave blank and
press 'Enter' to use the default [~/Komodo-IDE-9].
Install directory: /opt/xy

chcon: can't apply partial context to unlabeled file `/opt/xy/lib/mozilla/libfreebl3.so'
chcon: can't apply partial context to unlabeled file `/opt/xy/lib/mozilla/libfreebl3.so'
chcon: can't apply partial context to unlabeled file `/opt/xy/lib/mozilla/libfreebl3.so'
chcon: can't apply partial context to unlabeled file `/opt/xy/lib/mozilla/libfreebl3.so'
install: warning: could not set SELinux security context for '/opt/xy/lib/mozilla/libfreebl3.so': 'texrel_shlib_t', 'textrel_shlib_t', 'shlib_t', 's0' contexts failed (this can be safely ignored if you do not use SELinux on your system)

==============================================================================
Komodo IDE 9 has been successfully installed to:
    /opt/xy
    
You might want to add 'komodo' to your PATH by adding the 
install dir to you PATH. Bash users can add the following
to their ~/.bashrc file:

    export PATH="/opt/xy/bin:$PATH"

Or you could create a symbolic link to 'komodo', e.g.:

    ln -s "/opt/xy/bin/komodo" /usr/local/bin/komodo

Documentation is available in Komodo or on the web here:
    http://docs.activestate.com/komodo

Please send us any feedback you have through one of the
channels below:
    komodo-feedback@activestate.com
    irc://irc.mozilla.org/komodo
    https://github.com/Komodo/KomodoEdit/issues

Thank you for using Komodo.
==============================================================================



  



-- 
Gerry R. Grieve                                      ph: 604-822-4320
Systems Manager,                                fax:  604-822-5324
Physics&  Astronomy, UBC
6224 Agricultural Rd.
Vancouver, BC, Canada
V6T 1Z1

**Comment by cgchoffman** [comment]
Hi @BigGreenFrog, our github issues is for bug reports.  Our forums are found here: http://forum.komodoide.com/, the link I shared above.  We'll be glad to give you a hand figuring out what went wrong for you in the forums.  If we determine there is a bug then we'll get you to file an issue here.
