### ISSUE TITLE
Perl 'if' and 'while' statements disappearing 

### ISSUE THREAD

**Issue by LAHavens** [Komodo/KomodoEdit#3723]
### Short Summary

When coding, when I try to start and 'if' or 'while' statement, no matter what character I type following the 'if' or 'while', the 'if' or 'while' word disappears and my cursor goes down multiple lines. This doesn't happen with 'unless' or 'elsif'  statements or in my python codes.

### Steps to Reproduce

1.) Create perl script 
2.) Type an if() or while() loop

### Expected results

I would be able to type and keep and if or while loop

### Actual results

The 'if' and 'while' disappear

### Platform Information

Komodo Edit 11
Mac running Mojave Version 10.14.3

### Additional Information

*Added by Carey*
error:
In notification tab we get: `insertion of snipper 'if' suppressed: not t start of line` but that is a blatant lie.  i am indeed at the start of a line...and regardless, that shouldn't fail.  Nothing comes up in the logs.

**Comment by cgchoffman** [comment]
Sounds like some broken/maimed snippets in your toolbox maybe?  Try turning off *Edit >Preferences > Editor > Smart Editing > Auto-Abbreviations: disable*

**Comment by LAHavens** [comment]
That worked!! Thank you so much.

**Comment by cgchoffman** [comment]
No worries.  If you want to continue using WORKING auto abbrevs you can find the broken snippets in your toolbox > Abbreviations > Perl

**Comment by cgchoffman** [comment]
I'd be interested to know if they are default and broken in the release or if you had modified them.  I'd obviously want to fix them if it was the former :)

**Comment by LAHavens** [comment]
I didn't knowingly modify them on my end (but, honestly, anything is possible). I just downloaded the Mac version and noticed the disappearing act. I don't have this problem on my other computer. Should I reopen the issue?

**Comment by cgchoffman** [comment]
@LAHavens ya looks like there is a bug

**Comment by cgchoffman** [comment]
i've added some details to the original description. Thanks for the report @LAHavens .
