### ISSUE TITLE
Ruby ~= 2: Cannot change variables in debug session

### ISSUE THREAD

**Issue by th3coop** [Komodo/KomodoEdit#3724]
### Short Summary

I can't change a variable value in a paused debug session when debugging Ruby 2.3.  

### Steps to Reproduce

It's likely this can be reproduce with any version over 2.0 (I think that's when we switched to `byebug`)  but I was using 2.3.
Debug a Ruby script and break after a variable has been set.
Double click it in the Locals tab in the Debugger window
Try to set a new value

You get the error shown here: https://community.komodoide.com/t/komodo-alert-when-trying-to-change-value-of-a-variable/4603/2?u=careyh

Nothing in the logs.

**Comment by cgchoffman** [comment]
Have added a handler for `-k` in the `property_set` handler in the rb2dbgp.rb file  but now it's failing silently for some reason.  I'm assuming *byebug* doesn't know what `-k` is supposed to mean...maybe byebug dumps logs somewhere.

**Comment by cgchoffman** [comment]
This will be in tomorrows nightly.
