### ISSUE TITLE
Select Server dropdown in Places SideBar

### ISSUE THREAD

**Issue by mjbrancato** [Komodo/KomodoEdit#373]
It would be nice to have a drop down to select which server to work on in the FTP section of places. Often there are times we are working on hundreds of projects so there needs to be a way to access these servers conveniently.

Please see screenshot/mockup for idea: http://dl.dropbox.com/u/23057021/Selection_026.png

Thanks,
Mike

**Comment by cgchoffman** [comment]
Thanks for filing this @mjbrancato.  Putting in the backlog for now as i'm not sure where we would fit this into our dev cycle yet.  As an initial implementation, this would totally be doable as a macro.

**Comment by mjbrancato** [comment]
I don't know if this feature is needed anymore since there is a specific way to use Komodo IDE and I am using it that way and I already am beyond adapted to it.

You can close this as you feel necessary.

**Comment by Naatan** [comment]
Thanks @mjbrancato. Frankly it is unlikely this would be prioritised, so I will go ahead and close it.

**Comment by mjbrancato** [comment]
Thank you, that works for me. It would be unlikely that I would use this feature anymore. This was back in the beginning days coming from Dreamweaver. Your way is so much better because I can work on multiple projects at once without closing everything (Places and Projects).
