### ISSUE TITLE
Komodo Tab Browser: Incremental Search command produces "scintilla is undefined" error

### ISSUE THREAD

**Issue by ervumlens** [Komodo/KomodoEdit#374]
*Problem* 
The Komodo tab browser produces an error when the incremental search command is performed on it. This occurs with Markdown Preview as well as Preview Buffer in Browser.

*Steps to Reproduce* 
1) Open Komodo Edit 9.1.0
2) Open a Markdown file or HTML file
3) Run `Preview Markdown` or `Preview Buffer in Browser`, using the built-in tab browser.
4) Click on the browser pane to focus on it.
5) Run the incremental search command (e.g., `Ctrl+F`)

*Expected* 
I was hoping for a search dialog for the browser, but was expecting no errors.

*Actual* 
An error in the Notifications tab and the following error in the log:

```
[2015-06-27 15:39:07,217] [ERROR] commands: An error occurred executing the cmd_startIncrementalSearch command
-- EXCEPTION START --
[Exception... "[JavaScript Error: "scintilla is undefined" {file: "chrome://komodo/content/library/findController.js" line: 358}]'[JavaScript Error: "scintilla is undefined" {file: "chrome://komodo/content/library/findController.js" line: 358}]' when calling method: [nsIController::doCommand]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 263"  data: yes]
+ QueryInterface (function) 3 lines
+ message (string) '[JavaScript Error: "scintilla is undefined" {file: "chrome://komodo/content/library/findController.j'...278 chars
+ result (number) 2153185313
+ name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
+ filename (string) 'chrome://komodo/content/library/commands.js'
+ lineNumber (number) 263
+ columnNumber (number) 0
+ location (object) JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 263
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/library/commands.js'
| + name (string) 'command_doCommand'
| + lineNumber (number) 263
| + columnNumber (number) 0
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/library/commands.js :: command_doCommandAsync :: line 215
| + formattedStack (string) 'command_doCommand@chrome://komodo/content/library/commands.js:263:0
command_doCommandAsync@chrome://'...476 chars
| + inner (object) null
| + data (object) [xpconnect wrapped nsISupports]
| + QueryInterface (function) 3 lines
| + initialize (function) 3 lines
-- EXCEPTION END --
```

Komodo version: Komodo Edit 9.1.0 build 15798 (platform linux-x86_64, running on Linux 3.13.0-37-generic version 64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014)

**Comment by Naatan** [comment]
The error being logged should definitely be resolved. As for the expected result, well your focus is not on the editor, but on the preview. For you to perform actions on the editor you need to put focus on the editor. Since this is a browser preview you are putting your focus on it would not make sense to try and forward those keypresses as the browser preview may itself hold content that relies on those keypresses (either from Komodo or from the end-user).

**Comment by ervumlens** [comment]
Thanks, @Naatan .

> your focus is not on the editor, but on the preview. For you to perform actions on the editor you need to put focus on the editor...

When I posted this issue, I was more intent on describing the error than on describing my use-case, so I apologize for the confusion. 

To clarify: I was looking for some text in a third-party Markdown file, but I didn't want to try reading the raw Markdown itself. I opened up the Markdown preview, but didn't want to scroll around looking for the text, either. (Yes, there is a pattern of laziness here :grin:) At that point, I was done with the editor and just as well could have closed it. I wanted to see the HTML-ified Markdown. I thought I'd see if the browser's own Find dialog was available, since that would really be the only way to get me down to the HTML I wanted to see. When I pressed `ctrl+F`, though, I just got the error. I would have been happy to see Firefox's own search thing pop-up, or even a crude unstyled textbox.

**Comment by Naatan** [comment]
That's fair :) Atm our browser preview is very basic, I'd agree that it ought to support stuff like Ctrl+F. That's an enhancement request though, and should be tracked separately.

Realistically, it's not likely to make our roadmap very soon, but if there is enough interest that might change.
