### ISSUE TITLE
CoffeeScript: pressing return after certain arrays incorrectly auto-indents next line

### ISSUE THREAD

**Issue by ervumlens** [Komodo/KomodoEdit#375]
*Problem* 
In CoffeeScript, pressing return after ending an array sometimes wrongly auto-indents the next line.

*Example Code*

```coffeescript
x = []		#pressing return...
	console.error 'Doh! Auto-indented line.'

x = [1,2,3]	
	console.error 'Doh! Auto-indented line.'

x = [ 		#pressing return...
	'indent looks good here...'
]			#pressing return...
	console.error '...Doh! Auto-indented here.'

x[0] = []
	console.error 'Doh!'

x = [].length
	console.error 'Argh!'

#These are all fine...
x[0] = 0
x = x[0]
x = x([])
x = x []
```

This problem occurs with and without the soft-character setting enabled.

Komodo version: Komodo Edit 9.1.0 build 15798 (platform linux-x86_64, running on Linux 3.13.0-37-generic version 64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014)

**Comment by Naatan** [comment]
Reproduced, thanks!
