### ISSUE TITLE
Komodo edit v11.1.1, project files with %20 instead of blank

### ISSUE THREAD

**Issue by alfredrajo** [Komodo/KomodoEdit#3766]
### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?*

**Comment by alfredrajo** [comment]
when drag and drop project filenames from the Tabs to the project name, the filename will be inserted, but with %20 instead of blank " ", when Blanks in pathnames. Then opening the project file will result in error message: does not exist

**Comment by th3coop** [comment]
@alfredrajo I'm not able to reproduce an issue here.  Could you please update the original ticket properly by clicking `...` and Edit to add reproduction steps or a video or gif that illustrates the issue?

I opened a file that had a space in it's name and in it's path.  I dragged the files tab to my open project.  The name of the file shows correctly and there was no issue opening the file.

**Comment by th3coop** [comment]
I'll reopen if you're able to add repro steps
