### ISSUE TITLE
res_index not written to disk for 5 minutes

### ISSUE THREAD

**Issue by ssigwart** [Komodo/KomodoEdit#3768]
### Short Summary
`res_index` not written for at least 5 minutes causing CodeIntel directory rescans.

### Steps to Reproduce
- Clear CodeIntel database.
- Open a project and then trigger a completion (e.g. `$this->` in a PHP class).
- Close Komodo within 5 minutes.
- Open Komodo and project.
- Trigger a completion (e.g. `$this->` in a PHP class).

### Expected results
- CodeIntel only rescans directories on first time.

### Actual results
- Directories are scanned both times.

### Platform Information
Komodo Edit
Custom build
MacOS Mojave

### Additional Information
The issue is that this line returns can't find the `res_index` file:
https://github.com/Komodo/KomodoEdit/blob/99b37b1c7eef04d6a918b7f3f1db74adf19c80a6/src/codeintel/lib/codeintel2/database/langlibbase.py#L84

That's because `res_index` isn't written to disk until 5 minutes after it's last access:
https://github.com/Komodo/KomodoEdit/blob/99b37b1c7eef04d6a918b7f3f1db74adf19c80a6/src/codeintel/lib/codeintel2/database/langlib.py#L1400

In #3664, I had updated the code to write dirty indexes to disk even if accessed, but removed it due to https://github.com/Komodo/KomodoEdit/pull/3664#discussion_r251471147

I wonder if it would be ok to update the code to at least write `res_index` to disk even if it's been accessed.

The other issue is that `cull_mem` is only scheduled for 5 minutes after an event, so it could be an issue if you close Komodo quickly, but that might not be worthy of fixing.
https://github.com/Komodo/KomodoEdit/blob/99b37b1c7eef04d6a918b7f3f1db74adf19c80a6/src/codeintel/lib/codeintel2/indexer.py#L660

**Comment by th3coop** [comment]
> The other issue is that `cull_mem` is only scheduled for 5 minutes after an event

Does this mean a memory leak that remains after Komodo stops?

> I had updated the code to write dirty indexes to disk even if accessed, but removed it due

I wonder if this can be done (and maybe the memory cull) in oop-driver.py when Komodo is shutdown:
https://github.com/ssigwart/KomodoEdit/blob/master/src/codeintel/bin/oop-driver.py#L191

It would likely require a new function in each case that can be called from there that will have enough context to perform the cull or index save.

**Comment by ssigwart** [comment]
> Does this mean a memory leak that remains after Komodo stops?

I don't think so.  It just never gets saved.

> I wonder if this can be done (and maybe the memory cull) in oop-driver.py when Komodo is shutdown:
https://github.com/ssigwart/KomodoEdit/blob/master/src/codeintel/bin/oop-driver.py#L191
>
> It would likely require a new function in each case that can be called from there that will have enough context to perform the cull or index save.

I'm not sure.  I don't have enough knowledge of that file.  Does only one copy of `oop-driver.py` run in the background when Komodo starts and then get killed when Komodo is closed?  If so, then that's probably a good starting point.

**Comment by th3coop** [comment]
I'm not having any luck digging through this code to find out how (or even if) oop-drive.py is called to start things.  Lets' try your suggestions, put them in a nightly and see if things get noticeably worse.
