### ISSUE TITLE
Buffers are cached forever in driver.py

### ISSUE THREAD

**Issue by ssigwart** [Komodo/KomodoEdit#3769]
### Summary
https://github.com/Komodo/KomodoEdit/blob/99b37b1c7eef04d6a918b7f3f1db74adf19c80a6/src/codeintel/lib/codeintel2/oop/driver.py#L337
Whenever `get_buffer` is called, it stores the buffer in `self.buffers[path]`.  However, it never seems to clean up the cached buffers.  I wonder if this is the reason Komodo gets slow after a few hours of usage.

## Possible Updates
My initial thought is to clear the cache when a file is closed.  I'm not sure how to get that information to the driver class though.

### Platform Information

Komodo Edit
GitHub master

**Comment by th3coop** [comment]
I think we'll be limited to a time out for this.  The only alternative I see would be implementing a `CloseHandler` in  Driver and send  `closed` requests to the process from Komodo which seems like way more of a pain than just aging out entries.

**Comment by ssigwart** [comment]
I'm good with just adding a 5 minute timeout period or something like that.  Maybe add a way to manually trigger it to flush it from the console (I assume that's probably possible to build).

An alternative might also be to only keep the last 2 or 3 files.  I've already forgotten how often `get_buffer` is called, but I think it might only need the currently open file most of the time.
