### ISSUE TITLE
Unable to click on "Environment Prefs" button in Preferences  

### ISSUE THREAD

**Issue by victorhooi** [Komodo/KomodoEdit#377]
I've just downloaded Komodo 9 IDE (`Komodo IDE, version 9.0.1, build 87208, platform macosx. Built on Thu Apr 16 13:18:49 2015.`), and I'm trying to set it up for using with Go.

I've put in the paths for `go` and `gocode`, however, when I try to click on the *Environment Prefs* button, nothing happens - it literally does nothing:

![screenshot 2015-06-28 09 57 26](https://cloud.githubusercontent.com/assets/243499/8394458/48596906-1d7c-11e5-9c43-9de5cd4e85fd.png)

This is on OSX 10.11 (DP2).

Is there another way of setting the environment preferences correctly, or getting Go working on Komodo?

**Comment by ervumlens** [comment]
Reproduced in Linux.

This happens when the "Show Advanced" checkbox (in the lower left of the Preferences window you're looking at) is unchecked. Check the box and the button works.

It looks like it's trying to switch you to an advanced preference page without checking to see if the page is actually showing.

**Comment by Defman21** [comment]
There are two ways how to fix that: do not display this button if "Show Advanced" isn't checked or always display Environment tab. Which is better?
Or Komodo could enable Advanced view if the user clicked on this button...

**Comment by ervumlens** [comment]
> There are two ways how to fix that: do not display this button if "Show Advanced" isn't checked or always display Environment tab. Which is better?
Or Komodo could enable Advanced view if the user clicked on this button...

I don't think it's correct to show and hide the Go page's "Environment Prefs" button. The page claims that `GOPATH` needs to be set to use Go, and Komodo should facilitate setting that even when "Show Advanced" is disabled. (Your commits don't code this option so I figure we generally agree here.)

I'm a little leery of enabling the advanced view as a side effect of clicking the "Environment Prefs" button, for similar reasons. If changing the environment is a basic need for configuring Go, then it seems odd to jump to an advanced page. But given the narrow scope of the problem, this is a minor quibble. It's easy enough to move the environment page to the non-advanced list when there is a more serious case for doing so. 

Ideally, the Go preference page would not depend on another preference page for a necessary setting. Maybe a simple textbox could be added here to view/change the `GOPATH` value.
