### ISSUE TITLE
I can no longer select text in the editor using the mouse.

### ISSUE THREAD

**Issue by isleofwighter** [Komodo/KomodoEdit#3778]
Suddenly I can no longer select text using the mouse cursor, individual bits of text on one or multiple lines. Have uninstalled and reinstalled but still the same.Worked fine yesterday (9th Aug 2019. Have tried on different projects and file. same result. Mike

**Comment by th3coop** [comment]
@isleofwighter, Please fill in as many of the template fields as possible.  There isn't enough information to work with here.

**Comment by isleofwighter** [comment]
Hi

Why it ceased working I have no idea but after a third re-installation it started working again. I can see no reason why the program should be the cause or what else in the setup of the machine, but now it works again.

Worked in IT for 30 years before I retired and have experienced stranger things. So I may never know.

Thanks

Mike

**Comment by th3coop** [comment]
Thanks for letting me know @isleofwighter.  If it comes up again grab your logs(**Help > troubleshooting > View log file**) and let me know which platform and version of Komodo you're on.  I'm going to close this for now.
