### ISSUE TITLE
Activestate popup window is impossible to get rid of.

### ISSUE THREAD

**Issue by FullPrice123** [Komodo/KomodoEdit#3783]
Opening the app constantly results in a popup window prompting me to update to the "latest version of komodo ide" even though I am on the current version. I have tried using this link as well as the one on the website and no matter what it still pops up. There are no options to configure or dismiss this page. 

All you have to do is open the app and it pops up every time

I expect the app to not annoy me whenever I am trying to open it

The app berates me every time I open it

Komodo IDE
V 11.1.1
macOS Catalina Beta

**Comment by th3coop** [comment]
@FullPrice123 Click "not interested" and it should stop.

**Comment by FullPrice123** [comment]
> @FullPrice123 Click "not interested" and it should stop.

<img width="1280" alt="Screen Shot 2019-08-20 at 5 38 04 PM" src="https://user-images.githubusercontent.com/25888275/63386537-523d9880-c371-11e9-8e16-62f9f6ff8b92.png">

Unfortunately, I have no such option.

**Comment by th3coop** [comment]
OH fun!  Please check your system prefs and reduce your font size then open Komodo again.  That dialog must not be able to handle the expanded text size when it comes to it's dimensions.  It looks like it's pushing the bottom of the dialog off your screen.

**Comment by th3coop** [comment]
You can revert the text size change in your system prefs after.  The rest of Komodo should function normally.

**Comment by FullPrice123** [comment]
Wow! That worked perfectly! Thanks so much!
