### ISSUE TITLE
Select line on line num click not working.

### ISSUE THREAD

**Issue by th3coop** [Komodo/KomodoEdit#3786]
### Short Summary

I even remember Todd showing me this when I started here and it's in the docs.

### Steps to Reproduce

Click the line number in a file

### Expected results

Line is selected

### Actual results

Breakpoint is created

**Comment by th3coop** [comment]
PR up https://github.com/Komodo/KomodoIDE/pull/172

**Comment by th3coop** [comment]
Fixed

**Comment by dbotham** [comment]
How did a complaint about not be able to "select lines" turn into fix for "Select line"?  

Here, the plural sense of the word is actually important.  Any chance we can add the 's' back onto lines?
