### ISSUE TITLE
"Go" Language preference page has problems with dark window theme

### ISSUE THREAD

**Issue by ervumlens** [Komodo/KomodoEdit#379]
*Problem*
My window theme has a very dark background with a nearly white default font. The preference page for Go does not honor the theme in a couple of places.

> Komodo Edit 9.1.0 build 15798 (platform linux-x86_64, running on Linux 3.13.0-37-generic version 64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014)

*Steps to Reproduce*
1. Switch to a dark window theme. I'm using `Xfce-dusk`, which comes with Xfce4.
2. Open Komodo Edit.
3. Open Preferences. 
4. Open the Go language preference page.

*Expected*
The golang.org link is readable.
The Environment Prefs button is readable.

*Actual*
The link and button are not readable. Screenshot!

![go preferences - dark](https://cloud.githubusercontent.com/assets/13005338/8399092/ce7ec036-1dcb-11e5-9b43-643fb5fe8d69.png)

With a light theme it's fine: 

![go preferences - light](https://cloud.githubusercontent.com/assets/13005338/8399309/0a04ece8-1dd1-11e5-9da6-a006f8060082.png)

**Comment by ervumlens** [comment]
Same problem on the PHP preferences page:

![image](https://cloud.githubusercontent.com/assets/13005338/8513211/0dbfa566-2327-11e5-9b61-01557bd06e79.png)

**Comment by Naatan** [comment]
Yeah, the problem is the button, which is horribly styled even on a light theme. Straight out of the 90s.
