### ISSUE TITLE
Packages stuck for a long while

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3790]
## Short Summary
The packages page:

https://community.komodoide.com/packages/

Is stuck for a long while.

Edit (Carey): The code for this lives here: https://github.com/Komodo/komodo-website

**Comment by th3coop** [comment]
It's not slow for me @babobski, is it still hanging for you?

**Comment by babobski** [comment]
I meant, it is not updating the packages info anymore. 
It says I updated Komodo Git yesterday. But "yesterday" was 28 of may.

**Comment by th3coop** [comment]
@babobski key details to leave out! heh.  Thanks for clarifying.  

Very weird, but thankfully it's not preventing people from getting the packages.  I have quite a few things that will take priority over this.  @babobski, if you or anyone else is interested, the Komodo Website code and this packages code is a public repo if you want to have a look and see what might be up.  https://github.com/Komodo/komodo-website

It might be the servers clock though, who knows.

**Comment by th3coop** [comment]
Token used to pull in the updates had expired.  Updated and fixed.

**Comment by babobski** [comment]
Nice, Thanks!
