### ISSUE TITLE
TopView state isn't saving properly, wrong files opened after crash/forced quit

### ISSUE THREAD

**Issue by th3coop** [Komodo/KomodoEdit#3791]
### Short Summary

I'm not 100% on repro steps for this other than it involves a forced quit/manually kill the process or a crash.  Either the open view state isn't being saved when the rest of the window state gets saved or Komodo recovery code is loading the saved state from somewhere else.  I'm pretty sure it's the latter.

### Steps to Reproduce

Force quit Komodo however your platform supports that
Restart Komodo

### Expected results

Should open with all the files you had open before the crash

### Actual results

Some long gone state is loaded.

**Comment by ssigwart** [comment]
MacOS Catalina seems to have broken my setup and I can't get it running again.  But I think you are referring to the list of open files being restored to the set of files open at the last normal quit, not the crash.  It looks like `saveWorkspaceIfNeeded` and `ko.workspace.saveWorkspace` might be what saves the files.  However, that's only called when the app is quit or when you do a Save All.  What do you think of adding a call to `ko.workspace.saveWorkspace` each time a file is opened or closed?

P.S. Any ideas how to fix this?
```
bk run
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
Obtaining the module object from Python failed.

Traceback (most recent call last):
  File "/Users/ssigwart/Documents/Programming/KomodoEdit/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/Komodo.app/Contents/MacOS/python/xpcom/server/__init__.py", line 40, in <module>
    from policy import DefaultPolicy
  File "/Users/ssigwart/Documents/Programming/KomodoEdit/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/Komodo.app/Contents/MacOS/python/xpcom/server/policy.py", line 39, in <module>
    from xpcom import xpcom_consts, _xpcom, client, nsError
<type 'exceptions.SystemError'>: dynamic module not initialized properly
Creating an interface object to be used as a result failed
```

**Comment by th3coop** [comment]
Make sure catalina didn't overwrite your Xcode dir and remove the platform SDKs Komodo needs.  It happens everytime.



> What do you think of adding a call to `ko.workspace.saveWorkspace` each time a file is opened or closed

Honestly, I thought this was already occurring though not the entire workspace.  My names all over that code but I guess it's been a while since I looked at it.

Looked at the code.  Yeah that should be just fine.  We `debounce` the save function so even if you open 10 files at once, the function will only run once.  To centralize things, add an eventListener with a `onFileOpenHandler` in workspace.p.js.  I think that should work.

**Comment by th3coop** [comment]
Left the event name out: `view_opened`.  Should probably save on file close too: `view_closed`

**Comment by ssigwart** [comment]
> Make sure catalina didn't overwrite your Xcode dir and remove the platform SDKs Komodo needs. It happens everytime.

Yeah, I caught that issue.  It seems to be something else.  I think the *dynamic module not initialized properly* part is the key.  If I can figure it out, I'll work on this issue.

**Comment by th3coop** [comment]
@ssigwart, your regular Komodo install runs though?  ie. /Application/Komodo...?  I hate to say it, you might need to rebuild Mozilla though I can't imagine WHY this would occur other than #OSXUPDATES.

Oh maybe, did your system Python get upgraded?  I heard OSX was removing Python.  Maybe you're not using the Python that you think you're using.

**Comment by ssigwart** [comment]
Yeah, the regular nightly runs.  I've actually tried rebuilding Mozilla at least 4 times now.  I'm pretty sure when I upgraded MacOS, python did too.  I actually have both python 2.7.16 and 3.7.4 installed with brew.  I tried `bk run` with the system python and brew versions.  They both failed with the same error.  I even tried python 3, but it was clear `bk` isn't intended to run with that.

**Comment by ssigwart** [comment]
Several rebuilds later and still no luck.

Looking at the code more, I now see that `views.p.js` calls `ko.workspace.saveWorkspaceDeferred` in `handle_view_opened` and `handle_view_closed`.  I assume based on the `if` conditions, that that is being run.  That then sets a timeout for `saveWorkspace` to be called.  However, that doesn't set `saveNow`, which means `saveWhenIdle` is used.  I wonder if it's never idle long enough.  Really wish I could debug.

**Comment by th3coop** [comment]
> which means `saveWhenIdle` is used

Right,  this has nipped me in the butt a few times now.  That might require a `saveNow`.

**Comment by ssigwart** [comment]
Thanks for looking into that.  I've always had the `[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0` error, but it used to work fine anyway.  I think it's something with Python and imports.

**Comment by th3coop** [comment]
@ssigwart, I'm stumped here.  My best guess is `/Users/ssigwart/Documents/Programming/KomodoEdit/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/Komodo.app/Contents/MacOS/python/xpcom/_xpcom.pyd` is bunged up somehow.  When you rebuilt Mozilla did you use `python build.py distclean all`?  or just `python build.py all`?

**Comment by ssigwart** [comment]
I ran them separately:
```bash
python build.py distclean
python build.py all
```

I don't see any `.pyd` files (it looks like that might be Windows only).  I tried this to wipe out any compiled code, but to no avail:
```bash
find . -name '*.pyc' -print0 | xargs -0 rm
find . -name '*.pyo' -print0 | xargs -0 rm
```

I was wondering if it's a `.dylib` issue.
```
Binary files /Applications/Komodo Edit 11.app/Contents/MacOS/libpyxpcom.dylib and /Users/ssigwart/Documents/Programming/KomodoEdit/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/Komodo.app/Contents/MacOS/libpyxpcom.dylib differ
```
I'm trying to figure out how those are created.  Or maybe I'll just rsync all the `.dylib` files from the nightly to it and see what happens.

**Comment by th3coop** [comment]
Build conversation moved to forums: https://community.komodoide.com/t/macos-catalina-build-issues/4787

**Comment by ssigwart** [comment]
For the view state:
1.  It looks like the code was never setting up the "idle" observer.  I added that.
2.  It's still using the `saveWhenIdle` method, so it will still wait a little.
3.  The project state was only saved when closed, so I added code to save that when the workspace view state is saved.

**Comment by th3coop** [comment]
I think 3 fixed the issue.  See my comment in the PR.
