### ISSUE TITLE
Error In Komodo Lock 183

### ISSUE THREAD

**Issue by wilecoyte78** [Komodo/KomodoEdit#3798]
### Short Summary

Unexpected result acquiring commandments lock: 183

### Steps to Reproduce

Right click file hover over open with and click ActiveState Komodo

### Expected results

Open file in Komodo Edit

### Actual results

Unexpected result acquiring commandments lock: 183

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 11.1.2 build 91158
*Operating System (and version)?* Window 10 64

**Comment by th3coop** [comment]
Looking.  Just to confirm, the *Expect Results* is a typo, correct?

**Comment by wilecoyte78** [comment]
I am not quite understanding your question.

The Expected Results is what I expected the file to do after I right clicked the file and hovered over open with and clicked ActiveState Komodo. I expected the file to open in Komodo but I got the error instead. It happens with any file I try to open this way. I can open files while in Komodo using the file menu in Komodo.

**Comment by th3coop** [comment]
@wilecoyte78 you said `Open file in Komodo Edit` but you're running Komodo IDE.  Is that a typo or do you expect Komodo Edit to open.  They are two different code bases for me to look for the bug in.

**Comment by wilecoyte78** [comment]
Sorry everything is Komodo IDE. http://x-v.it/hzd63h

**Comment by th3coop** [comment]
@wilecoyte78 thanks for confirming and thanks for reporting.

**Comment by th3coop** [comment]
@wilecoyte78 I can't reproduce this.  I just installed the nightly, setup the Windows Config prefs, then tried "Edit with Komodo IDE" with komodo already running and with it stopped.  The file opens without issue in both cases.  

Can you provide more info?  Where are you seeing the error your shared?  Is there more output?  Is it possible there is another Komodo instance running in a half shutdown state?  Have a look in task manager or see  if `running.lock` and/or `startup-env.tmp` exist in your user profile: *%LOCALAPPDATA%\ActiveState\KomodoIDE\11.1\*

Could also try reapplying the Windows Config setting in case those have been corrupted in someway.

**Comment by wilecoyte78** [comment]
I have no idea what the issue was I restarted my computer and it is now working as expected. This error only happened after I upgraded Komodo IDE without restarting.

**Comment by th3coop** [comment]
OK, thanks for reporting back.  Sounds like I don't need to pounce on this then.
