### ISSUE TITLE
"Find" dialog's "pattern not found" message is mostly invisible with dark window theme

### ISSUE THREAD

**Issue by ervumlens** [Komodo/KomodoEdit#380]
*Problem*
Similar to #379. The Find dialog has an info line that is hard to read when the window theme uses a nearly white font. I'm using Linux with window theme `Xfce-dusk`.

> Komodo Edit 9.1.0 build 15798 (platform linux-x86_64, running on Linux 3.13.0-37-generic version 64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014)

*Steps to Reproduce*
1. Open Komodo Edit.
2. Open a file.
3. Open the Find dialog.
4. Search for something that isn't in the file.
 
*Expected*
The dialog issues a message that says the search text could not be found.

*Actual*
The dialog issues the message, but I have to tilt my monitor to read it. Behold:

![image](https://cloud.githubusercontent.com/assets/13005338/8399167/647268c6-1dcd-11e5-9f5c-bf2c72d7d703.png)

I don't know for a fact, but the orangey-yellow might be coming from [here](https://github.com/Komodo/KomodoEdit/blob/master/src/chrome/komodo/content/find/find2.p.xul#L403-L429)

**Comment by Defman21** [comment]
This message should looks fine If the color will be defined to `#303030` (or similar) in the lines from your link.

**Comment by Naatan** [comment]
This is resolved in 9.3 due to the find dialog overhaul.
