### ISSUE TITLE
Feature Request: Read and Write to Google Docs

### ISSUE THREAD

**Issue by milanlakhani** [Komodo/KomodoEdit#3803]
### Short Summary

I'm not sure how feasible this is but if at all possible it would be great to have integration with Google Docs so I can read and write to my Google Docs from my text editor!

### Expected results

Connect with Google Drive account and read and write to Google Docs

### Actual results

No Google Drive integration yet

### Platform Information

Komodo Edit
Operating System Linux

**Comment by th3coop** [comment]
This isn't use case we would accommodate for a few reasons:
1. There are existing tools to have your Google drive sync'd locally so you could interact with them in that manner.
2. This is not a use case that most people using Komodo would need.  Storing source code is not what Googled drive is meant for.
3. Given the above two, the work to benefit ratio is way off.

Apologies to just close this but it wouldn't be something we would ever prioritize.
