### ISSUE TITLE
html code intel suggestions don't work

### ISSUE THREAD

**Issue by th3coop** [Komodo/KomodoEdit#3808]
### Short Summary

Still works in 11.1.1.  Doesn't work in the latest.  Commits since: https://github.com/Komodo/codeintel/commits/master

NOTE: on first start up tag completions may appear but they will stop working after the first completion.

### Steps to Reproduce

From 11.1.1:
![html-completions](https://user-images.githubusercontent.com/655154/70949649-30001280-2013-11ea-83cd-fe7b573594a7.GIF)

Tag and attr suggestions don't work in latest

**Comment by ssigwart** [comment]
Is this IDE only?

**Comment by th3coop** [comment]
@ssigwart correct

**Comment by th3coop** [comment]
Cannot reproduce anymore.  Not sure why it wasn't working for me at the time but no one seems to be able to reproduce the issue any more.
