### ISSUE TITLE
css languages (including less and scss) don't autocomplete after ;

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3812]
### Short Summary
I'm taking V12 for a test drive, but this issue still exist in css type languages.
It is working for css files, but in less or scss files I get the unwanted behavior.

*scss*
![afbeelding](https://user-images.githubusercontent.com/3530262/71308589-c743dc00-23fe-11ea-92bf-60cc121d4984.png)

*less*
![afbeelding](https://user-images.githubusercontent.com/3530262/71308596-f4908a00-23fe-11ea-8dee-3fa894b05c07.png)

### Platform Information

Komodo IDE 12.0.0 build 91814 (platform win32-x86, running on Windows post2012Server version 6.3.9600)

**Comment by th3coop** [comment]
@babobski can you link the ticket you're referencing?

**Comment by babobski** [comment]
#3297

**Comment by th3coop** [comment]
@babobski so the patch I did never fixed this for you?  I assume you've been using the nighlies of 11?

**Comment by babobski** [comment]
No sorry, there are still to many issues that I'm still on 10.2.3.
There where too many bugs in js and css like languages, that it would intervene with my workflow to much.

**Comment by th3coop** [comment]
@babobski ahh that's unfortunately.  It would have been helpful if you had reported back on the original ticket so we knew it wasn't fixed.  I'll re-open that one, link and close this one.

**Comment by babobski** [comment]
@th3coop I know, but there where various tickets arround this issue. It's fixed i css but not in the other languages (less, scss)

**Comment by th3coop** [comment]
@babobski, BAH. I read this ticket wrong apparently :(  Sorry for the noise.  Keeping this ticket closed for https://github.com/Komodo/KomodoEdit/issues/3716
