### ISSUE TITLE
Komodo complains about being unable to find go/gocode/godef, but they are on the path

### ISSUE THREAD

**Issue by victorhooi** [Komodo/KomodoEdit#382]
I have installed Komodo 9.0.1 (`Komodo IDE, version 9.0.1, build 87208, platform macosx`) on OSX 10.11.

I have also installed Go 1.4.2 via Homebrew:
```
victorhooi@thadeus ~> go version
go version go1.4.2 darwin/amd64
```

In Komodo, I have configured the Default Go Locations to use the path. However, for some reason, Komodo keeps complaining about being unable to find the binaries:

![screenshot 2015-06-29 17 27 48](https://cloud.githubusercontent.com/assets/243499/8403081/bf141434-1e84-11e5-8654-277386cd65ef.png)
![screenshot 2015-06-29 17 27 36](https://cloud.githubusercontent.com/assets/243499/8403083/c13bc9b4-1e84-11e5-88b9-b5daf713f1d5.png)

However, I've confirmed that both `go` and `gocode` are in my path.

```
victorhooi@thadeus ~> which go
/usr/local/bin/go
```
```
victorhooi@thadeus ~> which gocode
/Users/victorhooi/code/gocode/bin/gocode
```

Any thoughts on how to get Komodo working correctly as a Go development environment on OSX?

**Comment by Naatan** [comment]
Please update to Komodo 9.1
