### ISSUE TITLE
Windows state tool install fails: 

### ISSUE THREAD

**Issue by th3coop** [Komodo/KomodoEdit#3826]
### Short Summary

Ref: https://community.komodoide.com/t/saving-private-key-failed-with-the-system-cannot-find-the-path-specified/4859/9

I've not been able to reproduce this but if anyone comes across this and can add more data please do.  

- In a Windows VM I confirmed that I CANNOT run scripts in Powershell.  
- Deleted already installed state tool, Komodo profile.  
- Komodo starts up no problem, logs in, and everything seems to work.  

#### Workaround

Manually install the state tool: http://docs.activestate.com/platform/state/

Error:
```
tool.js: Stderr while running state tool installer: File C:\Users\Me\AppData\Local\Temp\6767a500-958d-4f72-a3a5-a90705d55098install.ps1 cannot be loaded because 

[2020-01-16 16:40:21,802] [WARNING] tool.js: Stderr while running state tool installer: running scripts is disabled on this system. For more information, see about_Execution_Policies at 
https:/go.microsoft.com/fwlink/?LinkID=135170.
    + CategoryInfo          : SecurityError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

**Comment by th3coop** [comment]
Had someone try to reproduce this internally and it's just not panning out.  If someone comes across this you can add details and we might re-open.

**Comment by mjross** [comment]
I recently installed version 12.0.1, and every time I start up Komodo IDE, in the lower right-hand corner there is a yellow pop-up that indicates "State tool install failed". If I can help in any way in trying to track down what's happening, please let me know.

![Clipboard01](https://user-images.githubusercontent.com/829492/112070761-fbdba180-8b33-11eb-9205-a9ce763743a7.jpg)

**Comment by th3coop** [comment]
Hey @mjross if you could share your logs that could be helpful.

**Comment by mjross** [comment]
@th3coop: Here we are...

[pystderr.log.txt](https://github.com/Komodo/KomodoEdit/files/6213929/pystderr.log.txt)

**Comment by Patrick5** [comment]
"State tool install failed" still an issue?    (June 25, 2021)
This is my first experience with Komodo.  I downloaded the installer "Komodo-IDE-12.0.1-91869.msi" and ran it. When the installer completed, it opened Komodo. 
In the notifications window I found the message:
>  State tool install failed. Please contact ActiveState support or review your logs.

Upon reviewing the logs (attached) I found the following in pystderr.log:
> [2021-06-26 02:14:29,897] [WARNING] tool.js: Stderr while running state tool installer: At C:\Users\Patrick\AppData\Local\Temp\04dd1a13-7200-4934-8e0c-a3b4ab471b31install.ps1:390 char:37
> \+     $ConfigDir = Invoke-Expression "& $Command" | Out-String
> \+                                     ~
> The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it 
> as part of a string.
> At C:\Users\Patrick\AppData\Local\Temp\04dd1a13-7200-4934-8e0c-a3b4ab471b31install.ps1:444 char:1
> \+ }
> \+ ~
> Unexpected token '}' in expression or statement.
>     \+ CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
>     \+ FullyQualifiedErrorId : AmpersandNotAllowed

And sure enough, at line 390 in the file 04dd1a13-7200-4934-8e0c-a3b4ab471b31install.ps1 I found the line 
>     $ConfigDir = Invoke-Expression "& $Command" | Out-String

Searching online led to this forum, and hence my first post.  Perhaps he installation process needs some touching up (??). 

[pystderr.log](https://github.com/Komodo/KomodoEdit/files/6720686/pystderr.log)

[04dd1a13-7200-4934-8e0c-a3b4ab471b31install.ps1.txt](https://github.com/Komodo/KomodoEdit/files/6720687/04dd1a13-7200-4934-8e0c-a3b4ab471b31install.ps1.txt)

**Comment by th3coop** [comment]
Morning @Patrick5, thanks for the report.  The workaround, if you want to use the state tool features, is to manually run the install script: https://docs.activestate.com/platform/state/install/#installing-on-windows.
