### ISSUE TITLE
Don't Correct Work JS Beautify

### ISSUE THREAD

**Issue by Nemial** [Komodo/KomodoEdit#3827]
### Platform Information

*Komodo IDE
*Komodo Version 12.0.0

The standard JS Beautify formatter does not work correctly. It does not recognize JavaScript arrow functions, function = () => {} and corrects them to function = () = > {}, which naturally causes the function to fail.

**Comment by th3coop** [comment]
@Nemial your best bet will be to a new formatter in your preferences:
- Install the version of the formatter you want to use
- *Edit Menu > Preferences > Formatters*
- Click the `+`
- Name and language are obvious
- Formatter > Other > Generic Commandline-line formatter
- Find the formatter install using the browse button
- Add whatever options you'd like.

**Comment by Nemial** [comment]
I tried to do this, but js-beautify doesn't work with standard options,but only in the style where changes are visible when reloading files in the IDE. And alas, I could not overcome it in any way.

`js-beautify -o file.js` doesn't work if you do everything according to your advice

**Comment by th3coop** [comment]
@Nemial could you share a screenshot of your config?  I'm not clear what issue you're having.

**Comment by Nemial** [comment]
![Снимок экрана_2020-01-23_14-14-28](https://user-images.githubusercontent.com/18151125/72983824-e90ff480-3dea-11ea-9778-3f2ad15b82d5.png)

**Comment by th3coop** [comment]
That field is expecting an executable file which a JS file is not.  Isn't there a binary/executable file that gets installed?

**Comment by Nemial** [comment]
There will be no difference if I put a file from the`/usr/bin` directory in that field , I tried to do this, but the result is the same. And all because it's the same file with this content 
```
#!/usr/bin/env node

var cli = require('../lib/cli');
cli.interpret();
```

**Comment by th3coop** [comment]
@Nemial what IS that file?  It looks like it's loading node cli.  How are you using it?  What did you change in the configuration dialog?

I also note that you are on Linux, I thought you were on Windows for some reason.  There should be an executable file in your *node_modules* folder for js-beautify.  What does `which js-beautify` return?

**Comment by Nemial** [comment]
This is a file from a folder  `/usr/lib/node_modules/js-beautify/js/bin/`. I use it to format my code(remove extra spaces, indents, and align everything). Yes I find on Linux Slackware Current.
When used(in the options, specify use when saving a file), it gives

```
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIFormatter.format]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://komodo/content/formatters/formatters.js :: _formatViewWithFormatterAndContext :: line 135"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIFormatter.format]'
+ result (number) 2147500037
+ name (string) 'NS_ERROR_FAILURE'
+ filename (string) 'chrome://komodo/content/formatters/formatters.js'
+ lineNumber (number) 135
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) '_formatViewWithFormatterAndContext@chrome://komodo/content/formatters/formatters.js:135:16
formatVie'...982 chars
+ location (object) JS frame :: chrome://komodo/content/formatters/formatters.js :: _formatViewWithFormatterAndContext :: line 135
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/formatters/formatters.js'
| + name (string) '_formatViewWithFormatterAndContext'
| + lineNumber (number) 135
| + columnNumber (number) 16
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/formatters/formatters.js :: formatViewUsingConfig :: line 870
| + formattedStack (string) '_formatViewWithFormatterAndContext@chrome://komodo/content/formatters/formatters.js:135:16
formatVie'...982 chars
| + stack
    _formatViewWithFormatterAndContext@chrome://komodo/content/formatters/formatters.js:135:16
    formatViewUsingConfig@chrome://komodo/content/formatters/formatters.js:870:16
    formatViewUsingConfigUuid@chrome://komodo/content/formatters/formatters.js:939:0
    @chrome://komodo/content/formatters/formatters.js:991:16
    _doSave@vieweditor:1327:0
    save@vieweditor:1588:27
    viewManager.prototype.do_cmd_save@chrome://komodo/content/views.js:1539:4
    xtk.Controller.prototype.doCommand@chrome://xtk/content/controller.js:61:8
    command_doCommand@chrome://komodo/content/library/commands.js:239:0
    command_doCommandAsync@chrome://komodo/content/library/commands.js:191:0
    @chrome://komodo/content/keybindings/keybindings.js line 2603 > eval:1:0
    this.Manager.prototype.evalCommand@chrome://komodo/content/keybindings/keybindings.js:2603:22
    this.Manager.prototype.keypressHandler@chrome://komodo/content/keybindings/keybindings.js:2774:16
    gKeyHandler@chrome://komodo/content/keybindings/keybindings.js:2658:4
-- EXCEPTION END --
```

**Comment by Nemial** [comment]
However, if you use js-beautify from a regular linux terminal, everything works. It does not work in the IDE

**Comment by th3coop** [comment]
@Nemial try removing the `-o`.  Komodo should handle the input and output file options.

**Comment by Nemial** [comment]
Oh, thank you. It's finally working

**Comment by th3coop** [comment]
Oh awesome!  Ok cool.  Thanks for your patience @Nemial !
