### ISSUE TITLE
Don't Work Autocomplete JS

### ISSUE THREAD

**Issue by Nemial** [Komodo/KomodoEdit#3828]
### Short Summary
Autocompletion of JS functions does not work

### Steps to Reproduce
Even if you enter the `console.` they don't complement anything, although they should. Maybe I didn't include autocomplete and if so, how do I enable it to make it work

### Platform Information

*Komodo IDE
*Komodo Version 12.0.0
*Operating System (and version)?*

**Comment by th3coop** [comment]
Looks like this one has slipped under the radar for a while: https://github.com/Komodo/KomodoEdit/issues/125

Going to close this in favour of #125
