### ISSUE TITLE
API Catalogs don't enabled

### ISSUE THREAD

**Issue by Nemial** [Komodo/KomodoEdit#3829]
### Short Summary
How to include an API in the Komodo IDE's catalogs API 12. If there is no button or check mark and it is not clear whether they are enabled or not

### Platform Information

*Komodo IDE 12.0.0

### Additional Information
 
![Снимок экрана_2020-01-23_00-50-25](https://user-images.githubusercontent.com/18151125/72941826-9b5ba380-3d7a-11ea-9d87-9e215fd7f124.png)

**Comment by th3coop** [comment]
@Nemial if you have questions about Komodo you can post them in the forums: https://community.komodoide.com/

You select then click OK or Apply
