### ISSUE TITLE
Windows error installing Komodo Edit 12

### ISSUE THREAD

**Issue by geertemo** [Komodo/KomodoEdit#3831]
### Short Summary
I have Komodo Edit 11.1.1 installed on my Windows 10 machine.
When I install Komodo-Edit-12.0.0-18431.msi Windows gives the following error : Another version of this product is already installed. Installation of this version cannot continue. To configure or remove the existing version of this product, use Programs and Features in the Control Panel

### Steps to Reproduce
evident.

### Expected results
installation of version 12 besides version 11.

### Actual results
error.

### Platform Information

*Komodo Edit or IDE?*  Edit
*Komodo Version?*  12.0.0
*Operating System (and version)?* latest Windows 10 64bit

**Comment by th3coop** [comment]
@geertemo thanks for reporting this.  Komodo IDE is free now so you can use that if you like.

I'll push a fix for this in a nightly tomorrow when the build is ready: https://github.com/Komodo/KomodoEdit/commit/6e38234d05debe8f5e93500331b145fbf88df105

**Comment by geertemo** [comment]
@th3coop I see you made changes to the code and you said to "push for a fix in the nightly tomorrow", but the msi I downloaded today still gives the error. Can you give me an estimatie when the fixed msi will be available on the download page?

**Comment by th3coop** [comment]
Not sure what you downloaded but the nightlies are here: http://downloads.activestate.com/Komodo/nightly/komodoedit/latest-12.0.x/

Is that what you downloaded?  If not, give that a try.

**Comment by geertemo** [comment]
I am just a humble user ;-) , so I downloaded from https://www.activestate.com/products/komodo-ide/downloads/edit/ (version 12.0.0, today still the current, not upgradable version)

Installation via the nightly link you provided worked like a charm. Thanks!
Will I be able to update this version with regular updates via the "Check for updates..." option in the menu, or do I have to reinstall the program when 12.0.1 becomes available on the download page?

As for "Komodo IDE is free now so you can use that if you like" :
I just use Komodo as an intelligent (and very nice!) editor for PHP, JS, CSS, (HTML, XML, JSON, (XUL)).
As a result I think I use not even half of the functionality of Komodo Edit.
Using Komodo IDE would only widen the percentage of functionality I do not use, so as long as Edit is available I am not tempted to switch over to IDE :-)

Best regards,
Geert-Emo

**Comment by th3coop** [comment]
@geertemo, glad that worked for you!

When 12.0.1 is officially release you will be prompted to updated to it.  If we release new nightlies you will also be prompted to update to those.
