### ISSUE TITLE
Komodo IDE 12 Don't Save Configuration Eslint

### ISSUE THREAD

**Issue by Nemial** [Komodo/KomodoEdit#3832]
### Short Summary
Good afternoon. I have a problem. I used to use JSHint Linter and everything was fine.The other day I decided to try out ESlint. And here is a strange situation. I select the bin file and its config in the settings, click APPLY and OK, but when I go back to the settings, I see that nothing was applied

### Platform Information

*Komodo IDE 12.0.0
*Slackware Current

**Comment by th3coop** [comment]
@Nemial please post in the forums if you're unsure about configuration:
https://community.komodoide.com/

If we find a bug we can create a ticket for the found issue
