### ISSUE TITLE
Rectangular Selection with Japanese IME is wrong.

### ISSUE THREAD

**Issue by htsign** [Komodo/KomodoEdit#384]
It is occured that single insertion to selected code with Rectangular Selection
when Japanese IME is enabled on Windows.
![before](https://cloud.githubusercontent.com/assets/1135891/8437200/81509aa4-1f98-11e5-9e91-429168740bb9.png)
![after](https://cloud.githubusercontent.com/assets/1135891/8437201/8196af4e-1f98-11e5-9d60-7e3c7d0aab95.png)
To input any Japanese words makes selected letters are deleted, be wide selection area and insert a word (inserted "あ" in upper image)

**Comment by Naatan** [comment]
Could you provide a test case with which we can reproduce the issue?

**Comment by htsign** [comment]
It is necessary to install any Japanese IME(e.g. Microsoft Japanese IME)

0. [Setup an new language](http://windows.microsoft.com/en-us/windows7/Add-or-change-an-input-language) and install Microsoft Japanese IME.
0. Launch Komodo Edit/IDE
0. Enable the IME ("Alt + ~" in US Keyboard)
0. Select some text with Alt + mouse drag
0. Press any key to input

I am sorry to take you time.

**Comment by Naatan** [comment]
Sorry, I meant some actual text with which we can repro, ie. a file with japanese characters.
