### ISSUE TITLE
remember folding setting for a file

### ISSUE THREAD

**Issue by dmolirl** [Komodo/KomodoEdit#385]
Hi Devs,
Great job with Komodo Edit. It's a great product!
Using version: Komodo Edit, version 9.1.0, build 15798, platform linux-x86_64

Feature request:
I use Codeigniter PHP code with lots of functions and I use code folding to make the code more readable by collapsing each function. 
The folding settings don't seem to survive saving and later re-opening.
I'm not sure if it exists but is there a feature or file meta-data that stores the last folding setting for this file?

Or a feature to set a folding template for a file type?
Kind regards
Dave Molloy

**Comment by cgchoffman** [comment]
Hi @dmolirl,  try Preferences > Editor > Smart editing > Folding: "Restore fold state on document reload" enabled.
