### ISSUE TITLE
Error attempting to save [file name]: Bad file descriptor

### ISSUE THREAD

**Issue by DarthGaymer** [Komodo/KomodoEdit#3856]
### Short Summary
I am currently unable to save any of my .xml projects to my C: drive as I get the following error message. This issue is persistent when working with all file sizes, 30KB to 1140KB.

 Looking at the log file, see below, it appears that Komodo Edit is trying to add to backlashs everywhere possible.

![image](https://user-images.githubusercontent.com/62295415/76865606-f4066480-6830-11ea-8d24-5f4cf6f2331a.png)

*Komodo Edit 12.0.1, build 18441 
*Windows 10 Pro version 1909 OS Build 18363.719?* 

### Additional Information

Log file info:

![image](https://user-images.githubusercontent.com/62295415/76866217-cbcb3580-6831-11ea-805a-fa828c0d9edd.png)

**Comment by th3coop** [comment]
@DarthGaymer share the actual log file please.

> it appears that Komodo Edit is trying to add to backlashs everywhere possible.

Not sure what you mean here unless you're referring to escaping of backslashes in Windows paths?  eg. C:\\blah\\foo\\something.xml. That's normal otherwise your path would be full of escape sequences.

**Comment by DarthGaymer** [comment]
@th3coop Below is the log file.  The error I am getting starts on line 124.  If you look at the file path, there appears to be a doubling of all backslashes.

[pystderr.log](https://github.com/Komodo/KomodoEdit/files/4369408/pystderr.log)

**Comment by th3coop** [comment]
The doubling backslash is normal.  I fixed my previous comment to show my example properly.  The backslashes need to be escaped otherwise they will create an escape sequence with the letter following them.

Have you tried a restart of Komodo?

btw, whatever you're working on looks like it will be pretty awesome.

**Comment by DarthGaymer** [comment]
I have tried restarting Komodo, reinstalling Komodo, and updating Windows 10.

**Comment by th3coop** [comment]
@DarthGaymer what happens if you try to open that path in File Explorer?

**Comment by DarthGaymer** [comment]
Using C:\\Users\\ryheiderscheit\\iCloudDrive\\Desktop\\D&D\\D&D App Files\\Items\\Magic Items 5.3.xml, Windows throws the following error message:

![image](https://user-images.githubusercontent.com/62295415/77349298-ce81cb00-6d08-11ea-872e-f286c287e55f.png)

Using C:\Users\ryheiderscheit\iCloudDrive\Desktop\D&D\D&D App Files\Items, the file path opens as expected.

**Comment by th3coop** [comment]
We need to figure out what might be wrong with your computer.  The code that you're hitting, EVERYONE hits when they save a file.  If this was a problem in Komodo then no one could save a file.  It might still be Komodo, but there is something unique about your setup that's triggering this so we need to figure out what that thing is.  

@DarthGaymer can you try restarting Komodo in safe mode, *Help > Troubleshooting > Restart in Safe-mode*.  Try to reproduce the issue, report back with a new log file then you can restart Komodo manually to get back to original settings.

A couple more clarifying Qs, answer/try theses after reverting safe-mode by manually restarting Komodo:
1. How are you saving the file exactly?  ctrl + S?
1. If you move a problem file to your `Deskstop` dir instead and try again, does the problem persist?

**Comment by DarthGaymer** [comment]
@th3coop Turns out this was just a symptom of a bigger issue.  Last night iTunes began having issues writing data as well.  Turns out that the drive permissions got royally messed up.  Ended up having to do a clean install of Windows and all other programs which resolved the issue.

**Comment by th3coop** [comment]
Well I'm glad I could be a part of helping you get this figured out, not that I helped that much!  Best of luck with what you're working on.  Looks cool.
