### ISSUE TITLE
Komodo Python2 syntax checking is dependent on system Python2, ignores virtualenv

### ISSUE THREAD

**Issue by hobbsd** [Komodo/KomodoEdit#386]
I have a Python2 project with a virtualenv configured. The virtualenv has pylint, pep8, and pyflakes installed, but they aren't available in Project Prefs > Syntax Checking:

![screen-2015-07-01_13-34](https://cloud.githubusercontent.com/assets/1676348/8460929/ae2e9f2c-1ff6-11e5-8aaf-ced0e1c2c41a.png)

But if I add `c:\python27` (which has pylint and pep8 installed) to the path under Project Prefs > Environment, the syntax checking options become available:

![screen-2015-07-01_13-45](https://cloud.githubusercontent.com/assets/1676348/8461056/a523477e-1ff7-11e5-986f-401c8952f9ca.png)

Maybe this isn't a bug and just calls for some documentation (i.e., tell users to configure Komodo for Python syntax checking in the application prefs). It doesn't seem like syntax checking tools should need to be installed into every project. But the way it stands syntax checking is broken until I add the system Python to the project's environment, because I don't have the system Python directories on my path due to using the `py` launcher on Windows (which, I believe, is intended to be the standard setup for Python developers working with both 2 and 3).

This is on KE 9.1, by the way.

**Comment by Naatan** [comment]
What are you adding to your environment variables exactly?

Note it's up to you whether you do this per Project or just globally. If you define it globally (Edit > Preferences) then all projects will inherit this setting unless they explicitly define their own.

**Comment by hobbsd** [comment]
In the project prefs I just added `PATH=%PATH%;c:\python27` to the environment. That made the options change to be like the second image above. Now when I look at it today, the project prefs > syntax checking options for Python 2 are back to grayed-out pylint/pep8/pyflakes (as in the first image above), even though the path is still modified in project prefs.

I'm a bit confused because the settings options appear to vary/change mysteriously. For example, in my global prefs for both Python 2 and 3 default interpreters I have 'Find on path', and my Windows system doesn't have either one on the path (I use the `py` launcher, as I mentioned above); and I haven't adjusted the environment in the global prefs at all; so my expectation would be that Komodo should have no awareness of my system Python installations.

Then under global prefs > syntax checking for Python the options look like the first image above with pylint/pep8/pyflakes grayed-out, which makes some sense if Komodo has no Python 2 installation to work with (and we assume it's going to use its own Python2 interpreter for syntax checking?), although I don't know why the pychecker option is available (I assume Komodo provides that).

Under global prefs > syntax checking for Python 3 I would expect the options to be the same as for Python 2, but they look like this:

![screen-2015-07-02_12-47](https://cloud.githubusercontent.com/assets/1676348/8482614/cc07e64e-20b8-11e5-8e36-1d0e8ab6acbe.png)

So it has found the system Python 3 installation even though it's set to find it on the path (where it's not).

**Comment by hobbsd** [comment]
Similarly: start with the system Python2 having pep8 installed, turn on pep8 checking for a Python2 project that uses a virtualenv without pep8. KE won't do pep8 checking because it doesn't find it in the virtualenv. Now install pep8 in the virtualenv and remove it from the system Python2 -- pep8 checking will work even though the preference is no longer available in project prefs:

![screen-2015-07-09_13-20](https://cloud.githubusercontent.com/assets/1676348/8602148/9713c7b0-263e-11e5-82e8-ed8a62e61044.png)

So pep8 has to be installed in the system Python2 in order to enable the preference, and it needs to be installed in the virtualenv in order to run.

Maybe pylint/pep8/pyflakes/pychecker should only use the system's Python installation.

**Comment by Naatan** [comment]
It has to be installed in the system Python 2 because it doesnt sound like you are telling Komodo to use your virtualenv properly. Point your python interpreters at your virtualenv interpreters and point your PATH, PYTHONPATH and PYTHONHOME at your virtualenv as well.

**Comment by hobbsd** [comment]
I couldn't find anything in the Komodo docs about that -- could you explain why those variables would need to be set when the virtualenv interpreter is correctly set? Normally, the python interpreter determines `PYTHONPATH` and `PYTHONHOME`, and I don't need to adjust the `PATH`.

**Comment by ervumlens** [comment]
> ... So it has found the system Python 3 installation even though it's set to find it on the path (where it's not).

FYI, in Komodo on Windows, the path refers to the environment `%PATH%` *and* to the registry entries under `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\` (see [which.py](https://github.com/Komodo/KomodoEdit/blob/master/util/which.py#L89)). The latter is not referenced by the command line, but is used in places like the Windows Run dialog.

The Python3 Windows installer apparently adds `Python.exe` to the registry and Komodo picks it up there.

If you ever want to know what Komodo sees on the path, run something like this Komodo macro. I have no `python` available in the `%PATH%`, but Komodo finds one in the registry and displays it.

```python
#this is a python macro
import which

#look for `python`
window.alert(str(which.whichall('python')));

```
