### ISSUE TITLE
Mozilla build error Linux gcc-8

### ISSUE THREAD

**Issue by Holerim** [Komodo/KomodoEdit#3862]
### Short Summary
Mozilla throws error with default gcc version 8.
`error: ‘bad_alloc’ in namespace ‘std’ does not name a type`

### Steps to Reproduce
`sudo apt install gcc`
`git clone https://github.com/Komodo/KomodoEdit.git`
`cd KomodoEdit/mozilla`
`python build.py configure -k 12.10`
`python build.py all`

### Expected results
build successfully

### Actual results
headache

### Platform Information

*Komodo Edit* 
*Komodo Version 12.10* 
*Operating System linux any* 

### Additional Information

Log https://ghostbin.co/paste/audjr

It throws a different error with gcc-4.9 but that's another issue.

**Comment by th3coop** [comment]
@Holerim sorry if I gave the impression that this would get fixed.  Komodo runs on an older version of Mozilla which for multiple reasons, we have no plans to upgrade. You need to use the recommended gcc.
