### ISSUE TITLE
CoffeeScript syntax coloring: dots in numeric range miscolored

### ISSUE THREAD

**Issue by ervumlens** [Komodo/KomodoEdit#387]
*Problem*
The CoffeeScript syntax coloring miscolors ranges that end in a number, such as `x = [1...2]`. The coloring suggests that the range ends in `.2` when it actually ends in `2`. 

*Code 1* 

```coffeescript
x = [1..2]
x = [1...2]
```
*Screenshot 1*
![screenshot](https://cloud.githubusercontent.com/assets/13005338/8469061/428db912-203a-11e5-99a6-87487dbbd5c8.png)

Note the orange dot before the `2`. This dot should be blue.

*Code 2*
The code below is a basic test case for the syntax coloring of ranges and arrays. This includes the two lines listed above. All lines are valid CoffeeScript, but not always meaningful (e.g., `[1... .2]` is valid but not useful). The coloring for the lines marked "incorrect" suggest something different than what the code itself represents.

```coffeescript
#CoffeeScript syntax highlighting: Problem with dots in ranges.
#All lines are valid CoffeeScript, but not always meaningful.
two = 2
x = [1]			#correct
x = [.1]		#correct
x = [0x1]		#correct
x = [1.2]		#correct
x = [1..2]		#incorrect, range is 1 through 2, not ??
x = [1...2]		#incorrect, range is 1 to 2, not 1 through .2
x = [1 ..2]		#incorrect, range is 1 through 2, not ??
x = [1 ...2]	#incorrect, range is 1 to 2, not 1 through .2
x = [1 .. 2]	#correct
x = [1 ... 2]	#correct
x = [1.. 2] 	#correct
x = [1... 2] 	#correct
x = [1.. .2]	#correct
x = [1... .2]	#correct
x = [1..two]	#correct
x = [1.. two]	#correct
x = [1 .. two]	#correct
x = [1 ..two]	#correct
x = [1...-2]	#correct
x = [1..0x2]	#incorrect, range is 1 through 2, not ??
x = [1...0x2]	#incorrect, range is 1 to 2, not ??

#Komodo Edit, version 9.1.0, build 15798, platform linux-x86_64.
#Built on Sat May 30 05:22:08 2015.
```

*Screenshot 2*
![screenshot](https://cloud.githubusercontent.com/assets/13005338/8469013/b56a8362-2039-11e5-8020-0247e23688c9.png)

> Komodo Edit, version 9.1.0, build 15798, platform linux-x86_64. Built on Sat May 30 05:22:08 2015.

**Comment by Naatan** [comment]
Nice catch, I had to squint pretty hard to even see what you were talking about :)

**Comment by ervumlens** [comment]
FYI, this bug might be a remnant of [scintilla bug 1583](http://sourceforge.net/p/scintilla/code/ci/47d68ec04cfe49127547292b65db29df7516c9eb/), which fixed a similar styling problem in `[1...foo]`.

**Comment by Naatan** [comment]
Nice, thanks for providing that link @ervumlens !

**Comment by Defman21** [comment]
Just saying - it's not only in CoffeeScript, also in Ruby.

**Comment by Defman21** [comment]
@mitchell-as this also happens in Ruby! :)

**Comment by Defman21** [comment]
![Imgur](http://i.imgur.com/wkzWrVn.png)

**Comment by mitchell-as** [comment]
@Defman21 Please open a new bug :)

**Comment by Defman21** [comment]
Ok!
