### ISSUE TITLE
internal komodo error

### ISSUE THREAD

**Issue by AlfonsoPonchio** [Komodo/KomodoEdit#3874]
### Short Summary
an error in komod when open, failed to start komodo intel

### Steps to Reproduce
only start komodo

### Actual results
2147500037 (NS_ERROR_FAILURE)

Komodo Edit, version 12.0.1, build 18441.
Built on Tue Feb 11 04:14:27 2020.

### Platform Information

*Komodo Edit or IDE?*  komodo edit 
*Komodo Version?*  12.0.1 bulit 18441
*Operating System (and version)?*  windows 10 home single language, x64

**Comment by th3coop** [comment]
Not sure what you're reporting.  Please fill out all requested fields fully.
