### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by ziplizard** [Komodo/KomodoEdit#388]
I'm using CakePHP, so have files that end with ".ctp" and I have those configured to syntax highlight and behave like PHP files. However, the indentation of these files does not work. I have it configured in Preferences to use 4 spaces (no tabs), and when I indent on these files it uses 8 spaces. There is no way I can find to fix this. I'm using Komodo Edit  9.1.0. Thanks.

**Comment by Naatan** [comment]
Hi there, could you please open a thread for this on the forums? The bug tracker is not for general support.

Forum link: http://forum.komodoide.com/
