### ISSUE TITLE
I'm a complete novice - Run command shortcut not working

### ISSUE THREAD

**Issue by TomPythonCode** [Komodo/KomodoEdit#3884]
Hi guys, I'm a complete beginner trying to learn code, specifically Python. 
I'm learning via LinkedIn Learning's  "Python Essential Learning" and my first hurdle has been met pretty much off the bat. I was happily following along with the tutorial, which so far includes downloading the exercise files and the subsequent software, e.g Python and Komodo Edit. 

When trying to simply create  run command to open up my first exercise folder, it starting saying that the command isn't working. Please note: If I manually click on the file, it seems to open up fine. If I try my Ctrl+Shift+R key bind for the command, it gives me this message:

C:\Users\Lenovo\AppData\Local\Programs\Python\Python38-32\python.exe: can't open file 'chrome://komodo/content/quickstart.xml#view-quickstart': [Errno 22] Invalid argument

Any tips? If you need more info please let me know

![image](https://user-images.githubusercontent.com/71277317/93105680-4670f280-f6a7-11ea-9085-f6268ee1c6d7.png)

**Comment by th3coop** [comment]
Hi @TomPythonCode , lets keep this in the forum post you created.
