### ISSUE TITLE
PHP Namespace Keyword Has No Code Intel

### ISSUE THREAD

**Issue by ssigwart** [Komodo/KomodoEdit#3896]
### Short Summary
The `namespace` keyword in PHP does not autocomplete.

### Steps to Reproduce
Type `namespace` followed by a space.

```php
<?php

namespace |
```

### Expected results
- Autocompletion of existing namespaces should show.
- A nice feature would be to also use the directories in the current path as a possible suggestion (e.g. `/path/to/my/project/MyNamespace/SubSpace/File.php` would have autocompletes for `path`, `to`, `my`, `project`, `MyNamespace`, and `SubSpace`.  If you use `MyNamespace\`, it then has `SubSpace` as a suggestion).

### Actual results
There is no autocompletion.

### Platform Information

Komodo Edit, version 11.2.0 (Custom build)
MacOS Catalina 10.15.6

### Additional Information

These few lines look like it's intentionally not implemented, but I feel like it should be.
https://github.com/Komodo/KomodoEdit/blob/9c66308f19cad8ff946eb16acb95eee1b9b6f5aa/src/udl/skel/PHP/pylib/lang_php.py#L330-L332
https://github.com/Komodo/KomodoEdit/blob/9c66308f19cad8ff946eb16acb95eee1b9b6f5aa/src/udl/skel/PHP/pylib/lang_php.py#L356 

@th3coop,
1.  Do you see any reason not to implement my suggestions (particularly given the existing code above)?
2.  This is probably something that I should hold off on since it won't easily merge into the IDE version, right?

**Comment by th3coop** [comment]
@ssigwart, I'm not sure why those comments are there.  As you said, it likely won't merge into IDE easily, but if you're interested in implementing it here in Edit I'll be happy to merge it in to Edit.
