### ISSUE TITLE
Javascript autocomplete bug for try inside a string

### ISSUE THREAD

**Issue by KnowZero** [Komodo/KomodoEdit#3899]
### Short Summary
The autocomplete for javascript is treating strings as code. Typing try inside a string leads to it autofilling the try function.

### Steps to Reproduce

For a javascript file
type:

```console.log("try")```

and than add a space at the end of try.

### Expected results

It should be:
```console.log("try ")```

### Actual results

You get this:
```
console.log("try {
    
} catch(e) {
    alert(e);
}")
```

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 12
*Operating System (and version)?* Linux Mint 19.3 

### Additional Information

Edit: The same happens if I do "if"

```
console.log("if (test) {
    //code
}")
```

**Comment by KnowZero** [comment]
This seems to be related to #3892 , but that one is for comments. This is for strings.

So seems like the underlying issue is the autocomplete isn't context aware.

**Comment by th3coop** [comment]
Yeah, this can be handled in #3892 but it should be added to the ticket.  I'll do that.  Going to close this ticket in favour of that.
