### ISSUE TITLE
Places SCC status doesn't update for SVN

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#39]
http://forum.komodoide.com/t/komodo-9-svn-icons/1291

> Apparently a modified file is shown as "modified" (with the pencil icon) on its tab 
> header when it's open for edit. The same file appears to be "as in the repository' 
> whe appearing in the places tree.Is this a bug or should I do something in order to > make it show the pencil there too?Please have a look on this picture:

**Comment by cgchoffman** [comment]
Confirmed the same for Git.  I've never noticed this before.

**Comment by toddw-as** [comment]
Fixed in IDE commit https://github.com/Komodo/KomodoIDE/commit/e52322ee778939e2688f948928a2f479b1e2a4e1

Same as https://bugs.activestate.com/show_bug.cgi?id=104886
