### ISSUE TITLE
Perl autocomplete issue when writing $res->hash

### ISSUE THREAD

**Issue by KnowZero** [Komodo/KomodoEdit#3900]
### Short Summary
Perl autofill activates when it shouldn't

### Steps to Reproduce
Type:
```
$res->hash
```
Than add ";"

### Expected results

```
$res->hash;
```

### Actual results

```
   $res->%name = (
     => ,
     => ,
   );
```

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 12
*Operating System (and version)?* Linux Mint 19.3

**Comment by th3coop** [comment]
@KnowZero you'll have to remove that char from the trigger chars in your prefs: Edit menu > Preferences > Edirot > Smart Editing: Auto-abbreviations
