### ISSUE TITLE
Unresponsive after clicking Add > New Command

### ISSUE THREAD

**Issue by henry90** [Komodo/KomodoEdit#3906]
### Short Summary
Both Komodo Edit 12 and IDE 12 became unresponsive after clicking Add -> New Command... on the Right Pane.

### Steps to Reproduce
Right-click on the Right Pane, click Add > New Command, both Komodo Edit 12 and IDE 12 immediately became unresponsive.

### Expected results
It should allow the user to create a new command without crashing.

### Actual results
The application was freezing, I have to Force Quit the application.

### Platform Information
Komodo Edit 12 and IDE 12 
Komodo Version: Komodo IDE version 12.0.1 build 91869; 
Operating System (and version): macOS Big Sur Version 11.0.1 (20B29)

**Comment by th3coop** [comment]
#3905.
