### ISSUE TITLE
Komodo IDE 12.0.1 update check fails

### ISSUE THREAD

**Issue by joho1968** [Komodo/KomodoEdit#3908]
### Short Summary

Komodo IDE 12.0.1 fails to check for update.

### Steps to Reproduce

Wait for Komodo IDE to check for upgrades, or force it through the menu.

### Expected results

Well, either that there are no updates or that there are updates :-)

### Actual results

"Update XML file malformed (200)"

### Platform Information

*Komodo IDE* 
*12.0.1* 
*Ubuntu 18.04.LTS* 

### Additional Information

![image](https://user-images.githubusercontent.com/3135227/99942471-0184ce80-2d70-11eb-985a-00bb0f008425.png)

**Comment by th3coop** [comment]
Thanks @joho1968 .  For your piece of mind, there are no updates.

**Comment by mjross** [comment]
I'm seeing the same behavior from Help > Check for Updates. Also, when Komodo IDE does its periodic update check (monthly?), the same dialog box appears, but no reason for the failure is mentioned. Screenshot attached.
![image](https://user-images.githubusercontent.com/829492/103437752-0485a100-4bf1-11eb-8acb-74b991352132.png)

**Comment by reetp** [comment]
Been there for months and still not fixed. No idea what is happening.

https://community.komodoide.com/t/update-failed-update-xml-file-malformed-200/5134/10

**Comment by th3coop** [comment]
@reetp, the forum post was a different issue.  This is a new one though that's not obvious.  For anyone concerned the are missing out on updates, you are not. There have been no updates to be installed.

**Comment by reetp** [comment]
Thanks.
Just makes you wonder if you are up to date etc.

**Comment by th3coop** [comment]
@reetp, yep, I understand.

**Comment by kgrammer** [comment]
I'm still getting this issue when trying to update Komodo.  Has there been any progress made on resolving this issue?

**Comment by th3coop** [comment]
@kgrammer, no change.  If there are, they will be in this ticket.  There are no planned changes to Komodo.  If some come about, we'll obviously address this.

**Comment by VeNoMouS** [comment]
`There are no planned changes to Komodo` ... does mean the project is **__dead__**? since theres > 1.2k issue tickets and no commits for months?

**Comment by th3coop** [comment]
@VeNoMouS it means there are currently no planned changes.

**Comment by vladisslav** [comment]
I've had this problem for over a year: Update XML file malformed (200)
PS:
Komodo IDE, version 12.0.1, build 91869, platform win32-x86.
Built on Mon Feb 10 18:14:23 2020.

**Comment by ratajs** [comment]
Still the same issue.
![Screenshot](https://user-images.githubusercontent.com/19972986/123862582-d0cdce80-d928-11eb-83f1-1c1845740778.png)

**Comment by Patrick5** [comment]
Same story 21-07-04 

For what it's worth, running updates.xml through www.w3schools.com [XML validator](https://www.w3schools.com/xml/xml_validator.asp) indicates problems with undefined labels _update.details.label_ , _update.installedOn.label_, and _update.status.label_

Revisiting the download site offers the same .msi file that I downloaded a few days ago, so obviously no updates.  The reason I even checked was that I was about to report another issue, and did not want to report on a fixed problem :-)

**Comment by th3coop** [comment]
> so obviously no updates

Correct.  There are no updates.  Please contact support@activestate.com to request more details on future Komodo development.

**Comment by ErgunCln** [comment]
![image](https://user-images.githubusercontent.com/6827180/208256448-507be516-5cd3-4361-8595-c18493da41fe.png)

**Comment by th3coop** [comment]
Morning @ErgunCln.  ActiveState is no longer working on Komodo and has open sourced the code base: https://www.activestate.com/blog/activestate-komodo-ide-now-open-source/  This issue will not be fixed unless at some point in the future a community forms around the code base and starts producing updates.
