### ISSUE TITLE
{Main menu -> Edit -> Replace} is disabled for new, unsaved, files.

### ISSUE THREAD

**Issue by martinvahi** [Komodo/KomodoEdit#391]
# Reproduction sequence:

1. **Ctrl-N**
2. Write some nonsense.
3. Try to replace part of the nonsense by the **Alt->Edit->Replace**.

# Version info

* version 9.10.0-devel, 
* build 14998, 
* platform linux-x86_64. 
* Built on Thu Oct 9 10:01:22 2014.

**Comment by ervumlens** [comment]
Is your version information correct? It suggests that you're running a local build that was built in October 2014.

FWIW, I'm not able to reproduce this in the current release.

**Comment by Naatan** [comment]
I cannot reproduce this. Could you please try on a stable build?
