### ISSUE TITLE
Editor is no longer responding after update to MacOS 11

### ISSUE THREAD

**Issue by LeFrankOnGit** [Komodo/KomodoEdit#3910]
I updated to MacOS 11. Komodo Edit crashes and I need to stop the Komodo process. A restart bringt me to the same status. If I remove both Komodo folders in ~/Library/Application Support I can use it again. It seems like the editor is crashing where I do a search in files. If I try to set a start folder in the file search it also crashes.

**Comment by th3coop** [comment]
Hi @LeFrankOnGit, tracked here https://github.com/Komodo/KomodoEdit/issues/3905.
Workaround here: https://community.komodoide.com/t/komodo-and-big-sur-do-not-upgrade/5191/16
