### ISSUE TITLE
Information needed!

### ISSUE THREAD

**Issue by Naman23-coder** [Komodo/KomodoEdit#3931]
This is dumb question but can you guys tell which files have code for gui,executing and autocomplete for following languages:-
1.python
2.c++
3.Js
4.Html
5,C

**Comment by Naman23-coder** [comment]
C and c++ is only if supported

**Comment by th3coop** [comment]
Python, HTML and JS have full support in Komodo.  C and C++ have some rudimentary support like syntax colouring.  

In the future, please don't use the issue tracker for product questions, that's what the forums are for: https://community.komodoide.com/

Have a good one!

**Comment by Naman23-coder** [comment]
Thanks :-)
