### ISSUE TITLE
TCL edit environment adds auto-text when typing the word "for" in a comment

### ISSUE THREAD

**Issue by Patrick5** [Komodo/KomodoEdit#3932]
### Short Summary
When typing the word "for" in a TCL comment line, the editor auto-inserts "{set START} {TEST} {NEXT}" on the first space.

I don't want to disable auto-abbreviations in general, just to ignore them in comment text. 

### Steps to Reproduce
Type the following into the editor (with a space at the end):
 \# this shows the problem with for 

### Expected results
Nothing should happen

### Actual results
Editor inserts autotext:
\# this is a comment for **{set START} {TEST} {NEXT}**

### Platform Information

*Komodo IDE* 
*Komodo-IDE-12.0.1-91869.msi* 
*Windows 8.1* 

### Additional Information

Haha the workaround is to not type the word "for" in a comment.   One solution is to type "fr" instead, then go back and insert the 'o' once the text is complete.

**Comment by th3coop** [comment]
Thanks for reporting @Patrick5.  Will close in favour of this ticket though: https://github.com/Komodo/KomodoEdit/issues/3892
