### ISSUE TITLE
Komodo edit IDP.Generic 

### ISSUE THREAD

**Issue by ogsalinas** [Komodo/KomodoEdit#3938]
### Platform Information
Win 10

2147500037 (NS_ERROR_FAILURE)

Komodo Edit, version 12.0.1, build 18441.
Built on Tue Feb 11 04:14:27 2020.

### Additional Information

<!--
eg. Error logs, screenshots, workarounds

You can find your error log via Help > Troubleshooting > View Log File
--
![komodo edit](https://user-images.githubusercontent.com/90006437/131912187-dd4e4e85-ada6-4754-97e9-b9ff030d1bf2.jpg)
>

**Comment by th3coop** [comment]
Please fillout the field properly.  Closing for now.
