### ISSUE TITLE
Komodo freezes after drag and drop file

### ISSUE THREAD

**Issue by kemoc** [Komodo/KomodoEdit#3947]
### Short Summary
Komodo freezes after drag and drop pre-commit file on Mac OS, restart Komodo did not help, after open Komodo it freezes/not responding

found in pystderr.log file:
`[2022-01-24 15:04:39,854] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in `

### Steps to Reproduce
Drag and drop pre-commit file

### Expected results
Open file

### Actual results
Freeze Komodo, not responding

### Platform Information

*Komodo Edit or IDE?* 
Komodo Edit on Mac
*Komodo Version?* 
The newest, 12? not sure can't use Komodo after open.
*Operating System (and version)?* 
Mac OS Monterey 12.0.1

**Comment by th3coop** [comment]
@kemoc you're likely hitting this issue: https://community.komodoide.com/t/how-to-start-komodo-on-osx-big-sur/5664

Follow the instructions linked there.  I'm going this ticket.
