### ISSUE TITLE
Komodo Plugins are not working

### ISSUE THREAD

**Issue by gear24** [Komodo/KomodoEdit#3951]
I tried to install some plugins from komodo ide and the search bar was just loading and loading, then I wrote some text and the same, I have to import the downloaded file and import it to komodo ide, I do not know if that is the way to install plugins or if it is an error

**Comment by th3coop** [comment]
Closing for: https://github.com/Komodo/KomodoEdit/issues/3945

**Comment by strizzo-sudo** [comment]
Same problem. Never been able to solve. It's for sure a bug.

**Comment by th3coop** [comment]
@strizzo-sudo you tried the workaround linked [here ](https://github.com/Komodo/KomodoEdit/issues/3945#issuecomment-1136103453)?

**Comment by strizzo-sudo** [comment]
Yes, i did but it it didn't work for me. Sorry.

Il lun 30 mag 2022, 22:31 Carey Hoffman ***@***.***> ha
scritto:
