### ISSUE TITLE
Brace highlighting causes neighbor character's style to "flicker"

### ISSUE THREAD

**Issue by ervumlens** [Komodo/KomodoEdit#396]
**Problem**
Typing next to a brace-highlighted character (e.g., before a `]`) causes the typed character to adopt the brace highlighting style briefly, then switch to normal. This looks like a flicker at normal typing speed. This is most obvious on a dark background with bold white brace highlighting, which is essentially what I'm using.

This happens whether or not soft characters are enabled.

> Komodo Edit, version 9.1.0, build 15798, platform linux-x86_64.
Built on Sat May 30 05:22:08 2015.

**Steps to Reproduce**
1. Open a file.
2. Type `[]`.
3. Put the cursor between the brackets.
4. Start typing.

**Expected**
The typed character appears in its normal style. The braces continue to appear highlighted.

**Actual**
The typed character appears with the highlighted style. The neighboring brace appears with its unhighlighted style. A moment later the styles are corrected.

Tapping `3`:
![image](https://cloud.githubusercontent.com/assets/13005338/8509948/3f6955f8-228c-11e5-9d38-f8a30bd4bf91.png)

A moment later this (correctly) turns into:
![image](https://cloud.githubusercontent.com/assets/13005338/8509997/970663a2-228f-11e5-85eb-a29ee79a1f4c.png)

**Workaround**
No effective one that I can find. Brace highlighting is always on, so there is always a highlight style active.

**P.S.**
If your computer is too fast to exhibit the problem, please send it to me and I will promptly close this issue. :wink: Or try setting your `bracehighlight` style to a ridiculously large font size, like so:

![image](https://cloud.githubusercontent.com/assets/13005338/8510010/46c0401a-2290-11e5-85a9-c27b5fd80a9a.png)

Or hold the key down rather than tapping it:

![image](https://cloud.githubusercontent.com/assets/13005338/8510053/7bb30e9a-2292-11e5-8f4c-de4329b5bcf6.png)

**Comment by Naatan** [comment]
My guess is this is a scintilla "issue" that's by design. @mitchell-as can you comment?

**Comment by mitchell-as** [comment]
Correct. Scintilla has a character buffer and a style buffer. The character buffer holds buffer text and the style buffer holds styles to draw characters in. They need to be resynchronized as text is inserted and removed, and it is very likely you are capturing Scintilla in the middle of a resynchronization attempt. I doubt there's anything we can do here.

**Comment by ervumlens** [comment]
Ok, that's for digging into it. I was unable to reproduce the problem in SciTE or CodeBlocks (which I think still uses Scintilla), so I thought it might be a Komodo thing.

**Comment by ervumlens** [comment]
The style sync'ing in this case occurs in [views-buffer-base::onUpdateUI](https://github.com/Komodo/KomodoEdit/blob/8865f7249de2715c648b6aebc37b0f00b6466214/src/chrome/komodo/content/bindings/views-buffer.p.xml#L1160). The actual style updating [occurs behind a `timeout` call](https://github.com/Komodo/KomodoEdit/blob/8865f7249de2715c648b6aebc37b0f00b6466214/src/chrome/komodo/content/bindings/views-buffer.p.xml#L1164-L1169). This accounts for the delay in updating Scintilla. Making the styles update directly in `onUpdateUI` was enough to resolve the flickering.

This would also explain why I can't reproduce the issue in SciTE or other Scintilla-based editors.

The update occurs in a `timeout` because ["often painting during onUpdateUI doesn't work correctly"  but "if we set it in a timeout, it works"](https://github.com/Komodo/KomodoEdit/blob/8865f7249de2715c648b6aebc37b0f00b6466214/src/chrome/komodo/content/bindings/views-buffer.p.xml#L1164-L1165).

The changes [were made in 2009](https://github.com/Komodo/KomodoEdit/blame/8865f7249de2715c648b6aebc37b0f00b6466214/src/chrome/komodo/content/bindings/views-buffer.p.xml#L1169), and it's not immediately clear to me what didn't work correctly then or whether the timeout is the most appropriate solution to that problem. 

*Concerning the flicker issue in particular*: reducing the timeout delay to 5ms (from 50ms) made a visually significant reduction to the flicker. Even in the extreme case of holding down the key to force a repeat, the shorter delay made the problem surprisingly less noticeable.

**Comment by ervumlens** [comment]
I wrote down a few more details on [my fork's issue](https://github.com/ervumlens/KomodoEdit/issues/9), in case you're morbidly curious.

**Comment by Naatan** [comment]
Thanks for digging into that @ervumlens ! I just spoke about it with Mitchell and he thinks its too risky to fix this for the upcoming build, as Komodo does a lot of things with Scintilla under the hood. We'd need to test over a longer period of time whether removing that delay causes any nasty issues that may not be immediately obvious.

So we'll definitely look into this, just not for 9.2.

**Comment by ervumlens** [comment]
Good plan, and thanks to both of you for the quick update. 

Without knowing the original motivation for the `setTimeout` call, it's hard to know the risks involved in pulling it. :confused:

**Comment by mitchell-as** [comment]
Labelling this "Minor" because fixing this requires removing the 50ms timeout, which dates back to forever ago and it's really unclear what would happen if we removed it. Therefore this issue is very likely to remain unresolved.

**Comment by Naatan** [comment]
Given the current timeline it wouldn't be a bad idea to implement this now and essentially have months to see if there is any fallout. Reducing the timeout would also make typing feel more responsive I imagine?

**Comment by mitchell-as** [comment]
Not exactly. Typed characters and connected actions show up immediately. UI updates like styling take 50ms to show up.

**Comment by Naatan** [comment]
Gotcha. Still, given the timeline we're working with I wouldn't be opposed to trying this out. Nows as good a time as we'll ever have.

**Comment by Defman21** [comment]
I'd want to test the version with decreased timeout. Some sort of a preference available from sdk/ko/prefs module would be very appreciated.
