### ISSUE TITLE
Download link not working

### ISSUE THREAD

**Issue by DazFather** [Komodo/KomodoEdit#3960]
### Short Summary
Missing/Wrong download link or button in the Komodo web page and/or GitHub repo

### Steps to Reproduce
1. go to Download's section of the README.md of this repo and click on:
 "[download Komodo Edit here](https://www.activestate.com/komodo-ide/downloads/edit)"
2. the page automatically redirects to: https://www.activestate.com/products/komodo-edit/
3. Download does not start and on the page is missing any button or link to download "KomodoEdit" but only "KomodoIDE"

### Expected results
Download to start when link is clicked or to find a button to start the download on the web page

### Actual results
A page that holds only a comparison between "KomodoIDE" and "KomodoEdit" with the only possibility to download the IDE version

### Platform Information
Project: *Komodo Edit*
Browser tested: **Chrome, FireFox**
OS: **Windows**

**Comment by th3coop** [comment]
https://downloads.activestate.com/
There you go.  I'll update the README
