### ISSUE TITLE
Russian characters are not printed

### ISSUE THREAD

**Issue by Fox1567** [Komodo/KomodoEdit#3963]
### Short Summary
When you enter Russian characters, squares are displayed.
code table: UTF-8

### Platform Information
os Windows 7 x64 rus
Komodo-Edit-12.0.1-18441
Komodo-Edit-11.1.1-18206

**Comment by th3coop** [comment]
@Fox1567 , please provide a code sample.

**Comment by th3coop** [comment]
FYI, Komodo IDE is no longer under development so no fix will be in coming but I can try to help figure out why this isn't working for you when it works for other Russian users.  I'm guessing file encoding.  I just try switching encoding on the file to see if any work properly.

**Comment by Fox1567** [comment]
Thank you all. The problem is solved.
The font in Comodo did not support Cyrillic.
