### ISSUE TITLE
dark window theme problem: checkboxes in grid view appear black

### ISSUE THREAD

**Issue by ervumlens** [Komodo/KomodoEdit#398]
**Problem**
Checkboxes in tables are black. This is hard to see on a dark background. Visually it's a big deal, but I've only seen these kinds of tables in two out-of-the-way places (below). 

> Komodo Edit, version 9.1.0, build 15798, platform linux-x86_64.
Built on Sat May 30 05:22:08 2015.

**Preferences: Code Intelligence**
3 boxes checked in this image.

![image](https://cloud.githubusercontent.com/assets/13005338/8513198/a24e0b10-2326-11e5-8b3f-d8ef124b0be1.png)

**Preferences: Languages**
4 boxes checked in this image.

![image](https://cloud.githubusercontent.com/assets/13005338/8513205/de4ad2ce-2326-11e5-82e4-0b12335032c4.png)

**Comment by mitchell-as** [comment]
This issue has to do with the way Mozilla renders checkboxes in trees. Currently, images must be used, as native checkboxes cannot be drawn (see https://bugzilla.mozilla.org/show_bug.cgi?id=462618).

As far as I can tell, all of Komodo's skins with the exception of Abyss are not full skins, meaning there is nothing but the default, black checkbox. Thus, when setting the GTK theme's window background color to dark, even though Komodo tries to autodetect a skin for your dark background, it still cannot use anything but black checkboxes. The only solutions I see are us developing a new [partial?] skin that supplies different colored checkboxes, or you (@ervumlens) using the Abyss skin.

@Naatan @cgchoffman do either of you have any additional input? Perhaps I'm off the mark here.

**Comment by ervumlens** [comment]
Thanks a lot for the update. 

Would it be possible to use [the Stylish add-on](http://komodoide.com/resources/addons/jasonbarnabe--stylish/) to change the checkboxes locally? I'm not familiar with it, but if it sounds like a feasible option, I'll look into it.

**Comment by ervumlens** [comment]
Oops, never mind.

![image](https://cloud.githubusercontent.com/assets/13005338/8656957/60003d56-2960-11e5-8518-ebcf815104f3.png)

**Comment by Defman21** [comment]
Ahh, build Stylish for yourself. Stylish is compatible with Komodo 9.*, but the author did not update the release: https://github.com/JasonBarnabe/stylish/commit/381d6d3cf2eae98a14cba81901cc91ca19f4ee64 - the fix, https://github.com/JasonBarnabe/stylish/compare/2.0.2...master - commits since the latest release.

**Comment by ervumlens** [comment]
Thanks, @Defman21 :+1: 

**Preferences: Code Intelligence**
3 boxes checked in the image.

![image](https://cloud.githubusercontent.com/assets/13005338/8657426/239335fa-2963-11e5-86f1-1e974714f461.png)

**Preferences: Languages**
4 boxes checked in this image.

![image](https://cloud.githubusercontent.com/assets/13005338/8657456/458f9298-2963-11e5-8c0b-416d44adc460.png)


I'm satisfied with this solution and I think there is no better option available.

Feel free to reclassify this issue as not-a-bug and close.

**Comment by Defman21** [comment]
This has been fixed in 10.
