### ISSUE TITLE
v9.0.0 Publishing context menu grayed out when local path has spaces

### ISSUE THREAD

**Issue by dallmon** [Komodo/KomodoEdit#40]
To recreate:
1. Plug a USB thumb drive into a Mac OS X machine.
2. From a terminal "sudo /usr/sbin/diskutil rename /Volumes/<usb_name> name\ with\ spaces".
2a. It will respond with something like "Volume at disk04 renamed to name with spaces"
3. Go to Preferences->Users and right-click your user. Select "Advanced options".
4. Change your user directory to the USB drive by using the "Choose" button to select it.
5. Restart the computer and build a project, Server pref, and Publishing pref.
6. Right-click on any file in the "Places" panel. Select Publishing->Push - it will be grayed out.

**Comment by dallmon** [comment]
The file icons are present when there are spaces in the path, but the little flags beside them are not. I only noticed that because they are there after removing the spaces from the path.

**Comment by cgchoffman** [comment]
Fixed b3f7bf30079
