### ISSUE TITLE
New type of fold indicator controls

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#400]
Can you add a new type of fold indicators to see open/close brackets like on this screen?
![scr](https://cask.scotch.io/2013/12/sublime-flatland.png)

Like if a fold is opened - it should looks like on the screen, if it's closed - it should looks like `{}`

**Comment by Naatan** [comment]
I'll mark this as PRs welcome, in that I'd be happy to review a PR for this but I don't feel it's really worth putting time into as its very subjective and I honestly don't see it adding much value. Happy to discuss if you disagree.

**Comment by Defman21** [comment]
Well, I'll try to play with that and If I'll get the result - I'll send a PR.

**Comment by Defman21** [comment]
@mitchell-as this feature requires a patch to Scintilla? I don't see anything related to fold indicators in `KomodoEdit/src/` folder.

**Comment by mitchell-as** [comment]
@Defman21 No this will not require a patch to Scintilla. What you'd do is redefine the fold markers `SC_MARKNUM_FOLDEROPEN` and `SC_MARKNUM_FOLDERTAIL`. This may look something like

    scimoz.markerDefine(scimoz.SC_MARKNUM_FOLDEROPEN,
                                           SC_MARK_CHARACTER+'{'.charCodeAt(0))
    scimoz.markerDefine(scimoz.SC_MARKNUM_FOLDERTAIL,
                                           SC_MARK_CHARACTER+'}'.charCodeAt(0))

**Comment by mitchell-as** [comment]
Relevant Scintilla doc: http://scintilla.org/ScintillaDoc.html#Markers

**Comment by Defman21** [comment]
Thanks :)

**Comment by Naatan** [comment]
@mitchell-as so to have these be dependant on the language/context is pretty much impossible (or rather, infeasible given the time investment required) I assume?

**Comment by Defman21** [comment]
@Naatan something like "{" for PHP, "+/-" for Python, etc.?

**Comment by Naatan** [comment]
Right, or even for PHP you could also fold on arrays I believe. Point being the `{` fold indicator would not always be correct.

**Comment by mitchell-as** [comment]
@Naatan Well if Komodo provides an event we can listen for when a language is set/changed, then you can run the `scimoz.markerDefine()` routines with language-specific markers. I don't think that would be infeasible. I don't know of such an event though.

**Comment by Naatan** [comment]
Interesting, I'm gonna have a look at this for 10. See if it's feasible in that timeframe.

**Comment by mitchell-as** [comment]
Closing this. There are very few cases where this might be helpful, as many languages have multiple fold points, but Scintilla only has one marker for fold open points and one marker for fold close points. For example, PHP can fold on '{' and '[', but only one fold marker can be shown. Picking '{' as a fold marker when folding on '[' is obviously counter-intuitive.
