### ISSUE TITLE
Mac: Komodo reacts pretty slow after switching windows

### ISSUE THREAD

**Issue by nopenopenope** [Komodo/KomodoEdit#402]
Hi guys,

I'm experiencing a bug where Komodo always need several seconds to regain "focus", when I tab out and back in. This slows down my whole coding experience and speed.

I'm using Komodo Edit 9 on Mac and Linux and on both there are lags as soon as I go out and back in the programm. :(

Any ideas on this? I've read on an old thread that this is a known bug, but it was a 2 year old bug so I assume you may not be aware of this anymore.

Cheers

**Comment by Naatan** [comment]
Thanks for reporting. This is tracked in #70, a workaround is described there as well.
