### ISSUE TITLE
Editor: marking a latin-1 Umlaut does not mark, replace prints "xC3"

### ISSUE THREAD

**Issue by oehhar** [Komodo/KomodoEdit#403]
With Kommodo Edit 9.1.0 on Win 8.1 64bit GER:
A TCL source file coded in latin-1 with Umlauts.
- load the file
- place the caret in front of the Umlaut ("ü" in this case).
- Press SHIFT-Right to mark the Umlaut
-> there is no selection shown
- If a key is pressed ("u" on the sample picture), the display is as follows: 

![kommodo_latin1](https://cloud.githubusercontent.com/assets/12413997/8544159/44e76d4e-24a3-11e5-94df-62e9f8945034.png)

I tried to make this reproducible and extract a file - no success.
If you mark and unmark several times, le phenomenon disappears. It is more like "a mode".
But the "c3" gives a hint, that the characters are internally represented by utf-8, as the utf-8 representation of "ü" is "c3bc". So there seams to be a mismatch, that the cursor thinks there are two characters, selects the second invisible one and replaces it. The "c3"-part remains and is shown.
There seams to be an internal counter of positions which gets out of sync...

Sorry, not more info...

**Comment by oehhar** [comment]
It has something to do with the search results.
If a found umlaut in the "Find Results 1" window is pressed, the cursor is positionned between the characters.

**Comment by oehhar** [comment]
This ticket widget is really stange. In one of two cases it says "Something went wrong with that request. Please try again.
I am obviously the wrong person using this....

**Comment by Naatan** [comment]
I cannot reproduce this. Can you provide a test case (sample code)?
