### ISSUE TITLE
Search failure(s) with complicated strings

### ISSUE THREAD

**Issue by datamafia** [Komodo/KomodoEdit#404]
Summary:

When searching in code using complicated string(s) (like ```something.anothter.stuff['key'] = 'value'```) search fails.

To replicate:

Open attached py file and search string per comments and screenshot.

Produces:

No search results despite the target string appearing 2x in the doc

Expected:

Search result highlighting 2 matches on string

Theory:

My suspicion is that [square brackets] are messing with the JS regX. Just a theory.

The following link contains a test file and screenshot of the problem.
https://drive.google.com/file/d/0B_qwTJosdPkiSzBZY1F2X2VqRkk/view?usp=sharing

Komodo IDE, version 9.1.0, build 87337, platform macosx. Built on Fri May 29 20:57:45 2015.
OSX 10.10.2

**Comment by cgchoffman** [comment]
I can't reproduce this.  Komodo found the strings just fine for me.

String I searched:
```PatientTicket.objects.filter(pk=ticket_id).first()```

I can see from you screenshot that you have regex selected in the options for the find.  Try turning that off.

**Comment by datamafia** [comment]
Thx, that works, new UI is quite the fight for me in this version.

**Comment by Naatan** [comment]
To be fair that checkbox has always been in that place. I think it says something about the "old" UI that you didn't notice it, something the "new" UI can fix .. ;)
