### ISSUE TITLE
Commando: Request for toggle functionality (show/hide Commando)

### ISSUE THREAD

**Issue by ervumlens** [Komodo/KomodoEdit#413]
I like Commando.  I like it so much that I often open it before I even know what I'm going to do with it. Sadly, I have to close it when I don't really need it open.

There are two ways (that I know of) to close Commando without running something: click away or `Esc` out. Being a keyboard guy, I'd rather not use the mouse to close something that I opened with the keyboard. That leaves me with the "escape" route.

**First Problem**
I don't immediately know how many times I have to hit escape to close Commando. It's 3 presses if I'm in a scope with a previous command, 2 with a scope and no command or no scope with a command, etc. I end up just mashing on the button until I don't see Commando. :pensive:

**Second Problem**
 Commando opens in my last scope with my last command. Hitting escape to close Commando means losing my command and my scope. :disappointed: 

**Enhancement Request**
I would like to request one of the following enhancements: 
1. The `cmd_showCommando` command will close Commando when Commando is open, *or*
2. A new command, maybe `cmd_toggleCommando`, will open Commando when it's closed and will close it when it's open.

The first option is the least intrusive but some may not approve of a `show` command hiding something. 

The second option is more work to program, includes some duplication of processes, and requires me to remap my Commando binding... Okay, the second option is just here so that I can save I provided two options. 

What are your thoughts, thoughtful people?

**Comment by Naatan** [comment]
I like this idea, I had toyed around with a "hold ESC" to close commando option to get around the history issue, but it didnt feel intuitive to me. Making showCommando a toggle is a good compromise and probably more intuitive.

**Comment by ervumlens** [comment]
I'm glad you approve. I think it also keeps Commando nimble, which is important for commandos. :guardsman:

It may be worth implementing on the `cmd_focusQuickCommando` as well, since it appears to follow the same general rules as pop-up Commando. Whatever you think is best.
