### ISSUE TITLE
Display corruption

### ISSUE THREAD

**Issue by brenthuisman** [Komodo/KomodoEdit#415]
Does anybody else have this sort of display corruption?

![komodoeditcorruption](https://cloud.githubusercontent.com/assets/2943652/8646337/49762444-294f-11e5-9a04-8e0767d0a059.png)

It pops up fairly regularly, too often to ignore. I am not sure what causes it, it does not seem to be related to my use or certain actions or functions. Once it happens, the corrupted area is influenced by the position of the cursor, but not in a way I've been able to predict. I've no plugins or addons. The fix is either to minimize-maximize the window, but more often to restart the program (and then sometimes it immediately has it again).

The strange thing is, this occurs on both Windows and Linux (which I run in a VM and do most of my work on). My second machine, Windows, also has it. Only Komodo Edit shows this corruption, no other program. I've tried v9, v9.1, a few nightlies, all the same.

Pity, because I really like the program ;)

**Comment by Naatan** [comment]
Could you please explain what the corruption is? I don't see anything in your screenshot that looks particularly alarming.

**Comment by brenthuisman** [comment]
Line 1-17 show the contents of line 17. The actual text is not shown, unless I either move the cursor up. Changing to another open file usually will have a similar problem: either duplicate a certain line, or leave lines blank. It's a very weird issue, but since it exhibits itself on different OSes and different machines, I do not think the problem is with my systems.

**Comment by Naatan** [comment]
Ahh, that's very odd. Are you able to reproduce the issue or does it happen randomly?

@mitchell-as this mean anything to you?

**Comment by brenthuisman** [comment]
There is no specific set of steps that triggers it as far as I've been able to uncover. It seems random. But often (I can't get 5 minutes of work done without have to restart Komodo).

Date: Mon, 13 Jul 2015 09:42:04 -0700

**Comment by ervumlens** [comment]
@brenthuisman -- A few of questions, if you don't mind.

1. What programming language do you typically work in when you see this error?
2. Do you use any (and I mean *any*) Komodo Edit macros or toolbox commands during these sessions?
3. Just for the record, what versions of Windows and Linux are you using?
4. Are these English-language OS versions? (Sorry if this sounds crass. It's not quite what I want to ask, but I can't think of the right wording.)

**Comment by brenthuisman** [comment]
No problem ;) I hope I can help fix this.

1) The effect is confined to a particular language (it just seems some character-level corruption of the text view for lack of a more precise description). Off the top of my head I've edited markdown, python, shell and C++ files.
2) Nothing, out of the box.
3) Windows 7 (twice), Ubuntu Linux 15.04
4) All of them are.

Date: Mon, 13 Jul 2015 10:52:40 -0700

**Comment by Naatan** [comment]
Could you try using a clean profile? https://community.activestate.com/node/15233

See if the issue still reproduces then.

**Comment by brenthuisman** [comment]
I did so (deleted ~/.komodoedit and ~/.activestate). I've seen some corruption thrice since, once on a python file, twice on tex. Attached a screenshot.
![more-corruption](https://cloud.githubusercontent.com/assets/2943652/8696362/f7039496-2aeb-11e5-83c6-54580275406c.png)

**Comment by brenthuisman** [comment]
Forgive me for including this 5MB gif (hey, it's the first one I created), but I thought that some dragging across text (markdown) would should you better how unusable the software is when the effect occurs (which is actually basically every minute). 
![output](https://cloud.githubusercontent.com/assets/2943652/8718659/734aef94-2ba6-11e5-99f8-5699d231daad.gif)

**Comment by cgchoffman** [comment]
Could you try turning off word wrap to see if that might be causing the issue?  
Also, could you explain exactly what you're doing in the gif?  It may be obvious to you and I THINK I know what you're doing but ambiguity is not our friend when tracking a bug :)

**Comment by brenthuisman** [comment]
I'm trying to select a region, and you see me drag the cursor across the text area as it flickers. You suspect word wrap might be it? I can't quite live without that you see ;) I've tried browsing about a few files without it, but of course you'll always see that all goes well when you're looking for trouble.

**Comment by ervumlens** [comment]
So the text editor works without word-wrap then? No problems selecting text, etc.?

Digging a little deeper here: Is the minimap turned on in your gif? Is that typical when you see these problems (i.e., always)? If so, could you try turning word-wrap *on* and minimap *off*?

**Comment by Naatan** [comment]
> I'm trying to select a region, and you see me drag the cursor across the text area as it flickers. You suspect word wrap might be it? I can't quite live without that you see ;) I've tried browsing about a few files without it, but of course you'll always see that all goes well when you're looking for trouble.

No one is asking you to live without word wrap :) But we need to narrow down the issue. Please try using Komodo without word wrap just for a short while, so that you can determine whether that works around the issue. If we know word wrap is a trigger then we at least have something to work with.

**Comment by brenthuisman** [comment]
It's quite hard to diagnose, because I have no reproducible way of triggering this. But I just ran some tests that showed that indeed after having the corruption, switching word-wrap off (which did not remove the corruption) and then minimizing and maximizing (causing the corruption to be gone) resulted in a state where it did not return for the time that I tested. Turning word wrap back on could trigger the corruption again (occasionally ;) ).

Also, I have the minimap enabled at all times.

**Comment by Naatan** [comment]
I'll try using the minimap for a while to see if I can repro. I generally have word wrap enabled also but have not seen this issue.

**Comment by brenthuisman** [comment]
I just worked a little with the minimap off and word-wrap on, and I again had some corruption.

**Comment by Naatan** [comment]
Sadly we have not seen this bug pop up anywhere. If you find any more info to narrow down the issue please let us know, until then there is no point in us tracking this unfortunately. I'm sorry.
