### ISSUE TITLE
Update the screenshot in the readme

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#420]
I think it would be better if the screenshot will contain how Komodo looks in Windows, Linux and OSX, like here: ![screen](http://komodoide.com/assets/images/screenshots/featured/crossplatform.png)

**Comment by Naatan** [comment]
Making screenshots is a long involved process. Sorry but I really don't see much merit in dedicating time to update a github screenshot unless we had one ready to use. I dont think the one you linked to is a better option. 

The intend with the current screenshot was to show off Komodo's customizability, which I think it does well.

I appreciate the suggestion, but we simply have bigger fish to fry atm.
