### ISSUE TITLE
dedenting block causes the editor jump to line #1

### ISSUE THREAD

**Issue by yargolan** [Komodo/KomodoEdit#421]
Instead of showing the relevant block being "back idented"

**Comment by Naatan** [comment]
Can you provide steps to reproduce, with a test case?

I have no issues dedenting blocks.

**Comment by yargolan** [comment]
That usually happens to long (>250 lines) files.

Usually, on xml files.

Paste a text block (maven plug-in in my case)

dedent the pasted block - the line jumps to line #1

On Wed, Jul 15, 2015 at 4:43 PM, Nathan Rijksen <notifications@github.com>
wrote:

> Can you provide steps to reproduce, with a test case?
>
> I have no issues dedenting blocks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Komodo/KomodoEdit/issues/421#issuecomment-121621019>.
>



-- 


--------------------------------------------------------------------------------------

**Comment by Naatan** [comment]
Could you provide a file on which you can reproduce this?
