### ISSUE TITLE
Open subscope is expandable

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#422]
Causes this error:
```
[2015-07-15 13:52:09,447] [ERROR] commando: Subscope does not exist: undefined
Traceback from ERROR in 'commando' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:261:27
    this.setSubscope@chrome://commando/content/sdk/commando.js:1129:1
    this.expandResult@chrome://commando/content/sdk/commando.js:657:9
    onExpandResult@chrome://commando/content/sdk/commando.js:342:9
    onKeyNav@chrome://commando/content/sdk/commando.js:187:17
```

**Comment by Naatan** [comment]
Please explain your problem more accurately? Steps to reproduce? I've no clue what is going on here other than that it relates to commando and subscopes.

**Comment by Defman21** [comment]
Open Commando with any scope.
Press right arrow, select "Open" by arrows. Press right arrow again. Commando will try to open "Open" item and log the error in the log.

**Comment by Naatan** [comment]
I see, thanks. Fwiw the PR you committed does not fix the issue, it merely works around it. 

Thanks for reporting!

**Comment by Defman21** [comment]
So I should close the PR?

**Comment by Defman21** [comment]
You marked this as a bug but as I can see it's the right behaviour when the scope does not exists.
https://github.com/Defman21/KomodoEdit/blob/21ab9b21bfa4abba6a7a6b4b9900f3f238a6f796/src/modules/commando/content/sdk/commando.js#L1176
In the case with "Open" it's actually does not exists and "Open" should have ability to expanding (making a new subscope if I understand this feature properly).
So I'm interesting what is the bug in this case? I thought you just forgot to set `allowExpand: false` for "Open": https://github.com/Komodo/KomodoEdit/blob/master/src/modules/commando/content/sdk/commando.js#L578 (for example you set this thing to "Favourite" action: https://github.com/Komodo/KomodoEdit/blob/master/src/modules/commando/content/sdk/commando.js#L594)

**Comment by Naatan** [comment]
My bad, you're totally right. I had misread your commit.
