### ISSUE TITLE
Modification to "Monitor Remote Files for Changes" feature/bane-of-my-existence

### ISSUE THREAD

**Issue by thebeline** [Komodo/KomodoEdit#426]
I would like to propose three enhancements for the Remote Changes feature in Komodo that may make the whole experience more enjoyable (and useful):

1.  Please introduce a timer that will only trigger a check after X seconds of a de/re-focus event, and not on EVERY re-focus event.  Alt-Tabbing to respond to an IM, and having the application lock up when I only de-foscus for 5 seconds is TERRIBLE user experience.
2.  Please time the process that checks in the background, and if it exceeds a threshold (say, 10 seconds overall, or more than 1 second per file) prompt the user to abort the process.
3. Please only block editing of yet-to-be-checked files.  Indicate the file is locked by greying out its tab and editor space.

As it stands, if your computer has an internet connection, Komodo will check the file.  This locks the entire application (editing all files, the file menus, browsing the file system, everything).  Further, if your internet connection is experiencing congestion, this poses the posibility of hanging the entire application until each remote check times out.  Even if the connections do not time-out, I regularly code with many files open, and even when my network is not completely congested, this can mean 30-60 seconds.

Please, thank you, and for the record, Komodo ROCKS!  I have disabled the remote check at this time, which allows me to work fine, but I would like to use this feature, and frankly, even one of the above enhancements would make this feature usable, two of them would be perfect, and all three would be the cats meow.

**Comment by cgchoffman** [comment]
@thebeline thanks for the suggestions.  I appreciate the effort you put into this report.  Before I answer, are you referring to issue #70?

**Comment by thebeline** [comment]
Yes, and I am using that workaround.

I would also like to add that I would kind of like the part about locking the related file edit-pane, instead of the whole application, for saving as well.  It seems there are some hard-blocking operations that really make the application difficult to work with when on a sub-par internet connection.

**Comment by cgchoffman** [comment]
@thebeline thanks for clarifying.  This shouldn't have been created as a separate bug.  These are suggestions to fix issue #70 so there fore can go there.  Having said that, once we fix the regression of issue #70 your suggestions won't be needed, though again, they are appreciated.  We do not purposefully block the UI or any file.  That is the bug.  No blocking should occur once this is fixed.  Komodo simply tells you a remote file has changed so you can update if you want.

On that note, I'll close this ticket.

**Comment by thebeline** [comment]
@cgchoffman - Thank you for your timely reply.  I just re-read #70 to confirm: There is no mention in #70 that this is a confirmed bug or that it is being resolved, just some debugging and a workaround.  Glad to hear that it is fubar all-around.  Looking forward to the fix.

**Comment by cgchoffman** [comment]
Absolutely fair.  Thanks for pushing us!

**Comment by thebeline** [comment]
You guys kick all of it.  Keep it up.  Do you take feature requests?

**Comment by thebeline** [comment]
Generally speaking, for new things?

**Comment by Defman21** [comment]
>Do you take feature requests?

I'm not an official Komodo developer but yes we take feature requests :) https://github.com/Komodo/KomodoEdit/labels/Enhancement

**Comment by cgchoffman** [comment]
What @Defman21 said.  We totally take enhancement requests...we even take pull request for Komodo Edit ;)  @Defman21 has quite a few in already.
