### ISSUE TITLE
Phantom changes to file preferences: word wrap preference altered when file is open, reverted when closed

### ISSUE THREAD

**Issue by ervumlens** [Komodo/KomodoEdit#430]
Spoiler alert: I include the lines of code that cause the problem (at least in part). 
Also: This may be related in a roundabout way to #175, although the symptoms are different.

**Problem**
If a file has long lines, its file-level preference for word wrapping is changed whenever it is opened. Because it's changed with every open, that file will always open with word wrap enabled no matter what preferences are set, no matter where they are set.

&lt;blink&gt;**The problem is easy to reproduce**&lt;/blink&gt; But because word-wrap bug reports are sometimes spurious, I made sure to include all the obvious gotchas here. 

**Steps to Reproduce &mdash; Part 1**
1. Open Komodo preferences. Ensure that "word wrap" is set to "none."
2. Ensure that "view &rarr; word wrap" is disabled.
3. Create a new project. Open project preferences. Ensure that "word wrap" is set to "none."
4. Create a new, blank file. Close the file.
5. Open the new file's preferences in Places. Ensure that "word wrap" is set to "none."
6. Open the new file again. Copy into it the contents from https://raw.githubusercontent.com/ajaxorg/ace-builds/master/src-noconflict/worker-coffee.js. This file has a few giant lines that make it a good test case.
7. Before closing, open the new file's preferences in Places. Ensure that "word wrap" is still set to "none."
8. Save and close the file. 
9. Open the new file's preferences in Places. Ensure that "word wrap" is still set to "none."
10. Open the new file.

**Expected**
Word wrapping is **disabled** both on the screen and in the file preferences.

**Actual**
Word wrapping is **enabled** both on the screen and in the file preferences. But hey, who cares? It's a new file. :guitar: 

![image1](https://cloud.githubusercontent.com/assets/13005338/8738655/2f2ad1f6-2bf8-11e5-89b3-5aef2b9c6056.png)

**Steps to Reproduce — Part 2**
1. Close the file.
2. Open the new file's preferences in Places.

**Expected**
Word wrapping is disabled.

**Actual**
Word wrapping is, as expected, disabled. :+1:

![image2](https://cloud.githubusercontent.com/assets/13005338/8738775/6dc3d920-2bf9-11e5-90c3-2f5822994800.png)

**Steps to Reproduce &mdash; Part 3**
1. Open the file again.

**Expected**
Word wrapping is **disabled** both on the screen and in the file preferences.

**Actual**
Word wrapping is **enabled** both on the screen and in the file preferences. :-1: We're not a new file any more.

![image3](https://cloud.githubusercontent.com/assets/13005338/8738793/b693da56-2bf9-11e5-9d1e-d62d37435015.png)

**Steps to Reproduce &mdash; Part 4**
1. With the file still open, change the file's "word wrap" preference to "none". Save the preferences.
2. Close the file.
3. Open the file again.

**Expected**
Word wrapping is **disabled** both on the screen and in the file preferences.

**Actual**
Word wrapping is **enabled** both on the screen and in the file preferences. :-1: We're not a new file and we have a preference set.

![image4](https://cloud.githubusercontent.com/assets/13005338/8738901/acd85afe-2bfa-11e5-9667-437cdd68101e.png)

**Code**
[koDocument.py#L644-L649](https://github.com/Komodo/KomodoEdit/blob/ea3d0d28c6544861544300eb653d755626c086eb/src/views/koDocument.py#L644-L649)

This code is always hit when opening a long-lined file, despite promises to the contrary:
```python
        # Bug 93790: If the file is new to Komodo, and has any long lines,
        # where long > 2000 chars, turn word-wrap on
        if hasLongLine:
            self.prefs.setLongPref('editWrapType', True)
            for view in self._views:
                view.scimoz.wrapMode = view.scimoz.SC_WRAP_WORD
```

Some strategic logging shows this to be the case. 

The guard code (not shown) isn't working. As the comments here and elsewhere suggest, the preference change should not occur with a file that has been opened previously.

P.S. I just found another use-case with a similar problem, but not with long lines (I'll comment about it below if I can find a visible error). I suspect there's something broadly wrong with this code.

**Comment by ervumlens** [comment]
Using "view &rarr; word wrap" rather than the file preference doesn't correct the error. In fact, the word wrap menu item sometimes fails:

![image5](https://cloud.githubusercontent.com/assets/13005338/8739523/56a29480-2c02-11e5-820f-7374213b81ad.png)

Note that "word wrap" is not checked, but the text is word wrapped.

**Comment by Naatan** [comment]
Reproduced. This looks like a fun one ..

Thanks @ervumlens

**Comment by ervumlens** [comment]
I'm glad I could help narrow it down. This was the first problem I ran into with Komodo. I noticed Komodo forum posts describing similar problems, so I figured there was no point in logging a bug until I had something useful to share.

Regarding [the intentional, one-time preference change](https://bugs.activestate.com/show_bug.cgi?id=93790): I hope you'll agree that the typical user doesn't expect this to happen.  Would you consider adding a notification or similar to tell the user "Yes, we just turned on word wrap. No, it's not a bug," to mitigate some of the surprise?

**Comment by Naatan** [comment]
@cgchoffman I saw you were looking at this the other day, could you add your findings to the ticket?

**Comment by Naatan** [comment]
@ervumlens I agree a notification would make a lot of sense.

**Comment by cgchoffman** [comment]
I didn't find much to add.  I was messing around, trying to find a way to block that code if the file wasn't new to Komodo but I suspect that that check occurs before that code is hit any way. I didn't have tons of time to look into this.

**Comment by mitchell-as** [comment]
For performance reasons we automatically turn on word wrap for new files when lines of length 2000+ are detected. The problem is that "File Properties" is reporting two different values: one when the file is open, and another when the file is closed. Need to investigate further.

**Comment by tonyattwood** [comment]
Hello,

I'm extremely grateful to you for all you have done, please read my message for you  here  <http://fast.softwarevalueoptimisation.com/e4qxfxuh>

Warmest, tony.attwood@ntlworld.com

**Comment by tonyattwood** [comment]
Hello,
Here is an amazing article that you  may  find really useful,  olease read it  here <http://fair.seocostaricaexperts.com/e4udv>
Typos courtesy of my iPhone, tony.attwood@ntlworld.com
