### ISSUE TITLE
vi mode: editor view doesn't scroll down when selecting down

### ISSUE THREAD

**Issue by trentm** [Komodo/KomodoEdit#436]
This is with Komodo IDE, version 9.1.0, build 87337, platform macosx.

Repro:
- switch to Vi keybindings
- type 'V' to enter line selection mode
- select down repeatedly with 'j'

When selection hits the bottom of the view port (actually the y-slop line), the editor view should scroll up.

The same problem exists when scrolling up.

**Comment by Naatan** [comment]
I'll get our Vi guy to have a look at this. oh wait ..

Kidding aside, was able to easily reproduce this, will have a look.

**Comment by twhiteman** [comment]
Probably needs a ```scimoz.scrollCaret();``` after the *updateVisualModeSelection()* call:
https://github.com/Komodo/KomodoEdit/blob/master/src/chrome/komodo/content/keybindings/viKeyBinder.js#L804
