### ISSUE TITLE
Fetch CSS files in HTML files to provide auto-complete for classes and ids

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#438]
http://forum.komodoide.com/t/what-css3-keywords-you-want-to-see-in-komodo-auto-complete/1805/6?u=defman
Komodo should scan CSS files in a HTML file and parse them to provide auto-complete for easier HTML editing.
Original request: 
>You also should add automaticly fetch rules from included css files in page. It helps auto-comlplete html code.

**Comment by cgchoffman** [comment]
Please add the actual request and specs here.  Don't expect the dev who takes this on to click and scroll through a forum post to extract .

**Comment by Defman21** [comment]
Should looks fine now :smiley:

**Comment by Defman21** [comment]
Fixed in 586364bb8747b9d1c320ea37b80b5fbbff86d645
