### ISSUE TITLE
Saving opened files’ changes in buffer #Enhancement

### ISSUE THREAD

**Issue by Nes-si** [Komodo/KomodoEdit#439]
Please, add feature (optional) to keep changes that was maked in open files. I mean that a user never sees a dialog "Select files to save" on quitting the app. All changes will be saved in a temp buffer, and if a user runs Komodo edit again, he show all himself changes. Also it apply to new documents that still not saved in a file.
This feature is available in many text editors such as Notepad++, Sublime Text, TextMate, etc.

**Comment by ervumlens** [comment]
Hi @Nes-si , does the description in issue #350 sound like what you're looking for?

**Comment by Nes-si** [comment]
@ervumlens, yes.

**Comment by cgchoffman** [comment]
Thanks @ervumlens and @Nes-si, I'll close this in favour of #350
