### ISSUE TITLE
Spastic Code intel Throbber

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#444]
I'm not 100% sure how to reproduce is as I don't know why my code intel was reacting like this but when Komodo starts to scan a large code base (drupal for example) the code intel throbber DOM element will flash on and off in the DOM, and in notifications you will see 10s of `scanning one directory` messages popping up.

Could fix this in a few ways but I think the easiest would be to put the throbber on the left of the Syntax Checking indicator so the throbber and appear and disapear without pushing things around in the status bar.

**Comment by Naatan** [comment]
Moving it wont do much, as it would still push the other elements (position indicator, language selection). Best we could do is reserve the space it needs.
