### ISSUE TITLE
FR: Codeintel server

### ISSUE THREAD

**Issue by cweagans** [Komodo/KomodoEdit#446]
Right now, there are two options to interact with the OOP codeintel (as installed by `pip install codeintel`): 

1. Run the `codeintel` command and pass your input to the program that way, or
2. Run `codeintel` and pass it a host and port to connect back to.

I'd like a way to tell Codeintel to just open a local server on some specified port that my editor can connect to and pass commands.

Is there already a way to do this? If not, any chance you're planning on implementing it?

**Comment by cweagans** [comment]
cc @Kronuz

**Comment by Naatan** [comment]
The codenintel version on pypi is maintained by @Kronuz, we have no hand in that.

That said we are looking into modularizing codeintel better, but that's still a little ways off.
