### ISSUE TITLE
Allow HTML5 for language PHP

### ISSUE THREAD

**Issue by mpopp75** [Komodo/KomodoEdit#447]
If language PHP is selected, syntax checker & highlighter recognizes HTML as well but currently not HTML5.

I think with HTML5 being a W3C Recommendation now, syntax checker & highlighter should allow all HTML5 also if language PHP is selected.

**Comment by mitchell-as** [comment]
Sorry, I cannot reproduce this. When I select PHP and use the "<article>" tag, I do not get a syntax check error. When I switch to HTML (not HTML5), I get an error, but when I switch back to PHP, the error disappears. Therefore I conclude that HTML5 is supported by PHP.

Is there any other information you can provide that would help me reproduce the issue? Thanks.

**Comment by mpopp75** [comment]
This screenshot may explain. This tag shouldn't say <video> is not recognized, same for other HTML5 tags.

![php](https://cloud.githubusercontent.com/assets/4977998/8858476/f2c82ef4-3177-11e5-8189-70536c5c852b.png)

**Comment by Naatan** [comment]
The only way I am able to reproduce that is by setting `Prefs > Syntax > HTML 5` to use html5lib, which should work of course, but doesnt. Thats not the issue you are describing though. Does the syntax checking pass if you use that tag in a html5 doc?

**Comment by mitchell-as** [comment]
Do you have a custom Tidy config file? Komodo uses Tidy behind the scenes for HTML checking.

**Comment by mpopp75** [comment]
If I set the language to HTML5 (bottom right of the screen), I can use all HTML5 tags without syntax check complaining. This is how it also should work if the language is set to PHP IMO.

If I switch to HTML5 as you described, I get this (after clicking Apply). Syntax check still recognizes the &lt;video&gt; tag as error:

![komodoedit](https://cloud.githubusercontent.com/assets/4977998/8859274/a2fb6332-317c-11e5-95f4-ee9b6769c597.png)

I haven't updated any Tidy configuration, so I should have the default configuration.

**Comment by cgchoffman** [comment]
> This is how it also should work if the language is set to PHP IMO

This is how is supposed to work and this is how it's working for myself

> I get an error, but when I switch back to PHP, the error disappears.

As is Mitchell.

I believe this is an issue some where in your preferences since it's working as you expect for myself and Mitchell.  

Could you see what you have set under `Preferences > Languages > HTML: Default HTML Document Type`?

**Comment by mpopp75** [comment]
I just tried creating a new profile (made a backup of the previous one) and now indeed, syntax checker doesn't consider &lt;video&gt; an error anymore when language is set to PHP.

So probably it's really some old setting from a previous version (I've been using Komodo Edit for a few years). Best thing for me to do seems to be transferring my personal settings into a new profile to get rid of leftovers from the past.

If you choose to close the request, I'm fine with it. Thanks for all your feedback!
