### ISSUE TITLE
Perl code intelligence does not recognize logical defined or operator in sub

### ISSUE THREAD

**Issue by asb-capfan** [Komodo/KomodoEdit#449]
The Komodo IDE code intelligence shows some nice tool tips for sub parameter lists. However, when checking a parameter using the logical defined or operator (the double forward-slash //, cf. http://perldoc.perl.org/perlop.html#Logical-Defined-Or), the parameter is not recognized. 
It works with a standard or operator, but this will not account for a 0 as input value (at least, not without workarounds I prefer not to use just to satisfy code intel).

Please find a screenshot of the issue below.

Komodo IDE build info:

    Komodo IDE, version 9.1.0, build 87337, platform win32-x86. Built on Fri May 29 

![wrong-param-listing](https://cloud.githubusercontent.com/assets/131959/8846576/9d5d2b80-3128-11e5-8424-dce4859661e5.jpg)

Here is the code for reproduction:

    #!perl
    
    package MyTest;
    
    use 5.016003;
    use Moose;
    
    sub test_method {
        my $self = shift;
        my $param1 = shift or die('Missing param 1');
        my $param2 = shift or die('Missing param 2');
    } # /test_method
    
    1; # /MyTest
    
    use 5.016003;
    use strict;
    use warnings;
    
    my $app = MyTest->new;
    $app->test_method(
    
    say ">done";
    exit(0);

**Comment by Naatan** [comment]
Thanks @asb-capfan - we'll look into this!
