### ISSUE TITLE
Go to definition tends to stop working after Komodo had been in use for a while

### ISSUE THREAD

**Issue by shelldweller** [Komodo/KomodoEdit#451]
There are no specific steps to reproduce this. Just using Komodo for awhile often makes "go to definition" stop working. Neither Command+Click nor clicking on "go to definition" form contextual menu works. (Sometimes "go to definition" is greyed out and sometimes it it not). Restarting Komodo makes it work again.

I'm mostly using python and I'm talking about normal Python code (not C extensions).

Build info: Komodo IDE, version 9.1.0, build 87337, platform macosx. Built on Fri May 29

**Comment by Naatan** [comment]
Fairly certain this is the same issue as #297, please check there and see if you can add anything.
