### ISSUE TITLE
HUD notifications rarely work in Xfce and OpenBox (Linux WMs)

### ISSUE THREAD

**Issue by ervumlens** [Komodo/KomodoEdit#456]
Unlike #378, the HUD window is usually missing and I can't find a workaround. 

Note that with the same user on the same machine there is no problem seeing HUD windows on the Cinnamon window manager.

**Problem**
HUD notifications rarely appear in Linux when using Xfce or OpenBox window managers.

**Steps to Reproduce**
1. Create a macro with this code and run it. 

```javascript
require("notify/notify").send("I'm visible!", "projects"); //Any category, doesn't matter.
```

**Expected**
A HUD notification every time the macro is executed.

**Actual**
Sometimes a black box flashes on the screen (too fast for a screenshot). Often nothing happens. Very rarely the notification appears as expected.

**Comment by Naatan** [comment]
I've added options to disable opacity and animations on notifications, this should hopefully solve these issues.
