### ISSUE TITLE
Highlighted text issue

### ISSUE THREAD

**Issue by Cegard** [Komodo/KomodoEdit#457]
While writing a .py file the editor highlights the use of the sentence "yield from ..." as if it was an invalid syntax when it is not (I know one can use pylint or pep8 for this purpose, but still it would be nice to see it fixed).

Thanks.

**Comment by Naatan** [comment]
I cannot reproduce this. Please ensure you are using Python 3 (not Python) and you are using 'yield' inside a function.

**Comment by Cegard** [comment]
Here's an example.

![proof](https://cloud.githubusercontent.com/assets/4041082/8913242/13df2598-3498-11e5-9b0a-bb308c4188a7.png)

**Comment by Defman21** [comment]
You're using Python, not Python 3.
