### ISSUE TITLE
"New Project" throws error

### ISSUE THREAD

**Issue by retorquere** [Komodo/KomodoEdit#458]
Freshly installed KE 9.1.0 build 15798/linux x64. When choosing "New Project" from the meu presented after start, and picking a filename for my komodoproject, I get the error as attached.
![snapshot1](https://cloud.githubusercontent.com/assets/132108/8895760/55badb00-33e5-11e5-8cee-2d52ee7febfe.png)

**Comment by Defman21** [comment]
I'm not able to reproduce it, but I'm on dev branch using Komodo Edit, version 9.10.0-devel, build 15951, platform linux-x86_64.
Built on Wed Jul 15 15:49:42 2015.
Any steps to reproduce? Maybe you're in a specific folder where you don't have write access?

**Comment by retorquere** [comment]
It happens for any folder I've tried so far.

**Comment by Defman21** [comment]
I've tried to reproduce it, no luck with that. We're talking about the "New Project" button on start page? (When you have no files opened)
![illuminati](http://i.imgur.com/ahGHCta.png)

**Comment by Naatan** [comment]
Could you explain exactly what steps you are taking to create the project? And whether you are saving it to a local disk or a remote/mounted location?

**Comment by ervumlens** [comment]
FWIW, I suspect a bad install.

I'm able to reproduce the error, even down to the same line number,  if I remove the file `~/Komodo-Edit-9/lib/mozilla/components/koProject.py`. 

```
[Exception... "Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance]"  nsresult: "0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE)"  location: "JS frame :: chrome://komodo/content/project/projectManager.js :: projectManager.prototype.newProject :: line 522"  data: no]
                                         Mon Jul 27 2015 11:52:39 GMT-0500 (CDT)
```

**Comment by Defman21** [comment]
Lol, if you remove the file which does everything related to the projects - then of course it won't work :smile:

**Comment by ervumlens** [comment]
I'm glad my experiment could get a laugh. :smile_cat: But you read the original error message, right? You looked up the point of error in the code and noticed that it's failing to load the XPCOM component before it even saves the project? Doesn't that suggest to you a problem with the install?

**Comment by Defman21** [comment]
It didn't and I really don't understand why :confused: 
Thanks for digging in it @ervumlens :+1:

**Comment by retorquere** [comment]
@Defman21, yes, from that screen. 

@Naatan, nothing beyond starting up KE and clicking "New project" and trying to save the suggested file anywhere. Only local drives tried.

@ervumlens: I don't have ~/Komodo-Edit-9. Botched install looks plausible, if I start KE from the console I get this: https://gist.github.com/retorquere/f171f5773740cea64b6d

I installed KE from this PPA: deb http://ppa.launchpad.net/mystic-mirage/komodo-edit/ubuntu vivid main

**Comment by Defman21** [comment]
Please install KE from komodoide.com as the ppa isn't an official ppa.

**Comment by cgchoffman** [comment]
Yes, if there is an issue in the ppa package, please contact the maintainer of that package: https://launchpad.net/~mystic-mirage

**Comment by retorquere** [comment]
I can confirm the download from komodoide.com works without a problem.
