### ISSUE TITLE
Paths listed in Places dropdown are shown in upper-case

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#46]
Reference: https://bugs.activestate.com/show_bug.cgi?id=106308

**Comment by we3geeks** [comment]
Places widget still shows uppercase in 9.0.1...

![ke9-20150420](https://cloud.githubusercontent.com/assets/2390335/7244199/3531de7a-e795-11e4-88eb-363d481508b6.png)

Build info: Komodo Edit, version 9.0.1, build 15745, platform macosx.
Built on Mon Apr 20 17:19:25 2015.

**Comment by Naatan** [comment]
That's by design, all widget header titles are uppercase on OSX. See other widgets for example.

I originally did it that way because that's how Finder was doing it (IIRC), but I see now that they've changed it again. I'll add a new enhancement ticket for this.
