### ISSUE TITLE
Tcl code analyzer incorrectly labels namespace variables as global

### ISSUE THREAD

**Issue by sgeard** [Komodo/KomodoEdit#460]
... and does not label namespace variables when it should. It also does not identify variables in the global namespace as global.
```tcl
namespace eval C++ {
	variable x; # A namespace variable
	proc init++ {y} {
		variable x
		set x $y
		puts "x = ${x}"
	}
}

proc f {} {
	puts "t = $::t"; # Direct reference to a variable in the global namespace
}

proc g {} {
	global z
	puts "z = $z"; # Global vaiable imported into g
}

C++::init++ 5

set z ${C++::x}; # A variable that can be imported globally
set ::t ${C++::x}; # A variable in the global namespace
f
g
```
![komodo_bug_2](https://cloud.githubusercontent.com/assets/13196616/8919104/b902d17a-34b4-11e5-8829-a674ec8f64b5.png)

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoEdit/commit/331bc9f848610e9b1e3bb6bfe6e5c60fa7e4a382.
