### ISSUE TITLE
Ctrl+Del does not work.

### ISSUE THREAD

**Issue by srgloureiro** [Komodo/KomodoEdit#462]
Ctrl+Del does not delete the word at the right. I did not mess with keybindings.

**Comment by Defman21** [comment]
Set the keybinding for `Editor: Delete Word Right` (`Preferences - Key Bindings`, use search to find the command) to `Ctrl+Del` :smiley:

**Comment by Naatan** [comment]
It's definitely set up

https://github.com/Komodo/KomodoEdit/blob/master//src/schemes/Default.p.kkf#L56
https://github.com/Komodo/KomodoEdit/blob/master//src/schemes/Mac.p.kkf#L61

Perhaps you have software installed which is conflicting with this keybind.

Either way, not a bug in Komodo. Please use the forums :) Thanks
