### ISSUE TITLE
Markdown Preview broken in 9.2

### ISSUE THREAD

**Issue by randomsock** [Komodo/KomodoEdit#464]
Since updating to 9.2, the Markdown Preview no longer shows any content.  The split view shows but is always blank.

![komodo-edit-markdown](https://cloud.githubusercontent.com/assets/8095654/8983188/fde8cd46-36bf-11e5-9f11-63f887c2b9fa.png)

Strangely, when I just saved that file (force of habit!) it then appeared but in an additional BROWSER view.  The original Markdown view is still blank.

![komodo-edit-markdown2](https://cloud.githubusercontent.com/assets/8095654/8983192/069a4e88-36c0-11e5-9e9e-1bd8219fd747.png)

**Comment by Naatan** [comment]
Thanks for reporting! Fixed with https://github.com/Komodo/KomodoEdit/commit/b6ce830c0d42ab2926cd8bef0866a779ef520464

**Comment by randomsock** [comment]
Awesome - thanks!  Works a treat.
