### ISSUE TITLE
Toggle Focus mode enabled menu bar silently

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#466]
- View > Enable focus mode

Expect: Focus mode

Actual: Focus mode + menu bar is enabled.

If this is meant to happen then the issue is that it's silently enabled and not disabled when focus mode is turned off.

**Comment by mitchell-as** [comment]
I'm not seeing this in master. My menubar is of by default. Toggling into Focus Mode keeps it hidden and untoggling from Focus Mode also keeps it hidden. Only when I manually enable the menubar does Focus Mode keep it enabled. @cgchoffman Is this still a problem?

**Comment by cgchoffman** [comment]
Yes, I'm not seeing this anymore but I'm seeing a new issue.  I'll file a new bug.
