### ISSUE TITLE
error log gone wild

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#469]
When i start komodo there is nothing wrong, but if i work for a while, komodo eidt hangs on most simple tasks when i open the the error log file it's going wild, the error file is looking like my filezila transfer screen(errors been added every second). i have this problems not after the last 2 update.

I use the sites addon but this one works but ginving also a lot of errors (onlay after the last 2 updates)
<pre>
[2015-07-31 12:36:11,150] [ERROR] console-logger: TypeError: properties is undefined (2) in chrome://sites/content/dinamicTree.js:145
Traceback (most recent call last):
  File "chrome://sites/content/dinamicTree.js", line 145, in 

[2015-07-31 15:00:04,859] [ERROR] console-logger: TypeError: topView.findViewsForURI is not a function (2) in chrome://breadcrumbs/content/breadcrumbs.js:430
Traceback (most recent call last):
  File "chrome://breadcrumbs/content/breadcrumbs.js", line 430, in 

[2015-07-31 15:00:05,233] [ERROR] console-logger: TypeError: ex.stack is undefined (2) in chrome://komodo/content/sdk/logging.js:415
Traceback (most recent call last):
  File "chrome://komodo/content/sdk/logging.js", line 415, in 
</pre>

**Comment by Naatan** [comment]
Could you share the full error log (github gist if its too big)?

Also, please try disabling any third party addons just to see if that makes the errors go away.

**Comment by babobski** [comment]
added the error log as gist
https://gist.github.com/babobski/e8d607951bfed374b904

I will disable third party addons and will come back on the result of it

**Comment by cgchoffman** [comment]
How are you starting Komodo?  Are you starting Komodo from the commandline using `-v`?

**Comment by babobski** [comment]
no just with the button in the widowns taskbar

**Comment by Naatan** [comment]
I see a ton of errors in there referencing one of these addons:

http://community.activestate.com/node/6894
http://community.activestate.com/xpi/jstreedrive

Definitely try disabling all non-default addons to see if that resolves the issue.

**Comment by babobski** [comment]
disabling the addons resolves the extreme amount of errors. 
When testing the only thing giving errors is when you use the breadcrumb navigation it throws error on paths that doesn't exist. renamed the ActiveState folder in the user directory to test but even then the error gets thrown.
<pre>
-- EXCEPTION START --
Error: path does not exist: C:\Users\Administrator\AppData\Local\ActiveState\KomodoEdit\9.2\XRE\icons\fileicons\UnknownSND16.png.forcedAttrs.svg
+ stack
    friendlyError@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:62:1
    ensureExists@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:54:11
    ensureFile@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:47:3
    remove@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:174:3
    _createPngFromSvg/img.onload/<@chrome://komodo/content/sdk/icons.js:586:25
    notify@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/timers.js:40:9
-- EXCEPTION END --
</pre>

complete logfile (pc at home had same problem at work)
https://gist.github.com/babobski/b49b1c1a64fab5162162

**Comment by Naatan** [comment]
You can safely ignore those for now, they should not affect your user experience.

**Comment by babobski** [comment]
I will do
