### ISSUE TITLE
Pane config doesn't persist

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#47]
Combine panes, resize, etc. It all resets on restart.

**Comment by agroszer** [comment]
affects me too

**Comment by Naatan** [comment]
Hmm I can no longer reproduce the actual issue. Anyone have steps to reproduce?

**Comment by Defman21** [comment]
I also can't. Combining tabs, resizing and another stuff works fine to me now (but they doesn't work a couple weeks ago). Tested with just simple restarting and instant OS restarting.

**Comment by Defman21** [comment]
Oops, I find a bug. If you change size of the bottom pane and the height will be smaller than default height - the pane will restore the height to default.

**Comment by Naatan** [comment]
I can only reproduce this when making the bottom pane unreasonably small. Technically a bug but not one that I can imagine many people running into, I'd be surprised if that's what @agroszer is referring to.

**Comment by hobbsd** [comment]
The bottom pane always resets for me. I had it set to show 8 lines, restarted, and it's now showing 16. This is on Win7.

**Comment by agroszer** [comment]
in case it still matters,

before restarting KO9 it looks like this:
![before](https://cloud.githubusercontent.com/assets/350912/7061322/979b9a0a-de90-11e4-9ea0-8d212a10eec4.png)

after restart:
![after](https://cloud.githubusercontent.com/assets/350912/7061327/a895a06c-de90-11e4-9048-842227e260be.png)

**Comment by Defman21** [comment]
Sometime combine tabs reset but I don't know steps to reproduce. It's absolutely randomly and I don't know where Komodo store these preferences.
