### ISSUE TITLE
Scroll Bar disappeared for the Open Files windows - Komodo Edit.

### ISSUE THREAD

**Issue by easyhouse** [Komodo/KomodoEdit#470]
About a week ago the scroll bar disappeared for the Open Files window in the latest version of Komodo Edit.

Any idea how to fix this? I have about 50+ files opened at one time.

**Comment by cgchoffman** [comment]
Easy work around for now would be to not have 50 files open or role back to [9.1][9.1].  I'm guessing it's a pretty easy fix though.  We're in the middle of testing and prepping the 9.2 release and this is really low prio so I won't be looking at it but if @Naatan knows a quick fix...

[9.1]:http://downloads.activestate.com/Komodo/releases/

**Comment by easyhouse** [comment]
I've opened up an issue at this URL for this problem:

https://github.com/Komodo/KomodoEdit/issues/470

**Comment by cgchoffman** [comment]
> I've opened up an issue at this URL for this problem:

Did you mean to post that here? http://forum.komodoide.com/t/scroll-bar-disappeared-for-open-files-in-komodo-editor-v9-2-0-build-15958/1845/2

**Comment by Naatan** [comment]
Fixed with 8387c472879365bfd168a14a057364dabf2c75b0
