### ISSUE TITLE
Server configuration Icons

### ISSUE THREAD

**Issue by pacav69** [Komodo/KomodoEdit#471]
The graphic for server configuration is misleading it should be a new page graphic and call tip should read ‘new sever config - enter in name below’ then tab to name entry.
![komodoservererror](https://cloud.githubusercontent.com/assets/2259579/9020455/ab25ee64-383f-11e5-952d-3b32ab78d8f0.png)

**Comment by Naatan** [comment]
Thanks for the suggestion! 

Agreed that those aren't the prettiest and could do with some tweaking, but I dont see how a plus is miss-leading? Seems pretty synonymous with "Add" to me.

**Comment by pacav69** [comment]
A new document logo i think would be better because when you click on the + logo it clears or resets the information indicating something new, it took me awhile to work out that it was a new config and clearing the contents. At least have the call tip point to the name text box.

**Comment by Naatan** [comment]
I dont like the idea of having a new document/file icon for something that is in no way a document or file, but I agree that the icons need to be updated.

**Comment by Naatan** [comment]
Will be fixed in next nightly.
