### ISSUE TITLE
Buggy context menu when right click on snippets (OSX)

### ISSUE THREAD

**Issue by danitoader** [Komodo/KomodoEdit#475]
When I right click on a snippet from the right pane, an ugly and unusable context menu appear.
![screen shot 2015-08-02 at 23 05 32 2](https://cloud.githubusercontent.com/assets/13614457/9027790/72a8d538-396b-11e5-91c1-c8e860380e48.png)

**Comment by Naatan** [comment]
Thanks! Fixed with e8ee3eacebdb9b48cf3b89129349a279bfde2f4a.
