### ISSUE TITLE
Komodo Utilizes Default Key Binding Scheme upon Restart

### ISSUE THREAD

**Issue by zinic** [Komodo/KomodoEdit#476]
### Overview
When restarting Komodo IDE, the key binding scheme is always reset to the default scheme. This requires the user to open Komodo's preferences and set the key binding scheme back to the one previously selected. This does not modify or delete user specified key binding schemes.

### Build Tested
Tested against build: **Komodo IDE, version 9.2.0, build 87613, platform linux-x86_64. Built on Fri Jul 31**

### Steps
* Create custom key binding scheme
* Select key binding scheme for use
* Close Komodo IDE
* Open Komodo IDE
* Check currently selected key binding scheme (should be set to ```Default```)

**Comment by babobski** [comment]
same problem here, loosing selected key bindings scheme on start up

**Comment by Naatan** [comment]
Could you please try these steps:

 * Shut down Komodo
 * Delete your 9.2 [profile folder](https://community.activestate.com/faq/komodo-profile-structure) (make a backup just in case)
 * Start Komodo
 * Change your keybinding scheme
 * Restart Komodo

Does it still reset?

**Comment by Naatan** [comment]
Reproduced, it seems to reset to whatever keybinding was selected when you upgraded.

**Comment by mitchell-as** [comment]
Fixed via b70ccec87b35e103f3bc9afe417eb973d69e6cd0

**Comment by zinic** [comment]
You guys rock!

**Comment by Naatan** [comment]
Thanks a ton for reporting this in time zinic! Gave us a last-minute heart attack but it was well worth it! :p
