### ISSUE TITLE
Internal SCSS Syntax checker hangs

### ISSUE THREAD

**Issue by bbak** [Komodo/KomodoEdit#480]
This is, what's added to pystderr.log

[2015-08-04 18:17:02,253] [WARNING] RefactoringLanguageServiceBase: Can't find a refactoring service for SCSS
[2015-08-04 18:17:02,255] [WARNING] koLanguage: Asked for unknown language: 'None'

I'm using the current 9.2 Nightly. 
Looks like the internal Syntax Checker is broken.

**Comment by Naatan** [comment]
Works fine for me, what are your "Prefs > Syntax & Spell Ccecking > SCSS" settings? I believe by default you need to have scss/sass (`gem install sass`) on your PATH.

**Comment by bbak** [comment]
I've set "use Built-In SCSS Syntax-Checker". If I remember right, in Komodo 8 there was no dependency to an external ruby sass and the internal SASS Linter was basically a "CSS Syntax checker with a little bit SCSS-knowledge". I believe this was true around 2013 when I filed [this bug](https://bugs.activestate.com/show_bug.cgi?id=98286). So, without a local ruby-sass installation, there's currently no SCSS Syntax check in Komodo 9.x, right?

**Comment by bbak** [comment]
Though I'm unfamiliar with Python, after looking into the SCSS-Linter Sources, it seems SCSS Linting requires a working ruby installation with the sass gem. In that case, you can close this Bug, since that's the reason. 
Any chance to get SCSS Linting through node-sass in the not too far future?

**Comment by Naatan** [comment]
As long as node-sass is backwards compatible with ruby sass Komodo should not really care what language is powering the executable.

**Comment by bbak** [comment]
Well, sorry, but I believe this is not true for JavaScript and SCSS. Looking at `/src/lint/koJavaScriptLinter.py` Line 170 and `/src/lint/koCSSExLinter.py` Line 118 the "executable" is always the internal Javascript Engine (js.exe) or the installed ruby Interpreter. What can be changed is - more or less - just the Lint-Script (jshint.js), but NOT the executable/interpreter itself. Therefore, no nodejs based linting, neither for JavaScript nor for sass is currently possible by just setting preferences.
