### ISSUE TITLE
Colorize minus before values as value

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#481]
![screen](http://i.imgur.com/Cro32QA.png)
I think `-` should be red in this case (so `-1` should be a value), not only the `1` part.

**Comment by jack17529** [comment]
Someone forgot to reset the color if its python code.

**Comment by Naatan** [comment]
It's not Python code. I can link you if @Defman21 tells me what language this issue is for.

**Comment by Defman21** [comment]
For any language.

**Comment by Naatan** [comment]
In that case it probably gets a bit more complicated. @mitchell-as any pointers?

**Comment by mitchell-as** [comment]
I recommend closing this ticket. Every lexer would have to be modified (both C++ and UDL), and would not handle expressions like `2-1` or `i-1` properly (note the lack of space between operands). We're getting into parser territory, which we should not try to do in a lexer for efficiency concerns.
