### ISSUE TITLE
The UI for breakpoints fails when the length of the program changes

### ISSUE THREAD

**Issue by DavidHowlett** [Komodo/KomodoEdit#483]
I am using Komodo 9.1 with the abyss theme to edit python 3.4.3 on 64bit windows 7.

If I add a breakpoint by clicking on the left of my source code I get a red dot indicating the location of the break point. If I click again the break point goes away. This is as it should be. 

If I add a breakpoint then change the number of lines above the break point then the image of the red dot moves but the breakpoint does not. To remove the breakpoint it is necessary to click on where the break point actually is rather then where the red dot is. This is very counterintuitive. 

Even when the breakpoint is removed this way the red dot remains. The only solution I have found for removing the red dot is restarting Komodo.

I attach a screenshot showing the residual red dots.
![image](https://cloud.githubusercontent.com/assets/4719098/9089381/cb62122a-3b8c-11e5-89ea-fc4435c8e9aa.png)

**Comment by Naatan** [comment]
Thanks David, this bug is being tracked here: https://github.com/Komodo/KomodoEdit/issues/256
