### ISSUE TITLE
Unreadable tooltips - Windows 8 / Windows 10 in High Resolution Monitors

### ISSUE THREAD

**Issue by jdgamble555** [Komodo/KomodoEdit#484]
http://forum.komodoide.com/t/unreadable-tooltips/1506/13

I'm using Windows 10, 3840 x 2160... Dell XPS 15.  

The "linter error indicators" fine, but for some reason the "linter warning indicators" do not show correctly.  Please read the other post to see what has been tried and what hasn't.  I'm just wondering with more and more people getting high resolution monitors if this will be updated soon.  

![linter](https://cloud.githubusercontent.com/assets/8333090/9090224/16bf8a7a-3b67-11e5-8857-00e35e88367f.png)
![error](https://cloud.githubusercontent.com/assets/8333090/9090231/1d99af6a-3b67-11e5-8459-515660ed2121.png)

Thanks so much,
Jonathan

**Comment by Naatan** [comment]
This is likely because you are using a non-default DPI. Try setting your DPI (font/text-scaling) to the default.

Sorry for the late response, this one slipped by.

**Comment by cyberbit** [comment]
FWIW, I'm also having this issue. This is what I see on Komodo Edit 9.3.2, Windows 10, 3200x1800 laptop with 150% scaling:

![image](https://cloud.githubusercontent.com/assets/7350183/12245618/4f618b5a-b86f-11e5-9041-11e0ddbb038d.png)

**Comment by Naatan** [comment]
Seems to be the same as #162
