### ISSUE TITLE
Add structured edit ("paredit") for Lisps

### ISSUE THREAD

**Issue by polymeris** [Komodo/KomodoEdit#485]
Structured editing is a mode that forces the syntactical correctness of LISP code by always keeping matching parentheses, brackets and quotes balanced, in practice allowing the code to be treated like a tree more than just a linear array of characters/declarations. It also offers commands to modify and navigate this tree.

Emacs' paredit mode is an example of this:
http://www.emacswiki.org/emacs/PareditCheatsheet
http://danmidwood.com/content/2014/11/21/animated-paredit.html

Lisps like Clojure and Racket are gaining a lot of traction. It would be great if we could work with them without having to switch to another IDE.

**Comment by Naatan** [comment]
Moved to backlog until we have a good understanding of what work is involved. @mitchell-as can you take a look at this and weigh in?

**Comment by polymeris** [comment]
This is a very interesting alternative, as well: http://shaunlebron.github.io/parinfer/

**Comment by Naatan** [comment]
Targeting the evaluation of this feature for 9.4, so we don't forget.

**Comment by mitchell-as** [comment]
This does not look trivial. As far as I can tell, at this time parinfer is experimental. There's no wonder no IDE implements it yet.

I would target this at least 10.1 @Naatan.

**Comment by Naatan** [comment]
Let's put it back in the backlog for now. I like the idea but the fact that it's only for lisps puts a bit of a damper on it. Maybe we can do something with the general idea though.

**Comment by mitchell-as** [comment]
I'm going to close this issue because I don't realistically see us ever being able to put in the time to implement this, especially because it's targeted at Lisps, which we do not have any special extra support for.
