### ISSUE TITLE
Komodo fits to screen and some controls are hidden by Windows' task bar

### ISSUE THREAD

**Issue by vokiput** [Komodo/KomodoEdit#487]
Komodo fits to screen and some controls are hidden by Windows' task bar
Because of this I cannot use controls on all tabs placed on Bottom Pane

As workaround I need to :
1. Use 'Aouto-hide the taskbar' option for Windows taskbar
2. Use full-screen mode for Komodo

This was broken in Komodo 9.2

Komodo IDE, version 9.2.0, build 87616, platform win32-x86.
Built on Tue Aug 04 10:31:35 2015.

**Comment by Naatan** [comment]
I'm not sure I understand your issue, could you share a screenshot?

**Comment by cgchoffman** [comment]
I'm not seeing this.  I use Windows key + arrow key to move my window around and it's never under the task bar unless I physically move it there with the mouse.

**Comment by vokiput** [comment]
![bottom_controls_are_hidden_by_taskbar](https://cloud.githubusercontent.com/assets/5433342/9099086/c78aabee-3b82-11e5-91b0-af46f580d9a4.png)

Bottom controls are hidden by taskBar

**Comment by cgchoffman** [comment]
![capture](https://cloud.githubusercontent.com/assets/655154/9099232/f98085f0-3b83-11e5-94f8-ca5ebf57e047.PNG)
I'm not getting the same results. I see you tried a clean profile to test #174.  Did you experience the same issue while using a clean profile?  How are you sizing your window?

Are you 100% sure it's not *because* you've enabled auto-hide on the taskbar that you're getting this issue?

**Comment by vokiput** [comment]
Hi,

Yesterday I used Komodo 9.1 and it was fine. Today I updated by 9.2 version and it became like this.

I don't use  'Auto-hide the taskbar' option for Windows taskbar.

I used this option at #174  to show you what I need to click on this hidden controls (button in that case) to get expected result.

![screenresolution](https://cloud.githubusercontent.com/assets/5433342/9099530/4ea3ec28-3b86-11e5-9c93-9f940dfd2f8a.png)

My screen resolution if it could help.

**Comment by cgchoffman** [comment]
With Auto-hide enabled, which you said you did in your very first message, this issue will never go away.  You have to disable it whether or not you were using it when you first noticed the issue.

Once you're disabled it, could you try starting Komodo with a clean profile and see if the issue persists.  

Please also answer my other question from my previous question.

**Comment by vokiput** [comment]
One more. 

I never used autohide option on the machine.

Today I updated Komodo from 9.1 to 9.2 and got this issue.

I think I found roots of issue.

Could you try it on your side with these settings?

![mytoolbarssettings](https://cloud.githubusercontent.com/assets/5433342/9099824/3545ae62-3b89-11e5-9f20-0d71259c0883.png)

**Comment by cgchoffman** [comment]
> As workaround I need to :
> 1. Use 'Aouto-hide the taskbar' option for Windows taskbar

This was in your first message.  I have no idea if you've disabled it or not.  I guess you have.

Enabling Show Tabs and Menubar have no effect.  I still have access to the items in the bottom bar.

How are you resizing the window?

**Comment by cgchoffman** [comment]
Also, when you're experiencing the issue, could you try resizing the bottom pane?  Size it to as big as you can and to as small as you can.

**Comment by vokiput** [comment]
Last trick helped. I resized bottom pane down and back to maximum size and all became normal.

Thanks for your help.

I'll try to reproduce #174 on different machine.

**Comment by Naatan** [comment]
@vokiput do you have to do that repeatedly or did that fix it permanently?

**Comment by vokiput** [comment]
Yes, 

Everything normal even after I restart Komodo.

Good trick to be added to FAQ.

**Comment by Defman21** [comment]
I think that FAQ isn't a good place for workarounds :|

**Comment by cgchoffman** [comment]
> I think that FAQ isn't a good place for workarounds :|

That's exactly where I would put a workaround.  

Nathanr, this is the issue I was telling you on OSX the other day.  I don't know how to repro it though :(

**Comment by Defman21** [comment]
>That's exactly where I would put a workaround. 

This is your opinion and I respect it :) But I don't think that the issue is a good place to discuss this sort of questions :)

**Comment by vokiput** [comment]
This is your opinion and I respect it :) But I don't think that the issue is a good place to discuss this sort of questions :) 

JIRA has 'For Developers' only option. :))

**Comment by vokiput** [comment]
I'll do my best to repro issue .

**Comment by Naatan** [comment]
Thanks @vokiput.

@cgchoffman I miss understood then, I thought the issue you raised was consistently reproducible.

Sounds like it may be an upgrade issue then.

**Comment by cgchoffman** [comment]
> @cgchoffman I miss understood then, I thought the issue you raised was consistently reproducible.

It was 100% reproducible until I found the workaround of re-sizing the bottom pane. I haven't seen it since.  It's really odd.

**Comment by vokiput** [comment]
I tried to reproduce it on my home Win 7. It is worked as expected.

I don't have time to test it on my work machine.

Sorry for a long delay.

It is up to you is it bug or not.

Sergey.

**Comment by Naatan** [comment]
I'll close for now as this is the only report we've seen and it was very easily resolved permanently by resizing. Obviously not ideal but it doesn't seem it affects a lot of people.
