### ISSUE TITLE
no contrast between less and php file icons

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#488]
I've got a little request about the file icons.
I love the new file icons from 9.0 they give a nice fresh look to komodo, but i am running into a small workflow issue. For my job i edit mostly multiple php and less files, but im running the problem that i cant keep them apart. Both icons are the same color blue (the less file icon was first purple), what results that all the files look from the same file type.
![snap 2015-08-05 at 20 30 59](https://cloud.githubusercontent.com/assets/3530262/9096315/a1672e6c-3bbc-11e5-995a-230c42b963ce.png)
My request is if you guys can add some more contrast between the two file types, maybe its a idea to give the less file a darker blue color, for instance the  [less](http://lesscss.org/) dark blue(#1D365D) that will result in something like this.
![snap 2015-08-05 at 20 30 59-less-blue](https://cloud.githubusercontent.com/assets/3530262/9096292/85d3cc1e-3bbc-11e5-81b1-a9c463f07f4c.png)

**Comment by Naatan** [comment]
I tried to respect the icons for each respective language, eg. 

http://moduscreate.com/wp-content/uploads/2012/01/less-css-logo.png

But yeah, there is barely any contrast there, and the content itself looks similar too. Will see what I can do.

**Comment by babobski** [comment]
:thumbsup: thanks, looking forward to it.

**Comment by babobski** [comment]
problem solved with new icon set in 9.3 :thumbsup:
