### ISSUE TITLE
content from spellcheck window is pushed out, when content is loaded (windows 10)

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#489]
Just noticed that when i open the spell check window the content is pushed out when fully loaded.
Its opening fine but when the content is loaded, the content get's pushed out.
<em>while loading</em>
![snap 2015-08-05 at 22 12 15](https://cloud.githubusercontent.com/assets/3530262/9096821/f65062ce-3bbf-11e5-873c-185024743563.png)
<em>finished loading</em>
![snap 2015-08-05 at 22 12 33](https://cloud.githubusercontent.com/assets/3530262/9096846/16f5bf74-3bc0-11e5-96ee-57b0dc2c80ed.png)

**Comment by Naatan** [comment]
Odd, seems the multiline select box is growing. I think this can probably be fixed by enforcing a max heigh on it.
