### ISSUE TITLE
HTTPS extension homepage doesn't open in add-on window

### ISSUE THREAD

**Issue by ervumlens** [Komodo/KomodoEdit#490]
> Komodo Edit, version 9.2.0, build 15966, platform linux-x86_64. Built on Tue Aug 4 17:31:26 2015.

Not hurting me, just a general problem. I don't know if this worked in 9.1.

**Problem**
An extension's homepage will not open for me if the URL uses HTTPS protocol. HTTP protocol links work fine.

**Steps to Reproduce**
1. Open Komodo's Tools &rarr; Add-ons menu.
2. Find the "Go Language" extension (easiest way to test). Click its "More" link.
3. Click the homepage link (https://github.com/trentm/komodo-go).

**Expected**
A browser window opens to the homepage, like any other extension homepage.

**Actual**
No browser window opens.
An exception is logged.
```
[2015-08-05 19:33:42,669] [ERROR] console-logger: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIExternalProtocolService.loadUrl]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://komodo/content/bindings/text-link.xml :: open :: line 90"  data: no] (0) in chrome://komodo/content/bindings/text-link.xml:95
Traceback (most recent call last):
  File "chrome://komodo/content/bindings/text-link.xml", line 95, in 

[2015-08-05 19:33:42,673] [ERROR] console-logger: Error: Failed to open https://github.com/trentm/komodo-go in the system default handler (0) in chrome://komodo/content/bindings/text-link.xml:99
Traceback (most recent call last):
  File "chrome://komodo/content/bindings/text-link.xml", line 99, in 
```

I can reproduce the lower-level problem in a macro, although as far as I know this code is specific to [`text-link.xml`](https://github.com/Komodo/KomodoEdit/blob/master/src/chrome/komodo/content/bindings/text-link.xml) (that's where the code and the error are from). Here I'm attempting to open https://www.google.com.

```javascript
//This is a javascript macro
const ioService =
Components.classes["@mozilla.org/network/io-service;1"].getService(Components.interfaces.nsIIOService);
var uri = ioService.newURI("https://www.google.com", null, null);
const cID = "@mozilla.org/uriloader/external-protocol-service;1";
const nsIEPS = Components.interfaces.nsIExternalProtocolService;
var protocolSvc = Components.classes[cID].getService(nsIEPS);
protocolSvc.loadUrl(uri);

```
It may be a configuration problem somewhere, but the error message doesn't give me a clue.

**Comment by Naatan** [comment]
We'll be removing the old addon dialog entirely in the next Komodo version, so no point tracking any bugs for it unless they're breaking major functionality.

Not to detract from your efforts @ervumlens! They're very much appreciated! :)

**Comment by ervumlens** [comment]
No detraction taken. I trust you to put the kibosh on wayward issues like this one. :hammer:

**Comment by Mook-as** [comment]
This is actually probably a configuration problem (Komodo is set to open `https` links in something it can't actually use).  I don't know how you'd go fix it though, other than delete `XRE/mimeTypes.rdf` in your profile (or edit it while Komodo is closed).

It might be interesting to look at the contents of that file, at least?

**Comment by ervumlens** [comment]
> This is actually probably a configuration problem...

Roger that, thanks a lot for the tip. HTTPS  was  bound in  `XRE/mimeTypes.rdf` like so:

```xml
<RDF:Description RDF:about="urn:scheme:handler:https"
                   NC:useSystemDefault="true"
                   NC:alwaysAsk="false" />
```

Removing the file restored the "Launch Application" dialog when clicking the link.

It looks like there's something funky with the system default. If I choose the built-in `x-www-browser` option (no icon in the image below), no browser opens and an error is logged. But everything is fine if I explicitly find and select `/usr/bin/x-www-browser` (with the icon). 


![launch application](https://cloud.githubusercontent.com/assets/13005338/9121169/35165320-3c46-11e5-85bc-f43f95e1b4b8.png)

The system default is pulled from gconf. It's pointing to `x-www-browser %s`, which is the typical format for the values in there. Try as I might, I can't configure gconf to something that will open successfully in Komodo.

Anyway, I figure I'm well outside of Komodo territory now.

Thanks again, Mook-as.

**Comment by ervumlens** [comment]
FYI, here's a macro to reset the https protocol handler. Tweak to reset any other handler. 

```javascript
//This is a javascript macro
var protocolService = Cc["@mozilla.org/uriloader/external-protocol-service;1"].getService(Ci.nsIExternalProtocolService);
const ioService = Cc["@mozilla.org/network/io-service;1"].getService(Ci.nsIIOService);
var handlerService = Cc['@mozilla.org/uriloader/handler-service;1'].getService(Ci.nsIHandlerService);

//Load the handler info, change it, and save it.
var handlerInfo = protocolService.getProtocolHandlerInfo("https");
handlerInfo.alwaysAskBeforeHandling = true;
handlerService.store(handlerInfo);

//Open a URI to raise the handler prompt.
var uri = ioService.newURI("https://www.google.com", null, null);
protocolService.loadUrl(uri);
```
