### ISSUE TITLE
komodo edit undo disabled

### ISSUE THREAD

**Issue by farkass** [Komodo/KomodoEdit#491]
Hi,

In latest version of komodo edit - Komodo Edit, version 9.2.0, build 15966, platform linux-x86_64.
Built on Tue Aug 4 17:31:26 2015.

after executing a command:
![selection_186](https://cloud.githubusercontent.com/assets/9973405/9112541/689b949a-3c4f-11e5-945a-6313c611091e.png)

the undo is disabled in toolbar, in menu item, and hotkey is not working.

But if executing a macro:
![selection_187](https://cloud.githubusercontent.com/assets/9973405/9112697/720279bc-3c50-11e5-8075-f0525560c633.png)
The undo is working again.

**Comment by Naatan** [comment]
Cannot reproduce. Are you certain it was enabled before you executed the command?

**Comment by farkass** [comment]
sure, i have modified the file before executing command

**Comment by ervumlens** [comment]
I'm able to reproduce this, or something like it (9.2.0 Linux).

**Steps to Reproduce**
1. Create a toolbox command that runs `python %F`
2. Create a new Python file containing `Print "Hi!"`. Save the file.
3. Make a change to the python file. Ensure that Edit &rarr; Undo is enabled.
4. Run the toolbox command.

**Expected**
Edit &rarr; Undo is still enabled.

**Actual**
It's disabled.

The undo *command* is still available since `ctrl+z` is works.

@farkass, is this a fair summary of your problem?

**Comment by farkass** [comment]
Yes, thank you!

I have launched the command multiple times.

One more issue i have found now to tested,
After a few Undo/Redo through keyboard and launching command caused toolbox rendering malfunction, when hovering mouse, the items disappeared:
![selection_189](https://cloud.githubusercontent.com/assets/9973405/9122651/bf6c9bda-3c8a-11e5-98de-45932e0bb1d2.png)
Maybe this is a separate issue.

**Comment by ervumlens** [comment]
@farkass Regarding the disappearing items problem: I've run into this before, but I could never reproduce it in a new project, only projects I've worked in a while. Could you try to reproduce the problem in a brand-new project?

It's probably a different issue, I don't know. \*shrug\*

**Comment by Naatan** [comment]
Please file a new bug report for the disappearing issue if you can reproduce it.

**Comment by Naatan** [comment]
Not reproducible on IDE. Will attempt on Edit when I have a minute.

**Comment by farkass** [comment]
Reproduced in Komodo Edit, version 9.2.0, build 15966, platform win32-x86.
Built on Tue Aug 04 21:08:06 2015.

opened a python file, modified its content, then called command:
![selection_191](https://cloud.githubusercontent.com/assets/9973405/9134449/80aad36a-3d04-11e5-9de4-8e31a0a11c20.png)

Undo disabled:
![selection_192](https://cloud.githubusercontent.com/assets/9973405/9134454/9772aa78-3d04-11e5-884e-3cdc6cbaec00.png)

Pressed Ctrl+Z: file modified icons enabled:
![selection_194](https://cloud.githubusercontent.com/assets/9973405/9134500/f39b7334-3d04-11e5-8b92-bc168b0d34b2.png)

But when hovered mouse to execute again the command, the toolbox panel cleared again:
![selection_193](https://cloud.githubusercontent.com/assets/9973405/9134518/20680fda-3d05-11e5-8d02-1edc40ebbf34.png)

**Comment by farkass** [comment]
Just to mention this is not command specific, I have got this Undo disabled with another command too:
![selection_195](https://cloud.githubusercontent.com/assets/9973405/9134570/ad3144a4-3d05-11e5-9c3e-7a76782688a9.png)

**Comment by ervumlens** [comment]
Hi @farkass, I copied your "disappearing toolbox items" problem to issue #506. If you notice anything else about that problem, please leave a comment there. 

We'll use this issue (491) for just the "disabled undo" problem. :+1:

**Comment by farkass** [comment]
Hi @ervumlens, Thank you!
