### ISSUE TITLE
Missing ignore menu item when there are no spelling suggestions

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#493]
It indicates spelling errors but no solutions are given when you right click, nor the ability to ignore.

**Comment by Naatan** [comment]
Hmm, may not be related to collab after all. Some words work, others dont. Check the collab/planning/9.3 planning doc.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoIDE/commit/5be8d83409c9117c88de012ad06503249feb4450
