### ISSUE TITLE
IDE - Perl autocomplete $$myref and $@

### ISSUE THREAD

**Issue by cdcmicro** [Komodo/KomodoEdit#496]
Using Komodo IDE 9.2 on Win7/64 with autocomplete enabled.  In a Perl program, when I type "$$" intending to set the value of $$myref, it pastes the name of the first variable in the autocomplete list as soon as I type the second "$".  It's a little annoying.  Seems like a bug.  Thanks for considering it.  -Clark

```perl
$first_var = "";
$myref = \$firstvar;
# typing $$myref yields
$first_var$myref = "error";
# same for $@, yields
if ($first_var@) {
  #...
}
```

**Comment by Naatan** [comment]
I can't reproduce this. Do you have any macro's/addons installed that may be causing this?

**Comment by cdcmicro** [comment]
Ugh.  Thanks for the quick reply.  I have a few addons.  I'll see if it's one of those, or maybe a key mapping.  Either way, if you can't reproduce it, it's probably not a bug. I can pursue it in the forums.

**Comment by Defman21** [comment]
I have an idea what can cause that...
Try to remove `$` sign from `Preferences - Editor - Smart editing` and see are you able to reproduce it.

**Comment by Defman21** [comment]
Nevermind, it didn't help. @Naatan I'm able to reproduce it.
Press `$` one time, wait until auto-complete appear, then press `$` again.

**Comment by cdcmicro** [comment]
Well, it wasn't exactly that, but you sent me in the right general direction.

Turned off `Preferences - Code Intelligence - Enable autocomplete fill-up characters` and the behavior stopped.

**Comment by Defman21** [comment]
Also it's reproducible in CSS files, for example
 ```css
body {
font: 1rem|
```
| - cursor, press space to get auto-complete list and try to type `"`, `100` will be inserted.
I recorded the behavior: https://youtu.be/r2W1yVCnqzw

**Comment by Naatan** [comment]
So it's not very intelligent :p I don't think we can handle that as a general bug though, that seems like a case-by-case basis type of thing. The original "bug" reported here doesn't seem like something we could intelligently resolve, disabling fill-up is the appropriate solution. The css bug does seem like something we could fix, mind reporting a new bug Defman?

**Comment by Defman21** [comment]
Yeah, no problem. Give me a minute to report a new bug :)

**Comment by cdcmicro** [comment]
It's been annoying me in Javascript, for as long as I can remember.  Type
```javascript
//type
var xhr;
//and get 
var xhrCallbacks;
```

I'm just happy to have a workaround :-)

**Comment by Naatan** [comment]
That's odd, I don't believe it should trigger on alphanumeric characters. If you can repro that consistently please open a bug.

**Comment by cdcmicro** [comment]
I think it's triggering on the semicolon

**Comment by cdcmicro** [comment]
or spacebar

**Comment by Naatan** [comment]
Ahh gotcha, yeah that's it's intended use. Disabling the options is the appropriate solution.

I have it turned off as well, in fact would probably make sense to disable that by default, I think any new user would be confused by it.

**Comment by Defman21** [comment]
I was confused by it for 2 months, ohh...
