### ISSUE TITLE
CSS auto-complete automatically inserts a suggestion if " was pressed

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#497]
An example:
```css
body {
font: 1rem|
```
| - cursor, press space to get auto-complete list and try to type ", 100 will be inserted.
I recorded the behavior: https://youtu.be/r2W1yVCnqzw (LINUX WHAT'S YOUR PROBLEM WITH VIDEO QUALITY?)

**Comment by Naatan** [comment]
This is auto fill-up, just disable it.
