### ISSUE TITLE
Disable "Enable autocomplete fill-up characters" by default

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#498]
No newcomer to Komodo will ever run into this and think "oooh handy". Which is not to say it isnt handy, but only if you know what it is and what it does.

Relevant: https://github.com/Komodo/KomodoEdit/issues/496

**Comment by Defman21** [comment]
Also relevant: https://github.com/Komodo/KomodoEdit/issues/497

**Comment by Defman21** [comment]
@Naatan it's disabled by default, isn't it? 
https://github.com/Komodo/KomodoEdit/blob/master/src/prefs/prefs.p.xml#L868

**Comment by ervumlens** [comment]
Maybe it's the auto-abbreviations and not the auto-complete? ([pref.p.xml#L728](https://github.com/Komodo/KomodoEdit/blob/master/src/prefs/prefs.p.xml#L728)) That's the one that gets me.

**Comment by Defman21** [comment]
Nope, it's `codeintel_completion_auto_fillups_enabled` if we're talking about #496. You can try to enable it for yourself (`Prefs - Code Intelligence`) to reproduce #496 or #497 and then disable it to fix the "bug".

**Comment by ervumlens** [comment]
Ah, okay, thanks. I get my "autos" confused.

**Comment by cgchoffman** [comment]
This isn't enabled by default.  Does the title still reflect the issue being dealt with?
