### ISSUE TITLE
Can't cancel "close your project's files?" prompt when closing Komodo

### ISSUE THREAD

**Issue by ervumlens** [Komodo/KomodoEdit#499]
I noticed this after creating a fresh profile and forgetting to set some preferences. I don't use the prompt and I'm curious to know if anyone else does. 

Komodo 9.2.0 Linux.

**Problem**
The user can be prompted about whether they want their project's open files to be closed prior to closing the project. Normally the user can click cancel to abort the underlying operation (e.g., changing projects). The user can't cancel, though, if they're trying to close Komodo.

**Steps to Reproduce**
1. Open Preferences &rarr; Workspace and set "When closing a project" to "Ask me what to do".
2. Open a project. 
3. Open some of that project's files.
4. Close Komodo.
5. At the "Close your project's files?" prompt, click "Cancel".

**Expected**
The operation is cancelled. Komodo remains open.

**Actual**
The operation is not cancelled. Komodo closes.

**Comment by ervumlens** [comment]
"No, please close Komodo but leave my files open." :unamused:  

I guess the prompt itself doesn't make much sense here. Yes, No, and Cancel all do the same thing.

**Comment by Naatan** [comment]
Yeah agreed, its propably a prompt that happens when you close a project and its not smart enough to figure the full context of the event.
