### ISSUE TITLE
TrackChanges: Hangs Komodo when closing file while dialog up

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#50]
Open a track changes diff dialog, press Ctrl+W. Komodo hangs.

**Comment by Naatan** [comment]
Can't figure out what's happening. Things I've tried:

 * Stealing focus to the panel element
 * Deleting panel prior to closing view
 * Ensuring panel is hidden before closing view

It always hangs regardless, but only if the track changes dialog was open when I press Ctrl+W.

Could steal input, but that would also take away the ability to copy test from the track changes dialog.

Assigning to Mitchell, since this seems pretty low level. Not a priority for 9.2, it's fairly edge case.

**Comment by mitchell-as** [comment]
This looks to be a low-level Mozilla issue. On my Linux box, while Komodo hangs, I get a bunch of these warnings:

    (komodo:9915): Gtk-CRITICAL **: IA__gtk_propagate_event: assertion 'GTK_IS_WIDGET (widget)' failed
    Gtk-CRITICAL **: IA__gtk_widget_is_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed

The latter happens when I attempt to mouse over the current view.

I do not know how to solve this.

**Comment by mitchell-as** [comment]
This appears to have been fixed in Komodo 10.
