### ISSUE TITLE
Current file preference > Prefer tab charactor over spaces setting wouldn't be saved

### ISSUE THREAD

**Issue by jamadam** [Komodo/KomodoEdit#500]
### Version

Komodo Edit, version 9.2.0, build 15966, platform macosx. Built on Tue Aug 4 17:31:22 2015.

### Steps to Reproduce

1. Open file.
2. Open "Current file preference" in "Edit" menu.
3. Change "Prefer tab charactor over spaces setting" setting.
4. Push "OK".
5. Close the file and reopen it.
6. Open "Current file preference" in "Edit" menu.
7. The setting is reverted.

The other settings in same section are seem to be saved as expected.

Thank you.

**Comment by Naatan** [comment]
Should be fixed in 9.3

**Comment by jamadam** [comment]
This happens again with v10.0 and havnn't solved yet.

Komodo Edit, version 10.1.1, build 17414, platform macosx. Built on Thu Sep 1 21:26:18 2016.

**Comment by mitchell-as** [comment]
I followed the steps in your original post with a new file and did not encounter a problem. Help > Troubleshooting > Reset File Preferences may be of help to you.

**Comment by jamadam** [comment]
Thanks. The direction didn't help but I found a solution.

In the project root there found a file .editorconfig and indent_style was "tab". Changing this to "space" manually solve the problem. 

The global and project setting had been indicating "prefer spaces" anyway and I'm not opening files as project file so I'm curious about what had been going on for a year...

**Comment by Defman21** [comment]
I think it would be better if Komodo will show an indicator that there are some settings being redefined by EditorConfig. (probably in status bar). @Naatan what do you think?

**Comment by Naatan** [comment]
Opened a bug here

https://github.com/Komodo/KomodoEdit/issues/2011

**Comment by cgchoffman** [comment]
> In the project root there found a file .editorconfig and indent_style was "tab". Changing this to "space" manually solve the problem

This sounds like another bug no?  If someone overrides .editorconfig, shouldn't that take precedents?

**Comment by Naatan** [comment]
I recall I used to have it working like that but it caused too many issues (our pref system inheritance is already a bit .. complex).

I think in the short term just making it evident why your prefs don't "work" should suffice. I fear proper editorconfig "fallback" support would cost more work than it's worth investing.

**Comment by cgchoffman** [comment]
That makes sense.  K i'll make a note in the ticket you opened.
