### ISSUE TITLE
Special chars in filename caused publishing error

### ISSUE THREAD

**Issue by maorui2k** [Komodo/KomodoEdit#501]
Komodo IDE 9.1, Windows 7 x64.

I published all AngularJS files to a Linux box by SCP. There were files' name contain $ at the beginning. After the publish finished, I found all $ were removed, which caused some files misplaced in other directory or in wrong name.

**Comment by Naatan** [comment]
Definitely shouldn't be an issue.. but er, why put special characters in filenames in the first place? That seems like asking for trouble one way or another. This something specific about Angular?

**Comment by cgchoffman** [comment]
There were a few things fixed around file paths in Publishing.  Is this still an issue in 9.3 or 9.2.1?
