### ISSUE TITLE
Tools cannot be saved (updated) in IDE 9.2

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#504]

**Comment by Naatan** [comment]
Fixed on IDE repo with https://github.com/Komodo/KomodoIDE/commit/ce67f60e56005c6c1fa02af7e0bda47941ebedd5

**Comment by Naatan** [comment]
I will post a link to the nightly here when it is available.

**Comment by Naatan** [comment]
Nightly available: http://downloads.activestate.com/Komodo/nightly/komodoide/latest-9.2.x/

**Comment by Defman21** [comment]
Yaaay!
