### ISSUE TITLE
"Trigger Characters" textbox incorrectly enabled when "Auto-Abbreviations" is disabled.

### ISSUE THREAD

**Issue by ervumlens** [Komodo/KomodoEdit#507]
Logging this for correctness' sake. Nobody is hurting from it.

Komodo Edit 9.2.0 . Was in 9.1.0 also, FWIW.

**Problem**
The "trigger characters" preference textbox gets disabled when auto-abbrev gets disabled, but it is re-enabled after exiting prefs and then returning.

**Steps to Reproduce**
1. Open Preferences &rarr; Editor &rarr; Smart Editing. Disable auto-abbreviations. (The "trigger characters" textbox gets disabled.)
2. Close Preferences.
3. Open Preferences again and go back to Smart Editing.

**Expected**
The textbox is still disabled.

**Actual**
It's enabled. (It's a little hard to tell enabled from disabled in the screenshot, but you can see I was able to select some text.)

![screenshot - 08062015 - 07 05 54 pm](https://cloud.githubusercontent.com/assets/13005338/9126077/309c4520-3c6e-11e5-8fbc-40addd52d271.png)

**Comment by Defman21** [comment]
Should be easy to fix, will look into this tomorrow :)

**Comment by Defman21** [comment]
...or now.

**Comment by Defman21** [comment]
ohh, so much references... Sorry, it's because of branch rebasing :(

**Comment by ervumlens** [comment]
> ohh, so much references...

It's a terminator army!

Thanks for looking into this one, defman.

**Comment by Defman21** [comment]
>It's a terminator army!

I hope it's not. Those terminators... they are scary a bit.
