### ISSUE TITLE
Add "Close files by type" feature for Open Files pane

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#512]
For example I want to close all `Txt` files here:
![screen](http://i.imgur.com/VIOxBJX.png)
There is no way to do that exclude close each file manually. I suggest to add "close" icon for headers of these lists. (my paint skills are awesome, aren't they?)
![illuminati](http://i.imgur.com/CoSA3ZP.png)

**Comment by Naatan** [comment]
Been wanting to do this for a while. Will try for 9.3.

**Comment by Defman21** [comment]
Fixed via https://github.com/Komodo/KomodoEdit/commit/ab4ee25b7ea9e4b16575b985a3b711486edb014f

**Comment by Naatan** [comment]
Thanks @Defman21, knew there was a ticket for this, just couldn't find it.

**Comment by Defman21** [comment]
np :)
