### ISSUE TITLE
Outrunning Commando? Searches sometimes stop before completion

### ISSUE THREAD

**Issue by ervumlens** [Komodo/KomodoEdit#515]
Komodo Edit 9.2.0 Linux

**Problem**
I opened Commando and typed in "prefe" to bring up the Preferences command. When the Kitt animation stopped (which didn't take long), I hit enter without paying attention to the search results. I ended up in the Add-Ons manager. It takes me a few tries, but I'm able to reproduce the problem.

Apparently the Commando search occasionally stops before it has processed the query text. Increasing the delay in the Commando preferences reduces the likelihood of this problem. However, I would expect Commando to always have one more "cycle" to complete its search, regardless of how fast or slow I type.

There may be some complicating factors here besides just the Commando preferences. For example, I haven't been able to reproduce this in a project with lots of files (e.g., KomodoEdit).

I don't recall hitting this in 9.1, but I wasn't using Commando to access preferences until 9.2 (and "prefe" is pretty easy to type).

**Steps to Reproduce**
1. Open Commando.
2. Type "prefe" quickly.

**Expected**
Kitt eventually stops. The "Preferences" command is displayed in the results.

**Actual**
Kitt stops and usually "Preferences" is displayed. Other times the search stops where ever the results happened to be.

There isn't much to see in these screenshots except that the Kitt animation isn't active.

![stuck commando - 1](https://cloud.githubusercontent.com/assets/13005338/9157918/7c207f9a-3ed3-11e5-94be-649b4765ca6c.png)

![stuck commando - 2](https://cloud.githubusercontent.com/assets/13005338/9157921/80a376b2-3ed3-11e5-812b-c648a6be4292.png)

**Comment by Naatan** [comment]
Thanks @ervumlens, I've noticed this as well but was not able to find any reproduction steps. Will try your steps.
