### ISSUE TITLE
Make Advanced Options Easier To Discover

### ISSUE THREAD

**Issue by aaroncampbell** [Komodo/KomodoEdit#518]
I spent quite a bit of time looking for an option that I knew I had used before. Eventually I ended up in the IRC channel, and after still having no luck I opened #516. As it turns out, the option (actually, the whole section the option is in, places) was hidden behind the "Show Advanced" checkbox, which I didn't see. The preferences dialog is a full, busy place, and the "Show Advanced" checkbox is in the lower left, the least-viewed place in the box, and out of all the contexts in there.

The time I spent looking for the option found me clicking and reading each individual section in the left box inside the preferences dialog. If the option to "Show Advanced" had been in there, I definitely would have found it. The weird thing is, being OUTSIDE that box (even though not by much), it was so easy to miss that I actually didn't see it several days in a row when looking. I think the UI could be improved markedly if it were moved inside.

My thoughts:
If "Show Advanced" simply adds new sections, why not add "> Advanced" as the last section in there, and have it expand like all the other hierarchical sections in there, showing all the hidden sections indented under it.

If it also changes options INSIDE various already visible sections, then maybe just adding "Show Advanced" to the bottom of that box, styling it to match the various sections, and when clicked it would change to "Hide Advanced" (rather than using the checkbox).

**Comment by Naatan** [comment]
Definitely something a lot of users seem to be running into. Will do what I can.

**Comment by babobski** [comment]
Maybe it's an idea if you use the search function in the preferences, it ignores the advanced setting and shows all matches. Or a other approach if the show advanced settings is unchecked, and you search, to show there are also matches in the advanced section.
Something like this:
![show_advanced](https://cloud.githubusercontent.com/assets/3530262/10558177/d19e7994-74c6-11e5-98c2-e72be38cdf54.png)

**Comment by garretwilson** [comment]
When I ran into the (same issue) [http://forum.komodoide.com/t/backup-files/2376/6?u=garretwilson], I considered requesting in the very least that you have the search include all the options, even if the "Show Advanced" checkbox is not checked. But I didn't want to seem too picky. :smile: But yes, I agree with @babobski that the search should somehow indicate if some items aren't included in the results.

**Comment by Naatan** [comment]
Yep, that definitely sounds like a good idea to me.

**Comment by mitchell-as** [comment]
The new preferences UI in Komodo 10 does away with this distinction between "normal" and "advanced" preferences. Closing this ticket.
