### ISSUE TITLE
Ruby lexer does not highlight first symbol of keyword-style args

### ISSUE THREAD

**Issue by IronSavior** [Komodo/KomodoEdit#522]
(I'm sorry I couldn't submit a patch--I had to abandon my efforts to figure out how to set up and build a Komodo extension and tweak the ruby UDL with very little success.)

The ruby lexer does not highlight the first hash key as a symbol when using "keyword-style" implicit hash syntax.

#### How to reproduce
This issue only affects the following two cases related to keyword-style method syntax. Both cases are common, but case 1 is so common that it is represented in nearly all recent ruby code.

1. The first argument in a **method call** using keyword-style syntax. (ruby 1.9+)
2. The first argument in a **method definition** using keyword-style syntax--both with and without default values, see notes below. (ruby 2.0+)

This is more concisely demonstrated in code:
```ruby
# Case 1: method calls
obj.a_method arg1: 'val1', arg2: 'val2'  # arg2 is highlighted as a symbol, but not arg1

# Case 2a: method definition with defaults
def a_method( arg1: 'val1', arg2: 'val2' ) # arg2 is highlighted as a symbol, but not arg1

# Case 2b: method definition without defaults (indicates a required argument)
def a_method( arg1:, arg2:) # arg2 is correct, but only the colon after arg1 is highlighted
def a_method( arg1: , arg2:) # (space after arg1:) none of arg1: is highlighted
```

#### No problem for standalone hash-literals
I just want to clarify that there is no problem for brace-delimited hash-literals which use keyword-style syntax:
```ruby
a = {arg1: 'val1', arg2: 'val2'} # Highlights correctly for both, very nice!
```

#### Affected versions:
Komodo Edit, version 9.2.0, build 15966, platform win32-x86. Built on Tue Aug 04 21:08:06 2015
Komodo Edit, version 8.5.4, build 14424, platform win32-x86. Built on Thu Aug 14 00:30:57 2014
(also any prior version that I've ever used--I don't believe this is a regression)

**Comment by Naatan** [comment]
So I wasn't able to reproduce this at first because everything looked right on my screen, then I remembered @ervumlens [Style Spy addon](http://komodoide.com/packages/addons/style-spy/) and tried that, issue immediately became apparent. Seriousl @ervumlens, awesome work on that!

![screenshot at 10-57-53](https://cloud.githubusercontent.com/assets/278649/9276726/af9cb5ac-4273-11e5-9548-dc3864cccd20.png)

@mitchell-as all yours :p

**Comment by Defman21** [comment]
Ahh, awesome add-on! That should be included in Test Utils of Komodo dev version!

**Comment by mitchell-as** [comment]
Note to self: This is an issue with Scintilla's Ruby lexer, which has not been updated to accommodate this syntax. The end of the `isHashRocketSuccessorColon` method needs be updated to:

1. Allow for a '('.
2. Allow for a method name style.
3. Allow for `.identifier`.
4. Have a better method name to account for the new Ruby syntax.

**Comment by IronSavior** [comment]
Hey thanks for the fast update, guys! 

I also wanted to mention that there is a slightly different failure mode for case 2. When the default values are not in the method definition and there is no space after the colon, the trailing colon of arg1 is recognized as a symbol. I updated the issue to add an example.

**Comment by IronSavior** [comment]
I do appreciate the fast action on this, but I must point out that it's not quite there yet. Here is a screenshot from the latest nightly.

![image](https://cloud.githubusercontent.com/assets/174661/9321447/6834e964-451b-11e5-85cb-e13968ba84c9.png)

**Comment by mitchell-as** [comment]
I wasn't aware you could define methods with keyword-style arguments and no parentheses (it wasn't in your original set of examples).

The last method call was a corner case I hadn't thought of. Thanks for the report.

**Comment by IronSavior** [comment]
I'm blown away! Very much appreciated! :godmode: :+1:

**Comment by Defman21** [comment]
Thanks for the fix :+1:
