### ISSUE TITLE
Losing settings

### ISSUE THREAD

**Issue by FaimMedia** [Komodo/KomodoEdit#524]
When I update Komodo Edit (or crashes) I lose some or sometimes even all of my settings. This happens on Windows as well as Mac. It's getting very annoying.

I want to have the places sidebar on the left and opened files sidebar on the right. When I update or restart on crash this goes back to default.

**Comment by Naatan** [comment]
To clarify; are you loosing "all of your settings" or are you just using the way you have your panels configured?

**Comment by FaimMedia** [comment]
It's very random really, usually when it crashes I just lose my pane settings. On updating it differs from panes, guide lines, indentation, color schemes to key bindings, or multiple combinations.

**Comment by Naatan** [comment]
That's .. very odd. What platform?

Honestly low chance of us being able to do anything about this unless you can give us something to work with :\ See if you can grab an error log the next time it happens (Help > Troubleshooting > View Log FIle).
