### ISSUE TITLE
Ruby "online definition" is forwarding to an obsolete URL

### ISSUE THREAD

**Issue by ervumlens** [Komodo/KomodoEdit#527]
No biggie. Just looks like the ruby-doc site switched up their search URL.

**Problem**
I'm forwarded to "Online Definition" after attempting to Go to Definition of a builtin Ruby class. The destination page produces a 404 error.

The [preference for the URL](https://github.com/Komodo/KomodoEdit/blob/5c520a13f04d5a5eb8f7d3bed168ca1e6052721b/src/prefs/prefs.p.xml#L582-L604) points to `http://www.ruby-doc.org/find/pickaxe?search=%W`. A valid alternative that I've found is `http://ruby-doc.com/search.html?q=%W`.

Eyeballing the other search URLs, only Ruby and PHP point directly to language sites. The PHP URL appears to work fine when I plug it into a browser with a term. 

**Examples**
Using the URL from Komodo: http://www.ruby-doc.org/find/pickaxe?search=Kernel
Using an alternative URL: http://ruby-doc.org/search.html?q=Kernel

**Comment by pacav69** [comment]
Yes it looks like they changed over to a google search engine.
I tried the query http://ruby-doc.org/search.html?q=komodo and this works.
Just need to modify the preferences in search help for ruby from

open http://www.ruby-doc.org/find/pickaxe?search=%W
to
open http://ruby-doc.org/search.html?q=%W

**Comment by cgchoffman** [comment]
This is resolved with the new docs scope in commando.
