### ISSUE TITLE
CodeIntel isn't aware of the return type of Kernel#gets in Ruby

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#528]
```ruby
login = gets.chomp

puts "Login: #{login.|}"
```
| is the cursor, press Ctrl+J does not shows anything related to String methods, but If I'll use this code
```ruby
login = ""
login = gets.chomp
puts "Login: #{login.|}"
```
then I get methods and variables of `Class` string. @ervumlens described a lot of useful things in this post: http://forum.komodoide.com/t/set-the-type-of-variable-in-ruby-for-komodo-auto-complete/1913/5?u=defman but I'll post it here:
It looks like CodeIntel isn't aware of the return type of `Kernel#gets`. I get no CodeIntel help for the variables used in this code:

```ruby

abc = Kernel::gets
puts abc

ghi = gets
puts ghi

xyz = Kernel.gets
puts xyz

```

But like Defman's workaround, I get help for everything here because I'm assigning directly to strings:

```ruby

abc = ""
abc = Kernel::gets
puts abc

ghi = ""
ghi = gets
puts ghi

xyz = ""
xyz = Kernel.gets
puts xyz
```

Might just be a definition problem somewhere in CodeIntel's Ruby spec.

**Comment by ervumlens** [comment]
It looks like [the CodeIntel catalog for Ruby](https://github.com/Komodo/KomodoEdit/blob/master/src/codeintel/lib/codeintel2/stdlibs/ruby-1.9.3.cix) doesn't specify return values for anything. Here's what `Kernel#gets` looks like (I've removed the documentation attributes here for brevity):

```xml
<scope name="gets" ilk="function" signature="gets(*args)" />
```

In contrast, here's what a random function  [in the Python catalog](https://raw.githubusercontent.com/Komodo/KomodoEdit/master/src/codeintel/lib/codeintel2/stdlibs/python-2.7.cix) looks like:

```xml
<scope ilk="function" name="capitalize" returns="str" signature="S.capitalize() -&gt; string" />
```

CodeIntel knows that Python's `capitalize` returns a string, so all the variables here are always treated like strings even though their types depend on other variables:

```python
#This is Python

a = "foobar"
b = a.capitalize()
c = b.capitalize()
d = c.capitalize()
```

I'm not able to get a custom catalog to work, so I don't know yet if the `returns` attribute is actually the important thing.

**Comment by Defman21** [comment]
Couldn't be this milestoned for 10.0 or 10.1?

**Comment by mitchell-as** [comment]
I'll put it in for 10.1 tentatively.

Note to self: Probably need to modify the Ruby gencix to extract return information (if it's available) from ri/rdoc. If it's not available, then this ticket should be closed.

**Comment by mitchell-as** [comment]
I used the debugger to inspect the RDoc objects from Ruby's ri library (the library we use to produce our Ruby codeintel with) and there is no return type information available. Therefore there's nothing we can infer. Closing ticket.

**Comment by Naatan** [comment]
@mitchell-as is the library we use up to date?

**Comment by mitchell-as** [comment]
Yes, this was from latest Ruby 2.3.

**Comment by tonyattwood** [comment]
Hi,

I  think I 've just found some information that may be helpfull  to you, read it here  please <http://example.doctorkowalski.com/e4ntaol>


tony.attwood@ntlworld.com
