### ISSUE TITLE
In multi caret mode every keystroke is an undo action

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#529]
This only goes for the new multi-caret mode in Komodo 9.3 (current under development).

Open a new file and type "Hello", then press the undo button. Hello will be removed.

Now set 3 carets on 3 lines of the file and type Hello again. It will be typed 3 times as you would expect, but when you press Undo it only removes the character you typed.

This should work the same way as it does for single caret undo actions.

**Comment by mitchell-as** [comment]
This is Scintilla's default undo behavior for multiple selections. There's nothing we can do short of patching Scintilla, which I do not recommend.
