### ISSUE TITLE
Blog page incorrect link

### ISSUE THREAD

**Issue by pacav69** [Komodo/KomodoEdit#533]
in the http://komodoide.com/packages/submit-instructions/#pane-blogs

the link https://github.com/Komodo/komodo-website/tree/master/src/pages/blog

does not exist

**Comment by Defman21** [comment]
Not related to the editor. I'm tracking it here: https://github.com/Komodo/komodo-website/issues/35

**Comment by pacav69** [comment]
transferred to defman21 post
