### ISSUE TITLE
Copied text lost after Komodo is closed (Linux) 

### ISSUE THREAD

**Issue by ervumlens** [Komodo/KomodoEdit#534]
9.2.0 Linux. Cannot reproduce in Windows.

**Problem**
I copied text from an editor in Komodo Edit, then closed Komodo. The text I copied was no longer available to paste. 

This only occurs for text copied from within KE and only from KE editors/buffers. The clipboard is unaffected if the copy occurred in another program before closing KE. Also, I can copy the text from a textbox in Preferences and the text is available to paste after closing KE.

**Steps to Reproduce**
1. Cut or copy some text out of a Komodo editor.
2. Close Komodo.
3. Open some other editor or open Komodo again.
4. Attempt to paste into it.

**Expected**
The copied text appears.

**Actual**
The paste action is not available.

The following macro doesn't produce this problem. Good for you, macro!

```javascript
//this is a javascript macro
xtk.clipboard.setText("Don't blame me! I exist on the clipboard after Komodo is closed.");
```

However, the text copied by this macro does produce the problem. The text is lost after closing KE. 

```javascript
//this is also a javascript macro
var editor = require('ko/editor');
var scimoz = editor.scimoz();
var message = "I have failed you, Master.";

scimoz.copyText(message.length, message);
```

**Comment by ervumlens** [comment]
The lowest I can dig here is [in ScintillaGTK](https://github.com/Komodo/KomodoEdit/blob/258a3bfe3e6fe68dabfa36e691795f9b54d49b75/contrib/scintilla/gtk/ScintillaGTK.cxx#L1749-L1752). The [`gtk_clipboard_set_can_store`](https://developer.gnome.org/gtk2/stable/gtk2-Clipboards.html#gtk-clipboard-set-can-store) call "Hints that the clipboard data should be stored somewhere when the application exits...". There are conditions that reset this, as explained in the documentation.

**Comment by Naatan** [comment]
Hey ervumlens. This is a feature in Linux, not something we could (should) fix. 

See for more details: https://wiki.ubuntu.com/ClipboardPersistence

**Comment by ervumlens** [comment]
Thanks for the link. 

I'm more concerned about this being dropped as "works as intended" than I am about seeing a fix.  I'd like to make a few points to this effect. 

First, [Firefox had the same defect](https://bugzilla.mozilla.org/show_bug.cgi?id=311340), it was logged as a bug, and [fixed as a bug](https://hg.mozilla.org/mozilla-central/rev/270a70535807). This is why Komodo's own `xtk.clipboard` persists data after close.

Second, Komodo is actually doing what the Ubuntu page says will produce persistence:

> GTK+
> Applications that use GTK+ features can provide persistence by setting `set_can_store` on clipboard contents whenever they gain ownership of the clipboard [or by] saving clipboard contents on quit with `gtk_clipboard_store`.

Komodo is [calling `gtk_clipboard_set_can_store`](https://github.com/Komodo/KomodoEdit/blob/258a3bfe3e6fe68dabfa36e691795f9b54d49b75/contrib/scintilla/gtk/ScintillaGTK.cxx#L1749-L1752). The line is there to ensure the clipboard data is persisted after close (as I mentioned above). Some other behavior is preventing that. That other behavior is the bug here.

Third, non-Komodo editors on Linux persist the clipboard data without issue. It's hard to argue that they have a bug and Komodo has a feature. 

I can live without a fix, but I think it's wrong to call the behavior a feature. I hope you'll reconsider reopening this, just as a backlogged enhancement.

**Comment by Naatan** [comment]
I was not aware of this optional persistence, it bugs me that such an inconsistency exists by design. However as it does exist I'd agree that it'd be better to support persistence.

**Comment by ervumlens** [comment]
>  it bugs me that such an inconsistency exists by design.

Same here. I think it's a part of the (apparent) Linux desktop philosophy of "let's have a thousand different ways to do each thing." :disappointed: 

Thanks for reopening it, Nathan.

**Comment by Naatan** [comment]
I think it's more a case of xkcd.com/927 than anything else.

**Comment by Defman21** [comment]
lol this picture is to true! :smile:

**Comment by ervumlens** [comment]
Ha, that's it.

**Comment by Defman21** [comment]
I'm able to reproduce it. Copied `qwerty` from the scintilla view, closed Komodo and I'm not able to paste it anywhere.

Gonna try building Komodo myself to see if the change was backported to the IDE and there's a build for it.

**Comment by Defman21** [comment]
Works fine for me when I'm using my own build (Komodo Edit).

**Comment by mitchell-as** [comment]
Yeah, you'll have to build yourself since we haven't done a nightly yet.
