### ISSUE TITLE
Mapped URI not working

### ISSUE THREAD

**Issue by manngo** [Komodo/KomodoEdit#535]
When I try to add a mapped URI for the project or globally, it doesn’t get saved. I see that this has been reported, but wasn’t followed up with a log. I have attached one below.

System is Windows 8.1. KE version is a freshly installed 9.1 with one addon (HTML Tools) installed. Bug appears on my machine as well as on to other student machine.

Log follows:

```
[2015-08-17 13:15:09,987] [ERROR] console-logger: TypeError: remove is null (2) in chrome://komodo/content/pref/pref-mappeduri.xul:69
Traceback (most recent call last):
  File "chrome://komodo/content/pref/pref-mappeduri.xul", line 69, in 

[2015-08-17 13:15:10,082] [ERROR] console-logger: NS_ERROR_FILE_NOT_FOUND:  (2) in chrome://komodo/content/pref/koFilteredPrefTree.js:681
Traceback (most recent call last):
  File "chrome://komodo/content/pref/koFilteredPrefTree.js", line 681, in 

[2015-08-17 13:15:28,644] [ERROR] prefs: 
-- EXCEPTION START --
TypeError: item is null
+ stack
    getCellText@chrome://komodo/content/bindings/widgets.xml:835:29
    getData@chrome://komodo/content/bindings/widgets.xml:885:39
    get_value@chrome://komodo/content/bindings/widgets.xml:896:8
    koPrefWindow.prototype._getPrefValueFromElement@chrome://komodo/content/pref/koPrefWindow.js:613:17
    koPrefWindow.prototype._doSavePrefElements@chrome://komodo/content/pref/koPrefWindow.js:914:37
    koPrefWindow.prototype.savesinglepageprefs@chrome://komodo/content/pref/koPrefWindow.js:960:14
    koPrefWindow.prototype.savepageprefs@chrome://komodo/content/pref/koPrefWindow.js:950:18
    koPrefWindow.prototype._onOK@chrome://komodo/content/pref/koPrefWindow.js:293:14
    koPrefWindow.prototype.onApply@chrome://komodo/content/pref/koPrefWindow.js:338:16
    koPrefWindow.prototype.onOK@chrome://komodo/content/pref/koPrefWindow.js:329:16
    doOk@chrome://komodo/content/pref/project.xul:203:14
    oncommand@chrome://komodo/content/pref/project.xul:1:1
    openDialogWrap@chrome://komodo/content/komodo.js:532:19
    peFile_Properties@chrome://komodo/content/project/peFile.js:361:13
    projectManager.prototype.doCommand@chrome://komodo/content/project/projectManager.js:1236:13
    projectExtensionManager.prototype.doCommand@chrome://komodo/content/project/projectExtensionManager.js:313:12
    command_doCommand@chrome://komodo/content/library/commands.js:263:1
    command_doCommandAsync/<@chrome://komodo/content/library/commands.js:220:13
-- EXCEPTION END --
```

**Comment by Naatan** [comment]
I cannot reproduce this nor find a likely cause for this issue. Can you show what your mapped uris pref screen looks like when you hit Ok and the problem occurs? Feel free to blur out any sensitive info.

**Comment by manngo** [comment]
Attached.
I have also found the same error on my MacBook, running OSX Yosemite, and a clean install of KE 9.2.
Thanks

![uri mapping](https://cloud.githubusercontent.com/assets/3796633/9318488/4b1902cc-4587-11e5-93e8-a2995ce10057.png)
![project preferences](https://cloud.githubusercontent.com/assets/3796633/9318491/56326f4a-4587-11e5-87de-fdd1899574c1.png)

**Comment by Naatan** [comment]
Reproduced, note it only happens on the Project preferences window. It works fine in the global preferences window (Edit > Preferences).

Possibly related:

```
[2015-08-18 11:07:26,230] [ERROR] console-logger: NS_ERROR_FILE_NOT_FOUND:  (2) in chrome://komodo/content/pref/koFilteredPrefTree.js:681
Traceback (most recent call last):
  File "chrome://komodo/content/pref/koFilteredPrefTree.js", line 681, in 

[2015-08-18 11:07:27,707] [ERROR] console-logger: TypeError: remove is null (2) in chrome://komodo/content/pref/pref-mappeduri.xul:69
Traceback (most recent call last):
  File "chrome://komodo/content/pref/pref-mappeduri.xul", line 69, in 
```

**Comment by ervumlens** [comment]
Agreed, I think the errors in the log are related.

The code producing the `remove is null` error in [pref-mappeduri.xul](https://github.com/Komodo/KomodoEdit/blob/master/src/chrome/komodo/content/pref/pref-mappeduri.xul#L68) looks like so:

```javascript
function onload() {
    // for project prefs, we do not want to inherit the parent prefs
    if (parent.part) {
        document.getElementById("mappings").setAttribute("prefhere","true");
        // Don't want to show the drag/drop preferences for a project.
        var remove = document.getElementById("dropask_groupbox");
        remove.parentNode.removeChild(remove);
    }
    parent.initPanel();
}
```

Adding an `if(remove)` in the right place fixes the URI mapping probably because `parent.initPanel()` is currently not getting hit due to the thrown exception. (I don't propose that this is the ideal solution, but the failure to hit that `initPanel()` call is likely the underlying issue.)

Regarding the `NS_ERROR_FILE_NOT_FOUND` error from [`koFilteredPrefTree.js`](https://github.com/Komodo/KomodoEdit/blob/master/src/chrome/komodo/content/pref/koFilteredPrefTree.js#L681): In Linux, I get a different error in the same general area. However, this appears for me whenever I open a Preferences window, regardless of which set of prefs I'm looking at. E.g., opening file prefs produces this error in the logs. The code has no particular relation to the URI mapping. If there's a genuine problem there, I think it's unrelated.

**Comment by ervumlens** [comment]
FYI, the only reference to `dropask_groupbox` in KE code that I can find is in this `pref-mappeduri.xul` function. Might be worth checking for a reference in the IDE code, in case the `remove` is always going to be null.

**Comment by manngo** [comment]
Further information: two days ago none of us could get it working in the global preferences either. Today we succeeded, but not the first time. All we could think of is that Windows has been restarted, and, of course, so has Komodo Edit.
