### ISSUE TITLE
Rails catalog not working as expected

### ISSUE THREAD

**Issue by ervumlens** [Komodo/KomodoEdit#537]
(From [the forum](http://forum.komodoide.com/t/trouble-enabling-rails-codeintel/1916))

**Problem**
Enabling a CodeIntel catalog does not appear to change the list of suggestions provided by CodeIntel.

**Steps to Reproduce**
1. Open preferences to the Code Intelligence page.
2. Check the "Rails" entry in the catalog list.
3. Restart Komodo, just in case.
4. Create a new Ruby file.
5. Type "Act". 

**Expected**
I get a list of completions that includes [ActionController](https://github.com/Komodo/KomodoEdit/blob/master/src/codeintel/lib/codeintel2/catalogs/rails.cix#L40).

**Actual**
I get a notification saying "No completions found" and no list.

I can also reproduce this with very simple, custom CIX catalogs in Ruby and in JavaScript. Same result when adding them manually in the Preferences page and also when using an `apicatalogs` extension.

CodeIntel notifications appear that suggest the catalogs are recognized and valid. As a negative test, I tried a bad catalog. CodeIntel (correctly) produced errors, so apparently CodeIntel is paying attention. :smiley:

**Comment by Naatan** [comment]
Renamed to "Rails catalog", least until we've verified whether it happens for others also.

**Comment by mitchell-as** [comment]
While this is fixed in git, you need to be within a Rails project in order for Rails completions to show up.
