### ISSUE TITLE
Mac drag and drop files don't open if in split view.

### ISSUE THREAD

**Issue by mjknowle** [Komodo/KomodoEdit#538]
In Ko8.5, you used to be able to drop a file on a Komodo window and it would open. Ko9 sometimes will, but only if you aren't using split view.

**Comment by Naatan** [comment]
The problem is that you can only drop files on the primary view, dropping them on the secondary view won't do a thing.

**Comment by mjknowle** [comment]
Which is all well and good, but 8.5 would accept a drop anywhere and just open it in the main view.

Martin Knowles Photo/Media | Great Places, Great Photos
architectural  interior   exterior   construction progress   real estate
martin@mkphotomedia.com | www.mkphotomedia.com | 604-838-5785

**Comment by cgchoffman** [comment]
I'm not able to reproduce this with 9.3
