### ISSUE TITLE
Improve Unified Menu UX 

### ISSUE THREAD

**Issue by manngo** [Komodo/KomodoEdit#539]
These aren’t bugs, but I have found these irritating issues from a user point of view:
- The windows version makes the traditional menu bar a little too hard to find. Is it possible to show the menu bar more intuitively?
- When opening the addons manager, it still has Recommended Komodo 8 addons. Can this be updated?
- When restarting Komodo Edit, even with the previous project & files open, Komodo Edit does not restore the split view, and does not restore whether a tab has been viewed. Is it possible to save this information and restore it on restart?

Thanks

**Comment by cdcmicro** [comment]
On Windows, you can press and release the Alt key to show/hide the traditional menu bar.

**Comment by Naatan** [comment]
Hi @manngo, I really appreciate you taking the time to report this and hope you will continue to contribute in such a way, however for us to be able to track these issues properly they need to each be reported separately. I apologize for the inconvenience. 

In this particular case, issue 2 and 3 are already being addressed, I'll rename this issue to just be about the first issue (making the unified menu more apparent).

**Comment by cgchoffman** [comment]
Was this fixed?  It's in the same place but I assume you should be used to it by now. Reopen if this is still an issue.
