### ISSUE TITLE
Indentation bug

### ISSUE THREAD

**Issue by ziplizard** [Komodo/KomodoEdit#540]
Just a couple days ago while using KE9, it crashed and prompted to submit a bug report for the issue it encountered. I submitted it with my email. Immediately following the submission, it did an auto update to 9.2.0 build 15966, which I downloaded and installed. Since this time, the indentation is messed up. Despite my Preferences > Indentation being 4 spaces per indent and 4 width of each Tab character (4,4), every file I open is indented to 2,2. The only way I know to correct this is with the Current File Preferences. But I have to do this for every file I open. This is definitely an issue that surfaced since the update. Can someone please look into this and post a patch/update to fix? Thanks.

**Comment by ziplizard** [comment]
See: http://forum.komodoide.com/t/update-with-indentation-issues/1920?u=ziplizard

**Comment by Naatan** [comment]
I'm closing this issue until we've found something we can use in the forum thread.
