### ISSUE TITLE
auto wrap text in Komodo Edit?

### ISSUE THREAD

**Issue by jungle-boogie** [Komodo/KomodoEdit#541]
Hello,

I see in the settings where I can set the vertical bar to indicate when a per-determined line column is met, but I haven't figured out how to have Komodo Edit atually *wrap* the text if it goes beyond the limit,

For instance, set your KE to 80 for the edge line column and get some text from here:
http://www.lipsum.com/feed/html

Paste the text into your KE and observe the text is beyond 80 characters. 

Thanks,
Sean

**Comment by mitchell-as** [comment]
Thanks for the suggestion! Since this is not a trivial addition (and more difficult to get right than you'd think), we'll have to put this on our backlog.

**Comment by jungle-boogie** [comment]
Hello,

So is this to say that it's currently not possible to have an auto line wrapping?

Thanks!

**Comment by mitchell-as** [comment]
Correct, we currently do not modify buffer contents to forcibly wrap lines at X number of characters.

**Comment by Naatan** [comment]
In my opinion this does not belong in an IDE. Code is complex and cannot simply be wrapped at a certain point automatically, it requires a programmer to manage aspects like this, that's part of writing good code.

Note we do have a "Reflow paragraph(s)" command which you can access via keybindings (Prefs > Key Bindings) or via Commando (just search for the phrase mentioned).

You can also set up "virtual" wrapping under `Prefs > Editor > Smart Editing > Wrap long lines by ..` or under View > Word Wrap` on a per-file basis.

That said, I'm closing this issue as I don't feel it's something we should support (actually wrapping your code itself) for reasons mentioned above.
