### ISSUE TITLE
Komodo IDE 9.2 gets very sluggish after a while

### ISSUE THREAD

**Issue by joho1968** [Komodo/KomodoEdit#545]
I can't quite put my finger on when/how it happens, but it happens on three different computers. All running Ubuntu 14.04.LTS 64-bit OS. Sometimes it happens right after I've restored a project, including its open files. Sometimes it happens after a jump between a few files I have open (by clicking on tabs). But it does always happen and it never used to happen prior to 9.2. Looking at "top" output, nothing else is hogging any cores, and no other application shows the same behavior.

I posted this on Twitter as well and was asked to file this here :)

**Comment by joho1968** [comment]
And now when I'm saving stuff, I'm getting this:

[JavaScript.Application]
file_changed--sftp://wps.Dev.GS6/home/dev.html/fooproject/prefs.php
TypeError: views[0].document is undefined

(The text within brackets is the pop-up window title)

What's ... going on? :)

**Comment by Naatan** [comment]
Please report a separate issue for your second problem, we can't address multiple issues in a single thread, it will get chaotic and unmanageable. 

To the topic at hand; you say it happens on 3 machines all running linux. Do these all share the same profile/settings? If not, are there similarities between them in terms of addons/macros isntalled?

I use Linux myself as my daily driver and am not seeing these slowdowns. I use a different distro though.

**Comment by joho1968** [comment]
They don't share anything per se. The project file is written to a DropBox folder, but that's it. I have no addons/macros installed (that I have added outside of what is included in the distribution).

**Comment by joho1968** [comment]
I find a lot of these when this happens (it just did):

[2015-08-25 15:11:14,526] [ERROR] findlib2: `/home/theUser/.config/tmpOldDir/dosdevices/z:/proc/2297/cwd/Music/My Tunes 1': No such file or directory
[2015-08-25 15:11:14,559] [ERROR] findlib2: `/home/theUser/.config/tmpOldDir/dosdevices/z:/proc/2297/cwd/Music/My Tunes 2': No such file or directory
[2015-08-25 15:11:14,592] [ERROR] findlib2: `/home/theUser/.config/tmpOldDir/dosdevices/z:/proc/2297/cwd/Music/My Tunes 3': No such file or directory

There were a _lot_ more of these. I have no idea why it's trying to traverse my various directories/folders. This is just when its idling, after opening the project. Two buffers/files are open with remote files. Nothing is open locally that I can see.

**Comment by joho1968** [comment]
Letting sit like that for a while, it soon runs into this:

[2015-08-25 15:24:33,132] [ERROR] KoObserverService: notifyObservers:: topic: 'customCommonDataDir', data: u'global'
Traceback (most recent call last):
  File "/theUser/Komodo-IDE-9/lib/mozilla/components/koObserverService.py", line 188, in _notifyObservers
    observer.observe(aSubject, aTopic, someData)
  File "/theUser/Komodo-IDE-9/lib/mozilla/components/koToolbox2Components.py", line 744, in observe
    self._activateSharedToolbox(True)
  File "/theUser/Komodo-IDE-9/lib/mozilla/components/koToolbox2Components.py", line 483, in _activateSharedToolbox
    koToolbox2.DEFAULT_TARGET_DIRECTORY)
  File "/theUser/Komodo-IDE-9/lib/mozilla/python/komodo/koToolbox2.py", line 1882, in loadToolboxDirectory
    os.makedirs(actualToolboxDir)
  File "/theUser/Komodo-IDE-9/lib/mozilla/../python/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/theUser/Komodo-IDE-9/lib/mozilla/../python/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/theUser/Komodo-IDE-9/lib/mozilla/../python/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/etc/komodoide'


(there is no /etc/komodoide)

**Comment by joho1968** [comment]
Any news on this ... ?

**Comment by cgchoffman** [comment]
You mentioned your project file is in dropbox which means, I assume, that you share that file between these 3 machines.  That could be causing issues for you.  Unless your directory structure is identical across all 3 machines you're going to get a lot of errors about missing files.  



> File "/theUser/Komodo-IDE-9/lib/mozilla/../python/lib/python2.7/os.py", line 157, in makedirs
> mkdir(name, mode)
> OSError: [Errno 13] Permission denied: '/etc/komodoide'
> 
> (there is no /etc/komodoide)

That looks like either you installed Komodo as root which not recommended or you have a macro in your toolbox trying to create a folder in `/etc/komodoide`.  There is no clear indication of what might be wrong from what you've posted other than the fact that you're setup might be corrupted in some way.

I'd suggest reinstalling while following the [Komodo docs](http://docs.activestate.com/komodo/9.2/install.html#linux).

I would then try running Komodo while [overriding or reseting your userprofile](http://forum.komodoide.com/t/important-file-locations/489), look for the `Overriding The Profile Folder Location` section.  See if the problem persists then.

- Carey

**Comment by Defman21** [comment]
>That looks like either you installed Komodo as root which not recommended or you have a macro in your toolbox trying to create a folder in /etc/komodoide.

Or you have "shared toolbox" enabled.

**Comment by cgchoffman** [comment]
Yikes.  Looks like defman is right.  Do you need that preferences enabled @joho1968?  If you don't, i would disable it Preferences > Shared Support > Enable Share Toolbox.
If you do, you'll need ot give you're user `write` privileges to `/etc/komodoide`.  That's a UX bug and we'll fix that.

**Comment by joho1968** [comment]
I don't need shared support at present, so I'll just go ahead and disable it. Thank you all for your comments, this one was driving me nuts! :)

**Comment by joho1968** [comment]
Hmm ... this did not do the trick. And KomodoIDE is not installed as root. The directory is writeable by everyone (I still have the Shared Toolbox setting disabled). It seems to build up over time. The longer I use it, the more sluggish it gets. Like I said, this only happens on this machine. Not the other two installs.

**Comment by cgchoffman** [comment]
Please try the last suggestion [this comment](https://github.com/Komodo/KomodoEdit/issues/545#issuecomment-142448871).

**Comment by joho1968** [comment]
KomodoIDE was traversing symlinks found in the .config/teamviewer8 directory in my home directory. This is not present on any of my other machines. findlib2 kept generating errors, and it seems KomodoIDE was all over the disk (because there are other symlinks) ... I think that kills the mystery. But it doesn't explain why it was doing it :)

**Comment by joho1968** [comment]
But now it runs into other issues while traversing directory structure. This is present in /home/joho/Desktop/teamviewer8/profile:

    drwxrwxr-x 5 joho joho   4096 sep 11 10:44 ./
    drwxr-xr-x 7 joho joho   4096 maj 18 13:46 ../
    drwxrwxr-x 2 joho joho   4096 sep 11 10:43 dosdevices/
    drwxrwxr-x 6 joho joho   4096 maj 18 13:46 drive_c/
    -rw-rw-r-- 1 joho joho 232301 sep 11 10:44 system.reg
    drwxrwxr-x 2 joho joho   4096 maj 18 13:46 .tweak/
    -rw-rw-r-- 1 joho joho     11 maj 18 13:46 .update-timestamp
    -rw-rw-r-- 1 joho joho   2131 maj 18 13:46 userdef.reg
    -rw-rw-r-- 1 joho joho  30040 sep 11 10:44 user.reg

In particular, dosdevices contains this:

    drwxrwxr-x 2 joho joho 4096 sep 11 10:43 ./
    drwxrwxr-x 5 joho joho 4096 sep 11 10:44 ../
    lrwxrwxrwx 1 joho joho   47 sep 11 10:43 c: -> /home/joho/Desktop/teamviewer8/profile/drive_c//
    lrwxrwxrwx 1 joho joho    1 sep 11 10:43 z: -> //

Partial error message output from KIDE log:

[2015-10-06 13:23:41,296] [ERROR] findlib2: `/home/joho/Desktop/teamviewer8/profile/dosdevices/z:/proc/3961/cwd/proc/9002': No such file or directory
[2015-10-06 13:23:43,371] [ERROR] commando-scope-files-py: OSError while walking path: /home/joho/Desktop/teamviewer8/profile/dosdevices/z:/proc/3961/cwd/run/udisks2
[2015-10-06 13:23:43,391] [ERROR] commando-scope-files-py: OSError while walking path: /home/joho/Desktop/teamviewer8/profile/dosdevices/z:/proc/3961/cwd/run/lightdm
[2015-10-06 13:23:46,122] [ERROR] findlib2: `/home/joho/Desktop/teamviewer8/profile/dosdevices/z:/proc/3961/root/proc/9002': No such file or directory

Why does KIDE need to index my entire computer .... ??

**Comment by Defman21** [comment]
Komodo indexes your home folder (not your entire computer) because when you open Komodo, the default path in places is your $HOME directory. findlib2 cannot parse your teamviewer paths because they contains both linux- and windows-specific things like `/this/is/a/linux/path` and `z:/this/is/a/windows/path` (which is can be used in Windows, but the right path is `z:\this\is\a\windows\path` IIRC)

**Comment by joho1968** [comment]
So perhaps it could understand that it doesn't understand it ... ? :) What would happen if it ran into a wine configuration? I'm afraid I cannot control how Teamviewer does its thing. Is the $HOME directory used for anything else? Can I change it? Can I force it to prevent the scan with some CL-parameter?

**Comment by joho1968** [comment]
And the weird thing is ... that it does actually scan it. And there are a zillion proc directories. Now I've removed the teamviewer folder, both from $HOME and from $HOME/Desktop and the sluggishness is gone.

**Comment by Defman21** [comment]
Just append `;.*` to `Preferences - Places - Files and directories to exclude`. Then re-start Komodo and try to navigate to your home folder - you shouldn't see any `.dot` folders anymore.

**Comment by Defman21** [comment]
And yes, $HOME directory is used for your... home directory :P
`$HOME` = `/home/joho/` in your case.

**Comment by joho1968** [comment]
I know what ~/ is ... I meant, what does KIDE use it for ;) Well, removing the teamviewer directories has, for now, solved everything. If this is a WAD, then by all means, close it. I don't this is good behavior ... but .... :)

**Comment by Defman21** [comment]
Komodo stores its preferences in `.komodoide` or `.komodoedit`, and a license key in `.activestate` IIRC. I agree with you, this behavior is strange. I don't see any reasons to show `.dotted` folders by default. It's not enabled in any File Manager by default and I don't know why Komodo does it. But as I said, it's easy to implement this behavior - just append `;.*` to the preference I mentioned, it means that any `.folder` or `.file` where the first symbol is `.` will be excluded from the scanning process.

**Comment by joho1968** [comment]
:+1:

**Comment by cgchoffman** [comment]
> Why does KIDE need to index my entire computer .... ??

As the error reports, that's Commando indexing your files so that you can use Commando to access files.  It does  look like something is wrong there.  @Naatan is going to take a look.  Thanks for bring that to our attention.

**Comment by Naatan** [comment]
Note that while Commando should try and warn you when you are using it on a large directory structure, the real solution for you is to not point Komodo at eg. your home folder, because Komodo will scan your entire folder for files when you start using Commando. 

I would recommend you have a look at the projects screencast, learn to use Komodo the right way so it can work with you: http://komodoide.com/screencasts/

My fix will be useless to you if you continue to use Commando on a large folder, at most you'll get a warning and limited functionality because Commando won't scan all your files (even the ones you DO care about).

**Comment by joho1968** [comment]
OK, point taken.

The problem is that I haven't done "anything" to make Komodo behave this 
way. So I'd say the default behavior of Komodo in this case is wrong. It 
has nothing to do with "learning to use Komodo the right way". This is 
an out-of-the-box installation. I just happened to have a certain type 
of folder/directory/symlink structure that (IMHO), Komodo cannot handle 
properly.

If there's a risk of this happening, Komodo should _not_ have this 
enabled by default.
