### ISSUE TITLE
Publishing: Publish without syncing

### ISSUE THREAD

**Issue by AtmanActive** [Komodo/KomodoEdit#548]
Please add an option in the Publish Tool dialog/function to completely bypass syncing, but only use 'When a file is saved localy, auto-push it to the remote server' functionality.

This would effectively obsolete the addon called Uploader https://community.activestate.com/xpi/uploader?page=1

Rationale:
When working on huge projects (cca 61,084 Files, 11,154 Folders), all SFTP sync options become too slow to be usable, including WinSCP's built-in or rsync or the slowest of them all: Komodo's Publish Sync. The one and only tool that is able to do a sync in minutes instead of hours is Unison (http://www.cis.upenn.edu/~bcpierce/unison/), hence I'm forced to use that one for my syncing needs.
But, in my workflow, I keep my SVN dir on a remote linux server, not on my local windows machine,  which means that I need upload-to-server-on-each-save functionality in Komodo. My local windows machine is just a super-fast editor (as it is local), while all bulk changes get synced with Unison from my remote linux machine, but all file-by-file changes get uploaded-on-save so I can test/preview them on the linux machine right away.
The possibility to hit save on my local machine and then hit refresh in my browser to view the results on the remote linux server immediately is a must for me.
Now, when I started test driving Komodo IDE 9 to consider it for replacing my good old Komodo Edit 8, I tried using built-in Publish tool for that, but I just couldn't wait for SFTP sync analysis process to complete. It was taking too long, going too slow, to be even considered as a working solution. I understand that once initial sync is done, it should work much faster later, but still, it is unacceptably slow for me. Hence, I'm back to using 'uploader-1.62.xpi' to achieve this.

So I feel like opportunity missed with new Komodo and Publish tool, and just wanted to let you know.

Cheers!

**Comment by cgchoffman** [comment]
Closing this ticket for #148 as per my comment [here](https://github.com/Komodo/KomodoEdit/issues/148#issuecomment-203484840)
