### ISSUE TITLE
IDE - bad filenames in Open Files tab

### ISSUE THREAD

**Issue by cdcmicro** [Komodo/KomodoEdit#549]
I have IDE 9.2.0 on Win7 x64.  When I open a new file from a template, then save the file, the name in the Open Files tab does not update to match the newly-saved name.  Screenshot below.

If I open a new default file (Ctrl-N), then save it, the name in the Open Files tab updates as expected.

![screenshot_082015_073842_am](https://cloud.githubusercontent.com/assets/13684992/9386022/7c1cb12e-470e-11e5-9ba3-b751aa13454a.jpg)

**Comment by cdcmicro** [comment]
More info - attempting to rename the newly-saved file (right-click the file's tab, then choose "File Actions", Rename) updates the name in the Open Files tab, then raises an error (screenshot below).

![screenshot_082015_074708_am](https://cloud.githubusercontent.com/assets/13684992/9386293/a9c57b00-470f-11e5-857b-24430e097291.jpg)

**Comment by Naatan** [comment]
Thanks, reproduced. Seems to have something to do with the template functionality. I think it's not firing the proper events when starting a new file.

**Comment by cdcmicro** [comment]
You're probably aware this issue is partly fixed in 9.2.1 in that the rename activity described above no longer throws the exception.  Makes for a "less ugly" workaround :-)

**Comment by Naatan** [comment]
Should be fixed in 9.3.
