### ISSUE TITLE
Groupbox's title horrible gray background

### ISSUE THREAD

**Issue by srgloureiro** [Komodo/KomodoEdit#55]
In the Preferences Dialog, the titles' Groupboxes should not have that horrible gray background. It is happening in Komodo 9 on Windows 8.1

**Comment by cgchoffman** [comment]
Hi srgloureiro, could you clarify what you're referring to (ie. a screenshot)?  Also what Appearance setting you have in Preferences?
You could try cycling the Appearance setting regardless of the above to see if it resolves the issue you're seeing.

**Comment by srgloureiro** [comment]
See the effect in ![Preferences Dialog](http://i.imgur.com/D2FjR7e.png)
It is very visible on the "Interface" groupbox. It happens in Default and Classic Skins.

**Comment by Naatan** [comment]
I think this is just how Mozilla renders groupboxes. I agree it looks a bit outdated, but I wouldnt quite call it "horrible" :p

**Comment by Defman21** [comment]
The new UI fixed it I assume.

**Comment by cgchoffman** [comment]
Yep
