### ISSUE TITLE
CoffeeScript linter needs refreshing

### ISSUE THREAD

**Issue by ervumlens** [Komodo/KomodoEdit#550]
[The CoffeeScript linter](https://github.com/Komodo/KomodoEdit/blob/1b55437228cf6828a13d74dc9d7556e34bb3d8fd/src/lint/koJavaScriptLinter.py#L482) expects an older version of the `coffee` executable. This prevents the linter from working properly.

Two problems are immediately apparent:

* [The `-l` option](https://github.com/Komodo/KomodoEdit/blob/1b55437228cf6828a13d74dc9d7556e34bb3d8fd/src/lint/koJavaScriptLinter.py#L529) tells `coffee` that the input is [Literate CoffeeScript](http://coffeescript.org/#literate) rather than normal, illiterate CoffeeScript. 
* The format of errors has changed.

[Old format regex](https://github.com/Komodo/KomodoEdit/blob/1b55437228cf6828a13d74dc9d7556e34bb3d8fd/src/lint/koJavaScriptLinter.py#L540-L541): 
```
^Error: In (.*),\s*(.*) on line (\d+):\s*(.*)
```

New format example:
```
/home/ervumlens/projects/coffeescript-linter/test.coffee:1:19: error: unexpected number
s9wu0r930u09 2394 2340 32409 23409 23490 
                  ^^^^
```

**Comment by ervumlens** [comment]
May also be worth changing the use of option `-c` (compile to file) to `-p` (compile to stdout), to avoid creating temp files.

**Comment by Naatan** [comment]
Thanks @ervumlens, we'll definitely want to look into this for 9.3
