### ISSUE TITLE
Feature Request: Include Komodo Edit 8 Default Scheme

### ISSUE THREAD

**Issue by manngo** [Komodo/KomodoEdit#553]
I use Komodo Edit as the must-have coding editor for teaching web technologies.

Komodo Edit 9 has some nice new colour schemes, but I find none of them is clear as the old default scheme used in Version 8. In particular, when using a projected screen, the colours of this scheme display best, but I also find that new students are comfortable with this plain scheme.

No one is suggesting that this scheme is the most artistic or should be re-instated as the default, but would it be possible to include it as one of the standard schemes, possibly renamed to “Komodo 8” or “Classic” or “Nostalgic” … ?

**Comment by Naatan** [comment]
Is there any value in this being included by default versus offered as an optional download on our website?

**Comment by manngo** [comment]
Just a small advantage. I don’t think you can access colour schemes from within Komodo Edit, so students need to go through an extra process in setting up in class, and again when they return to their home or workplace.

Currently I give them an exported copy of the scheme and show them how to drag it onto Komodo Edit, so it’s not a big deal.

**Comment by Naatan** [comment]
Actually you can, as of Komodo 9.2 you just hit the little package icon next to the color scheme dropdown to select your preference.

Why force your students to use a color scheme though? That seems entirely subjective.

**Comment by Defman21** [comment]
You can't install Komodo classic schemes pack via Packages Manager because it doesn't contain any ksf files in the release, only a zip archive: http://komodoide.com/packages/schemes/komodo-classic-schemes/
I'll fix it tomorrow (by publishing a lot of binaries to the release)

**Comment by Naatan** [comment]
The package installer will only allow for one ksf file, so the only way to make that work is if you were release them as separate Komodo packages.

**Comment by Defman21** [comment]
Ahh crap. Well I'll release a lot of Komodo packages then. Hope you won't blame me if I won't create a `readme.md` for each package in the packages, it's boring :stuck_out_tongue:

**Comment by manngo** [comment]
I didn’t notice the package icon. That would be perfect once the particular scheme is available.

I’m not actually requiring the students to use a particular scheme. It’s just that this particular scheme has a white background without gaudy colours, and so it’s a good starting point, especially on some of the awful screens some of them will be using. I know that once I show them how to change schemes some of them will go crazy, which is all part of the fun.

Thanks

**Comment by Naatan** [comment]
Alright, thanks for explaining @manngo :) Will close this as I think the workaround suggested will suffice.
