### ISSUE TITLE
Option to disable opening files from the code.

### ISSUE THREAD

**Issue by damianszk** [Komodo/KomodoEdit#554]
There is a feature in Komodo that, without prompt, opens files from the code when the link is clicked (python). The problem is that Komodo hangs when opening large files (1Gb+). I have to manually kill Komodo couple of times a day because of that. 

How to resolve:
1. Give the option to disable the feature (preferred) 
2. Prompt if I actually wanted to open the file.
3. Time-out after couple of seconds.

**Comment by ervumlens** [comment]
Have you tried disabling hyperlinking in Preferences? There are two options under the "Hyperlinks" heading in Editor &rarr; Smart Editing:

![screenshot - 08242015 - 12 40 37 pm](https://cloud.githubusercontent.com/assets/13005338/9447514/6573ea30-4a5d-11e5-8d37-0a3b16c8baa7.png)

Might be worth a try.

**Comment by Defman21** [comment]
@ervumlens you're right. @damianszk you should disable those options (you just can disable the first one, the second will be disabled automatically) to solve the problem :smiley:
