### ISSUE TITLE
Command in the toolbox that depends on %p (active project directory) no working in Komodo IDE 9.2 on Windows 7

### ISSUE THREAD

**Issue by Roeya** [Komodo/KomodoEdit#558]
I have several commands to handle Perl modules in the Toolbox
perl Makefile.PL
dmake
dmake install
dmake test
They all stopped working in Komodo 9.2 they all use the Start in %p option
I get Can't open perl script "Makefile.PL": No such file or directory 
although the module as a project file and the project is active
They all work fine on Komodo IDE 8.5

**Comment by ervumlens** [comment]
I think you're seeing the same problem as #514 (problems with `%p`, `%f`, etc in Windows).

**Comment by mitchell-as** [comment]
Correct. This should be fixed in upcoming 9.2.1.
