### ISSUE TITLE
Prompt error when opening komodo

### ISSUE THREAD

**Issue by harpreetsb** [Komodo/KomodoEdit#559]
how to figure this out,
![selection_013](https://cloud.githubusercontent.com/assets/6584304/9514594/0110c730-4cb9-11e5-9af3-bf83faaac308.jpg)

**Comment by harpreetsb** [comment]
I have tried clearing all preferences(deleting .komodo-edit directory from home)

**Comment by mitchell-as** [comment]
Hi, it looks like Komodo Edit is trying to read a non-existent file from a previous session. Please close Komodo Edit and then delete both "~/.activestate" and any "~/.komodo*" directories before trying to reopen Komodo Edit. Also ensure you don't have a `KOMODO_USERDATADIR` environment variable set with a different path.

**Comment by mitchell-as** [comment]
It looks like Komodo is still trying to open a file from a previous session. Is that file contained anywhere within your "~/.komodoedit/9.x/prefs.xml" file?

**Comment by harpreetsb** [comment]
no html in 
`/.komodoedit/9.x/`
well this error goes as soon as i open a project and restart  komodo.

**Comment by mitchell-as** [comment]
Sounds like this is resolved then. Closing ticket.

**Comment by Naatan** [comment]
Reopening this so we can clean up that error, which doesn't seem very user friendly.

**Comment by cgchoffman** [comment]
Just going to assign to you nathanr, I don't know what you have in mind for cleaning up the error.

**Comment by Naatan** [comment]
Closing as the place where this error is triggered is too generic to give a proper error message. If it happens again please post your error log.
