### ISSUE TITLE
Collaboration connection problem blocks file saving

### ISSUE THREAD

**Issue by tuckdesign** [Komodo/KomodoEdit#560]
Hi,
When I start a session for collaboration and add relatively big file (eg. 260k) collaboration pane is stucked with message "Collaboration encountered a communication error and will recover automatically" (but that doesn't happen). There are no session or file list and I am not able to unshare file from session or even save it locally! Only solution is to restart komodo and then delete file from session.

**Comment by Naatan** [comment]
We'll track this in #561 (since I already responded there).

**Comment by tuckdesign** [comment]
This bug is not the same as #561 This is about not being able to do anything with file if collaboration is in state of reconnecting. I am not able even to save file locally.
