### ISSUE TITLE
Incorrect code folding caused by multiline comments (JS)

### ISSUE THREAD

**Issue by ReinarKein** [Komodo/KomodoEdit#571]
There is a bug: when there is no white space after '//' in multiline code, code folding works incorrectly. Please, fix.

First line causes bug:
```javascript
//var layer = self.leafletLayer;
// _map.on('almost:over', function(e) {
//    e.layer === self.leafletLayer ? self.addNewWaypointMarker.addTo(_map) : null;
```
![2015-09-03_12h17_04](https://cloud.githubusercontent.com/assets/10982017/9654808/c87b304a-5235-11e5-8250-7ca8eb008462.png)

White space inserted:
```javascript
// var layer = self.leafletLayer;
//  _map.on('almost:over', function(e) {
//     e.layer === self.leafletLayer ? self.addNewWaypointMarker.addTo(_map) : null;
```
![2015-09-03_12h17_27](https://cloud.githubusercontent.com/assets/10982017/9654809/c87f815e-5235-11e5-9a08-fff075f59019.png)

**Comment by Naatan** [comment]
Can you provide a code snippet to reproduce the problem?

**Comment by ReinarKein** [comment]
Here it is:

```javascript
(function () {
    var _abc = (function() {
        
        var abc = function() {

            this.abcd = function() {
                
                
                //var layer = blah;
                // _map.on('almost:over', function(e) {
                //    e.layer === sblah ? blah : null;
                // });
                // _map.on('almost:move', function(e){
                //    e.layer ===  blah ? blah : null;
                //});
                // _map.on('almost:out', function(e) {
                //    e.layer === blah ? blah : null;
                //});
                
                
            };
            
            
        };
        var blah = function() {};
        
        return {
            1: 1,
            2: 2,
            3: 3,
            4: 4
        };
        
    })();
})();
```
![2015-09-03_18h17_47](https://cloud.githubusercontent.com/assets/10982017/9662440/1d9cb396-5268-11e5-91be-c1b4d8454da8.png)

**Comment by ervumlens** [comment]
Here's a simplified case.

Source:

```javascript
// This is javascript
function foo() {
	//}
	var IShouldBeHidden = true;
}
```

Unfolded (works):
![screenshot - 09032015 - 02 37 07 pm](https://cloud.githubusercontent.com/assets/13005338/9668813/514459fc-5249-11e5-8af3-c8cf80cf4224.png)

Folded (problem):
![screenshot - 09032015 - 02 37 25 pm](https://cloud.githubusercontent.com/assets/13005338/9668817/56340872-5249-11e5-84f1-a5a06a83eb60.png)

As  ReinarKein mentions, a space in the comment fixes the problem:

Source:

```javascript
// This is javascript
function foo() {
	// }
	var IShouldBeHidden = true;
}
```
Folded (works):
![screenshot - 09032015 - 02 39 00 pm](https://cloud.githubusercontent.com/assets/13005338/9668848/8ebb4fe8-5249-11e5-9a03-4cb5448d9f9a.png)

**Comment by ervumlens** [comment]
Possibly related ("closed-invalid" Scintilla bug): http://sourceforge.net/p/scintilla/bugs/1676/

**Comment by tonyattwood** [comment]
Hi,

There are a couple of books  that inspire me to do  really great things, here is the list of that books <http://fast.ioutax.com/e4xnrrc>

Warmly, tony.attwood@ntlworld.com
