### ISSUE TITLE
Reflect relevant scintilla margins in Minimap

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#573]
Show:
 - breakpoints
 - bookmarks
 - trackchanges locations

**Comment by Defman21** [comment]
I think you can close this in favor of https://github.com/Komodo/KomodoEdit/issues/1887

**Comment by Naatan** [comment]
Yeah this should be in #1887. It's not technically feasible to add this to the minimap (we've had an issue for this before, that's where #1887 came from).
