### ISSUE TITLE
Show syntax error indicators in minimap

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#574]
Indicate lines in minimap that have syntax errors.

**Comment by ervumlens** [comment]
> Indicate lines in minimap that have syntax errors.

That's not current functionality? :confused:

![screenshot - 09032015 - 02 48 36 pm](https://cloud.githubusercontent.com/assets/13005338/9669121/e213ec94-524a-11e5-90fb-ee3300226ac0.png)

**Comment by Naatan** [comment]
I think we want to make it more obvious. Eg. color those lines red instead of show a tiny squiggly.

**Comment by ervumlens** [comment]
Gotcha. It would be nice having it cover the whole line:

![screenshot - 09032015 - 02 52 53 pm](https://cloud.githubusercontent.com/assets/13005338/9669247/7842a3a4-524b-11e5-8617-c95e7e7a6add.png)

**Comment by cgchoffman** [comment]
Closing in favour of #1157.
