### ISSUE TITLE
Spellchecker: doesn't update state when word is changed

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#576]
Example:
- write a string like "currentline"
- Komodo will underline it as spelled wrong
- add space between to make "current line"

Expect: red underline to go away 
Actual: Red underline spans the space you added.  you can even add a new line char and it still highlights.

**Comment by mitchell-as** [comment]
I haven't been able to reproduce this. Please update to latest git and re-open if you still see this.

**Comment by cgchoffman** [comment]
Can't repro with latest code.
