### ISSUE TITLE
File tab context menu: Collab: add to session only shows currently active session

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#578]
Right click on a file in open files or on it's tab (if you're showing them), Collab > Share in existing session > ...

Expect: I see a list of all the sessions in my collab
Actual: NOPE.  I have to switch to the session I want the file in then use the context menu.

**Comment by mitchell-as** [comment]
I forgot to mark this as fixed by https://github.com/Komodo/KomodoIDE/commit/b915c250e0cba21138066ad94551192dca7b3d11. It is in Komodo X.

**Comment by tonyattwood** [comment]
Hi,

We haven't talked for  a  while so I  just wanted to say Hi and share with you some information, read  more here please <http://famous.coolminuspromo.com/e4ujb>

In haste, tony.attwood@ntlworld.com
