### ISSUE TITLE
Changebar not working

### ISSUE THREAD

**Issue by ffxsam** [Komodo/KomodoEdit#579]
Komodo 9.2 on Mac OS. Changebar revert has no effect.

It also glitching earlier but I can't replicate it now. When I clicked on the changebar on the side, it would pop up for a very brief second then go away.

![licecap](https://cloud.githubusercontent.com/assets/12532733/9691869/250cadc4-52fa-11e5-9c5e-da4a9c0a280f.gif)

**Comment by cgchoffman** [comment]
I can't repro on Windows, works just fine for me.  Can someone try Linux and confirm OSX?

**Comment by Defman21** [comment]
I can try Linux using the latest **IDE** nightly.

**Comment by Defman21** [comment]
Naah. Everything works fine for me on Linux.

**Comment by ffxsam** [comment]
Here's the changebar popup glitch.

![licecap](https://cloud.githubusercontent.com/assets/12532733/9692005/0f20ee5c-52fb-11e5-82d4-60e7064e8c24.gif)

**Comment by cgchoffman** [comment]
> Here's the changebar popup glitch.

Please file as a separate bug.  For that and this bug please provide your logs; Help > Troubleshooting > View Log File

**Comment by Naatan** [comment]
Same as on the other bug, please try the nightly > http://downloads.activestate.com/Komodo/nightly/komodoide/latest-9.2.x/

**Comment by ffxsam** [comment]
Works in 9.2.1! Except for a slight usability bug: when the dialog pops up, it takes two clicks: one click to focus the dialog, a second click for "Revert Changes." The dialog should auto-focus.

**Comment by Naatan** [comment]
Yeah, that's a known bug on OSX caused by something that I have yet to determine. Its' the lesser of several evils at the moment, hopefully I can properly fix it in 9.3.
