### ISSUE TITLE
Changebar popup glitch on Mac OS

### ISSUE THREAD

**Issue by ffxsam** [Komodo/KomodoEdit#580]
Komodo IDE 9.2, Mac OS 10.10.5.

![licecap](https://cloud.githubusercontent.com/assets/12532733/9692089/975460ce-52fb-11e5-8a49-1e869a269b26.gif)

**Comment by Defman21** [comment]
I've reproduced it as well on Linux.

**Comment by Naatan** [comment]
I believe the nightly should fix this > http://downloads.activestate.com/Komodo/nightly/komodoide/latest-9.2.x/

**Comment by Defman21** [comment]
It's not. Able to reproduce in the latest nightly. Happens randomly for me :\

**Comment by Naatan** [comment]
@ffxsam can you confirm? I don't want to assume you two are seeing the same issue.

**Comment by ffxsam** [comment]
No more glitch for me in 9.2.1! Not so far, anyway.

**Comment by Naatan** [comment]
Great, @Defman21 please open a new bug for your issue if you can reproduce it.

**Comment by Defman21** [comment]
Yeah okay :)
