### ISSUE TITLE
Changebar popup glitch on Linux

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#581]
Same as #580 but on Linux using the latest nightly (Komodo IDE 9.2.1 build 87651)
Able to reproduce if I'm clicking very close to the editor area, if I'm clicking right on the changebar - it works fine for me (but If I've clicked very close to the editor area, got the bug, and then clicked on the changebar again - I'm still able to reproduce it, to work-around it I have to wait 1-3 seconds before I can click on the changebar again). Nothing appears in the log (at least nothing useful and related to the changebar behavior).

**Comment by Defman21** [comment]
Just recorded a video where you can see how the bug "works" exactly. Maybe you'll find something useful for debugging/reproducing the bug.
https://youtu.be/9L6HaZr_vV4

**Comment by Naatan** [comment]
I'm not able to reproduce this at all :\ What desktop environment are you using?

**Comment by Defman21** [comment]
Unity, huh.
