### ISSUE TITLE
Allow Keybindings with Mouse Event

### ISSUE THREAD

**Issue by Dgame** [Komodo/KomodoEdit#584]
I would love to see overloadable Mouse Events. That would allow me to use STRG + Left Mouse-Click for Multiple Cursors. Would that be possible?

**Comment by Naatan** [comment]
Sort of, you'd have to add actual event listeners with JS and override any existing event handlers (preventDefault()). It's not something that we'd be supporting as a native feature through eg. the preferences window.

Please open a thread on the forum if you'd like to discuss further :)

**Comment by Dgame** [comment]
I did that and [you meant](http://forum.komodoide.com/t/sublime-multiline-behaviour/1856) that I should open a feature request. Is that the wrong place for feature requests?
