### ISSUE TITLE
[Solved]Auto-completition popup window location bug

### ISSUE THREAD

**Issue by ik9999** [Komodo/KomodoEdit#585]
![bug2](https://cloud.githubusercontent.com/assets/6804575/9704288/be5f9756-54a9-11e5-92cb-387d61cb153a.png)
![bug1](https://cloud.githubusercontent.com/assets/6804575/9704289/be627dd6-54a9-11e5-9be8-694a475d7a00.png)

OS: Ubuntu 14.04
Window manager: Awesome WM
Komodo IDE version: 9.2.1-87651(also tried 87616)
Bug:
Start typing.
Auto-completition popup appears higher than it should be(~1/2 line).

**Comment by Defman21** [comment]
Are you using non-standard DPI by a chance? (Not equal to 90)

**Comment by ik9999** [comment]
I am using laptop.
My DPI is 127 pixels per inch.

**Comment by Defman21** [comment]
Yeah, you're using a non-standard value for DPI. Komodo has some problems with positioning when using custom DPI (not 90). Am I right @Naatan?

**Comment by ik9999** [comment]
Changed screen DPI to 90.
>xdpyinfo | grep dots
>resolution:    90x90 dots per inch
Its different now, but still not as it should be.
![bug3](https://cloud.githubusercontent.com/assets/6804575/9704487/77772784-54b1-11e5-8242-2c32d41a5a86.png)

**Comment by Defman21** [comment]
Excuse me, 96 is the right DPI.

**Comment by ik9999** [comment]
Works fine now, thank you.

**Comment by ervumlens** [comment]
Good catch, @Defman21 . Looks like #162, with the same effect I'm seeing (https://github.com/Komodo/KomodoEdit/issues/162#issuecomment-129976281).

**Comment by Defman21** [comment]
Yep, you're right. I was affected by this issue. Now I'm using 96 DPI (but my monitor's DPI is 90, huh).
