### ISSUE TITLE
Golang support: Error compiling outline

### ISSUE THREAD

**Issue by stef-k** [Komodo/KomodoEdit#587]
Every time I open a Go file i get the following error:

`Error compiling outline: Unable to compile 'outline.go'[Errno 2] No such file or directory: 'go'`

Resulting total absense for go support in IDE (no auto complete,  gofmt deletes whole file). The only working thing is error checking.

OS Ubuntu 14.04 64bit
Go 1.5 installed using `tar -C /usr/local -xzf go$VERSION.$OS-$ARCH.tar.gz` as mentioned at https://golang.org/doc/install

**IDE setup**:
![go_setup](https://cloud.githubusercontent.com/assets/5731388/9713737/078bc924-555c-11e5-9680-ed22fe15ed36.png)

also `GOPATH` has been set (In environment prefs)

Tested with - without paths to Go tools & with - without GOPATH variable set without any luck

**Comment by Naatan** [comment]
Are you running Komodo 9.2?

**Comment by stef-k** [comment]
Yes, I am running the latest Komodo IDE.

**Comment by stef-k** [comment]
Problem still persists in Komodo IDE 9.2.1 (Go 1.5.1)

**Comment by ervumlens** [comment]
Hi @stef-k , could you run a few commands to get all the numbers in one place? The actual, raw output helps us avoid hold-ups in these system-related situations.

1. Open a terminal and run `which go`. Please copy the output here.
2. From the same terminal, run `go version`. Please copy the output here.
3. From the same terminal, launch Komodo IDE manually (something like `~/Komodo-IDE-9/bin/komodo`), then run the following in a Python macro:

```python
import which

window.alert(which.which('go'))
```
... And type or screenshot the output here.
4. Close Komodo, then start it again like you normally would (i.e., not through a terminal). Re-run the macro, and type or screenshot the output here. (Skip this step if you normally launch from a terminal.)

**Comment by stef-k** [comment]
Hi, thanks for the response, here is the requested info about the issue:

`which go` output `/usr/local/go/bin/go
`

`go version` output `go version go1.5.1 linux/amd64
`
python macro output Komodo launched from terminal `/usr/local/go/bin/go`

python macro output Komodo launced through system UI:

![macro_output](https://cloud.githubusercontent.com/assets/5731388/9798453/9fcf9404-5809-11e5-85b9-1fb897757761.png)

**Comment by ervumlens** [comment]
That helps give some direction, thanks for your patience. I used a different installation process, so I'll have to feel around a bit to see what's happening for you.

Below is a macro that shows a few more things from Komodo's perspective. Could you run this from Komodo twice -- once when launched from the terminal and again when launched from the UI -- and copy the results here?

You may get different results depending on how you have your preferences configured. If you feel compelled to run the macro with some other configurations, don't hesitate to do so. The results might be useful.

Also, feel free to censor anything in the output that's not related to Go.

```python
# This is a Komodo Python macro

import os
import which

def try_env(varname):
	try:
		return "env: %s = %s\n" % (varname, os.environ[varname])
	except:
		return "env: %s not found.\n" % varname

def try_which(binname):
	try:
		return "which: %s = %s\n" % (binname, which.which(binname))
	except:
		return "which: %s not found.\n" % binname

msg = ""
msg += try_env('PATH')
msg += try_env('GOROOT')
msg += try_env('GOPATH')
msg += try_which('godef')
msg += try_which('gocode')
msg += try_which('gofmt')

window.alert(msg)

```

**Comment by Naatan** [comment]
If you explicitly defined Go then the result of `which` should be irrelevant. I'm not sure why this is still a problem though, this exact problem was [fixed here](https://github.com/Komodo/KomodoEdit/commit/cb73f0c26d14673e6d87af7da73276346b2cbcc7).

Could you see what this returns if you run it as a macro? `alert(ko.prefs.getString('gocodeDefaultLocation'))`

**Comment by stef-k** [comment]
@ervumlens macro results, note that GOPATH env variable is set in IDE

![macro_output](https://cloud.githubusercontent.com/assets/5731388/9819507/1ae4a7a8-58b7-11e5-93d7-a37fb8c0a432.png)

GOPATH from IDE preferences

![macro_output](https://cloud.githubusercontent.com/assets/5731388/9819540/57dc467a-58b7-11e5-9b42-a66b9345fcb4.png)

@Naatan additionally I have set Go binary tools path in IDE preferences as shown in the first screenshot just in case. Running `alert(ko.prefs.getString('gocodeDefaultLocation'))` or ``window.alert(ko.prefs.getString('gocodeDefaultLocation'))` raises an exception `NameError: global name 'ko' is not defined`, I probably need to import a module but I do not which.

**Comment by Naatan** [comment]
huh, where did you run that code I gave you? If you ran that from a macro it should definitely not give that error, unless your setup is seriously hosed.

**Comment by ervumlens** [comment]
@stef-k FYI, Naatan's code is a JavaScript macro.

**Comment by stef-k** [comment]
@ervumlens @Naatan  my bad i thought it was a python macro. Tomorrow i will run the given code and report the results.

thank you for your response

**Comment by stef-k** [comment]
Any update on this issue? 

If you need additional info please let me know because right now this is a show stopper for Go development.

**Comment by Naatan** [comment]
Sorry no updates, seems you may have found a bug in Komodo. I'm not sure what would cause it to not find the binary for you, as it works fine for me, but I'll run through the code again and scan for any potential issues.

Could you let me know if the problem persists after [starting Komodo with the default settings](http://beta.docs.komodoide.com/Troubleshooting/How-do-I-Start-Komodo-with-Default-Settings) and adjusting your golang prefs again?

**Comment by stef-k** [comment]
@Naatan I tried again using temporary profile as stated [here](http://beta.docs.komodoide.com/Troubleshooting/How-do-I-Start-Komodo-with-Default-Settings#how-do-i-start-komodo-with-default-settings_start-komodo-from-a-temporary-profile_linux), I've set GOPATH in Environment and the explicit paths for the go tool, gocode and godef without any luck.

Let me know if I can help with more info...

**Comment by SHeidemueller** [comment]
I am running into the same issue as @stef-k .
I have tried so many things. new clean installs, etc. Nothing worked yet.

Also I am running OS X Yosemite 10.10.4.

**Comment by Naatan** [comment]
Could you try installing 9.3 (pre-release), then from a new tab (File > New > New Tab) hit Troubleshooting (bottom right) > Reset File Preferences. Komodo will restart. Now see if you can still reproduce the issue.

You can download 9.3 here: http://komodoide.com/download/#preview

**Comment by SHeidemueller** [comment]
That worked for me. Thank you very much @Naatan 
The only issue now is that gocode autocompletion is not working, but that's a different cup of tea, I assume

**Comment by Naatan** [comment]
Yes it is, please open a new bug if you think it is an issue in Komodo. Thank you for checking :)
