### ISSUE TITLE
Komodo 9.2.0 keeps crashing for no apparent reason

### ISSUE THREAD

**Issue by henrycmjames** [Komodo/KomodoEdit#589]
Komodo Edit, version 9.2.0, build 15966, platform macosx.
Built on Tue Aug 4 17:31:22 2015.

The application keeps crashing during different processes, there doesn't appear to be a pattern.
Any thoughts about how to solve this would be greatly appreciated.
Thanks

**Comment by Naatan** [comment]
Anything useful in your error log (pystderr.log)? https://community.activestate.com/faq/komodo-profile-structure

Note this log is truncated whenever you start Komodo.

**Comment by henrycmjames** [comment]
Shall I send over the error log when the application next crashes?
All the best,
Henry

On 9 Sep 2015, at 16:20, Nathan Rijksen <notifications@github.com <mailto:notifications@github.com>> wrote:

Anything useful in your error log (pystderr.log)? https://community.activestate.com/faq/komodo-profile-structure <https://community.activestate.com/faq/komodo-profile-structure>
Note this log is truncated whenever you start Komodo.

**Comment by Naatan** [comment]
Yes please. Make sure you dont immediately restart Komodo, as said that would truncate the log.

**Comment by henrycmjames** [comment]
Nathan,
I will complete the crash report and then go to the directory you showed me, zip up the contents and send it to you, if that’s ok.
All the best,
Henry

On 9 Sep 2015, at 17:56, Nathan Rijksen <notifications@github.com <mailto:notifications@github.com>> wrote:

Yes please. Make sure you dont immediately restart Komodo, as said that would truncate the log.

**Comment by Naatan** [comment]
I only need the contents of pystderr.log, no zipping required. Just copy them in here.
