### ISSUE TITLE
TCL not collapsing correctly on some code

### ISSUE THREAD

**Issue by daw0975** [Komodo/KomodoEdit#590]
I am using komodo edit v9.2 and I'm getting some problems with the collapse
function. When I collapse the following section of TCL code, the remainder of the
page is hidden. I have had this problem on and off and it seems worse with this
newer version.

            if {[regexp -nocase -- "CRIT" $sysLEVEL]} {
                set sevLevel {!#!|#!#|!!!}
            } elseif {[regexp -nocase -- "WARN" $sysLEVEL]} {
                set sevLevel {!#!|#!#|!!!|\?#\?|#\?#|\?\?\?}
            } elseif {[regexp -nocase -- "INFO" $sysLEVEL]} {
                set sevLevel {!#!|#!#|!!!|\?#\?|#\?#|\?\?\?|###}
            } else {
                set sevLevel {!#!|#!#|!!!|\?#\?|#\?#|\?\?\?}
            }

**Comment by ervumlens** [comment]
Hi @daw0975 .  I'm not a TCLer, so I'm hoping to come up with some simplified cases for the problem you're seeing. Could you verify that the folding is correct / incorrect in the screenshots below?

```tcl
# Folds are correct.

{x} abc

set foo {2#}

set bar {!2#}
```

![screenshot - 09092015 - 12 56 37 pm](https://cloud.githubusercontent.com/assets/13005338/9769884/5d8d21a0-56f2-11e5-81dc-49890cf11c71.png)

```tcl
# Folds are incorrect.

{#} abc

set foo {#}

set bar {!#}
```
![screenshot - 09092015 - 12 57 00 pm](https://cloud.githubusercontent.com/assets/13005338/9769883/5d8ac39c-56f2-11e5-8e03-27b5bc716e8a.png)

**Comment by daw0975** [comment]
There are two aspect to this that I see as a bug.
1 is the else/elseif statements are showing a fold. I would think that the initial if should fold everything underneath it, and the else statements would not even have that.
2 is that once this folds that all other text from other procs are now hidden, and that is definitely where my biggest problem is.

[cid:image001.png@01D0EAFF.78E49230]
This sample code should demonstrate the problem:

#######################################
##
#package provide util 1.0

namespace eval util {
    proc test_1 {data_name file_name} {                                         ;# Test folding
        set sysLogFile "Test Data"
        if {[regexp -- "SYSLOG" $sysLogFile]} {
            if {[regexp -nocase -- "CRIT" $sysLEVEL]} {
                set sevLevel {!#!|#!#|!!!}
            } elseif {[regexp -nocase -- "WARN" $sysLEVEL]} {
                set sevLevel {!#!|#!#|!!!|\?#\?|#\?#|\?\?\?}
            } elseif {[regexp -nocase -- "INFO" $sysLEVEL]} {
                set sevLevel {!#!|#!#|!!!|\?#\?|#\?#|\?\?\?|###}
            } else {
                set sevLevel {!#!|#!#|!!!|\?#\?|#\?#|\?\?\?}
            }
        }
    }
    proc test_two {data_name file_name format_code col_size} {                  ;# Test  2
        #This is another test proc



    }

    proc test_three {data_name file_name} {                                     ;# AKA Test 3
        # Append to a file, if it doesn't exist the create the file
        global log_name
        puts $data_name
        set retur
    }
}

**Comment by Naatan** [comment]
@daw0975 would you mind responding via github.com? Github does a horrible job cleaning up email responses :\

**Comment by daw0975** [comment]
Reposting to GITHUB:

There are two aspect to this that I see as a bug.
1 is the else/elseif statements are showing a fold. I would think that the initial if should fold everything underneath it, and the else statements would not even have that.
2 is that once this folds that all other text from other procs are now hidden, and that is definitely where my biggest problem is.

 
![untitled](https://cloud.githubusercontent.com/assets/14202192/9791781/0fea385e-579a-11e5-81d5-a0c961aa9c6d.jpg)


This sample code should demonstrate the problem:

#######################################
##
#package provide util 1.0

namespace eval util {
    proc test_1 {data_name file_name} {                                         ;# Test folding
        set sysLogFile "Test Data"
        if {[regexp -- "SYSLOG" $sysLogFile]} {
            if {[regexp -nocase -- "CRIT" $sysLEVEL]} {
                set sevLevel {!#!|#!#|!!!}
            } elseif {[regexp -nocase -- "WARN" $sysLEVEL]} {
                set sevLevel {!#!|#!#|!!!|\?#\?|#\?#|\?\?\?}
            } elseif {[regexp -nocase -- "INFO" $sysLEVEL]} {
                set sevLevel {!#!|#!#|!!!|\?#\?|#\?#|\?\?\?|###}
            } else {
                set sevLevel {!#!|#!#|!!!|\?#\?|#\?#|\?\?\?}
            }
        }
    }
    proc test_two {data_name file_name format_code col_size} {                  ;# Test  2
        #This is another test proc
        
    

    }
    
    proc test_three {data_name file_name} {                                     ;# AKA Test 3
        # Append to a file, if it doesn't exist the create the file
        global log_name
        puts $data_name
        set retur
    }
}

**Comment by daw0975** [comment]
Done, thanks. First time using github.

-David
