### ISSUE TITLE
Komodo Edit icon under Gnome

### ISSUE THREAD

**Issue by xor** [Komodo/KomodoEdit#595]
I noticed two things with the Komodo Edit icon on Gnome.

-

First:
If I add this app to the favorites tab, and then opened the app, I will get two identical icons on the favorites tab, one for the favorite I added before, and another for the running app. Generally Gnome Shell knows to display just a single icon, but when the WMClass is different it sometimes doesn't. So I added the following line to the desktop file to change that.

StartupWMClass=Komodo

-

Second:
The icon I see on the Gnome dashboard is low resolution, 48px. I noticed you pack icons with the installer as large as 256px, so I changed another line on the desktop file to use that icon instead.

Icon=/home/xor/Komodo-Edit-9/share/icons/komodo256.png

**Comment by Naatan** [comment]
Thanks @xor, this is related to https://github.com/Komodo/KomodoEdit/issues/308, which I still need to find time to look into.
