### ISSUE TITLE
Komodo 9.2.0 falsely interprets ActivePerl's response and gives erroneous syntax-error

### ISSUE THREAD

**Issue by kayaalp** [Komodo/KomodoEdit#596]
I have three files:

 1. test.pl
 2. Level1/TestA.pm, and
 3. Level1/TestB.pm

test.pl is in the current directory and TestA.pm and TestB.pm are in directory Level1 under the current directory.

The program executes fine without any problem (no error, no warning). 

 - test.pl calls &alpha() located in TestA.pm and
 - &alpha() calls &beta() in TestB.pm. 

<pre>
%perl -w test.pl
Subroutine alpha is ON
Subroutine beta is ON
%
</pre>

So far, so good.

The problem I have is that something at the <code>use Level1::TestB</code> declaration in TestA.pm (see below) fools Komodo as if there were a syntax error.
![image](https://cloud.githubusercontent.com/assets/14223427/9798495/43a3a6e6-57cf-11e5-8b4d-05ee07ca12b2.png)

The error says:
"Can't locate Level1/TestB.pm in @INC (you may need to install Level1::TestB module) (@INC contains: . C:/Perl64/site/lib C:/Perl65/lib .).

This is not ActivePerl's problem since neither ActivePerl nor standard Perl has any problem running this code (as shown above).

Thanks.

PS. Below are additional info, which may be required to evaluate the issue

Info about the installed version of ActivePerl is below.<pre>
  Locally applied patches:
        ActivePerl Build 2000 [298557]
  Built under MSWin32
  Compiled at Oct 15 2014 14:56:57
  @INC:
    C:/Perl64/site/lib
    C:/Perl64/lib
    .
</pre>

test.pl:<pre>
use strict;
use warnings;
use Level1::TestA;
&alpha();</pre>

Level1/TestA.pm:<pre>
package Level1::TestA;
use strict;
use warnings;
use Exporter;

our @ISA = qw(Exporter);
our @EXPORT = qw(alpha);

use Level1::TestB;

sub alpha{
	print "Subroutine alpha is ON\n";
	&beta();
}
1;</pre>

Level1/TestB.pm:<pre>
package Level1::TestB;
use strict;
use warnings;
use Exporter;
our @ISA = qw(Exporter);
our @EXPORT = qw(beta);

sub beta{
	print "Subroutine beta is ON\n";
}
1;</pre>

**Comment by kayaalp** [comment]
Additional notes:
This issue is not specific to Windows version, but is there for the Linux version as well.
I also checked other versions of Komodo (9.1., 8.5, and even 7.1) on my Linux machine. The same error.

**Comment by Naatan** [comment]
Reproduced on Linux. @mitchell-as I think we may need to update our PDK dependency.

**Comment by mitchell-as** [comment]
Hi, you'll have to add the parent directory of "Level1" to your Perl include path (Project > Project Preferences and then Languages > Perl, and you'll find path settings under the "Additional Perl Import Directories" header).

Note that when syntax checking an individual Perl file, '.' in `@INC` means the directory of the current file. In your case, the syntax checker is looking for `Level1\Level1\TestB.pm`.
