### ISSUE TITLE
ko.browse.openUrlInDefaultBrowser opens browser behind Komodo

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#597]
Should open in foreground.

Priority because new feature depends on it.

**Comment by cgchoffman** [comment]
This looks to be working.  Reopen if it's not working how you thought.

**Comment by Naatan** [comment]
Still happens for me. Note I use chrome. Also I think it only happens when you already have the browser open (ie. it opens a tab).

**Comment by cgchoffman** [comment]
K i was using Firefox, browser was already open.  I put Komodo full screen ontop of the browser and firefox still pops on top...so there's that :dancer:

**Comment by Naatan** [comment]
Seems this only happens in Chrome, probably only on Linux and probably only on certain desktop environments. The issue is in chrome itself, not Komodo, as it also happens when opening url's from the terminal.
