### ISSUE TITLE
"Create Komodo Language" does not properly generate code-intel stub?

### ISSUE THREAD

**Issue by we3geeks** [Komodo/KomodoEdit#598]
Creating a new Komodo language via Komodo's "Project > New from Template > Create Komodo Language" does not seem to properly set up everything needed for code-intel to work cleanly. 

See https://bitbucket.org/we3geeks/komodo-moo

Build and install the skeleton extension generated by Komodo, then create a new file of the corresponding type and start typing stuff matching the handful of language keywords. This causes repeated "ImportError: No module named cile_moo" error notifications. 

pystderr.log has repeated entries like:
>[2015-09-10 22:17:28,253] [ERROR] codeintel.citadel: unexpected error scanning `Text-1.txt'
>Traceback (most recent call last):
>  File "/Applications/Komodo Edit 9.app/Contents/Resources/python/komodo/codeintel2/citadel.py", line 266, in scan
>    scan_tree = cile_driver.scan_purelang(self)
>  File "/Users/ron/Library/Application Support/KomodoEdit/9.2/XRE/extensions/komodo_moo_language@we3geeks.org/pylib/codeintel_moo.py", line 266, in scan_purelang
>    import cile_moo
>ImportError: No module named cile_moo

codeintel.log has repeated similar entries:
>ERROR:codeintel.citadel:unexpected error scanning `Text-1.txt'
>Traceback (most recent call last):
>  File "/Applications/Komodo Edit 9.app/Contents/Resources/python/komodo/codeintel2/citadel.py", line 266, in scan
>    scan_tree = cile_driver.scan_purelang(self)
>  File "/Users/ron/Library/Application Support/KomodoEdit/9.2/XRE/extensions/komodo_moo_language@we3geeks.org/pylib/codeintel_moo.py", line 266, in scan_purelang
>    import cile_moo
>ImportError: No module named cile_moo

**Comment by Naatan** [comment]
Priority because this is restricting Komodo's ability to be extended, which is a big part of it.

**Comment by mitchell-as** [comment]
This may be problematic now that codeintel is out of process. Extensions live in separate folders and codeintel's PYTHONPATH needs to be updated to include the Python component directories for all extensions such that the appropriate modules can be detected and loaded.

(This note is also a reminder for me when I get to this issue.)
