### ISSUE TITLE
Error on save before close

### ISSUE THREAD

**Issue by 6d6f6f** [Komodo/KomodoEdit#599]
When saving a file immediately before closing (`ctrl+s`, `ctrl+w`) I consistently get the error notification `2147500037 (list index out of range)`.

Komodo Edit, version 9.2.0, build 15966, platform linux-x86_64.

**Comment by cdcmicro** [comment]
FWIW, I don't reproduce this behavior with IDE 9.2.1 on Win7 x64.

**Comment by Naatan** [comment]
Could you update to 9.2.1, then reproduce and if it still happens share your error log? (Help > Troubleshooting > View Log File).

**Comment by 6d6f6f** [comment]
Reproduced with fresh install on a virtual machine.

Komodo Edit, version 9.2.1, build 15998, platform linux-x86_64.

> [2015-09-11 17:22:18,680] [INFO] Startup: Welcome to Komodo Edit 9.2.1 build 15998 (platform linux-x86_64, running on Linux 3.19.0-15-generic version #15-Ubuntu SMP Thu Apr 16 23:32:37 UTC 2015)
> [2015-09-11 17:22:18,680] [INFO] Startup: /usr/bin/python built on Wed Sep 2 00:18:45 2015
> [2015-09-11 17:22:18,979] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
> [2015-09-11 17:22:19,056] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
>     @chrome://komodo/content/komodo.js:48:1
> 
> [2015-09-11 17:22:19,696] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///home/yosh/Komodo-Edit-9/lib/mozilla/components/koamAddonManager.js:138
> [2015-09-11 17:22:19,917] [WARNING] koSkin: Detected GTK theme via libgtk: Greybird
> [2015-09-11 17:22:20,337] [WARNING] root: ko.findresults was already loaded, re-creating it.
> 
> [2015-09-11 17:22:20,688] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
> [2015-09-11 17:22:20,689] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
> [2015-09-11 17:22:20,690] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
> [2015-09-11 17:22:20,690] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
> [2015-09-11 17:22:20,690] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
> [2015-09-11 17:22:20,690] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
> [2015-09-11 17:22:20,690] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
> [2015-09-11 17:22:20,691] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
> [2015-09-11 17:22:22,270] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
> [2015-09-11 17:22:22,683] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
> [2015-09-11 17:22:22,684] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
> [2015-09-11 17:22:22,685] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
> [2015-09-11 17:22:22,685] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
> [2015-09-11 17:22:22,685] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
> [2015-09-11 17:22:22,685] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
> [2015-09-11 17:22:22,685] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
> [2015-09-11 17:22:22,686] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
> [2015-09-11 17:22:37,669] [WARNING] koDocument: setting `koDocument.codePage` is DEPRECATED, hardwired to 65001 (unicode mode): 65001 ignored
> [2015-09-11 17:22:38,170] [ERROR] koChangeTracker: notifyChanges:: exception
> Traceback (most recent call last):
>   File "/home/yosh/Komodo-Edit-9/lib/mozilla/extensions/trackchanges@activestate.com/components/koChangeTracker.py", line 118, in notifyChanges
>     lineCount = self.koDoc.getView().scimoz.lineCount
>   File "/home/yosh/Komodo-Edit-9/lib/mozilla/components/koDocument.py", line 1839, in getView
>     raise ServerException(nsError.NS_ERROR_FAILURE, str(ex))
> ServerException: 2147500037 (list index out of range)
> [2015-09-11 17:22:38,175] [WARNING] root: ko.statusbar.AddMessage is deprecated, please use require("notify/notify").send() instead
>     _addMessage@chrome://komodo/content/statusbar.js:468:1
>     this.AddMessage@chrome://komodo/content/statusbar.js:516:5
>     exports.ChangeTracker.prototype.onError@chrome://trackchanges/content/tracker.js:200:5
>     exports.ChangeTracker.prototype.update@chrome://trackchanges/content/tracker.js:157:9
>     notify@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/timers.js:40:9
> 
> [2015-09-11 17:22:45,441] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
> [2015-09-11 17:22:45,442] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
> [2015-09-11 17:22:45,443] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
> [2015-09-11 17:22:45,443] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
> [2015-09-11 17:22:45,443] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
> [2015-09-11 17:22:45,443] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
> [2015-09-11 17:22:45,443] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
> [2015-09-11 17:22:45,444] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'

**Comment by Naatan** [comment]
Can you confirm that log is from after reproducing the error, and without restarting Komodo? (Komodo truncates the log whenever it starts).

**Comment by 6d6f6f** [comment]
Yes, this was copied from the log immediately after the error occurred. My way of reproducing (on a fresh install on a Xubuntu virtual machine).

1. Start Komodo Edit.
2. Create new file.
3. Save file as something.
4. Type something (optional).
5. Save again and immediately close file (`ctrl+s`, `ctrl+w`).
6. Observe error notification.
7. View log.

**Comment by 6d6f6f** [comment]
After looking through the log I figured the following line was the culprit.

> [2015-09-11 17:22:38,170] [ERROR] koChangeTracker: notifyChanges:: exception
Traceback (most recent call last):
File "/home/yosh/Komodo-Edit-9/lib/mozilla/extensions/trackchanges@activestate.com/components/koChangeTracker.py", line 118, in notifyChanges
lineCount = self.koDoc.getView().scimoz.lineCount
File "/home/yosh/Komodo-Edit-9/lib/mozilla/components/koDocument.py", line 1839, in getView
raise ServerException(nsError.NS_ERROR_FAILURE, str(ex))
ServerException: 2147500037 (list index out of range)

Disabling the 'Track Changes' extension fixes the problem, but obviously changed lines are now no longer highlighted.

**Comment by Naatan** [comment]
Thanks for following up on that. Just so I have this right; the problem is caused by track changes but does not occur unless you immediately close after saving, correct?

**Comment by 6d6f6f** [comment]
That is correct, the error only occurs when closing a file immediately after saving it.

**Comment by cgchoffman** [comment]
Was anyone else able to reproduce this?

**Comment by 6d6f6f** [comment]
This has been fixed in 9.3, you can close the issue.

**Comment by Defman21** [comment]
You can do it as well :)
