### ISSUE TITLE
Do not open/close a folder by right click with Expand on click enabled

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#60]
I don't want to open or close a folder in Places if I click right mouse button on it. It should save the state.

**Comment by cgchoffman** [comment]
Platform?  Not seeing this on Windows.  You should get a context menu.

**Comment by Defman21** [comment]
Linux. I get a context menu but also I close or open the folder by right click.

**Comment by Naatan** [comment]
Reproduced on Linux.

@cgchoffman make sure you enable the "Click to Expand" setting under the Places cog menu
