### ISSUE TITLE
Authenticode signing for Windows installers

### ISSUE THREAD

**Issue by cdcmicro** [Komodo/KomodoEdit#600]
I would like to see the Komodo IDE installer downloads (Windows executables) signed with an Authenticode digital signature.

IMO, it's hard for a commercial entity like AS to defend delivering an un-signed installer - especially after I've paid a hundred dollars or more for the product and each of its major upgrades.

**Comment by cdcmicro** [comment]
Obviously, I don't know anything about AS's build environment.  But it's not impossible to to include code-signing the Windows exe files in a non-Windows (cross-compiled) environment.

**Comment by Naatan** [comment]
The main reason this hasn't happened yet is because of the technical implications, Komodo is not a windows-only app so we have more considerations to make. Obviously the price of the actual certificate is not a barrier.

We'll try to get this in for 9.3 if it doesn't significantly derail our planning. Thanks for bringing this to our attention again.

**Comment by cdcmicro** [comment]
OK, cool.  Thanks.

**Comment by cdcmicro** [comment]
Does Apple have code-signing guidelines?  Or is it just built-into developing Mac apps?

**Comment by Naatan** [comment]
I wasn't involved with that implementation in Komodo. It might be built-in but that's definitely not the only option as Komodo wasn't built with any Apple technologies aside from the dependencies Mozilla has on things like their SDK.

**Comment by mitchell-as** [comment]
Note to self: http://manpages.ubuntu.com/manpages/trusty/en/man1/signcode.1.html and https://msdn.microsoft.com/en-us/library/aa387764.aspx

**Comment by cdcmicro** [comment]
FYI, before you can sign, there's a conversion step or two required in order to get the PEM (DigiCert refers to them as "Apache") format code-signing cert, any intermediate certs, and the private key you get from the CA (Comodo, DigiCert, GoDaddy, etc.) into the .pvk and .spc formats mono signcode expects.

I just renewed my company's certificate, so it's reasonably fresh in my mind, and newly-documented in Evernote.  I use it in a scripted packaging process to build some web deliverable exe packages.

I retrieved mine in Authenticode (.p12) format and used Windows' certmgr to export to PEM.  I'm guessing you'll just start with the PEM format, so...

The CA should provide a PEM format private key (perhaps `privatekey.key`), its associated certificate (perhaps `komodo.crt`), and possibly an intermediate cert (perhaps `intermediate.crt`).

To convert the private key to PVK format, run:

>openssl rsa -in privatekey.key -outform PVK -pvk-strong -out privatekey.pvk

You'll be prompted to enter a password for the PVK private key.  It seems to accept an empty one if that's how you roll.

Then, to convert the certs to .spc format

>cert2spc komodo.crt intermediate.crt komodo_codesign.spc

The pvk/spc file pair is ready for use with mono codesign.  Perhaps:

>signcode -quiet -a sha1 -spc komodo_codesign.spc -v privatekey.pvk -t "http://timestamp.digicert.com" -i "http://komodoide.com" -n "Komodo IDE v9.3" komodoide_package.exe

Then:

>chktrust komodoide_package.exe

Chktrust may fail if your cert store doesn't include all of the intermediate certs and the CA cert.

You can check it from Windows by right-clicking the signed exe file, choose Properties and examining the "Digital Signatures" sheet.

**Comment by mitchell-as** [comment]
You are amazing. Thanks for your advice!

**Comment by cdcmicro** [comment]
Nothing amazing here, just many hours of trial and (mostly) error repeated every three years.

**Comment by Naatan** [comment]
Abort, abort! 

Sigh, no sadly we'll have to deal with this. Hopefully we can get it in for 9.3.1, those warnings Windows puts up get more invasive each version. Thanks for the advice @cdcmicro !

**Comment by Naatan** [comment]
@mitchell-as I think we can close this?

**Comment by Naatan** [comment]
As of 9.3.1 Komodo will be using a self-signed certificate thanks to @mitchell-as and @cgchoffman's hard work.

Re-targeted this for 10.0 to get a proper certificate.

**Comment by mitchell-as** [comment]
Our next release (10.1.2) should be using a recognized certificate.
