### ISSUE TITLE
problem with utf-8 characters , farsi

### ISSUE THREAD

**Issue by hassanzanjani1374** [Komodo/KomodoEdit#604]
<img width="1072" alt="screen shot 2015-09-12 at 22 07 27" src="https://cloud.githubusercontent.com/assets/4802463/9832899/bcd64736-599a-11e5-843c-a59b74bc622a.png">

hi
in farsi text , i have 2 problems with showing characters:
1 . wrong direction on cursor movement
2. show under other characters

**Comment by mitchell-as** [comment]
Hi, will you please copy paste a minimal example that demonstrate the problem? I cannot type Farsi and need to copy-paste to reproduce, test, etc. Thanks!

**Comment by hassanzanjani1374** [comment]
thanks for your respond

لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد. در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها و شرایط سخت تایپ به پایان رسد وزمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.

you can use this for more example
http://loremipsum.ir/

good luck :)

**Comment by Naatan** [comment]
I think @mitchell-as was asking for a full example, so for example the HTML in your screenshot there, but in a textual format.

**Comment by hassanzanjani1374** [comment]
if you copy this in komodo see picture:

                <div class="text">
                    <br>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد .
                    <br>تا با نرم افزارها شناخت بیستری را برای طراحان رایانه ای و فرهنگ پیشرو در زبان فارسی ایجاد کرد. در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها و شرایط سخت تایپ به پایان رسد وزمان مورد نیاز شامل حروفچینی دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.
                    <div class="items">
                        <img src="data/about-item.jpg" alt="item">
                        <img src="data/about-item.jpg" alt="item">
                        <img src="data/about-item.jpg" alt="item">
                        <img src="data/about-item.jpg" alt="item">
                        <img src="data/about-item.jpg" alt="item">
                    </div>
              </div>

<img width="677" alt="screen shot 2015-09-14 at 23 03 18" src="https://cloud.githubusercontent.com/assets/4802463/9858243/d8d837a0-5b34-11e5-88c2-6ba3e59e6ac2.png">

**Comment by Defman21** [comment]
Just saying: not able to reproduce the text overlaying issue on Linux using Source Code Pro as the font:
![Pic](http://i.imgur.com/1mH8Nlp.png)
Cannot say something about the cursor behavior, it's hard to me to select RTL-text in any editor/text/page (but when I'm using my cursor keys, the cursor is moving very slowly and randomly jumps through the Farsi text, not sure this is a right behavior for RTL-texts)

**Comment by mitchell-as** [comment]
Hi, when I copy-paste, it appears the word order is backwards. Are you using RTL input? Scintilla, our editing component, has been known to not work well with RTL languages. I would venture a guess that that is the problem.

**Comment by hassanzanjani1374** [comment]
yes im useing rtl input
thanks mitchell :)
