### ISSUE TITLE
tcl syntax checker: global arrays shows as undefined variables (2)

### ISSUE THREAD

**Issue by oehhar** [Komodo/KomodoEdit#605]
The following code snipped shows an "undefined variable error" for $g(1) for me.
This is a new issue in kommodo 9.0 for me and IMHO quite annoying...

    set g(1) 1
    proc a {} {
        global g
        puts $g(1)
    }

Language: TCL
Kommodo 9.0.1 to 9.2.1
Windows 8.1 GER 64 bit

Maybee it is just me and my installation is wrong and it is fixed. At least, for me, this is not the case, sorry.

This is a remider for the ticket with the same name which is in state "internally pending".
As usual, GitHub is outputting errors like "something went wrong, try again" when editied.
Of cause, trying again does not help, this does not fix github...
So please appologize to send a new ticket, it is due to issues in github...

**Comment by Naatan** [comment]
Hope github corrects itself soon for you. Will close this and leave a reference to #274.
