### ISSUE TITLE
Komodo IDE 9.2: Break point on blank line never gets executed

### ISSUE THREAD

**Issue by clokep** [Komodo/KomodoEdit#606]
Adding a break point to a blank line never gets called, execution just blows past it.

Obviously it doesn't make much sense to have a break point on a blank line (there's nothing to break *on*). When I was frequently using MATLAB, it handled this by having a break point 'fall' until it hit an executable line. This was reflected in the UI, but need not be. I.e. breaking whenever you pass a breakpoint might be good enough.

Please let me know if this isn't clear and I'll give an example!

**Comment by mitchell-as** [comment]
Hi, we often interface with the debuggers provided by the language authors, and they are the ones that dictate breakpoint policy. In theory we could test to see whether a breakpoint is being added to a blank line and, if so, shift it down to a non-blank line, but that would involve some unnecessary complexity and introduce potential bugs, as we do not have the level of knowledge about source code that the actual debugger would.

**Comment by clokep** [comment]
For a bit more context, the conversation @Naatan and I had over IRC:

> 3:51:30 PM * clokep_work just found an annoying bug. :(
3:51:39 PM - Defman: ?
3:52:02 PM - clokep_work: Adding a break point on a blank line never gets called.
3:52:26 PM - Defman: *file a bug for it
3:52:31 PM - clokep_work: Of course.
3:52:34 PM - clokep_work: I'm in the middle of that.
3:54:31 PM - Defman: Cool :)
3:54:40 PM - clokep_work: https://github.com/Komodo/KomodoEdit/issues/606
3:55:25 PM - Defman: thanks :)
3:59:34 PM - clokep_work: Yep yep.
4:08:21 PM - nathanr: clokep_work: because the interpreter doesnt handle empty lines, we should probably just refuse to place those breakpoints or something
4:08:37 PM - clokep_work: nathanr: Yeah I figured that was the technical reason.
4:08:45 PM - clokep_work: But as a user I don't care about the reason! ;)
4:08:50 PM - clokep_work: (I'm kidding, mostly.)
4:09:08 PM - clokep_work: Of course then you have to get into 'what is a blank line'.
4:13:25 PM - nathanr: clokep_work: yeah of course :) just explaining why it happens
4:13:31 PM - clokep_work: Yep, thanks.
4:13:40 PM - clokep_work: nathanr: Do you offload all breakpoint stuff to the interpreter I assume?
4:13:51 PM - clokep_work: So maybe I need to file a Python bug. :P
4:14:16 PM - nathanr: clokep_work: not 100% sure (not my area of expertise), but I believe the interpreter/debugger just tells us what line its on and we then tell it whether to wait or continue
4:14:30 PM - nathanr: so the interpreter/debugger itself likely isnt aware of breakpoints
4:14:35 PM - clokep_work: Interesting.
4:14:39 PM - nathanr: that may differ per debugger though, and I am assuming a lot here
4:14:41 PM - clokep_work: I wonder where that logic is.
4:15:00 PM - nathanr: I'd honestly have to dig myself, but it should be fairly well modularized
4:15:30 PM - nathanr: not that that would make it easier, abstraction can be worse than spaghetti code sometimes

I'd be curious how the interface with the debugger works. Do you tell it all the breakpoints ahead of time?

**Comment by Naatan** [comment]
>  In theory we could test to see whether a breakpoint is being added to a blank line and, if so, shift it down to a non-blank line, but that would involve some unnecessary complexity and introduce potential bugs, as we do not have the level of knowledge about source code that the actual debugger would.

Right, so perhaps a good compromise is to simply refuse placing breakpoints on lines that we "know" won't work (eg. empty lines). We could show a warning notification explaining why the breakpoint didn't take.
