### ISSUE TITLE
Click on a +/- sign before the folder name duplicate contents of the folder

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#61]
This happens if you enable `Expand on click`. I think it's better to hide these +/- buttons if `Expand on click` is enabled.

**Comment by cgchoffman** [comment]
Ca you provide a screenshot for clarity?

**Comment by Defman21** [comment]
https://youtu.be/hD4ecygPZDw

**Comment by cgchoffman** [comment]
Ahhh gotcha.  On Windows it's arrows, not +/-.  Reproduce.  Thanks Defman
