### ISSUE TITLE
Column Select + Transpose line does not actually transpose text

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#610]
- Column select anything
- `alt + [up|down]` (cmd_lineTranspose[Down|up])

Expect:  Select to be transposed in that direction with the appropriate, matching column above or below
Actual: Selection jumps down and a bunch of bits get dumped in a line below moved selection.

**Comment by mitchell-as** [comment]
This looks dangerous, like we're accessing some memory we shouldn't be if random bits are being dumped. Elevating priority.

**Comment by mitchell-as** [comment]
Fixed the weird bit dumping, but re-filing as an enhancement request, as we do not support moving columns of text.

https://github.com/Komodo/KomodoEdit/commit/3d4102dad67d5e96523d8d718b4bc987060a024e

**Comment by cgchoffman** [comment]
Dont support  it through keybindings or at all?  I assume you mean the former.

**Comment by Naatan** [comment]
Is there any merit in supporting transpose of column selection? Seems to me the proper fix here is to stop it from happening in block/multi select mode, which is what @mitchell-as did. Just because I can't think of a use-case doesn't mean there isn't one though.

**Comment by cgchoffman** [comment]
Unless it's an easy drop that scintilla already supports I don't see tons of merit, no.  I'm fine with it just not being allowed to occur.

**Comment by mitchell-as** [comment]
Scintilla does not support it natively and this is not trivial to implement. Naatan is right; that's why I chose to prevent it from happening.

**Comment by Naatan** [comment]
Ok, let's close this then. I think the current solution is sufficient.
