### ISSUE TITLE
[Errno 13] Permesso negato: u'/home/zeb-demon/.komodoedit/9.2/codeintel.log'

### ISSUE THREAD

**Issue by ZEB-DEMON** [Komodo/KomodoEdit#612]
At launch i've this error:

[Errno 13] Permesso negato: u'/home/zeb-demon/.komodoedit/9.2/codeintel.log'

Komodo Edit, version 9.2.0, build 15966.
Built on Tue Aug 4 17:31:26 2015.

**Comment by Defman21** [comment]
```bash
sudo chown $USER:$USER /home/zeb-demon/.komodoedit/ -R
```

**Comment by Naatan** [comment]
@Defman21 is correct, though he's not helping you understand what went wrong in the first place. I assume you ran Komodo with sudo, try not to do this as it will end up with conflicting permissions.

**Comment by Defman21** [comment]
Yeah, I wasn't very informative when I was writing my message :stuck_out_tongue:
