### ISSUE TITLE
Transpose:  extend/change  cmd_lineTranspose[Up | Down] to transpose current selection

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#613]
- Select any portion of a string
- Press `alt + [up | down]

Want: that selection to be transposed with the string above/below
Have: The entire line is selected and transposed with the line above/below

**Comment by mitchell-as** [comment]
This will not be trivial, particularly if the line above or below is shorter than the current line to the extent that there are no characters that exist above or below to transpose with. This seems like a very niche feature with few use cases.

I think a userscript would be better suited for this. Make a rectangular/block selection that encompasses the text on adjacent lines to transpose, and then have your userscript perform the transposition.

What do you think?

**Comment by cgchoffman** [comment]
It is a very narrow use case when this would actually be handy.  The two strings would need to line up perfectly but different to necessitate a transpose.  I believe I opened this because I thought that's how one of the transpose commands was supposed to work.  I'm fine with just closing this.  I don't want to write that userscript.
