### ISSUE TITLE
command listed twice in key binding preferences: "Show/Hide All Toolbars"

### ISSUE THREAD

**Issue by ervumlens** [Komodo/KomodoEdit#615]
In the Key Bindings preference page, the command "Show/Hide All Toolbars" appears twice. 

![screenshot_2015-09-20_12-24-27](https://cloud.githubusercontent.com/assets/13005338/9982009/010bc6da-5f93-11e5-8125-589b8a84cb35.png)

According to [Komodo.dtd](https://github.com/Komodo/KomodoEdit/blob/258a3bfe3e6fe68dabfa36e691795f9b54d49b75/src/chrome/komodo/locale/en-US/komodo.dtd#L746-L747), one of these commands affects the menubar rather than the toolbar:

```
<!ENTITY userInterfaceShowHideMenubar.desc "User Interface: Show/Hide All Toolbars">
<!ENTITY userInterfaceShowHideToolbars.desc "User Interface: Show/Hide All Toolbars">
```

**Comment by Naatan** [comment]
Nice catch.
