### ISSUE TITLE
Color picker no longer works in 9.3 (master)

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#618]
Due to the new ctrl+click multi caret behaviour. I think we need some prefs around this, eg.:
```
Control Clicking 
  * Control clicking behavior:
    * [radiobox] Go to definition
    * [radiobox] Place multi caret
  * [checkbox] Open color picker when clicking on colors
```

Note the color picker option works in both scenario's but only for multi-caret would it override the default behaviour. This will need some pref reworking.

Shame we can't use the ALT key, that would make this a lot easier..

**Comment by Defman21** [comment]
What do you think about <kbd>Ctrl+Right Click</kbd> or <kbd>Ctrl+Mouse Wheel Click</kbd>?

**Comment by mitchell-as** [comment]
Multi-caret mouse placement only works for Ctrl modifier. This is hardcoded into Scintilla and I'd prefer not to patch it.

**Comment by Defman21** [comment]
Nah, I didn't mean you should change the multi-caret modifier, but Color Picker modifier :)

**Comment by Defman21** [comment]
What about the "Go to definition" behavior? It works in the same way as Color Picker. (Holding Ctrl and pressing on an element in the code).

**Comment by Naatan** [comment]
@mitchell-as unfortunately we will have to. The color picker functionality is an important functionality that people will run into. Are you hesitant to patch because you don't like patching or because it would take a lot of work?

We really need to find a way to make this work, the lack of go to definition ctrl+click support (even with a pref) is one thing, but color picker support is a big feature in that I think it is widely used.

@Defman21 That is exactly what this ticket is seeking to address.

**Comment by mitchell-as** [comment]
@Naatan both.

Before I go into specifics, why can't we check if a color is under the caret during Ctrl+Click and then eat the click (not pass to Scintilla)? This way you won't be able to set multiple selections within colors, but it's a small price to pay vs. below.

Arguments against patching:

1. Patching should be a last resort.
2. Ctrl+Click is integrated in Scintilla in such a way that we cannot just redefine a modifier key in a '#define' directive. It will be an ugly, error prone patch that will be difficult to maintain between Scintilla releases.
3. We will have to create our own preferences in Scintilla and juggle any platform differences.
4. It's not even clear if we can have one modifier for multiple selections, since Alt+Click is eaten in Linux, and Super/Win+Click probably won't work on OSX. (I wouldn't be surprised why Scintilla hardcoded Ctrl+Click; it's the only sane option.)

**Comment by Naatan** [comment]
That sounds fine to me (eating the click), couldn't we do the same for goto def? Ie. if someone has chosen to use the goto def functionality instead of multi caret, then we eat the ctrl+click by default?

**Comment by mitchell-as** [comment]
That sounds reasonable.

**Comment by Naatan** [comment]
Reopened as the fix @mitchell-as committed just enabled hyperlinks again, which was not the intend of this ticket. The intend was to give more flexibility about how this works through preferences. See my first post in this ticket.

**Comment by mitchell-as** [comment]
I added clarification to the preferences page under hyperlinking. Due to our hyperlinking implementation, we cannot implement the preferences as stated in the original post.

**Comment by mitchell-as** [comment]
![hyperlink](https://cloud.githubusercontent.com/assets/12902397/11306906/c654e236-8f82-11e5-99ca-69346315e06e.png)

**Comment by mitchell-as** [comment]
By toggling combinations of the preferences in the image above, the desired behavior from the original set of suggested preferences can be obtained.

**Comment by Naatan** [comment]
Perfect, nice work! :)

**Comment by Defman21** [comment]
Did you guys put this also in IDE? I don't see these preferences in the latest version of Komodo.
![pic](http://i.imgur.com/HKTosGK.png)

**Comment by Naatan** [comment]
This will be in Komodo 10 (see the milestone).

**Comment by Defman21** [comment]
Have you reverted this commit? https://github.com/Komodo/KomodoEdit/commit/c439871acae51a046837aa7dc38df200e12ded8b

**Comment by mitchell-as** [comment]
No, I see the options in my development version of Komodo.

**Comment by Defman21** [comment]
I don't have a development version of the IDE. Only Edit :)

**Comment by mitchell-as** [comment]
My development version of Edit also has these options and color picking works.

**Comment by Defman21** [comment]
My as well, I don't see these preferences in Komodo IDE, version 9.3.2, build 88191, platform linux-x86_64.
Built on Thu Dec 10 13:00:48 2015.

**Comment by mitchell-as** [comment]
Well, as Nathan said, this will be in Komodo 10.

**Comment by Defman21** [comment]
Okay :)
I was confused a bit why it's closed but I don't see the fix in the latest stable build.

**Comment by Naatan** [comment]
We close issues when they are fixed on master. Whether they are fixed in the latest stable build has nothing to do with the resolved status of an issue.

**Comment by Defman21** [comment]
Thanks for clarification Nathan!
