### ISSUE TITLE
DPI_Scale is ignored

### ISSUE THREAD

**Issue by andypillip** [Komodo/KomodoEdit#619]
For productive work with HiDPI screens it's necessary to scale UIs.

Komodo 9 ignores the GDK scaling setting – probably because it's not a GDK app?

    env GDK_SCALE=1.3 GDK_DPI_SCALE=1.3 CLUTTER_SCALE=1.3 /opt/Komodo-Edit/bin/komodo 

Is there another way to scale the UI?

Thx a bunch

**Comment by cgchoffman** [comment]
This is tracked in issue #162.
