### ISSUE TITLE
Macro API: scimoz.setSel cut instead select.

### ISSUE THREAD

**Issue by krychu90** [Komodo/KomodoEdit#62]
Hi everyone,
I want to create some snippet but in macro API scimoz.setSel method cuts text instead of selecting.
Komodo Edit 9.

Regards.

**Comment by Naatan** [comment]
Use the new SDK :)

```
require('ko/editor').getSelection()
require('ko/editor').setSelection({line: 1, ch: 0},{line: 5, ch: 0})
```

More details: https://github.com/Komodo/KomodoEdit/blob/master/src/chrome/komodo/content/sdk/editor.js

Documentation to follow.

Btw please use the forums for general questions - http://forum.komodoide.com/

Bug tracker is for bugs and enhancement requests :) Thank you!

**Comment by krychu90** [comment]
Thanks for answer but code below should select new selection, but it does not. It place anchor at the beginning of the file.
```
var selection = require('ko/editor').getSelection();
require('ko/editor').replaceSelection(selection+selection, 'around');
```

**Comment by Naatan** [comment]
setSelection() does not delete any code for me, are you sure you're not doing anything else? If no, can you supply a snippet on which this type of behaviour occurs?

"getSelection" returns the actual selected text. Please refer to the file I linked above to see what these methods do.

I'm not sure what it is you're trying to do, but I think you want replaceSelection() and getSelectionRange().

This is not really a topic for the bug tracker though, please consider creating a thread on our forums for any further usage questions - http://forum.komodoide.com/

**Comment by krychu90** [comment]
Snippet with this code only delete first 5 lines.
```
<%
require('ko/editor').setSelection({line: 1, ch: 0},{line: 5, ch: 0})
%>
```

I want to create a snippet "Duplicate line/selection" because "Duplicate Line/Selection Down/Up" in Komodo Edit 9 is not the same as in 8.5 (don't duplicate selection).

**Comment by Naatan** [comment]
I'm happy to help you further with this but please take it to the forums, this is not a topic for the bug tracker :)

**Comment by Naatan** [comment]
Created issue for duplicating selection not working: https://github.com/Komodo/KomodoEdit/issues/84
