### ISSUE TITLE
Debugging configuration gets lost when errors occur during debugging

### ISSUE THREAD

**Issue by gpetrowitsch** [Komodo/KomodoEdit#620]
I'm using ActivePerl 5.16. When debugging my program in Komodo (I'm running 8.5) and a runtime error occurs, it is very likely that my debugging configuration is gone afterwards.
To work around this I've duplicated my Kommodo project file. In case of the error I close my current project and reopen it from the duplicated project file (because the original one is often overwritten - with the settings lost). This works but is very annoying and time-consuming...

**Comment by cgchoffman** [comment]
Could you clarify the reproduction steps?  Please be as precise as possible.  The workaround is helpful, thanks for that.  Are you able to reproduce this in Komodo 9.2?

**Comment by gpetrowitsch** [comment]
Thanks for responding. I could just reproduce the problem like this:
1. Start Kommodo with my project and check settings (see attached image step1.png)
2. Debug my program by pressing F5 while the main Perl file is active in the editor -> no problems
3. Debug my program by pressing F5 while the editor shows some other module file. As soon as an error occurs in the program (e.g. trying to call a method on an undefined object), which is not unlikely but it is caught by an eval, the configuration is gone, after I stopped the program. (see attached image result.png).

![result](https://cloud.githubusercontent.com/assets/14781010/10039857/680258e6-61d6-11e5-8a65-db1526948746.png)
![step1](https://cloud.githubusercontent.com/assets/14781010/10039856/680236ea-61d6-11e5-80e2-6f98e08d936b.png)

**Comment by gpetrowitsch** [comment]
I would like to upload my original and my destroyed project files, but somehow it doesn't work...

**Comment by gpetrowitsch** [comment]
OK: This is my original project file contents:
<?xml version="1.0" encoding="UTF-8"?>

<project id="3fc158f2-f235-43f6-937a-af11368197d1" kpf_version="5" name="VeraCG.kpf.komodoproject">
<preference-set idref="3fc158f2-f235-43f6-937a-af11368197d1" id="project" preftype="project">
  <string id="currentInvocationLanguage">Perl</string>
  <string id="import_dirname">C:\scripts\git.VeraCG</string>
  <string id="language">Perl</string>
  <string id="lastInvocation">bridge</string>
  <string id="perlExtraPaths">C:\scripts\git.VeraCG\Perl-Lib</string>
<preference-set id="Invocations">
<preference-set id="bridge">
  <string id="cookieparams"></string>
  <string id="cwd">C:\scripts\git.VeraCG</string>
  <string id="documentRoot"></string>
  <string id="executable-params"></string>
  <string id="filename">C:\scripts\git.VeraCG\veracg.pl</string>
  <string id="getparams"></string>
  <string id="language">Perl</string>
  <string id="mpostparams"></string>
  <string id="params">work\TestSuite\veracg.bridge.cfg</string>
  <string id="postparams"></string>
  <string id="posttype">application/x-www-form-urlencoded</string>
  <string id="request-method">GET</string>
  <boolean id="show-dialog">1</boolean>
  <boolean id="sim-cgi">0</boolean>
  <boolean id="use-console">0</boolean>
  <string id="userCGIEnvironment"></string>
  <string id="userEnvironment"></string>
</preference-set>
<preference-set id="run">
  <string id="cookieparams"></string>
  <string relative="path" id="cwd"></string>
  <string id="documentRoot"></string>
  <string id="executable-params"></string>
  <string id="filename"></string>
  <string id="getparams"></string>
  <string id="language">Perl</string>
  <string id="mpostparams"></string>
  <string id="params"></string>
  <string id="postparams"></string>
  <string id="posttype">application/x-www-form-urlencoded</string>
  <string id="request-method">GET</string>
  <boolean id="show-dialog">1</boolean>
  <boolean id="sim-cgi">0</boolean>
  <boolean id="use-console">0</boolean>
  <string id="userCGIEnvironment"></string>
  <string id="userEnvironment"></string>
</preference-set>
<preference-set id="usb">
  <string id="cookieparams"></string>
  <string id="cwd">C:\scripts\git.VeraCG</string>
  <long id="debugger.io-port">9011</long>
  <string id="documentRoot"></string>
  <string id="executable-params"></string>
  <string id="filename">C:\scripts\git.VeraCG\veracg.pl</string>
  <string id="getparams"></string>
  <string id="language">Perl</string>
  <string id="mpostparams"></string>
  <string id="params">veracg.gen2.cfg</string>
  <string id="postparams"></string>
  <string id="posttype">application/x-www-form-urlencoded</string>
  <string id="request-method">GET</string>
  <boolean id="show-dialog">1</boolean>
  <boolean id="sim-cgi">0</boolean>
  <boolean id="use-console">0</boolean>
  <string id="userCGIEnvironment"></string>
  <string id="userEnvironment"></string>
  <string id="warnings">enabled</string>
</preference-set>
</preference-set>
</preference-set>
</project>

**Comment by gpetrowitsch** [comment]
And this it, what it looks like, when the problem occurred.
```
<?xml version="1.0" encoding="UTF-8"?>
<!-- Komodo Project File - DO NOT EDIT -->
<project id="3fc158f2-f235-43f6-937a-af11368197d1" kpf_version="5" name="VeraCG.kpf.komodoproject">
<preference-set idref="3fc158f2-f235-43f6-937a-af11368197d1" id="project" preftype="project">
  <string id="currentInvocationLanguage">Perl</string>
  <string id="import_dirname">C:\scripts\git.VeraCG</string>
  <string id="language">Perl</string>
  <string id="lastInvocation">bridge</string>
  <string id="perlExtraPaths">C:\scripts\git.VeraCG\Perl-Lib</string>
</preference-set>
</project>
```

**Comment by Naatan** [comment]
I'm sorry we cannot provide support for older versions of Komodo, any fix would land in a newer version. Could you please try the 9.2 trial and see if you can reproduce your issue still?

**Comment by gpetrowitsch** [comment]
That's really a pity, because it forces me to buy the upgrade :-(
I tried 9.2 with the same sequence and it seems to work fine. I'll continue trying and let you know, should it fail...

**Comment by Naatan** [comment]
I am sorry about that, but we cannot support our older versions forever. If there are major breaking bugs we would of course fix them in those versions but other than that all fixes are going into the latest version.

**Comment by tonyattwood** [comment]
Hello,

Here is an article that I found by chance, but it  turned out so interesting that I decided  to share it with you, you can  find it here <http://explore.geneticjunk.com/e4vjeuy>

Best, tony.attwood@ntlworld.com

**Comment by gpetrowitsch** [comment]
thanks!

Gruß,
Gerhard

**Comment by Defman21** [comment]
@gpetrowitsch he's a spammer.

**Comment by gpetrowitsch** [comment]
thanks; fortunately our company network blocked the access; normally I'm not that blue-eyed, but he caught me…

Gruß,
Gerhard
