### ISSUE TITLE
Incremental Search throws errors on "[" or "{"

### ISSUE THREAD

**Issue by furnox** [Komodo/KomodoEdit#621]
Issue:
Using Incremental Search to search for the characters "[" or "(" turns the input field red and does not highlight any found characters despite there being several instances of those characters.

How to Reproduce:
1. `Ctrl-F` to open Incremental Search. Type "[" or "(". Input field turns red.
2. Then activate main text area and hit `Ctrl-F` again so it has the last searched text in the input field. Input field turns red.

Details:
I noticed the problem with the characters "[" and "(" but there may be others. Strangely, the character "{" seems to work without a problem. Checking the error log I found the attached error message.

Error message:
```
[2015-09-23 10:40:00,556] [ERROR] commands: An error occurred executing the cmd_startIncrementalSearch command
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [koIFindService.highlightall]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: chrome://komodo/content/find/find_functions.js :: Find_HighlightAllMatches :: line 1284"  data: no]
+ QueryInterface (function) 3 lines
+ message (string) 'Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [koIFindService.highlightall]'
+ result (number) 2147942487
+ name (string) 'NS_ERROR_ILLEGAL_VALUE'
+ filename (string) 'chrome://komodo/content/find/find_functions.js'
+ lineNumber (number) 1284
+ columnNumber (number) 0
+ location (object) JS frame :: chrome://komodo/content/find/find_functions.js :: Find_HighlightAllMatches :: line 1284
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/find/find_functions.js'
| + name (string) 'Find_HighlightAllMatches'
| + lineNumber (number) 1284
| + columnNumber (number) 0
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/library/findController.js :: FindController.prototype._startIncrementalSearch :: line 381
| + formattedStack (string) 'Find_HighlightAllMatches@chrome://komodo/content/find/find_functions.js:1284:0
FindController.protot'...847 chars
| + inner (object) null
| + data (object) null
| -- EXCEPTION END --
[2015-09-23 10:40:00,578] [ERROR] keybindings: 
-- EXCEPTION START --
2147500037
+ 0 (number) 2147500037
-- EXCEPTION END --
```

Build:
Komodo IDE, version 9.2.1, build 87651, platform linux-x86_64. Built on Tue Sep

**Comment by cgchoffman** [comment]
You likely have regex enabled.  When you open incremental find look for a `*` button and change it to plain.

**Comment by furnox** [comment]
That is true. And disabling regex does allow searching for those characters and normal operation.
Thanks!

However, while no longer a user-experience issue, that still doesn't explain why it's throwing an error message. Seems like that's the sort of thing that could be a bigger problem later.

**Comment by Defman21** [comment]
Because `[` and `(` are Regex special characters, they should be escaped in the way `\[` and `\(`.

**Comment by cgchoffman** [comment]
@furnox true enough.  Setting aside, there should not be an exception thrown.

@Defman21 
> Because [ and ( are Regex special characters, they should be escaped in the way \[ and \(.

That might be what's going on but that's not an excuse to throw an exception. 

Since the exception is handled cleanly though and doesn't effect functionality I'm going to leave this closed unless someone sees a reason to add it to the pile.

**Comment by Defman21** [comment]
An inline regex validator in Incremental Search would be a good feature (when the Regex search is enabled)

**Comment by cgchoffman** [comment]
> An inline regex validator in Incremental Search would be a good feature (when the Regex search is enabled)

You know where new enhancement requests go @Defman21 :smile:

**Comment by Defman21** [comment]
https://github.com/Komodo/KomodoEdit/issues/622 :)
