### ISSUE TITLE
IDE 9.2 will not recognize package from site-packages

### ISSUE THREAD

**Issue by wheelcode** [Komodo/KomodoEdit#624]
OS: Windows 7
Komodo IDE Personal 9.2
Python 3.4.2
I installed the openpyxl Excel package which installed in site-packages folder.
openpyxl imports fine running under the windows Python 3.4.2 interpreter in a script and from interactive shell.
If running the script in debug under Komodo I consistently get the following error:
Traceback (most recent call last):
  File "C:\Dropbox\PyDev\rename\rename.py", line 7, in <module>
    import openpyxl
ImportError: No module named openpyxl
I've tried adding the site-package directory in PYTHONPATH in the language and in the debug but nothing resolves the import error when running from within the IDE environment.
Bill Lange

**Comment by cgchoffman** [comment]
Could you move this to the [forums](http://forum.komodoide.com/).  It's likely that you haven't configured Komodo properly and not a bug.
