### ISSUE TITLE
PySide Code intelligence not working

### ISSUE THREAD

**Issue by Berkyjay** [Komodo/KomodoEdit#625]
In Komodo Edit 9.2.0. code completion does not fully work for PySide.  PySide can be imported but there is no access to the QtGui and QtCore libraries.

There is a .cix file:
https://github.com/ajalt/pyside-komodo-codeintel

But when added to the API catalog, it never shows up in the list.

**Comment by mitchell-as** [comment]
Hi,

As I mentioned in the forum post that cix file works, despite the fact it doesn't look like it initially. Again, here's what I did to get PySide completions in both Komodo and Komodo Edit 9:

1.    Download the referenced .cix file to a temporary directory.
2.    Open Komodo's Code Intelligence preference and clicked "Add an API Catalog".
3.    Select the .cix file in the temporary directory.
4.    Note that the file does not show up immediately in the view. This is a bug that will need to be looked into.
5.    Restart Komodo.
6.    Go back to Code Intelligence preference and PySide is now there in the tree view. Check it.
7.    Create a new Python file and added "import PySide" and then on a new line "PySide." and I got a list of completions.

The cix file looks good.

**Comment by Berkyjay** [comment]
I was asked by @nathanr to submit a bug for this.  I have followed the steps for both Komodo IDE and Komodo Edit 9.2.  The .cix file shows up in the file path but PySide never shows up as an option in the Code Intelligence tree view.

![komodo_cix_dir](https://cloud.githubusercontent.com/assets/5049386/10079076/fb7ac132-629c-11e5-8a74-e7b47e4c761f.JPG)

![komodo_api](https://cloud.githubusercontent.com/assets/5049386/10079081/02377db2-629d-11e5-960f-75f0d346f436.JPG)

**Comment by mitchell-as** [comment]
I just tried following my steps on Windows (I was previously on Linux) and I still get PySide completions. I'm sorry that you're having such trouble, but this works for me, so I don't know how else I can help.

**Comment by Berkyjay** [comment]
Well, just for posterity this is how I'm doing my imports.

from PySide import QtGui
from PySide import QtCore.
testWidget = QtGui.QWidget()

Is this similar to how you're doing it?  Also, I have installed Komodo Edit 9.2 on several of our farm machines and one of our macs.  None of them have worked so this isn't just isolated to my machine.  Is there anything with the Python install that would affect this?

**Comment by mitchell-as** [comment]
![pyside](https://cloud.githubusercontent.com/assets/12902397/10086512/c20fef22-62dc-11e5-9812-fa6a496ffd11.png)

I'm not sure if a Python install would affect this. You can try installing on a machine without Python installed (or on the PATH, etc.) and see if it works.

**Comment by Berkyjay** [comment]
Yeah, that's exactly how it should look.

So I went to one of my farm machines (Windows 7) installed Komodo IDE and then followed the same steps and I got the same results I have been getting.  I'm out of ideas on my end which sucks.  I really would like to get this working.  I've been using Komodo for years and would prefer to keep using it.
