### ISSUE TITLE
Drag to make file working side by side

### ISSUE THREAD

**Issue by drakele** [Komodo/KomodoEdit#626]
Some time i working with many file and i switch change only to file and i want it side by side 
Let see the picture : i want file main.css side by side with contact_tem... i just drag main.css to contact_temp, i think this feature very helpful for developer 

<img src="http://forum.komodoide.com/uploads/default/original/1X/5ec62c71b2bcc924f59c22e8d53b9b462cdcd452.png" width="690" height="431">

**Comment by Naatan** [comment]
Please don't file bugs like this. We monitor our forums and have notifications set up.

**Comment by Defman21** [comment]
Just some follow-ups:

1. Next time, set the correct title for your enhancement request.
2. If someone asked to file an enhancement request on the forums, please copy the text of your original request (from the forums) and use it as the text of the issue.

Thanks.

**Comment by drakele** [comment]
Ok i have update the request  !

**Comment by Defman21** [comment]
The title is still not good. Just name it in the way what are you asking to implement, there are no reasons to put "Request a new feature" or something like that (So the good title would be "Drag a file onto a tab to view it side-by-side" or something like that). But I'm not sure if you should do anything with this issue, @Naatan closed it 10 mins ago...

**Comment by drakele** [comment]
Ok i have change the title again !

**Comment by Naatan** [comment]
I'm not sure I follow. You want to open a file by dragging it to a specific position in the tab bar?

Do you know you can open a file and then drag its tab to a custom position?

**Comment by drakele** [comment]
I know i can drag the file from the tab bar but think so far when you open to many file it very hart to drag it together, i think it is best way to make komodo bester . You know i have move from dreamweave to komodo 'cause it good and i want it is bester day by day

**Comment by Naatan** [comment]
Are you aware of the Open File widget and it's sorting/grouping abilities? http://komodoide.com/screencasts/open-files-widget/

**Comment by drakele** [comment]
Yes i know this feature and it very helpful but i still recommend drag to side by side file , let think about it , hope your team will make komodo bester ...

**Comment by Naatan** [comment]
Ok, but I still don't understand exactly what it is you want. Your English is unfortunately a little bit cryptic. Could you try rephrasing?

**Comment by drakele** [comment]
Ok let me show you my mean !

When i working and when i open too many file and i want work with only 2 file together on the tab bar 
Ex :
Here is the tab on komo do :
[file 1] [file 2] [file 3] [file 4] [file 5] [file 6] [file 7]........ [file N]

Now i want [file 4] and [file n] ( or other file) side by side 

[file 1] [file 2] [file 3] <b>[file 4] [file N] </b>[file 5] [file 6] [file 7]........ [file N - 1 ]

Now on komodo i can only drag [file N] to [file 4] or [file 4] to [file N] on the tab bar and it very hard and slow to do so that why i recommend new feature to make this easier. And i want to do this feature i just only drag the file1 from the Open File, Place or from The Project to the file N on the tab bar to make it together .... that's it. I think this is a small change but very helpful, i have coding a long time and using many IDE but no IDE support this feature and i think komodo should had it...

**Comment by Naatan** [comment]
I don't understand how this is easier than doing it via the tab bar? It's also not nearly as simple as you may think it is, as those are two completely different UI elements, not to mention they live in different windows. 

As a potential solution for your use-case, how about we sort the tabs the same way they are sorted in your Open Files pane?

**Comment by AtmanActive** [comment]
Plus one for that last one.
Open File widget should be able to retrieve and set tabs sorting order in various dreamed of and undreamed of ways.

**Comment by cgchoffman** [comment]
> I don't understand how this is easier than doing it via the tab bar?

@nathanr, he's talking about dragging a file from Places to the tabs and dropping it in place (ie. drag file-n and drop it beside file-4, in between file-4 and 5).  At the moment you can only drop a file on the editor area and it's automatically placed at the end of the tab queue.  Then @drakele has to manually move it beside file-4.  He wants to cut out the last step.  Agreed that it's not as simple as it sounds though.  This implies that the view is instantiated while you drag it no?  Then it can interact with the other views.  

FWIW I stopped using the tabs in favour of Open Files a long time ago.  I highly recommend you give that a try @drakele and @AtmanActive

**Comment by AtmanActive** [comment]
@cgchoffman, I have more important uses for left pane, like Global Search and File Tree. 
True, I can switch to Open Files here and there to do some sorting job, but I can't have it open all of the time. 

Plus, it's inability to manually re-order files to one's liking is a big no-go for me. Right now you can rely on it to auto sort it for you and have an overview of all open files and that's it. The later I can achieve with Tabs' bell button (List all tabs), thank you very much.
So, for me Open Files dialog is almost there, but not quite yet. It should allow complete free/manual reordering, and it should have two more functions: get ordering from tabs, and, set ordering to tabs, so we can use it as a master tab navigator and organizer. For me, auto-sorting is always just a foundation, while manual sorting that comes after that really sets the working stage to be as fast as possible.
