### ISSUE TITLE
Potential memory leak in file closing

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#627]
1. Check your current Komodo memory usage
2. Open feature-core.ini (in the wix)
3. Close it
4. Repeat 2 and 3 10 times
5. Check memory usage

Memory usage will have increased by about 10-20mb. It will potentially be bigger with larger files.

Let's try and narrow this down to Komodo or Scintilla first.

**Comment by Naatan** [comment]
Memory reports of before and after 2 days of use. Nothing stands out to me, memory usage seems to simply increase across the board.

[memory-report1.txt](https://github.com/Komodo/KomodoEdit/files/3683/memory-report1.txt)
[memory-report2.txt](https://github.com/Komodo/KomodoEdit/files/3684/memory-report2.txt)

**Comment by mitchell-as** [comment]
This is very likely Komodo and not Scintilla.

Initial Memory usage: 221MB
Usage after one cycle of open/close feature-core.ini: 231MB
Usage after another cycle: 225MB
And another: 243MB
And another: 236MB
And another: 247MB
And another: 259MB
And another: 256MB
And another: 254MB
And another: 255MB

As you can see, memory usage plateaus. Therefore Scintilla is being a good citizen when it comes to memory usage.

**Comment by mitchell-as** [comment]
Perhaps we can try explicitly envoking the JS garbage collector on file close? I wouldn't be surprised if there are a lot of things left floating around.

**Comment by Naatan** [comment]
I have tried that, when Komodo starts it's at around 250MB memory usage for me, after about a day it is around 600MB (and usually stays around that point, the "leak" is not that bad) but clearing memory via about:memory has very little effect on that.

More concerning to me is that file opening and closing becomes much slower, which I think is related to this. Point being is that I believe fixing the memory issue will fix file opening/closing slowdowns.

**Comment by mitchell-as** [comment]
Are you still seeing this @Naatan ? Or has your profiling uncovered anything?

**Comment by Naatan** [comment]
Yep, still seeing this. It seems to increase pretty consistently for me, I cannot get it to "plateau".

None of the "Free Memory" tools in `about:memory` seem to reclaim this memory.
