### ISSUE TITLE
Skins: After installing and restarting Komodo should start with new skin.

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#628]
It takes two restarts to install a new skin.  Can we make it just one?

1 prefs > appearance > skins > download button > choose skin
2 restart
3 prefs > appearance > skins > select new skin
4 restart

Eliminate steps 3 and 4

**Comment by Defman21** [comment]
There are no skins anymore :)

**Comment by cgchoffman** [comment]
Ya this can probably be closed with all the changes that have occurred.  I haven't come across Komodo asking to restart.
