### ISSUE TITLE
Running Macro From Commando Fast Open

### ISSUE THREAD

**Issue by monoathero** [Komodo/KomodoEdit#63]
I am just wondering if I can run macro from commando, so far I can search a macro via commando but whenever I press enter the macro will be opened in edit mode instead of being run. I know I can assign shortcuts, but sometimes some macros are only relevant to certain projects, therefore these shortcuts will be redundant for any other projects. Commando is so great that now I am too lazy to leave my keyboard and click the toolbox.

**Comment by Naatan** [comment]
Glad you like Commando :)

I am unable to reproduce a macro being opened in edit mode, can you explain your exact work flow? Have you tested different macros?

**Comment by neurobashing** [comment]
I think this used to be "Invoke Tool", right? I see it in my old (8.5) keybindings but a search for 'invoke' in 9 only brings up "invoke hyperlink".

**Comment by Naatan** [comment]
Yes, correct @neurobashing 

(btw we're at Pycon again this year, hope to see you there again? :))

**Comment by neurobashing** [comment]
It's working correctly for me as well. 

Yes I will be at Pycon this year, looking forward to stopping by and chatting.

**Comment by monoathero** [comment]
Hi guys, my bad, it seems that the correct way to run macro is to use ctrl + shift + k shortcut, which was "invoke tool" in 8.5 but now it is called "Commando: Open Commando with the Tools and Commands Scope".  The flow where I had my macro opened in edit mode was because I used ctrl + shift + o, which listed my_macro.komodotool file and treat it as such. And since we have a lot of scopes in commando, how can someone change scope without clicking the top-left icon? 
I prefer assigning shortcut to  "Commando: Open Commando with the Everything Scope" though.

Sorry for the trouble.

**Comment by Naatan** [comment]
Ahh I see what happened, will be sure to exclude the .komodotools folder so this does not confuse other people as well.

You can define custom shortcuts under `Prefs > Key Bindings`. Look for "Commando".
