### ISSUE TITLE
Indent/dedent breaks on closing brackets

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#631]
Create a new file (text is fine), paste in the following:

```
    });
```

Hit Ctrl+A, then Shift+Tab - Dedents but looses selection
Hit Ctrl+A, then Tab - Deletes selection

**Comment by mitchell-as** [comment]
Odd, I cannot reproduce this. @Naatan can you still reproduce this?

**Comment by mitchell-as** [comment]
Closing, as I still cannot reproduce in HEAD. Please re-open if you see this again.

**Comment by Naatan** [comment]
Nope, can no longer reproduce it either, no idea what it was.
