### ISSUE TITLE
Auto-indent works bad inside Python dicts

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#632]
To reproduce:
```python
_dict = {
    'test': 123,
    'dict': {}, |
}
```
Or
```python
_dict = {
    'test': 123,
    'dict': {
        'key': "value"
    }, |
}
```
| - is a cursor. Press Enter and you will get an extra tab.

**Comment by Naatan** [comment]
I think you are missing a step?

**Comment by Defman21** [comment]
A step?

**Comment by Naatan** [comment]
From my perspective you are showing step 1 and step 3, I don't know what you did for step 2. 

In other words, please explain exactly what your steps to reproduce are?

**Comment by Defman21** [comment]
1. Write this code:
```python
_dict = {
    'test': 123,
    'dict': {}, |
}
```
2. Place your cursor in this code at the same place where is the `|` symbol (in other words - place your cursor after the `{}, ` construction).
3. Press Enter.
I get an extra tab in this case and my cursor moves to this place:
```python
_dict = {
    'test': 123,
    'dict': {},
        |
}
```

**Comment by mitchell-as** [comment]
Reproduced. Sorry for the delay.
