### ISSUE TITLE
Feature Request: back and forward only horizontal

### ISSUE THREAD

**Issue by AtmanActive** [Komodo/KomodoEdit#636]
The first two buttons in Komodo, those 'Go back one location' and 'Go forward one location' currently jump both horizontally and vertically, meaning, the points remembered are either different points in the current file, or in multiple files open.

This is all fine and dandy.

But, in my workflow I find it distracting when I hit back and it jumps vertically in the same file.
Indeed, I was there previously, but somehow, in my mind, I was expecting it to jump to previous file.

Hence I would like to suggest an user configurable option in Preferences: 'keep only one jump point per open file in history'. When turned on, this would mean that no matter how many times I scroll up and down through the current file, once I press BACK I want to jump to previous file and it's line number, and NOT to current file's previous line numbers.

In my mind, if the editor is Y axis, and tabs are X axis, then I would like BACK and FORWARD buttons to work only horizontally and not vertically as well. Although, it is true, when Komodo jumps BACK to previous file, I do expect it to be on the line number where I left it.

Thank you.

**Comment by cgchoffman** [comment]
This is exactly the same as using Ctrl + Tab is it no?

**Comment by AtmanActive** [comment]
If you meant pressing CTRL+Tab on my keyboard, then, no, nothing happens when I try that.

**Comment by cgchoffman** [comment]
Sounds like you have a custom keybinding setup then.  Please switch to default keybindings in your preferences and try it again.  Switching back to the previous file is already implemented and it's bound to Ctrl + Tab.

**Comment by AtmanActive** [comment]
Yup, I found it, thank you for the tip.
The function it does is: 'General: Most Recently Viewed File'.
I also tried CTRL+SHIFT+Tab and got unpredictable results, and that one is bound to 'General: Least Recently Viewed File'.

So, yes, you are right, 'Most Recently Viewed File' would do exactly what I was looking for.
I'm not even sure how FORWARD function would be usable in that context.
Now I just need to find a way to bring it to my toolbar.

Thank you very much for your help and this wonderful insight.
I just love it when developers already thought about it and it is there readily available.

Cheers!

**Comment by cgchoffman** [comment]
> Now I just need to find a way to bring it to my toolbar.

You'll want custome toolbars: http://docs.activestate.com/komodo/9.2/custtbi.html#custtbi_top

I think the easiest thing to do would be to create a macro that executes the `cmd_bufferNextMostRecent` command.  You can get the code for this by recording and saving a macro when you've used the keybinding to switch tabs.
http://docs.activestate.com/komodo/9.2/macros.html#macros_recording

**Comment by cgchoffman** [comment]
I"m going to close this now.  If you have further questions can you start a thread in the forums? http://forum.komodoide.com/  References this ticket if needed but this isn't the place to provide support.  This is strictly for feature and bug reports.
