### ISSUE TITLE
Context Menu Locks

### ISSUE THREAD

**Issue by wdbaker54** [Komodo/KomodoEdit#640]
When I do a right mouse-click in the editor pane and move down over an item containing a sub-menu I am unable to select anything else in the primary menu unless I dispose of the context menu by clicking outside of it and then re-selecting the context menu. For example, if I want to format my code using the 'Format ->' menu which is located below the 'Debug ->' menu item and move my mouse pointer down the menu slow enough for the 'Debug' sub-menu to appear then I cannot continue down to the 'Format' item - the only thing I can now do is select something under the 'Debug' sub-menu unless I start again.

I am running the latest nightly build of Komodo IDE 9 on Ubuntu Linux 14.04.

To reproduce the bug:
1. Open the context menu using the right mouse button.
![screenshot a](https://cloud.githubusercontent.com/assets/401129/10172069/48102318-6692-11e5-81da-cda999b4cece.png)
2. Slide the mouse pointer slowly enough down the menu past the 'Debug' item so that the sub-menu appears.
![screenshot b](https://cloud.githubusercontent.com/assets/401129/10172077/53661ed4-6692-11e5-9039-6f8e946bd795.png)
3. Try to continue down to the 'Format' item (or anything else, for that matter) and nothing else can be selected.
![screenshot c](https://cloud.githubusercontent.com/assets/401129/10172082/58ee6302-6692-11e5-804d-c7e4aa23d17c.png)

My current work-around is to make sure that when I activate the context menu that I move the mouse pointer outside the context menu until I am beside the 'Format' item (or whatever I want at the time) and then slide over to activate it specifically.

**Comment by mitchell-as** [comment]
I confirm that this happens, but as it looks to be a Mozilla thing, I'm not sure if we can solve it.

**Comment by wdbaker54** [comment]
Thanks for the speedy response. All I can say at this point is - Nuts!

**Comment by cgchoffman** [comment]
Tapping `Esc` should pop you up to the parent menu if that's an easier workaround for now.

**Comment by wdbaker54** [comment]
Didn't dawn on me about that. Much nicer - thank you.

**Comment by Defman21** [comment]
AFAIK this happens only on Ubuntu.
