### ISSUE TITLE
Menu not accessible with a single <Alt> keydown

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#641]
Komodo IDE, version 9.2.1, build 87651, platform linux-x86_64

I have the menubar hidden and ALT-shortcuts removed, in 9.1.0 it was possible to access the menubar with a single <ALT> keydown and keyup. That seems to be gone in 9.2.1.

**Comment by cgchoffman** [comment]
I have the same workflow but it's working for me in 9.2.1.  Did you just upgrade to 9.2.1 or did this happen over time?  Please post your logs as well.

I don't remove Alt-shortcuts but even enabling that didn't change anything.

**Comment by Naatan** [comment]
Did you upgrade your distro or desktop manager anywhere in between moving from 9.1 to 9.2.1?

**Comment by agroszer** [comment]
I just upgraded the IDE 9.1 -> 9.2.1 (side-by-side so I can go back anytime).
I had a working 9.1 config (~/.komodoide/9.1)
Installed 9.2.1, started it, ALT menubar access does not work...

**Comment by Naatan** [comment]
What distro and desktop manager?

**Comment by agroszer** [comment]
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty

Linux ebi 3.13.0-57-generic #95-Ubuntu SMP Fri Jun 19 09:28:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

xfce 4.10

**Comment by Naatan** [comment]
My Ubuntu 14.04 VM seems to be malfunctioning, so I cannot reproduce :\ Anyone with either Ubuntu (preferrably 14.04) or xfce 4 installed that can reproduce?

**Comment by mitchell-as** [comment]
I cannot reproduce on my Ubuntu 14.04 machine. I am using Unity though, and have disabled its Alt->HUD mapping. My hidden menu shows up when I press Alt.

**Comment by Naatan** [comment]
@cgchoffman do you have a 14.04 VM you could install xfce on?

**Comment by cgchoffman** [comment]
I do.  I'll try it now.

**Comment by Naatan** [comment]
So what happened? :P

**Comment by agroszer** [comment]
Just noticed that <ALT> does something... pressing it the further keypresses don't go to the editor, but prolly to a hidden menubar. Pressing <ALT> and moving around with the arrows and pressing <ENTER> seems to hit the menu commands. Seems like the menubar gets activated but is invisible.

**Comment by Naatan** [comment]
Interesting, possibly due to Ubuntu not liking menubars?

**Comment by cgchoffman** [comment]
Sorry, VMs....It took for ever.  I found that I cannot use ALT as Ubuntu steals the key binding to open the Unity menu.

**Comment by Defman21** [comment]
Reproduced on Ubuntu 15.04 using Unity :(

**Comment by agroszer** [comment]
I must be Komodo or Mozilla, I can anytime run 9.1.0 and [ALT] just works fine there.

**Comment by agroszer** [comment]
I guess this isn't pending response

**Comment by Naatan** [comment]
@agroszer I take it you disabled the Unity HUD?

**Comment by agroszer** [comment]
I have xfce, there's no HUD
As I wrote earlier, pressing ALT works fine with 9.1, fails with 9.2.1, fails too with 9.3.
Very same system, just KO is different.

**Comment by Naatan** [comment]
Does a clean profile resolve the issue?

Reference for myself: https://github.com/Komodo/KomodoIDE/commit/9c47fdd8f61a2fcfbfbfd7d1a79e135d32dda5a3

**Comment by agroszer** [comment]
You mean troubleshooting / reset everything in KO 9.3? What do I do to get a clean profile?

(Having earlier versions installed will pull the profile from the earlier version all the time)

**Comment by agroszer** [comment]
A pristine KO Edit 9.3 does it better. Menubar shows up, but ALT, the leftarrow, rightarrow does not show the current item as highlighted. You need to downarrow....

FOUND IT!

You need to "Show Toolbars"! If it's on, ALT access to the menubar works, if it's off it does NOT.

**Comment by Naatan** [comment]
Bah should have thought of that! We're tracking that issue here: #778

Thanks @agroszer, sorry for the inconvenience!

**Comment by samtajoshi20** [comment]
Press Alt Key for a couple of seconds, Menu bar will appear. Right click the menu bar and check Show Toolbar. Toolbar will appear.
