### ISSUE TITLE
Variable highlighting stops working in a file with Cyrillic characters

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#642]
I know this code is BIG but it's the only way to reproduce it - you should have a scrollable content in Komodo. Just scroll once to reproduce it. Not reproducible if you didn't scroll it a bit (so you see the first 4-5 lines of code).
```php
<?php

/* текст на русском */

/**
 * Test me
 */

function _test_function() {

    $long_variable = "Hello, world!";
    
    for ($i = 0; $i < 125; $i++) {
        echo "Test some code";
        $long_variable .= $i;
    }
    
    echo $long_variable;
    
}


die();
die();
die();
die();
die();
die();
die();
die();
die();
die();
die();
die();
die();
die();
die();
die();
die();
die();
die();
die();
die();
die();
die();
die();
die();
die();
die();
die();
die();
die();
die();
die();
die();
die();
die();
die();
die();
die();
die();
die();
```

**Comment by Naatan** [comment]
I cannot reproduce this. What encoding are you using?

**Comment by Defman21** [comment]
UTF-8. Please see this post, it contains some important info: http://forum.komodoide.com/t/variable-highlighting-stops-working-with-utf-8-symbols-in-document/2095/5

**Comment by Naatan** [comment]
Unfortunately nothing in there helps me to reproduce the issue.

**Comment by Defman21** [comment]
Are you sure you scrolled the area a bit down? I'm using Ubuntu 15.04 and I'm able to reproduce it, but there is nothing in the log.

**Comment by Naatan** [comment]
Yep I'm scrolling up and down, tried different ways of opening the file also. Tried on both IDE and Edit. Not happening :\

Can you record a video? Including the file opening part.

**Comment by Defman21** [comment]
Yeah, of course I can. :)

**Comment by Naatan** [comment]
Aff my bad, I was looking for highlighting, not *variable* highlighting.. 

Need to have my morning coffee before jumping in. Reproduced now, sorry Defman.

**Comment by Defman21** [comment]
Lol. No worries :)

**Comment by Naatan** [comment]
Spoke too soon, it was only getting stuck because it couldn't highlight a variable that's only 1 character in length, works fine after renaming $i.

https://dl.dropboxusercontent.com/u/41125814/var_highlighting.mp4

**Comment by Defman21** [comment]
Ehh, something weird is going on there. I'm not able to see the highlighting for `$long_variable` if I've the area scrolled down a bit.
https://youtu.be/VAbLxvCjk-g

**Comment by Naatan** [comment]
There we go, reproduced. Line 3 needs to be out of view for the issue to occur.

@mitchell-as all yours :p
