### ISSUE TITLE
Duplicate line up/down no longer works on selections

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#645]
When selecting multiple lines it only duplicates a single line. Transpose still seems to work fine with multiple lines.

**Comment by mitchell-as** [comment]
I cannot reproduce in latest git. I fixed something like this a while ago.

The command is "Editor: Duplicate Line/Selection Down", right?

**Comment by Naatan** [comment]
You're right, it's fixed on master. I was on a build that was slightly behind.

**Comment by tonyattwood** [comment]
Hello,
I  was reading an article  and suddenly came accross those words, they are  just perfect, you  can find the article here <http://expert.pinardelsol.info/e4iduyr>
All the best, tony.attwood@ntlworld.com
