### ISSUE TITLE
upgrading IDE 9.1 -> 9.2.1 disables add-on compatibility checking

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#647]
to repro:
Have a working 9.1 config, install 9.2.1
Wonder that disabled addons get enabled

**Comment by mitchell-as** [comment]
Hi, this is intentional. We are removing the add-on manager in favor of our own package management tool, so you will no longer see this in a future release.

**Comment by Naatan** [comment]
Note the next version of Komodo will have a tool specifically for checking addons that have not been updated for the current version of Komodo and could potentially cause issues.

The keyword there is "potentially"; we were seeing a lot of addons that were working perfectly fine but that didn't get their min/max version updated. This basically lets the user say "I know and I don't care".
