### ISSUE TITLE
Auto-wrap with delimiters should only trigger on plain text selections

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#649]
I think checking for /\w/ should do the trick? 

It should not trigger when I select a block of html for example.

**Comment by mitchell-as** [comment]
I can think of use cases where a user types `if (foo && bar || baz)`, forgot to enclose the `||` bit in parens, and wanted to do so with our feature. Also, what if you want to enclose multiple words in quotes?

**Comment by Naatan** [comment]
/\w/ matches whitespace iirc? if not then /[\w\s]/ would make more sense.

What you say is a valid use-case, but I find it less likely than wanting to replace a large selection with a different keystroke. We could only impose this rule on multi-line selections but the inconsistency would make for a confusing UX. How about we make it a pref?

**Comment by cgchoffman** [comment]
> Also, what if you want to enclose multiple words in quotes?

That is likely the most common use-case I'll have for this.

**Comment by Naatan** [comment]
For sure, didn't mean that those should be excluded. Whitespace is still "plain text" in my book.

**Comment by Naatan** [comment]
Sorry, I should have been clear about what I meant by "pref". I wanted the pref to be "whether or not to wrap non-plaintext selections".

The multiline only was what I was talking about being too complicated from a UX perspective.
