### ISSUE TITLE
Unable to see macro text when creating new macro

### ISSUE THREAD

**Issue by we3geeks** [Komodo/KomodoEdit#65]
Some of the editor window text visibility issues seem to still be present in the editor window used to create/edit macros. Steps to reproduce:

1. Switch to the Toolbox panel
2. Right-click on a folder; select Add > New Macro...
3. Click in the editor window where the macro source is to be entered
4. Type anything (nothing appears)
5. Click either Key Bindings or Triggers, then click Macro (returning to the portion of the window where you enter the source for the macro); whatever you typed in step 4, above, is now visible

Komodo Edit, version 9.0.0, build 15707, platform macosx.
Built on Thu Mar 19 06:08:01 2015.

**Comment by Naatan** [comment]
Same issue as #42
