### ISSUE TITLE
Closing brackets sometimes don't insert

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#655]
Generally happens when typing moderately fast, type out the following in JS (don't copy)

```
var foo =
{
```

It should insert a closing brace '}', if I go back delete the brace and type it again it works. If I type slow it also works.

**Comment by mitchell-as** [comment]
I cannot reproduce this, but then again, I cannot type '{' followed by 'Enter' in less than 50 milliseconds: https://github.com/Komodo/KomodoIDE/blob/790a9226d99b42f4de6d0f9a538a593f63a6c2dc/src/chrome/komodo/content/bindings/views-buffer.p.xml#L1165

Regardless, this is not a regression. The code responsible for this feature has not been touched in a long time. Therefore if this has been happening, I'll be its been happening forever.

**Comment by mitchell-as** [comment]
I can reproduce this by holding down '{' though. I end up with mismatched parenthesis.

**Comment by Naatan** [comment]
I am fairly certain it is a regression, as this is a very common workflow for me and it did not happen until I updated to 9.3. 

It may be a combination of preferences or something about my profile though, will try to narrow it down.

**Comment by Naatan** [comment]
I can no longer reproduce this. I guess it was caused by some other bug that since got fixed.
