### ISSUE TITLE
After update to 9.3 error on startup or new window

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#661]
After the update to 9.3, on start up i get a error
![snap 2015-10-06 at 11 30 11](https://cloud.githubusercontent.com/assets/3530262/10304999/ca3ac60a-6c1d-11e5-92f1-5b01b3e4948e.png)
and the error in the log file
<code>
[2015-10-06 09:20:08,009] [ERROR] console-logger: chrome://komodo/content/quickstart.xml : Unable to run script because scripts are blocked internally. (0) in :0
Traceback (most recent call last):
  File "", line 0, in 
</code>

**Comment by Naatan** [comment]
IDE or Edit?

@cgchoffman I seem to recall you saying you had this but then saying it was fixed on the latest nightly?

**Comment by babobski** [comment]
Edit, when i installed the update on work edit didn't started up after updating, after working for a while i closed all my screens(closing komodo) then when i wanted to restart komodo edit nothing happend. when i looked at my taskmanager komodo edit was still running when i killed the aplication i was able to start komodo edit again. Know im updating the version at home but after updating komodo didnt started automatic after update. When i click on the icon in my taskbar nothing happends, when i open my taskmanager komodo is still running.
![snap 2015-10-06 at 17 48 40](https://cloud.githubusercontent.com/assets/3530262/10313956/86f12940-6c52-11e5-8e4a-6ccdf3a08775.png)

**Comment by cgchoffman** [comment]
@Naatan I do see this yes.  I SWEAR it didn't happen when I first booted Edit but now it happens everytime.  The New Tab loads with an "unknown" name.
@babobski When you started Komodo and it appeared to NOT start then you noticed that the process was running in task manager this is likely because the "would you like to reload you last session?" window gets buried under another window.  I've seen this before and reported it but the bug fell off the radar.  *Time passes* oooooor was never filed?  I can't find it.

**Comment by babobski** [comment]
got the same error at home, killed komodo after a half hour, when i start komodo edit i got the same error. When started i was asked to restart komodo, when i clicked on it komodo edit wasn't restarting. when i looked at the taskmanager i got the same screen as above. after that i tried to get the same bug, but i wasnt able to reproduce, until i disabled a addon then komodo didn't restarted, i had my taskmanager open at first the proccesor had a vew procent and the disk, but this bleeded away after a vew seconds.
@cgchoffman there was no popup hiding somewhere (i have my settings to not restore last work space), komodo isn't quiting its last session, still got a session running, when i open the pystderr.log the last rules are 
<pre>
[ERROR] views: 
-- EXCEPTION START --
TypeError: view.initWithDocument is not a function
+ stack
    createViewFromDocument@viewlistbase:120:13
    viewManager.prototype._newViewFromURI@chrome://komodo/content/views.js:608:20
    viewManager.prototype._doFileOpen@chrome://komodo/content/views.js:732:12
    open_openStartPage@chrome://komodo/content/library/open.js:462:1
    uilayout_onload@chrome://komodo/content/library/uilayout.js:1867:9
    onloadDelay@chrome://komodo/content/komodo.js:393:9
    window.onload@chrome://komodo/content/komodo.js:515:9
-- EXCEPTION END --
</pre>

**Comment by Naatan** [comment]
@babobski please, one issue at a time. If you are running into other issues open other tickets.

I'll have a look at the quick start bug in komodo edit tomorrow.

**Comment by babobski** [comment]
ok will do, thought it was maybe related, but it are 2 different things.

**Comment by Naatan** [comment]
Note I was talking about this post> https://github.com/Komodo/KomodoEdit/issues/661#issuecomment-145907087

The other one does indeed seem related :)

**Comment by babobski** [comment]
ah think i found the problem. just created a new issue with a gist of my error log and this had some more information about the quikstart.xml bug on <a href="https://gist.github.com/babobski/c09b609fbc001c5d0743#ffile-pystdder-log-L34" target="_blank">line 34</a>.
<code>a undefined entity in quickstart.xml:65</code>
there is a unescaped & (and some more down below), ran in the same problem working on a addon with some old code from a other plugin.

**Comment by Naatan** [comment]
Thanks, should be fixed in the next nightly.
