### ISSUE TITLE
html4 auto completion doesn't always work

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#662]
When i create a new file from template a html5 template is opened(same behavior as 9.2), but im missing the auto completion for html4, for newsletters campaigns i need to work with html4 because html5 isnt supported. But the html4 auto completion on tables is completly gone.
The things im missing, on &lt;table&gt;: border, cellspacing, cellpadding, width on &lt;td&gt;&lt;th&gt;: align and valign.
Also still missing the target attribute on the &lt;a&gt; (if i remember it well, it was removed from the specs and therefore removed from komodo) but the target attribute made it to the html5 specs http://www.w3.org/TR/html5/text-level-semantics.html#the-a-element would be nice if it came to komodo

**Comment by Naatan** [comment]
This does not exist on Komodo 8 or 9.2 either, so it's nothing new in 9.3.

Making this an enhancement request.

**Comment by Naatan** [comment]
@mitchell-as if this is as simple as dropping some keywords into a catalog feel free to prioritize to your liking.

**Comment by babobski** [comment]
looked in to this, autocompletion for html4 is present in 9.3, only when you select new file from template and you select all languages this doesn't work.
![snap 2015-10-06 at 18 45 47](https://cloud.githubusercontent.com/assets/3530262/10315428/91ab53c6-6c5a-11e5-8a27-787faf0e6ad2.png)
When i select Common i got 1 more version of HTML, HTML (XHTML) in this the html4 autocompetion is working.
![snap 2015-10-06 at 18 49 20](https://cloud.githubusercontent.com/assets/3530262/10315497/f96d0144-6c5a-11e5-9d5a-497c3465ba8a.png)
And when i select the web i also got a HTML (4.01), where also the autocompletion is working.
![snap 2015-10-06 at 18 43 39](https://cloud.githubusercontent.com/assets/3530262/10315597/89bda4b0-6c5b-11e5-8470-8f840dd62e68.png)

At work i didnt find the right html template, then i tried to use the view > view as language, but the only options here where html and html5.

**Comment by Naatan** [comment]
Ahh there we go, the difference is the doctype, Komodo is apparently smart enough to infer what the current html file does and does not support.

Unfortunately, with templating and all of that type of stuff this is not something that ought to be automated that way in my opinion. @mitchell-as can you look into adding an HTML4 language that supports all of these classic arguments, regardless of doctype?

**Comment by mitchell-as** [comment]
There is no need to create a new HTML4 language. Just change the file's doctype manually via Edit > Current File Preferences and the scroll to the bottom section "Document Markup Settings". Pick HTML 4.01 Transitional or something other than "Determine from content".
