### ISSUE TITLE
The scrollbar stops moving randomly

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#663]
A file to reproduce: http://ticketdb.ru/view.zip
The problem: Start scrolling using your mouse to the end of the file. The scrollbar stops moving at random places (when you've scrolled about 80-85% of the file). I've reproduced it when Komodo wasn't maximized, but if it is - the scrollbar moves fine for me.
Video demonstration: https://www.screenr.com/jl5N

**Comment by Naatan** [comment]
What I'm seeing is slightly different; it appears to scroll multiple times in one "tick" randomly.

**Comment by mitchell-as** [comment]
@Defman21 does this still happen in Komodo X? The zip file is no longer available.

**Comment by Defman21** [comment]
I don't know. The file is not mine. However, the scrolling is working fine for me in Komodo X. There are no things that I'd want to file as bugs :)

**Comment by mitchell-as** [comment]
Okay, I will close this then.
