### ISSUE TITLE
All icons for find dialog are not rendering

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#665]
![screenshot 2015-10-06 09 05 46](https://cloud.githubusercontent.com/assets/655154/10314427/85866e7e-6c09-11e5-9b68-cf81e5a8f545.png)

Tried with clean profile.  Windows. Komodo IDE, version 9.3.0, build 87880, platform win32-x86.
Built on Mon Oct 05 01:00:36 2015.

**Comment by Naatan** [comment]
Something about the windows css rules is not allowing the icons to render, most likely a moz-appearance rule. @cgchoffman mind having a stab at this?

**Comment by Naatan** [comment]
Also those menu dropdown icons need to have their moz-appearance dropped.
