### ISSUE TITLE
Commando:  Relative paths don't seem to work.

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#667]
I can't use relative paths when I select the file scope.

**Comment by cgchoffman** [comment]
Can't seem to do any type of path actually.  I tried `C:\` and it just hangs searching.  If I add the start of a file or folder I know is there then the search stops and returns nothing.

**Comment by Naatan** [comment]
Todd reports it doesn't work for absolute either. Most likely due to my changes in adding support for live folders.
