### ISSUE TITLE
Help content for new Features

### ISSUE THREAD

**Issue by we3geeks** [Komodo/KomodoEdit#67]
Searching for either "commando" or "track changes" in the Komodo help content brings back nothing, even though both terms appear in the "What's New" section. Other than those references in the "What's New" section, I can't seem to find any coverage of these capabilities within the help content itself.

![ke9-20150326-2](https://cloud.githubusercontent.com/assets/2390335/6847600/698a8c42-d38d-11e4-8ad3-cba5109091ce.png)

Komodo Edit, version 9.0.0, build 15707, platform macosx.
Built on Thu Mar 19 06:08:01 2015.

**Comment by Naatan** [comment]
Documentation has fallen behind this release, it'll be added but it's no there atm. Luckily both features have pretty good UX and most functionality should be discoverable.

But yes - Docs arent there, they're on their way.

**Comment by Naatan** [comment]
Closing as this has been addressed in our workflow for 9.3. Meaning that by 9.3 release all new features should be documented.
