### ISSUE TITLE
Samples install to existing profiles

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#671]
I just noticed my abbreviations were reverted (overwritten) and a ton of samples are now in my toolbox. Seems the check does not work properly; samples are being installed to an existing profile.

**Comment by cgchoffman** [comment]
What does the toolbox look like?  Can you add a screenshot?

**Comment by Naatan** [comment]
I've already cleaned it up, but it was a mix of my tools and the sample tools.
