### ISSUE TITLE
Can't download Komodo Edit

### ISSUE THREAD

**Issue by BuddhikaGeasman** [Komodo/KomodoEdit#672]
The download does not process. Can not download for mac

**Comment by Naatan** [comment]
Just tried it, working fine for me. What page are you trying to download from and with what browser?

Closing this issue as it is not related to Komodo Edit itself, but would still like to discuss.

**Comment by BuddhikaGeasman** [comment]
So sorry for taking a while to reply. Does it work with the new OS for mac El Capitan? I still cannot download it. It stuck on the downloading komodo edit. I even clicked on the 'Just let me download your software' still not going through.

**Comment by Defman21** [comment]
http://downloads.activestate.com/Komodo/releases/9.2.1/Komodo-Edit-9.2.1-15998-macosx-x86_64.dmg

**Comment by BuddhikaGeasman** [comment]
@Defman21  Hey thank you for sending the dmg. I did a clean installation so had to reinstall the software. Thank you very much for the corporation.

**Comment by cgchoffman** [comment]
For future reference, this didn't warrant a bug report.  You can ask questions in the [forums](http://forum.komodoide.com/) and if it's determined that you've come across a bug then we'll request that you file one here.  Glad you're sorted out though!
