### ISSUE TITLE
9.3 Auto multi-caret for XML tags

### ISSUE THREAD

**Issue by Piniol** [Komodo/KomodoEdit#674]
Auto selecting matching tags can make life harder. It's not working as it should because it's not  selecting matching elements ;) Example on attached screenshot (selected "spa", "head" matched and replaced)
![komodo](https://cloud.githubusercontent.com/assets/15010011/10331031/3ae93ca6-6cd2-11e5-9400-4c6c4ce7791a.jpg)

**Comment by Naatan** [comment]
It's impossible for us to provide consistent functionality when your source code is malformed, unfortunately that'll be up to the end-user to control.

That said we may be able to better anticipate such events.

@mitchell-as leaving open for you to check if this can be improved (eg. the tag should at the very least match, and it should not be looking backwards if the selection is an opening tag, same goes for a closing tag not looking forwards.

Textual reproduction (you want to select "spa").

```
<!doctype html>

<html lang="en">
<head>
    <title><!-- Insert your title here --></title>
</head>
<body>
    <spa
</body>
</html>
```

**Comment by Piniol** [comment]
I understand this, but in this case code is not malformed. I started to write "span" but I have changed my mind and i want "div" element instead. So i select "spa" and start to write "div". As a bonus i have "div" in place of "head". It can make life harder i you have long code and you can't see what is going above. Maybe small improvement: match only closed tags, so it will not match elements while you are writing new tags.
