### ISSUE TITLE
Remove links to old addon dialog

### ISSUE THREAD

**Issue by Piniol** [Komodo/KomodoEdit#675]
Addons update doesn't work. After choosing "Check for updates", text "Updating add-ons" shows and nothing happens. (Windows 8.1 x64)

**Comment by Naatan** [comment]
Thanks for reminding us, we need to hook some of these old menu entries up to the new system.

To update addons you will now use Commando, hit Ctrl+Shift+O (Cmd instead of Ctrl on OSX) and go to Packages > Manage Packages > Update Packages.
