### ISSUE TITLE
Komodo edit not always rebooting/closing

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#677]
After the update komodo doesn't always reboot or restart, because of the last "session" is still running.
mentioned it in issue #661, this is does not happen every time but with a lager change to komodo, disabling a addon, change skin, but it is still quit random.

Things i tried to to for debugging.

1. disable all addons: 
does help a little bit but does not solve the problem

2. disable all macro's:
Taught this helped but was able to get komodo hanging in the last session again

When i have in my projects on a local directory, it seems to help.
But when i have a remote directory and the connection takes a while to connect, then it's almost certain that the session doesn't close. 

For me this behavior seem related to the issue i had with the sites plugin #469, i looked in to this issue to try and fix it for the plugin. The plugin was giving errors and was not working if the connection took to long to connect. but if the connection was fast the plugin was working (still gave a few errors but not like the issue). If it took to long i got a lot of undefined functions in my error log broke the plugin and komodo.

Also created a <a href="https://gist.github.com/babobski/c09b609fbc001c5d0743" target="_blank">gist</a> for the complete error log from the session that doesn't close

**Comment by Naatan** [comment]
Anything in your error log?

**Comment by babobski** [comment]
Noting special, added the log in the above comment. But in the log yesterday i had this code at the end 
<pre>[ERROR] views: 
-- EXCEPTION START --
TypeError: view.initWithDocument is not a function
+ stack
    createViewFromDocument@viewlistbase:120:13
    viewManager.prototype._newViewFromURI@chrome://komodo/content/views.js:608:20
    viewManager.prototype._doFileOpen@chrome://komodo/content/views.js:732:12
    open_openStartPage@chrome://komodo/content/library/open.js:462:1
    uilayout_onload@chrome://komodo/content/library/uilayout.js:1867:9
    onloadDelay@chrome://komodo/content/komodo.js:393:9
    window.onload@chrome://komodo/content/komodo.js:515:9
-- EXCEPTION END --
</pre>

view.initWithDocument, i looked at the quickstart.xml at the bottom of the page i find this code:
<pre><code>&lt;method name="initWithDocument"&gt;
        &lt;parameter name="doc"/&gt;
        &lt;body&gt; &lt;![CDATA[
            this.koDoc = doc;
            this.parentView.updateLeafName(this);
            this.parentView.updateFileStatus(this);
            xtk.domutils.fireEvent(this, 'view_document_attached');
            xtk.domutils.fireEvent(this, 'current_view_changed');
        ]]&gt; &lt;/body&gt;
        &lt;/method&gt;</code></pre>
I dont now if this is related to this bug, its look to me the page is loaded half, also missing all the buttons below
![snap 2015-10-07 at 20 45 03](https://cloud.githubusercontent.com/assets/3530262/10347873/5793da50-6d36-11e5-8b8b-8161a4a41867.png)
i think this is also blocking the methods below in the quickstart.xml

**Comment by babobski** [comment]
seems to be fixed in latest nightly, yesterday i had to kill komodo every time i installed a addon or switched skin. This morning it restarts when swithcing themes or installing addons

**Comment by Naatan** [comment]
It was probably related to a bug I found where Komodo would freeze if a preference was set from a child thread.
