### ISSUE TITLE
Tabs on osx are hard to close

### ISSUE THREAD

**Issue by jakeparis** [Komodo/KomodoEdit#68]
This renders them unusable, especially on large screens where the close[x] is so far away. They should be fixed width, so that all tabs are the exact same width, regardless of length of the title/filename. This makes it much easier to navigate the tabs and close a bunch at once.

**Comment by Naatan** [comment]
I wouldn't quite agree that it renders them "unusable", though I recognize that it may be an annoyance to some. We'll work on improving this UX, for now you could use Stylish to limit the tab width:

```
tab[type="file-tab"] {
   width: 250px !important;
   -moz-box-flex: 0 !important;
}
```

Leaving this bug open to improve tab closing UX.

**Comment by jakeparis** [comment]
Well, ok. Except that the *Stylish* plugin is incompatible with 9.0. :-1:

**Comment by Defman21** [comment]
Nope, it is. You just have to change maxVersion in `install.rdf` file.

**Comment by jakeparis** [comment]
Ok @Defman21, can you tell me where I might find the install.rdf file? I'm on osx.

**Comment by Defman21** [comment]
@jakeparis I can send you a modified Stylish plugin if you want. It is hard to describe if you don't know how to create plugins for Firefox/Komodo/etc.

**Comment by jakeparis** [comment]
@Defman21 I just sent you an email with my contact info. Thanks!
