### ISSUE TITLE
Commando doesn't display an icon for ids in Sections scope

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#680]

**Comment by Naatan** [comment]
Please by all means; explain? :P

**Comment by Defman21** [comment]
Write this code (or copy it):
```css
#id {
color: red;
}
```
Then open Commando with Code Section scope, you won't see an icon for `#id` item.

**Comment by Defman21** [comment]
Seems like Commando doesn't display an icon for any style type exclude classes.
