### ISSUE TITLE
Different icon sizes in the file type list

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#683]
Looks very... strange.

![whaaa](https://cloud.githubusercontent.com/assets/7100645/10345951/5fa19486-6d35-11e5-8755-d2512b34442d.png)

**Comment by Naatan** [comment]
The new icons don't seem to like being resized. Also it seems your icon cache didn't clear. Try deleting `~/.komodoide/9.3/XRE/icons` (while Komodo is not running).

**Comment by Defman21** [comment]
Well I've deleted this folder. Nothing has changed.

**Comment by Naatan** [comment]
IDE or Edit?

**Comment by Defman21** [comment]
IDE

**Comment by Naatan** [comment]
I'm talking about the icons that ARE sized properly btw, they shuold look different, which deleting the icons folder should have ensured.

**Comment by Naatan** [comment]
OH I think that may be in the next nightly, nevermind.

**Comment by Defman21** [comment]
Ok :)
