### ISSUE TITLE
Troubleshooting menu on Quickstart page is broken

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#684]
Btw it's visible with TabulaRasa :P

![whaaa2](https://cloud.githubusercontent.com/assets/7100645/10346240/c7821d90-6d36-11e5-83ad-2145e16f02c3.png)

**Comment by Naatan** [comment]
I guess we need another troubleshooting button for when the troubleshooting button isn't working.

**Comment by Defman21** [comment]
That's some kind of troubleshooting recursion..
