### ISSUE TITLE
Multiple errors breaks Syntax Checking Status menu

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#685]
It's so big so I wasn't able to screen the full menu on my 1680x1050 screen :P
![whaaaa3](https://cloud.githubusercontent.com/assets/7100645/10346335/5f7abdaa-6d37-11e5-80c5-e0d8f3141fcf.png)

**Comment by Naatan** [comment]
Simple fix: don't write code with syntax errors.

**Comment by Defman21** [comment]
Not very simple using PEP8 :P
