### ISSUE TITLE
New: Find: Having selected text should default to "selected text"

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#687]
9.3 if we can but it's not a blocker.  This is functionality that the old dialog had that the new should definitely have.

**Comment by Naatan** [comment]
With what command are you invoking the Find widget?

**Comment by cgchoffman** [comment]
I used ctrl + shift + H which is...oops, find/replace in **files**.  @dch, what key binding/command are you using where you saw this issue?  I run the Find: Find command and it works as expected.

**Comment by dch** [comment]
On Wed, 7 Oct 2015, at 09:00 PM, Carey Hoffman wrote:
> I used ctrl + shift + H which is...oops, find/replace in **files**. 
> @dch, what key binding/command are you using where you saw this issue?  I
> run the Find: Find command and it works as expected.
> Reply to this email directly or view it on GitHub:
> https://github.com/Komodo/KomodoEdit/issues/687#issuecomment-146294338

I use ctrl= which is bound to Find:Replace on OSX.

I can't replicate this now on either mac, both running now:

Komodo IDE, version 9.3.0, build 87940, platform macosx.
Built on Thu Oct 8 02:25:32 2015. 

- selecting a large (5 lines) block of text and ctrl= drops me into the
find/replace dialog box with "selected text" as scope
- selecting a single or a few words and ctrl= drops me into f/r dialog
with file as scope

Should we close this? It seems to be fixed.

**Comment by Naatan** [comment]
Yep, thanks for checking :)
