### ISSUE TITLE
Update Komodo API Catalog

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#688]
Well, you guys implemented a new Komodo SDK and I think it will be a good idea to update your Komodo API catalog for Code Intelligence, so when I do `require('ko/logging')` I should get some auto-completions from this file: https://github.com/Komodo/KomodoEdit/blob/master/src/chrome/komodo/content/sdk/logging.js and the same for other SDK modules.
I think it's an important issue, because
>this is restricting Komodo's ability to be extended, which is a big part of it. &copy; https://github.com/Komodo/KomodoEdit/issues/598#issuecomment-139570857

**Comment by cgchoffman** [comment]
It's funny, the JS console already has code completion for our require modules.  Can we piggy back on that or do we need to update a komodo.cix file?

**Comment by Naatan** [comment]
The JS console is actually bugged at the moment, it is invoked the actual module to get that code completion, which is very unsafe. So we can unfortunately not use that and it will disappear from the JS console unfortunately.

@mitchell-as do you have any idea of the complexity involved in supporting codeintel for require() modules? Pre-generated would be fine for now.

**Comment by Defman21** [comment]
>it is invoked the actual module to get that code completion, which is very unsafe.

Why it's very unsafe? It's not very good for memory or what?

**Comment by Naatan** [comment]
Because it could be invoking functionality that you don't want to invoke. It would be like your shell executing every keystroke, instead of just when you press enter.

**Comment by Defman21** [comment]
ahh, so when I enter require('ko/logging').getLogger('test'), Console will try to execute this code on each key press? Yeah, that's very unsafe. I suggest to show auto-completions only when you press Tab - so the code will be executed just to get some auto-completions and remove the `keypress` listener.

**Comment by mitchell-as** [comment]
@Naatan it appears codeintel has some support for recognizing 'require' CommonJS syntax. If you have a cix file with a blob name of 'ko/logging' or 'ko/editor', then I think you can use that catalog for completions. I haven't tried this though.

**Comment by Naatan** [comment]
Thanks, let's see what we can do for Komodo 10.

**Comment by Defman21** [comment]
You already have a milestone for Komodo 10? Lol

**Comment by mitchell-as** [comment]
This is no longer needed. Our improved codeintel for Javascript coupled with the new "Javascript Namespace Mapping" for `require` statements allows codeintel for Komodo's SDK.
