### ISSUE TITLE
Komodo IDE, version 9.3.0 on Ubuntu 14.04 Alt-key Bindings Not Working In Find/Replace

### ISSUE THREAD

**Issue by wdbaker54** [Komodo/KomodoEdit#689]
When I use Ctrl-F (or Ctrl-H) to open the Find/Replace widget and then attempt to use 'Alt'+key to access a sub-function (such as 'Alt'+A for 'Find All' the Find/Replace widget disappears as soon as the 'Alt' key is pressed. The only way to access the sub-functions is with a mouse.

**Comment by Naatan** [comment]
THis could be tricky, since the Alt bindings are OS level. As a workaround you could use Prefs > Find > Pin the Find Frame.

**Comment by Naatan** [comment]
I can't reproduce this. @cgchoffman would you mind checking on Windows?

**Comment by cgchoffman** [comment]
This is the bug I mentioned last week.  "Find All" and "Replace All" have the same accesskey attribute.  The issue being that "Find All" shouldn't be there.

**Comment by Naatan** [comment]
@cgchoffman that's a different bug, the issue here is that the find widget disappears when you press and hold Alt.

**Comment by cgchoffman** [comment]
Ya it's doing `find all`. @wdbaker54 doesn't the find pane open?

**Comment by cgchoffman** [comment]
Ahh. I didn't read this correclty. no i can't reproduce this.

**Comment by Naatan** [comment]
Ok, thanks :) This is probably something Ubuntu specific.

**Comment by mitchell-as** [comment]
This is an Ubuntu Unity issue. By default, Unity switches widget focus to the menu bar when the Alt key is tabbed. This focus switch triggers the find panel to hide. This happens in any GTK-based application, not just Komodo. The only solution is to download the "CompizConfig" program and disable the "Key to show the menu bar when pressed" setting in the "Ubuntu Unity Plugin" section of the Desktop category.

http://askubuntu.com/questions/452691/14-04-alt-key-conflict-after-changing-hud-and-window-menu-shortcuts

**Comment by wdbaker54** [comment]
Thank you for all the work you guys did on this. I was in the process of confirming and isolating the problem with a Komodo install on a virtual machine of Fedora when you saved me the effort.
