### ISSUE TITLE
Track Changes does not support character sets

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#69]
Reference: http://forum.komodoide.com/t/wrong-charset-in-changebar-window-ide-9/1350

**Comment by Naatan** [comment]
@cgchoffman Didn't you say you were in the market for a bug like this? ;)

**Comment by ericpromislow** [comment]
The HTML iframe decalres the text to be utf-8, so the insertions like 
concat(escapeLines...), and scimoz.insertText should convert their
arguments into utf-8, if needed. (I think).

**Comment by cgchoffman** [comment]
@ericpromislow do you mean we need to change the declaration for the iFrame?  or change the way the text is being added to the iframe?

**Comment by Naatan** [comment]
The latter, we'll need to convert the encoding for whatever the file is feeding us. Probably best if we do this with Python.
