### ISSUE TITLE
Komodo IDE, version 9.3.0 on Ubuntu 14.04 Column Selection Broke

### ISSUE THREAD

**Issue by wdbaker54** [Komodo/KomodoEdit#690]
When I attempt to use the 'Ctrl'+'left-click' + drag to select a column - it utterly fails and works just as if I didn't hold down the 'Ctrl' key.

**Comment by cgchoffman** [comment]
I'm guessing this is due to Ctrl + click being mapped to multiple cursor placement now.  Although, I thought Alt + Click/drag was column select.

**Comment by Naatan** [comment]
Perhaps we should make it Ctrl+Shift+Click-drag and save @mitchell-as a lot of pain. To be honest that makes more sense also (since shift is used for selections).

**Comment by mitchell-as** [comment]
Column selection on Linux now uses the Super/Win+Click-drag combination.

**Comment by mitchell-as** [comment]
Relevant documentation: https://github.com/Komodo/KomodoEdit/blob/7bacde1c3efc3c4bdc1517ee26762530645583d0/src/SciMoz/nsSciMoz.cxx#L192

**Comment by mitchell-as** [comment]
If you want the old behavior you can create a macro with this:

`require('ko/editor').scimoz().rectangularSelectionModifier=2`

2 is the Ctrl key modifier.

**Comment by Naatan** [comment]
@mitchell-as

**Comment by wdbaker54** [comment]
Just a note - on Ubuntu (at least 14.04 as far as I know) a long press of the super key will bring up that nasty shortcut key overlay. This causes the overlay to mask what I am trying to copy but it can be disabled by using the compiz config manager so I am good with that if nothing better comes along.

**Comment by mitchell-as** [comment]
Compromise: start making a normal selection with the mouse, then press and hold the column selection modifier key you're used to (e.g. Ctrl on Linux) in order to transform the normal selection into a column selection.

Super is no longer used.

Closed via https://github.com/Komodo/KomodoEdit/commit/e001dcfb5a78f3242ee6572f28f8a87b4bd09420

**Comment by tonyattwood** [comment]
Hi,

Here is some stuff that i like, and I wanted to  ask  you  if you're interested in something like that? Take  a look <http://famous.omiddental.com/e4jmi>

Take care, tony.attwood@ntlworld.com

**Comment by tonyattwood** [comment]
hi,
I think  this story is really awesome, you're gonna  love it, please read  it here <http://expert.healyourrelationshipwithmoney.com/e4jwmdx>

Take care, tony.attwood@ntlworld.com
