### ISSUE TITLE
Komodo Edit 9.3 File menu etc disappeared - Debian

### ISSUE THREAD

**Issue by VeNoMouS** [Komodo/KomodoEdit#691]
After upgrading to 9.3 yesterday, opened komodo this morning all the menus where gone, making changes to code key binds to save file etc did not bring up menu either to save...

Downgrading back to 9.2 brings the menus back...

**Comment by Naatan** [comment]
Are you talking about the menu that appears when you press Alt?

Note you can still access this menu from the burger menu (top right if you have a toolbar, otherwise on the left side of the statusbar).

**Comment by VeNoMouS** [comment]
All that I had was the top icons on the right hand side "+" and the hat looking icon...  the hat icon only let me open file... every other menu was gone.

**Comment by cgchoffman** [comment]
Screenshots speak 1000 words.  Could you please provide one so we can better understand exactly what you're talking about?

**Comment by VeNoMouS** [comment]
I can do that for you, I'll re-upgrade and see if I can reproduce the issue in a little bit, in middle of work atm, after I upgraded yesterday everything was fine...

It was only this morning when I fired up komodo that the issue arose.

**Comment by Naatan** [comment]
Note you can install multiple versions of Komodo side-by-side, just install them to a different path.
