### ISSUE TITLE
SCP: path taken as absolute

### ISSUE THREAD

**Issue by jhihn** [Komodo/KomodoEdit#692]
Within scp, you can specify a destination as server:path. where path is relative to the user home dir.
With Komodo, it takes path to mean /path, the error prints server:/path. I think this is as easy a fix as leaving the /  out.

**Comment by Naatan** [comment]
Thanks for reporting! Could you give some simple steps to reproduce the actually issue? Ie. where does Komodo give you trouble for using a relative path?

**Comment by jhihn** [comment]
Um, how about just that? I didn't do anything out of the ordinary.
I added the server in preferences,
using a id_rsa file,
set the path to an existing subdir of my home dir as "subdir" (no quotes)
saved
clicked on the gear and selected the remote directory option.
selected the server, got the error about :/subdir
Reconfigured the server to use /home/me/subdir
repeated, saw the dir listing.

**Comment by Naatan** [comment]
You gave the effect, not the cause. We could probably figure it out based on what you said but it's better if we have exact reproduction steps. Thanks for providing those.

Are you saying you set a relative path in the "Default path" field of your server settings? In that case I have to ask; relative to *what*? I think it stands to reason that you enter an absolute path there..

**Comment by jhihn** [comment]
Well, per the other issue, even as absolute, it takes it as relative.

And the answer as to relative to what, is wherever the sshd is configured to put me. 99% of the time it will be the user's home dir. I use relative paths all the time with scp.

**Comment by cgchoffman** [comment]
well that was fun.  

> I think this is as easy a fix as leaving the / out.

You would hope but sadly that's simply not try.  

I turned on debug in about 6 different files to try and trace this; Komodo seems to do the right thing for a while then magically the path it's supposed to use goes from "mypath" to "/mypath".  

This isn't really worth fixing when all you need to do is set a absolute path once in your server config and then forget about it.  I can see it being helpful when writing commands over and over again in the terminal, but not here.

Apologies @jhihn and we do appreciate the report.

**Comment by Naatan** [comment]
@cgchoffman anything we can add to the pref window to make it more evident what type of value is expected?

**Comment by cgchoffman** [comment]
Yes for sure.  You can even use tilde.  I can add some text to the pref window to clarify/manage expectations.

**Comment by Naatan** [comment]
I've reopened this as a reminder

**Comment by jhihn** [comment]
Would be nice for you to find out what functions thinks it has the right to modify the user-supplied parameter. Could cause issues. True files  in / aren't normally writable, until you figure someone someone might log in as root, and might have ~/bin ~/opt, etc. because no one *ever* has those :rolleyes: and logs in as root.

**Comment by cgchoffman** [comment]
> Would be nice for you to find out what functions thinks it has the right

I did finally find that function but that only solves your specific use case.  If you do any other type of relative path it will break.

One spot of concern is: https://github.com/Komodo/KomodoIDE/blob/master/src/components/koSCP.py#L332
Fixing that only allows you to access 

But that's only the start.  In order to allow the folder to be opened in Places it looks to need refactoring to do the right thing for SCP OR we could manually resolve relative paths before handing them back to Places.

Either way, too much for 9.3.  The best we can do is update the prefs dialog for now.

**Comment by cgchoffman** [comment]
Note to self:
I resolved like 332 from the link above with the following
```
if not parent_path:
    parent_path = os.path.dirname(os.path.join(self.do_getHomeDirectory(), norm_path))        
```
