### ISSUE TITLE
Komodo won't start on Windows VMs

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#694]
What I've found after brief testing is that it looks like Mozilla is crashing somehow.  It doesn't look like any Komodo starts, or at least any of the Komodo initialization code.  The profile folder consists of the XRE, Startup, and startup-env.tmp.

There is unfortunately no sign of logs or crash reports.  Running from terminal with verbose doesn't show anything.

**Comment by Naatan** [comment]
Fwiw I tried running the exe from visual studio, nothing useful, just returned exit code 0; nothing else.

**Comment by cgchoffman** [comment]
Note: to check this when we have a fresh Mozilla build for the nightly.

**Comment by Naatan** [comment]
Last nightly resolved this.
