### ISSUE TITLE
"Help > Troubleshooting > Log file" no longer works

### ISSUE THREAD

**Issue by twhiteman** [Komodo/KomodoEdit#699]
Komodo IDE, version 9.3.0, build 87940, platform macosx.
Built on Thu Oct 8 02:25:32 2015.

Help > Troubleshooting > Log file menu no longer finds the correct file. Somehow Komodo is writing it's pydterr.log to the 9.2 directory!? Someone forget to bump a version number somewhere (i.e. do a new mozilla build when the Komodo minor version changed)?

**Comment by Naatan** [comment]
Mine is getting the 9.3 pystderr.log on OSX. Is this right after update? See if it still happens after restarting Komodo?

**Comment by twhiteman** [comment]
No longer happening... so maybe it was during 9.2 > 9.3 update (and needed a full restart).
