### ISSUE TITLE
find: Add closing (X) to non default tab layouts 

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#701]
Start multiple find result sessions.  You can't close them.  They'll just keep being created.

**Comment by Naatan** [comment]
Workaround: Scroll all the way left and start from the first one.

Need to account for the scroll offset with my close button hack.

**Comment by Naatan** [comment]
Fixed on master.

**Comment by cgchoffman** [comment]
This isn't fixed in my local build or the nightly build Komodo IDE, version 9.3.0, build 88050, platform win32-x86. Built on Tue Oct 20 01:00:30 2015.

**Comment by Naatan** [comment]
What are you doing to close them?

**Comment by cgchoffman** [comment]
Restarting KOmodo :D

**Comment by Naatan** [comment]
Sigh, I mean what are you trying that doesn't work. :p

**Comment by cgchoffman** [comment]
Sigh, there is no way to close them.  That's what the bug is reporting.  So i'm not trying anything.

**Comment by Naatan** [comment]
Let me put this another way: Please explain what you are clicking or pressing on your computer to close a find results tab.

I just tried on my own build (off master) by clicking the closing icon (X) and it works for me.

**Comment by cgchoffman** [comment]
![capture](https://cloud.githubusercontent.com/assets/655154/10650951/5efbb4d6-7801-11e5-8e80-0c28a28da964.PNG)

I know what you're asking and I've answered twice.  There IS NO close button.  That is what I'm telling you.  Look at the picture i've attached.  Maybe there isn't an issue with Windows?

**Comment by Naatan** [comment]
AHH that helped! You are using non-default tabs, try using Prefs > Appearance > Side Pane Layouts > Bottom Pane > "Horizontal Tabs". The issue here is that there is no close button for tab layouts other than the default one.

**Comment by cgchoffman** [comment]
Ok, yes it's there when it's a tab rather than icon.  Need to add the close button to the tab if it's not the default.

**Comment by Naatan** [comment]
Note that since adding a close button to icon-only tabs would just be all around fugly I instead added the ability to middle-mouse button click the tabs to close it. Which is an established UX in browsers.
