### ISSUE TITLE
Feature Request: show file EOL in bottom bar

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#704]
got a freature request for the bottom bar, at my work i also have phpstrom running. There is one small feature i would love to see it come to komodo.
In komodo you can see and switch your file encoding in the footer, in phpstorm you can see and switch your file encoding and your files EOL settings.
![snap 2015-10-09 at 07 11 01](https://cloud.githubusercontent.com/assets/3530262/10386280/7598ece6-6e55-11e5-95ae-4aa510296ffb.png)
Would be nice if the same feature came to komodo

**Comment by cgchoffman** [comment]
So in the files preferences?  Is this a dialog somewhere in phpstorm?  I kind of assume that's not what you mean as that wouldn't be easier and I already exists....I think.  I'm not at my computer :P.  Could you provide a bigger screen shot to give more context?

**Comment by Naatan** [comment]
I'm not convinced about having this as a native feature, in all my years of using Komodo I can think of maybe a few instances where I wanted to change the line endings. My point being that this is a type of feature that is "not for everyone", and probably is only useful for a niche amount of users.

I think a better solution would be to write an addon/macro for it, which really wouldn't be very hard at all. 

In case anyone is interested, here is a Word Count in statusbar macro I did a while ago that could be easily modified to show/change line endings:

```
if (typeof(extensions) == "undefined") {
    extensions = {};
}

(function() {
    
    var editor  = require("ko/editor");
    var $       = require("ko/dom");
    
    window.removeEventListener('current_view_linecol_changed', extensions.addWordCount);
    
    $("#statusbar-wordcount").remove();
    $("#statusbar-selection").after($("<statusbarpanel id='statusbar-wordcount'/>"));
    
    var panel   = $('#statusbar-wordcount');
    panel.append("<label class='statusbarpanel-text'/>");
    var label = $('#statusbar-wordcount > label');

    var timer, timerRunning;
    extensions.addWordCount = function(){
        if (timerRunning) return;
        timer = setTimeout(addWordCount, 500);
        timerRunning = true;
    };

    window.addEventListener('current_view_linecol_changed', extensions.addWordCount);

    function addWordCount() {
        timerRunning = false;
   
        var words = editor.getValue().match(/\w+/g).length;
        label.attr('value', "Words: " + words);
    }
    
})();
```

**Comment by babobski** [comment]
@cgchoffman its a screenshot from phpstorm, at my work we work with phpstorm and this is a feature i really missing in komodo. When you open a file you could see in one instance if the file has the right line endings. 
@Naatan Why i made this feature request is because at work we started to work with version control (bitbucket) and composer, the things we ran in to, that you have to configure you're git/bitbucket to have the right line endings. The other problem we ran in to is, we ran the composer update local and ftp it with filezilla to the server. What happens is that we had the line endings on \r\n when uploaded true filezilla the where converted to \n, you can configure filezilla to not do that. Finally we figured out how to get every thing working fine with each other, but the thing we where left with is a bunch of files in version control with the wrong line endings, indentation and different file types.

In phpstorm when i open a file, i can see in one instance if the file has the right encoding and the right line endings and it even gives me a warning if the file is indention with the wrong format.
So from my perspective its a thing i need to know when opening a file and not a luxury function i use once a year, and i think i'm not the only one who has to go true the learning curve how to configure every thing to work with each other. That's why i think this should be native.

But if you still think this should not be native, i would thank you for the snippet and i will see what i can do.

**Comment by Xotic750** [comment]
Never played with the Macros on KE and saw this and looked interesting. Here is a simple line ending status macro, doesn't have any input to actually change line endings, just show the status of the file. Haven't tested it thoroughly, I just a had a few minutes to play, I take no responsibility for any bugs. :)
```
/*global extensions:true, require, window, setTimeout */
(function (editor, $) {
  'use strict';

  var timerRunning,
    timer,
    label;

  $('#statusbar-lineendings').remove();
  $('#statusbar-selection')
    .after("<statusbarpanel id='statusbar-lineendings'/>");
  $('#statusbar-lineendings')
    .append("<label class='statusbarpanel-text'/>");
  label = $('#statusbar-lineendings > label');

  function addLineEndings() {
    /*jshint maxcomplexity:7 */
    var s = editor.getValue(),
      dos = /\r\n/.test(s),
      unix = /(^|[^\r])\n/.test(s),
      mac = /\r([^\n]|$)/.test(s),
      mixed = dos && unix || dos && mac || unix && mac,
      endings = 'None';

    if (mixed) {
      endings = 'Mixed';
    } else if (dos) {
      endings = 'Dos';
    } else if (unix) {
      endings = 'Unix';
    } else if (mac) {
      endings = 'Mac';
    }

    label.attr('value', 'Endings: ' + endings);
    timerRunning = false;
  }

  if (typeof extensions === 'undefined') {
    extensions = {};
  }

  extensions.addLineEndings = function () {
    if (!timerRunning) {
      timer = setTimeout(addLineEndings, 500);
      timerRunning = true;
    }
  };

  window.removeEventListener(
    'current_view_linecol_changed',
    extensions.addLineEndings,
    false
  );

  window.addEventListener(
    'current_view_linecol_changed',
    extensions.addLineEndings,
    false
  );

}(require('ko/editor'), require('ko/dom')));
```

**Comment by babobski** [comment]
@Xotic750 :thumbsup: Nice, thanks for the snippet, tested it and worked fine.

+

**Comment by Xotic750** [comment]
Could be probably be improved using a better choice of events, I think it fires far to often for its purpose, but I'm only just beginning to look at macros since reading this request. :)

**Comment by babobski** [comment]
Youre wright, needs some figuring out, also wanted to extend it to check with the current file settings and if the current file settings match youre global configuration, but still needs some figuring out. Found already a <a href="http://forum.komodoide.com/t/setting-komodo-preferences-through-a-macro/908" target="_blank">tutorial</a> how to get your global preferences but need some more work.

**Comment by Xotic750** [comment]
Improved it a little after having some time to read some stuff.

**Comment by Xotic750** [comment]
Managed to get the current file preferences but can't find an event that will fire upon change of these preferences, that could cause  bit of an issue.

**Comment by babobski** [comment]
@Xotic750 nice going, also played around with the code a little bit.
You can catch the file preferences change with a simple "focus" after you save your preferences the window get his focus back and fires the event.

I got i kind of different approach just want to see settings for the current file and if the current setting mismatch the global configuration i wanted to give a warning.
If i got different eol in my file than the file settings komodo already gives me a warning.
This is what I've come up with so far:
<pre>
if (typeof(extensions) == "undefined") {
    extensions = {};
}

(function() {

    var editor  = require("ko/editor");
    var $       = require("ko/dom");
    var eol     = ['CRLF', 'CR', 'LF'];

    window.removeEventListener('current_view_changed', extensions.addEOL);
    window.removeEventListener('focus', extensions.addEOL);
    window.removeEventListener('view_opened', extensions.checkEOL);

    $("#statusbar-eol").remove();
    $("#statusbar-encoding").before($("&lt;statusbarpanel id='statusbar-eol'/&gt;"));

    var panel   = $('#statusbar-eol');
    panel.append("&lt;label class='statusbarpanel-text'/&gt;");
    var label = $('#statusbar-eol > label');

    var timer, timerRunning;
    extensions.addEOL = function(){
        if (timerRunning) return;
        timer = setTimeout(addEOL, 500);
        timerRunning = true;
    };
    
    extensions.checkEOL = function() {
    	var scimoz = ko.views.manager.currentView.scimoz;
    	if (scimoz == undefined) {
    		return;
    	}
    	var fileEOL = eol[scimoz.eOLMode];
    	var globalEOL = ko.prefs.getString('endOfLine');
    	if (fileEOL !== globalEOL) {
    		ko.statusBar.AddMessage(
    			'Current file EOL ' + fileEOL + ' mismatch global configuration ' + globalEOL,
    			'line-endings-event',
    			1000,
    			false
    		);
    	}
    }

    window.addEventListener('current_view_changed', extensions.addEOL);
    window.addEventListener('focus', extensions.addEOL);
    window.addEventListener('view_opened', extensions.checkEOL);

    function addEOL() {
        timerRunning = false;
        var scimoz =ko.views.manager.currentView.scimoz;
        if (scimoz == undefined){
            return;
        }
        
        label.attr('value', eol[scimoz.eOLMode]);
    }

})();
</pre>

**Comment by Xotic750** [comment]
Nice, gives me some more stuff to take a look at. Finding the right tools for the job and the documents is a real pain for a beginner.

**Comment by babobski** [comment]
Yeah i know (im also a beginner), finding the right documentation is some times a real pain tn the ass.
The things i collected so far:
<a href="http://code.activestate.com/recipes/langs/javascript/tags/komodo/" target="_blank">http://code.activestate.com/recipes/langs/javascript/tags/komodo/</a>
<a href="http://docs.activestate.com/komodo/9.2/komodo-js-api.html" target="_blank">http://docs.activestate.com/komodo/9.2/komodo-js-api.html</a>
<a href="http://docs.activestate.com/komodo/9.2/macroapi.html" target="_blank">http://docs.activestate.com/komodo/9.2/macroapi.html</a>
<a href="https://developer.mozilla.org/en-US/Add-ons/SDK" target="_blank">https://developer.mozilla.org/en-US/Add-ons/SDK</a>
<a href="https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/Tutorial" target="_blank">https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/Tutorial</a>
<a href="https://developer.mozilla.org/en-US/Add-ons/Code_snippets" target="_blank">https://developer.mozilla.org/en-US/Add-ons/Code_snippets</a>
<a href="http://www.scintilla.org/ScintillaDoc.html" target="_blank">http://www.scintilla.org/ScintillaDoc.html</a>

**Comment by Xotic750** [comment]
For example, just now we are both using our own lookup tables to get a test value for the eol. But in python code I am seeing things like:
```
import eollib
eollib.eol2eolStr[eollib.scimozEOL2eol[sm.eOLMode]]
```
Can I find the Javascript equivalent? Nope.

**Comment by babobski** [comment]
I don't know if you can get the text value from the eol with javascript, the [scimoz](http://docs.activestate.com/komodo/9.2/macroapi.html#macroapi_scimoz) object corresponds to the current file in your editor. The eOLMode gives back witch eol mode is active  
> eOLMode: The characters that are inserted when the user presses 'Enter': either 'CRLF' (0 - the default on Windows), 'CR' (1) or 'LF' (2 - the default on Linux).

if there are mixed line endings or wrong line endings komodo gives a warning
![snap 2015-10-11 at 16 33 31](https://cloud.githubusercontent.com/assets/3530262/10417272/e378ec70-7035-11e5-8690-988362d3675f.png)

**Comment by Defman21** [comment]
@babobski http://beta.docs.komodoide.com/

**Comment by babobski** [comment]
@Defman21 Thanks :thumbsup:, didn't know the new docs are on the way

**Comment by Naatan** [comment]
I hope you guys will submit this to the Komodo packages section when you're done, don't get me wrong I think it's a great idea, I just don't think it's for everyone. PHPStorm likes to put everything you could possibly ever think of on your screen, we tend to only put the most important stuff on screen, and let you decide for yourself what else is relevant to your workflow.

**Comment by babobski** [comment]
Will do, already ported it to a [addon/widget](https://github.com/babobski/EOL-widget), tested it for 2 days, and is working fine. So a pull request is coming your way.

**Comment by Xotic750** [comment]
Once I'm finished playing, learning and feel happy with what it does then it is all yours. ;)
