### ISSUE TITLE
projects broken in last nightly

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#705]
updated this morning to the latest nightly, but broke the project window completly.
I'm unable to switch to any other project, when i click on a other project nothing happend accept i get a loadiing cursor.
I get these error in my log
<pre>[2015-10-09 07:47:09,331] [ERROR] console-logger: NS_ERROR_FILE_UNRECOGNIZED_PATH: Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsILocalFile.append] (2) in resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:98
Traceback (most recent call last):
  File "resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js", line 98, in 

[2015-10-09 07:47:18,434] [ERROR] console-logger: TypeError: ko.toolbox2.manager is undefined (2) in chrome://komodo/content/project/projectManager.js:930
Traceback (most recent call last):
  File "chrome://komodo/content/project/projectManager.js", line 930, in </pre> and <pre>[2015-10-09 07:49:57,586] [ERROR] open: 
-- EXCEPTION START --
TypeError: ko.toolbox2.manager is undefined
+ stack
    projectManager.prototype.closeProjectEvenIfDirty_SingleProjectView@chrome://komodo/content/project/projectManager.js:234:5
    projectManager.prototype.closeProjectEvenIfDirty@chrome://komodo/content/project/projectManager.js:263:1
    projectManager.prototype.closeProject@chrome://komodo/content/project/projectManager.js:360:12
    project_openProjectFromURL@chrome://komodo/content/project/projectManager.js:1551:18
    open_openURIAtLine@chrome://komodo/content/library/open.js:190:13
    open_openURI@chrome://komodo/content/library/open.js:117:12
    open_recentURI@chrome://komodo/content/library/open.js:150:5
    _doUpdateMRUMenu/<@chrome://komodo/content/library/uilayout.js:1077:21
-- EXCEPTION END --</pre>

**Comment by babobski** [comment]
end of workday, updated komdo edit at work to latest nightly, but same got same issue here

**Comment by cgchoffman** [comment]
This is around the code I touched for the bug where cancelling project close didn't stop a komodo shutdown.  I'll have a look

**Comment by Naatan** [comment]
Guessing that code wasn't used only on shutdown.

**Comment by cgchoffman** [comment]
I"m not actually able to reproduce this in the latest Nightly for Edit or IDE.  @Naatan, did you reproduce?  @babobski, could you try starting Komodo with a fresh profile?http://forum.komodoide.com/t/important-file-locations/489

**Comment by babobski** [comment]
@cgchoffman yust renamed my 9.3 folder, this seems to fix the problem, but i want to test it a litle bit more. For me it's weekend and i'm almost heading for the bar, i will come back on it tomorrow when i tested it thoroughly.

**Comment by cgchoffman** [comment]
Enjoy your weekend!  Have a lager for me would ya?  Some thing I would be interested in is the structure of you tools folder in your evidently broken profile.

**Comment by babobski** [comment]
Thanks, i did :beers:. Got a screenshot from my old tools directory
![snap 2015-10-10 at 12 15 36](https://cloud.githubusercontent.com/assets/3530262/10410672/4f24e87c-6f49-11e5-8ad6-de2157a07274.png)
I conpared the two folders and the only thing changed is that all komodo tools have there async set to false in the new directory. But when i rename my old profile i can't reproduce the same bug i had before.
