### ISSUE TITLE
Global Find & Replace

### ISSUE THREAD

**Issue by ziplizard** [Komodo/KomodoEdit#709]
I've noticed with the new 9.3 that the global search hot keys (on mac) no longer work. They are Cmd + Shift + =. Is there a reason this no longer works? For uses such as myself that are quite used to KE's behavior, removing hot keys like this cause confusion. I see the hot key Cmd + Shift + F still works - thank you. I would expect the sister command to this Cmd + Shift + = would work as well. Is there a way for me to configure this command manually? Your help is appreciated. Thanks.

**Comment by cgchoffman** [comment]
Hi @ziplizard, the default for that keybinding has been font zoom for almost 2 years now.  https://github.com/Komodo/KomodoEdit/blame/master/src/schemes/Mac.p.kkf#L95

This sounds like you may have a config issue maybe?  Did you have a custom keybinding scheme?  

This would have been more appropriate for the forums FYI.  Questions about config or design decisions are meant for discussion until an bug or enhancement/change is settled on then we would open an issue report.  I"m going to close this.  Please do link back to this from a forum post though: http://forum.komodoide.com/

**Comment by ziplizard** [comment]
I have not changed anything in my settings for this and I've used KE for years. Find and replace has always been Cmd + =. The zoom's default setting has always been Cmd + keywheel. Also the Cmd + - will do zoom out. Even now, in KE 9.3 I can do find and replace with Cmd + =. I guess the issue is that once I hold Shift for the alternative method it is no longer "=" it would be "+" at that point. This has always worked for me in the past, and just stopped working with this nightly release. Please direct me on the correct usage to do Find All.

**Comment by Naatan** [comment]
`Cmd+=` still works for me on OSX. Try checking your keybinding preferences for "Find: Replace..."?

**Comment by cgchoffman** [comment]
Same, Cmd + = works (opens find).  Cmd + shift + = is zoom-in.  Cmd + shift + _ is broken though :S...New bug

**Comment by ziplizard** [comment]
So what keys to do Find and Replace All? Used to be Cmd + Shift + =
Cmd + F ... is Find
Cmd + = ... is Replace
Cmd + Shift + F ... is Find All
? ... is Find and Replace All

**Comment by Naatan** [comment]
There is no default keybind for Replace All, you need to set it yourself. Search for "Replace" in your key bindings.

**Comment by cgchoffman** [comment]
See what Help > List Key Bindings says.  You can also look in your preferences.

**Comment by ziplizard** [comment]
Can you give me a little support on how exactly do add my own custom key binding for Cmd + Shift + = to do Find and Replace All? I do realize that once holding Shift the "=" would be a "+", but in my head I've always thought as an equal since that it what is used for Cmd + = to do Find/Replace. Thanks.

**Comment by cgchoffman** [comment]
You're preferences @ziplizard; Preferences > Keybindings.

**Comment by ziplizard** [comment]
I went into Preferences > Key Bindings and have no idea how to add "Cmd" + "Shift" + "+" to do Find and Replace All.

**Comment by Naatan** [comment]
At step 3 you select the input box and hit the keybind you want.

![me_iyqoy5x_e4otcolzywo5aisnqfwy3ko1u9geujf8](https://cloud.githubusercontent.com/assets/278649/10405828/b4988042-6ea9-11e5-8ca2-e2fb8ed369b1.png)

**Comment by ziplizard** [comment]
Thanks, I think I got it working.
