### ISSUE TITLE
Folding region code CSS

### ISSUE THREAD

**Issue by bugayov** [Komodo/KomodoEdit#715]
Do, please, folding region code CSS, as described here:
http://forum.komodoide.com/t/regions-in-css-like-c-regions/2100
Example code:

```
/* #region RegionName \*/
.aaa {
  color: #fff;
}
.bbb {
  color: #fff;
}
/* #endregion RegionName \*/
```

**Comment by mitchell-as** [comment]
Thanks for the suggestion. We'll accept a pull request if you feel so inclined :) See https://github.com/Komodo/KomodoEdit/blob/8865f7249de2715c648b6aebc37b0f00b6466214/src/udl/udl/csslex.udl#L397 for details. Otherwise this will go into our backlog.

**Comment by babobski** [comment]
@mitchell-as would you do someting like this?
I'm new to this type of files, how to tell to ignore case.
<pre>
fold /\/\*\s*#region[^*]+\*\// CSS_OPERATOR +
fold /\/\*\s*#endregion[^*]+\*\// CSS_OPERATOR -
</pre>
and is it posible to make someting, to fold [data images](https://css-tricks.com/data-uris/).

**Comment by mitchell-as** [comment]
Hi @babobski, that looks reasonable.

As for folding data images, If you're talking about replacing them with '...' or something inline, then no that's not possible. You can only fold groups of lines. Now if your image spanned multiple lines, you could fold on the open and close parenthesis.

**Comment by babobski** [comment]
@mitchell-as created an pull request for the css region folding (if it needs some adjustments, let  me now). 

as for the folding of data images, already thought it can't be done with the lexer. But if you don't ask you don't know.

**Comment by Defman21** [comment]
#1057

**Comment by Defman21** [comment]
@Naatan you can close this as well :)

**Comment by bugayov** [comment]
I had hoped that by making changes in phplex.udl file (#1052). But does not work folding. So this is not possible in KomodoEdit?

**Comment by Defman21** [comment]
Oh, excuse me, I thought that this one is about PHP. Didn't read the title. I'll try to implement this for CSS as well.

**Comment by Defman21** [comment]
This is not that easy as for PHP because CSS doesn't provide _COMMENTBLOCK identifier...
