### ISSUE TITLE
Remove styling from Check configuration screen

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#716]
There is a skinning issue with the check configuration screen in help > check configeration.
This window has inline styles (white background and some other stuff), in every skin you will use this window will stay white. i think its better to remove the inline styling from this window, so it will adapt beter with the difrent skins.

**Comment by mitchell-as** [comment]
Thanks for the report. We'll look into this.

**Comment by babobski** [comment]
I'm currently checking out komodo 10, but this bug is still present. But now you can't read what's inside the screen anymore.
![2016-05-15 10_49_00](https://cloud.githubusercontent.com/assets/3530262/15272983/b75ea436-1a8a-11e6-9ef8-1070744c9b74.png)
As you can see there is some inline styling in the [feature control panel](https://github.com/Komodo/KomodoEdit/blob/master/src/chrome/komodo/content/dialogs/featureControlPanel.p.xul#L58) (and on the [vboxes](https://github.com/Komodo/KomodoEdit/blob/master/src/chrome/komodo/content/dialogs/featureControlPanel.p.xul#L74) and [hboxes](https://github.com/Komodo/KomodoEdit/blob/master/src/chrome/komodo/content/dialogs/featureControlPanel.p.xul#L83)).
@Naatan maybe it's an idea to label it as an bug, as in the current state the screen is unreadable.

**Comment by Naatan** [comment]
Thanks @babobski, you're right this is technically a bug.

Unfortunately some of the older parts of Komodo have hard coded styling (never a good idea).
