### ISSUE TITLE
Indentation bugs

### ISSUE THREAD

**Issue by AtmanActive** [Komodo/KomodoEdit#719]
Komodo IDE, version 9.2.1, build 87651, platform win32-x86.
Built on Tue Sep 01 17:19:15 2015.

This brand new bug that plagues 9.2.1 about the indentation and forcing the user to delete 'doc-state.xmlc' is introduced in the routine that needs to save the data from individual file preferences. The problem is that Komodo does not know how to save value of zero anymore.

Background:
In my coding I always use tab character for indentation, never spaces, and I would like Komodo to work that way as well. So far, since version 8 the desired indentation settings for me are:
- 'Allow file contents to override Tab and Indentation settings': OFF
- 'Prefer Tab characters over spaces': ON
- 'Number of spaces per indent': 0
- 'Width of each Tab character': 2

Also, I'm used to set these in Komodo's main Preferences and just forget about it as it was always working as expected, and I would never want to change that on individual file basis.

Until 9.2.1.

Now, suddenly, out of the blue, Komodo just switches to some undesired settings that don't make any sense for me. After reading around about it, I figured that this is caused by individual file indentation prefs having priority over what I set in main program preferences, although my 'Allow file contents to override Tab and Indentation settings' is always OFF. So, a temporary workaround is to delete the file 'doc-state.xmlc', which I done 5 times in last two weeks. Finally I realized that when I go to individual file indentation preferences and set there my desired settings, my 'Number of spaces per indent' does not get saved. I do set 0 there, close the dialog, but as soon as I reopen it, this setting is back to 4 (default I guess). Obviously Komodo 9.2.1 has trouble recognizing and saving number zero as a valid setting.

So, two bugs I see here:
1.) Main program indentation preferences setting 'Allow file contents to override Tab and Indentation settings' does not work at all
2.) Individual file indentation preferences setting 'Number of spaces per indent' can not save a value of zero anymore, always reverting to 4 and messing up my indentation configuration and also corrupting the file 'doc-state.xmlc'.

These bugs were non existent or non noticable before v9.2.1.

**Comment by AtmanActive** [comment]
Oh yeah, this thing pops up once in a while when I try to add or remove indentation:

![komodo_indentation_bug_2](https://cloud.githubusercontent.com/assets/7526717/10451130/91c993f6-719e-11e5-9fc2-8818c5226f3f.png)

**Comment by Naatan** [comment]
We have fixed a ton of indentation bugs in the 9.3 nightly that is currently available, however it is still a nightly and you will experience other bugs. This should all be fixed once 9.3 final is available.
