### ISSUE TITLE
Feature Request: jump to last saved file

### ISSUE THREAD

**Issue by AtmanActive** [Komodo/KomodoEdit#720]
I would like to propose a new addition to already wonderful functions of:
- Go back one location
- Go forward one location
- General: Most Recently Viewed File

which would be: Jump to last saved file

Usually in my workflow I have dozens of files that are open for reference and copy-from jobs, practically making their usage read-only, while there is always one file where I'm working on, which gets saved every once in a while. So, a function like that would help me always jump back to the file I'm pasting to, since that one would always be the last one saved.

Thank you.

**Comment by Naatan** [comment]
I can see the use-case in your workflow, but this does not sound like something that would be useful beyond a your very particular use-case. It could easily be achieved with a macro, I would recommend opening a thread on the forums if you'd like some assistance in figuring out how to write this macro.

**Comment by AtmanActive** [comment]
Komodo developers generously helped me out to realize this functionality with a macro here:

http://forum.komodoide.com/t/jump-to-last-saved-file/
