### ISSUE TITLE
Enhancement: Consider lodash as replacement for underscore or additional contrib?

### ISSUE THREAD

**Issue by Xotic750** [Komodo/KomodoEdit#721]
As title. IMO underscore is great but lodash is better.

**Comment by Naatan** [comment]
To what end would this be? Other than to replace one library with another which is subjectively better? We're not experiencing any issues with underscore to my knowledge.

Note you can easily include lodash yourself for your addon/macro development, you wouldn't really need to depend on us for that.

**Comment by Xotic750** [comment]
It wasn't that there is anything wrong or a problem with underscore, but lodash provides a more consistent API behaviour, more features (like deep clone, and deep merge), more thorough documentation and unit tests, better overall performance and optimizations for large arrays/object iteration, and more flexibility with custom builds and template pre-compilation utilities, lodash is even available in separate module format so that you can require only specific routines. I saw that another contrib had been replaced for similar reasons. e.g. dot.js replaced mustache.js. I would welcome the additional features that it would bring. It was just a thought and observation.

**Comment by Naatan** [comment]
Thanks @Xotic750 :) I'll keep it in mind for when we run into issues with underscore. As it stands we have no issues so replacing it just seems needlessly risky to me.

Note mustache.js was replaced with dot.js for performance reasons, dot.js is muuuch faster.

**Comment by Xotic750** [comment]
That's fair enough, and I wasn't about to argue performance. It was more of a case of that I reached for a tool in underscore that I use in lodash and it wasn't there. Of course I can combine a number of underscore tools, or write it myself or as suggested require lodash. As I said it was just a thought. ;)

**Comment by Naatan** [comment]
Much appreciate :) I'll keep it in mind.
