### ISSUE TITLE
Feature request: jsx support.

### ISSUE THREAD

**Issue by abdelouahabb** [Komodo/KomodoEdit#725]
Hi, can you please make a support for React.js (jsx)

**Comment by Defman21** [comment]
To clarify: he's asking for CodeIntel and jsx association.

**Comment by abdelouahabb** [comment]
@Defman21 yes, this is the hype now :D the new jquery (for dom manipulations) ^_^

**Comment by Naatan** [comment]
Pending internal to explore feasibility.

**Comment by abdelouahabb** [comment]
thank you, i hope it will be available :D

**Comment by mitchell-as** [comment]
There was a series of commits starting at https://github.com/Komodo/KomodoEdit/commit/0750a8c3832795a3fbfafaa447d8267f70e07bc4 that implemented this.

**Comment by abdelouahabb** [comment]
wonderful! thank you!

**Comment by estevancarlos** [comment]
+1

**Comment by rulatir** [comment]
This is only partly implemented. Specifically, syntax error detection is not there at all #1988 .

**Comment by cgchoffman** [comment]
@rulatir please see @mitchell-as's [response](https://github.com/Komodo/KomodoEdit/issues/1988#issuecomment-244094953).  Syntax checking is working correctly.
