### ISSUE TITLE
Add editor context menu for bookmarks

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#727]
Under Go to Definition

 * Bookmarks
   * Go to Quick Bookmark 1 (only show if QBM is set)
   * Go to Quick Bookmark 2 (only show if QBM is set)
   * Go to Quick Bookmark 3 (only show if QBM is set)
   * etc ..
   * ---
   * Place Bookmark
   * Place Quick Bookmark 1
   * Place Quick Bookmark 2
   * Place Quick Bookmark 3
   * Etc

The idea is that the quick bookmark menu entries show what the keybinding is, thereby exposing this functionality. The intend of this menu is to make this functionality discoverable, more so than it is to be actually used that way.

Note that XUL observers should already be able to show the keybindings and disable menuitems for which the command is not enabled (as instructed by the command controller). You could then simply use some CSS to identify these menu items and hide them. You should be able to do this only by writing XUL and CSS.

Let me know if something is not clear or you need help figuring something out.

**Comment by cgchoffman** [comment]
fixed 668b714
