### ISSUE TITLE
Close tab keybinding not working: ctrl + F4

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#728]
On Windows and Linux you can use Ctrl + F4 to close tabs in most programs.  This is no longer working in Komodo.

If you're used to this keybindings then this is a pretty big deal.  It's brutal for me.  It must have just started as I didn't notice it in my local build yesterday...thought I may not have been using the build as much as I thought.

**Comment by Naatan** [comment]
Works fine for me on Linux. I'd check on another windows machine to see if it happens there also before dedicating much time on this.

**Comment by cgchoffman** [comment]
You fixed it....It's back haha
