### ISSUE TITLE
find results: unable to close find results tab

### ISSUE THREAD

**Issue by twhiteman** [Komodo/KomodoEdit#729]
I'm no longer able to close the find results tabs after performing a find in files operation. Clicking on the close tab button does nothing.

Komodo IDE, version 9.3.0, build 87994, platform macosx.
Built on Thu Oct 15 02:34:26 2015.

**Comment by Naatan** [comment]
Your tabbox is likely scrolled, this is fixed in the next nightly. You can work around it for now by scrolling all the way to the left.

**Comment by twhiteman** [comment]
Also - is there a way (preference) to disable the opening of a new tab and re-use an old one?

**Comment by Naatan** [comment]
Not currently, we could add one but probably too late for 9.3 at this point. File a request? If the next 2 days are quiet I can maybe look into it. Would also be ok with a PR ;)
