### ISSUE TITLE
Color scheme behaves different in IDE

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#730]
uploaded my dracula color scheme a few days a ago. Tested it on windows and mac in edit, installed the trail version of IDE yesterday, but my color scheme is showing different then on edit.
<b>edit</b>
![snap 2015-10-15 at 20 51 01](https://cloud.githubusercontent.com/assets/3530262/10534318/186eee26-73d7-11e5-88eb-fd561781da9c.png)

<b>IDE</b>
![snap 2015-10-15 at 20 49 08](https://cloud.githubusercontent.com/assets/3530262/10534326/29de9ecc-73d7-11e5-99a4-94a0b9c76004.png)

**Comment by Defman21** [comment]
Maybe the first screen is a HTML file but the second one is a HTML**5** file?

**Comment by Naatan** [comment]
Or any number of other languages that highlight HTML. @babobski can you verify that both are using the same language and both are the same version of Komodo?

**Comment by babobski** [comment]
yep, its actually the same file, both a php file from the same project ( the language is php). for edit im using 9.3 and someting [2015-10-16 21:22:17,533] [INFO] Startup: Welcome to Komodo Edit 9.3.0 build 16269 (platform win32-x86, running on Windows post2012Server version 6.3.9600) end for IDE its 9.2 [2015-10-16 21:26:33,099] [INFO] Startup: Welcome to Komodo IDE 9.2.1 build 87651 (platform win32-x86, running on Windows post2012Server version 6.3.9600)

**Comment by Defman21** [comment]
Okay, I've reproduced the issue as well using HTML5 file type with the following code:
```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    
</body>
</html>
```
The colors looks exactly as in the header of the issue.
Komodo IDE, version 9.3.0, build 87994, platform linux-x86_64.
Built on Thu Oct 15 02:16:11 2015.
Komodo Edit, version 9.3.0, build 16280, platform linux-x86_64.
Built on Thu Oct 15 08:00:20 2015.

**Comment by mitchell-as** [comment]
Confirmed. Sorry for the delay.

**Comment by babobski** [comment]
np can happen
