### ISSUE TITLE
Tabbing through new find replace dialog isn't intuitive

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#734]
Open find replace dialog
enter your find text
press tab

Expect: to jump to the replace text field
Actual:  You need to hit tab about 5 times to get to the Replace text field.

**Comment by cgchoffman** [comment]
I could take this too.  I don't know how to fix this but I'd like to know.

**Comment by Naatan** [comment]
Should just be a matter of setting the tabindex correctly, ie:

https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/Attribute/tabindex

Note the index numbers do not need to connect I believe, so it's best if you use 10,20,30, etc. so that you don't have to alter them all if you want to add/remove something later on.

**Comment by ssigwart** [comment]
@cgchoffman, do you know if tabbing works anymore?  On MacOS, the only field I can focus on is the search field text.  If I hit tab, it takes me out of the find dialog.  If I add a text `<input>` to the find dialog, I can tab between those, but it seems `<button>`, `<checkbox>`, and `<menupopup>` can't.  However, I am able to manually set the focus via javascript to those elements.

**Comment by cgchoffman** [comment]
@ssigwart , i would not be surprised if Mojave broke this.  It's working on Windows and I can bet it's working on Linux.  I'll double check my Mac.

**Comment by cgchoffman** [comment]
Oh no, nvm.  I'm not on Mojave and it's still broken.  Looks like there is a OSX specific bug here.

**Comment by cgchoffman** [comment]
@ssigwart https://github.com/Komodo/KomodoEdit/issues/3715

**Comment by ssigwart** [comment]
Thanks for checking.  Good to know it's OSX only.  I found a clue which I'll update on the new issue.
