### ISSUE TITLE
Feature request: less, scss and sass variables autocompletion

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#737]
Love the new class and id completion. Thought maybe this is easy to adapt when you edit  less, scss and sass files you get auto completions on your variables.

for less when you type @ a auto completion box with your previous defined vars will be shown.
And for sass or scss files when you type $.

Also it would be nice when you define a color to an variable and you ctrl + hover on the item the right color is shown. (now if i call a var $blue and i ctrl + hover on it the wrong color is shown)

**Comment by mitchell-as** [comment]
Thanks for the suggestion!

**Comment by babobski** [comment]
@mitchell-as just tested it, but is working great :+1:

**Comment by nrigaudiere** [comment]
@mitchell-as Is this also available in Komodo IDE? Can't seem to make it work, thanks!

**Comment by mitchell-as** [comment]
Yes, if it doesn't work for you, please open a separate ticket.
