### ISSUE TITLE
Uncommitted but staged git file causes changetracker warnings

### ISSUE THREAD

**Issue by sfsccn** [Komodo/KomodoEdit#741]
When I add a file to my git repository but do not commit it, I get changetracker warnings in the notifications. This seems to be due to Komodo executing "git show HEAD:./myfile", which results in the git error "fatal: Path 'myfile' exists on disk, but not in 'HEAD'."

Komodo Version: Komodo IDE, version 9.2.1, build 87651, platform linux-x86_64.
Git version: 2.6.1

To reproduce:

* Go to a directory tracked by git
* Create a new file and add it: git add myfile
* Open myfile in komodo
* Go to notifications (or note the popup if enabled)
* Observe notification message:

Scc error Error 128 running '[u'/home/user/data/local/git/run/current/bin/git', 'show', u'HEAD:./test-komodo.txt']' in '/home/user/data/local/git/repos/linux-env/config': fatal: Path 'config/test-komodo.txt' exists on disk, but not in 'HEAD'.

* Note: I found nothing relevant in pystderr.log

**Comment by mitchell-as** [comment]
This appears to have been fixed in master with the SCC overhaul.
