### ISSUE TITLE
Enhancement: JSCS integration?

### ISSUE THREAD

**Issue by Xotic750** [Komodo/KomodoEdit#742]
In the past we had jslint, which has integration into KE. jslint was too harsh for many and jshint became popular due to it's flexibility, jshint has integration into KE. Now most JS linters (not jslint) are pulling out code that enforces code styling and are concentrating on code correctness. (jslint still demands its own styling preference, you will obey! :P ). So we have a new kid on the block that takes over the role of enforcing code styling, in a flexible manner: http://jscs.info/

If possible, I would like to see a similar type of integration that jslint and jshint have been offered. For me, jshint + JSCS if a powerful combination. Thanks for your consideration.

**Comment by mitchell-as** [comment]
Thanks for pointing out yet another linter. Hopefully its output format is similar to existing linters...

**Comment by Xotic750** [comment]
I am using unix reporter, so yes. There are other reporter formats too.
`/home/graham/source_projects/lineEndingsStatusBar/lineEndingsStatusBar.js:351:6: Missing space after line comment`

**Comment by mitchell-as** [comment]
Note to self: This is not trivial. Komodo's JS linter basically is hardwired to accept either JSHint or JSLint. It appears jshint.js is run as a script rather than an external command line program. This may interfere with running JSCS similarly, as JSCS appears to be command-line-only.

**Comment by Xotic750** [comment]
JSCS has a CLI http://jscs.info/overview#cli and it can be used programatically http://jscs.info/overview#programmatic-usage

**Comment by mitchell-as** [comment]
Upon further investigation, this would be more suited as a code formatter (Code > Format > Document using) rather than a linter. It would simply reformat the JS instead of highlighting formatting problems.

**Comment by Naatan** [comment]
It seems it goes both ways, you can use it as a linter and you can use it as a formatter.

**Comment by mitchell-as** [comment]
Closing this since JSCS has merged with ESLint and hit its end-of-life (https://medium.com/@markelog/jscs-end-of-the-line-bc9bf0b3fdb2#.x0o1xqkk9)

**Comment by Xotic750** [comment]
Thanks for that.
