### ISSUE TITLE
Enhancement Highlight object keys as strings

### ISSUE THREAD

**Issue by Xotic750** [Komodo/KomodoEdit#746]
Would it be possible to have KE highlight object keys as strings? Or perhaps that is a bad idea?
![objectkeys](https://cloud.githubusercontent.com/assets/216041/10601470/50620ffa-7712-11e5-8347-a5aea5d2b086.png)
But not computed property keys, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#Computed_property_names
```
var myKey = 'abc';

var myObj = {
  [myKey]: 'xyz'
};
```
Or perhaps some other highlighting for them?

**Comment by mitchell-as** [comment]
@Naatan you know more JavaScript than me; is this a good idea? I think all it would take is a look-behind when ':' is encountered; if an identifier is behind ':', highlight it as a string instead.

**Comment by Xotic750** [comment]
Perhaps as strings is not such a good idea, as type conversion happens on other objects. But just general be able to highlight the property keys so that they stand out would be good.

**Comment by Naatan** [comment]
I think these should be highlighted consistently with how they are accessed, eg. `extensions.enumerable`. I have not seen any editor highlight them differently when they are defined in object. Besides I feel if we were to do this we should do it all for all languages.

Note we do have a pending internal ticket for adding more "vibrancy" to the color schemes, which will implicitly include things like this. That is to say you likely won't get exactly what you are asking for, but you will get more contrasting colors that meet the same criteria (to be able to tell your code apart more easily).

**Comment by Xotic750** [comment]
The contrast is the important part, something that catches the eye so that the brain registers their presence. ;)

**Comment by Naatan** [comment]
Totally agree :) Will likely happen in Komodo 10. Unfortunately not as simple as you might think as codeintel depends on some of this stuff.
