### ISSUE TITLE
Support debugging for latest NodeJS version

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#747]
This is NOT slated for 9.3.1, but I am initially targeting it for 9.3.1 so it's on our roadmap to research it (ie. find out exactly how complex of an issue this is so that we can then target it properly).

**Comment by plevexier** [comment]
It's not part of KomodoEdit, is it?

**Comment by cgchoffman** [comment]
Debugging is not in Komodo Edit for any language.

**Comment by Naatan** [comment]
Note we have IDE bugs on this repo because Github does not allow you to have public bugs for a private repo. And even if it did Github provides no tools to consider multiple repositories for bug tracking.

**Comment by plevexier** [comment]
Gotcha. Thanks guys, looking forward to it!

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoIDE/commit/1ee017098f3a369c846c3422b985b888373b175d

**Comment by mitchell-as** [comment]
Note: due to a NodeJS debugger bug, Komodo users must manually press 'Stop' to stop debugging. NodeJS cannot detect when the process has terminated.

https://github.com/nodejs/node/issues/1788
