### ISSUE TITLE
PHPDoc only recognize first @var, rest is ignored

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#752]
Noticed when there is a PHPDoc only the first declared var is detected, the rest is ignored.
<pre>
/** 
 * @var $test TestForm
 * @var $test2 TestRelation
 * @var $test3 Website
 */
</pre>
Now when typing <code>$test-></code> i get auto completion, when i type <code>$test2-></code> nothing happens. When i switch it to:
<pre>
/** 
 * @var $test2 TestRelation
 * @var $test TestForm
 * @var $test3 Website
 */
</pre>
I get completions for <code>$test2</code>, and not anymore for <ocde>$test</code>

**Comment by mitchell-as** [comment]
Hi, would you please post a full code example. I don't know much PHP and am struggling to reproduce this. Thanks.

**Comment by Defman21** [comment]
```php
<?php

class MySuperObject 
{
    public function foo()
    {
        echo 1;
    }
}

class MyDuperObject
{
    public function bar()
    {
        echo 2;
    }
}

class Foo
{
    /**
     * @var MySuperObject $obj1
     * @var MyDuperObject $obj2
     */
    public static $obj1, $obj2;
}
```
Btw it works fine for me :\

**Comment by Naatan** [comment]
Well then that's not reproduction code? :p

**Comment by Defman21** [comment]
Maybe, but I don't know any other cases where multiple `@vars` could be used in PHPDoc's.

**Comment by Naatan** [comment]
My guess is if you cannot reproduce it easily then the issue @babobski is seeing is likely not in the phpdoc itself, but in the code preceding it.

**Comment by babobski** [comment]
i can split it in a feature request and a bug, if you use the above example from @Defman21, if you type <code>$obj1-></code> you get the auto completion for the function <b>foo</b> if you type <code>$obj2-></code> you get the autocompetion for the function <b>foo</b> and this is incorrect.
![snap 2015-10-21 at 18 46 04](https://cloud.githubusercontent.com/assets/3530262/10643637/2c2a0800-7824-11e5-8415-4507d32d134d.png)

![snap 2015-10-21 at 18 48 45](https://cloud.githubusercontent.com/assets/3530262/10643681/65f1c636-7824-11e5-9abb-49c7560f01ea.png)
If you split it up you get the correct result
![snap 2015-10-21 at 18 52 26](https://cloud.githubusercontent.com/assets/3530262/10643779/fc713f4c-7824-11e5-9d41-84d4c3018f1d.png)

The other bug/feature request is supporting the syntax the other way, this is giving me no auto completions(I'm used to do it like this and if you Google you get mixed results how to correctly do this, like this [example](http://stackoverflow.com/questions/14462390/how-to-declare-the-type-for-local-variables-using-phpdoc-notation)).
![snap 2015-10-21 at 18 59 09](https://cloud.githubusercontent.com/assets/3530262/10643913/d66ffd3c-7825-11e5-84de-d9a3b3ed32ce.png)

The use case is, at work we use the Yii framework. If you use a render or a [renderPartial](http://www.yiiframework.com/doc/api/1.1/CController/#renderPartial-detail) you can send a array with data to the view. if you add a php doc at the head of your view file, the editor knows which classes or models are related to the $var. And you are getting the correct auto completions.

**Comment by Defman21** [comment]
Well, I've missed the wrong auto-complete for `Foo::$obj2`
I'm getting the same result as @babobski.

**Comment by Defman21** [comment]
And just saying....
The correct syntax for `@var` declaration is:
`@var DataType Description`.
So I think PHPDoc just doesn't support multiple variables description in one PHPDoc section. That's why you get auto-completions from `MySuperObject` for both `$obj1` and `$obj2`. This behavior isn't incorrect IMO, that's how it supposed to be. I don't want to see this in Komodo, there are no reasons to implement this because it doesn't follow the PHPDoc standards. But I don't choose what to see/implement in Komodo, the last word always for developers.

**Comment by babobski** [comment]
@Defman21 actually you can add  multiple var statements in one docblock, did a quick Google search and found this [result](stackoverflow.com/questions/26091169/how-to-document-multiple-variable-declarations-in-phpdoc#answer-26392804), in the phpDoc 2 version you can add multiple <code>@var</code> statements as described [here](http://phpdoc.org/docs/latest/references/phpdoc/tags/var.html).

 As for supporting the wrong syntax, as in the example beside the official phpdoc the results are mixed in google and if you are used to a editor that supports the incorrect syntax. It can help with a easy transition to komodo(and you have declared it wrong in your previous projects). But as you say it isn't  for me to choose, and I wouldn't blame the developers for not supporting the wrong syntax, because it is the wrong syntax.

**Comment by Defman21** [comment]
So now I'm totally confused by PHPDoc. Lets leave it to the developers :P

**Comment by mitchell-as** [comment]
Confirmed that multiple `@var` declarations are not handled correctly.

I'm not sure about handling wrong syntax. If it's a simple test of which of the two fields has a '$', then it might be easy to support; I'll need to look into this though.

**Comment by babobski** [comment]
@mitchell-as I'm still having issues with this.

If i grab the code from @Defman21 Its working correct.
If I change the comment from multi line to single line, Its broken again:
```php
<?php

class MySuperObject 
{
    public function foo()
    {
        echo 1;
    }
}

class MyDuperObject
{
    public function bar()
    {
        echo 2;
    }
}

class Foo
{
	/** @var MySuperObject $obj1 */
	/** @var MyDuperObject $obj2 */
    public static $obj1, $obj2;

	
}
```
`$obj1->` will autocomplete with the bar function( incorrect ), also the `$obj2` will autocomplete for the bar function.

A other thing, when I'm using the wrong syntax (First the var and then the value), I will not get any auto-completions:
```php
<?php

class MySuperObject 
{
    public function foo()
    {
        echo 1;
    }
}

class MyDuperObject
{
    public function bar()
    {
        echo 2;
    }
}

class Foo
{
    /**
     * @var $obj1 MySuperObject
     * @var $obj2 MyDuperObject
     */
    public static $obj1, $obj2;
	
	
}
```
Would be nice to support the wrong syntax as most of my colleges are using the wrong syntax.
(They are using phpstorm but phpstorm doesn't care much about the syntax)

**Comment by Defman21** [comment]
Not sure what's the point of having single-line comments that should behave as multi-line, the proper use of single-line comments would be using different lines for definitions, like
```php
...
/** @var Foo $foo */
public $foo;
/** @var Bar $bar */
public $bar;
...
```

Not sure why there should be a parsing support for wrong syntax, it makes code too complicated.
The proper syntax for `@var` is:
`@var [“Type”] [$element_name] [<description>]`

`$element_name` should exist if it's a multi-line comment that describes a one-line multi-var definition (like `public $var1, $var2`), but it could be omitted when you're describing a one-line definition, like `public $var`)

https://phpdoc.org/docs/latest/references/phpdoc/tags/var.html

**Comment by Naatan** [comment]
> Would be nice to support the wrong syntax as most of my colleges are using the wrong syntax.
(They are using phpstorm but phpstorm doesn't care much about the syntax)

I don't really agree with this tbh, it's up to developers to write proper code. Writing bad PHPDoc's should be the developers responsibility. If we are to detect this at all it should be to tell them "you're writing bad code".

**Comment by babobski** [comment]
@Naatan @mitchell-as stated:
> I'm not sure about handling wrong syntax. If it's a simple test of which of the two fields has a '$', then it might be easy to support; I'll need to look into this though.

So I thought if it would be that easy, why won't we.
At first I want to say phpdocs is not good in documenting it self.
Searched some more on the phpdocs, but both syntaxes are valid:
```php
/**  @var $var01 MyModal */ // valid var statement
/**  @var MyModal $var01 */ // Also valid
```
If you look at php docs documentation about the [var statement](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#722-var):
> Another example is to document the variable in a foreach explicitly; many IDEs use this information to help you with auto-completion:

```
/** @var \Sqlite3 $sqlite */
foreach($connections as $sqlite) {
    // there should be no docblock here
    $sqlite->open('/my/database/path');
    <...>
}
```
As you can see the statement is reversed.
Also some editors use the statement reversed for autocompletion as described in this [stackoverflow article](http://stackoverflow.com/questions/14462390/how-to-declare-the-type-for-local-variables-using-phpdoc-notation).
I know phpstorm doesn't care about the order, and it would be nice when you switch to komodo, you get the same autocompletion in you projects.

About using multiple var statements with single line phpDocBlocks. 
This is also valid, to give you a use case, many frameworks use a render partial, where you can render a "template part", in this template part you want to define the variables send to this "render partial". So when you now write you're variables you will get autocompletion on you're variables.
Komodo shouldn't care if it's defined by one Multiline doc block or multiple single line doc blocks as both methods are valid phpDocs.
```php
<?
/** @var MySuperObject $obj1 */
/** @var MyDuperObject $obj2 */
```
```php
<?
/**
* @var MySuperObject $obj1
* @var MyDuperObject $obj2
*/
```
They both should work, as there is nothing wrong with the syntax.

A other issue with php docs is declaring [array's](https://www.phpdoc.org/docs/latest/guides/types.html#arrays).
You can declare arrays by adding [] to your variable like this: 
```
/** @var $settings[] test */
$settings = array();

foreach ($settings as $setting) {
	echo $setting;
}
```
In the foreach you should get autocompltion for test on $setting, but this is not working.
It's only working when I assign the class to the single value.
![2016-06-29 11_51_44](https://cloud.githubusercontent.com/assets/3530262/16448203/7935064e-3df0-11e6-854e-5c6b0e0ce2c7.jpg)

**Comment by Defman21** [comment]
>Searched some more on the phpdocs, but both syntaxes are valid:

Technically, everything inside comments is valid. But according to PHP coding standards, only `@var <class> <description>` should be parsed by IDEs. If PHPStorm is positioning itself as an PHP IDE, why don't it follow the code styling guidelines and especially PSR standards? They are doing something wrong I don't see any reasons to do the same in Komodo.

> A other issue with php docs is declaring array's.
You can declare arrays by adding [] to your variable like this: 

According to this code:
```
/** @var \Sqlite3 $sqlite */
foreach($connections as $sqlite) {
    // there should be no docblock here
    $sqlite->open('/my/database/path');
    <...>
}
```

I assume you can get the auto-completions for `$setting` only if you write the phpdoc **before** foreach statement. `/** @var <class> <description> */` should describe a variable on the next line, it has nothing to do with the variable name itself (`<description>` is an optional item and can be omitted as well as it can just describe the variable).

Seems like you're completely messed up everything about PHPDocs in your head. I could agree that Komodo could be a bit smarter about PHPDocs, but supporting the phpdocs that does not follow PSR standards is a bit useless.

**Comment by Defman21** [comment]
Also you should open a new ticket instead of replying to the old one. It has been fixed and it won't be re-opened because you're talking about different things (also in one post :P)

**Comment by tonyattwood** [comment]
Hi,

I wanted  to thank you a  lot for all  you've done, it  was a real help. Please read my  whole message here <http://excellent.baseil.com/e4eqlnq>

Yours, tony.attwood@ntlworld.com

**Comment by mitchell-as** [comment]
@babobski Sorry for taking so long to get back to you on this (lost in my Inbox).

Re: changing from multiline comment to single line comment breaks type recognition: it looks like our parser only looks at a doc comment immediately in front of a variable declaration. For consecutive comments, only the last is considered. Feel free to file a bug for this.

Re: supporting swapped variable-type PHP docs ala another product: feel free to file an enhancement request.
