### ISSUE TITLE
Cleaning line endings/removing trailing whitespace deletes bookmarks.

### ISSUE THREAD

**Issue by furnox** [Komodo/KomodoEdit#754]
When performing a *Clean Line Endings* or a *Remove Trailing Whitespace* operation on a buffer, any bookmarks in the buffer are deleted.

When performing one of these operations on a selection of lines that includes one or more bookmarks, the bookmarks are removed but a new one now appears *after* the selection.

To reproduce:

1. select an entire buffer or a collection of lines that includes one or more bookmarks
2. perform a *Clean Line Endings* or *Remove Trailing Whitespace* operation
   * the selection must include trailing whitespace for the *Remove Trailing Whitespace* operation to do anything.

**Comment by cgchoffman** [comment]
Thanks for filing this @furnox.  Next time please attach the forum post in as a reference. http://forum.komodoide.com/t/cleaning-whitespace-line-endings-removes-bookmarks/2160/4

**Comment by furnox** [comment]
Thanks Mitchell!
