### ISSUE TITLE
Error jumping to non-existant quick bookmark

### ISSUE THREAD

**Issue by mitchell-as** [Komodo/KomodoEdit#755]
I don't know how to use quick bookmarks so I just pressed Ctrl+1 to see what would happen. The following error occurred:

[2015-10-22 15:03:37,439] [ERROR] commands: An error occurred executing the cmd_goToQuickBookmark_1 command
-- EXCEPTION START --
[Exception... "[JavaScript Error: "docState is not defined" {file: "chrome://komodo/content/editor.js" line: 189}]'[JavaScript Error: "docState is not defined" {file: "chrome://komodo/content/editor.js" line: 189}]' when calling method: [nsIController::doCommand]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 263"  data: yes]
+ QueryInterface (function) 3 lines
+ message (string) '[JavaScript Error: "docState is not defined" {file: "chrome://komodo/content/editor.js" line: 189}]''...248 chars
+ result (number) 2153185313
+ name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
+ filename (string) 'chrome://komodo/content/library/commands.js'
+ lineNumber (number) 263
+ columnNumber (number) 0
+ location (object) JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 263
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/library/commands.js'
| + name (string) 'command_doCommand'
| + lineNumber (number) 263
| + columnNumber (number) 0
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/library/commands.js :: command_doCommandAsync :: line 215
| + formattedStack (string) 'command_doCommand@chrome://komodo/content/library/commands.js:263:0
command_doCommandAsync@chrome://'...476 chars
| + inner (object) null
| + data (object) [xpconnect wrapped nsISupports]
| + QueryInterface (function) 3 lines
| + initialize (function) 3 lines
-- EXCEPTION END --
[2015-10-22 15:03:37,443] [ERROR] keybindings: 
-- EXCEPTION START --
2147500037
+ 0 (number) 2147500037
-- EXCEPTION END --
[2015-10-22 15:03:37,447] [ERROR] console-logger: ReferenceError: docState is not defined (2) in chrome://komodo/content/editor.js:189
Traceback (most recent call last):
  File "chrome://komodo/content/editor.js", line 189, in

**Comment by mitchell-as** [comment]
Oh, I should mention that this is in KomodoEdit, not IDE (though IDE might be affected too).

**Comment by cgchoffman** [comment]
Ahhh that explains why the line numbers didn't make sense.
