### ISSUE TITLE
Console: scrolling: scrolling fails if input is more than 1 line.

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#757]

**Comment by Naatan** [comment]
I cannot reproduce this, can you provide more details?

**Comment by cgchoffman** [comment]
Ya sorry...was in a rush.  we're on the 26th floor :P.  You have to fill the screen so it has started scrolling.  Then just enter some input that is more than one line and it will not scroll anymore after that has been executed.
