### ISSUE TITLE
markdown preview button not showing

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#759]
Updated this morning to the latest nightly, but when editing markdown files, the markdown preview button is not showing up. when i look in my error log, i see nothing related to the markdown preview function.

**Comment by Naatan** [comment]
I'm unable to reproduce this. Did you check if the button was unabled under toolbar customization?

**Comment by babobski** [comment]
updated at home, to the latest nightly but not having this problem at home. Where can you find the toolbar customization? do you mean this menu?
![snap 2015-10-24 at 08 58 33](https://cloud.githubusercontent.com/assets/3530262/10709411/863cede8-7a2d-11e5-878c-1ad604f6053e.png)

**Comment by Naatan** [comment]
Hit the Customize button there.

**Comment by babobski** [comment]
hmm, think i'm going crazy, got the markdown preview working true the menu `view > markdown preview` (and not the preview button). but here at home that function is missing in my menu (but here i have a preview button). 
Forgot to hit the Customize button, so i will do that tomorrow.

**Comment by babobski** [comment]
Oke found out what's  the problem, add home i installed the markdown addon when it was released, and at work i didn't install it. That's why i had at home the old preview button and didn't find the relocated preview button (next to the browser preview) at work. When i removed the addon both my work and home versions are identical.

**Comment by Naatan** [comment]
Ahh I see, thanks for updating us :) We should probably show some sort of warning for those types of addons.
