### ISSUE TITLE
Images of New Toolbar Buttons Difficult to See

### ISSUE THREAD

**Issue by mitchell-as** [Komodo/KomodoEdit#762]
This is the default color scheme on Ubuntu with a clean profile. The icons for "Run-inline" and "Show Documentation" are not very visible. I completely missed them until I saw them while testing in Mac OSX.

![toolbar](https://cloud.githubusercontent.com/assets/12902397/10705086/5438c120-79a9-11e5-91eb-c623be34ffbe.png)

**Comment by mitchell-as** [comment]
And yes, they are enabled because I can click on them and they do something.

**Comment by Naatan** [comment]
Nice catch!
