### ISSUE TITLE
Trouble shooting and Report Bug buttons are alligned

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#764]
<img width="396" alt="screen shot 2015-10-23 at 2 23 44 pm" src="https://cloud.githubusercontent.com/assets/655154/10705300/bd6102d8-7991-11e5-8cab-ecc944c748d4.png">

See image.  This is on OSX retina.  I didn't notice this on Windows.

**Comment by Naatan** [comment]
This has been fixed, I guess you are testing on yesterdays nightly?

**Comment by Naatan** [comment]
Just tested again, this was fixed here: https://github.com/Komodo/KomodoEdit/commit/6bb1922c67cf178a3c41a6e0945a302dcf931a99

**Comment by cgchoffman** [comment]
Not seeing in my build so ya looks like an old nightly
