### ISSUE TITLE
Bad auto-completions for Closure in PHP

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#767]
Komodo shows me only `bind` and `__construct` methods via `->`, but `bind` is a static method and it shouldn't be visible via `->` and there are no `call` and `bindTo` functions.
Class hierarchy:
https://secure.php.net/manual/en/class.closure.php#closure.synopsis

**Comment by mitchell-as** [comment]
Looks like our CIX generator is not parsing PHP documentation correctly.

**Comment by mitchell-as** [comment]
After looking into this, the PHP documentation referenced in the original post is for PHP 7. Komodo's PHP 7 documentation has at least the `call` method now. Looking at PHP's closure code (https://github.com/php/php-src/blob/master/Zend/zend_closures.c), documentation is either very poor or non-existant. `bindTo` is a C alias and there's no way we can pick that up.

Until PHP's documentation improves, we cannot pick this up via our gencix scripts. Sorry :(

**Comment by Defman21** [comment]
I thought that you're parsing PHP docs.

https://secure.php.net/manual/en/closure.bind.php
https://secure.php.net/manual/en/closure.bindto.php

**Comment by mitchell-as** [comment]
Perhaps I thought so to, but we don't. Parsing HTML is really quite a nightmare. It's easier to parse structured comments in code.

**Comment by Defman21** [comment]
Yeah I agree with that :) I'm pissed off because the online documentation is more like documentation rather than comments in the code.
