### ISSUE TITLE
Cannot Drag-n-drop a file

### ISSUE THREAD

**Issue by caolandix** [Komodo/KomodoEdit#77]
If there is no file already loaded into the IDE, I cannot drag-n-drop a file onto the IDE to open it up. I am running on MacOS.

**Comment by srgloureiro** [comment]
I confirm this on Windows.

**Comment by cgchoffman** [comment]
I can not reproduce this on Windows.  Please attache (in a gist or code section) your logs after reproducing the issue.

**Comment by caolandix** [comment]
I am seeing this on Linux not Windows.

Caolan Dix
Release Engineer
cdix@fulcrum.net
206.491.2613

**Comment by srgloureiro** [comment]
It is not happening to me now. Perhaps it was the failure of the left-click I reported today causing this?

**Comment by geary** [comment]
I didn't test on Windows or Linux, but I can confirm that it consistently fails for me on OSX. Worked fine in Komodo 8.x.

**Comment by Naatan** [comment]
The event handler for dropping files is on the scintilla binding, when no file is open the file is dropped on the quick launch view which does not handle this event.
