### ISSUE TITLE
adding a new tab on markdown preview browser, replaces markdown preview

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#770]
Just noticed when i have a markdown preview browser open, and hit the new tab icon(<b>+</b>), the start screen replaces the markdown preview. After you done that there is no ability to close the preview/splitted view, because the start screen don't have a closing button.
To close it you will have to drag an drop something on the start screen so you can close it.

Tested it on preview in browser but here it's working fine, and the extra tab is added.

**Comment by cgchoffman** [comment]
As a work around you can still close the New Tab from Open Files.  Nice find @babobski.
