### ISSUE TITLE
Can't call "Refresh View" on root folder at "Source" tab

### ISSUE THREAD

**Issue by proowl** [Komodo/KomodoEdit#771]
Clicking "Refresh View" under ther source tree list has no affect.

**Comment by cgchoffman** [comment]
I know that this is definitely not 100% reproducible for everybody so please provide more details about your setup.  Are remote drives involved at or source code control tools involved?

**Comment by proowl** [comment]
Well, it is 100% reproducible when using komodo with folder mounted using sshfs.
Actions to reproduce: mount folder, make it root in komodo source view tab, make some changes in folder on remote host, try refresh view.

**Comment by cgchoffman** [comment]
Those would be the added details I was looking for.  Thanks @proowl.

**Comment by Naatan** [comment]
Fixed in 10
