### ISSUE TITLE
Disabling toolbar blocks 'Alt' from showing menu.

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#778]
View > Toolbars > disable toolbar
Press `alt` to show Menu bar

Nothing happens.

Haven't tried Linux yet.

Komodo IDE, version 9.3.0, build 88116, platform win32-x86.
Built on Wed Oct 28 17:11:02 2015.

**Comment by Naatan** [comment]
Happens on Linux too. I'm guessing hiding the toolbar also hides the parent element for the menu bar.

**Comment by samtajoshi20** [comment]
Press Alt Key for a couple of seconds, Menu bar will appear. Right click the menu bar and check Show Toolbar. Toolbar will appear.

**Comment by cgchoffman** [comment]
> Press Alt Key for a couple of seconds,

This doesn't appear to be necessary.  At some point this got fixed.
