### ISSUE TITLE
Inconsistent/incorrect icons on Project > Add... context menu

### ISSUE THREAD

**Issue by we3geeks** [Komodo/KomodoEdit#78]
The icons for the "Existing Remote File..." and "Existing Remote Folder..." entries on the Project > Add... context menu appear to be both incorrect (at least to me, the file and folder aspects of those menu entries seem swapped?) and inconsistent with the other icons on that same context menu.

![ke9-20150326-3](https://cloud.githubusercontent.com/assets/2390335/6856257/6306fd7e-d3c4-11e4-944f-a3aec3f28166.png)

**Comment by Defman21** [comment]
Sorry for offtop but what color scheme you use in this screen?

**Comment by we3geeks** [comment]
It is my own customized version of Solarized Dark (I call it Solaron-Dark, and I have a complementary Solaron-Light). The color palette stays true to the "real" Solarized palette in almost every aspect (but there are a couple places I have intentionally differed for either greater or lesser contrast -- e.g., choosing a color that is the mathematical midpoint between two greys within the Solarized palette -- and based on differences between how Komodo seems to render colors vs TextMate, Sublime, Atom, etc.). I've done a fair amount of tuning within the scheme to tie colors for consistency across syntaxes for languages and filetypes I typically work in and based on my own preferences and habits.

**Comment by Defman21** [comment]
Can you share it somewhere?

**Comment by we3geeks** [comment]
Similar Windows-y icon used here (inconsistent with other similar icons on OS X version of Komodo):

![ke9-20150327-3](https://cloud.githubusercontent.com/assets/2390335/6869696/afec2df2-d45b-11e4-8369-26473b33d30f.png)

**Comment by Defman21** [comment]
This could be closed in favor of #1437
