### ISSUE TITLE
Komodo Edit unstable after upgrade to Mac OS El Capitan

### ISSUE THREAD

**Issue by BernardA** [Komodo/KomodoEdit#785]
Hello

Komodo has become unresponsive at times and I have to force quit it.

I have not observed special circumstances that may provoke that to happen.

Regards
Bernard

**Comment by cgchoffman** [comment]
There isn't really anything we can do here without more information.  Could you try and narrow it down some?  I'm using El Capitan on a daily bases and haven't experienced any issues with Komodo.  Are you working on remote files?

**Comment by BernardA** [comment]
Thanks for your reply. Unfortunately, as said, I do not have much to add. It just stalls. I am working with local files only. 
I will let you know if I learn something more specific about it if it happens again.
Regards
Bernard

**Comment by cgchoffman** [comment]
Unfortunately this isn't actionable for us.  Please open a forum post http://forum.komodoide.com/.  We diagnose and troubleshoot in forums until we have determined there is a reproducible bug in Komodo and not a config issue.  Closing this report.
