### ISSUE TITLE
Prefs > Show all options is basically hidden away

### ISSUE THREAD

**Issue by robclancy** [Komodo/KomodoEdit#788]
When I went to change a file association I got confused and had to ask how to do it. Turns out I needed more options but I never noticed it at all.

Suggestion: instead of a checkbox just have an extra menu item that says advanced items.

**Comment by Naatan** [comment]
I actually made it more apparent already in 9.3, but I guess it wasn't enough. Your suggestion is an interesting approach, will try.

**Comment by robclancy** [comment]
It's actually fairly clear when the window is small, but I was using it full screen due to i3.

**Comment by Defman21** [comment]
There are no more "Show all options" anymore.

**Comment by Naatan** [comment]
Good point.
