### ISSUE TITLE
Komodo Edit 9.0, Find dialog loads incorrectly

### ISSUE THREAD

**Issue by dobosgy** [Komodo/KomodoEdit#79]
Pressing Ctrl-H the replace window appears, but the *Replace All* button is missing, so I have to replace all words one by one.

![screenshot](https://cloud.githubusercontent.com/assets/1547089/6857549/bcef4e84-d407-11e4-9b19-5681d357a510.png)

Komodo Edit, version 9.0.0, build 15707, platform linux-x86_64. Built on Thu Mar 19 06:35:26 2015.

**Comment by cgchoffman** [comment]
Odd, could you try disable/enable "replace"?  Just spinning up a Linux machine to see if it's occurring there.  Can't repro on Windows.

**Comment by cgchoffman** [comment]
I'm not seeing this on LInux either.  Could you open Help > List Key bindings and confirm that ctrl + h is indeed mapped to Replace...?

**Comment by Naatan** [comment]
Did you try Komodo Edit @cgchoffman ?

**Comment by dobosgy** [comment]
@cgchoffman you are right, after disable/enable "replace" checkbox, the Replace All button appears. Maybe this is not the expected behavior of "replacing all" although. :)

![screenshot2](https://cloud.githubusercontent.com/assets/1547089/6858789/148865d6-d412-11e4-9e07-bae64d9cda18.png)

**Comment by cgchoffman** [comment]
Ya just reproduced on Windows.  Thanks you dodosgy.

**Comment by cgchoffman** [comment]
A report of an issue that I think this bug covers:  https://bugs.activestate.com/show_bug.cgi?id=106464

**Comment by harpreetsb** [comment]
This is on Ubuntu as well. not just windows.

**Comment by hobbsd** [comment]
This Find Dialog bug may be related: Ctrl-shift-f to open, switch to search in Current document, switch to Files, and the dialog size has made the buttons inaccessible.

![screen-2015-04-02_13-22](https://cloud.githubusercontent.com/assets/1676348/6969357/0ceb0692-d93c-11e4-9458-7e0e9a886909.png)

There are other combinations of actions on the Find dialog that have the same effect.
This is on Win7.

**Comment by Naatan** [comment]
I think we may have missed a commit integration here.

**Comment by cgchoffman** [comment]
This has been integrated into the nightly 9.0.1 branch as well as you can see so a fix for this can be downloaded tomorrow (April 7 2015, lunch time) when we push a new nightly build: http://downloads.activestate.com/Komodo/nightly/komodoedit/

**Comment by srgloureiro** [comment]
Just got bitten by this bug. And as it is a so essential feature, it justifies a new version due solely to this glitch,

**Comment by cgchoffman** [comment]
@srgloureiro that new version would be 9.0.1 which will be coming in the relatively near future.  For now you can use the nightly.
