### ISSUE TITLE
Error: Failed to start codeintel

### ISSUE THREAD

**Issue by athensy** [Komodo/KomodoEdit#793]
When I first start Komodo edit version 9.2.1, I get the following error message:
---------------------------------------------------------------------------
[Error 6] The handle is invalid.

Komodo Edit, version 9.2.1, build 15998.
Built on Wed Sep 02 02:48:28 2015.
---------------------------------------------------------------------------

Remarks:
1. Operating system it ran is MS Windows 2003 Server x64 (SP2).
2. It is a virtual machine run on a VMware ESXi 5.5 virtual host.
3. Hardware configuration: 
    - CPU: Intel Xeon E3-1270
    - RAM: 4GB

**Comment by Naatan** [comment]
You are running an unsupported OS, Komodo requires at least Windows 7 to run.
