### ISSUE TITLE
Include/Exclude field for in-project find dialog

### ISSUE THREAD

**Issue by jsnjack** [Komodo/KomodoEdit#795]
Currently we have only include field. It would be nice to have exclude field also

Dev edit:

Added want for "Include" support as well. This doesn't work with Projects.

**Comment by Naatan** [comment]
It excludes what you have configured in your project preferences, are you saying you'd like something to override that on a per-search basis?

**Comment by jsnjack** [comment]
@Naatan yes. However, not like override, but extend. For example, I search for "body" in my project and I expect it to be not in html document. I think it is more logical to exclude *.html rather then think what to include (*.py, *.js and etc)

**Comment by Naatan** [comment]
We could just default to the project exclude, then you get to decide whether to override or extend simply by preserving the input or not. Thanks for explaining :)
