### ISSUE TITLE
Update default JS syntax checker to JSHINT with es6 support enabled

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#797]
The Mozilla one is dated and does not address common use-cases of modern Javascript, we can still include it but the default should support the newest technologies and jshint is good at that.

Note we currently do not package jshint, so we need to start doing that.

Atm jshint 2.6.0 is the latest version that works, later versions are broken due to https://github.com/lodash/lodash/issues/1493

**Comment by Naatan** [comment]
Fwiw these are the jshint settings I use: `moz=true unused=true esnext=true`

**Comment by Defman21** [comment]
@Naatan https://github.com/Komodo/KomodoEdit/commit/536f1e63aaf819b8b9c7e4ff62568be1456c68fc isn't the fix?

**Comment by mitchell-as** [comment]
It looks like half the fix. It looks like I still need to enable those settings by default.

**Comment by Naatan** [comment]
But only for HTML5, not HTML. 

As a side-note, we should probably rename those to HTML and HTML4, because HTML5 is the standard now.

**Comment by surfyogi** [comment]
Just to point out from the trenches of Google, I was over there last week and they made some announcements:

ES6 will be called ES2015
ES7 will be called ES2016
ES6 is supported by NodeJS now
Most browsers support most ES2015 features now

Fact is PHP, Java, some .NET, and Ruby to some extent are being eaten alive by NodeJS for server farms. It's 10x less load on servers, and less salaries ($) to manage it. Ebay, Walmart, IBM, Paypal, everybody is moving to it...

Which means I hope, that you will be giving JS support a lot more attention going forward, as it's taking over the landscape here quickly. Easily the most popular language now.

I don't want to have to hack my IDE so it will support ES2015...

**Comment by Naatan** [comment]
Thanks for the additional info! :)

> I don't want to have to hack my IDE so it will support ES2015..

Of course not, that's what this ticket is all about. JavaScript and everything that it entails will be a primary focus of Komodo 10.

**Comment by surfyogi** [comment]
Good to hear, I was about to purchase 9... 
Free upgrades?

**Comment by surfyogi** [comment]
OH yes, and the other announcement:

ES spec will have a new release yearly now, so that specs do take 4 years to write and approve.
Things are really speeding up.. so if a feature doesn't make it 2016, it will be in 2017, but there 
is still a new spec without fail.

**Comment by Naatan** [comment]
> Free upgrades?

Komodo 10 is still a ways off, too early to say anything about upgrades or pricing. So likely if you buy Komodo 9 now you would have to pay to upgrade to 10.

> ES spec will have a new release yearly now, so that specs do take 4 years to write and approve.

We'll definitely keep our eye on those. For now the primary focus is on ES6 / ES2015, as that is the most widely used at the current time. Which is not to say we aren't also looking into ES7 / ES2016.

**Comment by tonyattwood** [comment]
Hi,


There  are a couple  of books that inspire me to do really great  things, here is the list of that  books <http://explore.sportbros.com/e4wvhpoc>

Warmest, tony.attwood@ntlworld.com

**Comment by tonyattwood** [comment]
Hey,


I've  met  such  a cool couple recently and wanted to share  some of their  thoughts  with  you,  they are really interesting  and so unusual, here is the link  <http://explore.marioalv.com/e4hjfmct>


In haste, tony.attwood@ntlworld.com
