### ISSUE TITLE
Komodo Installer Issues False "gdk-2.0 not detected" Warning

### ISSUE THREAD

**Issue by mitchell-as** [Komodo/KomodoEdit#799]
In some cases Komodo's installer will issue a false (and scary looking) "gdk-2.0 not detected" warning when GDK 2.0 is in fact installed on the system. If Komodo has run on the system before, GDK 2.0 is installed the warning can be ignored.

**Comment by jsnjack** [comment]
I made this warning disappear by installing gtk2-devel on fedora 22
