### ISSUE TITLE
Go To Anything menu item check state is backwards

### ISSUE THREAD

**Issue by 1ec5** [Komodo/KomodoEdit#80]
The View ‣ Toolbars ‣ Go To Anything menu item is checked when the Go To Anything field is hidden and unchecked when the field is shown. It should be the other way around.

Komodo Edit, version 9.0.0, build 15707, platform macosx.
Built on Thu Mar 19 06:08:01 2015.

**Comment by cgchoffman** [comment]
Confirmed in IDE in a fresh profile.  Cycling the setting fixes it for me, eg. enable -  disable.

**Comment by Naatan** [comment]
Closing this in favour of #94, thanks carey.
