### ISSUE TITLE
Toggle quick bookmark 2 doesn't work on OSX

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#802]
That is, the keybinding does not work (Ctrl+Shift+2). We already spoke about this on Slack, just logging it so we can track it.

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoEdit/commit/de5c4739e51f29255d4199f8f2cec0886da53c66
https://github.com/Komodo/KomodoIDE/commit/c02e84dc4f89a14ce54c901f2d9080384475015e
It's been merged into 9.3.x on both as well so it'll be in the nightly.
