### ISSUE TITLE
Recent files not populated (9.3)

### ISSUE THREAD

**Issue by eco747** [Komodo/KomodoEdit#806]
Recent files menu is not populated on windows 10.
Closed tabs is populated with multiple times the same file if you open or close the same file (with Ctrl+W)

**Comment by Naatan** [comment]
Works fine for me on Windows. What are your reproduction steps?

**Comment by eco747** [comment]
Hello,
thanks for your fast response.



for the closed tabs:
-------------------------

[image: Images intégrées 2]

as you can see, my file main.php appear a lot of times.
i do nothing but open a file & close it



for the recent files:
--------------------------


I swear i opened more than 50 files today :)

[image: Images intégrées 1]

Just start Komodo, open some files, close them, and open this menu.
I do nothing special.




2015-11-05 17:09 GMT+01:00 Nathan Rijksen <notifications@github.com>:

**Comment by Naatan** [comment]
Please respond using github, we cannot see the images you attached in an email.

**Comment by eco747** [comment]
![im1](https://cloud.githubusercontent.com/assets/2598404/10976982/dc7fe55a-83ee-11e5-83d7-94d9c8272c57.png)
![im2](https://cloud.githubusercontent.com/assets/2598404/10976984/deea63c4-83ee-11e5-94be-9e95a4a9709b.png)

**Comment by Naatan** [comment]
Have you used previous versions of Komodo? Did it work with those?

**Comment by eco747** [comment]
To install 9.3 version i have to remove my old version (by the way it's not fun)
So i cannot tell you exactly. But I think that i should have seen it.

**Comment by Naatan** [comment]
Can you try this:

Open a new tab (File > New > New Tab), then from Troubleshooting hit Reset UI Setup and Reset Caches.

**Comment by eco747** [comment]
Well i found how to reproduce:
the file must be opened by a double click on the places tab (i think it's the name)
<img width="176" alt="im3" src="https://cloud.githubusercontent.com/assets/2598404/10977195/faf64938-83ef-11e5-9a66-d674c5d8a28b.png">

**Comment by Naatan** [comment]
Please provide more details, are you saying the method you used to open the file affects whether it is stored in recently opened files? Can you say what methods do and do not work?

**Comment by eco747** [comment]
No, in fact recent files is only populated for me if i restart in safe mode...

**Comment by Naatan** [comment]
What is your "Number of files" set to under Prefs > Appearance > Most Recently Used?

**Comment by Naatan** [comment]
Note you need to have "Show All Settings" enabled at the bottom left of the pref window.

**Comment by eco747** [comment]
Haha, well done !

2015-11-05 19:56 GMT+01:00 Nathan Rijksen <notifications@github.com>:
