### ISSUE TITLE
Cannot remove breakpoint by clicking on the red dot in some conditions

### ISSUE THREAD

**Issue by rocker19943** [Komodo/KomodoEdit#807]
Hi,

I've started using Komodo since 8.3 and this bug is still not fixed eventhought version 9.3 is out
When I set a breakpoint on N line, then remove that line completly the breakpoint does not disappear itself and it's not removable anymore, it can be removed only from "Breakpoints" but the RED dot still remains, it can be removed by clicking on "Delete all breakpoints".

Clicking on the RED dot to deactivate breakpoint, creates a new one for N-1 line instead.
This must be finally fixed!

See the screenshots...

![Normal Breakpoint](https://cloud.githubusercontent.com/assets/12564383/10966121/e2f8ae36-83ca-11e5-93d2-13433ecf3a23.PNG)
![Removed the line](https://cloud.githubusercontent.com/assets/12564383/10966122/e2f96272-83ca-11e5-8ec2-26b3ccb98c98.PNG)
![Removed Breakpoint from the list](https://cloud.githubusercontent.com/assets/12564383/10966120/e2f7b634-83ca-11e5-83e0-61654a461227.PNG)
![Clicked on a breakpoint to remove it but new one was created instead](https://cloud.githubusercontent.com/assets/12564383/10966123/e2fc275a-83ca-11e5-877e-07b9c2d2cfd1.PNG)

**Comment by mitchell-as** [comment]
Thanks for taking the time to report this. Related to #256

**Comment by Naatan** [comment]
@mitchell-as isn't this more then just related, seems like the exact same issue to me?

**Comment by mitchell-as** [comment]
They do not seem like the *exact same* issue to me. They may be similar, and may have the same underlying cause, but description-wise they are separate.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoIDE/commit/32b25c7b9153281dfbc3090fbd28375edff8c693

**Comment by tonyattwood** [comment]
Hey,

We have  recently visited a  great place in town, have you already been there? Here are  some pics of it <http://effort.soldoutshowz.com/e4ctqz>

Thx, tony.attwood@ntlworld.com
