### ISSUE TITLE
Toolbar Icons not displayed correctly (Adwaita Theme)

### ISSUE THREAD

**Issue by ziermmar** [Komodo/KomodoEdit#808]
Show/Hide (Left|Bottom|Right) Pane Icons are not displayed when using the adwaita theme.
Komodo IDE 9.2 / 9.3 on gnome 3.18.

(Default Theme, icons diplayed properly)
![default_theme](https://cloud.githubusercontent.com/assets/1862674/10966288/e19bba0a-83b2-11e5-8fe4-3c42d19de35c.png)

(Adwaita Theme, white boxes instead of icons)
![adwaita_theme](https://cloud.githubusercontent.com/assets/1862674/10966295/eee446be-83b2-11e5-89f1-f41471ae9eeb.png)

**Comment by Naatan** [comment]
Very peculiar, thanks for reporting!
