### ISSUE TITLE
Context menu icons go invisible for selected menu entry

### ISSUE THREAD

**Issue by we3geeks** [Komodo/KomodoEdit#81]
The icons on context menus become invisible when the corresponding menu entry is the currently highlighted menu entry (i.e., they become dark-on-dark). The icon coloring should follow the coloring of the menu entry itself, which goes from being dark-on-light to light-on-dark as it becomes the currently highlighted menu entry. See examples, below, from various context menus:

![screen_shot_2015-03-27_at_9_02_57_am__3_](https://cloud.githubusercontent.com/assets/2390335/6870428/9069e428-d461-11e4-8704-f816401892e5.png)

![screen_shot_2015-03-27_at_9_05_33_am__3_](https://cloud.githubusercontent.com/assets/2390335/6870438/a540bab6-d461-11e4-983b-34bc60b03335.png)

![screen_shot_2015-03-27_at_9_07_16_am__3_](https://cloud.githubusercontent.com/assets/2390335/6870442/aea63cf2-d461-11e4-9e5d-7aa0465d5bb1.png)

This is similar to https://bugs.activestate.com/show_bug.cgi?id=106312 but in a very different context.

Komodo IDE, version 9.0.0, build 87165, platform macosx.
Built on Wed Mar 18 21:57:11 2015.
Using "Default" skin and "IcoMoon - Yosemite" icon set.

**Comment by cgchoffman** [comment]
Possibly use [css filter](https://developer.mozilla.org/en-US/docs/Web/CSS/filter) on hover for the icon.

**Comment by Defman21** [comment]
There are no more icons in context menus.

**Comment by cgchoffman** [comment]
WEll that would resolve this issue for sure!
