### ISSUE TITLE
Disable Auto-Abbreviations in all but regular editing mode

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#811]
Ie. disable when:

 * Scintilla has multiple selections
 * You are recording a macro
 * ...

Those are the only 2 use-cases I can currently think of (ones I ran into), but there are probably more. Let's start with those 2 though.

**Comment by cgchoffman** [comment]
Is multi-selection same as column selection now? If not:
    - column-select

**Comment by Naatan** [comment]
Nope it is not, good point :)

**Comment by Naatan** [comment]
Reopening this so that it's integrated to 9.3.2, please do not integrate until 9.3.1 is out the door.

**Comment by mitchell-as** [comment]
Merged for 9.3.2 release.

**Comment by tonyattwood** [comment]
Hey,

I've just found something really strange but at the same  time interesting, I think it is  worth seeing, just take  a  look <http://expert.childrenoutfitter.com/e4ooun>

Yours, tony.attwood@ntlworld.com
