### ISSUE TITLE
Notifications steal focus on everything except Scintilla

### ISSUE THREAD

**Issue by testworksau** [Komodo/KomodoEdit#816]
In Komodo Edit 9.3, I've noticed that various operations prevent me from clicking on the code editor.

Scenario 1: Performing a search with CTRL-F and deleting some text. 

I can't always reproduce this but it happens quite often.

1. Press CTRL-F to open the find dialog
2. Type in some text that can be found and press Enter to search
3. Keep pressing Enter until the last occurrence is found
4. Highlight some code in the editor
5. Press delete - nothing happens, and the Incremental Search window has focus but is empty (previous search text is no longer there)
6. Type something - the text typed that should be in the editor is applied to the incremental search

Scenario 2: Performing a search and replace with CTRL-H

If I highlight some code, then press CTRL-H, then press tab and make a change to the Replace field:

 - Sometimes Replace All does nothing. I can click it multiple times but nothing changes
 - After clicking Replace All, sometimes clicking on the code in the editor doesn't do anything - i.e. the editor does not gain focus and the find / replace window remains open.

I think both problems may be related to the python linters / syntax checkers blocking access - the reason I think this is the case is because the squiggly lines disappear after the Replace All operation, and it's not until they reappear that I get control back.

I'm using Pylint, Pyflakes, and PEP8 linters. The issue will be easier to see on larger files with lots of linter issues.

Update: I can almost guarantee that the linter notifications shown in the screenshot below are stopping the Replace All operation from occurring. I don't actually know why these are appearing at all as they are coming under the Syntax Checking Status tab anyway.

![image](https://cloud.githubusercontent.com/assets/11973031/10986464/45de9854-847e-11e5-9770-fd59df60ac81.png)

Komodo Edit, version 9.3.0, build 16396, platform win32-x86.
Built on Fri Oct 30 20:10:45 2015.

**Comment by Naatan** [comment]
Could you please use a default skin and see if you can reproduce the issue. From your screenshot above it is evident that you are using a non-default skin which has not yet been updated to support 9.3.

**Comment by testworksau** [comment]
I still get these issues with the Default skin.

The issue appears to be that clicking anywhere on the Find / Replace area (e.g. on the Replace All button) acts to dismiss the pylint etc. warnings that are appearing above the find window without acting upon the click operation as it should.

For some reason the same operations on the code editor screen are more difficult to reproduce, but again it appears caused by the pylint etc. notifications blocking access to the code editor.

**Comment by Naatan** [comment]
Could you try double clicking on the editor? I have seen issues where focus won't switch properly but clicking on the intended target twice forces it properly.

**Comment by testworksau** [comment]
Double clicking the editor only works because the first click dismisses the linter notification.

**Comment by Naatan** [comment]
Exactly, unfortunately that's the way the focus flows atm :\ I'll target this for Komodo 10 as we'll be doing quite a few changes around Notifications to get rid of annoying behaviour like this.
