### ISSUE TITLE
search and replace dialog disappears when focus changes

### ISSUE THREAD

**Issue by Etenil** [Komodo/KomodoEdit#817]
When displaying the search and replace dialog (ctrl-shift-h), it disappears as soon as I click elsewhere. This is extremely counter-productive when trying to copy and paste a search and a replacement string into the fields, as the dialog disappears and forgets my inputs.

Even using an OS clipboard manager didn't fix the issue as displaying the clipboard manager's history was enough for the search and replace box to dismiss itself.

**Comment by Naatan** [comment]
You can disable this from `Preferences > Find > Find Frame`.

**Comment by Etenil** [comment]
ah great, thanks!

**Comment by cgchoffman** [comment]
> counter-productive when trying to copy and paste a search
@Etenil note that if you highlight text then open the dialog using the keybinding, Komodo should use that text in the  "find what" field.   You don't need to copy and paste.  It's not the same for replace strings though...so my point may be a moo point...you know...like a cows opinion, it doesn't matter.

**Comment by Naatan** [comment]
> so my point may be a moo point...you know...like a cows opinion, it doesn't matter.

![8119436f-adcb-4b35-8b80-a444be0a7651](https://cloud.githubusercontent.com/assets/278649/11006600/8a3bdc64-8492-11e5-84fe-a8abfd0494bb.gif)

**Comment by Defman21** [comment]
@cgchoffman hey, respect cows opinion, we live in the world where everyone is equal!
