### ISSUE TITLE
linting errors/warnings notifications unusable in 9.3

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#818]
you go to an error with the cursor... no notification...
the other time notifications seem to be fired like a load of bullets... good luck catching the right one

**Comment by agroszer** [comment]
at the same time the "Syntax checking status" tab is gone? there at least if was possible to get to the offending line what's impossible now in the nofitications tab :-(

**Comment by Naatan** [comment]
I have noticed this as well, will look into this.

You can find the same information you found in the Syntax Checking tab by clicking on the Syntax checking icon ad the bottom right of your screen.

**Comment by agroszer** [comment]
Little triangle? That has just 3 options: Check, Jump to next, Clear no list

**Comment by Naatan** [comment]
Could you provide some sample code where you have syntax errors and the "triangle icon" (doesn't look like a triangle to me?) has no results.

**Comment by agroszer** [comment]
ok, found it:

![screenshot - 11072015 - 01 03 35 pm](https://cloud.githubusercontent.com/assets/350912/11015066/1156bc88-8550-11e5-941e-cb8dfbf1be7f.png)

but it just shows the first 4 problems (that screenshot is of BeautifulSoup.py, having 390 warnings)

**Comment by Defman21** [comment]
Having all the 390 items in this popup will break the UI and I don't think there is a way to insert a scrollable box inside this popup.

**Comment by agroszer** [comment]
the bombs seem to be gone in
Komodo IDE, version 9.3.1, build 88142, platform linux-x86_64. Built on Mon Nov 9 01:15:29 2015.
but still no solution to show the one under the cursor?

**Comment by agroszer** [comment]
well some bombs fire when the linter finishes... sometimes taking away popups...

**Comment by Naatan** [comment]
That is a separate issue which is tracked here: https://github.com/Komodo/KomodoEdit/issues/837

I think we are talking about multiple issues here. As the one being mainly addressed here is fixed could you please open a new bug report for your remaining issue?
