### ISSUE TITLE
Package update available going away fast

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#819]
If there's a Package update available notification on startup...
It's not really easy to catch it with the mouse, once gone, no idea where to find the same function.

**Comment by Defman21** [comment]
Packages scope in Commando?

**Comment by Naatan** [comment]
Right, it's under Commando > Packages > Manage.

Unfortunately the Notification panel is plagued by focus issues, as a workaround for the issues the notification is hidden when focus is shifted. We'll be addressing this permanently in Komodo 10 but atm this is the best possible workaround for the issue.

**Comment by agroszer** [comment]
err some lost features? How can I tell which version of a package is installed? "Open" on a package does nothing

**Comment by Naatan** [comment]
Indeed lost, it's a new system that still needs some polish. Please report any such issues you run into as new bug reports. Thanks! :)
