### ISSUE TITLE
Code Profiling not working for PHP

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#821]
It's not supported atm. I don't think it's hard to implement the feature: after running the debugger, save the PID of the debugger process, once the debugging is done, open Code Profiler with the `%php.ini::xdebug.profiler_output_dir/cachegrind.out.%PID` file.
Some useful links:
http://www.xdebug.org/docs/all_settings#trace_output_name
http://www.xdebug.org/docs/all_settings#profiler_output_dir

**Comment by mitchell-as** [comment]
It appears we do support code profiling for PHP, and also with cachegrind files. Is there something in particular that's not working @Defman21 ?

http://docs.komodoide.com/Manual/profiling

**Comment by Naatan** [comment]
@Defman21 please report the issue you're seeing and let us figure out the solution :) We do indeed support code profiling for PHP.

**Comment by Naatan** [comment]
I don't understand why I targeted this, I knew we supported this. My bad.

**Comment by Defman21** [comment]
Gonna try.

**Comment by Defman21** [comment]
Debug - Start Code Profiling does not work. It runs the debug session, but not the code profiler.

**Comment by Naatan** [comment]
Are you using a custom xdebug.dll?

**Comment by Defman21** [comment]
Where's it located?

**Comment by Defman21** [comment]
Find it, you don't have PHP 7.0 though.

**Comment by cgchoffman** [comment]
> Find it, you don't have PHP 7.0 though.

That's fixed in 10.0.1
