### ISSUE TITLE
Extensions Sites in Komodo IDE 9.3

### ISSUE THREAD

**Issue by lucas1** [Komodo/KomodoEdit#826]
![komodo-error](https://cloud.githubusercontent.com/assets/784699/11011008/05ab8862-84cb-11e5-8f90-3664d46f37b2.png)

Komodo IDE 9.3 not see icon of extensions Sites
I'm using theme Abyss Skin.

**Comment by Naatan** [comment]
I'm not sure what you mean by "extensions Sites", but you should switch to the default skin. Abyss currently does not support Komodo 9.3

**Comment by lucas1** [comment]
What's skin more similar with Abyss?

**Comment by Naatan** [comment]
None that have been updated for 9.3 yet. 9.3 is brand new, give it a week or 2 for addons and skins that need updating to be updated.

**Comment by lucas1** [comment]
Hi.
Problem yet persists!
You have some solution?

**Comment by Defman21** [comment]
Are you talking about this extension? https://github.com/brabitom/komodo-sites

**Comment by lucas1** [comment]
Yes, see 9.2 vs 9.3. Icon komodo-sites not show.

![komodo9 2](https://cloud.githubusercontent.com/assets/784699/12860021/1a4d1390-cc41-11e5-8f2b-33fac771be25.png)
![komodo9 3](https://cloud.githubusercontent.com/assets/784699/12860022/1a5007da-cc41-11e5-87bb-9fdfdbb31341.png)

**Comment by Defman21** [comment]
Abyss is not compatible with 9.3 (nor with 9.2, it was designed for Komodo 8). Are you able to reproduce it with default skin and icons?

**Comment by lucas1** [comment]
Problem this in extension Sites, I tested in others skins and have same problem.
Exist other extension with sftp?
thanks

**Comment by Defman21** [comment]
@brabitom could you fix this issue in your add-on?

**Comment by brabitom** [comment]
Interesting, I'll try to fix it as soon as possible.
Please be patient.

**Comment by brabitom** [comment]
Problem was fixed.
You can download and install new version of extension Sites: https://github.com/brabitom/komodo-sites/releases/download/0.3.2/sites-0.3.2-ko.xpi

**Comment by Naatan** [comment]
Nice @brabitom! Please consider submitting it to http://komodoide.com/packages/submit-instructions/#pane-packages

**Comment by lucas1** [comment]
@brabitom very good! Thanks :)

**Comment by brabitom** [comment]
@Naatan It's already submitted https://github.com/Komodo/Packages/commit/b1cf58d100ea7465bd6c860353bb15f6457a3b3a ;)

**Comment by Naatan** [comment]
Oops, my bad :)
