### ISSUE TITLE
KomodoIDE 9.3 spellcheck words in literal strings; shouldn't do that

### ISSUE THREAD

**Issue by roman02** [Komodo/KomodoEdit#827]
It underlines many tokens in my SQL statements. Shouldn't do that.

It also underlines things in commented out statements, e.g., it doesn't like dbh in this: 

// $userId = $dbh->lastInsertId();

This is distracting.

**Comment by Naatan** [comment]
A comment is a comment, we cannot start interpreting those for "commented out code". You can disable spell checking if this annoys you.

As for SQL statements, can you give some sample code?

**Comment by roman02** [comment]
Sure, please see the attached screenshot.

![komodo - spellchecked sql statement](https://cloud.githubusercontent.com/assets/1476055/11016034/3de6473e-853a-11e5-9e75-e803575980c0.jpg)

**Comment by Naatan** [comment]
@mitchell-as thoughts on this? Should we just disable spell check in strings or maybe we can be more intelligent as to what words qualify for spell checking (ie. don't spell check blocks (delimited by whitespace) that contain special characters).

**Comment by mitchell-as** [comment]
I can disable spell checking in SQL strings only. That might be for the best for this particular language.

I don't like the idea of trying to be intelligent because you might have "(parenthetical)" in an error message or GUI label or something that should be spell checked.

**Comment by Naatan** [comment]
I am fairly certain we do not interpret SQL strings in languages like PHP, they are just interpreted like regular strings.

How about we make it a pref? I can certainly see the use-case in wanting to use spell checking but also having a document with a lot of complex strings that cannot possibly be spell checked properly unless the spell checker is made a bit less "literal".

**Comment by mitchell-as** [comment]
Oh, I thought you meant the SQL language lexer. Yeah I suppose we can do a pref.

**Comment by mitchell-as** [comment]
Closed via https://github.com/Komodo/KomodoIDE/commit/9255773e480c8db8d0f09be7ef25cafffe3f273d
