### ISSUE TITLE
Empty pages after minimizing in Komodo Edit under El Capitan

### ISSUE THREAD

**Issue by Paul142857** [Komodo/KomodoEdit#828]
This is probably an OS X issue but I thought that I would post it here as well just in case.  I use Komodo Edit 8.5.4 and after updating my OS X to El Capitan last week I have noticed that if I minimize Komodo on my desktop for a moment and open it back up the page that I am working on is blank - no code can be seen.  If I switch to another page in Komodo and then switch back to the blank page the contents becomes visible again.  (I've also noticed that the thumbnail views in the Pages word processor program are sometimes blank.  Possibly related?)

**Comment by Defman21** [comment]
Please upgrade up to 9.3.

**Comment by Paul142857** [comment]
Thank you!  9.3 seems to take care of it although I have noticed that when I bring it back up from being minimized it temporarily flashes to a blank page and then becomes visible.

**Comment by mitchell-as** [comment]
Sadly, the brief flash is a display artefact on Mac OSX and there's nothing we can do about it :(

**Comment by tonyattwood** [comment]
Hello,

I've  recently found that  article on the web and the facts I had  found in it were  just  shocking! Pleaseread  it  here <http://example.regainhumanity.com/e4mtalo>

Yours faithfully, tony.attwood@ntlworld.com
