### ISSUE TITLE
Run without debugging broken in 9.3

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#835]
Reference: http://forum.komodoide.com/t/komodo-ide-9-3-0-crtl-f7-cause-an-debugger-error/2214

Workaround: [Use Run In-Line](http://docs.komodoide.com/Manual/Run-Code-In-line).

**Comment by Naatan** [comment]
Fixed on IDE repo.

**Comment by AndreaNES** [comment]
Running the code with CTRL+ 5 or In-Line generates different results for me: some import do not work In-Line.

When is Komodo 9.3.1 expected to be released ? This bug is really rather annoying.

Thanks for your attention,

Andrea
