### ISSUE TITLE
KomodoIDE 9.3 - Search&Replace dialog disappears on pressing 'alt' key, hotkeys doesnt work

### ISSUE THREAD

**Issue by earx** [Komodo/KomodoEdit#836]
1. press Ctrl-H, 'replace'  dialog appears
2. when try to use shortcut (ex. - Replace _A_ll - Alt+A) - dialog disappears, text is not replaced

Ide was updated from version 9.2

ubuntu 14.04, 
Komodo IDE, version 9.3.0, build 88117, platform linux-x86_64. Built on Thu Oct 29 11:07:23 2015.

**Comment by Naatan** [comment]
IIRC this is because of Ubuntu's HUD stealing focus. You could try pinning the find frame from Preferences > Find. 

Closing this though, as the bug is with Ubuntu's HUD.

**Comment by earx** [comment]
Cannot agree. Do you really try to force me to live with broken Find & Replace???

for example - 'Alt-V' (View menu) does work.
If there is no way to fix it for ubuntu - is it possible to revert back old 'Find & Replace' dialog?

**Comment by mitchell-as** [comment]
Hi, perhaps this comment will help you: https://github.com/Komodo/KomodoEdit/issues/689#issuecomment-149621227

**Comment by earx** [comment]
@mitchell-as, thank you!
But I need this behavior  for other apps..

**Comment by Naatan** [comment]
I'm not sure I follow your meaning, I gave you a solution/workaround. The eventual solution is for Ubuntu to fix their HUD, this is not something we have control over.

This is an issue in any application which uses alt menu's, it may simply not be apparent in all of them as they do not necessarily rely on focus.
