### ISSUE TITLE
Syntax popups steals focus and closes the auto-completion popup

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#837]
Very easy to reproduce. Start typing any code where you can get auto-completions and make some syntax errors, the popups will notify you about the errors in the code but also steals the focus and closes the auto-completion popup.
And the "don't make syntax errors" workaround is not something that I'll use :P

**Comment by Naatan** [comment]
Please define "steals focus"? Do you have to click the editor to continue typing?

**Comment by Defman21** [comment]
Nope, but the autocomplete popup disappears

**Comment by Naatan** [comment]
Need to delay notifications when autocompletions are showing, I will not even attempt to solve this by handling focus, because XUL panels are a horrible mess.

**Comment by agroszer** [comment]
The pain is that notifications also steal mouse clicks and ALT-TAB... PITA PITA

**Comment by agroszer** [comment]
and get clipped...
![screenshot - 11132015 - 12 01 05 pm](https://cloud.githubusercontent.com/assets/350912/11144618/5565b746-89fe-11e5-9f1f-82875dd15e0c.png)

so good luck disabling....

**Comment by Naatan** [comment]
You can also disable them via Preferences > Notifications.
