### ISSUE TITLE
Find all - critical defect when a few komodo windowes are open

### ISSUE THREAD

**Issue by meheytavel** [Komodo/KomodoEdit#843]
I have a few open windows in komodo (9.3) - when I do find all (ctrl + shift + F) on current document, it searches the document in the second window and the results appear there.
see attached screenshot.
Please reply ASAP, it is really urgent!!!

![image](https://cloud.githubusercontent.com/assets/15797282/11088000/82031052-8867-11e5-99bf-8234143e11db.png)

**Comment by mitchell-as** [comment]
Hi, Ctrl+Shift+F is "Find in Files", not "Find in File" (note the plural). Find in Files will jump to an occurrence in another file if none exists in the current file. This behavior is intentional.

**Comment by Naatan** [comment]
@mitchell-as I think you are thinking of the wrong thing here, he is saying his results are opening in another window, not that selecting a result opens them in another window.

@meheytavel I cannot reproduce this issue, but I did push a fix that could be related to this on the nightly, see if it works: http://downloads.activestate.com/Komodo/nightly/komodoide/latest/

**Comment by meheytavel** [comment]
@Naatan Thank you, it works!!!

**Comment by Naatan** [comment]
Perfect, thanks for letting us know :)
