### ISSUE TITLE
Komodo 9.3.0 "replace" not working on Mac

### ISSUE THREAD

**Issue by JNJefferyDesign** [Komodo/KomodoEdit#847]
The new version of Komodo I can't get replace to work.  I'm trying to replace the word "pink" with the word "white" and it's not working.  The new interface doesn't make sense and I can't get it to work.  Could someone explain how it works?

**Comment by cgchoffman** [comment]
Hi @JNJefferyDesign it's definitely working.  This sounds like you just need some assistance.  Please open a topic in our forums:http://forum.komodoide.com/
