### ISSUE TITLE
Code completion for Tcl inserts at wrong point

### ISSUE THREAD

**Issue by Hermitifier** [Komodo/KomodoEdit#85]
When I use autocompletion in tcl files, it often inserts at position earlier than cursor. It seems related to file contents, in particular non-ascii characters.

This only affects completion selected from popup. Ctrl-space works correctly.

The first image shows code popup working as intended:
![clipboard01](https://cloud.githubusercontent.com/assets/310646/6873652/1ecd23e2-d4b2-11e4-80d6-78fefaaf9055.png)

Another popup is drawn in front of the expected insertion point:
![clipboard02](https://cloud.githubusercontent.com/assets/310646/6873650/1ecba1c0-d4b2-11e4-95a1-dd637fb50d54.png)
But it's the actual calculated insertion point:
![clipboard03](https://cloud.githubusercontent.com/assets/310646/6873651/1ecc118c-d4b2-11e4-87d6-edc44d9aafbd.png)

The more characters above 7-bit range the file has, the worse the spread:
![clipboard04](https://cloud.githubusercontent.com/assets/310646/6873655/1ece3c6e-d4b2-11e4-9dc5-ad1e4023cd7b.png)
![clipboard05](https://cloud.githubusercontent.com/assets/310646/6873654/1ecde0ca-d4b2-11e4-9a98-7d06ae308d49.png)

Certain characters are worse than others:
![clipboard06](https://cloud.githubusercontent.com/assets/310646/6873653/1ecd83be-d4b2-11e4-8c9f-8f481e169eb7.png)
![clipboard07](https://cloud.githubusercontent.com/assets/310646/6873656/1ee11000-d4b2-11e4-8276-41e24f7b5edd.png)

In extreme cases, this will calculate insertion point well in front of the cursor (even several lines above). When insertion happens, anything between calculated insertion point and current cursor position, is deleted.
Both 8.5 and 9.0 are affected. Tested under Windows 7 and 8.1.

**Comment by toddw-as** [comment]
Unicode conversion error in tcl completion handling. Fixed for 9.0.1 in commits:
  https://github.com/Komodo/KomodoIDE/commit/e7f56e5 (master)
  https://github.com/Komodo/KomodoIDE/commit/cecd752 (9.0.1 branch)
  https://github.com/Komodo/KomodoEdit/commit/d1fa8d4 (master)
  https://github.com/Komodo/KomodoEdit/commit/bd61303 (9.0.1 branch)
