### ISSUE TITLE
Support mouse key binding

### ISSUE THREAD

**Issue by rocker19943** [Komodo/KomodoEdit#852]
Hi,

Currently there is no way to make mouse buttons usable for keybinding, I'd like to be able to add variables to watchlist by clicking middle mouse button.

**Comment by Naatan** [comment]
Unfortunately there are too many caveats with mouse button binding that facilitating it would be too error-prone. You could however write a userscript to do this, wherein you yourself would be handling any edge cases you might run into.

Userscripts are written in javascript, so you can handle middle mouse clicks the same way you would in your browser.

**Comment by babobski** [comment]
@rocker19943 was looking at this request and played around with a small userscript to help you out.
Got it working with a other command, self i don't use debugging in komodo (just a front-end developer), and looking at my komodo edit i can't find a debug function. So I'm not able to complete test this userscript, but i think it should work.
Made it to trigger only on the middle mousse button and if you're editing `.py` files, but you can change it to the file ext. you want.

```javascript
(function() {
	
	var notify	= require("notify/notify");
    
    window.removeEventListener('click', this.midleClickCommand);

    this.midleClickCommand = function(e){ 
		// only trigger on middle button
		if (e.button === 1) {
			var view 	= ko.views.manager.currentView;
			var scimoz 	= view.scimoz;
			
			// if no current view is open
			if (view === null){
				return false;
			}
			
			// if file isn't saved we cant get it's extension
			var file = view.koDoc.file;
			if (file === null) {
				return false;
			}
			
			// if file is .py
			if (file.ext === '.py') {
				
				// and then do the command
				try {
					ko.commands.doCommand('cmd_dbgAddVariable');
					notify.send('Added Watch Variable', 'tools');
				} catch(e) {
					notify.send('Error: ' + e.message, 'tools');
				}
			}
		}
		  
    };
    window.addEventListener('click', this.midleClickCommand);

}).apply();
```
Just add this as a new userscript and set it to trigger on start-up.
Also found a other command that only will work with a selection "Make Selection a Watched Variable",
then you would get something like this (tested this one with the to upper case command and is working for me):
```javascript
(function() {
	
	var notify	= require("notify/notify");
    
    window.removeEventListener('click', this.midleClickCommand);

    this.midleClickCommand = function(e){ 
		// only trigger on midle button
		if (e.button === 1) {
			var view 	= ko.views.manager.currentView;
			var scimoz 	= view.scimoz;
			
			// if no current view is open
			if (view == null){
				return false;
			}
			
			// if file isn't saved we cant get it's extension
			var file = view.koDoc.file;
			if (file === null) {
				return false;
			}
			
			// if file is .py
			if (file.ext === '.py') {
				
				// if there is a selection
				var selection = scimoz.selText;
				if (selection.length === 0) {
					notify.send('No selection made', 'tools');
					return false;
				}
				
				// and then do the command
				try {
					ko.commands.doCommand('cmd_dbgMakeWatchedVariable');
					notify.send('Added Watch Variable', 'tools');
				} catch(e) {
					notify.send('Error: ' + e.message, 'tools');
				}
			}
		}
		  
    };
    window.addEventListener('click', this.midleClickCommand);

}).apply();
```
Hope this will help you out.

**Comment by Naatan** [comment]
That's awesome @babobski ! Nice work :)

**Comment by babobski** [comment]
Thanks :+1:
