### ISSUE TITLE
Track changes settings only apply after reopening buffers

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#854]
If you disable or enable the "track changes" setting, you have to restart komodo edit before these settings are applied. (on komodo edit windows 10)

**Comment by Naatan** [comment]
Thanks, the issue is in fact that it does not apply to already opened editor buffers. So reopening the files you had open also does the trick.

**Comment by babobski** [comment]
Ah ok, had some issues with the minimap background, the track changes settings seems to be the cause of this. Switching this settings i noticed this little bug.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/trackchanges/commit/3bee629fc6c185268bfa3ef332cf42095d01d1d6

**Comment by mitchell-as** [comment]
Reopening this so that it's integrated to 9.3.2, please do not integrate until 9.3.1 is out the door.

**Comment by mitchell-as** [comment]
Merged for 9.3.2 release.
