### ISSUE TITLE
Track changes is affecting the minimap background

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#855]
If you have track changes settings enabled, the minimap background sometimes gets white strokes in the background. If you disable the track changes this behavior disappears.
![snap 2015-11-12 at 18 06 40](https://cloud.githubusercontent.com/assets/3530262/11125271/4fc3cb60-8969-11e5-8e3f-a3113270e597.png)

**Comment by Naatan** [comment]
Can you provide steps to reproduce?

**Comment by babobski** [comment]
Yeah, finally got a screen capture program that's kinda working for me. Uploaded a [screen capture](https://youtu.be/6Q8ykjC7U9g) to youtube.

I have this bug since the introduction of the track changes, all what i have to do to reproduce this is edit a file with the track changes setting enabled and the white strokes are appearing.

**Comment by Naatan** [comment]
Thanks @babobski, one more question - can you reproduce this with a default color scheme?

**Comment by babobski** [comment]
yes, if i set the color scheme to tomorow dark i'm having the same results.
![snap 2015-11-12 at 20 00 50](https://cloud.githubusercontent.com/assets/3530262/11128128/39e99798-8978-11e5-9f92-39333d17a555.png)

**Comment by Naatan** [comment]
Alright, thanks.

**Comment by mitchell-as** [comment]
Reopening this so that it's integrated to 9.3.2, please do not integrate until 9.3.1 is out the door.

**Comment by mitchell-as** [comment]
Merged for 9.3.2 release.
