### ISSUE TITLE
Notifications clear autocompletion popups

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#856]
If you have a autocompletion popup open, and a notification message disappear the autocompletion box is canceled. 
When you have a autocomplete box open and a notification disappears, this can be a lint error or a other notification. When this one disappears the autocompletion box is canceled. The language where i have the most issues with this is php (also the autocompletion box isn't always triggered in php).
Made a [screen cast](https://youtu.be/OV8HYkabS98) to see it in action, here i type a var and hitting the `ctrl + space` a couple of times and wait till the notification disappear while having a autocompletion box open.

**Comment by Defman21** [comment]
Duplicate of https://github.com/Komodo/KomodoEdit/issues/837

**Comment by babobski** [comment]
Damm you're fast, but it is, closing it...

**Comment by Defman21** [comment]
>Damm you're fast,

Yeah, I know it :P
