### ISSUE TITLE
icons in vertical tabs looks a bit messy

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#857]
in komdo 9.3.1 there are icons in all tab layouts, in my opinion the are a bit redundant as the tab title tells you enough about the tab, i don't need a icon there it's only taking in space and is looking kind a messy on the vertical tabs.
In the vertical tabs layout i find it not that pretty because on the left side the icons are on top and on the right they are at the bottom and the icons looks kind a weird here.

![snap 2015-11-12 at 19 16 04](https://cloud.githubusercontent.com/assets/3530262/11131306/59c8b2bc-898a-11e5-84e3-73add8c1c95c.png)

![snap 2015-11-12 at 23 16 56](https://cloud.githubusercontent.com/assets/3530262/11133023/a6b05702-8993-11e5-9cba-354f0761db29.png)

If they are here to stay (which i hope not :stuck_out_tongue_winking_eye:  ), maybe it's an idea to add the default icon if the tab not having a own icon, as this is the default behavior in the icons only tab, now i only having icons on the default komodo tabs and not on the other tabs.

**Comment by Naatan** [comment]
Honestly these were never intended to be in vertical tabs, thanks for pointing it out :)

**Comment by babobski** [comment]
ok, nice :+1: good to know.

**Comment by babobski** [comment]
@Naatan you already fixed it
