### ISSUE TITLE
Include field is ignored in the search dialog for projects

### ISSUE THREAD

**Issue by jsnjack** [Komodo/KomodoEdit#858]
`Include` field is ignored in the search dialog when field `Where` is project. I tried to start search only in js files by specifying it like `*.js`. If `Where` field is Files it works as expected, but if I change it to Project it just starts search in all files.

Komodo 9.3, linux

**Comment by Naatan** [comment]
Reproduced on Linux.

**Comment by jsnjack** [comment]
@Naatan I have just checked and the same problem exists in komodo 10. I guess there will be no 9.3.3 release?

**Comment by Naatan** [comment]
Unlikely, we have a 9.3.3 nightly but I don't see a full release happening at this point.

**Comment by jsnjack** [comment]
Thanks! Looking forward to see that issue fixed (opening other editor just for search operation is annoying :/ )

**Comment by Naatan** [comment]
@mitchell-as was this not implemented at all for projects?

**Comment by mitchell-as** [comment]
That's right. Komodo 8 did not have this.

**Comment by Naatan** [comment]
Nor Komodo 9, I assume?

I'll create a new enhancement request for this to be added. I've found myself often wanting it in the project context.

**Comment by mitchell-as** [comment]
No. I noted in my commit message that this "include" field was accidentally introduced when the find dialog got integrated into a pane (as opposed to being a separate dialog).

**Comment by Naatan** [comment]
Gotcha, thanks @mitchell-as :)
