### ISSUE TITLE
Komodo should not check for updates twice

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#859]
Sometime I can miss "Komodo %version% is available" popup and I have to check for updates twice, but the operation isn't very fast as it can be (because of my geographic location). Komodo should cache this info and I should able to upgrade via About menu or Check for Updates if the check was here. (like in Firefox Nightly)

**Comment by Naatan** [comment]
It does cache this information. Based on what you're saying you are requesting a menu entry to check for updates, not asking for any sort of caching? 

Please ask for what you want and let us worry about how to implement it :)

**Comment by Defman21** [comment]
Komodo sometime checks for updates in background and shows me a popup, if I click on it - I get the Update window where I can continue with the updating process. But If I'll miss this popup somehow, I have to check for updates again via "Check for Updates" menuitem. So actually I check for updates 2 times. So I want Komodo to don't check for updates if it was checked in background and when I click on "Check For Updates", the checking should be skipped in favor of cached results of the update process, so I should able to update Komodo without fetching the update again.

**Comment by Naatan** [comment]
Ah I see. I am sorry about this but I don't really see this being worth the effort. It would likely take quite a bit of digging to figure this out and only to resolve a minor annoyance that is likely not affecting very many people. I'm sorry but I don't feel it's worth our time.

**Comment by Defman21** [comment]
Okay, no worries :)
