### ISSUE TITLE
If project name contains spaces then 'open in new window' fails

### ISSUE THREAD

**Issue by sfsccn** [Komodo/KomodoEdit#860]
**Komodo Version**: IDE 9.3.0
**OS1**: Scientific Linux (CentOS-based) 3.10.0-229.14.1.el7.x86_64
**OS2**: Windows 10

When opening a project in a new window via right-click, if the project name has no spaces it works, otherwise I get an error of the form: 'Unable to load project "My%20%Project". File does not exist.' This happens in both Linux and Windows.

**Comment by Naatan** [comment]
Reproduced, thank you.

**Comment by Defman21** [comment]
So this is not fixed as I can see, there are some reverts of the fix-commit. @cgchoffman?

**Comment by cgchoffman** [comment]
It's working in 9.3.2.  What makes you say it's not fixed?

**Comment by Defman21** [comment]
Those reverts.. but if it works fine - then it's cool :)

**Comment by cgchoffman** [comment]
I'm glad you approve.
