### ISSUE TITLE
Double-click on PHP variable selects more than one

### ISSUE THREAD

**Issue by seattledeveloper** [Komodo/KomodoEdit#863]
I have places in my code where I will include multiple variables in an output string:

echo "This is a sample $var1$var2$varx output.";

When double-clicking on one of these variables to select it, all three variables (in the example above) are selected instead.  It seems that the desired behavior is to just select individual variables.

Thanks in advance!

**Comment by mitchell-as** [comment]
We'll have to research this a bit further, as I'm not sure modifying the default double-click behavior is the right way to go.

**Comment by seattledeveloper** [comment]
It just seems a leading dollar sign should be a delimiter if you're in a PHP code block (or maybe just in general), but I will defer to your research.  Thanks for considering this.

**Comment by mitchell-as** [comment]
I finally had some time to look into this and came to the conclusion that modifying the default double-click behavior is not a good idea. The only way to go about this is to prevent `$` from being considered a word character. As a side-effect, this means that anytime you double click on a stand-alone variable like `$foo`, only the `foo` part will be highlighted. From your perspective as a PHP developer, would this be proper behavior?

**Comment by seattledeveloper** [comment]
This is a great suggestion.  I think it should go out to the group for a vote (if that is even possible).

Personally, I prefer to have the $ not included in the double-click select.  The reason being is that I always name local variables the same as my database field names.  Here's a case:

$var_name = $my_db_array['var_name'];

When I am copying that line to add a new field name, I need to be careful when selecting text to include or not include the leading $, depending on what I am copying/pasting from/to.  What is selected when double clicking the $var_name is different that what is selected when double clicking on the 'var_name'.

I am used to it other editors selecting the exact text "var_name" in both cases.  Other developers may disagree with this approach.  I definitely don't want to speak for all developers.  This is just my personal preference.

Thoughts?

Ed

**Comment by Naatan** [comment]
I'm +1 on not including $ in double clicks on vars in PHP files.

Any other PHP devs want to weigh in?

**Comment by VeryVito** [comment]
Personally, I prefer to have the $ included in the selection.  The use case of @seattledeveloper is a valid consideration, but I personally find it rarer that I need to remove the symbol than include it. It's a subtle difference, but it is one that I find distracting in practice when switching between Komodo and Brand X IDE.

**Comment by Naatan** [comment]
@VeryVito I'm confused, you speak as if this change is already present. Are you saying you "would" find distracting if it were implemented this way?

**Comment by Defman21** [comment]
Why not to make a checkbox for this?

**Comment by garak** [comment]
I think that using $var1$var2$etc is just a bad practice. You should put brackets around your variables.
The current click select behaviour looks fine to me.

**Comment by cgchoffman** [comment]
I think @Defman21's suggestion negates the need for discussion doesn't it?  Add a PHP lang pref to add/remove `$` from the known "word characters".

**Comment by seattledeveloper** [comment]
I agree.  It would be much better to have this as a preference.  That way the IDE isn't forcing everyone to the same solution.  Thanks @Defman21 for the idea.

**Comment by Naatan** [comment]
@mitchell-as is a pref possible? I figured this would be an UDL thing and thus not something that can be dynamic.

**Comment by mitchell-as** [comment]
I think a pref is possible. I'll let you know otherwise.

**Comment by girvo** [comment]
In the same way that double-clicking on `'something-quoted'`, I would expect it to select the word, not the quotes as well. I think double-clicking to select the variable name without the `$` would be a good feature for myself as a PHP dev, yes :)

**Comment by mitchell-as** [comment]
There will be a new "Double-click selects entire variable (including $)" preference in Edit > Preferences > Languages > PHP > Other Options. It will be enabled by default for backwards-compatibility.
