### ISSUE TITLE
Default wrap with / conflicts with Ctrl-/ shortcut

### ISSUE THREAD

**Issue by cdcmicro** [Komodo/KomodoEdit#865]
I've been getting used to text wrap in 9.3 (IDE), and I notice the default list of wrap-start chars includes '/'.  To me, that's a very Perlish wrap character, but I'm a Perl guy.  Anyway, when '/' is one of the wrap chars, and I press Ctrl-/ to comment-out a number of selected rows, the rows get wrapped instead of commented-out.

No big deal 'cause it's easy to remove '/' from the list in preferences.  But I wonder if it should be part of the default charlist?

**Comment by mitchell-as** [comment]
Thanks for the report. This is a bug.

**Comment by mitchell-as** [comment]
Reopening this so that it's integrated to 9.3.2, please do not integrate until 9.3.1 is out the door.

**Comment by mitchell-as** [comment]
Merged for 9.3.2 release.
