### ISSUE TITLE
Continue SCSS comments with Shift-Enter

### ISSUE THREAD

**Issue by cdcmicro** [Komodo/KomodoEdit#866]
Thanks for considering this enhancement request.

Editing Perl and Javascript files, I can continue single-line comments onto the next line by pressing Shift-Enter.
```javascript
// JS comment here<Shift-Enter>
// 
```
```perl
# Perl comment here<Shift-Enter>
# 
```
I would like to have that feature for SCSS files.  Is it possible?

**Comment by mitchell-as** [comment]
Note to self: this is an easy fix. koSCSSLanguage needs

    commentDelimiterInfo = {
        "block": [ ("/*", "*/") ],
        "markup": "*",
        "line": ["//"],
    }

The side effect is that Ctrl+/ will now use '//' comments instead of '/* */' comments.

**Comment by Naatan** [comment]
I think that's fine, that [seems to be desirable anyway](http://forum.komodoide.com/t/js-style-comments-for-scss/2254).
