### ISSUE TITLE
Multiple Selection - remove Previous Occurrence 

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#869]
I love the add next occurrence function, only missing the ability to go back. If working on large files i sometimes overshoot my target and have to start over again. Would be nice if you can jump back one(or more) occurrence. 

![snap 2015-11-15 at 16 52 592](https://cloud.githubusercontent.com/assets/3530262/11169573/1524a9d4-8bbc-11e5-8af2-e3c6d3237810.png)

**Comment by mitchell-as** [comment]
Hi, you can create a userscript that does this:

    var scimoz = require('ko/editor').scimoz();
    scimoz.dropSelectionN(scimoz.selections - 1);

You can bind that to a key shortcut too, like Ctrl+Shift+D

**Comment by Naatan** [comment]
@mitchell-as that still seems like something we ought to be supporting natively, especially if it's so simple :)
