### ISSUE TITLE
Komodo 8 and 9 Codeinteligence UpperLetters bug.

### ISSUE THREAD

**Issue by MironMironMiron** [Komodo/KomodoEdit#870]
i use comodoEdit
codeinteligence crash and down work when file name contens upper letters. or path.

example. i create class in php: newClass.php

<?php

class newClass {
    
}

?>

when i save file: calling method do_scan_document
in codeintel2/oop/driver.py

in AppData\Local\ActiveState\KomodoEdit\9.3\codeintel\db\php\
creates new blob file: 
scope ilk="blob" lang="PHP" name="newclass.php" src="s:/domains/class/newclass.php"
scope ilk="class" line="3" lineend="5" name="newClass2" 
how you see src is not s:/domains/class/newClass.php it contents lower case. 

then running scann all dirs script: and create new blob file. (IN DB We HAWE 2 blob files)
scope ilk="blob" lang="PHP" name="newClass.php" src="s:/domains/class/newClass.php"
scope ilk="class" line="3" lineend="5" name="newClass2"
second file src hawe upper letters.

but when i modific class and add some function this function add in firs blob file. 
scope ilk="blob" lang="PHP" name="newclass2.php" src="s:/domains/class/newclass.php"
scope ilk="class" line="3" lineend="8" name="newClass2"
scope attributes="public" ilk="function" line="4" lineend="7" name="last" signature="last()" 

and when i in editor try call my new function -> newClass->.... i dont see my new function.
because in db exist two blob index to one file. (function i call in other file)

this bag was in komodo8. and left in comodo9. 
Plese fix it. 

codeinteligence in all uses who create files width uppler/lowwer letters not work. !!!!!!!

**Comment by MironMironMiron** [comment]
creates new blob file: 
scope ilk="blob" lang="PHP" name="newclass.php" src="s:/domains/class/newclass.php"
scope ilk="class" line="3" lineend="5" name="newClass2" 

then running scann all dirs script: and crate new blob file
scope ilk="blob" lang="PHP" name="newClass.php" src="s:/domains/class/newClass.php"
scope ilk="class" line="3" lineend="5" name="newClass2" 

but when i modific class and add some function this function add in firs blob file.
scope ilk="blob" lang="PHP" name="newclass2.php" src="s:/domains/class/newclass.php
scope ilk="class" line="3" lineend="8" name="newClass2
scope attributes="public" ilk="function" line="4" lineend="7" name="last" signature="last()"

**Comment by mitchell-as** [comment]
Hi, I'm having difficulty understanding how this issue is being caused for you. Could you post the contents of both of your files so I can try to reproduce this? I'm also not sure how you get from "newClass.php" to a broken state -- the instructions are not clear to me.

Please keep in mind that Windows filenames are NOT case-sensitive. so if you are trying to edit a "newClass.php" file in the same directory as a "NewClass.php" file, you are actually editing the same file. That may be causing codeintel some problems, but again, I'm not sure exactly what you're trying to do.

Thanks for your patience.

**Comment by MironMironMiron** [comment]
hi problem not in windows case-sensitive.

when directories or files have upper lowwer leters in codeinteligence db creates to may .blob files
and codeingeligence dont work. when i modifi one class. my changes dont see in other classes.

i add dome wideo where i show what is wrong and what is problem.

https://www.dropbox.com/s/gp0vhbz4aic60yr/codeinteligence_bug.mp4?dl=0

you can try this self.

plesase fix this.  all who writes directories and file names withh uppler and lowwer letters cant use 
codeinteligence correctly.

**Comment by mitchell-as** [comment]
Note to self: this is not exclusive to PHP. I also reproduced using Python. Therefore it does not appear to happen in the language CILErs.
