### ISSUE TITLE
Autocompletions don't show in some cases

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#871]
Open a JS file, type the following:

`set`

You will get autocompletions for setTimeout.

Now remove the line and type (fast):

`setT`

You will get no autocompletions.

This is fixed by settings "show completions after" to 0.

This is likely related to the fact that completions trigger at 3 characters, and if the above setting is set to above 0 then it is possible that completions are triggered at eg. 4 characters and possibly this is not handled well?

**Comment by mitchell-as** [comment]
After investigating, codeintel has been operating under the assumption that it is always called immediately after each keypress. Therefore it cannot handle the new timeout mechanism.

The timeout mechanism has been reverted in 9.3.x.

For Komodo 10, work will need to be done to have codeintel work with any text behind the caret, not hard-coded positions based on the assumption of having the current state (which was the case pre-timeout). This affects at least Javascript, Python, and Ruby. All languages are likely affected. Unit tests will also need to be written to account for the new functionality. For example:

Javascript: `setT` will need to complete `setTimeout`.
Python: `__a` will need to complete `__abs__` and `__add__`.

**Comment by Naatan** [comment]
Overarching issue tracked here: #880

I'll close this one, the solution for the issue here was to revert the setTimeout change for 9.3.x
