### ISSUE TITLE
Find in Files does't remember last "Where" selection

### ISSUE THREAD

**Issue by seattledeveloper** [Komodo/KomodoEdit#873]
When doing a search using CTL+SHIFT+F, the default "Where" selection always seems to be "Project", no matter where the previous search had been done.  Since other aspects of this functionality remember previous search parameters (like the search text, regular expression, etc.) it seems like the the "Where" should be included.

Thanks in advance!

**Comment by Naatan** [comment]
Can you verify what "Ctrl+Shift+F" is set to in Prefs > Key Bindings?

**Comment by seattledeveloper** [comment]
The default "Files: Find in Files...", which brings up the new Find in Files band above the search results in Komodo IDE, version 9.3.0, build 88117, platform win32-x86.

**Comment by Naatan** [comment]
Thanks, just wanted to make sure.

I do recall seeing some inconsistencies here as well.

**Comment by seattledeveloper** [comment]
Hi Nathan,

This seems to be fixed as of 9.3.1.  Is this what you are seeing?

Ed

**Comment by Naatan** [comment]
It's not yet fully consistent in my experience.

**Comment by seattledeveloper** [comment]
OK.  I'll keep an eye on this as well.  Thanks for letting me know.

**Comment by seattledeveloper** [comment]
I agree.  One instance seems to be when *Files* is selected, it defaults to *Open files* on the next CTL+SHIFT+F
