### ISSUE TITLE
Shift + Command + Up key bind doesn't work

### ISSUE THREAD

**Issue by jamadam** [Komodo/KomodoEdit#874]
Shift + Command + Up key have been working as combination of "select region" + "go top" at least untill version 8.x.
Now it doesn't.

The following key binds are working as it used to.

* Shift + Command + Down
* Command Up

MacOSX Yosemite 10.10.5
Komodo Edit, version 9.3.0, build 16396, platform macosx. Built on Fri Oct 30 20:10:43 2015.

**Comment by Naatan** [comment]
Key bindings often change over major releases, if you don't like a change you can always set it yourself under Preferences > Key Bindings.
