### ISSUE TITLE
Button icons all emoticons

### ISSUE THREAD

**Issue by jmanpa** [Komodo/KomodoEdit#88]
Just installed:
Komodo IDE, version 9.0.0-rc1, build 87167, platform macosx. Built on Fri Mar 20 

Icons are all yellow emoticons

![k2](https://cloud.githubusercontent.com/assets/374877/6882379/3a58ff9e-d559-11e4-97bb-a6b59b329ed2.jpg)
![k1](https://cloud.githubusercontent.com/assets/374877/6882380/3a640b32-d559-11e4-8d21-5ab774657bae.jpg)

**Comment by Defman21** [comment]
What icon set you use? (`Prefs - Appearance`)

**Comment by jmanpa** [comment]
It is blank. Won't allow me to select one. Nothing in drop down

**Comment by Defman21** [comment]
Un-check `Auto-detect skin`. If there are nothing in dropdown list - you have to re-install Komodo.

**Comment by Defman21** [comment]
Ohh... I can see your image now, @jmanpa. I sure you have to reinstall Komodo.

**Comment by cgchoffman** [comment]
https://bugs.activestate.com/show_bug.cgi?id=106315 this was resolved already.

**Comment by cgchoffman** [comment]
FYI, you won't be able to use the pre-release for much longer.  now that Komodo 9 has been released you'll need to upgrade your license.

**Comment by jmanpa** [comment]
Fixed with Reinstall. Thanks.

**Comment by Defman21** [comment]
@jmanpa can you say btw your color scheme on the second screen in the issue?
