### ISSUE TITLE
CodeIntel code inspector tree crashing

### ISSUE THREAD

**Issue by AtmanActive** [Komodo/KomodoEdit#881]
Sorry to be a party breaker here, but the issue I opened here:

https://github.com/Komodo/KomodoEdit/issues/569

is still haunting me.

To recap: after working in Komodo for several days and couple of dozen of files opened, edited and closed, CodeIntel code inspector tree just stops working and there is a '[CRITICAL] codeintel.komodo: Out-of-process ran out of memory - killing process' line in the logs

Below is the log file.

[Komodo_Log_2015-11-17.txt](https://github.com/Komodo/KomodoEdit/files/37105/Komodo_Log_2015-11-17.txt)

**Comment by Naatan** [comment]
Please bump the existing ticket, no point in creating a new one :)

**Comment by AtmanActive** [comment]
I didn't realize I can still comment on closed ones :)
This red 'no-go' sign that GitHub displays looks like 'leave this thread alone!' to me :)
