### ISSUE TITLE
Hard to control search panels with tab key

### ISSUE THREAD

**Issue by jamadam** [Komodo/KomodoEdit#883]
1. open "Edit" > "Replace" then "Find:" area is forcused(as expected).
2. Hit tab key and then "Where:" area is focused but can't distinguish visibly.

The focus state of icons such as "Match Cases" is also indistinguishable.

MacOSX Yosemite 10.10.5
Komodo Edit, version 9.3.0, build 16396, platform macosx. Built on Fri Oct 30 20:10:43 2015.

**Comment by landy2005** [comment]
I also confirm this issue..
Icons "Match Cases" visually quite indistinguishable.

**Comment by cgchoffman** [comment]
Just to clarify, the Tab key isn't an issues.  It's the inability to see where you've tabbed to?  Pressing tab goes where you expect it to go right?

**Comment by jamadam** [comment]
I guess tab key works. Visibility is the issue here. 
Since I can't see where is the focus, I'm not sure the tab-order is as expected.

**Comment by testworksau** [comment]
Same issue on Windows. 

As a side note, when you tab all the way back around again, the find window closes itself. It's a bit annoying, particularly because reopening the find dialog will clear the test you may have just entered in.

**Comment by cgchoffman** [comment]
> As a side note, when you tab all the way back around again, the find window closes itself.

@testworksau that's a different issue. You can file a new issue for that.

@jamadam I think this needs to be narrowed down a bit.  The issue is that you can't tell when you're on the Icons right?  Note on OSX you can't Tab through buttons or Drop-downs (that eliminates the icons for replace, match case, etc.).  This means that Tabbing does the following (on OSX) Find > Replace> Includes.

**Comment by testworksau** [comment]
@cgchoffman done - see issue 888

**Comment by jamadam** [comment]
Ah, you reminds me of tab setting in OSX preference which I set to "All controls".

It's in OSX's System Preference > Keyboard > Shortcut > Mission Control. You can also toggle it with Control + F7 key bind. If the setting is "Only text box and list", the default one, there isn't any issue. I'm sorry not to share the information.

With my setting, the focus seems to moves in follow order and the visibility issue is on icons, buttons, drop-downs.

* Find:
* Replace:
* Where:
* Mark All button
* Replace All button
* include:
* ?
* case sensitivity icon
* W icon
* multiline icon
* Regular Expression icon
* and so on..

**Comment by Naatan** [comment]
> Ah, you reminds me of tab setting in OSX preference which I set to "All controls".

Oh wow, I was not aware this setting existed. Thanks for sharing!

The focus does seem to shift oddly when using the "Current Document" scope. 

@cgchoffman I think your workaround may be the cause here, probably safer if we are more explicit with the tabindex.

**Comment by Naatan** [comment]
Err actually this should be a separate issue, it has nothing to do with focus being hard to distinguish.

@jamadam can you please open a new bug.

**Comment by jamadam** [comment]
@Naatan Well, I don't get what I suppose to open a new issue for. My only point is the appearance of focus and not sure so far the tab-order is appropriate or not.

I also checked the komodo Edit v8.5 behavior depending on OSX keyboard setting and there is no major deferences between the versions except the appearance.

**Comment by Naatan** [comment]
@jamadam the issue we'll track here is the focus not being distinguishable, you raised another issue which is that the focus is not shifting logically, this would need to be tracked in its own bug report.

Generally we ask people to open a bug rather than doing it ourselves because when we do it ourselves the original reporter of the issue is not CC'ed on future updates, and we may also be lacking some detail that the original reporter could give.

**Comment by jamadam** [comment]
@Naatan Sorry, It has something to do with my English literacy but I have never intended to report "the focus is not shifting logically." and not even understand what it means.

I also don't get what you mean by

> The focus does seem to shift oddly when using the "Current Document" scope.

**Comment by Naatan** [comment]
Oh ok, no worries then :) You unintentionally raised another issue.
