### ISSUE TITLE
Komodo 9.3.0 default "Code: Uncomment Region" keyboard shortcut conflicts with OSX help menu shortcut

### ISSUE THREAD

**Issue by elo2112** [Komodo/KomodoEdit#884]
In Mac OS 10.10 (and possibly other versions), the keyboard shortcut "Command+shift+/" triggers the "Show Help menu" action for all applications.  This conflicts with the new Komodo 9.3.0 default shortcut for "Code: Uncomment Region."  The OSX shortcut takes precedence.

Users either need to disable the OSX shortcut or change the Komodo shortcut.  Definitely doable, but inconvenient.

**Comment by elo2112** [comment]
Thanks!

**Comment by atbraoy** [comment]
I found in my komodo preferences that you can use (Meta+Ctrl+/) to un-comment area.
Meta = 'command' in mac.

**Comment by cgchoffman** [comment]
You got it @atbraoy. That's what the commit that closed this bug did https://github.com/Komodo/KomodoEdit/commit/176e5bce730e6b5b3f1728ef203c2daa81c330bc#diff-015cfc54633232f335a07e8a5f861458R60
