### ISSUE TITLE
Must klick "Start" twice to run a script

### ISSUE THREAD

**Issue by paulsommer** [Komodo/KomodoEdit#886]
Starting with Komodo 9.x I always have to click the green "Start" button twice to start a script. Same applies to "F5", "F7" and "F11".

The first click only opens the "Debug Output" pane (or initializes it if already opened).
Only the second click starts the script.

Tested with PHP and Perl on Kubuntu 14.04.3 64bit

Exception:
If I run a script without debugging (F7) then the next start/debug works with a single click.
_Sometimes_ a single click works on newly opened files (cannot see any system here).

I tried different V9 beginning with 9.0 and all had the same behaviour.
I'm currently using 
Komodo IDE, version 9.3.1, build 88149, platform linux-x86_64. Built on Thu Nov 12 02:28:09 2015.

If You need more informations, please let me know.

Regards,  Paul Sommer

**Comment by cgchoffman** [comment]
I'm not able to reproduce this on Windows or OSX.  Maybe it's Linux specific?  Tested using a basic PHP script.

```php
<?php
echo "pizza";
?>
```

**Comment by Defman21** [comment]
Not able to reproduce on Linux with the same script. Using F5 gives me a Debugging preferences window, but I don't have to click twice to start debugging. Start Debugging without preferences (or however it's called) works fine too, only 1 click required to open the pane and start debugging (at the same time of course).

**Comment by mitchell-as** [comment]
I cannot reproduce this on Ubuntu 14.04.1 64-bit. @paulsommer could you share the script that requires two clicks?

**Comment by paulsommer** [comment]
Hi Mitchell,

Thanks for still taking care of this problem.
I am afraid, though I cannot provide a script that triggers that behaviour. I
am using Komodo for perl and PHP and every script require two clicks to start.
The first click just initializes/clears the debug pane at the bottom of the
window.
Maybe it's due to some systen configuration rather then script depending. 
Previous versions of Kommodo still run as expected.

All I can offer is a TeamViewer or vlc session so you can see and test it
yourself. If you want to try that, please tell me a time. I live in Germany and
you can roach me until midnight (we are nine hours ahead of CA-BC)

On the other hand, the problem is somewhat annoying but I got used to it
meanwhile.

Best regards,  Paul Sommer

**Comment by Naatan** [comment]
Few questions:

 * What linux distro are you using? 
 * Does it also happen on a fresh start?
 * Can you reproduce the issue in safe-mode? Help > Troubleshooting > Restart in Safe-mode.

**Comment by paulsommer** [comment]
Oh,

Only in safe-mode the error is gone.

Can it be related to the debug configuration? I'm always a bit uncertain how to
set it up, especially the remote debugging.

**Comment by Naatan** [comment]
Could be, see if using the same debug configuration in safe-mode reproduces the issue?

**Comment by paulsommer** [comment]
I will try to do that. But please give me a week as I am suffering a bad cold.
