### ISSUE TITLE
Search and Replace panel closes when all controls have been tabbed through

### ISSUE THREAD

**Issue by testworksau** [Komodo/KomodoEdit#888]
The search and replace panel will close itself after all controls have been tabbed through. It should go back to the first control in the panel.

It's a bit annoying, particularly because reopening the find dialog will clear the test you may have just entered in.

To reproduce, highlight some text, press CTRL-H, and start tabbing.

**Comment by cgchoffman** [comment]
I've seen this too.  You end up tabbing into the Editor which is odd.  Note you can prevent the Find Frame from closing by enabling "Pin the Find Frame..." in Prefs > Find.
