### ISSUE TITLE
Find Next command do not find text

### ISSUE THREAD

**Issue by eco747** [Komodo/KomodoEdit#889]
If you search something with a bad case in a file (using Ctrl+F) with the options 'case insensitive' set
ex: the text contains 'hello world' and you search 'Hello'
The text will be found.

If you dismiss the find dialog (with ESC) and then you do a 'Find next' command (F3)
The text will not be found because 'find next' do not remember the option 'case insensitive'

**Comment by cgchoffman** [comment]
I can't reproduce this.  F3 still finds "hello world" using "Hello World" as the *What*.  Are there more steps involved here?

**Comment by cgchoffman** [comment]
Please re-open if you are able to reproduce the issue.
