### ISSUE TITLE
Mako highlighting extension not working with version 9

### ISSUE THREAD

**Issue by kashifpk** [Komodo/KomodoEdit#89]
The extension is available but mako files open as text and there is no option to select mako from the available languages. Reinstalling the extension doesn't solve the problem either.

**Comment by Defman21** [comment]
It's not a Komodo problem. The extension should be modified by the author for Komodo 9.

**Comment by Defman21** [comment]
`[2015-03-30 11:35:49,705] [WARNING] codeintel.manager: error registering `/home/defman/.komodoide/9.0/XRE/extensions/mako_language@evilchuck.com/pylib/lang_mako.py' support module: could not find lexres file for Mako: `Mako.lexres' does not exist in any of the lexer dirs`
So this is a problem in the extension.

**Comment by Naatan** [comment]
Like @Defman21 said, this is a problem in the addon. You'd have to report it to the author.
