### ISSUE TITLE
File state change does not affect open file in Komodo 9.3

### ISSUE THREAD

**Issue by meheytavel** [Komodo/KomodoEdit#894]
I have an open file (lets call it example.txt) in Komodo IDE 9.3. I ran a script that changed the content of example.txt (while it was opened in Komodo). When I go and look at the example.txt file that is still open in the komodo - it is not updated.
The same, if I delete a file (through windows explorer) while it's opened in the Komodo - I'm not alerted, and if I save the file in Komodo it creates it.
this is a totally different behavior from previous versions of Komodo.

**Comment by Defman21** [comment]
`Preferences - Editor - Detect when files are changed outside the environment` (check `Show All Settings` at left bottom of the prefs window).

**Comment by meheytavel** [comment]
Got it, Thanks for your quick response.
Is there documentation of all the changes applied in version 9.3, and where each feature could be changed back to how it behaved by default in 9.2?

**Comment by Naatan** [comment]
Sorry, this is not documented. But the main thing would be the quick bookmarks (ctrl+0 through 9).

Note your issue has nothing to do with an upgrade. You may simply have toggled this by accident in the past, or toggled it to work around remote file slowing Komodo when you toggle back to it?

**Comment by meheytavel** [comment]
I upgraded my Komodo to 9.3 a week or two a go, and all my default settings changed.
Since then I'm struggling to restore them to how they were,
but thanks for the bookmark feature - it is AWESOME!!!

**Comment by Naatan** [comment]
hmm, sounds like you may have had multiple profile folders, perhaps you tried a nightly at some point.

You can find your profile folders here: http://docs.komodoide.com/Troubleshooting/Where-does-Komodo-keep-settings-data

You could simply rename your old folder to 9.3 to get your old settings back, although it would skip certain upgrade actions. I believe in this particular case you should be safe but generally it is not recommendable.
