### ISSUE TITLE
Expand recursively broken in 9.3/9.3.1

### ISSUE THREAD

**Issue by tagleader** [Komodo/KomodoEdit#898]
In 9.2, View-> Fold-> Expand Recursively, in Python, when selected at the top of a function, the entire function would be expanded.  In 9.3 and 9.3.1 build 16424 only the first level of the function expands..  I have to expand each sublevel (like 'if'  and 'for' stmts) to see the entire function.

**Comment by mitchell-as** [comment]
Hi, I cannot reproduce this. I created a simple Python file:

    def foo():
        if bar:
            try:
                baz
            except ArithmeticError:
                pass

I collapsed the lower-level folds and then the top-level fold. View > Fold > Expand Recursively worked as expected. I also tried View > Fold > Collapse Recursively and then View > Fold > Expand Recursively. That worked too. Would you please be more specific? Thanks.
