### ISSUE TITLE
Please make the bottom pane width configurable

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#90]
I need a full width bottom pane badly, otherwise the debugger is squeezed.

See:
http://forum.komodoide.com/t/how-to-set-the-bottom-pane-to-full-width/1351

**Comment by Naatan** [comment]
I'll definitely be looking into making a macro/addon for this, but this will not be a native supported feature as we would then need to maintain it and thus far there does not seem to be a lot of demand for this functionality.

Closing this as it wont be natively supported, but rest assured I will be looking into turning this into a macro/addon soon.

**Comment by cgchoffman** [comment]
Right click on the debugger tab and select *Detach pane*.  This will allow you to put it where ever you want and make it as big as you like.

**Comment by agroszer** [comment]
@Naatan thanks!, 
@cgchoffman well, detach does not really fit
