### ISSUE TITLE
Dragging text in large file while wraping long lines is tricky

### ISSUE THREAD

**Issue by goozak** [Komodo/KomodoEdit#901]
If I have the Smart Editing Preference "Wrap long lines by: Word", dragging a selected line of text can be tricky — the editor keeps scrolling even when the mouse is in the middle of the window.  The problem is intermittent: it seems to manifest when dragging a line toward the end of a large file (in my case, it begins around line 3900 of a 5000 lines file).
The problem goes away when I change the Preference to "Wrap long lines by: None".

Video of what happens with wrapping (bug) : https://youtu.be/I4wl17A85A4
Video of what happens without wrapping (expected) : https://youtu.be/7yG6rNXqoho

**Comment by mitchell-as** [comment]
Hi, thanks for the report. Unfortunately I'm not able to reproduce this with large files on my machine. Would it be possible for you to provide a file that exhibits this behavior along with the line number it happens on? Since I don't think github accepts such files, maybe you could provide the link to a gist or something? Many thanks.

**Comment by goozak** [comment]
I've sent the file to ActiveState's support email, mentioning this issue.
I've noticed that the issue manifests itself around line 5030 now.  It's the same file as my previous tests, so I'm not entirely sure why it doesn't happen at the same line number...  Anyway, since it seems elusive, I'm sure not many users will be affected by it if you're unable to reproduce it.

**Comment by Naatan** [comment]
File is in OTRS #43425 (note for us devs)

**Comment by cgchoffman** [comment]
I was able to reproduce this using Komodo.p.xul, turning on wordwarp under the View Menu, selecting some text then slightly moving my mouse down.  The screen will just scroll until i lift the mouse button or i hit to bottom of the document.

**Comment by mitchell-as** [comment]
Confirmed with the file you sent. Thanks for taking the time to do so :)

**Comment by tonyattwood** [comment]
Hi,

I was just wondering , have you ever seen something like that? Just take a look <http://famous.nofeelance.com/e4lrohy>


Yours faithfully, tony.attwood@ntlworld.com
