### ISSUE TITLE
Selected Text Char wrapping: Keep selected text selected

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#904]
I hit this last night when I was editing markdown:
I had to wrap a bunch of different lines in MD bold (ie. **text**).
It's super easy to select the text then type "*" to do the first wrapping.
The selection goes away though and you have to reselect the text to do it again.

Can we make it so the selected text stays selected?

**Comment by Naatan** [comment]
This should be a pref (not everyone will want this behaviour)
