### ISSUE TITLE
Editing xsd file results in "TypeError: 'NoneType' object has no attribute '__getitem__'" notifications

### ISSUE THREAD

**Issue by goozak** [Komodo/KomodoEdit#906]
When editing .xsd files (as XML file type), the editor shows several "TypeError: 'NoneType' object has no attribute '__getitem__'" errors.  The error shows up when the cursor is moved, either by keyboard or mouse.

(To use the 'attached' file, replace the .txt extension with .xsd)
[shiporder.txt](https://github.com/Komodo/KomodoEdit/files/45101/shiporder.txt)

Komodo IDE, version 9.3.1, build 88153, platform win32-x86.
Built on Tue Nov 17 09:49:57 2015.

**Comment by Naatan** [comment]
Reproduced

**Comment by mitchell-as** [comment]
Note, this is not limited to XSD files, but any XML files.
