### ISSUE TITLE
Integrated EditorConfig ignores .editorconfig

### ISSUE THREAD

**Issue by LaTradia** [Komodo/KomodoEdit#908]
I used EditorConfig as an add-on until KE 9.2 that worked very well. Now KE ignores everything set in `.editorconfig` file.

I run KE on 2 different Linux machines (1 VM) and the issue is present on both. I've tried to re-install KE -- EC still doesn't work.

--

Komodo Edit, version 9.3.0, build 16396, platform linux-x86_64. Built on Fri Oct 30 20:10:33 2015.

**Comment by Naatan** [comment]
Please uninstall the addon, Komodo has built-in support for editorconfig now.

**Comment by LaTradia** [comment]
Yes, I know that and I don't use EC add-on. That's why I wrote here "Integrated EditorConfig" -- I mean the built-in support for EC.

**Comment by Naatan** [comment]
Try this:

Hit Help > Troubleshooting > Reset File Preferences

EditorConfig used to override file level prefs, now it only enforces them softly. Meaning that it does not override a pref that was explicitly set on a file. By using the action I explained you reset all your file level prefs.

**Comment by LaTradia** [comment]
Sorry, no desired result.

**Comment by Naatan** [comment]
I'll try to reproduce this when I have some time.

**Comment by LaTradia** [comment]
No problem

**Comment by Naatan** [comment]
Reproduced, I'll have to revert our change that was meant to make editorconfig less forceful as there is currently no proper way to address this that wouldn't take a lot of work.

EditorConfig users will just have to use EditorConfig to make their changes to prefs that they define in their .editorconfig file. You cannot use both .editorconfig and the Komodo prefs, the former will always win.
