### ISSUE TITLE
The workspace, left, and right panes randomly open when switching tabs.

### ISSUE THREAD

**Issue by julian-karst** [Komodo/KomodoEdit#910]
Using Komodo Edit, version 9.3.1, build 16424, platform win32-x86. Built on Tue Nov

I can't easily replicate this problem, but several times a day, when I'm switching tabs, the workspace, left, and right pane will all spontaneously open.  

I can't see how to open them all at once, so I don't think I'm accidentally clicking on something or hitting a keyboard shortcut.

It's not a huge deal, but it's annoying to have to manually close them afterward.

**Comment by julian-karst** [comment]
Oops!  Never mind!

Double clicking the tab toggles it.  That explains it! :)

**Comment by Naatan** [comment]
> Oops! Never mind!

My favourite type of bug report! ;) Glad you resolved your issue :)
