### ISSUE TITLE
Variable highlighting in double quoted strings of Perl scripts (KOMODO IDE 9.3)

### ISSUE THREAD

**Issue by ko-ichi-h** [Komodo/KomodoEdit#914]
In KOMODO IDE 9.2, variable names in double quoted strings of Perl scripts like below are highlighted.

> print "printing a $variable!\n";

But they are not highlighted in 9.3.1 anymore.  It seems like 9.3 broke variable highlighting in strings, at least in Perl.

Thanks!

p.s.
I am heavily using KOMODO IDE to write Perl scripts. This is a very nice IDE and editor!

**Comment by mitchell-as** [comment]
Thanks for the report. We updated our editing component (Scintilla), which has a new Perl lexer that appears to not support the functionality you describe (but adds lots of new stuff). We'll try to address this in the future.

**Comment by mitchell-as** [comment]
It turns out Scintilla's new Perl lexer did support interpolated variable highlighting, but we were not set up correctly to use it. This is fixed now.

**Comment by ko-ichi-h** [comment]
Thank you!
