### ISSUE TITLE
Komodo Edit 9.3.1:  key command (ctrl+9) does not work

### ISSUE THREAD

**Issue by aaronELBorg** [Komodo/KomodoEdit#915]
Komodo Edit, version 9.3.1, build 16424, platform linux-x86.
Built on Tue Nov 17 17:48:33 2015.

Clicking on "word wrap" works.  Truth be told, it takes a second.  

Huge bummer.

It seems like Komodo Edit is "phoning home" during this lag.  Is it?

**Comment by mitchell-as** [comment]
You seem to be reporting multiple things. Please try to report separate issues in separate tickets. Nevertheless I will address them here:

1. Ctrl+9 does not work: please be more specific. What were you expecting? What is Komodo doing?
2. Word wrap may take some time depending on how long your lines are and how large the document is. Komodo needs to calculate how to represent lines and this is no small task for long lines.
3. Komodo does not phone home during lag.

**Comment by Naatan** [comment]
As @mitchell-as said, please open separate issues for each bug and explain them in detail.

Ctrl+9 is used to go to a quick bookmark, it will only work if you have set one (ctrl+shift+9).

I'll close this as this report is too in-concise to act on.

Note for general support on how to use Komodo you can use the forums: http://forum.komodoide.com/

**Comment by aaronELBorg** [comment]
I expect ctrl+9 to execute 'word wrap'.  It says so in the drop-menu under "View".  When I hit the keys "ctrl" and "9" nothing happens.
