### ISSUE TITLE
Komodo Edit 9 keeps crashing

### ISSUE THREAD

**Issue by cweis88** [Komodo/KomodoEdit#916]
Just downloaded Komodo Edit 9 for Mac and it keeps crashing every time I open it. Any ideas?

**Comment by mitchell-as** [comment]
What version of Mac OSX are you running on? Komodo requires 10.9 minimum.

Have you had a previous version of Komodo on your system? If so, you might need to remove any existing profile folders to ensure you are starting from a clean slate. Please remember to make backups if necessary. The location of your profile folder is described here: http://community.activestate.com/faq/komodo-file-locations.

The link above also describes where to find Komodo's log file (pystderr.log). That log file may also aid in troubleshooting. Please post the entire contents of that log if you are unsure.

Thanks!

**Comment by Defman21** [comment]
#1007

**Comment by cgchoffman** [comment]
I think this can just be closed.  The user doesn't seem interested in solving the issue and we can't do anything about it without their participation.  Same comment from #953: https://github.com/Komodo/KomodoEdit/issues/953#issuecomment-249287320
