### ISSUE TITLE
Screen flicker on OS X 10.9

### ISSUE THREAD

**Issue by hauke28** [Komodo/KomodoEdit#919]
Komodo-Edit 9.3.0 and 9.3.1 shows a screen flicker from time to time, which is annoying. It seems not to be related to any user interaction and also occurs when the window is simply inactive on the screen. Komodo-Edit 9.2.1 does not have this problem. 

I use an iMac 27" with Mac OS X version 10.9.5.

**Comment by cgchoffman** [comment]
This is already being tracked #293. Thanks for reporting.

**Comment by hauke28** [comment]
I don't think it is the same as #293. I my case it does not have anything to do with scroll bars, it affects the whole window (at least it looks like that). And I have not seen bursts of flickering, it is just one short flicker. And it affects the main window (I do not use diff in Komodo-Edit).

**Comment by Naatan** [comment]
@hauke28 if you read the next post it says that the ticket does not have anything to do with scrollbars either, I was just checking if it did :)

**Comment by cgchoffman** [comment]
It's also been determined that is not just the diff window.  It's basically any scintilla view from what I can tell.

**Comment by mitchell-as** [comment]
Just a follow-up @hauke28: please see my comment in #293: https://github.com/Komodo/KomodoEdit/issues/293#issuecomment-161088848 (at the time of writing it's at the bottom of the ticket). We have identified the issue and are working to push out a resolution shortly. Thanks again for the report.
