### ISSUE TITLE
Trying to close a split window tab causes an exception and fails

### ISSUE THREAD

**Issue by srgloureiro** [Komodo/KomodoEdit#92]
As you can see in the screenshot:

![exception window tab] (http://i.imgur.com/ed1yY50.png)

Note: before this I tried to drag the ColorThemes.xml file to the first tabs group, and those "unknow" tabs where unduly created by the dragging actions.

**Comment by Naatan** [comment]
You seem to be using some type of macro/addon. Komodo does not natively support more than 2 split views.

**Comment by srgloureiro** [comment]
Wrong. It is just Komodo 9 Edit. If if is an Add-on, it is "from factory" or some remainder of the Komodo 8 installation. I didn't install anything

**Comment by cgchoffman** [comment]
Could you confirm by starting Komodo withCould you confirm by starting Komodo with a clean profile?
- shutdown Komodo
- set the KOMODO_USERDATADIR environmental variable in commandline
- start Komodo from that same commandline window.
- Try to reproduce the issue.
It's never been possible to have more than two split views in Komodo, natively any way.  Perhaps you are not aware that Komodo will import addons from your previous install?  If you used Komodo 8 then Komodo Edit 9 will import your profile from 8, including addons a clean profile?
- shutdown Komodo
- set the KOMODO_USERDATADIR environmental variable in commandline
- start Komodo from that same commandline window.
- Try to reproduce the issue.
It's never been possible to have more than two split views in Komodo, natively any way.  Perhaps you are not aware that Komodo will import addons from your previous install?  If you used Komodo 8 then Komodo Edit 9 will import your profile from 8, including addons

**Comment by Naatan** [comment]
Komodo 9 inherits settings from Komodo 8.

There simply isnt a way to have 3 split views in Komodo, it's not supported. Your issue is with an addon, which we unfortunately cannot really address here.

If you can provide a list of your installed addons I'd be happy to help you narrow down the culprit, but I'm closing this issue as its not an issue on our end.
