### ISSUE TITLE
HDPI issues on Gnome

### ISSUE THREAD

**Issue by Jiehong** [Komodo/KomodoEdit#922]
Hello,

Today, installing Komodo Edit 9.3.1 on my Archlinux with Gnome is far form usable, because a lot of the elements of the UI is not of the correct size.

My screen resolution is 2880×1800, and I haven't changed settings related to font in Gnome, Gnome Tweak Tools or Komodo itself.

Here is full screen capture (look at it in fullscreen):

![komodo_hdpi](https://cloud.githubusercontent.com/assets/1061229/11513217/3c2bf09c-9872-11e5-8619-ca298040b4ad.png)

As you can see, multiple things are wrong:

- Top toolbar and icons are too small, as well as the tab bar;
- Font is crazily huge (but preferences say it's size 11);
- Left bar is more or less ok, but icons are tiny.

I think Komodo has serious issues with higher dpi.

While trying to fix it, I came up with this moderate improvement:

- set layout.css.devPixelsPerPx to 2.0;
- set font size to 6;

You can see the result here (look at it in fullscreen again):
![komodo2](https://cloud.githubusercontent.com/assets/1061229/11513432/686726da-9873-11e5-83e9-90097490bea4.png)

But, still:

- Icons are larger but blurred;
- Lines numbers and lines heights are still huge;
- Completion pop-up still tiny (not on the capture).

Could you please have a look at this issue?

**Comment by Naatan** [comment]
Thanks, we have an existing bug for this here: #160. Thank you for providing additional details. 

For what it's worth the main issue is the font scaling set in gnome. If you set this to 100% (default) your issues should go away.

**Comment by Jiehong** [comment]
No, because the font scale is set to 1.0 according to Gnome Tweak Tool. I didn't have to change it since it's working fine everywhere, except Komodo.

**Comment by Naatan** [comment]
Alright, I guess that workaround isnt relevant if your actual display is HiDPI.
