### ISSUE TITLE
Fuzzy matching in code-intel (autocomplete)

### ISSUE THREAD

**Issue by geoken** [Komodo/KomodoEdit#928]
There's already a request asking for this in a limited scope in php files (https://github.com/Komodo/KomodoEdit/issues/616). 

I think it should be universal in all languages. This is how it works right now in most other popular editors. Sublime, VS, Atom, Brackets, the JetBrains apps, etc. Fuzzy matching seems to be enabled in every major code editor. 

It's helpful to me with CSS, for example, where I can complete border-left by typing in "bl" in most editors but in komodo I need to type out "border-l". 2 keystrokes vs 8 keystrokes is a huge savings factored out over the development of a normal sized website.

Emmet is usually suggested when this comes up by It's more of a passable workaround than a solution.

**Comment by mitchell-as** [comment]
Thanks for your suggestion.

**Comment by cgchoffman** [comment]
I would love to see this in CSS for sure.  Can we bump this into 10.1?  Or would this be an 11 feature (based on amount of work).

**Comment by mitchell-as** [comment]
We can investigate for 10.1, but no guarantees.

**Comment by mitchell-as** [comment]
I've taken some time to investigate this and it will not be easy. Our code intelligence was not built with fuzzy matching of top-level completions in mind (e.g. CSS border-left or Python built-in functions, PHP top-level namespaces, etc.). It would require some pretty major surgery of all of our codeintel engines to support top-level fuzzy matching.

For secondary-level completions (for lack of a better word...), it will be much easier. (e.g. `object.`[completions]) Codeintel only evaluates the lower-most "object"/"thing", gets all possible completions, and then forwards those to Komodo for display. Then as the user types, Komodo updates the list with something that matches. The way I see fuzzy matching working is for Komodo to "filter" the original completion list given by codeintel as the user types. For example, given `object.` and possible completions being "[foo, bar, baz]", when the user:

* initiates autocompletion with `.`, they are presented with [bar, baz, foo] (alphabetic order)
* types `a`, the list filters out "foo" and the completion list is now [bar, baz]
* (if the user backspaces, the list returns to [bar, baz, foo])
* types `az`, the list filters out "bar" and the completion list is now [baz]

Right now Komodo just changes the selection in the completions list to whatever the user types, retaining all completions that may not begin with the typed text.

I think we can do a "hybrid" type of fuzzy matching for 10.1 (this will not involve touching codeintel at all), but full fuzzy matching would have to go into 11, and even then will require significant effort.

@Naatan @cgchoffman let me know how you want to proceed with this ticket and/or re-milestone as appropriate.

**Comment by cgchoffman** [comment]
It looks like CSS functions more like the secondary-level you describe.  If I do the following
```
blah {
    b|
}
```
I'll get the entire available list of styling but the first item starting with a "b" will be selected.  Is it possible to have any char act like the "." in your example above?  It would be like "." after `sys.` in Python.

Any way, even secondary level completions would be awesome but the fact that fuzzy matching only works there could be really confusing and very annoying to users who don't ask (most won't) why they can't filter code intel results triggered by the "3 char" trigger.

**Comment by mitchell-as** [comment]
@cgchoffman Yes I think you're right about CSS completions behaving like secondaries. It appears the "hybrid" fuzzy matching would work in that case.

As for having any character act like ".", that is pretty much what I mean by invasive surgery to the codeintel engines -- each language behaves differently. Take Perl. If I type "ch", I get a list of completions starting with only "ch". I'd have to modify the Perl codeintel to retrieve all top-level completions.

I agree with your last point. Ideally it's all or nothing.

**Comment by Naatan** [comment]
@mitchell-as could we extend symbols.db to have more context and thus be the source for fuzzy matching?

**Comment by mitchell-as** [comment]
@Naatan no because we do not index the stdlibs for languages. There's also the topic of imports. In Python for example, you only get completions for what you import. The symbol browser would have no knowledge of this.

**Comment by mitchell-as** [comment]
I've been experimenting more with some sort of fuzzy matching in autocompletion lists and I have some mixed results.

When I try `bl` in CSS, as suggested by the OP, I get this:

![1](https://cloud.githubusercontent.com/assets/12902397/17108418/6043a67e-5261-11e6-9bdb-e932b66e229b.png)

Clearly there is a "b" and an "l" in that result, so there's no "bug".

I'll try something more explicit: `bleft`:

![2](https://cloud.githubusercontent.com/assets/12902397/17108436/87dbf98e-5261-11e6-94e9-97956a2853a7.png)

Hmm, that didn't work either. How about `borleft`?:

![3](https://cloud.githubusercontent.com/assets/12902397/17108455/9e617788-5261-11e6-85fd-bea489bc26fc.png)

It's closer, but still will require more key presses to get what you really want.

I will admit that with my tests, the autocomplete list is not filtering down results. In the three examples I tried there are still items in the autocomplete list that do not fuzzy match the input. It will require work to filter them out, but the three examples I gave should show that it is very likely the arrow keys will still have to be used to get what you want.

Also, you might suggest filtering on "word characters" -- that is, `bl` should really mean find a `b` followed by an `l` when that `l` follows a non-word character. Obviously this is a CSS-specific thing. Other languages would not benefit from such a thing. Configuring language-specific delimiters like this would be complex and error prone.

Then there's the topic of highlighting in bold the characters that end up matching. (In the first example, it's not perfectly clear that the selected option truly does fuzzy match `bl`.) That may not be straightforward.

The conclusions I'm drawing from this are that it is probably too much work to go into 10.1 and would require some engineering decisions anyway. I'd like to move this back into the backlog.

Note to self for future reference:

koScintillaAutoCompleteController.js adds the following in the `if (aPrefix) {` block in the `show()` function:

```
      let pattern = new RegExp("^" + aPrefix.split("").reduce(function(a, b) {
        return a + "[^" + b + "]*" + b;
      }));
```

along with

`        if (pattern.test(string)) {`

and

`          if (pattern.test(this._searchStrings[index])) {`

in the appropriate places.

An idea for highlighting matches in bold would be to have

```
      let pattern = new RegExp("^" + aPrefix.split("").reduce(function(a, b) {
        return "(" + a + ")[^" + b + "]*(" + b + ")"; // e.g. (a)[^b]*(b)
      }));
```

and iterate through the capture positions to know which substrings to highlight in bold.

**Comment by Naatan** [comment]
Moved it to 11 so we can make a decision on this by then.

**Comment by mitchell-as** [comment]
Moving milestone to 11.x.x. With the recent codeintel refactoring, I think the pieces are in place for this to be added as a preference.

**Comment by Naatan** [comment]
Yep, I wanted to add it for 11 but ran out of time :(

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoIDE/commit/09ddd887e0682c9ad7afdefb85caf0bb533c3d0e
