### ISSUE TITLE
Project Menu Ghosting on New Blank tab after opening project

### ISSUE THREAD

**Issue by lxrocks** [Komodo/KomodoEdit#930]
I find some of the GUI behaviors on OSX to be a little annoying at times  on v8 so fired up the free trial to check it out. 
The Project menu remained painted on the screen - that's probably not good.

After opening a new project, via the Project drop down - the drop down remains drawn on the blank new tab. 
Komodo IDE, version 9.3.1, build 88153, platform macosx.
Built on Tue Nov 17 11:36:24 2015.

![screen shot 2015-12-04 at 1 06 11 pm](https://cloud.githubusercontent.com/assets/10369910/11580127/674a37bc-9a88-11e5-9761-8df289857fb9.png)

![screen shot 2015-12-04 at 1 12 13 pm](https://cloud.githubusercontent.com/assets/10369910/11580173/b6fda488-9a88-11e5-972a-b1cb8f68b2a1.png)

**Comment by cgchoffman** [comment]
I can't  reproduce an issue with the Project Popup menu.  It's not clear to me what you're seeing and your screen shots aren't showing anything.

Are you able to consistently reproduce this?  And if yes, could you be more specific of what you're clicking on?  Also provide a screenshot of the issue if you can.

**Comment by lxrocks** [comment]
I can see the screenshot - here is a screenshot of what I see.

![screen shot 2015-12-04 at 1 30 24 pm](https://cloud.githubusercontent.com/assets/10369910/11580397/36a7db70-9a8b-11e5-9d08-ea8ff567ac26.png)

**Comment by Naatan** [comment]
I don't quite understand the screenshot, it's just a screenshot of our quick launch page? This is shown whenever you open a new tab or don't have any tabs open.

**Comment by mitchell-as** [comment]
The quick launch page is designed to be there when there are no open files, even after you've created a new project.
