### ISSUE TITLE
CSS syntax errors only show on last character

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#931]
Eg. 

```
foo { bar: "foobar" }
```

The "r" in "bar" will be marked, whereas it should be the whole world.

**Comment by mitchell-as** [comment]
This is how the Mozilla CSS reporter reports the error. Here's the Python representation:

    entry: {u'columnEnd': 9, u'severity': 1, u'columnStart': 8, u'lineEnd': 1, u'lineStart': 1, u'description': u"Unknown property 'bar'. "}
