### ISSUE TITLE
All projects gone after update from 9.2 to 9.3.1

### ISSUE THREAD

**Issue by antongorodezkiy** [Komodo/KomodoEdit#934]
Hello guys,

After I updated from 9.2 to 9.3.1 I got few problems. I updated through the komodo's update dialog. 

1. All projects gone from the projects list
1. Key bindings scheme was set to Default
1. Appearance theme was set to "Auto detect skin"

---

Komodo Edit, version 9.3.1, build 16424, platform linux-x86_64. Built on Tue Nov 17 17:48:34 2015.

OS: Ubuntu 14.04.3 LTS ( Linux moonlight 3.13.0-68-generic 111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux )

**Comment by Naatan** [comment]
Sounds as if Komodo inherited the wrong profile, for whatever reason. You can find your old profile folders here, see if that helps: http://docs.komodoide.com/Troubleshooting/Where-does-Komodo-keep-settings-data

Did you maybe have IDE installed as well?

**Comment by antongorodezkiy** [comment]
@Naatan 
renaming .komodoedit/9.2 folder to .komodoedit/9.3 folder solved the issue.

> Did you maybe have IDE installed as well?

Nope
