### ISSUE TITLE
trial

### ISSUE THREAD

**Issue by roamy** [Komodo/KomodoEdit#939]
so i downloaded your trial and it would not even open a project - so I shitcanned it and went back
to PyCharm

**Comment by Naatan** [comment]
Really there isnt much for us to go on here. Thanks for stopping by and giving some unbiased input I guess?

**Comment by roamy** [comment]
it is simple - I have a couple of django projects and i could not open either one.

**Comment by Naatan** [comment]
Please explain "could not open". 

 - What steps did you take? 
 - What did you expect would happen? 
 - What happened?

**Comment by roamy** [comment]
selected open project
scrolled to project 
the ide would not give me the option to open
did not see a import option either

**Comment by Defman21** [comment]
You don't understand how projects works. A Project in Komodo is a `.komodoproject` file in the root of a project directory. Just create a new project for any of your django thing ("Project - New Project")  and then you will able to open the project and configure it as you want (set the interpreter, indentation settings, etc.). Next time if you want to restore the environment you set up for your project - just open the project.
For those types of questions please use our forums:
http://forum.komodoide.com/

Best regards.

**Comment by Naatan** [comment]
Please check out this screencast, it explains projects: http://komodoide.com/screencasts/projects-and-what-theyre-for/

Unfortunately your explanation is still too basic for me to understand what you are doing or what you are expecting. Please provide as many details as possible.

Keep in mind every editor/IDE is different and while there are similarities in the way "Projects" work they are not exactly the same. If they were all exactly the same then there'd be no point to there being different editors/IDEs.

**Comment by cgchoffman** [comment]
> and then you will able to open the project and configure it as you want

More to this, Komodo will automatically scan the files in the root to give you code intel.  There is no additional configuration unless you have code outside the project root.

> Thanks for stopping by and giving some unbiased input I guess?
Also that... haha.  We're totally open to UX/UI/any feedback but there are better ways to provide that feedback.
