### ISSUE TITLE
Toolbar buttons toggle/save/persist inconsistently

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#94]
This code needs some refactoring, it is too unreliable.

**Comment by cgchoffman** [comment]
Do you want to close issue 80 for this one?  Or patch 80 and save this for later?

**Comment by Naatan** [comment]
Ah yeah lets close #80, this should address that and other similar issues. Better to fix the leak than to keep putting down buckets.

**Comment by 2114L3** [comment]
#172 minimap issue still exists in 9.3.2

**Comment by Naatan** [comment]
This issue has not been resolved, so yes it would still exist.

**Comment by cgchoffman** [comment]
I think this is fixed.  I can't reproduce any of the linked tickets.
