### ISSUE TITLE
Documents becoming blank after updating to 9.3.1

### ISSUE THREAD

**Issue by timarcosdias** [Komodo/KomodoEdit#940]
Hi, guys. I'm using Windows 10 and everytime I update to 9.3.1 my documents just gets blank. I already closed all the docs and opened new ones but all I see is a blank screen. Did anyone get the same problem? Thank you.

**Comment by cgchoffman** [comment]
Need more info:
- "everytime I update to 9.3.1 ", please elaborate.  Updating should only happen once.  Do you mean that you have reinstalled multiple times?
- "I already closed all the docs and opened new ones":  So you never tried reopening the same documents?
- When do the documents become blank?  At start up?  After editing?  When switching between files in Komodo?
- what in your logs? Help > Troubleshooting > View Log File

I'm not aware of any one else reporting this.

**Comment by timarcosdias** [comment]
* Yes, I reinstalled the software multiple times (three times, I think).
* Yes, I tried to open the same documents, I tried to create new documents and I tried to open other documents.
* After updating, my documents remain open, so I try to edit any of them, writting or deleting something and the whole document tab becomes blank, so I switch to another open document and the screen is still blank. The same happens if I try do create a new document.
* [My Log File](https://drive.google.com/file/d/0B-o7cbXh05v_RXBHZEJxR3F6b2c/view?usp=sharing)

Thanks.

**Comment by Naatan** [comment]
Does `Help > Troubleshooting > Restart in Safe-Mode` resolve your issue?

**Comment by timarcosdias** [comment]
Sorry for my late reply. It doesn't help. The program restarted, the new tab was good, but the "Open file" windows is blank and any new file I create is blank too and I can't see what I write there. 

Thanks.

**Comment by timarcosdias** [comment]
It just works with: `set KOMODO_USERDATADIR=%TEMP%\ko`

**Comment by Naatan** [comment]
Ok so a clean profile does work then. Were you using a non-default color scheme or possibly an addon that could be causing issues?

**Comment by timarcosdias** [comment]
No, that was a clean installation. The other day Komodo showed me an error message 535 saying "codeintel" failed to start. I don't really know if that was the cause.

**Comment by mitchell-as** [comment]
It's likely you had a profile from an earlier install that, when loaded, caused the problems you are experiencing. That would explain why things work when you temporarily changed the Komodo profile directory.

Whenever you perform a "clean install", the profile directory remains, so tha term may be misleading.

Also, if you see an error message like that about codeintel failing to start, please feel free to grab the error log and let us know. Thanks.

**Comment by mitchell-as** [comment]
This appears to be resolved. Please correct me if I'm wrong.
