### ISSUE TITLE
keyboard buffering?

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#941]
Komodo IDE, version 9.3.2, build 88190, platform linux-x86_64. Built on Mon Dec 7 04:23:16 2015.

Since the recent update to the above I get the following effect.
Scrolling down in the editor is pretty slow (that's not new).
So I keep holding the down arrow for a while, my repeat KB repeat speed is pretty fast.
Before the update when I released the down arrow scrolling stopped. With the above nightly it keeps scrolling for a while, till the buffer is exhausted.

**Comment by Naatan** [comment]
Give the changes we have made in Komodo 9.3.2 this is more likely the screen drawing being behind. We do not buffer keyboard input events except for some very niche cases (eg. when you are typing while opening the find dialog).

@mitchell-as can you confirm my suspicion? I guess there wouldn't be much we could do in terms of small fixes?

**Comment by agroszer** [comment]
Whatever it is, it is super annoying.

**Comment by mitchell-as** [comment]
I am not able to reproduce this with a relatively large file. Do you have word wrapping enabled? What kind of file is it? Komodo may also be doing something in the background which contributes to the lag.

The behavior you described seems pretty standard among applications -- they attempt to process events as they come in, but if they cannot process them as quickly as you give them, there will be a lag until they catch up.

**Comment by agroszer** [comment]
see wonders, restart helped
