### ISSUE TITLE
Preview should auto-update and scroll.

### ISSUE THREAD

**Issue by garretwilson** [Komodo/KomodoEdit#945]
On Windows 10 I turned on HTML preview in a split screen for my XHTML5 file.
1. Unfortunately when I scroll down in the XHTML5 source code, the preview doesn't scroll accordingly.
2. When I edit the XHTML5 source code, the preview isn't updated automatically until I save the document.

I note that HTMLKit, for example, auto-updates after edits, even without saving.

Without these features, embedded preview is of little use. I might as well open up an external browser.

**Comment by Naatan** [comment]
Thanks for filing this Garret! :)

**Comment by Defman21** [comment]
Syncing the scroll between the code and the preview could not be possible at all, your styles could override the height attribute for any element while the "height" of your code could be much smaller (in px).

**Comment by garretwilson** [comment]
I wasn't expecting syncing to involve calculating the pixel extent of various components. I would expect most browser APIs to have a feature for "scroll to this location in the DOM". You could even do it in JavaScript and be somewhat cross-browser compatible. There are lots of ways to approach this.

Note that there are two features here; @Naatan , should we break these out into two bugs? The auto-update feature perhaps should get higher priority, but they both are important for real preview editing.

**Comment by Naatan** [comment]
This will be resolved in the new preview feature, tracked here - #2844
