### ISSUE TITLE
Codeintel doesn't work after switching project

### ISSUE THREAD

**Issue by Zent0** [Komodo/KomodoEdit#946]
Hi,

in all my projects i've set in preferences the "PHP Directories" to the root of my project.
But every time i switch my project, codeintel stops working. It doesn't matter how long i wait.
Most time i need to remove the "PHP Directories" and add it again or i need to delete the codeintel db to get it to work again.

Alex

**Comment by mitchell-as** [comment]
Do you get any popup notifications that an error happened? Would you please post the contents of your log after a project switch? (Help > Troubleshooting > View Log File). Thanks!

**Comment by Zent0** [comment]
Hers my logfile. I switched the project at 10:42
[komodo.txt](https://github.com/Komodo/KomodoEdit/files/61008/komodo.txt)

Additional information: I've already reinstalled Komodo Edit an deleted all files in AppData,

**Comment by mitchell-as** [comment]
Unfortunately there's nothing in the log file to go on...

In the AppData directory there is a "codeintel.log" file. Would you please post the contents of that after switching projects?

For what it's worth I am not able to reproduce this. I have created two separate projects, which have two separate PHP directory includes as project preferences. Switching between both projects still gives me the correct codeintel for files in the differing PHP directory includes.

**Comment by Zent0** [comment]
Unfortunately there's no new entry in this file when switching project.
The last entry is from yesterday.

[codeintel.txt](https://github.com/Komodo/KomodoEdit/files/62202/codeintel.txt)

I think i will try again to reinstall and delete all AppData and the Project files.

**Comment by cgchoffman** [comment]
> Unfortunately there's no new entry in this file when switching project

@mitchell-as doesn't codeintel debugging need to be turned on first?

**Comment by mitchell-as** [comment]
Error messages will show up regardless of the debug option @cgchoffman .

**Comment by Zent0** [comment]
@mitchell-as I've figured out that I need to wait 15-20 minutes. After this time, it works without an interaction by myself. But it think this long time isn't normal?

**Comment by mitchell-as** [comment]
Hi @Zent0 it sounds like you have a large project that Komodo is re-indexing. I see this occasionally as well when initially loading a project (but not switching). If you close the current project, restart Komodo, and then open the other project (basically switching, but with a restart in-between), does that help speed things up? If not, then I don't think there's anything that can be done :(

**Comment by tonyattwood** [comment]
Hey,

I  was looking  for something  an I've suddenly came accross that thing, jeez... you  have to take a look <http://fair.robertcampbellphoto.com/e4rcwi>

tony.attwood@ntlworld.com
