### ISSUE TITLE
wish: spell checking, add word to ignored words with key binding

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#947]
Go to the highlighted word, now the context menu has suggestions.

Would be great to have an option to add the word to ignored words fast...

**Comment by mitchell-as** [comment]
Thank you for the suggestion!

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoIDE/commit/5aca051598da641f970e7fdd1c939ceb05e94ce5
