### ISSUE TITLE
Editor pane flickering

### ISSUE THREAD

**Issue by shelldweller** [Komodo/KomodoEdit#949]
I upgraded yesterday to the latest Komodo (`Komodo IDE, version 9.3.1, build 88153, platform macosx.
Built on Tue Nov 17 11:36:24 2015.`) The editor pane keeps flickering approximately each 10 seconds. This was not happening prior to upgrade. [Here's the video in Google drive](https://drive.google.com/file/d/0BwMWnjS7boykNVR2UTBQdUd2M2s/view?usp=sharing).

My OS X version: 10.9.5.

**Comment by shelldweller** [comment]
You can't see flickering when watching it on Google, you need to download the original.

**Comment by cgchoffman** [comment]
This is fixed in the latest nighty. http://downloads.activestate.com/Komodo/nightly/
