### ISSUE TITLE
Optimize file polling on Komodo re-focus

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#95]
Reference: http://forum.komodoide.com/t/komodo-9-hanging/1343/10

When Komodo gets focus it checks up on all the opened files, if these files are on a remote server then this hangs Komodo until it's done.

We need to either perform this check on a separate thread or space out the checks so they dont all happen at the same time.

Is it even worth checking all files? It might be better simply to check the currently open file and then check individual files as they are switched to. This would only really affect remote files and I would imagine most people using those arent editing them from several locations at once, and when they are the individual check should suffice.

**Comment by cgchoffman** [comment]
"and I would imagine most people using those arent editing them from several locations at once" wouldn't this be the only time someone would be editing a file from multiple locations?  If we can dump the check in a separate thread that would probably be better.

**Comment by Naatan** [comment]
I'm sure it happens, I don't think it happens often / in most cases though.

Using a separate thread would be ideal but may not be as easy as you'd think since we're using Watchdog. We'd have to dig and find out where the hang occurs before we can make a decision on this.

**Comment by toddw-as** [comment]
If Komodo automatically detected when a file was on a network share (implemented on Windows, but not Mac/Linux), it should solve most of this issue:
https://bugs.activestate.com/show_bug.cgi?id=79589
and background (threaded) checks are probably wanted too.

**Comment by cgchoffman** [comment]
I think this can be closed in favor of https://github.com/Komodo/KomodoEdit/issues/1959
