### ISSUE TITLE
update availible showing wrong update

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#950]
Updated my beautify js addon, updated version numbers inside addon to 1.3, but when i install the addon i get a update available message, when i click on it, it want to update from 1.3 > 1.0. 
Am i doing something wrong here or this a bug?

**Comment by Naatan** [comment]
Thanks @babobski, that's pretty bad. I'm patching our server code to only offer up the latest version as an interim solution.

**Comment by Naatan** [comment]
May take a while (hours) before I can get this interim solution deployed, we're having some network issues due to a recent server move.
