### ISSUE TITLE
Find (and replace) dialog disappears on blur

### ISSUE THREAD

**Issue by orangeaid** [Komodo/KomodoEdit#951]
A very inconvenient feature of recent versions of Komodo IDE is that the Find(/Replace) UI no longer appears in a separate window.  This means that if you move the focus away from the editing window for the file in which you initiated a Find(/replace) action, the UI disappears.  Therefore one has to start all over again - which is particularly frustrating with complex regular expressions, for example.  I often want to look elsewhere when I am deciding what to search for, and replace with.  Now this results in the values that I have already entered being lost.  It also means that we no longer have the convenience of a persistent window - accross multiple files - which allowed us to perform the same search in a different file, without needing to re-enter the search criteria.  The new Find(/Replace) UI is definitely a step backwards in terms of ease of use and convenience - in my opinion.  Perhaps not a "Bug", in the strictest sense (assuming that the disappearing of the Find(/Replace) UI on blur was a deliberate feature), but definitely a new inconvenience, in my view.

**Comment by orangeaid** [comment]
Sorry - I now have discovered that I can get the functionality that I desire by using the Find > Find Frame > Pin the Find Frame preferences setting.  Therefore I shll close this issue.
Apologies again!

**Comment by Naatan** [comment]
For what its worth; we'll still be improving this functionality in future versions. There are indeed some issues around regex and focus loss.

**Comment by orangeaid** [comment]
Nice one Nathan - good to hear.

Simon

**Comment by orangeaid** [comment]
Oops! Naatan, I mean  :-)
