### ISSUE TITLE
9.3.1 Random Crashes on Windows 10

### ISSUE THREAD

**Issue by LeeroyJenks** [Komodo/KomodoEdit#953]
I keep getting random crashes when using Komodo on remote files (may happen on local files too, not sure).
Most recent error log attached.
Any more info I can give?
[pystderr.txt](https://github.com/Komodo/KomodoEdit/files/61507/pystderr.txt)

**Comment by Naatan** [comment]
Any consistency in the crashes? Steps to reproduce?

**Comment by LeeroyJenks** [comment]
Sorry. Nothing I can reproduce directly. I'm in a place with spotty internet, not sure if the disconnect of the internet is having and effect on the local files.
Also not working on one specific type of file. Sometimes it's css, other times php.

The only steps I can give are:
- open remote file (css or php)
- type

It's not consistent enough to have more than that sorry. I was hoping the log files would help.

I did, however, transfer Komodo over from another computer.
The Komodo directory has two "9.3" directories within it, one of which was created after I transferred. If I can delete that, I'll go ahead and see if that was causing the issue.

**Comment by cgchoffman** [comment]
> I keep getting random crashes when using Komodo

Could you elaborate on what you mean by this?  Does the program crash and close?  Does it hang?  Do any messages dialogs appear?

**Comment by LeeroyJenks** [comment]
I get the "XXX Stopped Working" dialogue from windows as it attempts to "find a solution" before closing.

**Comment by Naatan** [comment]
> I keep getting random crashes when using Komodo on *remote files*
> I'm in a place with spotty internet

That could be more than just correlation. Do you experience crashes when you are on a stable connection?

**Comment by LeeroyJenks** [comment]
I believe I have, hard to say.
Sorry for such little help. Just wanted to report it with the log file in case it was something obvious.
You can close this issue out. If it happens again I'll log the status of everything at the time.
Thanks for the quick responses!

**Comment by Naatan** [comment]
Unfortunately the log does not help :\ Please report any future info on this same ticket. I'll leave it marked as pending for now.

**Comment by LeeroyJenks** [comment]
Thanks Naatan!

**Comment by Defman21** [comment]
#1007

**Comment by Defman21** [comment]
Oops, sorry. I believe there's a bug report for foreground crashes as well.

**Comment by Naatan** [comment]
#1007 is specifically about background crashes on OSX. It's not a catch all for crashes.

**Comment by Naatan** [comment]
Komodo IDE 10.1.2 is [now released](http://activestate.com/blog/2016/11/komodo-ide-1012-released), including a potential fix to this issue.
