### ISSUE TITLE
typo on docs

### ISSUE THREAD

**Issue by pacav69** [Komodo/KomodoEdit#955]
http://docs.komodoide.com/Manual/extensions

the text reads 
Feature Addons
The best way to start creating a new Komodo feature is by utilizing the Komodo usersciprt system, 

There is a mispelling of 'usersciprt' should read 'userscript'

**Comment by cgchoffman** [comment]
@pacav69 if you login to the site (docs.komodoide.com) using github you can patch the docs in the site.  We review any changes.  Otherwise I can certainly update this since I'm the one who wrote that misspelling :P Let me know what you decide to do.

**Comment by pacav69** [comment]
I tried logging in and i get an authentication failure so please correct it yourself

**Comment by cgchoffman** [comment]
K.  FYI. That's likely because your email is private on Github.

Fixed spelling error, thank you. http://docs.komodoide.com/Manual/extensions#komodo-addons_feature-addons

**Comment by pacav69** [comment]
you removed the hyperlink which was correct

**Comment by cgchoffman** [comment]
I'm not seeing this.  I didn't change the hyperlink.  I only changed the text that was wrong.  Hyperlink works fine for me.

**Comment by pacav69** [comment]
its working now

**Comment by cgchoffman** [comment]
OK, glad you figured it out.
