### ISSUE TITLE
Authentication failed while trying to login to http://docs.komodoide.com

### ISSUE THREAD

**Issue by pacav69** [Komodo/KomodoEdit#956]
While trying to login to http://docs.komodoide.com
Authentication failed
Insufficient data from authentication provider, name not provided or empty

even though i have made my email address publc

**Comment by Naatan** [comment]
Hmm, seems to be the same issue as mention here:

https://github.com/FreeRADIUS/freeradius-server/issues/168#issuecomment-12332873

Could you ensure you have both a name and email set in your github profile?

**Comment by pacav69** [comment]
That fixed by putting my name in the correct position and ensuring that my email was the correct one
