### ISSUE TITLE
KomodoEdit uses inconsistent data directory

### ISSUE THREAD

**Issue by garretwilson** [Komodo/KomodoEdit#958]
Somehow KomodoEdit has managed to create two different data directories on my Windows 10 machine:

    %AppData%\ActiveState\Komodo Edit
    %AppData%\ActiveState\KomodoEdit

There must be a typo in some configuration somewhere. Please use references in your configuration scripts to prevent these inconsistencies and typos.

**Comment by cgchoffman** [comment]
Hi @garretwilson,  that's a mozilla artifact.  Mozilla uses it in it's own special way.  The Komodo user data is stored where is always has been (since Komodo 5 any way...i think), in the Komodo[IDE|Edit] folder.
