### ISSUE TITLE
RLang support

### ISSUE THREAD

**Issue by jacoby** [Komodo/KomodoEdit#96]
I wrote an add-on to bring in RLang syntax highlighting (https://github.com/jacoby/RLangSyntax). I have since moved to another editor for my day-to-day, so I was surprised by a user asking for help getting my add-on working.

(https://www.dropbox.com/s/qrkdevn26kqc6e4/r_language-0.1-ko.xpi?dl=0 , and yes, I should have it somewhere else, too)

I suppose the "bug" is that Komodo doesn't have R in the "View as Language" menu, but mostly I'm wondering how to modify my project to make it work with 9.0.

**Comment by Naatan** [comment]
There were no specific changes around language support, could you please detail what the exact issues are that you're running into?

**Comment by jacoby** [comment]
When I try to install the package, I get an error like this:

![r_language_9 0 0](https://cloud.githubusercontent.com/assets/56015/6901281/3eff42ba-d6da-11e4-8160-efd960b41997.png)

(Not my screen capture, my user's, but I get the same on Linux.)

The process might not have changed recently, but I created this over a year ago. 

I'd like to see R added as a built-in language. Failing that, I'd love it if someone took over support, as I have moved to another editor. But, as a final fallback, I'd like to see documentation on how to build an xpi so I can get my project up to 9.0.0 standards.

![selfie-0](http://i.imgur.com/iVUQWYc.png)

**Comment by Defman21** [comment]
Change `8.*` in https://github.com/jacoby/RLangSyntax/blob/master/install.rdf#L18 and https://github.com/jacoby/RLangSyntax/blob/master/install.rdf#L26 to `9.*`. Next navigate to the folder with the source of your add-on and run `<path to komodo dir>/lib/sdk/bin/koext build --unjarred`

**Comment by cgchoffman** [comment]
Yep, that should do it def man.  This should have been opened in your issues jacoby ;)  Please close this issue if defman21's comment resolves the issue.

**Comment by Naatan** [comment]
I asked him to report it here since it sounded like it could be an issue in Komodo. But yeah, should just be a case of updating your install.rdf.

**Comment by jacoby** [comment]
That's a fair amount of d'oh! Seems like a simple fix, which revealed missing/misnamed udl files, which I've fixed. Now reading docs to koext to give it the right name. Thanks.
