### ISSUE TITLE
tools -> addons no longer works (build 88153)

### ISSUE THREAD

**Issue by hlslaughter** [Komodo/KomodoEdit#964]
tools -> addons now brings up the 'go to anything' search box rather than addons.

**Comment by cgchoffman** [comment]
Hey @hlslaughter, this is the new addons tool.  If you want to use the old one you can access it through the new JS console: http://docs.komodoide.com/Manual/Komodo-Packages#komodo-packages_accessing-the-old-addon-manager

I highly recommend you use the new Commando tool though.  We've phased the old Mozilla addons dialog out.

**Comment by cgchoffman** [comment]
Note, it's not just Addons now.  It's any tool that you can install into Komodo.  The old dialog was holding us back.  http://docs.komodoide.com/Manual/Komodo-Packages#komodo-packages_what-are-packages.

**Comment by hlslaughter** [comment]
So where do you go to enable/disable addons/extensions/plugins/etc...

**Comment by hlslaughter** [comment]
The use case here is this:

TODO helper plugin no longer works after upgrade.
I want to go to the plugin "homepage" or something to see if it's been deprecated or if I need to do something. 

I rely on this functionality and have been using it for years and I've got no options here other than the ability to reinstall it (which fixes nothing)

**Comment by cgchoffman** [comment]
- Ctrl + SHift + O (opens commando)
- Packages (6)
Then you can use Manage Packages to *Update Packages* or *List Installed, Reinstall.*

**Comment by scholer** [comment]
+1 for how frustrating this is try try to figure out. Not intuitive at all. 
Still haven't figured out how to install new packages.
If it is not possible to install add-ons, maybe add a note about how to do that for new users?

**Comment by Naatan** [comment]
Agreed the UX needs work. But you can install packages just fine from within Komodo. Hit ctrl+shift+o (or cmd+shift+o on OSX) and navigate to the "Packages" scope.
