### ISSUE TITLE
"cmd_dedent": [ "Shift+Tab" ] Throws Exception

### ISSUE THREAD

**Issue by seattledeveloper** [Komodo/KomodoEdit#966]
The following is a screenshot of an exception I've been getting lately when trying to do an dedent.  Single or multiple lines selected.  Just restart Komodo and still getting error.

![shift-tab-exception](https://cloud.githubusercontent.com/assets/9749337/11857666/28de9cd0-a40f-11e5-9f62-9498bda28aa4.png)

Komodo IDE, version 9.3.1, build 88153, platform win32-x86. Built on Tue Nov 17 09:49:57 2015.

Thanks in advance for checking this out.

**Comment by Naatan** [comment]
Does this happen on all files at all times or just in certain scenario's? 

Can you share your error log after reproducing the bug? Help > Troubleshooting > VIew Log File.

**Comment by seattledeveloper** [comment]
This is one of those frustrating ones, like the noise in the car.  It only happens sometimes.  But it was pretty consistent yesterday, which is why I entered the bug.  It's not happening this morning, but I'll keep an eye out and send the error log when it happens again.

**Comment by seattledeveloper** [comment]
This just happened a few minutes ago, this time on a block indent attempt.  Attached is the log file dump.

[komodo_indent_dedent_log.txt](https://github.com/Komodo/KomodoEdit/files/68841/komodo_indent_dedent_log.txt)

Hope this proves to be helpful.

**Comment by mitchell-as** [comment]
Thanks for the report. It is most helpful!

**Comment by mitchell-as** [comment]
Note to self, in koLanguageCommandHandler.p.py:1979, when `sm.indent` is zero, that means Scintilla is using `sm.tab_width`. Use the non-zero value.
