### ISSUE TITLE
after update got orange dotted border on focus in start screen

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#967]
After the update to the latest nightly,when i press a button or select, and the focus state get triggerd.
I got a strange orange dotted border arround my button
![snap 2015-12-17 at 07 47 59](https://cloud.githubusercontent.com/assets/3530262/11863219/8262a066-a492-11e5-9e06-826f2e862ec6.png)

**Comment by mitchell-as** [comment]
Hi, this is just an indication that that button has focus if you were to press the "Enter" key (rather than clicking with the mouse). It's no different from Ubuntu highlighting the currently focused button in a dialog.

**Comment by Naatan** [comment]
And just to expand on that; this was added because we have had some complaints from keyboard driven users where they could not see what the focus was set to on HUD elements.

**Comment by babobski** [comment]
Ah thanks, than i understand why this is, one thing i noticed that on some button's this is double bordered, is this intended to be like this?
![snap 2015-12-17 at 19 42 18](https://cloud.githubusercontent.com/assets/3530262/11878574/f0a592cc-a4f6-11e5-86a1-798a2736b0dc.png)
And also noticed i can jump around with the `tab` key, but was especting that i could go back when i press `shift + tab` but this isn't the case, is this the default behavior?
