### ISSUE TITLE
Komodo - 

### ISSUE THREAD

**Issue by johngilbrough** [Komodo/KomodoEdit#969]
I installed Komodo Edit and few days ago and have really been struggling with it.  I've recorded 21 different bugs, some serious - what do I do with them?  And is there anything like an IRC channel for Komodo that people watch?  One of my major problems is having to use root to either launch komodo or to open another file because of the permission bugs.

**Comment by Naatan** [comment]
Please file bugs on the bug tracker here, each in their own bug report. 

We hang out on irc - #komodo on irc.mozilla.org. Note that the holidays are upon us though, so we may not be around to answer questions. The forums would be a better place to ask them: http://forum.komodoide.com/

As for your permission issue, sounds like you started Komodo using sudo, so now your profile files are owned by root rather than your own user. To fix this execute 

`sudo chown -R myusername.myusergroup ~/.komodoedit` 

Replace myusername and myusergroup with your username and usergroup. Don't use sudo to start Komodo again, it will mess up your file permissions. In general you do not want to be using sudo unless you understand the consequences.

Closing this as it is not actually a bug report.

**Comment by johngilbrough** [comment]
Nathan -

I've got 55 Komodo 9.3 bugs to report.  Are you asking that I create 55
different emails?  How about I just send you the list for now and then you
let me know what to do.

======================

Positive things with Komodo 9.3:
* It looks like you've got the line selection & moving working great.
* Just figured out that a ^+ increases the size of the line # font so it's
visible.
* the "comment" command produces a '# ' which looks good.  Whoops, stopped
looking good (back to a single #).
* alt-up and down arrow to move one or more lines very well
* you have a delete-line command
* configurable key bindings
* search for configuration settings
* It's looking like the completions are working


Komodo 9.3 bugs:

Komodo will not launch unless it's root.  Otherwise we get:
(process:4784): GLib-CRITICAL **: g_slice_set_config: assertion
'sys_page_size == 0' failed
Error: Access was denied while trying to open files in your profile
directory.

komodo: error: could not open
'/home/john/.komodoedit/9.3/commandments.fifo' for writing - at least this
time they told us what file they can't access.

Selecting multiple lines by dragging through the line numbers is a crap
shoot that works about half the time.  Same is try when dragging right in
front of the lines - sometimes it selects and sometimes it cancels the
select in progress.  Even shift-select has stopped working.

Can we do better than "syntax error" for Python syntax errors?

Enter a find string - then choose whole word or not - but there is no
choice.

I'm on a 100-line source program towards the bottom, I start to enter the
variable name "urlpatterns".  As soon as I type the "l" that part of the
source dives off the bottom of the screen where I can no longer see it.
I've been using an <esc> to rescue when this happens.

At first I thought there were no menus.  Then I found them all in one box
in the upper right corner.

Komodo-edit ALWAYS ends with a random failure code rather than a zero.

Drag through text to select it, then right click in order to copy but the
right click cancels the selection.

Can barely see text you are selecting.

The tab contrast that lets you know which file is active is barely
discernible.

Line numbers are far too small to be read and there is no way to fix them.

Now and then for no reason, a number of panes within the komodo window open
up and one has to close them all manually.

Are bookmarks disappearing?

Go to Line # - the field contrast - same color as page - really hard to see.

Selecting one or more lines and then dragging no longer works.

Shift-tab no longer reduces indentation when an indention error is involved.

The whole Find/Replace mechanism has come apart.  There's no way to know
what state it is in (whole word, case sensitive, etc).  The previous
approach worked well.

As the find/replace mechanism is unreliable, we're using another editor to
do this part of the work but that is destroying the bookmarks.

Could not use open dialog to open /scripts/align - just hung up.

What are the random icons on the tabs?

Alt-A no longer works for replace all.  There is no key binding for replace
all.

We no longer have highlighted matching braces - at least I cannot see them.

I keep selecting the PyWin32 language which keeps disappearing.

root's preferences keep getting discarded (but not the color scheme).

How does one list out the key bindings that they've done?

It would be good if you could show the # of matches in the find box.

Every time I do a search/replace, a window opens up below with all the old
strings - how to keep this from happening?

On the left edge, if I type in "names" and then press the tab key, the
cursor does not move, I have to press the tab again - very weird.

Manually searched through the menu for "Toggle Bookmark" only to find that
the shortcut is not shown.

When one uses the incremental search, there is no way they can tell what is
being selected - (the matching color is the same as the background color)

The path displayed in the lower left corner of the window shows
"(root)/home/john..." - remove the "(root)", it is incorrect.

I would expect an incremental search to use the same states as the regular
search - but that doesn't appear to be the case - I want to incrementally
search for the whole word "roots" - cannot do it.  If I incrementally
search "roots", I get "roots", "rootsabc", etc.

I double click on the misspelled word "aamougst", expecting to right click
and select "spell checking" - doesn't work - as soon as you right click,
the selection disappears.  You cannot double click and right click anything.

I type "root = argument" and then press the return.  The cursor remains
after the word "argument".  I have to press the return again to get it to
drop to the next line.

I double-click and right click to check spelling - won't work - selection
gets destroyed.  So I use the upper-right menu to find the spell-checking
selection - but IT DOES NOT HAVE THE SHORTCUT.

More frustration on the Find dialog.  I kept screwing with it until it
would only search for the whole word "root", like I wanted.  I then scroll
back to the top of the page so I can start searching from there and, damn,
the Find dialog disappeared.  When I re-enter "root", it's back to
searching for "roots" again.

I'm on a word and I press control-H.  That word does not get placed in the
Find field.

I'm trying to search from the top for a something.  I've entered the search
criteria into control-H.  I then click on the top line to position the
search there, but the control-h business disappears.  What to do?

Suggestion - when a new search target is found, blink it twice.

Bookmarks could stand out more (like before).

Key bindings won't list.  And we only want to see the ones we changed/added.

You can barely see the right scroll thumb as there's no contrast.

Syntax error clear delay is way too long.  Should be more like a 1/4 second
rather than 2-3 seconds.

Shift-tab does not reduce the indention unless cursor is at the beginning
of the line?

Control-Z undoes but Shift-Control-Z blows up.

I drag my cursor through the line numbers in order to select some lines but
it doesn't work.  You have to do it twice.  But then DO NOT RIGHT CLICK as
that will destroy the selection.

Does not take focus when another application opens a Komodo document.

Welcome to Komodo banner comes up randomly and with it the business about
helping Komodo with statistics.  Damn - there goes the preferences again!

I have a Komodo error dialog but I cannot select the words (which is
dumb).  It's something about "restoring the backup".  This dialog is
missing the checkbox that says "Don't show this again".

**Comment by Defman21** [comment]
>Komodo will not launch unless it's root. Otherwise we get: (process:4784): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed Error: Access was denied while trying to open files in your profile directory.

Not a problem. If you've ran Komodo as sudo, then your profile is bad-chmoded. Run `sudo chown $USER:$USER ~/.komodoide/ -R && sudo chmod 777 -R ~/.komodoide/` to fix it.

>komodo: error: could not open '/home/john/.komodoedit/9.3/commandments.fifo' for writing - at least this time they told us what file they can't access.

Above.

>Line numbers are far too small to be read and there is no way to fix them.

Just change the size of `linenumbers` element in Color Scheme - Common Syntax.

>Shift-tab no longer reduces indentation when an indention error is involved.

Already filed #966 

>What are the random icons on the tabs?

What tabs? Can you give us a screenshot? If you're talking about file tabs - those icons shows you type of file.

>We no longer have highlighted matching braces

You can set any color you want for them. Color Scheme - Common Syntax - `bracehighlight` element.

**Comment by Naatan** [comment]
Unfortunately, yes it would have to be reported each in a different ticket. This is how bug trackers work, if we were to start tracking 55 bugs all in one ticket I guarantee that the process would be absolutely impossible. 

There is some very useful feedback there but I am afraid on almost all of them I would need to ask for more information. Also a lot of them aren't bugs at all but just general questions. I'm really more than happy to help you with these but you need to report them properly or post them on the forums in the case of general questions, otherwise they simply are not addressable in a meaningful way.
