### ISSUE TITLE
Komodo 9 Codeinteligence UpperLetters bug dont fixed

### ISSUE THREAD

**Issue by MironMironMiron** [Komodo/KomodoEdit#970]
dont fixed this in 9.3.2: 
https://github.com/Komodo/KomodoEdit/issues/870

make some directory with lowerlUpper letters.
and try. 

hm .... 

i fix this problem so. But i have to do this all time when i reinstall komodo :/

i modifi function normcase in two files. and add check: if this is windows - dont normase file location path.
(meby wy dont need normacase locations in this functions, i dont work width linux ant other platforms)

fix1:
ActiveState Komodo Edit 9\lib\mozilla\python\komodo\codeintel2\oop\driver.py

![driverrr](https://cloud.githubusercontent.com/assets/15866713/11927758/86043da4-a7d7-11e5-9ab1-e98267b0522a.png)

-comment return normacase. and just return path.

ActiveState Komodo Edit 9\lib\mozilla\components\koCodeIntel.py

![kocodeintel](https://cloud.githubusercontent.com/assets/15866713/11927084/77a51fa8-a7d2-11e5-8657-9f42229f132e.png)
- add check from driver.py to normcase functio in koCodeIntel.py. if windows return path withou normcase.

Problem is:
1) when codeinteligence scann all files in directories it scann dirs width lowellUpper leters.
2) when file changes are saved in db imediatly kodeIntel  normase path 

and so we have 2 path. 2 blob files. and codeinteligence dont work

i just disable normacase when filechanges are saved in db in windows  imediatly. then.
1) when codeintel scann all files dirs have lowwerUpper letter
2) when filechanges saved in dirs  imediatly have lowwerUpper letter

i thing you fix this in second update .... 

meby you find better solution to fix this path problem

**Comment by mitchell-as** [comment]
I'm not sure I understand the problem. Are you saying you updated to Komodo 9.3.2 and the issue of mixed-case paths is still present?

**Comment by MironMironMiron** [comment]
yes still presents. i add code examples how i fix this insune.  

ok in codeinteligence informationa about class and functions added two ways.

1) - when codeinteligence scann all dirs and files.
2) - when file is changed.

when codeinteligence snann all dirs in db creates two files:
1 - path
2 - *.blob

in path we have path to the folder width lowerUpper letter
in blob we have info about class

when file is changed in db creates two files: path and *.blob
and in path we have lower letters ... 

what you neet to do. when file is changed. in db. file path. mus have lowerUpeer letters.

in my examples i chek if this is windows and then i dont use normcase function in path.

**Comment by MironMironMiron** [comment]
meby so:

when codeinteligence scann all dirs and files: all works good. 
in db creates path file. if edit this file there is path to folter: C:/pathToFolder example.

but when file is modificated. before scanin or after scaning. in db creates path file. 
and if you edit this file path example: c:/pathtofolder. is width lowwer letters.

**Comment by MironMironMiron** [comment]
problem: when file is modificated. id db. in file path. writed normcase path.
example: c:/pathtofolder

but when is scann all dirs path file is C:/pathToFolder

in my exmaple i disable normcase path when file is changed.

**Comment by MironMironMiron** [comment]
when scann all dirs: path is corect.
![path1](https://cloud.githubusercontent.com/assets/15866713/11950117/22a70c02-a88e-11e5-81aa-51ff2c62c507.png)

but when i change file creates anothrer path file and dir:
![path2](https://cloud.githubusercontent.com/assets/15866713/11950152/75ac56f0-a88e-11e5-9dfc-539f65c7c820.png)

ant we have in db two dirs.

**Comment by mitchell-as** [comment]
Thanks for the followup and all the additional information!

**Comment by mitchell-as** [comment]
Note: this will likely be fixed by our scheduled architecture changes in 11.

**Comment by mitchell-as** [comment]
This should be fixed in Komodo 11.
