### ISSUE TITLE
Feature Request: Autocomplete and Calltips for HTML inside PHP variables

### ISSUE THREAD

**Issue by seattledeveloper** [Komodo/KomodoEdit#974]
Hello,

I would like to request a feature that I am used to from the (very old) HomeSite, my editor of choice until switching to Komodo.  They recognized HTML tags anywhere within the code structure, and added Autocomplete/Calltips accordingly.  Here are some screenshots:

Simple string declaration:
![inline-string](https://cloud.githubusercontent.com/assets/9749337/11965937/2349df08-a8ad-11e5-939f-da4f2d6fcb6a.png)

String declaration, with double quotes escaped:
![escaped-string](https://cloud.githubusercontent.com/assets/9749337/11965953/41da3a26-a8ad-11e5-82c2-760a11f5c853.png)

And in a heredoc:
![heredoc](https://cloud.githubusercontent.com/assets/9749337/11965957/4826249e-a8ad-11e5-8171-43be947a040d.png)

I think this is the feature I miss the most.  Please consider adding it to Komodo.

Thanks!

**Comment by seattledeveloper** [comment]
I didn't remember that you had renamed https://github.com/Komodo/KomodoEdit/issues/761 to mention both the syntax highlighting and the coloring.  If you wish to close this item, you can, although I'm now thinking that these may be two different tasks -- don't know if the autocomplete/calltip feature is easier or more difficult than the syntax highlighting, but it is one that I'd definitely appreciate seeing completed sooner than the other.  This would be more useful to me for sure.

**Comment by mitchell-as** [comment]
Thanks for the suggestion! This request is separate from #761, so I'll leave it open. At first glance this looks to be very difficult due to the way our codeintel works. I'm going to file it into our backlog and we'll have to revisit to see if this is really worth our time given our resource allocation.

**Comment by seattledeveloper** [comment]
That is unfortunate, but thanks for keeping this open and being willing to consider it at a future date.  Interesting -- I was mentioning this feature to a developer I work with and he said "That would be an awesome feature. I haven't seen that in any modern IDEs. That would get me to switch to Komodo for sure."  Thanks again.

**Comment by mitchell-as** [comment]
After a more in-depth investigation, I've determined this is out of scope for our code intelligence. The screenshots and examples given are not really "intelligent" completions from our perspective, as PHP strings are just sequences of characters. It is true that in the given context, those completions appear to work well, but PHP can also be within CSS and JavaScript, and the level of difficulty really increases trying to handle those cases.
