### ISSUE TITLE
new find / replace pane tab order, hotkeys

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#975]
Looks like the default control is "Find", then match case, match whole words, etc. comes, then "Replace" later.
When the whole thing was a dialog, the tab order was "Find", then "Replace", everything after that.

BTW, are there hotkeys for match case, match whole words, etc. ?

**Comment by mitchell-as** [comment]
Hi, are you using the latest 9.3.2 version? Tabbing through the pane gives me Find and then Replace. I do not believe there are any hotkeys for find options though. Our devs that would know for sure are on holiday at the moment.

**Comment by agroszer** [comment]
yep, sorry

Komodo IDE, version 9.3.2, build 88190, platform linux-x86_64. Built on Mon Dec 7 04:23:16 2015.

talking about this pane:

![screenshot - 12232015 - 07 43 29 pm](https://cloud.githubusercontent.com/assets/350912/11982670/80fe3be8-a9ad-11e5-904e-02506cba8eca.png)

**Comment by mitchell-as** [comment]
Okay, thanks for the follow up. We'll take a look.

**Comment by Naatan** [comment]
> BTW, are there hotkeys for match case, match whole words, etc. ? 

I seem to recall there's an enhancement request open for this, but I can't seem to find it right now. @cgchoffman do you remember what it's called?

**Comment by cgchoffman** [comment]
I'm not able to reproduce this issue @agroszer.  Tabbing through fields works in the correct order for me. Find > Replace > Where > Mark All > Replace > Replace all > Includes.  That is for Find/Replace in current doc.

What command are you using to open the Find Dialog?
Have you tried this in SafeMode?

@Naatan I'm not aware of an enhancement request to add hotkeys for the enable buttons but it's a good idea.

**Comment by agroszer** [comment]
Here you go:

https://youtu.be/ty6w7LIFijo

I opened the pane with shift+ctrl+f which is bound to "Find: Find in Files..."

**Comment by Naatan** [comment]
Please update to 9.3.2, this was an issue that was only present in 9.3.0 and 9.3.1.

**Comment by agroszer** [comment]
This is Komodo IDE, version 9.3.2, build 88190, platform linux-x86_64. Built on Mon Dec 7 04:23:16 2015.

**Comment by agroszer** [comment]
aha build 88191 needed

**Comment by Naatan** [comment]
Now you know what that 1 commit did :p
