### ISSUE TITLE
Not able to create a file from template

### ISSUE THREAD

**Issue by PsionTheory** [Komodo/KomodoEdit#977]
Bad bug, i can't start a new file from template (no templates work)

**Comment by mitchell-as** [comment]
Hi, I can create files from PHP templates and Ruby templates to name a few. I don't know what kind of template you are trying to create, but any more information would help me diagnose the issue you are experiencing.

**Comment by cgchoffman** [comment]
Hi @PsionTheory, we're not able to reproduce this.  We need you to provide more information.
- Operating system and version
- File you're opening
- Contents of **Help > Troubleshooting > View Log File**
- any other errors that might be displayed

- Carey
