### ISSUE TITLE
Opening a project in a new window loads the wrong "places" view

### ISSUE THREAD

**Issue by tprocter** [Komodo/KomodoEdit#98]
Environment: Windows 7 x64, Komodo IDE 9.0

In projects, right-click on a different project and select "Open project in a new window".  
Expected result: The "places" sidebar loads the folders for the opened project.
Observed: Sometimes, the "places" are displayed for the wrong project, seemingly the last project that was previously closed.  Double-clicking the current project reloads the places sidebar correctly.

**Comment by Naatan** [comment]
Duplicated of #3
