### ISSUE TITLE
Autocomplete for php/laravel not working for typed method parameters

### ISSUE THREAD

**Issue by verybigelephants** [Komodo/KomodoEdit#980]
hello, i have been sent here to submit a bugreport from [komodo forums](https://github.com/Komodo/KomodoEdit/issues/new). the issue goes like this:

let's assume you are editing a function inside a class that has a typed parameter, like this

    // a specific example of "table migrations" of laravel framework    
    public function up(){ 
        Schema::create('test', function (Blueprint $table) {
            $table->string('testtest'); //you get no hints for the ->string from the Blueprint class here
        }
    }

the problem is that when you start typing $table->s... you get no autohint on public function "string" of the class "Blueprint", even though if you go to the Blueprint in the function parameters and jump to definition by pressing ctrl+j, it successfully opens the file with all of its methods listed

**Comment by mitchell-as** [comment]
Thanks for catching this case!

**Comment by verybigelephants** [comment]
cool, thanks! will try komodo out again later
