### ISSUE TITLE
Smart Wrap Selection Does Not Work for 'Shift'ed Delimiters

### ISSUE THREAD

**Issue by mitchell-as** [Komodo/KomodoEdit#986]
The fix for ignoring Ctrl keys and smart wrap selection accidentally ignores Shift keys also. As a result, *, ", (, {, etc. delimiters cannot be used.

**Comment by mitchell-as** [comment]
Note to self: views-editor.p.xml:2411

**Comment by we3geeks** [comment]
@mitchell-as Thanks for fixing this. I thought I was going crazy...

**Comment by stramin** [comment]
@mitchell-as How can I have this fix please?

**Comment by Defman21** [comment]
Wait for the first nightly :)

**Comment by stramin** [comment]
Oh, ok... I has been waiting for this feature for 3 years, I think i can wait for 1 year more.

**Comment by Defman21** [comment]
Not for a year but for a week I guess 😊

**Comment by stramin** [comment]
That's a good new! thank you

Its a version 10 nightly? or 9.3.3?

**Comment by Defman21** [comment]
9.3.3

**Comment by mitchell-as** [comment]
Hi @stramin I think we did some internal nightlies recently that may have this fix: http://downloads.activestate.com/Komodo/nightly/komodoide/latest-9.3.x/. Yes it says 9.3.2, but it should contain many fixes up to the beginning of March (this one included).

**Comment by stramin** [comment]
Thank you so much mitchell-as! I going to download it now :+1:

**Comment by tonyattwood** [comment]
Hi,

I just wantet to tell  you  how much I appreciate all  you're doing for me, and I'd  like to share with you something really important,  please read it  here <http://experience.stupray.com/e4ctjac>

Bests, tony.attwood@ntlworld.com
