### ISSUE TITLE
Resizing is very laggy when an editor buffer is open

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#989]
If it sounds like something you won't understand without explanations, I'll explain it for you :)

I'm experiencing lags when resizing left pane and have any code opened (so Komodo renders Scintilla part on each resize iteration I guess?), but if I don't have any files opened (only New Tab) - there are no lags. I don't know what's going on there, but I guess when you're resizing a pane in Komodo, it re-renders Scintilla part on each resizing iteration and it doesn't cache the render (so Komodo won't render my code again until the resizing operation is done). Commando helps me in this situation sometimes when I don't need panes being opened and resized, but it's not my default UI. In big projects I have left pane opened and sometimes I need to resize it and those UI lags makes me crying a lot (I'm joking, but I hope you understand my pain).

Here's what I have:

* Komodo IDE, version 9.3.2, build 88191
* Ubuntu 15.10 (I had the same lags when I was using Debian 7 with nVidia 8800GT and proprietary drivers installed)
* AMD R9 280X with fglrx 15.201.1151 installed

So, do you know any solutions/workarounds? Or is it just XUL and there's nothing to optimize?

**Comment by mitchell-as** [comment]
There's really nothing we can do here. I see a bit of lag myself, but I'm not sure if it's due to the whole UI resizing or Scintilla itself. (For example, the breadcrumbs seem a bit sluggish as they collapse and expand into the dynamically changing space. This is completely subjective though.)

If you toggle the visibility of the left pane on and off there is no lag. I only see it when I'm using the mouse to drag and manually resize the pane. This shouldn't happen very often in practice.

Closing ticket.

**Comment by Defman21** [comment]
So even if komodo will replace breadcrumbs and scintilla with placeholders, it would lag?

**Comment by mitchell-as** [comment]
No, I'm saying it's possible the breadcrumbs are contributing or causing lag themselves. If you replace breadcrumbs and scintilla with placeholders (blank space), the lag might go away.

**Comment by Defman21** [comment]
Will try to remove breadcrumbs with CSS.

**Comment by Naatan** [comment]
I tried removing both breadcrumbs and scintilla but it was still laggy. I'm running i3 though which may contribute.

@Defman21 let me know how you fare.

**Comment by Defman21** [comment]
Would you share the CSS styles? I don't want to boot into Linux for now.

**Comment by Defman21** [comment]
Nvm, it's not something that I'm able to reproduce on Windows. I'll load into Linux today and try.

**Comment by Naatan** [comment]
I just used DOMi. No custom styles.

**Comment by Defman21** [comment]
Tried. Still bad. If your file is not big (about 20-30 lines), it works not that good but not that bad. If it's bigger, lags are seems to be bigger as well. Tried to disable syntax checking & higlighting by setting file type to Text, but that doesn't work. So the only one way to fix that is hiding scintilla wrapper with `display: none` (in this case Mozilla engine does not use any resources to render an element) and show something over it (maybe the screen of code?). The latest thing is not necessary, I assume it's too much to do.
