### ISSUE TITLE
Open Files Cog Menu - double ticks

### ISSUE THREAD

**Issue by adzchappers** [Komodo/KomodoEdit#990]
Silly little bug. When I click the cog in the files pane, I get double ticks on the displayed menu - bugging my OCD! ;-)

![screen shot 2016-01-07 at 09 32 34](https://cloud.githubusercontent.com/assets/611127/12167018/aeaa63a8-b521-11e5-8979-7d908a70d5de.png)

**Comment by Naatan** [comment]
Are you using a custom skin or iconset?

**Comment by adzchappers** [comment]
Fresh install.

**Comment by Naatan** [comment]
Are you using the latest version? 9.3.2

**Comment by adzchappers** [comment]
Komodo Edit, version 9.3.2, build 16460, platform macosx. Built on Thu Dec 10 19:37:46 2015.

MAC OS X Yosemite 10.10.4

**Comment by cgchoffman** [comment]
Have you used Komodo Edit at any time before this?  Komodo might be importing old settings that you're not aware of so a "Fresh Install" is possibly not actually what you're running

**Comment by Naatan** [comment]
Just tested Komodo Edit 9.3.2 on OSX, seems to work fine for me.

Try Help > Troubleshooting > Reset UI setup

**Comment by adzchappers** [comment]
Tried that, doesn't make a difference, also tried reset everything, still getting double ticks.

Yes I've used Edit before, having a look in ~/Library/Application Support/KomodoEdit, I have 6.0, 6.1, 8.0, 8.5, 9.1, 9.2, 9.3 

I ahve uninstalled and reinstalled 9.3 and still have the same issue.

Regards, Adam.

**Comment by Naatan** [comment]
Does `Help > Troubleshooting > Restart in Safe-mode` fix it?

**Comment by adzchappers** [comment]
Nope.

**Comment by cgchoffman** [comment]
Can you try that step manually? [Start Komodo with defaults settings](http://docs.komodoide.com/Troubleshooting/How-do-I-Start-Komodo-with-Default-Settings#how-do-i-start-komodo-with-default-settings_start-komodo-from-a-temporary-profile_mac-osx).  No one else has reported this since 9.3.2 came out and none of us on the dev team can reproduce it.
