### ISSUE TITLE
Dedent is not a word

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#991]
"Dedent" is not a word. "Unindent" is. 

http://forum.komodoide.com/t/unindent-menu-option-rename/2417

**Comment by Naatan** [comment]
I don't disagree that unindent is a better word, but this is so very minor.. so PRs welcome :)

**Comment by seattledeveloper** [comment]
Personally, I like outdent better (https://en.wiktionary.org/wiki/outdent) but I don't know if it is a "real" word either.  Dedent sounds too close to what a dentist might do. :).  Interestingly, none of these words, including unindent, are in Chrome's spell checker.

**Comment by Defman21** [comment]
I like outdent because it's shorten than "unindent" and it's easier to read for me. But I'll have a look at both words, just to check if they are ok with UI.

> so PRs welcome :)

I'll do a PR of course ;)

> Interestingly, none of these words, including unindent, are in Chrome's spell checker.

The same in Firefox, m8y.

**Comment by Naatan** [comment]
To be clear, PRs for unindent are welcome. Outdent has the same problem as dedent. Both sound wrong.

**Comment by Defman21** [comment]
Ah, okay then :)

**Comment by seattledeveloper** [comment]
After thinking about this more, I agree with Nathan.  Unindent is really clear. My apologies if I messed things up by posting my original comment. That was definitely not my intention.

**Comment by Defman21** [comment]
@Naatan you can remove "PRs-welcome" label, this is a part of IDE, no way to fix this via a PR.

**Comment by xspokex** [comment]
I completely disagree. In Croatian dedent is amazingly accepted word. For example:
"Deder dedentaj mi to!"
It is just amazing!
If you changed it to lame "Unindent" I will post counter bug report!

**Comment by Naatan** [comment]
It's done! If you post a counter bug report I will close it! :p
