### ISSUE TITLE
Can't seem to remotely edit a file imdb.pm

### ISSUE THREAD

**Issue by VeNoMouS** [Komodo/KomodoEdit#993]
If I try open a remote file it just doesnt open... nothing happens no errors..

if i open another file and try saveas imdb.pm it generates this error...

```
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIDocumentService.createDocumentFromURI]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: vieweditor :: saveAsURI :: line 1503"  data: no]

Exception: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIDocumentService.createDocumentFromURI]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: vieweditor :: saveAsURI :: line 1503"  data: no]

Traceback:
saveAsURI@vieweditor:1503:30
saveAsRemote@vieweditor:1412:19
viewManager.prototype.do_cmd_saveAs_remote@chrome://komodo/content/views.js:1917:4
xtk.Controller.prototype.doCommand@chrome://xtk/content/controller.js:91:8
command_doCommand@chrome://komodo/content/library/commands.js:263:0
command_doCommandAsync/<@chrome://komodo/content/library/commands.js:220:12


Komodo Edit, version 9.3.2, build 16460.
Built on Thu Dec 10 22:21:38 2015.
```

**Comment by VeNoMouS** [comment]
If i move the file to different directly, i can open it, how ever... i cant press enter or use arrow keys in code... i can type... but thats all...

**Comment by VeNoMouS** [comment]
deleted prefs, and seems to work again... so that ticket that people keep raising that you keep closing this isnt fixed..

**Comment by mitchell-as** [comment]
Would you please reference that ticket(s)? Thanks!

**Comment by VeNoMouS** [comment]
ie #217

**Comment by Naatan** [comment]
I'll reopen that ticket and close this one. Please see my response there. 

> so that ticket that people keep raising that you keep closing ..

It was closed only once, and that was automatically by a commit. Far as we knew it was resolved.

**Comment by VeNoMouS** [comment]
There are other tickets relating to same thing, I found them simply by googling the error code...

**Comment by cgchoffman** [comment]
Same thing Mitchell already said: Would you please reference that ticket(s)? Thanks!
  It's pointless for us to search and guess what you're talking about @VeNoMouS 

I assume you're referring to `0x80004005` which is as the Mozilla documentation states: 
> NS_ERROR_FAILURE (0x80004005)
> This is the most general of all the errors and occurs for all errors for which a more specific error 
> code does not apply. 

So taht's not very helpful :(
ref: https://developer.mozilla.org/en-US/docs/Mozilla/Error
