### ISSUE TITLE
Screenshot outdated on repo

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#994]
The screenshot currently shown in the readme of this repo is outdated, current version shown is 8.5.
Missing the new file icons in the screenshot, and the screenshot shown is from Komodo IDE and not edit.
Also missing some reference to Komodo IDE in the readme.

**Comment by Defman21** [comment]
#420

**Comment by mitchell-as** [comment]
Thanks for catching this!

**Comment by Naatan** [comment]
Thanks @babobski, all good points :)

**Comment by Defman21** [comment]
I really like how it looks like on komodoide.com (3 screenshots in one)
