### ISSUE TITLE
Komodo Ignores *Allow file contents to override...* indentation pref

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#995]
http://forum.komodoide.com/t/komodo-picks-up-file-indentation-prefs-regardless-of-existing-settings/2428

- set global prefs for indentation to...see screenshot
![capture](https://cloud.githubusercontent.com/assets/655154/12211892/55c34586-b619-11e5-9f2a-065051162cd4.PNG)
- create a file outside of Komodo with the following content:
```javascript
var x={
        y:2
    }
```

- Open the file in Komodo
- go to end of file and press tab

Expect: a two space width tab
Actual: Cursor jumps 8 spaces

Notes:
- File level prefs reflect global (so no idea where this is being saved)
- This is tested from a fresh profile
- Changing the file contents (4 spaces in front of **y** instead of 8) and reopening the file changes the indenting setting.

**Comment by Naatan** [comment]
> Expect: a two space width tab

Do you mean two tabs? Ie. you're not saying two space characters and a tab right? :p

Given that your space per indent is set to 2 and it is inserting 4 per indentation it seems to me that the pref is working fine, the problem appears to be that it's detecting 4 spaces where it should be detecting a tab.

**Comment by cgchoffman** [comment]
> Do you mean two tabs?

Why would I expect two tabs?  I hit tab once. I expect one tab that is two space wide but I got 8 spaces.

> your space per indent is set to 2 and it is inserting 4 per

Where is the 4 coming from?

**Comment by Naatan** [comment]
Ahh I missunderstood what you meant by "a two space width tab".

**Comment by Etenil** [comment]
I'm experiencing this issue also. The only way I found to reset the IDE's idea of the file's identation setting is to edit the file preference setting and tick "Prefer tab characters over spaces", apply, then untick it and apply again. After this, Komodo IDE will indent with spaces without fail.

Of course it isn't very nice to have to do this repeatedly, so I hope this gets fixed in the next release.

**Comment by tribis** [comment]
Thank you for your suggestion, it helped me to get indentation back to some kind of sanity. The trick only works for me when changing the setting, closing the file, then reopening it and changing again
