### ISSUE TITLE
Cannot save files in non-UTF8 encoding

### ISSUE THREAD

**Issue by vsespb** [Komodo/KomodoEdit#997]
Getting the following message when trying to save some files.
![screenshot from 2016-01-10 23 18 15](https://cloud.githubusercontent.com/assets/1210230/12223759/8cd668e0-b7f0-11e5-9b3f-ad7a6b285a80.png)

Restart does not help. Have no idea why some files affected, some not. File perms are ok.

Komodo Edit, version 9.3.2, build 16460, platform linux-x86_64. Built on Thu Dec 10 19:37:22 2015.

*UPD*: Ok, I get it. Everything that is not UTF-8 cannot be saved. I.e. files in Latin1 (which is not maps to valid UTF8) give such message.

**Comment by vsespb** [comment]
to reproduce: create empty project, then
`echo привет | iconv -t windows-1251 > file.pm` open it (it's Perl, encoding correctly detected).
you can try any non-ascii in non-utf8 encoding. press Ctrl-S to save.

**Comment by mitchell-as** [comment]
That's strange. I am also on 64-bit Linux and I cannot reproduce after following your steps. See my screenshot below. Is this what you're seeing? I am able to Ctrl+S (Save) just fine. I can even type some normal characters and still save. Toggling between Latin1 and UTF8 also allows me to save.

![latin1](https://cloud.githubusercontent.com/assets/12902397/12237782/77a636cc-b84e-11e5-87b5-c4cb8bb776f8.png)

**Comment by Defman21** [comment]
I'm able to reproduce it.
`echo привет мир | iconv -t windows-1251 > file.pm`
`komodo file.pm`
Added some random text at a new line, pressed Ctrl+S.
Here's what I got:
```
/home/defman/Apps/Komodo/latest/lib/python/lib/python2.7/difflib.py:416: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  for j in b2j.get(a[i], nothing):
/home/defman/Apps/Komodo/latest/lib/python/lib/python2.7/difflib.py:437: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  a[besti+bestsize] == b[bestj+bestsize]:
ERROR:xpcom:Unhandled exception calling 'int8 * save(in boolean);'
Traceback (most recent call last):
  File "/home/defman/Apps/Komodo/latest/lib/mozilla/python/xpcom/server/policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "/home/defman/Apps/Komodo/latest/lib/mozilla/components/koDocument.py", line 1664, in save
    self._clean(ensureFinalEOL, cleanLineEnds)
  File "/home/defman/Apps/Komodo/latest/lib/mozilla/python/xpcom/components.py", line 268, in wrapperFn
    return fn(*args, **kwargs)
  File "/home/defman/Apps/Komodo/latest/lib/mozilla/components/koDocument.py", line 1428, in _clean
    wsLinesToStrip = self.getChangedLinesWithTrailingWhitespace()
  File "/home/defman/Apps/Komodo/latest/lib/mozilla/components/koDocument.py", line 1386, in getChangedLinesWithTrailingWhitespace
    diff_content = self.getUnsavedChanges()
  File "/home/defman/Apps/Komodo/latest/lib/mozilla/components/koDocument.py", line 2060, in getUnsavedChanges
    return ''.join(difflines)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xef in position 1: invalid continuation byte
```

**Comment by mitchell-as** [comment]
@vsespb When you get the chance would you please answer my original questions? That may help me diagnose and reproduce the issue. Thanks!

**Comment by vsespb** [comment]
@mitchell-as,

> See my screenshot below. Is this what you're seeing?

Yes, that's what I am seeing. When I told `it's Perl, encoding correctly detected` it was a bit misleading.
Encoding detected as Latin1 (as in your screenshot) and I am unable to save. I switch encoding `to Eastern Europe/Cyrilic (CP1251)` and I see `привет` and that is correct text,
but I still unable to save it (and if I switch to UTF-8 I still unable to save it). (note that Komodo always autodected CP1251 texts as Latin1; it's probably impossible to detect better).

**Comment by vsespb** [comment]
@mitchell-as, also on your screenshot it's Komodo 9.1, but I have 9.3

**Comment by Defman21** [comment]
It's Komodo 9.10 - development version of Komodo built from the source code.

**Comment by mitchell-as** [comment]
Thanks for the feedback. I still cannot reproduce this, but @Defman21's traceback is something to go on.

**Comment by vsespb** [comment]
sad that cant be fixed till next major version

**Comment by mitchell-as** [comment]
Okay, I'll file it earlier, but there's no guarantee, as I cannot reproduce it right now.

**Comment by vsespb** [comment]
thanks!
i've got log from Troubleshooting/log file:

```
/opt/komodo-edit-9/lib/python/lib/python2.7/difflib.py:433: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  a[besti-1] == b[bestj-1]:
/opt/komodo-edit-9/lib/python/lib/python2.7/difflib.py:437: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  a[besti+bestsize] == b[bestj+bestsize]:
ERROR:xpcom:Unhandled exception calling 'int8 * save(in boolean);'
Traceback (most recent call last):
  File "/opt/komodo-edit-9/lib/mozilla/python/xpcom/server/policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "/opt/komodo-edit-9/lib/mozilla/components/koDocument.py", line 1697, in save
    self._clean(ensureFinalEOL, cleanLineEnds)
  File "/opt/komodo-edit-9/lib/mozilla/python/xpcom/components.py", line 268, in wrapperFn
    return fn(*args, **kwargs)
  File "/opt/komodo-edit-9/lib/mozilla/components/koDocument.py", line 1461, in _clean
    wsLinesToStrip = self.getChangedLinesWithTrailingWhitespace()
  File "/opt/komodo-edit-9/lib/mozilla/components/koDocument.py", line 1419, in getChangedLinesWithTrailingWhitespace
    diff_content = self.getUnsavedChanges()
  File "/opt/komodo-edit-9/lib/mozilla/components/koDocument.py", line 2089, in getUnsavedChanges
    return ''.join(difflines)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xcc in position 1: invalid continuation byte
```

**Comment by mitchell-as** [comment]
I finally managed to reproduce it. It turns out you need to have the "clean trailing whitespace" file-saving preference turned on.

**Comment by vsespb** [comment]
Ok, thanks!
Indeed reproducible only with "clean trailing whitespaces".
