### ISSUE TITLE
Icons not scaling properly with high DPI settings

### ISSUE THREAD

**Issue by cyberbit** [Komodo/KomodoEdit#998]
I'm on Windows 10, Komodo Edit 9.3. With 3200x1800 set at 150% scaling, this is what I see:

![image](https://cloud.githubusercontent.com/assets/7350183/12224233/fd1d05d6-b7b0-11e5-835c-16f1564185e9.png)

You can see that some of the icons seem to be scaled a bit too much, almost like they are scaled (by Windows) 150% relative to the Komodo interface rather than the screen.

**Comment by Naatan** [comment]
Does this only happen for icons in the find frame or elsewhere also?

**Comment by cyberbit** [comment]
There's a few other places that I've seen it. The only one that comes to mind at the moment is the preferences window:

![image](https://cloud.githubusercontent.com/assets/7350183/12245518/979c39d4-b86e-11e5-9411-ad2a71c46996.png)

The icons of interest are in the search bar and the API Catalog checkboxes.

I feel like this is closely related to #484, as I have a similar issue with tooltips.

**Comment by Naatan** [comment]
Alright, thanks for clarifying :)

**Comment by cyberbit** [comment]
Thought I should update this now that I have 10. It doesn't appear to be a problem in 10, at least in the examples here.

**Comment by Naatan** [comment]
Thanks for updating us @cyberbit  :)
