### ISSUE TITLE
Check for Updates... apparently not working

### ISSUE THREAD

**Issue by seattledeveloper** [Komodo/KomodoEdit#999]
I am currently running Komodo IDE, version 9.3.1, build 88153, platform win32-x86. Built on Tue Nov 17 09:49:57 2015.  I have been wondering when it would auto-update to 9.3.2 which seems to have been released last month.  When I use the "Check for Updated..." menu item, Komodo reports that there are no updates available.  Please let me know if I need to manually update to get this working again (if it was only broken in 9.3.1).  Thanks!

**Comment by vsespb** [comment]
not sure if it's relevant, but I had Komodo 8 and "Check for updates" never shown me that there is Komodo 9, until December 2015 when I went to site and manually updated it.

**Comment by cgchoffman** [comment]
> not sure if it's relevant

 @vsespb Nope, there is no Auto-update path between major versions.  

@seattledeveloper, @Naatan tried this last week and it worked for him but you're the second person to report this.  We'll take a closer look.

**Comment by seattledeveloper** [comment]
Something just changed.  I returned to the office and logged in and the Komodo update dialog was displaying the availability of 9.3.2 which I now have installed.

Komodo IDE, version 9.3.2, build 88191, platform win32-x86. Built on Thu Dec 10 11:38:17 2015.

**Comment by mitchell-as** [comment]
We've been fiddling with our update server and noticed some issues. It's likely our fiddling fixed your issue :) Thanks for your vigilance.

**Comment by Naatan** [comment]
We managed to resolve the issue yesterday after thorough investigation. In short the issue was caused by our recent datacenter move and once we located the cause was easily resolved. Thanks for reporting this issue to us! :)

**Comment by seattledeveloper** [comment]
You're welcome.  Glad I could help out.
